### ISSUE TITLE
ClosedChannelException with Micronaut4 application

### ISSUE THREAD

**Issue by smaharajan** [micronaut-projects/micronaut-core#10004]
### Expected Behavior

HttpClient should return 200 status code with response message.

### Actual Behaviour

I have built a Rest proxy API using Micronaut-3.x and it is working fine but when I migrate to Micronaut-4 using openRewrite, I am facing the ClosedChannelException error always.  

As per analysis, I could see the same API in Micronaut-4 is working while connecting to other API endpoint running in Cipher AES128-GCM-SHA256 rather the failure endpoint is enabled with the cipher - ECDHE-RSA-AES256-SHA384.  

Need to understand the Netty/Micronaut-4 compatible cipher list whether it supports ECDHE-RSA-AES256-SHA384, if not, how to add this during the Http client request.

_io.micronaut.http.client.exceptions.HttpClientException: Client 'https://api.testing1.com/': Connect Error: null
    at io.micronaut.http.client.netty.ConnectionManager$Pool.onNewConnectionFailure(ConnectionManager.java:984)
Caused by: java.nio.channels.ClosedChannelException
    at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1150)
Caused by: java.nio.channels.ClosedChannelException
Suppressed: io.netty.handler.ssl.StacklessSSLHandshakeException: Connection closed while SSL/TLS handshake was in progress
        at io.netty.handler.ssl.SslHandler.channelInactive(Unknown Source)
`_

### Steps To Reproduce

**dependencies**
 annotationProcessor("io.micronaut:micronaut-http-validation")
    annotationProcessor("io.micronaut:micronaut-inject-java")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-jackson-databind")
    runtimeOnly("ch.qos.logback:logback-classic")
    runtimeOnly("io.micronaut.discovery:micronaut-discovery-client")
    runtimeOnly("org.yaml:snakeyaml")

**code snippet**
public String targetEndpointRequest(String queryParams) {
    try {
        HttpResponse<String> response = httpClient.toBlocking().exchange(HttpRequest.GET("https://api.testing1.com:443/proxyAPI?slno=123)
            .header("Authorization", "Basic xxxx"), String.class);
        } catch (Exception e) {
            e.printStackTrace();
        }
    return response.body();   
}

### Environment Information

JDK17
Micronaut4
Netty-4.1.x

### Version

4.0.2

**Comment by yawkat** [comment]
which cipher mode is ECDHE-RSA-AES256-SHA384 using? If it's CBC or something, that cipher is potentially insecure, and forbidden for HTTP/2.

**Comment by smaharajan** [comment]
It's CBC.  yes, looks like it is insecure one.  Is there a restriction from Netty IO server or Micronaut-4 as it is working fine with Micronaut-3 ?  Can you share some documentations.

**Comment by yawkat** [comment]
Micronaut HTTP client 4 uses HTTP/2 where possible. For HTTP/2, potentially insecure cipher suites are prohibited in compliance with the spec: https://httpwg.org/specs/rfc9113.html#BadCipherSuites

**Comment by smaharajan** [comment]
Thanks much @yawkat , I could see TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 in the prohibited cipher list, hence Micronaut-4 not allowing to process it.  Just out of curiosity, is there a way to allow this cipher from MN4-Http Client as a tactical fix ?

**Comment by yawkat** [comment]
Also from the spec: https://httpwg.org/specs/rfc9113.html#tls12ciphers

> deployments of HTTP/2 that use TLS 1.2 MUST support TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 [[TLS-ECDHE]](https://httpwg.org/specs/rfc9113.html#RFC5289) with the P-256 elliptic curve [[RFC8422]](https://httpwg.org/specs/rfc9113.html#RFC8422).

It seems your server is violating the HTTP/2 spec. If you really cannot fix the server, just turn off HTTP/2: `micronaut.http.client.alpn-modes=http/1.1`

**Comment by ssmule** [comment]
Yes it worked now by adding the http-1:1.. Thanks @yawkat for your support..

**Comment by smaharajan** [comment]
yes it worked after applied the http/1.1 change. Thanks.
