### ISSUE TITLE
Java 21 Slow Boot up time

### ISSUE THREAD

**Issue by sidhant92** [micronaut-projects/micronaut-core#10032]
### Issue description

Anyone else noticed that while using java 21, the boot-up time for the server has increased almost 3x

**Comment by peddaiahjuturu** [comment]
@sidhant92 , you closed this issue, did you find the solution? i need it, i have same issue.

**Comment by peddaiahjuturu** [comment]
> @sidhant92 , you closed this issue, did you find the solution? i need it, i have same issue.

Any updates here from anyone.
