### ISSUE TITLE
Missing GraalVM support for JDK 21

### ISSUE THREAD

**Issue by sergey-morenets** [micronaut-projects/micronaut-core#10046]
### Expected Behavior

We should be able to build native image for JDK 21 Micronaut application as JDK 21 is already supported by GraalVM.

### Actual Behaviour

Hi

We tried to generate GraalVM native image for our JDK 21 application as written in the documentation(https://docs.micronaut.io/latest/guide/#graal):

_gradle dockerBuildNative_

However we see from the log that GraalVM for JDK 17 is used:

`Step 1/31 : FROM ghcr.io/graalvm/native-image-community:17-ol9 AS graalvm`

And that predictably leads to the build error:

```
Error: Unable to load 'demo.Application' due to a Java version mismatch.
Please take one of the following actions:
 1) Recompile the source files for your application using Java 17, then try running native-image again
 2) Use a version of native-image corresponding to the version of Java with which you compiled the source files for your application

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
```

We couldn't find any steps in the documentation how to change GraalVM docker image (version).

### Version

4.1.4

**Comment by Omega359** [comment]
Note that the current impl (https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/master/docker-plugin/src/main/java/io/micronaut/gradle/docker/NativeImageDockerfile.java) points to the graalvm community edition which doesn't seem to have a jdk 21 release for the docker image (https://github.com/graalvm/container/pkgs/container/native-image). As well it seems that the community edition is hardcoded - no way to switch to the oracle repository for graalvm which does seem to have a jdk 21 version.

**Comment by jkl-lkj** [comment]
I recently also ran into this problem and I concur that it would be nice to resolve this. Rather unpleasant to add support for native docker images and then be confronted with a Java version mismatch.

**Comment by melix** [comment]
The plugin defaults to Java 17 and GraalVM CE, but ou can use this (Kotlin DSL, adapt for Groovy) for example to use the Java 21 version:

```gradle
tasks {
    dockerfileNative {
         jdkVersion.set("21")
    }
}
```

Alternatively you can set the whole image name:

```gradle
tasks {
    dockerfileNative {
         graalImage.set("ghcr.io/graalvm/native-image-community:whatever-tag")
    }
}
```

```

**Comment by muraria** [comment]
Is there an equivalent to this with Maven Plugin?

**Comment by alvarosanchez** [comment]
This is supported by the Maven Plugin since 4.4.0

**Comment by timyates** [comment]
Tested with Micronaut 4.3.3, and this now works as expected, using

```
Step 1/17 : FROM ghcr.io/graalvm/native-image-community:21-ol9 AS graalvm
```

👍

**Comment by ArnauAregall** [comment]
> The plugin defaults to Java 17 and GraalVM CE, but ou can use this (Kotlin DSL, adapt for Groovy) for example to use the Java 21 version:
> 
> ```groovy-gradle
> tasks {
>     dockerfileNative {
>          jdkVersion.set("21")
>     }
> }
> ```

I confirm this worked for me as well, thanks!

Sorry to comment on a closed issue, but would be great giving a hint on the guides, such as: 

- https://guides.micronaut.io/latest/micronaut-docker-image-gradle-java.html
- https://guides.micronaut.io/latest/micronaut-docker-image-gradle-kotlin.html

**Comment by timyates** [comment]
Hi @ArnauAregall the latest plugin defaults to the current JDK, so if you are running the build on 21 with the latest plugin, you shouldn't need to set this `jdkVersion` property...

You're right that we're lacking documentation on it though, so I raised https://github.com/micronaut-projects/micronaut-gradle-plugin/pull/958 which hopefully plugs tht gap by documenting it in the plugin documentation 🤞
