### ISSUE TITLE
I'm trying to use this solution in order to log requests body in my application. However every request ends up with an error like so:

### ISSUE THREAD

**Issue by Scutc** [micronaut-projects/micronaut-core#10052]
I'm trying to implement solution for getting http request body in HttpRequestFilter. I've implemented it in recommended way using NettyServerCustomizer. Here is my implementation:

`public class HttpRequestBodyExtractor implements BeanCreatedEventListener<NettyServerCustomizer.Registry>, NettyServerCustomizer {
    private static final String BODY_AGGREGATOR = "body-aggregator";
    private static final String BODY_LOGGER = "body-logger";

    private final Channel channel;
    private final HttpServerConfiguration serverConfiguration;

    public HttpRequestBodyExtractor(@Nullable Channel channel, HttpServerConfiguration serverConfiguration) {
        this.channel = channel;
        this.serverConfiguration = serverConfiguration;
    }

    @Override
    public NettyServerCustomizer.Registry onCreated(BeanCreatedEvent<Registry> event) {
        NettyServerCustomizer.Registry registry = event.getBean();
        registry.register(this);
        return registry;
    }

    @Override
    @NonNull
    public NettyServerCustomizer specializeForChannel(@NonNull Channel channel, @NonNull ChannelRole role) {
        return new HttpRequestBodyExtractor(channel, serverConfiguration);
    }

    @Override
    public void onStreamPipelineBuilt() {
        if (channel != null) {
            ChannelPipeline pipeline = channel.pipeline();
            pipeline.addBefore(HANDLER_HTTP_STREAM, BODY_AGGREGATOR,
                new HttpObjectAggregator((int) serverConfiguration.getMaxRequestSize()));
            pipeline.addAfter(BODY_AGGREGATOR, BODY_LOGGER, new SimpleChannelInboundHandler<FullHttpRequest>() {
                @Override
                protected void channelRead0(ChannelHandlerContext context, FullHttpRequest message) {
                    byte[] bytes = ByteBufUtil.getBytes(message.content());
                    String body = StringUtils.trimToNull(new String(bytes, StandardCharsets.UTF_8));
                    MDC.put("body", body); //I'm trying to keep body for further logging
                    context.fireChannelRead(message);
                }
            });
        }
    }
}
`

In this implementation I always have such an error:
`io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1`

and following :
`io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: cannot send more responses than requests`
	
I found workaround for some cases. If read bytes in this way:

` byte[] bytes = ByteBufUtil.getBytes(message.retain().content());`
 
the mistake generally doesn't appear, but in some services where I use ProxyHttpClient for proxying requests (without having internal logics and service model inside), I still meet the same problem. 

Is any other way to get http request body?

**Comment by graemerocher** [comment]
Set `server-type` to `FULL_CONTENT`. See https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration

```properties
micronaut.server.netty.server-type=FULL_CONTENT
```

**Comment by Scutc** [comment]
> Set `server-type` to `FULL_CONTENT`. See https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration
> 
> ```ini
> micronaut.server.netty.server-type=FULL_CONTENT
> ```
We're using Micronaut 3.7.3 and there is no such configuration property. It's impossible to upgrade version at the moment

**Comment by yawkat** [comment]
We will not make further changes to the http stack in 3.x. As of micronaut http server 4.x you can access the request body inside a regular filter using `@Body`.
