### ISSUE TITLE
Invalid bytecode generated when using Boolean as constructor in DTOs 

### ISSUE THREAD

**Issue by nbrugger-tgm** [micronaut-projects/micronaut-core#10062]
### Expected Behavior

The code compiles, runs and tests without issue

### Actual Behaviour

The JVM crashes due to invalid bytecode. This is extremely simmilar to #9528 but with some differences in the crashlog and meaning of the message it also has a workaround - changing the `Boolean` in the DTO to a `boolean`.

### Steps To Reproduce

1. Clone https://github.com/nbrugger-tgm/micronaut-bytecode-reproducer
2. run `./gradlew test`

### Environment Information

- JDK(s): 17, 20, 21

### Example Application

https://github.com/nbrugger-tgm/micronaut-bytecode-reproducer

### Version

4.0.0 -> 4.1.x

**Comment by marcinfigiel** [comment]
I just got hit by this issue during migration from 3.9.5 to 4.3.2. A DTO class with a Boolean attribute causes the following error during test class initialization:
```
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.http.server.RouteExecutor]

Message: Error loading BeanIntrospection for type [class com.cobrick.aiops.topology.dto.SimpleService]: Bad type on operand stack
Exception Details:
  Location:
    com/cobrick/aiops/topology/dto/$SimpleService$Introspection.dispatchOne(ILjava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; @358: invokespecial
  Reason:
    Type top (current frame, stack[6]) is not assignable to 'java/lang/Boolean'
```

**Comment by nbrugger-tgm** [comment]
I would like to raise awareness for this.
This issue is not detectable or foreseeable at compile time and hard to debug and work around.
This class of issues (wrong bytecode generation) should be prioritized to be honest, since it drives "trust" in micronaut. Sice you do not generate Java code but bytecode and with that circumvent the compiler, I think this should be dealt with. A "DTOs cannot contain fields of type Boolean" would be better - even tho I would not understand why this limitation exists

**Comment by graemerocher** [comment]
@dstepanov could you take a look?
