### ISSUE TITLE
Beans in testFixtures is not possible to inject

### ISSUE THREAD

**Issue by dniel** [micronaut-projects/micronaut-core#10078]
### Expected Behavior

I'm trying to inject a Bean defined as a Singleton in a testFixture from another sub-module in gradle, but it seems that Micronaut injection doesnt pick up the bean when I use the test fixture bean in another project.

I have one module using the micronaut plugin to build a lambda and another one using micronaut-library plugin to build testFixture the lambda project depends on the fixtures from the other module but the beans from that project fail with bean not exist when injected into the lambda tests.

I can see that there isn't a io.micronaut.inject.BeanDefinitionReference in the fixture Jar generated, but if I create my own Jar with
```
tasks.register<Jar>("testJar") {
    archiveFileName.set("lambda-shared-test.jar")
    from(project.the<SourceSetContainer>()["test"].output)
}
```
such file is generated and added to the jar under META-INF but does not contain a reference to the beans from the fixture sourceset.

hm. but the `io.micronaut.inject.BeanDefinitionReference` does not contain the beans that I moved to the `testFixture`.

### Actual Behaviour

`@Inject` should inject a bean from  testFixture `sourceSet`

### Environment Information

- JDK 19

### Version

Micronaut 3.9.x

**Comment by melix** [comment]
I would say this isn't a bug but the expected behavior since we cannot assume that any source folder contains Micronaut related sources. You will need to explicitly add the `micronaut-inject` processor to the test fixtures annotation processing:

```
testFixturesAnnotationProcessor "io.micronaut:micronaut-inject-java"
```

**Comment by dniel** [comment]
Adding to `dependencies`
```
testFixturesAnnotationProcessor("io.micronaut:micronaut-inject-java")
testFixturesImplementation("com.fasterxml.jackson.module:jackson-module-kotlin")
```

Didn't change anything, should no more info under META-INF generated? How can I verify that testFixturesAnnotationProcessor did work as expected?

**Comment by dniel** [comment]
My testcase was just a simple 
- `src/test`
- `src/testFixtures`

where src/testFixtures contains a bean that should be injected into a unit test under src/test

**Comment by dniel** [comment]
Using 
```
plugins {
    kotlin("jvm")
    kotlin("kapt")

    id("java-library")
    id("java-test-fixtures")
    id("io.micronaut.application")
}
```

**Comment by melix** [comment]
Actually the easiest is to add the test fixtures source set to the processing configuration of the `micronaut` block, e.g:

```gradle
micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        ...
        additionalSourceSets.add(sourceSets.testFixtures)
    }
...
```

I have tested this locally and it works as expected.

**Comment by dniel** [comment]
But would that work if the testFixtures is located in a different sub-module?

**Comment by melix** [comment]
It should, yes. The plugins you apply depend on the kind of modules. So if you have a separate module which is not an application but exposes test fixtures, you should probably apply the `io.micronaut.library` plugin, which would add the `micronaut` extension.

**Comment by dniel** [comment]
I tested with a clean project using `additionalSourceSets.add(sourceSets.testFixtures)` and that did work as expected.
Will create a new clean multi-module to verify if that works as well.

**Comment by dniel** [comment]
Tested again with a multi-module project https://github.com/dniel/micronaut-test-fixtures/ and it seems to work as expected even without `additionalSourceSets.add(sourceSets.testFixtures)`, just using `testImplementation(testFixtures(project(":module2")))`
