### ISSUE TITLE
Can't resolve type argument in field types

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#10083]
Sample classes for test:
```java
@Controller
class CommonController {

    @Get("/get1")
    public ListElement<String> list() {
        return null;
    }
}

class ListElement<T> {
    public Iterable<T> iterableValues;
}
```

Check type component - it is ok:

![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/77f29f4b-f01b-4489-9140-546b2c21c13b)

next get field property component and check field type component:

![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/e7506c54-f5d8-4c6d-b7ff-6cf8ba323eaf)

As you see, field type component can't resolve type argument. `T` must be java.lang.String

### Version

4.1.11

**Comment by altro3** [comment]
Relates to this: https://github.com/micronaut-projects/micronaut-openapi/issues/1288

**Comment by altro3** [comment]
The problem only when you use public fields. With records and getters / setters all works fine

**Comment by dstepanov** [comment]
Are you using getGeneric versions of result/field type?

**Comment by altro3** [comment]
Yes indeed. This solved the problem
