### ISSUE TITLE
ContextualConnection$Intercepted doesn't implement all methods

### ISSUE THREAD

**Issue by marcinfigiel** [micronaut-projects/micronaut-core#10080]
### Expected Behavior

When trying to insert a row into the PostgreSQL DB via JDBI SqlObject method annotated with `@GetGeneratedKeys` the generated ID should be returned, as it was on Micronaut 3.x.

### Actual Behaviour

The following error is thrown:
`
Unexpected error occurred: Receiver class io.micronaut.data.connection.jdbc.advice.ContextualConnection$Intercepted does not define or inherit an implementation of the resolved method 'abstract java.sql.PreparedStatement prepareStatement(java.lang.String, int)' of interface java.sql.Connection.
`
from `org.jdbi.v3.core.statement.DefaultStatementBuilder.create(DefaultStatementBuilder.java:53)`

### Environment Information

- Operating system: pop!_OS 22.04 LTS (kernel 6.2.6)
- JDK version: OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)

### Example Application

https://github.com/marcinfigiel/demo-jdbc-error

### Version

4.0.2

**Comment by dstepanov** [comment]
Can you extend your test to use test containers / test resources? Thanks

**Comment by oddaolse** [comment]
I can just add that I face the same issue.

**Comment by frodeo** [comment]
@graemerocher @dstepanov Any idea when a fix for this will be available? This is preventing us from upgrading to Micronaut 4 now.

**Comment by marcinfigiel** [comment]
@frodeo There is a workaround for this issue - it works fine if you explicitly specify the PK columns in the `value` of the `@GetGeneratedKeys` annotation, e.g. `@GetGeneratedKeys("id")`

@dstepanov I'm sorry, I haven't had time lately. I will try to do it, but cannot give you any ETA at the moment :( 
@oddaolse if you can spare some time I will gladly accept a PR :)

**Comment by frodeo** [comment]
We are using JDBC and java.sql.Statement.getGeneratedKeys(), and we are still getting the same error. There we are not able to specify the PK (there is no getGeneratedKeys("id")), but we have specified the PK in the schema. Is there any workaround for plain JDBC?

**Comment by radovanradic** [comment]
> Can you extend your test to use test containers / test resources? Thanks

Here is an example with test resources reproducing the error
[mn-demo-jdbi-error.zip](https://github.com/micronaut-projects/micronaut-core/files/13472471/mn-demo-jdbi-error.zip)
