### ISSUE TITLE
Document it is possible to use Java Records for immutable configuration with @ConfigurationProperties

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#10086]
### Issue description

We have an example in a the [Micronaut Data with Java Records](https://guides.micronaut.io/latest/micronaut-java-records-gradle-java.html#immutable-configuration-with-java-records) guide. 

However, in the Micronaut Core reference documentation we don't have any example of immutable configuration using Java records. 

> [From a performance perspective records are better than interfaces](https://github.com/micronaut-projects/micronaut-views/pull/613#discussion_r1386450561)

**Comment by graemerocher** [comment]
should be noted that records have a downside of not being refreshable, so depends if you need refresh functionality
