### ISSUE TITLE
TestEmbeddedServer is not starting if created with custom port number

### ISSUE THREAD

**Issue by nedelva** [micronaut-projects/micronaut-core#10109]
### Expected Behavior

Take these examples from the user's guide:

```java
import io.micronaut.http.MediaType;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;

@Controller("/hello") // (1)
public class HelloController {

    @Get(produces = MediaType.TEXT_PLAIN) // (2)
    public String index() {
        return "Hello World"; // (3)
    }
}
```

and its Junit test:

```java
import io.micronaut.http.HttpRequest;
import io.micronaut.http.client.HttpClient;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.runtime.server.EmbeddedServer;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@MicronautTest
//NOT working!
//@Property(name="micronaut.test.server.url", value = "http://localhost:5050")
class HelloControllerTest {

    @Inject
    EmbeddedServer server; // (1)

    @Inject
    @Client("/")
    HttpClient client; // (2)


    @BeforeEach
    void setUp() {
        assertTrue(server.isRunning());
    }

    @Test
    void testHelloWorldResponse() {
        String response = client.toBlocking() // (3)
                .retrieve(HttpRequest.GET("/hello"));
        assertEquals("Hello World", response); // (4)
    }
}
```

This test works as expected but if you uncomment the @Property annotation it will fail the assertion in the setUp().

### Actual Behaviour

It should be possible to specify a dedicated port for the embedded server (currently it seems to work only for random ports).

### Steps To Reproduce

See the example given. Un-comment the @Property annotation for the unit test class.

### Environment Information

Tested with JDK 17.

### Version

4.1.6

**Comment by yawkat** [comment]
not sure what youre trying to do here, the micronaut.test.server.url property belongs to micronaut-test and is not intended for testing controllers. It's for testing an external http server that has to be running already.

**Comment by nedelva** [comment]
According to https://micronaut-projects.github.io/micronaut-test/latest/guide/#writingAMicronautTestWithJUnit5, section 4.10, it should be possible to specify an url for a programmatically created server using this property.

So my take on this is that the creation of a TestEmbeddedServer should observe and honor the value of this property (so what I want to achieve is a way to specify a port number for the server used in a MicronautTest)

**Comment by yawkat** [comment]
You're not programmatically starting an EmbeddedServer in your test though. When youre using the `micronaut.test.server.url` property, there needs to be a server already running on the port. micronaut-test will not start its own.

**Comment by nedelva** [comment]
> You're not programmatically starting an EmbeddedServer in your test though. When youre using the `micronaut.test.server.url` property, there needs to be a server already running on the port. micronaut-test will not start its own.

@yawkat you are perfectly right, I don't.  Here's the equivalent test with explicit instantiation of an embedded server:

```java
@MicronautTest
class HelloControllerWithManualEmbeddedServerTest {

    static EmbeddedServer embeddedServer; // (1)

    @Inject
    @Client("/")
    HttpClient client; // (2)

    @BeforeAll
    public static void setupServer() {
        embeddedServer = ApplicationContext.run(EmbeddedServer.class);
        //Map<String, Object> properties = Map.of("micronaut.test.server.url", "http://localhost:8081");
        //embeddedServer = ApplicationContext.run(EmbeddedServer.class,properties);
    }

    @AfterAll
    public static void stopServer() {
        if (embeddedServer != null) {
            embeddedServer.stop();
        }
    }

    @BeforeEach
    void setUp() {
        assertTrue(embeddedServer.isRunning());
    }

    @Test
    void testHelloWorldResponse() {
        String response = client.toBlocking() // (3)
                .retrieve(HttpRequest.GET("/hello"));
        assertEquals("Hello World", response); // (4)
    }
}
```

Once again, if you try to specify the **"micronaut.test.server.url"** (see the commented lines in _setupServer()_) the server won't start and the assertion inside _setUp()_ will fail. Surely, I misread the documentation.
But then, my question is how could one be able to specify the port number for the embedded server created in a test like this one?

**Comment by yawkat** [comment]
are you looking for micronaut.server.port?

**Comment by nedelva** [comment]
> are you looking for micronaut.server.port?

Silly me, that was exactly what I was looking for. Thanks for pointing it out @yawkat.
I was sidetracked by what I read about **micronaut.test.server.url** in the section 4.10 of the _micronaut-test_ user's guide. Maybe that section could be improved with some example use cases..
