### ISSUE TITLE
GORM autoTimestamp not working

### ISSUE THREAD

**Issue by eddgrant** [micronaut-projects/micronaut-core#1014]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Create a gorm Entity which uses auto timestamps e.g.

    @Entity
    @Canonical
    class MyEntity {
        static mapping = {
            autoTimestamp true
        }
    
        String name
        Date dateCreated
        Date lastUpdated
    }

    Write code which persists the entity:

    new MyEntity(name: "foo").save(flush: true)

### Expected Behaviour

GORM should automatically manage the `createdDate` and `lastUpdated` properties.

Tell us what should happen

### Actual Behaviour

GORM doesn't the `createdDate` and `lastUpdated` properties. If validation is configured validation fails the insert as the properties are still null at the point of insert.

### Environment Information

- **Operating System**: Ubuntu 16.04
- **Micronaut Version:** 1.0.1
- **JDK Version:** 1.8.0_144

### Example Application

This can be demonstrated in the following repro project:

    git clone git@github.com:eddgrant/micronaut-gorm-auto-timestamp-issue.git
    cd micronaut-gorm-auto-timestamp-issue
    ./gradlew clean build

    # Open test report
    # Look at `MicroserviceStateDetailsSpec` results

**Comment by graemerocher** [comment]
This appears to be a bug in GORM, however it is related to the configuration of multiple data sources. You can workaround the issue by not using the multiple data source configuration style. 

```diff
diff --git a/src/test/resources/application-test.yml b/src/test/resources/application-test.yml
index 8f202d1..bbc76ff 100644
--- a/src/test/resources/application-test.yml
+++ b/src/test/resources/application-test.yml
@@ -12,11 +12,11 @@ hibernate:
         use_second_level_cache: true
         use_query_cache: false
         region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
-dataSources:
-    default:
-        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
-        pooled: true
-        jmxExport: true
-        driverClassName: org.h2.Driver
-        username: sa
-        password: ''
+dataSource:
+    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
+    pooled: true
+    jmxExport: true
+    driverClassName: org.h2.Driver
+    username: sa
+    password: ''
```

**Comment by benlucchesi** [comment]
I'm using a single datasource as follows:

dataSource:
   url: jdbc:mysql://127.0.0.1:3306/dontdrive
   pooled: true
   jmxExport: true
   driverClassName: com.mysql.jdbc.Driver
   username: XXXXXX
   password: XXXXXX

beforeInsert event, beforeUpdate event, and autoTimestamp are not working.

micronaut version 1.1.0.RC2
groovy project
mac osx 10.13.6

example entity:

import grails.gorm.annotation.Entity
@Entity
class Customer {
  Date dateCreated
  Date lastUpdated
  ....
  static mapping = {
     autoTimestamp true
  }
}

**Comment by jisikoff** [comment]
This is not working for me either
