### ISSUE TITLE
Sanitize URL output for HTTP error 400

### ISSUE THREAD

**Issue by rlconst** [micronaut-projects/micronaut-core#10147]
### Actual Behavior

I'm playing around with `io.micronaut.docs.server.urisyntax.MalformedUriSpec` test.

When you send a malformed URL like `$embeddedServer.URL?"><tag>=` 
Micronaut replicates malformed URL in message

```
{"message":"Bad Request","_embedded":{"errors":[{"message":"Malformed URI: Illegal character in query at index 2: /?\"><tag>="}]},"_links":{"self":{"href":"/","templated":false}}}
```

And pentest tool from security vendor freaks out when it sees angle brackets in output, despite JSON being **properly** escaped.

This is just for reference in case someone will search:
[CWE-79 Improper Neutralization of Input During Web Page Generation](http://cwe.mitre.org/data/definitions/79.html)
[A3 Injection](https://owasp.org/Top10/A03_2021-Injection/)
[WASC-22 IMPROPER OUTPUT HANDLING](http://projects.webappsec.org/w/page/13246934/WASC)

Can we have an option to silence out original input to something harmless like:
```
{"message":"Bad Request","_embedded":{"errors":[{"message":"Malformed URI: Illegal character in query"}]},"_links":{"self":{"href":"/","templated":false}}}
```
or even
```
{"message":"Bad Request","_embedded":{"errors":[{"message":"Malformed URI"}]},"_links":{"self":{"href":"/","templated":false}}}
```
or we can urlencode user input

### Version

3.10.x

**Comment by rlconst** [comment]
After investigation as an immediate workaround I can try to substitute `io.micronaut.http.server.exceptions.URISyntaxHandler`. The error itself reported from the guts of JDK `java.net.URI.Parser#fail(java.lang.String, int)`

**Comment by yawkat** [comment]
yea we should try to avoid user-controlled output in error messages.

**Comment by be-a-bee** [comment]
@yawkat  , what is the recommendation here ? 

Option 1 : 
Offer a configuration to define whether the exception message should be suppressed or not.
Outcome message is to be suppressed (default) : "message":"Malformed URI"
Outcome message is NOT to be suppressed : "message":"Malformed URI: Illegal character in query at index 2: /?\"><tag>="

Option 2: 
Always suppress the exception message. If someone comes with a requirement that they want the exception to be printed, then implement Option 1. 
Outcome  : "message":"Malformed URI"

Option 3: 
Always encode/escape the content in the exception message before printing to logs. for example < would be encoded as &lt; . 
Outcome : "message":"Malformed URI: Illegal character in query at index 2: /?\"&gt;&lt;tag&gt;="

Option 4:
Offer a configuration to define whether the exception message should be suppressed, encoded or displayed as it is.
Outcome message is to be suppressed : "message":"Malformed URI"
Outcome message is to be encoded (default) : "message":"Malformed URI: Illegal character in query at index 2: /?\"&gt;&lt;tag&gt;="
Outcome message is NOT to be suppressed : "message":"Malformed URI: Illegal character in query at index 2: /?\"><tag>="

Personally I prefer Option 4 but Option 2 or Option 1 are also acceptable. What do the maintainers prefer ?

**Comment by yawkat** [comment]
@be-a-bee the path should not be included at all, so option 2. i dont think a config option is necessary. it's also fine if the index is included in the message, but we should avoid the user-supplied input altogether.

**Comment by be-a-bee** [comment]
Thanks @yawkat  for the prompt response. If I may, I will contribute a PR for Option 2.

**Comment by yawkat** [comment]
go ahead :)

**Comment by sdelamo** [comment]
closed via https://github.com/micronaut-projects/micronaut-core/pull/10324
