### ISSUE TITLE
how to inject httpclient supporting https

### ISSUE THREAD

**Issue by stanleyw2014** [micronaut-projects/micronaut-core#10141]
### Issue description

Hi,
I added below properties to suppor https for my micronaut server
micronaut.server.ssl.enabled=true
micronaut.server.ssl.buildSelfSigned=true
after adding them, my unit test failed due to Connect Error: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
my httpclient in unit test is defined like this:
  
  @Inject
  @Client("/")
  HttpClient client;

How can I make this httpclient support https or ignore certificate?

**Comment by yawkat** [comment]
The reason for the error is that you're using a self-signed certificate. The self-signed certificate cannot be verified to be trustworthy so the client will refuse to connect by default.

You can change this behavior using the `micronaut.http.client.ssl.insecure-trust-all-certificates` config property, but this is a security risk. Only do this for testing.
