### ISSUE TITLE
Micronaut KSP does not support anonymous classes

### ISSUE THREAD

**Issue by oehme** [micronaut-projects/micronaut-core#10165]
[This non-null assert](https://github.com/micronaut-projects/micronaut-core/blob/2e85f63476005c539d41c4e37ae345243db0ef7b/inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/visitor/AbstractKotlinElement.kt#L527C17-L527C17) fails if you have any anonymous types on private signatures. E.g.

```
class Foo {
   private val bar = object {}
}
```

Workaround: Declare an explicit type for the field.

**Comment by dstepanov** [comment]
Please create a reproducer

**Comment by oehme** [comment]
Run `gradlew test` in this [example project](https://github.com/micronaut-projects/micronaut-core/files/13503082/anonymous-type-bug.zip)

**Comment by altro3** [comment]
@dstepanov Yeah, this bug reproducable:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/a457205d-96ca-453c-a610-b16954b435e4)
