### ISSUE TITLE
Cache name is translated from camel-case to dash-case 

### ISSUE THREAD

**Issue by michalpetrov** [micronaut-projects/micronaut-core#1016]
After naming a cache in application.yml in camel-case (e.g. "myCache"), you have to use a dash-case name in annotation (e.g. `@Cacheable("my-cache")`). 

### Steps to Reproduce
```java
public class Application {
    public static void main(String[] args) {
        ApplicationContext ctx = Micronaut.run(Application.class);
        Cache cache = ctx.getBean(Cache.class);
        System.out.println(cache.getData());
    }
}

@Singleton
class Cache {
    @Cacheable("myCache")
    String getData() {
        return "data";
    }
}
```

```yml
-- application.yml
micronaut:
    application:
        name: test-cache
    caches:
        myCache:
            maximum-size: 10
```

This throws exception `io.micronaut.context.exceptions.ConfigurationException: No cache configured for name: myCache`. After changing the annotation to `@Cacheable("my-cache")` everytihng works as expected.

### Expected Behaviour
Cache name should be the same in yml and annotation. Or at least (if this a limitation of Caffeine library) there should be a warning about the naming in the documentation (the documentation uses camel-case names too).

### Actual Behaviour
Application throws exception because cache with provided name is not found.

### Environment Information

- **Operating System**: macOs Mojave 10.14
- **Micronaut Version:** 1.0.1
- **JDK Version:** OpenJDK Runtime Environment 18.9 (build 11.0.1+13)

**Comment by graemerocher** [comment]
This is due to how configuration is normalised in Micronaut. This is a documentation issue and it should indeed be clarified in the documentation on how cache names are resolved. Thanks for the feedback
