### ISSUE TITLE
Wildcard path /** returns 404

### ISSUE THREAD

**Issue by katoquro** [micronaut-projects/micronaut-core#10192]
### Expected Behavior

```
@Controller("/demo")
public class DemoController {
    @Post("/**")
    Publisher<HttpResponse<?>> proxy1(HttpRequest<?> request) {
        return Publishers.just(HttpResponse.ok());
    }
}
```

Controller avow should match `/demo/any` and `/demo`

### Actual Behaviour

```
HTTP/1.1 404 Not Found
Content-Type: application/json
content-length: 132

{"_links":{"self":[{"href":"/demo/any","templated":false}]},"_embedded":{"errors":[{"message":"Page Not Found"}]},"message":"Not Found"}
```

### Steps To Reproduce

1. create basic app with Java, Gradle and Micronaut 4.2.0
2. use controller above
3. run service ./gradlew run
4. make a call `curl -X POST  http://localhost:8080/demo/any`

### Environment Information

- OpenJDK Runtime Environment Corretto-17.0.9.8.1 (build 17.0.9+8-LTS)
- Micronaut 4.2.0  

### Version

4.2.0

**Comment by yawkat** [comment]
i dont think we support this syntax. is it documented anywhere?

**Comment by sdelamo** [comment]
@katoquro you should create a filter instead

**Comment by katoquro** [comment]
@yawkat I thought it's the same rule as for filter https://docs.micronaut.io/latest/guide/#filterPatterns 🤔

@sdelamo Sorry, I didn't got how to use the Filters to build API gateway/proxy functionality. I need some request processing like changing path or doing some auth and then send modified request to another service (I use HttpClient).

**Comment by sdelamo** [comment]
you can do all that in a filter. I think for building API gateway, using filters is the best option.

**Comment by sdelamo** [comment]
@katoquro Moreover, can you provide details about what gateway functionality would need in https://github.com/micronaut-projects/micronaut-core/issues/10164 ?

**Comment by katoquro** [comment]
>you can do all that in a filter. I think for building API gateway, using filters is the best option. 

@sdelamo, I still don't see how it can be done only with filters. Filters should end with Controller method or something like that. 
OK, filter can do auth logic but what will do the logic of building and sending requests to another server? Should be something like a filter with termination (preventing calling the next filters and returning result)? In that case, I can write such 1-way filter but it doesn't look the right way.

**Comment by sdelamo** [comment]
I created a sample project https://github.com/micronaut-projects/micronaut-guides/pull/1390

**Comment by sdelamo** [comment]
Closing this for now @katoquro I don't think we are planning to support `/**` for a controller method anytime soon.
