### ISSUE TITLE
RequestLifecycle refactor breaks servlet, which breaks starter 4.3.x development.

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-core#10204]
### Issue description

The Starter 4.3.x branch is broken with respect to `FunctionSpec` tests in `starter-aws-lambda`, `starter-gcp-function` and `starter-azure-function`. 

It's a problem in that Starter 4.3.x points to `micronaut-http-server-4.3.0-SNAPSHOT` where @dstepanov refactored the ctor on #10167, removing a ctor argument, from `RequestLifecycle(RouteExecutor routeExecutor, HttpRequest<?> request)` to `RequestLifecycle(RouteExecutor routeExecutor)`. 

This is incompatible with the version of micronaut-servlet pointed to by starter 4.3.x. Normally this violates semantic versioning, but it is an `@Internal class` Nevertheless it breaks the Starter 4.3.x branch because that uses core 4.3.x and servlet is trying to call the removed ctor.

I think we either need to restore the 2-arg method and deprecate it; otherwise, we're blocked on passing CI for Starter 4.3.x for the servlet/core mismatch.

**Comment by dstepanov** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-core/commit/f875db7786fa2fd2a3d3913f4b29cdf42a051977
