### ISSUE TITLE
ContextualConnection$Intercepted does not define or inherit an implementation of the resolved method

### ISSUE THREAD

**Issue by frodeo** [micronaut-projects/micronaut-core#10216]
### Expected Behavior

Calling

```ContextualConnection$Intercepted does not define or inherit an implementation of the resolved method```

should not result in an error. This works fine for Micronaut  3.10.1, but not for Micronaut 4 (have tested with 4.2.1).

### Actual Behaviour

The following exception is thrown:

```java.lang.AbstractMethodError: Receiver class io.micronaut.data.connection.jdbc.advice.ContextualConnection$Intercepted does not define or inherit an implementation of the resolved method 'abstract java.sql.PreparedStatement prepareStatement(java.lang.String, int)' of interface java.sql.Connection```

### Steps To Reproduce

Run test DemoTest. This will reproduce the error for the Micronaut 4.2.1 version, and the test will succeed in the Micronaut 3.10.1 version.

### Environment Information

Linux/MacOS
Java 17.0.9

### Example Application

The following demo using Micronaut 4.2.1 will fail:

### Version

4.2.1

**Comment by radovanradic** [comment]
Duplicate https://github.com/micronaut-projects/micronaut-core/issues/10217
