### ISSUE TITLE
ContextualConnection$Intercepted does not define or inherit an implementation of the resolved method

### ISSUE THREAD

**Issue by frodeo** [micronaut-projects/micronaut-core#10217]
### Expected Behavior

Calling

```ContextualConnection$Intercepted does not define or inherit an implementation of the resolved method```

should not result in an error. This works fine for Micronaut  3.10.1, but not for Micronaut 4 (have tested with 4.2.1).

Related issue:
```https://github.com/micronaut-projects/micronaut-core/issues/10080```

### Actual Behaviour

The following exception is thrown:

```java.lang.AbstractMethodError: Receiver class io.micronaut.data.connection.jdbc.advice.ContextualConnection$Intercepted does not define or inherit an implementation of the resolved method 'abstract java.sql.PreparedStatement prepareStatement(java.lang.String, int)' of interface java.sql.Connection```

### Steps To Reproduce

Run test DemoTest. This will reproduce the error for the Micronaut 4.2.1 version, and the test will succeed in the Micronaut 3.10.1 version.

The following demo using Micronaut 4.2.1 will fail: 
```https://github.com/frodeo/micronaut-demo-contextualconnection-error```

The following demo using Micronaut 3.10.1 will succeed:
```https://github.com/frodeo/micronaut-demo-contextualconnection-success```

### Environment Information

Linux/MacOS
Java 17.0.9

### Example Application

https://github.com/frodeo/micronaut-demo-contextualconnection-error

### Version

4.2.1

**Comment by graemerocher** [comment]
this was fixed by https://github.com/micronaut-projects/micronaut-core/pull/10163/commits/e279f3ead2a1bbefcb2717f45aaa6a77d66cac8a I believe

**Comment by frodeo** [comment]
https://github.com/micronaut-projects/micronaut-core/commit/e279f3ead2a1bbefcb2717f45aaa6a77d66cac8a is not part of Micronaut 4.2.1 then? Because this is not fixed in 4.2.1.

**Comment by radovanradic** [comment]
Will need micronaut-data that will be released with core 4.2.1.

**Comment by frodeo** [comment]
I cannot quite see how https://github.com/micronaut-projects/micronaut-core/commit/e279f3ead2a1bbefcb2717f45aaa6a77d66cac8a fixes this issue. I am not even using io.micronaut:micronaut-core-processor in the demo that fails, and even if I include the dependency it fails (I then get the 4.2.1 version with the commit that is referred to).

**Comment by dstepanov** [comment]
The connection proxy is generated using the processor, after the fix, Micronaut Data needs to be recompiled to have the proxy regenerated with a missing method.

**Comment by codepitbull** [comment]
Looking forward to the fix.
Currently running into the same exception when using Jdbi.
It can be triggered on every JDBI operation using the @GetGeneratedKeys annotation (org.jdbi.v3.sqlobject.statement.GetGeneratedKeys).

Just leaving this message here for other JDBI-users who run into the issue ;)

Looking forward to Micronaut 4.2.2 (I guess the fix is gonna be in there?).

**Comment by frodeo** [comment]
Any idea when this issue will be solved? It is still failing with Micronaut 4.2.2.

**Comment by radovanradic** [comment]
It's fixed in micronaut-data 4.4.1 (not sure why it wasn't included in Micronaut 4.2.2). You can try it in the the example app you provided by changing micronaut-data-jdbc dependency to 4.4.1 version.

**Comment by frodeo** [comment]
It works fine with micronaut.data 4.4.1. Is it safe to use micronaut.data 4.4.1 with micornaut-starter 4.2.2, or will that lead to other problems?

**Comment by graemerocher** [comment]
it is safe, it is only because we follow semantic versioning that it was not upgraded

**Comment by timyates** [comment]
Checked this with Micronaut 4.3.3 and it works without requiring manual intervention 👍
