### ISSUE TITLE
KSP incorrectly interprets fields in the interface

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#10228]
### Expected Behavior

Try to analyze `io.micronaut.data.model.Pageable`. Here differences between KSP and java:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/d5a3b95d-615f-49de-805f-b295fc971c8c)

As you see we have two bugs:

1. Constants `UNPAGED` and `UNSORTED` were interpreted as properties
2. Problem with processing class `Sort.Order`: KSP lost property `direction`,  but interpreted wrong property `ascending`

### Version

4.2.1

**Comment by altro3** [comment]
@dstepanov one more :-)

**Comment by altro3** [comment]
@dstepanov The problem with method `KotlinClassElement.getBeanProperties()`: KSP identificate static final fields as bean property:

![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/084077f8-42eb-4e50-964c-a41df50c9348)

**Comment by altro3** [comment]
About second problem with class `io.micronaut.data.model.Sort$Order`. 

Hm.... KSP identificate method `isAscending` as bean property, but it's a bug., because method `getBeanProperties` must return properties with getters and setters:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/3e271db6-6c69-470d-8e3c-549eb74f4bcd)
Java and groovy ignore method `isAscending`

This screenshot for process with KSP:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/ba951a5e-ac41-4a10-9341-7cbfe99419fb)

**Comment by altro3** [comment]
It's unlikely, but perhaps the bug is not in the KSP, but in the Java visitor. You need to decide how to interpret the `isAscending` method - as a property of the bean or not. In the first case, KSP works correctly, but Java does not work correctly. In the second case - vice versa

**Comment by altro3** [comment]
@dstepanov Found third critical bug: KSP can't identificate internal enums (that's why field `direction` was lost):
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/9071fc7a-fdde-4d3b-81d5-75d8f9b8ef14)
Class `io.micronaut.data.model.Sort$Order$Direction` identificated as simple `ClassElement`, but must be `EnumElement`

**Comment by altro3** [comment]
@dstepanov About method `isAscending` - yeah, sorry, this is my fault. I agree, java visitor has thi property too. Forget about this bug.

About enum `io.micronaut.data.model.Sort$Order$Direction`: There is still a problem, I identified the place where classElement is returned, instead of enumElement.

Problem inside method `KotlinSimplePropertyElement.getGenericType()`. Look to srenshot (KSP):
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/ae579946-83d7-4339-aa0c-03884238d1a0)
As you see, method `publicField.getType()` return right `KotlinEnumElement`, but method `publicField.getGenericType()` return `KotlinClassElement`.

Same code with java:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/24a125fc-0c7c-448e-9c50-62bf869db2f0)
As you see, both method return same `JavaEnumElement`

**Comment by altro3** [comment]
@dstepanov Forgot to tell you about another one bug: As you see on screenshot

![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/d5a3b95d-615f-49de-805f-b295fc971c8c)

required properties list is different between java and kotlin. For example, property `number`. That's because of wrong return value for method `element.isNonNull()`

KSP `element.isNonNull()` returns `true`:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/27d02a51-aa33-48d9-8997-9d8d12e14776)

Java `element.isNonNull()` returns `false`:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/1dd3128a-2888-4957-97d7-767b91f74527)

Need to fix primitive types processing for KSP

**Comment by dstepanov** [comment]
I think KSP is correct, the primitive type cannot be null

**Comment by altro3** [comment]
Great! it means we found a bug in the java handler

**Comment by altro3** [comment]
Are you planning to fix this error?

**Comment by dstepanov** [comment]
I will check it later

**Comment by altro3** [comment]
@dstepanov @graemerocher I thought again, and now I'm not entirely sure that primitives should be NotNull automatically. The point is that NotNull is usually perceived as a required argument/field, but for primitives, the absence of this field in JSON is perceived as assigning a default value, not null.

On the other hand, a primitive cannot be null...

In general, I think we need to decide how to correctly define the isNotNull flag for primitives, but now KSP returns true, and Java returns false

**Comment by altro3** [comment]
I think, need to fix this last problem before 4.2.2 will be released

**Comment by altro3** [comment]
With mcronaut 4.2.2 now we have a single difference between KSP and java:

![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/1a49b00d-0f9d-43cc-91c4-f794545b0ee2)

Let's decide whether we should treat primitives as NotNull or not. But this is an obvious bug, because the behavior of the handler for Java and Kotlin is different

**Comment by dstepanov** [comment]
I will try to see if it's possible to change for Java primitives, but anyway, that would be a 4.3 change.

**Comment by altro3** [comment]
@dstepanov I also want to remind you about this problem

**Comment by dstepanov** [comment]
Going to close it. I think everything is fixed now.

**Comment by altro3** [comment]
@dstepanov No! Last problem didn't solved: now we have different behaviour with kapt and ksp:

See this comment: https://github.com/micronaut-projects/micronaut-core/issues/10228#issuecomment-1850199994

And repeat this comment too:

I thought again, and now I'm not entirely sure that primitives should be NotNull automatically. The point is that NotNull is usually perceived as a required argument/field, but for primitives, the absence of this field in JSON is perceived as assigning a default value, not null.

On the other hand, a primitive cannot be null...

In general, I think we need to decide how to correctly define the isNotNull flag for primitives, but now KSP returns true, and Java returns false

**Comment by dstepanov** [comment]
See https://github.com/micronaut-projects/micronaut-core/pull/10348

**Comment by altro3** [comment]
ok, undertand
