### ISSUE TITLE
Micronaut 4.2.x: AnnotationValue.get("") method return default parameter values even if the parameters are not specified

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#10242]
Related issue: https://github.com/micronaut-projects/micronaut-openapi/issues/1346

Simple test class:
```java
@Controller("/test")
class TestController {

  @Get
  @Operation(
    summary = "summary",
    description = "description",
    responses = {
      @ApiResponse(
        description = "response",
        content = @Content(
          mediaType = MediaType.APPLICATION_JSON,
          schema = @Schema(oneOf = {String.class, UUID.class})
        )
      )
    }
  )
  void test() {
  }
}
```
We set for `Schema` annoation only field `oneOf `.

What I see, when I get `AnnotationValue` parameters with `micronaut 4.1.11` in code block
```java
        AnnotationValue<?> av ....
        var anyOfList = av.get("anyOf", ARGUMENT_STRING_ARRAY).orElse(null);
        var oneOfList = av.get("oneOf", ARGUMENT_STRING_ARRAY).orElse(null);
        var allOfList = av.get("allOf", ARGUMENT_STRING_ARRAY).orElse(null);
```
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/b7577738-c4f8-4071-b099-c2aae6dfa785)

All is ok, `allOf` - null, `anyOf` - null and `oneOf` - array with 2 elements

What I see with the same block with micronaut 4.2.x:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/05dd07b2-c691-4dd4-b54d-7336a109771c)

As you see now fields `allOf` and `anyOf` setted as empty array. This is wrong

### Version

4.2.x

**Comment by altro3** [comment]
@dstepanov looks like this bug created here: https://github.com/micronaut-projects/micronaut-core/pull/9838

**Comment by dstepanov** [comment]
Well technically the default value is en empty array so it works fine IMHO. Why do you need to use Get method instead of StringValues?

**Comment by dstepanov** [comment]
The change in v4 is that Get method returns the default values if empty and to avoid it StringValue/StringValues or equivalent should be used.

**Comment by altro3** [comment]
Because an empty list and null are not the same thing. Yes, in this case it is suitable, but I do not understand why the system behavior changed in version 4.2.0.

I need to distinguish the concept of a default value from what is specified by the user or not. Now it turns out that I cannot understand whether the `anyOf` parameter is specified or whether the default value is an empty list. This is very important because, as I wrote above, a missing value and an empty list are not the same thing.

How can we now get the real value in the annotation in the code and distinguish it from the default value?

**Comment by dstepanov** [comment]
As I wrote before, stringValues(“anyOf”) should be used and that will return only user specified value.

**Comment by altro3** [comment]
No! `stringValues(“anyOf”)` return emptyArray too! But user didn't set anything in annotaion. Empty array is a default value for annotaion, but I can't understand is it default value or user specified

![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/a1318114-6abf-418e-b563-05fce65b9169)

Because `stringValues` with annotation `@NonNull`:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/247979f7-cdaf-4411-8c17-68d766b9cb71)

But I need to get null value to understand that user didn't speified it. With version `4.1.11` method `av.get("anyOf", ARGUMENT_STRING_ARRAY).orElse(null)` returned `null`,  after `4.2.0` it return `empty array`

**Comment by dstepanov** [comment]
Why do you need to know if an user specified an empty array?

I think the behavior is correct, because an empty array is specified as a default. You can also access the values and the defaults of the value, that should tell you exactly what is set vs defaults.

**Comment by altro3** [comment]
@dstepanov because sometimes I need to divide default value and user-set value.

For example:

 `@Schema(required = false)`: if user manually set that this schema is not required, I need to ignore all other annotations and set `false`.
`@Schema(required = true)`: if user manually set that this schema is not required, I need to ignore all other annotations and set `true`.
`@Schema`: if user manually **didn't set** `required` property in annotaion, I can calculate `required` value from other sources, for example `@NotNull` annotaion.

In general, there are cases when you need to understand whether a value was specified by the user in the code, or whether it was not specified. Therefore, now micronaut-openapi may not work correctly in some places.

Once again, specifically in the case of anyOf, you can use your option, but in other cases the behavior may now change. It would be better if you left the system behavior as it was :-(

**Comment by altro3** [comment]
The second exmaple: `@Schema` annotation have two properties - `required` (deprecated) and `requiredMode`. How I can understand now, that user set only of them? `required` ahs default value `false`, requiredMode - `RequiredMode.AUTO`. 

By your new logic, if user write `@Schema(requiredMode = RequiredMode.TRUE)`, I will have two values, instead of one. this kind of logic is more difficult to process. There must be a way to understand whether the user himself has set the value or whether the value is not set and the default value is taken - as before.

**Comment by dstepanov** [comment]
I understand `Optional<T> get(CharSequence member, ArgumentConversionContext<T> conversionContext)` was always supposed to return the default value, so it works as intended. You can call `getConvertibleValues().get(member, conversionContext)` to retrieve the value without the default.

**Comment by yawkat** [comment]
we have had problems before with behavioral differences between the default value and the unset value. we should avoid creating APIs that have differences like you describe @altro3

**Comment by altro3** [comment]
@dstepanov As I understand it, the get method returns Optional precisely in order to see the value that the user himself has set, i.e. if `Optional.empty()` is returned (let me remind you that an annotation cannot have a default value of `null` ), then the user did not set any value. At the same time, methods such as `stringValue` return a `@NotNull` value, i.e. either the one set by the user or the default one.

**Comment by altro3** [comment]
Simply, according to the new logic, using `Optional` becomes meaningless, because the value will never be null according to the new logic

**Comment by dstepanov** [comment]
No, stringValue/ stringValues will never return the default. Only the get method does. It was like this probably since v1 but the problem was that, AnnotationValue didn’t always had the defaults set, after that was corrected you can see the default coming from the get method.

**Comment by altro3** [comment]
Then I don't understand why stringValue returns `@NotNull` value. It turns out that it returns some objects that are not related to the real default values, but they are invented by Micronaut himself. An empty string or an empty array (which is usually the default) is not the same thing as null

**Comment by altro3** [comment]
It turns out that if I write a default value, for example I write `test`, and then do not set any value in the annotations, then stringValue will return me empty string, and not the value of `test` ?

**Comment by dstepanov** [comment]
Do you have an example of a case when `stringValue` returns non-empty for strings and hasn't been set?  `stringValues` Does return an empty array but that's because it was created in this way.

**Comment by altro3** [comment]
Yes, you are right, stringValue never returns the default value. Yes, indeed stringValue was a bad example.

So, what I personally don't like now: Here's a code example - we have an annotation with two fields.

![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/7a9a54e9-ae7c-4d5a-b87e-0f2aec007829)

Next we call the get / stringValues / enumValues methods and this is what we get:

![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/36730662-fa4d-425c-a1f7-5afccfb7c608)

As you can see, the get method now returns the default value - hence the question: why do we need Optional at all if you will NEVER get a Null value. That is, you made this method de facto never return null.

At the same time, the enumValues and stringValues methods return empty arrays - why? The logic here is completely incomprehensible. You are trying to get the notNull value of these fields, you get empty arrays, and these empty arrays were invented by Micronaut himself. They have nothing to do with reality.

In general, now the behavior of the system has become even more confusing than before. The get method and the enumValues and stringValues methods do not work logically.

In my opinion, now there is only one logically and unambiguously working method left - the one you suggested above: getConvertibleValues().get(member, conversionContext)

I just don’t understand why the behavior of the system should be so confusing

**Comment by dstepanov** [comment]
You are right. It doesn't make sense to have `Optional` as a `get` result now, but before, the defaults were missing in some cases, which I did fix in v4. I don't like our `*Values` methods. We cannot check if not set, and working with arrays is sometimes annoying. I was thinking of introducing `*ValuesSet` to fix it.

Looking at the API, we might want to add `getRequiredValue(CharSequence member, ArgumentConversionContext<T> conversionContext)`,

**Comment by graemerocher** [comment]
The original idea with the `*Value` and `*Values` methods were to provide alternatives that were more performant and didn't wrap `Optional` or go through conversion service since you know ahead of type what type you were looking up.

The original design they intentionally did not return defaults as that would require another lookup hurting performance. But somehow over time the introduction of default value lookup was introduced changing the semantics of these methods from the original intent which is unfortunate.

**Comment by altro3** [comment]
Well, that's how I understood it. The `stringValue` method does work now; it returns null if no value is specified. But here’s the problem: now the `Values` methods do NOT return the default value, but an empty array, which has nothing to do with the default value. This is misleading. Because now an empty array is NOT a default value, it is NOT a value entered by the user, but it is a value that Micronaut himself came up with.

**Comment by altro3** [comment]
In general, there is now clearly no transparent logic for working with annotation parameters. The methods work in different ways, but from the names and descriptions of the methods it is not clear how to use them correctly and what they return. As I wrote above, the only method with transparent logic is `getConvertibleValues().get(member, conversionContext)` - it returns Null if the parameter was not specified by the user or the value that was specified by the user.

But then it turns out that other methods are just a breeding ground for bugs

**Comment by graemerocher** [comment]
> Well, that's how I understood it. The `stringValue` method does work now; it returns null if no value is specified. But here’s the problem: now the `Values` methods do NOT return the default value, but an empty array, which has nothing to do with the default value. This is misleading. Because now an empty array is NOT a default value, it is NOT a value entered by the user, but it is a value that Micronaut himself came up with.

On this topic, this is intentional, originally the `*Value()` and `*Values()` methods were designed for the following behaviour:

* Don't factor in defaults
* Don't convert
* Don't wrap in `Optional`

What you are saying here is you want to the default value from `*Values` but they were never designed to lookup the default value.

**Comment by altro3** [comment]
No it is not true. Let's go point by point:

1. Initially, I am saying that the `get` method used to return the value specified by the user and if it is not specified, then null is returned. Starting from version `4.2.0`, the default value began to be returned instead of null. That is, now the wrapper in Optional is meaningless and now the de facto return value is NotNull , although the annotation is not specified.

2. Now, using the get and Value / Values methods, it is impossible to determine whether the user has specified a value or not because the Values method returns an empty array if the user has not specified anything, but the user can intentionally specify an empty array. It is impossible to understand whether this was done by a user or by the micronaut himself.

3. What I need is just a way to take the value that the user specified, without replacing it with an empty array or the default value. The only way available now is to use the getConvertibleValues().get(member, conversionContext) method

As I wrote above, because of the first two points, the get and Value / Values methods become useless, because either they can deceive or do not give the necessary information.

**Comment by dstepanov** [comment]
To clarify:
1. The default value was returned in `get` method before. Before v4 the default values were not set correctly in many cases. The default array values were somehow missing, and it was corrected in v 4.2. It is correct, that having an optional as a return type of `get` method doesn't make sense.
2. The problem is only for `Values` methods as it is always not null, `Value` method will return empty for not specified.

**Comment by altro3** [comment]
Yes that's right. About get: now Optional is not needed at all, because the value is always NotNull - either the default one or the one set by the user.

This means that before I completely relied on this bug :-).

The illogical behavior of the Values method remains - because returning an empty array is misleading.

And it would be nice if there was some simple method to get exactly the value specified by the user. Yes, the Value method is suitable, but due to the illogical behavior of the Values method, it is scary to use it, because there is no guarantee that it will not return something invented by Micronaut

**Comment by graemerocher** [comment]
perhaps `stringValuesOrNull()` or something is missing. Note that you can also always check `isPresent(@NonNull String annotation, @NonNull String member)` on `AnnotationMetadata`

**Comment by altro3** [comment]
Yes, I understand that there are still ways to work normally. I’m just pointing out that simple methods don’t work and you have to write more complex logic or understand how to write it correctly using tickets on Github

**Comment by altro3** [comment]
Okay, we found out that this is not a bug, but a feature, so the ticket can be closed
