### ISSUE TITLE
Error while using Inputstream as a bodytype in exchange method of BlockingHttpClient 

### ISSUE THREAD

**Issue by munishchouhan** [micronaut-projects/micronaut-core#10256]
### Expected Behavior

Return InputStream inside an HttpRespone.

### Actual Behaviour

Getting following error:
`io.micronaut.http.client.exceptions.HttpClientResponseException: Client 'proxy-client': Error decoding HTTP response body: Error decoding stream for type [class java.io.InputStream]: Cannot construct instance of `java.io.InputStream` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information`

### Steps To Reproduce

It can be reproduced by just Passing Input.class in this method
httpClient.toBlocking().exchange(request, bodyType) 

### Environment Information

OS: Mac 14.1.2 (23B92)
Java: openjdk version "17.0.8" 2023-07-18 LTS

### Example Application

https://github.com/seqeralabs/wave/pull/356

### Version

3.10.3

**Comment by graemerocher** [comment]
don't believe input stream is supported you can use `byte[]` and wrap the return value in a `ByteArrayInputStream`
