### ISSUE TITLE
Ignored annotation metadata default value

### ISSUE THREAD

**Issue by xaviarias** [micronaut-projects/micronaut-core#10267]
### Expected Behavior

The project contains a defined `@Bindable` annotation `@PageableMapping` to allow `Pageable` order properties to be mapped in each controller method.

This is useful when returned DTOs structure doesn't match the internal JPA entities, eg:

```kotlin
@Get("/test")
fun test(
    @PageableMapping(
        orderBy = [
            OrderMapping(
                property = "name",
                mappedName = "mappedName"
            )
        ]
    ) pageable: Pageable
): HttpResponse<TestDto> {
    // Run JPA queries with the pageable argument sorted by the mapped name
    return HttpResponse.ok(TestDto("test"))
}
```

When obtaining the annotation metadata in the `MappedPageableRequestArgumentBinder`, `AnnotationValue.isTrue(String)` should consider default values for user-defined annotations.

I.e., `mapping.isTrue("sortable")` should be `true` for the above defined `OrderMapping` annotation, as `sortable`defaults to `true`:

```kotlin
annotation class OrderMapping(
    val property: String,
    val mappedName: String = "",
    val sortable: Boolean = true
)

```

### Actual Behaviour

The result of `mapping.isTrue("sortable")` is `false`.

This issue might be related: 
- https://github.com/micronaut-projects/micronaut-core/issues/9780

### Steps To Reproduce

1. Checkout the [demo application](https://github.com/xaviarias/demo)
2. Start the application with `./gradlew run`
3. Go to the URL http://localhost:8080/test?sort=name
4. An 400 Bad Request error is received instead of 200 OK

### Environment Information

- OS: MacOSX 14
- JDK Version: 17
- Gradle 8.4

### Example Application

https://github.com/xaviarias/demo

### Version

4.2.1

**Comment by dstepanov** [comment]
This is correct, `isTrue` is not returning the default values. The only method returning the default is `AnnotationValue#get`
