### ISSUE TITLE
KSP with micronaut 4.2.2: `@Client` annotated class not introspected when use also `@Generated` annotation

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#10277]
look to the screenshot:

![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/369ed845-e51b-434c-882a-c6d13c90746f)

At the top you see what kapt generated: 2 packages - `io.micronaut.openapi.test.api` and `io.micronaut.openapi.test.model`

Next you see generated sources yt micronaut openapi and introspected class by KSP. As you see, generated 2 packages, but introspected only one - `io.micronaut.openapi.test.model`.

That's because introspection lost all interfaces from package `io.micronaut.openapi.test.api`

With micronaut `4.2.1` all works fine

Sample interface which lost:
```kotlin
@Generated("io.micronaut.openapi.generator.KotlinMicronautClientCodegen")
@Client("\${openapi-micronaut-client-base-path}")
interface PetApi {

    @Post("/pet")
    fun addPet(
        @Body @Nullable @Valid body: Pet?
    ): Mono<Void>
}
```

### Version

4.2.2

**Comment by altro3** [comment]
@dstepanov hi! Look to this, pls. This is critical bug for micronaut with KSP

**Comment by dstepanov** [comment]
No sure what would cause that, going to check next week

**Comment by altro3** [comment]
@dstepanov Hi! You know, this is certainly a strange error, but I was able to figure it out.

So, the problem is NOT with the interfaces, but with... the `@Generated` annotation!!!

To reproduce it you need to create an interface, for example:
```kotlin
@Generated("io.micronaut.openapi.generator.KotlinMicronautClientCodegen")
@Client("openapi-micronaut-client-base-path")
interface PetApi {

    /**
     * {@summary Add a new pet to the store}
     *
     * @param body Pet object that needs to be added to the store (optional)
     * @return Mono&lt;Void&gt;
     */
    @Post("/pet")
    fun addPet(
        @Body @Nullable @Valid body: Pet?
    ): Mono<Void>
}
```
We run the build and see this:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/3dd7564d-0f08-4295-a4c8-483525999050)
As you can see, there is no class for PetApi in the generated folder, it’s as if the @Client annotation was simply ignored

Next, remove the Generated annotation and run `clean build` again:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/f6490d22-d11e-4277-bd44-4deb50a1032e)
As you can see, we now see the generated classes PetApi$Intercepted, $PetApi$Intercepted$Definition and others.

**Comment by altro3** [comment]
To reproduce this bug you just can add `@Generated` annotation to PetClient in `test-suite-kotlin-ksp`:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/7fc2ff6a-faac-40bb-bb54-f116d5114ad0)

**Comment by dstepanov** [comment]
Ah right, we have a check that was skipping processing classes with Generated annotations. And I have noticed that it was incorrect and fixed it, now we have this. I guess it needs to be removed

**Comment by dstepanov** [comment]
What is the full name of that `@Generated` annotation?

**Comment by altro3** [comment]
@dstepanov `jakarta.annotation.Generated`
