### ISSUE TITLE
Kapt treats annotation's default "" value as null, while KSP treats it as empty string

### ISSUE THREAD

**Issue by cdome** [micronaut-projects/micronaut-core#10271]
### Actual Behaviour

This difference is causing e.g. this issue https://github.com/micronaut-projects/micronaut-jms/issues/439.

The problem is that when annotations and their default values get registered in ```io.micronaut.inject.annotation.DefaultAnnotationMetadata#registerAnnotationDefaults(io.micronaut.core.annotation.AnnotationClassValue<?>, java.util.Map<java.lang.CharSequence,java.lang.Object>)```, with Kapt, ```defaultValues``` doesn't contain parameters their default value is empty string, while Ksp includes them. This means, that e.g. ```@io.micronaut.transaction.annotation.Transactional``` registers 6 default values under Kapt and 9 under Ksp (```value```, ```transactionManager``` and ```name``` have all empty strings as default). This then leads to problems with libraries (such as micronaut-jms), that depend on one or other behavior.

In the case  of micronaut-jms - it checks if the value of ```io.micronaut.jms.annotations.Queue#messageSelector``` is set, and if yes, it will create different SQSSession. Now - if the value is not specified in the applied annotation, it would return ```Optional.valueOf("")``` when using Ksp and ```Optional.empty()``` when using Kapt. While this particualar MN-JMS issue can be fixed in the library, this different behavior might affect other libraries as well.

### Steps To Reproduce

1. Add breakpoint  at ```io.micronaut.inject.annotation.DefaultAnnotationMetadata#registerAnnotationDefaults(io.micronaut.core.annotation.AnnotationClassValue<?>, java.util.Map<java.lang.CharSequence,java.lang.Object>)```
2. Run any sample application with Kapt as annotation processor in debug and observe ```defaultValues``` for annotations that contain empty string as default for any of its parameters.
3. Do the same with Ksp annotation processor
4. Compare results

### Environment Information

- JDK 17
- Kotlin 1.9.0
- Gradle 8.5
- KSP

### Version

4.2.1

**Comment by dstepanov** [comment]
https://github.com/micronaut-projects/micronaut-jms/blob/5b9b6785a2b1e21471b8bfe202ca560688d6a867/jms-core/src/main/java/io/micronaut/jms/configuration/AbstractJMSListenerMethodProcessor.java#L129-L136

Some of those values should be `stringValue` variations that don't add the default value.
