### ISSUE TITLE
AbstractMethodError when using KSP instead of KAPT with @Client

### ISSUE THREAD

**Issue by meriouma** [micronaut-projects/micronaut-core#10279]
### Expected Behavior

This is a simplified version, but I have those classes
```kotlin
@Singleton
class SessionHttpRepository(
    private val sessionApi: SessionApiClient,
) : SessionRepository {
    override fun findSession(uuid: String): Session? = runCatching {
        sessionApi.getSession(uuid, false) }
    }.getOrNull()
}
```
using this client

```java
@jakarta.annotation.Generated("org.openapitools.codegen.languages.MicronautCodegen")
@io.micronaut.http.client.annotation.Client(id = "account-service")
public interface SessionApiClient {
    @io.micronaut.http.annotation.Get("/sessions/{uuid}")
    @io.micronaut.http.annotation.Consumes({ "application/json" })
    io.micronaut.http.HttpResponse<Session> getSession(
        @io.micronaut.core.annotation.NonNull
        @io.micronaut.http.annotation.PathVariable(value = "uuid")
        java.lang.String uuid,
        @io.micronaut.core.annotation.Nullable
        @io.micronaut.http.annotation.QueryValue(value = "keepAlive")
        java.lang.Boolean keepAlive);
}
```

This works with KAPT but not with KSP. Removing the `keepAlive` parameter makes it work too.

This looks similar to https://github.com/micronaut-projects/micronaut-core/issues/10277, however I tried with 4.2.1 and it doesn't work.

### Actual Behaviour

```
java.lang.AbstractMethodError: Receiver class c.e.session.$CachedSessionHttpRepositoryTest$SessionApi0$Definition$Intercepted does not define or inherit an implementation of the resolved method 'abstract io.micronaut.http.HttpResponse getSession(java.lang.String, java.lang.Boolean)' of interface c.e.SessionApiClient
```

### Steps To Reproduce

1. Use KSP

### Environment Information

- JDK 17

### Version

4.2.0, 4.2.1, 4.2.2

**Comment by altro3** [comment]
@meriouma It's better to use the official generator from micronaut - https://github.com/micronaut-projects/micronaut-openapi/tree/master/openapi-generator. But yes, you're right, there is a bug. I came across it myself. I saw that you connected our issues. We are waiting for a fix

**Comment by altro3** [comment]
And to fast fix, you can disable adding `@Generated` annotation

**Comment by dstepanov** [comment]
I think this is fixed by https://github.com/micronaut-projects/micronaut-core/pull/10282
