### ISSUE TITLE
Unable to Get Body in Filter class

### ISSUE THREAD

**Issue by satya-devloper** [micronaut-projects/micronaut-core#10274]
### Expected Behavior

In the output I should get 
TestFilter Request Body : Optional[{key=value}]
TestController Request Body : Optional[{key=value}]

### Actual Behaviour

TestFilter Request Body : null
TestController Request Body : Optional[{key=value}]

### Steps To Reproduce

./gradlew run
It will run on port 8082
hit the api : http://localhost:8082/test/api/myapi with postbody
{
   "key":"value"
}

### Environment Information

jdk version - 17.0.8

### Version

4.0.2

**Comment by satya-devloper** [comment]
[test_micronaut.zip](https://github.com/micronaut-projects/micronaut-core/files/13687140/test_micronaut.zip)

**Comment by yawkat** [comment]
It is not possible to access the request body in a legacy filter. You can do it with filter methods, however. https://docs.micronaut.io/latest/guide/index.html#filtermethods
