### ISSUE TITLE
Porting our WebPortal Software to Micronaut 4.4

### ISSUE THREAD

**Issue by atpguru** [micronaut-projects/micronaut-core#10291]
### Feature description

Hi there, probably you already know that you've created something brilliant, but let me anyway state that I also find it brilliant. My actual problem is, that I most of the time work on my Apple M1 in a virtual Debian 12 machine. Now with upgrading to Micronaut 4.4.2 I'm not able to install and run mn on arm ( since Java is 17 ) any suggestions or maybe a solution? thanks a lot in advance. Andreas

**Comment by wetted** [comment]
see https://github.com/micronaut-projects/micronaut-starter/issues/1919
