### ISSUE TITLE
Assemble task on fresh project (using create-function) failed

### ISSUE THREAD

**Issue by antondelpiero** [micronaut-projects/micronaut-core#1031]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided

### Steps to Reproduce

1. create a function `mn create-function test`
2. open the project (in IntelliJ), wait until all dependencies loaded, and then do assemble

### Expected Behaviour

Build should be successful

### Actual Behaviour

i got this error:
```00:27:03: Executing task 'assemble'...


> Task :compileJava
Note: Creating bean classes for 1 type elements

> Task :processResources UP-TO-DATE
> Task :classes
> Task :jar UP-TO-DATE
> Task :startScripts UP-TO-DATE
> Task :distTar UP-TO-DATE
> Task :distZip UP-TO-DATE
> Task :shadowJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shadowJar'.
> java.lang.AbstractMethodError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
7 actionable tasks: 2 executed, 5 up-to-date
Execution failed for task ':shadowJar'.
00:27:10: Task execution finished 'assemble'.
```

### Environment Information

- **Operating System**: MacOS Mojave
- **Micronaut Version:** 1.0.1
- **JDK Version:** 1.8

### My workaround

if i downgrade the `com.github.johnrengelman.shadow` to version 4.0.0 in `build.gradle`, the error is gone

**Comment by vlabs** [comment]
same here with `1.0.2`

**Comment by graemerocher** [comment]
Duplicated by https://github.com/micronaut-projects/micronaut-profiles/issues/101
