### ISSUE TITLE
A CompletableFuture Controller method returning an empty body results in 404

### ISSUE THREAD

**Issue by jeremyg484** [micronaut-projects/micronaut-core#10419]
### Expected Behavior

A `@Controller` method with a return signature of `CompletableFuture<MutableHttpResponse<Object>>` can return a response with an empty body such as

```
return CompletableFuture.completedFuture(HttpResponse.ok());
```

### Actual Behaviour

Any CompletableFuture response with an empty body returns a 404 Not Found response.

The logic that results in this is at: https://github.com/micronaut-projects/micronaut-core/blob/443de14b0dbc4fa9449b6726fe25f60b4dacc6c3/http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java#L711-L713

Note that this in contrast to doing the same with a `Publisher<MutableHttpResponse<Object>>` signature.

For example, this works as expected:
```
return Mono.just(HttpResponse.ok());
``` 

### Version

4.3.1

**Comment by altro3** [comment]
@yawkat You fixed it, right? I think we can close it.

**Comment by yawkat** [comment]
Yep thanks
