### ISSUE TITLE
Feature request: build a fully executable jar

### ISSUE THREAD

**Issue by iBernd81** [micronaut-projects/micronaut-core#1042]
Within Grails or SpringBoot applications it is possible to build a fully runnable jar. With such a file the application can be started using system defaults.

See this link for more information: (https://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html)

Is it possible or will it be possible to do so with new Micronaut?

**Comment by jameskleeh** [comment]
Closing this due to a solution already existing and we have no plans to get into creating build tool plugins

**Comment by iBernd81** [comment]
Thank you @graemerocher for your lightning fast answer again. We all can see your love on this great piece of software!

According to your suggestion I am using the Spring Boot Gradle Plugin and so I can include `bootJar { executable = true }` in my `build.gradle`. With `cat` I can see that the launch script is included in the resulting build. This is what I need in the end...

But the first problem is now that my application will not start anymore within IDE. Something is wrong with GORM because it is not able to start anymore (`NoSuchMethodException`).
The second problem is that the `bootJar` starts on console but without GORM and therefore no access to the underlying PostgreSQL database.

I have to spend a few more hours and will keep you informed.
