### ISSUE TITLE
New context propagation API works incorrectly on reactive subscribers

### ISSUE THREAD

**Issue by lgathy** [micronaut-projects/micronaut-core#10443]
### Expected Behavior

In the following example code in a controller:

```java
  @Get("/foo")
  public Mono<String> foo() {
    // (1)
    return downstreamCall().map(this::mapResponse);
  }

  protected Mono<String> downstreamCall() { ... }

  private String mapResponse(String body) {
    // (2)
  }
```

Upon execution at code point (2) the `PropagatedContext` should always be the same as it was at code point (1).

### Actual Behaviour

When `mapResponse(...)` is called on a different thread than `foo()` was, then the `PropagatedContext` at code point (2) is non-deterministic, i.e. empty.

### Steps To Reproduce

1. Check out https://github.com/lgathy/micronaut-tracing/tree/bug/subsequent-client-traces
2. Run `./gradlew :micronaut-tracing-opentelemetry-http:test`
3. The newly added test case in `io.micronaut.tracing.opentelemetry.instrument.http.OpenTelemetryHttpSpec` fails

The failure is also demonstrated by unit tests added in my forked repo, see the Example application link.

### Environment Information

- Operating system: MacOS 14.2.1
- JDK version: 17.0.10

### Example Application

https://github.com/lgathy/micronaut-core/commit/8db3f9c02ee864fc27290e51b06d9a75b6101214

### Version

[4.0.0; 4.3.3]

**Comment by dstepanov** [comment]
I don't think that can be "fixed", the only way is to add Micrometer Context propagation dependency and let the Reactor propagate it

**Comment by lgathy** [comment]
@dstepanov We started with that approach as well, but it was equally unsuccessful. This however seems to be fixing the problem (together with https://github.com/micronaut-projects/micronaut-core/pull/10445) and we do not even need the legacy context propagation. Thanks for merging them in so quickly! :)

**Comment by dstepanov** [comment]
What is the problem with using the Reactor-Micrometer integration?

**Comment by lgathy** [comment]
Can we please also backport these into earlier 4.x versions, at least into 4.2.x? To me this seems to be affecting all 4.x version since 4.0.0

**Comment by dstepanov** [comment]
@sdelamo Do we need extra PRs to backport those two PRs?

**Comment by lgathy** [comment]
@dstepanov We followed https://docs.micronaut.io/latest/guide/index.html#reactorContextPropagation for the tests in https://github.com/micronaut-projects/micronaut-tracing/pull/498 and they were failing anyways. I traced down how the context was propagated through and arrived to these two bits were it goes wrong. I also hard-patched them into tracing locally and the tests turned green.

Once micronaut-core v4.3.4 is released and tracing master is updated to use it, I will rebase that PR and we should see the failure go away.

**Comment by sdelamo** [comment]
@lgathy can you try with Micronaut Framework 4.3.1 which contains core 4.3.5?

**Comment by lgathy** [comment]
@sdelamo Yes, I tried this locally yesterday and it worked. I see that https://github.com/micronaut-projects/micronaut-tracing/pull/512 is merged now so I updated the [PR](https://github.com/micronaut-projects/micronaut-tracing/pull/498) in tracing. Those new tests should now turn green.
