### ISSUE TITLE
Parsing of application/x-www-form-urlencoded is broken, can result in Internal Server Error.

### ISSUE THREAD

**Issue by marek-stanulewicz-vonage** [micronaut-projects/micronaut-core#10446]
### Expected Behavior

Parsing should conform to https://url.spec.whatwg.org/#application/x-www-form-urlencoded.

### Actual Behaviour

Parsing does not support the case when a single sequence is just `key`. Moreover, if this `key` is followed by more sequences an exception is thrown and Internal Server Error is returned.

### Steps To Reproduce

Just run the test.

### Environment Information

Windows.
JDK Corretto 17.0.10.

### Example Application

https://github.com/marek-stanulewicz/micronaut-issues/tree/www-form-urlencoding-parsing

### Version

4.2.4

**Comment by marek-stanulewicz-vonage** [comment]
It behaves differently than 3.10.1, which is even worse: https://github.com/marek-stanulewicz/micronaut-issues/tree/3.x-www-form-urlencoding-parsing

**Comment by jeremyg484** [comment]
@marek-stanulewicz Thank you for the thorough reproducible tests - they were very helpful in getting this resolved.

Note that the change to Micronaut in #10601 is just a partial fix - no-value keys will work now except in cases where the key is the last in the POST body sequence. To fix that final case, we had to submit a patch to Netty - see https://github.com/netty/netty/pull/13908. It looks like it should be in the 4.1.108 version of Netty.
