### ISSUE TITLE
Declarative client error handling works differently with Micronaut 4

### ISSUE THREAD

**Issue by vekonypeter** [micronaut-projects/micronaut-core#10458]
### Issue description

We have a 3rd party API which returns certain errors with 200 response code. We communicate with it via the declarative client, and until now, used an `HttpClientFilter` like the following to detect these errors:

```
override fun doFilter(request: MutableHttpRequest<*>, chain: ClientFilterChain): Publisher<out HttpResponse<*>> {
    return Flux
        .from(chain.proceed(request))
        .doOnError(HttpClientResponseException::class.java) { responseException ->
            if (responseException.status == HttpStatus.OK) {
                try {
                    responseException.response.getBody(ErrorResponse::class.java).ifPresent { responseBody ->
                        throw SpecialExceptionFromErrorBody(responseBody)
                    }
                } catch (ex: CodecException) {
                    throw SomethingElse()
                }
            }
            throw responseException
        }
}
```

The client is something like this:
```
@MyErrorHandling
@Client("my-client", errorType = ErrorResponse::class)
@JacksonFeatures(
    enabledDeserializationFeatures = [
        DeserializationFeature.FAIL_ON_MISSING_CREATOR_PROPERTIES,
        DeserializationFeature.FAIL_ON_NULL_FOR_PRIMITIVES
    ]
)
interface MyClient
```

What happened here is basically that upon these errors, serialisation to the expected type failed, so an error was thrown, and this error was handled in the filter.

From Micronaut 4, this stopped working, because `HttpClientResponseException` never contains the body of the response, so `responseException.response.getBody` never succeeds.

I tried with the new filtering API, using `@ClientFilter` and `@ResponseFilter` annotations, but the effect is basically the same, I can never get the body.

I also tried to set `errorType = ErrorResponse::class`, but it had no effect.

Could someone please advise on how we could make this work again?

**Comment by sdelamo** [comment]
do you have a sample application?

**Comment by vekonypeter** [comment]
@sdelamo I'll try to put together a minimal application to reproduce this

**Comment by vekonypeter** [comment]
@sdelamo see demo app here: https://github.com/vekonypeter/miconaut-core-issue-10458

see test: https://github.com/vekonypeter/miconaut-core-issue-10458/blob/main/src/test/kotlin/com/example/DemoClientTest.kt

what I would like to achieve is to make all these tests pass, currently only the 4xx and 5xx are green

**Comment by vekonypeter** [comment]
@sdelamo , @wetted do you have an estimation maybe when this could get fixed? 🙏

**Comment by sdelamo** [comment]
We don't have any estimation. If you need urgent fixes, we have [commercial support](https://micronaut.io/support/).

**Comment by wetted** [comment]
@yawkat I'm puzzled by this. Any ideas?

On the test for statuscode = 200, I get 

`io.micronaut.http.codec.CodecException: Error decoding JSON stream for type [T]: Unable to deserialize type [com.example.DemoResponse]. Required constructor parameter [Entity result] at index [0] is not present or is null in the supplied data` 

at `FullNettyClientHttpResponse` line 175. The `DemoResponse` data class isn't getting initialized with a result.

**Comment by dobe** [comment]
is there an estimate when this will be fixed?

**Comment by sdelamo** [comment]
@dobe we don't have any estimate. @jeremyg484 can you look into this?
