### ISSUE TITLE
Is using @Inject in constructor making the bean findable a normal behavior ?

### ISSUE THREAD

**Issue by FrogDevelopper** [micronaut-projects/micronaut-core#10474]
### Issue description

Hello,

As I'm not sure if it is a bug or not, I just open a simple ticket.
We discovered a very weird behaviour: when a class has its constructor (or a field)  annotated with `@Inject`, it is findable using `BeanLocator.findBean(Class)`, even if the bean itself is not annotated by `@Contex` or `@Singleton` nor declared in any `@Factory`.

How to reproduce:
1. create a simple minimal Micronaut project
2. Add 2 classes
  ```java
  package org.example;
  
  import jakarta.inject.Singleton;
  
  @Singleton
  public class Bar {
  }
  ```
and
  ```java
  package org.example;
  
  import jakarta.inject.Inject;
  
  public class Foo {
  
      private final Bar bar;
  
      @Inject
      public Foo(Bar bar) {
          this.bar = bar;
      }
  }
  ```
3. Update existing test class
```java
package org.example;

import jakarta.inject.Inject;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import io.micronaut.runtime.EmbeddedApplication;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;

@MicronautTest
class DemoTest {

    @Inject
    EmbeddedApplication<?> application;

    @Test
    void testItWorks() {
        Assertions.assertTrue(application.isRunning());

        final var bean = application.getApplicationContext().findBean(Foo.class);
        Assertions.assertTrue(bean.isEmpty());
    }

}
```
The test will fail, as the bean will be found, which is not what I will have expected.

So, is it correct to have implicite declaration like this ?

**Comment by FrogDevelopper** [comment]
Of course, when commenting the `@Inject` annotation, the test is not failing anymore

**Comment by sdelamo** [comment]
Why are you not annotating Foo with `@Singleton`?

**Comment by FrogDevelopper** [comment]
it was a error to not annotating it, that we didn't saw until we add the lombok annotation `@RequiredArgsConstructor` to generate the constructor instead of having a field annotated with `@Inject`
Then, of course it was not working anymore, and we were even more surprised that it was working before!

**Comment by dstepanov** [comment]
That's a feature that originated here https://javax-inject.github.io/javax-inject/ I think

**Comment by FrogDevelopper** [comment]
I don't see any reference about an annotated constructor being instantiate
For what I understand, the annotation `@Inject` is to identify constructor (or fields) to be used for _dependency injection_, nothing else

> This package provides dependency injection annotations that enable portable classes, but it leaves external dependency configuration up to the injector implementation. Programmers annotate constructors, methods, and fields to advertise their injectability

source [The final specification for the JSR-330 annotations](https://javax-inject.github.io/javax-inject/api/javax/inject/package-summary.html#:~:text=This%20package%20provides%20dependency%20injection%20annotations%20that%20enable%20portable%20classes%2C%20but%20it%20leaves%20external%20dependency%20configuration%20up%20to%20the%20injector%20implementation.%20Programmers%20annotate%20constructors%2C%20methods%2C%20and%20fields%20to%20advertise%20their%20injectability)

**Comment by nedelva** [comment]
I suppose it boils down to asking what makes a class a _managed bean_, that can be discovered in your DI context. To complement what @dstepanov mentioned, I believe that Micronaut's DI is inspired (or tries to implement as much as possible) from the CDI spec.

If you want to know more about CDI, I encourage you to have a look at the Weld documentation. If you go and read [Section 2.2](https://docs.jboss.org/weld/reference/latest/en-US/html_single/#_what_kinds_of_classes_are_beans) you will find out that most classes are also managed beans (and your `Foo`class as well).

**Comment by FrogDevelopper** [comment]
thank for all your responses
I've learned a lot
