### ISSUE TITLE
Bug in non-incemental annotation processing

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-core#10477]
We had an issue reported with using Groovy/spring boot and MicronautApplicationContext 

https://github.com/micronaut-projects/micronaut-spring/issues/521

After some digging, I believe it's an issue with the non-incremental annotation processor 🤔 

I have created a Java repo over here which does what the Groovy issue does

https://github.com/bloidonia/micronaut-incremental-annotation-issue

If I run `./gradlew --stop && ./gradlew clean run --no-build-cache` then the app starts and port 8080 returns hallo as expected

If we look inside `build/classes/java/main` we see:

![image](https://github.com/micronaut-projects/micronaut-core/assets/49317/3d29186a-1641-44bb-ac1f-37606273fed9)

If I then change incremental to false in the build script

```diff
diff --git a/build.gradle.kts b/build.gradle.kts
index d95c0c8..788d38d 100644
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -43,7 +43,7 @@ micronaut {
     runtime("netty")
     testRuntime("junit5")
     processing {
-        incremental(true)
+        incremental(false)
         annotations("bootTestJava.*")
     }
 }
```

And re-run `./gradlew --stop && ./gradlew clean run --no-build-cache` then the build fails with 

> Caused by: java.lang.IllegalAccessError: failed to access class org.springframework.boot.autoconfigure.AutoConfigurationPackages$Registrar from class bootTestJava.$Application$AutoConfigurationPackages$Registrar0$Definition$Reference (org.springframework.boot.autoconfigure.AutoConfigurationPackages$Registrar and bootTestJava.$Application$AutoConfigurationPackages$Registrar0$Definition$Reference are in unnamed module of loader 'app')

This is the same error we see in the original issue with Groovy

And `build/classes/java/main` now looks like:

![image](https://github.com/micronaut-projects/micronaut-core/assets/49317/3e09d464-2763-4c9c-91b8-84cf93a264aa)

**Comment by dstepanov** [comment]
You are missing spring annotations in the processing definition:
```
        annotations("bootTestJava.*", "org.springframework.boot.*")
```
This makes it fail. Sorry @timyates

**Comment by timyates** [comment]
~~@dstepanov That still fails for me, even with that change 🤔~~

Ahhhhh

**Comment by timyates** [comment]
@dstepanov I have updated the repo https://github.com/bloidonia/micronaut-incremental-annotation-issue with that suggestion, and I get the same failure as without it 🤔
