### ISSUE TITLE
Micronaut is dead slow to start

### ISSUE THREAD

**Issue by thestarmaker** [micronaut-projects/micronaut-core#1048]
Hi peoplezz, 

Apologies if this has already been reported, but I have only seen similar issue raised for Mac OS while I am working on wondows. I have tried the Mac OS workaround (adding 127.0.0.1 to hosts file) but it did not help. 

The bottom line is that the application is really slow to start. This is especially problemous when running many integration tests as each would take 10 seconds just to start the app given the new application instance is booted for every run. 

### Steps to Reproduce
1. create new app using mn tool:
mn create-app experiment
2. clean build the app:
gradlew clean build
3. run the far jar
java -jar experiment-0.1-all.jar 

### Expected Behaviour
The application start up in reasonable time (say 3 seconds like Ratpack does)

### Actual Behaviour
The application takes unreasonable time to start: 1round 10 seconds:

c:\dev\projects\experiment\build\libs>java -jar experiment-0.1-all.jar
22:05:43.123 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 12710ms. Server Running: http://localhost:8080

### Environment Information
OS Name: Microsoft Windows 10 Pro
Version: 10.0.17134 Build 17134
Processor: Intel(R) Core(TM) i7-3517U CPU @ 1.90GHz, 2401 Mhz, 2 Core(s), 4 Logical Processor(s)
Micronaut Version: 1.0.1
JDK: OpenJDK Runtime Environment Zulu11.2+3 (build 11.0.1+13-LTS); OpenJDK 64-Bit Server VM Zulu11.2+3 (build 11.0.1+13-LTS, mixed mode)

**Comment by thestarmaker** [comment]
Hi, here is the trace log attached. This is interesting when I redirect output from cmd to a file the start up time does improve even with increased logging volume (trace). It is still 5 seconds though.

[log.txt](https://github.com/micronaut-projects/micronaut-core/files/2702130/log.txt)

**Comment by graemerocher** [comment]
What is interesting is that Netty takes over 3 seconds to start in the example. So it seems to be an issue creating the Netty event loop.

**Comment by graemerocher** [comment]
Possibly related https://github.com/netty/netty/issues/614

**Comment by thestarmaker** [comment]
UPDATE: installed Ubuntu on my machine, the same app starts in 3 seconds. People bound to using Windows by corporate policy are still in trouble...

**Comment by gyulavoros** [comment]
@thestarmaker Is your `/etc/hosts` file contains both of these lines?

```
127.0.0.1       localhost <output of hostname command>
::1             localhost <output of hostname command>
```

**Comment by graemerocher** [comment]
This is clearly a networking configuration issue and since the code that is slow is netty related impacts any project built on netty. If you want to take this further please feel free to report to https://github.com/netty/netty/issues
