### ISSUE TITLE
Java inject: `classElement.getBeanProperties()` lost field annotations for JavaPropertyElement

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#10480]
### Expected Behavior

Sample class:
```java
class Animal {

    @JsonProperty("class")
    protected String propertyClass;
    @Schema(name = "color", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    @Nullable
    private ColorEnum color;

    public String getPropertyClass() {
        return propertyClass;
    }

    public void setPropertyClass(String propertyClass) {
        this.propertyClass = propertyClass;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }
}
```

When I get `FieldElement` - all is ok:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/8a24e7dd-03d3-4265-b1d9-87cdeb771272)

When I use `classElement.getBeanProperties()` I see this:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/a6fce525-56e5-4099-885d-c4c47c9a9b22)

As you see,  `classElement.getBeanProperties().get(1).getAnnotationNames()` return empty list.

With KSP all works fine.

### Version

4.3.5

**Comment by altro3** [comment]
@dstepanov The very case when KSP works better than java :-D

**Comment by dstepanov** [comment]
Try `.get(1).getType().getAnnotationNames()`

**Comment by altro3** [comment]
@dstepanov I do not know what it was, but today I ran the test again and everything worked correctly with both KSP and Java...
