### ISSUE TITLE
Feature - Please allow decorations of threads for passing MDC information

### ISSUE THREAD

**Issue by RaviH** [micronaut-projects/micronaut-core#1049]
Spring provides `TaskDecorator` which can be used to decorate async threads with information for example retrieved from MDC: https://moelholm.com/2017/07/24/spring-4-3-using-a-taskdecorator-to-copy-mdc-data-to-async-threads/

I am tasked with bringing micronaut based service in line with Spring based services. Is there a way I can pass MDC / threads safe information created in `HttpServerFilter` to worker threads so that they access information like transaction id etc?

If not, can we add a feature like `TaskDecorator` in Spring?

We already do something similar in `ServerRequestContextInstrumentation`?

Thoughts?

**Comment by graemerocher** [comment]
Does `ServerRequestContext.currentRequest()` not work for you?

**Comment by RaviH** [comment]
@graemerocher Yup, it did. Works wonderfully well. Here's what I did for posterity:

a. Add what I would have normally added to MDC to a request attribute.
b. Write an around advice to the controller and in the around advice get the request object using: `ServerRequestContext.currentRequest()` and 
c. Get what I need from request attribute and add it to MDC.

I personally think: adding a feature like `enable MDC` and doing the above in Micronaut would be awesome. i.e. provide a generic framework. Happy to make a PR for that if it's a good idea. If not, I thought about creating a simple library that would do the same. 

Thoughts?

**Comment by graemerocher** [comment]
@RaviH sure sounds like it could be useful, maybe just an abstract interceptor one can extend. Contributions welcome!

**Comment by LarsEckart** [comment]
We're having the same issue. Sadly I'm not quite able to follow the conversation here. Such an around advice would mean an additional annotation for each controller everywhere, right? 

Wouldn't it be possible somehow to rather overwrite some of the default beans or similar to achieve such behaviour? Similar like this here: https://moelholm.com/2017/07/24/spring-4-3-using-a-taskdecorator-to-copy-mdc-data-to-async-threads/

I'm very happy to try out, explore and then contribute to such a solution, but I think right now I'm lacking direction to go anywhere :/

**Comment by graemerocher** [comment]
I don't believe around advice would be necessary. A instrumentation can be written that does this the same way as described in the article. Would be very similar to https://github.com/micronaut-projects/micronaut-core/blob/master/tracing/src/main/java/io/micronaut/tracing/instrument/util/TracingRunnableInstrumenter.java

Just with the code:

```java
Map<String, String> contextMap = MDC.getCopyOfContextMap();
    return () -> {
      try {
        // Right now: @Async thread context !
        // (Restore the Web thread context's MDC data)
        MDC.setContextMap(contextMap);
        runnable.run();
      } finally {
        MDC.clear();
      }
    };
```

**Comment by luckyswede** [comment]
This seems to work, after a quick test:
```
@Singleton
public class MdcInstrumenter implements Function<Runnable, Runnable>, RunnableInstrumenter, ReactiveInstrumenter {

    @Override
    public Runnable apply(Runnable runnable) {
        Map<String, String> contextMap = MDC.getCopyOfContextMap();
        if (contextMap != null && !contextMap.isEmpty()) {
            return wrapWithMdc(contextMap, runnable);
        }
        else {
            return runnable;
        }
    }

    @Override
    public Runnable instrument(Runnable command) {
        return apply(command);
    }

    @Override
    public Optional<RunnableInstrumenter> newInstrumentation() {
        Map<String, String> contextMap = MDC.getCopyOfContextMap();
        if (contextMap != null && !contextMap.isEmpty()) {
            return Optional.of(new RunnableInstrumenter() {
                @Override
                public Runnable instrument(Runnable runnable) {
                    return wrapWithMdc(contextMap, runnable);
                };
            });
        }
        return Optional.empty();
    }

    private Runnable wrapWithMdc(Map<String, String> contextMap, Runnable runnable) {
        return () -> {
            try {
                MDC.setContextMap(contextMap);
                runnable.run();
            } finally {
                MDC.clear();
            }
        };
    }
}
```

**Comment by graemerocher** [comment]
@luckyswede yup that is what I meant. Feel free to a send a PR with that you wish to include this in core. Probably needs a `@Requires(classes = MDC.lass)` on the bean

**Comment by LarsEckart** [comment]
indeed, it's working, thanks a lot @luckyswede !

I still don't fully understand why though :) Do the interfaces RunnableInstrumenter and ReactiveInstrumenter generate code that is wrapped around Runnables and Reactives?

**Comment by graemerocher** [comment]
Thanks for the PR

**Comment by marceloverdijk** [comment]
@luckyswede @LarsEckart did one of you maybe encounter this issue regarding the MDC propagation? https://github.com/micronaut-projects/micronaut-core/issues/2312

**Comment by RaviH** [comment]
Hi, is there a way to know which release of Micronaut would this be part of?

**Comment by puneetbehl** [comment]
@RaviH I believe it should already be part of `v1.1.0`as per the milestone.

**Comment by johncurrier** [comment]
@graemerocher is there documentation / hints on how we would take advantage of @luckyswede 's MdcInstrumenter to make the caller's MDC available in a method annotated with @Async? The infrastructure around it seems to be @Internal / @Experimental.

Edit: I finally discovered that adding the following to my build.gradle enabled propagation of the AWS Context's parameters via MDC. It looks like it's done under the covers by DefaultDiagnosticInfoPopulator.

`implementation "io.micronaut:micronaut-tracing"`
