### ISSUE TITLE
NoSuchBeanException: No bean of type [io.netty.bootstrap.ServerBootstrap] exists

### ISSUE THREAD

**Issue by transhkoot** [micronaut-projects/micronaut-core#10500]
### Issue description

My Micronaut app is using netty "ServerBootstrap" to build a network . But it seems not working.
I have tried many solution but failed. I'm not sure why app can't inject  ServerBoost.
I have looked into many problems like this on stackoverflow but none of the solution worked for me.

`@Singleton
class TcpServer(
    @Bean
    private val bootstrap: ServerBootstrap,
    private val eventPublisher: ApplicationEventPublisher<ServerReadyEvent>
) : ApplicationEventListener<StartupEvent> {
    companion object {
        private val log: Logger = LoggerFactory.getLogger(TcpServer::class.java)
    }

    override fun onApplicationEvent(event: StartupEvent) {
        try {
            val channelFuture = bootstrap.bind(properties.port!!).sync()
        } catch (e: InterruptedException) {
            log.error("Failed", e)
        }
    }

}`

Exception: 
`
 Failed to inject value for parameter [bootstrap] of class: com.example.server.TcpServer
Message: No bean of type [io.netty.bootstrap.ServerBootstrap] exists. 
`

Gradle:
`plugins {
    id("org.jetbrains.kotlin.jvm") version "1.9.22"
    id("org.jetbrains.kotlin.plugin.allopen") version "1.9.22"
    id("org.jetbrains.kotlin.plugin.jpa") version "1.9.22"
    id("com.google.devtools.ksp") version "1.9.22-1.0.17"
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("io.micronaut.application") version "4.3.2"
    id("io.micronaut.test-resources") version "4.3.2"
    id("io.micronaut.aot") version "4.3.2"
    //id("io.micronaut.library") version "4.3.2"
   }
val kotlinVersion= project.properties["kotlinVersion"]
repositories {
    mavenCentral()
    }
    ksp("io.micronaut.data:micronaut-data-processor")
    ksp("io.micronaut:micronaut-http-validation")
    ksp("io.micronaut.validation:micronaut-validation-processor")

    implementation("io.micronaut:micronaut-jackson-databind")
    implementation("io.micronaut.data:micronaut-data-hibernate-jpa")
    implementation("io.micronaut.kotlin:micronaut-kotlin-runtime")
    implementation("io.micronaut.sql:micronaut-jdbc-hikari")
    implementation("io.micronaut.validation:micronaut-validation")
    implementation("jakarta.validation:jakarta.validation-api")
    implementation("org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}")
    compileOnly("io.micronaut:micronaut-http-client")
    runtimeOnly("ch.qos.logback:logback-classic")
    runtimeOnly("com.fasterxml.jackson.module:jackson-module-kotlin")
    runtimeOnly("org.postgresql:postgresql")
    testImplementation("io.micronaut:micronaut-http-client")
    implementation("commons-net:commons-net:3.9.0")
    implementation("org.apache.commons:commons-lang3:3.7")
    implementation("com.github.oshi:oshi-core:3.5.0")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    runtimeOnly("org.yaml:snakeyaml")
`

**Comment by yawkat** [comment]
ServerBootstrap is not a bean micronaut provides. you have to create it yourself.
