### ISSUE TITLE
Micronaut not able to route the incoming request when having multiple methods with same path

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#1052]
I'm getting `More than 1 route matched the incoming request.` when having a controller with different methods.

For example:

```
@Post(produces = APPLICATION_JSON_UTF8)
public HttpResponse post(
            @QueryValue("query") String query,
            @Nullable @QueryValue("operationName") String operationName,
            @Nullable @QueryValue("variables") String variables) { .. }

@Post(consumes = APPLICATION_JSON, produces = APPLICATION_JSON_UTF8)
public HttpResponse post(@Body GraphQLRequestBody body) { .. }

@Post(consumes = APPLICATION_GRAPHQL, produces = APPLICATION_JSON_UTF8)
public HttpResponse post(@Body String query) { .. }
```

When having a client like:

```
    @Client("/graphql")
    static interface GraphQLClient {

        @Post(consumes = APPLICATION_JSON)
        HttpResponse<Map> post(@Body GraphQLRequestBody body)
    }
```

When invoking the `post` method I get the following error:

io.micronaut.http.client.exceptions.HttpClientResponseException: More than 1 route matched the incoming request. The following routes matched /graphql: POST - /graphql, POST - /graphql

Based on the `consumes` and e.g. required query values Micronaut would be able to differentiate the requests to the appropriate controller method.

For now I think I will have to create a single `post` method supporting the 3 variants I have to implement.

**Comment by marceloverdijk** [comment]
Thanks for adding this to `1.0.3` milestone, very useful for the GraphQL integration.

**Comment by marceloverdijk** [comment]
Note this is not needed for the GraphQL integration, I took another approach.

**Comment by marceloverdijk** [comment]
I tested these changes in the `micronaut-graphql` but it did not work yet as (I) expected.

I created a separate branch `micronaut-1052` to show what I tried to do.
[Here](https://github.com/micronaut-projects/micronaut-graphql/blob/micronaut-1052/graphql/src/main/java/io/micronaut/graphql/GraphQLController.java#L90-L136) are the 3 post methods I have and when I run the tests they fail with: `The following routes matched /graphql/: POST - /graphql, POST - /graphql, POST - /graphql`

Maybe I'm doing something wrong?

**Comment by jameskleeh** [comment]
@marceloverdijk Looks like there was an issue with the dependency as it was failing for me at first even with application/graphql. After getting that resolved it is still having issues for a couple reasons.

The first post method is not specifying a consumes type and thus all types match. When a json request is issued it matches both routes. This use case is not described in https://graphql.org/learn/serving-over-http/ and is in general an anti-pattern to accept a POST request with no body. The method should probably just be removed.

**Comment by marceloverdijk** [comment]
Yes, it is likely because of the first method.

I also understand it is in general not a best practice to accept a POST request without a body.

But note this **is** valid use case as specified in the https://graphql.org/learn/serving-over-http/ recommendations, similar as the `application/graphql` use case.

> In addition to the above, we recommend supporting two additional cases:
> 
> * If the "query" query string parameter is present (as in the GET example above), it should be parsed and handled in the same way as the HTTP GET case.
> * If the "application/graphql" Content-Type header is present, treat the HTTP POST body contents as the GraphQL query string.

See the first bullet.

Maybe Micronaut should not support this, then I will keep it in a single post method.
But I think we should support it as it is described as recommendation. What do you think?
