### ISSUE TITLE
Document how to configure a JsonFactory

### ISSUE THREAD

**Issue by hberrayana** [micronaut-projects/micronaut-core#1059]
When performing a pen test using Owasp ZAP, I have a Body Object that contains an enum. In case of unsuccessful enum parsin, an error message is returned. In general error messages needs to be html escaped.
Below an example:
`{"_links":{"self":{"href":"/invoke/configuration/roles","templated":false}},"message":"Failed to convert argument [invokeRequest] for value [null] due to: Cannot deserialize value of type ``io.micronaut.http.HttpMethod`` from String \"<script>alert(1);</script>\": value not one of declared Enum instance names: [HEAD, TRACE, GET, PATCH, CONNECT, DELETE, OPTIONS, PUT, POST]\n at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.x.x.http.resources.InvokeRequest[\"method\"])","path":"/invokeRequest"}`

**Comment by graemerocher** [comment]
I don't think that this should be the default behaviour as it isn't in most other frameworks.

Something like https://github.com/rwinch/spring-jackson-owasp could be built which configures Jackson the way you want it to be configured.

**Comment by graemerocher** [comment]
Related http://www.cowtowncoder.com/blog/archives/2012/08/entry_476.html

**Comment by hberrayana** [comment]
I've seen how this could be handled in spring-boot. How do you imagine it for Micronaut? I haven't checked the sources yet. Does it require the creation of a new ObjectMapperFactory that depends on a configuration or it's more complicated?
