### ISSUE TITLE
How to run micronaut service on port provided using commandline

### ISSUE THREAD

**Issue by ramgopalcheedu** [micronaut-projects/micronaut-core#1061]
How to override port using jvm arg to run micronaut service. Tried below not working, Can you please assist how we can override values in application.yml with jvm args

java -jar target/jsonprettyfy-0.1.jar -Dmicronaut.server.port=8070

**Comment by ilopmar** [comment]
You have a couple of options:
```
$ java -Dmicronaut.server.port=7070 -jar foo-0.1-all.jar
```
or
```
$ MICRONAUT_SERVER_PORT=7070 java -jar foo-0.1-all.jar
```

**Comment by ramgopalcheedu** [comment]
Thanks

**Comment by bric3** [comment]
Does that mean that native cannot change that ? i.e. these options have to be passed at native build time.?
