### ISSUE TITLE
Kotlin: Using withContext when throwing an error is being absorbed and the route return is like 200 instead of 500

### ISSUE THREAD

**Issue by thalesdev** [micronaut-projects/micronaut-core#10618]
### Expected Behavior

It is expected that when an exception is thrown, it will be propagated until it reaches the application's global error handler, which returns a response with status `500`.

### Actual Behaviour

Since version `4.3.0`, it is returning `200` with the content `"COROUTINE_SUSPENDED"`, errors do not appear even after placing the trace profile in the _logback_. This only happens when the function returns Unit. When you change to another return _type_ for example `string`, `int` or use same `coroutine context`, works as expected.

### Steps To Reproduce

Example of Controller:

```kotlin
import io.micronaut.http.MediaType.APPLICATION_JSON
import io.micronaut.http.annotation.Body
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Post


data class TestDTO(
    val body: String
)

@Controller("/test")
class TestController(
    private val serviceTest: ServiceTest
) {
    @Post("/", produces = [APPLICATION_JSON])
    suspend fun test(
        @Body bodyDTO: TestDTO
    ) {
         serviceTest.test(bodyDTO.body)
    }
}
```

Example of service used:
```kotlin
import jakarta.inject.Singleton
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

@Singleton
class ServiceTest {
    suspend fun test(body: String) {
        withContext(Dispatchers.IO) {
                throw RuntimeException("ServiceTest.test: $body")
        }
    }
}
```

and to get this answer just run curl:

```shell
curl -X 'POST' "http://localhost:8080/test" --data-raw '{"body": "test"}' --header 'Content-Type: application/json'
```

### Environment Information

Operating System: Mac OS 14.3.1
JDK: 17.0.7-tem

### Example Application

https://github.com/thalesdev/micronaut-coroutine-unit

### Version

4.3.4

**Comment by yawkat** [comment]
Thanks for the report!
