### ISSUE TITLE
micronaut-bom jar package not kept up-to-date?

### ISSUE THREAD

**Issue by aozmen121** [micronaut-projects/micronaut-core#10649]
### Issue description

Are you still maintaining the micronaut-bom (bill-of-materials) package? Will there be an update to use the 4.x versions of micronaut-data-bom, micronaut-core etc. The latest version is still pointing at the older 3.x versions of micronaut-data-bom, which has some missing micronaut-data related entity json serializer fixes. We could explicitly override the dependency, but this could lead to incompatibility issues, against other dependencies.

**Comment by aozmen121** [comment]
@dstepanov Would you be able to assist pls?

**Comment by auke-** [comment]
The Micronaut bill of materials has moved since Micronaut 4, see https://micronaut.io/2023/05/09/upgrade-to-micronaut-framework-4-0-0/, https://micronaut-projects.github.io/micronaut-platform/snapshot/guide/ and https://mvnrepository.com/artifact/io.micronaut.platform/micronaut-platform
