### ISSUE TITLE
MapFormat.MapTransformation.FLAT not working for @EachProperty in kotlin

### ISSUE THREAD

**Issue by skorikovdm** [micronaut-projects/micronaut-core#1064]
There is always nested map injected on Map property in @EachProperty annotated class in Kotlin

```
@EachProperty("bean")
class BeanConfiguration(@Parameter val name: String) {

    @MapFormat(transformation = MapFormat.MapTransformation.FLAT)
    var properties: Map<String, Any>? = null

    override fun toString(): String {
        return "${super.toString()} [name=$name, properties=$properties]"
    }
}
```
toString() prints:
```
[org.test.BeanConfiguration@218123a8 [name=test, properties={xxx={yyy={zzz3=3, zzz2=2, zzz1=1}, zzz=xxxzzz}}]]
```
Expected:
```
[org.test.BeanConfiguration@218123a8 [name=test, properties={xxx.yyy.zzz3=3, xxx.yyy.zzz2=2, xxx.yyy.zzz1=1, xxx.zzz=xxxzzz}]]
```
In Groovy it's working as expected

### Environment Information

- **Operating System**: Linux Mint 18
- **Micronaut Version:** 1.0.2
- **JDK Version:** 1.8

### Example Application

https://github.com/skorikovdm/kt-mapproperty

**Comment by jameskleeh** [comment]
You aren't applying the annotation correctly. That is a kotlin property and just applying the annotation isn't enough. You have to tell Kotlin where the annotation should be applied. See https://kotlinlang.org/docs/reference/annotations.html#annotation-use-site-targets

The correct usage for this case is `@setparam:MapFormat(transformation = MapFormat.MapTransformation.FLAT)`

**Comment by jameskleeh** [comment]
@graemerocher 

> If you don't specify a use-site target, the target is chosen according to the @Target annotation of the annotation being used. If there are multiple applicable targets, the first applicable target from the following list is used:
param;
property;
field.

There is no target on the `MapFormat` annotation. Perhaps we should add that?

**Comment by jameskleeh** [comment]
It appears that Kotlin only looks at the Kotlin target annotation, so this can't be fixed easily

**Comment by graemerocher** [comment]
I'm going to leave this open until we have the multi language docs in place that shows how to do this with Kotlin

**Comment by alediaferia** [comment]
The docs don't seem to have been updated for Kotlin.
