### ISSUE TITLE
File upload is limited to 1GB when using  MultipartBody

### ISSUE THREAD

**Issue by loicmathieu** [micronaut-projects/micronaut-core#10666]
### Expected Behavior

We ca upload files of anysize when using [MultipartBody](https://docs.micronaut.io/4.3.12/api/io/micronaut/http/server/multipart/MultipartBody.html)

### Actual Behaviour

I have an endpoint that can handle multipart request with multiple parts of unknown names, some are files, some are not.
The only way to deal with such endpoint is to bind the body to `@Body MultiparBody body` then doing something like that:

```java
Flux.from(body)
            .subscribeOn(Schedulers.boundedElastic())
            .map(part -> {
                if (part instanceof CompletedFileUpload fileUpload) {
                    File tempFile = File.createTempFile(fileUpload.getFilename() + "_", ".upl");
                    try (var inputStream = fileUpload.getInputStream();
                        var outputStream = new FileOutputStream(tempFile)) {
                        long transferredBytes = inputStream.transferTo(outputStream);
                        System.out.println(fileUpload.getSize()); // 1681355024 => 1.7GB: OK
                        System.out.println(transferredBytes); // 1073708906 => 1GB !!!
                    }
                    return new AbstractMap.SimpleEntry<>(
                        fileUpload.getFilename(),
                        tempFile.getName()
                    );

                } else {
                    return new AbstractMap.SimpleEntry<>(
                        input.getName(),
                        new String(input.getBytes())
                    );
                }
            })
            .collectMap(AbstractMap.SimpleEntry::getKey, AbstractMap.SimpleEntry::getValue)
            .block();
```

However, when I create the file, it only store 1GB whereas my file in the part is approx 1.7GB.
When I call `fileUpload.getSize()` it correctly reports the correct file size (1.7GB in my case) but the generated file is only 1GB long, in fact it seems to be the underlying InputStream that limit to 1BG.

### Version

4.3.4

**Comment by yawkat** [comment]
probably a bug in MicronautHttpData

**Comment by loicmathieu** [comment]
I have a reproducer, it happens only with `micronaut.server.multipart.disk=true` or `micronaut.server.multipart.mixed=true`, with the default it works but the request is very slow to answer (multiple minutes whereas it took a few seconds with disk or mixed).

This is the reproducer project: 
[issue-multipart-body.zip](https://github.com/micronaut-projects/micronaut-core/files/15132424/issue-multipart-body.zip)

It can be reproduced using the following cURL:
```
curl -XPOST -F "files=@1536m.txt;filename=file1" -F "string1=value1" http://localhost:8080/upload/file1
```

**Comment by loicmathieu** [comment]
Just checked Micronaut Platform 4.4.1 and the issue still exists.

**Comment by yawkat** [comment]
Thanks for the report!
