### ISSUE TITLE
Support for Protobuff Content Type

### ISSUE THREAD

**Issue by luistrigueiros** [micronaut-projects/micronaut-core#1066]
I would like to ask for a new feature, support for Google/Protocol-Buffer as a Content-Type in the HTTP headers.
I am aware of the issue #615 but I not requesting for grpc I would just like to be able to send and receive content encoded using protocol buffers is a similar way as it is supported in Spring by the:

- https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/converter/protobuf/ProtobufHttpMessageConverter.html
- https://www.baeldung.com/spring-rest-api-with-protocol-buffers

I have the initials of a Protocol-Buffer media codec that I would like to contribute as a starter, but to fully support what is mention above I belive I still need to write a custome type converter.

`
import com.google.protobuf.ExtensionRegistry
import com.google.protobuf.Message
import io.micronaut.core.io.buffer.ByteBuffer
import io.micronaut.core.io.buffer.ByteBufferFactory
import io.micronaut.core.type.Argument
import io.micronaut.http.MediaType
import io.micronaut.http.codec.MediaTypeCodec
import java.io.InputStream
import java.io.OutputStream
import java.lang.reflect.Method
import java.nio.charset.Charset
import java.util.concurrent.ConcurrentHashMap
import javax.inject.Singleton

@Singleton
class ProtoBufferMessageCode : MediaTypeCodec {
    companion object {
        val PROTOBUF = MediaType("application/x-protobuf", "proto")
        val DEFAULT_CHARSET = Charset.forName("UTF-8")
        private val methodCache = ConcurrentHashMap<Class<*>, Method>()
    }

    private val extensionRegistry = ExtensionRegistry.newInstance()

    private fun flagError() {
        require(false) { "The input obj is not of type Message" }
    }

    override fun supportsType(type: Class<*>): Boolean {
        return Message::class.java.isAssignableFrom(type)
    }

    override fun getMediaTypes(): MutableCollection<MediaType> = mutableListOf(PROTOBUF)

    override fun <T : Any> encode(obj: T, outputStream: OutputStream) {
        if (obj is Message) {
            outputStream.write(obj.toByteArray())
        } else {
            flagError()
        }
    }

    override fun <T : Any> encode(obj: T): ByteArray {
        return if (obj is Message) {
            obj.toByteArray()
        }else {
            flagError()
            ByteArray(1)
        }
    }

    override fun <T : Any> encode(obj: T, allocator: ByteBufferFactory<*, *>): ByteBuffer<*> {
        return allocator.copiedBuffer(encode(obj))

    }

    override fun <T : Any> decode(type: Argument<T>, inputStream: InputStream): T {
        val builder = getMessageBuilder(type.type as Class<Message>)
        if (type.hasTypeVariables()) {
            TODO("Not implemented yet")
        } else {
            builder.mergeFrom(inputStream, this.extensionRegistry)
        }
        return builder.build() as T
    }

    /**
     * Create a new `Message.Builder` instance for the given class.
     *
     * This method uses a ConcurrentHashMap for caching method lookups.
     */
    @Throws(Exception::class)
    private fun getMessageBuilder(clazz: Class<out Message>): Message.Builder {
        var method: Method? = methodCache[clazz]
        if (method == null) {
            method = clazz.getMethod("newBuilder")
            methodCache[clazz] = method!!
        }
        return method.invoke(clazz) as Message.Builder
    }
}`

**Comment by graemerocher** [comment]
PRs are welcome. Note that if you do do a PR it will need to be in Java.

**Comment by graemerocher** [comment]
You probably need to implement a `HttpContentSubscriberFactory`. See `JsonHttpContentSubscriberFactory` and `JsonContentProcessor` for an example

If Protobuffer doesn't support streaming and only parsing the whole request you want to accumulate all the bytes of the request and then parse the resulting byte[]

**Comment by luistrigueiros** [comment]
Thank you Graeme,

I am current use case I only need to parse parse the single binary encoded
request and return a response not using stream at the moment yet.

**Comment by luistrigueiros** [comment]
Hi @graemerocher 

I belive that part of the problem, not sure if this is an bug is that the DefaultUriRoute has accepted  content type hardcoded to json.

- [Debug-Session](https://ibb.co/v4TSrWb)
`        /**
         * @param httpMethod The HTTP method
         * @param uriTemplate The URI Template as a {@link CharSequence}
         * @param targetMethod The target method execution handle
         */
        DefaultUriRoute(HttpMethod httpMethod, CharSequence uriTemplate, MethodExecutionHandle targetMethod) {
            this(httpMethod, uriTemplate, MediaType.APPLICATION_JSON_TYPE, targetMethod);
        }
`
- [Debug-Session](https://ibb.co/v4TSrWb)

**Comment by graemerocher** [comment]
The controller defines that it produces protobuf but not that it consumes it, hence it defaults to accepting JSON

**Comment by luistrigueiros** [comment]
Hi @graemerocher initially this was the case but I have this changed but at the moment I am not getting the COSUMES content to be taken in account.

Thank you, kindly
  Oscar

**Comment by graemerocher** [comment]
why do you have `produces` defined on `@Post` and then later consumes defined in `@Consumes`? Just use:

```
@Post(value = "/nearby", produces = ProtobufferCodec.PROTOBUFFER_ENCODED, consumes =ProtobufferCodec.PROTOBUFFER_ENCODED )
```

or event better:

```
@Post(value = "/nearby", processes = ProtobufferCodec.PROTOBUFFER_ENCODED)
```

**Comment by luistrigueiros** [comment]
Hi @graemerocher,  It is supposed to be done by the : 

[ProtobufferCodec.java](https://github.com/luistrigueiros/micronaut-protobuff-extensions/blob/master/src/main/java/io/micronaut/http/codec/ProtobufferCodec.java)

But is is not getting yet to this point because I see that in the: **_io.micronaut.web.router.AbstractRouteMatch#accept_** that the acceptedMediaTypes have somehow been changed & defaulted to application/json .

I believe it is loosing the content type originally give in the controller class.

Thank you, kindly
  Oscar

**Comment by luistrigueiros** [comment]
[Post test now is passing](https://ibb.co/D16XxF6)

**Comment by graemerocher** [comment]
The reason for this is your HTTP client usage which does:

```
        Request.Get(url)
                .addHeader(HttpHeaders.CONTENT_TYPE, ProtobufferCodec.PROTOBUFFER_ENCODED)
...
```

If I comment out the first line:

```java
        Request.Get(url)
//                .addHeader(HttpHeaders.CONTENT_TYPE, ProtobufferCodec.PROTOBUFFER_ENCODED)
...
```

The tests pass. 

The `Content-Type` header makes no sense when sending `GET` requests since `GET` requests don't support a body and the `Content-Type` header relates to the body. One could maybe argue that Micronaut should not reject the request even if it is invalid, but the bug is currently in the client code.

**Comment by luistrigueiros** [comment]
Thank you @graemerocher :+1:   for the help, I learn something today, I was always under the impression that I should send the content-type even in a get request, but you are right it does not makes sense since it applies to the body payload.

Would you include the [ProtobufferCodec.java](https://github.com/luistrigueiros/micronaut-protobuff-extensions/blob/master/src/main/java/io/micronaut/http/codec/ProtobufferCodec.java) and converts I have written in the official, micronaut code ?

Kindly
  Luis Oscar Trigueiros

**Comment by graemerocher** [comment]
Sure, feel free to send a PR

**Comment by luistrigueiros** [comment]
Can I do this in the micronaut-core ?
This requires adding dependencies to protocol-buffers and even changing the
build to include sample protocol buffer generation to that I can sample
tests.

Kind regards, Luis Oscar

**Comment by graemerocher** [comment]
An alternative is to send a PR to https://github.com/micronaut-projects/micronaut-grpc since this is related

**Comment by luistrigueiros** [comment]
Ok can it be a new sub-module as I think what it is related but one could
what to use it whiteout the gprc, maybe named something like
protobuf-support ?

**Comment by luistrigueiros** [comment]
Hi @graemerocher I think we can close this issue now with the creation of the new module in micronaut-grpc.

Kindly
 Oscar

**Comment by luistrigueiros** [comment]
Hi @graemerocher 
I would like to to a small tutorial about using this featue I am guessing the process is to clone the https://github.com/micronaut-projects/micronaut-guides ?

Kind regards, 
  Luis Oscar

**Comment by sandeep14-singh** [comment]
Hi @graemerocher ,
Is this feature merged and available ?

**Comment by luistrigueiros** [comment]
@sandeep14-singh yes this is available and documented in the module documentation
