### ISSUE TITLE
Inability to inject `Collection<Provider<MyInterface>>`

### ISSUE THREAD

**Issue by RonBarkan** [micronaut-projects/micronaut-core#10679]
### Expected Behavior

Micronaut supports injecting a `Provider<MyInterface>`, a `Collection<MyInterface>`, but not a `Collection<Provider<MyInterface>>` / `Collection<BeanProvider<MyInterface>>`.

Now, a provider might be used to get a new instance for every `get()` call, or for circular dependency.
However, another use case is for incompatible scope. Say `MyInterface` is on a Request Scope but the object it gets injected to is a singleton, where the `get()` call will happen in a request scope, but the constructor is not (some DI frameworks will not even allow you to inject incompatible scopes, something you should look into).
If the only requirement is to get a fresh new instance when calling `get()`, that is not possible when a singleton gets a set of objects that immediately become stale.

### Actual Behaviour

Injection exceptions, see below.

### Steps To Reproduce

```
  @Inject
  public MyFactory(List<BeanProvider<MyListener>> listeners) {
    this.listeners = Collections.unmodifiableList(listeners);
    System.out.println("### MyFactory:");
    for (var p : listeners) {
      System.out.println("### Listener: " + p.isResolvable());
      try {
        p.get();  // No exception unless get() is called
      } catch (Throwable e) {
        System.out.println(e);
      }
    }
  }

### MyFactory:
### Listener: true    <=== this looks like another bug
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [<a different class that injects MyFactory>]

Message: Cannot inject provider for Object type
Path Taken: <the injector param that failed in square brackets>
```

Note that the error message `Cannot inject provider for Object type` is not helpful at all.
I am not sure why it does not complain about either `MyFactory` explicitly or its constructor argument.

### Environment Information

Ubuntu / Microsoft WSL2
JDK 21

### Version

3.10.1

**Comment by graemerocher** [comment]
this isn't a problem in Micronaut 4 which has `BeanProvider<MyInterface>` which has methods to retrieve one or more instances
