### ISSUE TITLE
add .zip / .png / .jpg to io.micronaut.http.MediaType

### ISSUE THREAD

**Issue by PeterFokkinga** [micronaut-projects/micronaut-core#10673]
### Feature description

The io.micronaut.http.MediaType utility class is incredibly convenient for sending stuff to the browser with the proper content type and I would like to see three more very common types supported:

- application/zip 
- image/jpeg
- image/png

Now, I realise this may be the signal for the floodgates to open, but I think it can be argued that these are very generic and MediaType already has some more specific (but also very practical) ones like .xlsx

**Comment by sdelamo** [comment]
@PeterFokkinga would you be willing to contribute a PR?

**Comment by PeterFokkinga** [comment]
@sdelamo see PR #10747
