### ISSUE TITLE
Mybatis integration with mybatis

### ISSUE THREAD

**Issue by developer-sunnywu** [micronaut-projects/micronaut-core#10686]
### Feature description

https://guides.micronaut.io/latest/micronaut-data-access-mybatis-maven-java.html

In the example of official miconaut website, it uses sqlSessionFactory in the Impl class, and then we inject the Impl class afterward.

My question is that can we inject the inteface class directly without create additional Impl class using SqlSessionFactory? Just like in springboot, we can do mapper scan, and the mybatis mapper interface is registered in the spring context. Thank you

I have search for the info, but seems like there is not much answer to that.

**Comment by sdelamo** [comment]
We don't have any specific integration for MyBatis.  If you are interested please up-vote, this https://github.com/micronaut-projects/micronaut-sql/issues/815
