### ISSUE TITLE
Declarative HTTP client methods with primitive return types fail after upgrading to Micronaut 4

### ISSUE THREAD

**Issue by kevin-wise** [micronaut-projects/micronaut-core#10698]
### Expected Behavior

Primitives should be allowed as return types from client methods

### Actual Behaviour

io.micronaut.http.client.exceptions.HttpClientResponseException: Client 'xxxxx': Failed to decode the body for the given content type [application/json]
	at io.micronaut.http.client.netty.DefaultHttpClient$1.retrieve(DefaultHttpClient.java:585)

### Steps To Reproduce

1. create a project that does not have micronaut-http-server-netty as a dependency
2. create a declarative HTTP client containing a method returning a primitive type, for example `boolean`
3. use the client to call an endpoint. The response comes back and fails 

It's failing  because io.micronaut.http.body.DefaultMessageBodyHandlerRegistry#findReaderImpl looks for beans which implement `MessageBodyReader<boolean>` which of course is impossible.

A similar problem appears to be happening with request bodies that are primitives. In this case the error is 400 Bad Request instead of the exception above.

### Environment Information

- environment doesn't seem to matter
- happens with Micronaut 4+; worked fine in Micronaut 3

### Example Application

```java
@Client(id = "test")
public interface ExampleClient {

  @Get("/api/users/{userId}/tenants/{tenantId}/access")
  boolean hasTenantAccess(@PathVariable String userId, @PathVariable String tenantId);
}
```

### Version

4.3.7

**Comment by kevin-wise** [comment]
Note this only happens if `micronaut-http-server-netty` is not loaded, since NettyConverters has a fallback conversion for ByteBuf to Object using toString().  I think it would be better to use the MessageBodyReader rather than a fallback TypeConverter though, even if Netter server is available.

**Comment by sdelamo** [comment]
closed via https://github.com/micronaut-projects/micronaut-core/commit/26420186a21fd5ae7458d79a19f4cda5acc7fd17
