### ISSUE TITLE
No bean of type exists when importing beans from external libs

### ISSUE THREAD

**Issue by stanleyw2014** [micronaut-projects/micronaut-core#10719]
### Expected Behavior

beans should be found

### Actual Behaviour

the beans defined in 3rd party library can't be found

### Steps To Reproduce

1 build a jar with micronaut 4.2.1, including some beans with annotation @Repository
2 create a new project with micronaut 4.3.1, introduced the jar build in step 1 as dependency, inject some beans from the jar into rest controller in the new project
3 the project can be complied successfully and started normally, but when calling the rest api defined in controller, it will camplain that the beans from the library defined in step 1 can't be found.

### Environment Information

MacOS 13.6.6
JDK 17

### Version

4.3.1

**Comment by alvarosanchez** [comment]
Is the library compiled with the Micronaut annotation processors?

**Comment by stanleyw2014** [comment]
below is the dependencies included in the library
dependencies {
    annotationProcessor("io.micronaut:micronaut-http-validation")
    annotationProcessor("io.micronaut:micronaut-inject-java")
    implementation("io.micronaut.discovery:micronaut-discovery-client")
    implementation("io.micronaut.cache:micronaut-cache-caffeine")
    
    compileOnly("io.micronaut:micronaut-http-client")
    runtimeOnly("ch.qos.logback:logback-classic")
    testImplementation("io.micronaut:micronaut-http-client")
}

**Comment by stanleyw2014** [comment]
should I add annotationProcessor "io.micronaut:micronaut-inject-java:4.x.x" in the build.gradle of the library?
