### ISSUE TITLE
MN:4.4.0 - Changed behavior for @JsonGetter in @Introspected-annotated classes

### ISSUE THREAD

**Issue by roar-skinderviken** [micronaut-projects/micronaut-core#10737]
### Expected Behavior

With the example application and MN:4.4.0, I expect this JSON as output from the controller.
```
{"afterCare":[{"klassifisering":{"regionKode":"01"},"stats":{"SomeField1":0,"SomeField2":0}}]}
```

### Actual Behaviour

This is a simplistic reconstruction of what happened: 
```
{"afterCare":[{"klassifisering":{"regionKode":"01"},"stats":{"SomeField1":0,"SomeField2":0}}]}
```
changed to
```
{"afterCare":[{"klassifisering":{"regionKode":"01"},"stats":{"shouldNotAppearInJson":{"SomeField1":0,"SomeField2":0}}}]}
```
with MN:4.4.0.

### Steps To Reproduce

1. In the example application, switch to MN:4.4.0 in gradle.properties.
2. Start the application with `./gradlew clean run`
3. Open http://localhost:8080/get-aggregation

Observe that JSON has changed to
```
{"afterCare":[{"klassifisering":{"regionKode":"01"},"stats":{"shouldNotAppearInJson":{"SomeField1":0,"SomeField2":0}}}]}
```

Please note that removing `@Introspected` fixes the issue.

### Environment Information

JDK 21
Kotlin 1.9.23
Ubuntu 22.04

### Example Application

https://github.com/roar-skinderviken/MN-4.4-jackson-issue

### Version

4.4.0

**Comment by timyates** [comment]
@dstepanov Any ideas?

**Comment by dstepanov** [comment]
It's probably some KSP stuff. I have added similar test to Micronaut Serialization and fixed some bug https://github.com/micronaut-projects/micronaut-serialization/pull/826

**Comment by dstepanov** [comment]
Looks like the annotation is not retained in the property annotations

**Comment by roar-skinderviken** [comment]
Seems like you're right about KSP @dstepanov. When replacing it with `kotlin("kapt") version "1.9.23"`, returned JSON is as expected.

**Comment by timyates** [comment]
It might be us, as changing the field name in the reproducer to be different to the JsonGetter name seems to work

```diff
diff --git a/gradle.properties b/gradle.properties
index ab4cf7a..c3fd1bb 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -1,3 +1,3 @@
-micronautVersion=4.3.8
+micronautVersion=4.4.0
 kotlinVersion=1.9.23
 org.gradle.jvmargs=-Xmx4096M
diff --git a/src/main/kotlin/no/javatec/viewmodel/ClassificationAndStats.kt b/src/main/kotlin/no/javatec/viewmodel/ClassificationAndStats.kt
index 3972f0b..3ecf94a 100644
--- a/src/main/kotlin/no/javatec/viewmodel/ClassificationAndStats.kt
+++ b/src/main/kotlin/no/javatec/viewmodel/ClassificationAndStats.kt
@@ -9,8 +9,8 @@ data class ClassificationAndStats<out T : StatsEntry>(
     val klassifisering: ClassificationVars,
     /** Ignore field to avoid double wrapping of values in resulting JSON */
     @JsonIgnore
-    val stats: T
+    val spats: T
 ) {
     @JsonGetter("stats")
-    fun getValues(): Map<Aggregation, Int> = stats.shouldNotAppearInJson
+    fun getValues(): Map<Aggregation, Int> = spats.shouldNotAppearInJson
 }
```

**Comment by roar-skinderviken** [comment]
Working now with MN:4.4.1 :+1:
