### ISSUE TITLE
Allow attribute definition via declarative http client 

### ISSUE THREAD

**Issue by ahmedlafta** [micronaut-projects/micronaut-core#1074]
It would be nice to be able to define a parameter in a declarative http client as a custom attribute, just like headers or cookies. See the following example:

```
@Client("/pets")
public interface PetClient {

    @Get("/{name}")
    Single<Pet> get(@Attribute(name="X-Pet-Client") String name);
}
```
This would allow for an http client filter to access the metadata and use it as necessary (like logging).

```
public class ClientLogger implements HttpClientFilter {
    @Override
    public Publisher<? extends HttpResponse<?>> doFilter(MutableHttpRequest<?> request, ClientFilterChain chain) {
        Optional<String> name = request.getAttributes()
                .get("X-Pet-Client", String.class);
        return Flowable.fromPublisher(chain.proceed(request))
                .doOnNext(response -> {
                    // TODO log request data and response for indexing
                });
    }
}
```

Alternatively the `@Attribute` annotation could be defined at the class level as well, just like `@Header`.

The goal is to continue to use declarative clients while also customizing the attributes that are intended for internal data sharing. My current thought is that this will only be possible by extending the `RxHttpClient` and forcing users to use that. I could define these values as headers and remove them via a client filter before going out but that doesn't seem ideal. If there is another way this is possible with declarative clients then please let me know.

**Comment by graemerocher** [comment]
This seems like a good idea. We will get to it, otherwise PRs welcome!

**Comment by ahmedlafta** [comment]
I will be submitting a PR soon 😄

**Comment by graemerocher** [comment]
PR merged- thank you!
