### ISSUE TITLE
 even in a vanilla application - you will see this error in dependency tree (  io.micronaut:micronaut-inject-java FAILED)

### ISSUE THREAD

**Issue by CtrlAltFly** [micronaut-projects/micronaut-core#10752]
### Expected Behavior

kotlinProcessors
\--- io.micronaut:micronaut-inject-java:4.4.6 (lets say)

the mend scan is failing to run for this unresolved version 
using kapt or ksp doesn't matter. this issue will be still there.

### Actual Behaviour

kotlinProcessors
\--- io.micronaut:micronaut-inject-java FAILED

### Steps To Reproduce

create a vanilla application from micronaut starter and dont add anything.. just vanilla
unzip and open in IDE - i used intellij
run ./gradlew dependencies 
once build is success, search for inject-java in the whole tree and you should stumble on this error from gradle not finding a suitable version
[inject-check.zip](https://github.com/micronaut-projects/micronaut-core/files/15072035/inject-check.zip)

kotlinProcessors
\--- io.micronaut:micronaut-inject-java FAILED

### Environment Information

oS- macos
jdk - 17

### Version

4.3.6

**Comment by CtrlAltFly** [comment]
added my vanilla testing project showing the error. my other apps are in 4.3.4 and they are also showing same failure, so its something not started in 4.3.6 version

i would love any guidance you have to get rid of this failure too

**Comment by timyates** [comment]
Just to check, this doesn't cause any issues does it?

What do you mean by

> the mend scan is failing to run for this unresolved version

What's a mend scan?

It looks like the Gradle plugin is setting up a `kotlinProcessors` configuration here

https://github.com/micronaut-projects/micronaut-gradle-plugin/blob/2d20a5128c52aa997a36aa5d0a748f71aa6b334a/minimal-plugin/src/main/java/io/micronaut/gradle/MicronautKotlinSupport.java#L147

But I'm not sure if this is used anymore, or is just a legacy thing... @melix any idea?

Either way, it shouldn't be causing you any problems building and running a project, is it?

**Comment by CtrlAltFly** [comment]
@timyates - thank you for the PR. really appreciate you looking into this so soon 🥂 👍 

now, mend is renovate's offering (that i see you guys use too in micronaut foundation) for security scanning of packages in the projects

the project gradle build happens just fine. no issues there.

its just that, when the security scanning by renovate is happening, it doesn't like an unresolved dependency and doesn't complete the gradle file scan for any outdated packages in the build.

**Comment by timyates** [comment]
I've just released v4.3.8 of the Gradle plugin which should fix this issue (by correctly marking the `kotlinProcessor` configuration as unresolvable) 👍 

Nice spot!  And thanks for raising the issue 👍
