### ISSUE TITLE
Use gradle-versions-plugin to discover updates

### ISSUE THREAD

**Issue by ben-manes** [micronaut-projects/micronaut-core#1079]
From #889 and the issue tracker, it looks like dependencies are being monitored manually for possible version upgrades. That leads to missing upgrades and wasted time, so please instead use my plugin  (or one of the extensions) to help manage this for you.

https://github.com/ben-manes/gradle-versions-plugin

**Comment by graemerocher** [comment]
That is true although we tried to upgrade to Caffeine to 3.6.x but had to roll back due to a regression on Graal native image

**Comment by ben-manes** [comment]
Fair enough. This issue only suggests using the plugin to get a report generated for you.

**Comment by koziolk** [comment]
@graemerocher I think, I can work on it. Any suggestions on how it should be integrated?

**Comment by graemerocher** [comment]
Not sure really I have not used the plugin before

**Comment by koziolk** [comment]
Ok, seems to be straightforward.

**Comment by ben-manes** [comment]
I suggested this to encourage upgrading `Caffeine`. 😃 

You should be able to add by,
```groovy
plugins {
  id 'com.github.ben-manes.versions' version '0.21.0' 
}
```

If you want to filter out beta versions, you can specify a resolution strategy. See the plugin's readme for an example.

You can then run `gradle dependencyUpdates` and it will print a report to the console. This is similar to Maven's version report, if you were familiar with that. It queries your configured repositories using Gradle's built-in dependency resolution to determine the latest versions. If desired, you can integrate this into a CI workflow, etc. using the json report or additional plugins. Regardless the team would no longer manually hunt for version upgrades and can instead run the report periodically and upgrade if appropriate.

**Comment by koziolk** [comment]
Hi @graemerocher . I've tried to build `micronaut-core` on my local machine following the guides in "Working on the code base" section. Unfortunately, ended up with the test failure:

```
> Task :http-client:test 
................................................................lSelfSignedSpec
io.micronaut.http.client.SslStaticCertSpec > test send https request FAILED
    io.micronaut.http.client.exceptions.HttpClientException: Error occurred reading HTTP response: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

        Caused by:
        javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
............
254 tests completed, 1 failed, 1 skipped

```
My settings:

```➜  micronaut-core git:(master) ./gradlew --version                                                                                                                                                                                              
------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Mac OS X 10.14.4 x86_64
```
I did check other JDKs: Oracle 1.8.0_202 and AdoptJDK 1.8.0_202 but with the same result.
Have you faced similar issue?

**Comment by koziolk** [comment]
Hi @ben-manes and @graemerocher . PR is ready.
