### ISSUE TITLE
Unable to inject istio side car when running micronaut docker image in Kubernetes

### ISSUE THREAD

**Issue by petenorth** [micronaut-projects/micronaut-core#1081]
I am posting this as an issue because a simple Spring Boot image supports sidecar injection without any issues. 

### Steps to Reproduce

I assume that minikube has been installed 

    curl -L https://git.io/getLatestIstio | sh -
    cd istio-1.0.5
    minikube start 
    #IMPORTANT version 2.12.0 of helm doesn't work
    alias helm="docker run -ti --rm -v $(pwd):/apps:rw -v ~/.kube:/root/.kube -v ~/.minikube:$(echo ~)/.minikube alpine/helm:2.11.0"
    #is the service account needed etc. when the default minikube install doesn't have RBAC enabled?
    kubectl apply -f install/kubernetes/helm/helm-service-account.yaml
    helm init --service-account tiller

you may have to wait for the tiller pod to come up. The following is the minimal istio install

    helm install install/kubernetes/helm/istio --name istio-minimal --namespace istio-system \
      --set security.enabled=false \
      --set ingress.enabled=false \
      --set gateways.istio-ingressgateway.enabled=false \
      --set gateways.istio-egressgateway.enabled=false \
      --set galley.enabled=false \
      --set sidecarInjectorWebhook.enabled=false \
      --set mixer.enabled=false \
      --set prometheus.enabled=false \
      --set global.proxy.envoyStatsd.enabled=false \
      --set pilot.sidecar=false

    kubectl get pods -n istio-system -w

    git clone https://github.com/petenorth/micronaut-tutorial-1
    cd micronaut-tutorial-1
    alias helm="docker run -ti --rm -v $(pwd):/apps:rw -v ~/.kube:/root/.kube -v ~/.minikube:$(echo ~)/.minikube alpine/helm:2.11.0"
    helm install helm/books --name books-current --set image.tag=1.0.152
    kubectl get deployment books --export=true -o yaml > books.yaml
    ~/istio-1.0.5/bin/istioctl kube-inject -f books.yaml | kubectl apply -f -

This pod seems to initially succeed but possibly not consistently. The canary deployment

    helm install helm/books --name books-canary --set image.tag=1.0.156 --set fullnameOverride=books-canary
    kubectl get deployment books-canary --export=true -o yaml > books-canary.yaml
    ~/istio-1.0.5/bin/istioctl kube-inject -f books-canary.yaml | kubectl apply -f -

seems to consistently fail with

    kubectl logs -lapp.kubernetes.io/instance=books-canary -c books

    16:20:41.535 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments [cloud, k8s]
    16:20:43.043 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: 
    Unable to start Micronaut server on port: 8082 io.micronaut.http.server.exceptions.ServerStartupException: Unable to start Micronaut server on port: 8082
    at io.micronaut.http.server.netty.NettyHttpServer.bindServerToHost(NettyHttpServer.java:409)
    at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:303)
    at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:107) 
    at io.micronaut.runtime.Micronaut.lambda$start$1(Micronaut.java:73)
    at java.util.Optional.ifPresent(Optional.java:159)
    at io.micronaut.runtime.Micronaut.start(Micronaut.java:71)
    at io.micronaut.runtime.Micronaut.run(Micronaut.java:271)
    at io.micronaut.runtime.Micronaut.run(Micronaut.java:257)
    at example.micronaut.Application.main(Application.groovy:9)
    Caused by: java.net.BindException: Address already in use
	... 9 common frames omitted

But if I alter the docker image to one based on gs-spring-boot with actuator health endpoint added injection works (consistently)

    helm install helm/spring-test --name spring-test --set fullnameOverride=spring-test
    kubectl get pod -w
    kubectl get deployment spring-test --export=true -o yaml > spring-test.yaml
    ~/istio-1.0.5/bin/istioctl kube-inject -f spring-test.yaml | kubectl apply -f -
    kubectl get pod -w

everything works.

Is there a difference in behaviour between how netty is used in Micronaut and tomcat in Spring Boot. I looked into so_reuseaddr but couldn't see anything obvious, the netstat information (running locally as these are alpine based images) suggest the use of interfaces is the same between micronaut and spring boot tomcat.

### Expected Behaviour

Sidecar injection should work transparently as it does for the Spring Boot application.

### Actual Behaviour

The side car injection only seems to work for one pod, and then if you try a redeployment even that will fail

### Environment Information

- **Operating System:** minikube
- **Micronaut Version:** 1.0.1
- **JDK Version:** alpine java 8

### Example Application

- https://github.com/petenorth/micronaut-tutorial-1

### Alternative Non Helm install of the applications

    cd kubernetes
    kubectl apply -f deployments.yaml 
    kubectl get pod -w
    kubectl get deployment books --export=true -o yaml > books.yaml
    kubectl get deployment inventory --export=true -o yaml > inventory.yaml
    kubectl get deployment gateway --export=true -o yaml > gateway.yaml
    ~/istio-1.0.5/bin/istioctl kube-inject -f books.yaml | kubectl apply -f -
    ~/istio-1.0.5/bin/istioctl kube-inject -f inventory.yaml | kubectl apply -f -
     ~/istio-1.0.5/bin/istioctl kube-inject -f gateway.yaml | kubectl apply -f -

**Comment by graemerocher** [comment]
Ok that makes sense, thanks for the feedback. It does seem there is some other processing running on the port Micronaut wants to bind to. Could be that the init container is not shutting down correctly? Is another Micronaut app in the init container? I'm not sure you can bind to containers to the same port on the same virtual network space.

**Comment by petenorth** [comment]
After removing the check at 

https://github.com/micronaut-projects/micronaut-core/blob/69466ab5c338fcd3df1a70b259e144f2ca0f8f40/http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java#L408

Things seem (!) to work (this hasn't tested istio at all just whether the application pod can start) 

    peters-mbp:books peterfry$ kubectl get pod
    NAME                     READY     STATUS    RESTARTS   AGE
    books-5c8775bbf6-kfvrq   2/2       Running   0          5m
    
    peters-mbp:books peterfry$ kubectl logs books-5c8775bbf6-kfvrq -c books
    Active Internet connections (servers and established)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       
    Active UNIX domain sockets (servers and established)
    Proto RefCnt Flags       Type       State         I-Node Path
    Active Internet connections (only servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
    host used is books-5c8775bbf6-kfvrq/172.17.0.9
    isTcpPortAvailable = true
    15:42:07.900 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [cloud, k8s]
    15:42:11.764 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 3841ms. Server 
    Running: http://books-5c8775bbf6-kfvrq:8082

The in pod test being

    peters-mbp:books peterfry$ kubectl exec -it books-5c8775bbf6-kfvrq sh
    Defaulting container name to books.
    Use 'kubectl describe pod/books-5c8775bbf6-kfvrq -n default' to see all of the containers in this pod.
    / # curl http://localhost:8082/api/books
    [{"isbn":"1491950358","name":"Building Microservices"},{"isbn":"1680502395","name":"Release It!"}]

**Comment by graemerocher** [comment]
Interesting we can maybe make the error message configurable or simply remove that check and wait for the later binding error from Netty. Please do provide more feedback as to whether the prod is actually working however.

**Comment by graemerocher** [comment]
If you wish to verify the fix you can do so by adding the snapshot repo to `build.gradle`:

```groovy
repositories {
    ...
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

And specifying the snapshot version as your BOM:

```groovy
dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:1.0.3.BUILD-SNAPSHOT'
    }
}
```

**Comment by petenorth** [comment]
Verified that 1.0.3.BUILD-SNAPSHOT fixes the issue and can now inject Istio sidecar without any issues.

**Comment by graemerocher** [comment]
Thanks for the feedback.

**Comment by missourian55** [comment]
Thank you, my enterprise is considering Istio in existing K8s, one more reason for me to justify micronaut instead of spring
