### ISSUE TITLE
@Cacheable with Publisher does not work

### ISSUE THREAD

**Issue by rburgst** [micronaut-projects/micronaut-core#1082]
In Micronaut 1.0.2 the `@Cacheable` annotation does not work on a method that returns a `Publisher`.

Service Method:
```kotlin
@Singleton
open class HelloService {
    val logger = LoggerFactory.getLogger(this.javaClass)

    @Cacheable("num-cache")
    @SingleResult
    open fun calculateValue(num: Int): Publisher<String> {
        logger.info("Calculating value for {}", num)
        return Flowable.just("Hello $num")
    }
}
```

Cache config in `application.yml`
```yaml
micronaut:
    application:
        name: cacheable-sample
    caches:
        num-cache:
            expire-after-write: 10m
```

### Steps to Reproduce

1. run the app

    ```bash
    ./gradlew run
    ``` 
    
2. send an http request multiple times

    ```bash
    http :8080/hello
    ```
   

### Expected Behaviour

the method `HelloService.calculateValue(0)` should only be called once, which should produce the following
output:

```
20:18:07.133 [nioEventLoopGroup-1-3] INFO  c.s.$HelloServiceDefinition$Intercepted - Calculating value for 0
```

### Actual Behaviour

the method is called multiple times producing the output

```
20:17:53.374 [nioEventLoopGroup-1-2] INFO  c.s.$HelloServiceDefinition$Intercepted - Calculating value for 0
20:18:07.133 [nioEventLoopGroup-1-3] INFO  c.s.$HelloServiceDefinition$Intercepted - Calculating value for 0
20:18:17.442 [nioEventLoopGroup-1-3] DEBUG i.m.c.interceptor.CacheInterceptor - Value found in cache [num-cache] for invocation: Publisher calculateValue(int num)
20:18:20.828 [nioEventLoopGroup-1-4] INFO  c.s.$HelloServiceDefinition$Intercepted - Calculating value for 0
20:18:23.043 [nioEventLoopGroup-1-4] DEBUG i.m.c.interceptor.CacheInterceptor - Value found in cache [num-cache] for invocation: Publisher calculateValue(int num)
```

### Environment Information

- **Operating System**: Mac OSX Mojave
- **Micronaut Version:** 1.0.3
- **JDK Version:** 1.8.0_181

### Example Application

https://github.com/rburgst/cacheable-sample

**Comment by rburgst** [comment]
Please note that in my real app I am trying to cache calls to `UserFetcher` therefore, I cannot change the method signature:

```kotlin
open class UserFetcherService(private val userRepository: UserRepository) : UserFetcher {
    @Cacheable("user-cache")
    @SingleResult
    @Transactional
    open override fun findByUsername(username: String?): Publisher<UserState> {
...
```

**Comment by graemerocher** [comment]
As far as I can see this is behaving correctly. The method is invoked once to retrieve the publisher then the result of subscribing to the publisher is cached, not the publisher itself.

This behaviour can be seen in the test I committed https://github.com/micronaut-projects/micronaut-core/commit/da143f0f84d89351ae77dbf1b0dbccae2174c2c7

It doesn't really make sense to cache the publisher itself in the reactive case, so what Micronaut does is subscribe to the publisher and cache the result of the subscription as this is what is normally expensive. You can rewrite your code to return a callable which will get the behaviour you want:

ie

```groovy
       Publisher<String> calculateValue(Integer num) {
            return Flowable.fromCallable({->
                println("Calculating value for $num")
                return "Hello $n: $num".toString()
            })
        }
```

**Comment by rburgst** [comment]
this does indeed work, however, I guess the documentation/code sample in http://guides.micronaut.io/micronaut-database-authentication-provider-groovy/guide/index.html#userFetcher should be adapted as it will steer people in a wrong direction
