### ISSUE TITLE
POST Forms are limited to 128 fields with netty-codec-http dependency >= 4.1.108.Final

### ISSUE THREAD

**Issue by jamcole** [micronaut-projects/micronaut-core#10825]
### Expected Behavior

The Netty DEFAULT_MAX_FIELDS setting in HttpPostRequestDecoder should be configurable in Micronaut or set to -1 to behave as prior versions of Micronaut.

### Actual Behaviour

Netty throws a TooManyFormFieldsException if posts are made with more than 128 fields by default because of the changes merged into 4.1.108.Final related to https://github.com/advisories/GHSA-5jpm-x58v-624v 

### Steps To Reproduce

While using any version of Micronaut greater than or equal to 4.3.12

1. Create a POST form with more than 128 fields (such as a table with many checkboxes)
2. Submit form

### Version

4.3.12

**Comment by rakeshdavanum** [comment]
Hi @yawkat , @graemerocher, our applications are running on Micronaut 3.x and will take us some time to upgrade to Micronaut 4.x. Is this fix available on Micronaut 3.x? Or is there a way for us to override max fields configurations? Thanks!

**Comment by yawkat** [comment]
No, there is no fix for 3.x
