### ISSUE TITLE
Unable to set micronaut.http.client.channel-options through YML configuration

### ISSUE THREAD

**Issue by eddie-thp** [micronaut-projects/micronaut-core#10832]
### Expected Behavior

Configuration values should NOT be converted during deserialization.
e.g. `SO_KEEPALIVE: true` gets converted to `so-keepalive: true`

See: https://github.com/micronaut-projects/micronaut-core/blob/4.5.x/http-client-core/src/main/java/io/micronaut/http/client/HttpClientConfiguration.java#L393

### Actual Behaviour

When specifying settings through the YML configuration, they get converted to, and so, netty does not recognize them.

```
io.netty.bootstrap.Bootstrap             : Unknown channel option 'so-keepalive' for channel '[id: 0xc309b803]'
```

### Steps To Reproduce

1. Configure an application's http client channel option using `application.yml` file.

```
  http:
    client:
      channel-options:
        SO_KEEPALIVE: true
      pool:
        enabled: true
        max-connections: 10
```

2. Implement a client / try executing the code/client.
3. When instantiating the client, netty will complain that it does not recognize the configuration.

```
io.netty.bootstrap.Bootstrap             : Unknown channel option 'so-keepalive' for channel '[id: 0xc309b803]'
```

### Environment Information

- Operating System: `MAC OS`
- JDK: 
```
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode)
```

### Version

Micronaut-core 4.4.9

**Comment by yawkat** [comment]
Thanks for the report!
