### ISSUE TITLE
HttpClient: support Optional<T> as response type in declarative client

### ISSUE THREAD

**Issue by sschnabe** [micronaut-projects/micronaut-core#1084]
### Steps to Reproduce

1. Create an [api](https://github.com/sschnabe/micronaut-httpclient-optinal/blob/master/src/main/java/io/micronaut/issue/HelloApi.java#L13) with repsonse `Optional<T>`
2. Create declarative [client](https://github.com/sschnabe/micronaut-httpclient-optinal/blob/master/src/test/java/io/micronaut/issue/HelloClient.java#L6) based on the api
3. Create [server](https://github.com/sschnabe/micronaut-httpclient-optinal/blob/master/src/main/java/io/micronaut/issue/HelloController.java#L11) 
4. Use client for server (see [test](https://github.com/sschnabe/micronaut-httpclient-optinal/blob/master/src/test/java/io/micronaut/issue/HelloControllerTest.java#L28-L32))

### Expected Behaviour
Client returns `Optional` with value.

### Actual Behaviour
Client returns always an empty `Optional`.

### Environment Information
- **Operating System**: Ubuntu
- **Micronaut Version:** 1.0.2
- **JDK Version:** openjdk 11.0.1 2018-10-16

### Example Application
see [micronaut-httpclient-optinal](https://github.com/sschnabe/micronaut-httpclient-optinal)
The tests **declarativeWithValue** and **httpWithValue** are failing.

**Comment by romeoro** [comment]
Stumbling onto this bug because i noticed the same behavior in my application with version 1.0.3.
The sample also still fails with micronaut version 1.0.3 or 1.0.4.

**Comment by jameskleeh** [comment]
The test is failing because the parameter names are being included in the class files.

```
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<compilerArgs>
						<arg>-parameters</arg>
					</compilerArgs>
```

causes the tests to pass
