### ISSUE TITLE
Can't find micronautserviceconfigs when running as jlink-ed application

### ISSUE THREAD

**Issue by rfscholte** [micronaut-projects/micronaut-core#10842]
### Expected Behavior

Even though micronaut is not yet fully modularized, there are some steps to be taken before #6395 can be solved. This is an important one.
Root cause is the io.micronaut.core.io.service.ServiceScanner.findMicronautMetaServiceConfigs. If the classloader is coming from a ModuleLayer, non-specific resources (let's say directories) won't be found.

### Actual Behaviour

It fails with the following exception:
```
Exception in thread "main" io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists.
        at io.micronaut.di@4.4.9/io.micronaut.context.DefaultBeanContext.newNoSuchBeanException(DefaultBeanContext.java:2768)
        at io.micronaut.di@4.4.9/io.micronaut.context.DefaultApplicationContext.newNoSuchBeanException(DefaultApplicationContext.java:309)
        at io.micronaut.di@4.4.9/io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2737)
        at io.micronaut.di@4.4.9/io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1731)
        at io.micronaut.di@4.4.9/io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:837)
        at io.micronaut.di@4.4.9/io.micronaut.context.BeanLocator.getBean(BeanLocator.java:96)
        at io.micronaut.di@4.4.9/io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1817)
        at io.micronaut.di@4.4.9/io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:357)
        at io.micronaut.di@4.4.9/io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:202)
```

### Steps To Reproduce

A new ClasspathResourceLoaderSpec would probably look a bit like this (I'm struggling to get Gradle tests running), just make sure there's a jar available as test-resource with the specified modulename.

    void "test resolving a resource using ModulePath"() {
        given:
        String modulename = "core.foo.bar" 
        ModuleFinder finder = ModuleFinder.of(Path.of("build/resources/test"))
        ModuleLayer parent = ModuleLayer.boot()
        Configuration cf = parent.configuration().resolve(finder, ModuleFinder.of(), Set.of(modulename))
        ClassLoader scl = ClassLoader.getSystemClassLoader()
        ModuleLayer layer = parent.defineModulesWithOneLoader(cf, scl)
        ClassPathResourceLoader loader = new DefaultClassPathResourceLoader(layer.findLoader(modulename), base)

        expect:
        loader.getResource(resource).get().text == "bar.txt"

        where:
        base             | resource
        null             | "foo/bar.txt"
        "foo"            | "bar.txt"
        "/foo"           | "bar.txt"
    }

### Version

4.4.9

**Comment by graemerocher** [comment]
do you know of any modular jars out there that contain static resources that we could use in this test? Currently Micronaut doesn't support the module system, but maybe with the change you propose it could be possible I guess.

**Comment by rfscholte** [comment]
A bit of background: One of the requirements of the application I'm building is that is has to be built with jlink. 
It should also use a DI-container, but currently there's no modularized implementation available, so I patch them a bit. Guice +Sisu seems okay, but has quite some third party dependencies that are not modularized yet. Micronaut looks like a better option if a few issues are solved (including this one).

One of the things I'm wondering: why did you choose for a services-directory with empty files where the name is the implementation?
sisu guice works, because is has the file META-INF/sisu/javax.inject.Named containing all the named classes. (and you probably also notice another issue here: as I'm writing a new application, I'd like to start with the jakarta namespaced classes).
Can we work on a similiar approach here?

**Comment by graemerocher** [comment]
we used to have `META-INF/services` definition that contained a single file with all of the classes, but the issue with this approach is it needs a full recompile of all classes that participated in its creation each time any of them change which is not great for incremental compilation performance.

We had a project that has over a million lines of code and was taking a significant amount of time to compile, we switched the implementation to a directory with a list of files that represent the class names and with this solution you have a 1-to-1 relationship between annotated class and generated file so we could effectively compile incrementally and significantly improve compiler performance.

**Comment by graemerocher** [comment]
for reference https://github.com/micronaut-projects/micronaut-core/pull/7195

**Comment by rfscholte** [comment]
> do you know of any modular jars out there that contain static resources that we could use in this test? Currently Micronaut doesn't support the module system, but maybe with the change you propose it could be possible I guess.

I'll prepare one just for testing. Notice in the exception that io.micronaut.context.event.ApplicationEventPublisher cannot be found when micronaut-inject-x.y.z.jar is on the modulepath instead of on the classpath. It is not a third-party jar issue, just the specs of modulepath that's causing an issue.

**Comment by rfscholte** [comment]
This only seems to be an issue when using **jlink**. 

    logger.error("{}", Application.class.getClassLoader().getResource("META-INF/micronaut/io.micronaut.inject.BeanDefinitionReference") != null );
    logger.error("{}", Application.class.getClassLoader().getResource("META-INF/micronaut/io.micronaut.inject.BeanDefinitionReference/io.micronaut.context.event.ApplicationEventPublisherFactory") != null );

    [main] ERROR micronaut.Application - false
    [main] ERROR micronaut.Application - true

The steps to reproduce it using modulelayers are incorrect, which makes it even harder to verify this. 

I guess the approach with the least impact here is to whitelist paths like `META-INF/micronaut/io.micronaut.inject.BeanDefinitionReference`; don't verify if it exists. WDYT?

**Comment by sgammon** [comment]
@rfscholte I did [some experiments in this area](https://github.com/sgammon/micronaut-jpms-experiments) a few months ago, they may be useful to you. I would be happy to help on this as we have been wanting to use `jlink` and Micronaut together too.

_Edit:_ Ah, I see you are a Java champion and work on Maven. You probably don't need my help. But I would still be happy to test or assist any way I can 😄

**Comment by graemerocher** [comment]
> This only seems to be an issue when using **jlink**.
> 
> ```
> logger.error("{}", Application.class.getClassLoader().getResource("META-INF/micronaut/io.micronaut.inject.BeanDefinitionReference") != null );
> logger.error("{}", Application.class.getClassLoader().getResource("META-INF/micronaut/io.micronaut.inject.BeanDefinitionReference/io.micronaut.context.event.ApplicationEventPublisherFactory") != null );
> 
> [main] ERROR micronaut.Application - false
> [main] ERROR micronaut.Application - true
> ```
> 
> The steps to reproduce it using modulelayers are incorrect, which makes it even harder to verify this.
> 
> I guess the approach with the least impact here is to whitelist paths like `META-INF/micronaut/io.micronaut.inject.BeanDefinitionReference`; don't verify if it exists. WDYT?

Seems reasonable to me

**Comment by rfscholte** [comment]
Just received confirmation from Alan Bateman that this is indeed the expected behavior: https://mail.openjdk.org/pipermail/jigsaw-dev/2024-June/015042.html
