### ISSUE TITLE
Http client compilation error when using custom @Header name with route URI variable

### ISSUE THREAD

**Issue by ahmedlafta** [micronaut-projects/micronaut-core#1085]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Add a `@Header` annotation with a custom name in any declarative http client.
Under http-client src/test/groovy/io/micronaut/http/client/docs/annotation/headers/HeadersTest
```
@Client("/pets")
@Header(name="X-Pet-Client", value="${pet.client.id}")
public interface PetClient extends PetOperations {

    @Override
    Single<Pet> save(String name, int age);

    @Get("/{name}")
    Single<Pet> get(@Header("pet-name") String name);
}
```
After adding `@Header("pet-name")`, compilation fails against the `MissingParameterRule` since the variable name is now treated as `pet-name`.
```
The route declares a uri variable named [name], but no corresponding method argument is present
    Single<Pet> get(@Header("pet-name") String name);
```

### Expected Behaviour

Compilation should succeed, and the request should attach a header named `pet-name` and a value of whatever is passed to the `get` method.

### Actual Behaviour

Compilation fails

### Environment Information

- **Operating System**: osx
- **Micronaut Version:** 1.0.1
- **JDK Version:** 1.8

### Example Application

Modified the Header test under http-client in this repo

**Comment by graemerocher** [comment]
I'm not sure if compilation should success because there is still no method parameter that matches `{name}` in the URI?

**Comment by graemerocher** [comment]
I have pushed support for `@PathVariable` although your case can be resolved by adding a parameter that takes `@QueryValue("name")` since Micronaut doesn't know which parameter to bind the path variable to
