### ISSUE TITLE
While upgrading to micronuat 4.4 from 3.8 HTTPResponse Body content is in unpooledContent and body is null

### ISSUE THREAD

**Issue by munishchouhan** [micronaut-projects/micronaut-core#10898]
### Expected Behavior

Content should be present in body or in bodybytes for streamedfiles

### Actual Behaviour

It is present in unpooledContent 

### Steps To Reproduce

Please check this PR
https://github.com/seqeralabs/wave/pull/318
and check tested results in this action:
https://github.com/seqeralabs/wave/actions/runs/9447636577

### Minimal Reproducer

1. git clone git@github.com:munishchouhan/NullBodyProblem.git
2. cd NullBodyProblem
3. ./gradlew test

### Environment Information

- Operating System: Linux
- Java 19

### Example Application

https://github.com/seqeralabs/wave/pull/318

### Version

5.4.3

**Comment by munishchouhan** [comment]
Minimal Reproducer

1. git clone git@github.com:munishchouhan/NullBodyProblem.git
2. cd NullBodyProblem
3. ./gradlew test

**Comment by munishchouhan** [comment]
Solved it by changing the type in exchange method from streamed file to string

**Comment by munishchouhan** [comment]
added the solution in reproducer

**Comment by munishchouhan** [comment]
There are some observations
Now HttpResponse does not have status and bodyBytes fields.
https://github.com/seqeralabs/wave/pull/318#discussion_r1637146728

**Comment by pstacherzakNX** [comment]
@munishchouhan I have just encounter the same thing you described in the Issue. I read the discussion linked in the comments, does it mean it is fixed in Micronaut 4.5?

**Comment by munishchouhan** [comment]
@pstacherzakNX you need pass String as class type in exchange method and it will appear in the body

**Comment by yawkat** [comment]
Your test case does not work with 3.10.3 either. I'm a bit confused how it is supposed to work anyway, since StreamedFile is a http-server type, and http-client has no handling for it.

**Comment by munishchouhan** [comment]
@yawkat I migrated from 3.8 to 4.5 now, so I have not tested in 3.10.3 
Previously in 3.8, the content was present in the body bytes part of the HTTP response, and mentioning streamedfile as response type in exchange method was working
but after upgrading that field was missing, it maybe related to netty.
so to solve that in testing I used String instead of Stremed file in exchange method

**Comment by yawkat** [comment]
`bodyBytes` is a private field in 3.x. How did you access it?

**Comment by munishchouhan** [comment]
@yawkat I think I didn't clarify the context correctly
I got these errors in Groovy Spock tests, where I was using the exchange method of the Micronaut HTTP client, where I can access private fields. 
To run those tests successfully in Micronaut 4.5, I used String instead of Streamedfile to get the content from HttpResponse. I am unsure if this is the correct solution, but it works in my case.

**Comment by yawkat** [comment]
ok. private fields are not preserved.

**Comment by yawkat** [comment]
fwiw you can just use byte[] as the body type and you'll get the bytes directly
