### ISSUE TITLE
Rendering issue in docs

### ISSUE THREAD

**Issue by tcrespog** [micronaut-projects/micronaut-core#10903]
### Expected Behavior

The line is rendered as expected.

### Actual Behaviour

This [line](https://github.com/micronaut-projects/micronaut-core/blame/c19a1abc669695601eb26d162ac33576cb626c50/src/main/docs/guide/httpServer/routing.adoc#L94) in the docs doesn't seem to be rendered as expected in the latest [docs](https://docs.micronaut.io/latest/guide/#_uri_reserved_character_matching).

![image](https://github.com/micronaut-projects/micronaut-core/assets/10177888/c057568c-1771-4dff-be6b-9847ef3e6b1b)

It seems to happen only with `/latest/`, as it is rendered correctly in the docs of specific Micronaut versions including [3.x](https://micronaut-projects.github.io/micronaut-docs-mn3/3.5.0/guide/#_uri_reserved_character_matching) and [4.x](https://docs.micronaut.io/4.1.0/guide/#_uri_reserved_character_matching):

![image](https://github.com/micronaut-projects/micronaut-core/assets/10177888/bd254729-ba88-4a2d-9598-9e42994a3007)

### Steps To Reproduce

1. Go to https://docs.micronaut.io/latest/guide/#_uri_reserved_character_matching.
2. See the line with missing `+`.

### Version

latest

**Comment by graemerocher** [comment]
fixed by https://github.com/micronaut-projects/micronaut-core/pull/10969
