### ISSUE TITLE
Micronaut Management stopped working after migration to Micronaut 4.5.3

### ISSUE THREAD

**Issue by sergey-morenets** [micronaut-projects/micronaut-core#10913]
### Expected Behavior

Management routes endpoints should show actual route information

### Actual Behaviour

Hi

We failed to migrate our project from Micronaut 4.0 to 4.5.3 because of the multiple failures so we created simple application to reproduce this behavior.
In general Management base endpoints URI (localhost:8080/) returns this incorrect response:

`{"_links":{"self":[{"href":"/","templated":false}]},"_embedded":{"errors":[{"message":"Page Not Found"}]},"message":"Not Found"}`

And if we try to query routes endpoint (http://localhost:8080/routes) we receive 401 error and the following stack-trace in the console:

```
[default-nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Micronaut Server Error - No request state present. Cause: An established connection was aborted by the software in your host machine
java.io.IOException: An established connection was aborted by the software in your host machine
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:46)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:340)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:294)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:269)
	at java.base/sun.nio.ch.SocketChannelImpl.implRead(SocketChannelImpl.java:426)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:493)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:255)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)

```

### Steps To Reproduce

1. We generated sample application using Micronaut Launch and added single management dependency:

```
plugins {
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("io.micronaut.application") version "4.4.0"
    id("io.micronaut.aot") version "4.4.0"
}

version = "0.1"
group = "com.example"

repositories {
    mavenCentral()
}

dependencies {
    annotationProcessor("io.micronaut:micronaut-http-validation")
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    compileOnly("io.micronaut:micronaut-http-client")
    runtimeOnly("ch.qos.logback:logback-classic")

    implementation("io.micronaut:micronaut-management")

    testImplementation("io.micronaut:micronaut-http-client")
}


application {
    mainClass = "com.example.Application"
}
java {
    sourceCompatibility = JavaVersion.toVersion("22")
    targetCompatibility = JavaVersion.toVersion("22")
}

```
Here's our controller:

```
@Controller("/hello") 
public class HelloWorldController {

    @Get("/world") 
    public String issue() {
        return "Issue # ";
    }
}
```

And application.yml:
```

endpoints:
  routes:
    enabled: true
```

### Environment Information

OS: Windows 10
JDK: 22.0.1

### Version

4.5.3

**Comment by roar-skinderviken** [comment]
To enable the `routes`-endpoint, I believe you'll need this configuration (tested and verified with MN plafform 4.5.0/micronaut-core:4.5.3):
```
endpoints:
  routes:
    enabled: true
    sensitive: false
```

Please see section [16.2 Built-In Endpoints](https://docs.micronaut.io/latest/guide/index.html#providedEndpoints).

**Comment by sergey-morenets** [comment]
Hi @roar-skinderviken 

Yes, you are right. My problem was that Micronaut 4.x doesn't include SnakeYAML dependency. And Micronaut Launch doesn't include it by default:

`runtimeOnly("org.yaml:snakeyaml")`

I guess if there are YAML files in the resources folder and there's no YAML processor it'd be nice to warn developer about that.

**Comment by roar-skinderviken** [comment]
Hi @sergey-morenets 

> I guess if there are YAML files in the resources folder and there's no YAML processor it'd be nice to warn developer about that.

Strange, just tested adding an application.yml to repo in addition to existing application.properties. When running 
`./gradlew clean build`
I get this build error:
```
* What went wrong:
Execution failed for task ':inspectRuntimeClasspath'.
> YAML configuration file detected but snakeyaml is not on classpath. Make sure to add a runtimeOnly dependency on snakeyaml, e.g 'runtimeOnly("org.yaml:snakeyaml")'
```

**Comment by graemerocher** [comment]
if you didn't get the error it is because you didn't upgrade to the newest Gradle plugins

**Comment by sergey-morenets** [comment]
Hi @graemerocher 

I created Micronaut application using Micronaut Launch so I guess I use the latest plugin versions:

```
plugins {
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("io.micronaut.application") version "4.4.0"
    id("io.micronaut.aot") version "4.4.0"
}
```
