### ISSUE TITLE
How to register a bean definition to  the context at runtime? 

### ISSUE THREAD

**Issue by eisig** [micronaut-projects/micronaut-core#1092]
I'm trying to make  my  micronaut application to support mybatis.

I want to scan  all the mapper interfaces and then  register the mapper interfaces to bean context, just like https://github.com/mybatis/spring

 How to register a bean definition to  the context at runtime? and when?

**Comment by graemerocher** [comment]
you can call `beanContext.registerSingleton(..)`

**Comment by eisig** [comment]
When to  register the bean?
I write a simple demo register a bean in ApplicationStartupEvent:
```
@EventListener
    public void onStartup(ApplicationStartupEvent startupEvent) {
        beanContext.registerSingleton(new Demo.ServiceA());
    }
```

```
It work when other @Singleton bean use it. But failed when I change @Singleton to @Context

@Singleton
public class MyOtherServcie {
    @Inject
    Demo.ServiceA serviceA;
}

```
Is there any thing like BeanFactoryPostProcessor in spring?
