### ISSUE TITLE
Expose AnnotationMetadata of the route match in server filters

### ISSUE THREAD

**Issue by mikehearn** [micronaut-projects/micronaut-core#10942]
### Feature description

I'd like to write a server request filter method that triggers based on controller method annotations, not hard-coded URL patterns. This can be done already using some internal knowledge and request attributes:

https://github.com/micronaut-projects/micronaut-core/blob/4f353fa79288d2ee56314ac2982586216590fffc/http-server/src/main/java/io/micronaut/http/server/cors/CrossOriginUtil.java#L56

but it should be exposed more directly in a documented way. Either by supporting annotations directly in `@ServerFilter` or by allowing the `AnnotationMetadata` to be injected.

**Comment by graemerocher** [comment]
I think it makes sense to allow the `RouteMatch` to be injected

**Comment by yawkat** [comment]
@graemerocher i'll take over
