### ISSUE TITLE
How to return a static resource(view) through the controller?

### ISSUE THREAD

**Issue by Avbat** [micronaut-projects/micronaut-core#1095]
Unable to display html page when responding to get request.

### Steps to Reproduce

1. Place "testview.html" file in src/main/resources/views"
2. Add `compile "io.micronaut:micronaut-views"`
3. Create controller
```
@Controller
public class TestController {

  @View("testview")
  @Get("/testview")
  public HttpResponse indexTestView() {
    return HttpResponse.ok();
  }

  @Get("/testmodelandview")
  public ModelAndView indexTestModelAndView() {
    return new ModelAndView("testview", "testmodel");
    //return new ModelAndView("views/testview.html", "testmodel");
    //return new ModelAndView(..., null);
  }
}
```
3. Start the app.

### Expected Behaviour

Display testvew.html content in the browser.

### Actual Behaviour

/testview:
`<Response body is empty>`

/testmodelandview:
`{"view":"testview","model":"testmodel"}`

### Environment Information

- **Micronaut Version:** 1.0.2
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
I imagine this is not supported yet, you would need a view renderer like free marker, velocity etc.

I'm not sure the point of returning a static view that has no access to the model

**Comment by jameskleeh** [comment]
@Avbat Can you state the use case here?

**Comment by jameskleeh** [comment]
Closing due to a lack of feedback

**Comment by davecramer** [comment]
One such use case is a purely javascript app, where I would want to render the first page as well as the javascript.

**Comment by jameskleeh** [comment]
@davecramer Not sure what you mean by "as well as the javascript". Can you elaborate?

**Comment by davecramer** [comment]
@jameskleeh 
how do you load the .js file ?

**Comment by jameskleeh** [comment]
@davecramer I would use the static resource support https://docs.micronaut.io/latest/guide/index.html#staticResources

**Comment by davecramer** [comment]
@jameskleeh thx!
