### ISSUE TITLE
`suspend` controller function returning `Unit` has a body set

### ISSUE THREAD

**Issue by tmapes** [micronaut-projects/micronaut-core#10992]
### Expected Behavior

If an `@Controller` function is both `suspend`-able and returns `Unit` i would expect no body to be written to the caller.

### Actual Behaviour

After the coroutine is resumed, a `Unit` body is set on the response. This then causes issues later with [serialization](https://github.com/micronaut-projects/micronaut-serialization/issues/890) and sometimes causes an empty body `{}` to be written.

### Steps To Reproduce

- Clone project
- Set JDK/JRE to 21
- Run included tests
```shell
./gradlew test
```

### Environment Information

- macOS (arm)
- Java 21 & 17

### Example Application

https://github.com/tmapes/mn-serde-unit

### Version

4.5.0 platform, 4.5.3 core

**Comment by tmapes** [comment]
I did some investigation, after walking the call chain the RouteExecutor seems to think the return type despite explicitly being `Unit` in the controller, the `isKotlinFunctionReturnTypeUnit` value is being set to false.

Seems to come from [this](https://github.com/micronaut-projects/micronaut-core/blob/v4.5.3/http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java#L581-L583) `instanceof` check, it's returning false.

![image](https://github.com/user-attachments/assets/c26be56f-5a30-45c1-ac8c-7fa2fa7f8d7d)

It's then causing the check [here](https://github.com/micronaut-projects/micronaut-core/blob/v4.5.3/http-server/src/main/java/io/micronaut/http/server/RouteExecutor.java#L598-L600) to become truthy, thus causing the body to be set to `Unit`

![image](https://github.com/user-attachments/assets/bb0efa47-9740-4b42-8220-81e49b3572a9)

**Comment by yawkat** [comment]
Thanks for the report & test case!

**Comment by tmapes** [comment]
Thanks for the fix, this was driving me insane for a bit and I thought I was doing something wrong.

**Comment by yawkat** [comment]
fwiw you should be able to return `""` as a workaround.
