### ISSUE TITLE
Compiling Controller with Route/Method Defined in Trait Fails to Compile - No Corresponding Argument

### ISSUE THREAD

**Issue by mphouston** [micronaut-projects/micronaut-core#1103]
When using Micronaut 1.0.3 with a get method in a Groovy Trait, the compile fails with an error about missing argument for a method in the Trait.

BTW, Excellent framework :).

### Task List

- [X] Steps to reproduce provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create the app with -l groovy option
2. Create a groovy Trait that provides a method with a router on @GET
3. Create Controller that implements that trait.
4. Compile and Run

### Expected Behaviour

The program will compile and execute the method from the trait.

### Actual Behaviour

When using Micronaut 1.0.3 with a get method in a Groovy Trait, the compile fails with the error:

    ....\HelloController.groovy: -1: The route declares a uri variable named [x], but no corresponding method argument is present

### Environment Information

- **Operating System**: Windows 7
- **Micronaut Version:** 1.0.3
- **JDK Version:** 1.8_181

### Example Application

See https://github.com/mphouston/mn-issues/tree/master/route-trait-issue for a bare-bones application that reproduces the problem.  Use this command to run the app:

    gradlew run

Quick summary of the code:

    HelloController.groovy
      @CompileStatic
      @Controller("/hello")
      class HelloController implements ControllerTrait {
          @Get("/{x}")
          @Produces(MediaType.TEXT_PLAIN)
          String index(String x) {
              "Hello World ${x}"
          }
      }

    ControllerTrait.groovy
      trait ControllerTrait {
          @Get("/trait/{x}")
          @Produces(MediaType.TEXT_PLAIN)
          String indexT(String x) {
              "Hello World Trait ${x}"
          }
      }

I have not tried this with Java interfaces with default parameters.  I would prefer to stay with Groovy.

The app was created with this micronaut command (1.0.0):

    mn create-app example.route-trait-issue -l groovy

Except for the two classes above and a change to build.gradle to micronaut 1.0.3, the application is the default from the micronaut command.

This seems similar to https://github.com/micronaut-projects/micronaut-core/issues/936 but the symptoms are different.

**Comment by mphouston** [comment]
One other note:  I will be using this with the @Secured() annotation in the concrete class.  The method in the trait will not have @Secured() used on it.  This support for @Secured() seems to be working fine in 1.0.3 for methods provided from a trait.

**Comment by graemerocher** [comment]
This is a bug in Groovy. I have reported it here https://issues.apache.org/jira/browse/GROOVY-8969

Once an upstream fix is committed to Groovy we can resolve this issue. In the meantime as a workaround you can explicitly specify the name of the path variable with `@PathVariable("x")`

**Comment by mphouston** [comment]
Excellent!  The work around worked fine.  Many thanks :)

The work-around looks like this:

    @CompileStatic
    trait ControllerTrait {
        @Get("/trait/{x}") 
        @Produces(MediaType.TEXT_PLAIN) 
        String indexT(@PathVariable(name = 'x') String x) {
            "Hello World Trait ${x}" 
        }
    }

**Comment by edalex-joe** [comment]
I've run into something that might be a similar groovy compiler bug perhaps. I created a @Client interface e.g. FooHttpClient that extended on another interface e.g. FooOperations, the latter having all the annotated get/post etc methods. This worked OK when the classes/interfaces lived in the same package, but moving the client interface out exercises the bug where it complains about the path variables not being present. The workaround to supply the name property in the PathVariable annotation works (but isn't ideal).

**Comment by bjuretic** [comment]
> I've run into something that might be a similar groovy compiler bug perhaps. I created a @client interface e.g. FooHttpClient that extended on another interface e.g. FooOperations, the latter having all the annotated get/post etc methods. This worked OK when the classes/interfaces lived in the same package, but moving the client interface out (into a gradle subproject in this case) exercises the bug where it complains about the path variables not being present. The workaround to supply the name property in the PathVariable annotation works (but isn't ideal).

Confirmed, this is still an issue.
