### ISSUE TITLE
KSP doesn't work with CoroutineCrudRepository

### ISSUE THREAD

**Issue by nilols** [micronaut-projects/micronaut-core#11040]
### Expected Behavior

KSP should produce compilation time data for CoroutineCrudRepository, when using KAPT or if you use KSP with CrudRepository this works.

### Actual Behaviour

When using KSP and a CoroutineCrudRepository micronaut data fails with
```
Micronaut Data method is missing compilation time query information. Ensure that the Micronaut Data annotation processors are declared in your build and try again with a clean re-build.
java.lang.IllegalStateException: Micronaut Data method is missing compilation time query information. Ensure that the Micronaut Data annotation processors are declared in your build and try again with a clean re-build.
	at io.micronaut.data.runtime.intercept.DataInterceptorResolver.findDataInterceptor(DataInterceptorResolver.java:111)
	at io.micronaut.data.runtime.intercept.DataInterceptorResolver.resolve(DataInterceptorResolver.java:77)
	at io.micronaut.data.runtime.intercept.DataIntroductionAdvice.intercept(DataIntroductionAdvice.java:75)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:138)
	at com.example.BrokenRepository$Intercepted.save(Unknown Source)
```

A workaround seems to be to re-define functions from the CoroutineCrudRepository interface
```
@Repository
interface FixedRepository : CoroutineCrudRepository<DataEntity, Long> {
    override fun findAll(): Flow<DataEntity>
    override suspend fun <S : DataEntity> save(entity: S): S
}
```

### Steps To Reproduce

1. clone the example application
2. run the tests

### Example Application

https://github.com/nilols/micronaut-ksp-issue

### Version

4.5.1

**Comment by nilols** [comment]
It exists a similar problem if you extend a `CrudRepository` in your test sources, when using `KSP` but it works with `KAPT` and the same workaround mentioned in this issue also works in this case. Can add that case to the example application

**Comment by nilols** [comment]
Been trying to investigate this further but I don't fully understand what is wrong, but `DataInterceptorResolver` seem to fail because there is no `DataMethod` annotation added, so there is no `DataMethod.META_MEMBER_INTERCEPTOR` available that the `interceptorName` can be extracted from. And what I can see the `micronaut-data-processor` should add this through the `RepositoryTypeElementVisitor` so I assume for some reason that this is not done

**Comment by dstepanov** [comment]
Something is broken with KSP :(

**Comment by nilols** [comment]
@dstepanov thanks, I tested the snapshot version in the example project and it worked great 👍
