### ISSUE TITLE
HTTP DELETE with BODY

### ISSUE THREAD

**Issue by yawkat** [micronaut-projects/micronaut-core#11047]
### Discussed in https://github.com/micronaut-projects/micronaut-core/discussions/11045

<div type='discussions-op-text'>

<sup>Originally posted by **magnayn** August  1, 2024</sup>
The keycloak REST API, sadly, uses "DELETE with BODY". There's no point in pointing at specs that say you shouldn't do this - people have and that's just a fact of life.

I cannot find a way of working around the fact that micronaut-http does not like that, and fails to include the body I provide. I think this is down fundamentally to HttpRequestFactory.builder, which is just statically invoked from AbstractJdkHttpClient.

(I'm using an @Client).

How can I work around this?</div>

**Comment by altro3** [comment]
If you do this, then I think it’s worth adding processing for the GET request body

**Comment by yawkat** [comment]
@altro3 DELETE is already marked as permitsRequestBody in our source, so I classify this as a bug. GET is not marked as such so I would classify that as an improvement

**Comment by altro3** [comment]
I say this because you have already deviated from the HTTP specification. Therefore, I don’t think that another removal of the restriction (for GET requests) will contradict anything :-)
