### ISSUE TITLE
HttpAttributes.SERVICE_ID not set when using jdk http client

### ISSUE THREAD

**Issue by magnayn-mns** [micronaut-projects/micronaut-core#11041]
### Expected Behavior

Service ID should be propagated in attributes

### Actual Behaviour

nothing is there - meaning that the OAuth2 token flow is not invoked.

### Steps To Reproduce

Have a service defined with @Client using OAuth2, and attempt to match with service-regex

### Version

4.2.3

**Comment by altro3** [comment]
@graemerocher @yawkat You already merged fix. Issue can be closed
