### ISSUE TITLE
AliasFor in annotation properties modify real values

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#11053]
Based on this: https://github.com/micronaut-projects/micronaut-openapi/issues/1676

For example, create HttpClient with `@Header` annotation like this:
```java
@Client("test")
public interface DefaultApi {

    /**
     * {@summary Check if a file is already available}
     *
     * @param xtESTCrc32 Decimal CRC32B representation of the file (required)
     * @param xtESTSha512 Lowercase SHA512hex representation of the file (required)
     * @param xtESTSize Size of the file in bytes (required)
     */
    @Head("/")
    void fileAvailable(
        @Header(name = "X-TEST-crc32") @NotNull String xtESTCrc32,
        @Header(name = "X-TEST-sha512") @NotNull String xtESTSha512,
        @Header(name = "X-TEST-size") @NotNull Long xtESTSize
    );
```
If you send request by this client you will see wrong header names:

![изображение](https://github.com/user-attachments/assets/2a3ff327-982f-477e-ac04-62c427e8dc39)

Wron heade names: `xt-estcrc32`, `xt-estsha512`, `xt-estsize`. Must be `x-test-crc32`, `x-test-sha512`, `x-test-size`.

If you use value, instead name for Header annotaions, like this:
```java
@Client("test")
public interface DefaultApi {

    /**
     * {@summary Check if a file is already available}
     *
     * @param xtESTCrc32 Decimal CRC32B representation of the file (required)
     * @param xtESTSha512 Lowercase SHA512hex representation of the file (required)
     * @param xtESTSize Size of the file in bytes (required)
     */
    @Head("/")
    void fileAvailable(
        @Header("X-TEST-crc32") @NotNull String xtESTCrc32,
        @Header("X-TEST-sha512") @NotNull String xtESTSha512,
        @Header("X-TEST-size") @NotNull Long xtESTSize
    );
}
```
All works fine:
![изображение](https://github.com/user-attachments/assets/e334ebf7-9294-4603-8863-c0b0681c2bab)

I think, the same value can be with all annotaions tha uses `@AliasFor`

### Version

4.5.4

**Comment by altro3** [comment]
@graemerocher @sdelamo @dstepanov I think, this is a critical bug

**Comment by altro3** [comment]
Reproducer app in related issue: https://github.com/micronaut-projects/micronaut-core/issues/11053

**Comment by dstepanov** [comment]
Not related to `AliasFor`. You can see `Header` is binding the the annotation `Bindable` intead of to inself making definition by name not present.

**Comment by altro3** [comment]
but problem exists

**Comment by dstepanov** [comment]
I'm just explaining why is it happening, it's a bug
