### ISSUE TITLE
NotFoundSpec.test 404 handling with Flowable fails since #11002

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#11068]
### Issue description

Since PR https://github.com/micronaut-projects/micronaut-core/pull/11002 the following test is flaky.  

https://ge.micronaut.io/scans/tests?search.query=project:micronaut%20&search.timeZoneId=Europe%2FMadrid&tests.container=io.micronaut.http.client.aop.NotFoundSpec&tests.test=test%20404%20handling%20with%20Flowable

The following script passes with this commit https://github.com/micronaut-projects/micronaut-core/commit/bf860b1e34f1775042ea33ecec50e6aed977ba55

starts failing in the next commit https://github.com/micronaut-projects/micronaut-core/commit/f4a7f9dd38b1167f41999d26157c9f9546fefec4 which his the merge of this PR: https://github.com/micronaut-projects/micronaut-core/pull/11002

You can reproduce by running the following script: 

```
#!/bin/bash

EXIT_STATUS=0

for ((i=1; i<=10; i++))
do
  ./gradlew :http-client:test --tests "io.micronaut.http.client.aop.NotFoundSpec.test 404 handling with Flowable" --rerun-tasks || EXIT_STATUS=$?
  if [ $EXIT_STATUS -ne 0 ]; then
    exit $EXIT_STATUS
  fi
done

exit $EXIT_STATUS
```

This failure is causing every PR to fail.

**Comment by yawkat** [comment]
we already found the cause and @dstepanov said he'd work on a fix.
