### ISSUE TITLE
Help needed to use BouncyCastle with Micronaut example

### ISSUE THREAD

**Issue by padetiloye** [micronaut-projects/micronaut-core#11120]
### Issue description

I'm a new to micronaut but we need to use it to build AWS lambda native-image custom runtime using graalvm. I got the example micronaut native-image built and deployed to AWS lambda which works great.

```
 mn create-app example.micronaut.micronautguide \                                
    --features=aws-lambda,graalvm \
    --build=maven \
    --lang=java \
    --test=junit

```

However, we have a requirement to add BouncyCastle provider to use the Format Preserving Encryption algorithim ("AES/FF3-1/NoPadding"). Unfortunately, I'm not sure how to register the BouncyCastle library, all attempts seem not to work.

Running the test
`mvn -Pnative -Dagent=true clean test`

Exception:
```
21:43:36.418 [main] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Trying to verify a provider that was not registered at build time: BC version 1.76. All providers must be registered and verified in the Native Image builder. 
com.oracle.svm.core.jdk.UnsupportedFeatureError: Trying to verify a provider that was not registered at build time: BC version 1.76. All providers must be registered and verified in the Native Image builder. 
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:92)
        at java.base@17.0.9/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:384)
        at java.base@17.0.9/javax.crypto.Cipher.getInstance(Cipher.java:718)
        at java.base@17.0.9/javax.crypto.Cipher.getInstance(Cipher.java:642)
        at 
```

I find very little documentation to help on the micronaut site.

Any suggestion to add BouncyCastle provider ?

**Comment by yawkat** [comment]
More of a native image thing than a Micronaut framework thing.

All JCA security providers have to be registered at build time for native image. This can happen either through JDK config or through a Feature. It is described here: https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/JCASecurityServices/
