### ISSUE TITLE
Micronaut Data JDBC Criteria API upper and lower methods are not working correctly.

### ISSUE THREAD

**Issue by ralmeida7** [micronaut-projects/micronaut-core#11128]
### Expected Behavior

By using the UPPER method from criteria builder, I expect the generated SQL statement to include the UPPER function.

```java
    public static <T> PredicateSpecification<T> titleContains(String title) {
        return (root, criteriaBuilder) -> criteriaBuilder.like(criteriaBuilder.upper(root.get("title")), "%" + title.toUpperCase() + "%");
    }
```

Generated SQL statement:

```SQL
select b1_0.id,b1_0.author,b1_0.title from book b1_0 where upper(b1_0.title) like ? escape '' offset ? rows
```

This works fine with Micronaut Data JPA

### Actual Behaviour

The generated SQL statement is not including the UPPER function.

```SQL
SELECT book_.`id`,book_.`title`,book_.`author` FROM `book` book_ WHERE ('io.micronaut.data.model.jpa.criteria.impl.expression.UnaryExpression@2e3572e8' LIKE ?)
```

### Steps To Reproduce

1. Download the example application
2. Use the "jdbc" branch `git checkout jdbc`
3. Run the test `./gradlew test --tests "com.example.BookRepositoryTest.testUpperCriteriaQuery"`

The same implementation with Micronaut Data JPA can be found in the branch "jpa" `git checkout jpa`

### Environment Information

- Operating System: MacOS Sonoma
- JDK: 21

### Example Application

https://github.com/ralmeida7/criteria-builder-bugs

### Version

4.6.0

**Comment by dstepanov** [comment]
Why did you close it?

**Comment by ralmeida7** [comment]
Wrong repo
