### ISSUE TITLE
Wrong route matched when http request to /

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-core#11122]
### Expected Behavior

With three routes /, /{id} and /{id}/relations and sending a request to / I expect the root route to match. 

### Actual Behaviour

But instead the /{id}/relations route is matched.

### Steps To Reproduce

1. Add a controller with three routes /, /{id} and /{id}/something (maybe the middle one is not needed)
2. Send a http request to /
3. Get 400 response -> GET / (Bad Request): Required argument [String id] not specified

### Environment Information

 - MacOS 14.6.1
 - JDK 21

### Example Application

https://github.com/goeh/micronaut-460-issue

### Version

4.6.0

**Comment by goeh** [comment]
I simplified the reproducer application. Removed micronaut-security and some cleanup.

**Comment by yawkat** [comment]
Thanks for the report!
