### ISSUE TITLE
`AnnotationClassValue.getType()` / `AnnotationClassValue.classValue("...")` returns null everytime

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#11134]
Sample classes structure:
```java
record Car(String model, @JsonUnwrapped @Schema(implementation=ResourcePath.class) Resource resource, boolean selected) {
}

abstract class Resource {
}

abstract class ResourcePath extends Resource {

  public String resourcePath;
  public String resourceType;

}
```

When I try to read `resource` annotaion `@Schema` and try to get classValue for `implementation field`, I see null. There are two cases to catch error:

1. i try to read this value by `getValues()`:
```java
 var schemaAnn = element.getAnnotation(io.swagger.v3.oas.annotations.media.Schema.class);
 var implClass1 = schemaAnn.getValues().get("implementation");
```

I see this:
![изображение](https://github.com/user-attachments/assets/13ce9c89-281e-4971-924e-e2593a76e512)

`name` field is right, but `theClass` field is null .

2. If i ty to use `AnnotationClassValue.classValue("...")` method like this:
```java
        var schemaAnn = element.getAnnotation(io.swagger.v3.oas.annotations.media.Schema.class);
        var implClass = schemaAnn.classValue("implementation").orElse(null)
```
![изображение](https://github.com/user-attachments/assets/4c685c68-5014-46e9-87b9-0e6a4c445704)

`implClass` is null.

### Version

4.6.3

**Comment by altro3** [comment]
@dstepanov Hi! Look to this, please

**Comment by dstepanov** [comment]
If `ResourcePath` is not on the annotation processor classpath, you will get null. You should be using `annotationClassValue()`.

**Comment by altro3** [comment]
But class `ResourcePath` in java sources, java sources in annotation processor classpath.

And I don't understand, why I need to write this (this solution is works):
```java
            var implClass = schemaAnn.annotationClassValue(PROP_IMPLEMENTATION).orElse(null);
            if (implClass != null) {
                elType = context.getClassElement(implClass.getName()).orElse(elType);
            }
```
Instead of this:
```java
            var implClass = schemaAnn.classValue(PROP_IMPLEMENTATION).orElse(null);
            if (implClass != null) {
                elType = context.getClassElement(implClass).orElse(elType);
            }
```
I mean, why `annotationClassValue()` return `AnnotationClassValue` with filled `name` field, but empty `theClass` field???

![изображение](https://github.com/user-attachments/assets/d9ad5540-7c76-4659-840c-41628a37de81)

**Comment by dstepanov** [comment]
The Java source is being compiled and is not included in the annotation processor's classpath.

**Comment by altro3** [comment]
ok, if this behavior is correct, then we can close this issue. Thanks!
