### ISSUE TITLE
Configuration search from Consul KV is ignoring /config/application

### ISSUE THREAD

**Issue by jdeex** [micronaut-projects/micronaut-core#11136]
### Expected Behavior

ConfigurationProperties("property") should resolve from the sources available [as described here](https://github.com/micronaut-projects/micronaut-core/blob/4.6.x/src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationConsul.adoc#storing-configuration-as-keyvalue-pairs)

### Actual Behaviour

variable is not being populated 

### Steps To Reproduce

In Consul KV store your configuration in two sources:
1. /config/application

```
app: 
   scenarios:
     s1:
       name: one
       type: t
     s2:
       name: two
       type: t
```

2. /config/your-service-name
```
service:
  ...
```

```
@ConfigurationProperties("app")
public class ConfiguredScenarios {
    private Map<String, Object> scenarios = new HashMap<>();   // scenarios will not receive values
   
    env.getProperty("apps.scenarios", Map.class) // retrieves the values, but changes all keys to kebab
}
```

Trying with @Value instead...

```
public class ConfiguredScenariosValue {

   @value("app.scenarios")
    private Map<String, Object> scenarios = new HashMap<>();   // scenarios will not receive values
   
   // Fails on startup --> Message: Error resolving property value [app.scenarios]. Property doesn't exist
}
```

On the logs side:
m.d.c.c.DistributedPropertySourceLocator: [inspectionId=] [workflow=] Resolved 2 configuration sources from client: compositeConfigurationClient(consul)

And Environment has all the sources ok with the actual values, that's whyl env.getProperty() works fine

### Environment Information

- Windows 10
- Eclipse Adoptium\jdk-21.0.1.12-hotspot
- Micronaut 4.5.0

### Version

4.5.0

**Comment by graemerocher** [comment]
use `@MapFormat` see [https://github.com/micronaut-projects/micronaut-sql/blob/5.8.x/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/JpaConfiguration.java#L139 for an example](https://github.com/micronaut-projects/micronaut-sql/blob/e145a1f5f135d31df6eff3bbd8671e52306d0da7/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/JpaConfiguration.java#L139)

**Comment by jdeex** [comment]
> use `@MapFormat` see [https://github.com/micronaut-projects/micronaut-sql/blob/5.8.x/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/JpaConfiguration.java#L139 for an example](https://github.com/micronaut-projects/micronaut-sql/blob/e145a1f5f135d31df6eff3bbd8671e52306d0da7/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/JpaConfiguration.java#L139)

You mean that for @ConfigurantionProperties or @Value to work I have to use @MapFormat? 

I mean, I’m able to get the config from the /config/your-service-name source with those annotations, but I don’t get anything from /config/application.

**Comment by jdeex** [comment]
I was missing setters in the class! With setters added, the @ConfigurationProperties and @MapFormat it worked. Thanks
