### ISSUE TITLE
Breaking change with micronautPlatform:4.6.0 and micronaut-views-thymeleaf

### ISSUE THREAD

**Issue by roar-skinderviken** [micronaut-projects/micronaut-core#11143]
### Expected Behavior

With the example applcation, I expect the application to return homepage as with MN:4.5.1.

### Actual Behaviour

With MN:4.6.0, the controller hangs forever.

### Steps To Reproduce

Start the example application with 
```
./gradlew -p backend build run
```
Go to http://localhost:8080 and observe that browser displays the default Vite React page.

In gradle/libs.versions.toml, change `micronautPlatform = "4.5.1"` to `micronautPlatform = "4.6.0"`, and start the application again. Observe that the http://localhost:8080 now hangs.

A colleague reported a similar issue with a MN REST-API, and had to roll back to 4.5.1.

### Environment Information

JDK 21 (Temurin)
Kotlin:2.0.20
Ubuntu 22.04 

### Example Application

https://github.com/roar-skinderviken/micronaut-plus-react

### Version

4.6.0

**Comment by yawkat** [comment]
This may be #11115. Please try upgrading core to 4.6.4

**Comment by roar-skinderviken** [comment]
Thanks @yawkat. Problem resolved with MN:4.6.1.
