### ISSUE TITLE
HTTP requests - are there limitations in data structure sizes in request body?

### ISSUE THREAD

**Issue by moliveiraOptiply** [micronaut-projects/micronaut-core#11144]
### Issue description

I'm working on an HTTP endpoint that receives a JSON that includes multiple data structures. One of these is a list of strings. Here's an example of the structure sent as a request body:
` {      "fileType": "CSV", 
         "visibleColumns": ["NAME", "STOCK_TIME", "FREE_STOCK", "EXPECTED_DEMAND", "EAN_CODE", "SALES_PRICE", "CATEGORY", "NOVEL", "NOTES",  "STOCK",  "CREATED_AT"],
          "fileName": "test-products",
          "include": [],
           "queryData": {
                   "page": {
                       "from": "0",
                       "page_by_id": false,
                       "size": 10
                   },
                   "sort_by": [
                       {
                           "order": 1,
                           "field": "NAME"
                       }
                   ]
               }
}`

The issue I'm facing is the following error:
`Suppressed: io.micronaut.http.client.exceptions.HttpClientResponseException: exportProducts.body.visibleColumns: size must be between 1 and 17
		at io.micronaut.http.client.netty.DefaultHttpClient$FullHttpResponseHandler.makeErrorFromRequestBody(DefaultHttpClient.java:2232)`

This only happens if the number of strings in `visibleColumns` is equal to or larger than 17 elements. My code has no limitations regarding the sizes of data structures in the HTTP request body. 

Is there any limitation or default setting controlling this on Micronaut's side?

Micronaut version: 3.7.10

**Comment by yawkat** [comment]
Sounds like a micronaut-validation thing

**Comment by moliveiraOptiply** [comment]
Do you mean a validation issue on the http client side? 
I am not using any validation constraints for this list of strings, though. 

ETA: nevermind. I ended up fixing it. It was indeed a validation added by a colleague. Thanks for the help!
