### ISSUE TITLE
mn CLI is failing with custom SSL security cert

### ISSUE THREAD

**Issue by DuskoV** [micronaut-projects/micronaut-core#1115]
Issue #627 is reproducible (same issue).

This is still issue in the latest 1.0.3 version. We are having custom SSL cert which is used by firewall security (original SSL is replaced with internal SSL on the network). Custom SSL cert is properly installed in JDK (other applications don't have this issue).

### Steps to Reproduce

1. Manual download of micronaut-1.0.3.zip
2. Unzip on Windows machine, which is behind firewall, with custom SSL required
3. Setup environment variables - %MICRONAUT_HOME% and %PATH% Environments are correctly set
4. run "mn" in command prompt

### Expected Behaviour

get CLI output

### Actual Behaviour

| Error Error occurred running Micronaut CLI: unable to find valid certification path to requested target (Use --stacktrace to see the full trace)

### Environment Information

- **OS: Windows10**
- **Micronaut Version: 1.0.3**
- **JDK Version: 1.8.0_172** TODO

### Example Application

- Wish it would work

**Comment by graemerocher** [comment]
Micronaut uses Aether (maven's resolution engine for dependency resolution in the CLI). Does it help passing the appropriate SSL config. Like https://maven.apache.org/guides/mini/guide-repository-ssl.html

**Comment by DuskoV** [comment]
Can you give sample Windows command line, if cert is in ssl_keys.cert file ?

Another problem is we are using Nexus as repo storage. Based on this, seems like we couldn't point Micronaut to use our custom repo.

Is there a reason why Micronaut isn't using standard command like "mvn" or something, since there are Maven package dependencies?

**Comment by graemerocher** [comment]
Micronaut uses standard Maven or Gradle builds that fully support nexus. The CLI is just a convenience tool for creating apps but is not needed other than for app creation

**Comment by DuskoV** [comment]
Cool! Is it possible to have somewhere some basic project templates (as .zip), or have them included in .zip distribution package, in a separate folder? At least those from the website would be awesome! 

* Here I mean on packages like:

https://github.com/micronaut-projects/micronaut-core/releases/download/v1.0.3/micronaut-1.0.3.zip


* Or another link to demo templates at:

http://micronaut.io/download.html


Thanks!

**Comment by graemerocher** [comment]
There are some here https://github.com/micronaut-projects/micronaut-examples

**Comment by DuskoV** [comment]
Thank you, Graeme. If installing custom SSL procedure/development for CLI won't be addressed, I believe we can close this ticket.

**Comment by kenyee** [comment]
I get this on OSX as well:
```
ma-lt-kyee:ios kyee$ mn help --stacktrace
| Error Error occurred running Micronaut CLI: unable to find valid certification path to requested target (Use --stacktrace to see the full trace)
ma-lt-kyee:ios kyee$ 
```

**Comment by kenyee** [comment]
I also don't have a custom maven SSL cert or anything...just did "sdk install micronaut" (which grabbed 1.0.4) and ran "mn".
Would help if it could tell you what cert path it's looking for...or just use some sensible default..

**Comment by sf666** [comment]
Hey guys,

you have probably installed custom ssl certs within your operation system keystore. Therefore you have to tell `mn` using those by setting JAVA_OPTS (or MN_OPTS) environment variable ... 

For mac os :
```
export JAVA_OPTS="-Djavax.net.ssl.trustStoreType=KeychainStore -Djavax.net.ssl.trustStoreProvider=Apple"
```
