### ISSUE TITLE
Wrong field type when it GenericPlaceholderElement in inner classes

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#11162]
### Expected Behavior

Sample classes structure:
```java
@Controller("/test")
class TestController {
    @Get
    public HttpResponse<ResponseObject<List<Dto>>> endpoint() {
        return null;
    }
    
    public static class ResponseObject<T> {

        public T body;
    }

    public static class Dto {

        public Locale locale;
    }
}
```
`HttpResponse` is `io.micronaut.http.HttpResponse`

The problem with process type `HttpResponse<ResponseObject<List<Dto>>>`, more precisely, with type `ResponseObject<List<Dto>>`.

That's what I see, when process ResponseObject class:
![изображение](https://github.com/user-attachments/assets/f673247d-9180-4bb1-8ca0-2cbd82addd13)

As you see, generic type is correct - `type.getTypeArguments().get("T") = java.util.List`

But when I get field `body` I see type `java.lang.Object`, but must be  `java.util.List` with generic `Dto`

### Version

4.6.4

**Comment by altro3** [comment]
@dstepanov Please, look to this

**Comment by altro3** [comment]
@dstepanov Hm... interesting. this bug reproduced only  in real project. I can't reproduce it in tests!

**Comment by altro3** [comment]
@dstepanov Oh, I got this case! The problem is reproduced ONLY if the classes are internal!

**Comment by dstepanov** [comment]
The best would be to reproduce it in `ClassElementSpec`

**Comment by altro3** [comment]
@dstepanov Done! See: https://github.com/micronaut-projects/micronaut-core/pull/11173

**Comment by altro3** [comment]
Fixed here: https://github.com/micronaut-projects/micronaut-core/pull/11173
