### ISSUE TITLE
KSP: Aggregating annotation processors process as isolating

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#11215]
See discusion here: https://github.com/micronaut-projects/micronaut-openapi/issues/1776

The main problem is that in micronaut-openapi realized only AGGREGATING processors - and all works fine with java or kapt with incremental mode on. But when we use incremental processing with KSP - KSP process only changed files like an ISOLATING processor and because of it we can't use incremental mode with KSP and micronaut-openapi

### Version

4.6.5

**Comment by altro3** [comment]
@dstepanov Could you look to this, pls?

**Comment by dstepanov** [comment]
Can you debug and check that https://github.com/micronaut-projects/micronaut-core/blob/4.7.x/inject-kotlin/src/main/kotlin/io/micronaut/kotlin/processing/KotlinOutputVisitor.kt#L89 `aggregating` is set to true for your files?
