### ISSUE TITLE
[Kotlin] Json validation flow

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-core#1126]
Usually on deserialization we want to collect all validation errors and return them in response to the client. 
In order to catch all error the validation should be done before object creation.

If it will be done after object creation, in `init` block, than validation will be separated in 2 phases, first one will be validation regarding non-nullable field, because we cannot create objects if they have non-nullable properties. 
The second one will be to do structural validation: min/max values, length, regexp pattern, etc.

Example
`class Data(val name: String, val age: Int, val email: String)`
when we send a json `{"email": "xyz@xyz.com", "name": "A"}` we should return a response where to indicate that `age` can not be null and `name` size must be greater than 2, at once to send all the errors.

Also, structural validation will be great to do based on annotations and not in `init` block, something like JSR 303.
This will be useful for documentation generation, it is far easier to generate based on annotations.

How I see the flow:
1. Read annotations and generate validation rules. Can be done by 3rd party library. As result Map<Class, List<Rules>>
2. Parse json as a map
3. Apply validation rules. Validation rules can be passed as parameter in configuration.
4. Create object

This flow also will fit validation for Java.

**Comment by graemerocher** [comment]
I think we probably need more clarity on what you are trying to achieve. Maybe if you provide an example we can help solve your case.

**Comment by graemerocher** [comment]
Needs more feedback, if provided please reopen

**Comment by raderio** [comment]
I mean that is a solution to solve this issue https://github.com/FasterXML/jackson-module-kotlin/issues/58

Basically I tried to fix that for Kotlin validation should return all validation failure, not just first error regarding to null.

**Comment by raderio** [comment]
@graemerocher what do you think about this?
