### ISSUE TITLE
Add support for ReDoc

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-core#1127]
[ReDoc](https://github.com/Rebilly/ReDoc) - OpenAPI/Swagger-generated API Reference Documentation
It has more featured and nice UI for Swagger.

**Comment by hc-codersatlas** [comment]
ReDoc is just html/js. You can simply use it via adding it as a static resource in Micronaut. Works fine for me. If you need to further tune the parameters from server side, embed it with a server side view.

**Comment by raderio** [comment]
Ok, thanks.
