### ISSUE TITLE
KSP treating repository classes and custom annotations as dirty when unrelated files change

### ISSUE THREAD

**Issue by marvinkhristianzamora** [micronaut-projects/micronaut-core#11273]
### Expected Behavior

When the following prerequisites are all true

- `ksp.incremental` is  set to true
- `micronaut.processing.incremental` is set to true
- `micronaut.processing.annotations` is set to the correct package
- and ksp have processed all files in a previous run

When a class file is changed and the `kspKotlin` gradle task is triggered, ksp will only re-process the class file that changed (and any of its dependents, if any). 

### Actual Behaviour

When a class file is changed, even when there are no other files/classes dependent on it, ksp  re-processes all files annotated with `io.micronaut.data.annotation.Repository` (or `JdbcRepository`) and all classes dependent on them, as well as class files with a custom annotation and all classes  dependent on them. 

This makes a moderately-sized micronaut project have quite slow compile times because ksp has to do so much work even when only a single file is changed.

### Steps To Reproduce

1. Clone this repo https://github.com/marvinkhristianzamora/micronaut-ksp-incremental-bug-demo
2. Execute `./gradlew kspKotlin --profile`
3. Confirm all files are processed by ksp by `cat build/kspCaches/main/logs/kspDirtySet.log`. See all files are under the `Dirty:` section
4. Change the println string in `src/main/kotlin/demo/Application.kt`
5. Run ksp again `./gradlew kspKotlin --profile`
6. All Repository classes, as well as the custom annotation class is marked as "Dirty" again even though they were not changed

### Environment Information

- OS: Mac OS X 14.7 aarch64
- JDK: 21.0.4 (Eclipse Adoptium 21.0.4+7-LTS)

### Example Application

https://github.com/marvinkhristianzamora/micronaut-ksp-incremental-bug-demo

### Version

4.7.0

**Comment by altro3** [comment]
@dstepanov Maybe this bug related to this: https://github.com/micronaut-projects/micronaut-core/issues/11215

**Comment by marvinkhristianzamora** [comment]
@altro3 @dstepanov I maybe wrong but it seems #11215 is describing the opposite problem wherein micronaut-openapi does not support the isolating nature of ksp incremental processing. 

The behavior observed in this issue is that even with incremental processing enabled, ksp seems to behave in an "aggregating" way and rebuilds all files (even ones that were unaffected by changes).

**Comment by altro3** [comment]
@marvinkhristianzamora Yes, that's right, but it seems like the problem is the same - it feels like the Isolating Annotation Processors work like the Aggregating ones and vice versa - the Aggregating ones work like the Isolating ones

**Comment by dstepanov** [comment]
It looks like I misunderstood how `aggregating` is supposed to be marked. 
https://github.com/micronaut-projects/micronaut-core/pull/11318
