### ISSUE TITLE
POST without body using a declarative client doesn't send content headers

### ISSUE THREAD

**Issue by stefan-torstensson** [micronaut-projects/micronaut-core#1128]
When making a POST request without a body parameter on a declarative client the content length and content type request headers are not sent. 

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a declarative client with a post method without any body parameter
```java
@Client("${api.url}")
public interface ClientApi {
    @Post
    Single<String> getTime();
}
```
2. Execute the `getTime()` method and inspect the sent headers

### Expected Behaviour

The content-length and content-type content headers are sent even if there's no payload. I.e.
```
content-length: 0
content-type: application/json
```

### Actual Behaviour

No content headers are sent

### Environment Information

- **Operating System**: MacOS 10.14
- **Micronaut Version:** 1.0.3
- **JDK Version:** 11.0.1

### Example Application

https://github.com/stefan-torstensson/micronaut-declarative-client-post-without-body

**Comment by jameskleeh** [comment]
Should the content type header be sent? There is no content thus no type of that content

**Comment by jameskleeh** [comment]
https://stackoverflow.com/a/29784642/1264846

**Comment by stefan-torstensson** [comment]
Not sure, I guess one could argue both ways.
If there's no body there's nothing to decode so content-type doesn't really make any sense. On the other hand the spec doesn't state that it shouldn't be there. If I add an empty param, like in the provided example, both content length and content type are set even if the body is empty.

In our specific case we're working with an api (out of our control) which expects content type even if content length is zero, and otherwise returns "415 Unsupported Media Type".

**Comment by jameskleeh** [comment]
@stefan-torstensson Then in your case I think the api is out of spec

**Comment by graemerocher** [comment]
I think if an explicit content type is set with the low level client then that content type should be honoured even if the content length is zero.

This would allow falling back to use the low level client in case when you have no choice but to talk to an API that is not necessarily spec compliant. I'm not sure we should be changing the higher level client however.

**Comment by jameskleeh** [comment]
I've changed this so the content length will be set to 0
