### ISSUE TITLE
Changes to threading from Micronaut 4.4 to 4.5 with RolesFinder

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#11303]
### Discussed in https://github.com/micronaut-projects/micronaut-core/discussions/10924

I just realized why this would cause my thread to be interrupted--
Because io.micronaut.security.token.TokenAuthenticationFetcher#fetchAuthentication calls
```
        return Flux.fromIterable(tokens)
            .flatMap(tokenValue -> Flux.fromIterable(tokenValidators)
                .flatMap(tokenValidator -> tokenValidator.validateToken(tokenValue, request))
                .next()
    ...
```

So, both token validators actually get called (because of `Flux.fromIterable(tokenValidators)`) but then the second one gets discarded (because of `.next()`) and I'm 99% sure that Flux ends up interupting the thread of the second when only the first result is consumed and the subsequent results are cancelled.

In my case it's causing side effects because the RolesFinder implementation also calls Redis which has it's own threading, and that is also getting interupted, throwing exceptions.

So, I think the fix for my problem is to provide some mechanism to ensure that JwtTokenValidator and NimbusReactiveJsonWebTokenValidator don't both run at the same time, or at least order `NimbusReactiveJsonWebTokenValidator` before `JwtTokenValidator`. Disabling `JwtTokenValidator` is a start, but if someone ever needed to implement their own TokenValidator implementation, they would need some way to disable `NimbusReactiveJsonWebTokenValidator` as well; and `@Replace`-ing it won't work because it's marked `@Internal` and is package-private.

**Comment by kevin-wise** [comment]
https://github.com/micronaut-projects/micronaut-security/pull/1847 should fix this. 

Also, I wrote up the same issue in micronaut-security: https://github.com/micronaut-projects/micronaut-security/issues/1846. Sorry for the duplicate issue. I didn't realize this issue was opened.

**Comment by kevin-wise** [comment]
I think we can close this as fixed
