### ISSUE TITLE
4.6.3 Is Currently Not Included In the Version List On The Docs Page

### ISSUE THREAD

**Issue by jeffscottbrown** [micronaut-projects/micronaut-core#11329]
<img width="1556" alt="Screenshot 2024-11-08 at 10 14 30 AM" src="https://github.com/user-attachments/assets/1b2c0d46-6cc9-4f59-baa6-8e7292cacf15">

**Comment by jeffscottbrown** [comment]
Separate but related, at both https://docs.micronaut.io/4.6.3/guide/ and https://docs.micronaut.io/latest/guide/ currently version 4.6.3 of the docs are rendered.  Should latest point to 4.6.5 right now?

**Comment by jeffscottbrown** [comment]
I saw that the release of 4.7.0 was announced and 4.7.0 also isn't in the version list on the docs page.  Is there a step here that the team has an expectation that OCI is updating this?  Please let me know how we can help.

**Comment by sdelamo** [comment]
[we were hitting some limit issues in GitHub Pages](https://github.com/micronaut-projects/micronaut-docs/tree/gh-pages)

**Comment by jeffscottbrown** [comment]
> [we were hitting some limit issues in GitHub Pages](https://github.com/micronaut-projects/micronaut-docs/tree/gh-pages)

@sdelamo I am not sure if it is the same problem or not, but 4.7.2 is currently not showing up on the main docs page.

<img width="1234" alt="Screenshot 2024-12-18 at 9 44 02 AM" src="https://github.com/user-attachments/assets/a5a57548-c752-43ef-b64e-1dc6eb0ab98b" />

**Comment by jeffscottbrown** [comment]
4.7.2 is showing up now.
