### ISSUE TITLE
Not able to use HTTP and HTTPS together

### ISSUE THREAD

**Issue by hc-codersatlas** [micronaut-projects/micronaut-core#1137]
Hi, currently when you specify SSL and a port, SSL overrides the config.  Ideally it'd be good if Micronaut can support both HTTP and HTTPS together on different ports like a normal web server. HTTP can then be redirected to HTTPS if needed.

**Comment by saqib-ahmed** [comment]
Is this feature planned in upcoming releases?

**Comment by graemerocher** [comment]
Not currently, it is on the backlog but if you want to have a crack go for it!

**Comment by zendern** [comment]
So would the thought be that no matter what http would redirect to https?? Or is the request more of a i just want to be able to have both and use whatever i want?? cc @hc-codersatlas @saqib-ahmed 

Im working on a micronaut-acme project to integrate ACME (aka Let's Encrypt) into micronaut and to be able to accomplish HTTP-01 validation which needs to be able to call an http endpoint on the server. The spec will follow redirects so simply redirecting http -> https would satisfy what i need but I wanted to see if there was anything else that was behind this request and see if i could work that in.

**Comment by saqib-ahmed** [comment]
@zendern I would go with the second connotation. 
> i just want to be able to have both and use whatever i want

**Comment by graemerocher** [comment]
@zendern Thanks for the contribution. Nice work!
