### ISSUE TITLE
Documentation error for consul.client.config.format: FILE

### ISSUE THREAD

**Issue by gboersma** [micronaut-projects/micronaut-core#1138]
In Release 1.0.3 User Guide, it says to use the FILES setting for git2consul integration (section 8.1.2 Storing Configuration as File References). Actual setting in FILE (without the S).

**Comment by gboersma** [comment]
Created a pull request for this one. Closing this issue.

**Comment by BjoernAkAManf** [comment]
For those that were looking for the PR: #1139
