### ISSUE TITLE
HttpClient should not fail with non-standard http codes

### ISSUE THREAD

**Issue by ggerbaud** [micronaut-projects/micronaut-core#11383]
### Expected Behavior

I have to call a rest service that sometimes answer with weird http code like 551.
I expect to get a HttpClientResponseException with getResponse().code() == 551 and the body of the error.

### Actual Behaviour

Some part of code handle this HTTP 551 wrong (in my opinion).

[This line](https://github.com/micronaut-projects/micronaut-core/blob/4.7.x/http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java#L622) produce an IllegalArgumentException because getStatus call HttpStatus.valueOf. And then the original HttpClientResponseException is lost.

Same thing [here](https://github.com/micronaut-projects/micronaut-core/blob/4.7.x/http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java#L622).

Since the goal is to verify if the exception comes from an HTTP 404, the test could be `HttpStatus.NOT_FOUND.getCode() == ex.getResponse().code()` instead of using getStatus

### Version

4.6.5

**Comment by yawkat** [comment]
Thanks for the report!

**Comment by ggerbaud** [comment]
Thanks for the quick fix ;)
