### ISSUE TITLE
ClassCastException in BeanIntrospection.getReadProperty(String name, Class type)

### ISSUE THREAD

**Issue by erkieh** [micronaut-projects/micronaut-core#11395]
### Expected Behavior

get BeanReadProperty

### Actual Behaviour

ClassCastException: class io.micronaut.inject.beans.AbstractInitializableBeanIntrospection$BeanReadPropertyImpl cannot be cast to class io.micronaut.core.beans.BeanProperty (io.micronaut.inject.beans.AbstractInitializableBeanIntrospection$BeanReadPropertyImpl and io.micronaut.core.beans.BeanProperty are in unnamed module of loader 'app')

io.micronaut.core.beans.BeanIntrospection in getReadProperty at line 330

### Steps To Reproduce

I am trying to use BeanIntrospection.getIntrospection(value.javaClass).getReadProperty(field, klass) in Kotlin but get an exception because there is an invalid cast inside that method

### Environment Information

Kotlin 2.1 
Java 21 
Micronaut 4.7.1

### Version

4.7.1

**Comment by dstepanov** [comment]
Please create a reproducer

**Comment by erkieh** [comment]
I added some tests to PR

**Comment by sdelamo** [comment]
I assume this is closed via #11396
