### ISSUE TITLE
 HttpClient/Server: unable to use OffsetDateTime as query param

### ISSUE THREAD

**Issue by sschnabe** [micronaut-projects/micronaut-core#1141]
### Steps to Reproduce
1. Create an [api](https://github.com/sschnabe/micronaut-httpclient-offsetdatetime/blob/master/src/main/java/io/micronaut/issue/TimeApi.java#L14) with query param `OffsetDateTime`
2. Create declarative [client](https://github.com/sschnabe/micronaut-httpclient-offsetdatetime/blob/master/src/test/java/io/micronaut/issue/TimeClient.java#L6) based on the api
3. Create [server](https://github.com/sschnabe/micronaut-httpclient-offsetdatetime/blob/master/src/main/java/io/micronaut/issue/TimeController.java#L13) 
4. Use client for server (see [test](https://github.com/sschnabe/micronaut-httpclient-offsetdatetime/blob/master/src/test/java/io/micronaut/issue/TimeControllerTest.java#L32-L37))

### Expected Behaviour
`OffsetDateTime` is mapped with Jackson to  ISO8601 format (depending on Jackson config)

### Actual Behaviour
Client generates value for query param like: `Sun,%2020%20Jan%202019%2010:55:53%20+0100`:
```
11:03:15.714 [nioEventLoopGroup-1-3] DEBUG io.micronaut.issue - Sending HTTP Request: GET /offset?time=Sun,%2020%20Jan%202019%2011:03:15%20+0100
11:03:15.739 [nioEventLoopGroup-1-3] DEBUG io.micronaut.issue - Chosen Server: localhost(57311)
11:03:15.817 [nioEventLoopGroup-1-4] ERROR i.m.h.s.n.c.UnsatisfiedRouteHandler - GET /offset?time=Sun,%2020%20Jan%202019%2011:03:15%20+0100 (Bad Request): Required argument [OffsetDateTime time] not specified
```
This is not created by Jackson configurable in [application.yaml](https://docs.micronaut.io/latest/guide/index.html#clientJackson). I also tried to create a custom [TypeConverter](https://github.com/sschnabe/micronaut-httpclient-offsetdatetime/blob/master/src/main/java/io/micronaut/issue/Application.java#L20-L35) but then i have issues with url encoding:
```
10:59:31.830 [nioEventLoopGroup-1-3] DEBUG io.micronaut.issue - Sending HTTP Request: GET /offset?time=2019-01-20T10:59:31.711244+01:00
10:59:31.831 [nioEventLoopGroup-1-3] DEBUG io.micronaut.issue - Chosen Server: localhost(38592)
10:59:31.903 [nioEventLoopGroup-1-4] ERROR io.micronaut.issue.Application - Unable to parse 2019-01-20T10:59:31.711244 01:00
```

### Environment Information
- **Operating System**: Ubuntu
- **Micronaut Version:** 1.0.3
- **JDK Version:** openjdk 11.0.1 2018-10-16

### Example Application
see [micronaut-httpclient-offsetdatetime](https://github.com/sschnabe/micronaut-httpclient-offsetdatetime)

**Comment by jameskleeh** [comment]
Seems like an issue with either encoding or decoding that the `+` symbol isn't preserved
