### ISSUE TITLE
Optimize Jackson access with Afterburner Module

### ISSUE THREAD

**Issue by hc-codersatlas** [micronaut-projects/micronaut-core#1146]
Hi Jackson has a module called [Afterburner](https://github.com/FasterXML/jackson-modules-base/tree/master/afterburner) that speeds up access for POJO. This would help make Micronaut faster. There are places where ObjectMapper is created and cannot be customized, so would be great if Micronaut can add support for the module. Thanks!

**Comment by hc-codersatlas** [comment]
Thanks, maybe just a documentation issue. Noted.

**Comment by graemerocher** [comment]
To be clear, we call `findAndRegisterModules` here https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/jackson/ObjectMapperFactory.java#L88
