### ISSUE TITLE
Issue with PgPool bean when executing aws lambda function test remotely (works locally)

### ISSUE THREAD

**Issue by karlazzam** [micronaut-projects/micronaut-core#1152]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. git clone git@github.com:karlazzam/lambda-pgpool-micronaut-issue.git
2. run this client test locally, it works!
https://github.com/karlazzam/lambda-pgpool-micronaut-issue/blob/master/src/test/java/com/micronaut/PocFunctionTest.java#L14
3. Create a new function on AWS similar to this guide under step 4 (4 Deploy to AWS Lambda)
http://guides.micronaut.io/micronaut-function-aws-lambda/guide/index.html
4. Add test with this payload: (same as local client test in the test class)
```
{
    "name" : "Philadelphia 76ers"
}

```
5. Run the test

### Expected Behaviour
Test should pass, as it did locally with the Function Client 

### Actual Behaviour
Error stack trace:
https://raw.githubusercontent.com/karlazzam/lambda-pgpool-micronaut-issue/master/error_log.txt
### Environment Information
- **Operating System**: aws lambda 
- **Micronaut Version:** 1.0.3
- **JDK Version:** 1.8

### Example Application
- https://github.com/karlazzam/lambda-pgpool-micronaut-issue

### Full description of the error

I uploaded a function to aws lambda without any database connections or reactive postgres libraries/dependencies and it worked following this guide:
http://guides.micronaut.io/micronaut-function-aws-lambda/guide/index.html

I then added the dependency below to add a DAO layer which will fetch data from a postgres database
```
    <dependency>
      <groupId>io.micronaut.configuration</groupId>
      <artifactId>micronaut-postgres-reactive</artifactId>
      <scope>compile</scope>
    </dependency>
```

I tested it locally using the micronaut's local testing method via declaring a function with a @FunctionClient and then starting the client via the EmbeddedServer bean. It worked locally. I then uploaded the function to AWS the same way I did prior following the aws lambda guide. This time with the dependencies with PgPool, it did not work. The error stacktrace is posted above.

**Comment by karlazzam** [comment]
```
Caused by: java.lang.IllegalStateException: Failed to create cache dir
	at io.vertx.core.impl.FileResolver.setupCacheDir(FileResolver.java:312)
	at io.vertx.core.impl.FileResolver.<init>(FileResolver.java:87)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:186)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:145)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:38)
	at io.vertx.core.Vertx.vertx(Vertx.java:88)
	at io.reactiverse.pgclient.PgClient.pool(PgClient.java:82)
	at io.reactiverse.reactivex.pgclient.PgClient.pool(PgClient.java:121)
	at io.micronaut.configuration.postgres.reactive.PgPoolClientFactory.createClient(PgPoolClientFactory.java:82)
	at io.micronaut.configuration.postgres.reactive.PgPoolClientFactory.client(PgPoolClientFactory.java:64)
	at io.micronaut.configuration.postgres.reactive.$PgPoolClientFactory$ClientDefinition.build(Unknown Source)
```
reading this error stack trace, could it be an issue with the PgPoolClientFactory bean not finding the DB properties when deployed to aws lambda?

https://github.com/micronaut-projects/micronaut-sql/blob/master/postgres-reactive/src/main/java/io/micronaut/configuration/postgres/reactive/PgPoolClientFactory.java#L82

https://github.com/micronaut-projects/micronaut-sql/blob/master/postgres-reactive/src/main/java/io/micronaut/configuration/postgres/reactive/PgPoolClientFactory.java#L64

seems vertx is null since its hitting L64

**Comment by graemerocher** [comment]
Seems to me postgres reactive client is trying to write to the file system which is not allowed on lambda

**Comment by graemerocher** [comment]
Looks like you can define your own `Vertx` bean to override the default if you wish:

```
@Factory
class VertxFactory {
         @Bean
        @Singleton
        Vertx vertx() {
             // customize here
        }
}
```

**Comment by karlazzam** [comment]
@graemerocher thanks yeah that worked

```
@Factory
public class VertXFactory {
    @Bean
    @Singleton
    Vertx vertx() {
        System.setProperty("vertx.disableFileCPResolving", "true");
        return Vertx.vertx();
    }
}
```
adding it as a JVM param also works:

![image](https://user-images.githubusercontent.com/26029285/51649415-54ae5000-1f52-11e9-8d59-3c8361a7e8c4.png)
