### ISSUE TITLE
Paths with queryparameters generates incorrect open-api yaml

### ISSUE THREAD

**Issue by andersmartini** [micronaut-projects/micronaut-core#1170]
### Steps to Reproduce

1. define a endpoint that accepts query parameters
2. add Swagger to the project
3. build the project to generate the open-api yaml documentation

### Expected Behaviour
The generated open-api yaml should be valid.

### Actual Behaviour
the "path" field corresponding to the endpoint with queryparameters is incorrect (it contains curlybrackets with the query parameters)

the "in" field under each parameter has the value "path" instead of "query".

read more on correct formatting here: https://swagger.io/docs/specification/describing-parameters/#query-parameters

### Environment Information

- **Operating System**: 
- Tested on Ubuntu 18.04 LTS 
- **Micronaut Version:** 
  1.0.3
- **JDK Version:** 
11
### Example Application
https://github.com/andersmartini/helloQueryparams
there is a folder in the root directory named swagger-yaml. in it you'll find current and corrected yaml files for your convinience. 

You may also just run gradle clean build to generate the yaml.

**Comment by graemerocher** [comment]
Related discussion https://github.com/OAI/OpenAPI-Specification/issues/1054
