### ISSUE TITLE
Add Thymeleaf Dialect support

### ISSUE THREAD

**Issue by ascasso** [micronaut-projects/micronaut-core#1180]
Add support for Thymeleaf Dialects. 

Currently there is no way to add a dialect to the TemplateEngine.

A possible solution is adding an optional constructor argument to ThymeleafViewsRenderer and then adding the dialect(s) to in the initializeTemplateEngine() method.
An example of this approach:
https://github.com/ascasso/micronaut-core/commit/5d7f820ef767784f3fa0ee15b8d1f07b825472a2

**Comment by jameskleeh** [comment]
https://github.com/micronaut-projects/micronaut-core/tree/views_refactor in progress

**Comment by jameskleeh** [comment]
Completed by https://github.com/micronaut-projects/micronaut-core/pull/1250

**Comment by cosmin-marginean** [comment]
Can I ask what the solution is here? We're looking at loading the layout dialiect (https://www.thymeleaf.org/doc/articles/layouts.html, Section 4) but I'm not certain how we can configure this with Micronaut Views (couldn't find any docs for this)

**Comment by deenar** [comment]
I agree with @cosmin-marginean, this issue should be reopened. the fix #1250 does not add support for adding dialects.

**Comment by jameskleeh** [comment]
@cosmin-marginean @deenar That PR made it possible for the dialect to be set because prior to that the engines themselves were not beans. You can create a BeanCreatedEventListener for the `TemplateEngine` and set the dialect

**Comment by jameskleeh** [comment]
Any documentation improvement PRs are welcome https://github.com/micronaut-projects/micronaut-views

**Comment by Brutus5000** [comment]
> @cosmin-marginean @deenar That PR made it possible for the dialect to be set because prior to that the engines themselves were not beans. You can create a BeanCreatedEventListener for the `TemplateEngine` and set the dialect

I tried that and the onInitialized event never fires. Sorry I just started working on Micronaut, so maybe you have an idea what I'm doing wrong?

```kotlin
@Singleton
class ThymeleafDialectLoader : BeanInitializedEventListener<TemplateEngine> {
    override fun onInitialized(event: BeanInitializingEvent<TemplateEngine>): TemplateEngine =
        event.bean.apply {
            addDialect(LayoutDialect())
        }
}
```


An "eager loading" approach however works:

```kotlin
@Singleton
@Context
class ThymeleafDialectLoader(val templateEngine: TemplateEngine) {

    @PostConstruct
    fun setDialect() {
        templateEngine.addDialect(LayoutDialect())
    }
}
```

**Comment by Brutus5000** [comment]
Soo as it turns out my eager loading approach crashes the application when compiled into a native graalvm image :cry:
