### ISSUE TITLE
Spring data support

### ISSUE THREAD

**Issue by reitzmichnicht** [micronaut-projects/micronaut-core#1193]
Hi

One major missing feature for Micronaut for us is the missing Spring Data support.
Are there any plans to get a smooth integration instead of using GORM? Sadly I got no satisfying integration to work as the creation of a Spring Data Repository inside a Bean Factory needs an active Hibernate Session context which is not available there. 

Kind regards,
Michael

**Comment by graemerocher** [comment]
A similar feature is planned, in fact I will be working on it soon but just replicating or supporting Spring Data directly is not something we want to do since the implementation is everything Micronaut tries to avoid (massive use of reflection, runtime proxies, high memory overhead etc.).

**Comment by henriquelsmti** [comment]
> A similar feature is planned, in fact I will be working on it soon but just replicating or supporting Spring Data directly is not something we want to do since the implementation is everything Micronaut tries to avoid (massive use of reflection, runtime proxies, high memory overhead etc.).

Any news about this?

**Comment by cemo** [comment]
Another lately emerging project is [spring-data-jdbc](https://github.com/spring-projects/spring-data-jdbc). It is similar to [ jdbi](http://jdbi.org/). We will definitely need a simple effective solution. (I don't like hibernates and other jpa implementations.)

**Comment by zulq** [comment]
Another possible solution may be Panache from [Panache orm](https://quarkus.io/guides/hibernate-orm-panache-guide).

**Comment by graemerocher** [comment]
The feature is in progress, we will update this issue once we have something to show

**Comment by RaviH** [comment]
Can't wait. A lot of our projects use Spring Data. Any way to keep spring data in Spring context and port rest to micronaut? Kind of like running 2 contexts?

**Comment by graemerocher** [comment]
@zulq Panache is limited to Hibernate and seems to encourage the use of static methods, so no.

Just an update, the JPA implementation of this is done and we will be open sourcing it soon, I am working on the raw SQL implementation. As a survey please indicate which backends you are interested in support for:

* JPA
* SQL
* MongoDB
* Neo4j
* Cassandra

**Comment by SlyDen** [comment]
1) SQL, JPA (though I don't like it, but it is used widely)
2) MongoDB and Neo4j can be interesting for wide adoption

**Comment by cemo** [comment]
I am on the side of anti-jpa. Please provide a simply solution based on SQL. 

+1 for SQL.

**Comment by zulq** [comment]
1. SQL with crud and pagination features.
2. JPA

**Comment by graemerocher** [comment]
First version will include JPA and SQL support, afterwards we will evolve it from there.

**Comment by cemo** [comment]
@graemerocher can you little expand what is SQL support? Is it annotation based implementation?

**Comment by henriquelsmti** [comment]
I agree with @zulq, SQL with template CRUD and JPA

**Comment by graemerocher** [comment]
@cemo Currently plan for SQL is annotations plus functional interfaces for customization. It will be a simple data mapper and won't support any ORM concepts (lazy loading, entity proxies etc.)

**Comment by RaviH** [comment]
JPA
SQL
mongo

**Comment by ralmeida7** [comment]
1. JPA
2. SQL

**Comment by dstepanov** [comment]
1. SQL
2. JPA

Is there planned release version for this feature?

I would like to try it and give feedback if you are interested.

**Comment by graemerocher** [comment]
We are working on it and will announce something soon (next month or so)

**Comment by cemo** [comment]
@graemerocher SQL support will be included in 1.2.0?

**Comment by graemerocher** [comment]
No 1.2 is already RC stage likely 1.3

**Comment by TobiasBales** [comment]
TBH for me this is one of the bigger things holding me back from fully committing. Very happy to see this getting integrated

**Comment by graemerocher** [comment]
We have Open Sourced this feature here https://github.com/micronaut-projects/micronaut-predator if folks want to try this out. 

Also see associated announcement https://objectcomputing.com/news/2019/07/18/unleashing-predator-precomputed-data-repositories

**Comment by zulq** [comment]
Trying out to migrate jdbi sample to predator-jdbc with MySQL but getting an error. Where should I raise an issue?

**Comment by graemerocher** [comment]
Here please https://github.com/micronaut-projects/micronaut-predator/issues

**Comment by jameskleeh** [comment]
Going to close this as we have no plans to integrate with Spring Data given the existence of Micronaut Data
