### ISSUE TITLE
CachePut only works with async=true

### ISSUE THREAD

**Issue by luckyswede** [micronaut-projects/micronaut-core#1197]
Basically `@CachePut` only works if `async=true`, but only if it is defined in combination with `@CacheConfig` on the class level.
For examples see README in the github repo linked below. 

### Task List

- [*] Steps to reproduce provided
- [*] Stacktrace (if present) provided
- [*] Example that reproduces the problem uploaded to Github
- [*] Full description of the issue provided (see below)

### Steps to Reproduce

See README in the github repo linked below. 

### Expected Behaviour
The default `async=false` should not cause the method to return something else than the return value from the method.
If I modify `serviceA.get(keyA)` to `serviceA.get(keyA).map(s -> s)` the following error is thrown:
```
ERROR i.m.h.n.stream.HttpStreamsHandler - Error occurred writing stream response: class io.reactivex.internal.operators.flowable.FlowableJust cannot be cast to class java.lang.String (io.reactivex.internal.operators.flowable.FlowableJust is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class io.reactivex.internal.operators.flowable.FlowableJust cannot be cast to class java.lang.String (io.reactivex.internal.operators.flowable.FlowableJust is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	...
 ```

Also, as I understand it it should be enough to declare `@CachePut` on a method, with no other annotations required.

### Environment Information

- **Operating System**: Mac OS
- **Micronaut Version:** 1.0.4
- **JDK Version:** 11

### Example Application

https://github.com/luckyswede/micronaut-cachetest

**Comment by jameskleeh** [comment]
> it should be enough to declare @CachePut on a method, with no other annotations required

Yes, but you have to declare what cache to put the data on by setting the value of `@CachePut`. That is why C and D are not putting data into the cache. I have validated that adding that causes those services to behave the same as A.

As far as why returning a `Single` with the default `async = false` is not returning the correct value, that is in fact a bug

**Comment by graemerocher** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-core/commit/2ffd83bcd16a15523d2e3bb4178891bc280f2456

**Comment by luckyswede** [comment]
Thanks guys, great job
