### ISSUE TITLE
No embedded container found. Running as CLI application with function-application as Graal native-image

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#1199]
It is not possible to execute a function as a Graal native-image.

- `git clone https://github.com/micronaut-guides/micronaut-function-aws-lambda`
- `cd micronaut-function-aws-lambda/complete/vies-vat-validator-graal`
- `git checkout upgrade-1.0.4`
- Use GraalVM RC11
- `./gradlew assemble`
- `java -cp build/libs/vies-vat-validator-0.1-all.jar io.micronaut.graal.reflect.GraalClassLoadingAnalyzer`
- `./build-native-image.sh`

The `build-native-image.sh` script still uses `-H:-UseServiceLoaderFeature` because of https://github.com/oracle/graal/issues/947 that has been fixed in GraalRC13-dev.

Execute the function as a native-image:
```
$ echo '{"memberStateCode":"es", "vatNumber":"B99286353"}' | ./vies-vat-validator
12:35:30.255 [main] INFO  io.micronaut.runtime.Micronaut - No embedded container found. Running as CLI application
```

I've also tried without `-H:-UseServiceLoaderFeature` and GraalRC13-dev and the behavior is the same.

**Comment by ilopmar** [comment]
I've realized that the entry point was wrong. Instead of `-H:Class=function.graal.Application` it needs to be `-H:Class=io.micronaut.function.executor.FunctionApplication`. With this change everything works as expected.

I'm closing the issue and I'll see if there is anything we can do in the profiles to use the right class for functions.

**Comment by mageddo** [comment]
Also make sure you are compiling/running gradle with graalvm not the regular JDK otherwise micronaut will not generate `reflect.json` and the process will not work

**Comment by nhoughto** [comment]
This can also be because you have disabled ServiceLoaderFeature
`-H:-UseServiceLoaderFeature`

I had an existing project that was converting to micronaut and this caused me problems, micronaut uses service loader internally, so you can't disable it.
