### ISSUE TITLE
Unable to use Java Websocket Client with authentication

### ISSUE THREAD

**Issue by stoxalpha** [micronaut-projects/micronaut-core#1208]
First of one of the most awesome Projects I have seen. I am able to use the HttpClients with authentication but unable to do this for WebSocketClient.

What I need to do. Any Help will be really appreciated. Not able to find many examples yet on the web.
#Sample cURL call - only use for testing
#Please note that you may get disconnected after some time
curl \
-H 'authorization: Bearer {your_access_token}' \
-H 'x-api-key: {your_api_key}' \
-H "Connection: Upgrade" \
-H "Upgrade: websocket" \
-H "Sec-WebSocket-Key: {random-number}" \
-H "Sec-WebSocket-Version: 13" \
--include \
--no-buffer \
'https://ws-api.upstox.com/?apiKey={your_api_key}&token={your_access_token}'

Warm Regards,
Sudeep Batra

**Comment by sdelamo** [comment]
Hello @algotradersxyz 

I understand that you are trying to connect to a Websocket server published by a non micronaut application from a Micronaut app.  I think you could define a bean such as:

```
@ClientWebSocket("/")
abstract class WsApiUpStoxClientWebSocket implements AutoCloseable {
```

Then create a `RxWebSocketClient`

`RxWebSocketClient wsClient = embeddedServer.applicationContext.createBean(RxWebSocketClient, 'https://ws-api.upstox.com')`

and connect supplying the params:

```
Map<String, Object> parameters = new HashMap<>();
parameters.put("apiKey", "XXXXX");
parameters.put("token", "YYYYY");
WsApiUpStoxClientWebSocket clientWebSocket = wsClient.connect(WsApiUpStoxClientWebSocket.class, parameters)
```

Check the java docs for more methods:

https://docs.micronaut.io/latest/api/io/micronaut/websocket/RxWebSocketClient.html

I have added a commit with tests for security + Websockets:

You can see the PR here: https://github.com/micronaut-projects/micronaut-core/pull/1293

Please, let me know if this solves your problem and we can close this issue.

**Comment by sdelamo** [comment]
I am closing the issue. Please, @stoxalpha reopen the issue if you are still experiencing issues.
