### ISSUE TITLE
HttpFilter when you are using multiple third party libraries requiring Auth

### ISSUE THREAD

**Issue by algotradersxyz** [micronaut-projects/micronaut-core#1212]
Currently HttpClientFilter can be used to add authorization based on @Filter("path") but
a) What if there are multiple client libraries requiring different Authorization params
b) The path for a third party library may not be under the control and applying /** maybe a bad idea.

Wouldn't it be better if you can write Filter based on Client Hosts ?

Warm Regards,
Sudeep Batra

**Comment by algotradersxyz** [comment]
Hey @jameskleeh what i was asking is let's say I have 2 Different Api's that I was connecting to: ETrade and RobinHood Api's requiring different Auth's and do not want to separate it and have it as part of the same app. Now both of them would require different Auth so how would you differentiate ?

**Comment by jameskleeh** [comment]
I don't understand "do not want to separate it and have it as part of the same app". Surely those 2 services would have different URLs so you can filter based on that

**Comment by algotradersxyz** [comment]
Hey Thanks @graemerocher that works perfectly. Thanks for all your help.
