### ISSUE TITLE
Add option to disable environment deduction

### ISSUE THREAD

**Issue by tunovic** [micronaut-projects/micronaut-core#1244]
Hi,

I would like to request a feature to disable the environment deduction.

Case:
Execution of tests using Jenkins pipeline on Kubernetes will activate `k8s` environment leading in undesirable overrides of default/test environment settings because of existence of k8s environment in production sources:
`11:32:31.293 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test, k8s, cloud, build-local]`

As a developer
I would like to disable the environment deduction
So that it doesn't potentially lead to hidden undesirable behavior

Given I have started the Micronaut application
When `micronaut.env.deduction` is set to false
Then the environment deduction is not executed

Given I have started the Micronaut application
When `micronaut.env.deduction` is set to true (default)
Then the environment deduction is executed

**Comment by alvarosanchez** [comment]
Cloud platform detection can be skipped by giving a value to the `micronaut.cloud.platform` system property, eg:

    -Dmicronaut.cloud.platform=BARE_METAL

The possible values are documented at https://docs.micronaut.io/latest/guide/index.html#cloudConfiguration

**Comment by tunovic** [comment]
I have provided `<argLine>-Dmicronaut.cloud.platform=BARE_METAL</argLine>` option to the maven-surefire-plugin but doesn't make the difference.

In my opinion this cloud platform detection should be off by default as it may lead to hidden undesirable behavior. For example the one I am facing. No to mention unknowingly connecting to the wrong environment . I think we are perfectly capable in setting the correct environment.

**Comment by graemerocher** [comment]
Disabling it has broad implications for the builtin configurations that rely on being enabled for a particular environment, whether that be GCP, Kubernetes or whatever. Apart from that it would be a breaking change to current behaviour.

I am not sure exactly what you are doing that would cause problems, but there are several options you have in front of you to resolve whatever the issue may be including defining your own environment names (eg. `prod`) and don't use `k8s` or whatever you are relying on right now for activating production beans

We are certainly willing to consider adding the option to disable it though and making it easier to disable it for tests certainly makes sense to me.
