### ISSUE TITLE
Add support for Moshi as Json library

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-core#1255]
Moshi is very fast json library, will be very useful to add support for this library.

https://github.com/square/moshi

**Comment by jameskleeh** [comment]
Does it support non blocking serialization? I wasn't able to see any mention of it with a quick glance at the readme

**Comment by raderio** [comment]
What do you mean by non blocking deserialization?

**Comment by graemerocher** [comment]
Jackson allows parsing large JSON streams without using blocking IO. See https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/jackson/parser/JacksonProcessor.java

This helps Micronaut scale better, hence why it was chosen as the default. Support for something like Moshi can of course be added, but it may not be optimal if it doesn't support a non-blocking API.

**Comment by raderio** [comment]
I think it uses non-blocking IO
> Built on Okio
Moshi uses Okio for simple and powerful I/O. It’s a fine complement to OkHttp, which can share buffer segments for maximum efficiency.

**Comment by raderio** [comment]
Can you please elaborate, please, what is your use-case for "non blocking deserialization"? What exactly are you trying to achieve?

**Comment by JakeWharton** [comment]
Moshi uses blocking I/O

**Comment by jameskleeh** [comment]
@raderio Based on the information provided, we likely will not add support for this library, however if you or anyone else wants to implement support for it in an external library that would be fine.

**Comment by raderio** [comment]
@jameskleeh can you please give a point from which to start to implement this module?
