### ISSUE TITLE
Multi-language documentation: Java, Groovy and Kotlin

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#1265]
The mechanism is in place to include Multi-language snippets in Java, Kotlin and Groovy. An example can be found here:

https://github.com/micronaut-projects/micronaut-core/blob/master/src/main/docs/guide/quickStart/creatingServer.adoc

The syntax is for example:

```
snippet::io.micronaut.docs.server.intro.HelloController[tags="imports,class"]
```

With the sources looked for in `test-suite/src/test/java` for Java, `test-suite-kotlin/src/test/kotlin` for Kotlin and `test-suite-groovy/src/test/groovy` for Groovy.

Now the bigger task is to gradually migrate all of the code snippets that are only in 1 language to support all 3 languages of which there are many. We will leave this issue open to track that until all snippets are migrated. Contributions / PRs welcome.

**Comment by willbuck** [comment]
Beginning work to add some Kotlin samples today
