### ISSUE TITLE
Improve Kotlin Coroutine support

### ISSUE THREAD

**Issue by ahmedlafta** [micronaut-projects/micronaut-core#1270]
It would be nice to have improved support for kotlin coroutines as controller and declarative http client return types. 

Currently one way to use kotlin coroutines is converting to/from a [CompletableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html), which tends to get verbose and may not be a recommended approach. See [Asynchronous Programming Styles](https://github.com/Kotlin/KEEP/blob/master/proposals/coroutines.md#asynchronous-programming-styles) for more context.

I'm not quite sure what the implementation requirements would be, but more so just creating the issue to start the conversation.

**Comment by jameskleeh** [comment]
@ahmedlafta It seems that you can return a reactive stream that works like a coroutine natively? You don't have to do manual conversion. See https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/coroutines-guide-reactive.md

**Comment by graemerocher** [comment]
Duplicates https://github.com/micronaut-projects/micronaut-kotlin/issues/4

**Comment by ahmedlafta** [comment]
Whoops, i had forgot to check the subprojects. I can close this issue.

@jameskleeh thanks for the link. I'll look into that and update the other issue if i can come up with any examples.
