### ISSUE TITLE
StreamingHttpClient.exchangeStream hangs while retrieving response

### ISSUE THREAD

**Issue by vemilyus** [micronaut-projects/micronaut-core#1286]
As the title says, I consistently experience a hang while exchanging streams of data.

The request data is a multipart request with some random bytes which are all read correctly by the controller.

A response is created by the controller which is encoded by the `RoutingInBoundHandler` but after that the client hangs.

I have created an example application that perfectly illustrates this.

https://github.com/vemilyus/mn-exchange-stream-hang

UPDATE: I've checked using Wireshark and the response is sent correctly, so it's most likely an issue with the client or underlying IO implementation

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run tests for example application
2. Observe hang

### Expected Behaviour

Test should complete normally

### Actual Behaviour

Test hangs at line 59 (`responseFlowable.blockingLast()`) while retrieving response.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.1.0.BUILD-SNAPSHOT
- **JDK Version:** 1.8.0_161

### Example Application

https://github.com/vemilyus/mn-exchange-stream-hang

**Comment by jameskleeh** [comment]
Why are you using `exchangeStream` if you aren't streaming multiple items?

**Comment by vemilyus** [comment]
Isn't that beside the point? I should be able to transfer one item or multiple, it doesn't really matter.

**Comment by charliewolf** [comment]
We are experiencing the same issue

**Comment by jisikoff** [comment]
Any news on this one? I can't get this working either
