### ISSUE TITLE
Improve the documentation of Bean Factories regarding @Bean's default scope

### ISSUE THREAD

**Issue by codependent** [micronaut-projects/micronaut-core#1288]
As I Spring user, I was really confused by the fact that @Bean methods in a @Factory produced prototype-scoped instances instead of singletons:

```
@Factory
class MyFactory {

    @Bean
    fun myPing(): Ping {
        return Ping(23, "myPing")
    }

}
```
In a Controller I got the myPing object every request and, surprisingly it was a new instance every time:
```
@Controller("/ping")
class PingController(private val pingService: PingService) {
    @Inject
    private lateinit var applicationContext : ApplicationContext

    @Get("/")
    fun getPings(@Header("Host") host: String): List<Ping> {
        val bean = applicationContext.getBean(Ping::class.java)
        ...
    }
```
Then I added @Singleton and I got the expected behaviour
```
    @Bean
    @Singleton 
    fun myPing(): Ping {
        return Ping(23, "myPing")
    }
```
In my opinion there are two points that should be clearer in the docs:

1) In 3.7 Bean factories the example shows @Bean + @Singleton. I would explicitly state that @Bean without @Singleton produces prototype scoped beans:

```
@Factory
class EngineFactory {

    @Bean
    @Singleton
    Engine v8Engine(CrankShaft crankShaft) {
        new V8Engine(crankShaft)
    }
} 
```

2) There are examples of @Factory where @Bean is not used, but only @Singleton. Why???
```
@Factory
public class BookFactory {

    @Singleton
    Book novel() {
        return new Book("A Great Novel");
    }

    @Singleton
    TextBook textBook() {
        return new TextBook("Learning 101");
    }
}
```

**Comment by graemerocher** [comment]
To cover the questions.

1. Micronaut != Spring. In Spring the default was chosen as singleton because the performance of prototype instantiation is poor. However in many DI systems including `javax.inject` the default scope is not singleton. Micronaut is closer to CDI than Spring is this respect.
2. It seems obvious that a `Singleton` is also a `Bean` so why require the annotation?

**Comment by codependent** [comment]
1. Well since Micronaut is heavily inspired by Spring this may confuse people like me who switch to Micronaut expecting that behaviour. That's why I suggested making it explicit in the docs.

2. I agree with you so there's no point in using them together. The point is in different parts of the documentation sometimes there's both @bean + @singleton ([Bean Factory](https://docs.micronaut.io/1.1.0.M1/guide/index.html#factories)) and in other cases only @singleton ([Bean replacement](https://docs.micronaut.io/1.1.0.M1/guide/index.html#replaces) - BookFactory.java), which could be confusing...
