### ISSUE TITLE
Sort routes endpoint

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#1295]
The output of the Routes endpoint is not sorted. Would be nice to sort it for better readability of the routes.

Same goes for beans and loggers endpoint btw.

**Comment by marceloverdijk** [comment]
@graemerocher Would you prefer the sorting in the endpoint or higher up in e.g. `io.micronaut.web.router.Router#uriRoutes()`?

**Comment by graemerocher** [comment]
in the endpoint
