### ISSUE TITLE
No embedded container found. Running as CLI application executing JAR

### ISSUE THREAD

**Issue by marcosflobo** [micronaut-projects/micronaut-core#1299]
### Description
Following the official Micronaut hellow world, it does work running the application with gradle but running the resultant JAR file

### Steps to Reproduce

1. Follow up the official HelloWorld tutorial for the first micronaut application https://guides.micronaut.io/creating-your-first-micronaut-app/guide/index.html
2. Include slf4j-simple missing dependency in build.gradle (see below)
3. In build.gradle, override JAR gradle task to include missing manifest
4. Run `./gradlew jar`
5. Run resultant JAR file `java -jar build/libs/complete-0.1.jar`

build.gradle
```
plugins {
    id "io.spring.dependency-management" version "1.0.6.RELEASE"
    id "com.github.johnrengelman.shadow" version "4.0.2"
    id "application"
    id "java"
    id "net.ltgt.apt-eclipse" version "0.20"
    id "net.ltgt.apt-idea" version "0.20"
}

version "0.1"
group "example.micronaut"

repositories {
    mavenLocal()
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
}

dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:1.1.0.BUILD-SNAPSHOT'
    }
}

configurations {
    // for dependencies that are needed for development only
    developmentOnly 
}

dependencies {
    annotationProcessor "io.micronaut:micronaut-inject-java"
    annotationProcessor "io.micronaut:micronaut-validation"
    compile "io.micronaut:micronaut-inject"
    compile "io.micronaut:micronaut-validation"
    compile "io.micronaut:micronaut-runtime"
    compile "io.micronaut:micronaut-http-client"
    compile "io.micronaut:micronaut-http-server-netty"
    // https://mvnrepository.com/artifact/org.slf4j/slf4j-simple
    compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'
    runtime "ch.qos.logback:logback-classic:1.2.3"
    testAnnotationProcessor "io.micronaut:micronaut-inject-java"
    testCompile "org.junit.jupiter:junit-jupiter-api"
    testCompile "io.micronaut.test:micronaut-test-junit5"
    testRuntime "org.junit.jupiter:junit-jupiter-engine"
}

shadowJar {
    mergeServiceFiles()
}

run.classpath += configurations.developmentOnly
test.classpath += configurations.developmentOnly
run.jvmArgs('-noverify', '-XX:TieredStopAtLevel=1')

mainClassName = "example.micronaut.Application"
// use JUnit 5 platform
test {
    useJUnitPlatform()
}
tasks.withType(JavaCompile){
    options.encoding = "UTF-8"
    options.compilerArgs.add('-parameters')
}

jar {
    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
    manifest {
        attributes("Built-By": System.properties['user.name'])
        attributes("Created-By": "Gradle ${gradle.gradleVersion}")
        attributes("Build-Jdk": System.properties['java.version'])
        attributes('Main-Class': mainClassName)
    }
}
```

### Expected Behaviour

Same as running the application using `./gradlew run`
```
SLF4J: Class path contains multiple SLF4J bindings.
...
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
[main] INFO io.micronaut.runtime.Micronaut - Startup completed in 566ms. Server Running: http://localhost:8080
```

### Actual Behaviour

```
java -jar build/libs/complete-0.1.jar 
[main] INFO io.micronaut.runtime.Micronaut - No embedded container found. Running as CLI application
```
### Environment Information

- **Operating System**: Linux 4.15.0-45-generic
- **Micronaut Version:** Micronaut Version: 1.1.0.BUILD-SNAPSHOT
- **JDK Version:** JVM Version: 1.8.0_191

### Example Application

I'm following the helloworld from micronaut https://guides.micronaut.io/creating-your-first-micronaut-app/guide/index.html

**Comment by graemerocher** [comment]
You are probably running the non shaded JAR

**Comment by marcosflobo** [comment]
Hi all,

Apologies, you pointed me in the right direction. I do not have to run gradle JAR task, I have to run gradle ASSEMBLE task.

This issue can be closed and sorry for the noise.

Thanks

**Comment by shubhamsaykar** [comment]
Hello graemerocher,

We have build a java application in micronaut  framework and with maven dependencies.
we have created the jar file of the application. When we run a jar file , it is not showing on which port it is running.
It is shownig like this: No embedded container found. Running as CLI application

Can you guide us  that how do we know that the application is running on the port:8080

Thank you !!!
