### ISSUE TITLE
Resolve AWS Route53 and ParameterStore test failures and documentation

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#130]
Since the AWS features (Route 53 and Parameter Store) are not currently working I have placed them on a branch and removed them from master:

https://github.com/micronaut-projects/micronaut-core/tree/aws-route53

Once the issues have been resolved and the code cleaned up they can be merged back in.

**Comment by rvanderwerf** [comment]
last task on this.. convert the route53 stuff to nonblocking rxjava. This mean converting the Future result from AWS client and converting to RxJava then fixing tests.
