### ISSUE TITLE
Add @Valid annotation by default

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-core#1311]
At the moment we should specify every type that`@RequestBody` should be validated by `@Valid` annotation.
```
fun process(@RequestBody @Valid dto: RequestDto) {
    // ...
}
```
Will be very useful if this annotation will be by default, or add a new annotation `@ValidRequestBody`.

**Comment by graemerocher** [comment]
Not sure I agree with this. However we should probably support adding `@Valid` to `RequestDto`

**Comment by raderio** [comment]
What are the issues by not adding it?

**Comment by jameskleeh** [comment]
Closing this because we shouldn’t be forcing validation on users. It would also be a breaking change.

**Comment by raderio** [comment]
Hm, what about new annotation `@ValidRequestBody` ?

**Comment by raderio** [comment]
Maybe it is possible to enable this by configuration property? By default it will be disabled to not break existing code.
