### ISSUE TITLE
Add support for logging request & response body

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-core#1312]
Add support by configuration to log the request/response body.

**Comment by graemerocher** [comment]
this is already possible by setting trace logging on `io.micronaut.http`

**Comment by schrek1** [comment]
is possible exclude some endpoints e.g. health?

**Comment by forresthopkinsa** [comment]
This doesn't seem to work today

**Comment by sgammon** [comment]
@forresthopkinsa make sure you:

- are not using logback's serialized model generator and placing the serialized logback model in sources, where it will get re-used, as this will cause logback not to notice changes in your logging configuration

- are not overriding logging somewhere for that logger, i.e. verify that `TRACE` mode is actually applied, for instance, by using Micronaut AOT which will print all the logger settings on startup

**Comment by mkpaz** [comment]
This doesn't seem to work today 2

**Comment by stefanofornari** [comment]
it does not log body... but really there is not an easy way to do that???

**Comment by graemerocher** [comment]
In `application.properties` set:

```
micronaut.server.netty.log-level=TRACE
```

In `logback.xml` set:

```xml
<logger name="io.micronaut.http.server" level="TRACE" />
```

Send request and see body in logs
