### ISSUE TITLE
Proxy ignored when using SSL

### ISSUE THREAD

**Issue by KrzysztofKowalczyk** [micronaut-projects/micronaut-core#1343]
Follow up to previously raised bug:
https://github.com/micronaut-projects/micronaut-core/issues/1281

Unfortunately the fix for that bug was not really fixing the issue but hiding it.
DefaultHttpClient is simply ignoring the proxy when ssl is being used. Because urls where accessible without proxy anyway the issue is easy to miss.

# Expected Behaviour
Http Client can call services that are only visible through proxy.

# Actual Behaviour
Proxy is being ignored if ssl is used.

# Steps to reproduce
I changed my previous example to be self contained (no internet calls) and validate if proxies are used:
https://github.com/KrzysztofKowalczyk/micronaut-problems/blob/master/proxy_problem/src/main/groovy/CallWithProxy.groovy

# Workaround 
As suggested by @mebowler, you can change DefaultHttpClient.java:

```java
} else if (proxy.isPresent()) {
```
to 
```java
}

if (proxy.isPresent()) {
```

Not sure if this is a complete fix.

**Comment by mebowler** [comment]
In order for this to work when using SSL, another change to the current `DefaulHttpClient` was required, in addition to the above suggestion, in order to pass the request through the proxy before the SSL context handler in the `configureProxy` method:

```java
case HTTP:
    HttpProxyHandler httpProxyHandler = new HttpProxyHandler(proxyAddress);
    if (pipeline.get(HANDLER_SSL) != null) {
        pipeline.addBefore(HANDLER_SSL, HANDLER_HTTP_PROXY, httpProxyHandler);
    } else {
        pipeline.addLast(HANDLER_HTTP_PROXY, httpProxyHandler);
    }
    break;
```

This worked in our scenario but may not be suitable for all use cases.

**Comment by KrzysztofKowalczyk** [comment]
I've added a client
https://github.com/KrzysztofKowalczyk/micronaut-problems/blob/master/proxy_problem/src/main/java/io/micronaut/http/client/DefaultHttpClient_hack.java

with fixes that make if work in my test case. Other fixes are most likely needed (for instance when username and password for proxy is required).

**Comment by graemerocher** [comment]
Feel free to send a PR with a configuration option
