### ISSUE TITLE
Duplicate datasources.default definition

### ISSUE THREAD

**Issue by jeffbrown** [micronaut-projects/micronaut-core#1346]
See below, notice the duplicate `datasources.default` definition.

    ~ $ mn --version
    | Micronaut Version: 1.1.0.M2
    | JVM Version: 1.8.0_131
    ~ $ 
    ~ $ 
    ~ $ mn create-app --features hibernate-jpa com.demo.somejpaapp
    | Generating Java project...
    | Application created at /Users/jeffbrown/somejpaapp
    ~ $ 
    ~ $ 
    ~ $ cat somejpaapp/src/main/resources/application.yml 
    ---
    micronaut:
        application:
            name: somejpaapp
    jackson:
        module-scan: false
    ---
    datasources.default: {}
    ---
    datasources:
      default:
        url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password: ''    
    jpa:
      default:
        properties:
          hibernate:
            hbm2ddl:
              auto: update

**Comment by jameskleeh** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-profiles/commit/61116eac3083e88b6b12607a272991848f3cb088
