### ISSUE TITLE
Support for mapstruct with jsr330 component model

### ISSUE THREAD

**Issue by SirWojtek** [micronaut-projects/micronaut-core#1359]
### Task List
- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
1. Create a project using `mn`
2. Setup mapstruct
3. Create a mapper with `componentModel = "jsr330"
4. Inject mapper to a controller

### Expected Behaviour
Generated mapper should be injected to controller.

### Actual Behaviour
Micronaut fails to inject the mapper:
```
Unexpected error occurred: Failed to inject value for field [modelMapper] of class: micronaut.mapstruct.TestController

Path Taken: TestController.modelMapper
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [modelMapper] of class: micronaut.mapstruct.TestController

Path Taken: TestController.modelMapper
```

### Environment Information
- **Operating System**: Arch Linux
- **Micronaut Version:** 1.1.0.BUILD-SNAPSHOT
- **JDK Version:** openjdk version "1.8.0_202"

### Example Application
https://github.com/SirWojtek/micronaut-mapstruct

**Comment by graemerocher** [comment]
See https://github.com/micronaut-projects/micronaut-core/pull/1339
