### ISSUE TITLE
Creating first Micronaut sample with OpenApi

### ISSUE THREAD

**Issue by Evg-Work** [micronaut-projects/micronaut-core#1362]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Java application
2. Add OpenAPIDefinition annotation to the Application class.
`@OpenAPIDefinition(
        info = @Info(
                title = "Hello Security API",
                version = "1.0",
                description = "Public API for testing Micronat OpenAPI/Swagger for authenticated routes"
        ),
        servers = { @Server(url = "https://example.com") }
)
public class Application {

	public static void main(String[] args) {
		Micronaut.run(Application.class);
	}
}`

3. Compile with Gradle build task :
`com\micronaut\Application.java:18: Note: Generating OpenAPI Documentation
public class Application {
       ^
Writing OpenAPI YAML to destination: build/classes/java/main/META-INF/swagger/hello-security-api-1.0.yml
public class Application {
       ^
**error: Error finalizing type visitor [io.micronaut.openapi.visitor.OpenApiApplicationVisitor@22226d75]: org/apache/commons/lang3/StringUtils**
Note: Creating bean classes for 1 type elements
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.`

### Expected Behaviour

OpenAPI Documentation should be generated in the build folder.

### Actual Behaviour

Build failed with an exception. It goes wrong when I add:
**annotationProcessor "io.micronaut.configuration:micronaut-openapi"**

### Environment Information

- **Operating System**: Windows 10 Pro
- **Micronaut Version:** 1.0.4 and 1.1.0.M2
- **JDK Version:** jdk1.8.0_201

**Comment by graemerocher** [comment]
Could you provide an example that reproduces the issue please

**Comment by Evg-Work** [comment]
Here is the complete example:

**https://github.com/Evg-Work/micronaut-example**

I have the same behavior even with the test downloaded from this repo. (hello-world-java)

**Comment by graemerocher** [comment]
@Evg-Work can you try remove the `mavenLocal()` line, must be corrupt local maven cache I suspect https://github.com/Evg-Work/micronaut-example/blob/master/build.gradle#L15

**Comment by Evg-Work** [comment]
It was that. I started two days with Gradle. :-)

Thanks for the support.

**Comment by anandjaisy** [comment]
@graemerocher Recently I have upgraded the project to `micronautVersion=3.8.1` and in one of the library project I have the below dependency

```
dependencies {
    annotationProcessor "io.micronaut:micronaut-inject-java:${micronautVersion}"
    annotationProcessor "io.micronaut:micronaut-validation:${micronautVersion}"
    annotationProcessor("io.micronaut.security:micronaut-security-annotations")
    annotationProcessor("io.micronaut:micronaut-http-validation:${micronautVersion}")

    api('io.swagger.core.v3:swagger-annotations:2.2.8')
    api "io.micronaut:micronaut-validation:${micronautVersion}"
}
```

When I build the other project that has the local maven dependency of the library, getting the exception as `error: Error finalizing type visitor [io.micronaut.openapi.visitor.OpenApiApplicationVisitor@3edc576b]: null` I can't remove the mavellocal().

```
repositories {
    mavenLocal()
    mavenCentral()
}
```

```
dependencies {
    annotationProcessor("io.micronaut:micronaut-http-validation")
    annotationProcessor("io.micronaut.openapi:micronaut-openapi")
    annotationProcessor("io.micronaut.security:micronaut-security-annotations")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-runtime")
    implementation("io.micronaut.tracing:micronaut-tracing-zipkin")
    implementation("io.micronaut.discovery:micronaut-discovery-client")
    implementation("io.micronaut.security:micronaut-security-jwt")
    implementation("io.swagger.core.v3:swagger-annotations")
    runtimeOnly("ch.qos.logback:logback-classic")
    implementation("io.micronaut:micronaut-validation")
    implementation("io.micronaut.reactor:micronaut-reactor-http-client")
    implementation("io.micronaut.discovery:micronaut-discovery-client")
    implementation("io.micronaut.tracing:micronaut-tracing-zipkin")
    compileOnly("org.graalvm.nativeimage:svm")

    implementation project(':core')
    runtimeOnly project(':infrastructure')

    testImplementation("org.testcontainers:junit-jupiter")
}
```
https://stackoverflow.com/questions/75191088/error-finalizing-type-visitor-io-micronaut-openapi-visitor-openapiapplicationvi
