### ISSUE TITLE
HttpServerFilter is invoked twice upon exception

### ISSUE THREAD

**Issue by ahmedlafta** [micronaut-projects/micronaut-core#1364]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone https://github.com/ahmedlafta/micronaut-server-filter-demo
2. Run the tests in `BookServerFilterTest`
3. Observe the log output of each test

### Expected Behaviour

In the second test when an exception is generated (by the http client) and handled by an ExceptionHandler, the HttpServerFilter should only be invoked once.

### Actual Behaviour

The HttpServerFilter is invoked twice when an exception is generated by the http client.
Log output: <br>
```
16:28:16.402 [nioEventLoopGroup-1-4] INFO  m.s.f.demo.filter.BookServerFilter - Inside book server filter
16:28:16.422 [nioEventLoopGroup-1-2] INFO  m.s.f.demo.filter.BookServerFilter - Inside book server filter
```
In this scenario, it now looks like the server has processed two requests when it has only processed one. Also, the second log entry is (usually) on a separate thread as per my example.

### Environment Information

- **Operating System**: macOs mojave
- **Micronaut Version:** 1.0.4
- **JDK Version:** openjdk11

### Example Application

https://github.com/ahmedlafta/micronaut-server-filter-demo

**Comment by graemerocher** [comment]
This is actually by design and is largely the same as how servlet filters behave since some filters need to run for both regular request handling and error handling.

If you only want it to be invoked once you can subclass `OncePerRequestHttpServerFilter`

**Comment by rafalschmidt97** [comment]
> This is actually by design and is largely the same as how servlet filters behave since some filters need to run for both regular request handling and error handling.
> 
> If you only want it to be invoked once you can subclass `OncePerRequestHttpServerFilter`

Good! I've just come across this problem. Thanks @graemerocher. It would be great to see a disclaimer about this in [the documentation section](https://docs.micronaut.io/latest/guide/index.html#_exceptionhandler). By the way - I don't understand the purpose of Produces and Requires annotations in the global exception handler example so if you could describe bit (since it works without it as well) why it would be fantastic.

**Comment by wq163** [comment]
no exception, invoked twice too, version 2.0.1
