### ISSUE TITLE
Support Request  Content-Encoding GZIP, DEFLATE

### ISSUE THREAD

**Issue by alphawolf1988** [micronaut-projects/micronaut-core#1384]
I know, that micronaut supports Content-Encoding: gzip,deflate for responses, but it would be also nice, if requests can post their body with  Content-Encoding: gzip  and decode it correctly. Currently this is not supported.

**Comment by jameskleeh** [comment]
Can you be more specific? Are you referring to our http client? If so, show some example code that isn’t working as you expect.

**Comment by alphawolf1988** [comment]
I'm refering to the micronaut server, especially NettyHttpServer. The netty pipeline add a content compressor:

`pipeline.addLast(HTTP_COMPRESSOR, new SmartHttpContentCompressor(serverConfiguration.getCompressionThreshold()));`

but a content decompressor is missing like:

`HttpContentDecompressor`

so the micronaut backend isn't able to decode content, which uses Content-Encoding: gzip.

**Comment by alphawolf1988** [comment]
@jameskleeh do you need more information about the problem or is the description from the previous comment enough?

**Comment by jameskleeh** [comment]
@alphawolf1988 No, I understand the issue. Thanks for the report
