### ISSUE TITLE
@Transactional not working on compiled graal binary

### ISSUE THREAD

**Issue by mageddo** [micronaut-projects/micronaut-core#1387]
### Steps to Reproduce

**Reproducing the actual behavior**

```bash
$ git clone https://github.com/mageddo/graalvm-examples.git &&\
cd graalvm-examples/micronaut && \
git checkout evidence-transactional-not-working-on-binary-mode &&\
./gradlew clean nativeImage
$ ./build/graal/micronaut
$ curl -s localhost:8080/fruits
```
[current-behavior.txt](https://github.com/micronaut-projects/micronaut-spring/files/2975441/current-behavior.txt)

**Reproducing the expected behavior**
```bash
$ ./gradlew run
$ curl -s localhost:8080/fruits
```
[expected-behavior.txt](https://github.com/micronaut-projects/micronaut-spring/files/2975442/expected-behavior.txt)

**Additional Info**
I realized the follow line is not present on the binary execution what looks like micronaut is not registering `@Transactional` interceptor or something like that

```
2019-03-17 13:56:45.881 [pool-1-thread-3] TRA   i.m.aop.chain.InterceptorChain m=<init> l=77 Intercepted method [List getFruits()] invocation on target: com.mageddo.micronaut.service.$FruitsServiceDefinition$Intercepted@673f30fe
2019-03-17 13:56:45.881 [pool-1-thread-3] TRA   i.m.aop.chain.InterceptorChain m=proceed l=143 Proceeded to next interceptor [io.micronaut.spring.tx.annotation.TransactionInterceptor@312e480] in chain for method invocation: List getFruits()
```

### Expected Behaviour
I configured micronaut + spring jdbc and generated a binary using graalvm.
JDBC Transactions working by using `@Transactional`

### Actual Behaviour

`@Transactional` is not working after generate the binary using `native-image` the feature works but keep getting a new connection for every SQL statement

### Environment Information

- **Operating System**: Ubuntu 18.10
- **Micronaut Version:** 1.1.0.M2
- **JDK Version:** OpenJDK Runtime Environment (build 1.8.0_202-20190206132807.buildslave.jdk8u-src-tar--b08) / OpenJDK GraalVM CE 1.0.0-rc13 (build 25.202-b08-jvmci-0.55, mixed mode)

### Example Application

- https://github.com/mageddo/graalvm-examples/tree/evidence-transactional-not-working-on-binary-mode

**Comment by mageddo** [comment]
Okay, I fixed the problem by Registering the annotation clazz on GraalVM
```java
Class<?> clazz = io.micronaut.spring.tx.annotation.Transactional.class;
RuntimeReflection.register(clazz);
for (final Method method : clazz.getMethods()) {
    RuntimeReflection.register(method);
}
```
[Updated sample](https://github.com/mageddo/graalvm-examples/tree/evidence-transactional-working-on-binary-mode)

**Comment by mageddo** [comment]
Not sure if micronaut is supposed to do this automatically?

**Comment by graemerocher** [comment]
It is supposed to, however this is fixed in master. If you are using Graal I recommend the snapshots, much has been fixed and we will be doing an RC soon

**Comment by mageddo** [comment]
Allright, thanks for the tip

**Comment by graemerocher** [comment]
If you wish to verify the fix you can do so by adding the snapshot repo to `build.gradle`:

```groovy
repositories {
    ...
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

And specifying the snapshot version as your BOM:

```groovy
dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:1.1.0.BUILD-SNAPSHOT'
    }
}
```

**Comment by mageddo** [comment]
I confirm it's working on `1.1.0.BUILD-SNAPSHOT`, I don't need to create `MicronautSubstitutions.java` as well
