### ISSUE TITLE
Review docs design

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#139]
> jameskleeh [16:37]
> @sdelamo Did you do the color scheme for the docs?
> 
> fonts, etc
> 
> sdelamo [16:37]
> I changed it slightly but I still need to work on it
> website is a WIP right now
> 
> jameskleeh [16:37]
> one thing that bugs me is the TOC dropdown
> 
> sdelamo [16:37]
> that will impact docs
> 
> jameskleeh [16:37]
> the font is weird
> 
> sdelamo [16:37]
> TOC right bar column gives problesm
> I will revisit that
> 
> jameskleeh [16:38]
> the dropdown itself
> 
> sdelamo [16:38]
> the whole docs and guides design
> 
> zacharyaklein [16:38]
> The dropdown for the TOC makes sense to me on mobile devices, but is a bit of a pain on a desktop IMHO.
> Personally  I’d prefer an `iframe` (either the actual HTML iframe or simply a CSS-fixed div) for the TOC - that seems to be pretty common on a lot of docs that I see.
> 
> jameskleeh [16:39]
> the font looks blurry, i think because it has a shadow or something
> 
> sdelamo [16:40]
> I have not spent much time but I will soon.

**Comment by Solido** [comment]
Could you add a simple sticky arrow so we can reach the main menu without scrolling to top ?

**Comment by remkop** [comment]
I agree with @ZacharyKlein  that it would be nicer to have the TOC in an `iframe` so that it stays in sight when scrolling down the user manual. It allows for much smoother navigation. 

This is one thing the default style sheet does well IMO. For mobile devices the default style sheet puts the TOC at the top of the page, which works well.

**Comment by remkop** [comment]
I really like the new design where the TOC is always visible. It allows me to quickly jump back and forth between different sections that are far apart in the document without breaking my flow. Thank you very much!
