### ISSUE TITLE
Adding micronaut-openapi annotation processor dependency causes `ClassNotFoundException: org.slf4j.LoggerFactory`

### ISSUE THREAD

**Issue by marcocamacho** [micronaut-projects/micronaut-core#1395]
I am using `mavenBom 'io.micronaut:micronaut-bom:1.0.4'`. The app runs fine, but as soon as I add `annotationProcessor "io.micronaut.configuration:micronaut-openapi"` and run the app I get:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at io.micronaut.runtime.Micronaut.<clinit>(Micronaut.java:45)
```

**Comment by marcocamacho** [comment]
My work around was to add
```
implementation ("org.slf4j:slf4j-api:1.7.26") {
        force = true
    }
```

Which is not nice

**Comment by puneetbehl** [comment]
Please share sample application.

**Comment by marcocamacho** [comment]
I found part of the issue, I upgrade the gradle wrapper to the latest version:

```
 cat gradle/wrapper/gradle-wrapper.properties 
distributionUrl=https\://services.gradle.org/distributions/gradle-5.2.1-all.zip
```

Then add `annotationProcessor "io.micronaut.configuration:micronaut-openapi"`

You will get the exception. I guess is OK for now since micronaut supports the latest of gradle 4, but not 5. But it is a heads up if you plan to ever use gradle 5.

**Comment by puneetbehl** [comment]
@marcocamacho I am able to run fine, please see attached [sample project.zip](https://github.com/micronaut-projects/micronaut-core/files/3001073/hello-world.zip)

**Comment by funnyleolee** [comment]
also has this problem！
Use commandline `mn create-app example.micronaut.auth-demo2 --features security-jwt` generate project done.But Run 'Application.main()' use IntelliJ IDEA throw exception the same as that.

Finally we move `compile "io.micronaut:micronaut-runtime"` line up like this:

> 
>    **compile "io.micronaut:micronaut-runtime"**
>     compile "io.micronaut:micronaut-inject"
>     compile "io.micronaut:micronaut-validation"
>     compile "io.micronaut:micronaut-http-client"
>     compile "io.micronaut:micronaut-http-server-netty"

And  this problem was resolved.
