### ISSUE TITLE
Abstract endpoint annotation for delegation

### ISSUE THREAD

**Issue by rverma-nikiai** [micronaut-projects/micronaut-core#1402]
Looking for an alternative of @RequestMapping, if we do not specify any mapping this method will resolve all the http request i.e. we can send GET, POST, HEAD, OPTIONS, PUT, PATCH, DELETE, TRACE request to the specified url and it will be resolved.

What is the way to achieve the same in micronaut?

**Comment by graemerocher** [comment]
You can achieve that by writing a controller that has a method with:

`@Error(status=HttpStatus.NOT_FOUND, global=true)` which will be invoked if a page is not found

**Comment by jameskleeh** [comment]
You would need to register a route for each method if you want the route to match only for a given URI, but for all methods.
