### ISSUE TITLE
1.1.0.RC1 Kotlin Data Classes <-> Json Parameter

### ISSUE THREAD

**Issue by monsdroid** [micronaut-projects/micronaut-core#1405]
### Task List

- [x ] Steps to reproduce provided

### Steps to Reproduce

1. Use Cli and Setup Simple Controller + lang = kotlin
```
@Post("/")
@Consumes(MediaType.APPLICATION_JSON)
fun create(createEntity: User) ...
```
2. Post valid "User" Json

### Expected Behaviour
Json gets converted to Kotlin User Data Class as in Mironaut 1.1.0.M2

### Actual Behaviour
```Failed to convert argument [createEntity] for value [null] due to: Cannot construct instance of `.api.User` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1]```

Switching back to .M2 resolves that matter a.t.m.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.1.0.RC1
- **JDK Version:** JDK 11
- **Kotlin Version:** 1.3.21

**Comment by jameskleeh** [comment]
Try setting `jackson.module-scan: true` in your config
