### ISSUE TITLE
How to disable discoveryclienthealthindicator 

### ISSUE THREAD

**Issue by chenjpu** [micronaut-projects/micronaut-core#1406]
When the number of services is large, the request times out

**Comment by jameskleeh** [comment]
Please ask questions in [gitter](gitter.im/micronautfw)

**Comment by pavelbucek** [comment]
@jameskleeh that's not very helpful answer (especially for future readers), since there doesn't seem to be gitter archive indexed by google.

**Comment by jameskleeh** [comment]
@pavelbucek Whether its archived or index or not doesn't matter. I didn't indicate Gitter was a place to look for answers via searching the history. I said Gitter was the place to questions. You can ask a question even if it has been asked many times before.

**Comment by pavelbucek** [comment]
@jameskleeh well, it goes against building a knowledge base which can be accessed without interaction on gitter, which is not infinitely scalable. Anyway, I'd expect that answers to questions like that should be then considered as something to be added to the documentation, which is rather sparse especially when looking at health management, see https://docs.micronaut.io/latest/guide/index.html#healthEndpoint

@jeffbrown FYI

I can see the reasoning behind closing questions like that, on the other side transforming them to documentation requests could be better long-term way how to handle them.
