### ISSUE TITLE
Support for multiple paths on the same mapping

### ISSUE THREAD

**Issue by mageddo** [micronaut-projects/micronaut-core#1422]
### Expected Behaviour

I think it would be very nice if **`@Get`**, **`@Post`**, etc. have the support  for multiple paths instead of only one, something like that

```java
@Get({"/api/v1.0/settings", "/api/v2.0/settings"})
public String getSettings(){
.....
}
```

### Actual Behaviour

I can't map multiple paths to the same controller method, so I have to create a common controller method and create another method for every new mapping I want to create, it is a LOT more verbose to develop
```java
@Get("/api/v1.0/settings")
public String v1GetSettings(){
    return commonGetSettings();
}

@Get("/api/v2.0/settings")
public String v2GetSettings(){
    return commonGetSettings();
}

String commonGetSettings(){
....
}
```
### Environment Information

- **Operating System**: not applicable
- **Micronaut Version:** 1.1.0.BUILD-SNAPSHOT
- **JDK Version:** not applicable

**Comment by mageddo** [comment]
Looking at  [the router reference](https://github.com/liwujun0513/micronaut_demo/blob/master/src/main/java/com/framework/LoginCommand.java) I've created the following example which make a hack for my case, anyway I think this is a nice freature which should be considered

```java
@Patch(value = "/api/v{version:[12]}.0/settings")
public HttpResponse route(String version, @Body Object o){
.......
```

**Comment by jameskleeh** [comment]
> which make a hack for my case

I don't think that is a hack. That is the intended use case

**Comment by mageddo** [comment]
For my case yes, but thinking in a case where you have two totally different URIs but you want to call the same method then I think the first example fits better, something like

```java
@Get({"/legacy-url/my-project", "/new-web-site/the-new-project"})
public String loadProject(){
.....
}
```

Just like [Spring Web do](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/GetMapping.html#path--)

**Comment by graemerocher** [comment]
I think what would make sense here is to allow the HTTP annotations to be repeatable. The example above looks complex to me

**Comment by mageddo** [comment]
Allows annotation to be repeatable will also permit the user to map multiple HTTP methods, it would be great

**Comment by jameskleeh** [comment]
Probably something for 1.2

**Comment by recursivecodes** [comment]
>I think what would make sense here is to allow the HTTP annotations to be repeatable. The example above looks complex to me

I think that would be very nice, but would make it even better (to me) is to allow stacking methods.

Example:
```
@Get("/foo")
@Post("/foo")
String method(HttpRequest request) { 
    if ( request.method == 'GET' ) {}
    if ( request.method == 'POST') {}
    ...
}
```

**Comment by saw303** [comment]
@graemerocher why did you close this ticket? Is it fixed or won't it be fixed? I'm asking because I dont' see any reference to a PR or commit.

**Comment by graemerocher** [comment]
Oops sorry. PR merged https://github.com/micronaut-projects/micronaut-core/pull/2188
