### ISSUE TITLE
Got 500 error or getting wrong content-type when loading static resources on native-image binary

### ISSUE THREAD

**Issue by mageddo** [micronaut-projects/micronaut-core#1424]
### Steps to Reproduce

1. Build and start the project 
```
$ git clone https://github.com/mageddo/graalvm-examples.git &&\
  cd graalvm-examples/micronaut && \
$ git checkout dd3de8e9a254e1b570b081e17c954eaf56efb6bb &&\
  ./gradlew clean build reflectConfigFiles nativeImage
$ ./build/graal/micronaut
```
2. Simulating an 500 error when loading the resource

```
$ curl -i  localhost:8080/static/foo.css
HTTP/1.1 500 Internal Server Error
Date: Mon, 25 Mar 2019 00:40:50 GMT
content-type: application/json
content-length: 41
connection: close

{"message":"Internal Server Error: null"}
```
[log.log](https://github.com/micronaut-projects/micronaut-core/files/3001432/log.log)

3. On the next time you try to load any other resource it will respond successfully but with the wrong content-type

```bash
curl -i  localhost:8080/static/foo.css
HTTP/1.1 200 OK
Date: Mon, 25 Mar 2019 00:47:09 GMT
connection: keep-alive
transfer-encoding: chunked
Content-Type: text/plain
Date: Mon, 25 Mar 2019 00:47:09 GMT
Expires: Mon, 25 Mar 2019 00:48:09 GMT
Cache-Control: private, max-age=60
Last-Modified: Thu, 1 Jan 1970 00:00:00 GMT

p.one {
    border-style: solid;
    border-width: 5px;
}
```

### Expected Behaviour

Static resources loading without errors with the right content-type, `.css` with `text/css` content type for example

### Actual Behaviour

After start the app and try to load the resource I get 500, if I try again I get the resource successfully but get the wrong content-type `Content-Type: text/plain` it makes my browser ignore this css resource even if I force the content-type on the html tag

### Environment Information

- **Operating System**: Ubuntu 18.10
- **Micronaut Version:** 1.1.0.RC1
- **JDK Version:** GraalVM 1.0.0-rc13
- **Browser**: Chrome 72.0.3626.109 (Official Build) (64-bit)

### Example Application

https://github.com/mageddo/graalvm-examples/tree/dd3de8e9a254e1b570b081e17c954eaf56efb6bb

**Comment by graemerocher** [comment]
Can you try and include `META-INF/http/mime.types` in your graal resources `-H:IncludeResources`

**Comment by mageddo** [comment]
@graemerocher I confirm your solution works
