### ISSUE TITLE
Graal: Returned empty POJO (basic-app)

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#1426]
The basic-app we use for Graal integration tests is returning an empty json with lastest Graal and Micronaut snapshots.
To reproduce the issue:

- `git clone https://github.com/micronaut-graal-tests/micronaut-basic-app`
- `cd micronaut-basic-app`
- Use latest Graal
- `./build-native-image.sh`
- `./basic-app`

```
curl localhost:8080/hello/micronaut
{}
```

The output should be `{"msg":"Hello micronaut"}`

**Comment by ilopmar** [comment]
I also tried removing `jackson.module-scan: false` but nothing changed.

**Comment by ilopmar** [comment]
A related error also happened with the project `function-graal`. When a function running on Graal with a json input the error is:
```
$(echo '{"name":"Micronaut"}' | $CI_PROJECT_DIR/micronaut-function-graal/function-graal > RESPONSE.txt)
Error executing function (Use -x for more information): Error decoding JSON stream for type [greetingRequest]: Cannot construct instance of `function.graal.pojo.GreetingRequest` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (BufferedInputStream); line: 1, column: 2]
```
More info: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/183402269

**Comment by graemerocher** [comment]
the issue appears to be that the `src/main/resources/META-INF/native-image/example/micronaut/native-image.properties` is overwriting the generated file hence breaking the reflection data

We should probably change the name of this file to include another key in the `create-app` command to avoid users bumping into this problem

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-profiles/commit/a27806684d3d3a6c7da2e3ca8520b398a0a18fbf you will need to adjust the test projects as well
