### ISSUE TITLE
Graal & security: Cannot construct instance of `io.micronaut.security.authentication.UsernamePasswordCredentials` (no Creators, like default construct, exist)

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#1427]
As https://github.com/oracle/graal/issues/659 and https://github.com/oracle/graal/issues/717 are fixed now it is possible to build native-images with Security support.

To reproduce the new issue:
- `git clone https://github.com/micronaut-graal-tests/micronaut-security-jwt-graal`
- `cd micronaut-security-jwt-graal`
- Use latest Graal from master branch (rc15-dev)
- `./build-native-image.sh`
- `./graal-security`

- Execute curl to authenticate: `curl -X POST -H 'Content-Type:application/json' -d '{"username":"sherlock","password":"password"}' localhost:8080/login`

Error:
```json
{
	"message": "Failed to convert argument [usernamePasswordCredentials] for value [null] due to: Cannot construct instance of `io.micronaut.security.authentication.UsernamePasswordCredentials` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)\n at [Source: UNKNOWN; line: -1, column: -1]",
	"path": "/usernamePasswordCredentials",
	"links": {
		"self": {
			"templated": false,
			"href": "/login"
		}
	}
}
```

**Comment by graemerocher** [comment]
This is because the security module has yet to be reviewed and `@Introspected` added to the various types used in the JSON. Also needs to the `graal` dependency added such that the correct compile time metadata is produced.
