### ISSUE TITLE
Versioned requests don't match non-versioned routes

### ISSUE THREAD

**Issue by juliuskrah** [micronaut-projects/micronaut-core#1430]
Users should be able to set default version if `X-API-VERSION` header or `api-version` parameter is not included in request.

### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

I created a micronaut application, and enabled versioning and security (JWT).
Then I added a bean to add default version, below is my implementation:

```java
@Replaces(HeaderVersionResolver.class)
@Requires(beans = { RoutesVersioningConfiguration.class, HeaderVersionResolverConfiguration.class })
public class DefaultHeaderVersionResolver extends HeaderVersionResolver {
	@Value("${version.default:1}")
	private String version = "1";

	public DefaultHeaderVersionResolver(HeaderVersionResolverConfiguration configuration) {
		super(configuration);
	}

	@Override
	public Optional<String> resolve(HttpRequest<?> request) {
		return super.resolve(request).or(() -> Optional.of(version));
	}

}
```

And here is my `application.yml`:

```yaml
micronaut:
  router:
    versioning:
      enabled: true
      parameter:
        enabled: false
      header:
        enabled: true 
```

### Expected Behaviour

When a version is not included in the `Header` or as a `Url Parameter`, the request should be processed by serving the default versioned Url. This works for versioned endpoints.

### Actual Behaviour

When a non versioned endpoint is accessed e.g. /login, I get a 401 response.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version**: 1.1.0.RC1
- **JDK Version:** 11

### Example Application

- https://github.com/jaesoft/resk/tree/micronaut/message-command-side

**Comment by jameskleeh** [comment]
To summarize the issue:

1. 1. You're getting the 401 because no route is found for `/login` thus no security rules are explicitly allowing or rejecting the request.
2. No route is being found because your version resolver is returning `1` and the login endpoint is not versioned
3. In order to make this project work as is we would need to allow versioned requests to non versioned routes

Given that the versioning feature is new to 1.1.0 we could technically make this change if we all agree it makes sense. Thoughts @graemerocher @sdelamo ?

**Comment by jameskleeh** [comment]
I think this can be made to work by supplying the default version in configuration instead of in a version resolver.

Then in the version filter we can match the default version for versioned routes and ignore it for non versioned routes

**Comment by juliuskrah** [comment]
> Then in the version filter we can match the default version for versioned routes and ignore it for non versioned routes

This is what I'm looking for.
