### ISSUE TITLE
Add support for Batch API

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-core#1446]
Allow to put several API calls into a single HTTP request.

Here you can find an example at PayPal
https://medium.com/paypal-engineering/batch-an-api-to-bundle-multiple-paypal-rest-operations-6af6006e002

**Comment by graemerocher** [comment]
I don't see this being part of core, but would make an interesting module

**Comment by jameskleeh** [comment]
Closing because this will not be part of core
