### ISSUE TITLE
allow wildcard subdomains in cors-config

### ISSUE THREAD

**Issue by andersmartini** [micronaut-projects/micronaut-core#1448]
I'd like to enable CORS for any subdomain of our domains. I tried configuring cors as such:
`micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.all.allowedOrigins[0]=https://*.minecraft.net
micronaut.server.cors.configurations.all.allowedOrigins[1]=https://*.mojang.com
`

but with this configuration my preflight requests get a 200 response with origin set to "https://minecraft.net" but a 401 for "https://test.minecraft.net"

**Comment by jameskleeh** [comment]
It uses regex for matching, so you could do something like `https:\/\/(.*?)\.minecraft\.net`

**Comment by andersmartini** [comment]
oh! thanks! I must be tired, its actually pretty clear reading the docs, don't know how I missed it
