### ISSUE TITLE
OpenApi - wrong schema for body as List

### ISSUE THREAD

**Issue by croudet** [micronaut-projects/micronaut-core#1450]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a project with OpenApi support
2. add an endpoint as follows:
```java
  @Post("/echo/listlongs")
  Flux<Long> echoListLongs(@Body List<Long> longs);
```
3. generates the yaml file (compile the project.)

### Expected Behaviour

The generated yaml for the request body should be:
```
/hello/echo/listlongs:
    post:
      operationId: echoListLongs
      parameters: []
      requestBody:
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int64
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int64
```

### Actual Behaviour
The generated yaml has nested item arrays for request body:
```
/hello/echo/listlongs:
    post:
      operationId: echoListLongs
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: array
                items:
                  type: integer
                  format: int64
        required: true
      responses:
        default:
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
                  format: int64
```

### Environment Information

- **Operating System**:  Windows 10
- **Micronaut Version:** 1.1.0.RC1
- **JDK Version:** jdk 8

### Example Application

- https://github.com/croudet/micronaut-hello-world

**Comment by puneetbehl** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-core/commit/ba5968ac5f687951250cf6c5c72090ef66b9da8b
