### ISSUE TITLE
Enable to have request body as Flux of literal json type work

### ISSUE THREAD

**Issue by croudet** [micronaut-projects/micronaut-core#1451]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

I have endpoints as follows:
```java
public interface HelloOperations {

  @Post("/echo/booleans")
  Flux<Boolean> echoBooleans(@Body Flux<Boolean> bools);
  
  @Post("/echo/strings")
  Flux<String> echoStrings(@Body Flux<String> strings);
  
  @Post("/echo/longs")
  Flux<Long> echoLongs(@Body Flux<Long> longs);
  
  @Post("/echo/listlongs")
  Flux<Long> echoListLongs(@Body List<Long> longs);
  
}
```
With implementation:
```java
package hello.world;

import java.util.List;

import io.micronaut.http.annotation.*;
import reactor.core.publisher.Flux;
import reactor.core.scheduler.Schedulers;

@Controller("/hello") 
public class HelloController implements HelloOperations {

  @Override
  public Flux<Boolean> echoBooleans(Flux<Boolean> bools) {
    return bools.subscribeOn(Schedulers.elastic()).map(b -> b);
  }

  @Override
  public Flux<String> echoStrings(Flux<String> strings) {
    return strings.subscribeOn(Schedulers.elastic()).map(b -> b);
  }

  @Override
  public Flux<Long> echoLongs(Flux<Long> longs) {
    return longs.subscribeOn(Schedulers.elastic()).map(b -> b);
  }

  @Override
  public Flux<Long> echoListLongs(List<Long> longs) {
    return Flux.fromIterable(longs);
  }
    
}
```

### Expected Behaviour

I expect endpoints with `Flux` request body to return a result as the endpoint with the `List` body.

### Actual Behaviour

Endpoints with `Flux` request bodies with type `String`, `Long` or `Boolean` does not work.
They return an empty body.
If you use a non json literal type, everything works.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.1.0.RC1
- **JDK Version:** jdk8

### Example Application

- https://github.com/croudet/micronaut-hello-world

**Comment by jameskleeh** [comment]
So the only issue here is returning `List<String>` or `Flux<String>` and expecting Micronaut to produce a response like `["a", "b", "c"]`. Since we have no idea if the string represents already formatted json or not, we simply render it as is.
