### ISSUE TITLE
@Validated and @Valid

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-core#1457]
Why we need to put both annotation to make validation to work?
If I put only one annotation, than validation is not working.

```
@Validated
@Controller("/")
open class HelloController {

    @Post("/signup")
    open fun signup(@Body @Valid dto: SignUpDto): String {
        println("${dto.email} ${dto.password}")
        return "OK"
    }
}

class SignUpDto @JsonCreator constructor(
        @JsonProperty("email") @field:Size(max=5) val email: String,
        @JsonProperty("password") val password: String)
```

**Comment by raderio** [comment]
Also, why validation is not done for nested object?
```
class SignUpDto @JsonCreator constructor(
        @JsonProperty("email") @field:Size(min=5) val email: String,
        @JsonProperty("password") val password: String,
        @JsonProperty("address") val address: AddressDto)


class AddressDto @JsonCreator constructor(
        @JsonProperty("country") @field:Size(min=3) val country: String )
```
`country` field is not validated for request `{ "email": "agent@corp.com", "password": "LOL", "address": { "country": "US" } }`

**Comment by graemerocher** [comment]
The 2 annotations mean different things. `@Valid` is used to control cascading validation. If you want `AddressDto` to cascade validation you have to annotate `address` with `@Valid`.

This is not really related to Micronaut but how Bean validation is Java works https://beanvalidation.org/2.0/spec/#constraintdeclarationvalidationprocess-requirements-graphvalidation

**Comment by raderio** [comment]
> If you want AddressDto to cascade validation you have to annotate address with @Valid.

Is it possible to fix this somehow in Micronaut? because it can leads to mistakes.

**Comment by graemerocher** [comment]
Current versions of Micronaut use Hibernate Validator we may in the future replace this and it could be possible to add a configuration option, but since we cannot change Hibernate Validator's behaviour today we cannot change it

**Comment by raderio** [comment]
Ok thanks.

What about that `@Vaild` in method does not work if controller is not annotated with `@Validated`?

**Comment by graemerocher** [comment]
that we can maybe fix by automatically annotating a bean with `@Validated` if `@Valid` is present

**Comment by gunnarmorling** [comment]
It might be possible to imply the presence of `@Validated` whenever `@Valid` or any specific Bean Validation constraint is present. That'd be akin to what the CDI integration of BV is doing for method validation, too.

**Comment by graemerocher** [comment]
@gunnarmorling yes that it possible, and will be a nice improvement. Thanks for the feedback

**Comment by raderio** [comment]
https://hibernate.atlassian.net/browse/BVAL-726

**Comment by IgorEulalio** [comment]
Why the validations doesn't talks with jackson to throw the exception?
```yml
jackson:
  property-naming-strategy: SNAKE_CASE
```

My class:
```java
package br.com.itau.adapter.http.dto;

import io.micronaut.core.annotation.Introspected;
import io.micronaut.validation.Validated;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.Valid;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

@Introspected
public class ProdutosDTO {

    @NotNull
    @NotBlank
    private String siglaSistema;

    @NotNull
    @NotBlank
    private String codigoProduto;

    public String getSiglaSistema() {
        return siglaSistema;
    }

    public void setSiglaSistema(String siglaSistema) {
        this.siglaSistema = siglaSistema;
    }

    public String getCodigoProduto() {
        return codigoProduto;
    }

    public void setCodigoProduto(String codigoProduto) {
        this.codigoProduto = codigoProduto;
    }
}
```

The error handled have the properties with the CAMEL_CASE strategy:
```
{
    "message": "Bad Request",
    "_links": {
        "self": {
            "href": "/contratacaorecomendacaoservice/valida_cvm",
            "templated": false
        }
    },
    "_embedded": {
        "errors": [
            {
                "message": "dto.produtos.codigoProduto: must not be null"
            },
            {
                "message": "dto.produtos.codigoProduto: must not be blank"
            },
            {
                "message": "dto.produtos.siglaSistema: must not be blank"
            },
            {
                "message": "dto.produtos.siglaSistema: must not be null"
            }
        ]
    }
}
```
