### ISSUE TITLE
Automatically annotating a bean with @Validated if @Valid is present

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-core#1458]
Automatically annotating a bean with @Validated if @Valid is present.

Relates to https://github.com/micronaut-projects/micronaut-core/issues/1457

**Comment by jameskleeh** [comment]
@graemerocher Can this be closed?

**Comment by nbrugger-tgm** [comment]
Is this implemented? If yes i haven't seen a mention of it in the micronaut-validator documentation/user-guide (https://docs.micronaut.io/latest/guide)
