### ISSUE TITLE
ClassCastException when forwarding HttpRequest via io.micronaut.http.client.HttpClient#exchange(io.micronaut.http.HttpRequest<I>)

### ISSUE THREAD

**Issue by ivyazmitinov** [micronaut-projects/micronaut-core#1470]
### Steps to Reproduce

1. Create the following `@Controller` method
```java
    @Get("/test")
    public String test(HttpRequest<?> request)
    {
        rxHttpClient.exchange(request).subscribe();
        return "test";
    }
```
2. Invoke it

### Expected Behaviour

IMO, this is an architectural issue:  `io.micronaut.http.client.HttpClient#exchange` in fact, takes only `NettyClientHttpRequest` as parameter, but interface of `HttpClient` doesn't provide this information. So, either there should be another hierarchy of `ClientHttpRequest`s, which `HttpClient` should work with, or it should be able to consume any implementation of `HttpRequest`. 

### Actual Behaviour

```
java.lang.ClassCastException: io.micronaut.http.server.netty.NettyHttpRequest cannot be cast to io.micronaut.http.client.NettyClientHttpRequest
	at io.micronaut.http.client.DefaultHttpClient.sendRequestThroughChannel(DefaultHttpClient.java:1540)
```

### Environment Information

- **Micronaut Version:** 1.1.0.RC1

**Comment by graemerocher** [comment]
Yeah we are aware of this limitation and will look to address it in 1.2

Thanks

**Comment by ameet123** [comment]
Hi,
I am using 1.3.4 and I still see this issue.
Could you please advise a workaround and when it would be fixed?
thanks
ameet

**Comment by graemerocher** [comment]
Duplicates #1113
