### ISSUE TITLE
Add support for Undertow server

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-core#1482]
http://undertow.io/
Undertow is a flexible performant web server written in java, providing both blocking and non-blocking API’s based on NIO.

The performance is near the Netty's http://blog.arungupta.me/undertow-benchmarks-wildfly/
It is also supported by Spring Boot https://docs.spring.io/spring-boot/docs/current/reference/html/howto-embedded-web-servers.html

**Comment by graemerocher** [comment]
Supported in https://github.com/micronaut-projects/micronaut-servlet
