### ISSUE TITLE
StackOverflowError in 1.1.0.RC2

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#1494]
I have a simple app in Micronaut which uses Hibernate + MySQL. Hibernate works in auto schema update mode. It's no more than 3 weeks of development from scratch in this app.

Today I migrated from 1.0.4 to 1.1.0.RC2 and now server randomly crashes on startup with `StackOverflowError`. This doesn't happen each time, maybe in 30% of cases.

I caught the problem with `io.micronaut` logged on `trace`. Please see the attached log.

[api.log.gz](https://github.com/micronaut-projects/micronaut-core/files/3050215/api.log.gz)

**Comment by graemerocher** [comment]
This duplicates #1484 you can see instructions in that issue to try the snapshot. Thanks for the report however.
