### ISSUE TITLE
ExceptionHandler can not override response body when UserFetcher returns empty Flowable

### ISSUE THREAD

**Issue by thestarmaker** [micronaut-projects/micronaut-core#1496]
Hi guys, I have upgraded from micronaut 1.0.2 to 1.1.0.RC2 and the functionality has stopped working. 

To reproduce:
1. create a new project
2. enable JWT security and login controller
3. provide UserFetcher implementation that always returns empty Flowable
4. provide ExceptionHandler implementation as follows:

```
    @Override
    public HttpResponse handle(HttpRequest request, Exception exception) {
        HttpStatus status;
        ErrorDTO error;
        if (pureCause instanceof AuthenticationException) {
            //thrown by micronaut LoginController
            status = UNAUTHORIZED;
            error = new ErrorDTO("WRONG_PASSWORD_OR_EMAIL");
        } else {
             status = INTERNAL_SERVER_ERROR;
             error = new ErrorDTO("INTERNAL_SERVER_ERROR");
        }
        return HttpResponse.status(status).body(error);
    }
```
5. invoke the login controller

Expected response:
the ErrorDTO with "WRONG_PASSWORD_OR_EMAIL" message
Actual response:
`
{"_links":{"self":{"href":"/api/v1/public/login","templated":false}},"message":"User Not Found"}
`
It looks like it is no longer possible to override the error response from inside the ExceptionHandler when the error is produced by the built-in security flow. This had been possible in 1.0.2.

**Comment by puneetbehl** [comment]
Please share a sample application.

**Comment by thestarmaker** [comment]
@puneetbehl - not willing to be rude, the above description is detailed enough, surely you can generate the sample application yourself.

**Comment by puneetbehl** [comment]
@thestarmaker It seems to be working fine, please check the following sample application:
[testapp.zip](https://github.com/micronaut-projects/micronaut-core/files/3055719/testapp.zip)

**Comment by thestarmaker** [comment]
Hi, @puneetbehl, thanks for looking into this. Your example has puzzled me all night yesterday. There are two major differences between what your example does and what I am doing:
1. your example implies running the application and testing it via curl/postman while my application asserts via unit test
2. your example uses explicit `@Replaces(io.micronaut.security.authentication.AuthenticationExceptionHandler.class)` annotation in the ExceptionHandler while my does not and this is not required according to documentation.

I have adapted your code to follow the way how my project has setup (see attachment). I have also stripped my own project down from all the logic and renamed packages (also attached). I am able to reproduce the unwanted response in both cases. What I have also noticed is that it is inconsistent - some test runs yield in expected response while some end up with the default error (inconsistent ordering of exception handlers during assembly??).

See the ExperimentTest in both projects.

[bug-test.zip](https://github.com/micronaut-projects/micronaut-core/files/3057749/bug-test.zip)
[testapp.zip](https://github.com/micronaut-projects/micronaut-core/files/3057750/testapp.zip)

**Comment by puneetbehl** [comment]
The reason I am using `@Replaces` is because there is already a `AuthenticationExceptionHandler` in the micronaut-security. Also, for the sample bug-test.zip works fine by making following changes:
* Updating the test to:
```
@Test
    public void testBug() {
        try (EmbeddedServer server = ApplicationContext.run(EmbeddedServer.class)) {
            try (HttpClient client = server.getApplicationContext()
                    .createBean(HttpClient.class, server.getURL())) {
                LoginDTO login = new LoginDTO("invaliduser", "password");
                HttpRequest<LoginDTO> request = HttpRequest.POST("/example/login", login);
                try {
                    client.toBlocking().exchange(request, Argument.of(String.class), Argument.of(String.class));
                } catch (HttpClientResponseException e) {
                    assertEquals(e.getStatus(), HttpStatus.UNAUTHORIZED);
                    assertEquals(e.getMessage(), "{\"message\":\"MONKEY_BUSINESS\"}");
                }
            }
        }
    }
```
* Instead of Factory, using `@Singleton` on each bean. (No specific reason, just to avoid confusion)
* Annotated Exception Handler to: 
```
@Produces
@Singleton
@Replaces(io.micronaut.security.authentication.AuthenticationExceptionHandler.class)
```

**Comment by thestarmaker** [comment]
Yes, sorry, about the test, I was just looking at the exception stack where it prints the response body. My point is that `@Replaces` is very ambiguous and should not be required - from documentation:

> Additionally you can implement a ExceptionHandler; a generic hook for handling exceptions that occurs during the execution of an HTTP request.

One would assume that once a new instance of `ExceptionHandler` is present it would override all other exception handlers. I believe this is how it did behave in 1.0.2, but is no longer true in 1.1.0.RC2. 

The need for `@Replaces` implies that if I want just one common ExceptionHandler then I need to enumerate ALL other exception handlers there may be defined in Micronaut and there are problems with this: 
* it is not clear what needs replacing as there is no documentation on this
* the developer needs to remember to check that list every time new version of Micronaut is introduced or new Micronaut module dependency is introduced to the project

If I remove the `@Replaces` then the test sometimes fails (possibly because there are two exectption handlers).

**Comment by jameskleeh** [comment]
@thestarmaker The previous behavior in 1.0.x was a bug. The exception handler that matches the exception thrown should be invoked. Given there is a handler for the exception being thrown, it is executed instead. 

You state that you want to replace all exception handlers and we don't have a mechanism to replace all beans of a given type, however I doubt that is the behavior you would want. There are all sorts of exception handlers for dealing with error conditions like content type not supported, multiple routes found, etc that you would have to handle if your handler was the only one.

We'll take this issue as a lesson about introducing new exception handlers, however you should also have tests to verify your code is working as you expect. If there is an issue where which handler that gets invoked is non deterministic as you have suggested, we'll resolve it.
