### ISSUE TITLE
Date Header in Endpoints

### ISSUE THREAD

**Issue by monsdroid** [micronaut-projects/micronaut-core#1498]
### Task List

- [x ] Steps to reproduce provided

### Steps to Reproduce

1. application.yml
```
jackson:
    module-scan: true
    time-zone: Europe/Berlin
```
2. jvm with `-Duser.timezone=Europe/Berlin`
2. enable e.g. Health Endpoint, request it, parse Date Header

### Expected Behaviour

`Date: Mon, 8 Apr 2019 11:21:03 GMT`

### Actual Behaviour

`Date: Mon, 8 Apr 2019 13:21:03 GMT`

### Environment Information

- **Operating System**: Win10
- **Micronaut Version:** 1.1.0.RC2
- **JDK Version:** jdk8-zulu

### 
the user.timezone seems to get ignored

**Comment by jameskleeh** [comment]
@monsdroid Can you try with the latest snapshot?

**Comment by jameskleeh** [comment]
Before the date was being reported with the current date/time in the GMT zone, which is incorrect. The implementation was changed to get the current date time in the system time zone and convert it to GMT.

```
ZonedDateTime.of(LocalDateTime.now(), ZoneId.systemDefault())
        .withZoneSameInstant(ZoneId.of("GMT"))
        .format(DateTimeFormatter.RFC_1123_DATE_TIME) = "Mon, 8 Apr 2019 18:52:32 GMT"

ZonedDateTime.of(LocalDateTime.now(), ZoneId.of("GMT"))
        .format(DateTimeFormatter.RFC_1123_DATE_TIME) = "Mon, 8 Apr 2019 14:52:46 GMT"
```

**Comment by monsdroid** [comment]
Works 👍 

jvm `-Duser.timezone=Europe/Berlin` generates the correct time in date header

thanks for the fast response
