### ISSUE TITLE
Security Intercept URL Map deviates from Docs

### ISSUE THREAD

**Issue by emazzotta** [micronaut-projects/micronaut-core#1510]
In the latest Micronaut Docs the Intercept URL Map is described like so:
https://docs.micronaut.io/latest/guide/index.html#interceptUrlMap

Note that the HTTP method is defined as `http-method`.

However, if you check how Micronaut actually parses this config in `io.micronaut.security.config.InterceptUrlMapConverter` it expects the keyword to be called `httpMethod`.

In fact, if I use `http-method` in my application.yml as described in the docs, the HTTP method part will be ignored, whereas if I use `httpMethod` in my application.yml it works correctly.

I'm not sure if the docs are wrong or if `io.micronaut.security.config.InterceptUrlMapConverter` needs to be changed. Thus I am raising this issue.

### Environment Information

- **Operating System**: macOS Mojave 10.14.4
- **Micronaut Version:** 1.1.0.RC2 (Issue persists with 1.1.0.BUILD-SNAPSHOT)
- **JDK Version:** openjdk version "11.0.2" 2019-01-15

**Comment by jameskleeh** [comment]
Technically the documentation is wrong, however this may represent a use case we aren't supporting right now, which is to support key conventions with type converters

**Comment by jameskleeh** [comment]
I've made it so both ways will work
