### ISSUE TITLE
Allow @Client(path = ) to override services configuration

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#1517]
In 1.0.0. I have following manual load balancer config:

```yaml
micronaut:
  http:
    services:
      myservice:
        urls:
          - http://localhost:8081
```

Now, for following operation:

```java
public interface IOperation {
   	@Post("/op")
	String op();
}
```

I declare following client:

```java
@Client(id = "myservice", path = "/some/path")
public interface IClient extends IOperation {
}
```

What I expect is this code working:

```java
@Singleton
class SomeBean {
  @Inject protected IClient client;

  public void doOp() {
    client.op();
  }
}
```

But it doesn't work, because the client does the request to `http://localhost:8081/op` **instead of** `http://localhost:8081/some/path/op`, because it ignores the `@Client(path)` annotation argument completely.

I've delved into the `HttpClientIntroductionAdvice` code, which is responsible for doing the request, and [here's the culprit](https://github.com/micronaut-projects/micronaut-core/blob/v1.1.0/http-client/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java#L611-L614). This method creates a client with the proper `contextPath`, but only if there is not already defined a http client bean with the service name, and it is defined if you have configured it in yaml. Then the `intercept()` method uses this shared client, but it expects the `contextPath` is already set on the client and it doesn't set its own path.

I've done some workaround [here](https://github.com/micronaut-projects/micronaut-core/blob/v1.1.0/http-client/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java#L348):

```java
// for default http clients taken from load balancer and not prepended with @Client(path) we need to prepend them manually here
if (getClientReturnedSharedClientInstance) {
	String path = clientAnnotation.get("path", String.class).orElse(null);
	if (path != null) {
		uri = path + uri;
	}
}
```

**Comment by jameskleeh** [comment]
You have to specify the path via config:

```
micronaut:
  http:
    services:
      myservice:
        urls:
          - http://localhost:8081
        path: /some/path
```

The documentation clearly states: 

> This client configuration can be used in conjunction with the @Client annotation, either by injecting an HttpClient directly or use on a client interface. In any case, all other attributes on the annotation will be ignored other than the service id.

https://docs.micronaut.io/latest/guide/index.html#clientConfiguration

**Comment by l0co** [comment]
Maybe I understand something wrong here but does it mean that in a service I can only have one client with one hardcoded context path?

**Comment by jameskleeh** [comment]
@l0co If you're creating a service with load balancing supplied by configuration, the context path will be the same for all clients. If you like you can edit the issue to ask for an improvement of the feature to support overriding the configuration with values from the annotation.

**Comment by jameskleeh** [comment]
Note that you can work around this limitation by specifying the context path in your methods.

`@Get("/some/path/hello")`

**Comment by l0co** [comment]
OK, I've changed the title because it looks as a design flaw for me. 

First thing is that I don't see a reason to ignore `@Client(path)` attribute if someone wants to use it. It also doesn't prevent from using the configuation in currently working way (if the `path` property is given in yaml, it can be used as is used now, if the `path` attribute is given on `@Client` it can override the `path` property from yaml).

The second thing is that's quite odd to have a service with only one context path possible by design. This is different that in other frameworks, like in spring boot + spring cloud AFAIR: service is a service (host + port), and it can have multiple endpoints in a single service, and I should be able to easily build clients to these endpoints.

**Comment by l0co** [comment]
OK, I've changed the title because it looks as a design flaw for me. 

First thing is that I don't see a reason to ignore `@Client(path)` attribute if someone wants to use it. It also doesn't prevent from using the configuation in currently working way (if the `path` property is given in yaml, it can be used as is used now, if the `path` attribute is given on `@Client` it can override the `path` property from yaml).

The second thing is that's quite odd to have a service with only one context path possible by design. This is different that in other frameworks, like in spring boot + spring cloud AFAIR: service is a service (host + port), and it can have multiple endpoints in a single service, and I should be able to easily build clients to these endpoints.

**Comment by graemerocher** [comment]
I agree this should be improved and is confusing. Thanks for the feedback

**Comment by l0co** [comment]
I can confirm this works in 1.2.0.RC1.

:+1:

**Comment by oscarfh** [comment]
@jameskleeh is there any documentation I can use as reference to all configurations available? I just spent the whole afternoon with a problem because I could not find any reference to the "path" attribute in the config.

**Comment by mauri-sfdc** [comment]
@jameskleeh is there a documentation we can refer to in order to configure the declarative http client? the path was completely missed because I couldn't find it anywhere. In the same I tried to contribute by adding that to the documentation but is hard to spot where the reference should be.

**Comment by jameskleeh** [comment]
@oscarfh Yes https://docs.micronaut.io/latest/guide/configurationreference.html
@mauri-sfdc Here https://docs.micronaut.io/latest/guide/index.html#clientConfiguration would be a good place to put it
