### ISSUE TITLE
Qualifier example in docs works fortuitously.

### ISSUE THREAD

**Issue by kalexmills** [micronaut-projects/micronaut-core#1520]
[The IoC documentation](https://docs.micronaut.io/latest/guide/index.html#ioc) includes the following example
```
public interface Engine { 
    int getCylinders();
    String start();
}
@Singleton
public class V6Engine implements Engine {  
    public String start() {
        return "Starting V6";
    }

    public int getCylinders() {
        return 6;
    }
}
@Singleton
public class V8Engine implements Engine {
    public String start() {
        return "Starting V8";
    }

    public int getCylinders() {
        return 8;
    }

}
@Singleton
public class Vehicle {
    private final Engine engine;

    @Inject
    public Vehicle(@Named("v8") Engine engine) {
        this.engine = engine;
    }

    public String start() {
        return engine.start();
    }
}
```
Running this in a small project indeed causes `V8Engine` to be injected, but this seems to just be good luck, as there are no `@Named` annotations on either of the `Engine` implementations.

I would open a PR, but I can't find where the snippets are being stored in this repo.

**Comment by kalexmills** [comment]
Perhaps more concerning -- running the above code with the following main method does not yield a `NonUniqueBeanException`, despite two conflicting implementations of `Engine`

```
import io.micronaut.context.BeanContext;

class Main {
  public static void main(String[] args) {
    Vehicle vehicle = BeanContext.run().getBean(Vehicle.class);
    System.out.println(vehicle.start());
  }
}
```

**Comment by jameskleeh** [comment]
@kalexmills This is how the JSR-330 specification says this should work. The implementations are not conflicting because the V8Engine bean class name matches the name qualifier plus the bean type requested. `Named("v8") Engine engine` -> `V8Engine`

**Comment by jameskleeh** [comment]
See https://github.com/javax-inject/javax-inject/blob/1f74ea7bd05ce4a3a62ddfe4a2511bf1b4287a61/tck/org/atinject/tck/auto/V8Engine.java#L40

`seatB` will be inject with a `DriversSeat` and `tireB` will be injected with a `SpareTire`

The `DriversSeat` class lacks the qualifier https://github.com/javax-inject/javax-inject/blob/1f74ea7bd05ce4a3a62ddfe4a2511bf1b4287a61/tck/org/atinject/tck/auto/DriversSeat.java

The `SpareTire` class lacks the named qualifier https://github.com/javax-inject/javax-inject/blob/1f74ea7bd05ce4a3a62ddfe4a2511bf1b4287a61/tck/org/atinject/tck/auto/accessories/SpareTire.java
