### ISSUE TITLE
CLI interactive mode retains features when creating multiple projects

### ISSUE THREAD

**Issue by edgargs** [micronaut-projects/micronaut-core#1527]
### Task List

- [ X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ X] Full description of the issue provided (see below)

### Steps to Reproduce

1. mn
2. create-app --features spock com.gs.app-spock
3. create-app com.gs.app-junit
4. exit

### Expected Behaviour

Second project "app-junit" contains the feature test JUnit.

### Actual Behaviour

Both projects contain the "spock" feature.

![Captura de pantalla de 2019-04-12 10-38-24](https://user-images.githubusercontent.com/11461983/56049512-3f55f000-5d0f-11e9-916b-6e29cc9f2420.png)

### Environment Information

- **Operating System**: Ubuntu 18.10
- **Micronaut Version:** 1.1.0
- **JDK Version:** 1.8.0_202

**Comment by graemerocher** [comment]
interesting, good catch. Thanks for the report!

**Comment by ilopmar** [comment]
While testing the fix for this issue I've found another one. If we create the same application twice:
```
$ mn
| Starting interactive mode...
| Enter a command name to run. Use TAB for completion:
mn> create-app --features spock com.gs.app-spock
| Generating Java project...
| Application created at /tmp/app-spock
| Initializing application. Please wait...
mn> create-app --features spock com.gs.app-spock2
| Generating Java project...
| Application created at /tmp/app-spock2
| Initializing application. Please wait...
```

The second one doesn't contain all the files:

![image](https://user-images.githubusercontent.com/559192/56651827-3ad3f480-668a-11e9-8a00-93d9103034ed.png)

I'm going to fix this too.
