### ISSUE TITLE
Static resources has default Cache-Control: private header value, this does not work well with cache servers like Varnish

### ISSUE THREAD

**Issue by olavgg** [micronaut-projects/micronaut-core#1528]
### Steps to Reproduce

1. Fetch a static resource and check its cache-control header

### Expected Behaviour

A static resource is often a public resource, like a js/css/image file and should be cacheable.

### Actual Behaviour

The cache-control: private value makes some cache server like Varnish ignore the resource

**Comment by jameskleeh** [comment]
@olavgg What are you suggesting? A more sensible default or making it configurable?

**Comment by olavgg** [comment]
Static resources are cacheable, so in my opinion setting the cache-control header to public + max age is good enough. You can still fetch static resources through a controller and change the cache-control if needed. So I see no value in making it configurable.

**Comment by jameskleeh** [comment]
Rather than changing the header, which may not be desirable for some, I've added a configuration option that can be changed
