### ISSUE TITLE
Annotation-less DI prevents using whole delegation concept in Kotlin.

### ISSUE THREAD

**Issue by soberich** [micronaut-projects/micronaut-core#1530]
HI, 
Simply having class
```kotlin
@Controller("/api")
class Resource(FX: Fx<ForFluxK> = FluxK.fx()) :  Fx<ForFluxK> by FX
```
gives you

```console
Unexpected error occurred: Error instantiating bean of type  [com.example.web.rest.Resource]
Path Taken: new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
new Resource([Fx FX]) -->
...
```

I think this abopted from Spring where they unfortunately allowed container to try to inject parameters in constructor even without `javax.inject.Inject` (or similar) as a "feature". 
I am new to Micronaut, but I think this is huge. The whole concept of delegating from Kotlin thrown away.
It even looks better when injection is marked, than a ctor which has nothing on it but "something" does him.
I'd propose to only inject when there is `javax.inject.Inject` say starting form 1.2.0 or smth like that.

**Comment by graemerocher** [comment]
I think what is missing here is support for Kotlin default arguments

**Comment by jameskleeh** [comment]
You can add an empty constructor and annotate it with `@Inject` to work around this issue

**Comment by soberich** [comment]
@graemerocher yes this one is also, but it is more understandable. @jameskleeh thank you.

**Comment by soberich** [comment]
@graemerocher any comment on this? Is it hard to implement and not worth effort or something like it?

**Comment by graemerocher** [comment]
Currently nothing is exposed via KAPT for us to interpret this. We would need to re-implement KAPT and write a native Kotlin plugin. That is a larger piece of work that if done we could maybe reconsider this issue

**Comment by soberich** [comment]
@graemerocher 
would these help?

[[KT-29355 - YouTrack - JetBrains] Provide access to default values for primary constructor properties](https://youtrack.jetbrains.com/issue/KT-29355)

[Kapt: Add DUMP_DEFAULT_PARAMETER_VALUES flag (KT-29355)](https://github.com/JetBrains/kotlin/commit/2044ece33564696792a7d9971208bc656b89bb06)
