### ISSUE TITLE
Error starting Micronaut container: No bean of type [io.micronaut.jackson.codec.JsonMediaTypeCodec] exists.

### ISSUE THREAD

**Issue by rama99526** [micronaut-projects/micronaut-core#1533]
#### issue 1:

1. Import the project to intelliJ
2. run ./gradlew clean
3. open deploy_aws.sh file and modify the amazon account
4. run ./deploy_aws.sh 
5. aws lambda invoke --function-name example-function --payload '{"resource": "/{proxy+}", "path": "/ping", "httpMethod": "GET"}' build/response.txt
6. cat build/response.txt

### Expected Behaviour

{
    "pong": true
}

### Actual Behaviour
{
    "FunctionError": "Unhandled", 
    "ExecutedVersion": "$LATEST", 
    "StatusCode": 200
}

Exceptoin in lambda logs

[main] INFO io.micronaut.function.aws.proxy.AbstractLambdaContainerHandler - Starting Lambda Container Handler
[main] INFO io.micronaut.context.env.DefaultEnvironment - Established active environments: [function]
com.amazonaws.serverless.exceptions.ContainerInitializationException: Error starting Micronaut container: No bean of type [io.micronaut.jackson.codec.JsonMediaTypeCodec] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.initialize(MicronautLambdaContainerHandler.java:191)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.<init>(MicronautLambdaContainerHandler.java:104)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.<init>(MicronautLambdaContainerHandler.java:113)
        at io.micronaut.function.aws.proxy.MicronautLambdaContainerHandler.getAwsProxyHandler(MicronautLambdaContainerHandler.java:122)
        at example.StreamLambdaHandler.<clinit>(StreamLambdaHandler.java:13)

### Environment Information

Operating System: Mac OS High Sierra ( 10.13.6 )
Micronaut Version: 1.1.0.M2
JDK Version:
    java version "1.8.0_201"
  Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
  Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

### Example Application

[api-proxy-graal-custom-runtime-example.zip](https://github.com/micronaut-projects/micronaut-core/files/3076796/api-proxy-graal-custom-runtime-example.zip)

**Comment by raviagarwal101** [comment]
I saw this issue as well and was able to resolve by adding **ServicesResourceTransformer** to the maven shade plugin:
`            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

`

**Comment by jameskleeh** [comment]
@raviagarwal101 @rama99526 Were those applications created with the CLI? As far as I can see that would have been added already if so

**Comment by athkalia** [comment]
May help future readers:

I was getting the same error with a non-native GraalVM app because I forgot to add the 

```
shadowJar {
    mergeServiceFiles()
}
```
[ShadowJar Gradle plugin](https://github.com/johnrengelman/shadow) configuration in my `build.gradle` file.
