### ISSUE TITLE
persistence events and Autotimestamp aren't working

### ISSUE THREAD

**Issue by benlucchesi** [micronaut-projects/micronaut-core#1538]
Steps to reproduce:

1. Create an entity and create dateCreated and lastModified and add beforeInsert. example:
```
@Entity
class Customer {
   Date dateCreated
   Date lastUpdated
   ...
}
```
2. Create an instance of the entity and save.

**Expected behavior**: 
`dateCreated` and `lastModified` get current time assigned to them and the `beforeInsert` gets called.

**Actual behavior**:
Record fails to save because `dateCreated` is `null` and `beforeInsert` is never called.

Micronaut Version: 1.1.0

The last time this functionality worked as expected was 1.1.0.RC1

**Comment by ibmsoft** [comment]
same problem,
