### ISSUE TITLE
ServerStartupEvent not execute

### ISSUE THREAD

**Issue by ibmsoft** [micronaut-projects/micronaut-core#1545]
micronaut 1.1.0

following the doc 

mn create-app my-app --features hibernate-gorm

then in Application

`
package com.zysoft

import com.zysoft.trench.domain.Tks
import groovy.transform.CompileStatic
import groovy.util.logging.Slf4j
import io.micronaut.context.event.ApplicationEventListener
import io.micronaut.runtime.Micronaut
import io.micronaut.runtime.server.event.ServerStartupEvent

@Slf4j
@CompileStatic
class Application implements ApplicationEventListener<ServerStartupEvent> {
    static void main(String[] args) {
        Micronaut.run(Application)
    }

    @Override
    void onApplicationEvent(ServerStartupEvent event) {
        printf "start"
    }
}
`

or use debug ,the onApplicationEvent can not arrive

**Comment by graemerocher** [comment]
This is not a bug as such, it just happened to work by luck before, when implementing events you must provide a type argument, in this case `ApplicationEventListener<ServerStartupEvent>` and they must be declared as beans. By just using the raw type `ApplicationEventListener` it is essentially saying you are interested in all event types and there were likely class cast exceptions occuring when invoking the listener.
