### ISSUE TITLE
Start is slow on UBUNTU

### ISSUE THREAD

**Issue by marcdexet-cnrs** [micronaut-projects/micronaut-core#1552]
I'm doing a micronaut tutorial  (https://alvarosanchez.github.io/micronaut-workshop/ )

The starting is very slow ( > 3 mn), and I'm not on Mac :)

## Steps to reproduce provided

- Create hello-world example
- gradlew run

### Expected Behaviour

Starting fast as announced

### Actual Behaviour

taking 2mn to start

### Environment Information

- **Operating System**: UBUNTU 18.04 TODO
- **Micronaut Version:** 1.1.0
- **JDK Version:** OpenJDK Runtime Environment (build 1.8.0_191-8u191-b12-2ubuntu0.18.04.1-b12)
- **Network configuration**: 
```
127.0.0.1	localhost my-hostname
#127.0.1.1	my-hostname

# The following lines are desirable for IPv6 capable hosts
#::1     ip6-localhost ip6-loopback localhost my-hostname
::1     localhost my-hostname
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by marcdexet-cnrs** [comment]
The biggest "gap" in log is between 

`10:58:23.334 [main] DEBUG i.m.context.env.DefaultEnvironment - Environment deduction is using the default of: true`

and 

`11:00:14.228 [main] DEBUG i.m.context.env.DefaultEnvironment - Starting environment io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@15d0c81b for active names []`


The begin of the log is given here


```
10:58:23.309 [main] DEBUG io.micronaut.core.reflect.ClassUtils - Attempting to dynamically load class com.fasterxml.jackson.databind.Module
10:58:23.311 [main] DEBUG io.micronaut.core.reflect.ClassUtils - Successfully loaded class com.fasterxml.jackson.databind.Module
10:58:23.334 [main] DEBUG i.m.context.env.DefaultEnvironment - Environment deduction is using the default of: true
11:00:14.228 [main] DEBUG i.m.context.env.DefaultEnvironment - Starting environment io.micronaut.context.DefaultApplicationContext$RuntimeConfiguredEnvironment@15d0c81b for active names []
11:00:14.234 [main] DEBUG i.m.context.env.DefaultEnvironment - Reading property sources from loader: io.micronaut.jackson.env.JsonPropertySourceLoader@2a742aa2
11:00:14.234 [main] DEBUG i.m.c.e.AbstractPropertySourceLoader - No PropertySource found for file name: application.json
11:00:14.234 [main] DEBUG i.m.context.env.DefaultEnvironment - Reading property sources from loader: io.micronaut.jackson.env.EnvJsonPropertySourceLoader@467aecef
11:00:14.234 [main] DEBUG i.m.c.e.AbstractPropertySourceLoader - No PropertySource found for file name: application.json
11:00:14.234 [main] DEBUG i.m.context.env.DefaultEnvironment - Reading property sources from loader: io.micronaut.context.env.yaml.YamlPropertySourceLoader@4d50efb8
11:00:14.236 [main] DEBUG i.m.c.e.AbstractPropertySourceLoader - Found PropertySource for file name: application.yml
11:00:14.256 [main] DEBUG i.m.context.env.DefaultEnvironment - Reading property sources from loader: io.micronaut.context.env.PropertiesPropertySourceLoader@2698dc7
11:00:14.256 [main] DEBUG i.m.c.e.AbstractPropertySourceLoader - No PropertySource found for file name: application.properties
11:00:14.260 [main] DEBUG i.m.context.env.DefaultEnvironment - Processing property source: application
11:00:14.260 [main] TRACE i.m.c.e.PropertySourcePropertyResolver - Processing property key micronaut.application.name
11:00:14.261 [main] DEBUG i.m.context.env.DefaultEnvironment - Processing property source: env
11:00:14.261 [main] TRACE i.m.c.e.PropertySourcePropertyResolver - Processing property key NVM_RC_VERSION

```

**Comment by graemerocher** [comment]
Problems like this are typically related to your network configuration in `/etc/hosts`. You can try pass `-Dmicronaut.env.deduction=false` to see if that helps

**Comment by graemerocher** [comment]
if you are using Maven:

```xml
     <arguments>
            <!-- Non production flags -->
            <argument>-noverify</argument>
            <argument>-Dmicronaut.env.deduction=false</argument>
            <argument>-XX:TieredStopAtLevel=1</argument>
            <argument>-Dcom.sun.management.jmxremote</argument>
            <argument>-classpath</argument>
            <classpath/>
            <argument>${exec.mainClass}</argument>
          </arguments>
```

or Gradle:

```groovy
run.jvmArgs('-Dmicronaut.env.deduction=false', '-noverify', '-XX:TieredStopAtLevel=1', '-Dcom.sun.management.jmxremote')
```

**Comment by marcdexet-cnrs** [comment]
> if you are using Maven:
> 
> ```
>      <arguments>
>             
>             <argument>-noverify</argument>
>             <argument>-Dmicronaut.env.deduction=false</argument>
>             <argument>-XX:TieredStopAtLevel=1</argument>
>             <argument>-Dcom.sun.management.jmxremote</argument>
>             <argument>-classpath</argument>
>             <classpath/>
>             <argument>${exec.mainClass}</argument>
>           </arguments>
> ```
> 
> or Gradle:
> 
> ```groovy
> run.jvmArgs('-Dmicronaut.env.deduction=false', '-noverify', '-XX:TieredStopAtLevel=1', '-Dcom.sun.management.jmxremote')
> ```

You hit the nail Graeme !

4s to start with this option :)

So the next step is : why in my configuration the deduction = true is so painful ?

poke @alvarosanchez

**Comment by marcdexet-cnrs** [comment]
But when I run `gradlew test` (with a dummy Controller test) is still slow, very slow, as if the option doesn't affect test running.

**Comment by marcdexet-cnrs** [comment]
I test inetAddress with this little script 
```
def timeIt = { resultFormatter = { obj -> obj?.toString() }, closure ->
    def start = System.nanoTime()
    def result = null
    try {
        result = closure()
    } catch (Exception e) {
        result = e
    }
    def end = System.nanoTime()
    def ms = (end - start) / 1e6
    if (resultFormatter) {
        println "Result ${resultFormatter(result)} obtained in $ms ms"
    }
    [result, ms]
}

timeIt {
        println(InetAddress.getLocalHost())
}
```

I get _null_ value is 6 ms.
But _null_ for localhost, is it not odd ?

**Comment by graemerocher** [comment]
There is definitely something add with your local network setup. Even 4s is still slow. As for testing, you would need to modify the `test` JVM parameters in the same way. But really this is just working around the core issue which is something wrong with your network config.

**Comment by marcdexet-cnrs** [comment]
Forget the null value from inetAddress, it's a misreading from me.

I validate the test solution also with 

```
test {
    jvmArgs '-Dmicronaut.env.deduction=false'
    useJUnitPlatform()
}
```

**Comment by jameskleeh** [comment]
Closing this as there doesn't seem to be anything we can do here

**Comment by botcoder** [comment]
This is an old thread but I had the same issue on a brand new setup running Ubuntu and Micronaut **2.3.1**. 

Disabling deduction works, but an alternative is mapping "metadata.google.internal" to localhost (`DefaultEnvironment#GOOGLE_COMPUTE_METADATA`), as it timeouts otherwise.
