### ISSUE TITLE
Intellij watch is stopping app on file change

### ISSUE THREAD

**Issue by zulq** [micronaut-projects/micronaut-core#1556]
Watch is killing the app with every file changed, is there a way to restart the app instead.
### Steps to Reproduce

1. Create new app with watch.
2. Run the app.
3. Change any of the source files.

### Expected Behaviour
App should be restarted

### Actual Behaviour
App is stopped

### Environment Information

- **Operating System**: Windows
- **Micronaut Version:** 1.1.0
- **JDK Version:** 11.0.1

**Comment by monsdroid** [comment]
Did you put `--continuous` in the `Arguments` Field in the intellij run configuration for your gradle task?

**Comment by zulq** [comment]
Thanks @monsdroid, missed that.
