### ISSUE TITLE
illegal reflective access 

### ISSUE THREAD

**Issue by scarlier** [micronaut-projects/micronaut-core#1560]
### Steps to Reproduce

1. Gradle build from intelij

### Expected Behaviour
Build without warning

### Actual Behaviour
Got the following warning

```
Task :appCommon:compileJava
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.micronaut.core.reflect.ReflectionUtils (file:/Users/nova/.gradle/caches/modules-2/files-2.1/io.micronaut/micronaut-core/1.1.0/f1fb118f0caf467137b1a3be97a22cd749c19f4a/micronaut-core-1.1.0.jar) to method com.sun.tools.javac.processing.JavacProcessingEnvironment.getContext()
WARNING: Please consider reporting this to the maintainers of io.micronaut.core.reflect.ReflectionUtils
```

### Environment Information

- **Operating System**: OSX 10.14.3
- **Micronaut Version:** 1.1
- **JDK Version:** 8

**Comment by jameskleeh** [comment]
Please provide a sample application

**Comment by graemerocher** [comment]
Think I know where this is coming from

**Comment by wdroste** [comment]
Same issue:

```
openjdk` version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment Zulu11.31+11-CA (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.31+11-CA (build 11.0.3+7-LTS, mixed mode)
```

**Comment by heimdall777** [comment]
Same issue:
`openjdk 12.0.1 2019-04-16
OpenJDK Runtime Environment Zulu12.2+3-CA (build 12.0.1+12)
OpenJDK 64-Bit Server VM Zulu12.2+3-CA (build 12.0.1+12, mixed mode, sharing)`

**System:** Ubuntu 19.04

**Comment by scarlier** [comment]
i am using the latest version of amazon Corretto 8
