### ISSUE TITLE
Validation based on validation rules

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-core#1561]
```
class Registration(val email: String,
                   val password: String,
                   val promoCode: String?) {

    fun constraints(userDao: UserDao): List<ValidationRule> {
        // userDao is injected, and can be used to check if email is not already taken in database
        return listOf(
            Registration::email {
                minLength(3)
                maxLength(100)
            },
            Registration::password {
                minLength(8)
                maxLength(40)
            }
        )
    }
}
```
So, proposal is to include validation rules(something like https://laravel.com/docs/5.8/validation) in DTO instead of validation based on annotations.

In this case:
- no need for reflection or annotation processor
- all validations are in one place, even if you have a complex one no need to have same validation as annotation, and another validation in another class
- can be used for complex validation
- normalization can be done before validation, for example first we need omit spaces in email, than to do validation

A good example could be https://docs.grails.org/latest/ref/Constraints/Usage.html

**Comment by jameskleeh** [comment]
@raderio Micronaut is based on annotation processing which has its pros and cons compared to the functional style. I don't think it's worth debating annotations vs functional in this issue, however at least for validation I don't think this is something we're interested in pursuing

**Comment by raderio** [comment]
Yes, it is based on annotation processing, but this doesn't mean that everything should be implemented based on annotations.
Can you please enumerate some pros for annotation style?

**Comment by graemerocher** [comment]
One challenge with this is it is pretty hard to come up with a typesafe API that works across all the languages we support

**Comment by raderio** [comment]
Kotlin and Groovy as I understand is not a problem. So, the issue is just with Java.

Maybe validation can be done like: read annotations, generate validation rules based on annotation(like in this proposal), execute validation.

in this case in Kotlin validation can start directly from step 2, or from step 1 if someone want.

**Comment by raderio** [comment]
@graemerocher what do you think about this flow?

**Comment by graemerocher** [comment]
It may be possible, to make the annotations drive some validation rules that could also be setup programmatically. I will give it some thought.

**Comment by raderio** [comment]
@graemerocher any thoughts about this?

**Comment by graemerocher** [comment]
I think it is doable, but is probably not in scope for 1.2 and is more a nice to have.

**Comment by raderio** [comment]
Another use case that we have is that validation depends on client setup, so for example for one client a field is mandatory, but for other clients this field is optional.

I am not sure how this can be implemented on the annotations.

**Comment by jameskleeh** [comment]
That can be done with validation groups I believe

**Comment by raderio** [comment]
I ma not sure how this can be implemented by groups.

BTW, we have 10 clients like this at the moment, but they can grow to hundreds, even if this somehow will be possible by groups, to have hundreds of groups and maintain them will be a nightmare.

We store this information in database, and before validation retrieve this rules.
