### ISSUE TITLE
@Factory with two @Context @Bean creates only one instance

### ISSUE THREAD

**Issue by ivyazmitinov** [micronaut-projects/micronaut-core#1574]
### Steps to Reproduce

1. Create `Strategy` interface and two implementations of it
2. Create `Container` class, taking `Set` of strategies as constructor parameter
3. Create three `@Factory`, producing one `Container` and two `Strategy` beans, all `@Named`

### Expected Behaviour

Three instances of `Container`  class should be created, each is injected with corresponding two `Strategy` beans

### Actual Behaviour

Two `Container` instances contain only one strategy implementation.

This bug is not reproduced with `@Singleton`, also a name and quantity of `@Factory` classes matters.

As far as I understood, problem is with `io.micronaut.context.DefaultBeanContext#doCreateBean()`: for some configurations declared calss (`Strategy`) is used as part of`BeanKey` instead of implementation class. So, when micronaut tries to resolve second `Strategy`, `io.micronaut.context.DefaultBeanContext#doCreateBean()` returns implementation created before.

### Environment Information

- **Micronaut Version:** 1.1.0

### Example Application

https://github.com/ivyazmitinov/micronaut-context-beans-bug

See `com.bug.config.ConfigTwo`. If replace return types to `Strategy` in `com.bug.config.ConfigThree`, reproduces there as well.

**Comment by jameskleeh** [comment]
Micronaut uses the combination of bean type and qualifier as a unique identifier for singletons. The example that you included, `ConfigThree`, is the correct way to do what you want to do.

**Comment by ivyazmitinov** [comment]
@jameskleeh Thanks for clarification. Would it make sense to implement some validation of `@Factory` classes for such cases?
