### ISSUE TITLE
jacksondecode is fails to parse json with graphql queries when fetched from react-native on android

### ISSUE THREAD

**Issue by benlucchesi** [micronaut-projects/micronaut-core#1577]
issue: react native fetch is unable to successfully query into a gorm-graphql configured micronaut app.

steps to reproduce:
1) create a micronaut app and install gorm-graphql. 
2) add a domain object, for example User and add static graphql = true
3) create a react native app and run it in expo on an android device
4) write a simple query for a list of users and use fetch to post the query to the server. for example:
    const fr = await fetch( 'http://xxxxxxxxx:8080/graphql', {
          method: 'POST',
          headers: {
             'Content-Type': 'application/json',
             'Authorization': 'Bearer ....................................'
         },
         body: '{"query":"{ userList { id } }"}'
      })
   .then(res => res.text())
   .then(res => {
       console.log(res)}
   );
// NOTE: this will work from a browser....

5) run the react-native app. 
result: the fetch call fails with 422, Could not process GraphQL request
expected result: call succeeds and returns a list of users if there are any

Here's a log from the server demonstrating the failure. Notice how the call fails on the routinginboundhandler with a error emitted from the jacksonmediattypecodec. No graphql code is reached!!!!!!!!!!! Its failing on the decode.
(please ignore some of the odd headers I've added - I was trying to replicate a successful call, which is shown below)

         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 4f 53 54 20 2f 67 72 61 70 68 71 6c 20 48 54 |POST /graphql HT|
|00000010| 54 50 2f 31 2e 31 0d 0a 61 75 74 68 6f 72 69 7a |TP/1.1..authoriz|
|00000020| 61 74 69 6f 6e 3a 20 42 65 61 72 65 72 20 65 79 |ation: Bearer ey|
|00000030| 4a 68 62 47 63 69 4f 69 4a 75 62 32 35 6c 49 6e |JhbGciOiJub25lIn|
|00000040| XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX |XXXXXXXXXXXXXX|
|00000050| XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX |XXXXXXXXXXXXX|
|00000060| XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX |XXXXXXXXXXXXXX|
|00000070| XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX |XXXXXXXXXXXXXX|
|00000080| XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX |XXXXXXXXXXXXXX|
|00000090| 4d 69 4f 69 4a 68 64 58 52 6f 5a 57 35 30 61 57 |MiOiJhdXRoZW50aW|
|000000a0| 4e 68 64 47 6c 76 62 69 49 73 49 6d 56 34 63 43 |NhdGlvbiIsImV4cC|
|000000b0| 49 36 4d 54 55 31 4e 6a 41 34 4f 54 63 34 4e 69 |I6MTU1NjA4OTc4Ni|
|000000c0| 77 69 61 57 46 30 49 6a 6f 78 4e 54 55 32 4d 44 |wiaWF0IjoxNTU2MD|
|000000d0| 67 32 4d 54 67 32 66 51 2e 0d 0a 43 6f 6e 74 65 |g2MTg2fQ...Conte|
|000000e0| 6e 74 2d 54 79 70 65 3a 20 61 70 70 6c 69 63 61 |nt-Type: applica|
|000000f0| 74 69 6f 6e 2f 6a 73 6f 6e 3b 20 63 68 61 72 73 |tion/json; chars|
|00000100| 65 74 3d 75 74 66 2d 38 0d 0a 43 6f 6e 74 65 6e |et=utf-8..Conten|
|00000110| 74 2d 4c 65 6e 67 74 68 3a 20 33 31 0d 0a 48 6f |t-Length: 31..Ho|
|00000120| 73 74 3a 20 61 70 69 2e 64 6f 6e 74 64 72 69 76 |st: api.xxxxxx|
|00000130| 65 2e 6f 6e 73 74 61 67 65 74 65 63 68 2e 63 6f |e.xxxxx.co|
|00000140| 6d 0d 0a 41 63 63 65 70 74 2d 45 6e 63 6f 64 69 |m..Accept-Encodi|
|00000150| 6e 67 3a 20 67 7a 69 70 0d 0a 55 73 65 72 2d 41 |ng: gzip..User-A|
|00000160| 67 65 6e 74 3a 20 6f 6b 68 74 74 70 2f 33 2e 36 |gent: okhttp/3.6|
|00000170| 2e 30 0d 0a 58 2d 46 6f 72 77 61 72 64 65 64 2d |.0..X-Forwarded-|
|00000180| 50 6f 72 74 3a 20 38 30 0d 0a 58 2d 46 6f 72 77 |Port: 80..X-Forw|
|00000190| 61 72 64 65 64 2d 50 72 6f 74 6f 3a 20 68 74 74 |arded-Proto: htt|
|000001a0| 70 0d 0a 58 2d 43 79 63 6c 65 2d 4c 69 73 74 65 |p..X-Cycle-Liste|
|000001b0| 6e 69 6e 67 2d 48 54 54 50 53 3a 20 6e 6f 0d 0a |ning-HTTPS: no..|
|000001c0| 58 2d 46 6f 72 77 61 72 64 65 64 2d 46 6f 72 3a |X-Forwarded-For:|
|000001d0| 20 3a 3a 66 66 66 66 3a 37 31 2e 39 32 2e 39 34 | ::ffff:71.92.94|
|000001e0| 2e 31 30 34 0d 0a 0d 0a 7b 22 71 75 65 72 79 22 |.104....{"query"|
|000001f0| 3a 22 7b 20 75 73 65 72 4c 69 73 74 20 7b 20 69 |:"{ userList { i|
|00000200| 64 20 7d 20 7d 22 7d                            |d } }"}         |
+--------+-------------------------------------------------+----------------+

07:02:35.817 [nioEventLoopGroup-1-3] DEBUG i.m.h.server.netty.NettyHttpServer - Server localhost:8080 Received Request: POST /graphql
07:02:35.818 [nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matching route POST - /graphql
07:02:35.819 [nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matched route POST - /graphql to controller class io.micronaut.configuration.graphql.GraphQLController
07:02:35.822 [nioEventLoopGroup-1-3] TRACE i.n.handler.logging.LoggingHandler - [id: 0x4b1b7609, L:/fd00:0:0:0:ec:c6e5:1:1:8080 - R:/fd00:0:0:0:ec:692a:1:1:58556] READ COMPLETE
07:02:35.822 [nioEventLoopGroup-1-3] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: IDLE) received demand: 2
07:02:35.823 [nioEventLoopGroup-1-3] TRACE i.m.h.n.reactive.HandlerPublisher - Demand received for next message (state = DEMANDING). Calling context.read()
07:02:35.823 [nioEventLoopGroup-1-3] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: DEMANDING) emitting next message: {"query":"{ userList { id } }"}
07:02:35.824 [nioEventLoopGroup-1-3] TRACE i.m.h.n.reactive.HandlerPublisher - Demand received for next message (state = DEMANDING). Calling context.read()
07:02:35.830 [nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Encoding emitted response object [Could not process GraphQL request] using codec: io.micronaut.jackson.codec.JsonMediaTypeCodec@5fe53712
07:02:35.836 [nioEventLoopGroup-1-3] TRACE i.n.handler.logging.LoggingHandler - [id: 0x4b1b7609, L:/fd00:0:0:0:ec:c6e5:1:1:8080 - R:/fd00:0:0:0:ec:692a:1:1:58556] WRITE: 249B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 31 20 34 32 32 20 55 6e 70 |HTTP/1.1 422 Unp|
|00000010| 72 6f 63 65 73 73 61 62 6c 65 20 45 6e 74 69 74 |rocessable Entit|
|00000020| 79 0d 0a 44 61 74 65 3a 20 57 65 64 2c 20 32 34 |y..Date: Wed, 24|
|00000030| 20 41 70 72 20 32 30 31 39 20 30 37 3a 30 32 3a | Apr 2019 07:02:|
|00000040| 33 35 20 47 4d 54 0d 0a 63 6f 6e 74 65 6e 74 2d |35 GMT..content-|
|00000050| 74 79 70 65 3a 20 61 70 70 6c 69 63 61 74 69 6f |type: applicatio|
|00000060| 6e 2f 6a 73 6f 6e 0d 0a 63 6f 6e 74 65 6e 74 2d |n/json..content-|
|00000070| 6c 65 6e 67 74 68 3a 20 31 30 33 0d 0a 63 6f 6e |length: 103..con|
|00000080| 6e 65 63 74 69 6f 6e 3a 20 63 6c 6f 73 65 0d 0a |nection: close..|
|00000090| 0d 0a 7b 22 5f 6c 69 6e 6b 73 22 3a 7b 22 73 65 |..{"_links":{"se|
|000000a0| 6c 66 22 3a 7b 22 68 72 65 66 22 3a 22 2f 67 72 |lf":{"href":"/gr|
|000000b0| 61 70 68 71 6c 22 2c 22 74 65 6d 70 6c 61 74 65 |aphql","template|
|000000c0| 64 22 3a 66 61 6c 73 65 7d 7d 2c 22 6d 65 73 73 |d":false}},"mess|
|000000d0| 61 67 65 22 3a 22 43 6f 75 6c 64 20 6e 6f 74 20 |age":"Could not |
|000000e0| 70 72 6f 63 65 73 73 20 47 72 61 70 68 51 4c 20 |process GraphQL |
|000000f0| 72 65 71 75 65 73 74 22 7d                      |request"}       |
+--------+-------------------------------------------------+----------------+
07:02:35.838 [nioEventLoopGroup-1-3] TRACE i.n.handler.logging.LoggingHandler - [id: 0x4b1b7609, L:/fd00:0:0:0:ec:c6e5:1:1:8080 - R:/fd00:0:0:0:ec:692a:1:1:58556] FLUSH
07:02:35.839 [nioEventLoopGroup-1-3] TRACE i.n.handler.logging.LoggingHandler - [id: 0x4b1b7609, L:/fd00:0:0:0:ec:c6e5:1:1:8080 - R:/fd00:0:0:0:ec:692a:1:1:58556] CLOSE
07:02:35.840 [nioEventLoopGroup-1-3] TRACE i.n.handler.logging.LoggingHandler - [id: 0x4b1b7609, L:/fd00:0:0:0:ec:c6e5:1:1:8080 ! R:/fd00:0:0:0:ec:692a:1:1:58556] CLOSE
07:02:35.840 [nioEventLoopGroup-1-3] TRACE i.n.handler.logging.LoggingHandler - [id: 0x4b1b7609, L:/fd00:0:0:0:ec:c6e5:1:1:8080 ! R:/fd00:0:0:0:ec:692a:1:1:58556] FLUSH
07:02:35.841 [nioEventLoopGroup-1-3] TRACE i.n.handler.logging.LoggingHandler - [id: 0x4b1b7609, L:/fd00:0:0:0:ec:c6e5:1:1:8080 ! R:/fd00:0:0:0:ec:692a:1:1:58556] INACTIVE
07:02:35.842 [nioEventLoopGroup-1-3] TRACE i.n.handler.logging.LoggingHandler - [id: 0x4b1b7609, L:/fd00:0:0:0:ec:c6e5:1:1:8080 ! R:/fd00:0:0:0:ec:692a:1:1:58556] UNREGISTERED

**Now here's an example of the exact same query being made from rest client in a browser:**
This time the exact same query /w the same representation in the request is successfully handed off to the graphql handler.

         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 50 4f 53 54 20 2f 67 72 61 70 68 71 6c 20 48 54 |POST /graphql HT|
|00000010| 54 50 2f 31 2e 31 0d 0a 48 6f 73 74 3a 20 61 70 |TP/1.1..Host: ap|
|00000020| 69 2e 64 6f 6e 74 64 72 69 76 65 2e 6f 6e 73 74 |i.xxxxxx.onst|
|00000030| 61 67 65 74 65 63 68 2e 63 6f 6d 3a 38 30 38 30 |agxxxxh.com:8080|
|00000040| 0d 0a 43 6f 6e 6e 65 63 74 69 6f 6e 3a 20 6b 65 |..Connection: ke|
|00000050| 65 70 2d 61 6c 69 76 65 0d 0a 43 6f 6e 74 65 6e |ep-alive..Conten|
|00000060| 74 2d 4c 65 6e 67 74 68 3a 20 33 31 0d 0a 41 63 |t-Length: 31..Ac|
|00000070| 63 65 70 74 3a 20 61 70 70 6c 69 63 61 74 69 6f |cept: applicatio|
|00000080| 6e 2f 6a 73 6f 6e 0d 0a 4f 72 69 67 69 6e 3a 20 |n/json..Origin: |
|00000090| 63 68 72 6f 6d 65 2d 65 78 74 65 6e 73 69 6f 6e |chrome-extension|
|000000a0| 3a 2f 2f 65 68 61 66 61 64 63 63 64 63 64 65 64 |://ehafadccdcded|
|000000b0| 62 68 63 62 64 64 69 68 65 68 69 6f 64 67 63 64 |bhcbddihehiodgcd|
|000000c0| 64 70 6c 0d 0a 41 75 74 68 6f 72 69 7a 61 74 69 |dpl..Authorizati|
|000000d0| 6f 6e 3a 20 42 65 61 72 65 72 20 65 79 4a 68 62 |on: Bearer eyJhb|
|000000e0| XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX |XXXXXXXXXXXXX|
|000000f0| XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX |XXXXXXXXXXXXXX|
|00000100| XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX |XXXXXXXXXXXXX|
|00000110| XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX |XXXXXXXXXXXXXX|
|00000120| XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX |XXXXXXXXXXXXX|
|00000130| 45 31 4a 54 69 4a 64 4c 43 4a 70 63 33 4d 69 4f |E1JTiJdLCJpc3MiO|
|00000140| 69 4a 68 64 58 52 6f 5a 57 35 30 61 57 4e 68 64 |iJhdXRoZW50aWNhd|
|00000150| 47 6c 76 62 69 49 73 49 6d 56 34 63 43 49 36 4d |GlvbiIsImV4cCI6M|
|00000160| 54 55 31 4e 6a 41 35 4d 6a 63 78 4d 79 77 69 61 |TU1NjA5MjcxMywia|
|00000170| 57 46 30 49 6a 6f 78 4e 54 55 32 4d 44 67 35 4d |WF0IjoxNTU2MDg5M|
|00000180| 54 45 7a 66 51 2e 0d 0a 55 73 65 72 2d 41 67 65 |TEzfQ...User-Age|
|00000190| 6e 74 3a 20 4d 6f 7a 69 6c 6c 61 2f 35 2e 30 20 |nt: Mozilla/5.0 |
|000001a0| 28 4d 61 63 69 6e 74 6f 73 68 3b 20 49 6e 74 65 |(Macintosh; Inte|
|000001b0| 6c 20 4d 61 63 20 4f 53 20 58 20 31 30 5f 31 33 |l Mac OS X 10_13|
|000001c0| 5f 36 29 20 41 70 70 6c 65 57 65 62 4b 69 74 2f |_6) AppleWebKit/|
|000001d0| 35 33 37 2e 33 36 20 28 4b 48 54 4d 4c 2c 20 6c |537.36 (KHTML, l|
|000001e0| 69 6b 65 20 47 65 63 6b 6f 29 20 43 68 72 6f 6d |ike Gecko) Chrom|
|000001f0| 65 2f 37 33 2e 30 2e 33 36 38 33 2e 38 36 20 53 |e/73.0.3683.86 S|
|00000200| 61 66 61 72 69 2f 35 33 37 2e 33 36 0d 0a 43 6f |afari/537.36..Co|
|00000210| 6e 74 65 6e 74 2d 54 79 70 65 3a 20 61 70 70 6c |ntent-Type: appl|
|00000220| 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0d 0a 41 63 |ication/json..Ac|
|00000230| 63 65 70 74 2d 45 6e 63 6f 64 69 6e 67 3a 20 67 |cept-Encoding: g|
|00000240| 7a 69 70 2c 20 64 65 66 6c 61 74 65 0d 0a 41 63 |zip, deflate..Ac|
|00000250| 63 65 70 74 2d 4c 61 6e 67 75 61 67 65 3a 20 65 |cept-Language: e|
|00000260| 6e 2d 55 53 2c 65 6e 3b 71 3d 30 2e 39 0d 0a 0d |n-US,en;q=0.9...|
|00000270| 0a 7b 22 71 75 65 72 79 22 3a 22 7b 20 75 73 65 |.{"query":"{ use|
|00000280| 72 4c 69 73 74 20 7b 20 69 64 20 7d 20 7d 22 7d |rList { id } }"}|
+--------+-------------------------------------------------+----------------+
07:04:14.412 [nioEventLoopGroup-1-2] DEBUG i.m.h.server.netty.NettyHttpServer - Server localhost:8080 Received Request: POST /graphql
07:04:14.414 [nioEventLoopGroup-1-2] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matching route POST - /graphql
07:04:14.416 [nioEventLoopGroup-1-2] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matched route POST - /graphql to controller class io.micronaut.configuration.graphql.GraphQLController
07:04:14.448 [nioEventLoopGroup-1-2] TRACE i.n.handler.logging.LoggingHandler - [id: 0xecaaaa36, L:/fd00:0:0:0:ec:c6e5:1:1:8080 - R:/fd00:0:0:0:ec:692a:1:1:58558] READ COMPLETE
07:04:14.450 [nioEventLoopGroup-1-2] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: IDLE) received demand: 2
07:04:14.450 [nioEventLoopGroup-1-2] TRACE i.m.h.n.reactive.HandlerPublisher - Demand received for next message (state = DEMANDING). Calling context.read()
07:04:14.451 [nioEventLoopGroup-1-2] TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: DEMANDING) emitting next message: {"query":"{ userList { id } }"}
07:04:14.453 [nioEventLoopGroup-1-2] TRACE i.m.h.n.reactive.HandlerPublisher - Demand received for next message (state = DEMANDING). Calling context.read()
07:04:14.471 [nioEventLoopGroup-1-2] DEBUG graphql.GraphQL - Executing request. operation name: 'null'. query: '{ userList { id } }'. variables '{}'
07:04:14.473 [nioEventLoopGroup-1-2] DEBUG graphql.GraphQL - Parsing query: '{ userList { id } }'...
07:04:14.479 [nioEventLoopGroup-1-2] DEBUG graphql.GraphQL - Validating query: '{ userList { id } }'
07:04:14.481 [nioEventLoopGroup-1-2] DEBUG graphql.GraphQL - Executing '9370b42d-2265-48bb-8e56-877c31b75761'. operation name: 'null'. query: '{ userList { id } }'. variables '{}'
07:04:14.482 [nioEventLoopGroup-1-2] DEBUG graphql.execution.Execution - Executing '9370b42d-2265-48bb-8e56-877c31b75761' query operation: 'QUERY' using 'graphql.execution.AsyncExecutionStrategy' execution strategy
07:04:14.483 [nioEventLoopGroup-1-2] DEBUG graphql.execution.ExecutionStrategy - '9370b42d-2265-48bb-8e56-877c31b75761' fetching field '/userList' using data fetcher 'org.grails.gorm.graphql.fetcher.interceptor.InterceptingDataFetcher'...
07:04:14.491 [nioEventLoopGroup-1-2] WARN  org.hibernate.orm.deprecation - HHH90000022: Hibernate's legacy org.hibernate.Criteria API is deprecated; use the JPA javax.persistence.criteria.CriteriaQuery instead
07:04:14.516 [nioEventLoopGroup-1-2] DEBUG graphql.execution.ExecutionStrategy - '9370b42d-2265-48bb-8e56-877c31b75761' field '/userList' fetch returned 'java.util.ArrayList'
07:04:14.517 [nioEventLoopGroup-1-2] DEBUG graphql.execution.ExecutionStrategy - '9370b42d-2265-48bb-8e56-877c31b75761' completing field '/userList'...
07:04:14.519 [nioEventLoopGroup-1-2] DEBUG graphql.execution.ExecutionStrategy - '9370b42d-2265-48bb-8e56-877c31b75761' fetching field '/userList[0]/id' using data fetcher 'org.grails.gorm.graphql.fetcher.impl.PersistentPropertyDataFetcher'...
07:04:14.519 [nioEventLoopGroup-1-2] DEBUG graphql.execution.ExecutionStrategy - '9370b42d-2265-48bb-8e56-877c31b75761' field '/userList[0]/id' fetch returned 'java.lang.Long'
07:04:14.520 [nioEventLoopGroup-1-2] DEBUG graphql.execution.ExecutionStrategy - '9370b42d-2265-48bb-8e56-877c31b75761' completing field '/userList[0]/id'...
07:04:14.521 [nioEventLoopGroup-1-2] DEBUG graphql.GraphQL - Execution '9370b42d-2265-48bb-8e56-877c31b75761' completed with zero errors
07:04:14.524 [nioEventLoopGroup-1-2] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Encoding emitted response object [{"data":{"userList":[{"id":1}]}}] using codec: io.micronaut.runtime.http.codec.TextPlainCodec@5a0a8297
07:04:14.527 [nioEventLoopGroup-1-2] TRACE i.n.handler.logging.LoggingHandler - [id: 0xecaaaa36, L:/fd00:0:0:0:ec:c6e5:1:1:8080 - R:/fd00:0:0:0:ec:692a:1:1:58558] WRITE: 300B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d |HTTP/1.1 200 OK.|
|00000010| 0a 41 63 63 65 73 73 2d 43 6f 6e 74 72 6f 6c 2d |.Access-Control-|
|00000020| 41 6c 6c 6f 77 2d 4f 72 69 67 69 6e 3a 20 63 68 |Allow-Origin: ch|
|00000030| 72 6f 6d 65 2d 65 78 74 65 6e 73 69 6f 6e 3a 2f |rome-extension:/|
|00000040| 2f 65 68 61 66 61 64 63 63 64 63 64 65 64 62 68 |/ehafadccdcdedbh|
|00000050| 63 62 64 64 69 68 65 68 69 6f 64 67 63 64 64 70 |cbddihehiodgcddp|
|00000060| 6c 0d 0a 56 61 72 79 3a 20 4f 72 69 67 69 6e 0d |l..Vary: Origin.|
|00000070| 0a 41 63 63 65 73 73 2d 43 6f 6e 74 72 6f 6c 2d |.Access-Control-|
|00000080| 41 6c 6c 6f 77 2d 43 72 65 64 65 6e 74 69 61 6c |Allow-Credential|
|00000090| 73 3a 20 74 72 75 65 0d 0a 44 61 74 65 3a 20 57 |s: true..Date: W|
|000000a0| 65 64 2c 20 32 34 20 41 70 72 20 32 30 31 39 20 |ed, 24 Apr 2019 |
|000000b0| 30 37 3a 30 34 3a 31 34 20 47 4d 54 0d 0a 63 6f |07:04:14 GMT..co|
|000000c0| 6e 74 65 6e 74 2d 74 79 70 65 3a 20 61 70 70 6c |ntent-type: appl|
|000000d0| 69 63 61 74 69 6f 6e 2f 6a 73 6f 6e 0d 0a 63 6f |ication/json..co|
|000000e0| 6e 74 65 6e 74 2d 6c 65 6e 67 74 68 3a 20 33 32 |ntent-length: 32|
|000000f0| 0d 0a 63 6f 6e 6e 65 63 74 69 6f 6e 3a 20 6b 65 |..connection: ke|
|00000100| 65 70 2d 61 6c 69 76 65 0d 0a 0d 0a 7b 22 64 61 |ep-alive....{"da|
|00000110| 74 61 22 3a 7b 22 75 73 65 72 4c 69 73 74 22 3a |ta":{"userList":|
|00000120| 5b 7b 22 69 64 22 3a 31 7d 5d 7d 7d             |[{"id":1}]}}    |
+--------+-------------------------------------------------+----------------+
07:04:14.530 [nioEventLoopGroup-1-2] TRACE i.n.handler.logging.LoggingHandler - [id: 0xecaaaa36, L:/fd00:0:0:0:ec:c6e5:1:1:8080 - R:/fd00:0:0:0:ec:692a:1:1:58558] FLUSH
07:04:14.531 [nioEventLoopGroup-1-2] TRACE i.n.handler.logging.LoggingHandler - [id: 0xecaaaa36, L:/fd00:0:0:0:ec:c6e5:1:1:8080 - R:/fd00:0:0:0:ec:692a:1:1:58558] FLUSH
07:04:14.531 [nioEventLoopGroup-1-2] TRACE i.n.handler.logging.LoggingHandler - [id: 0xecaaaa36, L:/fd00:0:0:0:ec:c6e5:1:1:8080 - R:/fd00:0:0:0:ec:692a:1:1:58558] FLUSH

github repo will be added shortly.

**Comment by jameskleeh** [comment]
Can you verify this is a problem with any other graphql api? Perhaps try Github.

**Comment by benlucchesi** [comment]
@jameskleeh - thank you for the very sound and pragmatic validation suggestions. I should have tried this at 2:00 AM instead of continuing to hammer my head against the wall. I've implemented a know working query against the github graphql endpoint and it failed with an empty response. I'll continue debugging on the react-native side of the setup.
