### ISSUE TITLE
User defined scheduler not found by @Scheduled annotation

### ISSUE THREAD

**Issue by croudet** [micronaut-projects/micronaut-core#1584]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. In `application.yml` declared a task executor with name `dispatcher`:
```yaml
micronaut:
    application:
        name: hello-world
    executors:
        dispatcher:
            type: scheduled
            core-pool-size: 1
```
2. Schedule a task as follow:
```java
package hello.world;

import javax.inject.Singleton;

import io.micronaut.scheduling.annotation.Scheduled;

@Singleton
public class HelloService {

    @Scheduled(cron = "0 15 10 ? * MON", scheduler = "dispatcher")
    void everyMondayAtTenFifteenAm() {
        System.out.println("Executing everyMondayAtTenFifteenAm()");
    }
}
```

### Expected Behaviour

The task should be scheduled on scheduler named `dispatcher`.

### Actual Behaviour

The named scheduler is not found. The following exception is thrown:
```
$ ./gradlew run

> Task :run
11:33:45.840 [ForkJoinPool.commonPool-worker-1] ERROR i.m.context.DefaultBeanContext - Error processing bean method Definition: hello.world.HelloService.void everyMondayAtTenFifteenAm() with processor (io.micronaut.scheduling.processor.ScheduledMethodProcessor@1fdf1c5): Invalid @Scheduled definition for method: void everyMondayAtTenFifteenAm() - Reason: No scheduler of type TaskScheduler configured for name: dispatcher
io.micronaut.scheduling.exceptions.SchedulerConfigurationException: Invalid @Scheduled definition for method: void everyMondayAtTenFifteenAm() - Reason: No scheduler of type TaskScheduler configured for name: dispatcher
        at io.micronaut.scheduling.processor.ScheduledMethodProcessor.lambda$process$1(ScheduledMethodProcessor.java:97)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at io.micronaut.scheduling.processor.ScheduledMethodProcessor.process(ScheduledMethodProcessor.java:97)
        at io.micronaut.context.DefaultBeanContext.lambda$null$25(DefaultBeanContext.java:1221)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

### Environment Information

- **Operating System**:  Windows 10
- **Micronaut Version**: 1.1.0
- **JDK Version:** jdk8

### Example Application

- https://github.com/croudet/micronaut-hello-world

**Comment by jameskleeh** [comment]
Currently a `TaskScheduler` bean is not created automatically for `ExecutorService` beans of type scheduled. You can add the bean yourself in the meantime. See  https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/scheduling/ScheduledExecutorTaskScheduler.java

**Comment by jameskleeh** [comment]
This issue is reliant upon https://github.com/micronaut-projects/micronaut-core/pull/1593

**Comment by croudet** [comment]
https://docs.micronaut.io/latest/guide/index.html#io.micronaut.scheduling.executor.UserExecutorConfiguration
Does the `UserExecutorConfiguration` only work for predefined executors (`SCHEDULE`, `IO`, `MESSAGE_CONSUMER `)?

**Comment by jameskleeh** [comment]
@croudet No it works for any executor configuration
