### ISSUE TITLE
Server side template view not working with Kotlin controller

### ISSUE THREAD

**Issue by luistrigueiros** [micronaut-projects/micronaut-core#1597]
Server side template views are not working with Kotlin controller I have create a very simple project to test it in Kotlin and it returns not found page for the Kotlin case but the equivalent code done in Groovy works.
The example project can be found at, [Example Kotlin Controller](https://raw.githubusercontent.com/luistrigueiros/mnsse/master/src/main/kotlin/proj2/ViewsController.kt)

**Comment by jameskleeh** [comment]
The example project works for me after fixing the logback xml which seems to be an issue with creating the app with the 1.2 snapshot

**Comment by puneetbehl** [comment]
It works for me as well. I tried with `v1.1.0`. Please check the following sample project:
[hello-kotlin-views.zip](https://github.com/micronaut-projects/micronaut-core/files/3125846/hello-kotlin-views.zip)
