### ISSUE TITLE
GraalVM and kotlin data classes @Introspected

### ISSUE THREAD

**Issue by knyttl** [micronaut-projects/micronaut-core#1600]
### Steps to Reproduce

1. Implement a kotlin controller with data class in @Body with @Introspected as follows:

```
@Controller
class DataBodyController {

    @Post("/")
    fun render(@Body body: DataBody)
            = HttpResponse.ok(body.templatel))
}

@Introspected
data class DataBody(
        val template: String = "",
        val model: MutableMap<String, Any> = mutableMapOf()
)
```

2. Try to call the controller with curl:
```
curl -v -H "Content-Type: application/json" --data '{"template":"foo","model":{"bar":"foo"}}' http://localhost:8080/
```

3. This works with `gradle run`, but doesn't work with graal `native-image` compiled file:

```
09:15:10.791 [nioEventLoopGroup-2-2] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Encoding emitted response object [ /body - Failed to convert argument [body] for value [null] due to: Cannot construct instance of `example.DataBody` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: UNKNOWN; line: -1, column: -1]] using codec: io.micronaut.jackson.codec.JsonMediaTypeCodec@1199c8d20
```

### Expected Behaviour

It should work the same with JAR and native-image.

### Actual Behaviour

native-image cannot introspect the kotlin data class.

Tell us what happens instead

### Environment Information

- **Operating System**: Docker -  frolvlad/alpine-glibc
- **Micronaut Version:** 1.1.0
- **JDK Version:** JDK8

### Example Application

Sources: https://gitlab.com/GoOutPublic/MicronautKotlinDemo/tree/master
CI run with the error: https://gitlab.com/GoOutPublic/MicronautKotlinDemo/-/jobs/203794687

**Comment by knyttl** [comment]
I tried also with regular class with the same result.

**Comment by graemerocher** [comment]
You need to enable the bean introspection module:

```
jackson:
       bean-introspection-module: true
```

**Comment by knyttl** [comment]
Thanks, that worked.
