### ISSUE TITLE
Request data normalization

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-core#1609]
What is the approach for request data normalization?
For example a request that contains `email` field
```
{ "email": "  SoMe@CORP.com  " }
```
we need to replace spaces(begin/end) and need to lowercase all characters.
All this operations should be done before validation.

**Comment by raderio** [comment]
@jameskleeh can you please describe why it was closed?

**Comment by jameskleeh** [comment]
@raderio Because its not an issue/improvement with the framework, which is the purpose of this tracker. You can ask questions in [gitter](https://gitter.im/micronautfw/)
