### ISSUE TITLE
Jansi errors with Windows

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#1612]
I am working with some colleagues which use Windows and they are hitting this error: 

https://jira.qos.ch/browse/LOGBACK-762

Removing `<withJansi>true</withJansi>` from `src/main/resources/logback.xml` gets rid of the exception. 

Maybe we should default to not use Jansi. Thoughts?

**Comment by graemerocher** [comment]
The correct solution is to default to not use jansi on Windows

**Comment by zulq** [comment]
This is already handled by the the commit on issue #1521.
