### ISSUE TITLE
Flowable<ByteBuffer> body: 1.1.0 regression

### ISSUE THREAD

**Issue by ddsimoes** [micronaut-projects/micronaut-core#1613]
The following code snippet works in 1.0.4 but throws an exception in 1.1.0.

```kotlin
class HelloController {

    @Put("/upload", consumes = [MediaType.ALL])
    fun putObject(@Body body: Flowable<ByteBuffer<*>>, request: HttpRequest<*>) {
        body.subscribeOn(Schedulers.io()).subscribe {
            println(it.readableBytes())
            println(it.getByte(0)) // <-- fail here; buffer already disposed.
        }
    }

}
```

### Steps to Reproduce

- run a server with the sample controller
- upload some content to the endpoint: `curl http://localhost:8080/upload --upload-file /path/to/some/data`

### Expected Behaviour

Handle body content reactively using ByteBuffer.

### Actual Behaviour

Throws the following exception:

```
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1446)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1376)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1372)
	at io.netty.buffer.AbstractByteBuf.getByte(AbstractByteBuf.java:352)
	at io.netty.buffer.PooledSlicedByteBuf.getByte(PooledSlicedByteBuf.java:127)
	at io.micronaut.buffer.netty.NettyByteBuffer.getByte(NettyByteBuffer.java:243)
	at example.HelloController$putObject$1.accept(HelloController.kt:95)
	at example.HelloController$putObject$1.accept(HelloController.kt:55)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	... 69 more
```

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Micronaut Version:** 1.1.0
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
Actually I am not sure this is a bug, you are subscribing to the body manually within the method body. You should instead by returning the flowable from the method and using `map` to process each junk.

**Comment by ddsimoes** [comment]
I tried various methods to do the "direct access" to the body and could not found a sample.

Can you point me to a sample/doc that show how to do the correct way?

**Comment by ddsimoes** [comment]
The following snippet also works on 1.0.4 and fail in 1.1.0:

```kotlin
    @Put("/upload", consumes = [MediaType.ALL], produces = [MediaType.TEXT_PLAIN])
    fun putObject(@Body body: Flowable<ByteBuffer<*>>, request: HttpRequest<*>): Single<String> {
        return body.doOnNext {
            println(it.readableBytes())
            println(it.getByte(0))
        }.ignoreElements().toSingle { "" }
    }
```

**Comment by jameskleeh** [comment]
This is a regression introduced into 1.0.5 by https://github.com/micronaut-projects/micronaut-core/commit/291c8ed49ba28dcc9589ad8c8c6de3f1ff00ac6f#diff-e7054e843c8adaa190305c4377f8c783

**Comment by jameskleeh** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/b66be8884160d3eadd68f08d342b4bac753d0acf
