### ISSUE TITLE
injecting prototype beans into a singleton using javax.inject.Provider

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#1615]
I'm having the *scoped bean injection problem* where I want to inject a `@Prototype` bean in a `@Singleton` bean.

If I have something like:

```
@Prototype
class PrototypeBean {
    fun do() {
         ..
    }
}

@Singleton
class SingletonBean(private val prototypeBean: PrototypeBean) {
    fun do() {
        prototypeBean.do()
    }
}
```

Then the `prototypeBean` instance is always the same and if only used in `SingletonBean` then the `prototypeBean` would effectively be a singleton.

It also makes sense as we wire it via the constructor, but there are situations that you would want a new `PrototypeBean` instance instead.

https://www.baeldung.com/spring-inject-prototype-bean-into-singleton describes this problem for Spring and the solution is to use Spring's `@Lookup` annotation or use the `javax.inject.Provider` instead.

I tried that with Micronaut like:

```
@Singleton
class SingletonBean(private val prototypeBean: Provider<PrototypeBean>) {
    fun do() {
        prototypeBean.get().do()
    }
}
```
 and it works. A new instance of the `PrototypeBean` bean is created when calling `get()` on the injected provider.

Note when debugging the code, the `get()` goes through Micronaut's `UnresolvedProvider` which ultimately ends up calling `return getScopedBeanForDefinition(resolutionContext, beanType, qualifier, throwNoSuchBean, definition);` in the `DefaultBeanContext`.

Now the question is this intentional or not?

Section 3.4 of the Micronaut user guide states:

> A javax.inject.Provider if a circular dependency requires it

If using the `Provider` is working intentional for injecting prototype beans in singletons the documentation could be changed to something like:

> A javax.inject.Provider if a circular dependency requires it or to inject a prototype in a singleton

**Comment by graemerocher** [comment]
This behaviour is intentional yes

**Comment by marceloverdijk** [comment]
@graemerocher thx for confirming!

**Comment by jameskleeh** [comment]
Closed by https://github.com/micronaut-projects/micronaut-core/pull/1617
