### ISSUE TITLE
Thymeleaf link expression seems incorrect for context-relative URLs

### ISSUE THREAD

**Issue by bufferings** [micronaut-projects/micronaut-core#1619]
Micronaut seems to add current path to the context-relative urls of Thymeleaf, but it's incorrect.

Related to: https://github.com/micronaut-projects/micronaut-core/pull/1423

### Task List

- [x] Steps to reproduce provided
- [(no need)] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create Micronaut Thymeleaf project
2. Write context relative link expression `<a th:href="@{/order/list}">Context Relative</a>` in a template file
3. Use the template with `/sample` url
4. Run the app and access to the `/sample` url

### Expected Behaviour

`<a href="/order/list">Context Relative</a>`

### Actual Behaviour

`<a href="/sample/order/list">Context Relative</a>`

Micronaut seems to use current path as context-path.

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Micronaut Version:** 1.1.0
- **JDK Version:** 8.0.202.hs-adpt
- **Thymeleaf Version**: 3.0.11.RELEASE

### Example Application

I created an example application: https://github.com/bufferings/micronaut-thymeleaf-linkcheck

1. clone the repo
2. cd to the project root `cd micronaut-thymeleaf-linkcheck`
3. `./gradlew :mnthyme:run`
4. `curl localhost:8080/sample`

```html
❯ curl localhost:8080/sample
<!doctype html>
<html>
<body>
<a href="order/list">Relative</a>
<a href="/sample/order/list">Context Relative</a>
<a href="/order/list">Server Relative</a>
</body>
</html>
```

The context relative url have to be `/order/list` but it's `/sample/order/list`.

The template is as follows:

```html
<!doctype html>
<html xmlns:th="http://www.thymeleaf.org">
<body>
<a th:href="@{order/list}">Relative</a>
<a th:href="@{/order/list}">Context Relative</a>
<a th:href="@{~/order/list}">Server Relative</a>
</body>
</html>
```

As an expected behavior, I created Spring Boot app with the same template:

1. Stop Micronaut application if it is running.
2. `./gradlew :sbthyme:bootRun`
3. `curl localhost:8080/sample`

```html
❯ curl localhost:8080/sample
<!doctype html>
<html>
<body>
<a href="order/list">Relative</a>
<a href="/order/list">Context Relative</a>
<a href="/order/list">Server Relative</a>
</body>
</html>
```

It works correctly.

### Detail

Thymeleaf link expression supports context-relative URLs:
https://www.thymeleaf.org/doc/articles/standardurlsyntax.html#context-relative-urls

It means if we run application under `server:port/context-path` of servlet, Thymeleaf adds the `context-path` in front of the link. For example, if we run app under  `localhost:8080/myapp` then the `/sample` path of the application is `localhost:8080/myapp/sample`. In that case, the context relative url becomes `<a href="/myapp/order/list">Context Relative</a>`.

Since netty doesn't have context-path, it should add nothing for the context-relative urls. But actually, Micronaut adds current path in front of the urls. 

As a workaround for now, we can use Server Relative URLs. But it's better to support Context Relative URLs correctly.

**Comment by jameskleeh** [comment]
@bufferings Thank you for the detailed issue report. I'm not super familiar with thymeleaf, however here is the commit that introduced the feature https://github.com/micronaut-projects/micronaut-core/commit/7b2a80bbfa85f2adac42486565c5d0399ca9f1a7. Can you point out what is incorrect?

**Comment by jameskleeh** [comment]
@gasches What are you thoughts on the above?

**Comment by bufferings** [comment]
@jameskleeh Thank you for your reply.

I think it's ok to return null in `computeContextPath`:

https://github.com/micronaut-projects/micronaut-core/commit/7b2a80bbfa85f2adac42486565c5d0399ca9f1a7#diff-a946190c84ccce1758d26fa8b96b352aR37

Then it's treated as empty context path here:

https://github.com/thymeleaf/thymeleaf/blob/bb2fd0e9005f8aab0de0a3f9f3897edea8084b88/src/main/java/org/thymeleaf/linkbuilder/StandardLinkBuilder.java#L125-L126

**Comment by gasches** [comment]
Agree with @bufferings. The current implementation does not match the documentation.

From thymeleaf doc:

Context-relative URLs
These are URLs which are supposed to be relative to the web application root once it is installed on the server. For example, if we deploy a `myapp.war` file into a Tomcat server, our application will probably be accessible as `http://localhost:8080/myapp`, and myapp will be the context name.

Context-relative URLs start with `/`:

```<a th:href="@{/order/list}">```

If our app is installed at `http://localhost:8080/myapp`, this URL will output:

```<a href="/myapp/order/list">```

@jameskleeh does Micronaut have the ability to set the context path? According to https://docs.micronaut.io/snapshot/guide/configurationreference.html seems that no.

If we assume that context path is empty then after fix following classes will become useless:

`io.micronaut.views.thymeleaf.WebContext`
`io.micronaut.views.thymeleaf.WebEngineContext`

and method

`io.micronaut.views.ViewsRenderer#render(String, Object, HttpRequest<?>): Writable`

@jameskleeh How to deal with them?

**Comment by graemerocher** [comment]
Well IMO they can just be left there, they do add additional flexibility I can imagine a case where you may want to customize view selection based on language, tenant etc. so it isn't all gone to waste. 

The thymleaf specific classes I am not sure.

**Comment by gasches** [comment]
#1631

**Comment by jameskleeh** [comment]
Thanks for the PR @gasches
