### ISSUE TITLE
Support Log4j2 feature in the CLI

### ISSUE THREAD

**Issue by knyttl** [micronaut-projects/micronaut-core#1621]
This is not a bug report, rather feature request or initiation of a discussion.

### References

- https://stackify.com/compare-java-logging-frameworks/
> I recommend using Log4j2 because it’s the fastest and most advanced of the three frameworks. Logback is still a good option, if performance is not your highest priority.
- https://www.loggly.com/blog/benchmarking-java-logging-frameworks/
> The combination that provided the best performance and reliability is Log4j 2’s FileAppender using an asynchronous logger (...) In second place was Log4j 2’s FileAppender using an AsyncAppender, and finally Logback’s FileAppender. However, we cannot recommend Logback’s FileAppender using an AsyncAppender due to the large number of dropped events.

### Motivation

- We would prefer to use a single logging framework instead of two - as log4j2 is newer and more current, we would prefer to use it.
- Logback doesn't have `log.fatal` which we use heavily within our project.
- Instead of `LogFactory.getLogger(currentClass)`, you can just write `LogFactory.getLogger()`, as the current class is inferred by reflection.

### Questions

- Was there some specific reason to use logback for Micronaut?
- Would switching to log4j2 be an issue?

**Comment by graemerocher** [comment]
Grails and Boot use logback so hence we chose it for familiarity purposes and unfamiliarity with log4j2. Other than that Micronaut is not really bound to logback, as we use slf4j for all logging. So swapping the implementation is actually quite easy an in fact we do it for deployment to AWS lambda for example. This could be as simple as a new CLI feature.

**Comment by knyttl** [comment]
One more advantage is that when use write `LogFactory.getLogger(currentClass)`, you don't need to write the `currentClass` as it is inferred by reflection.

I would be happy for such feature.

**Comment by graemerocher** [comment]
We would have to review the impact of such as feature and how well log4j2 works with GraalVM native

**Comment by knyttl** [comment]
It is true I had some reflection issues with GraalVM.

**Comment by benrhine** [comment]
I have added log4j2 support with this pr https://github.com/micronaut-projects/micronaut-profiles/pull/217.

**Comment by renannprado** [comment]
@benrhine the PR was already merged. Should this issue be still open?

**Comment by sergey-morenets** [comment]
@benrhine It seems that Micronaut already supports Log4j 2 as logging facade for Sl4fj (at least). 
However I still see this text in the documentation (since 1.1): https://docs.micronaut.io/latest/guide/index.html#introduction

`The current default implementation for the logging system is LogbackLoggingSystem, which works with the logback logging framework. Additional logging systems will be implemented in future revisions of Micronaut.`
I guess this text should be improved and include note about implemented support of other Slf4j logging facades.
Because now it just confuses the developers.
