### ISSUE TITLE
Move off JSR-305 annotations 

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#1633]
See https://github.com/spotbugs/spotbugs/issues/421

The `JSR-305` from findbugs is not longer supported, has split package problems for Java 9+ and may represent an Oracle license violation.

We currently use `javax` annotations for `Nullable` and `Nonnull` we need to eliminate the use of these annotations directly but still support them via annotation mapping.

The following screenshot shows the currently supported annotations by IntelliJ out of the box:

<img width="943" alt="Screenshot 2019-05-07 at 08 30 25" src="https://user-images.githubusercontent.com/66626/57276601-64d1e180-70a2-11e9-82fc-ef348016cab3.png">

Google tools are moving to the Checker Framework so maybe we should use that since it is supported out of the box by IntelliJ

The other option is our own set of annotations, however that would require end users to configure IntelliJ (and any other tooling) explicitly.

**Comment by graemerocher** [comment]
See also https://github.com/micronaut-projects/micronaut-examples/pull/45

**Comment by graemerocher** [comment]
Checker framework seems massive and also repackages `javax.annotation` classes. I think probably https://github.com/spotbugs/spotbugs/tree/master/spotbugs-annotations/src/main/java/edu/umd/cs/findbugs/annotations are the best ones to migrate to

**Comment by sdelamo** [comment]
Kotlin supported nullability annotations: https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations
