### ISSUE TITLE
Unable to POST Kotlin data class using polymorphic lists

### ISSUE THREAD

**Issue by reik-wargaming** [micronaut-projects/micronaut-core#1643]
### Steps to Reproduce

1. Create Controller and Unit Test as below

### Expected Behaviour

Both endpoints should respond with 200

### Actual Behaviour

Test fails due to JSON related error when using polymorphic lists. In the TRACE log of the HandlerPublisher you can see the json string it receives and it is actually valid when you deserialise to an object using vanilla ObjectMapper with the KotlinModule.

>>> Failed to convert argument [items] for value [null] due to: Instantiation of [simple type, class First] value failed for JSON property name due to missing (therefore NULL) value for creator parameter name which is a non-nullable type
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: Broken["items"]->java.util.ArrayList[0]->First["name"])
io.micronaut.http.client.exceptions.HttpClientResponseException: Failed to convert argument [items] for value [null] due to: Instantiation of [simple type, class First] value failed for JSON property name due to missing (therefore NULL) value for creator parameter name which is a non-nullable type
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: Broken["items"]->java.util.ArrayList[0]->First["name"])
	

### Environment Information

- **Operating System**: MacOS 10.14.4
- **Micronaut Version:** 1.1.0
- **JDK Version:** 1.8.x

### Example Application

```
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo
import io.micronaut.http.MediaType
import io.micronaut.http.annotation.Body
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Post
import io.micronaut.http.annotation.Produces

@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "name")
@JsonSubTypes(
    JsonSubTypes.Type(value = First::class, name = "first"),
    JsonSubTypes.Type(value = Second::class, name = "second")
)
sealed class Base {
    abstract val name: String
}

data class First(override val name: String, val foo: String): Base()
data class Second(override val name: String, val bar: String): Base()
data class Broken(val items: List<Base>)

data class Working(val foo: String, val bar: Int)

@Controller("/api")
class ExampleController {

    @Post("/broken")
    @Produces(MediaType.TEXT_PLAIN)
    fun broken(@Body items: Broken): String {
        return "works"
    }

    @Post("/working")
    @Produces(MediaType.TEXT_PLAIN)
    fun working(@Body item: Working): String {
        return "works"
    }
}
```

```
import io.micronaut.http.HttpRequest
import io.micronaut.http.HttpStatus
import io.micronaut.http.client.RxHttpClient
import io.micronaut.http.client.annotation.Client
import io.micronaut.test.annotation.MicronautTest
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test
import javax.inject.Inject

@MicronautTest
class ExampleControllerTest {

    @Inject
    @field:Client("/")
    private lateinit var client: RxHttpClient

    @Test
    fun `should post polymorphic lists`() {
        val workingRequest = HttpRequest.POST("api/working", Working("a", 1))
        val workingResponse = client.exchange(workingRequest).blockingFirst()
        assertEquals(HttpStatus.OK, workingResponse.status)

        val brokenRequest = HttpRequest.POST(
            "api/broken",
            Broken(items = listOf(First("first", "a"), Second("second", "b")))
        )

        // TRACE i.m.h.n.reactive.HandlerPublisher - HandlerPublisher (state: DEMANDING) emitting next message: {"items":[{"name":"first","name":"first","foo":"a"},{"name":"second","name":"second","bar":"b"}]}
        val brokenResponse = client.exchange(brokenRequest).blockingFirst()
        assertEquals(HttpStatus.OK, brokenResponse.status)
    }
}
```

**Comment by willbuck** [comment]
Thanks for reaching out @reik-wargaming ! This appears to be an issue with jackson (or perhaps your usage, not totally clear to me) and not specifically with Micronaut. 

You can confirm this by simply taking the `Broken(items = listOf(First("first", "a"), Second("second", "b")))` and trying to convert it to a Tree of `ObjectNode`s and back.

Consider the following test:

    class ExampleControllerTest : StringSpec() {
        "should post polymorphic lists"() {
            try {
                val mapper = ObjectMapper().findAndRegisterModules()
                val broken = Broken(items = listOf(First("first", "a"), Second("second", "b")))
                val mapperInput = mapper.valueToTree<ObjectNode>(broken)
                val readInBroken = mapper.treeToValue(mapperInput, Broken::class.java)
                readInBroken.items.first().name.shouldBe(broken.items.first().name)
            } catch (e: Exception) {
                fail("threw exception")
            }
        }

This test fails with no Micronaut code involved whatsoever. You may need to file a bug with Jackson, or perhaps the `com.fasterxml.jackson.module:jackson-module-kotlin`, or perhaps simply review how your annotations are set up on the `sealed class Base`
