### ISSUE TITLE
StackOverflow during annotations processing in 1.1.1

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#1645]
So, I really don't know how did I get to this point :) I cannot extract separate testcase and it happens only in my codebase.

This is about generics, having such circular dependency (proper in java):

```
class A<T extends B> {}
class B<T extends A> {}
```

When `BeanIntrospectionWriter` is fed with one of these classes it enters infinite recursion here:

![image](https://user-images.githubusercontent.com/1880196/57537126-e9905a00-7345-11e9-87b5-f0718b060be3.png)

Here are first arguments to `writeConstructor()` method:

![image](https://user-images.githubusercontent.com/1880196/57537351-602d5780-7346-11e9-8cbf-76dc84eae75d.png)

**Comment by graemerocher** [comment]
Thanks for the report, will take a look
