### ISSUE TITLE
Provide Convention over Configuration feature?

### ISSUE THREAD

**Issue by wureka** [micronaut-projects/micronaut-core#1648]
Is it possible to provide the feature of "Convention over Configuration" just like Grails ?
For example, drop a class into  controller folder and the class default become a controller.
I think it could simplify the development.

**Comment by jameskleeh** [comment]
We have no plans to implement something like what you're describing. Anyone could do exactly that and someone has started the effort https://github.com/virtualdogbert/micro-grails-plugin. If you're interested in seeing this feature I suggest following that library and/or creating something yourself
