### ISSUE TITLE
Release Notes clarification re: GAE-SE

### ISSUE THREAD

**Issue by lex-divert** [micronaut-projects/micronaut-core#1655]
From the v1.1 Release Announcement:
> Micronaut can be deployed to both Google Cloud Run and **Google App Engine Standard for Java 11**, and with Micronaut 1.1, we have dedicated support for Google Stackdriver Trace.

App Engine Standard Environment seems like it would be a great way to host MN. But as far as I can determine from its documentation [1], hosting on that platform requires compatibility with the Java Servlet API, which is still just a future possibility (see Issue #1013 , and confirmed by James in the Gitter/questions room).

The phrase in the announcement does specify "for Java 11", but it's a link to docs for the publicly-available Java8 environment. I hope that I'm just missing something obvious, but since I can't find any other mentions, I'm filing this Issue as an enhancement request against the release notes to clarify the description. (It seemed more appropriate than asking as a question on StackOverflow, but I can do that instead if desired.)

[1] For example: https://cloud.google.com/appengine/docs/standard/java/how-requests-are-handled

**Comment by graemerocher** [comment]
Google App Engine Standard for Java 11 (not Java 8) supports runnable JAR files, hence it does not require a servlet environment.

**Comment by lex-divert** [comment]
**That's** the detail I was missing, thank you.

I'm having trouble finding anything public from Google about the Java 11 platform. If you have a useful pointer, that seems like a good candidate for the the link target.

**Comment by graemerocher** [comment]
You can signup to be an Alpha tester here https://docs.google.com/forms/d/e/1FAIpQLSf5uE5eknJjFEmcVBI6sMitBU0QQ1LX_J7VrA_OTQabo6EEEw/viewform
