### ISSUE TITLE
how to auto configurate beans similar with Spring Boot(META-INF/spring.factories)

### ISSUE THREAD

**Issue by ronnin** [micronaut-projects/micronaut-core#1657]
I'm adding micronaut support to a xx-spring-boot-starter for my dev team.
what I have done:
```java
// a Component
@Singleton
@Requires(classes = HttpServerFilter.class)
@Requires(property = AuthProperties.PREFIX + ".login-page")
public class AuthHttpFilter implements HttpServerFilter, Ordered {
}

// a ConfigurationProperties
@Singleton
@ConfigurationProperties(AuthProperties.PREFIX)
public class AuthProperties {
    public static final String PREFIX = "ross.auth";

   private String loginPage;
}

// a package-info.java
@Configuration
package xxx.gatekeeper;

import io.micronaut.context.annotation.Configuration;
```
I didn't see the component instantialized in a demo project depends on the xx-spring-boot-starter

As to Spring boot, I setup an **META-INF/spring.factories**:
```ini
  org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
     package.to.MySpringBootAutoConfiguration
```
What's similar way in Micronaut ?

**Comment by graemerocher** [comment]
There is no need for `META-INF/spring.factories` in Micronaut. They are picked up automatically just by being present on the classpath.

**Comment by ronnin** [comment]
So what did I missed?
the demo project with
```groovy
// the build.gradle
dependencies {
  compile 'myGroupId:xx-spring-boot-starter:myVersion'
}
```
```kotlin
// the Bootstrap
object Application {

    @JvmStatic
    fun main(args: Array<String>) {
        Micronaut.build()
                .packages("micronaut.demo", "xxx.gatekeeper")
                .mainClass(Application.javaClass)
                .start()
    }
}
```
didn't see the component AuthHttpFilter instantialized.

**Comment by ronnin** [comment]
I see some files like io.micronaut.* under META-INF/services/ in most mocironaut-* libraries.
I studied quite a lot by reading sources of micronaut-core & micronaut-runtime, but still not get the point.

Will the instructions about META-INF/services/io.micronaut.* be covered by the User Guides of micronaut?

**Comment by graemerocher** [comment]
These are generated by the compiler there is no need for you to create them personally

**Comment by graemerocher** [comment]
If they are not being generated then you have misconfigured the build and it is missing the annotation processors

**Comment by ronnin** [comment]
Thanks for you help. my problem has been solved.
