### ISSUE TITLE
Allow replacement of http response compression logic

### ISSUE THREAD

**Issue by RaviH** [micronaut-projects/micronaut-core#1658]
The `SmartHttpContentCompressor` is simply size based. But, doesn't allow to customize compression. For example: I always want to ignore compression on certain endpoints in my API regardless of the size of the data. This is hard problem to solve without being able to replace `SmartHttpContentCompressor` with custom implementation. To get around lack of `Replace`-ability for `SmartHttpContentCompressor`, I had to write hacks like shown below:
https://github.com/RaviH/micronaut-custom-server which are causing performance issues for some reason. Also, if compression is purely size based, then if size of data increases for some reason, then the tests fail because the Dev Test team have to account for an endpoint that was not compressing data is now compressing data and vice versa. 

Thus, size based compression, while it's a good default, isn't flexible or consistent since same  api may sometimes compress data, whereas sometimes it won't since it relies on size of data.

This issue is a request to:

Either allow customization for compression such that certain endpoints can be ignored from compression regardless of the size of the response.

_Or_ allow ignoring compression if a header like `Ignore-Encoding` is passed for the api.

_Or_ please help me figure out why the small library above could be causing performance issues. 

Overall, this issue could be simply resolved by injecting `SmartHttpContentCompressor` into `NettyHttpServer` vs creating it via `new` operator. Since `NettyHttpServer` is a singleton bean an implementation of `SmartHttpContentCompressor` can easily be injected instead of manually creating it in the class.

I am happy to make the PR if need be. 

Please let me know your thoughts.

Thanks for the awesome framework.

**Comment by croudet** [comment]
It is not only size based, it also checks if content type is text based:
```java
    /**
     * Determines if encoding should occur based on the content type and length.
     *
     * @param contentType   The content type
     * @param contentLength The content length
     * @return True if the content is compressible and larger than 1KB
     */
    public boolean shouldSkip(@Nullable String contentType, @Nullable Integer contentLength) {
        if (contentType == null) {
            return true;
        }
        return !MediaType.isTextBased(contentType) || (contentLength != null && contentLength >= 0 && contentLength < compressionThreshold);
    }
```

**Comment by jameskleeh** [comment]
Now possible by replacing `HttpCompressionStrategy`

**Comment by RaviH** [comment]
You rock @jameskleeh. Thank you so much. I would venture to guess this will be part of 1.2.x?

**Comment by jameskleeh** [comment]
Correct
