### ISSUE TITLE
Read configuration file scrambling

### ISSUE THREAD

**Issue by gitjxm** [micronaut-projects/micronaut-core#1660]
file:’application.properties‘ The configuration is as follows
   project.name=中文
read value 
    @Value("${project.name}")
    protected String projectName;
The resulting values are scrambled，How to solve

**Comment by graemerocher** [comment]
make sure you run Micronaut with the correct file encoding

**Comment by graemerocher** [comment]
If that doesn't work please provide an example that reproduces the issue with steps to reproduce

**Comment by jameskleeh** [comment]
Closing due to a lack of feedback. Will reopen if a sample app is produced
