### ISSUE TITLE
Build failed with an exception (http-client)

### ISSUE THREAD

**Issue by rmorrise** [micronaut-projects/micronaut-core#169]
Error building micronaut from source in Java 9 - http-client compile failed.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. git clone https://github.com/micronaut-projects/micronaut-core.git
2. cd micronaut-core
3. gradlew publishToMavenLocal

### Expected Behaviour

Should publish micronaut to maven local as per the README.

### Actual Behaviour

Build failed:

```
> Task :http-client:compileJava
Note: Creating bean classes for 12 type elements
D:\src\github-csc\micronaut-projects\micronaut-core\http-client\src\main\java\io\micronaut\http\client\HttpClient.java:131: error: unreported exception X; must
be caught or declared to be thrown
                    .orElseThrow(() -> new HttpClientResponseException(
                                ^
  where X,T are type-variables:
    X extends Throwable declared in method <X>orElseThrow(Supplier<? extends X>)
    T extends Object declared in class Optional
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':http-client:compileJava'.
> Compilation failed; see the compiler error output for details.
```

### Environment Information

- **Operating System**: Win7 x64
- **Micronaut Version:** commit d53800700429a02c19b8f5ba478b13c4205feaf3 (master branch)
- **JDK Version:** 
```
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

### Example Application

- N/A

**Comment by graemerocher** [comment]
Please build the source with the latest version of Java 8

**Comment by rmorrise** [comment]
I was able to compile it. Thank you!
