### ISSUE TITLE
buildBeanDefinition method fails to build beans using introduction advice to implement interface

### ISSUE THREAD

**Issue by goldsam** [micronaut-projects/micronaut-core#1700]
`BeanDefinition AbstractTypeElementSpec#buildBeanDefinition(String className, String cls)`
in `inject-java-test` fails to build bean when using introduction advice to introduce an interface to a concrete classs. The intent is to achieve a similar result to [this test](https://github.com/micronaut-projects/micronaut-core/blob/master/inject-groovy/src/test/groovy/io/micronaut/aop/introduction/IntroductionAdviceWithNewInterfaceSpec.groovy#L31-L68).

### Steps to Reproduce

1. clone https://github.com/goldsam/axonframework-micronaut
2. checkout branch `introduction-new-interface-not-working`
3. build & test via `mvn test`

### Expected Behaviour
A Bean definition for class `test.Thing` should be built which implements interface `QueryHandlerAdapter` as result of annotating the class with the `@QueryHandling` annotation. This should be achieved via the `QueryHandlingAdapterIntoduction` method interceptor.

### Actual Behaviour

Compilation fails with the following:

```
java.lang.ClassNotFoundException: test.$ThingDefinition
	at org.github.goldsam.axonframework.micronaut.queryhandling.annotation.QueryHandlingAdapterIntoductionSpec.test that @QueryHandling introduces the QueryHandlerAdapter interface to a concrete class. (QueryHandlingAdapterIntoductionSpec.groovy:27)
```

### Environment Information

- **Operating System**: Windows 10 Pro
- **Micronaut Version:** 1.1.1
- **JDK Version:** 1.8.0_211

**Comment by goldsam** [comment]
Two points worth noting:

1) The code does indeed work as expected when imported by another Micronaut project, as I can inject a non-null `QueryHandlerAdpater` after I annotate a call with `QueryHanding`. The issue is limited to the testing annotated beans using the `AbstractTypeElementSpec` class.

2) Removing the `Introduction` stereotype from the `QueryHandling` annotation allows the bean definition to be created.

**Comment by goldsam** [comment]
Oops. wrong button.

**Comment by graemerocher** [comment]
This is working as designed. The test can be made to pass with

```diff
diff --git a/src/test/groovy/org/github/goldsam/axonframework/micronaut/queryhandling/annotation/QueryHandlingAdapterIntoductionSpec.groovy b/src/test/groovy/org/github/goldsam/axonframework/micronaut/queryhandling/annotation/QueryHandlingAdapterIntoductionSpec.groovy
index 6f53a17..c835955 100644
--- a/src/test/groovy/org/github/goldsam/axonframework/micronaut/queryhandling/annotation/QueryHandlingAdapterIntoductionSpec.groovy
+++ b/src/test/groovy/org/github/goldsam/axonframework/micronaut/queryhandling/annotation/QueryHandlingAdapterIntoductionSpec.groovy
@@ -16,7 +16,7 @@ import org.junit.Assert
 import org.junit.Before
 import org.junit.Test
 import static org.junit.Assert.*
-
+import io.micronaut.inject.writer.BeanDefinitionVisitor
 /**
  *
  */
@@ -24,7 +24,7 @@ public class QueryHandlingAdapterIntoductionSpec extends AbstractTypeElementSpec
 
     void "test that @QueryHandling introduces the QueryHandlerAdapter interface to a concrete class. "() {
         when:
-        BeanDefinition beanDefinition = buildBeanDefinition('test.Thing', '''
+        BeanDefinition beanDefinition = buildBeanDefinition('test.Thing'  + BeanDefinitionVisitor.PROXY_SUFFIX, '''
 package test;
 
 import javax.inject.Singleton;
```

**Comment by goldsam** [comment]
Awesome. thanks for the clarification :)
