### ISSUE TITLE
Lots of environment variables slow startup significantly

### ISSUE THREAD

**Issue by dhoff1985** [micronaut-projects/micronaut-core#1714]
We have many services in our kubernetes environment which results in a lot of environment variables being set by kubernetes for service discovery. We are seeing this cause a significant slowdown in startup time for our application.

https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Set 600 environment variables with 3 to 10 underscores
Start a micronaut app

### Expected Behaviour

startup in ~1 second

### Actual Behaviour

startup in 10 seconds

### Environment Information
Mac osx
latest master (see fork commit link)
1.8.0_202

### Example Application

https://github.com/dhoff1985/micronaut-core/commit/06a5135818409158cd349d6e271b8d1b88907c6a

**Comment by graemerocher** [comment]
Thanks for the report we will take a look

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/9ffa331cf700fc81a083912e82fc618c1a678d3e

**Comment by jameskleeh** [comment]
@dhoff1985 The algorithm to compute the properties has been rewritten and I'm seeing a speed improvement by a factor of 50. In addition, options on the context builder have been added to allow further control over which environment variables are included in the context, if any.

**Comment by dhoff1985** [comment]
Thanks. I will check it out.

**Comment by dhoff1985** [comment]
I pulled it in. I see that the startup time is normal now. Thanks for fixing this and being so responsive!!
