### ISSUE TITLE
HttpClient: support collections as query parameter in declarative client 

### ISSUE THREAD

**Issue by sschnabe** [micronaut-projects/micronaut-core#1715]
### Steps to Reproduce

1. Create declarative client with [list as query parameter](https://github.com/sschnabe/micronaut-httpclient-lists/blob/master/src/main/java/io/micronaut/issue/HelloApi.java#L12).
2. Use declarative client.

### Expected Behaviour

`List.of("a", "b")` results in URI with parameters `?args=a&args=b`

### Actual Behaviour

`List.of("a", "b")` results in URI with parameters `?args=a%2Cb
`

### Environment Information
- **Operating System**: Ubuntu
- **Micronaut Version:** 1.1.2
- **JDK Version:** openjdk 11.0.1 2018-10-16

### Example Application
see [micronaut-httpclient-lists](https://github.com/sschnabe/micronaut-httpclient-lists)
The test **declarative** is failing.

### Investigation

Query parameters are handled as single parameter in [HttpClientIntroductionAdvice](https://github.com/micronaut-projects/micronaut-core/blob/v1.1.2/http-client/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java#L288-L295). I wrote a [fix](https://github.com/sschnabe/micronaut-core/commit/b35cf94deacf68574ff396ebdd1b960265f499bb) but i am not sure where to write tests for this issues. Maybe part of [PetOperations](https://github.com/micronaut-projects/micronaut-core/blob/master/http-client/src/test/groovy/io/micronaut/http/client/docs/annotation/PetOperations.java)?

**Comment by jameskleeh** [comment]
To achieve the behavior you want you have to change the URI template on the controller to be `/hello{? args*}

**Comment by sschnabe** [comment]
Yes, this works. Thanks!

**Comment by stepanv** [comment]
For the record, to avoid confusion, the `{?args*}` goes to the `Controller` as well as the `Client`. In the case of this reproducer ^^, it goes only to the interface `HelloApi`, the `@Get` annotation which both the controller and the client implement:
```
public interface HelloApi {

	@Get(uri = "/hello{?args*}", produces = MediaType.APPLICATION_JSON)
	List<String> hello(@QueryValue List<String> args);
}
```
