### ISSUE TITLE
add -H:+AddAllCharsets to native-image.properties file

### ISSUE THREAD

**Issue by avierr** [micronaut-projects/micronaut-core#1716]
### Steps to Reproduce

1. use the hello-world app and use the popular okHttp library

### Expected Behaviour
No errors

### Actual Behaviour
...
Caused by: java.nio.charset.UnsupportedCharsetException: UTF-32BE
	at java.nio.charset.Charset.forName(Charset.java:531)
	at okhttp3.internal.Util.<clinit>(Util.java:75)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:347)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:267)

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 1.1.2
- **JDK Version:** graal 19

Also see, https://github.com/oracle/graal/issues/1294
Adding the -H:+AddAllCharsets to the native-image.properties file will sort a ton of issues with third party libraries.

**Comment by ilopmar** [comment]
I've tested with our basic app: https://github.com/micronaut-graal-tests/micronaut-basic-app and using `-H:+AddAllCharsets` flag makes the final images size gets increased in 6 MB.

```
-rwxr-xr-x  1 ivan ivan 62135568 May 29 15:49 basic-app.all-charsets
-rwxr-xr-x  1 ivan ivan 55837792 May 29 15:44 basic-app.19
```

So I'm not really sure if it is worth it to enable it by default.

@graemerocher thoughts?

**Comment by graemerocher** [comment]
Yeah I don't think this should be there by default.
