### ISSUE TITLE
Form data submitted using POJO seems to be urldecoded twice

### ISSUE THREAD

**Issue by michalpetrov** [micronaut-projects/micronaut-core#1718]
Form data submitted using POJO seems to be urldecoded twice. If the submitted text contains '+' it is translated to space.

### Steps to Reproduce
Run the example. Enter "a+b" in the field and submit. It should output same text to console, but instead outputs "a b"

```java
@Controller
public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }

    @Get(produces = MediaType.TEXT_HTML)
    public HttpResponse html(){
        return HttpResponse.ok("<body><form method='post'><input type='text' name='text'></form></body>");
    }

    //    this works, outputs "a+b"
    //    @Post(consumes = MediaType.APPLICATION_FORM_URLENCODED)
    //    public HttpResponse save(String text) {
    //        System.out.println("TEXT: " + text);
    //        return HttpResponse.ok();
    //    }

    // this doesn't work, outputs "a b"
    @Post(consumes = MediaType.APPLICATION_FORM_URLENCODED)
    public HttpResponse save(Dto dto) {
        System.out.println("TEXT: " + dto.getText());
        return HttpResponse.ok();
    }

    public static class Dto {
        private String text;
        public String getText() { return text; }
        public void setText(String text) { this.text = text; }
    }
}
```

### Environment Information

- **Operating System**: Macos x
- **Micronaut Version:**  1.1.1
- **JDK Version:** OpenJDK Runtime Environment 18.9 (build 11.0.1+13)

Any quick workaroud would be appreciated.

**Comment by michalpetrov** [comment]
After further investigation.
If the `save` method uses parameters instead of POJO, it skips the `NettyHttpRequest.buildBody()` method.
But if POJO is used, then an already urldecoded request is urldecoded again in the `NettyHttpRequest.buildBody()` method.

**Comment by jameskleeh** [comment]
Thanks for the report and investigation
