### ISSUE TITLE
consul.client.discovery.enabled has no effect

### ISSUE THREAD

**Issue by lightoze** [micronaut-projects/micronaut-core#1720]
### Steps to Reproduce

1. Set `consul.client.discovery.enabled: false`
2. Try using a `DiscoveryClient`.

### Expected Behaviour

`DiscoveryClient` responds with empty instance list.

### Actual Behaviour

`DiscoveryClient` attempts to use Consul and produces "HttpClientException: Connect Error: Connection refused: localhost/127.0.0.1:8500"

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.1.2
- **JDK Version:** 11.0.3

**Comment by graemerocher** [comment]
That property doesn't seem to be handled. There is `consul.client.enabled` but that disables the client completely
