### ISSUE TITLE
Tests failed to run when using kotlin and spock

### ISSUE THREAD

**Issue by skorikovdm** [micronaut-projects/micronaut-core#1721]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. `mn create-app -l kotlin --features=spock mn-kotlin-spock`
2. `cd mn-kotlin-spock`
3. `mn create-controller mn.kotlin.spock.Main`
This generates tests, but ends up with error
```
| Rendered template Controller.kt to destination src/main/kotlin/mn/kotlin/spock/MainController.kt
| Rendered template ControllerSpec.groovy to destination src/test/groovy/mn/kotlin/spock/MainControllerSpec.groovy
| Error Command [mn] error: create-controller.reset()V (Use --stacktrace to see the full trace)
```

4. edit `src/test/groovy/mn/kotlin/spock/MainControllerSpec.groovy` to make test to fail: 
```
expect:
        response.status != HttpStatus.OK
```
5. `./gradlew test`

### Expected Behaviour

There should be 1 failed test

### Actual Behaviour

If I run `./gradlew test` without any modifications in build.gradle, I receive exception
```
Execution failed for task ':compileTestGroovy'.
> BUG! exception in phase 'semantic analysis' in source unit '/home/xxx/mn-kotlin-spock/src/test/groovy/mn/kotlin/spock/MainControllerSpec.groovy' sun.reflect.annotation.TypeNotPresentExceptionProxy
```
If I comment this line in build.gradle
```
// testCompile "org.junit.jupiter:junit-jupiter-api"
```
I receive 

> BUILD SUCCESSFUL

 with no test errors

### Environment Information

- **Operating System**: Linux Minn 17
- **Micronaut Version:** 1.1.2
- **JDK Version:** 1.8.0_201 (Oracle Corporation 25.201-b09)

### Example Application

https://github.com/skorikovdm/mn-kotlin-spock

**Comment by puneetbehl** [comment]
Also, remove following from your `build.gradle`:
```
test {
    useJUnitPlatform()
}
```

**Comment by puneetbehl** [comment]
Here is the sample application [kotlin-spock.zip](https://github.com/micronaut-projects/micronaut-core/files/3235738/kotlin-spock.zip)

**Comment by benrhine** [comment]
@puneetbehl I re-looked at this because I have been working in this area specifically in generating tests when using kotlin. I can say that this issue will no longer be present for certain once pr https://github.com/micronaut-projects/micronaut-profiles/pull/198 is merged in.

With that said though, do we close this issue as fixed in a future version? I do see that if I use micronaut version 1.1.2 as listed in the ticket i see the error when attempting to generate a controller

```
 => mn create-controller Tom --stacktrace
| Rendered template Controller.kt to destination src/main/kotlin/example/TomController.kt
| Rendered template ControllerSpec.groovy to destination src/test/groovy/example/TomControllerSpec.groovy
| Error Command [mn] error: create-controller.reset()V (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
java.lang.AbstractMethodError: create-controller.reset()V
	at io.micronaut.cli.profile.AbstractProfile.handleCommand(AbstractProfile.groovy:497)
	at io.micronaut.cli.MicronautCli.handleCommand(MicronautCli.groovy:428)
	at io.micronaut.cli.MicronautCli.handleCommand(MicronautCli.groovy:414)
	at io.micronaut.cli.MicronautCli.execute(MicronautCli.groovy:264)
	at io.micronaut.cli.MicronautCli.main(MicronautCli.groovy:178)
| Error Command [mn] error: create-controller.reset()V
``` 

I did try removing the test block as you suggested and that did not fix that an error was thrown in that specific version.
