### ISSUE TITLE
Micronaut slow start

### ISSUE THREAD

**Issue by RaviH** [micronaut-projects/micronaut-core#1732]
A simple micronaut app created via command line on Mac starts in 1184ms. I have seen people report less than 500 ms. In comparison to that 1184 ms (even though way faster than Spring) still seems slow.

I have attached the zipped project and log file to the issue:

**Logs**: [simple_service.log](https://github.com/micronaut-projects/micronaut-core/files/3235541/simple_service.log)

**Example application**: [simple-service.zip](https://github.com/micronaut-projects/micronaut-core/files/3235543/simple-service.zip)

My _/etc/hosts_ file (since that's been the cause of slowness on Mac in other similar issues):

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       localhost KAPAMAC12FMG3QD
::1             localhost KAPAMAC12FMG3QD
```

### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Either you can open the attached project zip file or try the steps below: 

`mn create-app --features http-server,http-client --lang java --build maven simple-service`
`cd simple-service`
`mvn clean package`
`java -jar target/simple-service-0.1.jar`

### Expected Behaviour

An empty service should start in less than 300 ms.

### Actual Behaviour

Service starts in 1.1 seconds.

### Environment Information

- **Operating System**: Mac OS High Sierra 10.13.6
- **Micronaut Version:** 1.1.2
- **JDK Version:** 1.8.0_162

```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T11:41:47-07:00)
Maven home: /Users/rhasija/.sdkman/candidates/maven/current
Java version: 1.8.0_162, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

```

**Comment by jameskleeh** [comment]
Approximately 1 second startup time is to be expected for an empty Java application

**Comment by RaviH** [comment]
Thanks @jameskleeh . Good to know I wasn't missing something obvious.
