### ISSUE TITLE
Single injection of @EachProperty should throw NonUnique exception

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-core#1736]
Creating the issue to track this behavior change for the next major version

The current behavior is surprising and inconsistent with how injections work from beans created in different ways.

**Comment by lightoze** [comment]
Is it pushed to next version because of too much changes required or because there's some code out there depending on this behaviour?
I'm asking because returned bean is nondeterministic here and it's hard to imagine how it can be used reliably.

**Comment by jameskleeh** [comment]
It is deterministic based on the first property. It’s in the next version
because it’s a breaking change

**Comment by lightoze** [comment]
I see now that it is indeed deterministic. Do you think it's possible for now to at least add a warning to `DefaultApplicationContext.findConcreteCandidate` when there are more than two candidates?
