### ISSUE TITLE
[Micronaut Environment Detection] Detect AWS Lambda, too

### ISSUE THREAD

**Issue by SchulteMarkus** [micronaut-projects/micronaut-core#1745]
I am using Micronaut 1.1.2 as Java-framework for my AWS Lambdas as described on https://micronaut-projects.github.io/micronaut-aws/latest/guide/#lambda

The Java-lambda runs fine within AWS Lambda.

I am using [MICRONAUT_ENVIRONMENTS](https://docs.micronaut.io/latest/guide/index.html#environments) for having environment specific Lambda-behavior. For example, in a test environment, do not use AWS services. 
When running the Java-Micronaut-Lambda within AWS, I can see the (auto-)detected environment in the log

    2019-06-04 09:30:14 INFO DefaultEnvironment:204 -
      Established active environments: [function]

**Is**: [Micronaut Environment Detection](https://docs.micronaut.io/latest/guide/index.html#cloudConfiguration) does not have a detection of being run in AWS Lambda. 
**Bug?**: The [cloud](https://docs.micronaut.io/latest/api/io/micronaut/context/env/Environment.html#CLOUD)-detection is not active. "The application is running in a Cloud environment (present for all other cloud platform types)" (from https://docs.micronaut.io/latest/guide/index.html#cloudConfiguration).
**Feature request**: Please add a detection for AWS Lambda, too.

**Comment by graemerocher** [comment]
This is resolved in the latest version

**Comment by SchulteMarkus** [comment]
> + RESPONSE='13:16:47.917 [main] INFO i.m.context.env.DefaultEnvironment - Established active environments: [ec2, cloud, function]

:-)
