### ISSUE TITLE
Support for Websockets and HTTP2 ?

### ISSUE THREAD

**Issue by sureshg** [micronaut-projects/micronaut-core#175]
Hi, I am not sure this is the right place to ask for the feature requests, but couldn't find any better place than Github issue tracker. It would be great to add support for HTTP2 and Websockets to `micronaut`.

**Comment by jameskleeh** [comment]
We already have an issue in place for websockets which is planned to be implemented before the 1.0 release. HTTP/2 support will come after and it is on our list. I've just created an issue for it. Thanks for the request!

https://github.com/micronaut-projects/micronaut-core/issues/191
https://github.com/micronaut-projects/micronaut-core/issues/176
