### ISSUE TITLE
mn CLI connection timeout - problem parsing proxies in .m2/settings.xml

### ISSUE THREAD

**Issue by DBarthe** [micronaut-projects/micronaut-core#1751]
After installing micronaut through skdman, I got timeout issues :
```bash
$ mn
Resolving dependencies...
| Error Error occurred running Micronaut CLI: connect timed out (Use --stacktrace to see the full trace)
```
After inspection, it's because mn tries to connect to a proxy that is configured in my `~/.m2/settings.xml` even if it is disabled.
```xml
<settings>
      ...
      <proxies>
       <proxy>
          <id>exemple-proxy</id>
          <active>false</active>
          <protocol>http</protocol>
          <host>proxy.exemple.com</host>
          <port>3128</port>
        </proxy>
      </proxies>
 ...
</settings>
```
It seems that mn reads the `~/.m2/settings.xml` file but ignores the `<active>false</active>` directive.

You can inspect the network behavior of mn cli by running something like :
```
strace -f -e trace=network -s 10000 /usr/lib/jvm/java-8-oracle/bin/java -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:CICompilerCount=3 -classpath ~/.sdkman/candidates/micronaut/1.1.3/cli-1.1.3.jar io.micronaut.cli.MicronautCli
```
and you'll see if it tries to connect through the proxy.

**Comment by graemerocher** [comment]
We use Maven's dependency resolution Aether within the CLI so the behaviour is whatever that gives us. It may be a bug our out dated version of Aether we are using? Not sure

**Comment by Centaur** [comment]
Same problem here. Luckily this blocking one has simple workaround.

**Comment by KLBonn** [comment]
Same for me, on Windows 10 with downloaded binary.

It was quite annoying to dig through Micronaut documentation and StackOverflow completely in vain. No environment variables (HTTPS_PROXY, MN_OPTS...) system properties could change the behaviour of mn: it always tried the (disabled and dysfunctional) first proxy entry of %USERPROFILE%\.m2\settings.xml.

I am really glad I discovered this issue (and workaround), so at least I can continue for now.

**Comment by jameskleeh** [comment]
This is no longer an issue for Micronaut 2 because no external calls are done
