### ISSUE TITLE
Add support for `@Parameter` bean list injection

### ISSUE THREAD

**Issue by lightoze** [micronaut-projects/micronaut-core#1753]
Currently `@Parameter` only supports single bean injection. For consistency it would be great to have support for injecting collections of beans and so on (see "Injectable Container Types" in documentation).

### Expected Behaviour

`@Parameter` works generally the same as `@Inject @Named("<parent bean name>")`

### Actual Behaviour

`@Parameter` produces unexpected results, such as `List<String>` instead of `List<BeanClass>` which later leads to runtime class cast exception.

### Environment Information

- **Micronaut Version:** 1.1.2

### Example

See https://github.com/micronaut-projects/micronaut-core/pull/1752

**Comment by jameskleeh** [comment]
Closing this issue because it seems like what is desired is to have multiple beans with the same qualifier which is not something we will likely ever support. You can inject a list with `@Parameter` in the case of prototype beans.

**Comment by lightoze** [comment]
@jameskleeh yes, this was essentially about having multiple beans with the same `@Named` qualifier.
