### ISSUE TITLE
Release Micronaut-Redis 1.1.1

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#1762]
Release Micronaut-Redis 1.1.1 and include it in the BOM.

**Comment by graemerocher** [comment]
Is there any particular reason this is needed? Is it just for this commit https://github.com/micronaut-projects/micronaut-redis/commit/79c566c9a6b61290f750671f292fb6e04e61005b ?

**Comment by ilopmar** [comment]
Yes, because I saw there were changes in the repo. If you think that commit is not that important we can wait to next release.
