### ISSUE TITLE
Generic Types not being Handled properly in Controller methods

### ISSUE THREAD

**Issue by juliuskrah** [micronaut-projects/micronaut-core#1769]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

I have a Controller method that inherits from a base controller with generic types:

I am using Micronaut 1.1.1

### Steps to Reproduce

```java
// Generic Controller
public abstract class GenericController<T, ID extends Serializable> {
  public abstract String getPath();
  @Post
  public Mono<HttpResponse<T>> save(@Valid @Body T entity) {
	return service.save(entity).map(savedEntity -> {
			var location = UriBuilder.of(getPath()) //
					.path(getId(savedEntity)).build();
			return created(savedEntity, location);
	});
  }
}

// Status Controller
@Validated
@Controller(StatusController.PATH)
public class StatusController extends GenericController<Status, UUID> {
  static final String PATH = "/statuses";
  @Override
  public String getPath() {
	return PATH;
  }
}

// Entity
@Value
@Builder
@JsonDeserialize(builder = Status.StatusBuilder.class)
public class Status {
	private UUID id;
	@Size(max = 100)
	@NotBlank
	private String name;
	private boolean editable;
	private String description;

	@JsonPOJOBuilder(withPrefix = "")
	public static class StatusBuilder {}
}
```

When I do a post `http://localhost:8080/statuses` with payload:

```json
{
  "name": "foo"
}
```

I get the following error:

```
Internal Server Error: class com.fasterxml.jackson.databind.node.ObjectNode cannot be cast to class com.foo.dto.Status (com.fasterxml.jackson.databind.node.ObjectNode and com.foo.dto.Status are in unnamed module of loader 'app'
```

### Expected Behaviour

Micronaut should deserialize the JSON into the POJO type using Jackson

### Actual Behaviour

It throws an exception

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.1.1
- **JDK Version:** 11

### Example Application

- Github Link: [jaesoft/resk](https://github.com/jaesoft/resk/tree/miconaut-1769)

**Comment by jameskleeh** [comment]
I boiled this down to a simpler example and it works. Can you upload a sample that reproduces the issue

```
public class GenericController<T, ID extends Serializable> {
    @Post
    Mono<HttpResponse<T>> save(@Body T entity) {
        return Mono.just(HttpResponse.created(entity));
    }
}

@Controller("/statuses")
public class StatusController extends GenericController<Status, UUID> {

}

@JsonDeserialize(builder = Status.StatusBuilder.class)
public class Status {

    private String name;

    private Status(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    @JsonPOJOBuilder
    static class StatusBuilder {

        private String name;

        StatusBuilder withName(String name) {
            this.name = name;
            return this;
        }

        Status build() {
            return new Status(name);
        }
    }
}
```

**Comment by juliuskrah** [comment]
> I boiled this down to a simpler example and it works. Can you upload a sample that reproduces the issue?
> 

@jameskleeh I have uploaded sample at https://github.com/jaesoft/resk/tree/miconaut-1769

**Comment by jameskleeh** [comment]
@juliuskrah Thanks I understand what the issue is now

**Comment by juliuskrah** [comment]
This issue is re-occurring with 1.2.0.RC2

**Comment by jameskleeh** [comment]
@juliuskrah Same repo/branch/steps to reproduce?

**Comment by juliuskrah** [comment]
> @juliuskrah Same repo/branch/steps to reproduce?

Use this repo to reproduce the issue: https://github.com/jaesoft/resk/tree/micronaut-1769

**Comment by jameskleeh** [comment]
Turns out the commits got accidentally rolled back. Thanks for the report
