### ISSUE TITLE
[CLI] Specify which features are coming by default or as dependencies of other features

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#1774]
Currently, the `profile-info` command doesn't specify which features will be selected by default (like those of the `base` profile), or as dependencies of other features.

It would be great to append `(+)` to those features that will be default. Also, features that have requirements could be listed in their description.

**Comment by benrhine** [comment]
This is basically the same issue https://github.com/micronaut-projects/micronaut-profiles/issues/181

**Comment by benrhine** [comment]
this pull request will append the `(+)` to included features as well as there is now an additional `-e` or `--enhancedInfo` option that will display what comes in or is evicted with certain features https://github.com/micronaut-projects/micronaut-core/pull/2476
