### ISSUE TITLE
Json decode error in the Http client silently returns Optional.empty

### ISSUE THREAD

**Issue by luckyswede** [micronaut-projects/micronaut-core#1779]
Hi,
I'm using Lombok for Pojos that are converted to/from json when sent as requests/responses with Micronaut clients, and every once in a while i mess up the Lombok/Jackson annotation combination that is needed to make it work.
When that happens and cause the decoding to fail, the Micronaut http client silently (well, almost, it logs on DEBUG) returns an Optional.empty, which is very confusing and takes time to understand. See https://github.com/micronaut-projects/micronaut-core/blob/master/http-client/src/main/java/io/micronaut/http/client/FullNettyClientHttpResponse.java#L240

Is this a conscious design decision? Why is not an error logged and an exception thrown instead?

**Comment by graemerocher** [comment]
I agree this is confusing
