### ISSUE TITLE
static-resources can not dynamic serve upload file

### ISSUE THREAD

**Issue by ibmsoft** [micronaut-projects/micronaut-core#1781]
use micronaut 1.1.3

in my application.yml

config 
`
  router:

    static-resources:

      vbot:

        enabled: true

        mapping: /static/**/*

        paths: "classpath:public"
`
when i dynamic upload a image  111.png file to the  resource/publc dic, the file can not show by full url

http://localhost:8080/static/upload/image/20190611/111.png

but when i restart the app ,the full url image can show correct

**Comment by jameskleeh** [comment]
You would have to use one of the supported reload options. See https://docs.micronaut.io/latest/guide/index.html#reloading

In general that isn't something you would ever do in production for a number of reasons
