### ISSUE TITLE
Inconsistent inflection on uppercase value names when setting the value in a MicronautTest

### ISSUE THREAD

**Issue by SchulteMarkus** [micronaut-projects/micronaut-core#1786]
Hi there,

I am using Micronaut 1.1.2, and I have discovered a inconsistency in combination of the name of a [@Value](https://docs.micronaut.io/latest/api/io/micronaut/context/annotation/Value.html),  and setting this value (using @Property) in a MicronautTest.

There is a project available, illustrating my problems https://github.com/SchulteMarkus/markusschultevalue

My class under test https://github.com/SchulteMarkus/markusschultevalue/blob/master/src/main/java/markusschultevalue/SomeFactory.java#L15 has 

    @Value("${SOME_CONFIG_VALUE}")

As I assume meanwhile, this should better be written _some.config.value_. Anyhow, this is valid code, and it does even work (when I run the application with SOME_CONFIG_VALUE=abc, it will be read).

The MicronautTest https://github.com/SchulteMarkus/markusschultevalue/blob/master/src/test/java/markusschultevalue/PropertyAnnotationTest.java fails for time being because of missing  SOME_CONFIG_VALUE, although it has

    @Property(name="SOME_CONFIG_VALUE", value="Some Widget Name")

But, if I run the test like this

    SOME_CONFIG_VALUE="Some Widget Name" ./gradlew clean test

the test succeeds. 

This issue is a follow up of https://stackoverflow.com/q/56539052/1645517

**Comment by jameskleeh** [comment]
The `@Property` annotation should only have names set that are kebab case.

When an uppercase underscore name is encountered in a placeholder, it is looked up in the environment variables.

You can allow this to work by using `@Value("${some.config.value}")` and that value will still be populated from the environment variable.

**Comment by SchulteMarkus** [comment]
ack
