### ISSUE TITLE
Kotlin inline classes breaking micronaut AOP

### ISSUE THREAD

**Issue by dant3** [micronaut-projects/micronaut-core#1792]
If you use inline classes in your micronaut application as return type or as parameter in `@Advice` annotated class, this leads to runtime exceptions `java.lang.AbstractMethodError`

Example stacktrace:
```
java.lang.AbstractMethodError: com.example.backend.HelloClient$Intercepted.hello-SS0zJaQ(Ljava/lang/String;)Ljava/lang/String;
	at com.example.backend.HelloControllerTest.testHelloWithName(HelloControllerTest.kt:32)
```

You can find example application that reproduce issues I found with micronaut+kotlin inline classes at https://github.com/dant3/kotlin-inline-classes-issue. Just run `./gradlew test` - if micronaut + inline classes would work I expect every test to pass.

### Steps to Reproduce

1. Use inline class as argument of method in `@Advice`-annotated interface (or use it as return type)
2. Call this method

### Expected Behaviour
MethodInterceptor should be invoked.

### Actual Behaviour
An exception `java.lang.AbstractMethodError` is thrown.

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 1.1.13
- **JDK Version:** JDK 8

### Example Application
https://github.com/dant3/kotlin-inline-classes-issue

*P.S.*
In kotlin 1.3 inline classes are still experimental, as you can see in disclaimer at https://kotlinlang.org/docs/reference/inline-classes.html. However they are still useful, so it is something to consider.

**Comment by jameskleeh** [comment]
As per the Kotlin documentation suggests:

> Note that - is an invalid symbol in Java, meaning that it's impossible to call functions which accept inline classes from Java.

The classes that Micronaut generates are Java classes, thus the above is the reason why it can't work
