### ISSUE TITLE
Provide Default for RxJavaPlugins.setErrorHandler

### ISSUE THREAD

**Issue by dhoff1985** [micronaut-projects/micronaut-core#1799]
I have noticed a lot of stack traces in our logs coming out of RxJavaPlugins.onError. I created a sample application to demonstrate this. 

By Default for unhandled rxjava errors it prints a stack trace. This is problematic because the stack trace printing is a blocking IO call from an event loop thread. We have witnessed this cause significant slowdown during failure modes.

The other problem with this is that the stacktrace interleaves with std out logging so kubernetes style apps logging to standard out have random stack traces interleaved into their logging output. 

I think it would be reasonable for micronaut to provide a default for RxJavaPlugins.setErrorHandler. This could be done in a way where it is added if there is not one already present so the application itself can decide to do something differently if desired.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

This seems to happen when a netty error occurs when the caller has already hung up. For example when there is a rx timeout added to an object that times out before the netty read timeout. 

1. Run RxFailureSpec in example project
2. observe stacktrace in standard out
3. Also you could set a breakpoint at RxJavaPlugins.onError() and observe it is calling printStackTrace()

### Expected Behaviour

Don't print a stack trace

### Actual Behaviour

Printed a stack trace

### Environment Information

Mac os x
1.1.3
openjdk version "1.8.0_202" 

### Example Application
https://github.com/dhoff1985/micronaut-rx-stacktrace

[rx-stacktrace.txt](https://github.com/micronaut-projects/micronaut-core/files/3292176/rx-stacktrace.txt)

**Comment by graemerocher** [comment]
It should never arrive to point of calling `RxJavaPlugins.onError()`. I think we have resolved the cases where this is happening, but if you see it again in a future release after 1.1.4 let us know.
