### ISSUE TITLE
Error resolving property value [redis.password]

### ISSUE THREAD

**Issue by chenjpu** [micronaut-projects/micronaut-core#1800]
micronaut : 1.2.0-RC1

Message: Error resolving property value [redis.password]. Property doesn't exist
Path Taken: StatefulRedisConnection.redisConnection([RedisClient redisClient]) --> RedisClient.redisClient([AbstractRedisConfiguration config]) --> DefaultRedisConfiguration.setPassword([char[] password])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [password] of method [setPassword] of class: io.micronaut.configuration.lettuce.DefaultRedisConfiguration

Message: Error resolving property value [redis.password]. Property doesn't exist
Path Taken: StatefulRedisConnection.redisConnection([RedisClient redisClient]) --> RedisClient.redisClient([AbstractRedisConfiguration config]) --> DefaultRedisConfiguration.setPassword([char[] password])

**Comment by jameskleeh** [comment]
Please follow the issue template
