### ISSUE TITLE
Validating POJO with Custom Constraint and Bean Validation API doesn't work

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#1801]
### Steps to reproduce the issue ### 

- Create a new Micronaut application with 1.2.0.RC1 and Spock
- Create a POJO:

```java
@Introspected
@NameAndLastNameValidator
public class Search {

    private String name;
    private String lastName;

   // Constructors, getters and setters
}
```

- Create the custom validator:

```java
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE})
@Constraint(validatedBy = { })
public @interface NameAndLastNameValidator {

    String message() default "Both name and lastName can't be null";
}
```

- Create factory:
```java
@Factory
public class NameAndLastNameValidatorFactory {

    @Singleton
    ConstraintValidator<NameAndLastNameValidator, Search> nameAndLastNameValidator() {
        return (value, annotationMetadata, context) ->
                value != null && (value.getName() != null || value.getLastName() != null);
    }
}
```

- Create test:
```groovy
@MicronautTest
class NameAndLastNameValidatorSpec extends Specification {

    @Inject
    Validator validator

    void 'test custom validator'() {
        given:
        Search search = new Search()

        when:
        Set<ConstraintViolation<Search>> constraintViolations = validator.validate(search)

        then:
        constraintViolations.size() == 1
    }
}
```

### Expected Behaviour ###

The test should pass

The test fails:
```
Condition not satisfied:

constraintViolations.size() == 1
|                    |      |
[]                   0      false
```
### Environment Information

- **Operating System**: Linux Mint 19.1
- **Micronaut Version:** 1.2.0.RC1
- **JDK Version:** OpenJDK 1.8.0_212

### Example Application

- https://github.com/ilopmar/mn-bean-validator-data-class

**Comment by v-marathe** [comment]
I have done the exact same implementation for validator on a bean. but when i fire the request, i get below exception:
javax.validation.UnexpectedTypeException: HV000030: No validator could be found for constraint <ConstraintName>.  Check configuration for <PropertyName on which validator is applied>. Any pointers?
If we create a separate class for validator and provide it @Constraint ( validatedBy = {MyValidator.class) only then it works. 
How can the validators written in @Factory be registered?
