### ISSUE TITLE
@PostConstruct being called twice in Function

### ISSUE THREAD

**Issue by itsdrew** [micronaut-projects/micronaut-core#1808]
The sample provided is from creating a function using the CLI (as described in the steps to reproduce) however this occurs in 1.2.0.RC1 as well.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. mn create-function extra-post-construct
2. added @PostConstruct public void initialize() { System.out.println("HELLO"); }
3. run the main method

### Expected Behaviour

HELLO should appear in the console once

### Actual Behaviour

HELLO appears in the console twice

### Environment Information

- **Operating System**: macOS mojave 10.14.4
- **Micronaut Version:**  1.2.0.RC1 and 1.1.1
- **JDK Version:** 1.8.0_202

### Example Application

https://github.com/itsdrew/extra-post-construct

**Comment by graemerocher** [comment]
I think this may be because we inject in the constructor (self inject) and then register the bean. Will investigate. Thanks for the feedback.

**Comment by graemerocher** [comment]
I have resolved this but note that is generally unsafe to use `@PostConstruct` in a function since the function injects itself via the constructor and at the point of the injection not all fields may have been initialised
