### ISSUE TITLE
Kafka Messaging Application Support

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#181]
Micronaut should natively support creating Kafka or RabbitMQ message/stream driven Microservices

**Comment by dominique-jocal-cbp** [comment]
Hi, if people who intended to contribute on this issue are available for discussion, a question: what about JMS instead of native RabbitMQ, to be able to use any 'traditionnal' messaging solution, from on premise MQSeries to managed AWS SQS ?

**Comment by graemerocher** [comment]
@dominique-jocal-cbp We are building out a generic solution, but starting with Kafka and Rabbit as those are the most popular solutions in a micro service environment. You can follow the progress on the `kafka` branch... so far we have `@KafkaClient` and `@KafkaListener` largely working. See https://github.com/micronaut-projects/micronaut-core/blob/kafka/configurations/kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaReactiveListenerSpec.groovy#L412

These build on general messaging APIs and annotations found in https://github.com/micronaut-projects/micronaut-core/tree/kafka/messaging/src/main/java/io/micronaut/messaging

There is still work to do to make things more generic and re-usable, but please feel free to contribute ideas and suggestions.

**Comment by akozel** [comment]
What decision about this ticket? Is new features appear (against documentation)? Is there no RabbitMQ  plans any more?

**Comment by graemerocher** [comment]
Kafka support is documented here https://docs.micronaut.io/snapshot/guide/index.html#messaging

RabbitMQ support has been moved to a separate ticket #384
