### ISSUE TITLE
Improvement: Error when unable to convert http body in http-client

### ISSUE THREAD

**Issue by Chase22** [micronaut-projects/micronaut-core#1824]
I am currently running into a problem using the Micronaut HTTP Client. When working with it in a production environment the logging/errors thrown by it are not sufficient.

### Steps to Reproduce

1. Inject a client using the @Client annotation
2. Make a request using a json serializable body type 
3. Have the request return a malformed json, or a json that cannot be parsed into the given type

### Expected Behaviour
An HttpClientException with a message like "Unable to parse body from Response" with a description why i couldn't be parsed

### Actual Behaviour
It returns an HttpClientResponseException with the message "Empty body"

### Environment Information

- **Operating System**: Xubuntu 16.04
- **Micronaut Version:** 1.1.3
- **JDK Version:** Java 11

**Comment by graemerocher** [comment]
Duplicates https://github.com/micronaut-projects/micronaut-core/pull/1780
