### ISSUE TITLE
Problem uploading multipart to Publisher<StreamingFileUpload>

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#1826]
In micronaut 1.2.0.RC1.

I'm trying to upload a multipart data and then receive it on the server side using `StreamingFileUpload`. Here's my test sending method:

```java
protected void testUploadMulti(String uri, int size) {
	MultipartBody.Builder builder = MultipartBody.builder();

	for (int i=0; i<size; i++)
		builder.addPart(
			"data",
			String.format("file%d.txt", i),
			MediaType.TEXT_PLAIN_TYPE,
			"0123456789"
		);

	client
		.toBlocking()
		.exchange(HttpRequest.POST(uri, builder.build())
			.contentType(MediaType.MULTIPART_FORM_DATA_TYPE), String.class)
		.getBody()
		.orElseThrow());
}
```

Where `client` is of `HttpClient` type. So, this method uploads one or more the same parts (text files) to the server. Now I'm testing `testUploadMulti("...", 1)` on the server side using this test controller method:

```java
@Post(uri = "...", consumes = MediaType.MULTIPART_FORM_DATA, produces = MediaType.TEXT_PLAIN)
public HttpResponse<String> uploadStreaming(StreamingFileUpload data) {

	data.subscribe(new Subscriber<>() {
		protected Subscription s;

		@Override
		public void onSubscribe(Subscription s) {
			logger.debug("onSubscribe: {}", s);
			this.s = s;
			s.request(1);
		}

		@Override
		public void onNext(PartData partData) {
			logger.debug("onNext: {}", partData);
			s.request(1);
		}

		@Override
		public void onError(Throwable t) {
			logger.debug("onError: ", t);
		}

		@Override
		public void onComplete() {
			logger.debug("onComplete");
		}
	});

	Utils.sleep(2000);

	logger.debug("Exitting...");

	return null;
}
```

And this works well when I upload one part in multipart post:

```
20:18:42.482 [pool-1-thread-2] DEBUG c.t.j.s.t.s.StreamingUpDownScratchController - onSubscribe: 0
20:18:42.484 [pool-1-thread-2] DEBUG c.t.j.s.t.s.StreamingUpDownScratchController - onNext: io.micronaut.http.server.netty.multipart.NettyPartData@43e282e1
20:18:42.485 [pool-1-thread-2] DEBUG c.t.j.s.t.s.StreamingUpDownScratchController - onComplete
20:18:44.485 [pool-1-thread-2] DEBUG c.t.j.s.t.s.StreamingUpDownScratchController - Exitting...
```

Now, according to the docs to upload more parts I should use `Publisher<StreamingFileUpload>`:

```java
@Post(uri = "...", consumes = MediaType.MULTIPART_FORM_DATA, produces = MediaType.TEXT_PLAIN)
public HttpResponse<String> uploadStreamingMulti(Publisher<StreamingFileUpload> data) {

	data.subscribe(new Subscriber<>() {
		protected Subscription s;

		@Override
		public void onSubscribe(Subscription s) {
			logger.debug("onSubscribe: {}", s);
			this.s = s;
			s.request(1);
		}

		@Override
		public void onNext(StreamingFileUpload streamingFileUpload) {
			logger.debug("onNext: {}", streamingFileUpload);
			s.request(1);
		}

		@Override
		public void onError(Throwable t) {
			logger.debug("onError: ", t);
		}

		@Override
		public void onComplete() {
			logger.debug("onComplete");
		}
	});

	Utils.sleep(2000);

	logger.debug("Exitting...");

	return null;
}
```

However, a result from `testUploadMulti("...", 2)` to this method is the following:

```
20:27:59.959 [pool-1-thread-2] DEBUG c.t.j.s.t.s.StreamingUpDownScratchController - onSubscribe: 0
20:27:59.961 [pool-1-thread-2] DEBUG c.t.j.s.t.s.StreamingUpDownScratchController - onNext: io.micronaut.http.server.netty.multipart.NettyStreamingFileUpload@14b07700
20:27:59.961 [pool-1-thread-2] DEBUG c.t.j.s.t.s.StreamingUpDownScratchController - onNext: io.micronaut.http.server.netty.multipart.NettyStreamingFileUpload@566f08d0
20:28:01.962 [pool-1-thread-2] DEBUG c.t.j.s.t.s.StreamingUpDownScratchController - Exitting...
```

It looks the `onComplete()` method is never invoked for this request. Therefore I also can't convert the `Publisher` to `Flowable` and use for example `map()` or `flatMap()` because after the conversion the streams always freezes.

Please check if it's a bug or I'm doing something wrong.

**Comment by jameskleeh** [comment]
@l0co We have a test that verifies this here https://github.com/micronaut-projects/micronaut-core/blob/master/test-suite/src/test/groovy/io/micronaut/upload/UploadController.java#L203

Can you upload a sample that reproduces the issue?

**Comment by l0co** [comment]
OK, I can see what the problem is with my code. To properly finish the whole process and complete `Publisher<StreamingFileUpload>` subscription you need to subscribe to each `StreamingFileUpload` separately. If you don't do it, this subscription never ends.

For example this one hangs infinitely:

```java
@Post(value = "/receive-multiple-streaming", consumes = MediaType.MULTIPART_FORM_DATA)
public Single<HttpResponse> receiveMultipleStreaming(
        Flowable<StreamingFileUpload> data) {
    return data.subscribeOn(Schedulers.io()).flatMap((StreamingFileUpload upload) -> {
        return Flowable.just(new byte[] {1});
    }).collect(LongAdder::new, (adder, bytes) -> adder.add((long)bytes.length))
            .map((adder) -> {
                return HttpResponse.ok(adder.longValue());
            });
}
```

**Comment by jameskleeh** [comment]
@l0co That is correct because you aren't requesting any demand from the client

**Comment by l0co** [comment]
Yes. However I still consider it a little confusing. When I started to play around this observable it just hangs and I thought it doesn't work, so I've never reached the second part of processing it, which is extracting yet another observables from the main observable, and then subscribing them.

If this is not a very big deal I'd consider to make the main observable properly completed even without child observables subscription.

**Comment by jameskleeh** [comment]
@l0co Unfortunately its not possible. The child observables request demand from the client. If no demand is requested then the process is hung waiting for demand. The parent observable completes after all files have been processed. How could it be properly completed without processing the children?

**Comment by l0co** [comment]
OK, I understand it's difficult, so let's live with this implementation.

> The same thing would happen if you just had `Publisher<byte[]>` file and never subscribed to it

This is not exactly the case. Here we have `Publisher<Publisher<byte[]>>` and we subscribe to the outer publisher, but never subscribe to the inner one. I'm quite new to reactive concepts so I cannot say if it's a common thing in such construction that if you don't subcribe to the inner one this automatically means the outer one doesn't end (?)

But this is just for the record. I understand the problem now and have a working example. Thanks!
