### ISSUE TITLE
Is it possible to mock AuthenticationProvider in my tests?

### ISSUE THREAD

**Issue by khangaikhuu** [micronaut-projects/micronaut-core#1828]
Hello,
I'm new in micronaut. I would like to ask some questions regarding to the tests of my current project. We are using for authentication JWT authentication via Cookies. It works fine in real projects, but if i want to test it regarding to this tutorial [Micronaut JWT authentication via Cookies](https://guides.micronaut.io/micronaut-security-jwt-cookie-kotlin/guide/index.html), then i cannot go through authentication. It always gives an error Unauthorized, even though we mock AuthenticationProvider. Is it possible to mock AuthenticationProvider? Thanks.

**Comment by sdelamo** [comment]
Thanks for reaching out @khangaikhuu  

Yes, you can mock an AuthenticationProvider.

However, this issue is more suited as a question in our Gitter community since it is not an issue of the framework: 

https://gitter.im/micronautfw/

> WHERE CAN I INTERACT WITH MICRONAUT DEVELOPERS AND COMMUNITY?
> The best place to chat with developers and users of Micronaut is the Gitter community. Drop in and join our community!
