### ISSUE TITLE
Part size is not recoverable from StreamingFileUpload

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#1832]
I upload a single file in multipart POST to this method:

```java
@Post(uri = "...", consumes = MediaType.MULTIPART_FORM_DATA, produces = MediaType.TEXT_PLAIN)
public Single<HttpResponse<String>> uploadStreamingForward(StreamingFileUpload data) throws IOException {
  // ...
}
```

The part size is sent in multipart header and known to `StreamingFileUpload` object, but is not accessible for user code in this method body:

![image](https://user-images.githubusercontent.com/1880196/60196951-a713d580-983e-11e9-84bc-c27b017dbccb.png)

This should be exposed on `StreamingFileUpload` interface because now I cannot get to know about this value before I consume all streaming parts and sum their sizes.

**Comment by l0co** [comment]
BTW. Is there any other option to receive a single file content (or just a binary data) on the server side in the streaming way without using a multipart request?

**Comment by graemerocher** [comment]
Yes you can declare Flowable<ByteBuffer> to receive the raw body in chunks
