### ISSUE TITLE
Function apply setter invoked multiple times

### ISSUE THREAD

**Issue by ctoestreich** [micronaut-projects/micronaut-core#1833]
When running simple openfaas profile function created via `mn create-function --build=maven --lang=java --features=openfaas  com.optum.cirrus.faas.hello-world-faas`

When the setter for the function object is changed to 

```java
   ...
    public String getName() {
        return name+ " muxed";
    }
   ...
```
The test for 

```java
@MicronautTest
public class HelloWorldFaasFunctionTest {

    @Inject
    HelloWorldFaasClient client;

    @Test
    public void testFunction() throws Exception {
        HelloWorldFaas body = new HelloWorldFaas();
        body.setName("hello-world");
        assertEquals("hello-world muxed", client.apply(body).blockingGet().getName());
    }
}

```

fails with 

```
[ERROR] Failures: 
[ERROR]   HelloWorldFaasFunctionTest.testFunction:19 expected: 
<hello-world muxed> but was: <hello-world muxed muxed muxed>
```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run `mvn clean install`

### Expected Behaviour

tests should pass

### Actual Behaviour

tests do not pass

### Environment Information

- **Operating System**: osx
- **Micronaut Version:** 1.2.0.RC
- **JDK Version:** 1.8

### Example Application

https://github.com/tardisoft/hello-world-faas-example

### Related Issue

Could be related to #1808

**Comment by ctoestreich** [comment]
I can confirm this only happens during local test/run.

Once the code is deployed to OpenFaaS I get the correct response

<img width="1402" alt="Screen Shot 2019-06-26 at 4 19 12 PM" src="https://user-images.githubusercontent.com/691357/60215882-4381ac00-982e-11e9-88e7-d4681296b87f.png">

**Comment by itsdrew** [comment]
#1808 Occurs local as well as when deployed to AWS
