### ISSUE TITLE
@Nullable Provider<SomeBean> someBean not working

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#1835]
I have a class like:

```
@Singleton
public class DefaultGraphQLInvocation implements GraphQLInvocation {

    private final GraphQL graphQL;
    private final GraphQLExecutionInputCustomizer graphQLExecutionInputCustomizer;
    private final Provider<DataLoaderRegistry> dataLoaderRegistry;

    public DefaultGraphQLInvocation(
            GraphQL graphQL,
            @Nullable GraphQLExecutionInputCustomizer graphQLExecutionInputCustomizer,
            @Nullable Provider<DataLoaderRegistry> dataLoaderRegistry) {
        this.graphQL = graphQL;
        this.graphQLExecutionInputCustomizer = graphQLExecutionInputCustomizer;
        this.dataLoaderRegistry = dataLoaderRegistry;
    }
```

which fails due to: `Failed to inject value for parameter [dataLoaderRegistry] when there is not DataLoaderRegistry bean.`

The reason I used `Provider` is that this bean is as prototype bean.

**Comment by jameskleeh** [comment]
@marceloverdijk Would you expect the provider itself to be null or `.get()` to return null ?

**Comment by marceloverdijk** [comment]
@jameskleeh I think with `@Nullable`, the natural would be that the provider itself is `null`.
I mean if `.get()` would return `null` instead, I would think `@Nullable` would not be needed.
Any solution would be fine, as currently there seems no way to do it unfortunately.

**Comment by marceloverdijk** [comment]
Thx @jameskleeh
