### ISSUE TITLE
Swagger for Kotlin seems broken in 1.1.3

### ISSUE THREAD

**Issue by matss** [micronaut-projects/micronaut-core#1844]
General
--------
Create a fresh Micronaut project by:
`mn create-app swagk --features=swagger-kotlin --features=kotlin`
then
`cd swagk` and
`./gradlew run`

No swagger yml gets generated.

As a side note
`mn create-app swagj --features=swagger-java` works fine.

### Steps to Reproduce

`mn create-app swagk --features=swagger-kotlin --features=kotlin`
`cd swagk` and
`./gradlew run`

### Expected Behaviour

swagger yml to be generated under `build` 
(as for Java)

### Actual Behaviour

No swagger yml generated

### Environment Information

- **Operating System**: MacOs 10.14.5
- **Micronaut Version:** 1.1.3
- **JDK Version:** 1.8.0_212 (also tried w 1.8.0_161)

### Example Application

Nothing edited after "mn create-app ..." - see above

**Comment by graemerocher** [comment]
As far as I can tell this is working even though it may "appear" not to be working. The Swagger YAML is generated to `build/tmp/kapt3/classes/main/META-INF/swagger/swagk-0.0.yml`

And included in the generated JAR file built with `assemble`. 

Kotlin's compiler for some reason suppresses messages from annotation processors so you don't get the same nice output as with Java. In addition Kotlin uses a weird location `build/tmp/kapt3/classes/main` to put content generated to annotation processors.

Neither of these problems are Micronaut bugs as such, more oddities in Kotlin IMO.

We may want to add more documentation to cover this for Kotlin users.

**Comment by matss** [comment]
Thanks!
You are right.
I was too busy looking under `build/classes` and missed the existence 
of `build/tmp/kapt3/classes`

**Comment by benrhine** [comment]
This has been updated https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#gettingStarted as per the merged pr #56 on Aug 18
