### ISSUE TITLE
Low-Level HTTP Client ignores serviceIds from filters

### ISSUE THREAD

**Issue by sascha-frinken** [micronaut-projects/micronaut-core#1850]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an app with 
2. Create a http  client filter with *serviceId annotation* **test** 
3. Create an RxHttpClient from the application context 
4. Make a request with the the RxHttpClient

### Expected Behaviour
Filter is not invoked as the low level client does not match the serviceId

### Actual Behaviour
Filter is invoked

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.2.0.RC1 and 1.1.3
- **JDK Version:** 1.8

### Example Application
https://github.com/safri-net/mn-client-filter-issue

1. Start application: `./gradlew run`
2. Call app `curl http:localhost:8080`
3. Notice print **`Should not happen: for uri https://www.google.com/search?q=micronaut`** should not be visible

**Comment by graemerocher** [comment]
You can resolve this by calling `setClientIdentifiers` on the created client.

**Comment by sascha-frinken** [comment]
The problem is that the current client that is used by `micronaut-security-oauth` to authenticate against our openid provider runs into our client filter. This leads into an infinite loop. We have no access to this client and therefor cannot `setClientIdentifiers`. Our current workaround is to tell the filter which uris it should match.
Our main problem is that a non serviceId cient runs a filter with an serviceId.
