### ISSUE TITLE
native-image: Including micronaut-http-netty dependency forces https / all security services

### ISSUE THREAD

**Issue by nhoughto** [micronaut-projects/micronaut-core#1856]
### Steps to Reproduce

1. n/a

### Expected Behaviour

The minimum set of things should be forcibly included in the native-image, with the option to opt-in to more if required? `http` protocol is required to use micronaut and netty, but `https` and all the TLS/security services that go along with it (increasing the size of your native image) are not.

It obviously depends on your use case, but i'd think the majority of users of micronaut are not running an HTTPS server, but terminating TLS elsewhere and using HTTP. This is especially likely in a docker/kubernetes environment.

### Actual Behaviour

Because of the way `native-image.properties` is configured, it enables the `https` protocol in the native-image build which bundles a bunch of possibly unrequired classes along with your native image, as per:

https://github.com/micronaut-projects/micronaut-core/blob/master/http-netty/src/main/resources/META-INF/native-image/io.micronaut/netty/native-image.properties

The simplest answer would be to make the netty native-image properties just `http` and add another maven artifact to add `https` as an opt-in if people require it. I don't think there is a way to make arguments conditional. 

The problem is there is no easy way to opt-out of how it currently works, but it is quite easy to opt-in.

**Comment by graemerocher** [comment]
This is just adding protocol support not enabling security services. That is a separate flag which is `--enable-security-services`. Without enabling the protocol support you cannot communicate with any third party services over https

**Comment by nhoughto** [comment]
As per https://github.com/oracle/graal/blob/master/substratevm/URL-PROTOCOLS.md
`https` protocol also enables security services.

```
Support for the https URL protocol relies on the Java Cryptography Architecture (JCA) framework. Thus when https is enabled --enable-all-security-services is set by default
```

Which then means you should ship SunEC JNI (for ECC ciphers), unless you workaround it via:
https://github.com/oracle/graal/issues/951

You are right tho `https` is required to call https services, I guess the question is do you want batteries included with no ability to opt-out or not? 🤔

**Comment by nhoughto** [comment]
Ah difference between `--enable-https` and `EnableURLProtocols=https`... so just enabling the protocol, but no full `https` which would enable security services.. cool :+1:
