### ISSUE TITLE
Using both Path Parameters and POJO based query parameters

### ISSUE THREAD

**Issue by juliuskrah** [micronaut-projects/micronaut-core#1858]
When creating a route template such as `Get status/{id}/sub-categories/{?pageable*,name}` always result in `404`

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

I have a controller method defined that takes both a Path Parameter and Query parameter

```java
@Get("status/{id}/sub-status/{?pageable*,name}")
public Flux<Status> findSubCategories(UUID id, 
	@Nullable Pageable pageable, //
	Optional<String> name) {
  //...
}
```

My pojo

```java
public class Pageable {
	private int page = 0;
	private int size = 20;
	private List<String> sort = List.of();	
        // Getters and Setters omitted for brevity
}
```

> NOTE: When I use `Get status/{id}/sub-status/` without the template query parameters, `name` is populated but not `pageable`

### Expected Behaviour

querying with `/status/0bf3bcd9-b285-49eb-9daa-cccb0aaba844/sub-status/?page=0&size=20&sort=name,DESC&name=Open` should match my Controller method

### Actual Behaviour

```json
{
    "_links": {
        "self": {
            "href": "/status/0bf3bcd9-b285-49eb-9daa-cccb0aaba844/sub-status/?page=0&size=20&sort=name,DESC&name=Open",
            "templated": false
        }
    },
    "message": "Page Not Found"
}
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.1.3
- **JDK Version:** 11

**Comment by jameskleeh** [comment]
You have an extra `/` in your template

`@Get("status/{id}/sub-status/{?pageable*,name}")` should be `@Get("status/{id}/sub-status{?pageable*,name}")`

**Comment by juliuskrah** [comment]
> `@Get("status/{id}/sub-status/{?pageable*,name}")` should be `@Get("status/{id}/sub-status{?pageable*,name}")`


@jameskleeh Thanks. This solved it for me
