### ISSUE TITLE
Allow consuming JSON streams without sending Accept: application/x-json-stream

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#1864]
While developing the Kubernetes module, there is an SSE-like API with a weird behaviour:

```
$ curl -i "http://localhost:8001/api/v1/watch/namespaces/default/configmaps?resourceVersion=0"
HTTP/1.1 200 OK
Content-Type: application/json
Date: Thu, 04 Jul 2019 13:38:51 GMT
Transfer-Encoding: chunked

{"type":"ADDED","object":{...}}
{"type":"ADDED","object":{...}}
{"type":"ADDED","object":{...}}
```

Note that curl is sending `Accept: */*` in this case.

In a declarative `@Client`, this design would cause to only process the first chunk.

If changing the client to send an `Accept` header of `application/x-json-stream`, the server rejects the request:

```
$ curl -i -H "Accept: application/x-json-stream" "http://localhost:8001/api/v1/watch/namespaces/default/configmaps"
HTTP/1.1 406 Not Acceptable
Content-Length: 182
Content-Type: application/json
Date: Thu, 04 Jul 2019 13:44:43 GMT

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "406: Not Acceptable",
  "reason": "NotAcceptable",
  "details": {},
  "code": 406
}
```

Ideally, there should be a way to consume this API without changing the `Accept` header.

**Comment by jameskleeh** [comment]
This issue really has nothing to do with the headers at all. It's a bug with the jackson processor that occurs when multiple objects are sent in a single chunk
