### ISSUE TITLE
Prometheus dependency causes crash on 1.1.4

### ISSUE THREAD

**Issue by ivyazmitinov** [micronaut-projects/micronaut-core#1867]
### Steps to Reproduce

1. Add micronaut-micrometer-registry-prometheus as dependency
2. Try to start the app

### Expected Behaviour

App is started, prometheus endpoint is avalilabled

### Actual Behaviour

Exception
```
Message: Multiple possible bean candidates found: [io.micrometer.core.instrument.composite.CompositeMeterRegistry, io.micrometer.prometheus.PrometheusMeterRegistry]
Path Taken: new ExecutorServiceMetricsBinder([Provider meterRegistryProvider])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [meterRegistryProvider] of class: io.micronaut.configuration.metrics.binder.executor.ExecutorServiceMetricsBinder

Message: Multiple possible bean candidates found: [io.micrometer.core.instrument.composite.CompositeMeterRegistry, io.micrometer.prometheus.PrometheusMeterRegistry]
```

It seems, that problem was introduced by https://github.com/micronaut-projects/micronaut-core/pull/1794,

as both beans defined as `@Primary`, see `io.micronaut.configuration.metrics.micrometer.MeterRegistryFactory#compositeMeterRegistry`, `io.micronaut.configuration.metrics.micrometer.prometheus.PrometheusMeterRegistryFactory#prometheusConfig`

### Environment Information

- **Micronaut Version:** 1.1.4

**Comment by graemerocher** [comment]
Do you have a hard coded version for the `micronaut-micrometer-registry-prometheus`? This was resolved in https://github.com/micronaut-projects/micronaut-micrometer/commit/f37d700143a6e6d2f13839c6328945768548b624

**Comment by ivyazmitinov** [comment]
Yep, haven't noticed `1.1.1` update. Works great, thanks.
