### ISSUE TITLE
StackOverflow during annotations processing in 1.1.4

### ISSUE THREAD

**Issue by Siroque** [micronaut-projects/micronaut-core#1868]
### Task List

- [N] Steps to reproduce provided
- [Y] Stacktrace (if present) provided
- [N] Example that reproduces the problem uploaded to Github
- [Y] Full description of the issue provided (see below)

### Steps to Reproduce

The project code base cannot be shared. But here are some infos:
[stacktrace.txt](https://github.com/micronaut-projects/micronaut-core/files/3363438/stacktrace.txt)
[debug.txt](https://github.com/micronaut-projects/micronaut-core/files/3363455/debug.txt)
[build.gradle.txt](https://github.com/micronaut-projects/micronaut-core/files/3363443/build.gradle.txt)

### Expected Behaviour

The annotation processing at he app start should be completed without an exception

### Actual Behaviour

StackOverflow exception

### Environment Information

- **Operating System**: MacOS 10.14.5
- **Micronaut Version:** 1.1.4
- **JDK Version:** 1.8
- **Project Language:** Kotlin 1.3.41

### Example Application
 -

**Comment by graemerocher** [comment]
I have not been able to reproduce this but I have pushed a potential fix. Please could you verify it works for you:

Add the snapshot repo:


```groovy
repositories {
    ...
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

And specifying the snapshot version as your BOM:

```groovy
dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:1.1.5.BUILD-SNAPSHOT'
    }
}
```

**Comment by Siroque** [comment]
The issue seems to be resolved now with that fix. I'm looking forward for the production release. Thanks a lot, Graeme! For your help and for such a great framework.
