### ISSUE TITLE
Feature request: `io.micronaut.http.client.HttpClient` to expose it's base URL

### ISSUE THREAD

**Issue by dcmoeller** [micronaut-projects/micronaut-core#1873]
As far as I understand the design of `io.micronaut.http.client.HttpClient` is is recommeded to get it injected in the class responsible for executing HTTP requests.

I've found no way to access the "base" URL used to create the `HttpClient` instance (e.g. via `RxHttpClient.create(baseURL)`) back from the injected instance.
In my current project this info is required (to execute requests I have to add a HTTP header, who's value is some detached JWS, which itself contains the complete target URL as one of the JWS headers).

I would appreciate some kind of getter method like

	HttpClient.getURL()

Or am I missing a way in the current API to get the info?

Thanks

Christian

**Comment by asarkar** [comment]
I think the issue is that the URL is not a property to be exposed on the client. One Client may make multiple calls, which URL would you expect to be returned? You may want to look at writing an interceptor for capturing that.

**Comment by dcmoeller** [comment]
I would expect to get the URL the `HttpClient` instance has been instantiated with. The multiple calls a "user"/"client" of this instance issues - as far as I know - are directed to URI paths "below" this "base" URL. Otherwise it would make no sense to me that creation of instances of `HttpClient` requires a mandatory URL ("base" URL as I have named it), e.g. via `RxHttpClient.create(@NotNull URL)`: Usually your component gets the `HttpClient` instance injected preconfigured with a (usually externally configurable) "base" URL, so this component does not know the URL; it has not to deal with lifecycle of this `HttpClient` instance, etc. Currently my component has to call `RxHttpClient.create(URL)` each time it's method is invoked (to get `HttpClient` closed properly after usage - try-with-resource). Only the "base" URL is injected to this component.

**Comment by graemerocher** [comment]
In general you should never be calling `RxHttpClient.create(..)`, that is what we have `@Client("..") @Inject RxHttpClient client` for.

Also what this does is just set the default to use in the case of relative paths being sent such as `client.retrieve('/foo')`. You can still pass absolute URLs to any client to make requests to other servers.

**Comment by dcmoeller** [comment]
OK, works as described :smile: Test-case injects an instance created like `RxHttpClient.create(new URL("http://foo.bar"))` along with the "real" base URL to the Class Under Test.

I think it would make sense to
- add an appropriate hint in documentation/JavaDoc (describing this "workaround" together with the role the injected URL is usually going to play) and/or
- provide a parameterless factory method
to clarify the usual usage scenario.

Thanks

**Comment by tibistibi** [comment]
Because I end up here often when I forgot how to get the url this is an option too:

````    
    @Value("${micronaut.http.services.occupancy.urls}")
    private String occupancyUrl;
````
