### ISSUE TITLE
client.toBlocking().exchange throws an exception instead of returning a HttpResponse

### ISSUE THREAD

**Issue by asarkar** [micronaut-projects/micronaut-core#1880]
`client.toBlocking().exchange` throws an exception instead of returning a `HttpResponse`; this is unexpected and defeats the purpose of `HttpResponse`. If an exception is desired, `retrieve` should be used instead.

[This](https://github.com/asarkar/txn-stats/blob/master/src/test/kotlin/org/asarkar/stats/StatsControllerTest.kt#L34) test demonstrates the issue.

v 1.2.0.RC1

**Comment by jameskleeh** [comment]
The exception being thrown is the intended behavior

**Comment by asarkar** [comment]
@jameskleeh what difference is there with `retrieve` then? Given that most of Micronaut behavior is based on Spring, this isn’t what `RestTemplate` does.

**Comment by jameskleeh** [comment]
Retrieve returns just the body, exchange returns the entire response. Micronaut is _inspired_ by Spring and other frameworks, but that doesn't mean everything does or should work the same

**Comment by asarkar** [comment]
Thanks for your response, I will continue this discussion in chat.

**Comment by graemerocher** [comment]
Personally I don't see any similarities between `RestTemplate` and Micronaut's HTTP client. Maybe it is more similar to `WebClient` which is the reactive one in Spring, but the HTTP client has nothing inspired by Spring
