### ISSUE TITLE
typo on multitenancy.svg in documentation

### ISSUE THREAD

**Issue by pekcheey** [micronaut-projects/micronaut-core#1881]
### Steps to Reproduce

1. Navigate to https://docs.micronaut.io/latest/img/multitenancy.svg in section **16 Multi-Tenancy**
2. notice that the Watson flow between the gateway and the catalogue read 
GET /books -H "tenantId:sherlock"

### Expected Behaviour

3. It should be
GET /books -H "tenantId:watson"

### Actual Behaviour

Tell us what happens instead

### Environment Information

- **Micronaut Version:** https://docs.micronaut.io/latest/guide/index.html#multitenancy

**Comment by pekcheey** [comment]
[multitenancy-fixed.svg.gz](https://github.com/micronaut-projects/micronaut-core/files/3377089/multitenancy-fixed.svg.gz)

here is a fixed version.

**Comment by graemerocher** [comment]
@sdelamo can you have a look?

**Comment by sdelamo** [comment]
@pekcheey thanks for reporting this issue.
