### ISSUE TITLE
HttpClient async exchange test makes no call

### ISSUE THREAD

**Issue by asarkar** [micronaut-projects/micronaut-core#1886]
Following up on Gitter [chat](https://gitter.im/micronautfw/questions?at=5d262cee98934d15a7316879)

`client.toBlocking().exchange` works, but when I convert that to `client.exchange(..).test().assert*.awaitTerminalEvent()`, no call is ever made.

See test [here](https://github.com/asarkar/txn-stats/blob/micronaut-issue-1886/src/test/kotlin/org/asarkar/stats/StatsControllerTest.kt).

**Comment by jameskleeh** [comment]
The assert statements on `TestSubscriber` don't wait for events/completion. You can look at the source code yourself: https://github.com/ReactiveX/RxJava/blob/58b0014d8830f299b063aefb789c77ebc733e16e/src/main/java/io/reactivex/observers/BaseTestConsumer.java#L169
