### ISSUE TITLE
Generated Kotlin apps missing enforcePlatform for kapt scope in Kotlin

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#1896]
Generating applications with the CLI in Kotlin is currently broken in 1.2.

The following is missing resulting in dependency resolve errors:

```
kapt enforcedPlatform("io.micronaut:micronaut-bom:$micronautVersion")
```

**Comment by jameskleeh** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/87026f10785e3dde6fa920b784b441c27e8ab1d2

Note that I changed `enforcedPlatform` to `platform` because `enforcedPlatform` overrides even explicit dependencies in the build file, not just transients.
