### ISSUE TITLE
micronaut and cloud foundry environment variables

### ISSUE THREAD

**Issue by aljacinto** [micronaut-projects/micronaut-core#1898]
### Steps to Reproduce

1. Create micronaut app
2. Create user provided service
3. Deploy app to pcf
3. Bind to app and restage

### Expected Behaviour

Environment variables from user provided service should be available as properties similar to springboot (specifically CloudFoundryVcapEnvironmentPostProcessor).  It should translate the json into flat properties.

### Actual Behaviour

User provided service is not available as properties and can't configure them as environment variables of jdbc connection for example.

### Environment Information

- **Operating System**: pcf
- **Micronaut Version:** 1.1.4
- **JDK Version:** 1.8

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by aljacinto** [comment]
Do you accept PR for enhancement?  I can work on this, let me know.

**Comment by jeffbrown** [comment]
@aljacinto Yes we welcome PRs of course.
