### ISSUE TITLE
Update gradlew version from 4.6 to 5.5

### ISSUE THREAD

**Issue by gonciarz** [micronaut-projects/micronaut-core#1907]
version: 1.2.0.RC2

I get a compilation error when trying to compile app using ./gradlew script.
4.6 version does not support Java12. Please update it to e.g. 5.5

./gradlew cli:fatJar

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '12'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by graemerocher** [comment]
Micronaut core is currently built with JDK 8 since that is the minimum version of Java we support

**Comment by gonciarz** [comment]
Sure, but it doesn't prevent you to support higher java version. You may run gradle 5.5 with java8 as well.

**Comment by jameskleeh** [comment]
Closing because what version of Gradle we choose to build Micronaut with is an internal decision
