### ISSUE TITLE
Transaction not available

### ISSUE THREAD

**Issue by alphawolf1988** [micronaut-projects/micronaut-core#1909]
I've a weird behaviour, while using transactions. If i annotate a method with `@Transactional(readOnly=true)` and enter another bean with annotation `@Transactional` i expect, that for the scope of this bean a new transaction is created, but nothing happens. The entity added to the entitymanager is not persisted nor an exception orccured.

Is this behavior expected?

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue

**Comment by jameskleeh** [comment]
Yes the behavior is expected. If the method being called calls other methods that write, then the annotation on the original method is incorrect. You can set the propagation in the annotation to require a new transaction if that is the desired behavior.

**Comment by alphawolf1988** [comment]
@jameskleeh i wouldn't agree with that. If i call a service interface (port) in the application layer, i don't need to know the concrete implementation (adapter) of the infrastructure layer. This would break encapsulation since it's inversion of control. On the other side the adapter defines how the service can fulfill it's purpose and if it requires a read-write-transaction for it's scope, it should be granted.
