### ISSUE TITLE
HTTP/2 Support

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-core#191]
Micronaut should natively support HTTP/2

**Comment by sureshg** [comment]
@jameskleeh I know this has been added as high priority in the roadmap. Is team in position to provide any rough estimate for HTTP/2 support in micronaut? I really want to use micronaut for one of our new projects, which has an HTTP/2 requirment.

**Comment by soberich** [comment]
@jameskleeh I join @sureshg 's quiestion.

**Comment by graemerocher** [comment]
will be a priority in Q3

**Comment by x0a1b** [comment]
Is there any progress on this or some kind of work around I can do to enable this at Netty level to at least run some benchmarks?

**Comment by sgammon** [comment]
@graemerocher if there is a way the community can help dev or test HTTP/2, let us know. we are eagerly awaiting this one before adopting Micronaut on a wider basis (right now we run an Nginx proxy in front of it to support HTTP/2)

**Comment by graemerocher** [comment]
In progress PR https://github.com/micronaut-projects/micronaut-core/pull/2910

**Comment by sandeep14-singh** [comment]
Hi @graemerocher ,
We wanted to use Micronaut with http2 support but i see that its support is right now just present in the pre - release (mile stone build). Can you throw some light on when it would be released as GA?  We were actually refraining to use Micronaut's mile stone build with http2 support for our software. So, if its released as GA or something, then we can definitely use it

**Comment by graemerocher** [comment]
Micronaut 2.0 will be out of a couple of months max

**Comment by sandeep14-singh** [comment]
Hi @graemerocher ,
Thanks for the quick reply.
Would really appreciate if you can provide any tentative date ?

**Comment by graemerocher** [comment]
Currently we are targetting 15th of June for 2.0 RC1 and depending how that RC process goes it will be a few weeks (no more than a month) after that

**Comment by sandeep14-singh** [comment]
Thanks a lot @graemerocher for the confirmation!
For us, it would mean that we can start our development with micronaut's milestone build for now and we would switch to Micronaut 2.0 when its released around June or July.
However, i just had one last question - i looked at the PR for http2 support : https://github.com/micronaut-projects/micronaut-core/pull/2910 .
It says that it has been run through https://github.com/summerwind/h2spec and  it passes and fails on the same tests that raw Netty does. 
My understanding after reading this is that Micronaut would fully support http2 -- to the same extent which raw Netty does, which means it would be fully production ready with respect to http2. I was just concerned why does the PR title says "Initial Support for HTTP/2" ? Are there any other http2 features which are not implemented in this PR and are planned for future ?

**Comment by graemerocher** [comment]
Yes it is compliant in the same way as Netty is compliant. With respects to future development there may be additional APIs we can add in the future to allow bidirectional streaming based on the HTTP/2 core, those are beyond the scope of this issue however.
