### ISSUE TITLE
Build on Eclipse

### ISSUE THREAD

**Issue by MihaiSeptD** [micronaut-projects/micronaut-core#1913]
Will be useful to provide additional details for developers regarding of build on Eclipse.

**Comment by jameskleeh** [comment]
The documentation has a section on configuring Eclipse. If you feel it can be improved please send a PR https://docs.micronaut.io/latest/guide/index.html#ideSetup. As this issue stands there isn't enough information to take any action on it so I'm going to close it. If you include specifics about what details you think are missing Ill re-open.
