### ISSUE TITLE
Low-level @Client configuration

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#1917]
In `1.2.0.RC2`.

Likewise in #1517 I'm now trying to use low level client:

```java
@Client(id = "my-service-id", path = "/my/service/path", configuration = MyHttpConfig.class) 
@Inject 
protected RxStreamingHttpClient client
```

For this client:

1. `path` is not considered, and the client is created always with "/" path
1. `configuration` is always of `ServiceHttpClientConfiguration` class, even if `MyHttpConfig` bean exists.

**Comment by jameskleeh** [comment]
If you have `http.services.my-service-id` defined in configuration then its intentional that the configuration member is ignored. You should use configuration to configure it. We have tests that verify the path works with the manual configuration so If you could upload a sample that reproduces the issue I'll take a look

**Comment by l0co** [comment]
> If you have `http.services.my-service-id` defined in configuration then its intentional that the configuration member is ignored. You should use configuration to configure it. 

It looks similar to #1517. In my opinion the defaults should be taken from the config, but if you overwrite these settings in annotation, you should use value from annotations. Otherwise, what is the annotation value for? Currently it only misleads.

> We have tests that verify the path works with the manual configuration so If you could upload a sample that reproduces the issue I'll take a look

Testing with https://jsonplaceholder.typicode.com/posts/1

In my opinion with this configuration:

```yaml
micronaut:
  http:
    services:
      jsonplaceholder:
        urls:
          - https://jsonplaceholder.typicode.com
```

and this implementation:

```java
@Singleton
public class PlaceholderClient {

	@Client(id = "jsonplaceholder", path = "/posts") @Inject protected HttpClient client;

	@EventListener
	protected void init(StartupEvent event) {
		try {
			System.out.println("CHECK ONE");
			System.out.println(client.toBlocking().retrieve(HttpRequest.GET("/1")));
		} catch (Exception e) {
			e.printStackTrace();
		}

		try {
			System.out.println("CHECK TWO");
			System.out.println(client.toBlocking().retrieve(HttpRequest.GET("/posts/1")));
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}
```

The first one should work and the second one doesn't, but is the opposite:

```
CHECK ONE
io.micronaut.http.client.exceptions.HttpClientResponseException: Not Found
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1789)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1729)
	at java.base/java.lang.Thread.run(Thread.java:835)

CHECK TWO
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
```

**Comment by jameskleeh** [comment]
> what is the annotation value for?

It's for clients that don't have manual configuration. It doesn't make sense to configure a client with configuration, and then specify a configuration class. The semantics of what and how the configuration gets merged would only lead to further confusion, so we will not be going down that road.

**Comment by l0co** [comment]
For me, as the user, this is confusing. From my perspective I just get an annotation which doesn't seem to work. So I report a bug :)

If you don't plan support it I'd at least think about blowing up everyhing after someone uses it in the way I did.

It can be reasonable to provide different config, for example to service which provides multiple endpoints and some of them call the external API or upload a file - I may want to increase timeouts for these ones.
