### ISSUE TITLE
Http Client that produces form fails in docker container

### ISSUE THREAD

**Issue by sascha-frinken** [micronaut-projects/micronaut-core#1922]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a declarative client that produces `application/x-www-form-urlencoded`
2. Call the client when running the app in a docker container

### Expected Behaviour

The client should send all form values as body

### Actual Behaviour

The client sends an empty body

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.2.0.RC2
- **JDK Version:** openjdk version "11.0.3"

### Example Application

https://github.com/safri-net/micronaut-form-docker-problem

The [README.md](https://github.com/safri-net/micronaut-form-docker-problem/blob/master/README.md) describes how to reproduce the error

**Comment by christoph-frick** [comment]
The problem is related to the used JDK.  Switching from `adoptopenjdk/openjdk11-openj9` to `adoptopenjdk/openjdk8` to run with no longer shows the problem.

**Comment by sascha-frinken** [comment]
I just hit another error when using views with thymeleaf. And it is

Using `adoptopenjdk/openjdk11-openj9:jdk-11.0.1.13-alpine-slim` make things work.

**Comment by graemerocher** [comment]
Believe this duplicates #2168 which contains a workaround
