### ISSUE TITLE
"localhost" is printed when no micronaut.server.host provided

### ISSUE THREAD

**Issue by ivyazmitinov** [micronaut-projects/micronaut-core#1924]
### Steps to Reproduce

1. Create and app wtih no micronaut.server.host 
2. Observe logs

### Expected Behaviour

"listening on `0.0.0.0:port`" or "`*:port`" is printed, as it what really is listened.

### Actual Behaviour

"listening on `localhost:port`" is printed, as `io.micronaut.http.server.netty.NettyHttpServer#getHost` resolves to `localhost` if not `host` provided, though really it listens to `*`

- **Micronaut Version:** 1.1.4

**Comment by jameskleeh** [comment]
What is the issue with it saying localhost? The idea is that it is a clickable link if ran using an IDE. `*:8080` would not be a link. We could use `0.0.0.0`, but what is the point?

**Comment by ivyazmitinov** [comment]
It's confusing with "localhost", since you could naturally assume that without host provided micronaut will default to localhost and, for example, deploy it on production that way.

**Comment by ivyazmitinov** [comment]
Also, with REST api it is a pretty rare use-case to follow the raw link: usually a service is accesed via Swagger/another REST client.

**Comment by jameskleeh** [comment]
I disagree that its a rare use case. It exists because its very useful while developing the application, especially those applications that have a view layer.

**Comment by ivyazmitinov** [comment]
Well, it exists anyway, so `0.0.0.0` will be perfect, since it is clickable and represents what really listened.

**Comment by jameskleeh** [comment]
@graemerocher Can you chime in here whether you think this should be changed?
