### ISSUE TITLE
Compilation error when including class annotated with @Value.Immutable

### ISSUE THREAD

**Issue by freddieFishCake** [micronaut-projects/micronaut-core#1929]
### Steps to Reproduce

1. Generate a Java project using mn and maven build
mn create-app test --build maven
2. Add a class annotated with @Value.Immutable, for example:
`package test;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.immutables.value.Value;

@Value.Immutable
@JsonSerialize(as = ImmutableCapability.class)
@JsonDeserialize(as = ImmutableCapability.class)
public interface Capability {

  String getRes();

  String getType();

  @JsonProperty("TimeSteps")
  Timesteps getTimesteps();
}`

3. Add maven dependency for Immutables and extend the annotationProcessorPaths section of maven-compiler-plugin:
`            <annotationProcessorPaths>
                <path>
                    <groupId>org.immutables</groupId>
                    <artifactId>value</artifactId>
                    <version>2.7.4</version>
                </path>
                <path>
                    <groupId>io.micronaut</groupId>
                    <artifactId>micronaut-inject-java</artifactId>
                    <version>${micronaut.version}</version>
                  </path>
                  <path>
                    <groupId>io.micronaut</groupId>
                    <artifactId>micronaut-validation</artifactId>
                    <version>${micronaut.version}</version>
                  </path>
            </annotationProcessorPaths>`

4. build the project and see the error:
-------------------------------------------------------------
COMPILATION ERROR : 
-------------------------------------------------------------
Error occurred writing configuration metadata: Output stream or writer has already been opened.

5. Note that the Immutables annotation processor had created the generated sources for the immutable class.

### Expected Behaviour

Build without failing

### Actual Behaviour
-------------------------------------------------------------
COMPILATION ERROR : 
-------------------------------------------------------------
Error occurred writing configuration metadata: Output stream or writer has already been opened.

### Environment Information

- **Operating System**:  Windows [Version 10.0.17134.885]
- **Micronaut Version**: 1.1.4
- **JDK Version:** 1.8.0_202

### Example Application

Trivial

**Comment by graemerocher** [comment]
Already fixed as part of #1711
