### ISSUE TITLE
Kotlin Annotation processing not working in IntelliJ (although enabled)

### ISSUE THREAD

**Issue by larsduelfer** [micronaut-projects/micronaut-core#1936]
Hi there, 

I am trying to get the intellij build working (without delegating to gradle). Although annotation processing is enabled in intellij and although there is not other annotation processor configured (like discussed here in other issues) I cannot get it running. Is this supposed to work at all? Various colleagues also working with micronaut and intellij also said that it only works for them when delegating to gradle. 

I use IntelliJ 2019.1.3 (Ultimate Edition).

Regards, Lars

**Comment by graemerocher** [comment]
please provide an example project that reproduces the issue

**Comment by larsduelfer** [comment]
Here you can find a generated micronaut app with a hello controller and an IntelliJ project checked in: https://github.com/larsduelfer/micronaut-intellij

If you do not delegate the build to gradle in intellij, the hello conroller is not found (due to the not working annotation processors). As soon as you delegate the build to gradle, it works.

**Comment by larsduelfer** [comment]
Any news on this?

**Comment by graemerocher** [comment]
You need to check the option to enable annotation processing. I do this all the time and have not encountered an issue

**Comment by larsduelfer** [comment]
The checkbox in IntelliJ for that is activated, but still not working.

**Comment by graemerocher** [comment]
Ah this is Kotlin. See https://youtrack.jetbrains.com/issue/KT-15040

The issue has many votes, but it is up to the JetBrains/IntelliJ people to fix this. It is actually pretty mind blowing that they haven't done anything about it yet considering how common annotation processors are

**Comment by jameskleeh** [comment]
I don't see any progress on the issue so I'm going to close this

**Comment by jtlapp** [comment]
There is a problem with the Micronaut documentation here: it falsely says that enabling annotation solves the problem. It does not. It would be nice for the documentation to say that it's awaiting resolution of the above Kapt bug. Given that the bug has been documented for 8 years, you might consider simply saying that you must rebuild annotations from the command line.

**Comment by graemerocher** [comment]
the original documentation relates to Java not Kotlin. KAPT itself is now deprecated and replaced by KSP which will soon be replaced by KSP2. It is very hard to keep up with all the changes in the Kotlin world.

**Comment by jtlapp** [comment]
Oh. That's understandable. My apologies for the tone of exasperation.
