### ISSUE TITLE
PropertySourcePropertyResolver incorectly parses properties

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#1942]
The problem occurs when property has multiple indexes:

`micronaut.security.intercept-url-map[0].access[0]`

Problem is probably related to the code:
```
int i = resolvedProperty.indexOf('[');
if (i > -1 && resolvedProperty.endsWith("]")
```

In our case problem occurs with the usage of Spring Cloud Config, but I can imagine simple `.properties` will fail and ENV variables, test props etc.

**Comment by graemerocher** [comment]
Thanks for the PR!
