### ISSUE TITLE
Provide a way to fetch Server URL even over a proxy

### ISSUE THREAD

**Issue by juliuskrah** [micronaut-projects/micronaut-core#1955]
It will be nice to extract proxy URL from request to build another URL. 

When a micronaut application is sitting behind a proxy or API gateway, I want to be able to extract the scheme, host, port and path of the proxy.

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

Let's say I have a micronaut app running on `http://localhost:8080` when I call:

```java
var serverAddress = HttpRequest#getServerAddress(); // http://localhost:8080
```

Now I put an API gateway infront of the micronaut app:

```properties
url=http://api.example.com # Assuming proper proxy headers are configured
path=/api/{segment}
```

should produce:

```java
var serverAddressGateway = HttpRequest#getServerAddress(); // http://api/example.com/api
```

Now when I put the micronaut application behind an nginx proxy `https://example.com`:

```java
var serverAddressProxy = HttpRequest#getServerAddress(); // https://example.com
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.1.4
- **JDK Version:** 11

**Comment by jameskleeh** [comment]
We already have support for this. See the `HttpHostResolver` bean

**Comment by jameskleeh** [comment]
Also see https://docs.micronaut.io/snapshot/guide/index.html#hostResolution
