### ISSUE TITLE
Support retrieving all parts from multipart/form-data request

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#1957]
As discussed with @jameskleeh on gitter the `io.micronaut.http.HttpRequest` currently does not support retrieving the multipart parts.

E.g. in a servlet environment this can be done via [HttpServletRequest.getParts()](https://docs.oracle.com/javaee/7/api/javax/servlet/http/HttpServletRequest.html#getParts--)

Another point to think about is what object type to expose via the `HttpRequest` as the parts.
Micronaut has a `PartData` class but it does not contain the part name and file name.
There is also a `FileUpload` but that does not provide the content (inputstream or bytes) itself.
`CompletedFileUpload` does make more sense then, as it implements both `PartData` and `FileUpload`.

Some background for my use case is I would like to support the [GraphQL multipart request specification](https://github.com/jaydenseric/graphql-multipart-request-spec) which should accept an x number of parts with arbitrary names we don't know upfront, like:

```
--------------------------ec62457de6331cad
Content-Disposition: form-data; name="operations"

{ "query": "mutation($files: [Upload!]!) { multipleUpload(files: $files) { id } }", "variables": { "files": [null, null] } }
--------------------------ec62457de6331cad
Content-Disposition: form-data; name="map"

{ "0": ["variables.files.0"], "1": ["variables.files.1"] }
--------------------------ec62457de6331cad
Content-Disposition: form-data; name="0"; filename="b.txt"
Content-Type: text/plain

Bravo file content.

--------------------------ec62457de6331cad
Content-Disposition: form-data; name="1"; filename="c.txt"
Content-Type: text/plain

Charlie file content.

--------------------------ec62457de6331cad--
```

**Comment by jameskleeh** [comment]
@marceloverdijk Current progress is on this branch https://github.com/micronaut-projects/micronaut-core/tree/multipart-body. I have done no testing but it may work if you want to give it a spin. A `@Body MultipartBody` can be used as an argument. The argument is a publisher of type `Part` that emits each part as it completes.
