### ISSUE TITLE
NullPointerException during annotation processing in 1.2.0.RC2 & Eclipse

### ISSUE THREAD

**Issue by typhoon2k** [micronaut-projects/micronaut-core#1961]
### Task List

- [N] Steps to reproduce provided
- [Y] Stacktrace (if present) provided
- [N] Example that reproduces the problem uploaded to Github
- [Y] Full description of the issue provided (see below)

### Steps to Reproduce

We have to migrate our project from 1.1.0 to 1.2.0 due to new features and tried version 1.2.0.RC2.
After version switch Eclipse (tried with Eclipse 4.11 and 4.12) throws errors when generating bean classes.

![screenshot](https://user-images.githubusercontent.com/2978290/62281497-8e5a9900-b456-11e9-96e4-53df08cbb49a.png)
[TypeElementVisitorProcessor_stacktrace.txt](https://github.com/micronaut-projects/micronaut-core/files/3455887/TypeElementVisitorProcessor_stacktrace.txt)
[BeanDefinitionInjectProcessor_stacktrace.txt](https://github.com/micronaut-projects/micronaut-core/files/3455888/BeanDefinitionInjectProcessor_stacktrace.txt)

Unfortunately I can't share project code and the error doesn't give me any hints on which annotation is causing NPE (we are using many different micronaut annotation here) to narrow down this problem.

### Expected Behaviour

Bean classes should be generated successfully.

### Actual Behaviour

2 exceptions are thrown.

### Environment Information

- **Operating System**: WIN10
- **Micronaut Version:** 1.2.0.RC1 and 1.2.0.RC2
- **JDK Version:** 1.8

### Example Application

- N/A

**Comment by graemerocher** [comment]
Seems to be a bug in Eclipse JDT. It isn't coming from Micronaut code

**Comment by typhoon2k** [comment]
I will try to debug this.

Just some observations:
1. all works fine with micronaut 1.1.0
2. all works fine under maven
3. all works fine if I remove micronaut-validation from annotation processor path (i.e. only micronaut-inject-java is used)

My guess is that some change in validation module (or inject-java) in 1.2.0 lead to this problem...

**Comment by graemerocher** [comment]
Agreed it is that module, but the APIs being used are standard annotation processing APIs. We have had this situation before with Ecilpse and had to report an issue to https://bugs.eclipse.org/bugs/

**Comment by typhoon2k** [comment]
I found similar stacktrace in https://bugs.eclipse.org/bugs/show_bug.cgi?id=433804.

**Comment by typhoon2k** [comment]
@graemerocher , it seems that NPEs disappear as soon as I remove/comment out usage of io.micronaut.test.annotation.* annotations in our unit test code (we use MicronautTest and MockBean).
Do you have any ideas, how it is related?

**Comment by typhoon2k** [comment]
JFYI (if someone will face similar problem), problem in getRepeatableNameForType happens because directory listing is requested from classpath location, on which cleanup has already been called (directoryCache is nullified, therefore NPE).

As a simple workaround for this problem - uncheck "Clean projects" on project update/refresh screen:
![screenshot](https://user-images.githubusercontent.com/2978290/63925510-e7681d80-ca52-11e9-9d5a-8098c79d2e77.png)

Will close this issue for now as this seems as a problem in Eclipse IDE.
