### ISSUE TITLE
BOM does not contain io.micronaut.graphql:micronaut-graphql

### ISSUE THREAD

**Issue by timurstrekalov** [micronaut-projects/micronaut-core#1963]
### Long story short
micronaut-bom defines a non-existent artifact "io.micronaut.configuration:micronaut-graphql"

### Steps to Reproduce

1. Import micronaut-bom
2. Add a dependency on io.micronaut.graphql:micronaut-graphql

### Expected Behaviour

Dependency gets resolved

### Actual Behaviour

Dependency doesn't get resolved

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.2.0.RC2
- **JDK Version:** 12.0.1

**Comment by jameskleeh** [comment]
The graphql configuration is in the BOM, however it appears the group id was wrong

**Comment by jameskleeh** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/9212dbc10a60291e1b33f9947b696505dc622d5e
