### ISSUE TITLE
Integrate with Micronaut Data

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#1967]
This is a high level issue to ensure that for Micronaut 1.3 we integrate with Micronaut Data in terms of:

* The BOM
* The CLI and code gen
* Possible testing extensions
* Anything else we can think of

**Comment by benrhine** [comment]
Do we have any possible testing extensions or other items that have come to mind on this?

**Comment by graemerocher** [comment]
I guess we could generate a crud repository and associated crud test
