### ISSUE TITLE
Request matching 2 routes when using different consumes configurations

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#1971]
I'm having a controller with 2 post methods with the following signature:

```
    @Post(consumes = ALL, produces = APPLICATION_JSON, single = true)
    public Publisher<String> post(
            @Nullable @QueryValue("query") String query,
            @Nullable @QueryValue("operationName") String operationName,
            @Nullable @QueryValue("variables") String variables,
            @Nullable @Body String body,
            HttpRequest httpRequest) {
```

```
    @Post(consumes = MULTIPART_FORM_DATA, produces = APPLICATION_JSON, single = true)
    public Publisher<String> post(
            @Body MultipartBody body,
            HttpRequest httpRequest) {
```

The first post method should match requests with content type `application/json`, `application/graphql` and also if no explicit content type is set. Hence the consumes `MediaType.ALL`.

The second post method is meant to match the `multipart/form-data` content type and must be able to get multipart parts. Note this is work in progress: https://github.com/micronaut-projects/micronaut-core/tree/multipart-body

However, when I make a request without specifying the request content type I get the following error:

`io.micronaut.http.client.exceptions.HttpClientResponseException: More than 1 route matched the incoming request. The following routes matched /graphql/: POST - /graphql, POST - /graphql
`

Note the client I have looks like:

```
    @Client("/graphql")
    static interface GraphQLClient {

        @Get("{?query,operationName,variables}")
        GraphQLResponseBody get(@QueryValue String query, @QueryValue @Nullable String operationName, @QueryValue @Nullable String variables)

        @Post(value = "{?query,operationName,variables}")
        GraphQLResponseBody post(@QueryValue String query, @QueryValue @Nullable String operationName, @QueryValue @Nullable String variables)

        @Post(produces = APPLICATION_JSON)
        GraphQLResponseBody post(@Body GraphQLRequestBody body)

        @Post(produces = MULTIPART_FORM_DATA)
        GraphQLResponseBody post(@Body MultipartBody body)

        @Post(produces = APPLICATION_GRAPHQL)
        GraphQLResponseBody post(@Body String body)
    }
```

and the method used in this particular case is:

```
        @Post(value = "{?query,operationName,variables}")
        GraphQLResponseBody post(@QueryValue String query, @QueryValue @Nullable String operationName, @QueryValue @Nullable String variables)
```

### Environment Information

- **Operating System**: OSX
- **Micronaut Version:** 1.2.0.BUILD-SNAPSHOT (built from https://github.com/micronaut-projects/micronaut-core/tree/multipart-body)
- **JDK Version:** 8

**Comment by marceloverdijk** [comment]
Note the issue can be reproduced using https://github.com/micronaut-projects/micronaut-graphql/tree/multipart (it requires a snapshot of https://github.com/micronaut-projects/micronaut-core/tree/multipart-body though..). E.g. running this test: https://github.com/micronaut-projects/micronaut-graphql/blob/multipart/graphql/src/test/groovy/io/micronaut/configuration/graphql/GraphQLControllerSpec.groovy#L129-L143

**Comment by jameskleeh** [comment]
This can be lumped in with https://github.com/micronaut-projects/micronaut-core/issues/1303

**Comment by marceloverdijk** [comment]
As #1303 is targeted for Micronaut `2.0.0`, does it mean #1971 will also be moved to `2.0.0`?

**Comment by jameskleeh** [comment]
@marceloverdijk It requires some new methods added to get more data about the routes from the route match, so I'm not totally sure

**Comment by marceloverdijk** [comment]
OK understood. I'm subscribed to the ticket so will see how it goes.

**Comment by marceloverdijk** [comment]
Thx @jameskleeh .

Just asking, would it work to have a controller method having both a String body and multipart body like:

```
public Publisher<String> post(
        @Nullable @Body String body, 
        @Nullable @Body MultipartBody multipartBody) {
    ..
}
```

I guess not, but I'm looking at workarounds for https://github.com/micronaut-projects/micronaut-core/issues/1971 :-)
