### ISSUE TITLE
1.2.0 doesn't install native-image

### ISSUE THREAD

**Issue by sneakythr0ws** [micronaut-projects/micronaut-core#1994]
Hi!
I just updated MN to 1.2.0.
`mn create-app gn --features graal-native-image` generates Dockerfile 
```FROM oracle/graalvm-ce:1.0.0-rc15 as graalvm
COPY . /home/app/gn
WORKDIR /home/app/gn
RUN native-image --no-server -cp build/libs/gn-*-all.jar

FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/app/gn .
ENTRYPOINT ["./gn"]
```

with `1.0.0-rc15` and without `RUN gu install native-image`
`./docker-build.sh` fails(

**Comment by razrcallahan** [comment]
How did you solve the issue? I am having similar issue right now.

**Comment by sneakythr0ws** [comment]
use 1.2.1

**Comment by ilopmar** [comment]
Instead of using `1.0.0-rc15` you can use `FROM oracle/graalvm-ce:19.2.0 as graalvm` with Micronaut 1.2.x.
