### ISSUE TITLE
GET and HEAD route conflict

### ISSUE THREAD

**Issue by brandonlamb** [micronaut-projects/micronaut-core#2008]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a controller class
2. Create two methods e.g. headFoo(), getFoo()
3. Add `@Head("/foo")` and `@Get("/foo")`

### Expected Behaviour

HEAD requests should be routed to the defined method annotated with `@Head`, while GET requests should be routed to the `@Get` method.

### Actual Behaviour

400 errors on HEAD request, successful routing on GET. Simply changing the path on either the `@Head` or `@Get` annotation makes both work as expected.

My guess, some bug in figuring out explicit head declarations when there is a get listening on the same path.

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 1.2.0
- **JDK Version:** 1.8.212

### Example Application

```kotlin
@Controller
class RestController {
  @Head("/foo")
  headFoo() = "test from head"

  @Get("/foo")
  getFoo() = "test from get"
}
```

**Comment by jameskleeh** [comment]
Perhaps we should add a member to the `Get` annotation to allow for disabling of the `HEAD` route

**Comment by brandonlamb** [comment]
The feature totally makes sense, however our use-case is that it is a heavy database hit to fetch the entire data object, just to tell a consumer the resource exists. We have an optimized head method that just hits elasticsearch to find the primary key, being a difference between 100ms or 1+ second.

In case anyone wonders "why would you need that" hehe

**Comment by jameskleeh** [comment]
@brandonlamb You can also just take in the request and check the http method

**Comment by KangoV** [comment]
A pain that this is still happening. I'm implementing the IETF RPP protocol and HEAD and GET with the same URI is a firm requirement ("domainNames/{id}/availability").
