### ISSUE TITLE
HttpStatusException message is ignored

### ISSUE THREAD

**Issue by schrek1** [micronaut-projects/micronaut-core#2011]
When I throw HttpStatusException from controller:
`throw new HttpStatusException(HttpStatus.BAD_REQUEST, ex.getMessage());`

Controller completely ignore message in exception, and it returns:
`{
  "code": "bad_request",
  "message": "Request was malformed or missing important things",
  "_embedded": {},
  "_links": {
    "self": {
      "href": "/v1/user/aaa/info",
      "templated": false,
      "profile": null,
      "deprecation": null,
      "title": null,
      "hreflang": null,
      "type": null,
      "name": null
    }
  }
}`

It is necessary feature, because if I declare method throws it works, but I'm not able change response code...

**Comment by jameskleeh** [comment]
Please follow the issue template and upload an example project that reproduces the issue

**Comment by jameskleeh** [comment]
Closing due to a lack of feedback. Will re-open if more information is provided
