### ISSUE TITLE
@Status is ignored on exception handlers

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#2029]
In a Micronaut 1.2.0 application that renders HTML, we have this controller action: 
```java
@Post(value = "/update", consumes = MediaType.APPLICATION_FORM_URLENCODED)
public HttpResponse update(@Valid @Body UpdateApplicationForm form)
``` 
And if there is an error validating the `form` POJO we handle it in: 

```java
@Produces(MediaType.TEXT_HTML)
@View(EditApplicationController.VIEW)
@Error(exception = ConstraintViolationException.class)
public Map<String, Object> onUpdateFailed(HttpRequest<?> request, ConstraintViolationException ex) {
    Map<String, Object> model = new HashMap<>();
    ...
    ...
    return model;
}
```

The issue I see is that the HttpStatus for the responde is set to 500. The page is rendered correctly but with the status code 500 instead of 200. I also tried annotating both the controller action and the error hanlder methods with `@Status(HttpStatus.OK)` but I still get a 500.

This is happening because of this: https://github.com/micronaut-projects/micronaut-core/blob/master/http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java#L661.

As a workaround I change the method signature of `onUpdateFailed` method to `HttpResponse<Map<String, Object>>` I can do `return HttpResponse.ok(model);` and I get the 200.

I was expecting that using `@Status` should work.

**Comment by ilopmar** [comment]
@jameskleeh thanks for the fix. Is it possible to backport it to `1.2.x`?

**Comment by jameskleeh** [comment]
@ilopmar No - this is an improvement and not a bug fix

**Comment by ilopmar** [comment]
Well... that can be arguable because annotating with `@Status` doesn't work, but as there is an easy workaround I can live with it :+1: 

Thanks again :)

**Comment by jameskleeh** [comment]
@ilopmar If you can point to somewhere in the documentation that says it should, then I would agree

**Comment by ilopmar** [comment]
No worries, as I said I can live with the workaround :)

**Comment by alvarosanchez** [comment]
> @ilopmar If you can point to somewhere in the documentation that says it should, then I would agree

I found this:

![image](https://user-images.githubusercontent.com/153880/63442985-4bc42500-c434-11e9-978a-bab1233438da.png)
