### ISSUE TITLE
Error response with custom object is not testable

### ISSUE THREAD

**Issue by JacobAae** [micronaut-projects/micronaut-core#2030]
I have this 404 handler, responding with an MyError object

```
@Error(status = HttpStatus.NOT_FOUND, global = true)
    HttpResponse<MyError> notFound(HttpRequest request) {
        log.trace("Page not found: ${request.uri}" )
        HttpResponse.notFound().body(
                new MyError(
                        myErrorCode: 'Some error code',
                        myErrorMessage: 'Some message'
                )
        )
}
```
Running the application and using curl, it works like a charm, but trying to write a test for it fails:

```
    @AutoCleanup @Inject @Client(value = "/", errorType = MyError)
    RxHttpClient client

    void "test 404 status"() {
        when:
        client.toBlocking().exchange("/notFound", MyError)

        then:
        HttpClientResponseException exception = thrown(HttpClientResponseException)
        exception.response.status == HttpStatus.NOT_FOUND

        Optional<MyError> body = exception.response.getBody(MyError)
        body.present
        body.get().myErrorMessage == 'Some message'
        body.get().myErrorCode == 'Some error code'
    }
```

The body.present fails, as DefaultHttpClient attempt to parse body to JsonError, not the specified MyError class. Run gradlew check and see log output in test report. 

### Steps to Reproduce

1. Create a controller method, with an @Error(status = HttpStatus.NOT_FOUND, global = true) annotation, that has a custom object in the body response
2. Create a test that will test the response retrieving the thrown(HttpClientResponseException)
3. See that the body is not available as Jackson fails with "Error decoding JSON stream for type [class io.micronaut.http.hateoas.JsonError]"

### Expected Behaviour

I would expect to be able to retrieve the custom body response, that is not JsonError

### Actual Behaviour

No body object is available, as internal parsing fails in DefaultHttpClient

### Environment Information

- **Operating System**: Ubuntu Linux
- **Micronaut Version:** 1.2,0
- **JDK Version:** Eclipse OpenJ9 VM (build openj9-0.14.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190417_286 (JIT enabled, AOT enabled)

### Example Application

https://github.com/JacobAae/micronaut-custom-404-response-test

**Comment by jameskleeh** [comment]
`exchange(HttpRequest<I> request, Argument<O> bodyType, Argument<E> errorType)`

The second argument to the exchange method you're using is the body type for a successful request. You would need to use the above to specify the body type if an error occurs.

**Comment by JacobAae** [comment]
Thanks, I had missed that version of exchange.
