### ISSUE TITLE
More header annotation on method declarative http client

### ISSUE THREAD

**Issue by schrek1** [micronaut-projects/micronaut-core#2033]
I can't use more headers on method of declarative http client, only single works. When I wrap them into Headers it's applicable only on interface. Is it possible extend Headers annotation to more target than only ElementType.TYPE?

**Comment by jameskleeh** [comment]
So just FYI if we were to allow this if you had multiple headers on the class and method it would not handle overriding values

**Comment by schrek1** [comment]
I know that can be problem, but it's enable now too, but only with only one header on method....
