### ISSUE TITLE
Increase sensitivity of property resolving

### ISSUE THREAD

**Issue by schrek1** [micronaut-projects/micronaut-core#2034]
When I use placeholder for in  ${} or property, I must use property name only lowercase and kebab-case. If I use capitalized or camel case, property path isn't resolved. This is very prone to error. Please improve it as good is in Spring, it will be great.

**Comment by jameskleeh** [comment]
It is not prone to error because a compilation error should occur if the property is not in the correct format

**Comment by schrek1** [comment]
I don't agree because of declarative http client it fails on runtime, if it fall down on compile time, it's ok, but this in runtime can be tricky...

**Comment by jameskleeh** [comment]
If you can provide an example of the property not being found as invalid at
compile time, please create an issue
