### ISSUE TITLE
Basic Auth Support in Declarative Client

### ISSUE THREAD

**Issue by debuglevel** [micronaut-projects/micronaut-core#2035]
HttpRequest already has a very convenient way to provide a Basic authentication:
```Kotlin
val httpRequest = HttpRequest
            .GET<String>(retrieveUri)
            .basicAuth("myUser", "secretPassword")
```

To provide a Basic Auth HTTP-Header to a @Client, this is a little bit cumbersome
```Kotlin
@Get("/VIPs")
fun getVIPs(@Header authorization: String): Set<PersonDTO>
```
```Kotlin
val encodedCredentials = Base64.getEncoder().encodeToString("myUser:secretPassword".byteInputStream().readBytes())
val basicAuthenticationHeader = "Basic $encodedCredentials"
val retrievedPersons = personClient.getVIPs(basicAuthenticationHeader)
```

Maybe it is possible to provide somewhere a similar `basicAuth(user, pass)` function to abstract the Base64 encoding and String prefixing stuff.

### Environment Information

- **Micronaut Version:** 1.2.0

**Comment by jameskleeh** [comment]
This would be a matter of creating a POJO called `BasicAuth` or something like that and adding support in the `HttpClientIntroductionAdivce` to look for that type and handle it appropriately. Should be simple to do, PR is welcome

**Comment by ashishkujoy** [comment]
How about having something called AuthorizationHeader with a method to expose header value in <type> <credentials> string format, so when ever an instance of authorization header (BaseAuth, OAuth1, OAuth2 etc) is passed to Client call the HttpClientIntroductionAdivce will automatically add AuthorizationHeader in request with value of passed header instance.

**Comment by jameskleeh** [comment]
@ashishkujoy You can already do that with `@Header("Authorization") String authHeader`. The benefit of the POJO would to be automatically encode/construct the header for you automatically.

**Comment by ashishkujoy** [comment]
> @ashishkujoy You can already do that with `@Header("Authorization") String authHeader`. The benefit of the POJO would to be automatically encode/construct the header for you automatically.

Yes i knew that, but it will be better if i even dont need to specify @Header ("Authorization") any type of authorization header will be taken care by HttpClientIntroductionAdivce. Based on the type of parameter(in this case Authorization Header)  advice should automatically put encoded value of that in request header.

Something like this

```kotlin
@Client
interface OrderClient {
    @Get("/v1/orders/orderId")
    fun getOrderUsingBasicAuth(orderId: String, basicAuth: BasicAuth)

    @Get("/v2/orders/orderId")
    fun getOrderUsingOAuth2(orderId: String, oauth2: OAuth2)
}
```
Now in this case i don't even need to specify @Header
