### ISSUE TITLE
illegal reflective access using the CLI

### ISSUE THREAD

**Issue by tgoeke** [micronaut-projects/micronaut-core#2038]
### Steps to Reproduce

1. Install a fresh copy of version 1.2 on Mac OS 10.14.6 with JDK 11.0.4: sdk install micronaut
2. Run the version command: mn --version
3. Get warnings: WARNING: An illegal reflective access operation has occurred

### Expected Behaviour
I should only see:
| Micronaut Version: 1.2.0
| JVM Version: 11.0.4

### Actual Behaviour

mn --version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/Users/tgoeke/.sdkman/candidates/micronaut/1.2.0/cli-1.2.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
| Micronaut Version: 1.2.0
| JVM Version: 11.0.4

### Environment Information

- **Operating System**: Mac OS 10.14.6
- **Micronaut Version:** 1.2.0
- **JDK Version:** 11.0.4

### Example Application

NA

**Comment by chrisingenhaag** [comment]
Do you use a client certificate protected maven repo? Or do you have custom MAVEN_OPTS for accessing your repos in settings.xml from maven? Then try to pass them to MN_OPTS.

**Comment by cesdperez** [comment]
I have this same issue and I don't use any client certificate protected maven repo or any custom MAVEN_OPTS.
- OS: Linux 5.1.21-1-MANJARO
- installation method: `sdk i micronaut`
- sdk version
```
SDKMAN 5.7.3+337
```
- java --version
```
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```
- mn --version
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/checho/.sdkman/candidates/micronaut/1.2.2/cli-1.2.2.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
| Micronaut Version: 1.2.2
| JVM Version: 11.0.4
```

**Comment by luiszimmermann** [comment]
This is happening to me also in Java 11, in Java 8 this warning don't appear. Found this bug in Groovy JIRA: https://issues.apache.org/jira/browse/GROOVY-8843


```
sdk version                                                                                                                                                           
SDKMAN 5.7.3+337
```

```
java --version                                                                                                                                                        
openjdk 11.0.4 2019-07-16 LTS
OpenJDK Runtime Environment Corretto-11.0.4.11.1 (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.4.11.1 (build 11.0.4+11-LTS, mixed mode)
```

```
mn --version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/<user>/.sdkman/candidates/micronaut/1.2.4/cli-1.2.4.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
| Micronaut Version: 1.2.4
| JVM Version: 11.0.4
```

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/bf62e0e591b58f25ddc912942506cf3e69c12757

**Comment by nsidhaye** [comment]
@graemerocher : Is it part of 1.3.4 ? 

```
>mn --version
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/C:/opt/micronaut-1.3.4/cli-1.3.4.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
| Micronaut Version: 1.3.4
| JVM Version: 11.0.4
```
