### ISSUE TITLE
Pulsar Messaging Application Support

### ISSUE THREAD

**Issue by JamieCressey** [micronaut-projects/micronaut-core#2041]
It would be great if Micronaut natively supported creating [Apache Pulsar](https://pulsar.apache.org/) message/stream driven Microservices.

Similar to Kafka in the data streaming sense, but also crosses over with RabbitMQ in terms of far better queuing support.

**Comment by MaitreyaBuddha** [comment]
👍  This would be great.

**Comment by harissecic** [comment]
Started playing with it on [my profile](https://github.com/harissecic/micronaut-pulsar) not sure will it help at all, is there any kind of good enough code here to continue on work.

**Comment by graemerocher** [comment]
@harissecic nice!

**Comment by alvarosanchez** [comment]
@harissecic very nice indeed!

We have a [GitHub template repository](https://github.com/micronaut-projects/micronaut-project-template) that you could use to get our build, documentation and publishing standards. 

If it gets compliant with that, and gets into a state that a milestone could be released, we can consider hosting it in the `micronaut-projects` organization. That way, you could ask for reviews so that we can provide feedback about the Micronaut-specific parts.

**Comment by harissecic** [comment]
> @harissecic very nice indeed!
> 
> We have a [GitHub template repository](https://github.com/micronaut-projects/micronaut-project-template) that you could use to get our build, documentation and publishing standards.
> 
> If it gets compliant with that, and gets into a state that a milestone could be released, we can consider hosting it in the `micronaut-projects` organization. That way, you could ask for reviews so that we can provide feedback about the Micronaut-specific parts.

Thanks, I'll try out template as I started with Kafka integration and changed stuff which I realised is bad now

**Comment by harissecic** [comment]
Hello again, I've managed to create really basic consumers and producers for this. However I didn't get any feedback on code nor questions at gitter so I'm asking here if someone can take a look and have feature suggestion or complaint. I have an idea to include support multi-tenant producers but I'm not sure is it useful although Micronaut has good solution for multitenancy and pulsar is by default multitenant it doesn't mean it's really necessary to do so.

**Comment by graemerocher** [comment]
@harissecic nice, where is the code?

**Comment by MaitreyaBuddha** [comment]
@graemerocher It's here: https://github.com/harissecic/micronaut-pulsar

**Comment by graemerocher** [comment]
Great, will take a look

**Comment by harissecic** [comment]
> Great, will take a look

Thanks a lot.

**Comment by graemerocher** [comment]
@harissecic looks like a good start. There is clearly still quite a bit of work to do on docs and more test coverage. It may be worth setting up `micronaut-projects/micronaut-pulsar` which you can send a PR to and that will be a bit easier as you will be able to send a PR and then we can do a more extensive review of the code. Would you like me to create this repo? We are doing a similar process for the upcoming JMS support https://github.com/micronaut-projects/micronaut-jms/pull/1

In terms of some initial thoughts and many of these things maybe speak to my inexperience with Pulsar:

* I would rename the group from `io.micronaut.configuration.pulsar` to just `io.micronaut.pulsar`. We are moving away from including `configuration` in the name.
* Maybe `PulsarProducerClient` can just be `PulsarClient`? Or does Pulsar have other clients of clients?
* Is is typical in a an application to have more than one client configured? Currently the factory only supports a single client https://github.com/harissecic/micronaut-pulsar/blob/master/pulsar/src/main/java/io/micronaut/configuration/pulsar/PulsarClientFactory.java#L38
* `methods` doesn't seem to be used here https://github.com/harissecic/micronaut-pulsar/blob/master/pulsar/src/main/java/io/micronaut/configuration/pulsar/scope/PulsarClientScope.java#L84
* `remove` should probably be implemented to cleanup the bean by id https://github.com/harissecic/micronaut-pulsar/blob/master/pulsar/src/main/java/io/micronaut/configuration/pulsar/scope/PulsarClientScope.java#L99
* Need some javadoc explaining this interface https://github.com/harissecic/micronaut-pulsar/blob/master/pulsar/src/main/java/io/micronaut/configuration/pulsar/PulsarConsumerRegistry.java#L24


Other than that we will need to work on test coverage, documentation and making the documentation use code snippets that are tested and demonstrate Java/Kotlin/Groovy

Great start though!

**Comment by harissecic** [comment]
@graemerocher thanks for review. Would be nice to move project to your side. It may be more visible to potential contributors.
To address points one by one before move:

- Will rename when I catch time today and push to my repo until move is made to your side
- PulsarClient is an interface inside official Java library for Pulsar so I thought to avoid confusion and avoid using full class name for either annotation or that interface, just to simply add Producer part
- Sorry about it's a leftover will remove and push; but I don't think it's often to use many Pulsar clients as it supports list of URLs and service URL provider, however this is one of the this I need suggestions on from other users. I'll change it to Prototype for now
- Will remove
- Will try to implement with rest of the refactoring
- I'll try to make some java doc but as existing one it can only be really short until I get more input on what's good or bad and more time to write

When you make the repo please let me know to move this on your side in hope to get more contributors

**Comment by graemerocher** [comment]
Thanks, I have created https://github.com/micronaut-projects/micronaut-pulsar as a placeholder. You can send a PR there for review once you have got to the point where you feel it is ready. 

Having it without Micronaut projects will indeed encourage more contributors to get on board. We have seen that with other projects like graphql, ignite and so on

**Comment by harissecic** [comment]
Quick update, this https://github.com/micronaut-projects/micronaut-pulsar/pull/1 one is passing now and if merged, this issue can be closed.
