### ISSUE TITLE
Low-level HTTP client missing SERVICE_ID attribute

### ISSUE THREAD

**Issue by lightoze** [micronaut-projects/micronaut-core#2042]
One would expect that `HttpAttributes.SERVICE_ID` attribute is available for low-level clients created with `@Client(id="abc")`, but currently the attribute is only set for declarative style clients. Among other problems it breaks token propagation from micronaut-security.

### Expected Behaviour

`HttpAttributes.SERVICE_ID` is available to http filters on `@Client(id="abc")` client requests.

### Actual Behaviour

`HttpAttributes.SERVICE_ID` is null.

### Workaround

Manually set attribute on every `HttpRequest` created.

### Environment Information

- **Micronaut Version:** 1.2.0

**Comment by graemerocher** [comment]
Fixed as part of the unification behaviour for 2.0
