### ISSUE TITLE
Trace Id getting lost in the logs

### ISSUE THREAD

**Issue by SarthakMakhija** [micronaut-projects/micronaut-core#2055]
### Task List
  - [x] Steps to reproduce provided
  - [ ] Stacktrace (if present) provided
  - [x] Example that reproduces the problem uploaded to Github
  - [x] Full description of the issue provided (see below)

### Steps to Reproduce
We are using micronaut 1.2.0 in our application (Kotlin based) along with distributed tracing. We are observing a problem with tracing when an http server filter gets invoked before the request to actual controller. Any logs written in filter do not contain trace id.

Issue contains a sample application (without tests), run the application by executing the following commands - 
1. ./gradlew clean build
2. ./gradlew run
When the application starts, hit a GET request to http://localhost:8080/users/2 and check the logs in UserFilter

### Expected Behaviour
Trace id should be displayed in the logs.

### Actual Behaviour
Trace id is missed in filter logs but appears in controller and subsequent layer logs

### Environment Information
Operating System: any
Micronaut Version: 1.2.0
JDK Version: 1.8
Kotlin Version: 1.3.31

### Example Application
Attached is the link to an example application - 

https://github.com/SarthakMakhija/micronaut-tracing-issue

**Comment by graemerocher** [comment]
Probably related to #2051

**Comment by graemerocher** [comment]
Actually no, this is working as designed as far as I can see. Currently the filter decorates the publisher returned by the `chain.proceed()` method, so logging that occurs in the filter method is not instrumented for tracing at this point.

Why are you attempting to log within the `doFilter` method itself?

**Comment by SarthakMakhija** [comment]
Hello,

Thank you for your response. 

"Why are you attempting to log within the doFilter method itself?" - a couple of reasons / use-cases

1. LoggingFilter - the sole reason it exists is to log the path (request.path), time of request, user who made the request etc
2. SomeXAuthorizationFilter - which does some authorization checks and logs basic information including "User U attempting to perform an action A with and some request parameters"

We are currently using Micronaut filters for both these reasons.

One of the workarounds we have thought of is to replace filters with interceptors because we found that logging inside filter method is not instrumented for tracing.

Hope that helps. Your inputs on this will be valuable.

**Comment by graemerocher** [comment]
So the `chain.proceed()` method returns a reactive `Publisher` that you can decorate within our `doFilter` method. This is what the tracing filter does, it effectively decorates the returned publisher. 

If you wish to log the request you can do the same thing. The following code uses RxJava:

```java
        return Flowable.fromPublisher(chain.proceed(request))
        				.doOnSubscribe { _ -> logger.info("doFilter $tracer")}
```

So this will decorate the publisher so that when the publisher is subscribed to the request is logged. I believe this will give you the behaviour you want.

**Comment by SarthakMakhija** [comment]
Hey, thank you this works. 

Sorry will have to still bother you. Have pushed a commit [here](https://github.com/SarthakMakhija/micronaut-tracing-issue/commits/master)
which attempts at highlighting a use-case wherein a service is called from a filter which might be authorizing user action.

`@Singleton
open class UserVerificationService {

    private val logger: Logger = LoggerFactory.getLogger(UserVerificationService::class.java)

    open fun isVerified(): Boolean {
        //some network call and logging the response ..
        logger.info("Returning if user is verified ..")
        return true
    }
}`

**Invoking the code from filter - Option 1 does not print trace id in the logs of UserVerificationService ** 
`
@Filter("/**")
open class UserFilter(
    private val userVerificationService: UserVerificationService
) : OncePerRequestHttpServerFilter() {

    private val logger: Logger = LoggerFactory.getLogger(UserFilter::class.java)

    @NewSpan("doFilter")
    override fun doFilterOnce(request: HttpRequest<*>, chain: ServerFilterChain): Publisher<MutableHttpResponse<*>> {

        return Flowable.just(userVerificationService.isVerified())
            .flatMap {
                if (it)
                    chain.proceed(request)
                else
                    throw RuntimeException("test")
            }
            .doOnSubscribe { logger.info("filtering ${request.path}") }
    }
}
`
`
Output
20:41:39.837  [nioEventLoopGroup-1-3]  [ / ] INFO  org.examples.UserVerificationService - [ / ] - Returning if user is verified ..
20:41:39.868  [pool-1-thread-1]  [77af2bf155bf8bab / c276aa22eb0fc799] INFO  org.examples.UserFilter - [77af2bf155bf8bab / c276aa22eb0fc799] - filtering /users/2
20:41:39.884  [pool-1-thread-1]  [77af2bf155bf8bab / c276aa22eb0fc799] INFO  org.examples.UserController - [77af2bf155bf8bab / c276aa22eb0fc799] - Returning user by 2
20:41:41.063  [pool-1-thread-1]  [77af2bf155bf8bab / c276aa22eb0fc799] INFO  org.examples.UserService - [77af2bf155bf8bab / c276aa22eb0fc799] - Found user with email XYZ
20:41:41.063  [pool-1-thread-1]  [77af2bf155bf8bab / c276aa22eb0fc799] INFO  org.examples.UserController - [77af2bf155bf8bab / c276aa22eb0fc799] - Found user with email XYZ
`

**Invoking the code from filter - Option 2 
        //This block of code does not print trace id in the logs of UserVerificationService because
        //method is not instrumented for tracing.

        //Also, traceid that gets logged in ->
        // doOnSubscribe { logger.info("isVerified") } and
        // doOnSubscribe { logger.info("doFilter") }
        // is different probably because tracing filter decorates them with different trace ids.
**

`
@Filter("/**")
open class UserFilter(
    private val userVerificationService: UserVerificationService
) : OncePerRequestHttpServerFilter() {

    private val logger: Logger = LoggerFactory.getLogger(UserFilter::class.java)

    @NewSpan("doFilter")
    override fun doFilterOnce(request: HttpRequest<*>, chain: ServerFilterChain): Publisher<MutableHttpResponse<*>> {

        val userVerificationFlowable: Flowable<Boolean> = Flowable
            .just(userVerificationService.isVerified())
            .doOnSubscribe { logger.info("isVerified") }

        val proceedFlowable: Flowable<MutableHttpResponse<*>> = Flowable
            .fromPublisher(chain.proceed(request))
            .doOnSubscribe { logger.info("doFilter") }

        return userVerificationFlowable.flatMap {
            if (it)
                proceedFlowable
            else
                throw RuntimeException("test")
        }
    }
}
`

`
Output
20:44:49.109  [nioEventLoopGroup-1-3]  [ / ] INFO  org.examples.UserVerificationService - [ / ] - Returning if user is verified ..
20:44:49.139  [pool-1-thread-1]  [a55d6e321cb8bd4f / a55d6e321cb8bd4f] INFO  org.examples.UserFilter - [a55d6e321cb8bd4f / a55d6e321cb8bd4f] - isVerified

20:44:49.143  [pool-1-thread-1]  [4dc5a36b27273ec0 / 4dc5a36b27273ec0] INFO  org.examples.UserFilter - [4dc5a36b27273ec0 / 4dc5a36b27273ec0] - doFilter
20:44:49.160  [pool-1-thread-1]  [4dc5a36b27273ec0 / 4dc5a36b27273ec0] INFO  org.examples.UserController - [4dc5a36b27273ec0 / 4dc5a36b27273ec0] - Returning user by 2
20:44:50.159  [pool-1-thread-1]  [4dc5a36b27273ec0 / 4dc5a36b27273ec0] INFO  org.examples.UserService - [4dc5a36b27273ec0 / 4dc5a36b27273ec0] - Found user with email XYZ
20:44:50.159  [pool-1-thread-1]  [4dc5a36b27273ec0 / 4dc5a36b27273ec0] INFO  org.examples.UserController - [4dc5a36b27273ec0 / 4dc5a36b27273ec0] - Found user with email XYZ

`

If you look at the dummy committed code when a moment.

Thanks

**Comment by graemerocher** [comment]
Sorry I cannot understand what are you asking with the mess of formatting and intermingled comments

**Comment by SarthakMakhija** [comment]
Sorry, my bad.

Please look at the UserFilter [here](https://github.com/SarthakMakhija/micronaut-tracing-issue) which invokes a _dummy_ UserVerificationService. 

Now, trace id is missed in UserVerificationService.

**Comment by graemerocher** [comment]
This is because you are invoking the result directly within the filter. You can obtain the behaviour you want by replacing `Flowable.just(..)` with `Flowable.fromCallable(..)`

**Comment by SarthakMakhija** [comment]
Thanks, it works.
