### ISSUE TITLE
@Scheduled Annotation with cron expression

### ISSUE THREAD

**Issue by sillyoldman** [micronaut-projects/micronaut-core#2061]
I have following Scheduled task using cron expression - @Scheduled(cron = "0 0 7-23 ? * 1-5")

Want to run the task on the hour from 7 to 23. However, sometimes the task gets triggered twice - Here is the timing printed from the task 

Running Task::LocalTime 2019-08-30T15:00:00
Running Task::LocalTime 2019-08-30T16:00:00
Running Task::LocalTime 2019-08-30T17:00:00
Running Task::LocalTime 2019-08-30T18:00:00
Running Task::LocalTime 2019-08-30T18:59:58          - this shouldn't have been triggered
Running Task::LocalTime 2019-08-30T19:00:00
Running Task::LocalTime 2019-08-30T19:59:59          - this shouldn't have been triggered
Running Task::LocalTime 2019-08-30T20:00:00
Running Task::LocalTime 2019-08-30T21:00:00
Running Task::LocalTime 2019-08-30T22:00:00
Running Task::LocalTime 2019-08-30T23:00:00

Tried same thing with Spring, and it worked as expected there.

Thanks.

**Comment by jameskleeh** [comment]
Do you have any suggestions for testing this that won't take 8 hours?

**Comment by sillyoldman** [comment]
All the scenarios and junit tests we tried with @Scheduled with minutes or seconds differences (5 0 * ? * * ) (0 1/15 0 ? * *   have worked and given expected results. We only noticed jobs getting executed twice in one of our lower environments  (we are still in DEV) after we started seeing multiple results. It is indeed unpredictable.... happens intermittently.
To understand what's going on we finally decided to write small program and keep it running all day and overnight. I added the relevant log. Only visual clue that we see is the difference in seconds. E.g if we look at one of the log statements - Job first executed at 18:59:58 and then got executed at 19:00:00. In other scenario it is a seconds difference. So for some reason, when the job was run at 18:00:00, the nextRunTime was determined to be 18:59:58. And job got triggered at 18:59:58 and program correctly determined next time to be 19:00:00

I also recently bumped across CronExpression class. I don't know if it is right to assume that this gets called.  I kept looking for code that could give some clue but wasn't really able to get anywhere.

If you give me a few directions, I will happy to debug it.... 

Many Thanks

**Comment by croudet** [comment]
I think it can happen when the task is executed too early.

**Comment by sillyoldman** [comment]
Can you please explain why would that be the case? If job gets triggered at right time (18:00:00) and even if it gets executed within a second - why would next job execution time be 18:59:58 ? I am not able to understand.
Any suggestion to fix this ?

**Comment by croudet** [comment]
The clock is not always accurate. If you look at the spring code
https://github.com/spring-projects/spring-framework/blob/4575f82c726379b5f408d228074fb019c21a6d0a/spring-context/src/main/java/org/springframework/scheduling/support/CronTrigger.java#L74
You see that, they try to detect if the task has been run too early.
I think micronaut should do the same may be in `ReschedulingTask`.

**Comment by sillyoldman** [comment]
Thank you. Makes sense - as same code did work with spring boot! 
Since I want to run the job on the hour - I think, I can afford a few seconds of sleep to make the job run long enough (thinking ~ 5 secs)  and try.
