### ISSUE TITLE
The @Controller URI mapping is not computed based on class name

### ISSUE THREAD

**Issue by martinanderssondotcom** [micronaut-projects/micronaut-core#2062]
The [docs](https://docs.micronaut.io/1.2.0/api/io/micronaut/http/annotation/Controller.html#value--) has this to say about the `@Controller` value member:

> If not specified the URI will be formulated from the controller class name without the "Controller" suffix (ie. MessageController becomes /message).

It's not clear to me how to **not** specify the value and have it automagically computed.

In the following examples, I use Micronaut version 1.2.0 with a HelloController class as originally posted in the official [userguide](https://docs.micronaut.io/latest/guide/index.html#creatingServer). I.e., it's a simple controller with one `@Get` index() method.

If I leave out the value member like this:

    @Controller
    public class HelloController { ...

Then the default value `UriMapping.DEFAULT_URI` kicks in which map the controller to the root `/`, not `/hello`.

This doesn't compile (`null` not allowed as an annotation member value):

    @Controller(null)
    public class HelloController { ...

Specifying an empty String doesn't run:

    @Controller("")
    public class HelloController { ...

It fails with an exception:

<pre>Caused by: java.lang.IllegalArgumentException: Argument [templateString] should not be null
        at io.micronaut.http.uri.UriTemplate.<init>(UriTemplate.java:88)
        at io.micronaut.http.uri.UriTemplate.<init>(UriTemplate.java:76)
        at io.micronaut.http.uri.UriTemplate.of(UriTemplate.java:256)
        at io.micronaut.web.router.AnnotatedMethodRouteBuilder.resolveUri(AnnotatedMethodRouteBuilder.java:271)
        at io.micronaut.web.router.AnnotatedMethodRouteBuilder.lambda$new$0(AnnotatedMethodRouteBuilder.java:64)
        at io.micronaut.web.router.AnnotatedMethodRouteBuilder.lambda$process$10(AnnotatedMethodRouteBuilder.java:249)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.micronaut.web.router.AnnotatedMethodRouteBuilder.process(AnnotatedMethodRouteBuilder.java:242)
        at io.micronaut.web.router.AnnotatedMethodRouteBuilder.process(AnnotatedMethodRouteBuilder.java:48)
        at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:89)
        ... 28 common frames omitted</pre>

..so how am I supposed to **not** specify the mapping and have it computed??

I think it would be rather easy to get the implementation working with a special value such as a `UriMapping.COMPUTED`. I would personally be against anything else but having a special and explicit value like `COMPUTED`, which could be the default. Not that I am sure it should be the default, but if not the default value and the user has to type this special value into his annotation, then most users would probably find it easier and more quick to simply be explicit and type the path "\hello". Which leads me to my next point:

Many times frameworks add special semantics and behavior that has seemingly little added benefit but introduces lots of complexity instead and computing the mapping doesn't appear to be an exception so maybe we shouldn't even have this behavior built-in. **The easy (and good?) fix to this GitHub issue would then be to remove the documentation advertising the behavior.**

Okay so if we get this working as advertised, questions still arise. For example, "What happens if my class does not specify the value - i.e., invokes the implicit behavior to compute a mapping - but also does not have a 'Controller' suffix in the class name?". Should I as the framework user have to resort to constant laboration with toy code in order to "figure out" how a framework behave, what works and what does not work - like I do with all other frameworks out there because they love and adore obscure non-documented complexity? See, I don't think this is a good path to take.

My personal opinion is that magic is evil. Magic and implied behavior adds complexity not only to the implementation and documentation (the ever growing "if-else this if-else that" dilemma), but certainly makes it exponentially harder to understand for all users.

That is why, although computing a mapping based on a class name seems to be an easy task and easy to understand et cetera, I have real concerns this is a step in the wrong direction and I would vote for getting this behavior removed.

**Comment by jameskleeh** [comment]
You don't need to vote for the behavior to be removed because it already was, a long time ago. The javadoc was just never corrected.

**Comment by martinanderssondotcom** [comment]
Oh splendid. Why was it removed if I may ask?

**Comment by jameskleeh** [comment]
For reasons similar to the sentiments you described

**Comment by martinanderssondotcom** [comment]
Is the `@Get` [JavaDoc](https://docs.micronaut.io/snapshot/api/io/micronaut/http/annotation/Get.html) also out of date? At least it doesn't work for me lol.

> [...] route if not specified inferred from the method name and arguments

**Comment by graemerocher** [comment]
Yes it is also out of date
