### ISSUE TITLE
Config files have precedence over environment variables

### ISSUE THREAD

**Issue by ssouris-te** [micronaut-projects/micronaut-core#2072]
### Task List

- [x] Steps to reproduce provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a simple Micronaut app with spring-cloud-client included
2. Create a `bootstrap.yml` in `resources` and set `spring.cloud.config.uri` property there
3. Set the environment variable `SPRING_CLOUD_CONFIG_URI` before running the app
4. Add a breakpoint in `SpringCloudConfigurationClient#getPropertySources` and see the value of the `uri`.
5. If you use property `spring-cloud-config-uri` it gets replaced.

### Expected Behaviour

I would assume that environment variables take precedence over properties.

### Actual Behaviour

URI is not replaced with the environment variable value.

### Environment Information

- **Operating System**: Alpine linux and MacOS
- **Micronaut Version:** 1.2.0
- **JDK Version:** 1.8.0_144

**Comment by jameskleeh** [comment]
I can't reproduce. If you provide an example application I will reopen the issue. The only thing I can assume is that the environment variable was not in the scope of the apps session.

**Comment by ssouris** [comment]
So I can reproduce it [here](https://github.com/ssouris/micronaut-bug-2072).
The problems seems to arise when you are using `MICRONAUT_CONFIG_FILES `.

Use command to run it:
`SPRING_CLOUD_CONFIG_URI=https://localhost:9090;MICRONAUT_CONFIG_FILES=/path/to/my-app1/bootstrap.properties ./gradlew run 
`

Hope this helps.

**Comment by jameskleeh** [comment]
While I think this is a bug, I'm concerned about changing the behavior in a point release. Given the potential for users to rely on this behavior, I'm going to push this to 1.3

**Comment by ssouris-te** [comment]
Thanks I'll try to test this as soon as I can.
