### ISSUE TITLE
Make Introspected to support interface

### ISSUE THREAD

**Issue by eisig** [micronaut-projects/micronaut-core#2081]
Our use case is same as https://github.com/micronaut-projects/micronaut-core/issues/911.
We want to get all interfaces annotated by an annotattion.( [myabtis](https://github.com/mybatis/mybatis-3/tree/master/src/main/java/org/apache/ibatis) Mapper annotation)

It seems that `Introspected` and `BeanIntrospector.SHARED.findIntrospections` only workt with class.

**Comment by graemerocher** [comment]
Duplicates #1968
