### ISSUE TITLE
`CircuitBreakerRetry.open()` throws `lastError` instead of returning expected `Single.error(lastError)`

### ISSUE THREAD

**Issue by kreiger** [micronaut-projects/micronaut-core#2089]
### Steps to Reproduce

1. Have `@CircuitBreaker` annotation on method that returns `Single.error(exception)`
2. Call the method multiple times, making sure to observe the exception in the `Single` using e.g. `.blockingGet()`.
3. `CircuitBreakerRetry.open()` **throws** the exception instead of returning a `Single.error(exception)` as expected.

### Expected Behaviour

`CircuitBreakerRetry.open()` should return `Single.error(lastError)` instead of `throw (RuntimeException) lastError;` when the expected return type is `Single`.

### Actual Behaviour

`CircuitBreakerRetry.open()` throws `(RuntimeException) lastError;`

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.2.0
- **JDK Version:** OpenJDK 11

### Example Application

https://github.com/kreiger/micronaut-circuit-breaker-return-type/

**Comment by kreiger** [comment]
Furthermore, i've discovered that a `@CircuitBreaker` method that returns `Single.error(exception)` doesn't get called again.

This can be trivially realized by seeing that `context.proceed()` is only called once in the `isConvertibleToPublisher` flow, and not called again in `retryFlowable`.

As this is a related but separate but I'll try to write up another bug report.

**Comment by jameskleeh** [comment]
So while I agree this is an issue, it wouldn't present yourself if you were returning a cold observable. There is no benefit to returning a Single if you are going to do `Single.just` or `Single.error`

**Comment by jameskleeh** [comment]
I'm not sure the other issue you described is an issue. Return cold observables.

**Comment by kreiger** [comment]
Thanks, i think i will.

It was using `Single.error(exception)` in a test, and was confused for hours because the CircuitBreaker didn't retry like i would expect.
