### ISSUE TITLE
Property endpoints.all.path used together with micronaut.server.context-path sets wrong endpoints path

### ISSUE THREAD

**Issue by cdome** [micronaut-projects/micronaut-core#2090]
### Steps to Reproduce
Use this combination in your application.yml file:
```
micronaut.server.context-path=/abc
endpoints.all.path=/xyz
```

### Actual behavior:
Built-in endpoints like health would be then available at `/xyz/abc/health` which seems to be wrong.

### Expected behaviour:
Built-in endpoints should be available either at `/abc/xyz/...` path if we assume that context-path is shared also for endpoints OR, preferably at plain `/xyz/...` path - as these endpoints may be intentionally made to be out of the app context path - the same behavior as when `micronaut.router.static-resources.*.mapping` is used - it also doesn't take `context-path` into account.

### Environment Information
* **Operating System:** MacOs
* **Micronaut Version:**  both 1.2.0 and latest 1.3.0-BUILD-SNAPSHOT
* **JDK Version:** openjdk 12.0.1 2019-04-16

**Comment by jameskleeh** [comment]
If you'd like you can file an issue to allow for the static resources mappings to be context path aware. The current behavior is not a bug, so it would be a feature request
