### ISSUE TITLE
Http client on master is missing features from 1.1.x branch

### ISSUE THREAD

**Issue by KrzysztofKowalczyk** [micronaut-projects/micronaut-core#2091]
Hi, the master branch (including 1.2.x) seems to be missing features from 1.1.x branch:
For instance:
https://github.com/micronaut-projects/micronaut-core/blob/master/http-client/src/main/java/io/micronaut/http/client/HttpClientConfiguration.java

Does not allow  to set ProxySelector that was on 1.1.x:
https://github.com/micronaut-projects/micronaut-core/blob/1.1.x/http-client/src/main/java/io/micronaut/http/client/HttpClientConfiguration.java

Which was introduced in:
https://github.com/micronaut-projects/micronaut-core/commit/8a1f2470e76b53f1ed73632896b9c0c1fb6a5434

**Comment by jameskleeh** [comment]
Thanks - I cherry picked the commit into 1.2.x

**Comment by KrzysztofKowalczyk** [comment]
Thanks!
