### ISSUE TITLE
Reactive types error handling

### ISSUE THREAD

**Issue by Deviad** [micronaut-projects/micronaut-core#2096]
Hello, 
I think reactive types' errors at the moment are not handled correctly.
According to RxJava specs, it is not possible to throw an error from within a Reactive data structure (Maybe, Observable, Flowable, etc.) in order to avoid situations where methods are not allowed to end their work gracefully. 

To solve this problem, other frameworks provide a reference to the response object with a send method and the ability to build your response with an error status and message eventually.

At the moment in the following case I get either an empty list in case I use a non blocking approach and return an Observable or a null pointer exception if I use the blocking approach.
In both of these cases, however, I am not able to make a custom exception pop up in order to trigger the global error handler. 

This is the non blocking block of code:

```Java
            return Maybe.<String>create(emitter -> {
                try {
                    if (subject.getValue() != null) {
                        emitter.onSuccess(subject.getValue());
                    } else {
                        emitter.onComplete();
                    }
                } catch (Throwable ex) {
                    emitter.onError(ex);
                }
            })
                    .subscribeOn(Schedulers.single())
                    .observeOn(Schedulers.single())
                    .toObservable()
                    .switchIfEmpty(Observable.create(emitter ->
                    {
                        emitter.onError(new NoMessageReceivedException("No message from hyperledger"));

                    }))
                    .retryWhen(attempts -> attempts.zipWith(Observable.range(1, 3), (error, i) ->
                    {
                        if (i < 3) {
                            return Observable.timer(i, TimeUnit.SECONDS);
                        } else {
                            return Observable.error(new NoMessageReceivedException("No message from hyperledger"));
                        }
                    }))
                    .doOnError(throwable -> Observable.error(throwable.getCause()))
                    .map(command::getSuccessScalarResponse);
```

And this is the blocking code

```Java
         return Maybe.<String>create(emitter -> {
                try {
                    if (subject.getValue() != null) {
                        emitter.onSuccess(subject.getValue());
                    } else {
                        emitter.onComplete();
                    }
                } catch (Exception ex) {
                    emitter.onError(new NoMessageReceivedException("No message from hyperledger"));
                }
            })
                    .subscribeOn(Schedulers.single())
                    .observeOn(Schedulers.single())

                    .toObservable()
                    .switchIfEmpty(Observable.create(emitter ->
                    {
                        emitter.onError(new NoMessageReceivedException("No message from hyperledger"));

                    }))
                    .retryWhen(attempts -> attempts.zipWith(Observable.range(1, 3), (error, i) ->
                    {
                        if (i < 3) {
                            return Observable.timer(i, TimeUnit.SECONDS);
                        } else {
                            return Observable.error(new NoMessageReceivedException("No message from hyperledger"));
                        }
                    }))
                    .doOnError(throwable -> {
                        log.info("No message from Hyperledger!");
                    })
                    .blockingFirst();
```

### Task List

- [ V ] Steps to reproduce provided

1) Create a Subject and do not provide it any data.
2) Use a Maybe data structure which handles the null case which should return some value to the controller.

- [X ] Stacktrace (if present) provided

- [V ] Example that reproduces the problem uploaded to Github
- [ V] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Controller that returns an Observable;
2) Create a service that should return the events from  a Subject; 
2) Use a data structure like Maybe to handle null and return a custom error in case after a set amount of times the value is always null

### Expected Behaviour
The controller should return the exception

### Actual Behaviour

According if it's a blocking scenario or a non blocking scenario the controller returns either a null pointer exception or an empty list with status 200.

### Environment Information

- **Operating System**:  Mojave
- **Micronaut Version:** 1.20
- **JDK Version:** 
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Mac OS X amd64-64-Bit Compressed References 20190806_306 (JIT enabled, AOT enabled)

### Example Application
[Clarity App](https://github.com/Deviad/clarity/blob/d0cada46b529c18a98c09148f581a15a0be5e73a/claritydispatcher/src/main/java/com/clarity/claritydispatcher/web/handler/HyperledgerAccountHandler.java)

**Comment by Deviad** [comment]
As a workaround I have found this solution:
```
@SneakyThrows
        private static Map<String, Object> getResult(HyperledgerAccountHandler command) {

//            final CountDownLatch latch = new CountDownLatch(30);
//            while (!latch.await(10, TimeUnit.SECONDS)) {
//                if (command.kafkaMessageListener.messages.peek() == null) {
//                    latch.countDown();
//                } else {
//                    return command.getSuccessMonoResponse(command.kafkaMessageListener.messages.poll());
//                }
//            }
            final BehaviorSubject<String> subject = command.kafkaMessageListener.bus.getEvents();
            Map<String, Object> result = null;
            try {
                final Map<String, Object> stringObjectMap = Maybe.<String>create(emitter -> {
                    try {
                        if (subject.getValue() != null) {
                            emitter.onSuccess(subject.getValue());
                        } else {
                            emitter.onComplete();
                        }
                    } catch (Throwable ex) {
                        emitter.onError(ex);
                    }
                })
                        .subscribeOn(Schedulers.io())
//                    .observeOn(Schedulers.single())
                        .toObservable()
                        .switchIfEmpty(Observable.create(emitter ->
                        {
                            emitter.onError(new NoMessageReceivedException("No message from hyperledger"));

                        }))
                        .retryWhen(attempts -> attempts.zipWith(Observable.range(1, 3), (error, i) ->
                        {
                            if (i < 3) {
                                return Observable.timer(i, TimeUnit.SECONDS);
                            } else {
                                return Observable.error(new NoMessageReceivedException("No message from hyperledger"));
                            }
                        }))
                        .map(command::getSuccessScalarResponse).blockingFirst();
                result = stringObjectMap;
            } catch (NoSuchElementException ex) {
                throw new NoMessageReceivedException("No message from hyperledger");
            }
            return result;
        }
```

**Comment by Deviad** [comment]
Just so you know, that is the RxJava version of:
```Java
            final CountDownLatch latch = new CountDownLatch(30);
            while (!latch.await(10, TimeUnit.SECONDS)) {
                if (command.kafkaMessageListener.messages.peek() == null) {
                    latch.countDown();
                } else {
                    return command.getSuccessMonoResponse(command.kafkaMessageListener.messages.poll());
                }
            }
```

**Comment by Deviad** [comment]
Well, it looks like this might be related also to a design matter:
https://softwareengineering.stackexchange.com/questions/358243/should-no-results-be-an-error-in-a-restful-response

**Comment by graemerocher** [comment]
I am failing to understand how Micronaut is different to Spring in this respect. You can equally use `onErrorResume` and `HttpResponse.ok("Error handled")` to modify the response.

**Comment by jameskleeh** [comment]
@Deviad Can you document the steps to reproduce the issue with your application? What branch? Perhaps include a curl command or document what controller to call

**Comment by Deviad** [comment]
@jameskleeh I have created an ad hoc repo:
https://github.com/Deviad/micronaut-errorhandling
Just run the main app file
https://github.com/Deviad/micronaut-errorhandling/blob/master/src/main/java/reactive/micronaut/Application.java

And have a look here for the endpoints

https://github.com/Deviad/micronaut-errorhandling/blob/master/src/main/java/reactive/micronaut/resource/MonoDemoController.java

**Comment by jameskleeh** [comment]
In order for it to not hang the observable needs to complete

```
    MyRxOutputBean<String> bean = new MyRxOutputBean<>();
    return Flux.interval(Duration.ofMillis(500))
        .take(1)
        .flatMap(x -> bean.getEvents().next())
```

results in a Mono that never completes, because no events are emitted through the subject

**Comment by Deviad** [comment]
Well, this is about the philosophical matter described here:
https://softwareengineering.stackexchange.com/questions/358243/should-no-results-be-an-error-in-a-restful-response

What you are describing as: "The absence of an event is not the same as an error".

The point is should there be any means for this to be detected as an error for those that want to choose this path?
I have the gut feeling that in 90% of the companies having legacy code and some sort of company policies for such things in this case an error should be represented.

**Comment by jameskleeh** [comment]
@Deviad That SO really doesn't have anything to do with this. The absence of an event is not an error has to do with how reactive streams works. You can use things like [the timeout operator](http://reactivex.io/documentation/operators/timeout.html) if you want to emit an error if no event has been emitted for a given period of time.

There is no philosophical decisions to be made, its all how you want to use the reactive streams api and doesn't have anything to do with Micronaut itself.

**Comment by Deviad** [comment]
@jameskleeh you might be right, however in one of my attempts I could get the null value after 3 tries with 200 status, this is why I have catalogued also the case when no event is present to the null kind of situation.  In any case, creating a utility function which makes that code abstract is not a big deal. I was thinking that since this is a common problem, maybe it made sense to treat it inside the framework.

**Comment by jameskleeh** [comment]
@Deviad I agree that it might be a pain point. Programming with reactive streams has a steep learning curve and is very complex. There isn't anything we can do about that, as it can't be our responsibility to teach that programming model for developers.

Because reactive streams is hard, we allow for controller methods to return blocking types and we automatically delegate those methods to a separate thread pool. We put in a lot of effort to allow for the blocking style of coding and keep as many of the advantages of the underlying server (Netty) as possible.
