### ISSUE TITLE
Declarative client always throws exception

### ISSUE THREAD

**Issue by schrek1** [micronaut-projects/micronaut-core#2117]
When I use declarative client, I use error handling as described (https://docs.micronaut.io/latest/guide/httpClient.html) 

> If the method returns an HttpResponse, the original response will be returned

But if I use HttpResponse declarative client always throws exception

Code:

`
import io.micronaut.http.HttpResponse;
@Client("ecommerce-service")
public interface CartClientEC {
    @Post("/api/Customer/Cart")
    HttpResponse<CartItemAddResponseEC> manageItemInCart(@Body CartItemRequestEC requestBody);
}
`

Exception:

> Method threw 'io.micronaut.http.client.exceptions.HttpClientResponseException' exception.

Logs:

https://textsaver.flap.tv/lists/2vf6

**Comment by jameskleeh** [comment]
That is by design

**Comment by schrek1** [comment]
Ok I think it is good when I use only raw response object but if I wrap into http response I think that I want handle processing whole response... som case for example I want to handle error message from server, it has other format than response in almost cases, I want reuse it and expose content of error response to my rest api.
