### ISSUE TITLE
Regression in CookieConfiguration getCookieMaxAge

### ISSUE THREAD

**Issue by puneetbehl** [micronaut-projects/micronaut-core#2124]
We got a breaking change in Micronaut 1.2.2 after upgrading from 1.2.0. It seems like this is introduced by fixing https://github.com/micronaut-projects/micronaut-core/issues/2085 

Where the signature of `CookieConfiguration.getCookieMaxAge` has been changed from `Optional<TemporalAmount>` to `Optional<Duration>`.

**Comment by jameskleeh** [comment]
I agree I think I shouldn't have changed the getter - my mistake
