### ISSUE TITLE
Auto support for Jackson KeyDeserializer

### ISSUE THREAD

**Issue by lightbody** [micronaut-projects/micronaut-core#2127]
Currently there is nice automatic support wiring up Jackson with beans of the following types:

- Module
- JsonDeserializer
- JsonSerializer
- BeanDeserializerModifier
- BeanSerializerModifier

But I've found another common pattern is a KeyDeserializer. Right now it's not a big deal since I just rig up a Module to register it, but it'd be convenient if you natively supported KeyDeserializer. Thanks!

**Comment by jameskleeh** [comment]
This would involve injecting an array of those types similar to https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/jackson/ObjectMapperFactory.java#L68

and then adding them to the factory similar to https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/jackson/ObjectMapperFactory.java#L124

**Comment by RushikeshSawant** [comment]
Hi, I would like to work on this issue for Hacktoberfest. Can you please assign it to me?

**Comment by RushikeshSawant** [comment]
Hi @jameskleeh, sorry for the delay, will be issuing pull request soon!

**Comment by RushikeshSawant** [comment]
@jameskleeh here is my PR: https://github.com/micronaut-projects/micronaut-core/pull/2221

**Comment by graemerocher** [comment]
Thanks for the contribution
