### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by cemo** [micronaut-projects/micronaut-core#215]
Having a comparison with Spring and other JVM stacks would be very nice.

**Comment by brandonlamb** [comment]
+1

https://github.com/TechEmpower/FrameworkBenchmarks

**Comment by jringuette** [comment]
Hi, I just made a pull request exactly for that, since I was interested in comparing it with spring and vanilla netty. You can see it here https://github.com/TechEmpower/FrameworkBenchmarks/pull/3894

**Comment by jameskleeh** [comment]
Closed by https://github.com/TechEmpower/FrameworkBenchmarks/pull/3941

**Comment by JStumpp** [comment]
The micronaut benchmarks seem to fail in latests tests see here: https://www.techempower.com/benchmarks/#section=test&runid=a0d523de-091b-4008-b15d-bd4c8aa25066

**Comment by JStumpp** [comment]
And it would be interesting to see how a GraalVM would increase performance. A test TechEmpower variant would be great.

**Comment by skybber** [comment]
Hi, I'm working on performance tests of simple REST service for some time, I've just included Micronaut. Look at https://github.com/HotswapProjects/pingperf

**Comment by graemerocher** [comment]
Interesting, from the data looks like Micronaut smokes most of the other frameworks for req/sec  🎉

**Comment by skybber** [comment]
Main difference is non blocking UI, that shines especially in 50-clients tests.

**Comment by graemerocher** [comment]
Yup

**Comment by oscarfh** [comment]
@graemerocher @skybber 
sorry for reviving this old thread.
You mentioned that "Micronaut somes most of the other frameworks", where could you find it?
The service tested by the benchmark, is it a reactive or a non-reactive one?

I ask this because I would like to replace a vertx service by a Micronaut one, but we are worried about the performance impacts we would have. And it seems that vertx has an advantage in the benchmark results, but your messages seem to show otherwise. 

thanks!

**Comment by graemerocher** [comment]
Vertx is more low level so maybe it easier to suck every last bit of performance out of it, but then you trade off convenience and productivity. You can see benchmarks here https://www.techempower.com/benchmarks/

Vertx does much better in the case of just sending text back, but most apps don't do that. For the other benchmarks the difference is smaller.

**Comment by oscarfh** [comment]
Thanks  for the answer and sorry for the late reply, missed it because I was not notified.
