### ISSUE TITLE
HTTP client pool caches dns lookup forever

### ISSUE THREAD

**Issue by luckyswede** [micronaut-projects/micronaut-core#2152]
When the DefaultHttpClient creates it's poolMap instance a DNS lookup is made and stored in the bootstrap instance:
`                        Bootstrap newBootstrap = bootstrap.clone(group);
                        newBootstrap.remoteAddress(key.getRemoteAddress());
`
The remoteAddress is never updated, which means that if the ip is recycled (very common for AWS hosted services), the pool will continue to try to create connections to the original ip.

### Task List
- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
https://github.com/luckyswede/micronaut-dnstest

### Expected Behaviour
When new connections are created a new DNS lookup should take place

### Actual Behaviour
The original DNS lookup result is reused

### Environment Information

- **Operating System**: All
- **Micronaut Version:** 1.2.2
- **JDK Version:** 11

### Example Application
https://github.com/luckyswede/micronaut-dnstest

**Comment by jameskleeh** [comment]
Note that even with the fix you cannot test this issue with your hosts file because it gets cached

**Comment by luckyswede** [comment]
Great stuff, thanks for the short turnaround time!
