### ISSUE TITLE
@Client requires @Validated

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#2155]
Given this Declarative HTTP Client: 

```java
package example;

import io.micronaut.http.annotation.Get;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.validation.Validated;

import javax.validation.constraints.PastOrPresent;
import java.time.LocalDate;

@Validated
@Client("https://exchangeratesapi.io")
public interface ExchangeRates {

    @Get("{date}")
    String rate(@PastOrPresent LocalDate date);
}
```

This spock tests passes: 

```groovy
package example

import io.micronaut.context.ApplicationContext
import spock.lang.AutoCleanup
import spock.lang.Shared
import spock.lang.Specification
import spock.lang.Subject

import javax.validation.ConstraintViolationException
import java.time.LocalDate

class ExchangeRatesSpec extends Specification {

    @AutoCleanup
    @Shared
    ApplicationContext applicationContext = ApplicationContext.run()

    @Subject
    @Shared
    ExchangeRates exchangeRates = applicationContext.getBean(ExchangeRates)

    void "passing a future date throws ConstraintViolationException"() {

        when:
        exchangeRates.rate(LocalDate.of(3000, 1, 1))

        then:
        thrown(ConstraintViolationException)
    }
}
```

However, if I remove the `@Validated` annotation from `@Client` it fails. 

I was expecting Micronaut to include @Validated annotation automatically for classes annotated with @Client. Similar behaviour it does for `@Controller`. 

[micronaut-2155.zip](https://github.com/micronaut-projects/micronaut-core/files/3656958/micronaut-2155.zip)
### Environment Information

- **Operating System**: MacOs Mojave
- **Micronaut Version:** 1.2.2
- **JDK Version:** 1.8.0_191

### Example Application

Attached sample app. 
[micronaut-2155.zip](https://github.com/micronaut-projects/micronaut-core/files/3656960/micronaut-2155.zip)

**Comment by jameskleeh** [comment]
Closed by https://github.com/micronaut-projects/micronaut-core/commit/ae80bd80680e610f7f8fe58b7edc094ba05dfe38
