### ISSUE TITLE
@PreDestroy on @RequestScope is not called

### ISSUE THREAD

**Issue by Andy2003** [micronaut-projects/micronaut-core#2162]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a `@RequestScope` bean wit a `@PreDestroy` method
2. Invoke a method of this bean in a RestController

### Expected Behaviour

The `@PreDestroy` method get invoked

### Actual Behaviour

The `@PreDestroy` method is not invoked each request

### Environment Information

- **Operating System**: Ubuntu
- **Micronaut Version:** 1.2.2
- **JDK Version:** OpenJdK 1.8.0_212

### Example Application

https://github.com/Andy2003/micronaut-session-test

**Comment by graemerocher** [comment]
So yeah whilst this is try, in the reactive model we have when a request ends is actually quite difficult to establish, it is not like servlet where you know when the thread terminates the request is finished as there may be multiple sub threads etc. hence why semantically we haven't implemented this feature yet.

The solution would be to call https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/runtime/http/scope/RequestCustomScope.java#L102

When the request completes. The tricky thing is knowing when that is the case. I guess it could be done in a filter when the publisher completes.

**Comment by jameskleeh** [comment]
This is confirmed to be working in 2.2.2

**Comment by thangnc2707** [comment]
@jameskleeh
@graemerocher 
 I using Micronaut version 1.3.3.
I wanna apply gracefully shutdown but when upgrading version Micronaut to 2.2.2 the Server has issued " No transaction manager configured"
