### ISSUE TITLE
Can't get original message from HttpClientResponseException

### ISSUE THREAD

**Issue by schrek1** [micronaut-projects/micronaut-core#2171]
When I used declarative client. I try handle bad responses in the try-catch block.

E.g. When I called endpoint which returns 400 - Bad request.
I tried obtain original response from inside of the HttpClientResponseException. However the original response body from called enpoint isn't  inside that exception, but I can see it in trace log in IntelliJ.

I attached console log and HttpClientResponseException dump.

[HttpClientResponseException_content.txt](https://github.com/micronaut-projects/micronaut-core/files/3665622/HttpClientResponseException_content.txt)

[console_logs.txt](https://github.com/micronaut-projects/micronaut-core/files/3665607/console_logs.txt)

**Comment by jameskleeh** [comment]
You likely aren't setting the error type and using a blocking client. Include some example code

**Comment by schrek1** [comment]
`
import io.micronaut.http.HttpResponse;
import io.micronaut.http.annotation.*;
import io.micronaut.http.client.annotation.Client;

@Client("service")
@Headers({
        @Header(name = "api-version", value = "${service.api-version}"),
        @Header(name = "Authorization", value = "${service.api-key}")
})
public interface EcommerceClient {

@Get("/api/Customer/Wishlist")
    HttpResponse<WishlistResponse> getWishlist(
            @PathVariable String customerId
    );

}
`

**Comment by schrek1** [comment]
Thanks @jameskleeh I had lack information, it's working when I put errorType to client annotation.

`@Client(value = "service", errorType = String.class)`
