### ISSUE TITLE
Jackson BeanIntrospectionModule as standalone for kotlin

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-core#2186]
Any plans to have the reflection free Jackson support wrapped as standalone package?  Would be interesting to use with standalone kotlin code without the need for reflection and get the flexibility of Jackson 👍🏻

**Comment by jameskleeh** [comment]
Please ask questions in Gitter

**Comment by graemerocher** [comment]
Just to update this incase anyone else comes upon this question. We have had quite a few people ask us to decouple the Bean Introspection module. This is probably going to be bundled into #1968

**Comment by StephenOTT** [comment]
@graemerocher if we ask questions only in Gitter there is essentially zero findability and searchability of that conversation /answer.

**Comment by graemerocher** [comment]
@StephenOTT that actually isn't true. The other day I searched for "org.springframework.jdbc.datasource.ConnectionProxy the class was requested to be initialized at build time" on google and one of the first results was a link to a gitter conversion

gitters searchability is actually one of its benefits over something like Slack. Some projects have encourages questions via Github issues too, we maybe need to have a conversation about that, but it does place an extra burden between Stackoverflow, Gitter and Github Issues and also makes it hard to keep track of real issues that are reported on Github.

Thanks for the feedback however.

**Comment by StephenOTT** [comment]
A gitter chat that is indexed is the individual messages not the topic of a conversation.  You end up with google results that just show the chat room not the actual topic.  No clarity if you are finding all the same conversation/topic or actually finding different information.  Searching your quoted text, the first result is GitHub with relevant context information to understand what you are getting into.  The next two results are gitter results and you have no idea if it's the same conversation or not.  Compounding this you then have multiple conversations going on that someone have to swift through.  GitHub does Not have to be used, but chat systems in their current state are very problematic for finding that information later and followup: (following a conversation for future updates, cross project references and mentions, saving a conversation for future reference rather than a single message in a chat room)

**Comment by graemerocher** [comment]
Ok, we will take this into future consideration. Thanks for the feedback.
