### ISSUE TITLE
@Cacheable not user-friendly

### ISSUE THREAD

**Issue by mnembrini** [micronaut-projects/micronaut-core#2200]
@Cacheable is not very user friendly in Micronaut:

Problem 1: you must configure every cache by name, there is no default config.
If a library is using @Cacheable("some-cache") the consumer has to configure it in the application.yml under micronaut.caches.some-cache

I would expect this to work without having to configure it with some sane defaults. Spring Boot works this way as far as I remember.

Problem 2: @Cacheable without a cache name does not do anything. No warning or error message is printed, and the caching is not active. 

### Environment Information

- **Operating System**: Mac OS 10.14.3
- **Micronaut Version:** 1.1.0
- **JDK Version:** 12.0.0-open from skdman

### Example Application

https://github.com/mnembrini/cacheable-qol

Problem 1 is not a bug but I think would improve the usability.

Problem 2 should be easy to fix and might save other people some time from figuring out why it's not working

**Comment by jameskleeh** [comment]
With 1.3 you can register a `DynamicCacheManager` that will handle cache requests for caches that have not been pre-defined.
