### ISSUE TITLE
Argument with generic type does not return the described generic type

### ISSUE THREAD

**Issue by fabienrenaud** [micronaut-projects/micronaut-core#2204]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Write a generic
```
class Foo<T> { 
  T foo;
}
```
2. Try:
```
Argument<Foo<Boolean>> arg1 = Argument.of(Foo.class, Boolean.class);
Argument<Foo<Boolean>> arg2 = (Argument<Foo<Boolean>>) Argument.of(Foo.class, Boolean.class);
```
But that does not compile.

### Expected Behaviour

One of:
```
Argument<Foo<Boolean>> arg1 = Argument.of(Foo.class, Boolean.class);
Argument<Foo<Boolean>> arg2 = (Argument<Foo<Boolean>>) Argument.of(Foo.class, Boolean.class);
```
should compile.

### Actual Behaviour

I have to drop my generic type to use the API:
```
Argument<Foo> arg = Argument.of(Foo.class, Boolean.class);
```
but still can't cast it to `Argument<Foo<Boolean>>`...
Instead, I have to trick the compiler with an intermediate `Object` type:
```
Object obj = (Argument<Foo<Boolean>>) Argument.of(Foo.class, Boolean.class);
Argument<Foo<Boolean>> arg = (Argument<Foo<Boolean>>) obj;
```

Jackson and Spring support fully parametrized generic types for parsing content/responses.

### Environment Information

- **Operating System**: Mac OS Mojave
- **Micronaut Version:** 1.2.3
- **JDK Version:** 8, 11

### Example Application

https://github.com/fabienrenaud/micronaut-bug-http-client-error-decoder/blob/master/src/test/java/bug/micronaut/AppTest.java#L30 shows I chose not to use the full parametrized generic otherwise it wouldn't compile.

**Comment by graemerocher** [comment]
As far as I know in Java there is no way to get the syntax 

`Argument<Foo<Boolean>>  arg = Argument.of(Foo.class, Boolean.class)` 

To work generically for all types. Hence why we support `of`, `listOf` etc. for common types. If you want to achieve the above you have to do:

`Argument<Foo<Boolean>>  arg = new GenericArgument<Foo<Boolean>>{}` 

Which is pretty much exactly how Jackson handles it with the syntax:

`mapper.readValue(jsonString, new TypeReference<Foo<Boolean>>() {});`

I am not sure how Spring handles it but I imagine the approach would be similar.

**Comment by fabienrenaud** [comment]
Yeah there is no way in Java to support such generic types with static factory/utility methods...
I didn't know about `GenericArgument`.
Closing.
