### ISSUE TITLE
Traces from micronaut app are not visible in Jaeger 

### ISSUE THREAD

**Issue by ZeinabAshjaei** [micronaut-projects/micronaut-core#2209]
I have an instrumented micronaut application. If I configure localhost jaeger to see the traces, it would be fine, but the same configuration for a customized jaeger endpoint is not working. It seems that micronaut configuration for tracing supports only localhost. 

- Steps to reproduce

Bring up a customized jaeger, not localhost and set its endpoint and port in the application.yaml file, like the way it has been explained in the documentation. 
https://guides.micronaut.io/micronaut-microservices-distributed-tracing-jaeger/guide/index.html

### Expected Behaviour

To see spans in jaeger UI.

### Actual Behaviour

The application is not in the list of services. 

### Environment Information

- **Micronaut Version:** 1.2.0
- **JDK Version:** 8

The same issue is reported in stackoverflow: 
https://stackoverflow.com/questions/58249869/micronaut-and-opentracing-of-method-calls

**Comment by graemerocher** [comment]
There were some issues that were resolved with Jaeger in Micronaut 1.2.3

Please could you upgrade to the latest version and verify again?

**Comment by ZeinabAshjaei** [comment]
I upgraded to 1.2.3, but did not help.

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue

**Comment by ZeinabAshjaei** [comment]
I think the explanation is clear, in order to configure tracing, we need to set jaeger endpoint and port like this:

---
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1
    sender:
      agentHost: "**jaeger endpoint**"
      agentPort: "**jaeger port**"

If I bring up a localhost all-in-one jaeger using docker and replace the jaeger endpoint with localhost and the port to 14268, traces are visible in jaeger, but if I want to use another jaeger server than localhost, it does not show any traces. My jaeger server is up and running, since other non-micronaut services are sending their traces to jaeger. I guess the configuration of the tracing in micronaut is so that it could only support localhost.

**Comment by graemerocher** [comment]
As a workaround you can define the following bean:


```java
import io.jaegertracing.Configuration;
import io.jaegertracing.Configuration.SenderConfiguration;

@Factory
class MySenderConfig {

     @Singleton
     SenderConfiguration senderConfig() {
           SenderConfiguration config = SenderConfiguration.fromEnv();
           config.withAgentHost("**jaeger endpoint**");
           config.withAgentPort("**jaeger port**");
           return config;
     }
}
```

**Comment by ZeinabAshjaei** [comment]
Thank you for the workaround, but it could not resolve my issue.

**Comment by zouxiang** [comment]
@ZeinabAshjaei I have the same issue with you

**Comment by graemerocher** [comment]
Apologies, this should work until 1.2.4 is out:

```java
import javax.inject.Singleton;

import io.jaegertracing.Configuration.ReporterConfiguration;
import io.jaegertracing.Configuration.SenderConfiguration;
import io.micronaut.context.event.BeanCreatedEvent;
import io.micronaut.context.event.BeanCreatedEventListener;
import io.micronaut.tracing.jaeger.JaegerConfiguration;

@Singleton
class CustomJaegerConfiguration implements BeanCreatedEventListener<JaegerConfiguration> {

    @Override
    public JaegerConfiguration onCreated(BeanCreatedEvent<JaegerConfiguration> event) {
        JaegerConfiguration config = event.getBean();
        ReporterConfiguration reporterConfig = ReporterConfiguration.fromEnv();
        SenderConfiguration senderConfig = SenderConfiguration.fromEnv();
        senderConfig.withAgentHost("**jaeger endpoint**");
        senderConfig.withAgentPort(14268);
        reporterConfig.withSender(
            senderConfig
        );
        config.setReporterConfiguration(reporterConfig);
        return config;
    }

}
```

**Comment by Bkamau** [comment]
Am not sure why but using ```agentPort: 14268```   did  not work in my case, however ```  agentPort: 6831 ``` did work. Maybe the documentation can expound a bit in configuration.
