### ISSUE TITLE
Support streaming JSON with @Client

### ISSUE THREAD

**Issue by akozel** [micronaut-projects/micronaut-core#222]
Im familiar with Spring Flux + SSE, tried to write some code that stream data.

Two issues here:

1. When Im making request in Chrome It does not closing connection for a some time (loading circle is spinning), but Im using regular Flux.fromIterable that emmits complete signal at the end of array.

2. It closes commection for a some time (about 1 minute). Probably its timeout somewhere. Response should be cloused only when OnComplete event fires.

```
@Controller("/")
@Validated
public class HelloController {

    @Produces(MediaType.TEXT_EVENT_STREAM) // add 'application/stream+json'
    @Get("/hello/{name}")
    public Flux<Hello> hello(@NotBlank String name) {

        List<Hello> list = new ArrayList<>();

        list.add(new Hello("test1", 1));
        list.add(new Hello("test2", 2));

        return Flux.fromIterable(list).doOnComplete(() -> {
            System.out.println("response should be closed here!");
        });
    }
}
```
-Also please add support for the application/stream+json content-type
-And support server side events for a client via Flux.

**Comment by graemerocher** [comment]
The content type `application/stream+json` is not an official media type. There is a draft attempting to registering this type but it relates to activity streams https://tools.ietf.org/id/draft-snell-activity-streams-type-01.html

The test https://github.com/micronaut-projects/micronaut-core/commit/b71f63aa8f2b2f00bdcbc25e60d9112321d8f003#diff-29dce542bb2e6326257895b376220c1aR16

Demonstrates your use case implemented with `MediaType.APPLICATION_JSON_STREAM` which is of type `application/x-json-stream`

As for why chrome keeps spinning this is because Micronaut implements keep alive and keeps the connection alive to satisfy further requests

**Comment by akozel** [comment]
> As for why chrome keeps spinning this is because Micronaut implements keep alive and keeps the connection alive to satisfy further requests

What kind of requests do you mean? I think that there is no sense to keeps the connection alive when Flux doOnComplete event fired.

If we need endless connection we can use EmitterProcessor to provide endless stream with some messages published. However, in this case too, the thread will end when the event doOnComplete is triggered. What's the use of keeping the connection?

**Comment by graemerocher** [comment]
The default for HTTP 1.1 and above is if `Connection: close` is not specified by the client to keep the connection alive until the client explicitly closes the connection. The connection will automatically timeout or be closed when the client closes the connection.

It is correct however that `@Client` doesn't currently support streaming json with `Flux`. We will look at implementing this for M2

**Comment by akozel** [comment]
I tried both headers `Connection: keep-alive` and `Connection: close`. Connection is open until clients timeout (1 minute). Please check Spring WebFlux example. Bouth `Connection: keep-alive` method `flux` emmits element from list and closes connection. But `fluxInterval ` provides endless connection. I really like this way:

```
@RestController
public class PersonResource {

    List<Person> list = new ArrayList<>();

    PersonResource() {
        list.add(new Person("Timmy", 12));
        list.add(new Person("Alex", 33));
        list.add(new Person("John", 24));
        list.add(new Person("Bob", 52));
    }

    @GetMapping(path = "/flux", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    @ResponseBody
    public Flux<Person> flux() {
        return Flux.fromIterable(list);
    }

    @GetMapping(path = "/endless", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    @ResponseBody
    public Flux<Person> fluxInterval() {
        EmitterProcessor<Person> emitterProcessor = EmitterProcessor.create();
        Flux<Long> intervalFlux = Flux
                .interval(Duration.ofMillis(500))
                .doOnNext(interval -> {
                    emitterProcessor.onNext(list.get(ThreadLocalRandom.current().nextInt(0, 4)));
                });
        return intervalFlux.zipWith(emitterProcessor.checkpoint(), (interval, person) -> person);
    }


    public class Person {
        public String name;
        public Integer age;
        
        Person(String name, Integer age) {
            this.name = name;
            this.age = age;
        }
    }
}
```
