### ISSUE TITLE
micronaut-openapi:jar:1.2.3 dependency missing for Micronaut version 1.2.3

### ISSUE THREAD

**Issue by nilogarcia** [micronaut-projects/micronaut-core#2220]
### Steps to Reproduce

    Use the cli to generate a new app with the swagger feature enabled:
`mn create-app micronaut-openapi-test --features junit,swagger-java --lang=java --build maven`

    Run:
`mvn clean package`

### Expected Behaviour

Build should be successful.

### Actual Behaviour

Maven build fails with a missing dependency issues:

[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ micronaut-openapi-test ---
Downloading from jcenter.bintray.com: https://jcenter.bintray.com/io/micronaut/micronaut-inject-java/1.2.3/micronaut-inject-java-1.2.3.jar
Downloaded from jcenter.bintray.com: https://jcenter.bintray.com/io/micronaut/micronaut-inject-java/1.2.3/micronaut-inject-java-1.2.3.jar (0 B at 0 B/s)
Downloading from jcenter.bintray.com: https://jcenter.bintray.com/io/micronaut/micronaut-inject-java/1.2.3/micronaut-inject-java-1.2.3.pom
Downloaded from jcenter.bintray.com: https://jcenter.bintray.com/io/micronaut/micronaut-inject-java/1.2.3/micronaut-inject-java-1.2.3.pom (0 B at 0 B/s)
Downloading from jcenter.bintray.com: https://jcenter.bintray.com/io/micronaut/configuration/micronaut-openapi/1.2.3/micronaut-openapi-1.2.3.pom
Downloading from central: https://repo.maven.apache.org/maven2/io/micronaut/configuration/micronaut-openapi/1.2.3/micronaut-openapi-1.2.3.pom
[WARNING] Missing POM for io.micronaut.configuration:micronaut-openapi:jar:1.2.3
Downloading from jcenter.bintray.com: https://jcenter.bintray.com/io/micronaut/configuration/micronaut-openapi/1.2.3/micronaut-openapi-1.2.3.jar
Downloading from central: https://repo.maven.apache.org/maven2/io/micronaut/configuration/micronaut-openapi/1.2.3/micronaut-openapi-1.2.3.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.126 s
[INFO] Finished at: 2019-10-11T08:15:22-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project micronaut-openapi-test: Resolution of annotationProcessorPath dependencies failed: Missing:
[ERROR] ----------
[ERROR] 1) io.micronaut.configuration:micronaut-openapi:jar:1.2.3
[ERROR]
[ERROR]   Try downloading the file manually from the project website.
[ERROR]
[ERROR]   Then, install it using the command:
[ERROR]       mvn install:install-file -DgroupId=io.micronaut.configuration -DartifactId=micronaut-openapi -Dversion=1.2.3 -Dpackaging=jar -Dfile=/path/to/file
[ERROR]
[ERROR]   Alternatively, if you host your own repository you can deploy the file there:
[ERROR]       mvn deploy:deploy-file -DgroupId=io.micronaut.configuration -DartifactId=micronaut-openapi -Dversion=1.2.3 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR]
[ERROR]   Path to dependency:
[ERROR]         1) io.micronaut:micronaut-inject-java:jar:1.2.3
[ERROR]         2) io.micronaut.configuration:micronaut-openapi:jar:1.2.3
[ERROR]
[ERROR] ----------
[ERROR] 1 required artifact is missing.
[ERROR]
[ERROR] for artifact:
[ERROR]   io.micronaut:micronaut-inject-java:jar:1.2.3
[ERROR]
[ERROR] from the specified remote repositories:
[ERROR]   jcenter.bintray.com (https://jcenter.bintray.com, releases=true, snapshots=true),
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] Path to dependency:
[ERROR]         1) io.micronaut:micronaut-inject-java:jar:1.2.3
[ERROR]
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

### Environment Information

- **Micronaut Version:** 1.2.3
- **JDK Version:** JDK 13

**Comment by graemerocher** [comment]
The latest versions if openapi is 1.2.2 seems the generated template is wrong
