### ISSUE TITLE
multitenancy not resolving tenant from httpFilter

### ISSUE THREAD

**Issue by rkimaoui** [micronaut-projects/micronaut-core#2226]
I followed the example from this guide:
https://guides.micronaut.io/micronaut-multitenancy-propagation/guide/index.html

But the tenant is not resolving from the httpFilter.
Micronaut version: 1.2.3

TenantFilter:

```groovy

@Filter("/**")
class TenantFilter extends OncePerRequestHttpServerFilter {

    private static final Logger LOG = LoggerFactory.getLogger(TenantFilter.class)

    @Inject
    TenantResolver tenantResolver

    @Override
    protected Publisher<MutableHttpResponse<?>> doFilterOnce(HttpRequest<?> request, ServerFilterChain chain) {
        try {
            tenantResolver.resolveTenantIdentifier()
        } catch (TenantNotFoundException e) {
            e.printStackTrace()
            return Publishers.just(HttpResponse.seeOther(URI.create("/tenant")))
        }
        return chain.proceed(request)
    }

```

I get this exception:
`io.micronaut.multitenancy.exceptions.TenantNotFoundException: Tenant could not be resolved outside a web request`

**Comment by graemerocher** [comment]
I imagine this is down to the ordering of the filters. Currently tenant filter doesn't supply an order it is as position 0 so you would have to make your filter run after the tenant filter

**Comment by jameskleeh** [comment]
Tenant resolution relies on the https://github.com/micronaut-projects/micronaut-core/blob/master/http-server/src/main/java/io/micronaut/http/server/context/ServerRequestContextFilter.java, so your filter will have to be executed after.
