### ISSUE TITLE
Micronaut + GraalVM windows 

### ISSUE THREAD

**Issue by jeag2002** [micronaut-projects/micronaut-core#2247]
Hello

I'm really new with this technology; and i want to explore the possibilities of Micronaut in conjunction with GraalVM (native image); in a windows environment

First to say; i perfectly know that GraalVM windows is in experimental stage yet; and would probably solve in a future releases; but sincerelly i don't understand why this error happens; and i don't know how to avoid or how to patch it

Environment:

Windows 10 Professional Edition (clean installation)
Micronaut 1.2.1
Windows SDK 7.1 (Net 4.0) (i remove all previous windows studio 10.0 references, before installing this SDK)
Eclipse 2019-06 (4.12)
Oracle JDK 1.8.0 212
GraalVM CE 19.1.1 

I created a simple microservice through http (port 8082) where simply connect to a remote host (through http); get the result and print in the client....

You can see the code here: https://github.com/jeag2002/TestMicronautGraalVM/tree/master/graal

The problem is generated when it's compiled with graalVM to get a native executable; 

In one of the steps, the following instruction:

HttpClient client = HttpClient.create(new java.net.URL(URL));

throw the following warning in the native image creation tool...

com.oracle.svm.hosted.FallbackFeature$FallbackImageRequest: Aborting stand-alone image build. Class initialization of io.netty.handler.ssl.JdkSslContext failed. Use the option --initialize-at-run-time=io.netty.handler.ssl.JdkSslContext to explicitly request delayed initialization of this class.
Detailed message:
[...]
Caused by: java.lang.Error: failed to initialize the default SSL context

Exception reproduced later when run the application; and browse the following url:

http://localhost:8082/rtbdispatcher/rtb/271

who do this response:

{"message":"Internal Server Error: failed to initialize the default SSL context"}

I don't understand why micronaut need to initalize SSL context, if i am working all the time with http urls....

I do tons of configurations that i find via internet, with no success...

Obvious to say if the application run as a standalone micronaut java application (/gradlew run); the microservice works perfectly    

Can you help me?... Have any idea why it's happens? ....

Thanks in advance....

**Comment by graemerocher** [comment]
I am unsure of the answer to this question, but it does seem more like a GraalVM native related question. My suggestion is you take it to https://gitter.im/graalvm/native-image where you can post questions regarding native image utilization and errors like this. Thanks.

**Comment by jeag2002** [comment]
Hello graemerocher

Yes, i know that seems more a graalvm native-image than a micronaut error;

Anyway i don't understand some internal workarounds of micronauts... for example why micronaut need to load a SSL context when i create a httpClient connection (httpClient is one class of your framework; io.micronaut.http.client.HttpClient)  if i am using http protocol all the time...  

I have been checking tons of configurations, trying to disable the ssl context without success ...
(
you can see for example my application.yml 
graal/src/main/resources/application.yml; in my repository 
https://github.com/jeag2002/TestMicronautGraalVM/tree/master/graal
)

Thanks for all
