### ISSUE TITLE
Micronaut non-GET endpoint at / overrides index.html serving at /

### ISSUE THREAD

**Issue by swaechter** [micronaut-projects/micronaut-core#2257]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github: 
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new Micronaut application
2. Add a static HTML page called `public/index.html` + configure it as static resource (Provides  GET / ). This index.html contains a file upload to POST / and serves as the main & only page of the web application
3. Add a controller that handles the POST / file upload
4. Compile and run
5. Navigate to GET / and try to upload a file via the web formular --> You'll get a 405: Method not supported (I guess a POST/PUT/DELETE etc action overrides the static resource handling at this endpoint like the GET of index.html)

### Expected Behaviour

5. Navigate to GET / and see the upload HTML page
6. Upload the file
7. See the result handled by the POST / controller action

My observations:

* It looks like as soon you define a non-GET endpoint for /, the static resource at / can't be served anymore
* Possible workaround: Use a server side render engine to serve a vanilla HTML page for GET / --> Personally I think this is an overkill, because Micronaut is so lean & fast. I don't want SSR back.

IMO: Serving a static resource shouldn't be overriden by an action that serves the same endpoint as long as the action is not a GET one.

### Actual Behaviour

5. Navigate to GET / and try to upload a file via the web formular --> You'll get a 405: Method not supported

### Environment Information

- **Operating System**: Linux Debian Testing x64
- **Micronaut Version:** 1.2.1
- **JDK Version:** 11.0.2" 2019-01-15

### Example Application

- Example repository (Change the endpoint name for the POST / controller to let's say /foo and the example will work (Change it in the controller + index.HTML): https://github.com/swaechter/micronaut-file-upload-problem

**Comment by jameskleeh** [comment]
This is by design. We don't know if there is a resource available to be served before the logic that handles the 405 response. Routes have priority over static resources. You can render the static resource without a server side rendering engine.

```
        Optional<URL> optionalUrl = resourceResolver.resolve("classpath:static/index.html");
```

I would then map the `URL` to a `StreamedFile` and return that from your controller

**Comment by swaechter** [comment]
Thank you very much for the fast & helpful response, This makes of course sense. 

For other people running into the same "problem":

1.) Disable the static resource mappin in the application.yml

2.) Change the controller (I moved the index.html file):

```
@Controller
public class FileController {

    private static final Logger logger = LoggerFactory.getLogger(FileController.class);

    @Get
    public StreamedFile showIndexPage() {
        // TODO: Handle situations where Optional.get() isn't present
        ClassPathResourceLoader loader = new ResourceResolver().getLoader(ClassPathResourceLoader.class).get();
        Optional<URL> resource = loader.getResource("classpath:index.html");
        return new StreamedFile(resource.get());
    }

    @Post
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public void handleFileUpload(CompletedFileUpload fileToUpload) {
        logger.info("A user just uploaded a file: " + fileToUpload.getFilename() + " with the size " + fileToUpload.getSize());
    }
}
```
