### ISSUE TITLE
Redirect loses headers

### ISSUE THREAD

**Issue by xpusostomos** [micronaut-projects/micronaut-core#2258]
It seems like if  the response to a GET is a redirect, then the auto-redirect loses the headers you've set.

So let's say I'm doing a GET and setting the Accept header:

```
def nsl = HttpClient.create(grailsApplication.config.getProperty('biodiversityURL').toURL()).toBlocking()
HttpRequest request = HttpRequest.GET(namelink).accept(MediaType.TEXT_JSON_TYPE)
HttpResponse<String> resp = nsl.exchange(request, String)
```

If that URL redirects to a 2nd URL and that 2nd URL gives back a different response depending on your Accept: header, then that 2nd URL doesn't receive the Accept: text/json header. So in this case I get back HTML, when I should have got back JSON.

I've verified this is the case a number of ways, including using curl.

I can get around it by manually following the redirect, but this shouldn't be necessary:

```
        DefaultHttpClientConfiguration config = new DefaultHttpClientConfiguration()
        config.setFollowRedirects(false)
        def nsl = new DefaultHttpClient(grailsApplication.config.getProperty('biodiversityURL').toURL(), config).toBlocking()
        HttpRequest request = HttpRequest.GET(namelink).accept(MediaType.TEXT_JSON_TYPE)
        HttpResponse<String> resp = nsl.exchange(request, String)
        if (resp.status.code == 303) {
            request = HttpRequest.GET(resp.getHeaders().get("Location")).accept(MediaType.TEXT_JSON_TYPE)
            resp = nsl.exchange(request, String)
        }
```

Expected result:
If I set a header on a request, such as the Accept: header, then the header should get passed to any redirects with auto follow that are encountered.

Actual result:
Header seems to be only passed to the first leg in the redirect sequence.

**Comment by puneetbehl** [comment]
@xpusostomos I tried to reproduce. the problem but it seems to be working fine, see `RedirectControllerSpec` in the attached sample application.

[sampleapp.zip](https://github.com/micronaut-projects/micronaut-core/files/3891178/sampleapp.zip)

**Comment by xpusostomos** [comment]
Hi,
Looking at your source code, it doesn't look like a valid test to me because on the server side, it always produces the same result regardless of your accept header - aka JSON. It's just your client side which is interpreting the result differently.
```
client.toBlocking().exchange(HttpRequest.GET("/redirect/test")
                .accept(MediaType.TEXT_PLAIN_TYPE), String)
        then:
        response.getBody().get() == "{\"title\":\"The Stand\"}"
```

That looks like JSON to me, so you're still getting JSON with a test/plain accept header.
For example, here's a real life, on the internet example of a URL that (with redirects) produces 2 different results depending on accept header:

https://id.biodiversity.org.au/name/apni/105906

You can also see the json output by appending a .json:

https://id.biodiversity.org.au/name/apni/105906.json

However the first URL also produces JSON with the appropriate accept header:
 curl -L -g -H 'Accept: application/json' https://id.biodiversity.org.au/name/apni/105906

If you can write sample code that gets JSON from https://id.biodiversity.org.au/name/apni/105906with an Accept: application/json header, then you'll have a valid test case.
I made a little change to your test case:
       ```
void "test redirect response with TEXT_PLAIN"() {

        given:
        HttpClient client = HttpClient.create(embeddedServer.getURL())

        when: "Accept: application/json"
        HttpResponse response = client.toBlocking().exchange(HttpRequest.GET("https://id.biodiversity.org.au/name/apni/105906")
                .accept(MediaType.APPLICATION_JSON_TYPE), String)

        then:
        response.status() == HttpStatus.OK
        response.getBody().isPresent()
        response.getBody().get() == "The Stand"

        cleanup:
        client.close()
```

And then I looked at the output of why it failed. The result it got back is HTML, not json. And as you can see from the above curl statement, that URL does indeed respond with JSON when you give the application/json accept header and follow redirects.
