### ISSUE TITLE
Live mode freezing when creating app with groovy feature

### ISSUE THREAD

**Issue by Solido** [micronaut-projects/micronaut-core#226]
Thanks for reporting an issue for Micronaut, please review the task list below before submitting the
issue. Your issue report will be closed if the issue is incomplete and the below tasks not completed.

### Steps to Reproduce

1. Enter live mode with mn
1. 'create-app hello-world --features groovy'

### Expected Behaviour

Create an app

### Actual Behaviour
Freeze then Ctrl+C -> | Stopping build. Please wait...
Can't leave live mode

### Environment Information

- **Operating System**: OSX
- **Micronaut Version:** 1 M1
- **JDK Version:** 1.8.0_131-b11

**Comment by graemerocher** [comment]
Can't personally reproduce this

**Comment by Solido** [comment]
Direct input is working only live mode freeze. 
Can reproduce each time. Let me know if I can help with some logs.

**Comment by jameskleeh** [comment]
@Solido There really isn't much logging to look at for the CLI. I would recommend debugging it with the standard remote debug options: `export MN_OPTS="-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"`. If you find the cause let us know
