### ISSUE TITLE
Support multiple headers with same name

### ISSUE THREAD

**Issue by luckyswede** [micronaut-projects/micronaut-core#2262]
Currently the Micronaut http client removes all but one header entries with the same name, and Controllers do not support injecting a list of values from multiple headers with the same name.

Here is a PR that fixes both cases: https://github.com/micronaut-projects/micronaut-core/pull/2261/

I can see that the Travis build failed, however the same gradle commands "work on my machine" ;), I'm not sure how to fix that?

**Comment by graemerocher** [comment]
Thanks for the contribution!
