### ISSUE TITLE
Add support for reading a raw url encoded body

### ISSUE THREAD

**Issue by svishnyakoff** [micronaut-projects/micronaut-core#2263]
I expect that once I use `HttpRequest` as controller argument I have full control under incoming request. At the very least I should be able to get request body as String irrespective of the underline request format

```groovy
    void "test form media type request"() {
        given:
        HttpClient client = HttpClient.create(embeddedServer.getURL())

        when:
        def result = client.toBlocking().retrieve(HttpRequest.POST("/media/form", "success")
                                                          .contentType(MediaType.APPLICATION_FORM_URLENCODED_TYPE))

        then:
        result == "success"
    }

    @Controller(value = '/media/form', consumes = MediaType.APPLICATION_FORM_URLENCODED, produces = MediaType.TEXT_PLAIN)
    static class FormController {

        @Post
        String respose(HttpRequest<String> body) {
            return body.getBody(String).get()
        }
    }
```

> 14:18:44.048 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
14:18:47.219 [multithreadEventLoopGroup-3-1] DEBUG i.m.http.client.DefaultHttpClient - Sending HTTP Request: POST /media/form
14:18:47.219 [multithreadEventLoopGroup-3-1] DEBUG i.m.http.client.DefaultHttpClient - Chosen Server: localhost(33533)
14:18:47.220 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - Content-Type: application/x-www-form-urlencoded
14:18:47.220 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - host: localhost:33533
14:18:47.221 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - connection: close
14:18:47.221 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - content-length: 7
14:18:47.221 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - Request Body
14:18:47.221 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - ----
14:18:47.221 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - success
14:18:47.221 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - ----
14:18:47.333 [nioEventLoopGroup-1-2] ERROR i.m.h.s.n.c.UnsatisfiedRouteHandler - POST /media/form (Bad Request): Required argument [HttpRequest body] not specified
14:18:47.423 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - HTTP Client Response Received for Request: POST http://localhost:33533/media/form
14:18:47.423 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - Status Code: 400 Bad Request
14:18:47.423 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - Date: Tue, 22 Oct 2019 18:18:47 GMT
14:18:47.423 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - content-type: application/json
14:18:47.423 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - content-length: 138
14:18:47.423 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - connection: close
14:18:47.423 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - Response Body
14:18:47.423 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - ----
14:18:47.423 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - {"message":"Required argument [HttpRequest body] not specified","path":"/body","_links":{"self":{"href":"/media/form","templated":false}}}
14:18:47.423 [multithreadEventLoopGroup-3-1] TRACE i.m.http.client.DefaultHttpClient - ----

io.micronaut.http.client.exceptions.HttpClientResponseException: Required argument [HttpRequest body] not specified

	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1747)
	at io.micronaut.http.client.DefaultHttpClient$10.channelRead0(DefaultHttpClient.java:1686)

**Comment by jameskleeh** [comment]
As I said in Gitter, `success` is not a valid URL encoded body and thus it cannot be decoded. Once you supply a valid body, the other issue will be that there is no built in way to convert a `Map` (already decoded request body) into a `String`. You could simply update your controller to take a `Map` and send a valid body and all would work as you expect.

**Comment by svishnyakoff** [comment]
I am reading micronaut documentation and it states that if I want more control over incoming request I can get it by using HttpRequest on controller. Based on test it is not true. So it is either mistake in the documentation or undocumented corner case or bug within code.

The scenario when dev would like to read incoming request body as a String is quite common. And workaround with Map is not really nice - it is still workaround not a solutio

**Comment by jameskleeh** [comment]
You’re statement that you can’t get the request is false. You can. The
reason it’s not working in your example is because the body is invalid. You
could argue that the request should bind anyways but you are setting an
explicit generic for the body. Using HttpRequest<Map> works, so it is
possible to bind to the request.

**Comment by svishnyakoff** [comment]
I didn't say that I `can’t get the request` or it is taken our of context. Anyway, HttpRequest does not give me full control over request. I want to read request as a String even if its not really correct from `APPLICATION_FORM_URLENCODED_TYPE` perspective, it is correct from type perspective.

I do think that it is bug that Micronaut does any kind of decoding in a first place for HttpRequest<String> argument. IMHO decoding is needed only if you want to bind body arguments to controller param. Another scenario when decoding is needed when you want to deserialize body to some container object (Map, List, etc).

On other side `String, InputStream, byte array and may be some other` should be exclusion as they are a raw representation of incoming request body, they are not bound to controller params and should not be decoded/deserialized. What is the point to deserialize raw incoming request?

**Comment by jameskleeh** [comment]
> I do think that it is bug that Micronaut does any kind of decoding in a first place for HttpRequest argument

It definitely isn't. That is the intended design.

> What is the point to deserialize raw incoming request anyway?

Because the vast majority of use cases do not want to be responsible for deserializing the body. For example you could do `HttpRequest<Person>` to have the body deserialized into a `Person` object.

**Comment by graemerocher** [comment]
This does seem like a bug / incorrect behaviour to me. Doing `HttpRequest<String>` should not be doing any kind of decoding, it should just read the raw body into a string. I believe this would be consistent with how `@Body String body` behaves.

**Comment by svishnyakoff** [comment]
@graemerocher I might be wrong but last time I checked `@Body String body` did not work for me either. And I though it is expected bahaviour for `@Body` params after reading annotations javadoc

> An annotation that can be applied to method argument to indicate that the method argument is bound from the HTTP body. 

When I read it my understanding was that micronaut will try to decode request body and bind a field from the body.

**Comment by graemerocher** [comment]
so you are able to receive the raw JSON if you use `@Body String body`, you can see this here:

https://github.com/micronaut-projects/micronaut-core/blob/593a51bc0edc51edd818bcb8f66fdf9422699bd3/http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/JsonBodyBindingSpec.groovy#L115

If that doesn't work the same for form data then IMO it would be a bug.
