### ISSUE TITLE
Nats.io integration proposal

### ISSUE THREAD

**Issue by grimmjo** [micronaut-projects/micronaut-core#2265]
Hi,

I started working on an integration of [nats.io](https://nats.io/) into the micronaut environment.
The basic functionality with publish and subscribe is already working.

Is there a chance to integrate the repository in the micronaut organization to get further support for developing it.

This is the repository: https://github.com/grimmjo/micronaut-nats.

**Comment by graemerocher** [comment]
@grimmjo nice work! We can certainly consider adding this to the `micronaut-projects` organization and adding you are a collaborator there. The Micronaut team itself doesn't really have any nats.io experience however, we can collaborate in Micronaut related best practises, but would need guidance from yourself and the nats.io community on taking the project forward. Does that make sense?

**Comment by graemerocher** [comment]
next step would be to fork it to `micronaut-projects` and add you as an external collaborate. That is how we have operated with other projects. @marceloverdijk  for example maintains the GraphQL integration. We can then setup the release process. I suggest you connect with me on Gitter https://gitter.im/micronautfw/Lobby where we can discuss the rest
