### ISSUE TITLE
Allow Environments to "include" other environments.

### ISSUE THREAD

**Issue by bangroot** [micronaut-projects/micronaut-core#2268]
Allow Environments to "include" other environments, similar to how spring-boot allows profiles to specify other active profiles: https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-adding-active-profiles

Mainly, I looking to be able to "compose" flags for my environment. An easy example would be a `TokenGenerator` with 2 implementations: `FixedTokenGenerator` and `RandomTokenGenerator` which are switched out using `@Requires(env = 'fixed-tokens')` and `@Requires(notEnv = 'fixed-tokens')` annotations, respectively.

Then, as I move through my environments, `local` -> `test` -> `dev` -> `stage` -> `prod`, my environment specific configuration file `application-<env>.yml` can include a simple set of flags to turn on/off features, such as:

```
micronaut:
  environments:
    - fixed-tokens
    - bypass-sms
    - enable-reset-db-controller
```

This is not earth shattering, just a nice little touch I appreciated about spring-boot.

**Comment by jameskleeh** [comment]
I think you could just as easily use `@Requires(property = "fixed-tokens", value = StringUtils.TRUE)`

Then in your config `application-env.yml`

```
fixed-tokens: true
```

**Comment by jameskleeh** [comment]
Because environments is what informs config this would require much more complexity in the configuration system. Given there is an easy path forward for your use case I vote to close.

**Comment by bangroot** [comment]
🤦‍♂ Good point. Perfectly suited to my need.
