### ISSUE TITLE
Document Startup time Fix for OS X

### ISSUE THREAD

**Issue by Solido** [micronaut-projects/micronaut-core#227]
### Steps to Reproduce

1. mn create-app hello-world --features groovy
2. ./gradlew run to load dependencies -> INFO  io.micronaut.runtime.Micronaut - Startup completed in **152272ms**.
3. Close and restart : Startup completed in **152313ms**

### Expected Behaviour

Faster startup time

### Environment Information

- **Operating System**:  OSX 10.13.3 8Go macbook pro
- **Micronaut Version:** 1 m1
- **JDK Version:** 1.8.0_131-b11

**Comment by graemerocher** [comment]
Duplicates #172
