### ISSUE TITLE
Please open a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [micronaut-projects/micronaut-core#2273]
I believe I've found a security vulnerability. Please open a security advisory.

https://github.com/micronaut-projects/micronaut-core/security/advisories

**Comment by graemerocher** [comment]
Please could you email info@micronaut.io with the information so that we have the opportunity to publish mitigation/fixes along with the advisory so that users are not left vulnerable if said vulnerability is valid. Thanks

**Comment by graemerocher** [comment]
I see you can collaborate on these privately so I have opened a draft one

**Comment by graemerocher** [comment]
Closing this as this is in process
