### ISSUE TITLE
@Produces / @Consumes switch prevents general goal of declarative client

### ISSUE THREAD

**Issue by diamondq** [micronaut-projects/micronaut-core#2274]
An `@Produces` (similarly `@Consumes`, but I'll stop repeating both) on a server interface indicates that the method 'returns' a specific type from the server. Based on the comments in #631, it appears that it's intended that an `@Produces` on a client interface indicates that the method accepts a specific type for its parameters. 

However, the documentation examples for declarative clients seem pretty clear that the goal is that you can define an 'uber' interface, that defines a method once and use it in both an `@Client` and a `@Controller`. This obviously wouldn't work, since the `@Produces` would change meanings.

```java
public interface PetOperations {
    @Post
    @Produces("text/xml")
    Single<Pet> save(@NotBlank String name, @Min(1L) int age);
}
@Controller("/pets")
public class PetController implements PetOperations {

    @Override
    public Single<Pet> save(String name, int age) {
   ...
@Client("/pets") 
public interface PetClient extends PetOperations { 

    @Override
    Single<Pet> save(String name, int age); 

```
It would seem that either
* the documentation needs to explicitly show that the controller must provide its own `@Produces` and the `@Client` needs to have a corresponding `@Consumes`, and NOT define it in the common interface (although this does get messy (impossible?) when you are using the produces/consumes in the `@Post` annotation, and not the separate annotation). It would seem that if this is the direction taken, then the produces and consumes should be removed from the `@Post`/`@Get`, etc. as their not meaningful in this case.
* OR the assumption is that the `@Produces` always has the meaning for a server, and the declarative client needs to internally flip the meaning during runtime.

### Environment Information

- **Micronaut Version:** 1.2.5

**Comment by jameskleeh** [comment]
> you can define an 'uber' interface, that defines a method once and use it in both an @Client and a @Controller. This obviously wouldn't work, since the @Produces would change meanings.

It does work, however the produces and consumes would need to be put in the client/server classes instead of the interface.

> the documentation needs to explicitly show that the controller must provide its own @Produces and the @Client needs to have a corresponding @Consumes, and NOT define it in the common interface

Could you please point out the specific parts of the documentation that should be improved?

> then the produces and consumes should be removed from the @Post/@Get, etc. as their not meaningful in this case.

They are meaningful when used directly on a server/client instead of an interface for both

**Comment by diamondq** [comment]
In order to improve the docs, I'd suggest the following:

* In the main section (https://docs.micronaut.io/latest/guide/index.html#clientAnnotation), there is a statement
> Note how the interface uses Micronaut’s HTTP annotations which are usable on both the server and client side.

I would expand this with something similar to 
> Most annotations are symmetric between client and server, but some annotations such as `@Produces` and `@Consumes` are 'side' specific. For example, `@Produces` on a server indicates how the server method return value is formatted, while `@Produces` on a client indicates how the parameters are formatted when sent to the server.

* In the SSE section (https://docs.micronaut.io/latest/guide/index.html#_streaming_server_sent_events), the use of `@Get(produces)` is incorrect. By the use of just a produces element, it's actually saying that the method produces is `text/event-stream` but the consumes is `application/json`, while the `@Client` use of `processes` means that it produces and consumes `text/event-stream`. While it works in this case since the method `streamHeadlines` takes no parameters, if someone added a parameter, it would break, since the client would sent it as text, and the server would expect it as JSON. I'd suggest changing it to `processes` in both cases, and add a statement:
> If the Media Type is the same for both incoming parameters and outgoing return types (which is fairly common), then use `processes` or `single` annotations to allow the same code to be used on both the client and server sides.

**Comment by jameskleeh** [comment]
@diamondq Thanks for the feedback! Those seem like valuable changes to me. I encourage you to submit a PR with the changes, otherwise we will get to it when we can.
