### ISSUE TITLE
Validation of the @Positive  should handle long values

### ISSUE THREAD

**Issue by borjab** [micronaut-projects/micronaut-core#2275]
I have found an unexpected error validating long values in Rest parameters.

Steps to reproduce: 
- Created a rest interface with positive parameter:
			@Nullable @QueryValue("until_epoch") @Positive Long untilEpoch);
- Called with parameter   /orders?until_epoch=1554190699984"
- Returned an error:   "message": "untilEpoch: must be greater than 0"

I have found the problematic code in [DefaultConstraintValidators](https://github.com/micronaut-projects/micronaut-core/blob/master/validation/src/main/java/io/micronaut/validation/validator/constraints/DefaultConstraintValidators.java) of the Validation module. The code unbox to int even if the value may be long.

```java
    private final ConstraintValidator<Positive, Number> positiveNumberValidator =
            (value, annotationMetadata, context) -> {
            // null is allowed according to spec
            return value == null || value.intValue() > 0;
        };
```
The same can be said to the PositiveOrZero, Negative and NegativeOrZero annotations.

This seems easy to change and I may make a pull request soon

**Comment by jameskleeh** [comment]
@borjab Please target the 1.2.x branch

**Comment by borjab** [comment]
@jameskleeh Pull request created. I hope everything is OK 

https://github.com/micronaut-projects/micronaut-core/pull/2278

**Comment by borjab** [comment]
Note that this bug not only affects longs but also other types:
-  A BigInteger bigger that Long.MAX_LONG would have been truncated to int
-  A double 0.1 will be rounded to 0 and will not be considered Positive nor -0.1 Negative
-  A new BigDecimal("0.1") will have the same problem
-  AtomicLong, AtomicDouble, LongAdder, LongAccumulator, DoubleAdder and DoubleAccumulator would have the same problem as it Long or Double type.

The pull request should fix all this cases.
