### ISSUE TITLE
Micronaut Validation fails on String types since they have not @Introspected annotation

### ISSUE THREAD

**Issue by saw303** [micronaut-projects/micronaut-core#2303]
The improvement issue https://github.com/micronaut-projects/micronaut-core/issues/2214 introduce a good fail fast feature in Micronaut 1.2.6. When a BeanIntrospection is missing the validator complains about it. This is good.

I have the following controller class with the method `getCollection` and a string parameter `q` that with a `NotNull` constraint. 

```java
@Controller("/v1/applications/{pin}/insurablePersons/{person}/houses")
@Validated
@Introspected
public class HousesResource {

  @Get
  @Produces("application/json")
  public Collection<HousesGetResourceModel> getCollection(@Valid @NotNull @QueryValue String q,
      String pin, String person) {
    return new ArrayList<HousesGetResourceModel>();
  }
}
```

When I call that end point in Micronaut 1.2.6 I get the following error message.

> getCollection.q: Cannot validate java.lang.String. No bean introspection present. Please add @Introspected to the class and ensure Micronaut annotation processing is enabled.

```
getCollection.q: Cannot validate java.lang.String. No bean introspection present. Please add @Introspected to the class and ensure Micronaut annotation processing is enabled
javax.validation.ConstraintViolationException: getCollection.q: Cannot validate java.lang.String. No bean introspection present. Please add @Introspected to the class and ensure Micronaut annotation processing is enabled
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:142)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at HousesResourceSpec.search for houses(HousesResourceSpec.groovy:41)
```

The problem now is that I cannot at `@Introspected` on a `java.lang.String`. AFAIK the https://github.com/micronaut-projects/micronaut-core/blob/v1.2.6/validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java#L711 is using the wrong `parameterType` for requesting the bean introspection. Instead of `String.class` shouldn't it use `HousesResource.class`?

**Comment by graemerocher** [comment]
The issue is the Valid annotation which hints at bean validation. Remove it and it will work

**Comment by saw303** [comment]
Good morning @graemerocher 

I did not manage to get it work. Add created a brand new Micronaut 1.2.6 application and pasted my controller code into it. Then I removed the `@Validation` annotation (see https://github.com/saw303/micronaut-validation-bug/blob/master/src/main/java/micronaut/validation/bug/HousesResource.java#L20).

The example repository can be found here. Simply start the Micronaut app and make an HTTP GET call to 

`http://localhost:8080/houses?q=`

Here is the error response a HTTP client gets.

```sh
➜ http http://localhost:8080/houses\?q\=
HTTP/1.1 400 Bad Request
Date: Thu, 7 Nov 2019 07:32:33 GMT
connection: close
content-length: 231
content-type: application/json

{
    "_links": {
        "self": {
            "href": "/houses?q=",
            "templated": false
        }
    },
    "message": "q: Cannot validate java.lang.String. No bean introspection present. Please add @Introspected to the class and ensure Micronaut annotation processing is enabled"
}

```

**Comment by saw303** [comment]
Sorry. I misunderstud your answer. All good.
