### ISSUE TITLE
Architecture Docs (internal?) 

### ISSUE THREAD

**Issue by akamanocha** [micronaut-projects/micronaut-core#2322]
This is in reference to Micronaut at large. And is an enhancement request not a bug.

Reference to this issue
micronaut-projects/micronaut-core#445

_Originally posted by @graemerocher in https://github.com/micronaut-projects/micronaut-core/issues/445#issuecomment-495755707_

@graeme suggested that there could be separate issue raised for creating architecture docs.

The rationale for the same could be:

It will give more contributors to the project, may be?, cause the consumers of this would be core developers / contributors at large and thus it's not just user guide.
It will also help in self led contribution from other projects let's say @nats_io for example who have expertise in their project but don't have heady start in micronaut.
It will give the good looking architecture diagram too :) in short
It will be a good nice back also to ASM, and APT
A random view on who should take this PR / do it?
I can also help, but I am not very well versed with ASM, and Annotation Processing (and I am not bringing the groovy and kotlin support here)
Individual effort so far have taken me to io.micronaut.annotation.processing. BeanDefinitionInjectProcessor just to build on, my idea is to reach to a component level diagram in the end with the explanation text of course, to give out the doc that how does the framework boots up.

**Comment by graemerocher** [comment]
I will spend some time starting of a draft of this soon. Maybe in a separate repo to the main docs initially

**Comment by akamanocha** [comment]
That's cool. Idea of different repo is good too. Initially short, and can be referenced back later with the main site. 

Again let me know if I can help in any which way.

**Comment by akamanocha** [comment]
@graemerocher 
I did add a simple story of my understanding on the inner workings
https://medium.com/@koolak82/micronaut-under-the-hood-d6a41566b2ca?sk=076c5d4ccb15c420022d00c62220a032

Might you have a look for correctness / improvements?

**Comment by timyates** [comment]
As of 3.3.2, we have an architecture appendix in the guide describing the inner workings 🎉 

https://docs.micronaut.io/latest/guide/index.html#architecture

**Comment by graemerocher** [comment]
soon turned out to be 3 years later, sounds about right 😂
