### ISSUE TITLE
Reduce reactive call stack

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#2338]
After adding `MdcInstrumenter` call I have noticed call stack is huge, nothing related to `MdcInstrumenter`.

Looks like `RxJava2Instrumentation` adds so many wrappers and each of them adding more `ReactiveInstrumenter`s. I have also noticed that in `RxJavaPlugins.setOnFlowableAssembly` the already wrapped instance is being wrapped again sometimes.

I would suggest adding a new interface with two methods, one to be called at the beginning and one at the end of the invocation:

```
    interface InstrumentInvocation {

        void beforeCall();

        void afterCall();
    }

    class ServerRequestContextInvocation implements InstrumentInvocation {

        final Optional<HttpRequest<Object>> httpRequest = ServerRequestContext.currentRequest();

        @Override
        public void beforeCall() {
            httpRequest.ifPresent(request -> ServerRequestContext.set(request));
        }

        @Override
        public void afterCall() {
            httpRequest.ifPresent(request -> ServerRequestContext.remove());
        }
    }

    void invokeRunnable(Runnable runnable, List<InstrumentInvocation> instrumentInvocations) {
        try {
            instrumentInvocations.forEach(InstrumentInvocation::beforeCall);
            runnable.run();
        } finally {
            instrumentInvocations.forEach(InstrumentInvocation::afterCall);
        }
    }
```

Most of the current instrumentations can be changed to use them instead of wrapping `Runner`.

**Comment by graemerocher** [comment]
Yeah improvements in this area would be welcome

**Comment by fabienrenaud** [comment]
Illustration:
![Screen Shot 2019-11-17 at 12 08 41 PM](https://user-images.githubusercontent.com/3112233/69013280-265f8e00-0933-11ea-8d2e-76922eed3c8e.png)
+ 6 extra or so calls before I get to the `micronaut.http.server` calls (which use overall 2.0% cpu in this call stack).

Some notes (for this call stack):
 * the reactive call stack takes 11% of cpu. Only about 2-3% are doing "useful" work (things I need).
 * the reactive call stack is as expensive as the netty channel read call stack (which itself is pretty inefficient too with half of cpu spent in `RequestArgumentSatisfier.fullfillArgumentRequirements`)

**Comment by graemerocher** [comment]
Thanks for the feedback. Yes that is why we are interesting is taking this pull request forward. But probably only in 1.3.x

As for the HTTP runtime. We are aware there are inefficiencies in it and it is an area for improvement. We should be higher in this list of benchmarks https://www.techempower.com/benchmarks/

**Comment by gnomeria** [comment]
Even in https://github.com/the-benchmarker/web-frameworks it's far below `Ktor 1.2`, and it only does simple http `get`,`post` tests in the controller. Are we gonna have separate issue to track the HTTP runtime performance improvements? Thanks

**Comment by graemerocher** [comment]
@gnomeria for simple text responses it is behind Ktor, but Ktor is much more low level and does not out of the box include support for things like distributed tracing, filters and so on. I doubt we will ever achieve parity there. However there are definite improvements we can make to get closer. When a more real world test is applied Micronaut does much better. For example Micronaut is 22nd for data updates https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=update and 9th for multiple queries https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=query

However yes it is on priority list to look at improving the performance and latency of the HTTP implementation.

**Comment by graemerocher** [comment]
@fabienrenaud could you provide the example that reproduces that reactive call stack? Thanks.

**Comment by fabienrenaud** [comment]
@graemerocher 
```
public class App {

  @Controller("/service")
  public static class Control {

    @Get
    public Single<A> get() {
      return Single.just(new A(1));
    }
  }

  static final class A {
    @JsonProperty("id")
    private final int id;

    public A(int id) {
      this.id = id;
    }
  }

  public static void main(String[] args) {
    Micronaut.run(App.class, args);
  }
}
```
That's enough to give me:
![Screen Shot 2019-11-22 at 8 09 54 AM](https://user-images.githubusercontent.com/3112233/69441444-9ab57b00-0cff-11ea-8d44-818303aa8341.png)
![Screen Shot 2019-11-22 at 8 10 21 AM](https://user-images.githubusercontent.com/3112233/69441451-9ee19880-0cff-11ea-8ba7-ae72158642a4.png)

That's with full instrumentation on jprofiler.
I'm running a little benchmark with `ab -c 10 -n 100000000 -k http://localhost:8080/service`

Running on micronaut 1.2.6
