### ISSUE TITLE
cli: upgrade to Gradle 6.0

### ISSUE THREAD

**Issue by jmfayard** [micronaut-projects/micronaut-core#2347]
### Steps to Reproduce

```bash 
$ mvn --version
Micronaut Version: 1.2.6
| JVM Version: 13.0.1
$ mn create-app hello-world
$ cd hello-world
$ ./gradle --version
```

### Expected Behaviour

Gradle 6.0 is used

### Actual Behaviour

Gradle 5.3 is used

# See also

Upgrading your build from Gradle 5.x to 6.0

https://docs.gradle.org/current/userguide/upgrading_version_5.html

**Comment by benrhine** [comment]
This will be resolved with PR https://github.com/micronaut-projects/micronaut-profiles/pull/202
