### ISSUE TITLE
Inefficient ArgumentUtils.requireNonNull

### ISSUE THREAD

**Issue by fabienrenaud** [micronaut-projects/micronaut-core#2351]
I profiled my Micronaut application and found out my 2nd biggest hotspot was caused by `ArgumentUtils.requireNonNull` and `StringBuilder.append` from the same method.

It's pretty obvious what's inefficient: https://github.com/micronaut-projects/micronaut-core/blob/master/core/src/main/java/io/micronaut/core/util/ArgumentUtils.java#L53

The app I am profiling performs no I/O besides handling request/response from client so it is very sensitive to such inefficiencies.

Using micronaut 1.2.6

**Comment by fabienrenaud** [comment]
<img width="913" alt="Screen Shot 2019-11-16 at 1 21 32 PM" src="https://user-images.githubusercontent.com/3112233/68999461-4c265d80-0875-11ea-8cb0-e972af011a03.png">
Hotspots with _full_ instrumention.

**Comment by graemerocher** [comment]
Thanks for the contribution!
