### ISSUE TITLE
Reduce Argument.of and ConversionContext.of call frequency for common types

### ISSUE THREAD

**Issue by fabienrenaud** [micronaut-projects/micronaut-core#2355]
`Argument.of(Class<T>)` creates a new instance of `DefaultArgument` on every call, which happens at least once on every request to fetch the content-type header (and others).
Methods in ConvertibleValues are also on some hot paths and invoke `Argument.of`+`ConversionContext.of` a lot

Possible solutions:
 *  ~Pool instances created by `Argument.of(Class<T>)`~ (only viable if the pooling solution is invoked rarely or is "shallow" and causes 0 alloc on read -- using a ConcurrentHashMap is not a solution).
 *  Optimize the few hot paths to use the `ConversionContext.of` or `Argument.of` constants where possible. 

There are several "hot" APIs that only expose a class type or argument type parameter when the final desired type is always (or almost) a ConversionContext. For services handling several thousands of requests per second, this may result in severe inefficiencies on the main code paths. The code base should be overhauled to promote usage of the type that performs the best at scale.

Micronaut 1.2.6

**Comment by graemerocher** [comment]
So anything else we can do to take this forward?

**Comment by fabienrenaud** [comment]
Several things:
 1. Change annotation processors to always generate (and use) the needed static `ConversationContext`  for bindables instead of relying on `Argument`. Constants in `Argument` class are apparently used by core generators but I haven't found them yet...
 2. Sweep the code base for any call using `Class`, or `Argument` and replace them with their `ConversionContext` equivalent where possible. This requires overloading some methods (e.g: flowable publishers).
 3. I think `Argument` and `ConversionContext` should either be consolidated; or `ConversationContext` dropped and `Locale` + `Charset` always passed as args separately...
