### ISSUE TITLE
Building Error with maven

### ISSUE THREAD

**Issue by kangzq0530** [micronaut-projects/micronaut-core#2359]
My project using microaunt 1.2.6 got a build time error with maven:
`Error:java: java.lang.NoSuchMethodError: io.micronaut.inject.writer.BeanDefinitionVisitor.visitSetterValue(Ljava/lang/Object;Ljava/lang/Object;Lio/micronaut/core/annotation/AnnotationMetadata;ZLjava/lang/Object;Ljava/lang/String;Ljava/util/Map;Lio/micronaut/core/annotation/AnnotationMetadata;Z)V` 
I think this is caused by some version mismatch in maven pom. Wish to be fixed soon.

**Comment by graemerocher** [comment]
Please provide an example. Most likely reason is you have incorrectly configured annotation processors.

**Comment by kangzq0530** [comment]
You are right, I just found the reason is micronaut-data-processor.1.0.0.M5 relies on micronaut 1.2.4, and I moved it‘s location to the last of the annotation processors and then everything is ok.Thanks for answer.

**Comment by graemerocher** [comment]
Interesting coincidence. I actually just fixed this problem so the CLI generates the processors in the right order https://github.com/micronaut-projects/micronaut-core/commit/a3260f3d3ccc694359493017ca7f648f316e6fa9
