### ISSUE TITLE
micronaut.config.files should be able to load configuration files from classpath

### ISSUE THREAD

**Issue by fedotxxl** [micronaut-projects/micronaut-core#2365]
Hello. Looks like micronaut.config.files unable to load configuration files from classpath. It's pretty important for me - classpath configuration contains global config for an app (which probably will not change on a server), server config files - server-specific configuration.

Configuration file order is also important. At the beginning most common config files (or vice versa), in the end - most specific. If configuration property is contained in both files the last one wins.

Working syntax from spring:

`--spring.config.location=classpath:/application.yml,/etc/my-app.yml`

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue. Here is a test in core that verifies this is supported https://github.com/micronaut-projects/micronaut-core/blob/master/inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy#L406

**Comment by fedotxxl** [comment]
yes, works as expected, my fault...
