### ISSUE TITLE
App should not start on invalid -Dmicronaut.config.files

### ISSUE THREAD

**Issue by fedotxxl** [micronaut-projects/micronaut-core#2366]
I specified invalid `-Dmicronaut.config.files=abc.yml` file path and app started without any warning. It may be pretty hard to detect this problem. App should not start in case of invalid `-Dmicronaut.config.files` value (invalid path, invalid syntax)

**Comment by graemerocher** [comment]
Thanks for the feedback, maybe you should consider submitting a PR? Code is here https://github.com/micronaut-projects/micronaut-core/blob/master/inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java#L633

**Comment by mickoallen** [comment]
not sure if you still want a pr for this or not
https://github.com/micronaut-projects/micronaut-core/pull/2384

**Comment by govi20** [comment]
@graemerocher is this issue is still relevant? or it's covered in #2384 
If yes, I would like to take this up.

**Comment by graemerocher** [comment]
The PR is there, but the CLA hasn't been signed, but of course if you can improve on it contributions welcome

**Comment by jameskleeh** [comment]
Closed by https://github.com/micronaut-projects/micronaut-core/commit/34d10e67a0ccbe1e24b89a6660edce4966f219d2
