### ISSUE TITLE
Could not start micronaut with env variables and default value in app properties

### ISSUE THREAD

**Issue by glaydsonarantes** [micronaut-projects/micronaut-core#2368]
### Environment Information

- **Operating System**: Fedora 31
- **Micronaut Version:** 1.2.6
- **JDK Version:** 11

### Example Application

`datasources:
  default:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/database}`

When env variable DATABASE_URL is not present, the application throws an error.

`Caused by: java.lang.IllegalArgumentException: Invalid JDBC URL [5432/database]. JDBC URLs must start with 'jdbc'.`

Expected behavior:
When DATABASE_URL is blank, the application should use the default property (in this example jdbc:postgresql://localhost:5432/database)

**Comment by ilopmar** [comment]
You need to scape the `:` in the url using backticks: https://docs.micronaut.io/latest/guide/index.html#_property_value_placeholders

Try with:
```
datasources:
  default:
  url: ${DATABASE_URL:`jdbc:postgresql://localhost:5432/database`}
```

**Comment by glaydsonarantes** [comment]
It works! :tada: 
Thanks!
