### ISSUE TITLE
Make all inner classes of @ConfigurationProperties property classes

### ISSUE THREAD

**Issue by fedotxxl** [micronaut-projects/micronaut-core#2373]
Please check the sample code:

```
@ConfigurationProperties("app")
@Getter
@Setter
public class MySettings {

    private DeepProperties pool = new DeepProperties();

    @ConfigurationProperties("pool") // <<< why should I annotate it?
    @Getter
    @Setter
    public static class DeepProperties {
        private int connectionTimeout;
    }
}
```

What's the reason for nested property `@ConfigurationProperties("pool")` annotation? Spring correctly works without it and I got bug after migrating a project from Spring to Micronaut

**Comment by graemerocher** [comment]
so Spring defaults inner classes to being nested configuration properties. A design decision on their part. What if you want an inner class that is not configuration properties?

**Comment by fedotxxl** [comment]
Sorry, I don't get your point...

Here is same working example from Spring:

```
@ConfigurationProperties("app")
@Getter
@Setter
public class MySettings {

    private DeepProperties pool = new DeepProperties();

    @Getter
    @Setter
    public static class DeepProperties {
        private int connectionTimeout;
    }
}
```

I don't see any problems with it. I thought you force to add `@ConfigurationProperties` on inner properties because of performance improvement but is it?

**Comment by graemerocher** [comment]
Currently yes we precompute the property paths at compilation time so the annotation is needed. However a larger question is what if you had another static inner class that was not configuration properties? Also how does one decide what the name of the properties are? Based on the class name? So `DeepProperties` becomes `deep`? That seems a stretch to enforce class naming on the user for the sake of not specifying the annotation.

It probably is technically possible to support this, but IMO we should not.

**Comment by fedotxxl** [comment]
`Also how does one decide what the name of the properties are? Based on the class name?`
Based on property name.

`However a larger question is what if you had another static inner class that was not configuration properties`
Can you provide an example where is it problem?

I still don't see any problems with Spring implementation.  Let's suppose I've got db connection properties and 2 databases. Here is Spring configuration:

```
@ConfigurationProperties("app")
@Getter
@Setter
public class MySettings {

    private ConnectionProperties myMainDb;
    private ConnectionProperties myOptionalDb;

    @Getter
    @Setter
    public static class ConnectionProperties {
        private int connectionTimeout;
    }
}
```

How can I do the same with Micronaut implementation? Something like this:
```
@ConfigurationProperties("app")
@Getter
@Setter
public class MySettings {

    private ConnectionProperties myMainDb;
    private ConnectionProperties myOptionalDb;

    @Getter
    @Setter
    public abstract static class ConnectionProperties {
        protected int connectionTimeout;
    }

    @Getter
    @Setter
    @ConfigurationProperties("myMainDb")
    public class MyMainDbConnectionProperties extends ConnectionProperties  {
    }

    @Getter
    @Setter
    @ConfigurationProperties("myOptionalDb")
    public class MyOptionalDbConnectionProperties extends ConnectionProperties  {
    }
}
```

When current implementation is better than Spring one? What's the problem with Spring one? Can you provide a code example? If current implementation compiles faster or runs faster than it's ok for me

**Comment by graemerocher** [comment]
Right, Spring uses reflection and so on to do what it does Micronaut computes the property paths and doesn't use reflection. However, we could probably support what you are after, so will note this down as a future improvement request. Thanks for the feedback.

**Comment by jameskleeh** [comment]
We can't rely on the field being there as it's not necessary for the bean to be created. It's often times injected into the constructor of the parent properties class. I don't see what the issue is with specifying the annotation. Not specifying forces all inner classes to be configuration and without a field there is no way to determine what the name would be. We could require a field or constructor parameter to exist but then this is getting way too complicated just for the sake of 1 less annotation. I vote to close

**Comment by jameskleeh** [comment]
Also its a breaking change

**Comment by yyvess** [comment]
As workaround you can do : 
   
    @ConfigurationBuilder(configurationPrefix = "myMainDb")
    private ConnectionProperties myMainDb = new ConnectionProperties();
   
   
    @ConfigurationBuilder(configurationPrefix = "myOptinalDb")
    private ConnectionProperties myOptionalDb = new ConnectionProperties();

    @Getter
    @Setter
    public static class ConnectionProperties {
        protected int connectionTimeout;
    }

**Comment by ratcashdev** [comment]
Took me quite some time until I found this issue. The workaround is OK, but this is something that needs to be put into the GUIDE as an example.
