### ISSUE TITLE
Feature Regression: Request not matching the closest mapping

### ISSUE THREAD

**Issue by mageddo** [micronaut-projects/micronaut-core#2375]
### Steps to Reproduce

1. Create the controller

```java
class PeopleController {

	@Get("/people/id-{personId}")
        HttpResponse m1(int personId){
          ...
	}

	@Get("/people/{personName}")
	HttpResponse m2(String personName){
          ...
        }
}
```

2. Try `curl -X GET localhost:8080/people/id-123`

### Expected Behaviour

Micronaut should match the closest mapping, **m1** in the example

### Actual Behaviour

Micronaut is matching the most generic mapping first, **m2** in the example

I think it is related to #1422

### Environment Information

- **Micronaut Version:** 1.3.0.BUILD-SNAPSHOT

**Comment by mageddo** [comment]
It works perfectly on micronaut `1.2.6`

**Comment by jameskleeh** [comment]
Can you verify what repository you are resolving the snapshot from?

**Comment by jameskleeh** [comment]
I added a test for this in 1.2.x and master and they work as expected

**Comment by mageddo** [comment]
I was using `https://oss.sonatype.org/content/repositories/snapshots/`. jfrog version it's working. Thanks for the help

Repository reproducing the issue https://github.com/mageddo/micronaut-mapping-issue/tree/f8a8386
