### ISSUE TITLE
MethodInvocationContext#stringValue has different behavior then #getValue

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#2387]
I noticed that `MethodInvocationContext`'s `#stringValue(annotation, member)` (and also `booleanValue()`, `enumValue()` etc.) has different behaviour then  `#getValue(annotation, member, requiredType)`

The first returns a empty optional in case the member is not defined explicitly.
The latter *does* return the annotation member defaults value if not explicitly defined, which I also expected for `#stringValue()`.

For example:

```
public @interface Loggable {

    Level level() default Level.DEBUG;

    boolean logMethodCall() default true;

    boolean logMethodReturn() default true;
}
```

Now when adding this annotation to a class like:

```
@Loggable(level = Level.INFO, logMethodCall = false)
```

Then in the `MethodInteceptor` this gives:

`context.booleanValue(Loggable.class, "logMethodCall").orElse(null)` 
==> `false` (as expected)

`context.getValue(Loggable.class, "logMethodCall", Boolean.class).orElse(null)` 
==> `false` (as expected)

`context.getDefaultValue(Loggable.class, "logMethodCall", Boolean.class).orElse(null)` 
==> `true` (as expected)

`context.booleanValue(Loggable.class, "logMethodReturn").orElse(null)` 
==> `null` (**!! expected to resolve the annotation's default value** `true` **and not** `null`)

`context.getValue(Loggable.class, "logMethodReturn", Boolean.class).orElse(null)` 
==> `true` (as expected; member not define explicitly so return default value)

`context.getDefaultValue(Loggable.class, "logMethodReturn", Boolean.class).orElse(null)` 
==> `true` (as expected)

According to the api docs the `#getValue` and `#boolean|enum|stringValue()` methods both simply return the value of the annotation member.

I would think that the `#boolean|enum|stringValue()` would be a wrapper around `#getValue()` but that is apparently not the case.

I think the difference is `#boolean|enum|stringValue()` is using the `annotation.getName()` string downstream, and `#getValue` seems to be using the annotation class itself?

Looking at the apidocs, `#boolean|enum|stringValue()` seem to be the most appealing at first sight, but there is caveat using them instead of `#getValue`.

If this is per design then it might be good to add this to the apidocs and/or add convenient `getBoolean|Enum|StringValue()` methods like `#boolean|enum|stringValue()` but also taking into account the annotation's default value?

**Comment by graemerocher** [comment]
These methods are working as designed. They are designed to be as efficient as possible as looking up the default value requires an extra lookup which adds overhead so we won't be changing them.

An argument can be made for additional set of methods or an argument that allows returning the default value, but that is an improvement not a bug fix.

**Comment by marceloverdijk** [comment]
OK @graemerocher thanks for the explanation.
