### ISSUE TITLE
micronaut-test issues seem to be unattended 

### ISSUE THREAD

**Issue by stepanv** [micronaut-projects/micronaut-core#2395]
Hi,

just wondering if it's expected to submit the issues related to micronaut-test there (e.g., https://github.com/micronaut-projects/micronaut-test/issues/91) or here in micronaut-core?

I understand Micronaut is an OSS, I just wanted to be sure the problem is not on my side.
Thanks!

**Comment by graemerocher** [comment]
No problem, we just haven't got round to it yet. If you wish to submit a PR to accelerate a fix for your problem please feel free. Thanks for the feedback.
