### ISSUE TITLE
HttpRequest argument missing for consumes=MediaType.ALL endpoints

### ISSUE THREAD

**Issue by fabienrenaud** [micronaut-projects/micronaut-core#2403]
### Steps to Reproduce

1. Write a simple controller:
```
public class App {

  @Controller("/service")
  public static class Control {

    @Post(consumes = MediaType.ALL)
    public String handle(HttpRequest<String> req) {
      return req.getBody().orElse("nobody");
    }
  }

  public static void main(String[] args) {
    Micronaut.run(App.class, args);
  }
}
```
2. Run and curl:
```
curl localhost:8080/service --data 'foobar'
```
Returns:
```
{"message":"Required argument [HttpRequest req] not specified","path":"/req","_links":{"self":{"href":"/service","templated":false}}}
```

### Expected Behaviour

The request should routed to the defined endpoint when the body can be mapped to the desired type. Here it is `String`. `Object` and `byte[]` should work as well.
I should not have to pass `-H "Content-Type: */*"` in my curl to get the response.

### Actual Behaviour

Call is not routed to the desired endpoint.
I have to set the content-type of the request to `*/*` to get it routed to the handler and get the desired response:
```
curl localhost:8080/service --data 'foobar' -H "Content-Type: */*" 
```

### Environment Information

- **Operating System**: Mac OS Mojave 10.14.6
- **Micronaut Version:** 1.3.0.M1
- **JDK Version:** Oracle JDK 11.0.2

Similar to https://github.com/micronaut-projects/micronaut-core/issues/2334

**Comment by jameskleeh** [comment]
Thanks for the report!

**Comment by fabienrenaud** [comment]
Thanks for fixing it so quickly :)
