### ISSUE TITLE
@ConfigurationProperties bean defined in test sources is created but properties are not loaded

### ISSUE THREAD

**Issue by fedotxxl** [micronaut-projects/micronaut-core#2406]
Hello. I've got the following bean:

```java
import io.micronaut.context.annotation.ConfigurationProperties;
import lombok.Getter;
import lombok.Setter;

/**
 * Created on 21.06.19.
 */
@ConfigurationProperties("prebid.test")
@Getter
@Setter
public class PrebidTestSettings {
    private int mockServerPort;
}
```

If I put this bean into test sources test will run but property `mockServerPort` will have default value (0). If I put this bean into main sources test will run and property `mockServerPort` will have config value

**Comment by jameskleeh** [comment]
Please upload an example application with steps to reproduce

**Comment by fedotxxl** [comment]
This was a problem with lombok and annotation processors order. 

Invalid build gradle file:
```
dependencies {
	testAnnotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
	testAnnotationProcessor "io.micronaut:micronaut-inject-java"
	testAnnotationProcessor "org.projectlombok:lombok:1.18.8"
}
```

Correct build gradle file:
```
dependencies {
        testAnnotationProcessor "org.projectlombok:lombok:1.18.8"
	testAnnotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
	testAnnotationProcessor "io.micronaut:micronaut-inject-java"
}
```

It was a surprise for me....

**Comment by ilopmar** [comment]
@fedotxxl That's explained in the documentation: https://docs.micronaut.io/latest/guide/index.html#_using_project_lombok. Micronaut annotation processor must run always after Lombok (or any other annotation processor)

**Comment by fedotxxl** [comment]
gr8
