### ISSUE TITLE
Documentation. How does security module works with @Client module?

### ISSUE THREAD

**Issue by akozel** [micronaut-projects/micronaut-core#241]
Please. Add some example how can we call @Client methods through built-in security (using headers)?

**Comment by sdelamo** [comment]
@akozel  I added an example of using `@Client` and supplying the JWT token as the `Authorization` HTTP Header value. 

http://guides.micronaut.io/micronaut-security-jwt/guide/index.html#jwt

**Comment by sdelamo** [comment]
@akozel I added an example of using @Client and supplying the Basic Auth as the Authorization HTTP Header value.

http://guides.micronaut.io/micronaut-security-basicauth/guide/index.html#declarativeclient
