### ISSUE TITLE
Add ability to provide default environment

### ISSUE THREAD

**Issue by ivyazmitinov** [micronaut-projects/micronaut-core#2417]
In current implementation configuration is taken from `application.yml` by default, so it seems appropriate to use it for local ("dev") environment. 
However, in this case it is necessary to remove the `application.yml` from artifact before publishing it so no "dev" configs are used on testing/production environment. 

A way to solve this issue is to store dev configuration in environment specific file (`application-dev.yml`) and use it if no other environment is provided. In that case it would be necessary to provide a name of default environment(s?) in main class:

```java
Micronaut.build((String[]) null)
               .defaultEnvironments("dev")
               .start();
```

**Comment by jameskleeh** [comment]
You can achieve this with your gradle/maven build setup and no additional features are required

**Comment by jameskleeh** [comment]
For example: `run.jvmArgs('-noverify', '-XX:TieredStopAtLevel=1', '-Dcom.sun.management.jmxremote', '-Dmicronaut.environments=dev')`

**Comment by ivyazmitinov** [comment]
@jameskleeh 
True, but this strips out possibilities to start an application without a build tool (via IDE, for example)

**Comment by jameskleeh** [comment]
@ivyazmitinov You can setup your IDE to set the environment variable when running the app as well

**Comment by ivyazmitinov** [comment]
@jameskleeh 
In this case all developers should be either aware that applications should be started only via Gradle or manually set up IDE.
It is much more cumbersome and error prone way than have default environment configured from inside the app, IMO.

**Comment by C06A** [comment]
Correct me if I am wrong, but the default environment (by default) is the one without name. So use different environment to run in test or production and run them with '-Dmicronaut.environments=test' and '-Dmicronaut.environments=prod' appropriately.

**Comment by ivyazmitinov** [comment]
@C06A 
It would be true, if configuration from `application.yml` isn't applied when you provide the environment. But now, if you run with `-Dmicronaut.environments=test`, for example, configuration from `application.yml` **and** `application-test.yml` would be applied. Because of that you should 
 either override every option in `application-test.yml` or remove `application.yml` from classpath of test jar.

As I can deduce from [doc,](https://docs.micronaut.io/latest/guide/index.html#_included_propertysource_loaders) `application.yml` is intened to contain application-specific properties which would be common for all environmemts.

**Comment by C06A** [comment]
@ivyazmitinov 

> As I can deduce from [doc,](https://docs.micronaut.io/latest/guide/index.html#_included_propertysource_loaders) `application.yml` is intended to contain application-specific properties which would be common for all environmemts.

Exactly!
Default configuration contains values for all environments. If in specific one you need a different value you should override it in that environment specific configuration file.

If in your case ALL values will be different for each environment then you need to define all of them for each environment. In this case your default config can be empty as there are no configurations shared between environments OR choose one of environment (I prefer development) as default. Then in that environment you won't need to override defaults, but all other environments would override all values.

**Comment by ivyazmitinov** [comment]
@C06A 
In that case you still need to create a dedicated `application-dev.yml` file and configure all possible ways  (gradle, IDE, `java -jar`) to run with `'-Dmicronaut.environments=dev`. 
My suggestion is exactly about possibility to eliminate the need of this configuration by setting `dev` environment from inside the app.

**Comment by eduardo-lago-aguilar** [comment]
I would suggest adding an additional `runEnv()` for Micronaut, allowing to specify a default environment like this:

```
public class Application {

    public static void main(final String[] args) {
        Micronaut.runEnv(Application.class, "dev");
    }
}

```

**Comment by graemerocher** [comment]
This can expressed with:

```
Micronaut.builder()
      .environments("dev")
      .start()
```

**Comment by dstepanov** [comment]
You can also store `application.yml` in the `config` folder which shouldn't be included into the artifact.

**Comment by swiftreap** [comment]
This issues is close but not resolved :(

**Comment by ivyazmitinov** [comment]
@mearafGitHub, it is resolved, we use it :) 
See the "Default Environment" section of the [docs](https://docs.micronaut.io/latest/guide/#environments)
