### ISSUE TITLE
CLI generates incomplete pom.xml

### ISSUE THREAD

**Issue by JonasJurczok** [micronaut-projects/micronaut-core#244]
### Steps to Reproduce

1. mn create-app example -build maven

### Expected Behaviour
The maven project should be ready to build.

### Actual Behaviour

Building the project fails with a java.lang.ClassNotFoundException: javax.annotation.PostConstruct.

Adding a dependency like the following solved the problem for me.

<dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
 </dependency>

### Environment Information

- **Operating System**: Mac OS
- **Micronaut Version:** 1.0.0.M1
- **JDK Version:** 10

### Example Application

Creating an example is trivial, thus I skip this step.

Again I would have provided a pull request, didn't have time to dig into the depths of the CLI though :(

**Comment by graemerocher** [comment]
This is Java 10 specific. See http://docs.micronaut.io/latest/guide/index.html#languageSupport

**Comment by graemerocher** [comment]
but yes we should generate a project with this dependency included in Java 10

**Comment by JonasJurczok** [comment]
Okay, my mistake. I overlooked that part of the docs.

Graeme Rocher <notifications@github.com> schrieb am Do., 31. Mai 2018,
20:52:

**Comment by jameskleeh** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/799ba92a6bcb6a05a548f987305ef28e80c499d9.

The annotations-api will be added automatically if the cli is being ran with Java 9+
