### ISSUE TITLE
Starting/testing the simple example takes over 150 seconds

### ISSUE THREAD

**Issue by JonasJurczok** [micronaut-projects/micronaut-core#245]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. follow http://guides.micronaut.io/creating-your-first-micronaut-app/guide/index.html
pick maven as build tool
2. Fix repository id as described in #243 
3. Add missing dependency as described in #244 
4. Run ./mwnw package

### Expected Behaviour

The build should execute, running the tests in less time it would take spring boot.

### Actual Behaviour

During the build the simple testcase starts a netty server. This startup takes over two minutes, thus delaying the whole build.
On my first try it stopped at initialising the heartbeat, but disabling that changed nothing about the build time.

The same behaviour shows if you just start a compiled jar file.

### Environment Information

- **Operating System**: Mac OS
- **Micronaut Version:** 1.0.0.M1
- **JDK Version:** JDK 10

### Example Application

https://github.com/JonasJurczok/micronaut-example

I added a trace log of the build. There are two huge pauses in the log at timestamps
- 20:35:54.081 > 1 min
- 20:37:09.367 again over 1 min

I couldn't find any obvious problems leading to this and maybe I just made a stupid mistake somewhere.. But I thought I let you know :)

- 
[build-log.txt](https://github.com/micronaut-projects/micronaut-core/files/2059627/build-log.txt)

**Comment by graemerocher** [comment]
This is https://github.com/micronaut-projects/micronaut-core/issues/227

**Comment by JonasJurczok** [comment]
Thanks. I didn't find that one while searching for duplicates....

**Comment by graemerocher** [comment]
Yes we have updated the documentation for that issue for M2. Thanks for the feedback
