### ISSUE TITLE
Allow using caches without having to configure them explicitly

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#2454]
Right now, Caffeine caches won't be created unless they are explicitly configured under `micronaut.caches.*`. It would be better to create them on demand with default values, and still let the users configure them if they want to customise the settings.

In addition to that, cache configurations should be toggleable (ie: allow to set `micronaut.caches.my-cache.enabled: true|false`

**Comment by graemerocher** [comment]
@alvarosanchez this is assigned to 1.3.x, is this something you plan to implement?

**Comment by alvarosanchez** [comment]
Sure, I'll prepare a PR
