### ISSUE TITLE
Using @Cacheable on non-reactive return type gives error: `Only Reactive types that emit a single result can currently be cached.`

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#2472]
In latest `1.3.0.BUILD-SNAPSHOT` I'm getting a `Only Reactive types that emit a single result can currently be cached. Use either Single, Maybe or Mono for operations that cache.`

I'm returning an `Optional` like below:

```
@Singleton
@CacheConfig(cacheNames = COUNTRY_CACHE)
public class CountryRepositoryImpl extends BaseRepositoryImpl implements CountryRepository {

    private final CountryRecordMapper countryRecordMapper;

    public CountryRepositoryImpl(DSLContext context, CountryRecordMapper countryRecordMapper) {
        super(context);
        this.countryRecordMapper = countryRecordMapper;
    }

    @Override
    @Cacheable
    @Transactional(readOnly = true)
    public Optional<Country> findById(String id) {
        var record = context
                .selectFrom(COUNTRY)
                .where(COUNTRY.ID.eq(param("country_id", id)))
                .fetchOne();
        return countryRecordMapper.toCountryOptional(record);
    }
}

```

**Comment by jameskleeh** [comment]
I can't reproduce this, please upload a sample app.

**Comment by marceloverdijk** [comment]
@jameskleeh I looked into and in normal cases it works.

However in combination with a `@Async` `ApplicationEventListener<ServiceStartedEvent>` it fails.

E.g.:

```
public class CachePopulator implements ApplicationEventListener<ServiceStartedEvent> {

    @Async
    @Override
    public void onApplicationEvent(ServiceStartedEvent event) {
        cacheCountries();
    }
}
```

This way I get the `Only Reactive types that emit a single result can currently be cached. Use either Single, Maybe or Mono for operations that cache.`.
When I remove the `@Async` then it works again, however in `1.2.x` and `1.3.0.M1` is worked also with the `@Async`.

**Comment by jameskleeh** [comment]
Can you provide a complete example ?

**Comment by marceloverdijk** [comment]
@jameskleeh you can find a sample project here: https://github.com/marceloverdijk/micronaut-2472
Just run `./gradlew clean run` and you will get the `This way I get the Only Reactive types that emit a single result can currently be cached. Use either Single, Maybe or Mono for operations that cache.` error.

Note: with a very basic sample I was not able to reproduce it. So I copied the same pattern I use from my actual project. I think [this](https://github.com/marceloverdijk/micronaut-2472/blob/master/src/main/java/mn/cacheable/repository/BookRepositoryImpl.java#L32) is the problem.

**Comment by marceloverdijk** [comment]
With latest `1.3.0.BUILD-SNAPSHOT` this is now fixed. Maybe another commit solved it.
Just tried with a `gradle --offline` build and the issue was still there; then with `--refresh-dependencies` and the issue is gone.
