### ISSUE TITLE
Feature Request: Kotlin Value for Interface Vals

### ISSUE THREAD

**Issue by jamesward** [micronaut-projects/micronaut-core#2473]
I'm not sure how it'd work but It'd be really nice to support injecting values into interface vals, like:
```
interface Foo {
    @Value("\${bar:asdf}")
    val bar: String
        get() = ???
}
```

**Comment by graemerocher** [comment]
Hi James, 1.3 M1 allows defining configuration properties as interfaces https://docs.micronaut.io/1.3.0.M1/guide/index.html#immutableConfig

Would that suffice?

**Comment by jamesward** [comment]
Perfect!  As always you are one step ahead of me.  :)
