### ISSUE TITLE
HttpServerFilter does not honor server context path

### ISSUE THREAD

**Issue by croudet** [micronaut-projects/micronaut-core#2478]
### Task List

- [ x] Steps to reproduce provided
- [ x] Example that reproduces the problem uploaded to Github
- [ x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Define an `HttpServerFilter`
```java
@Filter("/redoc**")
public class TestFilter implements HttpServerFilter {

    public TestFilter() {
        System.out.println("created");
    }

    @Override
    public Publisher<MutableHttpResponse<?>> doFilter(HttpRequest<?> request, ServerFilterChain chain) {
        System.out.println("In filter");
        return chain.proceed(request);
    }

}
```
2. Define a Controller
```java
@Controller("/redoc")
public class ReDocController {
    @Inject
    OpenApiConfig config;

    @View("redoc/index")
    @Get
    public OpenApiConfig index() {
        return config;
    }
}
```
3. Define a context path in `application.yml`
```yaml
micronaut:
  server:
    context-path: /hello
```

### Expected Behaviour

The filter should be called.

### Actual Behaviour

The filter is not called.
The filter is called when there is no context path.

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.2.7
- **JDK Version:** jdk 13

**Comment by jameskleeh** [comment]
Closed by https://github.com/micronaut-projects/micronaut-core/commit/17735b7b655f0172daa4e735700993de96e558ca
