### ISSUE TITLE
Kotlin: Method defines AOP advice but is declared final. Change the method to be non-final in order for AOP advice to be applied.

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#2479]
Since `1.2.x`/`1.3.0.M1` --> `1.3.0.BUILD-SNAPSHOT` something changed regarding AOP in Micronaut when using Kotlin as language.

When updating the dependency from `1.3.0.M1` to `1.3.0.BUILD-SNAPSHOT` I suddenly get `Method defines AOP advice but is declared final. Change the method to be non-final in order for AOP advice to be applied.` errors I didn't get before.

Below an example of affected code:

```
abstract class BaseRepositoryImpl(
    val context: DSLContext
)

@Singleton
lass CountryRepositoryImpl(
    context: DSLContext,
) : BaseRepositoryImpl(context), CountryRepository {
    ..
}
```

I had to change the `context` var in the `BaseRepositoryImpl` to `open`:

```
abstract class BaseRepositoryImpl(
    open val context: DSLContext
)
```

**Comment by marceloverdijk** [comment]
PS: I have no problem making the `context` var `open` but it worked before without the `open` modifier. This could be a breaking change for other users as well.

**Comment by graemerocher** [comment]
Agreed, thanks for spotting it, will take a look

**Comment by marceloverdijk** [comment]
@graemerocher I'm still seeing this error. I created a basic sample project that has the problem as well: https://github.com/marceloverdijk/micronaut-2479

Just run `./gradlew clean run --refresh-dependencies` and you will get:

```
❯ ./gradlew clean run --refresh-dependencies

> Task :kaptKotlin FAILED
e: /workspace/micronaut/micronaut-2479/build/tmp/kapt3/stubs/main/example/BaseService.java:11: error: Public method inherits AOP 
advice but is declared final. Either make the method non-public or apply AOP advice only to public methods declared on the class.
    public final io.micronaut.core.io.ResourceLoader getResourceLoader() {
```

**Comment by marceloverdijk** [comment]
Works now 👍

**Comment by cina-shahabi** [comment]
How did you resolve this issue? Having a similar problem

**Comment by marceloverdijk** [comment]
@cina-shahabi which version of Micronaut are you using?  For me it was broken at that time in the build snapshot...

**Comment by capricube** [comment]
@marceloverdijk i'm experiencing the same issue using 1.3.RC1

This yields the same error message
`@Transactional(readOnly = true)
    fun executeTwo() {`

However if i make it open it works (simple implementation; no interface)
`@Transactional(readOnly = true)
    open fun executeTwo() {`

**Comment by marceloverdijk** [comment]
@cina-shahabi @capricube just to be sure I updated https://github.com/marceloverdijk/micronaut-2479 to `1.3.0.RC1` and I don't see the issue happening in that project. Maybe it is good to create a small reproducer with your setup?

**Comment by rodolfodpk** [comment]
I had the same problem with 2.4.3. I had to add open modifier to class and method. Worked, nice. But so why should I use org.jetbrains.kotlin.plugin.allopen or else Micronaut throws an exception?

**Comment by zsiegel** [comment]
@rodolfodpk If you want the `allopen` plugin to be aware of `@Transactional` you need to indicate this in your `build.gradle` file. Docs and example are below...

https://kotlinlang.org/docs/all-open-plugin.html#gradle

```kotlin
allOpen {
    // Mark any classes with the following transactions as `open` automatically.
    annotations("io.micronaut.aop.Around", "javax.transaction.Transactional")
}
```
