### ISSUE TITLE
Controller returns HTTP 200 even if Flowable returns error

### ISSUE THREAD

**Issue by ramkumarkb** [micronaut-projects/micronaut-core#2495]
Micronaut Controller seems to return 200 even if the `Flowable<T>` returns error. If we wrap the controller response in a `HttpResponse<*>`, then it seems to return HTTP 500.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Define a simple controller that returns Flowable. See sample code below:
`@Controller("/hello")
class HelloController(val greetingService : GreetingService) {

    @Get("/{name}")
    fun hello(name: String): String {
        return greetingService.greet(name)
    }

    @Get("/test-flowable")
    fun getFromFlowable(): Flowable<String> {
        return getFlowableFromList(listOf("one", "two", "three"))
    }

    @Get("/test-flowable-err")
    fun getErrorFromFlowable(): Flowable<String> {
        return getFlowableFromList(listOf("", "two", "three"))
    }

    fun getFlowableFromList(myList: List<String>) : Flowable<String> {
        val myFlowable = Observable.create<String> { emitter ->
            myList.forEach { kind ->
                if (kind == "") {
                    emitter.onError(Exception("There's no value to show"))
                }
                emitter.onNext(kind)
            }
            emitter.onComplete()
        }.toFlowable(BackpressureStrategy.DROP)
        return myFlowable
    }
}`

### Expected Behaviour

Micronaut should return HTTP (non-200 - maybe 500) in the case of `/test-flowable-err` - Error returned by Flowable is not being expressed by the Framework?

### Actual Behaviour

Micronaut seems to return HTTP 200 in both the `/test-flowable` and `/test-flowable-err` case

### Environment Information

- **Micronaut Version: 1.2.0**
- **JDK Version: 1.8**

**Comment by croudet** [comment]
Related to https://github.com/micronaut-projects/micronaut-core/issues/2196

**Comment by graemerocher** [comment]
There is actually very little we can do about this because using a `Flowable` results in sending the headers back and including `transfer-encoding: chunked` then each chunk is streamed to the response so if something goes wrong in the middle the headers are already sent and there is nothing much that can be done other than dropping the connection.

We may be able to improve this behaviour with future http/2 or http/3 support

**Comment by croudet** [comment]
Would it be possible to return the headers after the subscribre?

**Comment by anupdangore** [comment]
@graemerocher Is this issue got fixed in latest Micronaut version 2.1.2 ?

**Comment by graemerocher** [comment]
No, like I said above with `Flowable<String>` it switches to transfer encoding `chunked` and writes each chunk. The first thing that is done is to write all the HTTP headers, and then write each chunk as it is streamed. So if an error occurs when writing one of the chunks the headers have already been committed to the response and all we can do is drop the connection.

If you don't want to use streaming and are likely to have errors in the middle of a chunked response then you are better off using `Single<List<String>>` which will set a `content-length` header buffer all responses in memory and write them out in one go, giving you a chance to handle errors.
