### ISSUE TITLE
QueryValue annotation on declarative client produces wrong URL query parameters

### ISSUE THREAD

**Issue by RuiffCardoso** [micronaut-projects/micronaut-core#2498]
Creating a client which receives a List query parameter, while using a @QueryValue annotation produces the wrong output.

Example:
``` java
@Get("/api/v1/stuff{?name*}")
public Object functionName(@QueryValue(value = "name") List<String> name);
```
Calling this client with a list containing  ```ABC, DEF```:
- Output URL produced will be: ```http://localhost:51008/api/v1/stuff?name=ABC,DEF```
- Expected output should be: ```://localhost:51008/api/v1/stuff?name=ABC&namespace=DEF```

Workaround for this issue is removing the ```@QueryValue``` annotation.
``` java
@Get("/api/v1/stuff{?name*}")
public Object functionName(List<String> name);
```
Calling this client with a list containing  ```ABC, DEF```:
- Output URL produced will be ```://localhost:51008/api/v1/stuff?name=ABC&namespace=DEF``` as expected.

Tested using 1.2.2 and 1.2.7 Micronaut versions.

**Comment by puneetbehl** [comment]
@RuiffCardoso It works with following:
```
 @Get("{?names*}")
    List<Stuff> get(@QueryValue("names") List<String> names, HttpRequest<?> request) {
        assert request.getUri().toString().endsWith(String.format("names=%s&names=%s", names.toArray()));
        return Collections.singletonList(new Stuff("Shower Rod"));
    }
```

I am going to test again with Kotlin app but I am assuming that it should not make any difference.

**Comment by puneetbehl** [comment]
@RuiffCardoso I am sorry it seem like my sample is replicating the problem and got confused with something else. I will look into fixing the same.
