### ISSUE TITLE
Change in response in `/health` endpoint in Micronaut 1.3.0 snapshot with GraalVM

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#2509]
There has been a change in Micronaut from version 1.2.x to 1.3.0 in the response of the `/health` endpoint.

1.2.x -> `{"status":"UP"}`
1.3.0 -> `{"status":{"name":"UP","description":null,"operational":true,"severity":null}}`

**Comment by graemerocher** [comment]
how does one reproduce this?

**Comment by ilopmar** [comment]
I'm sorry, I totally forgot about explaining how to reproduce it.

Running the application with Gradle returns the expected response but running it as a native-image don't.

- `git clone https://github.com/micronaut-graal-tests/micronaut-management-graal`
- `cd micronaut-management-graal`
- `sdk use java 19.3.0.r8-grl`
- `./build-native-image.sh`
- `./management-graal`
- `curl localhost:8080/health`

The output is:
```
{"status":{"name":"UP","description":null,"operational":true,"severity":null}}
```

But running with the JVM the output is:
```
{"status":"UP"}
```
