### ISSUE TITLE
Support for Kotlin's Flow 

### ISSUE THREAD

**Issue by dave08** [micronaut-projects/micronaut-core#2534]
Could support for Flow be added in controllers and clients (and maybe other services) just like RxJava? There are currently adapter functions in Kotlin Coroutines that can convert from RxJava and other such frameworks, so initial support might be using them...

**Comment by dave08** [comment]
Wow, thanks guys :1st_place_medal:!

**Comment by graemerocher** [comment]
Thanks to @konrad-kaminski
