### ISSUE TITLE
Support loading property files from a /config subdirectory of the current directory

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#2537]
That's one of the locations where Spring Boot is loading properties from.
The benefit of storing properties in the `/config` is that they are excluded from the final artifact.

Our current solution is to add this class with META-INF services entry:

```
public class ConfigFolderConfigurationClient extends YamlPropertySourceLoader {

    @Override
    public Optional<PropertySource> loadEnv(String resourceName, ResourceLoader resourceLoader, ActiveEnvironment activeEnvironment) {
        return super.loadEnv(resourceName, new DefaultFileSystemResourceLoader("./config/"), activeEnvironment);
    }

    @Override
    public Optional<PropertySource> load(String resourceName, ResourceLoader resourceLoader, String environmentName) {
        return super.load(resourceName, new DefaultFileSystemResourceLoader("./config/"), environmentName);
    }

}
```

**Comment by graemerocher** [comment]
If it doesn't impact startup time then I don't mind this one either.

**Comment by jameskleeh** [comment]
I'm not really convinced this is a good idea. There doesn't seem to be any reasonable assumption of the priority of the files in `config/` vs those in `src/main/resources/`.

**Comment by dstepanov** [comment]
`application.yml` usually includes base properties plus `dev` for running locally and `test` for tests, it's just better to have a convention to put everything in /config.

I think `getOrder` can be used define priority of extra classes after defaults.
