### ISSUE TITLE
When getting an datasource bean by ApplicationContext , an Exception happen!

### ISSUE THREAD

**Issue by theseusyang** [micronaut-projects/micronaut-core#254]
Exception in thread "main" io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [com.zaxxer.hikari.HikariDataSource] exists. If you are using Java or Kotlin make sure you have enabled annotation processing.
	at io.micronaut.context.DefaultBeanContext.createBean(DefaultBeanContext.java:662)
	at io.micronaut.context.DefaultBeanContext.createBean(DefaultBeanContext.java:538)
	at io.micronaut.context.BeanContext.createBean(BeanContext.java:65)
	at HelloJDBC.main(HelloJDBC.java:14)

My codes is : 

ApplicationContext applicationContext = new DefaultApplicationContext("test");
        applicationContext.start();
        
        HikariDataSource dataSource = applicationContext.getBean(HikariDataSource.class);
        
        dataSource.setJdbcUrl("jdbc:postgresql://localhost:5432/postgres");
        try {
			Connection con = dataSource.getConnection("postgres", "test");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

**Comment by graemerocher** [comment]
You are not configuring a data source or passing any configuration to the `ApplicationContext` so it is not surprising

**Comment by theseusyang** [comment]
OK, I try to put parameters into ApplicationContext.

@graemerocher  thank you !

**Comment by theseusyang** [comment]
Can you paste an example? I still don't solve it...

 Thank you!

**Comment by mOo7King** [comment]
Any solution for same issue but in maven project?

My dependencies are the following:

<dependencies>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>1.7.25</version>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>

        
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>runtime</artifactId>
            <version>1.0.0.M4</version>
        </dependency>
        <dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>http-client</artifactId>
            <version>1.0.0.M4</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>

    </dependencies>
