### ISSUE TITLE
Cache name is missing in 1.3.0.M2

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#2555]
I have a library JAR compiled with 1.2.6 with a service and a method:

```
@Cacheable("phone-number-cache")
    public Maybe<String> findByPhoneNumber(String phoneNumber) {
```

When used by an application compiled with 1.3.0.M1 everything works fine but with M2 I get an error:

`No cache configured for name: null`

Coming from `DefaultCacheManager`.

In debugger I see there is an empty values map in `AnnotationValue` for `CacheConfig` in `CacheOperation` constructor.

**Comment by graemerocher** [comment]
Can you provide an example that reproduces the issue?

**Comment by dstepanov** [comment]
Unfortunately there no easy example, I think it's related to the annotation being in the library with an older version.

**Comment by graemerocher** [comment]
Will investigate. Thanks for the feedback.

**Comment by dstepanov** [comment]
I did confirm it by including the project using `includeBuild` in Gradle and changing the version build passes, so it must be related to having different versions.

**Comment by jameskleeh** [comment]
I can't reproduce this. I'll upload a sample app

**Comment by jameskleeh** [comment]
@dstepanov https://github.com/jameskleeh/micronaut-issue-2555

The app has a `libs` folder that contains a jar that was created from Micronaut 1.2.6

**Comment by dstepanov** [comment]
@jameskleeh can you put the lib project into subdirectory?

**Comment by jameskleeh** [comment]
@dstepanov I don't know what you mean. If you can modify the app to reproduce the issue please send a PR to my repo

**Comment by dstepanov** [comment]
@jameskleeh Just if you can include inside the project that generates that lib jar.

**Comment by jameskleeh** [comment]
@dstepanov I created a separate repo https://github.com/jameskleeh/micronaut-issue-2555-2

**Comment by dstepanov** [comment]
@jameskleeh There was a log warring in your app about missing cache name. After I added reactive response it started to produce the same error as I have. PR included.

**Comment by jameskleeh** [comment]
This seems to be the issue https://github.com/micronaut-projects/micronaut-core/commit/72f8227fd4ba774346674c3fb42a105ad378d6ac#diff-6e9a16f17e521936110c3d11e65546c0R872-R876
