### ISSUE TITLE
Potential picocli integration

### ISSUE THREAD

**Issue by remkop** [micronaut-projects/micronaut-core#256]
@graemerocher , thank you for expressing an interest in picocli. As promised, raising a ticket to discuss potentially leveraging picocli in Micronaut.

I've spent some time reading the Micronaut code. My first impression is that there is already a lot there. Nice work! I would like to understand better what you have in mind and where you think picocli can add value. Which parts are you interested in? (Annotation API, strong typing, ANSI help, bash autocompletion, or something(s) else?)

For picocli to add value would likely mean to replace some of the Micronaut classes with picocli classes.

I see some functional overlap between these classes (micronaut <> picocli):
* CommandDescription ~= [CommandSpec](http://picocli.info/apidocs/picocli/CommandLine.Model.CommandSpec.html)
* Option ~= [OptionSpec](http://picocli.info/apidocs/picocli/CommandLine.Model.OptionSpec.html)
* CommandArgument ~= [PositionalParamSpec](http://picocli.info/apidocs/picocli/CommandLine.Model.PositionalParamSpec.html)
* CommandLineParser ~= [CommandLine](http://picocli.info/apidocs/picocli/CommandLine.html)
* CommandLine ~= [ParseResult](http://picocli.info/apidocs/picocli/CommandLine.ParseResult.html)
* ParseException ~= ParameterException

Looking at the code, it seems to me that the `Command` API is used mostly internally to add Micronaut functionality, but may also be meant to provide an extension mechanism for users to build Micronaut plug-ins. So the `Command` API would only be used by advanced users. Am I correct?

Are you open to using picocli classes directly in Micronaut, and expose the picocli classes to the `Command` implementations, or should picocli remain hidden behind Micronaut interfaces?

For example, CommandDescription, CommandArgument and Option: would you consider replacing these with picocli classes?  Generally the picocli classes will have more features. The question is whether you want that or whether you prefer the current, more minimalistic, approach.

I'm in two minds about the `CommandLine` interface. Perhaps here the way to go is to provide a `ParseResult`-based implementation of `CommandLine`, I'm not sure. Let me know your thoughts.

When it comes to parsing, picocli has some facilities that allow multi-pass parsing, so it should be possible to first get the global options and the command name (if any), and delegate processing of the remaining arguments to the specified command in a second pass.

Missing in picocli: micronaut CommandLineParser has explicit support for undeclared options, and these can be retrieved from the `CommandLine` parse result as painlessly as declared options. Picocli has the (weaker) concept of unmatched arguments: a simple list of command line arguments that could not be recognized as either declared options or declared positional parameters. I'm not sure if this feature is really needed: is it not possible to declare all options and arguments up front without loss of functionality?

Also missing in picocli: generate a jline Completer for a command or for the parameter values of an option/positional argument. (This would be a generally useful feature for picocli anyway.) This works best if options and parameters have strong types, like enum (completion can show all values), or File/Path (list current dir), etc.

----
Finally, some things I noticed:
* CommandLineParser splits property key-values on `=` but it should use the `arg.split("=", 2)` API to correctly handle cases where the value itself contains a `=` character. (E.g. `-Da=b=c` should result in a property with name 'a' and a value 'b=c'. I believe the current logic is incorrect and will result in value 'b'.)
* Is it a good idea to let `AbstractProfile.handleCommand` check the _number_ of required arguments before calling `Command.handle`? It may be better to simply call the Command and let the command itself give an error message that explains exactly _what_ required parameter was missing.

Also, I noticed some duplicate code beween the `core` and `cli` modules. Is this intentional?
The following classes have a lot of duplicate code: (Core) `io.micronaut.core.cli` vs (cli) `io.micronaut.cli.console.parsing`:
* CommandLine
* CommandLineParser
* DefaultCommandLine
* Option
* ParseException

**Comment by graemerocher** [comment]
The Micronaut CLI is completely separate from Micronaut itself. There are no dependencies in the CLI on any other Micronaut module nor does any other Micronaut module depend on the CLI. So I absolutely don't mind how or what tool that CLI is built with.

The thing is to retain the features of the CLI in terms of interactive mode and so on. To answer your specific questions:

* The `Command` API is indeed internal and it is not anticipated that users will extend this API
* I have no problem with direct dependencies on picocli, if that )means we can delete some of our code, all the better. Nothing feels better than deleting code 👍 
* I'm not sure if we are using undeclared options in Micronaut CLI, we would have to review that.
* The duplication is intentional. As I said we do not want any dependency between the CLI and Micronaut itself or visa versa

**Comment by remkop** [comment]
I see. That makes things a bit easier than I thought. I'll take a look at reimplementing the current CLI behaviour using picocli and provide a PR. Thanks for the clarification.

**Comment by graemerocher** [comment]
By the way, one other thing that might be interesting is a Micronaut profile for creating CLI applications with Picocli 

Right now the are variety of application types you can make with Micronaut (serverless functions, netty server apps etc.) with more coming (Kafka / RabbitMQ apps etc.) 

Another common domain is writing CLI apps and with Micronaut DI being fast it might be a good fit. For example your CLI apps could DI datasources, discovery services, http clients etc.

**Comment by remkop** [comment]
Quick update: I've started to work on this. Please take a look at the [revamped `FunctionApplication`](https://github.com/remkop/micronaut-core/blob/0b4810898535e013d132e9d43f77406aa14f8242/function/src/main/java/io/micronaut/function/executor/FunctionApplication.java) class on my branch. This is what I'm shooting for. Feedback welcome.

The usage help message for `FunctionApplication` now looks like this:

```
Usage: function [-hVx] [-d=<data>]
Allows executing functions from the CLI.
  -d, --data=<data>   For passing the data
  -x, --debug         For outputting debug information
  -h, --help          Show this help message and exit.
  -V, --version       Print version information and exit.
```

* synopsis shows optional options in square `[` and `]` brackets. This is different from the current `mn` style which is to mark optional options with a `*` in the options list. Let me know what you think.
* I added long options `--data` and `--debug`. I used GNU-style double hyphens. Let me know if you prefer single hyphens for such long options, or if you prefer to have only short options.
* I added "standard help options" `--help` and `--version`. This is built-in picocli functionality. If you prefer single hyphens we can create a reusable help options component for this that can be applied to all Micronaut commands for consistency. 
* Version is static in `FunctionApplication`. It is possible to retrieve version info dynamically from the jar manifest or a properties file in the classpath.

About undeclared options used in Micronaut, take a look at [`CommandLinePropertySource`](https://github.com/remkop/micronaut-core/blob/0b4810898535e013d132e9d43f77406aa14f8242/runtime/src/main/java/io/micronaut/runtime/context/env/CommandLinePropertySource.java#L63). When `io.micronaut.runtime.Micronaut` is started, undeclared options are treated as property key-value pairs and put into the ApplicationContext environment. This is doable but not natural/easy in picocli.

Instead, would it be acceptable to have an explicit option that takes any number of key-value pairs? So users would invoke a command like this:

```
#proposed
<command> -Xkey=value -Xkey2=value2
```
instead of this:
```
#current
<command> -key value -key2 value2
```
We could then document this `-X` (other name is fine too) option in the usage help message so users know this is the way to pass in environment options.

**Comment by graemerocher** [comment]
Sorry if I wasn't 100% clear, the `cli` subproject is free to use Picocli in any form possible, but we are trying to keep the rest of Micronaut as dependency free as possible. The `function` module especially is for building functions to be deployed to Lambda or FaaS systems, which you want to be as small as possible, so we can't really add Picocli support to `FunctionApplication`

Anything that is part of the CLI is fine though (ie the `cli` subproject)

**Comment by remkop** [comment]
Understood. Thanks for the clarification. Focusing on the `cli` subproject.

I spent more time familiarizing myself with the code and starting to migrate the "create" commands to picocli, and I now believe most of the effort will be related to integrating well with JLine - the completion.

Any objection if I model options that have a list of "valid values" as enums in `cli`? E.g. `enum SupportedLanguage { java, groovy, kotlin }` and `enum SupportedTestFramework { junit, spock, spek }`. Picocli's bash command line completion can then [generate completions](url) for the values of these options.

In the `cli` project I will probably use JLine's built-in `WhiteSpaceArgumentDelimiter` to "crack a command line" into tokens to replace `CommandLineParser.translateCommandLine` (the "borrowed from ant" stuff). It removes code and the JLine stuff handles escaped quotes. 

This may be interesting for the `core` module also:

```groovy
String line = "a bcd e"
ArgumentCompleter.ArgumentList list = 
        new ArgumentCompleter.WhitespaceArgumentDelimiter().delimit(line, 4)

assert list.arguments == ['a', 'bcd', 'e'] // cracked
assert list.cursorArgumentIndex == 1 // arguments[1]
assert list.argumentPosition == 2 // arguments[1].charAt(2)
assert list.bufferPosition == 4 // line.charAt(4)
```

**Comment by graemerocher** [comment]
No objections. I believe we are using quite an old version of Jline as well

**Comment by remkop** [comment]
Yes, micronaut is using jline 2.12. Most recent is 2.14.2. Would you object to upgrading to 2.14.2?

**Comment by remkop** [comment]
Sorry. Most recent is jline 2.14.6. 
To clarify, I have not yet encountered anything that requires upgrading from 2.12. I'll continue with jline 2.12 unless you prefer to upgrade or unless I find any issues that require upgrading to a later version.

**Comment by graemerocher** [comment]
No objection to upgrading

**Comment by remkop** [comment]
Quick status update: I spent most of last week updating picocli with features related to this ticket. Details are [here](https://github.com/remkop/picocli/issues/387), but most of it had to do with adding support for JLine completion.

I am now back to working on the Micronaut CLI code:
* simplify CLI commands by defining options and positional args with picocli annotations on fields
* remove the parser code
* remove the completion code (use enums for fixed values, define a function that generated completion candidates for dynamic stuff like profiles and features)

I'll give another update end of this week.

**Comment by remkop** [comment]
Update: the only remaining commands to convert are `DefaultMultiStepCommand` and `GroovyScriptCommand`; after I need to test to shake out any bugs.

For `GroovyScriptCommand`, I found `create-bean.groovy` and `create-job.groovy` in micronaut-profiles. I am hoping I might be able to combine the `GroovyScriptCommandTransform` with the `@PicocliScript` annotation and associated AST transform that is built into picocli. That would allow users to [define command options and parameters with picocli annotations](http://picocli.info/picocli-2.0-groovy-scripts-on-steroids.html). (I just started working on this, don't know yet.)
 
`DefaultMultiStepCommand` I have more trouble with. The javadoc mentions it is a "class that parses commands defined in YAML or JSON" but I could not find any json or yaml commands in the micronaut-profiles project. I also could not find anywhere that the Step implementations are used. Can someone tell me what I am missing?

**Comment by graemerocher** [comment]
@remkop Great! It does seem that `DefaultMultiStepCommand` is not used at the moment. The Groovy DSL for commands is nicer in many ways so we could simply abandon support for YAML defined commands.

**Comment by remkop** [comment]
Oh nice! Dropping support for YAML defined commands means quite a few classes can be removed:
* YamlCommandFactory
* MultiStepCommand
* DefaultMultiStepCommand
* AbstractStep
* io.micronaut.cli.profile.steps.*

I've done some experimenting and I think that by letting `GroovyScriptCommand` extend `PicocliBaseScript`, we can use the `PicocliScriptASTTransformation` and the `GroovyScriptCommandTransform` class will no longer be needed.


To give you an idea of what this will look like, the [`create-bean.groovy` script command](https://github.com/micronaut-projects/micronaut-profiles/blob/master/base/commands/create-bean.groovy) in micronaut-profiles will look something like this:
```groovy
@Command(name = 'create-bean', description = 'Creates a singleton bean')
@PicocliScript GroovyScriptCommand me

@Parameters(paramLabel = "BEAN-NAME", description = 'The name of the bean class to create')
@Field String beanName

@Option(names = '-force', description = 'Whether to overwrite existing files')
@Field boolean overwrite

@Option(names = '-lang', description = 'The language used for the bean class (options: ${COMPLETION-CANDIDATES})')
@Field SupportedLanguage lang

private SupportedLanguage calcDefaultLanguage() {
    def result = SupportedLanguage.valueOfOr(config.sourceLanguage, null)
    if (!result) {
        if (file("src/main/groovy").exists()) {
            result = SupportedLanguage.groovy
        } else if (file("src/main/kotlin").exists()) {
            result = SupportedLanguage.kotlin
        } else {
            result = SupportedLanguage.java
        }
    }
    result
}
lang = lang ?: calcDefaultLanguage()

def model = model(beanName)
String artifactPath = "${model.packagePath}/${model.className}"

render template: template("${lang}/Bean.${lang.extension}"),
        destination: file("src/main/${lang}/${artifactPath}.${lang.extension}"),
        model: model,
        overwrite: overwrite
```
The declaration of command options looks more verbose but overall the script is shorter.

**Comment by remkop** [comment]
Update:
Most of the work is done and I am now testing to shake out bugs. I hope to be able to provide a PR after the weekend.

I could not find any automated tests but if you have any manual test cases (or a list of CLI functions to verify) that you can share that would be helpful.

Small detail: I noticed that the fat-jar includes two versions of picocli: the version used in the project and the version used by groovy 2.5, so I added a `resolutionStrategy` to the build to force picocli to the version used by the micronaut project.

**Comment by remkop** [comment]
Thanks for merging PR #400! Closing this ticket.
