### ISSUE TITLE
YAML Map Keys are read incorrectly

### ISSUE THREAD

**Issue by pushpender673** [micronaut-projects/micronaut-core#2564]
When try to read map object from application.yml file with Keys containing spaces and starting with uppercase then keys are converted to kebab notation. But if root of the map is defined with Uppercase then everything works fine. Is it Micronaut default behaviour or is it a bug?

Below code gives Map with ["Key with space":[ "some more key", "some other key" ]]
```
Test:
  Key with space:
    - some more key
       some other key
```

But below code gives Map with ["k-ey with space":[ "some more key", "some other key" ]]

```
test:
  Key with space:
    - some more key
       some other key
```

Im not able to find documentation for it.

**Comment by jameskleeh** [comment]
How are you retrieving the map?

**Comment by pushpender673** [comment]
I was retrieving this way and it retrieves keys with spaces properly without hypenate them.
```
@Property( name ="Test")
private Map<String, List<String>> test;
```

And Config File looks like this 
```
Test:
  Key With Space: 
    - value1
    - Value2
```

But if I do this way
```
@Property( name ="test")
private Map<String, List<String>> test;
```
Config file
```
test:
  Key With Space: 
    - value1
    - Value2
```
it creates problem, it hypenate the keys

**Comment by pushpender673** [comment]
@jameskleeh can you help me with this?

**Comment by graemerocher** [comment]
Use 

```java
@Property(name = "test")
@MapFormat(keyFormat=StringConvention.RAW)
```

**Comment by pushpender673** [comment]
@graemerocher Thanks it works fine.
