### ISSUE TITLE
Reduce Reactive call stack

### ISSUE THREAD

**Issue by fabienrenaud** [micronaut-projects/micronaut-core#2566]
The reactive call stack is still huge in micronaut 1.3.0.M2 and has a lot of overhead.

![Screen Shot 2019-12-24 at 9 39 11 AM](https://user-images.githubusercontent.com/3112233/71425729-403c7100-2655-11ea-9683-d5c5b0f934ef.png)

This call stack shows only about 10% of useful work is done for a total of 32%  cpu used for this call stack.

Profiled with a very simple controller:
```
public class App {

  @Controller("/service")
  public static class Control {

    @Get
    public CompletionStage<String> handle(Optional<String> str) {
      return CompletableFuture.completedFuture(str.orElse("nop"));
    }
  }

  public static void main(String[] args) {
    Micronaut.run(App.class, args);
  }
}
```

**Comment by fabienrenaud** [comment]
@graemerocher Any hope of this getting done in the near future? Is there any work scheduled to improve micronaut's performance and move it upwards on these techempower benchmark charts?

**Comment by graemerocher** [comment]
@fabienrenaud Yes this issue is still on my todo list to look at for Micronaut 2.x which we are working on now. There are definitely things we can improve and have been improving. See https://github.com/micronaut-projects/micronaut-core/commit/15a1fd6a316e293ca0d2076604c290b54ea48e6c for example of a recent commit.

There are many potential areas for optimization.

**Comment by graemerocher** [comment]
btw what tool did you use to produce that call stack? I have been using YourKit for profiling

**Comment by fabienrenaud** [comment]
I used jprofiler from ej-technologies.

> Micronaut 2.x

Nice! Is there a roadmap / discussion topic somewhere that I can follow?

**Comment by graemerocher** [comment]
PR #2976 improves matters further, as for the road map you can see what we are working on here https://github.com/micronaut-projects/micronaut-core/milestone/43

**Comment by graemerocher** [comment]
Closing this for now, the stack depth is smaller in master. I have pushed some performance optimizations to some hotspots as well.
