### ISSUE TITLE
ConversionService is missing String to Duration conversion

### ISSUE THREAD

**Issue by joumenharzli** [micronaut-projects/micronaut-core#2567]
### Task List

- [ x ] Steps to reproduce provided
- [ x ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ x ] Full description of the issue provided (see below)

### Steps to Reproduce

Create a properties files
```yaml
lambda:
  presigned-url-expiration-period: 5m
```

and a configuration class
```java
@ConfigurationProperties("lambda")
@Data
public class LambdaProperties {
    private Duration presignedUrlExpirationPeriod;
}

```

### Expected Behaviour

the presignedUrlExpirationPeriod propertie have a value of 5 minutes

### Actual Behaviour

```
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value 
for parameter [presignedUrlExpirationPeriod] of method [setPresignedUrlExpirationPeriod] of class: lambdas.configuration.LambdaProperties

Message: Error resolving property value [lambda.presigned-url-expiration-period]. 
Property doesn't exist
```

After some debugging if found out that the method **io.micronaut.core.convert.DefaultConversionService#findTypeConverter** 
cannot resolve a converter with String to Duration key

### Workaround
I extended the class io.micronaut.context.DefaultApplicationContext
and I manually registred a converter 

```java
    @Override
    protected ConversionService createConversionService() {
        ConversionService<?> shared = ConversionService.SHARED;
        shared.addConverter(String.class, Duration.class,
                (str, targetType, context) -> {

                    Duration duration = null;

                    if (str.endsWith("h")) {

                        String timeStr = str.substring(0, str.lastIndexOf("h")).trim();
                        duration = Duration.ofHours(Long.parseLong(timeStr));

                    } else if (str.endsWith("m")) {

                        String timeStr = str.substring(0, str.lastIndexOf("m")).trim();
                        duration = Duration.ofHours(Long.parseLong(timeStr));

                    } else if (str.endsWith("s")) {

                        String timeStr = str.substring(0, str.lastIndexOf("s")).trim();
                        duration = Duration.ofHours(Long.parseLong(timeStr));

                    }

                    return Optional.ofNullable(duration);
                }
        );
        return shared;
    }
```

### Environment Information

- **Operating System**: OSX
- **Micronaut Version:** 1.3.0.M2
- **JDK Version:** 11

**Comment by poojalakhani27** [comment]
I would like to take this up. May I?

**Comment by graemerocher** [comment]
Go for it

**Comment by poojalakhani27** [comment]
String to Duration converter is present in `io.micronaut:micronaut-runtime` (`TimeConverterRegistrar`). Should it also be added to  micronaut-core?

**Comment by jameskleeh** [comment]
The duration converter is in runtime. If adding a dependency on runtime is not a possibility, please open a new issue and describe your use case.
