### ISSUE TITLE
Support for Templating Engines (Velocity, Thymeleaf, etc.)

### ISSUE THREAD

**Issue by gboersma** [micronaut-projects/micronaut-core#257]
Add support for templating engines for returning HTML content for REST call.

**Comment by akozel** [comment]
omg. microservices and REST are not abot HTML.

**Comment by gboersma** [comment]
We do software for enterprises, and we want to microservices architecture. Here's the conversation with my tech lead:

"We should think about switching to Micronaut. Better than Spring for what we are doing with microservices."

"Does it do everything we use Spring for?"

"Well, everything except server-side UI templating. We decided on that because the client does not want the UI on the browser."

"Okay. No."

Server-side templating makes that answer "yes".

**Comment by graemerocher** [comment]
With Micronaut 1.0 M2 we have added support for returning a `Writable`. An example of using Groovy's `SimpleTemplateEngine` can be seen here https://docs.micronaut.io/snapshot/guide/index.html#serverIO

It will therefore be pretty easy with this API to write a filter that resolves views and returns a `Writable` that writes the view on the I/O thread pool for the purposes of supporting server side views. See https://github.com/micronaut-projects/micronaut-core/blob/master/http-server-netty/src/test/groovy/io/micronaut/docs/writable/TemplateController.java
