### ISSUE TITLE
java.lang.ClassNotFoundException: kotlinx.coroutines.reactive.ReactiveFlowKt

### ISSUE THREAD

**Issue by noeliajimenezg** [micronaut-projects/micronaut-core#2571]
### Steps to Reproduce
Giving a project that implements a Consumer Pact contract using the following dependencies:

```
<dependency>
            <groupId>au.com.dius</groupId>
            <artifactId>pact-jvm-consumer-junit5</artifactId>
            <version>4.0.4</version>
</dependency>
<dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-http-client</artifactId>
            <version>1.3.0.M2</version>
</dependency>
<dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-core</artifactId>
            <version>1.3.0.M2</version>
</dependency>
```

### Expected Behaviour

The Pact consumer contract declaration should run successfully and this test too:

`
 @Test
    public void testGetVendor(MockServer mockServer) throws IOException
`

### Actual Behaviour

Micronaut throws the following exception:

java.lang.ClassNotFoundException: kotlinx.coroutines.reactive.ReactiveFlowKt

at this point [FlowConverterRegistrar.java](https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/reactive/flow/converters/FlowConverterRegistrar.java)

It seems that the version 1.3.3 of kotlinx-coroutines-core and kotlinx-coroutines-reactive used in [micronaut-core/blob/master/runtime/build.gradle](https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/build.gradle) did some changes on FlowKt on this
[commit](https://github.com/Kotlin/kotlinx.coroutines/commit/fbaedc4754eedf1082f945c7a1adb67498b2e1c4)

### Environment Information
- **Micronaut Version:** 1.3.0.M2
- **kotlinx-coroutines-core (included by pact):** 1.3.3
- **kotlinx-coroutines-reactive (included by pact):** 1.3.3
- **pact-jvm-consumer-junit5:** 4.0.4
- **kotlinx-coroutines-core (included by pact):** 1.3.2-1.3.60
- **kotlinx-coroutines-reactive (included by pact):** 1.3.2-1.3.60

### Workaround

In order to unblock the problem, I must excluded the kotlinx dependencies from micronaut-core and manually add the version 1.3.2-.1.3.60

```
<dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-core</artifactId>
            <version>1.3.2-1.3.60</version>
</dependency>
<dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-reactive</artifactId>
            <version>1.3.2-1.3.60</version>
</dependency>
<dependency>
            <groupId>io.micronaut</groupId>
            <artifactId>micronaut-core</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.jetbrains.kotlinx</groupId>
                    <artifactId>kotlinx-coroutines-core</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.jetbrains.kotlinx</groupId>
                    <artifactId>kotlinx-coroutines-reactive</artifactId>
                </exclusion>
            </exclusions>
</dependency>
```

**Comment by swarren-sumglobal** [comment]
I'm getting the exact same error, though pact is not involved. I'm using kotlinx-coroutines-core:1.3.3 fine in M1.  It was definitely introduced in M2.

**Comment by graemerocher** [comment]
Seems the `@Requires` here https://github.com/micronaut-projects/micronaut-core/issues/2215#issuecomment-541337811 needs updating to include `ReactiveFlowKt`
