### ISSUE TITLE
Referencing the `afterburner` Jackson module or registering it will cause native-image to fail.

### ISSUE THREAD

**Issue by doctorpangloss** [micronaut-projects/micronaut-core#2575]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

 1. Depend on the `afterburner` JAR in any way (including transitively), e.g. `compile 'com.fasterxml.jackson.module:jackson-module-afterburner:2.9.9'`.
 2. Observe that https://github.com/micronaut-projects/micronaut-core/blob/1cb2a3bd8b40b432013478c04e54c90001995d0e/runtime/src/main/java/io/micronaut/jackson/ObjectMapperFactory.java#L88 will register the module.
 3. `native-image` fails with an exception.

### Environment Information

- **Operating System**: macOS (native-image run in docker)
- **Micronaut Version:** 1.3.0.M2
- **JDK Version:** OpenJDK 64-Bit Server VM GraalVM CE 19.3.0.2 (build 11.0.5+10-jvmci-19.3-b06, mixed mode, sharing)

### Example Application

(In Progress)

**Comment by graemerocher** [comment]
I doubt we will be fixing this. Afterburner uses runtime byte code generation which doesn't play nicely with Graal. The dependency should be avoided in Graal targetting projects

**Comment by doctorpangloss** [comment]
Got it, let's mark this as solved then. Someone who gets the same issue as me will find this error :)
