### ISSUE TITLE
Caffeine cache: Maximum Weight configuration is invalid

### ISSUE THREAD

**Issue by ben-manes** [micronaut-projects/micronaut-core#258]
The `maximumWeight` requires a `Weigher` to evaluate the entry with. That way the user must specify the strategy, e.g. if they have a means to calculate the byte size (such as `ByteBuffer` values). The `maximumSize` is actually using a `Weigher` that always returns 1 and optimizes out the field in the entry object.

The current configuration cannot be used at runtime. The simplest would be to remove it. Alternatively, add an option to specify the `Weigher`.

https://github.com/micronaut-projects/micronaut-core/blob/2911e362353c9e57bf039c7d237789eb7b4dbde4/runtime/src/main/java/io/micronaut/cache/DefaultSyncCache.java#L126-L135

**Comment by graemerocher** [comment]
Thanks for the feedback Ben. The maximum weight is only set if set by the user so by default the config is not invalid. However I agree with you that if it is set then a weigher should be set at the same time. I will add a check for that.

**Comment by jameskleeh** [comment]
Resolved with https://github.com/micronaut-projects/micronaut-core/commit/3c14681437417f364afbc17951f952b26f132c6e

**Comment by ben-manes** [comment]
Thanks@

**Comment by jameskleeh** [comment]
@ben-manes Thank you for reporting the issue!
