### ISSUE TITLE
Management port should not respond to standard route  

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-core#2591]
Testing the last micronaut version 1.3.0.M2.

I need to use Dedicated management port as reported here #948 and fix in #2529
https://docs.micronaut.io/1.3.0.M2/guide/index.html#_management_port

It works well, the server is started on the expected port and the main server is not responding via endpoint request.

But the management port respond with all the route also declared by the user via `@Get` and also static handler.
I've the feeling the management port must handle only the management request and the request for the main webserver.

What do you think about it ?

**Comment by graemerocher** [comment]
Agreed this seems wrong
