### ISSUE TITLE
@Client constructor vs field injection

### ISSUE THREAD

**Issue by Marquis-August-Pagnin** [micronaut-projects/micronaut-core#2610]
### Steps to Reproduce

1. `git clone https://github.com/Marquis-August-Pagnin/micronaut-client-issue.git`
2. `./gradlew clean build run`
3. `curl localhost:8080/test1`
3. `curl localhost:8080/test2`

### Explanation

Two controllers inject a Client using `@Client`.  One uses field injection while other uses constructor injection.  When invoking the endpoints, different behaviors are observed

### Expected Behaviour

Both endpoints should return `http://1.1.1.1:8080/test`

### Actual Behaviour

The endpoint using field injection returns
```
Internal Server Error: Failed to inject value for parameter [client] of class: 
micronaut.client.issue.Test1\n\nMessage: Invalid service reference 
[${clients.MyClient.url:`http://1.1.1.1:8080/test`}] specified to 
@Client\nPath Taken: Test1.client"}
```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** Tested 1.2.6 & 1.2.8 & 1.3.0.M2
- **JDK Version:** 1.8

### Example Application

- https://github.com/Marquis-August-Pagnin/micronaut-client-issue

**Comment by graemerocher** [comment]
Think this may be related to the use of `private` fields which require special handling and we may deprecate support for as they require reflection to inject
