### ISSUE TITLE
Maybe wrong log level in io.micronaut.http.server.netty.converters.UnsatisfiedRouteHandler?

### ISSUE THREAD

**Issue by JoergAdler** [micronaut-projects/micronaut-core#2627]
### Steps to Reproduce

1. Setup the security sample application here https://guides.micronaut.io/micronaut-security-jwt/guide/index.html
2. Doing a POST without any body to /login

### Expected Behaviour

Getting a 400 response, with a WARNING or INFO log level in the log

### Actual Behaviour

Getting a 400 response, with an ERROR log level

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 1.2.8
- **JDK Version:** 8

### Example Application

The example from the tutorial. 

When setting up an application like the one provided in the examples about JWT security, I realized, that in the log there were errors, when I sent insufficient requests to the server. The requests resulted in 400 responses, which is fine. 
But as most likely there will be alarms on logs entries with an ERROR log level, I would not expect 400 to be logged on ERROR level.

The logging is done in io.micronaut.http.server.netty.converters.UnsatisfiedRouteHandler

Would you consider to make it configurable or at least make the log level WARNING?

**Comment by jameskleeh** [comment]
I agree that seems like incorrect behavior. Should be TRACE imo
