### ISSUE TITLE
Inconsistent json serialization behaviour with List<T> and Flowable<T>

### ISSUE THREAD

**Issue by ashishkujoy** [micronaut-projects/micronaut-core#2634]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an interface ```MovieResponse``` and two implementation of that interface ```SuccessfulMovieResponse``` and ```FailedMovieResponse```  with following json annotation on MovieResponse interface

```kotlin
@JsonTypeInfo(use = NAME, include = PROPERTY, defaultImpl = SuccessfulMovieResponse::class)
@JsonSubTypes(
    Type(value = SuccessfulMovieResponse::class, name = "successFulMovieResponse"),
    Type(value = FailedMovieResponse::class, name = "failedMovieResponse")
)
interface MovieResponse {
    val empty: Boolean
}
```
2. Create a controller with two end point one (non reactive) to return ``` List<MovieResponse> ``` and another to return ``` Flowable<MovieResponse> ```
3. Run the application and hit  non reactive end point and then the reactive endpoint

### Expected Behaviour

Both the api response should contain @type key in movie with value either "successFulMovieResponse" or "failedMovieResponse" based on the whether it is SuccessfulMovieResponse or FailedMovieResponse

### Actual Behaviour

The response from reactive api does contain @type key in each MovieResponse object but non reactive api does not container @type key

### Stracktrace
```
Error decoding HTTP response body: Error decoding JSON stream for type [interface java.util.List]: Instantiation of [simple type, class com.github.controller.SuccessfulMovieResponse] value failed for JSON property movie due to missing (therefore NULL) value for creator parameter movie which is a non-nullable type
 at [Source: (byte[])"[{"message":"Movie with Id invalid not found","empty":true}]"; line: 1, column: 59] (through reference chain: java.util.ArrayList[0]->com.github.controller.SuccessfulMovieResponse["movie"])
io.micronaut.http.client.exceptions.HttpClientResponseException: Error decoding HTTP response body: Error decoding JSON stream for type [interface java.util.List]: Instantiation of [simple type, class com.github.controller.SuccessfulMovieResponse] value failed for JSON property movie due to missing (therefore NULL) value for creator parameter movie which is a non-nullable type
 at [Source: (byte[])"[{"message":"Movie with Id invalid not found","empty":true}]"; line: 1, column: 59] (through reference chain: java.util.ArrayList[0]->com.github.controller.SuccessfulMovieResponse["movie"])
```
### Jackson Dependency
```
    compile    "com.fasterxml.jackson.module:jackson-module-kotlin:2.9.8"
    compile    "com.fasterxml.jackson.core:jackson-databind:2.9.8"
    compile     "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.9.8"
```

### Environment Information

- **Operating System**: MacOs Mojave 10.14.6
- **Micronaut Version:** 1.2.1
- **JDK Version:**
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```
### Example Application

- https://github.com/ashishkujoy/movie-store-api

**Comment by ashishkujoy** [comment]
@graemerocher Any update on this?

**Comment by ashishkujoy** [comment]
Closing this as no one is looking into this for a very long time.

**Comment by cosmin-marginean** [comment]
+1

**Comment by cosmin-marginean** [comment]
Can we reopen this actually? This seems an essential capability and we'd like to know if there are alternatives or workarounds to this requirement.
