### ISSUE TITLE
OpenTracing SpanContext not propagated between threads while handling client response (1.3.0.M2)

### ISSUE THREAD

**Issue by Marquis-August-Pagnin** [micronaut-projects/micronaut-core#2643]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Description

The following issue does not happen on 1.2.8 but does happen on 1.3.0.M2

ServiceA calls ServiceB
ServiceA then calls ServiceC with the response from ServiceB

ServiceA sets a baggageItem and it is correctly propagated to ServiceB but it is not propagated to ServiceC

Further triage appears to show that the SpanContext is not propagated between the threads in ServiceA when handling the client response

### Steps to Reproduce

1. `git clone https://github.com/Marquis-August-Pagnin/micronaut-issues.git`
2. Perform steps mentioned in [micronaut-tracing-issue/README.md](https://github.com/Marquis-August-Pagnin/micronaut-issues/blob/master/micronaut-tracing-issue/README.md)

### Expected Behaviour

ServiceB and ServiceC should both see the baggageItem set on the SpanContext from ServiceA

### Actual Behaviour

ServiceB does see the baggageItem set on the SpanContext from ServiceA
ServiceC does NOT see the baggageItem set on the SpanContext from ServiceA

### Environment Information

- **Operating System**: Any
- **Micronaut Version:** 1.3.0.M2
- **JDK Version:** openjdk version "1.8.0_232"

### Example Application

https://github.com/Marquis-August-Pagnin/micronaut-issues

**Comment by graemerocher** [comment]
Can be worked around by setting:

```
tracing:
  instrument-threads: true
```
