### ISSUE TITLE
Controller Paths are not resolved as relative paths but concatenated?

### ISSUE THREAD

**Issue by jexp** [micronaut-projects/micronaut-core#265]
For a controller like this:

1. the first method is routed to `/city/{name}`  as expected.
2. the second is routed to `/citycountry/{name}` which surprised me, I expected them to be resolved as relative paths.

```
@Controller("/city")
public class CityController {

    @Inject CityRepository repo;

    @Get("/{name}")
    public Stream<City> index(String name) {
        return repo.findByName(name);
    }

    @Get("country/{name}")
    public Stream<Map<String,Object>> country(String name) {
        return repo.findByCountry(name);
    }
}
```

**Comment by jexp** [comment]
Interestingly if you change the controller to `@Controller("/city/")`
the 2nd method is resolved correctly. 

But the first can't be addressed anymore, as it is probably resolved to `/{name}` which is not routed to/through the `/city/` controller.

**Comment by akozel** [comment]
I would like to add one more thing here.
```
@Get("/some")
    public String index() {
        return "hello";
    }
```

Is available by URL: `localhost:8080/some`
but `localhost:8080/some/` throws an error.

I think that is the same URI.
