### ISSUE TITLE
Document behaviour of package scanning for tests and applications

### ISSUE THREAD

**Issue by georgecodes** [micronaut-projects/micronaut-core#266]
### Steps to Reproduce

1. Create a new project 
2. Add JPA support
3. Configure a datasource in application.yml
4. Add a controller into which a SessionFactory is injected
5. Add a Spock test to exercise it
6. Add a Junit test to exercise it

### Expected Behaviour

Both the Spock and JUnit tests should pass.

### Actual Behaviour

The Spock test passes, the JUnit test fails, complaining that no implementation of SessionFactory exists.

### Environment Information

- **Operating System**: OSX, Linux
- **Micronaut Version:** 1.0.0.M1
- **JDK Version:** 1.8.0_112

### Example Application

Repository with example https://github.com/georgecodes/micronaut-weirdness
CircleCI https://circleci.com/gh/georgecodes/micronaut-weirdness

**Comment by graemerocher** [comment]
Seems to be a bug in automatic package detection. Micronaut by default will use the package of your test to look for entities to scan for. The back in this case is `micronaut.bug`. This doesn't seem to be working for JUnit in this case. 

You can workaround this issue with the following diff:

```diff
-        server = ApplicationContext.run(EmbeddedServer.class);
+        server = ApplicationContext.build()
+                                   .packages("micronaut.bug")
+                                   .start()
+                                   .getBean(EmbeddedServer.class)
+  
```

**Comment by georgecodes** [comment]
Thanks Graeme.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/f2404d44355386612dea98c9d4e2adbd9d601bd3
