### ISSUE TITLE
VisitorContext.getClassElement() always returns JavaClassElement object instance

### ISSUE THREAD

**Issue by ghost** [micronaut-projects/micronaut-core#2660]
We are using this method in our custom swagger processor, inspired on the openapi annotation processor provided out the box.

However, the method always returns a JavaClassElement instance which breaks all the swagger annotation processing logic which performs "instanceof EnumElement" on the returned type.

Perhaps it is possible for this method to be made more intelligent to return instances of an appropriate type?

This likely affects the out-the-box swagger annotation processor because I believe the piece of code that is failing to handle Enum types is from the original codebase.

Method from JavaVisitorContext below for reference:

    @Override
    public Optional<ClassElement> getClassElement(String name) {
        TypeElement typeElement = elements.getTypeElement(name);
        return Optional.ofNullable(typeElement).map(typeElement1 ->
                new JavaClassElement(typeElement1, annotationUtils.getAnnotationMetadata(typeElement1), this, Collections.emptyMap())
        );
    }

**Comment by jameskleeh** [comment]
Yeah seems like it could be returning more specific types. PR welcome!

**Comment by abedurftig** [comment]
@jameskleeh, while the required code change seems fairly simple, I have not idea how to write a test for this. Would you have any pointers?

**Comment by jameskleeh** [comment]
@abedurftig See https://github.com/micronaut-projects/micronaut-core/blob/2.0.x/inject-java/src/test/groovy/io/micronaut/visitors/CustomVisitorSpec.groovy. You would have to create a test visitor that uses that code, then inspect the result after. Note there is a CustomVisitorSpec in the inject-groovy project that would need to be done as well.

**Comment by preyest1300** [comment]
Hi! I have a question. What do you mean with appropriate type? Can you give me an example of the output that you expect to recieve?

**Comment by sapanparikh18** [comment]
Hi @jameskleeh I wrote a test case that looks like the following

```java
    void "test VisitorContext.getClassElement() should return more specific type"() {
        buildBeanDefinition('customvis1.TestController', '''
package customvis1;

public enum TestDay {
    SUNDAY, MONDAY, TUESDAY, WEDNESDAY,
    THURSDAY, FRIDAY, SATURDAY
    public getDay(){
        this.name();
    } 
}
''')
        expect:
        AllClassesVisitor.getVisitorContext().getClassElement("customvis1.TestDay").get() instanceof EnumElement
    }
```

It seems to be passing, I also did a little more digging and found that 

JavaElementFactory already returns the appropriate (enum) type. Here is the method from there

```java
    @NonNull
    @Override
    public JavaClassElement newClassElement(
            @NonNull TypeElement type,
            @NonNull AnnotationMetadata annotationMetadata) {
        ElementKind kind = type.getKind();
        if (kind == ElementKind.ENUM) {
            return new JavaEnumElement(
                    type,
                    annotationMetadata,
                    visitorContext
            );
        } else {
            return new JavaClassElement(
                    type,
                    annotationMetadata,
                    visitorContext
            );
        }
    }
```

Same applies to Groovy classes. Are we missing anything?

**Comment by graemerocher** [comment]
Yeah this logic has been refactored and now works as expected. Thanks for investigating
