### ISSUE TITLE
Support for suspending Http Filters [Feature Request]

### ISSUE THREAD

**Issue by sollecitom** [micronaut-projects/micronaut-core#2666]
Now that Micronaut supports suspending endpoint functions, it would be great to support Kotlin coroutines from Http Filters.

**Comment by jameskleeh** [comment]
I'm not sure how this would be possible given the API is defined as returning a `Publisher`

**Comment by sollecitom** [comment]
Well, I use a workaround for now, using the coroutines rx2 module.

**Comment by jameskleeh** [comment]
I can't envision a case where we would change the API to be language specific so I'm going to close this issue
