### ISSUE TITLE
@Client issue: GET Flux;

### ISSUE THREAD

**Issue by akozel** [micronaut-projects/micronaut-core#267]
Please see test case:
https://github.com/akozel/micronaut-hello-world/tree/master

Does not work:
```
    @Test
    void testFlux() throws Exception {
        List<Person> personList = personClient.fluxAll().collectList().block();
        Assertions.assertEquals(4, personList.size());
    }
```

P.s. another issue I fixed by myself.

**Comment by graemerocher** [comment]
Please provide a full example that reproduces the issues in this report
