### ISSUE TITLE
Regression: default value is overridden with null if no value provided

### ISSUE THREAD

**Issue by ivyazmitinov** [micronaut-projects/micronaut-core#2670]
### Steps to Reproduce

1. Create a `@Nullable` `Set<String>` field with `@Value` annotation initialized with a default value, as follows:
```java
    @Value("${fields}")
    @Nullable
    private Set<String> nullableSet = new HashSet<>();
``` 
2. Start an application and observe the field's  value

### Expected Behaviour

`nullableSet` contains `HashSet<>()`

### Actual Behaviour

`nullableSet` contains `null`

### Environment Information

- **Micronaut Version:** 1.2.9

Isn't reproduced on 1.2.8

### Example Application

https://github.com/ivyazmitinov/micronaut-nullable-bug

**Comment by jameskleeh** [comment]
Thanks for the report
