### ISSUE TITLE
Release the following modules and update the BOM

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#2682]
Release new versions of the following micronaut modules and update the bom for Micronaut 1.3.0.RC1:

```
gcp
micrometer
test
hibernate-validator
jmx
picocli
rabbitmq
groovy
elasticsearch
kubernetes
cache
```

**Comment by graemerocher** [comment]
Why are new modules needed for all of these?

**Comment by ilopmar** [comment]
i've gone through all the modules in gradle.properties, do git pull and gitk to see if there were commits after the latest version
for a few of them there were only upgrade some dependencies for tests so I didn't include them in the list

**Comment by ilopmar** [comment]
Those modules contain changes that we have not released yet. For a few of them there were only some dependencies upgrade (patch versions and sometimes only for test scope) so I didn't include them in the list

**Comment by graemerocher** [comment]
I updated the critical ones, the remainders can see patch releases in future 1.3.x releases
