### ISSUE TITLE
Validation annotations not working on abstract class

### ISSUE THREAD

**Issue by JEDIBC** [micronaut-projects/micronaut-core#2687]
### Steps to Reproduce

1. Create a java micronaut application
2. Create a `Config` and `AbstractConfig` class like :

```java
@ConfigurationProperties("my.config")
@Introspected
public class Config extends AbstractConfig{
}

abstract public class AbstractConfig {

    @NotNull
    @Min(1)
    @Max(10)
    private Integer count = 0;

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }
}
```
3. create the config informations in application.yml :

```yml
---
my:
  config:
     count: 0
```

4. Inject the `Config` on something that is called at the startup of the application
5. Start the application

### Expected Behaviour

We should have an exception on startup looking like the one I have when all the properties are in the `Config` class and not the `AbstractConfig` class :

```
Message: Validation failed for bean definition [my.Config]
List of constraint violations:[
	count - must be greater than or equal to 1
]
```

### Actual Behaviour

Nothing happen

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Micronaut Version:** 1.2.9
- **JDK Version:** openjdk 11.0.5

**Comment by jameskleeh** [comment]
I can't reproduce. Please upload a sample application

**Comment by jameskleeh** [comment]
Closing due to lack of feedback. Will reopen if you get around to uploading an app

**Comment by JEDIBC** [comment]
Hi,

Here's a sample application : https://github.com/JEDIBC/micronaut-validation-annotation

In `micronaut.validation.annotation.listener.ApplicationStartupListener` or `micronaut.validation.annotation.controller.ConfigController` I inject an invalid `MyConfig` and it doesn't throw an exception. I also inject the `Validator` which properly detect the violation if called manually.

Regards

Bruno

**Comment by jameskleeh** [comment]
The validation annotations are on private fields in the abstract class, so the subclass has no visibility to it. Move the annotations to the getter method and it will behave as you expect.
