### ISSUE TITLE
Interceptor returns originalParameters instead of Mutable parameters in Micronaut 1.2.1 and above

### ISSUE THREAD

**Issue by jzuijlek** [micronaut-projects/micronaut-core#2693]
In version Micronaut 1.2.1 a new `getParameterValues()` method was introduced that overwrites the `getParameterValues()` from `InvocationContext`.

https://github.com/micronaut-projects/micronaut-core/blob/master/aop/src/main/java/io/micronaut/aop/chain/InterceptorChain.java#L87

https://github.com/micronaut-projects/micronaut-core/blob/master/aop/src/main/java/io/micronaut/aop/InvocationContext.java#L88

The new one return the `originalParameters` instead of the mutated arguments that `getParameterValues()` from `InvocationContext` returns. Now the annotated controller function doesn't get the arguments mutated in the inspectors.

### Steps to Reproduce

Let take a simple interceptor that injects a `sheep` parameter.

``` kotlin
@Singleton
class SheepInterceptor : MethodInterceptor<Any, Any> {
	override fun intercept(context: MethodInvocationContext<Any, Any>) {
		val sheep = context.parameters["sheep"]?.value as String
		context.parameters["sheep"] = MutableArgumentValue.create(Argument.STRING, "bleat")
		context.proceed()
	}
}
```

Now in an annotated controller function should be able to do:

``` kotlin
	@Produces(MediaType.TEXT_PLAIN)
	@Sheep
	@Get("/")
	fun getSheep(name: String, sheep: String?) = sheep?.let { sheep.plus(" ").plus(name) }
```

### Expected Behaviour

Sheep should be `bleat`

### Actual Behaviour

Sheep is `null`

### Environment Information

- **Micronaut Version:** 1.2.1 and above
- **JDK Version:** OpenJDK 11

**Comment by graemerocher** [comment]
The bug here is that `context.parameters` is mutable. You should only be able to set the value not create and override new instances of `MutableArgumentValue`

**Comment by jzuijlek** [comment]
According to the docs from `InvocationContext`:

> An InvocationContext passed to one or many {@link Interceptor} instances. Attributes can be stored within the
> context and shared between multiple {@link Interceptor} implementations. The {@link #proceed()} method should be
> called to proceed to the next {@link Interceptor} with the last interceptor in the chain being the original
> decorated method implementation.
> 
> The parameters to pass to the next {@link Interceptor} can be mutated using {@link MutableArgumentValue}
> interface returned by the {@link #getParameters()} method

We have use cases where we need to introduce parameters that are needed by the several controllers. Otherwise Interceptor functionality is quite limiting.

**Comment by graemerocher** [comment]
My statement doesn't contradict the javadoc. It says `The parameters to pass to the next {@link Interceptor} can be mutated using {@link MutableArgumentValue}`

So you would do:

```
context.parameters["sheep"].value = "bleat"
```

**Comment by jzuijlek** [comment]
`context.parameters["sheep"]` is not null safe, so that doesn't work.

**Comment by graemerocher** [comment]
I imagine you would have to check for null then
