### ISSUE TITLE
Feature Request: add possibility to black list annotations

### ISSUE THREAD

**Issue by croudet** [micronaut-projects/micronaut-core#2703]
In the generated classes.

Use case: OpenApi annotations (swagger) have a runtime retention policy, but with micronaut-openapi all the processing is done at compile time so the annotations are not anymore useful at runtime.
Using java flight recorder I saw some ClassNotFoundException at startup for those annotations (I don't include swagger-annotations.jar at runtime.)

**Comment by graemerocher** [comment]
I think in general we need to support two things better:

1. Annotation transformation, disregarding the original annotation (we have `AnnotationMapper` but that keeps the original annotation around). We need a new interface like `AnnotationTransformer` for that.
2. Properly handle source vs runtime retention in annotations and allow a `AnnotationTransformer` to make a runtime annotation source level if required (your use case).

**Comment by graemerocher** [comment]
This was fixed with the support for source level annotations
