### ISSUE TITLE
GraalVM DockerFile with wrong line order

### ISSUE THREAD

**Issue by liefra** [micronaut-projects/micronaut-core#2713]
In Micronaut 1.3.0.RC1 the GraalVM DockerFile line order is wrong, as the `RUN native-image` command is being executed before the `COPY` command. 

### Steps to Reproduce

`mn create-app micronautapp --features graal-native-image`

### Expected Behaviour

```
FROM oracle/graalvm-ce:19.3.1-java8 as graalvm
#FROM oracle/graalvm-ce:19.3.1-java11 as graalvm # For JDK 11
COPY . /home/app/micronautapp
WORKDIR /home/app/micronautapp
RUN gu install native-image
RUN native-image --no-server --static -cp build/libs/micronautapp-*-all.jar
```

### Actual Behaviour
Current Dockerfile
```
FROM oracle/graalvm-ce:19.3.1-java8 as graalvm
#FROM oracle/graalvm-ce:19.3.1-java11 as graalvm # For JDK 11
RUN gu install native-image
RUN native-image --no-server --static -cp build/libs/micronautapp-*-all.jar
COPY . /home/app/micronautapp
WORKDIR /home/app/micronautapp
```
Causes:
**Error**: Please specify class containing the main entry point method. (see --help)
The command `/bin/sh -c native-image --no-server --static -cp build/libs/micronautapp-*-all.jar'` returned a non-zero code: 1

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** 1.3.0.RC1
- **JDK Version:** 13

**Comment by recursivecodes** [comment]
I can confirm this bug - just came here to report the same.
