### ISSUE TITLE
Allow custom ChannelHandlers to control their position

### ISSUE THREAD

**Issue by whiskeysierra** [micronaut-projects/micronaut-core#2719]
See https://github.com/zalando/logbook/issues/629. I have a custom netty channel handler that I need to register after the http request decoder/response encoder so that I can observe the request/response as messages in my channel handler.

Plain netty supports this in their `HttpServer` setup like this:

```java
HttpServer.create()
        .tcpConfiguration(tcpServer ->
                tcpServer.doOnConnection(connection ->
                        connection.addHandlerLast(new LogbookServerHandler(logbook))))
```

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. TODO
2. TODO
3. TODO

### Expected Behaviour

Tell us what should happen

### Actual Behaviour

Position in the channel pipeline can't be controlled.

### Environment Information

- **Operating System**: TODO
- **Micronaut Version:** TODO
- **JDK Version:** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by croudet** [comment]
I have an `HttpServerAccessLogger` class, that can help you for the moment:
https://gist.github.com/croudet/52386eb4a315fb7764b83bc12f522db5

**Comment by dstepanov** [comment]
I think the best idea would be to allow to set custom handlers in `HttpClientConfiguration`.

**Comment by graemerocher** [comment]
Relates to  #1113

**Comment by graemerocher** [comment]
Fixed in 2.x and added documentation on how to use logbook https://docs.micronaut.io/snapshot/guide/index.html#nettyPipeline

**Comment by dstepanov** [comment]
@graemerocher Looks great!
Is it possible to have a separate customizer for server and client?

**Comment by graemerocher** [comment]
Sure just check the `isServerChannel()` method
