### ISSUE TITLE
Can't get @Blocking working in kotlin project?

### ISSUE THREAD

**Issue by jisikoff** [micronaut-projects/micronaut-core#2727]
@Blocking is not scheduling the work on another thread besides the event loop in my kotlin projects.

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Make a controller that returns a reactive method but that you annotate with @Blocking to schedule somewhere besies the eventloop:
```
@Controller("/test")
open class TestController() {

    @Get("/reactiveblocking")
    @Blocking
    open fun reactiveBlocking(): Single<String> {
        return Single.fromCallable({ -> "thread: ${Thread.currentThread().name}" })
    }
}
```

2. Write a test to see where this is actually getting scheduled
```
@MicronautTest
class TestControllerSpec: StringSpec() {

    @Inject
    lateinit var server: EmbeddedServer

    @Inject
    @field:Client("/")
    lateinit var client: HttpClient


    init {
        "@blocking annotated controllers should return string indicating the thread is on the io pool not the event pool" {
            val rsp: String = client.toBlocking().retrieve("/test/reactiveblocking")
            rsp shouldContain "pool-"
        }
    }
}
```

### Expected Behaviour

Test should pass as I assume this this test does in the core code:
https://github.com/micronaut-projects/micronaut-core/blob/master/http-server-netty/src/test/groovy/io/micronaut/http/server/netty/threading/ThreadSelectionSpec.groovy#L34

### Actual Behaviour

Test fails, annotation seems not to have any effect.
```
thread: nioEventLoopGroup-1-3 should include substring pool-
java.lang.AssertionError: thread: nioEventLoopGroup-1-3 should include substring pool-
```

### Environment Information

- **Operating System**: MacOs Mohave
- **Micronaut Version:** 1.3.0.RC1
- **JDK Version:** OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)

### Example Application

- https://github.com/jisikoff/micronaut-issue-2727

**Comment by jameskleeh** [comment]
I cannot reproduce with Micronaut 1.3.6
