### ISSUE TITLE
Cookie: add support of SameSite attribute

### ISSUE THREAD

**Issue by fedotxxl** [micronaut-projects/micronaut-core#2736]
It becomes a pretty important attribute with Chrome 80 release - https://web.dev/samesite-cookies-explained/
Workaround worked for me - specify SameSite attribute in value: `myCookieValue + "; SameSite=None"`

**Comment by skwakman** [comment]
Quickly looking at the micronaut-code code, it seems that resolving this issue would become very easy when Netty starts supporting SameSite attributes in its cookie interface. It seems this will happen not too far in the future: https://github.com/netty/netty/issues/8161

**Comment by renannprado** [comment]
@graemerocher I was about to pick up this issue to work on, but I saw that it was fixed as part of #2956. Can it be closed?

**Comment by graemerocher** [comment]
You are correct. Thanks
