### ISSUE TITLE
Content Negotiation Problem with Jackson XML

### ISSUE THREAD

**Issue by JEDIBC** [micronaut-projects/micronaut-core#2743]
Hi,

The content negociation depending on the `accept` http header doesn't work (or there's some configuration not described in the doc)

### Steps to Reproduce

1. Create a 1.3 project
2. Add https://github.com/micronaut-projects/micronaut-jackson-xml dependency to be able to bind & serialise XML
3. Create a controller with `@Consumes({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})` and `@Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})`
4. call your controller with the `accept: application/xml` header

### Expected Behaviour

The result should be in XML.

### Actual Behaviour

The result is still in JSON

I must say that if you only need XML output and add `@Produces(MediaType.APPLICATION_XML)` in your controller, the ouput is correctly serialized in XML.

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Micronaut Version:** 1.3.0
- **JDK Version:** 11.0.5

Thanks

Regards,

Bruno

**Comment by JEDIBC** [comment]
In addition, if I call the controller with a not managed content type, say `accept: text/csv` it still return JSON instead of returning a `406 Not Acceptable` return code.

Regards,

Bruno

**Comment by graemerocher** [comment]
Was decided that this is too big a change for 1.3.x so will go into 2.0.x
