### ISSUE TITLE
[question] There is a way to use micronaut to be a socket server only?

### ISSUE THREAD

**Issue by prsolucoes** [micronaut-projects/micronaut-core#2745]
Hi,

There is a way to use micronaut to be a socket server only?

I want convert my golang GPS tracker system to micronaut with java. And the GPS system is a socket server that receive thousands of TCP/UDP/HTTP connections.

Can i use http server, tcp server and websocket server using micronaut? 

There is some example?

Thanks.

**Comment by jameskleeh** [comment]
Please ask questions in [Gitter](gitter.im/micronautfw )
