### ISSUE TITLE
Change in behavior (1.3.0) - AnnotationProxyHandler.invoke

### ISSUE THREAD

**Issue by alexwilbur** [micronaut-projects/micronaut-core#2748]
We have been using various Micronaut releases all the way up to 1.2.8 most recently

We have custom annotations that we use for our security tier. One of the attributes of these annotations contains a value that is a bit like a placeholder syntax - we retrieve security context from our framework and then fill in some placeholders to construct a literal value.

This has been working fine from Micronaut 1.x -> 1.2.8

However, now in testing 1.3.0 we have detected that our annotation values are being modified, whereas previously they worked.

Example of something working fine in v1.2.8:

@OurCustomAnnotation(value="${Category:Group}")

In 1.2.8 and earlier, when we resolve the value via AnnotationValue<...> and the reflection-free metadata, we used to get a value exactly as per the literal interpretation of the above annotation "value".

However in 1.3.0 the return value is now "Group"

In debugging, it looks like this change breaks compatibility:

https://github.com/micronaut-projects/micronaut-core/commit/72f8227fd4ba774346674c3fb42a105ad378d6ac#diff-7587aaf53b37143ba56dced31e7b44edR295

calling annotationValue.getRequiredValue() now in 1.3.0 invokes the PropertyPlaceholderResolver, whereas in prior releases it simply retrieved the values from the "resolvedValues" map:

(v1.2.8 for reference):

```
        public Object invoke(Object proxy, Method method, Object[] args) {
            String name = method.getName();
            if ((args == null || args.length == 0) && "hashCode".equals(name)) {
                return hashCode;
            } else if ((args != null && args.length == 1) && "equals".equals(name)) {
                return equals(args[0]);
            } else if ("annotationType".equals(name)) {
                return annotationClass;
            } else if (resolvedValues.containsKey(name)) {
                return resolvedValues.get(name);
            }
            return method.getDefaultValue();
        }
```

**Comment by graemerocher** [comment]
Thanks for the feedback. We will need to think about this one since for me this seems like more of a bug fix (although we probably should have noted in the breaking changes). The syntax with annotations that includes `${..}`  is reserved for property placeholders resolved from configuration. If there was a case where this was not happen one could consider it as a bug. Is there a reason you need to use the `${..}` syntax in your custom annotation?

**Comment by graemerocher** [comment]
Closed for lack of feedback

**Comment by alexwilbur** [comment]
There was a Good Reason why we did this, but I can't figure out it anymore, and doing some casual testing with prior versions would suggest that the original issue is not reproducible anymore (I only went back as far as 1.1.x). 

I think we can live with this so no issue closing. We'll workaround it.
