### ISSUE TITLE
Add optional configuration to support binding objects to XML using Jackson XML

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#275]
Some folks are still interested in consuming and exposing XML APIs.

We should add an optional module for this based off https://github.com/FasterXML/jackson-dataformat-xml

This would involve adding a `XmlCodec` (equivalent to `JsonCodec`) and beans for the `XmlMapper` etc.

**Comment by ilopmar** [comment]
Pending on this: https://github.com/FasterXML/jackson-dataformat-xml/issues/260

**Comment by ilopmar** [comment]
The `configuration:jackson-xml` project and a basic version to produce XML is in this branch: https://github.com/micronaut-projects/micronaut-core/commits/issue-275-xml

**Comment by jameskleeh** [comment]
Closed by https://github.com/micronaut-projects/micronaut-jackson-xml
