### ISSUE TITLE
ConfigurationProperties doesn't work with private fields

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-core#2754]
### Steps to Reproduce

1. Create a new application
2. Create a configuration properties Java class with some default values
3. Create a configuration file `application.yml` to override the default configuration

### Expected Behaviour

When the configuration is read then the values from `application.yml` overrides the default values.

### Actual Behaviour

Only the default values are present in the configuration.

### Environment Information

- **Operating System**: Darwin
- **Micronaut Version:** 1.3.0
- **JDK Version:** Java 8

### Example Application
See [Micornaut Configuration Strategies](https://github.com/agorapulse/micronaut-configration-strategies)

There is [Configuration Class](https://github.com/agorapulse/micronaut-configration-strategies/blob/master/simple/simple-configuration-two/src/main/java/com/agorapulse/micronaut/configuration/strategies/simple/two/SimpleConfigurationTwo.java) which cannot be overriden using [Configuration File](https://github.com/agorapulse/micronaut-configration-strategies/blob/master/simple/simple-application/src/main/resources/application.yml).

1. Check out the repository `git clone https://github.com/agorapulse/micronaut-configration-strategies.git`
2. Run ` ./gradlew :simple-application:runShadow`
3. Read the configuration values `curl http://localhost:8080/simple` or using the [HTTP Test File](https://github.com/agorapulse/micronaut-configration-strategies/blob/master/simple/simple.http)

**Comment by jameskleeh** [comment]
Are you asserting that this used to work? If so, what version?
Are you asserting this should work? If so, what gives you that impression?

**Comment by jameskleeh** [comment]
I did a little research and I don't think this was ever supported

**Comment by musketyr** [comment]
I'm sorry for panicking.  I was following [Configuration Properties](https://docs.micronaut.io/latest/guide/index.html#configurationProperties) section of the docs and I missed the setters. Thanks for a fast response!
