### ISSUE TITLE
Use generic configuration of the run task in Gradle builds

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-core#2765]
### Steps to Reproduce

1. Create a new application with Gradle build

### Expected Behaviour

Both application tasks `run` and `runShadow` are configured in the same way.

### Actual Behaviour

Only `run` task is configured which means that if you want to `runShadow` to verify the deployment package then you have to either duplicate the configuration of the task or use `tasks.withType(JavaExec) { }`

### Environment Information

- **Operating System**: Darwin
- **Micronaut Version:** 1.3.0
- **JDK Version:** Java 8

### Example Application

The following snippet can configure both - the `run` task and `runShadow` task as well.

```
tasks.withType(JavaExec) {
    classpath += configurations.developmentOnly
    jvmArgs('-noverify', '-XX:TieredStopAtLevel=1', '-Dcom.sun.management.jmxremote')
}
```

**Comment by alvarosanchez** [comment]
Would you rather send a PR changing https://github.com/micronaut-projects/micronaut-profiles/blob/master/base/features/application/skeleton/gradle-build/build.gradle#L6-L7 ?

**Comment by musketyr** [comment]
sure, see https://github.com/micronaut-projects/micronaut-profiles/pull/237
