### ISSUE TITLE
Injected Clients interfere in Micronaut Test

### ISSUE THREAD

**Issue by stepanv** [micronaut-projects/micronaut-core#2769]
Consider following test snippet
```java
@MicronautTest
public class TestClientConfigurationInterferenceInjection {

    @Inject
    @Client(value = "/", configuration = TestNoFollowRedirectClientConfig.class)
    RxHttpClient clientNoFollow;

    /**
     * Should use {@link DefaultHttpClientConfiguration}.
     */
    @Inject
    @Client(value = "/")
    RxHttpClient clientFollow;
}
```
In this case, both clients are the same instance and share the same configuration even though each was declared to use different configuration.

The reproducer is submitted as PR: https://github.com/micronaut-projects/micronaut-test/pull/110

**Comment by stepanv** [comment]
@jeffbrown, yeah, I originally thought it's related to `@MicronautTest` but then I was looking at the `HttpClientIntroductionAdvice#getClient()` and apparently, it's a micronaut-core feature/bug as you're "caching" the client in the map and the key is determined by clientId and path at `computeClientKey()`
cc @jameskleeh

**Comment by stepanv** [comment]
That being said, I'd suggest to either 
* document the behavior clearly, warn the user if he happens to inject the same client+path with different annotation coordinates (e.g., configuration) - if it's a feature
* or extend the map key to include anything one can put into the `@Client` annotation
I can do a PR for the latter one if you're time challenged.

I was kinda playing with some other client features and I found several other issues (submitted as https://github.com/micronaut-projects/micronaut-core/pull/2762 (sorry for mixing several things into one issue))

**Comment by jameskleeh** [comment]
The key should include the whole annotation.

**Comment by graemerocher** [comment]
I am currently rewriting this area of Micronaut for 2.0 which would resolve this
