### ISSUE TITLE
ApplicationContext.run() firing context start twice

### ISSUE THREAD

**Issue by ctoestreich** [micronaut-projects/micronaut-core#277]
When running tests the DefaultApplicationContext and DefaultBeanContext are both running start not he bean context.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

I ran into this by simply adding an event listener to there started event.

```java
package io.micronaut.configuration.metrics.micrometer;

import io.micronaut.context.event.ApplicationEventListener;
import io.micronaut.context.event.StartupEvent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.inject.Singleton;

@Singleton
public class SimpleApplicationEventListener implements ApplicationEventListener<StartupEvent> {

    private static final Logger LOGGER = LoggerFactory.getLogger(SimpleApplicationEventListener.class);

    @Override
    public void onApplicationEvent(StartupEvent event) {
        LOGGER.info("EVENT FIRED");
    }
}
```

In the console I see

```bash
09:00:25.858 [Test worker] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
09:00:25.869 [Test worker] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
09:00:29.957 [Test worker] INFO  i.m.c.m.m.SimpleApplicationEventListener - EVENT FIRED
09:00:31.071 [Test worker] INFO  i.m.c.m.m.SimpleApplicationEventListener - EVENT FIRED
```
When running tests using `ApplicationContext.run()` application context, events, etc are firing twice.

Here are the stack traces for running a single test as follows

```groovy
void "verify beans created by default"() {
        when:
        ApplicationContext context = ApplicationContext.run()

        then:
        context.containsBean(CompositeMeterRegistry)
        context.containsBean(SimpleMeterRegistry)
        context.containsBean(MeterRegistryConfigurer)

        cleanup:
        context.close()
    }
```

<img width="1627" alt="screen shot 2018-06-08 at 8 39 07 am" src="https://user-images.githubusercontent.com/691357/41161978-1a05834a-6afa-11e8-98c9-a152d253b89f.png">
<img width="1551" alt="screen shot 2018-06-08 at 8 38 49 am" src="https://user-images.githubusercontent.com/691357/41161979-1a189246-6afa-11e8-8981-8d033a64b4c6.png">

### Environment Information

- **Operating System**: OSX 10.13
- **Micronaut Version:** 1.0.0.BUILD-SNAPSHOT
- **JDK Version:** 1.8 171

**Comment by ctoestreich** [comment]
I see this happening in other tests as well example: https://travis-ci.org/micronaut-projects/micronaut-core/jobs/389619061#L1677

**Comment by ctoestreich** [comment]
@graemerocher I am still seeing this fire twice for tests.  It looks like when **running** the application only a single event is fired, but tests are triggering 2 still using `EmbeddedServer server = ApplicationContext.run(EmbeddedServer.class);`.  Seems minor, but I can't quite put my finger on if this is intended, and if not, if it will create any issues.

**Comment by graemerocher** [comment]
@ctoestreich The line linked to about doesn't seem to point to the output you are referring to. Can you point out a concrete test where this is happening?

**Comment by ctoestreich** [comment]
It looks like the event is only firing once.  I can confirm this appears to be fixed.

**Comment by seancarroll** [comment]
I've seem to have hit this as well running Micronaut 1.1.2. I have a test here https://github.com/seancarroll/jmediator/blob/master/jmediator-samples/jmediator-sample-micronaut/src/test/java/jmediator/sample/SampleMicronautControllerTest.java and the actual ApplicationEventListener  is here https://github.com/seancarroll/jmediator/blob/master/jmediator-micronaut/src/main/java/jmediator/micronaut/RequestHandlerProviderImpl.java.

I've started to attempt to dig into it more and determine where the events are being fired from.

**Comment by seancarroll** [comment]
Discovered the cause was because I was using `@MicronautTest` and `ApplicationContext.run(EmbeddedServer.class);`

**Comment by graemerocher** [comment]
yeah that is not needed as `@MicronautTest` already starts your server. If you are using `ApplicationContext.run(EmbeddedServer.class);` you should remove `@MicronautTest`
