### ISSUE TITLE
Don't allow generated property combinations from environment variables to be used by @EachProperty

### ISSUE THREAD

**Issue by ckosmowski** [micronaut-projects/micronaut-core#2790]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a micronaut app
2. Override configuration through environment variables
3. Generated variables will break things

### Expected Behaviour

Find a clear way to make sure environment variables are only generated in one single way:
DATASOURCES_DEFAULT_URL -> "datasources.default.url"

I expect that either only one representation is used or there is at least a configuration option to disable the variety of interpretations

### Actual Behaviour

Mirconaut generates a variety of different interpretations of the env variable:
DATASOURCES_DEFAULT_URL -> "datasources.default.url"
DATASOURCES_DEFAULT_URL -> "datasources.default-url"

the second case here breaks i.e. micronaut data because it thinks there should be a datasource created called "default-url".

I also tried the following:
```
Micronaut.build(null)
                .mainClass(Application.class)
                .environmentVariableIncludes("DATASOURCES_DEFAULT_URL", "DATASOURCES_DEFAULT_USERNAME", "DATASOURCES_DEFAULT_PASSWORD")
                .start();
```
but still the wrong configs are created

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.3.0.RC1
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
We are aware of this problem the solution is to use your own property as a value:

```
datasources:
      default:
             url: "${my.datasource.url}"
```

And then set `MY_DATASOURCE_URL`

I think we should consider changing this behaviour in Micronaut 2.0 since it would be a breaking change to change it for 1.x

**Comment by ckosmowski** [comment]
Okay thanks! That's a better solution i wasn't aware that there can be cross references in the configs, we used JSON config for a workaround:
```
MICRONAUT_APPLICATION_JSON={"datasources":{"default":{"url": "jdbc:mysql://[...]", "username":"user", "password": "xxxxx"}}}
```
