### ISSUE TITLE
Make raw http response body available to client filters

### ISSUE THREAD

**Issue by jdvega-tuenti-com** [micronaut-projects/micronaut-core#2795]
As commented on [Gitter](https://gitter.im/micronautfw/questions?at=5e429551cd2d737bb06eeb31) we have been implementing a response signature validation using a `HttpClientFilter`. This is nearly impossible due to body conversion on the available `HttpResponse` at  `doFilter` level.

We have found a way to make it works casting the response to an internal class, something similar to:

```kt
class ResponseFilter : HttpClientFilter {
    override fun doFilter(request: MutableHttpRequest<*>?, chain: ClientFilterChain?): Publisher<out HttpResponse<*>> {
        return Flowable.fromPublisher(chain!!.proceed(request)).filter {
            val fullyNettyClientHttpResponse = it as FullNettyClientHttpResponse
            val jsonMap = fullyNettyClientHttpResponse.getBody(Argument.of(Map::class.java)).map {
                it as Map<String, Any>
            }.orElse(emptyMap()) // we know that raw body is a serialized json, so a map will do the trick
            ...
           // code that validates raw json response body as map
            ...
        }
    }
....
}
```

It would be nice to have some public method that can access to raw http response, or at least make easy to access to the original raw http response body provided by public interface `HttpResponse`.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a `HttpClientFilter`
2. Try to get raw http response body (eg: bytes) from `HttpResponse`

### Expected Behaviour

Raw http response body is avaible in any ways at throw `HttpResponse` public interface

### Actual Behaviour

`HttpResponse`'s  body getters return a dto that is already parsed and serialized

### Environment Information

- **Operating System**: Any
- **Micronaut Version**: 2.9.7
- **JDK Version:** Any
- **Kotlin Version:** Any

### Example Application

Check example code above.

**Comment by graemerocher** [comment]
This should be done with channel handlers in Micronaut 2.x. See #2719
