### ISSUE TITLE
Support Groovy 3

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-core#2811]
Work started on the `groovy3` branch

Currently blocked by https://issues.apache.org/jira/browse/GROOVY-9399

**Comment by jameskleeh** [comment]
Issue above was resolved and confirmed to be working. Build is now passing with my locally installed Groovy 3.0.2 snapshot. Waiting for the release

**Comment by benmccann** [comment]
Groovy 3.0.3 is now available
