### ISSUE TITLE
Declarative HTTP client corrupts some binary data

### ISSUE THREAD

**Issue by swaechter** [micronaut-projects/micronaut-core#2836]
I am using Micronaut with the HTTP client and the OpenAPI plugin for my bachelor thesis where I exchange files with their SHA2 hashes. For some documents, mainly binary files like PDF, I encountered different SHA2 hashes than from the files persisted on the disk.

A minimal KISS example: A file server were you can upload files and then download them. The endpoints:

* Uploads: `POST` with `file` to `/uploadFile`
* Downloads:
  * a.) `GET` to `/downloadFileBySystemFile`: A direct download of the file via `SystemFile`. Works all the time
  * b.) `GET` to `/downloadFileByHttpClient`: An indirect download that uses the declarative HTTP client to access `downloadFileBySystemFile`. Some downloads there are corruped (See screenshot bellow)
  * c.) Manually via the Swagger interface at `/swagger-ui`. There the downloads are also corrupted

You can find the project here: https://github.com/swaechter/fileserver and the test PDF for the commands bellow here: https://www.pbl-beratung.ch/app/download/10081915271/Beispiel+Sur+Dossier+Empfehlung.pdf?t=1511955424

The SHA2 hash of the PDF document is `66d78aef290e596fe83dc18b0e8b0aa5dee33aa19f35dd1e6a26f7d44ad5db67`. The wrong hash I encountered is `313ae526415387b710b360c9da8589696f0ff16ea5944822bd35eec55a460c40`

My environment:
- **Operating System**: Linux Debian Testing
- **Micronaut Version:** 1.3.1
- **JDK Version:** openjdk 11.0.6 2020-01-14

## 1.) Start the project:

```
git clone https://github.com/swaechter/fileserver
cd fileserver
./gradlew build
java -jar build/libs/fileserver-0.1-all.jar
```

## 2.) Download the test PDF from the server and upload it to the file server:

```
wget "https://www.pbl-beratung.ch/app/download/10081915271/Beispiel+Sur+Dossier+Empfehlung.pdf?t=1511955424" -O originalfile.pdf
sha256sum originalfile.pdf
curl -F "file=@originalfile.pdf;filename=originalfile.pdf" http://localhost:8080/uploadFile
```

You should receive the proper SHA2 hash as response.

## 3.) Download the file via `/downloadFileBySystemFile`:

Use the working download:

```
wget http://localhost:8080/downloadFileBySystemFile -O downloadFileBySystemFile.pdf
sha256sum downloadFileBySystemFile.pdf
```

Works as expected.

## 4.) Download the file via `/downloadFileByHttpClient`:

```
wget http://localhost:8080/downloadFileByHttpClient -O downloadFileByHttpClient.pdf
sha256sum downloadFileByHttpClient.pdf
```

Now we get a corrupted PDF (=wrong values in the byte buffer) and thus the wrong hash. Attached is a `wxHexEditor --compare downloadFileBySystemFile.pdf downloadFileByHttpClient.pdf` diff of both files (Left correct, right corrupted):

![Screenshot_20200220_104358](https://user-images.githubusercontent.com/5626755/74921755-80f30500-53ce-11ea-9f12-e69f7dec6207.png)

## 5.) Download them via Swagger

The same hebaviour can be seen in Swagger (Should be obvious, but just for reference).

## 6.) Conclusion

For simple files (simple like ASCII/ANSI I guess?) with an input like `I'm a teapot` both downloads work fine. There ist just a problem with some more advanced binary files. My assumption: The HTTP client interface handles some binary values differently/corrupting them (Or I am just doing a silly mistake..)

**Comment by swaechter** [comment]
Interesting observation: Using `HttpClient` directly (Not declarativly) does not result in any corruption

**Comment by jameskleeh** [comment]
So basically this is happening because the `downloadFileBySystemFile` method is returning a content type of `text/plain`. That is causing the client to attempt to decode the bytes using the  `TextPlainCodec` which converts the data to a string, thus corrupted. 

The method is returning a content type of `text/plain` because you're not explicitly setting the content type in the returned file and it is inferring `text/plain` from `temporary_file.tmp`. To resolve the issue, supply a content type to the file that matches its content through the two argument constructor of `SystemFile`.

**Comment by jameskleeh** [comment]
One improvement we can make here is that if the return type is a `byte[]`, to ignore any decoding. I'm going to consider ignoring any decoding if the return type is a `byte[]`

**Comment by swaechter** [comment]
Thank you very much for the digging into the code (I completely forgot to reply). I think that changing the behaviour of `byte[]` would be a good idea - or just mention it that `SystemFile` has another constructor in the documentation.

For people encountering the same problem, I solved the issue with the overloaded constructor:

```java
public SystemFile downloadFile() throws IOException {
    File aFile = ... // Local file
    return new SystemFile(aFile, MediaType.APPLICATION_OCTET_STREAM_TYPE).attach(aFile.getName());
}
```
