### ISSUE TITLE
Stop! micronaut is not a valid candidate

### ISSUE THREAD

**Issue by mikepc** [micronaut-projects/micronaut-core#285]
### Task List

- [X ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X ] Full description of the issue provided (see below)

### Steps to Reproduce
0. Uninstall sdkman
1. Navigate to http://micronaut.io/download.html
2. Follow the installation steps as outlined on the page

```
sdk version

SDKMAN 5.6.4+305
```

3. 
```
sdk install micronaut

**Stop! micronaut is not a valid candidate.**
```

### Expected Behaviour

Micronaut should be installed

### Actual Behaviour

Micronaut is not installed and sdkman responds with an error: micronaut is not a valid candidate

### Environment Information

- **Operating System**: MacOS 10.13.4
- **Micronaut Version:** Latest
- **JDK Version:** Java(TM) SE Runtime Environment (build 1.8.0_92-b14)

**Comment by graemerocher** [comment]
Please report the issue to https://github.com/sdkman/sdkman-cli/issues
