### ISSUE TITLE
Race condition when using HttpClient from BeanCreatedEventListener

### ISSUE THREAD

**Issue by lightoze** [micronaut-projects/micronaut-core#2860]
Http client is obtained via ```event.getSource().createBean(RxHttpClient.class, loadBalancer).toBlocking()```, and then a request is being made.

Because of changes in https://github.com/micronaut-projects/micronaut-core/commit/b8d24019030efa4e7f578d2fdf77d96a0f839345, this triggers ObjectMapper bean initialization from another thread which becomes locked at `synchronized (singletonObjects)` line in `DefaultBeanContext.getBeanInternal` method. At the end only a non-descriptive `ReadTimeoutException` is printed in console and application main method exits but the process keeps running.

As a workaround I can inject ObjectMapper into my BeanCreatedEventListener, but it would be useful to at least have some kind of output from Micronaut to help with detecting such cases. Also application should be able to exit promptly after failing to start.

Side question - what I'm doing is creating `BeanCreatedEventListener<OauthClientConfigurationProperties>` to handle internal OAuth client auto-registration and populating some of client properties from authentication server response. Do you think BeanCreatedEventListener is the right approach or would you suggest something else?

### Environment Information

- **Micronaut Version:** 1.3.2

**Comment by graemerocher** [comment]
I don't think this will impact master as this has been rewritten to not use `createBean`

**Comment by lightoze** [comment]
@graemerocher very interesting! Is current snapshot stable/compatible enough to work with current micronaut-security?

**Comment by graemerocher** [comment]
I don't think there will be any problems with master and micronaut security specifically. There are other breaking changes you may want to be aware of though https://github.com/micronaut-projects/micronaut-core/blob/master/src/main/docs/guide/appendix/breaks.adoc

**Comment by lightoze** [comment]
@graemerocher Yeah indeed the only immediate breakage I got was caused by ExecutorServiceMetricsBinder from micronaut-micrometer (replacing Netty EventLoopGroup bean).

I was able to reproduce the problem on master - perhaps I was not clear enough about `createBean(RxHttpClient.class, loadBalancer)` being a part of my own code inside BeanCreatedEventListener.

**Comment by graemerocher** [comment]
Can you provide an example that reproduces the issue?

**Comment by lightoze** [comment]
Here: https://gist.github.com/lightoze/db160266ec4faeaa0688b474ff8d8df4
As is the example will fail to start, uncommenting one line works as a workaround.

**Comment by lightoze** [comment]
This seems to be solved in 2.0.2.
