### ISSUE TITLE
the docs for Configuration Reference latest not showing.

### ISSUE THREAD

**Issue by soufianenassih** [micronaut-projects/micronaut-core#2862]
I can not access the latest configuration reference page: https://docs.micronaut.io/latest/guide/configurationreference.html
<img width="1440" alt="Capture d’écran 2020-02-27 à 12 29 09 p m" src="https://user-images.githubusercontent.com/59503506/75441149-6cc67f00-595d-11ea-9aaa-742226d9a7e7.png">

**Comment by graemerocher** [comment]
Please use https://docs.micronaut.io/1.3.1/guide/configurationreference.html until we get it fixed. @sdelamo is looking into it. Thanks

**Comment by sdelamo** [comment]
I fixed the cause in the docs module and I have updated Github pages. Configuration reference for `1.3.2` and `latest` will be live as soon as the Github pages cache refreshes.

**Comment by graemerocher** [comment]
@sdelamo Thanks!
