### ISSUE TITLE
hateoas.AbstractResource: embedded is not deserialized

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-core#2863]
Using `JsonError jsonError = e.getResponse().getBody(JsonError.class).get();` in unit test does not return `embedded` in `JsonError`. 

The server is returning this json : 
```json
{
  "message": "Invalid entity: id: must match \"[a-zA-Z0-9_-]+\"",
  "_links": {
    "self": {
      "href": "/api/v1/flows/org.kestra.tests/each-sequential-nested",
      "templated": false
    }
  },
  "_embedded": {
    "errors": {
      "message": "must match \"[a-zA-Z0-9_-]+\"",
      "path": "id"
    }
  }
}
```

If I used the links attributes, I've the link provide by server.
If I try with embedded, nothing is return and size 0.

Maybe need the same Jackson setter for links ? : 
 
https://github.com/micronaut-projects/micronaut-core/blob/d1c6e7c5d7b94798049fd0f420ed03c7abbc1d6d/http/src/main/java/io/micronaut/http/hateoas/AbstractResource.java#L134-L150

**Comment by alphawolf1988** [comment]
I've the same problem! Any progress on this?

**Comment by yawkat** [comment]
The problem with deserializing `_embedded` is that we have no way of knowing which type of resource is actually embedded in the JSON.

**Comment by graemerocher** [comment]
Perhaps it needs to be documented that the embedded types need to use `@JsonTypeName` or something?

**Comment by yawkat** [comment]
HATEOAS doesnt have type tags, so this wouldn't be compatible with other servers

**Comment by graemerocher** [comment]
true
