### ISSUE TITLE
Compilation of derived HTTP client interface in dependend project fails

### ISSUE THREAD

**Issue by esocode** [micronaut-projects/micronaut-core#2879]
### Task List

- [x] Steps to reproduce provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

I have a library project that defines a service API interface with POST methods and a GET method with a path variable as the argument. A server project that implements the service API in a controller class and a client project derives a sub-interface and adds the `@Client` annotation. The signature of the GET method is
```java
public interface IdService {
    ...
    @Get(uri = "/get-id/{forName}")
    Maybe<Integer> getId(@PathVariable String forName);
    ...
}
```
And the client is derived like this:
```java
@Client("idservice")
public interface IdServiceClient extends IdService {}
```
If I compile the client project I get a compilation error:
```
The route declares a uri variable named [forName], but no corresponding method argument is present
```
If I place the derived client interface in the library project (containing the base interface) it will be compiled without error. POST methods as well as the controller class in the server project also compile without problems. As a workaround I currently re-declare/override the GET method in the derived interface (without the `@Get`annotation).

### Expected Behaviour

Compile without error

### Actual Behaviour

Compilation error

### Environment Information

- **Micronaut Version:** 1.3.2
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
Please provide a link to a repository that reproduces the problem

**Comment by esocode** [comment]
I will try to provide one as soon as I can, being on a tight schedule at the moment. But I thought that at least mentioning the workaround here may help others that encounter the same problem.

**Comment by jameskleeh** [comment]
@esocode Ensure you are compiling with parameters. For example in Gradle:

```
    compileJava.options.compilerArgs.add '-parameters'
```

**Comment by esocode** [comment]
Parameters are enabled in all projects.

**Comment by esocode** [comment]
In conjunction with #2905 I found the time to create a test project. To reproduce, checkout these projects side-by-side:

https://github.com/esocode/micronaut-http-test-lib
https://github.com/esocode/micronaut-http-client-test 

and switch the latter to the branch `lib-dependency`. In that case it will use the library project for the service interface. If you build the project you will see the error message mentioned above. If you activate the commented lines in the interface `ServiceClient` which will duplicate the method from the inherited `Service` interface the project will compile. The problem also only occurs if the code is in different projects.

**Comment by jameskleeh** [comment]
@esocode The only thing I can discern here is that this is a bug in JDK 8. It works as expected with JDK 11.
