### ISSUE TITLE
Question: is `/books?{max}` a valid uri template?

### ISSUE THREAD

**Issue by croudet** [micronaut-projects/micronaut-core#2892]
I need to define a required query value, I tried:
- `/books?{max}` 
- `/books?max={max}` 
But neither match `/books?max=10`.
I wonder if these are valid uri templates?

Thanks

**Comment by Uniqen** [comment]
You will find lots of examples of uri templates in https://github.com/micronaut-projects/micronaut-core/blob/1.3.x/http/src/test/groovy/io/micronaut/http/uri/UriTemplateSpec.groovy
I'd use `/books{?max}` but that doesn't say anything about the parameter being required or not. That is up to the method declaration. If the query parameter is not annotated with `@Nullable` then it is required. For more examples see https://github.com/micronaut-projects/micronaut-core/blob/1.3.x/http-client/src/test/groovy/io/micronaut/http/client/HttpGetSpec.groovy

**Comment by renannprado** [comment]
@Uniqen I believe you can find your answer here: https://docs.micronaut.io/latest/guide/#_uri_path_variables

If you scroll down a little you'll see some examples, and `/books{?max,offset}` is where you say that `max` and `offset` are optional (opposite of what you're looking for).

**Comment by graemerocher** [comment]
Seems your question was answered by the last 2 comments

**Comment by croudet** [comment]
Well not really. When doing a grep on micronaut-core, you can find:
```
./http/src/test/groovy/io/micronaut/http/uri/UriTemplateSpec.groovy:        'http://example.com/map?{x,y}'           | [x: 1024, y: 768]
./discovery-client/src/main/java/io/micronaut/discovery/eureka/client/v2/EurekaOperations.java:    @Put(uri = "/apps/{appId}/{instanceId}/metadata?{key}={value}", single = true)
```

But none of these works with `UriMatchTemplate`:
```java
public static void main(String... args) {
        UriMatchTemplate t = new UriMatchTemplate("http://example.com:8080/map?{x,y}");
        System.out.println(t.match("http://example.com:8080/map?x=100,y=200"));
        System.out.println(t.match("http://example.com:8080/map?1024,768"));
        t = new UriMatchTemplate("/apps/{appId}/{instanceId}/metadata?{key}={value}");
        System.out.println(t.match("/apps/hhhhh/aaaaaa/metadata?ccc=dddd"));
}
```
All returns empty.

As well when using:
```
@Get("/repos/{repository}/device/{deviceid}/resources{?syncpoint}")
    public Flux<AssetLocation> assetLocations(
            @PathVariable @NotNull @Pattern(regexp = "[A-Za-z0-9_]+") String repository,
            @PathVariable @NotNull long deviceid,
            @QueryValue @NotNull String syncpoint)
```
The compile time validation complains:
`The uri variable [syncpoint] is
optional, but the corresponding method argument [java.lang.String syncpoint] is not defined as an Optional or annotated with the javax.annotat
ion.Nullable annotation.`

So I must set it as `@Nullable` and do the validation programatically.

**Comment by renannprado** [comment]
@croudet you could argue it's a bit confusing, however I believe in your case you want to just have the `@QueryValue` parameter without `@NotNull` and without mentioning in your URL, i.e. no `{?syncpoint}`. At least this worksforme:

```kotlin
@Get(value = "/auth", produces = [MediaType.TEXT_HTML])
    fun authenticateChallenge(@QueryValue("test1") test1: String, @QueryValue("test2") test2: String): ModelAndView<Map<String, Any>>
```

**Comment by croudet** [comment]
I think there is a bug:
```
./discovery-client/src/main/java/io/micronaut/discovery/eureka/client/v2/EurekaOperations.java:    @Put(uri = "/apps/{appId}/{instanceId}/metadata?{key}={value}", single = true)
```
As far as I can tell (after looking at the code) will never be matched by `UriMatchTemplate`.

As well the spec and some examples shows:
```
./http/src/test/groovy/io/micronaut/http/uri/UriTemplateSpec.groovy:        'http://example.com/map?{x,y}'           | [x: 1024, y: 768]
```
as valid template.
But at this point `UriMatchTemplate` will never match this kind ot template.

**Comment by renannprado** [comment]
@croudet can you create a repository that can reproduce the issue?

**Comment by croudet** [comment]
Just look at the `main` method in https://github.com/micronaut-projects/micronaut-core/issues/2892#issuecomment-596594072
