### ISSUE TITLE
Can't Introspect sources generated though an AnnotationProcessor

### ISSUE THREAD

**Issue by bidorffOL** [micronaut-projects/micronaut-core#2901]
**EDIT**: Added example application

I have been trying to use an `AnnotationMapper` to add the `@Introspected` annotation to Immutables `@Generated` classes. However, it seems that `TypeElementVisitorProcessor` ignore those classes.

I believe that this is because `TypeElementVisitorProcessor` [only run on the first pass](https://github.com/micronaut-projects/micronaut-core/blob/479570f7a5af3e183bf46b04ef056957dbb1031b/inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java#L62). However, classes generated through an AnnotationProcessor are not available until the second pass and therefore are ignored and can't be `@Introspected`.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Create a simple `@Value.Immutable` class:

```
@Value.Immutable
abstract class MyClass {
    // No-op
}
```

And a `NamedAnnotationMapper`:
```
public class GeneratedAnnotationMapper implements NamedAnnotationMapper {

  @Nonnull
  @Override
  public String getName() {
    return "org.immutables.value.Generated";
  }

  @Override
  public List<AnnotationValue<?>> map(AnnotationValue<Annotation> annotation, VisitorContext visitorContext) {
    return Arrays.asList(AnnotationValue.builder("io.micronaut.core.annotation.Introspected").build(),
  }
}
```

### Expected Behaviour

A `BeanIntrospection` should be available for `ImmutableMyClass`.

### Actual Behaviour

No introspection is generated for this class.

### Environment Information

- **Operating System**: N/A
- **Micronaut Version:** 1.3.2
- **JDK Version:** 11.0.6

### Example Application

[https://github.com/bidorffOL/micronaut-issue-2901](https://github.com/bidorffOL/micronaut-issue-2901)

**Comment by bidorffOL** [comment]
Any hope to see this issue resolved "soon" ? I'm having trouble finding a way to bypass that. I'm trying to use validation with Immutables, and the lack of support for @Introspected makes it difficult.

**Comment by graemerocher** [comment]
Haven't had time to look into it yet, but PRs welcome!

**Comment by bidorffOL** [comment]
I was looking for a way to replace the [`private boolean executed = false`](https://github.com/micronaut-projects/micronaut-core/blob/479570f7a5af3e183bf46b04ef056957dbb1031b/inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java#L57) with a Collection of processed `TypeElementVisitor` (that way, we can ignore those a a second pass). However, I saw that [`findTypeElementVisitors()`](https://github.com/micronaut-projects/micronaut-core/blob/479570f7a5af3e183bf46b04ef056957dbb1031b/inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java#L123) was storing the `TypeElement`s in a Map (using `definition.getName()` as key) and I was wondering if it was expected that they may be overridden and how the processor should behave.

**Comment by graemerocher** [comment]
its storing them in a map of type element visitors by name to avoid duplications

**Comment by bidorffOL** [comment]
Looking further a the code, I finally understood that the `executed` field had nothing to do with the call to `findTypeElementVisitors()` but is actually linked to the call to [`javaVisitorContext.finish()`](https://github.com/micronaut-projects/micronaut-core/blob/479570f7a5af3e183bf46b04ef056957dbb1031b/inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java#L113) and the way META-INF files are generated.

So I'll try to see if the work that has been done for [MapStruct](https://github.com/micronaut-projects/micronaut-core/pull/1339) can be adapted here without any regression.
