### ISSUE TITLE
Chunked response detection / switching

### ISSUE THREAD

**Issue by sgammon** [micronaut-projects/micronaut-core#2902]
### Steps to Reproduce

1. Prepare a `@Controller` that returns a reactive type
2. Try to publish only one chunk as an HTTP response
3. It is still a chunked response, when it could be a regular response (or vice versa)

### Expected Behaviour

It would be awesome if Micronaut could "detect" a single-step emission, and turn that into a regular HTTP response, versus a multi-step emission, which it should turn into a chunked response.

### Actual Behaviour

Instead of the expected/desired behavior, Micronaut currently will only do one or the other per endpoint, based on the return type.

### Environment Information

- **Operating System**: N/A
- **Micronaut Version:** `1.3.2`
- **JDK Version:** N/A

### Example Application

This issue surfaced during work on `micronaut-views` (specifically, the Soy rendering layer), in micronaut-projects/micronaut-views#34. @graemerocher suggested filing this issue to track progress.

**Comment by jameskleeh** [comment]
As far as I understand, the headers get written first. The body is then subscribed to and written. I don't think we can know only a single item will be emitted unless it's noted either through the `@Single` annotation or `@Get(single=true)`, or returning `Single` that the response will not be chunked.

**Comment by graemerocher** [comment]
I think it may be possible, we would need to alter the logic to evaluate whether the emitted object is single or not. I did this for Micronaut Servlet so it may be possible with the Netty implementation too.

**Comment by graemerocher** [comment]
This PR includes a potential implementation of this https://github.com/micronaut-projects/micronaut-core/pull/2976

Don't know if you want to try build that branch of Micronaut and let me know if it works for you.

**Comment by sgammon** [comment]
@graemerocher i'll give it a shot, it may be next week though (we're pushing to get this little app into prod and for now it's patched to emit a single chunk)
