### ISSUE TITLE
Empty body exception on HTTP Status 204

### ISSUE THREAD

**Issue by ratcashdev** [micronaut-projects/micronaut-core#2908]
### Steps to reproduce:
1. have a service that may return HTTP 200 (with body) or HTTP 204 (without body).
2. have a declarative client defined as `Maybe<?> getAccounts(@PathVariable("userId") String userId);`
3. In a situation, when the remote service returns HTTP 204, the following exception happens:
```
io.micronaut.http.client.exceptions.HttpClientResponseException: Empty body
        at io.micronaut.http.client.HttpClient.lambda$null$0(HttpClient.java:160)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at io.micronaut.http.client.HttpClient.lambda$retrieve$1(HttpClient.java:160)
        at io.micronaut.core.async.publisher.Publishers$1.doOnNext(Publishers.java:143)
        at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onNext(CompletionAwareSubscriber.java:52)
```

### Expected Behaviour

the Maybe will return "EMPTY".
The situation is the same when using the Low-level client.

### Actual Behaviour

`io.micronaut.http.client.exceptions.HttpClientResponseException: Empty body`

### Environment Information

- **Operating System**: LINUX
- **Micronaut Version:** 1.3.2
- **JDK Version:** 11

**Comment by ratcashdev** [comment]
@graemerocher any workarounds until 1.3.4?

**Comment by ratcashdev** [comment]
for the record, my workaround was to wrap the declarative client like this:
```
client.getAccounts(clientId)
   .onErrorComplete(t -> t.getMessage().contentEquals("Empty body"))
...
```
This will properly yield an empty `Maybe` when the exception's message matches

**Comment by jameskleeh** [comment]
`Completable` is the more appropriate type for this use case. `Maybe<?>` is the same as `Maybe<Object>` at runtime so it's expecting there to be a body.

**Comment by ratcashdev** [comment]
@jameskleeh which `Completable` (what package)?

**Comment by jameskleeh** [comment]
@ratcashdev Right I missed that point. Thanks for the report

**Comment by jameskleeh** [comment]
I'm not sure what the best way to support this use case is. `Maybe<Object>` says to me that a body is expected so I think the current behavior is correct. You can use `Maybe<Optional<?>> ` and it will work as you expect.

**Comment by ratcashdev** [comment]
I am not really experienced with reactive streams. 
My understanding was that a `Maybe` is already an `Optional`, just in the world of streams. Can emit 0 or 1 value. What would be an equivalent in the REST client for a `Maybe.empty()`? Because based on your definition it would be the exact same as a `Single<Optional<?>>`

**Comment by ratcashdev** [comment]
The Optional works though.

**Comment by jameskleeh** [comment]
The difference is if the endpoint returned a 404, the maybe would just
complete without issue and the single would emit an error.
