### ISSUE TITLE
CompletedFileUpload with big files 

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-core#2909]
For now, the CompletedFileUpload only exposed `getInputStream` or `getBytes` that is not suitable with big files and will failed at 
```java
        if (srcsize > Integer.MAX_VALUE) {
            throw new IllegalArgumentException(
                    "File too big to be loaded in memory");
        }
```
We can't access to the underlying `FileUpload fileUpload` and in case of a big files, this will be a `DiskFileUpload` and the `fileUpload.getFile()` will solved my issue.

For now, I do this ugly things : 

```java
                Field f = file.getClass().getDeclaredField("fileUpload");
                f.setAccessible(true);
                FileUpload fileUpload = (FileUpload) f.get(file);

                if (fileUpload instanceof DiskFileUpload) {
                    URI put = this.put(
                        uri,
                        new BufferedInputStream(new FileInputStream(fileUpload.getFile()))
                    );

                    fileUpload.delete();

                    return put;
                } else {
                    return this.put(
                        uri,
                        file.getInputStream()
                    );
                }
```

It will be fine to have : 
* a method that allow to copy to another path 
* to have a `InputStream` that will use the underlyning `DiskFileUpload` and will not try to load the file in memory in this case.

For my use case, an `InputStream` will be fine, but the copy can help other people.

**Comment by graemerocher** [comment]
Seems that this could be solved by modifying `CompletedFileUpload` as follows:

```java
    @Override
    public InputStream getInputStream() throws IOException {
        if (!fileUpload.isInMemory()) {
            final File file = fileUpload.getFile();
            return new FileInputStream(file);
        } else {
            return new ByteBufInputStream(fileUpload.getByteBuf(), controlRelease);
        }
    }
```

PRs welcome :)

**Comment by tchiotludo** [comment]
I started working on that based (less smarter than your :grin:) but I've an issue about the deletion on the temporary files.
The `controlRelease` is not used, If you do like that, the temporary files will not be deleted and I don't have a clue how to handle that.

**Comment by graemerocher** [comment]
@jameskleeh any suggestions?

**Comment by jameskleeh** [comment]
My suggestion would be to stream the file instead of using `CompletedFIleUpload`.  I agree the `getInputStream` should be improved, however we would likely have to subclass `FileInputStream` in order to release the file on close.

**Comment by tchiotludo** [comment]
I'll go with `StreamingFileUpload` now to avoid ugly workaround for now. 
but IMO, the `CompletedFileUpload` is easier to use for most of people and they need a standard way to deal with bigfiles. 

The Wrapper around `FileInputStream` may be the right solution to avoid complexity for users.
Just read the InputStream and don't care about the `DiskFileUpload` or in memory will be the perfect api for most users

**Comment by jameskleeh** [comment]
Thanks for the report @tchiotludo
