### ISSUE TITLE
AmazonComputeInstanceMetadataResolver has an invalid path

### ISSUE THREAD

**Issue by jensW89** [micronaut-projects/micronaut-core#2934]
While connecting the application to a consul running in a different ec2 instance (same VPC) the following error occurs in the logs

`[35mi.m.d.c.a.AmazonComputeInstanceMetadataResolver[0;39m - error getting public host name from:http://169.254.169.254//latest/meta-data/publicHostname
java.io.FileNotFoundException: http://169.254.169.254//latest/meta-data/public-hostname`

double // is included in path.

**Comment by graemerocher** [comment]
Go for it!
