### ISSUE TITLE
Maven repo not in user.home

### ISSUE THREAD

**Issue by thomasmey** [micronaut-projects/micronaut-core#295]
Hi,

I have this configuration on my computer in .m2/settings.xml:
 <localRepository>C:\Users\Public\Documents\maven\repository\</localRepository>

So the local maven repo is shared for all users on this computer.

Looking at https://github.com/micronaut-projects/micronaut-core/blob/7ecbae2bfd8fe53daf7b1d7e108e850eafa7b7b5/cli/src/main/groovy/io/micronaut/cli/profile/repository/MavenProfileRepository.groovy it seems that it's assumed that the local maven repo is always under new File(System.getProperty("user.home"), "/.m2/repository/...")

a solution would be to add an CliSettings to configure the location of the local maven repo.

what do you think about this?

**Comment by graemerocher** [comment]
Seems reasonable

**Comment by thomasmey** [comment]
As a fun fact the AetherGrapeEngine calls deeply into "maven" classes, which seems to look at the .m2/settings.xml so -> the dependencies get downloaded and resolved but mn list-profiles doesn't find any profiles because it looks in the wrong place...

For future reference relevant stacktrace for download the artifacts is:

Thread [main] (Suspended)	
	owns: DualStackPlainSocketImpl  (id=978)	
	DualStackPlainSocketImpl.waitForConnect(int, int) line: not available [native method]	
	DualStackPlainSocketImpl.socketConnect(InetAddress, int, int) line: 85	
	DualStackPlainSocketImpl(AbstractPlainSocketImpl).doConnect(InetAddress, int, int) line: 400	
	DualStackPlainSocketImpl(AbstractPlainSocketImpl).connectToAddress(InetAddress, int, int) line: 243	
	DualStackPlainSocketImpl(AbstractPlainSocketImpl).connect(SocketAddress, int) line: 225	
	SocksSocketImpl(PlainSocketImpl).connect(SocketAddress, int) line: 148	
	SocksSocketImpl.connect(SocketAddress, int) line: 402	
	SSLSocketImpl(Socket).connect(SocketAddress, int) line: 591	
	SSLSocketImpl.connect(SocketAddress, int) line: 657	
	SslSocketFactory(SSLSocketFactory).connectSocket(Socket, InetSocketAddress, InetSocketAddress, HttpParams) line: 414	
	DefaultClientConnectionOperator.openConnection(OperatedClientConnection, HttpHost, InetAddress, HttpContext, HttpParams) line: 180	
	ManagedClientConnectionImpl.open(HttpRoute, HttpContext, HttpParams) line: 294	
	DefaultRequestDirector.tryConnect(RoutedRequest, HttpContext) line: 643	
	DefaultRequestDirector.execute(HttpHost, HttpRequest, HttpContext) line: 479	
	DefaultHttpClient(AbstractHttpClient).execute(HttpHost, HttpRequest, HttpContext) line: 906	
	DecompressingHttpClient.execute(HttpHost, HttpRequest, HttpContext) line: 137	
	HttpTransporter.execute(HttpUriRequest, HttpTransporter$EntityGetter) line: 287	
	HttpTransporter.implGet(GetTask) line: 243	
	HttpTransporter(AbstractTransporter).get(GetTask) line: 59	
	BasicRepositoryConnector$GetTaskRunner.runTask() line: 447	
	BasicRepositoryConnector$GetTaskRunner(BasicRepositoryConnector$TaskRunner).run() line: 350	
	RunnableErrorForwarder$1.run() line: 67	
	BasicRepositoryConnector$DirectExecutor.execute(Runnable) line: 581	
	BasicRepositoryConnector.get(Collection<ArtifactDownload>, Collection<MetadataDownload>) line: 249	
	DefaultArtifactResolver.performDownloads(RepositorySystemSession, DefaultArtifactResolver$ResolutionGroup) line: 520	
	DefaultArtifactResolver.resolve(RepositorySystemSession, Collection<ArtifactRequest>) line: 421	
	DefaultArtifactResolver.resolveArtifacts(RepositorySystemSession, Collection<ArtifactRequest>) line: 246	
	DefaultArtifactResolver.resolveArtifact(RepositorySystemSession, ArtifactRequest) line: 223	
	DefaultArtifactDescriptorReader.loadPom(RepositorySystemSession, ArtifactDescriptorRequest, ArtifactDescriptorResult) line: 320	
	DefaultArtifactDescriptorReader.readArtifactDescriptor(RepositorySystemSession, ArtifactDescriptorRequest) line: 217	
	DefaultDependencyCollector.resolveCachedArtifactDescriptor(DataPool, ArtifactDescriptorRequest, RepositorySystemSession, Dependency, DefaultDependencyCollector$Results, DefaultDependencyCollector$Args) line: 535	
	DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector$Args, DefaultDependencyCollector$Results, boolean, Dependency, ArtifactDescriptorRequest) line: 519	
	DefaultDependencyCollector.processDependency(Args, Results, List<RemoteRepository>, DependencySelector, DependencyManager, DependencyTraverser, VersionFilter, Dependency, List<Artifact>, boolean) line: 409	
	DefaultDependencyCollector.processDependency(Args, Results, List<RemoteRepository>, DependencySelector, DependencyManager, DependencyTraverser, VersionFilter, Dependency) line: 363	
	DefaultDependencyCollector.process(Args, Results, List<Dependency>, List<RemoteRepository>, DependencySelector, DependencyManager, DependencyTraverser, VersionFilter) line: 351	
	DefaultDependencyCollector.collectDependencies(RepositorySystemSession, CollectRequest) line: 254	
	DefaultRepositorySystem.resolveDependencies(RepositorySystemSession, DependencyRequest) line: 341	
	AetherGrapeEngine.resolve(List<Dependency>) line: 319	
	AetherGrapeEngine.resolve(Map, List, Map...) line: 301	
	AetherGrapeEngine.resolve(Map, Map...) line: 293	
	DependencyVersions.<init>(GrapeEngine, Map<String,String>) line: 53	
	DependencyVersions.<init>(GrapeEngine) line: 49	
	MavenProfileRepository.<init>(List<RepositoryConfiguration>) line: 71	
	MicronautCli.createMavenProfileRepository() line: 322	
	MicronautCli.execute(String...) line: 224	
	MicronautCli.main(String...) line: 158

**Comment by jameskleeh** [comment]
@ZacharyKlein we should probably just look for and parse the `settings.xml`

**Comment by thomasmey** [comment]
mhh, okay, as I'm very new to this project, I maybe have a mis-conception about the list-profiles command. even with maven local directory set to ${user.home} I still get an empty list, is that intended? I had maybe the wrong assumption that it should list all available profiles? But app-creation works correctly, so...

**Comment by jameskleeh** [comment]
@thomasmey You shouldn't need to have anything in your local maven for it to list the profiles

**Comment by thomasmey** [comment]
mhh. this is what I get:

| Starting interactive mode...
| Enter a command name to run. Use TAB for completion:
mn> list-profiles
| Available Profiles
--------------------

I do use this settings file because I'm in a corporate network:

def artifactoryUser = 'email';
def artifactoryPassword = 'pwd';

micronaut.profiles.repositories = [
    jcenter: [url: 'https://artifactory.example.com/artifactory/mvn-jcenter/',
    	      snapshotsEnabled: false,
	      username: artifactoryUser,
	      password: artifactoryPassword
	     ]
  ];

so I wonder why the list is empty?

**Comment by jameskleeh** [comment]
@thomasmey If you have specified profile repositories the profiles will not be pulled from the default repository. You can include the default repository in your configuration and then it will list the profiles found there as well (https://jcenter.bintray.com).
