### ISSUE TITLE
Transaction management with checked exception thrown not compliant with Spring

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#2960]
I don't know it's a bug or by-design, but new pure Micronaut-based transaction management in `2.0.0.M1` is not compliant with Spring one. And I believe it should be compliant because 1) it mimics their `TransactionManager` 2) in previous Micronaut version Spring-based transaction management was the only options and to enable migration to 2.0 Micronaut should provide compliant behavior.

It's about how checked exception is treated by transactional AOP, for this example:

```java
@TransactionalAdvice @Singleton
class MyBean {
  void myMethod() throws MyCheckedException {
    throw new MyCheckedException();
  }
}
```
When `myBean.myMethod()` is called with Spring `TransactionManager` the transaction would commit. With Micronaut it sets rollback only flag and the transaction will finally be rolled back.

**Comment by graemerocher** [comment]
This is behavior that I never agreed with in Spring and I am glad we get to fix this in Micronaut TX

It is based on some old EJB behavior and IMO makes no sense as a default. You can use noRollbackOn in the annotation to customize the behavior
