### ISSUE TITLE
Improve HTTP client/server filters

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#2965]
I'm trying to write my own logger for logging request/response for HTTP clients and HTTP server.
There are a few problems:

- Unfortunately, there is no way to get a raw request (clients) or a raw response (server) that is going to be sent in a custom filter. 
- Calling `getBody` will only return an object set by the controller
- The content-type header is not set
- The design of HttpFilter is not the best, to write logging you would like to log the request at the end of the chain and the response at the beginning. The only way at this moment is to write two filters. Personally, I find using `Publisher` very confusing in this scenario.

The logging can be improved by extracting the logging in some interface or provide a way to write a logger on the netty level, but I think those problems are still there.

**Comment by graemerocher** [comment]
I don't believe that filters are best suited for this use case. It would be best to expose a way to customize Netty handlers for wire level interaction like this

**Comment by dstepanov** [comment]
@graemerocher What would be the best way to integrate https://github.com/zalando/logbook ?

**Comment by graemerocher** [comment]
By adding an API to integrate the Netty handlers they already provide

**Comment by graemerocher** [comment]
See https://github.com/micronaut-projects/micronaut-core/issues/2719

**Comment by graemerocher** [comment]
Duplicates  #1113
