### ISSUE TITLE
Support multiple query params with some new annotation

### ISSUE THREAD

**Issue by nirvana124** [micronaut-projects/micronaut-core#2977]
To pass multiple values of query params, I was expecting some annotation which will expect a map of all the query params.
Can we have support for this in @Client annotation ?

Something like below:
To the method we can pass Map of query params with new Annotaion like @QueryParams  
and HttpClientIntroductionAdvice add all the values from params in URL 
@Client("test")
interface TestClient {

    @Get("/test")
    fun getValue(@QueryParams params: Map<String, Any?>): Single<String>
}

else if (annotationMetadata.isAnnotationPresent(QueryParams.class)){
                    conversionService.convert(definedValue, ConversionContext.of(Map.class).with(annotationMetadata))
                            .ifPresent(queryParams::putAll);
                }

**Comment by graemerocher** [comment]
An annotation is not the right thing here. We already have an `HttpParameters` interface for this which would should probably support creating a new instance of to pass as a parameter

**Comment by nirvana124** [comment]
I do not understand how can i use HttpParameters with  interface annotated with @Client ?
For now i am able use RxHttpClient.

val queryParams: MutableMap<String, Any?>
val uri = UriBuilder.of("test").path("path").expand(queryParams)
return client.retrieve(uri.toString())

Right now in HttpClientIntroductionAdvice, All the method arguments with QueryValue annotations are inserted into a LinkedHashMap //Map<String, String> queryParams = new LinkedHashMap<>();
And later   request object is getting created by appending all query params in url.

I am suggesting Directly pass a Map<String, String> and use that map to update query params in URI or can also use it to update path parameters as well. 
Lets say i have to pass 20 query params to a request i am making, instead of passing 20 method arguments with @QueryValue annotation. We can have some mechanism to pass Map or any kind of object that have value of each param.

**Comment by kash1102** [comment]
Is this resolved?

**Comment by yawkat** [comment]
You can have map params like `{?params*}` now

**Comment by schrek1** [comment]
@yawkat is possible insert nested maps for multidimensional array query param? 

e.g.: Map<String, Map<String, String>>  =>   filter[0][field]=xyz

**Comment by yawkat** [comment]
no it is not possible atm, exploded params don't parse the bracket syntax at all, they put *all* the parameters into the map
