### ISSUE TITLE
Cacheable atomic=true doesn't seem to work

### ISSUE THREAD

**Issue by stepanv** [micronaut-projects/micronaut-core#2999]
When using `@Cacheable` on a method that returns a Reactive Object, I'd expect the given chain to be called up to once, especially if `atomic = true` is set.

I'm submitting a reproducer https://github.com/micronaut-projects/micronaut-core/pull/2998

Given following code:

```
Flowable.merge(
    // cachedHttpGetCall is an http call that is annotated with @Cacheable(atomic = true)
    myClient.cachedHttpGetCall(),
    myClient.cachedHttpGetCall()
) 
```

Then the `cachedHttpGetCall()` could be called twice.

I'd expect the method to be call up to once. Never twice or more.

I'm not sure if `atomic` is really implemented an also if this is a scenario that cannot be really cached.

**Comment by graemerocher** [comment]
Reactive caching cannot be implemented automatically since you would have to block to obtain the value from the publisher

**Comment by stepanv** [comment]
Thanks @graemerocher for the quick response, however, I disagree one needs to block to obtain the value (or the values) though. I'd say, one needs to block only to get the reactive object which should be fine as long as the construction is not blocking (see the comments in the snippet bellow please).

I think the caching for reactive types could work as follows (I hope it would be easy to read since it's extending your own tests)

Maybe this is beyond what Micronaut aims to support (especially because it relies on the reactive type caching mechanism (e.g., `Flowable.cached()`)). 
So maybe it would be a feature request.
Nevertheless, I'd say Micronaut should at least explain why its caching of reactive types is not working in the fashion I'm outlining bellow because this is imho natural to expect.

(note that if the `.cache()` is commented out, the test would fail similarly to how it fails when Micronaut `@Cacheable` is used (the PR reproducer I linked originally)).
```
package io.micronaut.cache

import io.micronaut.context.ApplicationContext
import io.reactivex.Flowable
import spock.lang.Specification

import javax.inject.Singleton
import java.time.LocalTime
import java.util.concurrent.atomic.AtomicInteger

class CachePublisherSpec extends Specification {

    def "test cache is really cached - Flowable cached() - merging"() {
        given:
        def ctx = ApplicationContext.run()
        HelloService helloService = ctx.getBean(HelloService)

        when:
        def merger = Flowable.merge(
                helloService.calculateValueMonoOwnMap(10),
                helloService.calculateValueMonoOwnMap(10)
        )

        then:
        def all = merger.blockingIterable().asList()

        all.size() == 2
        all.every {
            it == "Hello 1: 10"
        }

        helloService.calculateValueMonoOwnMap(10).blockingFirst() == "Hello 1: 10"
    }

    @Singleton
    static class HelloService {

        AtomicInteger invocations = new AtomicInteger(0)

        // if this was rather a cache, it would support expiration and other cool/necessary features
        private final map = new HashMap<Integer, Flowable<String>>()

        Flowable<String> calculateValueMonoOwnMap(Integer num) {
            // we "block" here
            // but thanks to the fact the creating of the reactive object is non-blocking
            // we should be fine and the synchronized is just for the sake of "ordering"
            // as a result any other caller will get exactly same reactive object
            // and they will subscribe to it,
            // if the underlying object supports caching, all the callers will get the same result
            // and the "loader" will be called just once

            // this should be substituted by a proper caching to avoid unnecessary memory barriers and etc
            synchronized (map) {
                return map.computeIfAbsent(num, {
                    return calculateValueMonoReactorCache(num)
                })
            }
        }

        Flowable<String> calculateValueMonoReactorCache(Integer num) {
            return Flowable.fromCallable({
                        def n = invocations.incrementAndGet()
                        println("Calculating value for $num on ${Thread.currentThread()} at ${LocalTime.now()} .. $n")
                        return "Hello $n: $num".toString()
                    })
            // this is the essential part - the reactive object re-sends the same stuff to all subscribers
            // if commented out, the test fails
                    .cache()
        }
    }
}
```

**Comment by graemerocher** [comment]
caches may be remote and they may need to serialize the value (example redis). I am not aware of caches that support `Flowable` types as values

**Comment by stepanv** [comment]
@graemerocher I was able to implement the caching of Flowable by using Caffeine's AsyncLoadingCache. 
I'm transforming between `CompletableFuture<List<String>>` and `Publisher<String>` (by a little help of Reactor as they help with the transformations as JavaRx 2 is rather Java 6 without CompletableFuture support).

I believe the "reactiveness correctness" is preserved, although I'm not that experienced to be able to verify all the corner cases.

This is what I originally thought how Micronaut's caching of reactive objects work and I now wonder why it's not implemented this way in Micronaut?

(the test I pasted above works just fine with this implementation, the value loader is called just once)

```
import com.github.benmanes.caffeine.cache.AsyncCacheLoader
import com.github.benmanes.caffeine.cache.AsyncLoadingCache
import com.github.benmanes.caffeine.cache.Caffeine
import io.reactivex.Flowable
import org.reactivestreams.Publisher
import reactor.core.publisher.Flux
import reactor.core.publisher.Mono

import javax.inject.Singleton
import java.time.LocalTime
import java.util.concurrent.CompletableFuture
import java.util.concurrent.Executor
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicInteger

@Singleton
class HelloService {

    AtomicInteger invocations = new AtomicInteger(0)

    AsyncLoadingCache<Integer, List<String>> cache = Caffeine.newBuilder()
            .buildAsync(new AsyncCacheLoader<Integer, List<String>>() {
                @Override
                CompletableFuture<List<String>> asyncLoad(Integer num, Executor executor) {
                    // not using the executor as we want to stick to the current thread the stream is flowing on
                    Flux
                            .from(
                                    Flowable
                                            .fromCallable({
                                                def n = invocations.incrementAndGet()
                                                println("Calculating value for $num on ${Thread.currentThread()} at ${LocalTime.now()} .. $n")
                                                return "Hello $n: $num".toString()
                                            })
                                            .delay(5, TimeUnit.SECONDS)
                            )
                            .collectList()
                            .toFuture()
                }
            })

    // This is the method one would use @Cacheable with and call the loader directly
    Publisher<String> calculate(Integer num) {
        return Mono
                .fromCompletionStage(cache.get(num))
                .flatMapMany({
                    Flux.fromIterable(it)
                })
    }
}
```

**Comment by graemerocher** [comment]
We have to provide a common API to support all cache provides not just Caffeine and I don't believe there is a universal way to achieve this. Caffeine is an in memory cache so it is different from remote caches like redis and hazelcast

**Comment by stepanv** [comment]
@graemerocher, I understand that, but using the approach I'm suggesting above with Caffeine doesn't require any change of the Microanut API. It actually fixes the Micronaut Caffeine implementation because it's implementing the `atomic = true` part. 
So while it might be impossible to implement it correctly for Redis, it's worth making it right for the in-memory Caffeine impl, or not?

**Comment by graemerocher** [comment]
PRs are of course welcome

**Comment by stepanv** [comment]
well, after few hours of getting deeper into Micronaut Caches, I give up because there's no elegant way to implement it unless 
* the Caches were redesigned so that the AsyncCache is the base and the SyncCache is just a layer on top of it (and not vice versa as it's right now)
* the AsyncCache API needs to have the value loader returning CompletableFuture (and not the value directly)
* and several more backwards compatibility breaking changes
* the CacheInterceptor itself would deserve lot of improvements
* I'm afraid even the test coverage would need to be significantly increased to be sure it's working the same way as it used to

and as a matter of fact I'm definitely not the right person to do or even propose such changes.
But anyway, thanks for your time.

**Comment by ikovalyov** [comment]
@stepanv https://github.com/micronaut-projects/micronaut-core/pull/2911 might be related
