### ISSUE TITLE
build micronaut in windows7

### ISSUE THREAD

**Issue by JJAM2014** [micronaut-projects/micronaut-core#300]
I downloaded micronaut-core from git  
git clone https://github.com/micronaut-projects/micronaut-core.git
after I ran  shell   ./gradlew publishToMavenLocal
but show this error 
D:\micronaut-core\http-client\src\main\java\io\micronaut\http\client\HttpClient.java:131: error: unreported exception X; must be caught or declared to be thrown
                    .orElseThrow(() -> new HttpClientResponseException(
                                ^
  where X,T are type-variables:
    X extends Throwable declared in method <X>orElseThrow(Supplier<? extends X>)
    T extends Object declared in class Optional
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':http-client:compileJava'.

Operating System: 
windows 7 
MINGW64
Micronaut Version:
micronaut-core
JDK Version:  
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

thanks in advance

These operations I did in a mac  and  it was well

 micronaut maybe  not run in windows?

**Comment by graemerocher** [comment]
This error normally indicates you are attempting to build with an earlier version of the JDK 8 that had some type inference bugs. Please ensure you are building with the latest
