### ISSUE TITLE
Metrics test fails intermittently

### ISSUE THREAD

**Issue by ctoestreich** [micronaut-projects/micronaut-core#302]
Just Logging this here for an item I can tag a fix for.  Trying to address why this happens from time to time.

https://travis-ci.org/micronaut-projects/micronaut-core/builds/394398006

```
> Task :configurations:micrometer-core:test
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
io.micronaut.configuration.metrics.management.endpoint.FilteredMetricsEndpointSpec > test metrics endpoint with filtered metrics FAILED
    Condition failed with Exception:
    result.names.size() == 1
    |      |     |
    [:]    null  java.lang.NullPointerException: Cannot invoke method size() on null object
        at io.micronaut.configuration.metrics.management.endpoint.FilteredMetricsEndpointSpec.test metrics endpoint with filtered metrics(FilteredMetricsEndpointSpec.groovy:75)
        Caused by:
        java.lang.NullPointerException: Cannot invoke method size() on null object
            at io.micronaut.configuration.metrics.management.endpoint.FilteredMetricsEndpointSpec.test metrics endpoint with filtered metrics(FilteredMetricsEndpointSpec.groovy:75)
..........
92 tests completed, 1 failed
```

**Comment by ctoestreich** [comment]
My theory is that the server boots too fast for any metrics to make it into the registry sometimes.  I have tested this extensively locally and it fails about 5% of the time.  When I log the output it looks correct and the order of things is happening correctly.

Beans Created -> Beans Configured via `BeanCreatedEventListener<MeterRegistry>` -> Check For Missing Registries (create default) via `ApplicationEventListener<StartupEvent>` -> Endpoint Invoked

```
15:04:19.085 [Test worker] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]
15:04:19.114 [Test worker] INFO  i.m.c.m.m.MeterRegistryCreationListener - Meter registry SimpleMeterRegistry configured
15:04:19.119 [Test worker] INFO  i.m.c.m.m.SimpleMeterRegistryEventListener - Meter startup called
15:04:19.164 [Test worker] INFO  i.m.c.m.m.e.FilteredMetricsEndpointSpec - /metrics called
```

**Comment by jameskleeh** [comment]
@ctoestreich Are you going to submit another PR for the test that was ignored on travis? If it's ignored there it might as well be deleted.

**Comment by graemerocher** [comment]
One option to resolve this is to use PollingConditions

**Comment by ctoestreich** [comment]
Unclear.  It has value. However until I can figure it out I don't want it to break master for no reason.
