### ISSUE TITLE
Verify Gradle Wrappers with GitHub Actions

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#3023]
See [Verifying Gradle Wrappers with GitHub Actions](https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action). 

This should be applied to every module: 

### Data Access

- [ ] Micronaut Data
- [ ] Micronaut MongoDB
- [ ] Neo4j Configuration
- [ ] Micronaut Redis
- [ ] Micronaut SQL / JDBC 
- [ ] Micronaut for Cassandra

### Database Migration

- [ ] Flyway database migration
- [ ] Liquibase Datatabase Migration

### Analytics

- [ ] ElasticSearch Configuration
- [ ] Micronaut JMX Configuration
- [ ] Micronaut Micrometer
- [ ] Ratelimiter

### Views

- [ ] RSS Configuration
- [ ] Views

### Languages

- [ ] Micronaut Groovy
- [ ] Micronaut Kotlin

### Misc

- [ ] Cache
- [ ] Micronaut Hibernate Validator
- [ ] Micronaut Maven Plugin
- [ ] Micronaut Picocli
- [ ] Micronaut Security
- [ ] Micronaut Test

### Messaging

- [ ] Micronaut Kafka
- [ ] RabbitMQ Configuration

### Cloud

- [ ] AWS Configuration
- [ ] Micronaut GCP
- [ ] Kubernetes
- [ ] Micronaut Netflix

### API

- [ ] Servlet
- [ ] GRPC 
- [ ] Micronaut GraphQL
- [ ] JAX-RS
- [ ] Jackson XML
- [ ] Open API 
- [ ] Micronaut for Spring

**Comment by sdelamo** [comment]
@alvarosanchez  is this done?

**Comment by alvarosanchez** [comment]
Yes, it is.
