### ISSUE TITLE
Verify every module plays well with Micronaut 2.0

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#3024]
This should be done for every module. Legend:

| Symbol | Status |
| :---: | --- |
| ✅| Works with Micronaut 2. No further action required |
| ✳️| Works with Micronaut 2. However, it requires a new release, because either it uses an old Micronaut version, or needed changes to make it work with Micronaut 2 | 
| ❌| Doesn't work with Micronaut 2 |
| ❓| Hasn't been tested with Micronaut 2 |
| ☑️ | Not Applicable |

The upgrade PRs are mostly to see the changes required for the upgrade, so that when they want to move ahead, don't need to start from scratch. PRs that are failing are marked as draft to prevent merges.

### Data Access

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Data](https://github.com/micronaut-projects/micronaut-data) | 1.3.5 |✅| [#519](https://github.com/micronaut-projects/micronaut-data/pull/519) | [#518](https://github.com/micronaut-projects/micronaut-data/issues/518) |
| [MongoDB](https://github.com/micronaut-projects/micronaut-mongodb) | 1.3.3 | ✅ | [#35](https://github.com/micronaut-projects/micronaut-mongodb/pull/35) |  |
| [Neo4j Configuration](https://github.com/micronaut-projects/micronaut-neo4j) | 1.2.8 | ✅ | [#15](https://github.com/micronaut-projects/micronaut-neo4j/pull/15) |  |
| [Redis](https://github.com/micronaut-projects/micronaut-redis) | 1.3.4 | ✅| [#35](https://github.com/micronaut-projects/micronaut-redis/pull/35) | #3125 |
| [SQL / JDBC ](https://github.com/micronaut-projects/micronaut-sql) | 1.3.4 | ✅| [#152](https://github.com/micronaut-projects/micronaut-sql/pull/152) |  |
| [Cassandra](https://github.com/micronaut-projects/micronaut-cassandra) | 1.3.5 | ✅  | [#14](https://github.com/micronaut-projects/micronaut-cassandra/pull/14) | #3162 |

### Database Migration

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Flyway](https://github.com/micronaut-projects/micronaut-flyway) | 1.3.3 | ✅ | [#31](https://github.com/micronaut-projects/micronaut-flyway/pull/31) |  |
| [Liquibase](https://github.com/micronaut-projects/micronaut-liquibase) | 1.3.3 | ✅ | [#24](https://github.com/micronaut-projects/micronaut-liquibase/pull/24) |  |

### Analytics

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [ElasticSearch](https://github.com/micronaut-projects/micronaut-elasticsearch) | 2.0.0.M3 | ✅ | [#28](https://github.com/micronaut-projects/micronaut-elasticsearch/pull/28) | #3165 |
| [JMX](https://github.com/micronaut-projects/micronaut-jmx) | 2.0.0.M1 | ✅  |  |  |
| [Micrometer](https://github.com/micronaut-projects/micronaut-micrometer) | 1.3.5 | ✅ | [#67](https://github.com/micronaut-projects/micronaut-micrometer/pull/67) | #3177 |
| [Ratelimiter](https://github.com/micronaut-projects/micronaut-ratelimiter) | 1.3.0.BUILD-SNAPSHOT | ✅ | [#2](https://github.com/micronaut-projects/micronaut-ratelimiter/pull/2) |  |

### Views

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [RSS Configuration](https://github.com/micronaut-projects/micronaut-rss) | 2.0.0|  ✅ |[#1](https://github.com/micronaut-projects/micronaut-rss/pull/1) | #3182 |
| [Views](https://github.com/micronaut-projects/micronaut-views) | 2.0.0.M3 | ✳️ |  |  #3167 |

### Languages

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Groovy](https://github.com/micronaut-projects/micronaut-groovy) | 2.0.0.M3 | ✅ | [#56](https://github.com/micronaut-projects/micronaut-groovy/pull/56) | #3169 |
| [Kotlin](https://github.com/micronaut-projects/micronaut-kotlin) | 1.3.3 | ✅ | [#75](https://github.com/micronaut-projects/micronaut-kotlin/pull/75) | #3178 |

### Reactive

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Reactor](https://github.com/micronaut-projects/micronaut-reactor) | 2.0.0.M2 | ✳️ |  | #3171 |
| [RxJava 1](https://github.com/micronaut-projects/micronaut-rxjava1) | 1.3.3 | ✳️ | [#1](https://github.com/micronaut-projects/micronaut-rxjava1/pull/1) | #3170 |
| [RxJava 3](https://github.com/micronaut-projects/micronaut-rxjava3) | 2.0.0.M2 | ✳️ |  | #3172 |

### Misc

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Cache](https://github.com/micronaut-projects/micronaut-cache) | 2.0.0.M2 | ✳️ |  | #3173 |
| [Hibernate Validator](https://github.com/micronaut-projects/micronaut-hibernate-validator) | 2.0.0 | ✅ |  |  |
| [Maven Plugin](https://github.com/micronaut-projects/micronaut-maven-plugin) | N/A | ☑️ | []() |  |
| [Picocli](https://github.com/micronaut-projects/micronaut-picocli) | 1.3.4 | ✅ | [#30](https://github.com/micronaut-projects/micronaut-picocli/pull/30) |  |
| [Security](https://github.com/micronaut-projects/micronaut-security) | 2.0.0.M3 | ✳️ |  | #3174 |
| [Test](https://github.com/micronaut-projects/micronaut-test) | 1.3.3.BUILD-SNAPSHOT | ✅ | [#162](https://github.com/micronaut-projects/micronaut-test/pull/162) |  |
| [ACME](https://github.com/micronaut-projects/micronaut-acme) | 1.3.3 | ❓   |  |  |

### Messaging

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Kafka](https://github.com/micronaut-projects/micronaut-kafka) | 1.3.4 | ✅  | [#127](https://github.com/micronaut-projects/micronaut-kafka/pull/127) | [#128](https://github.com/micronaut-projects/micronaut-kafka/issues/128) |
| [RabbitMQ](https://github.com/micronaut-projects/micronaut-rabbitmq) | 1.3.5 | ✅ | [#65](https://github.com/micronaut-projects/micronaut-rabbitmq/pull/65) | [#66](https://github.com/micronaut-projects/micronaut-rabbitmq/issues/66) |
| [NATS](https://github.com/micronaut-projects/micronaut-nats) | 1.3.5 | ✅  | [#23](https://github.com/micronaut-projects/micronaut-nats/pull/23) | |

### Cloud

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [AWS](https://github.com/micronaut-projects/micronaut-aws) | 2.0.0.M2 | ✳️ |  | #3175 |
| [GCP](https://github.com/micronaut-projects/micronaut-gcp) | 1.3.4 | ✅ | [#114](https://github.com/micronaut-projects/micronaut-gcp/pull/114) |  |
| [Kubernetes](https://github.com/micronaut-projects/micronaut-kubernetes) | 1.3.5 | ✅ | [#103](https://github.com/micronaut-projects/micronaut-kubernetes/pull/103) | #3179 |
| [Netflix](https://github.com/micronaut-projects/micronaut-netflix) | 2.0.0.RC1 |✅ | [#14](https://github.com/micronaut-projects/micronaut-netflix/pull/14) | [#15](https://github.com/micronaut-projects/micronaut-netflix/issues/15) |

### API

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Servlet](https://github.com/micronaut-projects/micronaut-servlet) | 1.3.4 | ❌ | [#4](https://github.com/micronaut-projects/micronaut-servlet/pull/4) | [#5](https://github.com/micronaut-projects/micronaut-servlet/issues/5) [#6](https://github.com/micronaut-projects/micronaut-servlet/issues/6) |
| [GRPC](https://github.com/micronaut-projects/micronaut-grpc) | 2.0.0.M2 | ✳️ |  | #3176 |
| [Micronaut GraphQL](https://github.com/micronaut-projects/micronaut-graphql) | 1.3.0 | ✅ | [#43](https://github.com/micronaut-projects/micronaut-graphql/pull/43) |  |
| [JAX-RS](https://github.com/micronaut-projects/micronaut-jaxrs) | 1.3.3 | ✅ |  |  |
| [Jackson XML](https://github.com/micronaut-projects/micronaut-jackson-xml) | 1.3.0 | ✅ |  |  |
| [Open API](https://github.com/micronaut-projects/micronaut-openapi) | 1.1.4 | ✅ |  |  |
| [Spring](https://github.com/micronaut-projects/micronaut-spring) | 1.3.3 | ❌ | [#57](https://github.com/micronaut-projects/micronaut-spring/pull/57) | [#58](https://github.com/micronaut-projects/micronaut-spring/issues/58) |

**Comment by benmccann** [comment]
I found an issue with the GraphQL module 2.x compatibility. Sharing it here. https://github.com/micronaut-projects/micronaut-graphql/issues/42

**Comment by sdelamo** [comment]
rss 2.00 has been released. i have added a green checkmark to the table

**Comment by grimmjo** [comment]
I've added a pull request for micronaut-nats

**Comment by alvarosanchez** [comment]
@grimmjo thanks, I added the project to the table
