### ISSUE TITLE
Build fails if a controller uses coroutines, uri variables and bean validation

### ISSUE THREAD

**Issue by jeroenknoef** [micronaut-projects/micronaut-core#3054]
If you combine Kotlin coroutines with uri variables and @Validated, the build fails. Leave any of them out, and the build succeeds.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Clone and build the project provided at https://github.com/jeroenknoef/micronaut-failed-build-example.

The controller in question can be viewed at https://github.com/jeroenknoef/micronaut-failed-build-example/blob/master/src/main/kotlin/hello/world/Controller.kt

This project was created using `mn create-app hello-world --lang kotlin`.

### Expected Behaviour

A successful build.

### Actual Behaviour

build/tmp/kapt3/stubs/main/hello/world/Controller.java:12: error: The route declares a uri variable named [n], but no corresponding method argument is present
    public java.lang.Object test(@javax.validation.constraints.Max(value = 10L)

### Environment Information

- **Operating System**: Mac OSX 10.15.4
- **Micronaut Version:** 1.3.4
- **JDK Version:** 11.0.2

### Example Application

https://github.com/jeroenknoef/micronaut-failed-build-example

**Comment by jameskleeh** [comment]
This seems to be a bug in kapt. As a workaround, you can use `@PathVariable("n")`

kapt generates Java stubs and that is what we use in our annotation processors. kapt is generating the following for your method:

```
    @org.jetbrains.annotations.Nullable()
    @io.micronaut.http.annotation.Get(value = "/{n}")
    public java.lang.Object test(@javax.validation.constraints.Max(value = 10L)
    int p0, @org.jetbrains.annotations.NotNull()
    kotlin.coroutines.Continuation<? super java.lang.Integer> p1) {
        return null;
    }
```

As you can see `p0` != `n`. There isn't anything we can do about this that I'm aware of

**Comment by croudet** [comment]
From my tests, it happens when you declare the class and method `open`.
