### ISSUE TITLE
Invalid exec-maven-plugin settings in generate POM and micronaut-parent

### ISSUE THREAD

**Issue by aalmiray** [micronaut-projects/micronaut-core#3057]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an application with mn 1.3.4 targeting maven (`mn create-app sample -b maven`)
2. The generated POM contains an extra `<classpath/>` element inside the `<arguments>` section of the plugin's configuration.

OR

1. micronaut-parent 2.0.0.M2 has a faulty definition of the exec-maven-plugin's configuration

        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>exec-maven-plugin</artifactId>
          <version>1.6.0</version>
          <configuration>
            <executable>java</executable>
            <arguments>
              <argument>-classpath</argument>
              <classpath/>
              <argument>-XX:TieredStopAtLevel=1</argument>
              <argument>-Dcom.sun.management.jmxremote</argument>
              <argument>${exec.mainClass}</argument>
            </arguments>
          </configuration>
        </plugin>

### Expected Behaviour

Executing `mvn compile exec:java` should run the application without error.

### Actual Behaviour

    $ mvn exec:java
    [INFO] Scanning for projects...
    [INFO] 
    [INFO] ------------------------< micronaut:micronaut >-------------------------
    [INFO] Building micronaut 0.1
    [INFO] --------------------------------[ jar ]---------------------------------
    [INFO] 
    [INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ micronaut ---
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  1.388 s
    [INFO] Finished at: 2020-04-14T22:17:05+02:00
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (default-cli) on project micronaut: Unable to parse configuration of mojo org.codehaus.mojo:exec-maven-plugin:1.6.0:java for parameter arguments: Cannot store value into array: ArrayStoreException -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginConfigurationException

### Environment Information

- **Operating System**: OSX 10.15.3
- **Micronaut Version:** 1.3.4
- **JDK Version:** 1.8u232

Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: /Users/aalmiray/.sdkman/candidates/maven/current
Java version: 1.8.0_232, vendor: AdoptOpenJDK, runtime: /Users/aalmiray/.sdkman/candidates/java/8.0.232.hs-adpt/jre
Default locale: en_CH, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"

**Comment by sdelamo** [comment]
@aalmiray Please note we are working on a CLI rewrite here: https://github.com/micronaut-projects/micronaut-starter

**Comment by graemerocher** [comment]
We don't support `exec:java` you should use `exec:exec` which forks the process and uses the specified arguments. Even better use the new Maven plugin and run `mn:run`

**Comment by alvarosanchez** [comment]
[`<classpath/>` is a valid option](https://www.mojohaus.org/exec-maven-plugin/examples/example-exec-for-java-programs.html) for `exec:exec`, which is what should be used as Graeme pointed out.

Also, for Micronaut 2.0, the generated applications will use the new [Micronaut Maven Plugin](https://micronaut-projects.github.io/micronaut-maven-plugin/snapshot/) by default. That being said, the plugin can be used with any Micronaut version.

**Comment by aalmiray** [comment]
Thanks for the explanations but by your own admisions `exec:java` should not be used and `exec:exec` will be superseded by a new cli; the fact remains that the `micronaut-parent` contains a definition for the `exec-maven-plugin` that ought to be removed, isn't it?

**Comment by alvarosanchez** [comment]
We aren't completely removing the exec plugin to allow a smoother upgrade experience for 1.x users.
