### ISSUE TITLE
Deadlocks inside DefaultBeanContext

### ISSUE THREAD

**Issue by alexwilbur** [micronaut-projects/micronaut-core#3070]
### Task List

- [ ] Steps to reproduce provided
- [X ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ X] Full description of the issue provided (see below)

### Steps to Reproduce

We see a deadlock in a component after upgrading from Micronaut 1.3.3 to 1.3.4.

I do not know how to trigger this, but so far our CI/CD system reproduces it reliably, and one engineer's laptop is able to repro this sporadically.

The CI/CD is 100% deterministic but unfortunately we cannot debug it because the underlying infra is inaccessible. I do have trace level logging and could share that privately if needed.

One of our engineers captured stack dumps which I am attaching.

The test that triggers the deadlock is nothing special - just a micronaut test with some mocked beans and it uses the low-level HTTP client to make calls to the controller implementation. The test itself hasn't started (as far as I can see) when the deadlock occurs.

### Expected Behaviour

The test should execute.

### Actual Behaviour

The test threads appear to get stuck in a deadlock.

### Environment Information

-  Happens in the CI/CD on linux, but the engineer env is a mac:

uname -a
Darwin Michaels-MBP.home 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64

java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T15:39:06-04:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"

- **Micronaut Version:** 1.3.4.
- **JDK Version:** 1.8

### Example Application

Unfortunately cannot share our repo and I don't know how to make a small test case to reproduce this since many of our other components are working OK with 1.3.4.

[jstack1.txt](https://github.com/micronaut-projects/micronaut-core/files/4493573/jstack1.txt)

**Comment by graemerocher** [comment]
So without an example we are in the realms of trying things and asking you to try snapshots

**Comment by alexwilbur** [comment]
Agree. Very tricky. I'll see if I can carve it out and still reproduce, but moving from 1.3.4 back down to 1.3.3 immediately hid the issue.  I know this is not ideal but wanted to share the JStacks in case this triggered any quick ideas.

**Comment by graemerocher** [comment]
Thank for the feedback

**Comment by croudet** [comment]
I think the problem is there are nested `computeIfAbsent`  call:
```
"main" #1 prio=5 os_prio=31 tid=0x00007ffdbd802000 nid=0x2803 runnable [0x000070000d7c4000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1718)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2104)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2086)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
	- locked <0x000000077077b370> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1095)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1007)
	at com.signify.iot.platform.profileservice.service.$$ProfileResourceAttributesImplTest$GetProfileResourceAttributesService3Definition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
	at io.micronaut.context.DefaultBeanContext.lambda$getScopedBeanForDefinition$56(DefaultBeanContext.java:2111)
	at io.micronaut.context.DefaultBeanContext$$Lambda$807/515153670.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	- locked <0x0000000774695dd8> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2104)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2086)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
	- locked <0x000000077077b370> (a java.util.concurrent.ConcurrentHashMap)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1095)
```
Two calls for:
```
at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2104)
````
And since there is some synchronisation involved in that method it leads to a dealock.

Here is an easy reproducer:
```java
    public static void main(String... args) {
    	ConcurrentHashMap<String, Integer> map = new ConcurrentHashMap<>();
    	int count = map.compute("a", (k, oldValue) -> map.putIfAbsent(k, 0) + 1);
    	System.out.println(count);
    }
```

**Comment by graemerocher** [comment]
yeah but the root cause is normally a circular bean definition

**Comment by croudet** [comment]
Yes that's true.

**Comment by graemerocher** [comment]
The fix for #3124 maybe help this, would be good if you could try it

**Comment by mrwilby** [comment]
We continue to see this issue periodically, and it's always triggered by MicronautTest execution. The issue doesn't appear to be connected with @PostConstruct, nor does it relate to circular dependencies.

Some of our team have created Singleton services that are NOT implementations of interfaces. They're just a class with Singleton annotations. These singletons are then mocked via MockBean (mockito) inside a MicronautTest case. 

When we see the issue, it's usually related to one of these mocked beans. As far as I can tell, possibly micronaut is attempting to create the dependencies of the real bean (rather than realizing that this is a mocked bean that replaces the original Singleton). Refactoring the code so that the singleton's are now a combination of service interface & then singleton implementation, as well as using MockBean(ServiceInterface.class) then works around the issue. Some of the team are using @Primary annotations on the mockito MockBean definition as well - I am not sure if that is key or not. 

I might not be 100% correct in the above but this appears to be what is happening and the workaround (separating interface & implementation) seems to help.

**Comment by graemerocher** [comment]
If you have a reproducer let us know
