### ISSUE TITLE
Controller not support suspend

### ISSUE THREAD

**Issue by tmtbe** [micronaut-projects/micronaut-core#3089]
### Task List

- Controller not support suspend

### Environment Information

- **Operating System**: win10
- **Micronaut Version**: 2.0.0
- **JDK Version**: 1.8

### Example Application

@Controller
open class HelloController {
    @Get("/test")
    open suspend fun test(@QueryValue name: String?): String {
        return name ?: "empty"
    }
}

when i call http://localhost:8080/test?name=1 result is "empty"。
when i not use suspend ,result is "1"

**Comment by tmtbe** [comment]
By the way:
## code 
@Controller
open class HelloController {
    @Get("/test/{name}")
    open suspend fun test(@PathVariable name: String): String {
        return name ?: "empty"
    }
}

it can not build.

The route declares a uri variable named [name], but no corresponding method argument is present
    public java.lang.Object test(@org.jetbrains.annotations.NotNull()

remove suspend it's ok or i set the PathVariable value like:
@Get("/test/{name}")
    open suspend fun test(@PathVariable("name") name: String?): String {
        return name ?: "empty"
    }

**Comment by graemerocher** [comment]
There are fixes to suspend support in master if you want to try. This last error is correct your route defines `String?` whilst the variable in the path is required. It should be `String`
