### ISSUE TITLE
http server controller return type: `Single<HttpResponse<Flowable<MyEntity>>>` results in endless request

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-core#3091]
MN 1.3.4
Kotlin

consider:

```kotlin
   @Get("/test")
    fun test(): Single<HttpResponse<Flowable<MyEntity>>> {
       return Single.fromCallable {
           //do some checks
       }.map {
           service.getSomeFlowable()
       }.map {
           HttpResponse.ok(it)
       }
    }
```

The use of the Single is so you can conditionally change your HttpResponse info.
If you just return HttpResponse<Flowable<MyEntity>> then you seem to need to decide your response upfront `return HttpResponse.ok(service.getSomeFlowable())`.

To work around this problem you can do 

```kotlin
    @Get("/test")
    fun test(): Single<HttpResponse<List<MyEntity>>> {
       return Single.fromCallable {
           //do some checks
       }.map {
           service.getSomeFlowable()
       }.flatMap {
           it.toList()
       }.map {
           HttpResponse.ok(it)
       }
    }
```

Is there other options?  
Assuming no, it would be great if MN handled `Single<HttpResponse<Flowable<MyEntity>>> `, so you can return a non-streaming flowable.
The reason is related to https://github.com/micronaut-projects/micronaut-core/issues/2495#issuecomment-564628646, where the streaming response is already chosen ahead of time when the request starts, not when the request finally succeeds or fails.  
So from a ~most common REST usage, people want to return a typical HTTP response that is a flowable / array of objects.

Thanks!

**Comment by graemerocher** [comment]
That kind of level of nesting flowables and reactive we won't be supporting

**Comment by graemerocher** [comment]
You can just return `HttpResponse<Flowable<MyEntity>>` which is the same

**Comment by StephenOTT** [comment]
@graemerocher  if you return `HttpResponse<Flowable<MyEntity>>`, how can you control HttpResponse selection logic in non-blocking way?

such as:

```kotlin
   @Get("/test")
    fun test(): HttpResponse<Flowable<MyEntity>> {
         return HttpResponse.ok(service.getSomeFlowable())
    }
```

and now being able to 

```koltin
   @Get("/test")
    fun test(): HttpResponse<Flowable<MyEntity>> {
        val result = service.getSomeFlowable()

       if (someCondition){
           val res = HttpResponse.ok(result)
           res.addSomeHeaders()
           ....
           return res

       } else {
            return HttpResponse.accepted(result)
      }
    }
```

What is the proper pattern to handle conditional responses when using reactive?
The spec examples i have found in MN code have all been the `return HttpResponse.ok(service.getSomeFlowable())` pattern.
