### ISSUE TITLE
Flowable.merge corrupts opentracing ScopeManager state

### ISSUE THREAD

**Issue by lgathy** [micronaut-projects/micronaut-core#3093]
### Steps to Reproduce

1. When `tracer.activeSpan() == null`
2. Build and start a new span.
3. Execute a `Flowable.merge` operation in the scope of that span (in the same Thread).
4. Close the scope and finish the span.
5. Check `tracer.activeSpan()` afterwards.

### Expected Behaviour

The active span should be `null`.

### Actual Behaviour

The active span is not null, it contains infromation leaked from the merge operation's span context.

### Environment Information

- **Operating System**: macOS 10.15.4
- **Micronaut Version:** 1.3.4
- **JDK Version:** 11.0.5

### Example Application

I have created a [test case](https://github.com/Tesco/micronaut-core/blob/rxinstrumented-fix/tracing/src/test/groovy/io/micronaut/tracing/instrument/util/OpenTracingInvocationInstrumenterSpec.groovy) for this. The issue is generic though effecting potentially all `InvocationInstrumenter` implementations which do not tolerate chained invocation of their before/afterInvocation() methods, see [this generic test case](https://github.com/Tesco/micronaut-core/blob/rxinstrumented-fix/runtime/src/test/groovy/io/micronaut/reactive/rxjava2/RxChainedInstrumentationSpec.groovy). I posted this as a [question on gitter](https://gitter.im/micronautfw/questions?at=5e98177ce920022432aa1305) earlier on, as I was unsure whether this violates the contract of the `InvocationInstrumenter`. I strongly believe this should not be allowed as it is pretty hard to properly handle any internal state in the instrumenter instances if chained invocations can happen.

I will also post my proposed fix in a PR and link to this issue.

**Comment by graemerocher** [comment]
PRs welcome will help clarify understanding of the issue. Thanks
