### ISSUE TITLE
io.micronaut.core.annotation.Generated not found with GraalVM and function in JDK11

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#3098]
After merging this PR https://github.com/micronaut-projects/micronaut-core/pull/3090, the Micronaut GraalVM Function test app for JDK 11 is failing to compile with the following error:

```
> Task :compileJava
Note: Writing native-image.properties file to destination: META-INF/native-image/function.graal/pojo/native-image.properties
Note: Writing reflection-config.json file to destination: META-INF/native-image/function.graal/pojo/reflection-config.json
Note: Creating bean classes for 3 type elements
error: cannot access Generated
  class file for io.micronaut.core.annotation.Generated not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for io.micronaut.core.annotation.Generated not found
1 error

> Task :compileJava FAILED

FAILURE: Build failed with an exception.
```

To reproduce the issue:

- `git clone https://github.com/micronaut-graal-tests/micronaut-function-graal`
- `cd micronaut-function-graal`
- `sdk use java 20.0.0.r11-grl`
- `./gradlew assemble`

**Comment by graemerocher** [comment]
you need to use `enforcedPlatform` instead of `platform`

**Comment by ilopmar** [comment]
This issue with Gradle and using dependencies from BOM instead from the version defined is becoming annoying... :-(
