### ISSUE TITLE
Access-Control-Allow-Origin missing from response in 2.0.0.M2

### ISSUE THREAD

**Issue by Clintonio** [micronaut-projects/micronaut-core#3100]
### Steps to Reproduce

1. Configure a server to correctly respond via CORS in 1.3.4 (so you will be convinced it is working) 
2. Observe that your responses (not preflight OPTIONS, but the actual response) has the header "Access-Control-Allow-Origin" present 
3. Upgrade to Micronaut 2.0.0.M2
4. Run/Deploy the service
5. Observe that your requests now lack the Access-Control-Allow-Origin header.

### Expected Behaviour

The header is present

### Actual Behaviour

The header is not present

### Environment Information

- **Operating System**: OSX, Alpine Linux
- **Micronaut Version:** 2.0.0.M2
- **JDK Version:** 14

**Comment by graemerocher** [comment]
Something else must be going on here, we are building a project in Micronaut 2.0 right now and this functionality is working. Also we have tests to verify this behaviour. 

See https://github.com/micronaut-projects/micronaut-core/blob/master/http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/NettyCorsSpec.groovy

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue

**Comment by sollecitom** [comment]
Hi there, it only works when adding `micronaut.server.cors.single-header=true` in the configuration. Without overriding the default `false` value, the actual request (not the OPTIONS request) comes back without `Access-Control-Allow-Origin`.

Not sure why it seems to be working for you in Groovy.

**Comment by graemerocher** [comment]
I don't believe the language has anything to do with the problem. The test in question doesn't use `micronaut.server.cors.single-header=true`, however we will investigate.

**Comment by sollecitom** [comment]
Just added our test + configuration to my answer.

**Comment by graemerocher** [comment]
Thanks that helps

**Comment by graemerocher** [comment]
There must be something else at play here. I added a test for the issue and have been unable to reproduce so far https://github.com/micronaut-projects/micronaut-core/commit/cfb4a0d6663548a146f326ca99f52346d0fda011

**Comment by graemerocher** [comment]
Are you using any other filters?

**Comment by sollecitom** [comment]
I initially was, suspected the bug was there, removed them, and the bug was still there. So no, I don't believe that's the issue.

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue. Thank you.

**Comment by graemerocher** [comment]
Or alternatively you may want to verify with the `2.0.0.BUILD-SNAPSHOT` the issue is still present to `build.gradle`:

```groovy
repositories {
    ...
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

And specifying the snapshot version as your BOM:

```groovy
dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:2.0.0.BUILD-SNAPSHOT'
    }
}
```

**Comment by sollecitom** [comment]
Realised the issue is with CORS and suspending functions. Here's a project that exemplifies the issue.

https://github.com/sollecitom/micronaut-examples-issues-cors-suspension

**Comment by graemerocher** [comment]
That helps thanks. We will get it resolved
