### ISSUE TITLE
@Client does not throw on non-2xx status code

### ISSUE THREAD

**Issue by florian-besser** [micronaut-projects/micronaut-core#3104]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create interface like so:
`
@Client("https://myhost.com/")
public interface MyClient {
  @Get("/my/endpoint")
  MyObject makeCall();
}
`
2. Inject `MyClient` e.g. into a class annotated with `@Singleton`
3. Use `myClient` to make a HTTP call

### Expected Behaviour

If the call to `https://myhost.com/my/endpoint` returns 2xx then I'd expect the response body to be parsed as a `MyObject`
If the call returns 4xx or 5xx I expect an Exception to be thrown

### Actual Behaviour

For 2xx (tested with 200) response the expectation is fulfilled.
For 4xx and 5xx the returned object is simply `null`

### Environment Information

- **Operating System**: Linux / RedHat
- **Micronaut Version:** 1.3.4
- **JDK Version:** OpenJDK 11.0.5

### Example Application

- Due to the private nature of my client project no code may be shared to GitHub or other openly-accessible code repositories.

**Comment by graemerocher** [comment]
It is null for `404` for other response types it is an exception. You must be getting a 404 I suggest you enable trace logging in the client and check your request/responses

**Comment by florian-besser** [comment]
Thanks for the explanation. May I raise a PR to make this explicit in the documentation?

I'm referring to this:
https://docs.micronaut.io/latest/guide/httpClient.html

Especially:
`
7.1.6 Error Responses
If an HTTP response is returned with a code of 400 or above, an HttpClientResponseException is created. The exception contains the original response. How that exception gets thrown depends on the return type of the method.

For blocking clients, the exception is thrown and should be caught and handled by the caller. For reactive clients, the exception is passed through the publisher as an error.
`

Here it says: 400 or above would create an exception and for blocking clients (just as this) it would throw.

**Comment by graemerocher** [comment]
This is already explained here https://docs.micronaut.io/latest/guide/index.html#clientError

**Comment by florian-besser** [comment]
Ah, so section 7.1.6 deals only with the lower-level client, whereas 7.2.3 deals with the declarative client. I would not have thought that there is a difference in behavior (only in how you set up these clients).

I'd additionally say that singling out a special behavior for 404 (to me) was unexpected.

I've since reworked my code to circumvent this issue by returning a `Single<MyObject>`, which throws on 404 as expected.

**Comment by ericsnx** [comment]
@graemerocher Sorry to revive such an old issue but I'm a bit puzzled, so if I have the following

```
 @Get("/not-found")
    fun notFound(): Any
```

I need to change it to 

```
 @Get("/not-found")
    fun notFound(): Any?
```

and then since Micronaut does not raise 404 I have to do it manually?

```
client.notFound() ?: throw NotFoundException("resource not found?")
``` 

I just stumbled into this issue and having to do this check manually does not feel right to me, maybe because I'm new to Micronaut in general, is there another way to avoid this?
