### ISSUE TITLE
Modify GraalTypeElementVisitor to generate resource-config.json

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#3108]
Modify `GraalTypeElementVisitor` to generate the file `resource-config.json` and include all the files in `resource` directory.

**Comment by pontello** [comment]
@ilopmar , it will be very helpful to have resource-config.json being generated automatically.

I've also noticed that [files aren't being placed on the recommended folder](https://github.com/micronaut-projects/micronaut-core/blob/master/graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java#L247-L258) as peer [GraalVm docs](https://www.graalvm.org/docs/reference-manual/native-image/#native-image-configuration):

```
META-INF/
└── native-image
    └── groupID
        └── artifactID
            └── native-image.properties
```


Kindly consider fixing it as part of this effort.

Thanks

**Comment by graemerocher** [comment]
@pontello for that issue we would need to make the group id and artifact id configurable via annotation processor parameters, please raise a separate feature request for that to track it. Thanks.
