### ISSUE TITLE
Byte-code instrumentation side-effects

### ISSUE THREAD

**Issue by ratcashdev** [micronaut-projects/micronaut-core#3110]
### Steps to Reproduce

1. create a small sample project. Have a POJO called MyPojo.java. 
2. create a separate jar that is using ByteBuddyAgent to apply instrumentation to selected classes as a javaagent 
3. Instrument MyPojo.java like this:
```
public class LoggerJavaAgent {
static final AgentBuilder.Listener LISTENER = new AgentBuilder.Listener() {
        @Override
        public void onDiscovery(
                final String typeName,
                final ClassLoader classLoader,
                final JavaModule module,
                final boolean loaded) {
                System.out.println(typeName + " was discovered.");
        }

        @Override
        public void onTransformation(
                final TypeDescription typeDescription,
                final ClassLoader classLoader,
                final JavaModule module,
                final boolean loaded,
                final DynamicType dynamicType) {
            System.out.println(typeDescription + " was transformed.");
        }

        @Override
        public void onIgnored(
                final TypeDescription typeDescription,
                final ClassLoader classLoader,
                final JavaModule module,
                final boolean loaded) {
                System.out.println(typeDescription + " was ignored.");
        }

        @Override
        public void onError(
                final String typeName,
                final ClassLoader classLoader,
                final JavaModule module,
                final boolean loaded,
                final Throwable throwable) {
            System.err.println("ERROR " + typeName);
            throwable.printStackTrace(System.out);
        }

        @Override
        public void onComplete(
                final String typeName,
                final ClassLoader classLoader,
                final JavaModule module,
                final boolean loaded) {
                System.out.println(typeName + " was completed.");
        }
    };


private static void agent(final boolean shouldRedefine, final Instrumentation instrumentation) {
...
     AgentBuilder agentBuilder = new AgentBuilder.Default(new ByteBuddy().with(TypeValidation.DISABLED))
                .with(LISTENER)
                .disableClassFormatChanges()
                .with(shouldRedefine
                        ? AgentBuilder.RedefinitionStrategy.RETRANSFORMATION : AgentBuilder.RedefinitionStrategy.DISABLED);

    agentBuilder = agentBuilder.type(isSubTypeOf(MyPojo.class))
                .transform((builder, typeDescription, classLoader, javaModule)
                        -> builder
                            .visit(to(MyPojoInterceptor.class).on(named("methodName")))
                );
...
    agentBuilder.installOn(instrumentation);
}

public static void agentmain(final String agentArgs, final Instrumentation instrumentation) {
        agent(true, instrumentation);
    }
}
```
4. start the project together with the jar

### Expected Behaviour

the `onDiscovery` annd `onTransformation` method of `AgentBuilder.Listener` will be called for MyPojo and the instrumentation is applied.

### Actual Behaviour

the `onDiscovery` method of `AgentBuilder.Listener` is NOT called for MyPojo and the instrumentation is NOT applied.

However, if I comment out the instrumentation, `onDiscovery` is called for MyPojo.

It works flawless if I enable the java-agent for a test-case (or rather integration test case with micronaut running) using: 
```
LoggerJavaAgent.agentmain("", ByteBuddyAgent.install());
```

### Environment Information

- **Operating System**: LINUX
- **Micronaut Version:** 1.3.3
- **JDK Version:** JDK 11.0.7

**Comment by graemerocher** [comment]
I don't see what this has to do with Micronaut

**Comment by ratcashdev** [comment]
@graemerocher I am not sure either. The very same approach works flawless in other projects that DON'T use micronaut.

Reason I posted this was to eliminate the possible interference between micronaut's introspection and compile time code generation and ByteBuddy's instrumentation.
I find it very strange, that it works when running a test case but it does not when starting the JVM up with the agent specified through the command line.

**Comment by graemerocher** [comment]
Maybe @raphw can chip in. Micronaut doesn't modify your byte code, but maybe ByteBuddy doesn't like our byte code for some reason? I don't know enough about ByteBuddy to answer this.

**Comment by ratcashdev** [comment]
I posted a question also to ByteBuddy: https://github.com/raphw/byte-buddy/issues/849

**Comment by ratcashdev** [comment]
solved. Problem was in the premain method not applying transformations, why the agentMain was.
User error, as usual.
