### ISSUE TITLE
[docs] metrics endpoint doc does not list all integrations

### ISSUE THREAD

**Issue by benmccann** [micronaut-projects/micronaut-core#3111]
https://docs.micronaut.io/latest/guide/management.html#metricsEndpoint says:

> supply one of micrometer-atlas, micrometer-graphite, micrometer-prometheus, or micrometer-statsd features 

I think there's a more substantial list of features supported?
https://github.com/micronaut-projects/micronaut-core/blob/3c329e8fe435ab403424748143a83a2b240b7ef0/build.gradle#L280

Maybe it should just link to https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/ instead of trying to list them all

**Comment by graemerocher** [comment]
A link would be appropriate yes
