### ISSUE TITLE
Default annotation values are not retained in the metadata

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#3125]
Given an annotation like:

```java
public @interface CacheInvalidate {
    boolean all() default false;
}
```

Used without values, like `@CacheInvalidate`.

When calling `AnnotationMetadata::getRequiredValue` with `"all"` and `Boolean.class`, it throws an exception because there are no default values in the annotation metadata.

![image](https://user-images.githubusercontent.com/153880/80701084-1d2c3d00-8adf-11ea-8c8e-e4d0d385957a.png)

**Comment by graemerocher** [comment]
The previous code ended up using reflection hence why it was removed since the approach wouldn't work on GraalVM. I have updated the cache plugin code to note use this method anymore.
