### ISSUE TITLE
Updated from 1.3.4 to 2.0.0 M3 missing  io.micronaut:micronaut-security

### ISSUE THREAD

**Issue by chenjpu** [micronaut-projects/micronaut-core#3126]
```
dependencyManagement {
    imports {
        mavenBom "io.micronaut:micronaut-bom:2.0.0.M3"
    }
}
```
# Environment Information
- **Micronaut Version:**  2.0.0.M3
- **JDK Version:** JDK8

Could not resolve: io.micronaut:micronaut-security

**Comment by jameskleeh** [comment]
@chenjpu Why do you have a dependency on the core security module? Did you write your own extension and are not using jwt,session,ldap,oauth2 ?

**Comment by chenjpu** [comment]
@jameskleeh Yes, I have some of my own expansion and control

**Comment by graemerocher** [comment]
We should add this dependency to the BOM
