### ISSUE TITLE
Support package-level visibility of Condition classes mentioned in @Requires

### ISSUE THREAD

**Issue by posto** [micronaut-projects/micronaut-core#313]
As discussed in the Gitter channel, support for package-level classes in `@Requires(condition=...)` annotations should be implemented.

### Steps to Reproduce

1. create a package-level Condition class
2. mention it in `@Requires(condition=...)` annotation

### Expected Behaviour

Condition should be called.

### Actual Behaviour

Instantiation of condition fails with IllegalAccessException.

**Comment by jameskleeh** [comment]
@graemerocher Do we have a decision on this one?

**Comment by graemerocher** [comment]
one option to allow this is allow condition classes to be beans themselves. Not sure how easy that is to do though

**Comment by jameskleeh** [comment]
@posto Unfortunately due to the reasons above, this change is not going to be made in Micronaut at this time. I appreciate the issue and the PR!
