### ISSUE TITLE
Annotation mapper for Bindable annotations does not populate Bindable stereotype data

### ISSUE THREAD

**Issue by asodja** [micronaut-projects/micronaut-core#3131]
When testing Jaxrs app I noticed that I get route validation errors when my Java variable name does not match one in route, example:
```
@GET
@Path("/path{?q}")
public String index(@Nullable @QueryParam("q") String queryValue) {
    return queryValue;
}
```
returns :
```
error: The route declares a uri variable named [q], but no corresponding method argument is present
    public String index(@Nullable @QueryParam("q") String queryValue) {
                  ^
```
---
I dig a bit in jax-rs mappers code and it looks like issue is not there, `@QueryParam` is correctly mapped to `@QueryValue`. The problem seems to be that `@Bindable` values are not populated. So with debbuger you can see that in constructor:
```
RouteParameterElement(ParameterElement delegate) {
    this.delegate = delegate;
    this.name = delegate.stringValue(Bindable.class).orElse(delegate.getName());
}
```
`this.name` equals to  `queryValue` even though that delegate has correct `@QueryValue` with value `q` in annotation metadata `allAnnotations`, but `@Bindable` does not have any value in `allStereotypes`.

---

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. git clone git@github.com:asodja/micronaut-bindable-reproduce.git
2. Run `TestControllerTest`

### Expected Behaviour

Application should compile, `@QueryParam("q")` should behave the same as `@QueryValue("q")`. 

### Actual Behaviour

Application does not compile.

### Environment Information

- **Operating System**: macOS Catalina
- **Micronaut Version:** 1.3.4, 1.3.5.BUILD-SNAPSHOT, 2.0.0.BUILD-SNAPSHOT
- **JDK Version:** Java 8

### Example Application

- https://github.com/asodja/micronaut-bindable-reproduce

**Comment by jameskleeh** [comment]
Thank you for the well formed and detailed issue report. We'll look into it

**Comment by graemerocher** [comment]
The issue appears to be `@QueryValue` uses `@AliasFor` which is not handled by `AnnotationMapper`
