### ISSUE TITLE
Document LogLevel package rename in Micronaut 2.x

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#3137]
`LogLevel` has been moved from `io.micronaut.management.endpoint.loggers` to `io.micronaut.logging`

**Comment by alvarosanchez** [comment]
See https://github.com/micronaut-projects/micronaut-core/issues/3024

**Comment by ladybug** [comment]
https://github.com/micronaut-projects/micronaut-core/pull/3689
