### ISSUE TITLE
@EventListener not propagated from interface method

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#3140]
In `2.0.0.M3`.

I'm migrating from M2 to M3 and JTW refresh token policy is now changed and requires to implement [RefreshTokenPersistence](https://github.com/micronaut-projects/micronaut-security/blob/v2.0.0.M2/security/src/main/java/io/micronaut/security/token/refresh/RefreshTokenPersistence.java) bean.

This interface has `@EventListener` on the `persistToken()` method, which I'm guessing should be propagated to related implementation method in a bean. However, this doesn't work and without repeating the same annotation on overridden method this method is never called.

**Comment by jameskleeh** [comment]
@l0co Are you using Java/Groovy/Kotlin?

**Comment by l0co** [comment]
The project is microservice-based with some parts written in kotlin and some parts in java. Generally, kapt is used for annotations processing:

```
    kapt {
        arguments {
            arg("micronaut.processing.incremental", true)
            arg("micronaut.processing.annotations", "my.package.*")
        }
    }
```

And here is the main section with deps:

```
dependencies {
    implementation platform("io.micronaut:micronaut-bom:$micronautVersion")
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}"
    implementation "org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}"
    kapt platform("io.micronaut:micronaut-bom:$micronautVersion")
    kapt "io.micronaut:micronaut-inject-java"
    kapt "io.micronaut:micronaut-validation"
    kaptTest platform("io.micronaut:micronaut-bom:$micronautVersion")
    kaptTest "io.micronaut:micronaut-inject-java"
    runtimeOnly "com.fasterxml.jackson.module:jackson-module-kotlin:2.9.8"
    implementation "io.micronaut:micronaut-inject"
    implementation "io.micronaut:micronaut-validation"
    implementation "javax.annotation:javax.annotation-api"
    implementation "io.micronaut:micronaut-runtime"
    implementation "io.micronaut:micronaut-http-client"
    runtimeOnly "ch.qos.logback:logback-classic:${libLogbackVersion}"
    testImplementation platform("io.micronaut:micronaut-bom:$micronautVersion")
    testAnnotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
    testAnnotationProcessor "io.micronaut:micronaut-inject-java"
    testImplementation "org.junit.jupiter:junit-jupiter-api"
    testImplementation "io.micronaut.test:micronaut-test-junit5"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
}
```

**Comment by l0co** [comment]
Actually, it looks the annotation processing is done by kapt even for java code.

**Comment by jameskleeh** [comment]
@l0co Is the interface and the resulting implementation written in Java or Kotlin?

**Comment by l0co** [comment]
> @l0co Is the implementation written in Java or Kotlin?

Java.
