### ISSUE TITLE
Upgrade to GraalVM 20.1 on May 19 for Kotlin coroutine support

### ISSUE THREAD

**Issue by benmccann** [micronaut-projects/micronaut-core#3152]
I hit an issue with Kotlin coroutine support today. It turns out it has been fixed in the GraalVM compiler and the fix will be included with the next release on May 19. I'm putting this issue here to track it

The place to update it is:
https://github.com/micronaut-projects/micronaut-core/blob/5453a6b844a6b30f78b7f3f6fabc50599cda6d09/gradle.properties#L114

We should then be able to remove the sentence "Due to the way Kotlin compiler generates bytecode for coroutines they are currently unsupported out-of-the-box in GraalVM. There is, however, a workaround for this problem." from https://github.com/micronaut-projects/micronaut-core/blob/master/src/main/docs/guide/languageSupport/kotlin/coroutines.adoc

**Comment by ilopmar** [comment]
@benmccann if you want to give it a try, the GraalVM team publishes "snapshopt" releases so you can use the lastest 20.1.0-dev: https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/20.1.0-dev-20200430_1443
