### ISSUE TITLE
Release a new version of Micronaut Elasticsearch

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#3165]
Bumping its Micronaut version to 1.3.x

**Comment by graemerocher** [comment]
Elastic search doesn't seem to have any changes that warrant a release specifically for Micronaut 2.0 https://github.com/micronaut-projects/micronaut-elasticsearch/pull/28/files

**Comment by alvarosanchez** [comment]
It is to upgrade them to 1.3. Description updated

**Comment by graemerocher** [comment]
@alvarosanchez When you release the new version please update the group ID for the module to `io.micronaut.elasticsearch`
