### ISSUE TITLE
Release a new version of Micronaut Kotlin

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#3178]

**Comment by sdelamo** [comment]
I've reopened the issue because RC1 and RC2 is not sync to maven central. 

https://mvnrepository.com/artifact/io.micronaut.kotlin/micronaut-kotlin-runtime

**Comment by alvarosanchez** [comment]
RC5 is synced in Central:

https://search.maven.org/search?q=g:io.micronaut.kotlin

PS: don't use mvnrepository, better search.maven.org instead
