### ISSUE TITLE
Is it possible to use @Client repositories outside of mucronaut core module?

### ISSUE THREAD

**Issue by akozel** [micronaut-projects/micronaut-core#318]
What if I use micronaut as REST api.

And another framework as queque postprocess worker, like AKKA.
Can I use `@Client` repository from the code from another framework ?

**Comment by graemerocher** [comment]
Sure just include `http-client` dependency run `ApplicationContext ctx = ApplicationContext.run()` and then lookup the client. ie `ctx.getBean(MyClient.class)`
