### ISSUE TITLE
Revert JacksonMediaTypeCodec#objectMapper visibility to protected

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#3180]

**Comment by graemerocher** [comment]
We should revert the change in core that broke this to make it compatible rather than requiring a new release

**Comment by jameskleeh** [comment]
I'm not sure this is a good idea because the mapper may not be initialized. The getter method is there so it could be called which would initialize it

**Comment by graemerocher** [comment]
Then we need to fix and release new versions of the modules that references the protected field

**Comment by graemerocher** [comment]
I believe this is Jackson XML module

**Comment by graemerocher** [comment]
Jackson XML module was updated
