### ISSUE TITLE
Release a new version of Micronaut OpenAPI

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#3181]
Bumping its Micronaut version to 1.3.x

**Comment by graemerocher** [comment]
We should revert the change in core that broke this to make it compatible rather than requiring a new release.

In this case `getPropertyEntries` should be a default interface method that returns an empty list

**Comment by alvarosanchez** [comment]
Still, it should be released bumping its Micronaut version to 1.3.x

**Comment by graemerocher** [comment]
I think since this module is compile time only it doesn't need to be bumped to 1.3.x
