### ISSUE TITLE
Add back micronaut-security to bom

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#3212]
`micronaut-security` was removed from bom here: 

> Leave micronaut-security version to transitive
https://github.com/micronaut-projects/micronaut-core/commit/093cf99e7c5ef5b15574d404697a2f1380d425f2

However, you may want to use just `micronaut-security`. e.g. you want to support in your app just  basic auth but you don't need any security extra module (jwt, ldap, session).

**Comment by alvarosanchez** [comment]
Duplicates #3126
