### ISSUE TITLE
 The order in which the set attributes are injected is random

### ISSUE THREAD

**Issue by chenjpu** [micronaut-projects/micronaut-core#3215]
In 'io.micronaut.jackson.ObjectMapperFactory' class, the order of array attribute injection is random.

As I inherit Odered interface, the order is still random

### Environment Information

- **Micronaut Version:**  1.3.4
- **JDK Version:** JDK8

**Comment by graemerocher** [comment]
So this is a feature request that you would like objects that implement `Ordered` to be sorted automatically when injected right?

**Comment by chenjpu** [comment]
yes injected right, if my collection type is inherited  ```Ordered```  interface. The result I expect is that whatever my collection type is, it should be sorted.

```io.micronaut.core.order.OrderUtil.OrderUtil.COMPARATOR``` algorithms are handled at a default low level for objects that do not implement ordered interface

**Comment by chenjpu** [comment]
For example, ```io.micronaut.jackson.ObjectMapperFactory``` in the micronaut framework,all sets of properties  is a third-party-defined type that must be implement ```Ordered``` to be sorted

**Comment by jameskleeh** [comment]
@chenjpu If the type being injected does not implement `Ordered`, we assume none of the implementations do either. You can use the `@Order` annotation for this use case.
