### ISSUE TITLE
wish: auto space encoding in http-client URI

### ISSUE THREAD

**Issue by kbachl** [micronaut-projects/micronaut-core#3226]
Micronaut 1.3.5;

This works:
```
@Get('/DeliveryNotes?$filter=U_timestamp%20eq%200')
    def getDeliveriesForTimestampToProcess()
```

this fails:
```
@Get('/DeliveryNotes?$filter=U_timestamp eq 0')
    def getDeliveriesForTimestampToProcess2()
```

it would be nice if micronaut could automatically grab any space in URIs and replace them with %20 so its more readable in code

**Comment by graemerocher** [comment]
For this use case you would have to use a URI variable and a parameter

**Comment by kbachl** [comment]
Problem here for me is that I try to make OData calls using the client. I tried it that way but it is, lets say, not simple or elegant. I coul do:

```
@Get('/DeliveryNotes?$select=DocEntry,DocNum,DocType,NumAtCard,U_timestamp,U_versandmail')
    DeliverysTimestamp getDeliveriesForTimestampToProcessTest(@QueryValue(value = '$filter', defaultValue = 'U_timestamp eq 0') filter)
```

but this leads to exception as  '$filter' is made to %24filter and this gets rejected by the OData Definition where is has to be '$filter' in URI

I could do:
```
    @Get('/DeliveryNotes?$filter={filter}&$select=DocEntry,DocNum,DocType,NumAtCard,U_timestamp,U_versandmail')
    DeliverysTimestamp getDeliveriesForTimestampToProcessTest(@QueryValue(value = "filter", defaultValue = "U_timestamp eq 0") filter)
```

and that is working, yet I still end up having to manual put all the params into the `@Get ` while having to get a 2nd function that calls it to get a 0 param function e.g.: getDeliveriesForTimestampToProcessTest()
since the $filter and $select etc. cant be simply changed as this leads to much different return data meaning at least $select will break anything as it defines the fileds like SQL that gets returned plus pathing etc.

**Comment by kbachl** [comment]
Ok, follow up. It seems that the $filter replacement to %24filter violates 
https://tools.ietf.org/html/rfc3986#section-2.2
where  $ is one of the 
```
reserved    = gen-delims / sub-delims

      gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

      sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```
Any Feedback on that?
