### ISSUE TITLE
Add a root bean into the validation context.

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#3243]
This is a feature request for `micronaut-validation`.

You could extend `ConstraintValidatorContext` with method returning validated bean. It currently returns only a clock provider:

```java
public interface ConstraintValidatorContext {
    @NonNull ClockProvider getClockProvider();
}
```

But it could return also a `rootBean`: 

```java
public interface ConstraintValidatorContext {
    @NonNull ClockProvider getClockProvider();
    @Nullable Object getRootBean();
}
```

You have everything required beneath, just need to add this method to the interface and to (private final) `DefaultConstraintValidatorContext`.

Usecase: contextual validation on which one can check something additional about the root bean, for example if it implements some interface, etc.

Related discussions:

1. https://stackoverflow.com/questions/37750656/how-to-access-a-field-which-is-described-in-annotation-property
1. https://hibernate.atlassian.net/browse/BVAL-237

They aren't going to implement this in hibernate validator because "they aren't going to".

**Comment by l0co** [comment]
In fact, there's a root bean accessible now from the context, but only with a reflection.

**Comment by graemerocher** [comment]
Since this may be specific to your use case maybe you would like to put together a PR for what you have in mind.

**Comment by jameskleeh** [comment]
@l0co Based on your example you included in the hibernate issue, it seems the validation annotation should be applied to the root object since it relies on multiple properties of that object

**Comment by l0co** [comment]
@jameskleeh This kind of solution is ugly, dirty and not very fantastic from the performance point of view. To achieve simple goals you have to use reflection and iterate through fields to find what you want. See the example [here](https://stackoverflow.com/a/37814382/320761).

Having the root bean in validation context the implementation from the link above could look like this:

```java
@Entity public class User {

    @NotBlank
    private String password;

    @Match(field = "password")
    private String passwordConfirmation;
}

public class MatchValidator implements  ConstraintValidator<Match, Object> {

    @Override
    public boolean isValid(final Object o, final ConstraintValidatorContext context) {
        String fieldName = context.getAnnotation().field();
        Object rootBean = context.getRootBean();
        return o.equals(rootBean.getField(fieldName).get(rootBean));
    }
    
}
```

**Comment by jameskleeh** [comment]
```
@Matches("password", "passwordConfirmation")
@Introspected
@Entity public class User {

    @NotBlank
    private String password;

    private String passwordConfirmation;
}

public class MatchValidator implements  ConstraintValidator<Matches, Object> {

    @Override
    public boolean isValid(final Object o, final ConstraintValidatorContext context) {
        // retrieve the bean introspection
        // retrieve the properties from the introspection for the `o`
        // test they are equal
    }
    
}
```

You can use introspections to not have to worry about reflection and the inherit performance costs of doing so. I don't think that type of logic is ugly or dirty

**Comment by l0co** [comment]
This solution is indeed much cleaner than the example from stackoverflow (the ugly part there is iteration over fields using reflection). I haven't been thinking too much about this example because it's not my usecase. I want to do something a bit different...

Anyway, with the current validation I can either have a root bean instance and lookup for particular fields using reflection or introspection **or** I can have the field value but no bean instance. There's no option to have both things on hand (the field value and the bean instance) what would be much more flexible, and micronaut implementation can give this with only a few lines of code.

In the meantime I've created PR #3263
