### ISSUE TITLE
http-netty should provide --initialize-at-run-time flags

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#3252]
Currently the following warnings occur:

```
Warning: class initialization of class io.micronaut.http.netty.channel.converters.EpollChannelOptionFactory failed with exception java.lang.NoClassDefFoundError: io/netty/channel/epoll/EpollChannelOption. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.micronaut.http.netty.channel.converters.EpollChannelOptionFactory to explicitly request delayed initialization of this class.
Warning: class initialization of class io.micronaut.http.netty.channel.converters.KQueueChannelOptionFactory failed with exception java.lang.NoClassDefFoundError: io/netty/channel/kqueue/KQueueChannelOption. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.micronaut.http.netty.channel.converters.KQueueChannelOptionFactory to explicitly request delayed initialization of this class.
```

This can be avoided by adding `--initialize-at-run-time` as per the error message to our metadata

**Comment by alvarosanchez** [comment]
Now I get the following warnings:

```
WARNING: Could not resolve io.netty.channel.epoll.EpollChannelOption for reflection configuration.
WARNING: Could not resolve io.netty.channel.kqueue.KQueueChannelOption for reflection configuration.
```

**Comment by graemerocher** [comment]
I think to resolve those we need an `@AutomaticFeature`

**Comment by ilopmar** [comment]
Not really sure about how to solve them. According to https://github.com/oracle/graal/issues/1505#issuecomment-530944372

![image](https://user-images.githubusercontent.com/559192/82552460-70376400-9b62-11ea-91c3-bffccaef47eb.png)

I've tried with (note I'm using  `duringSetup` so this is handled before the warning happens):
```java
@AutomaticFeature
final class NettyFeature implements Feature {

    @Override
    public void duringSetup(DuringSetupAccess access) {
        registerForReflection(access, "io.netty.channel.epoll.EpollChannelOption");
        registerForReflection(access, "io.netty.channel.kqueue.KQueueChannelOption");
    }

    private void registerForReflection(DuringSetupAccess access, String n) {
        Class<?> t = access.findClassByName(n);
        if (t != null) {
            // tried both just in case. It doesn't make any difference
            RuntimeReflection.register(t);
            RuntimeReflection.registerForReflectiveInstantiation(t);
        }
```
But the result is the same. I've asked in GraalVM slack.

**Comment by ilopmar** [comment]
I've finally found where this warnings are coming from, this commit https://github.com/micronaut-projects/micronaut-core/commit/73bf437ecb350ac3005fdfa730b99ddc410fca4d.
Commenting out those `@TypeHint` make the warnings disappear. I think the warning happens because the classes are not on the classpath (I've checked and in the `basic-app` they are not).

I think I can write now an `@AutomaticFeature` to add the configuration if the classes are present.

In the mean time, @croudet can you please explain why you added them? If you can share an example of where they are needed it would be great so I can test the fix.

**Comment by croudet** [comment]
@ilopmar I have been asked to add them:
https://github.com/micronaut-projects/micronaut-core/pull/3043#issuecomment-613282014
