### ISSUE TITLE
Self signed requires client ssl to be enabled

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-core#3255]
```
@Requires(property = SslConfiguration.PREFIX + ".enabled", value = TRUE, defaultValue = FALSE)
@Requires(property = SslConfiguration.PREFIX + ".build-self-signed", value = TRUE, defaultValue = FALSE)
@Singleton
@Internal
public class SelfSignedSslBuilder extends SslBuilder<SslContext> implements ServerSslBuilder {
```

It requires `micronaut.ssl.enabled`, which enables SSL for the client. I think that is the default anyways and it is unlikely anyone will want to disable it, but the possibility exists. In addition this is a server only feature, so it should probably only exist in the server config. Currently `micronaut.server.ssl.build-self-signed` does nothing.

This will likely require a custom condition because it should be enabled for `ssl.enabled` or `server.ssl.enabled`

Seems to me `micronaut.ssl.build-self-signed` should be `micronaut.server.ssl.build-self-signed`

**Comment by timyates** [comment]
Is the same true for `micronaut.ssl.port`?

**Comment by jameskleeh** [comment]
I think so

**Comment by timyates** [comment]
👀  👍 

On it

**Comment by timyates** [comment]
Closed by https://github.com/micronaut-projects/micronaut-core/pull/6779 in 3.3.0
