### ISSUE TITLE
OpenJDK 14.0.1 reports an illegal reflective access when running mn 2.0.0.M2

### ISSUE THREAD

**Issue by ikakara** [micronaut-projects/micronaut-core#3257]
Not sure if this is still a concern, since I'm a few builds behind. 
OpenJDK 14.0.1 - from redhat
Micronaut 2.0.0.M2 (taken from the release zip)
Windows 10 v1903

Running (on Windows 10) ...
$ mn -V
... returns:
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/C:/micronaut-2.0.0.M2/cli-2.0.0.M2.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
| Micronaut Version: 2.0.0.M2
| JVM Version: 14.0.1

---------------------------------------

Running on Docker ToolBox for Windows (default linux container) ... returns something different
$ mn -V
WARNING: package java.security.acl not in java.base
| Micronaut Version: 2.0.0.M2
| JVM Version: 14.0.1

**Comment by graemerocher** [comment]
This is fixed in M3

**Comment by ikakara** [comment]
Thanks.  I haven't been able to test with M3 - the don't include a zip (of the release).  I tried building M3 from source, but I have issues w/ cli.  Anyway, I'll just way for the next release w/ zip I can install.
