### ISSUE TITLE
Improve Kotlin setup instructions for IntelliJ in guide

### ISSUE THREAD

**Issue by johanhaleby** [micronaut-projects/micronaut-core#328]
### Task List

- [x] Steps to reproduce provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new micronaut project:
    ```bash
    mn create-app micronaut-example --features kotlin --build maven
    ```
1. Import project to Intellij
1. Enable Annotation Processing in Intellij (as described [here](http://guides.micronaut.io/creating-your-first-micronaut-app-kotlin/guide/index.html))
1. Create the `HelloController` as indicated by the [docs](http://guides.micronaut.io/creating-your-first-micronaut-app-kotlin/guide/index.html)
1. Configure the server to run on port 8080 in `application.yml` file
1. Run the `main` method from inside Intellij
1. Create a `http` test in Intellij, i.e. create a file called `test.http` with the following content:
    ```http
    GET http://localhost:8080/hello
    Accept: */*
    ```
1. Run `test.http`

### Expected Behaviour

Expecting the `HelloController` to return "Hello World"

### Actual Behaviour

```http
GET http://localhost:8080/hello

HTTP/1.1 404 Not Found
Date: Fri, 29 Jun 2018 09:11:14 GMT
content-type: application/json
content-length: 82

{
  "_links": {
    "self": {
      "href": "/hello",
      "templated": false
    }
  },
  "message": "Page Not Found"
}

Response code: 404 (Not Found); Time: 269ms; Content length: 82 bytes
```

Note that it works if I run the jar file manually from the command-line after having executed `mvn clean install`.

### Environment Information

- **Operating System**: MacOS
-**Intellij Version**: Intellij Ultimate 2018.1.5
- **Micronaut Version:** 1.0.0.M2
- **JDK Version:** 1.8.0_144

**Comment by graemerocher** [comment]
Please see the section https://docs.micronaut.io/latest/guide/index.html#kotlin under "Kotlin, Kapt and IntelliJ"

Hopefully IntelliJ will add direct support in the future for Kapt without requiring an external build step

**Comment by johanhaleby** [comment]
Thanks a lot for the fast reply. One suggestion might be to include this link in the [guide](http://guides.micronaut.io/creating-your-first-micronaut-app-kotlin/guide/index.html). I assume that most people, like me, just read the guide and assume it to work.

**Comment by satb** [comment]
@graemerocher - The guides talk about IntelliJ configuration for gradle. Anything has to be done for maven? I enabled annotation processing but running into the same problem as in this issue. Doing it through command line maven works fine, but running Application.kt through IntelliJ will not work until and unless I run it through the command line first.

**Comment by OndraZizka** [comment]
> I've observed that the memory requirements for a single hello world controller example is 165 MB on the Mac with Kotlin. Is that normal? To me it looks a little on the high side.

For running the result? I doubt that's because of Kotlin, which just creates Java classes. It's more likely because of the framework and the web server (I guess Spring + Tomcat?)
