### ISSUE TITLE
HTTP/2 Problems When Specifying KeyStore

### ISSUE THREAD

**Issue by RyanHoldren** [micronaut-projects/micronaut-core#3299]
I am having trouble getting HTTP/2 to work using M3. I've enabled it, but Chrome and Firefox are both still using HTTP/1.1. There are a bunch of online tools that check whether HTTP/2 is enabled, but they give conflicting results:

- [http2.pro](https://http2.pro/) says **No**
- [gf.dev](https://gf.dev/http2-test) says **Yes**
- [nixcp.com](https://nixcp.com/tools/http2-test/) says **No**

### Environment Information

- **Operating System**: Amazon Linux 2.0
- **Micronaut Version:** 2.0.0.M3
- **JDK Version:** OpenJDK Runtime Environment Corretto-11.0.7.10.1

### Example

When putting together an example to illustrate the problem, I initially excluded `keyStore` and used `build-self-signed` instead so that it would be easier to run. I was a little surprised to see that it worked perfectly with `build-self-signed`. I still don't know exactly what the problem is, but it seems like it might somehow related to `keyStore` being specified. The TLS certificate I am using is whatever Let's Encrypt gives you by default for a request such as `--domains "example.com"  --domains "*.example.com"`.	

[Example.zip](https://github.com/micronaut-projects/micronaut-core/files/4659416/Example.zip)

**Comment by RyanHoldren** [comment]
Is there any additional information I can provide to help with this? Or are there any suggestions for other things I should try?

**Comment by graemerocher** [comment]
Will investigate however if `build-self-signed` is working then it is almost certainly an issue with your SSL configuration

**Comment by RyanHoldren** [comment]
I believe I found the bug! In [`CertificateProvidedSslBuilder`](https://github.com/micronaut-projects/micronaut-core/blob/b5cc40ea85d020d875f5a95e570188d4a47890a1/http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/CertificateProvidedSslBuilder.java#L114) the order of the supported protocols is `HTTP_1_1` **then** `HTTP_2`. In [`SelfSignedSslBuilder`](https://github.com/micronaut-projects/micronaut-core/blob/b5cc40ea85d020d875f5a95e570188d4a47890a1/http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/SelfSignedSslBuilder.java#L98) on the other hand, the order is the other way around. Sure enough, when I reverse the order in `CertificateProvidedSslBuilder`, it immediately starts in Chrome and Firefox. All three of the tools (i.e. [http2.pro](https://http2.pro), [gf.dev](https://gf.dev) and [nixcp.com](https://nixcp.com)) also pass.

I am really confused. How has no one but me noticed this bug?

**Comment by graemerocher** [comment]
Good question, @RyanHoldren would you like to send a PR?

**Comment by RyanHoldren** [comment]
It would be my pleasure :)
