### ISSUE TITLE
Kotlin Module for Jackson: configuration flag for KotlinModule: `nullisSameAsDefault`

### ISSUE THREAD

**Issue by StephenOTT** [micronaut-projects/micronaut-core#3301]
As of kotlin module for jackson 2.10+ you can do the following config of the module:

`ObjectMapper().registerModule(KotlinModule(nullisSameAsDefault = true)`

https://github.com/FasterXML/jackson-module-kotlin/issues/130#issuecomment-546625625

Is there a way through config of MN? or if not, would be great to have this configuration option of jackson.

MN 1.3.4 Kolin

**Comment by bzolivereckle** [comment]
afaik: 

```
@Singleton
    internal class ObjectMapperBeanEventListener : BeanCreatedEventListener<ObjectMapper?> {
        override fun onCreated(event: BeanCreatedEvent<ObjectMapper?>): ObjectMapper {
            val mapper: ObjectMapper = event.bean ?: ObjectMapper()
            mapper.registerModule(JavaTimeModule())
            mapper.registerModule(KotlinModule(nullIsSameAsDefault = true, nullToEmptyMap = true, nullToEmptyCollection = true))
            mapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            mapper.dateFormat = StdDateFormat().withColonInTimeZone(true)
            return mapper
        }
    }
```

**Comment by StephenOTT** [comment]
Nice idea on the listener usage

**Comment by StephenOTT** [comment]
for future ref:

I did something like this:

I disabled module classpath scan, and then recreate the JDK8 modules + the kotlin module:

```kotlin
@Factory
@Requirements(
        Requires(classes = [KotlinModule::class]),
        Requires(property = JacksonConfiguration.PROPERTY_MODULE_SCAN, value = StringUtils.FALSE)
)
class KotlinModuleFactory(
        private val kotlinModuleConfiguration: JacksonKotlinModuleConfiguration
) {

    @Named("kotlinModule")
    @Singleton
    @Requires(classes = [KotlinModule::class])
    @Indexed(Module::class)
    fun kotlinModule(): Module {
        return KotlinModule(
                reflectionCacheSize = kotlinModuleConfiguration.reflectionCacheSize,
                nullToEmptyCollection = kotlinModuleConfiguration.nullToEmptyCollection,
                nullToEmptyMap = kotlinModuleConfiguration.nullToEmptyMap,
                nullisSameAsDefault = kotlinModuleConfiguration.nullisSameAsDefault
        )
    }
}
```

```kotlin
@ConfigurationProperties("jackson.kotlinModule")
interface JacksonKotlinModuleConfiguration{

    @get:Bindable(defaultValue = "512")
    val reflectionCacheSize: Int

    @get:Bindable(defaultValue = StringUtils.FALSE)
    val nullToEmptyCollection: Boolean

    @get:Bindable(defaultValue = StringUtils.FALSE)
    val nullToEmptyMap: Boolean

    @get:Bindable(defaultValue = StringUtils.FALSE)
    val nullisSameAsDefault: Boolean

}
```

**Comment by pravee1801** [comment]
In the same context, does anyone have idea on configurong Jackson objectmapper in a way that. 
There are some of the fields in my schema which are non-nullable and even incase if some Dev or QA give a json omitting certain non-nullable collections, it is throwing kotlinparameter exception which is expected. So I want to config my objectmapper in some way that even if some non-nullable collections fields are omitted I want Jackson to deserialize it as an emptylist. Any simple configuration for this which we can configure while building the mapper other than a 1. custom deserializer and 2.annotations as the schema has multiple collections of nested class.
[Kotlin Codebase with Maven 3.8.6 running on JDK17 and Springboot 2.x]
