### ISSUE TITLE
DefaultLink does not support templated links with URI Templates

### ISSUE THREAD

**Issue by jcassee** [micronaut-projects/micronaut-core#3330]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Try to create a templated Link with a [Form-Style Query Expansion](https://tools.ietf.org/html/rfc6570#section-3.2.8) component.

### Expected Behaviour

The Link can be created.

### Actual Behaviour

The Link cannot be created because the `build()` method accepts only a URI, which cannot contain all characters supported by URI Templates. For example, `URI.create("https://example.com/test{?param}")` results in `java.net.URISyntaxException: Illegal character in path at index 24: https://example.com/test{?param}`.

Even if `build()` were overloaded with a String version, `DefaultLink.href` is defined as a URI, so it would also have to be changed. I'm not sure whether this would be a publicly visible change, which could be backward incompatible.

### Environment Information

- **Operating System**: Ubuntu 20.04
- **Micronaut Version:** 1.3.5
- **JDK Version:** 11.0.7

### Example

```
Link.build(new URI("https://example.com/test{?param}")).templated(true).build();
```

**Comment by graemerocher** [comment]
Yeah I noticed this, and had to use different classes for starter https://github.com/micronaut-projects/micronaut-starter/blob/master/starter-api/src/main/java/io/micronaut/starter/api/Linkable.java

Will fix this in core. Thanks for the report
