### ISSUE TITLE
HttpMethod is opinionated about what HTTP methods permit a body

### ISSUE THREAD

**Issue by nhoughto** [micronaut-projects/micronaut-core#3331]
`HttpMethod.permitsRequestBody` hardcodes what methods are 'permitted' to have a body and thus have the body parsed and accessible. This opinionated view on how HTTP should be used limits micronauts application to different usecases. As per the HTTP spec and popular interpretation GET can have a body (although it is likely a bad idea), as per discussion: https://stackoverflow.com/questions/978061/http-get-with-request-body

There doesn't seem to be any value in preventing this behaviour if that is the intent of the developer using your framework.

### Expected Behaviour

GET requests should be able to use the @Body annotation to retrieve the request body

### Actual Behaviour

The body is unavailable / null

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** 1.3.5
- **JDK Version:** 8

**Comment by graemerocher** [comment]
There is value from a performance perspective. I am unsure as well we should be encouraging bad practice with the the framework

**Comment by nhoughto** [comment]
So having a default is fine, but the way its implemented at the moment (via static methods) aren't configurable / overridable in the usual ways, so its a hard limit rather than a sane default.

I guess if that is the intent then thats ok, I wasn't sure if it was a conscious decision or an accident of history, thus the issue =)

**Comment by jameskleeh** [comment]
@nhoughto I don't think it makes much sense to allow for this. It would require a lot of refactoring and have potential widespread impact on other areas that wouldn't be obvious. Seems to be a very niche use case.

**Comment by nhoughto** [comment]
:+1: thanks for clearing it up
