### ISSUE TITLE
Issue with WindowsAnsiOutputStream class not found occuring in Micronaut 2.0.0.M3

### ISSUE THREAD

**Issue by deanfarwell** [micronaut-projects/micronaut-core#3374]
### Steps to Reproduce

1. Created new project using Micronaut Laundh
2. Built using Gradle
3. Ran project using gradle

### Expected Behaviour

Should start without error

### Actual Behaviour
Started fine but got the following message

11:15:02,644 |-INFO in ch.qos.logback.core.ConsoleAppender[STDOUT] - Enabling JANSI WindowsAnsiOutputStream for the console.
11:15:02,645 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - Failed to create WindowsAnsiOutputStream. Falling back on the default stream. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.fusesource.jansi.WindowsAnsiOutputStream
        at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type org.fusesource.jansi.WindowsAnsiOutputStream
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:69)
        at      at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:40)
        at      at ch.qos.logback.core.ConsoleAppender.getTargetStreamForWindows(ConsoleAppender.java:88)

### Environment Information

- **Operating System**:   Windows 10
- **Micronaut Version:**  2.0.0.M3
- **JDK Version:** Java 8

### Example Application

This is the same issue as https://github.com/micronaut-projects/micronaut-core/issues/1521, which was closed.  It seems to have come back in Micronaut version 2.  Easy to work around but still it should be disabled by default.

**Comment by graemerocher** [comment]
Already addressed, thanks for the report
