### ISSUE TITLE
Unable to send h2c request to Micronaut server

### ISSUE THREAD

**Issue by shashanka981** [micronaut-projects/micronaut-core#3389]
I am having a simple setup with http2 enabled on Micronaut - with SSL disabled.  Exposed an endpoint on the server - which returns a constant value as an output/response.

I have written a  standalone java program to create a httpclient and issue a request to endpoint i exposed on Micronaut

Attaching the application.yaml and java program to initiate the client below

**### Expected Behaviour**

I am expecting that HttpClient should be able to  get the response from server. 

**### Actual Behaviour**

Program hangs at the call when request is sent to server.  Note that Same program works when i enable SSL on micronaut. I see same issue when using RxHttpClient. 

How can i hit an endpoint that is served over h2c using Micronaut OOTB ? or is this a restriction

**### Environment Information**

- **Operating System**: Ubuntu 18
- **Micronaut Version:** 2.0.0.M3
- **JDK Version:** Open JDK 11

**### Example Application**

package com.org.MyPackage;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

public class test {
    public static void main(String args[]) throws IOException, InterruptedException {
        HttpClient client = HttpClient.newBuilder()
            .version(HttpClient.Version.HTTP_2)
            .build();
        HttpRequest request = HttpRequest.newBuilder()
            .header("Content-Type", "application/json")
            .uri(URI.create("<actual endpoint>"))
            .GET()
            .build();
        HttpResponse<String> response =
            client.send(request, HttpResponse.BodyHandlers.ofString());
        System.out.println(response.statusCode());
        System.out.println(response.body());
    }
}

**Also the application.yaml config**

micronaut:
  ssl:
    enabled: false
    port: 8080
  server:
    host: localhost
    port: 8080
    http-version: 2.0

**Comment by graemerocher** [comment]
With SSL disabled it has to attempt an upgrade over plain text and both the client and the server have to be configured for HTTP2. See https://github.com/micronaut-projects/micronaut-core/blob/master/test-suite/src/test/groovy/io/micronaut/http/client/http2/Http2RequestSpec.groovy#L94 for an example with Micronaut's client.

For the java client I imagine you would have to send an initialize upgrade request if this is not implemented automatically by the client.

**Comment by shashanka981** [comment]
Hi

Thanks for quick response.

Here is the program and application.yaml, i have using Micronaut rxHttp client that works with h2 protocol, but with h2c, it gets into a readtimeout exception.  I may be missing something here.. Can you help me figure out ? Any other configuration needed to support h2c other than application.yaml?


**Application.yaml**

micronaut:
  ssl:
    enabled: false
    buildSelfSigned: true
    port: ${APPLICATION_PORT:8080}
  server:
    host: ${APPLICATION_HOST:localhost}
    port: ${APPLICATION_PORT:8080}
    http-version: 2.0
  http:
    client:
      http-version: 2.0


package com.org.Mypackage;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.micronaut.core.type.Argument;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.HttpResponse;
import io.micronaut.http.HttpVersion;
import io.micronaut.http.client.RxHttpClient;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.http.client.exceptions.HttpClientResponseException;
import io.micronaut.test.annotation.MicronautTest;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.inject.Inject;
import java.io.IOException;

@MicronautTest
public class Testh2c {
    @Inject
    @Client(httpVersion=HttpVersion.HTTP_2_0)
    private RxHttpClient client;

    @Test
    public void test_cache_creation_and_basicOperations() {

        ObjectMapper mapper = new ObjectMapper();
        String requestBody = "**************************************8" ;
        HttpRequest cacheCreationRequest = HttpRequest.POST("http://localhost:8080/cache", requestBody);
        HttpResponse response = client.toBlocking().exchange(cacheCreationRequest, Argument.of(String.class));
        Assertions.assertThat(response.getStatus().getCode()).isEqualTo(200);
        Assertions.assertThat(response.getBody()).isNotEmpty();
    }
}

**Comment by graemerocher** [comment]
Maybe if you upload an example application. I tried a post request with `h2c` and it works fine https://github.com/micronaut-projects/micronaut-core/commit/f394d7ffa406b13a46f770d278510251c22c5b5b

**Comment by kbachl** [comment]
@shashanka981 if I may point you to something:
Http2 has no requriement of encryption (e.g: SSL) but to be fair it is expected to only reliably work when using encryption, see:
https://http2.github.io/faq/#does-http2-require-encryption
So no browser as of today works without it and I suggest you just use SSL/TLS with a custom certificate

**Comment by shashanka981** [comment]
@graemerocher 
I believe i figured out what was the issue in my environment when working with h2c.
It appears like defining micronaut.http.client.read-timeout is mandatory for a Micronaut http client to talk to Micronaut h2c enabled server.

can you try removing the above said field and validate the behaviour ? If so,  can you tell me little bit about this setting and what is the thinking behind making this setting mandatory or is this a bug from Micronaut end ?

@kbachl  In our case, we think enabling SSL adds to the cost and with our current architecture, we think we dont face the problem of some one spying over the data over the wire.

Other question i have is when i hit the endpoint exposed by Micronaut server from browser, i still am able to talk to server, but looks like the communication happens over http/1.1 . Is this expected behavior ? is there a way in Micronaut by which i can enable communication to happen only on http/2

**Comment by graemerocher** [comment]
As @kbachl pointed out browsers generally only support communication via http/2 with TLS

**Comment by shashanka981** [comment]
Hi @graemerocher  i agree on the point of supporting  h2c from browsers, my question actually was if Micronaut will be able to server both h2 and http/1.1 requests at same time depending on client support - if a client doesnt support h2, then it has to fall back to http/1.1.

Also, what is the justification behind mandating to set **micronaut.http.client.read-timeout** in application yaml for h2c support from Micronaut ?

**Comment by graemerocher** [comment]
@shashanka981 The `read-timeout` requirement was indeed a bug, I have push a fixed that will go into the next release.

Micronaut already supports serving both `h2` and `http/1.1` and falling back to `http/1.1` if `h2` is not available.
