### ISSUE TITLE
Add Support For Customizing Response Content Negotiation

### ISSUE THREAD

**Issue by jeffbrown** [micronaut-projects/micronaut-core#340]
While building an Http Client for calling the iTunes search service:

```
import io.micronaut.http.annotation.Get;
import io.micronaut.http.client.Client;

@Client("https://itunes.apple.com/")
public interface ItunesClient {

    @Get("/search?limit=25&media=music&entity=album&term=Riverside")
    SearchResult search();
}
```

...or this...

```
import io.micronaut.http.annotation.Get;
import io.micronaut.http.client.Client;

@Client("https://itunes.apple.com/")
public interface ItunesClient {

    @Get("/search?limit=25&media=music&entity=album&term={term}")
    SearchResult search(String term);
}
```

...it was discovered that the content type of the response is `text/javascript` and that keeps our demarshalling thing from behaving as expected.  The commit at https://github.com/micronaut-projects/micronaut-core/commit/4ba8961cdb9ea7014158a7e3b82af5da808a1fa6 is one approach to making it work for that particular case.

I think we should have some mechanisms to allow folks to deal with situations like this in general, not just ones that we might code for.  That is, folks ought to be able to map a response content type to the behavior of some other content type if desired.

I don't know what the best way to do that is.  Maybe a config setting that maps certain codes to other codes.  Maybe a new annotation like `@ResponseContentType(contentType='application/json')` which would force the system to ignore the actual content type and behave as if it were `application/json`.

I think if we don't have some kind of mechanism for dealing with unexpected response content types, some use cases will end up in a dead end where our client couldn't be used.

**Comment by jeffbrown** [comment]
FYI... As a workaround for now I can make that particular scenario work by including the following in my project...

```java
import com.fasterxml.jackson.databind.ObjectMapper;
import io.micronaut.http.MediaType;
import io.micronaut.jackson.codec.JsonStreamMediaTypeCodec;
import io.micronaut.runtime.ApplicationConfiguration;

import javax.inject.Singleton;

/**
 * This class is temporary, pending a resolution
 * to https://github.com/micronaut-projects/micronaut-core/issues/340
 */
@Singleton
public class JavascriptMediaType extends JsonStreamMediaTypeCodec {

    public static final MediaType JAVASCRIPT_MEDIA_TYPE = new MediaType("text/javascript");

    public JavascriptMediaType(ObjectMapper objectMapper, ApplicationConfiguration applicationConfiguration) {
        super(objectMapper, applicationConfiguration);
    }

    public MediaType getMediaType() {
        return JAVASCRIPT_MEDIA_TYPE;
    }
}
```

**Comment by jameskleeh** [comment]
This can now be configured with `micronaut.codec.json.additionalTypes: ["text/javascript"]`

The `json` section of the configuration can be changed to configure other codecs (text, text-stream, json-stream)

**Comment by jameskleeh** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/3d8ad3005687e69e5fdf31c969201a864cbe296a
