### ISSUE TITLE
Use of @ConfigurationProperties with Kotlin

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#341]
### Steps to reproduce

Create a Micronaut Kotlin app

`mn create-app kotlinfoo --features=kotlin`

Create a class to encapsulate configuration properties:

```
package kotlinfoo

import io.micronaut.context.annotation.ConfigurationProperties

@ConfigurationProperties("bintray")
class AppConfigurationProperties(val username : String) {

}
```

Create a controller: 

package kotlinfoo
```

import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.micronaut.context.annotation.Value

@Controller("/app")
class AppController(val appConfigurationProperties: AppConfigurationProperties) {

    @Get("/")
    fun index(): String {
        return appConfigurationProperties.username
    }
}
```

Add `bintray.username` configuration to `src/main/resources/application.yml`

```
micronaut:
    application:
        name: kotlinfoo
    server:
        port: 8080
bintray:
    username: sdelamo
```

Start the app and try to access `/app` endpoint

### Expected Behaviour

endpoint returns `sdelamo`

### Actual Behaviour

```
17:37:56.386 [nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Failed to inject value for parameter [username] of class: kotlinfoo.AppConfigurationProperties

{"message":"Internal Server Error: Failed to inject value for parameter [username] of class: kotlinfoo.AppConfigurationProperties\n\nMessage: No bean of type [java.lang.String] exists. If you are using Java or Kotlin make sure you have enabled annotation processing.\nPath Taken: new AppController([AppConfigurationProperties appConfigurationProperties]) --> new AppConfigurationProperties([String username])"}
```

[kotlinfoo.zip](https://github.com/micronaut-projects/micronaut-core/files/2155845/kotlinfoo.zip)
"Enable annnotation processors" is checked. 

### Environment Information

- **Operating System**: MacOs
- **Micronaut Version:** 1.0.0.M2
- **JDK Version:** 1.8.0_161

### Example Application

[kotlinfoo.zip](https://github.com/micronaut-projects/micronaut-core/files/2155847/kotlinfoo.zip)

**Comment by graemerocher** [comment]
This is because you are defining `username` as a constructor argument
