### ISSUE TITLE
micronaut-hibernate-validator can not be resolved at the new maven coordinates

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#3459]
Generate a 2.0.0.BUILD-SNAPSHOT Groovy project with `hibernate-gorm` feature which includes `micronaut-hibernate-validator`

<img width="1095" alt="Screenshot 2020-06-10 at 11 17 16" src="https://user-images.githubusercontent.com/864788/84250157-fb759b00-ab0b-11ea-9bc9-b4570fb685b2.png">

It cannot resolve 

```
Could not resolve io.micronaut.beanvalidation:micronaut-hibernate-validator:2.0.0.

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/pull/3461
