### ISSUE TITLE
i18n issue with some characters

### ISSUE THREAD

**Issue by frangarcia** [micronaut-projects/micronaut-core#3468]
I am trying to use properties file to internationalise the application I am building but I am getting issues with some characters like ñ. The application I created to replicate the issue only has a controller called HomeController.java and it is basically printing out a translated message.

### Steps to Reproduce

1. Start the app with ./gradlew run
2. Go to http://localhost:8080
3. The message output has wrong characters

### Expected Behaviour

It should print out _Inválido en Español_

### Actual Behaviour

It is printing out _InvÃ¡lido en EspaÃ±ol_

### Environment Information

- **Operating System**: Mac OS X Mojave 10.14.6
- **Micronaut Version:** 1.3.5
- **JDK Version:** openjdk version "1.8.0_252"

### Example Application

https://github.com/frangarcia/i18nutf

**Comment by jameskleeh** [comment]
Given this is resolved with Java 9 and future versions of Micronaut will not likely support Java 8 I'm going to close this as a wont fix.
