### ISSUE TITLE
jackson dateformat doesn't work for LocalDateTime

### ISSUE THREAD

**Issue by cooocy** [micronaut-projects/micronaut-core#3498]
```properties
# jackson.serialization.write-dates-as-timestamps=true
jackson.date-format=yyyy-MM-dd HH:mm:ss
```
These properties of jackson works when the field is type of ```java.util.Date```.
But when I modify the field to type of ```java.time.LocalDateTime```, properties doesn't works.

### Steps to Reproduce

1. build application
2. ```curl localhost:8080/hello```

### Actual Behaviour
```json
{
  "success": true,
  "data": {
    "localDateTime": "2020-06-15T16:07:58.793955",
    "date": "2020-06-15 16:07:58"
  }
}
```

### Environment Information

- **Operating System**: macOS 10.15.4
- **Micronaut Version:** 2.0.0.M3
- **JDK Version:** 11

**Comment by olejnikk** [comment]
I don't think it's a Micronaut issue. Property `jackson.date-format` maps to `setDateFormat(DateFormat dateFormat)` of Jackson's `ObjectMapper`, and `DateFormat` applies to pre-JSR310 time formats such as `java.util.Date`, `java.sql.Date` and `java.util.Calendar`.

Serializers and deserializers of "new" time formats are delivered with `jackson-datatypes-jsr310` (which is included by default in Micronaut) and `jackson-modules-java8`. 
You can use `@JsonFormat` on a field or create custom `JsonSerializer<LocalDateTime>` bean (e.g. Jackson's `LocalDateTimeSerializer` with pattern given) - both work fine in Micronaut.
