### ISSUE TITLE
ConcurrentModificationException from NettyMutableHttpResponse.getMessage()

### ISSUE THREAD

**Issue by KiranSathi** [micronaut-projects/micronaut-core#3537]
We are getting ConcurrentModificationException from NettyMutableHttpResponse while calling getMessage() method. Internally we are using LinkedHashMap and is not thread safe. Is this a known issue?

Following is the stack trace.

  "file": "HashMap.java",
  "method": "computeIfAbsent",
  "class": "java.util.HashMap",
  "line": 1134,
  "exact": false,
  "location": "?",
  "version": "?"
},
{
  "file": "NettyMutableHttpResponse.java",
  "method": "getBody",
  "class": "io.micronaut.http.netty.NettyMutableHttpResponse",
  "line": 146,
  "exact": false,
  "location": "product-store-position-api-1588876073.0.623-z45ad911.jar",
  "version": "?"
},
{
  "file": "HttpClientResponseException.java",
  "method": "getMessage",
  "class": "io.micronaut.http.client.exceptions.HttpClientResponseException",
  "line": 70,
  "exact": false,
  "location": "product-store-position-api-1588876073.0.623-z45ad911.jar",
  "version": "?"
}

Can we make convertedBodies Map in NettyMutableHttpResponse to concurrent Map?

**Comment by graemerocher** [comment]
Seems reasonable, want to send a PR?

**Comment by KiranSathi** [comment]
Sure. Will do.

**Comment by KiranSathi** [comment]
@graemerocher Raised PR https://github.com/micronaut-projects/micronaut-core/pull/3549. Please review.

**Comment by graemerocher** [comment]
Thanks for the PR
