### ISSUE TITLE
Json processing exception for double values when using request binding

### ISSUE THREAD

**Issue by vanga** [micronaut-projects/micronaut-core#3538]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
* Use micronaut request binding to convert incoming json body to a POJO.
* POJO is a wrapper to encapsulate top level properties of the request body and one of the property is of type `Map<String,Object>`
* Make a request with a large number as the value ex: `DoubleProperty: 17976931348623157580412819756850388593900235011794141176754562789180111453639664485361928830517704263393537268510363518759043843737070229269956251768752166883397940628862983287625967246810352023792017211936260189893797509826303293149283469713429932049693599732425511693654044437030940398714664210204414967808`
* Notice the error `Invalid JSON: Numeric value (17976931348623157580412819756850388593900235011794141176754562789180111453639664485361928830517704263393537268510363518759043843737070229269956251768752166883397940628862983287625967246810352023792017211936260189893797509826303293149283469713429932049693599732425511693654044437030940398714664210204414967808) out of range of long (-9223372036854775808 - 9223372036854775807)\n at [Source: UNKNOWN; line: 17, column: 340]`

### Expected Behaviour

I expect the value to be treated as double and not error out. When I include a decimal in the value `.0` at the end or use scientific notation (_E107_), it gets processed correctly. if I am using an injected ObjectMapper to convert the json instead of using the request binding, value gets processed even without the decimal at the end. I am not sure if this is expected or not, it seems inconsistent to me at-least. 
I asked in gitter and was pointed towards checking [JacksonProcessor](https://github.com/micronaut-projects/micronaut-core/blob/1.3.x/runtime/src/main/java/io/micronaut/jackson/parser/JacksonProcessor.java). I can see that the value is being recognised as `VALUE_NUMBER_INT`.
Is there any special configuration that needs to be set to have the default behaviour of json processing while using request binding recognise these numbers as valid numbers? Or is the expectation that clients have to send decimal precision?

### Actual Behaviour

Value gets processed as integer/long value and errors out

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 1.3.2
- **JDK Version:** JDK 11

**Comment by graemerocher** [comment]
I don't think that `Map<String, Object>` provides the type information needed to know this should be bound via BigDecimal binding

**Comment by vanga** [comment]
@graemerocher Thanks, I sort of agree, but it seems to be something that is not desired. I also don't know how jackson Objectmapper is able to convert it correctly (it only converts larger numbers to BigInteger). Do you think it is not expected that the micronaut request binding behaves in same way? Do you have any alternative suggestions on how to tackle this in micronaut natively?

**Comment by yawkat** [comment]
I would definitely count this as a bug, "arbitrary" deserialization to Object should use BigDecimal where necessary, and should never overflow.

However I can't reproduce this with 3.2.0, and knowing the deserialization code I think it should work, so I assume this was fixed since this was reported. Please reopen if that is not the case.
