### ISSUE TITLE
Implicit `@Named`

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-core#354]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create the following test

```
import io.micronaut.context.ApplicationContext
import io.micronaut.inject.qualifiers.Qualifiers
import spock.lang.Specification

import javax.inject.Singleton

class InjectSpec extends Specification {

    void 'qualifier by name works'() {
        given:
            ApplicationContext context = ApplicationContext.build().build()
            context.registerSingleton(HasName, new HasName("first"), Qualifiers.byName('first'))
            context.registerSingleton(HasName, new HasName("second"), Qualifiers.byName('second'))
            context.start()
        when:
            Injected bean = context.getBean(Injected)
        then:
            bean.toString() == 'first+second'
        cleanup:
            context.stop()
    }

}

class HasName {
    private final String name

    HasName(String name) {
        this.name = name
    }

    @Override
    String toString() {
        return name
    }
}

@Singleton
class Injected {

    private final HasName first
    private final HasName second

    Injected(HasName first, HasName second) {
        this.first = first
        this.second = second
    }


    @Override
    String toString() {
        return "$first+$second";
    }
}
```

### Expected Behaviour

The test passes because of the name of the constructor parameter is transferred to implicit `@Named` annotation. Or at least you should get some warning.

### Actual Behaviour

The test fails because the name of the parameter is ignored

**Comment by graemerocher** [comment]
Not sure this is really a bug, rather an enhancement request. The above will worked if you declared `@Named` on each argument

I think this may be one of those cases where if we implement this people will say it is too much magic

**Comment by musketyr** [comment]
Sure, I wasn't able to assign label. Isn't this how it works in Grails? That the name of the injected bean is important?

**Comment by graemerocher** [comment]
Yes, but Micronaut is not Grails or Spring. There are no bean names in Micronaut, only qualifiers.

**Comment by graemerocher** [comment]
also, your example would not work in Grails or Spring either, not for constructor injection anyway since injection by name in Spring and Grails only works for setters

**Comment by musketyr** [comment]
Ok, thanks for explanation.

**Comment by jameskleeh** [comment]
I don't think this is a good idea. I think this can introduce corner cases where it may not be obvious to the user what will happen

**Comment by musketyr** [comment]
Ok, I see. can we at least raise some compilation error when two same
arguments (by type) are injected?

Dne pá 6. čvc 2018 15:57 uživatel James Kleeh <notifications@github.com>
napsal:
