### ISSUE TITLE
Regression when switching from Micronaut 2.0.0.M3 to RC1/2 regarding execution of Spock tests with/without JUnit platform

### ISSUE THREAD

**Issue by dcmoeller** [micronaut-projects/micronaut-core#3550]
Switching from Micronaut 2.0.0.M3 to RC1/2 I found that my Spock test cases are NOT executed anymore.  

### Task List
To easier reproduce my observation, I have coined a completely new and simple project on [https://micronaut.io/launch/](https://micronaut.io/launch/) like this:
- Application Type: Application
- Java Version: 11
- Base Package: micronaut.test
- Name: spock-only-with-junit
- Micronaut Version: **2.0.0.RC2**
- Language: Java
- Build: Gradle
- Test Framework: **Spock**
- No further features

Downloading, extracting, and executing clean build shows expected behaviour:
```
$ ./gradlew clean build

BUILD SUCCESSFUL in 14s
13 actionable tasks: 12 executed, 1 up-to-date

$ ls build/test-results/test/
binary/
TEST-micronaut.test.SpockOnlyWithJunitSpec.xml
```

### Steps to Reproduce
1. In `build.gradle` we found JUnit platform referenced **although** only Spock framework is used for testing. So let's remove the following code block from `build.gradle`:
```
test {
  useJUnitPlatform()
}
```

2. But now, executing a clean build gives:
```
$ ./gradlew clean build

BUILD SUCCESSFUL in 5s
13 actionable tasks: 13 executed

$ ls build/test-results/test/
binary/

$ ls -s build/test-results/test/binary/
0  output.bin
4  output.bin.idx
0  results.bin
```
**No execution** of Spock test cases when removing JUnit platform from `build.gradle` (with Micronaut 2.0.0.RC2 - RC1 behaves the same)!

3. **Switching to Micronaut 2.0.0.M3**:
  - Edit `gradle.properties` to change from RC2 to M3
  - Edit `build.gradle` and add version `1.2.3` to `runtimeOnly` dependency like this: `runtimeOnly("ch.qos.logback:logback-classic:1.2.3")`

4. Now with a clean build the Spock test cases are executed again (and **without** JUnit platform):
```
$ ./gradlew clean build

> Task :compileJava
warning: The following options were not recognized by any processor: '[micronaut.processing.module, micronaut.processing.group]'
1 warning

> Task :compileTestGroovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass [...]

> Task :test
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass [...]

BUILD SUCCESSFUL in 7s
13 actionable tasks: 13 executed

$ ll build/test-results/test/
binary/
TEST-micronaut.test.SpockOnlyWithJunitSpec.xml
```

### Expected Behaviour

So, is this "regression" by intention?  
To me it was surprising (and requires a lot of time to nail down the root cause - missing JUnit platform - of why my Spock tests are NOT executed when switching from M3 to RC1/2) to see JUnit plaform is required although only Spock framework is used.

### Actual Behaviour

Switching from Micronaut 2.0.0.M3 to RC1/2, to get Spock tests executed JUnit platform is required to be active, even though no single JUnit test case is present.

### Environment Information

- **Operating System**: Ubuntu 18.04
- **Micronaut Version:** 2.0.0.M3, RC1, RC2
- **JDK Version:**
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
```

**Comment by dcmoeller** [comment]
> It is not a regression, Micronaut 2.0 uses Groovy 3 and Spock 2 by default which is based off of JUnit platform. If you wish to continue to use Spock 1.3.x you must explicitly declare that version in your build and also explicitly downgrade back to Groovy 2.5.x.

Didn't get your point: In my original business project, I switched from Micronaut 2.0.0.M3 to RC1 (and later to RC2) stumbling over the described observation: Obligation to add `useJUnitPlatform()` instruction to `build.gradle` to get Spock tests executed. So to me it was not my intention to up/downgrade Groovy/Spock dependencies.

**Comment by graemerocher** [comment]
Micronaut 2.0.0.M3 did not include the upgrade to Groovy 3 / Spock 2 hence why you did not observe the problem there.

Spock 2 drops support for JUnit 4 and legacy test runner and replaces it with JUnit 5 platform. See https://solidsoft.wordpress.com/2020/01/02/migrating-spock-1-3-tests-to-spock-2-0/

By using the Micronaut BOM you inherit the third party dependencies that Micronaut defaults to. In Micronaut 2.0 this is Spock 2/Groovy 3 so whilst you did not explicitly upgrade by uprading to Micronaut 2.0 you have done so.

If this is confusing for you can always remove the micronaut bom from your dependencies and declare versions explicitly

**Comment by dcmoeller** [comment]
OK, thanks for clarification :-)
