### ISSUE TITLE
Distribute micronaut in Homebrew

### ISSUE THREAD

**Issue by gastaldi** [micronaut-projects/micronaut-core#356]
Homebrew is a very popular package manager. It would be nice to have a `brew install micronaut`

**Comment by luolong** [comment]
For more information about how to create/publish homebrew packages see https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by graemerocher** [comment]
@luolong There is a PR here https://github.com/Homebrew/homebrew-core/pull/29807 although so far it hasn't got any attention from the homebrew maintainers.

**Comment by gastaldi** [comment]
Homebrew PR merged.

**Comment by graemerocher** [comment]
Great! So to update to M4 what is the process? We send them a pull request with the change?

**Comment by gastaldi** [comment]
@graemerocher yes, just provide a PR changing the same file and that should be it ;)
