### ISSUE TITLE
How does micronaut 2 incremental annotation processing work? 

### ISSUE THREAD

**Issue by LifeIsStrange** [micronaut-projects/micronaut-core#3574]
I was reading the fantastic micronaut 2.0 changelog when I stumbled upon this:

*Micronaut supports Gradle incremental annotation processing which helps speed up builds by compiling only classes that have changed avoiding a full recompilation.*
It is also said to be supported for Kotlin (so using KAPT) 
(while it is opt-in because of the rare use case of custom meta annotations it does not matter in the following discussion)

The Gradle documentation say:
*They must not depend on com.sun.source.util.Trees compiler-specific APIs like . Gradle wraps the processing APIs, so attempts to cast to compiler-specific types will fail. If your processor does this, it cannot be incremental, unless you have some fallback mechanism.*

Spring boot show to every kotlin user a warning when enabling incremental annotation processing. 
I even made an issue about it https://github.com/gradle/gradle/issues/12855

So my question is: how did you achieve to not need com.sun.source.util.Trees compiler-specific APIs? Especially since I believe that you use some spring libraries such as optionally for transaction/repository support.

**Comment by jameskleeh** [comment]
Please ask questions in [Gitter](https://gitter.im/micronautfw)
