### ISSUE TITLE
OpenAPI TypeElementVisitor.finish() is called multiple times with micronaut 2.0

### ISSUE THREAD

**Issue by croudet** [micronaut-projects/micronaut-core#3575]
### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create a simple project with openapi with https://micronaut.io/launch/
2. Add some openapi annotations

### Expected Behaviour

OpenApi `TypeElementVisitor.finish()` is called once.

### Actual Behaviour

OpenAPI `TypeElementVisitor.finish()` is called 3 times:
```
$ ./gradlew clean compileJava

> Task :compileJava
Note: Generating OpenAPI Documentation
Note: Writing OpenAPI YAML to destination: E:\workspace\hello\build\classes\java\main\META-INF\swagger\hello-0.0.yml
Note: Creating bean classes for 1 type elements
Note: Writing OpenAPI YAML to destination: E:\workspace\hello\build\classes\java\main\META-INF\swagger\hello-0.0.yml
Note: Writing OpenAPI YAML to destination: E:\workspace\hello\build\classes\java\main\META-INF\swagger\hello-0.0.yml

BUILD SUCCESSFUL in 14s
2 actionable tasks: 2 executed
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.0.0
- **JDK Version:** OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14.0.1+7, mixed mode, sharing)

### Example Application

- https://github.com/croudet/micronaut-2.0-bug

**Comment by graemerocher** [comment]
So I think the reason for this behaviour is so introspections can be added to classes generated by another annotation processor. 

But it causes regression tests to fail https://github.com/micronaut-projects/micronaut-core/runs/841052810?check_suite_focus=true

So I think the  correct fix is the one you applied to OpenAPI visitor.
