### ISSUE TITLE
openssl command in guide is wrong

### ISSUE THREAD

**Issue by Vorlent** [micronaut-projects/micronaut-core#3606]
https://docs.micronaut.io/latest/guide/index.html#_using_a_valid_x509_certificate

### Steps to Reproduce

https://docs.micronaut.io/latest/guide/index.html#_using_a_valid_x509_certificate
```
$ openssl pkcs12 -export \
                 -in server.crt \ 
                 -inkey server.key \ 
                 -out server.p12 \ 
                 -name someAlias \ 
                 -CAfile ca.crt -caname root
$ openssl pkcs12 -info -in server.p12
```

### Expected Behaviour

The certificate should contain intermediate certificates inside of ca.crt. What's missing is the -chain flag that will actually add the intermediates.

The command should look something like this.
```
$ openssl pkcs12 -export \
                 -in server.crt \ 
                 -inkey server.key \ 
                 -out server.p12 \ 
                 -name someAlias \ 
                 -chain -CAfile ca.crt -caname root
```

### Actual Behaviour

No intermediate certificates in the .p12 file. Just the server.key and server.crt file.
Curl and other low level libraries will complain about missing intermediate certificates.
Browsers don't complain presumably because they cache intermediate certificates.

**Comment by graemerocher** [comment]
Thanks, would you consider sending a PR?

**Comment by Vorlent** [comment]
Here's the PR.
