### ISSUE TITLE
Support routing by query parameters

### ISSUE THREAD

**Issue by chrylis** [micronaut-projects/micronaut-core#3608]
When writing an HTTP request mapping, it is often very useful to match on the presence of query parameters; for example, `/books?author=` and `/books?character=`. Spring MVC supports this with the `params` parameter of the `@RequestMapping`, but Micronaut currently only supports a singleton endpoint per path-without-query-parameters.

This is a feature request to support matching based on the presence of query parameters.

**Comment by graemerocher** [comment]
Does the following not serve this purpose?:

```
@Get("/books?author={author}") 
```

**Comment by spencercjh** [comment]
I think it will lead to confusions.

**Comment by jameskleeh** [comment]
I vote to close. The route matching logic is likely already a contributing factor to response time and this would cause it to perform worse.

**Comment by chrylis** [comment]
@graemerocher: No, it doesn't. Micronaut does not support routing the request `/books` (no parameter) and `/books?author={author}` to different controller methods (or any other conditional-on-parameter dispatch). If two mappings `@Get("/books")` and `@Get("/books?author={author}")` are both defined, Micronaut will report that both mappings are added and will not complain, but it does not use the query parameter in routing. (This seems like _buggy_ rather than simply less-featured behavior to me.)

```
20:51:41.389 [main] DEBUG i.m.web.router.DefaultRouteBuilder - Created Route: GET /books?author={author} -> $BookControllerDefinition$Intercepted#io.micronaut.context.DefaultBeanContext$4@5c09d180 (application/json )
20:51:41.389 [main] DEBUG i.m.web.router.DefaultRouteBuilder - Created Route: HEAD /books?author={author} -> $BookControllerDefinition$Intercepted#io.micronaut.context.DefaultBeanContext$4@23aae55 (application/json )
20:51:41.389 [main] DEBUG i.m.web.router.DefaultRouteBuilder - Created Route: GET /books -> $BookControllerDefinition$Intercepted#io.micronaut.context.DefaultBeanContext$4@5f574cc2 (application/json )
20:51:41.389 [main] DEBUG i.m.web.router.DefaultRouteBuilder - Created Route: HEAD /books -> $BookControllerDefinition$Intercepted#io.micronaut.context.DefaultBeanContext$4@680bddf5 (application/json )
...
20:52:17.465 [nioEventLoopGroup-1-3] DEBUG i.m.h.server.netty.NettyHttpServer - Server localhost:8080 Received Request: GET /books?author=Tom%20Clancy
20:52:17.466 [nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matching route GET - /books
20:52:17.466 [nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matched route GET - /books to controller class co.vendorflow.sandbox.graph.$BookControllerDefinition$Intercepted
2
```

This means that _any_ variation in query parameters has to be handled by Express-style inline `if` trees instead of declaratively.

Being able to route by the presence or absence (or value) of a parameter _should_ be cheap (just a `containsKey` lookup), its expression as an annotation value of `params={"author"}` is not the slightest bit ambiguous, and if the condition isn't applied it shouldn't add any even trivial performance impact.

**Comment by chrylis** [comment]
@graemerocher: No, it doesn't. Micronaut does not support routing the request `/books` (no parameter) and `/books?author={author}` to different controller methods (or any other conditional-on-parameter dispatch). If two mappings `@Get("/books")` and `@Get("/books?author={author}")` are both defined, Micronaut will report that both mappings are added and will not complain, but it does not use the query parameter in routing. (This seems like _buggy_ rather than simply less-featured behavior to me.)

```
20:51:41.389 [main] DEBUG i.m.web.router.DefaultRouteBuilder - Created Route: GET /books?author={author} -> $BookControllerDefinition$Intercepted#io.micronaut.context.DefaultBeanContext$4@5c09d180 (application/json )
20:51:41.389 [main] DEBUG i.m.web.router.DefaultRouteBuilder - Created Route: HEAD /books?author={author} -> $BookControllerDefinition$Intercepted#io.micronaut.context.DefaultBeanContext$4@23aae55 (application/json )
20:51:41.389 [main] DEBUG i.m.web.router.DefaultRouteBuilder - Created Route: GET /books -> $BookControllerDefinition$Intercepted#io.micronaut.context.DefaultBeanContext$4@5f574cc2 (application/json )
20:51:41.389 [main] DEBUG i.m.web.router.DefaultRouteBuilder - Created Route: HEAD /books -> $BookControllerDefinition$Intercepted#io.micronaut.context.DefaultBeanContext$4@680bddf5 (application/json )
...
20:52:17.465 [nioEventLoopGroup-1-3] DEBUG i.m.h.server.netty.NettyHttpServer - Server localhost:8080 Received Request: GET /books?author=Tom%20Clancy
20:52:17.466 [nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matching route GET - /books
20:52:17.466 [nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matched route GET - /books to controller class co.vendorflow.sandbox.graph.$BookControllerDefinition$Intercepted
2
```

This means that _any_ variation in query parameters has to be handled by Express-style inline `if` trees instead of declaratively.

Being able to route by the presence or absence (or value) of a parameter _should_ be cheap (just a `containsKey` lookup), its expression as an annotation value of `params={"author"}` is not the slightest bit ambiguous, and if the condition isn't applied it shouldn't add any even trivial performance impact.

**Comment by chrylis** [comment]
@graemerocher: No, it doesn't. Micronaut does not support routing the request `/books` (no parameter) and `/books?author={author}` to different controller methods (or any other conditional-on-parameter dispatch). If two mappings `@Get("/books")` and `@Get("/books?author={author}")` are both defined, Micronaut will report that both mappings are added and will not complain, but it does not use the query parameter in routing. (This seems like _buggy_ rather than simply less-featured behavior to me.)

```
20:51:41.389 [main] DEBUG i.m.web.router.DefaultRouteBuilder - Created Route: GET /books?author={author} -> $BookControllerDefinition$Intercepted#io.micronaut.context.DefaultBeanContext$4@5c09d180 (application/json )
20:51:41.389 [main] DEBUG i.m.web.router.DefaultRouteBuilder - Created Route: HEAD /books?author={author} -> $BookControllerDefinition$Intercepted#io.micronaut.context.DefaultBeanContext$4@23aae55 (application/json )
20:51:41.389 [main] DEBUG i.m.web.router.DefaultRouteBuilder - Created Route: GET /books -> $BookControllerDefinition$Intercepted#io.micronaut.context.DefaultBeanContext$4@5f574cc2 (application/json )
20:51:41.389 [main] DEBUG i.m.web.router.DefaultRouteBuilder - Created Route: HEAD /books -> $BookControllerDefinition$Intercepted#io.micronaut.context.DefaultBeanContext$4@680bddf5 (application/json )
...
20:52:17.465 [nioEventLoopGroup-1-3] DEBUG i.m.h.server.netty.NettyHttpServer - Server localhost:8080 Received Request: GET /books?author=Tom%20Clancy
20:52:17.466 [nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matching route GET - /books
20:52:17.466 [nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matched route GET - /books to controller class co.vendorflow.sandbox.graph.$BookControllerDefinition$Intercepted
2
```

This means that _any_ variation in query parameters has to be handled by Express-style inline `if` trees instead of declaratively.

Being able to route by the presence or absence (or value) of a parameter _should_ be cheap (just a `containsKey` lookup), its expression as an annotation value of `params={"author"}` is not the slightest bit ambiguous, and if the condition isn't applied it shouldn't add any even trivial performance impact.
