### ISSUE TITLE
Micronaut not able to process consecutive http/2 POST requests

### ISSUE THREAD

**Issue by sandeep14-singh** [micronaut-projects/micronaut-core#3618]
Issue:
We are using Micronaut-2 to have a HTTP/2 server. When we are trying to send multiple POST, the first one gets processed and the second one fails because Micronaut seems to close the connection.
We have tried sending POST request from Vertx client (and later tried with Jetty client as well)  and micronaut is only able to process the first request. 
We suspected first to be an issue with Vertx client and we raised an issue(https://github.com/eclipse-vertx/vert.x/issues/3471) but they have clarified that its not a Vertx client issue, its something wrong with the server.

### Steps to Reproduce
1. Kindly pull the code : git clone https://github.com/sandeep14-singh/vertxpoc.git
2. Open the project "vertxpoc" in intellij. Under the project, open "Application" class and run it. This will bring up a HTTP/2 enabled server : https://localhost:8443. We are using Micronaut framework, which brings up the server with self signed certificate.
3. Open VertxGetClient class and run it. This class sends 2 GET requests and they get processed all fine -- this is good enough.
4. Open VertxPostClient class and run it. This class sends 2 POST requests and the first one gets processed but the second one does not. We get  below on client side:
Jul 01, 2020 7:31:01 AM io.vertx.core.http.impl.HttpClientRequestImpl
SEVERE: io.vertx.core.VertxException: Connection was closed

And we receive below on server side :
DEBUG io.micronaut.context.DefaultBeanContext - Resolving beans for type: <HttpRequestTerminatedEvent> io.micronaut.context.event.ApplicationEventListener 
09:27:56.992 [nioEventLoopGroup-1-4] ERROR io.micronaut.http.server.netty.RoutingInBoundHandler - Micronaut Server Error - No request state present. Cause: refCnt: 0, decrement: 1
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1

5. [This is optional step, if you want to reproduce issue with Jetty client] We have also tried Jetty client but over there also, its the same issue. Running Jetty client on various jdk8 versions requires specific versions of alpn. For example, i was using openjdk-1.8.0_222 and with this jdk version, i needed to have "compile group: 'org.eclipse.jetty', name: 'jetty-alpn-openjdk8-client', version: '9.4.30.v20200611'" in the build.gradle and also needed to download alpn-boot-8.1.13.v20181017.jar and specify 
-Xbootclasspath/p:/home/vagrant/stuff/jars/alpn-boot-8.1.13.v20181017.jar  in VM args. After this, i ran JettyHighLevelPostClient. If you want to test this issue with Jetty as well and you have some other jdk8 version, then  
pls configure the corresponding alpn for it by referring to https://www.eclipse.org/jetty/documentation/current/alpn-chapter.html. After this, you can also run JettyHighLevelPostClient

### Expected Behaviour
I would expect Micronaut to be able to serve multiple POST requests on a single HTTP/2 connection

### Actual Behaviour
Micronaut-2 is not able to process consecutive http/2 POST requests

### Environment Information

- **Operating System**: Ubuntu 18.04.3 LTS
- **Micronaut Version:** 2.0.0
- **JDK Version:** openjdk-1.8.0_222

### Example Application
Link - https://github.com/sandeep14-singh/vertxpoc.git
Please refer to "Steps to Reproduce" to see how issue can be reproduced from this code

**Comment by sandeep14-singh** [comment]
Kindly review this issue as its a blocker for us. We are not able to send multiple POST requests on a single HTTP/2 connection at all.

**Comment by graemerocher** [comment]
It has been scheduled

**Comment by graemerocher** [comment]
Curiously the problem doesn't occur when using the Micronaut HTTP client. Still researching...

**Comment by sandeep14-singh** [comment]
> Curiously the problem doesn't occur when using the Micronaut HTTP client. Still researching...

Thanks @graemerocher for having look on it. Yea, we have not tried with Micronaut's OOB client yet because the clients of our service have their own choice such as Vertx/Jetty etc.

But pls let us know if and when you get some finding/workaround or if you see any configuration issue with our code.
