### ISSUE TITLE
JdbcIndicator not working when connection is down

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#362]
The JdbcIndicator as written will not work if the connection is down. The `DataSource` instances fail to inject resulting the indicator never being loaded and not being able to reproduce health status.

The `/health` endpoint the reports a 500 error without the status:

```
{
"message":
"Internal Server Error: Failed to inject value for parameter [datasourceConfiguration] of class: org.apache.tomcat.jdbc.pool.DataSource\n\nPath Taken: new HealthEndpoint(HealthAggregator healthAggregator,[HealthIndicator[] healthIndicators],HealthLevelOfDetailResolver healthLevelOfDetailResolver) --> new JdbcIndicator(ExecutorService executorService,[DataSource[] dataSources],HealthAggregator healthAggregator) --> new DataSource([DatasourceConfiguration datasourceConfiguration])"
}
```

**Comment by jameskleeh** [comment]
@graemerocher I can't reproduce this. I created an app with `-lang groovy`, then added the following dependencies:

```
    compile "io.micronaut.configuration:jdbc-tomcat"
    runtime "mysql:mysql-connector-java:5.1.46"
    runtime "io.micronaut:management"
```

And modified configuration to add: 
```
datasources:
    default:
        url: jdbc:mysql://localhost/test
        username: sa
        password: ""
```

When I visit the health endpoint I see the status is down, however it returns a 200 status. The mysql exception is logged to the console

**Comment by jameskleeh** [comment]
@graemerocher Any additional info you can provide so I can reproduce?

**Comment by graemerocher** [comment]
If I recall it was with Postgres, but can't remember now. If you can't reproduce maybe we just close it
