### ISSUE TITLE
Cannot create a http client with no base url

### ISSUE THREAD

**Issue by JamesPace-GBI** [micronaut-projects/micronaut-core#3625]
As requested per https://gitter.im/micronautfw/questions?at=5efe226de73f7169498693b0

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Try to create a http client with a null url i.e. `HttpClient.create(null);`

### Expected Behaviour

A http client with no base url is returned.

### Actual Behaviour

A null pointer exception is thrown.

### Stack Trace

```
java.lang.NullPointerException
	at io.micronaut.http.client.loadbalance.FixedLoadBalancer.<init>(FixedLoadBalancer.java:43)
	at io.micronaut.http.client.LoadBalancer.fixed(LoadBalancer.java:56)
	at io.micronaut.http.client.DefaultHttpClient.<init>(DefaultHttpClient.java:363)
	at io.micronaut.http.client.RxHttpClient.create(RxHttpClient.java:95)
```

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 1.3.6
- **JDK Version:** 11

**Comment by graemerocher** [comment]
You should just use `@Inject RxHttpClient client` to create a client in the meantime

**Comment by JamesPace-GBI** [comment]
Thanks for the help and the prompt fix @jameskleeh 👏
