### ISSUE TITLE
Health issue

### ISSUE THREAD

**Issue by akozel** [micronaut-projects/micronaut-core#363]
Test case:
1. Run micronaut with mongodb
2. get /health. See status ("status": "UP")
3. Get mongodb down. While it shooting down see ("status": "DOWN")
4. But when it did there are endless loading

Also one more wish:
Let /health be detailed with separate dependencies (not only general status). like:
{
"status": "DOWN",
"mongodb": "UP",
"mongodb-external": "DOWN",
"postgres": "UP",
"rabbitmq": "UP"
}

**Comment by graemerocher** [comment]
This was resolved by 43b07b801adf739eea265f54744e29d9e5bcba36

It does hang a little bit, but we have to have some kind of timeout handling

**Comment by akozel** [comment]
but what about separate output for each indicator?

**Comment by graemerocher** [comment]
that is already possible, but the `health` endpoint is sensitive by default so you have to set `endpoints.health.sensitive=false`
