### ISSUE TITLE
Property List is not converted correctly in Micronaut 2.0.0

### ISSUE THREAD

**Issue by tom59** [micronaut-projects/micronaut-core#3634]
Lists are not converted correctly in micronaut 2.0.0.
It is a regression of micronaut 2 as it is working fine on 1.3.6.

For a yaml file:
````
whitelist:
  scope:
    - aUserName
    - aUserName2
````

Expected Behaviour
getProperty("whitelist") should be: Map.of("scope", asList("aUserName", "aUserName2"))

Actual Behaviour
getProperty("whitelist") is: Map.of("scope[0]", "aUserName", "scope[1]", "aUserName2", "scope", asList("aUserName", "aUserName2"))

Environment Information
Operating System: Mac
Micronaut Version: 2.0.0
JDK Version: 11
Example Application
https://github.com/tom59/micronaut-property-issue

**Comment by jameskleeh** [comment]
You can achieve the desired behavior with 'applicationContext.getProperties("whitelist", StringConvention.RAW)'
