### ISSUE TITLE
Nested Argument.listOf do not deserialize to the correct type

### ISSUE THREAD

**Issue by nickpalladino** [micronaut-projects/micronaut-core#3638]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Make a request with the RxHttpClient that has a deserialized type of nested lists such as `<List<List<Event>>` using Argument.listOf as shown below:

```
Flowable<HttpResponse<List<List<Event>>>> call = client.exchange(
                POST(QUERY_ENDPOINT, request).contentType(MediaType.APPLICATION_JSON),
                Argument.listOf(Argument.listOf(Event.class).getType())
        );
```

### Expected Behaviour

Expected behavior is to get a `List<List<Event>>`

### Actual Behaviour

Actual behavior is getting a `List<List<LinkedHashMap>>` without any errors being indicated.

### Environment Information

- **Operating System**: Ubuntu 18.04.4 LTS
- **Micronaut Version:** 2.0.0
- **JDK Version:** 13

### Example Application

Example included in issue.

**Comment by jameskleeh** [comment]
The issue is with how you're using `Argument.listOf`. `Argument.listOf(Event.class).getType()` will return `List`, thus the type parameter `Event` is not part of the equation. I've modified `Argument.listOf` to accept an `Argument`, so you can do `Argument.listOf(Argument.listOf(Event.class))`.

**Comment by nickpalladino** [comment]
Cool, thanks!
