### ISSUE TITLE
It appears the datasources.*.dialect parameter doesn't do anything Micronaut 2.0.0

### ISSUE THREAD

**Issue by pfrank13** [micronaut-projects/micronaut-core#3640]
It appears the datasources.*.dialect parameter doesn't do anything Micronaut 2.0.0. I was forced to hardcode the dialect in the dialect parameter of the @JdbcRepository to get proper SQL generation against MySQL

### Steps to Reproduce

Failure
1. Checkout this tag `git clone --branch hardcoded_dialect_required https://github.com/pfrank13/java-serverless.git`
2. Execute: `./gradlew --debug clean test`
3. Notice in the stack trace `Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"book" ("name","isbn") VALUES ('Building Microservices-726629857685286834','3a2a' at line 1` or something approximating that. The quoting is not MySQL complaint (backticks is the mysql way)

Passing
1. Go to `BookRepository` and uncomment out the dialect in @JdbcRepository (so hardcoding it)
2. Execute: `./gradlew clean test`
3. Notice it passes

### Expected Behaviour

The dialect parameter in `application.yml` should be used.

### Actual Behaviour

The dialect parameter in `application.yml` appears to be ignored

### Environment Information

- **Operating System**: macOS Mojava
- **Micronaut Version:** 2.0.0
- **JDK Version:** 11.0.7

### Example Application

`git clone --branch hardcoded_dialect_required https://github.com/pfrank13/java-serverless.git`
The pertinent test is `MySqlDialectFailureTest` and it is using a MySQL Docker Container to test this. It's automagically bootstrapped via the custom JdbcUrl and Driver in application.yml.

**Comment by croudet** [comment]
I think there is no `dialect` property in datasource.
https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc

**Comment by pfrank13** [comment]
I'll try and find where I saw that cause I sure as hell didn't make that up haha. When I find it I'll link it. However, I'd prefer not to hardcode this in the code so is there another mechanism in which to do this properly?

**Comment by pfrank13** [comment]
Seems `io.micronaut.data.jdbc.config.DataJdbcConfiguration` mentions this
```
@EachProperty(value = DataJdbcConfiguration.PREFIX, primary = "default")
public class DataJdbcConfiguration implements Named {
    /**
     * The prefix to use.
     */
    public static final String PREFIX = "datasources";
...
    /**
     * @return The dialect to use.
     */
    public Dialect getDialect() {
        return dialect;
    }

    /**
     * Sets the dialect.
     * @param dialect The dialect
     */
    public void setDialect(Dialect dialect) {
        this.dialect = dialect;
    }
```

**Comment by pfrank13** [comment]
Found it https://micronaut-projects.github.io/micronaut-data/latest/guide/#buildConfig, scroll down a bit you'll see this block
```
datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
```

**Comment by graemerocher** [comment]
Dialect is only used to customize the generated schema and for pagination. Since the queries to execute are computed at compilation time we need to know the dialect ahead of time to efficiently generate these.

**Comment by pfrank13** [comment]
@graemerocher So using say H2 for tests and MySQL in Prod isn't supported? I read somewhere Micronaut scans the classpath for figuring out the dialect, so is maybe this bug in how that works? My estimation is H2 being on the testRuntimeOnly classpath is what Micronaut is actually compiling down to but perhaps I'm wrong. Thanks!

**Comment by graemerocher** [comment]
@pfrank13 Since H2 and MySQL are different databases it is not a great setup to use a different one for testing vs production. You should use test containers with MySQL which is much better. For an example of how to set this up go to https://micronaut.io/launch/ and choose the MySQL feature which sets up test containers for the test environment by default
