### ISSUE TITLE
Slow startup (k8s) over 10min.

### ISSUE THREAD

**Issue by forbi** [micronaut-projects/micronaut-core#3658]
### Steps to Reproduce

App with 1 Contorller and 1 Client
Enabled metrics with prometheus

### Expected Behaviour

few seconds

### Actual Behaviour

over 10min startup

### Environment Information

- **Operating System**: k8s
- **Micronaut Version:** latest
- **JDK Version:** 11 openj9 / jre-alpine

[Log](https://filebin.net/jua8de702l33ntgk/asd.log?t=ibq0bt1u)

I don't know if its theamount of env variables that picks from k8s or what.

I tries multiple configurations, disabled env detection, forced to k8s env, etc. The result is always the same.

Edit: And doing kubectl top pod...
I get **900m** and **400Mi** (and keeps rising..) 

Edit: Running the docker image works just fine (1.5seg)

**Comment by alvarosanchez** [comment]
Is this running in a cloud provider? If so, which one?

Can you share an application that reproduces the issue?

**Comment by forbi** [comment]
@alvarosanchez no, it's running on our own k8s.

Here is a example of the project: https://github.com/forbi/slow-mn

**Comment by forbi** [comment]
After some hours I realized that this only happens when I use the openj9 vm, If I switch to hotspot it work as intended.

**Comment by graemerocher** [comment]
Think it may be worth looking at https://docs.micronaut.io/latest/api/io/micronaut/context/ApplicationContextBuilder.html#environmentVariableIncludes-java.lang.String...-

Since it seems you have thousands of environment variables in your k8s cluster. You should set to this to only the environment variables your app needs to read otherwise all will be processed.

**Comment by forbi** [comment]
@graemerocher Sure, can you provide an example?

Btw, what about the fact that with hotstop it works just fine?

**Comment by graemerocher** [comment]
That is more a question for the OpenJ9 people

**Comment by graemerocher** [comment]
In terms of an example. Something like:

```java
  public static void main(String[] args) {
    Micronaut.builder()
                    .environmentVariableIncludes("FOO", "BAR")
                    .start();
  }
```

**Comment by forbi** [comment]
```java
  public static void main(String[] args) {
    Micronaut.build(args)
            .mainClass(Application.class)
            .environmentVariableIncludes()
            .start();
  }
```
I tried that one, but the env variables are processed anyways.

**Comment by graemerocher** [comment]
You need at least one specified

**Comment by forbi** [comment]
That worked. But it had no impact on the startup (on hotspot), so loading env variables is no problem at all. 

The biggest problem is that j9 works erratically on k8s (intensive CPU and RAM usage). Latter I'll try with jdk j9 13/14.

I guess we can close this issue.
