### ISSUE TITLE
management endpoints on grpc sever

### ISSUE THREAD

**Issue by SushmaReddyLoka** [micronaut-projects/micronaut-core#3664]
If I use grpc server and disable netty server by following steps given @ https://micronaut-projects.github.io/micronaut-grpc/snapshot/guide/index.html#server

"If you wish to use GRPC standalone without the Micronaut HTTP server you should comment out the micronaut-http-server-netty dependency." , how will the management endpoints be served ? 
  
Are the management endpoints served by same http server which will be used hosting application endpoints given that port of endpoints is not changed?  What happens when port in endpoints config. is customized to some other value than the one given under micronaut http server ?

**Comment by graemerocher** [comment]
The management endpoints require the `micronaut-http-server-netty` (or some server) so you cannot disable it if you require them exposed. The statement `given that port of endpoints is not changed? ` is incorrect, in Micronaut 2.0 you can change the port using `endpoints.all.port`

**Comment by SushmaReddyLoka** [comment]
Thanks for answering. 
My question was "Say that I haven't changed port of management endpoints, then will the management endpoints get served by same http server which will be used hosting application endpoints . And What happens when port in endpoints config. is customized to some other value using endpoints.all.port , than the one given under micronaut http server ?

**Comment by graemerocher** [comment]
answer is yes, they will be served on the same port. If you supply config you will have 2 ports exposed one for the app one for the endpoints

**Comment by SushmaReddyLoka** [comment]
Do we have management endpoints implementation on grpc server ? Any chance of building it in future ?

**Comment by SushmaReddyLoka** [comment]
If i have my micronaut application with both grpc server for app end points and micronaut http server running for management endpoints, will it cause any problems ? in terms of performance or any other resource utilization ? or any other issues ?

**Comment by SushmaReddyLoka** [comment]
@graemerocher , can you please answer above questions.

**Comment by graemerocher** [comment]
No it won't cause problems

**Comment by SushmaReddyLoka** [comment]
Any specific version i should use for this support ?
