### ISSUE TITLE
annotationProcessor doesn't create synthetic classes `*Definition.class` etc for only inherited annotations

### ISSUE THREAD

**Issue by nhoughto** [micronaut-projects/micronaut-core#3674]
# Steps to Reproduce

1. Create a simple controller, 'UserController.java' that implements and interface 'UserApi.java', the interface holds the @Controller and @Get etc annotations, the implementation 'UserController' only implements the interface methods, it has no micronaut annotations.
2. Run a `gradle build`

### Expected Behaviour

Expect a `UserControllerDefinition.class` and friends to be generated so micronaut at runtime can introspect and use the route definitions in RouteBuilder.

### Actual Behaviour

No synthetic classes are generated for `UserController` in this example, even though it implements an interface that does have micronaut annotations, this means that the class/@Controller is ignored at runtime, obviously no errors or warning is generated as it is just ignored/missing.

Adding any form of micronaut annotation to 'UserController' solves the problem and all the annotations, inherited or otherwise are detected, the UserController is detected and configured via RouteBuilder and is callable via HTTP.

### Environment Information

- **Operating System**: macOS 10.15
- **Micronaut Version:** 2.0.0
- **JDK Version:** 14.0.1

### Example Application

https://github.com/nhoughto/micronaut-annotation-repro

**Comment by jameskleeh** [comment]
This is by design. We don't assume that because a class inherits from one that has bean annotations that it is also a bean
