### ISSUE TITLE
Improve javadoc for attach method on Streamed/SystemFile

### ISSUE THREAD

**Issue by debuglevel** [micronaut-projects/micronaut-core#3701]
In `StreamedFile` and `SystemFile` there is a function `attach(String attachmentName)`:
https://github.com/micronaut-projects/micronaut-core/blob/b5cc40ea85d020d875f5a95e570188d4a47890a1/http-server/src/main/java/io/micronaut/http/server/types/files/StreamedFile.java#L119-L128

At least, I think the javadoc in conjunction with the function name might be misleading. I understood it something like "use this function to attach a file. Probably pass the file path as argument."

But as far as I see, `attachmentName` is only used in `process()` which only sets the filename which is exposed to the HTTP client:
https://github.com/micronaut-projects/micronaut-core/blob/b5cc40ea85d020d875f5a95e570188d4a47890a1/http-server/src/main/java/io/micronaut/http/server/types/files/StreamedFile.java#L130-L135

I suggest to change at least the javadoc, e.g.: (feel free to use something better)
```
    /**
     * Sets the filename of the attachment which is sent in the Content-Disposition HTTP header.
     *
     * @param attachmentName The name of the attachment to be used in the HTTP header.
     * @return The same StreamedFile instance
     */
```

Furthermore I wonder if the function name `attach()` actually does a good job in describing what is happening in there. I would expect `setName()`or the like. (But that would result in an API change, @Deprecated and so on.)

**Comment by jameskleeh** [comment]
@debuglevel This is certainly subjective, but I'm not opposed to making the javadoc more explicit. 

Something like this seems reasonable to me:
"Sets the file to be downloaded as an attachment. The name is set in the Content-Disposition header"

PRs welcome
