### ISSUE TITLE
micronaut-inject writes on stderr by default

### ISSUE THREAD

**Issue by ogregoire** [micronaut-projects/micronaut-core#3702]
Micronaut's documentation says:

> Note that the IoC part of Micronaut can be used completely independently of Micronaut itself for whatever application type you may wish to build. To do so all you need to do is configure your build appropriately to include the `micronaut-inject-java` dependency as an annotation processor.

So I did just that. But doing so adds slf4j message errors on stderr. I don't want to use slf4j. I don't want to use any logging framework.

By default I shouldn't have any error messages for just a basic application. If I wanted a logging mechanism, I'd expect to have to add an additional dependency. Not to spend time reading how to disable a logging framework and add another extra dependency.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an application with only `micronaut-inject-java` as dependency, as said in the doc
2. Run the app

### Expected Behaviour

See nothing on `stderr`.

### Actual Behaviour

The following message appears on `stderr`:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

### Environment Information

- **Operating System**: Windows
- **Micronaut Version:** 2.0.0
- **JDK Version:** 11

### Example Application

```
import io.micronaut.context.BeanContext;
import javax.inject.Singleton;

public class Main {
	public static void main(String[] args) {
		BeanContext beanContext = BeanContext.run();
		Greeter greeter = beanContext.getBean(Greeter.class);
		greeter.greet();
	}

	interface Greeter {
		void greet();
	}

	@Singleton
	class HelloWorld implements Greeter {
		@Override
		public void greet() {
			System.out.println("Hello, World!");
		}
	}
}
```

**Comment by croudet** [comment]
http://www.slf4j.org/codes.html#StaticLoggerBinder

**Comment by ogregoire** [comment]
@croudet In m fully aware of that, especially since I wrote:

> By default I shouldn't have any error messages for just a basic application. If I wanted a logging mechanism, I'd expect to have to add an additional dependency. Not to spend time reading how to disable a logging framework and add another extra dependency.

So basically I don't understand your point. Could you clarify it with just a few sentences? Link-only replies tend to be atrociously unclear in regards with your intent. Especially links that are already referenced in previous comments.

**Comment by graemerocher** [comment]
@ogregoire Micronaut uses Slf4j for logging of dependency injection, so you need at least one logging backing implementation for it to work such as log4j2, logback or jul (java's built in logging). If you don't want any logging you can add `slf4j-nop` to your classpath

**Comment by graemerocher** [comment]
and btw slf4j is not a logging framework, it simply delegates to other logging frameworks, it is a facade so we can provide logging if needed or not (as is the case with `slf4j-nop`)

**Comment by ogregoire** [comment]
Reading the documentation of micronaut-inject made me hope for a clean framework. Well, I guess I was wrong. It definitely doesn't fit my requirements of no non-sensical transitive dependencies because of slf4j (and snakeyaml) for my current projects, but I will definitely consider it whenever I write web applications.

**Comment by graemerocher** [comment]
snakeyaml is only required if you use `ApplicationContext`, if you are only using `BeanContext` (which is just DI without configuration management) you can exclude snakeyaml from the transitives in your build config
