### ISSUE TITLE
Feature request: support for Apache POI in native image

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-core#3706]
Is it planned to make module with configurations needed to run Apache POI in native image?

Thank you very much for you response.

**Comment by graemerocher** [comment]
Not at the moment and certainly not in micronaut core

**Comment by jameskleeh** [comment]
@morki We don't have any integration with POI and don't have anything in the works to create an integration. We can't create configurations for every third party library to work with Graal. Really that work should lie at the hands of Apache POI.
