### ISSUE TITLE
Regression: micronaut.io.watch.restart not working

### ISSUE THREAD

**Issue by esocode** [micronaut-projects/micronaut-core#3708]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

I just noticed that setting `micronaut.io.watch.restart` to true no longer works after migration to Micronaut 2.0.0.

### Steps to Reproduce

1. Set `micronaut.io.watch.paths=src/main`and `micronaut.io.watch.restart=true` in application.yml.
2. Run application
3. Change source file under `src/main` - application won't terminate

### Expected Behaviour

Application should terminate on source file change

### Actual Behaviour

Application continues to run

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.0.0
- **JDK Version:** 8

**Comment by graemerocher** [comment]
This is definitely working however enabled by default in `build.gradle` ... all you have to do now is run `./gradlew run -t`

**Comment by esocode** [comment]
This is strange, for me this is not working anymore. I have been using this with 1.x all the time, but since upgrading to 2.0.0 my apps won't stop if I save a modified source file.

**Comment by esocode** [comment]
Maybe a problem with the file change detection on Windows?

**Comment by esocode** [comment]
Where is the code for this feature located in the project? Maybe I can find the reason why it's not working anymore on Windows.

**Comment by graemerocher** [comment]
The thing that stops the server is this:

https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/runtime/server/watch/event/FileWatchRestartListener.java

The thing that watches files is this:

https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/scheduling/io/watch/DefaultWatchThread.java

**Comment by esocode** [comment]
I found the reason: the feature now requires the property `micronaut.io.watch.enabled` to be set to TRUE. This is probably caused by the following `DefaultWatchThread` annotation:
```java
@Requires(property = FileWatchConfiguration.ENABLED, value = StringUtils.TRUE, defaultValue = StringUtils.TRUE)
```
The code has not changed since Micronaut 1.x. Maybe the property evaluation has changed somehow in 2.0?

**Comment by graemerocher** [comment]
Don't believe so

**Comment by chrisparton1991** [comment]
@esocode looks like I fell down the same rabbit hole as you! I wound up with the exact same conclusion.

I've raised PR #4554 to include `enabled: true` in the docs.
