### ISSUE TITLE
Intermittent Unexpected error: Attempt to recreate a file for type errors with incremental compilation

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#3712]
When Gradle incremental compilation is enabled the compilation intermittently fails with errors like:

```
error: Unexpected error: Attempt to recreate a file for type io.micronaut.oci.objectstorage.$ObjectStorageClientTestDefinition
error: Unexpected error: Attempt to recreate a file for type io.micronaut.oci.objectstorage.$SdkTestDefinition
```

Unclear whether this is a Gradle bug or Micronaut bug at this stage.

### Steps to Reproduce

1. Checking git@github.com:micronaut-projects/micronaut-oracle-cloud.git
2. Make a change to any of the classes and rerun compilation
3. After a few changes the error will appear

### Environment Information

- **Operating System**: Any
- **Micronaut Version:** 2.0.0
- **JDK Version:** Any

**Comment by graemerocher** [comment]
Can't see anything we are doing wrong from an annotation processing perspective. Reported https://github.com/gradle/gradle/issues/13767

**Comment by l0co** [comment]
This happens for me only for the project running on JDK 8, while gradle JVM version was set in Idea to 14. After switching gradle JVM version to 8 this problem seems to dissapear.

**Comment by graemerocher** [comment]
A PR has been submitted to Gradle core to fix the issue https://github.com/gradle/gradle/pull/13833

**Comment by graemerocher** [comment]
Hopefully it will go into Gradle 6.7

**Comment by kbachl** [comment]
@l0co 
sorry, but can't confirm this... I'm here on JDK 11 src and target and idea at 11 and it happens... interestingwise every 2nd refresh it seems to work and it did start plaguing me after putting my micronaut project into a multi-project-structure; having only a solo project it never occured before.... its IMHO a nasty one at gradle

**Comment by graemerocher** [comment]
@kbachl As a workaround you can disable incremental annotation processing

**Comment by l0co** [comment]
@kbachl Does your JVM from *File | Settings | Build, Execution, Deployment | Build Tools | Gradle* is exactly the same as in *File | Project structure | Project | Project SDK*?

**Comment by kbachl** [comment]
@l0co 
1st is set to: "11 GraalVM11 (version 11.0.7)" and 
2nd is set to:  "11 GraalVM11 (version 11.0.7)"
yet it happens....

@graemerocher thanks for the hint! - this helps a lot!

**Comment by nbrugger-tgm** [comment]
> @kbachl As a workaround you can disable incremental annotation processing

How could one do this? As far as i read from gradle, incremental annotation processing is enabled if it is explicitly defined by the annotation processor. So how would I disable it (and for which processor)
