### ISSUE TITLE
/health endpoint (micronaut management) returns HTTP 401 code when router.versioning is enabled

### ISSUE THREAD

**Issue by sdautovic** [micronaut-projects/micronaut-core#3733]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. enable micronaut.io /health endpoint
`endpoints:
    health:
      enabled: true`
2. enable micronaut.io router versioning
`micronaut:
   router:
    versioning:
      enabled: true`

### Expected Behaviour
/health endpoint should return health status the same way as when versioning is disabled. 
### Actual Behaviour
returns HTTP response code 401
### Environment Information

- **Operating System:** macOS Catalina, version 10.15.5
- **Micronaut Version:** 2.0.0
- **JDK Version:** java 11.0.2 2019-01-15 LTS

**Comment by jameskleeh** [comment]
I can't reproduce. Please upload an example that reproduces the issue

**Comment by sdautovic** [comment]
I have to say that this is not a bug... Realized that I had problem with custom route versioning implementation. 
I apologize for causing this situation.
