### ISSUE TITLE
Random hotswap problems with classes re-genereated by kapt

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#3734]
In `2.0.0`.

I'm trying to debug why hotswap doesn't work for my project, during development in Idea. I use gradle build and I run services using gradle. I also use kapt instead of standard annotation processor, because the project is partially written in kotlin. My configuration (important part) is the following:

```
build.gradle
------------

    kapt {
        arguments {
            arg("micronaut.processing.incremental", true)
            arg("micronaut.processing.annotations", "io.luna.*") // this is my main package
        }
    }

    dependencies {
        kapt platform("io.micronaut:micronaut-bom:$micronautVersion")
        kapt "io.micronaut:micronaut-inject-java"
        kapt "io.micronaut:micronaut-validation"
        kaptTest platform("io.micronaut:micronaut-bom:$micronautVersion")
        kaptTest "io.micronaut:micronaut-inject-java"

gradle.properties
-----------------

kapt.include.compile.classpath=false
kapt.use.worker.api=true
kotlinVersion=1.3.71
org.gradle.parallel=true
```

Now, I'm trying to test hotswap just by changing some string inside a bean method. It randomly works and randomly says "hotswap failed, hierarchy change not implemented". I've compared build output for successful and in a nutshell here's the difference in the failed hotswaps:

![image](https://user-images.githubusercontent.com/1880196/87540885-a7c51700-c6a0-11ea-888b-68e70bb36331.png)

It seems you use a `Set` or something similar to keep superclasses, and if the order is changed, the class is reloaded and for some reason this ends up with a failed hotswap.

The other difference I've found, which didn't result in failed hotswap, but it concerns the class which didn't change, is here:

![image](https://user-images.githubusercontent.com/1880196/87541339-62551980-c6a1-11ea-8083-fb2c924d85d2.png)

I'm not 100% sure the above is a reason for failed hotswap, I'm just trying to find a solution to the problem. I don't know also why kapt decides to process these classes again on recompilation, while they weren't changed (they only refer to the singleton which were changed).

However, I think, that for the consistency, if the class weren't changed, Micronaut annotation processor should generate exactly the same bytecode as in the previous run, and this would be the desired fix for me.

**Comment by l0co** [comment]
I've checked in aside project that hotswap indeed doesn't work when the order of implemented interfaces changes (Micronaut is not involved in this project). So now I'm sure that this is at least a part of this problem.

**Comment by graemerocher** [comment]
Looks like `BeanDefinitionWriter` uses `private final Set<Class> interfaceTypes;` which means the interfaces are in a different order each build. The fix seems to be use a list and include a `contains` check to avoid duplicates. 

I think `private final Map<String, GeneratorAdapter> loadTypeMethods = new HashMap<>();` may also need to be changed to a `LinkedHashMap`.

Would you like to send a PR?

**Comment by l0co** [comment]
PR #3744

**Comment by l0co** [comment]
I use build snapshot right now and the problem seems to be solved, because I can now rebuild the project and the hotswap works each time. So, the last problem preventing from using micronaut with kapt conveniently is #3742, because without incremental annotations processing, even after changing a single char and building the project, the process takes long time and rebuilds a lot of classes.
