### ISSUE TITLE
Intermittent BeanInstantiationException with Message: Recursive update

### ISSUE THREAD

**Issue by JasonTypesCodes** [micronaut-projects/micronaut-core#3753]
The Micronaut JHipster generator was recently updated to use Micronaut 2.0.0 by default.  Since that time, we have seen intermittent failures in our CI due to BeanInstantiationExceptions being thrown during the integration tests.  They don't always have the same stack trace

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. New applicaiton generated with mhipster and Micronaut 2.0.0
2. Run Integration Tests
3. They might pass, if they do, run them again
4. They will eventually fail with one of these:

```
io.micronaut.context.exceptions.BeanInstantiationException: 
Error instantiating bean of type  [io.micronaut.liquibase.$LiquibaseMigrationRunnerDefinition$Intercepted]

Message: Recursive update
Path Taken: new $LiquibaseMigrationRunnerDefinition$Intercepted(ApplicationContext applicationContext,ResourceAccessor resourceAccessor,DataSourceResolver dataSourceResolver,BeanContext beanContext,Qualifier qualifier,[Interceptor[] interceptors])
        at io.github.jhipster.sample.config.CorsTest.testCorsFilterDeactivated(CorsTest.java:56)
Caused by: java.lang.IllegalStateException: Recursive update
        at io.github.jhipster.sample.config.CorsTest.testCorsFilterDeactivated(CorsTest.java:56)
```

-or-

```
io.micronaut.context.exceptions.BeanInstantiationException: 
Error instantiating bean of type  [io.micronaut.validation.validator.resolver.CompositeTraversableResolver]

Message: Recursive update
Path Taken: new DefaultValidator([ValidatorConfiguration configuration]) --> DefaultValidatorConfiguration.setTraversableResolver([TraversableResolver traversableResolver]) --> new CompositeTraversableResolver([List traversableResolvers])
	at com.mycompany.myapp.config.CorsTest.testCorsFilterDeactivated(CorsTest.java:56)
Caused by: java.lang.IllegalStateException: Recursive update
	at com.mycompany.myapp.config.CorsTest.testCorsFilterDeactivated(CorsTest.java:56)
```

### Expected Behaviour

The context should start with recursive update issues

### Actual Behaviour

See above

### Environment Information

- **Operating System**: Debian Linux 10 (Buster)
- **Micronaut Version:** 2.0.0
- **JDK Version:** OpenJDK Runtime Environment 18.9 (build 11.0.7+10)

### Example Application

https://github.com/JasonTypesCodes/mhipster-recursive-update

MHipster sibling issue: https://github.com/jhipster/generator-jhipster-micronaut/issues/122

**Comment by graemerocher** [comment]
Duplicates #3577
