### ISSUE TITLE
ProxyHttpClient implementation in DefaultHttpClient does not rewrite Host header

### ISSUE THREAD

**Issue by jacobmims** [micronaut-projects/micronaut-core#3759]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a `ProxyHttpClient`
2. Call the `proxy` method on a URI with a `host()` value that is different from the originating service.
3. Note the `Host` header still references the originating service URI's `host()` value.
    - Known issues with Cloud Providers:
       - GCP AppEngine will not accept requests with a `Host` header different from the service being called.

### Expected Behaviour

The `proxy` method should rewrite the `Host` header to the `host()` value of the URI being called by `proxy()`.

### Actual Behaviour

The `Host` header of the request made by the `proxy` method is set to the `host()` value the originating service's URI.

### Environment Information

- **Operating System**: MacOS 10.15.5
- **Micronaut Version:** 2.0.0
- **JDK Version:** 11

Relevant documentation: https://docs.micronaut.io/latest/guide/httpClient.html#proxyClient

**Comment by jacobmims** [comment]
**Update**: I was able to workaround the issue by removing the header when constructing the request. This should probably be standard behavior for the proxy method, instead of having to do it when mutating the request.

```java
private final String host = "some-gcp-project-name.appspot.com";
 
@Override
  protected Publisher<MutableHttpResponse<?>> doFilterOnce(
      HttpRequest<?> request, ServerFilterChain chain) {
    HttpRequest<?> proxyRequest = request.mutate()
        .uri(b -> b.scheme(HttpRequest.SCHEME_HTTPS).port(443).host(host))
        .headers(h -> h.remove("Host"));

    return Publishers.map(client.proxy(proxyRequest), response -> response);
  }
```

**Comment by miguelaferreira** [comment]
If it's worth anything towards validation, I've just faced this same issue while building a web proxy using the ProxyHttpClient.

**Comment by cpriisholm** [comment]
Can confirm that I've seen load balancers and http server return various errors (503, 421...) unless the above workaround is applied.
