### ISSUE TITLE
HTTP return code 200 OK, without properly parsing semicolon

### ISSUE THREAD

**Issue by jankolarik** [micronaut-projects/micronaut-core#3778]
Micronauts will ignore part of user input/query but will still give a good reponse status code.

### Steps to Reproduce

1. With the following code:

**Application.java**

```
package example.micronaut;

import io.micronaut.runtime.Micronaut;

public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }
}
```

**HelloController.java**
```
package example.micronaut;

import io.micronaut.http.MediaType;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.annotation.Produces;
import io.micronaut.http.client.annotation.Client;

import java.util.Optional;

@Controller("/hello")
public class HelloController {
    @Client("http://localhost:8080")

    @Get(uri = "/optionalString{?name}")
    @Produces(MediaType.TEXT_PLAIN)
    public String helloOptionalString(Optional<String> name) {
        if(name.isPresent()) {
            return name.get();
        }
        return "NoNamePresent";
    }
}
```

2. Run GET `http://localhost:8080/hello/optionalString?name=Alice;Bob`

### Expected Behaviour

Request should return `Alice;Bob` 

-- alternatively -- 

Response code should be `400`

### Actual Behaviour

Request returns `Alice` and reponse code of `200 OK`

### Environment Information

- **Operating System**: macOS 10.15.6
- **Micronaut Version:**  2.0.0.RC1
- **JDK Version:** openjdk 11.0.7 2020-04-14

**Comment by jankolarik** [comment]
Without Optional<>, we get the same behaviour.

**Comment by jameskleeh** [comment]
`;` is a delimiter for query values. You should be encoding the value. For example with our client:

``` URI uri = UriBuilder.of("/optionalString").queryParam("name", "a;b").build()
        client.retrieve(HttpRequest.GET(uri))

**Comment by jankolarik** [comment]
I think the issue still remains here. 

If a user uses an external client for sending requests which does not automatically encode ; to %3B or any other character for that matter, the developer cannot do much about it in Micronauts.

For example netty’s implementation to parse the query parameters provide a way to modify the behaviour of parsing of semicolons. I was thinking of having a similar feature in Micronauts. Would it be possible?
