### ISSUE TITLE
Multiple query params does not work properly with graalvm

### ISSUE THREAD

**Issue by traycho** [micronaut-projects/micronaut-core#3779]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Build application
2. Run it in sam local environment
3. Execute curl -G http://localhost:3000/execute?filter=1&filter=2&filter=3   (It prints only ["1"] but expected ["1","2","3"]

Note: Issue is reproducible only with graalvm native image

### Expected Behaviour

curl -G http://localhost:3000/execute?filter=1&filter=2&filter=3   should return ["1","2","3"]

### Actual Behaviour

curl -G http://localhost:3000/execute?filter=1&filter=2&filter=3  returns ["1"]  (only first filter)

### Environment Information

- **Operating System**: MacOs Mojave
- **Micronaut Version:** 1.3.6
- **JDK Version:** 1.8.0_222

### Example Application

Checkout code from
https://bitbucket.org/traycho/micronaut-examples/src/master/

**Comment by yawkat** [comment]
Reproducer is broken (not too surprising after two years). I will close since I doubt this is an issue anymore in mn 3
