### ISSUE TITLE
Warn about using the wrong Singleton class when using groovy

### ISSUE THREAD

**Issue by podollb** [micronaut-projects/micronaut-core#378]
It might be nice if there could be micronaut warnings about the very common issue that occurs when using Groovy and Micronaut regarding the Singleton classes.
```
Groovy automatically imports groovy.lang.Singleton which can be confusing as it conflicts with javax.inject.Singleton. Make sure you include the javax.inject.Singleton import when declaring a singleton bean!
```

**Comment by graemerocher** [comment]
I agree this is unfortunate for Groovy users. However I am not sure how to resolve it. If we print a warning for every use of `groovy.lang.Singleton` then what happens to the valid uses of it?

Really I don't understand why that class is in the `groovy.lang` package. It should be in `groovy.transform`

**Comment by podollb** [comment]
Maybe there could be a way to create an alias annotation such as `MicronautSingleton` that you could optionally use?
