### ISSUE TITLE
Gradle multi module project compile error with client 

### ISSUE THREAD

**Issue by sascha-frinken** [micronaut-projects/micronaut-core#3780]
When using gradle > 6.0, in a multi module project, a client extending an interface from another module fails in
compile phase. With the following error:

```
startup failed:
/src/scratchpad/mn-gradle-6-error/client/src/main/groovy/com/example/FailingClient.groovy: -1: The route declares a uri variable named [command], but no corresponding method argument is present
 @ line -1, column -1.
1 error
```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Checkout linked repo and run `./gradlew classes`

### Expected Behaviour

Compile without error

### Actual Behaviour

Compilation error

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.3.7
- **JDK Version:** 11

### Example Application

https://github.com/safri-net/mn-gradle-6-error

**Comment by sascha-frinken** [comment]
Is this more likely to be a gradle problem and should be reported there?

**Comment by sascha-frinken** [comment]
Update this also happens on a java project and micronaut 2.0.1.

**Comment by graemerocher** [comment]
most likely is that groovy named parameters are not enabled correctly

**Comment by sascha-frinken** [comment]
@graemerocher 
As I just mentioned it also happens on a plain java project and micronaut 2.0.1.
I try to push it as a `java` branch asap.

**Comment by sascha-frinken** [comment]
Branch `java` pushed.  
Just run `./gradlew classes` to reproduce

**Comment by sascha-frinken** [comment]
Since updating to micronaut 2.1.x, gradle 6.7 it appears to befixed. Either by micronaut, micronat gradle plugin or gradle version…
