### ISSUE TITLE
LocaleResolver bean

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#3787]
I think it would be good to create a `LocaleResolver` contract to help with Locale resolution. 

Multiple implementations should be provided. Some for resolution within an HTTP Request (Accept Header, Cookie, Session) but also for environments such as Alexa Skills. 

Relates to: https://github.com/micronaut-projects/micronaut-core/issues/2617

**Comment by jachinte** [comment]
@sdelamo Is there a way to implement a `LocalResolver` without adding parameters (e.g., the Accept-Language header) to controllers' methods?

I'd like to implement this functionality for my project.
