### ISSUE TITLE
Minor error/improvement in HTTP client's Javadoc, version 2.0.0

### ISSUE THREAD

**Issue by dcmoeller** [micronaut-projects/micronaut-core#3806]
Dealing with Micronaut's HTTP client lib (version 2.0.0) I found that Javadoc of [`io.micronaut.http.MutableHttpHeaders`](https://docs.micronaut.io/2.0.0/api/io/micronaut/http/MutableHttpHeaders.html) contains minor errors when it comes to setting date-related header fields like

- [`date(LocalDateTime date)`](https://docs.micronaut.io/2.0.0/api/io/micronaut/http/MutableHttpHeaders.html#date-java.time.LocalDateTime-)
- [`expires(LocalDateTime date)`](https://docs.micronaut.io/2.0.0/api/io/micronaut/http/MutableHttpHeaders.html#expires-java.time.LocalDateTime-)
- [`ifModifiedSince(LocalDateTime date)`](https://docs.micronaut.io/2.0.0/api/io/micronaut/http/MutableHttpHeaders.html#ifModifiedSince-java.time.LocalDateTime-)
- [`lastModified(LocalDateTime date)`](https://docs.micronaut.io/2.0.0/api/io/micronaut/http/MutableHttpHeaders.html#lastModified-java.time.LocalDateTime-)

Javadoc claims that they all accept parameter of type `java.time.ZonedDateTime`, but it's `java.time.LocalDateTime`.

Further I would like to suggest an addition to Javadocs of the aforementioned methods, something like
```
@param date - The local date/time (assumed to represent system's default time-zone `java.time.ZoneId.systemDefault()`,
will be converted to GMT) as per DateTimeFormatter.RFC_1123_DATE_TIME
@see #add(CharSequence, ZonedDateTime) to set date/time with time-zone.
```

This makes it clear that users might get unexpected results if using `LocalDateTime`-based methods.

### Environment Information

- **Micronaut Version:** 2.0.0

**Comment by graemerocher** [comment]
PRs welcome!
