### ISSUE TITLE
Stop publishing shadow versions of some jars

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#3815]
The new gradle build is publishing the `-all` shadow jars for modules that require repackaging ASM like `micronaut-inject-groovy`, `micronaut-inject-java` etc.

**Comment by alvarosanchez** [comment]
This seems to be a feature of Shadow 6: https://github.com/johnrengelman/shadow/releases/tag/6.0.0

As agreed with Graeme, I am closing this unless it manifests as an actual issue.
