### ISSUE TITLE
Improve error message when trying to run create-app within a Micronaut project

### ISSUE THREAD

**Issue by pelenthium** [micronaut-projects/micronaut-core#382]
- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
1 Installed micronaut by sdkman using command
`$ sdk install micronaut

Downloading: micronaut 1.0.0.M2

In progress...

######################################################################## 100.0%

Installing: micronaut 1.0.0.M2
Done installing!

Setting micronaut 1.0.0.M2 as default.`

2 Try to create new project
`$ mn create-app hello
Resolving dependencies..
.
.
.

| Error Command not found create-app
Did you mean: create-bean or create-job or create-client?`

### Expected Behaviour

I would like to see new created project

### Actual Behaviour

Project wasn't created, error on console

### Environment Information

- Mac OS 10.13.5
- micronaut 1.0.0.M2
- openjdk version "1.8.0_172"

As I see micronaut profiles was downloaded - 

`$ find /Users/pelenthium/.m2/repository/io/micronaut
/Users/pelenthium/.m2/repository/io/micronaut
/Users/pelenthium/.m2/repository/io/micronaut/bom
/Users/pelenthium/.m2/repository/io/micronaut/bom/1.0.0.M2
/Users/pelenthium/.m2/repository/io/micronaut/bom/1.0.0.M2/bom-1.0.0.M2.pom
/Users/pelenthium/.m2/repository/io/micronaut/bom/1.0.0.M2/bom-1.0.0.M2.pom.sha1
/Users/pelenthium/.m2/repository/io/micronaut/bom/1.0.0.M2/_remote.repositories
/Users/pelenthium/.m2/repository/io/micronaut/profiles
/Users/pelenthium/.m2/repository/io/micronaut/profiles/service
/Users/pelenthium/.m2/repository/io/micronaut/profiles/service/1.0.0.M2
/Users/pelenthium/.m2/repository/io/micronaut/profiles/service/1.0.0.M2/service-1.0.0.M2.pom.sha1
/Users/pelenthium/.m2/repository/io/micronaut/profiles/service/1.0.0.M2/service-1.0.0.M2.pom
/Users/pelenthium/.m2/repository/io/micronaut/profiles/service/1.0.0.M2/service-1.0.0.M2.jar.sha1
/Users/pelenthium/.m2/repository/io/micronaut/profiles/service/1.0.0.M2/_remote.repositories
/Users/pelenthium/.m2/repository/io/micronaut/profiles/service/1.0.0.M2/service-1.0.0.M2.jar
/Users/pelenthium/.m2/repository/io/micronaut/profiles/base
/Users/pelenthium/.m2/repository/io/micronaut/profiles/base/1.0.0.M2
/Users/pelenthium/.m2/repository/io/micronaut/profiles/base/1.0.0.M2/base-1.0.0.M2.jar.sha1
/Users/pelenthium/.m2/repository/io/micronaut/profiles/base/1.0.0.M2/base-1.0.0.M2.pom
/Users/pelenthium/.m2/repository/io/micronaut/profiles/base/1.0.0.M2/_remote.repositories
/Users/pelenthium/.m2/repository/io/micronaut/profiles/base/1.0.0.M2/base-1.0.0.M2.pom.sha1
/Users/pelenthium/.m2/repository/io/micronaut/profiles/base/1.0.0.M2/base-1.0.0.M2.jar`

**Comment by graemerocher** [comment]
Looks like you are running `create-app` within another micronaut project

**Comment by pelenthium** [comment]
@graemerocher you are right, I found micronaut-cli.yml in this directory, thanks! In another directory project was created.
maybe we need to change this message to another to avoid this misunderstanding, like as 'You can't create micronaut application inside another'

**Comment by pelenthium** [comment]
Guys, as I see in the new version we don't have this errors - mn with create-app command in current project open interactive console, so there's nothing to do here
