### ISSUE TITLE
Fix unresolved directives in docs

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#3825]
See for example https://docs.micronaut.io/latest/guide/index.html#distributedConfigurationOracleCloudVault

And output:

```
Unresolved directive in <stdin> - include::/Users/jameskleeh/IdeaProjects/Micronaut/micronaut-core/build/generated/configurationProperties/io.micronaut.discovery.oraclecloud.vault.config.OracleCloudVaultClientConfiguration.adoc[]
```

**Comment by jameskleeh** [comment]
@graemerocher The docs were built correctly. That file no longer exists in this project, thus the unresolved directive.

**Comment by graemerocher** [comment]
@jameskleeh if the file no longer exists then there is something broken in the build since the file was previously generated as part of the build. This is not a documentation issue. All snippets in the docs that reference configuration properties are broken.

**Comment by graemerocher** [comment]
Oh I see ignore me, the `discovery-client` stuff was moved out of core

**Comment by jameskleeh** [comment]
@graemerocher That isn't true. See https://docs.micronaut.io/latest/guide/index.html#io.micronaut.scheduling.executor.UserExecutorConfiguration

There are 6 references to unresolved directives:

Unresolved directive in <stdin> - include::spring/src/test/groovy/io/micronaut/spring/beans/MicronautBeanProcessorByAnnotationTypeSpec.groovy[tags=springconfig, indent=0]

Unresolved directive in <stdin> - include::/Users/jameskleeh/IdeaProjects/Micronaut/micronaut-core/build/generated/configurationProperties/io.micronaut.cache.DefaultCacheConfiguration.adoc[]

Unresolved directive in <stdin> - include::/Users/jameskleeh/IdeaProjects/Micronaut/micronaut-core/build/generated/configurationProperties/io.micronaut.discovery.vault.config.VaultClientConfiguration.adoc[]

Unresolved directive in <stdin> - include::/Users/jameskleeh/IdeaProjects/Micronaut/micronaut-core/build/generated/configurationProperties/io.micronaut.discovery.aws.parameterstore.AWSParameterStoreConfiguration.adoc[]

Unresolved directive in <stdin> - include::/Users/jameskleeh/IdeaProjects/Micronaut/micronaut-core/build/generated/configurationProperties/io.micronaut.discovery.oraclecloud.vault.config.OracleCloudVaultClientConfiguration.adoc[]

Unresolved directive in <stdin> - include::/Users/jameskleeh/IdeaProjects/Micronaut/micronaut-core/build/generated/configurationProperties/io.micronaut.discovery.eureka.EurekaConfiguration$EurekaRegistrationConfiguration.adoc[]

As you can see - they all reference files that are not in core.
