### ISSUE TITLE
Add a TypeElementVisitor that validates route variables at compile time

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#383]
### Expected Behaviour

The following should produce a compilation error for both HTTP clients and controllers:

```java
@Get("/{nombre}")
String hello(String name)
```

### Actual Behaviour

Currently a runtime error occurs.

**Comment by beckje01** [comment]
Another great addition would be the following check:

Expected the following to error:
```
@Get("/beck{/var}")
String xyz(String var)
```


While the following should pass:
```
@Get("/beck{/var}")
String xyz(@Nullable String var)
```

**Comment by jameskleeh** [comment]
@beckje01 If you have any other ideas for this, let me know. I'm implementing this now
