### ISSUE TITLE
Make Router api more easy to use

### ISSUE THREAD

**Issue by eisig** [micronaut-projects/micronaut-core#3836]
In  both MicronautLambdaContainerHandler and  http server netty, after getting  RouteMatch with Router.route,  have to do much config with it. 
Is it possible to make it more easy to use? Then  more simpler to implement something like the lambda api gateway  

1. convert my input to a request.
2. find route match, and execute with it. 
3. convert the response

**Comment by graemerocher** [comment]
The API is not really designed for direct consumption agreed and it is something we should improve, but why are you trying to use this API in a lambda API gateway function?

**Comment by eisig** [comment]
I want to try whether it is easy to support other event sources, such as aws http api, ALB.  And even in other cases, use non-HTTP protocols, such as nats rpc. In these scenarios, we can use a uniform style to write services.

**Comment by graemerocher** [comment]
I see. You may want to look at https://github.com/micronaut-projects/micronaut-aws/tree/master/function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy which already does proxying for API gateway

**Comment by eisig** [comment]
@graemerocher thanks. I have already used that api for some service.
Maybe just need little  modify to support  AWS Gateway HTTP API (https://github.com/micronaut-projects/micronaut-aws/issues/321).
But how to make it more generic to support other event type.(not only aws event)
The micronaut-azure project uses Servlet api, seems more simple。
Or more generally, how to make this pattern simpler, not necessarily in a serverless environment.

**Comment by graemerocher** [comment]
Yes it was actually in my mind to port the AWS project to servlet so that is what I would do in this case

**Comment by eisig** [comment]
OK, maybe I should close this first.

@graemerocher， another thing,
Aboout a months ago, I report https://github.com/micronaut-projects/micronaut-aws/issues/410 and https://github.com/micronaut-projects/micronaut-aws/issues/409。It seems that no one take a look at it.
Although they are not big problems, we still want some feedback, otherwise we will feel that there is no one to maintain the projec
What is  the right way to report a new  issue, just report here(micronaut-core), and the maintainers move them to sub projects?
