### ISSUE TITLE
RabbitMQ Messaging Application Support

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#384]
We should support RabbitMQ / AMQP in the same way as we support Kafka

**Comment by mattmoss** [comment]
Un-assigning self.... This looks like more than I can bite off at this time. I'll try to find some smaller tasks to help out on.

**Comment by wykapedia** [comment]
I may be interested in taking on part of this.  Do we have any structure or documentation to follow, or just winging it?

**Comment by graemerocher** [comment]
@wykapedia probably not until early next year

**Comment by wykapedia** [comment]
Thanks @graemerocher.  I am going to take an initial stab at the skeleton of rabbit setup.

Going to follow after kafka and reference rabbit docs here:
https://www.rabbitmq.com/api-guide.htm

**Comment by wykapedia** [comment]
@graemerocher should I cut this off of `master` or `1.0.x` branch?

**Comment by graemerocher** [comment]
Off master.

**Comment by brianwyka** [comment]
Is this no longer **high priority**?

**Comment by jameskleeh** [comment]
It is finished, hence the closed status.

github.com/micronaut-projects/micronaut-rabbitmq
