### ISSUE TITLE
Implement JUnit 4/5 and Spock extensions

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#386]
We should have Spock and JUnit extensions that start and shutdown the `EmbeddedServer` or the `ApplicationContext` for each test class and also allow dependency injection into the test itself. This will make testing simpler.

Although it is fairly simple right now with `@AutoCleanup @Shared` with Spock, the same can not be said for JUnit

A trivial `micronaut-test` module could resolve this and make life simpler for users.

**Comment by chantrybjss** [comment]
I agree with this. I had to create a JUnit class rule to simplify my testing as I would prefer not to use Spock. Having clear documentation about testing without Spock would also be beneficial.

**Comment by jeffbrown** [comment]
@chantrybjss Are you interested in sharing your JUnit class rule as a contribution to help start the effort?

**Comment by chantrybjss** [comment]
> @chantrybjss Are you interested in sharing your JUnit class rule as a contribution to help start the effort?

I did not do anything fancy. All I really did was move the handling of getting the client from the application context to the class rule.

I imagine there's a better way to approach it than this, but this was the code I was using in my experiments. 

```
public class TestHttpClient<T> implements TestRule, Supplier<T> {
    private final EmbeddedServer embeddedServer;
    private final T client;

    public TestHttpClient(final Class<T> client) {
        this.embeddedServer = ApplicationContext.run(EmbeddedServer.class);
        this.client = embeddedServer.getApplicationContext().getBean(client);
    }

    @Override
    public final Statement apply(final Statement statement, final Description description) {
        return new Statement() {
            @Override
            public void evaluate() throws Throwable {
                try {
                    embeddedServer.start();
                    statement.evaluate();
                }
                finally {
                    embeddedServer.stop();
                }
            }
        };
    }

    @Override
    public final T get() {
        return client;
    }
}
```
Then in each test class I had something like the following.

```
@ClassRule
public static final TestHttpClient<SomeClient> httpClient = new TestHttpClient<>(SomeClient.class);
```

**Comment by alvarosanchez** [comment]
Yes, I self-assigned this and https://github.com/micronaut-projects/micronaut-profiles/issues/68

**Comment by graemerocher** [comment]
We should also resolve https://github.com/micronaut-projects/micronaut-test/issues/12 as part of this
