### ISSUE TITLE
Fallback Not applicable when implements of an interface

### ISSUE THREAD

**Issue by oscarcitoz** [micronaut-projects/micronaut-core#3864]
### Task List

- [ ] Steps to reproduce provided
The next classes can explain the issue (kotlin-micronaut)

interface PetInterface {
    fun doAny(): String
}

@Singleton
@Recoverable
@CircuitBreaker(delay = "1ms", attempts = "3", multiplier = "2", reset = "30s")
class PetImplementation: PetInterface {
    override fun doAny(): String {
        return throw RuntimeException("")
    }
}

@Fallback
class PetFallback: PetInterface {
    override fun doAny(): String {
        return ""
    }
}

- [ ] Example that reproduces the problem uploaded to Github
Then if you can see in the before code, PetFallback and PetImplementation implement of an interface (PetInteface), then the circuitBreaker never activate because the fallback extends of PetInterface, then the code only can search fallback for the PetImplementation (before micronaut 1 you can activate fallback of the an interface).

### Environment Information

- **Micronaut Version:**2.0.1

**Comment by jameskleeh** [comment]
@oscarcitoz You can simply do `@Recoverable(api = PetInterface)`. This is one of the breaking changes in Micronaut 2. This is documented in the user guide
