### ISSUE TITLE
"Error GraalVM only supports up to JDK 11" when: mn create-app micronaut-graal-maven --build maven --features graalvm

### ISSUE THREAD

**Issue by tivrfoa** [micronaut-projects/micronaut-core#3884]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

mn create-app micronaut-graal-maven --build maven --features graalvm

### Expected Behaviour

Create the app

### Actual Behaviour

Error GraalVM only supports up to JDK 11

### Environment Information

- **Operating System**: Ubuntu
- **Micronaut Version:** 2.0.1
- **JDK Version:** 11

**Comment by ilopmar** [comment]
I'm not able to reproduce the issue:

```
ivan@nobita:/tmp$ sdk use java 11.0.7-open
Using java version 11.0.7-open in this shell.

ivan@nobita:/tmp$ java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment 18.9 (build 11.0.7+10)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10, mixed mode)

ivan@nobita:/tmp$ mn -V                                                               
Micronaut Version: 2.0.1

ivan@nobita:/tmp$ mn create-app micronaut-graal-maven --build maven --features graalvm
| Application created at /tmp/micronaut-graal-maven
```

**Comment by tivrfoa** [comment]
> I'm not able to reproduce the issue:
> 
> ```
> ivan@nobita:/tmp$ sdk use java 11.0.7-open
> Using java version 11.0.7-open in this shell.
> 
> ivan@nobita:/tmp$ java -version
> openjdk version "11.0.7" 2020-04-14
> OpenJDK Runtime Environment 18.9 (build 11.0.7+10)
> OpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10, mixed mode)
> 
> ivan@nobita:/tmp$ mn -V                                                               
> Micronaut Version: 2.0.1
> 
> ivan@nobita:/tmp$ mn create-app micronaut-graal-maven --build maven --features graalvm
> | Application created at /tmp/micronaut-graal-maven
> ```

Sorry Ivan. I know what happened:
  - Micronaut uses $JAVA_HOME
  - My $JAVA_HOME was 14
  - But the $PATH I has Java 11

That is why when I ran `java --version` I got 11 ...

Sorry.

**Comment by ilopmar** [comment]
Glad it works :)
