### ISSUE TITLE
Mutable response has no content type since Micronaut 2.0

### ISSUE THREAD

**Issue by saw303** [micronaut-projects/micronaut-core#3888]
We have a filter to post process a controllers return value. Previous to Micronaut 2.0 the filter was accessing the `MutableHttpReponse#getContentType()` to verify the `MediaType` of the [return value](https://github.com/saw303/micronaut-2-no-content-type-in-response/blob/master/src/main/java/com/example/SomeFilter.java#L25).

```java
@Override
protected Publisher<MutableHttpResponse<?>> doFilterOnce(HttpRequest<?> request, ServerFilterChain chain) {
        return Flowable.fromPublisher(chain.proceed(request))
                .switchMap(response -> Flowable.fromCallable(() -> {
                      // in Micronaut 1.3.x the content type was present.
                      if (response.getContentType().isEmpty()) {
                                log.error("This is unexpected since the content type was available in Micronaut 1.3.x");
                      }
                      return response;
          }));
}
```

Since Micronaut 2.0 the content type is not present yet. Is there a reason for that or is this a bug?

Example project is available at https://github.com/saw303/micronaut-2-no-content-type-in-response

**Comment by jameskleeh** [comment]
I don't think this is a bug. I think this is a consequence of the refactoring done to the server implementation

**Comment by jameskleeh** [comment]
@saw303 Can you describe the use case? One issue with trying to set it beforehand is returning files. The `@Produces` is essentially ignored and the content type of the file is used.

**Comment by saw303** [comment]
@jameskleeh Sorry, I did not realize that you responded in September. Let me explain the use case to you and hopefully you might reconsider to open this issue again.

I use a `HttpServerFilter` to wrap a controllers body in to a HATEOAS model if the controller e.g. will return `application/json` or `application/xml`.

A response body that would be returned as this (without a the filter applied).

```json
{
    "id": "CHE",
    "name": "Switzerland",
    "foundationDate": "1291-08-01",
    "surface": 41285
}
````

But with the filter enabled it will wrap the response body in a HATEOAS like body containing additional meta data such as `self` link.

```json
{
  "data": {
    "id": "CHE",
    "name": "Switzerland",
    "foundationDate": "1291-08-01",
    "surface": 41285
  },
  "links": [
    {
      "rel": "self",
      "method": "GET",
      "href": "/v1/countries/CHE"
    }
  ]
}
```

Currently I'm working this around by accessing the `UriRouteMatch` within the filter (find an example [here](https://github.com/saw303/gradle-java-rest-api/blob/2.2.x/rest-api-micronaut/src/main/java/ch/silviowangler/rest/micronaut/HateoasResponseFilter.java#L130)). But in general I think I would expect the response content type within a filter or is there another more reliable way to get the information of what content type the client will receive?
