### ISSUE TITLE
Add MQTT protocol support

### ISSUE THREAD

**Issue by akozel** [micronaut-projects/micronaut-core#389]
Add MQTT protocol support.
MQTT (Message Queuing Telemetry Transport) is an ISO standard for IoT projects.

**Comment by bademux** [comment]
Full featured netty based MQTT server https://github.com/moquette-io/moquette

**Comment by dobermai** [comment]
A full fledged and Netty based MQTT client is available here: https://github.com/hivemq/hivemq-mqtt-client 

Also supports MQTT 5 and 3.1.1

**Comment by bademux** [comment]
Unfortunately it has almost all maven jars as a dependency.

**Comment by SgtSilvio** [comment]
@bademux What do you mean with "Unfortunately it has almost all jars in maven as a dependency :)"? Is there a problem with the dependencies of the HiveMQ MQTT Client?

**Comment by bademux** [comment]
> @bademux What do you mean with "Unfortunately it has almost all jars in maven as a dependency :)"? Is there a problem with the dependencies of the HiveMQ MQTT Client?

Well I'm thinking about MQTT server as well and Hive is really FAT

**Comment by jameskleeh** [comment]
This landed in 2.2
