### ISSUE TITLE
AWS SDK Dependencies not included in 2.0.1 BOM

### ISSUE THREAD

**Issue by bsamartins** [micronaut-projects/micronaut-core#3895]
Documentation states that to use either AWS SDK V1 or V2, it should be sufficient to include the dependency as follows:
```
implementation("io.micronaut.aws:micronaut-aws-sdk-v1")
``` 
After including Micronaut 2.0.1 BOM in a Gradle project, build does not resolve the AWS V1 SDK.
When verifying the BOM, neither V1 or V2 SDKs are declared as dependencies.

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Expected Behaviour

Expected Gradle to resolve AWS SDK v1 dependency

### Actual Behaviour

Build does not resolve V1 or V2 SDK dependencies 

### Environment Information

- **Micronaut Version:** 2.0.1

**Comment by kiranmairavipati1978** [comment]
Any updates on this? It doesn't work with earlier versions either (from 1.3.7)

**Comment by graemerocher** [comment]
You can always specify the version number explicitly in the meantime

**Comment by alvarosanchez** [comment]
This should be fixed via https://github.com/micronaut-projects/micronaut-aws/issues/325

**Comment by graemerocher** [comment]
Agreed having a BOM for that project would be better

**Comment by jameskleeh** [comment]
Closing this issue as it will be tracked in the AWS issue

**Comment by alvarosanchez** [comment]
`io.micronaut.aws:micronaut-aws-sdk-v1` still isn't in the BOM, so until https://github.com/micronaut-projects/micronaut-aws/issues/325 is implemented, it should be added to the BOM like the other modules.

**Comment by andydoe19** [comment]
> 
> 
> You can always specify the version number explicitly in the meantime

please which version numbers does it work for? Can you provide an example please?

**Comment by ilopmar** [comment]
The commit with this was first included in Micronaut 2.3.1. See https://github.com/micronaut-projects/micronaut-core/commit/d4683be573c5f57d470b8bcb3b775c20fbd976d6

![image](https://user-images.githubusercontent.com/559192/115363599-e4d7b000-a1c2-11eb-80da-f0312ea99de2.png)
