### ISSUE TITLE
Manipulating HttpRequest in Http(Server)Filter fails when an error handler is invoked

### ISSUE THREAD

**Issue by grollinger** [micronaut-projects/micronaut-core#3903]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Define an HttpFilter that manipulates incoming requests (even without changing anything for real).
```java
import io.micronaut.http.HttpRequest;
import io.micronaut.http.HttpRequestWrapper;
import io.micronaut.http.MutableHttpResponse;
import io.micronaut.http.annotation.Filter;
import io.micronaut.http.filter.HttpServerFilter;
import io.micronaut.http.filter.ServerFilterChain;
import org.reactivestreams.Publisher;

@Filter(Filter.MATCH_ALL_PATTERN)
public abstract class VersionFilter implements HttpServerFilter {
  @Override
  public Publisher<MutableHttpResponse<?>> doFilter(
      final HttpRequest<?> request, final ServerFilterChain chain) {

    // Don't actually change anything, just wrap
    final HttpRequest<?> newRequest = new HttpRequestWrapper<>(request); 
    return chain.proceed(newRequest);
  }
}
```
2. Send a request that causes an error handler to be invoked.

### Expected Behaviour

According to the `HttpFilter` [JavaDoc](https://docs.micronaut.io/2.0.1/api/io/micronaut/http/filter/HttpFilter.html):
```
* <p>To modify the request filters can either wrap it (using {@link io.micronaut.http.HttpRequestWrapper} or pass it
* along the chain as is</p>
```

So when I change an incoming request in a filter, I expect this to work.

### Actual Behaviour

We receive an exception in [RoutingInBoundHandler](https://github.com/micronaut-projects/micronaut-core/blob/0930f658b0b3d4dc285d7c35144b22d898542438/http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java#L1321)

```
io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.ClassCastException: io.micronaut.http.HttpRequestWrapper cannot be cast to io.micronaut.http.server.netty.NettyHttpRequest
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
...
Caused by: java.lang.ClassCastException: io.micronaut.http.HttpRequestWrapper cannot be cast to io.micronaut.http.server.netty.NettyHttpRequest
	at io.micronaut.http.server.netty.RoutingInBoundHandler$3.doOnError(RoutingInBoundHandler.java:1321)
	...
```

### Environment Information

- **Operating System**: Linux x86_64 5.7.11
- **Micronaut Version:** 2.0.1
- **JDK Version:** OpenJDK 1.8.0_222

### Example

See https://github.com/grollinger/micronaut-demo/tree/manipulated-request-fails-on-error

Run with: `./gradlew check`

**Comment by yawkat** [comment]
Can reproduce original issue, but upgrading to 3.4.1 fixes this.
