### ISSUE TITLE
Unable to modify response headers with RxHttpClient

### ISSUE THREAD

**Issue by lehotskysamuel** [micronaut-projects/micronaut-core#3936]
### Expected Behaviour

Hi, I'm trying to implement api gateway / proxy service with RxHttpClient that modifies requests and their responses. I'd like to filter some headers from response, e.g. SET-COOKIE header.

### Actual Behaviour

I don't see the header in response, although I can see in my browser (latest Chrome) it's actually being sent.

I only see 4 headers in code:
- Connection: close
- Transfer-Encoding: chunked
- Date: //date
- Content-Type: text/plain

### Steps to Reproduce

```
@Filter("/**")
public class ProxyingFilter extends OncePerRequestHttpServerFilter {

    private final RxProxyHttpClient client;

    //constructor

    @Override
    protected Publisher<MutableHttpResponse<?>> doFilterOnce(HttpRequest<?> request, ServerFilterChain chain) {
                    MutableHttpRequest<?> proxiedRequest = request.mutate()
                             //modify request headers, uri etc...

                    return client.proxy(proxiedRequest)
                            .map(pr -> {  //<---- PR HAS TYPE MutableHttpResponse<?>, SO I'D EXPECT THAT MODIFYING HEADERS IS POSSIBLE
                                pr.getHeaders();  //<---- NEVER CONTAINS SET-COOKIE HEADER BUT BROWSER RECEIVES IT
                                return pr.headers(headers -> headers.remove(HttpHeaderNames.SET_COOKIE));  //<---- DOES NOT REMOVE IT SINCE IT'S NOT EVEN PRESENT ABOVE
                            })
}
```

### Environment Information

- **Operating System**: Windows 10 Pro, 64bit
- **Micronaut Version:** 2.0.0
- **JDK Version:** adopt-openjdk 14.0.2

**Comment by graemerocher** [comment]
Can you upload an example that reproduces the problem?

**Comment by lehotskysamuel** [comment]
I might find more time next week but the code above should be all you need. Just put it into hello world application and you should be able to reproduce the problem. Just try proxying to any endpoint that returns e.g. set-cookie header.

**Comment by lehotskysamuel** [comment]
Hi, sorry for a late reply. I've been looking into this more deeply and found out my issue is not with the RxProxyHttpClient itself but with `CookieHttpSessionStrategy` combined with RxProxyHttpClient. I've pinpointed the error to the last line of `CookieHttpSessionStrategy.encodeId` method. Specifically this line:
```
response.cookie(cookie);
```

I have thought the issue is with the proxy client because the Set-Cookie always returned incorrect value with proxied requests but never did with local requests. Response in the snippet above can be of two instances: NettyStreamedHttpResponse or NettyMutableHttpResponse. Here's the relevant code from both:

NettyStreamedHttpResponse
```
    @Override
    public MutableHttpResponse<B> cookie(Cookie cookie) {
        if (cookie instanceof NettyCookie) {
            NettyCookie nettyCookie = (NettyCookie) cookie;
            String value = ClientCookieEncoder.STRICT.encode(nettyCookie.getNettyCookie());
            headers.add(HttpHeaderNames.SET_COOKIE, value);
        } else {
            throw new IllegalArgumentException("Argument is not a Netty compatible Cookie");
        }
        return this;
    }
```

NettyMutableHttpResponse:
```
    @Override
    public MutableHttpResponse<B> cookie(Cookie cookie) {
        if (cookie instanceof NettyCookie) {
            NettyCookie nettyCookie = (NettyCookie) cookie;
            String value = serverCookieEncoder.encode(nettyCookie.getNettyCookie());
            headers.add(HttpHeaderNames.SET_COOKIE, value);
        } else {
            throw new IllegalArgumentException("Argument is not a Netty compatible Cookie");
        }
        return this;
    }
```

The problem is with ClientCookieEncoder - it strips away cookie settings like http-only, same-site, path etc. That's a problem for session cookies. We had to override CookieHttpSessionStrategy and enforce using ServerCookieEncoder.

**Comment by graemerocher** [comment]
Please provide an example

**Comment by candrews-ns** [comment]
We have seen the same issue and tracked it down to this use of ClientCookieEncoder in NettyStreamedHttpResponse. The workaround described by @lehotskysamuel fixes the immediate problem for us, but I've also put a version of the hello-world-java example application up which reproduces the issue:

https://github.com/candrews-ns/micronaut-session-cookie-repro

This application enables session cookies and implements a trivial use of RxProxyHttpClient (proxying to itself) to trigger use of NettyStreamedHttpResponse.

**Comment by yawkat** [comment]
Thanks for the reproducer, sorry it took so long.
