### ISSUE TITLE
Activate Gradle build cache

### ISSUE THREAD

**Issue by aalmiray** [micronaut-projects/micronaut-core#3941]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. check out the repository
2. `./gradlew clean check  --parallel --continue`
3. note the time it takes to make the build
4. `./gradlew clean check  --parallel --continue`
5. note the time it takes to make the build is very similar to step 2

### Expected Behaviour

Local builds should be faster even if `clean` command is invoked. When the local build cache is enabled:

1. check out the repository
2. `./gradlew clean check  --parallel --continue --build-cache`
3. note the time it takes to make the build
4. `./gradlew clean check  --parallel --continue --build-cache`
5. note the time it takes to make the build is drastically less than in step 2

The following times were captured on OSX 10.5.5 (2.9 GHz 6-Core Intel Core i9; 32 GB 2400 MHz DDR4)

    ------------------------------------------------------------
    Gradle 6.5.1
    ------------------------------------------------------------
    
    Build time:   2020-06-30 06:32:47 UTC
    Revision:     66bc713f7169626a7f0134bf452abde51550ea0a
    
    Kotlin:       1.3.72
    Groovy:       2.5.11
    Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
    JVM:          11.0.1 (Oracle Corporation 11.0.1+13-LTS)
    OS:           Mac OS X 10.15.5 x86_64

    // cold build
    $ gradlew clean check --parallel --continue
    SUCCESS: Executed 457 tests in 3m 14s (4 skipped)
    BUILD SUCCESSFUL in 6m 32s
    389 actionable tasks: 389 executed
    
    // warm up the cache
    $ gradlew clean check --parallel --continue --build-cache
    SUCCESS: Executed 457 tests in 3m 11s (4 skipped)
    BUILD SUCCESSFUL in 6m 3s
    426 actionable tasks: 402 executed, 11 from cache, 13 up-to-date
    
    // cache hits!
    $ gradlew clean check --parallel --continue --build-cache
    BUILD SUCCESSFUL in 39s
    426 actionable tasks: 133 executed, 221 from cache, 72 up-to-date
    
    // cache hits!
    $ gradlew check --parallel --continue --build-cache
    BUILD SUCCESSFUL in 4s
    389 actionable tasks: 33 executed, 356 up-to-date

Enable local build cache for anyone by adding `org.gradle.caching=true` to `gradle.properties`.

https://docs.gradle.org/current/userguide/build_cache.html#sec:build_cache_enable

### Actual Behaviour

Builds do not take advantage of local Gradle build cache.

### Environment Information

- **Operating System**: all
- **Micronaut Version:** N/A
- **JDK Version:** N/A

**Comment by melix** [comment]
Work is already in progress as part of our Gradle Enterprise integration. There's a lot to get there, because unfortunately the Micronaut build has lots of undeclared inputs, and there's this issue with non reliable annotation processing which could easily become a problem with caching.

**Comment by melix** [comment]
Caching issues have been fixed and the build cache is now enabled on the `3.2.x` branch. Let us know if you are seeing anything suspicious.
