### ISSUE TITLE
Update remaining modules to Micronaut 2.0

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#3946]
## Summary 

This is a follow up on #3024. 

For **Micronaut 2.1** all the remaining modules need to be updated to Micronaut 2.

| Symbol | Status |
| :---: | --- |
| ✅| Worked with Micronaut 2. It was tested before Micronaut 2.0 release. Needs to be updated before Micronaut 2.1 |
| 🆗 | Existing PR updated with latest changes. Read latest PR comments before merging |
| 2️⃣ | Release version 2.0.0 |
| ✳️| Works with Micronaut 2. However, it requires a new release, because either it uses an old Micronaut version, or needed changes to make it work with Micronaut 2 | 
| ❌| Doesn't work with Micronaut 2 |
| ❓| Hasn't been tested with Micronaut 2 |
| ☑️ | Not Applicable |

### Data Access

| Module | Micronaut version | Status | Upgrade PR |  Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Data](https://github.com/micronaut-projects/micronaut-data) | 2.0.0 | 2️⃣ |  | | [#518](https://github.com/micronaut-projects/micronaut-data/issues/518) | |
| [MongoDB](https://github.com/micronaut-projects/micronaut-mongodb) | 3.0.0  | 2️⃣ |  |  |
| [Neo4j Configuration](https://github.com/micronaut-projects/micronaut-neo4j) | 4.0.0 | 2️⃣|  |  |
| [Cassandra](https://github.com/micronaut-projects/micronaut-cassandra) | 3.0.0 | 2️⃣ |  | |

### Analytics

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Micrometer](https://github.com/micronaut-projects/micronaut-micrometer) | 3.0.0  | 2️⃣  |  |  |
| [Ratelimiter](https://github.com/micronaut-projects/micronaut-ratelimiter) | 1.3.0.BUILD-SNAPSHOT |✅  | [#2](https://github.com/micronaut-projects/micronaut-ratelimiter/pull/2) |  |

### Languages

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Kotlin](https://github.com/micronaut-projects/micronaut-kotlin) | 2.1.0 (Kotlin 1.4.10) | 2️⃣  |  |  |

### Reactive

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [RxJava 1](https://github.com/micronaut-projects/micronaut-rxjava1) | 1.3.5. Won't be upgraded to Micronaut 2 | ❌ | [#1](https://github.com/micronaut-projects/micronaut-rxjava1/pull/1) | |

### Misc

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Picocli](https://github.com/micronaut-projects/micronaut-picocli) | 3.0.0 |  2️⃣ |  |  |
| [Test](https://github.com/micronaut-projects/micronaut-test) | 2.0.0 (Kotlin 1.3.x) and 2.1.0.M1 (Kotlin 1.4.10) | 2️⃣ | |  |
| [ACME](https://github.com/micronaut-projects/micronaut-acme) | 2.0.0 |  2️⃣ |  |  |

### Messaging

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Kafka](https://github.com/micronaut-projects/micronaut-kafka) | 3.0.0 | 2️⃣ | | |

### Cloud

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [GCP](https://github.com/micronaut-projects/micronaut-gcp) | 3.0.0  | 2️⃣|  |  |
| [Netflix](https://github.com/micronaut-projects/micronaut-netflix) | 2.0.0  | 2️⃣|  |  |

### API

| Module | Micronaut version | Status | Upgrade PR | Issues |
| :---: | :---: | :---: | :---: | :---: |
| [Micronaut GraphQL](https://github.com/micronaut-projects/micronaut-graphql) | 2.0.0  | 2️⃣ |   | |
| [JAX-RS](https://github.com/micronaut-projects/micronaut-jaxrs) | 1.3.5 | ❌ |  [#9](https://github.com/micronaut-projects/micronaut-jaxrs/pull/9)  [#69](https://github.com/micronaut-projects/micronaut-jaxrs/pull/69)|  |
| [Jackson XML](https://github.com/micronaut-projects/micronaut-jackson-xml) | 2.0.0 | 2️⃣ |  |  |
| [Open API](https://github.com/micronaut-projects/micronaut-openapi) | 2.0.0  | 2️⃣ |  |  |
| [Spring](https://github.com/micronaut-projects/micronaut-spring) | 1.3.5 | ❌ | [#57](https://github.com/micronaut-projects/micronaut-spring/pull/57) | [#58](https://github.com/micronaut-projects/micronaut-spring/issues/58) |

**Comment by sdelamo** [comment]
I've released a new version of [jackson-xml](https://github.com/micronaut-projects/micronaut-jackson-xml) with Micronaut 2.0.1. It is in the 2.1.x bom of micronaut-core.

**Comment by sdelamo** [comment]
I've released a new version of [picocli](https://github.com/micronaut-projects/micronaut-picocli) module with Micronaut 2.0.1. 

Related PRs in core: 

- [build: bump up picocli to 4.5.1 ](https://github.com/micronaut-projects/micronaut-core/pull/4041)
- [Bump micronaut-picocli to 3.0.0](https://github.com/micronaut-projects/micronaut-core/pull/4040)

**Comment by esocode** [comment]
Is there a specific reason that micronaut-micrometer 3.0.0 hasn't been added to the 2.0.2/3 BOM? Services using micrometer are affected by a bug in micrometer versions before 1.5.3 and 3.0.0 includes a newer dependency.

**Comment by ilopmar** [comment]
The micronaut-micrometer version included in 2.0.2/2.0.3 BOM is 2.0.0. See https://github.com/micronaut-projects/micronaut-core/blob/2.0.x/gradle.properties#L59

**Comment by esocode** [comment]
Yes, I know. My question is, why hasn't the version not been bumped to 3.0.0? From the changelog the only change in 3.0.0 was to adapt it to micronaut 2.0. Wouldn't it make sense to include it into micronaut 2.0 then?

**Comment by ilopmar** [comment]
@esocode That would be a breaking change in Micronaut 2.0.x. Micronaut Micrometer 3.0.0 is the default in Micronaut 2.1 https://github.com/micronaut-projects/micronaut-core/blob/2.1.x/gradle.properties#L60

**Comment by ilopmar** [comment]
@esocode Just to clarify this a little bit more. You can manually upgrade both micrometer and micronaut-micrometer version if you want and if it works for you. We can't include those dependencies by default because we don't want to take the risk of breaking user apps with the upgrade in a patch version. We are following this strategy https://github.com/micronaut-projects/micronaut-core/wiki/Module-Upgrade-Strategy
