### ISSUE TITLE
POST Request with undefined URL cause connection issue

### ISSUE THREAD

**Issue by myspec** [micronaut-projects/micronaut-core#3979]
### Steps to Reproduce

Make a POST request to make 404 (or 403)  twice, (second request has issue)

POST /blabla HTTP/1.1
Host: localhost:8080
Content-Type: text/plain

dd

Use Postman( or YARC. ) 
with cURL or body is empty, issue doesn't reproduce.

### Expected Behaviour
404 or 403 error

### Actual Behaviour
First call make a 404 error.
But second, client blocked on request. Server doesn't receive any request.

### Environment Information
micronaut 2.0.1 has this issue.
2.0.0 or 2.0.0RC works fine

- **Operating System**: WINDOWS10, AWS Linux
- **Micronaut Version:** 2.0.1
- **JDK Version:** OpenJDK 14

### Example Application
https://github.com/micronaut-guides/creating-your-first-micronaut-app

change configuration to micronaut version 2.0.1 
(2.0.0 has no issue)

**Comment by jameskleeh** [comment]
"with cURL or body is empty, issue doesn't reproduce."

If you can't reproduce the issue with curl, then I would assume the issue is in your client.

I can't reproduce the issue with the example app provided with curl or Postman

**Comment by jameskleeh** [comment]
Closing due to lack of feedback

**Comment by myspec** [comment]
@jameskleeh 
Sorry for my feedback.
I found how to reproduce with wget.

$ mn create-app hello-world
$ cd hello-world
$ gradlew.bat run


$ wget --method POST --body-data '{test}' 'http://localhost:8080/notexist1' 'http://localhost:8080/notexist2'
--2020-09-25 00:58:03--  http://localhost:8080/notexist1
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-09-25 00:58:04 ERROR 403: Forbidden.

--2020-09-25 00:58:04--  http://localhost:8080/notexist2
Reusing existing connection to [localhost]:8080.
HTTP request sent, awaiting response...


-----

from windows 10 (19041.508)
$ java --version
java 14.0.1 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

**Comment by myspec** [comment]
> Closing due to lack of feedback

please, check new comment.
