### ISSUE TITLE
"Unresolved directive" in documentation

### ISSUE THREAD

**Issue by agilob** [micronaut-projects/micronaut-core#3995]
![image](https://user-images.githubusercontent.com/2544251/91755439-a0a78900-ebba-11ea-8e48-c6b3f3a8e6b3.png)

You can find "Unresolved directive" many times in 2.0.1 docs, havent checked any others.

https://docs.micronaut.io/latest/guide/index.html#distributedConfigurationAwsParameterStore

I think that's a documentation bug - which is a phase I don't write often.

**Comment by graemerocher** [comment]
It is. The documentation moved to the AWS module, we will fix it. Thanks

**Comment by jameskleeh** [comment]
Duplicate of #3825
