### ISSUE TITLE
Do not inject Netty's EventLoopGroup as a primary ExecutorService

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#4004]
It's caused by `@Primary` annotation added for default `EventLoopGroup` in `DefaultEventLoopGroupRegistry`.

Would it be possible to allow specifying something like `@Primary(of = EventLoopGroup.class)`? That would restrict injecting `ExecutorService` as a primary implementation.

**Comment by jameskleeh** [comment]
@dstepanov Can you describe what issue is being caused by the current behavior?

**Comment by dstepanov** [comment]
@jameskleeh https://github.com/micronaut-projects/micronaut-core/issues/3868 I wouldn't expect Netty executor to be injected as a default one it probably can cause some performance problems if it's used to execute long-running tasks.

**Comment by jameskleeh** [comment]
We will remove the primary qualifier
