### ISSUE TITLE
Micronaut validator is not compatible with Hibernate BeanValidationEventListener

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#4030]
In `2.0.1`.

Micronaut's `DefaultValidator` is not compatible with Hibernate `BeanValidationEventListener`, because produced `ConstraintViolation`-s frequently contains null `leafBean` and [this line](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/cfg/beanvalidation/BeanValidationEventListener.java#L124) crashes with NPE. Please note, that I don't use Hibernate Validator, only Hibernate with Micronaut validator.

Looking at `DefaultValidator` and spots where it produces `DefaultConstraintViolation`, there are three cases where `leafBean` is `null`, and only one where is not. For example if you define your own validator with `@Validation` annotation to be used directly on entity class:

```
@Validation class MyEntity {}
```

This will crash with NPE from within Hibernate. This scenario is documented on `ConstraintViolation.getLeafBean()`: *Returns the bean instance the constraint is applied on if it is a bean constraint*. So, at least this kind of produced `ConstraintViolation` is wrong, and in this scenario `leafBean` should be set to `rootBean`, but there're two other usages of `DefaultConstraintViolation` constructor where `leafBean` is also `null`, which should be reviewed separately.

Refs:

1. Line which crashes in Hibernate [here](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/cfg/beanvalidation/BeanValidationEventListener.java#L124)
1. What should be set as a `leafBean` in `ConstraintViolation` in different scenarios is described [here](https://docs.oracle.com/javaee/7/api/javax/validation/ConstraintViolation.html#getLeafBean--)
1. Spots where there's a constraint violation created with `null` `leafBean`: [one](https://github.com/micronaut-projects/micronaut-core/blob/2.0.x/validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java#L861), [two](https://github.com/micronaut-projects/micronaut-core/blob/2.0.x/validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java#L1031), [three](https://github.com/micronaut-projects/micronaut-core/blob/2.0.x/validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java#L1084)

**Comment by graemerocher** [comment]
Seems like you have gone a long way to diagnose the problem, would you like to send a PR?

**Comment by l0co** [comment]
The only fix I can think about is to use `rootBean` as a `leafBean` for all instances where it previously was `null`. PR #4058 submitted.
