### ISSUE TITLE
Controller initialisation loop leading to CPU usage due to missing configuration value

### ISSUE THREAD

**Issue by brunovale91** [micronaut-projects/micronaut-core#4045]
#4020 # Steps to Reproduce

1. Create micronaut application with a Controller and a test stream endpoint
```
 @ExecuteOn(TaskExecutors.IO)
    @Get("test/stream", produces = [MediaType.TEXT_EVENT_STREAM])
    fun testStream(): Publisher<Event<Counter>> {
        logger.debug { "New test stream connected" }
        return Flowable.intervalRange(
            0,
            11,
            5,
            5,
            TimeUnit.SECONDS
        ).map {
            logger.debug { "New test stream event $it" }
            createCounterEvent(it, Counter(it))
        }
    }
```
2. Create bean with a configuration property
```
@Singleton
class ServiceImpl(
    @Value("\${propertyt}")
    val property: String
) : Service {
```
3. Fail to provide property in configuration

### Stracktrace
```
{"time":"2020-09-08T10:56:28.401+01:00","@version":"1","message":"Found matching exception handler for exception [Failed to inject value for parameter [property] of class: com.example.ServiceImpl\n\nMessage: Error resolving property value [${property}]. Property doesn't exist\nPath Taken: new Controller(EventConsumer eventConsumer,[Service service]) --> new ServiceImpl(ServiceStub serviceStub,[String property])]:  Throwable -> Controller#HttpResponse error(HttpRequest request,Throwable e)","logger_name":"io.micronaut.http.server.netty.RoutingInBoundHandler","thread_name":"nioEventLoopGroup-1-2","level":"DEBUG","level_value":10000}
```
### Expected Behaviour
Http call returns a 500 error and stops trying to initialise bean.

### Actual Behaviour
Http call hangs trying to initialise bean in an infinite loop leading to CPU usage.

### Environment Information

- **Operating System**: adoptopenjdk:11-jre
- **Micronaut Version:** 2.0.1
- **JDK Version:** 11

**Comment by graemerocher** [comment]
Annotation `ServiceImpl` with `@Context` to ensure validation occurs at startup

**Comment by brunovale91** [comment]
> Annotate `ServiceImpl` with `@Context` to ensure validation occurs at startup

In this case I don't mind bean is lazy loaded. The issue I wanted to highlight here is the way how the exception is handled since in my case it causing high CPU usage when trying to initialise the bean in an infinite loop.

In my opinion the correct behaviour would be to call the endpoint and get an error, even if the error was a 404 since the controller was not properly initialised.

**Comment by graemerocher** [comment]
Agreed that this should be improved

**Comment by jameskleeh** [comment]
@brunovale91 I can't reproduce. Please upload an example application that reproduces the issue

**Comment by brunovale91** [comment]
Hi,

I could reproduce the issue on an example app: https://github.com/brunovale91/micronaut-example

The loop is related with error handling in controllers. From my troubleshooting I could understand that it only happens when you handle a throwable exception and any other exception.

For example, if I setup a global not found handler then all endpoints that don't exist trigger the loop.

If I setup a bad request exception then it just triggers the loop when I call an endpoint that is defined in that controller.
