### ISSUE TITLE
Problem using @Body on Groovy Declarative Client

### ISSUE THREAD

**Issue by ricfeatherstone** [micronaut-projects/micronaut-core#4048]
I'm not sure if this is a bug, or if I am missing a magic Groovy annotation on my Client but I am not able to using the `@Body` 
annotation to control the json serialisation 

### Steps to Reproduce

```
@MicronautTest
class BodySpec extends Specification {
    @Inject
    WorkingClient working

    @Inject
    BrokenClient broken

    void 'test @Body works on declarative client'() {
        expect:
        // Body = {"role_id":"xxx"}
        'xxx' == working.apiMethod('xxx')
        // Body = xxx
        'xxx' == broken.apiMethod('xxx')
    }
}

@Client('/')
interface WorkingClient {
    @Post
    String apiMethod(String role_id)
}

@Client('/')
interface BrokenClient {
    @Post
    String apiMethod(@Body('role_id') String roleId)
}

@Controller('/')
class ExampleController {
    @Post
    String apiMethod(@Body('role_id') String roleId) {
        roleId
    }
}
```

### Expected Behaviour

Both apiMethod calls should send `{"role_id":"xxx"}` as the body.

### Actual Behaviour

The BrokenClient.apiMethod call sends `xxx` as the body 

`io.micronaut.http.client.exceptions.HttpClientResponseException: Invalid JSON: Unexpected character ('x' (code 120))`
 
### Environment Information

- **Operating System**: Fedora
- **Micronaut Version:** 2.0.1
- **JDK Version:** OpenJDK Runtime Environment Zulu14.29+23-CA (build 14.0.2+12)

**Comment by sdelamo** [comment]
In a declarative HTTP Client method parameter `@Body('role_id')` will not generate a `{"role_id":"xxx"}` json payload.  

Java doc of the `value` of `@Body`

> A Key or qualifier within the body. For example a reference to a nested JSON attribute

You could create a POJO for the body: 

```groovy
package com.example

import com.fasterxml.jackson.annotation.JsonProperty
import io.micronaut.core.annotation.Introspected

@Introspected
class Role {

    @JsonProperty("role_id")
    String roleId
}
```

Your client : 

```
@Client
interface BrokenClient {
    @Consumes(MediaType.TEXT_PLAIN)
    @Post
    String apiMethod(@Body Role roleId)
}
```

Because your client is consuming a media type other than `application/json`, I annotated the method with  `@ Consumes(MediaType.TEXT_PLAIN)`


Your Controller

```groovy
@Controller
class ExampleController {
    @Produces(MediaType.TEXT_PLAIN)
    @Post
    String apiMethod(@Body('role_id') String roleId) {
        roleId
    }
}
```

Your controller is producing a media type other than `application/json` annotate it  with `@Produces(MediaType.TEXT_PLAIN)`

**Comment by ricfeatherstone** [comment]
Ignore the media type, it was just enough of a code sample to explain what was occurring.

Thanks for the explanation but the behaviour is slightly unexpected given how it works on the Controller side. 

I am using a pojo to get the required outcome but if in the future I simply want to have a parameter mapped to a json field that does not follow Java naming standards without having to wrap a single field into a pojo is this possible?

If not, is it possible to make the `@Body` annotation work like this on the client side?

**Comment by sdelamo** [comment]
> I simply want to have a parameter mapped to a json field that does not follow Java naming standards without having to wrap a single field into a pojo is this possible?

You want `@Body("role_id") String roleId` in a client to generate a JSON payload such as `{"role_id": "XXX"}`. However, I don't think @Body has ever behaved like that. The way it behaves matches what the Javadoc says, in my opinion. 
Changing that behaviour will be a breaking change which will need to wait until Micronaut 3.0

Moreover, I don't think we any other annotation which does what you describe. I will personally recommend you to use a POJO as the method parameter.

**Comment by ricfeatherstone** [comment]
It's not whether it ever did that, it's more why doesn't it? At the moment you are failing the principle of least surprise, `@Body` works on Classes the same but not on primitive parameters. I initially asked how to do this on the Micronaut Gitter chat and was told it should work and to file an issue if it didn't, so it's not just me who expected it to work on the Client the same as on the Server side.

I'm not sure it's a breaking change because if you use that annotation on a Client at the moment, the Client will not work so no one will be using it, therefore nothing will break.

I am happy to wait as currently I do not need this functionality, but can see it may be useful in the future if I have one parameter to pass and it does not meet the Java naming conventions. In this case the overhead of creating a Class to wrap one parameter is too much imo.

I think it would be a useful feature to add based on the above
