### ISSUE TITLE
Health endpoint should return 503 if status is DOWN

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#405]
The `/health` endpoint should return an appropriate response code depending on the health status

**Comment by jameskleeh** [comment]
What if the status is unknown?

**Comment by rogelio-o** [comment]
Hi!

Can I give a try?

**Comment by graemerocher** [comment]
Spring and Grails report 200 for unknown, but allow the codes to be mapped to other values like `management.health.status.http-mapping.UNKNOWN=404`

**Comment by graemerocher** [comment]
@rogelio-o You can if you wish, although it is not the most trivial issue to resolve as a first issue.

I think this needs to be handled as a `HttpServerFilter` since we can't really put anything web related in `HealthEndpoint`

**Comment by rogelio-o** [comment]
Ok @graemerocher, no problem. I've taken an approach according to what you said about the filter: https://github.com/rogelio-o/micronaut-core/commit/4b37c7ee4638bc6f8617657ebe7aa9921218400f

If you think it is good enough, I can keep going with this feature (adding tests and refactoring some code). If not, no problem, I can start contributing with some other issue.

**Comment by graemerocher** [comment]
@rogelio-o You were are on the right track, but since I needed this done for M3 today I finished it off. Thanks for your interest in contributing.

**Comment by rogelio-o** [comment]
No problem! I’ll check another issue to contribute. Thanks!
