### ISSUE TITLE
Not possible to configure read-timeout on ProxyHttpClient

### ISSUE THREAD

**Issue by MikiLoz92** [micronaut-projects/micronaut-core#4090]
### Steps to Reproduce

1. Configure the default HTTP client properties:
```
micronaut:
  http:
    client:
      read-timeout: 15s
      read-idle-timeout: 15s
```
2. Inject a ProxyHttpClient on a simple HttpFilter. Annotate the injection site of the client with `@Client(configuration = DefaultHttpClientConfiguration::class)`. Configure the filter to redirect the request to `localhost:8001`, for example, creating a sort of gateway.
3. Open a terminal, and create a simple TCP server that will not reply the request: `$ nc -l 8001`
3. Make a request to the gateway's port. The request will be proxied to the netcat server, which will not respond.

### Expected Behaviour

Because read-timeout and read-idle-timeout have been set, the TCP connection should be dropped in 15s and the netcat server should end, since there is no TCP traffic.

### Actual Behaviour

However, it is **not** dropped because these settings do not seem to affect the ProxyHttpClient. Making the same steps with an instance of an HttpClient instead of a ProxyHttpClient seems to work, though.

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.0.2
- **JDK Version:** 1.8

**Comment by MikiLoz92** [comment]
any news on this?

**Comment by graemerocher** [comment]
Perhaps provide an example with steps to reproduce. Thanks

**Comment by graemerocher** [comment]
PR submitted
