### ISSUE TITLE
Eager initialization of singletons fails

### ISSUE THREAD

**Issue by jpragma** [micronaut-projects/micronaut-core#4096]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create new "Messaging application" using micronaut.io/launch (all default settings)
2. Setup eager singleton initialization either by modifying Application.main or create TestApplicationContextBuilder and reference it from @MicronautTest 
3. Run the application or execute the unit test

### Expected Behaviour

Application context should start successfully

### Actual Behaviour

Application context fails to start with BeanInstantiationException

### Stacktrace
```
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.apache.kafka.clients.producer.KafkaProducer] could not be loaded: Error instantiating bean of type  [org.apache.kafka.clients.producer.KafkaProducer]

Message: Missing bean argument [AbstractKafkaProducerConfiguration producerConfiguration] for type: org.apache.kafka.clients.producer.KafkaProducer. Required arguments: AbstractKafkaProducerConfiguration producerConfiguration

	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1540)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2771)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:228)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.0.2 (but also older versions)
- **JDK Version:** 11

### Example Application

https://github.com/jpragma/mntests/tree/master/kafka-eager-init-demo

**Comment by jpragma** [comment]
Shouldn't **`@Parameter`** annotation in **_KafkaProducerFactory.createProducer_** and **_KafkaConsumerFactory.createConsumer_** be removed? It looks like it fixes the issue with eager initialization of these factories, and _AbstractKafkaConsumerConfiguration_ is successfully injected into them without this annotation.
If I understand correctly `@Parameter` is used in Configuration classes or in Factories in conjunction with @EachBean..

**Comment by gls-dev** [comment]
There is a similar issue using the `@Factory` examples from the documentation and generating beans using `@EachBean`. Throwing a `DisabledBeanException` generates the following -
`Error starting Micronaut server: Bean definition [com.example.Engine] could not be loaded: Engine configuration disabled` - when `eagerInitSingletons` is set to true. The same occurs when using a `MicronautRequestHandler` even when overriding the default behaviour of eager instantiation in `newApplicationContextBuilder`. Happy to provide a sample app if need be.

Micronaut version - 2.0.2
Kotlin 1.4.10
Gradle 6.5.1

**Comment by graemerocher** [comment]
@gls-dev examples welcome

**Comment by gls-dev** [comment]
@graemerocher please see - https://github.com/gls-dev/micronaut-demo. It has been upgraded to Micronaut version 2.0.3. As mentioned in the README, the application fails to start if setting `eagerInitSingletons()` to true. `SampleRequestHandlerTest` also fails for similar reasons and overriding `newApplicationContextBuilder()` does not affect the outcome of the test.

**Comment by zdegner** [comment]
I see the same thing with HTTP clients when eager singletons are enabled. If health-check is not `true` the service fails to startup. (Micronaut 2.0.2)

```
 20:01:48.438 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Bean definition [io.micronaut.context.event.ApplicationEventListener] could not be loaded: HTTP
Client Health Check not enabled
```

https://github.com/micronaut-projects/micronaut-core/blob/c5699e4817c62d577c26ef30eeb088efc596f4e7/http-client-core/src/main/java/io/micronaut/http/client/ServiceHttpClientFactory.java#L125

Seems like a similar scenario involving DisabledBeanException.

**Comment by graemerocher** [comment]
Thanks for the feedback, PR submitted
