### ISSUE TITLE
HttpStreamsHandler produces broken JSON body on post requests in some cases

### ISSUE THREAD

**Issue by klu2** [micronaut-projects/micronaut-core#410]
I have a Vue.js app with a generated Swagger API, producing POST requests with JSON bodies. That works fine usually, but sometimes I get errors about invalid JSON in the POST body.

I checked the request in firebug and chrome, it is always the same, but from time to time the server really gets only half of the JSON body, in JsonContentProcessor.onData I can clearly see that if I debug into that.

Going back where this comes from brought me to `HttpStreamsHandler.handleReadHttpContent`:

```
    private void handleReadHttpContent(ChannelHandlerContext ctx, HttpContent content) {
        if (!ignoreBodyRead) {
            if (content instanceof LastHttpContent) {

                if (content.content().readableBytes() > 0 ||
                    !((LastHttpContent) content).trailingHeaders().isEmpty()) {
                    // It has data or trailing headers, send them
                    ctx.fireChannelRead(content);
                } else {
                    ReferenceCountUtil.release(content);
                }

                removeHandlerIfActive(ctx, ctx.name() + "-body-publisher");
                currentlyStreamedMessage = null;
                consumedInMessage(ctx);

            } else {
                ctx.fireChannelRead(content);
            }

        } else {
            ReferenceCountUtil.release(content);
            if (content instanceof LastHttpContent) {
                ignoreBodyRead = false;
                if (currentlyStreamedMessage != null) {
                    removeHandlerIfActive(ctx, ctx.name() + "-body-publisher");
                }
                currentlyStreamedMessage = null;
            }
        }
    }
```

It turns out that sometimes the `content` (coming from netty) is not a LastHttpContent, but a `io.netty.handler.codec.http.DefaultHttpContent`. In that case we're jumping directly to else-branch (`ctx.fireChannelRead(content)`) and subsequently we end up in `JsonContentProcessor.onData` with only half of the JSON stream.

Interestingly, if I resend exact the same request from firebug a second time, then it works, and that is reproducable.

I know that sounds weird, and unfortunately my code is part of a bigger project that I cannot share; I also don't know if I could easily extract a demo app for you to check that. 

That is why I debugged into micronaut, trying to figure our what is going on here, and I think the root cause is somewhere in the method above, but I'm no netty expert. 

Hope you can somehow deal with it, otherwise I'd need to try extract a dummy project there....

**Comment by graemerocher** [comment]
Maybe if you can provide a little more details, like what the method signatures looks like. How you are calling it etc. that would help

**Comment by graemerocher** [comment]
Note that `JsonContentProcessor.onData` is designed to take "only half the JSON" in that it receives a stream of bytes, that could be incomplete. What should be happening is that `JacksonProcessor.needMoreInput()` returns false and then a request is sent for more data to fed to `JacksonProcessor`. This allows Micronaut and Netty to read the request stream chunk by chunk.

See https://github.com/micronaut-projects/micronaut-core/blob/master/runtime/src/main/java/io/micronaut/jackson/parser/JacksonProcessor.java#L148

**Comment by graemerocher** [comment]
Ok thanks for the report, will investigate and try to reproduce

**Comment by klu2** [comment]
> What should be happening is that JacksonProcessor.needMoreInput() returns false

Correct, that happens. `JacksonProcessor:136` 

Next time I'm in `JsonContentProcessor.onData` I see the second half of the JSON then.

Then somehow I get back to `JacksonProcessor.doOnComplete()` and `needMoreInput()` still returns true, that is why the `JsonEOFException` is thrown.

**Comment by klu2** [comment]
Some more findings, maybe that helps:

After the first bunch of JSON, I get into `SingleThreadedBufferingSubscriber:89` (`upstreamState` is `DEMANDING`), and in the finally block the `upstreamState` is set to `IDLE` (line 101)

Next time `SingleThreadedBufferingSubscriber.onNext` is called (with the second part of the JSON), I get into the switch case 'IDLE' then, the message is added to the upstreamBuffer (which is empty at that time)

**Comment by graemerocher** [comment]
I tried to add a test to replicate, but so far no luck https://github.com/micronaut-projects/micronaut-core/commit/2b3dd8048cc165397ac77af3f06e382134b55050

**Comment by klu2** [comment]
> I tried to add a test to replicate, but so far no luck 

It has nothing to do with big and concurrent requests. My request is tiny (724 bytes) and it's the only concurrent request at that time.

**Comment by klu2** [comment]
tried out your fix, that makes it work!

**Comment by klu2** [comment]
if you can reproduce that in a test and make the fix go to M3, I'm happy :)
meanwhile I can live with patching that class

**Comment by graemerocher** [comment]
Ah great.. thanks I was waiting for the build to upload the snapshots to ask if it worked for you. Thanks for all the feedback. I am concerned I cannot reproduce, however, I am glad we can get this fix into M3 (which is coming out tomorrow).
