### ISSUE TITLE
VersionUtils class is not compatible with GraalVM

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#4100]
The method used to get the Micronaut version https://github.com/micronaut-projects/micronaut-core/blob/2.0.x/core/src/main/java/io/micronaut/core/version/VersionUtils.java#L46 doesn't work with GraalVM.

**Comment by graemerocher** [comment]
Should be replaced by a field substitution since the version is already known at compilation time

**Comment by jameskleeh** [comment]
@graemerocher What do you mean by a field substitution?

**Comment by graemerocher** [comment]
Actually I am not sure if a substitution is necessary. It could be fixed by initializing VersionUtils at build time. @ilopmar maybe have a go at that

**Comment by ilopmar** [comment]
After giving this a try and test a few things, this code doesn't work either when running on the JVM.

I've put a few `println`s to see what's going on.

I've created a simple test application that has this on a controller:
```java
System.out.println("VersionUtils.MICRONAUT_VERSION = " + VersionUtils.MICRONAUT_VERSION);
```

### Gradle

Executing the application with `./gradlew run` works because https://github.com/micronaut-projects/micronaut-core/blob/53c39de0ffc7f2cdd9569014d9b1816ad1e31e23/core/src/main/java/io/micronaut/core/version/VersionUtils.java#L47 `getImplementationVersion()` method returns the right version.

I've also tried commenting out that line and trying to get the version from the manifest and it works. This is the output of some `println`s I've added. You can see that the `MANIFEST.MF` that contains the right version is pulled from the right jar file (micronaut-core):

```
classPath = jar:file:/home/ivan/.m2/repository/io/micronaut/micronaut-core/2.1.0.BUILD-SNAPSHOT/micronaut-core-2.1.0.BUILD-SNAPSHOT.jar!/io/micronaut/core/version/VersionUtils.class
manifestPath = jar:file:/home/ivan/.m2/repository/io/micronaut/micronaut-core/2.1.0.BUILD-SNAPSHOT/micronaut-core-2.1.0.BUILD-SNAPSHOT.jar!/META-INF/MANIFEST.MF

micronautVersion = 2.1.0.BUILD-SNAPSHOT
```

### Java 

Executing the fatjar application doesn't work. Trying to get the version from the `getImplementationVersion()` method returns `null`. And then, using the fallback to get it from the manifest doesn't work either. You can see that the `VersionUtils.class` is pulled directly from the fatjar and from there the "calculated" `MANIFEST.MF` is the only one available (the one from the application, not from micronaut-core). So that manifest doesn't include the micronaut version

```
classPath = jar:file:/home/ivan/workspaces/micronaut-graal-tests/micronaut-basic-app/build/libs/basic-app-0.1-all.jar!/io/micronaut/core/version/VersionUtils.class
manifestPath = jar:file:/home/ivan/workspaces/micronaut-graal-tests/micronaut-basic-app/build/libs/basic-app-0.1-all.jar!/META-INF/MANIFEST.MF

micronautVersion = null
```

### Native image

As we already knew this doesn't work either. Without any additional configuration the `VersionUtils` class is already being initialized at build time. During native image build I see the output of the `println`s I added and they are exactly like running the fatjar application (previous section).
Delaying the class initializacion to runtime with `--initialize-at-run-time=io.micronaut.core.version.VersionUtils` doesn't run that code during native image creating and postpone it until I send a request to my endpoint. The output, is pretty much again the same as the one running the fatjar app although the `VersionUtils` class can't be found and the code to look for the version in the manifest is not even executed.


@graemerocher @jameskleeh any idea of how to get the right version at compile time that doesn't involve parsing the manifest file so it also works when running the fatjar?

Should we go with an approach similar to the one used in Starter https://github.com/micronaut-projects/micronaut-starter/blob/286357626a92cb79793e7832d24776b0f7722329/starter-core/build.gradle#L23-L45 but adding only the `projectVersion` instead all the versions in the BOM?

**Comment by graemerocher** [comment]
Well you guys wanted fat jars 😉
