### ISSUE TITLE
Micronaut HttpServer configuration parameters not working anymore in 2.0.1.

### ISSUE THREAD

**Issue by ashish-sharma09** [micronaut-projects/micronaut-core#4114]
# Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run the test HelloWorldController.
2. We used Intellij to run the test.

### Expected Behaviour

The test should not pass with status code 200 as the value of ```micronaut.server.idle-timeout``` is lower than the sleep in "HelloWorldController" and that should prevent the request from completing successfully and RestAssured should fail with the following error:

```org.apache.http.NoHttpResponseException: localhost:<port> failed to respond```

### Actual Behaviour
The test works fine and ```micronaut.server.idle-timeout``` seems to be ignored.

The test fails as expected in version 1.x.x (we tried 1.3.7)

### Environment Information

- **Operating System**: Mac OS 10.15.4
- **Micronaut Version:** 2.0.1
- **JDK Version:** 11.0.7

### Example Application

- https://github.com/ashish-sharma09/mn-server-timeout

**Comment by jameskleeh** [comment]
This is happening because you are blocking the event loop thread. The thread that schedules the checking for idle events is the same thread being blocked, thus the scheduled checks happen after the Thread.sleep has occurred. Beyond having the idle state handler run on a different thread (which doesn't seem to be an option, and I'm not sure its desirable), I don't know what could be done here. Thoughts @graemerocher ?

**Comment by ashish-sharma09** [comment]
I can try @ExecuteOn and have the controller running on IO thread and see if it helps.

**Comment by graemerocher** [comment]
That would be the correct fix

**Comment by ashish-sharma09** [comment]
And it does for this example. Also in our application, we have "micronaut.server.thread-selection: AUTO" configuration in place, configuring this for our integration test makes our test work as expected too. This works as expected hence closing this ticket now.

Thks @jameskleeh and @graemerocher for your inputs, much appreciated.
