### ISSUE TITLE
HTTP client does not reject untrusted certificates unless trust store is configured

### ISSUE THREAD

**Issue by myles-anderson-ox** [micronaut-projects/micronaut-core#4116]
### Steps to Reproduce

1. Create a Micronaut application with feature http-client
2. Create a controller
3. Configure the server to enable ssl and use a self signed certificate
4. Create a test that calls the controller with an http client that points to the controller's https endpoint

### Expected Behaviour

An SSLException is thrown due to an unknown certificate

### Actual Behaviour

The client accepts the certificate and gets a valid response

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** tested with 1.3.5 and 2.0.2
- **JDK Version:** 8

### Example Application

- https://github.com/myles-anderson-ox/micronaut-http-ssl-bug
Run `gradle test` and see 1 out of 3 tests fail. This may require an update to the trust store configuration in `HttpSslBugTest.java` if your jdk default cacerts has been modified.

**Comment by yawkat** [comment]
Code in question: https://github.com/micronaut-projects/micronaut-core/blob/a6c0bae9431e0cc072b3d6940e11c168986ebb2e/http-client/src/main/java/io/micronaut/http/client/netty/ssl/NettyClientSslBuilder.java#L132

While it seems sensible not to use the `InsecureTrustManagerFactory` by default (it even has a warning in its javadoc: "Never use this TrustManagerFactory in production. It is purely for testing purposes, and thus it is very insecure."), we can't really change this now. Maybe for 4.0?
