### ISSUE TITLE
Run Micronaut app by Eclipse does not register my beans in the app context

### ISSUE THREAD

**Issue by engilyin** [micronaut-projects/micronaut-core#4125]
Micronaut app launched by Eclipse launcher does not have the defined beans like controllers etc.
Running the app from command line works just fine:
```bash
./gradlew run
```
I have setup it as described here:
https://docs.micronaut.io/latest/guide/index.html#ideSetup

Alternatively I tried to import it as git app and than add Gradle Nature and did Gradle\Refresh Gradle Project
Also I did `./gradlew eclipse` but it breaks the project and I needed to run Refresh Gradle Project again to fix it.

I used the latest Eclipse IDE for Enterprise Java Developers with no additional plugins

### Task List

- [V ] Steps to reproduce provided
- [- ] Stacktrace (if present) provided
- [V ] Example that reproduces the problem uploaded to Github
- [ V] Full description of the issue provided (see below)

### Steps to Reproduce

1. Install latest Eclipse IDE for Enterprise
2. clone sample project:
```bash
git clone https://github.com/micronaut-guides/creating-your-first-micronaut-app.git
cd creating-your-first-micronaut-app
```
3. Run eclipse task:
```bash
./gradlew eclipse
```
4. Open up Eclipse and import project as Gradle project:
`File → Import then choosing Gradle → Existing Gradle Project`

5. Find in the `complete` project the `Application.java` class, right-click it and select `Debug As\Java Application`

6. Using any browser navigate to: `http://localhost:8080/hello`

7. You will see that app is up and running but the endpoint defined in the `HelloController` class is not working because it was not available in the Application Context:
```json
{"message":"Page Not Found","_links":{"self":{"href":"/hello","templated":false}}}
```

### Expected Behaviour

When I run app by Eclipse launcher
The `http://localhost:8080/hello` should return `Hello World` plain text.
All my declared beans should be properly registered in the app context. 

Tell us what should happen

### Actual Behaviour

My beans are not registered in the app context when I run the app by Eclipse
```json
{"message":"Page Not Found","_links":{"self":{"href":"/hello","templated":false}}}
```

### Environment Information

- **Operating System**: macOS Catalina 10.15.6
- **Micronaut Version:** 2.0.0.RC1 and 2.0.2
- **JDK Version:** openjdk version "11.0.5" 2019-10-15 LTS Amazon Corretto
- **Eclipse:** Eclipse IDE for Enterprise Java Developers 2020-09 (4.17.0) (Build id: 20200910-1200)
- **Gradle BuildShip:**	3.1.4.v20200326-1743	

### Example Application

- https://github.com/micronaut-guides/creating-your-first-micronaut-app

**Comment by graemerocher** [comment]
You have to run `./gradlew eclipse` first because it configures the annotation processors correctly for Eclipse. Without this it does not work

**Comment by graemerocher** [comment]
hmm actually it seems that Eclipse's annotation processor stuff is again broken and not behaving like the Java implementation since the META-INF/services file are not being generated.

**Comment by graemerocher** [comment]
Reported https://bugs.eclipse.org/bugs/show_bug.cgi?id=567116

**Comment by graemerocher** [comment]
Submitted a PR with a temporary workaround until the bug in Eclipse is fixed

**Comment by graemerocher** [comment]
If anyone ever needs to remote debug the Eclipse compiler + Micronaut annotation processors here is a Maven build to do it https://gist.github.com/graemerocher/d3f36c1ff56d50b69a14cad3c13ae8ee

**Comment by esocode** [comment]
Is there anything to do to activate this fix? I have upgraded to 2.1.0 but if I try to run services or (micronaut) tests I only get error messages like the one shown in this issue. Eclipse is the latest version (2020-09).

**Comment by esocode** [comment]
With 2.1.0 I have a strange dependency problem in Eclipse. I have a library project that only defines entities and repositories with micronaut-data. For this purpose it has an implementation dependency to `io.micronaut.data:micronaut-data-hibernate-jpa`. For gradle builds this is sufficient, as it has been in Eclipse before. But since 2.1.0 Eclipse displays an error in varying files:

>The type io.micronaut.websocket.annotation.WebSocketComponent cannot be resolved. It is indirectly referenced from required .class files

I was only able to fix this by adding a dependency to `io.micronaut:micronaut-http-server`. 

As this only happens in Eclipse: could this be caused by the Eclipse-specific fix in this issue?

**Comment by graemerocher** [comment]
There appear to be many problems and inconsistencies with the Eclipse compiler

**Comment by esocode** [comment]
With the compiler I normally have no problems. But the annotation processing seems to be quite buggy, to the point of being unusable. But the build problem mentioned only occurred after switching to 2.1.0, so I thought that maybe the recent apt-fix causes that.

**Comment by graemerocher** [comment]
Here is a `pom.xml` that lets you run the Eclipse compiler with a Maven build. If you are able to provide an example that uses this that reproduces the problem that could help https://gist.github.com/graemerocher/d3f36c1ff56d50b69a14cad3c13ae8ee

**Comment by graemerocher** [comment]
I cannot reproduce the problem described in 2.1.0 with latest Eclipse. Make sure you follow the instructions to setup Eclipse APT https://docs.micronaut.io/latest/guide/index.html#eclipseSetup
