### ISSUE TITLE
SimpleHttpHeaders.add() is setting the header instead of adding

### ISSUE THREAD

**Issue by pontello** [micronaut-projects/micronaut-core#4126]
[This line](https://github.com/micronaut-projects/micronaut-core/blob/master/http/src/main/java/io/micronaut/http/simple/SimpleHttpHeaders.java#L90) is **setting** the header instead of **adding** a new header value. The entire implementation looks wrong as well, because Http headers can accept multi values..

I have found it by chance while running unit tests in a project without `micronaut-http-server-netty`. If netty project is added, calls to `io.micronaut.http.HttpResponse.ok()` would return a netty implementation at low level that doesn`t have the bug.

**Comment by kanibs** [comment]
hey @pontello  can I pick this issue?

**Comment by kanibs** [comment]
@pontello my bad, just noticed that @ze12augusto has already created a PR for this issue. So not proceeding on this.
