### ISSUE TITLE
Duplicated @Generated annotation at $Intercepted class after build

### ISSUE THREAD

**Issue by ednesic** [micronaut-projects/micronaut-core#4127]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create new micronaut kotlin project with http client
2. Create new controller(Ex: FooController)
3. Annotate controller class with `@Validated`
4. Build

### Expected Behaviour

Should create $Intercepted class for controller annotated with one `@Generated` at `target.classes.*some_package*` after build

### Actual Behaviour

Duplicated `@Generated` annotation on controller intercepted class(Ex:`$FooControllerDefinition$Intercepted.class`) after build.

### Environment Information

- **Operating System**: Catalina
- **Micronaut Version:** 2.0.2
- **JDK Version:** 11

### Example Application

https://github.com/ednesic/micronaut-generated-problem

**Comment by ggerbaud** [comment]
ArchUnit fails when scanning classes because this annotation appears twice

**Comment by graemerocher** [comment]
Thanks for the report, PR submitted
