### ISSUE TITLE
mn CLI bash completion script

### ISSUE THREAD

**Issue by remkop** [micronaut-projects/micronaut-core#414]
Now that https://github.com/micronaut-projects/micronaut-core/issues/256 is merged, would there be any interest in a bash completion script for the `mn` CLI?

This would be a file named `mn_completion` that would be packaged with the `mn` launcher script.
Users would have to source the `mn_completion` script or add it to their bash_profile:

```
#1. Source completion script in your .bash_profile

cd $MICRONAUT_HOME/bin
echo ". $(pwd)/mn_completion" >> ~/.bash_profile

#2. Open a new bash console, and type `mn [TAB][TAB]`
```

As an example, see the competion scripts for groovy 2.5/3.0: https://github.com/apache/groovy/tree/master/src/bin

**Comment by remkop** [comment]
To be clear, this would be more static than what `mn` in interactive mode can do. It would not generate project-specific completion candidates when in a project directory. So it would not show the `create-controller`, `create-client` or `create-command` commands (where `mn` in interactive mode would).

**Comment by graemerocher** [comment]
Sounds like a great idea

**Comment by remkop** [comment]
Please see PR #415.

To test:

```
$ gradlew cli:fatJar
$ cd cli/build/bin
$ . mn_completion
$ ./mn [TAB][TAB]
```

**Comment by remkop** [comment]
One drawback is that the script would need to be regenerated as features or profiles are added.

**Comment by graemerocher** [comment]
I think what makes sense to is to regenerate it prior to each release. Thanks.

**Comment by remkop** [comment]
Thoughts on future improvements:

It would be nice if the completion script could be regenerated as part of the build. Perhaps as a separate task. 

Currently, to regenerate you'd have to uncomment [a line of code](https://github.com/micronaut-projects/micronaut-core/blob/master/cli/src/main/groovy/io/micronaut/cli/MicronautCli.groovy#L219) and run the `mn` CLI.

If you're interested in automating this, one option is to turn this line of code into a command, let's say `create-completion-script`. You could then create a gradle task that would invoke this command: `mn create-completion-script`.

(This could be a "hidden" command, like `quit`, `exit` and `!`, so it won't show up in the usage help. )

Perhaps not worth the trouble, depending on how often you'll be doing releases.

**Comment by graemerocher** [comment]
might be an idea, more automation is always good
