### ISSUE TITLE
Reactive retry doesn't work as expected

### ISSUE THREAD

**Issue by Im-dex** [micronaut-projects/micronaut-core#4141]
### Steps to Reproduce

Run test

### Expected Behaviour

All the test successfully completes

### Actual Behaviour

The reactive test does fail. The reactive retryable method doesn't retry while blocking and async methods successfully retry.

### Environment Information

- **Operating System**: TODO
- **Micronaut Version:** 2.0.2
- **JDK Version:** TODO

### Example Application

https://github.com/Im-dex/micronaut-rx-retryable-issue

**Comment by dstepanov** [comment]
Reactive retry is done by re-subscribing so the method is invoked only once.

**Comment by Im-dex** [comment]
> Reactive retry is done by re-subscribing so the method is invoked only once.

It is quite unobvious, error-prone, and inconsistent behavior I think, isn't it?

**Comment by graemerocher** [comment]
Generally for code like you have presented in the example there is no value in using reactive programming 

If you are just doing logic and returning `just` or `error` then you may as well use imperative style programming and be done with it in which case retry behaviour would work like you expect.

**Comment by Im-dex** [comment]
> Generally for code like you have presented in the example there is no value in using reactive programming
> 
> If you are just doing logic and returning `just` or `error` then you may as well use imperative style programming and be done with it in which case retry behaviour would work like you expect.

The code is just a minimal example. Let's take something like this:
```java
@Singleton
class Bean {
    @Inject
    DbReader reader;

    @Retryable(attempts = "5", delay = "1ms")
    public Mono<Integer> read(String name) {
        return reader.readFromDatabase("SELECT * FROM ....", name)
            .map(record -> record.getColumn("age"));
    }
};
```

Here I should don't forget to wrap the body into `Mono.defer` or nothing will be retried silently.
So the code becomes ugly:

```java
@Singleton
class Bean {
    @Inject
    DbReader reader;

    @Retryable(attempts = "5", delay = "1ms")
    public Mono<Integer> read(String name) {
        return Mono.defer(() ->
            reader.readFromDatabase("SELECT * FROM ....", name)
                .map(record -> record.getColumn("age"))
        );
    }
};
```

But micronaut already knows how to call the method, so why the users need to do unnecessary wrapping?

**Comment by graemerocher** [comment]
Seems a bug in `dbReader` which is not allowing to be subscribed to twice?

**Comment by Im-dex** [comment]
> Seems a bug in `dbReader` which is not allowing to be subscribed to twice?

It is not a bug according to reactive streams spec:
```
A Publisher MAY support multiple Subscribers and decides whether each Subscription is unicast or multicast.
```

**Comment by graemerocher** [comment]
Ok, seems like this is something worth improving the documentation on. Behaviorally it is not something we can fix.
