### ISSUE TITLE
Still listening on port after stopping micronaut on Android

### ISSUE THREAD

**Issue by igiantpanda** [micronaut-projects/micronaut-core#4162]
When I start the micronaut server with a single IP(e.g. 192.168.0.10), but not "0.0.0.0". Then after I stop the server, the program is still listening on the port. So I can not start micronaut with the same port again.

When I stop the server, `NettyHttpServer.stop()` will be called.
But I found `InetAddress.getLocalHost()` in the follow code will return the localhost(127.0.0.1) on Android, but return the actual address on Windows. So `NettyHttpServer.stopInternal()` will not be called on Android because the server did not listen on 127.0.0.1.

io/micronaut/core/io/socket/SocketUtils.java
```java
    public static boolean isTcpPortAvailable(int currentPort) {
        try (Socket socket = new Socket()) {
            socket.connect(new InetSocketAddress(InetAddress.getLocalHost(), currentPort), 20);
            return false;
        } catch (Throwable e) {
            return true;
        }
    }
```
io/micronaut/http/server/netty/NettyHttpServer.java
```java
    public boolean isRunning() {
        return running.get() && !SocketUtils.isTcpPortAvailable(serverPort);
    }

    public synchronized EmbeddedServer stop() {
        if (isRunning() && workerGroup != null) {
            if (running.compareAndSet(true, false)) {
                stopInternal();
            }
        }
        return this;
    }
```

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Start micronaut and listen the IP of WiFi, but not listen "0.0.0.0".
2. Stop micronaut
3. Start micronaut with the same port of step 1.

### Expected Behaviour

After step 2, the program will stop listening the port.
After step 3, micronaut can be started.

### Actual Behaviour

After step 2, the program is still listening the port.
After step 3, micronaut can not be started, and the program will crash.

### Environment Information

- **Operating System**: Android 10
- **Micronaut Version:** 2.0.0
- **JDK Version:** 1.8

### Example Application

- https://github.com/igiantpanda/AndroidWebTest/tree/disconnect-issue

**Comment by graemerocher** [comment]
Should be fixed by https://github.com/micronaut-projects/micronaut-core/commit/170758eb439670e6bb6d651d3ff1668a292a8ba6
