### ISSUE TITLE
Multipart upload in server side can cause timeout or NPE

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#4181]
2.0.3

I have added test-cases to simulate it, first one will cause timeout and the second one NPE because the byte buffer is destroyed.

```
   @Post(value =  "/receive-multipart-body-blocking", consumes = MediaType.MULTIPART_FORM_DATA, produces = MediaType.TEXT_PLAIN)
    String multipartBlocking(@Body MultipartBody multipartBody) throws IOException {
        CompletedPart completedPart = Flowable.fromPublisher(multipartBody).blockingSingle();
        return completedPart.getBytes() == null ? "FAIL" : "OK";
    }

    @Post(uri = "/receive-multipart-body-as-single", consumes = MediaType.MULTIPART_FORM_DATA, produces = MediaType.TEXT_PLAIN)
    Single<String> multipartAsSingle(@Body io.micronaut.http.server.multipart.MultipartBody body) {
        return Single.fromPublisher(body).map(single -> single.getBytes() == null ? "FAIL" : "OK");
    }
```

https://github.com/dstepanov/micronaut-core/commit/145b28bba48cbd3146afa97f546d1389078bd781

**Comment by jameskleeh** [comment]
@dstepanov Try removing `@Body` from the `multipartAsSingle` method. If the first one is in the client package, then it cannot be used on the server.

**Comment by dstepanov** [comment]
Both are server ones, there is a link to the reproducible test

**Comment by jameskleeh** [comment]
The first one likely needs `@ExecuteOn(TaskExecutors.IO)`. I'll debug the second

**Comment by jameskleeh** [comment]
@dstepanov This is due to `Single.fromPublisher`. We have logic in the binder for MultipartBody that releases the data after the onNext call. https://github.com/micronaut-projects/micronaut-core/blob/2.0.x/http-server-netty/src/main/java/io/micronaut/http/server/netty/multipart/MultipartBodyArgumentBinder.java#L133

The conversion to single simply caches the result and waits for onComplete to send down the value. At that point the buffer has been released.

**Comment by jameskleeh** [comment]
The second result could be written as follows and works:

`Flowable.fromPublisher(body).map(single -> single.getBytes() == null ? "FAIL" : "OK").singleOrError();`

**Comment by dstepanov** [comment]
It would be nice to have some specific error message that tells you what is wrong.

**Comment by jameskleeh** [comment]
@dstepanov Agreed. We should definitely throw a more useful exception rather than letting the NPE get thrown
