### ISSUE TITLE
Creating an empty project and add new modules of Micronaut project in intellj gradle is not working

### ISSUE THREAD

**Issue by ghost** [micronaut-projects/micronaut-core#4208]
Created an empty project and trying to add new modules of Micronaut project in IntelliJ Gradle is not working.

### Task List
-  Creating multiples micronaut project in IntelliJ 

### Steps to Reproduce

1. On Intellj create an empty project
2. After creating an empty project, a module pop up window will appear, then add new modules and select Micronaut application
3. The module will be added to the project structure 
4. Select Apply and exit the Gradle daemon will not work and there is no way to run the multiple projects

### Expected Behaviour

After adding all the modules the Gradle daemon should run and we should be abe to run multiple projects

### Actual Behaviour

Gradle daemon build is not working

### Environment Information

- **Operating System**: MAC OS Catalina 10.15.7
- **Micronaut Version:** 2.0.3
- **JDK Version:** openjdk 15 2020-09-15

### Issue link

-  https://stackoverflow.com/questions/64120749/creating-an-empty-project-and-add-new-modules-of-micronaut-project-in-intellj-gr

**Comment by graemerocher** [comment]
Please report to https://youtrack.jetbrains.com/issue/IDEA
