### ISSUE TITLE
Breaking change in configuration deserialization behavior between 2.0.1 and 2.0.2 (newer behavior contradicts the docs)

### ISSUE THREAD

**Issue by oscarfh** [micronaut-projects/micronaut-core#4219]
The behavior of deserialization from application configuration to a map if different ("breaking change") in version 2.0.1 and 2.0.2.

Summary:
I have an application.yaml similar to this
```
properties:
    client-id: myId
```

In 2.01, properties would be deserialized to a Map<String,String> where the key is  `client-id`, while starting in 2.0.2, the key is `clientId`, which goes against [the documentation](https://docs.micronaut.io/1.2.2/guide/index.html#propertySource), which states 
```Property Value Binding

Note that these property references should always be in kebab case (lowercase and hyphen-separated) when placing references in code or in placeholder values. In other words you should use for example micronaut.server.default-charset and not micronaut.server.defaultCharset.```


Link to project to reproduce the issue: https://github.com/oscarfh/micronaut-configuration-deserialization

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue. I think this probably due to https://github.com/micronaut-projects/micronaut-core/pull/3859 but I am not sure.

I believe this would occur if Jackson was used to bind a type that then had a nested map

@dstepanov thoughts?

**Comment by dstepanov** [comment]
Yes, it's probably caused by that. Maybe `@MapFormat` can be used as a workaround.

@graemerocher I think https://github.com/micronaut-projects/micronaut-core/pull/3866 fixes it by moving the conversion to the actual bean binder otherwise an extra check needs to be added to exclude changing the keys for Map conversion.

**Comment by oscarfh** [comment]
I am sorry @graemerocher , I had the github repository ready and forgot to link here.
I will edit the original ticket.
