### ISSUE TITLE
2.1.0 doesn't have release notes 

### ISSUE THREAD

**Issue by agilob** [micronaut-projects/micronaut-core#4228]
2.1.0 doesn't have release notes / changelog

**Comment by graemerocher** [comment]
we are working on it, the docs are failing to publish for some reason

**Comment by graemerocher** [comment]
In the meantime you can find them here https://micronaut-projects.github.io/micronaut-core/latest/guide/#whatsNew

**Comment by agilob** [comment]
Thanks, I think I'm seeing a regression on graalvm or svm.

Project that used to compile on on 2.0.1 doesn't compile on 2.0.3 `com.oracle.svm.core.util.UserError$UserException: Main entry point class 'target/original-mhip-2-0.0.1-SNAPSHOT.jar' not found.`

Wanted to see if any graal changes went it to fix it. Will investigate more in the next days.
