### ISSUE TITLE
Make the default ProxySelector work with HttpClient

### ISSUE THREAD

**Issue by lgathy** [micronaut-projects/micronaut-core#4229]
### Steps to Reproduce

1. Set a working HTTP proxy via standard Java system properties (see: https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html) using a DNS hostname (not IP address) and port.
2. Upon application startup set proxySelector to `java.net.ProxySelector.getDefault()` in `DefaultHttpClientConfiguration`.
3. Using the default `HttpClient` send an HTTP request to a public website or API accessible by the configured proxy server.

### Expected Behaviour

The HTTP request goes through and the response received is the same as without the proxy.

### Actual Behaviour

`HttpClientException` is thrown. Caused by: java.nio.channels.UnresolvedAddressException: null.

### Environment Information

- **Operating System**: macOS 10.15.7
- **Micronaut Version:** 2.0.3
- **JDK Version:** 11.0.7

### Example Application

I have put together a test running squid as a proxy in a testcontainer attempting to download the `micronaut.io` webpage. The test spec is located in this [branch](https://github.com/Tesco/micronaut-core/tree/fix-default-selector) alongside with my proposed fix. I will raise a PR.

The problem is that the proxy selector is returning (potentially) unresolved addresses and the client is not attempting to resolve those before passing it to netty. When a fix `proxyAddress` is set in the `HttpClientConfiguration` this does not cause issue since the `ConversionService` always creates resolved `InetSocketAddress` instances. Since the configuration instance is a long-lived object, this is not such a good idea, as the underlying IP address may change in the DNS over time. Moreover, hostname resolution in `InetSocketAddress` is done in a best effort basis, if it fails the exception gets swallowed, and the configuration may end up with an unresolved proxyAddress anyway. We have seen this happening in long running services.

**Comment by Xaseron** [comment]
i tried setting it with `JAVA_TOOL_OPTIONS = "-Dmicronaut.http.client.proxy-selector=default -Dhttps.proxyHost=b2b-http.mycompany.com -Dhttps.proxyPort=8080 -Dhttps.nonProxyHosts='*.mycompany.com'"`
Setting the proxy works but the nonProxyHosts gets ignored. Is there something missing in the implementation?

**Comment by alcudiaMV** [comment]
> Hi #Xaseron,

Did You find a solution ?

Thanks

**Comment by yawkat** [comment]
@Xaseron @alcudiaMV it's `http.nonProxyHosts`, with `http` instead of `https`. `https.nonProxyHosts` does nothing: https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html

**Comment by alcudiaMV** [comment]
> @Xaseron

Thanks @Xaseron
