### ISSUE TITLE
mn create-project does not create graal files in 2.1.0

### ISSUE THREAD

**Issue by lizzyTheLizard** [micronaut-projects/micronaut-core#4234]
### Task List

- [x ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ x] Full description of the issue provided (see below)

### Steps to Reproduce
Try to create a new project with graal

mn create-app --features=graalvm test.example

### Expected Behaviour
According to the docu at https://docs.micronaut.io/latest/guide/index.html#graal a Dockerfile, a script docker-build.sh and a native-image.properties configuration file src/main/resources/META-INF/native-image should have been added.

However, the dependency org.graalvm.nativeimage:svm is added to build.gradle, so it does work it seems just not completely.

### Actual Behaviour
No Dockerfile, a script docker-build.sh or native-image.properties configuration has been added to the build

### Environment Information

- **Operating System**: Linux Mint 20
- **Micronaut Version:** 2.1.0 (latest version from sdkman)
- **JDK Version:** openjdk 11.0.8 2020-07-14

**Comment by graemerocher** [comment]
The documentation is a little out of date it seems, these files are no longer needed. You can build a native image with:

```bash
./gradlew nativeImage
```

Or on docker with:

```
./gradlew dockerBuildNative
```

**Comment by lizzyTheLizard** [comment]
Thanks a lot, seems to run fine! I was just confused by the doc :-) Micronaut 2.1.0 seems very cool so far, thanks a lot for the good work!
