### ISSUE TITLE
Indexed property not recognized by introspector when interface is reimplemented

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#4236]
In `2.1.0` but also in previous versions.

I have the following java interface:

```java
public interface IEmail {
	String getEmail();
}
```

This interface is then implemented in kotlin class:

```kotlin
@Introspected
open class SuperClass: IEmail {

    @Email
    override fun getEmail(): String = "a@a.pl"
    
}
```

And then I have two derived classes:

```kotlin
class SubClass: SuperClass()
class SubClassWithInterface: SuperClass(), IEmail
```

As you can see the latter one reimplements the same interface (in the real-world scenario it implementes another `MyInterface extends IEmail`, but the same bug is reproducible here).

And the problem is that `email` is no longer visible as indexed property by the introspector:

```java
logger.debug("Indexed properties of SuperClass: {}", BeanIntrospection.getIntrospection(SuperClass.class)
	.getIndexedProperties(Constraint.class).size());
logger.debug("Indexed properties of SubClass: {}", BeanIntrospection.getIntrospection(SubClass.class)
	.getIndexedProperties(Constraint.class).size());
logger.debug("Indexed properties of SubClassWithInterface: {}", BeanIntrospection.getIntrospection(SubClassWithInterface.class)
	.getIndexedProperties(Constraint.class).size());
```

Returns:

```
16:06:33.519 [main] DEBUG micronaut.general.AutoStartingBean - Indexed properties of SuperClass: 1
16:06:33.520 [main] DEBUG micronaut.general.AutoStartingBean - Indexed properties of SubClass: 1
16:06:33.521 [main] DEBUG micronaut.general.AutoStartingBean - Indexed properties of SubClassWithInterface: 0
```

So, `SubClassWithInterface.email` is not recognized by the introspector as the indexed property, as it was overridden, while it isn't.

**Comment by l0co** [comment]
It's reproduced here: https://github.com/l0co/micronaut-playground/tree/micronaut-4236

**Comment by graemerocher** [comment]
have you tried declaring `@Introspected` on the child class just out of interest?

**Comment by l0co** [comment]
I've tried now (on `SubClassWithInterface`) but it doesn't help. This class is `@Introspected` properly because otherwise `BeanIntrospection.getIntrospection()` would throw an exception. Just the `email` property disappears. In my project I have a lot of different properties in super and subclasses, and only these reintroduced by reimplemented interface dissapear. The rest is recognized fine.

**Comment by jameskleeh** [comment]
@l0co This is because we visit interfaces before super types here: https://github.com/micronaut-projects/micronaut-core/blob/2.1.x/inject-java/src/main/java/io/micronaut/annotation/processing/SuperclassAwareTypeVisitor.java#L100. The interface method is visited and then the superclass one is ignored because it's the same method. That results in the annotation metadata of the superclass not being present in the introspection.
