### ISSUE TITLE
Http client @Client still uses the default content type even a new one is provided.

### ISSUE THREAD

**Issue by traycho** [micronaut-projects/micronaut-core#4238]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run application
2. Check console logs
```
11:14:38.724 [nioEventLoopGroup-1-1] DEBUG i.m.http.client.DefaultHttpClient - Sending HTTP Request: POST /something
11:14:38.725 [nioEventLoopGroup-1-1] DEBUG i.m.http.client.DefaultHttpClient - Chosen Server: google.com(-1)
11:14:38.726 [nioEventLoopGroup-1-1] TRACE i.m.http.client.DefaultHttpClient - Content-Type: application/json
11:14:38.726 [nioEventLoopGroup-1-1] TRACE i.m.http.client.DefaultHttpClient - Content-Type: application/json;type=custom-type;version=1.0;charset=utf-8
```

### Expected Behaviour
Only one content type header is present
Content-Type: application/json;type=custom-type;version=1.0;charset=utf-8

### Actual Behaviour
Two content type headers are present
Content-Type: application/json - (should not be present)
Content-Type: application/json;type=custom-type;version=1.0;charset=utf-8

### Environment Information

- **Operating System**: MacOs Mojave
- **Micronaut Version:** 1.3.6
- **JDK Version:** 1.8.0_222

### Example Application

Checkout code from by using  *bug/http-client*  branch
git clone https://bitbucket.org/traycho/micronaut-examples.git

https://bitbucket.org/traycho/micronaut-examples/src/4dc5bc77f64a8a4335d0a5ac050f03021a1ee571/?at=bug/http-client

**Comment by jameskleeh** [comment]
You need to use `@Produces("application/json;type=custom-type;version=1.0;charset=utf-8")` instead of setting a content type header directly.
