### ISSUE TITLE
2.1.0: ServiceReadyHealthIndicator is never healthy when 'micronaut.application.name' isn't set

### ISSUE THREAD

**Issue by nhoughto** [micronaut-projects/micronaut-core#4242]
### Steps to Reproduce

1. Run Micronaut HTTP server without a name set
2. Call /health endpoint to assert liveness/readiness health
3. It will return DOWN status forever

### Expected Behaviour

It should be UP

### Actual Behaviour

It stays down

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** 2.1.0
- **JDK Version:** JDK 14

The problem is in `NettyHttpServer`, in `fireStartupEvents`:

```
private void fireStartupEvents() {
        Optional<String> applicationName = serverConfiguration.getApplicationConfiguration().getName();
        applicationContext.publishEvent(new ServerStartupEvent(this));
        applicationName.ifPresent(id -> {
            this.serviceInstance = applicationContext.createBean(NettyEmbeddedServerInstance.class, id, this);
            applicationContext.publishEvent(new ServiceReadyEvent(serviceInstance));
        });
    }
```

If `applicationName` isn't set, the ReadyEvent never gets fired, so the health check never goes healthy.

The fix is setting the `-Dmicronaut.application.name=something` or various other ways, but its not obvious why it fails!

**Comment by ramanujDAS** [comment]
for micronaut version 3.7.10 it is  still not working , without application.name  **ServiceReadyEvent** is not getting triggered.
