### ISSUE TITLE
HttpClient hangs when receiving 404 response

### ISSUE THREAD

**Issue by dimio111** [micronaut-projects/micronaut-core#4249]
I am having difficulty upgrading from micronaut 1.3.5 to 2.1.0.
We are using micronaut in an AWS lambda environment, but we also have this issue locally when running on a netty container.

We see time-outs when using the micronaut HttpClients on receiving a 404 response.
This time out is usually the same as the configured micronaut.http.services.test-client.read-timeout in the property files.

This issue is not present on Micronaut 1.3.1, the client throws the expected exception immediately when the 404 is received.

### Steps to Reproduce
Example code:
```
import io.micronaut.cache.annotation.Cacheable;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.client.RxHttpClient;
import io.micronaut.http.client.annotation.Client;

import javax.inject.Singleton;
import java.util.Optional;


@Singleton
public class HttpTest {

    private final RxHttpClient httpClient;

    public HttpTest(@Client("test-client") final RxHttpClient httpClient) {
        this.httpClient = httpClient;
    }

    @Cacheable("testcache")
    public Optional<MyClass> getMyClass(final Long someNumber) {
        return this.httpClient.retrieve(HttpRequest.GET("/some-endpoint-returning-404"), MyClass.class)
                .doOnError(t -> System.out.println("oops"))
                .onErrorReturnItem(new MyClass())
                .map(r -> Optional.ofNullable(r))
                .blockingSingle();
    }
}
```

### Expected Behaviour

HttpClient should throw the expected exception immediately and not wait for the time out.

### Actual Behaviour

Our backend responds with a 404 within 100ms, but the HttpClient hangs for the time set in micronaut.http.services.test-client.read-timeout

### Environment Information
- AWS Lambda 
- corretto java 11
- redis lettuce cache
- getMyClass is accessed in parallel by streams in other classes

### Example Application

Not an example application, but we did write a blog on what we created: https://medium.com/vrt-digital-studio/how-sporza-created-a-real-time-sport-data-api-b157b033b7c0
Hoping this provides some context.

**Comment by ilopmar** [comment]
You are executing a blocking HTTP call in Netty event loop and you are blocking it.

Take a look at the [Upgrade to Micronaut 2](https://docs.micronaut.io/2.0.0/guide/index.html#upgrading) section in the docs, the [breaking changes](https://docs.micronaut.io/2.0.0/guide/index.html#breaks) and [this blog post](https://objectcomputing.com/resources/publications/sett/june-2020-micronaut-2-dont-let-event-loops-own-you) about the new event loop execution model.
