### ISSUE TITLE
Enhance `DefaultPropertyPlaceholderResolver` to also resolve non-dotted expressions

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#425]
Currently `DefaultPropertyPlaceholderResolver` only resolves placeholders containing dots (`.`) or matching `^[\\p{Lu}_]+` (only uppercase letters if I'm correct).
Ordinary placeholders like `${version}` will not be replaced.

It would be nice to enhance the `DefaultPropertyPlaceholderResolver` to also not-dotted placeholders.

E.g. this would make it useful to use the `DefaultPropertyPlaceholderResolver` to replace arbitrary `${}` placeholders in String templates (similar as Apache Commons `StrSubstitutor`) like:

```
String template = "Hello ${foo}!";

Map<String, Object> parameters = new HashMap<>();
parameters.put("foo", "bar");

PropertyResolver propertyResolver = new MapPropertyResolver(parameters);
DefaultPropertyPlaceholderResolver propertyPlaceholderResolver = new DefaultPropertyPlaceholderResolver(propertyResolver);

String resolvedTemplate = propertyPlaceholderResolver.resolvePlaceholders(template).get(); 
```

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/ed885aa180284abd598b90fe0a481b00d3cb64ca

**Comment by marceloverdijk** [comment]
Thx, this works now!
