### ISSUE TITLE
Kotlin dependencies included in a Java/Groovy apps

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#4252]
I've realized that Kotlin dependencies are now included in Java/Groovy applications in Micronaut 2.1.0. I'm not sure if this is intentional, can be avoided or is a mistake.

Creating a new 2.1.0 application and running `./gradlew assemble` leads to this in  `build/layer/libs` directory:

```
-rw-rw-r-- 1 ivan ivan 1487085 Oct  6 11:41 kotlin-stdlib-1.4.10.jar
-rw-rw-r-- 1 ivan ivan  191211 Oct  6 11:41 kotlin-stdlib-common-1.4.10.jar
-rw-rw-r-- 1 ivan ivan    3985 Oct  6 11:41 kotlin-stdlib-jdk7-1.4.10.jar
-rw-rw-r-- 1 ivan ivan   16230 Oct  6 11:41 kotlin-stdlib-jdk8-1.4.10.jar
```

And they are also included in the shadow jar.

I've checked and in Micronaut 2.0.3 this is not happening, so I'm wondering what have we changed.

![DeepinScreenshot_select-area_20201006114942](https://user-images.githubusercontent.com/559192/95186359-34780080-07ca-11eb-8ecc-6a04814beb06.png)
 

### Expected Behaviour

Kotlin dependencies shouldn't be included in a Java/Groovy application.

### Actual Behaviour

Kotlin libraries are included in Java/Groovy application.

**Comment by graemerocher** [comment]
Bizarre they are `compileOnly`, has Gradle suddenly changed to include `compileOnly` dependencies in the POM? https://github.com/micronaut-projects/micronaut-core/blob/2.1.x/http/build.gradle#L9

**Comment by graemerocher** [comment]
Bizarre they are `compileOnly`, has Gradle suddenly changed to include `compileOnly` dependencies in the POM? https://github.com/micronaut-projects/micronaut-core/blob/2.1.x/http/build.gradle#L9

**Comment by ilopmar** [comment]
Manually modifying the Gradle version to 6.5.1 in the generated app leads to the same behavior.

**Comment by graemerocher** [comment]
This seems to be a change in the Kotlin Gradle plugin which is automatically adding Kotlin dependencies to the `implementation` classpath. 

The `aop` module is using Kotlin 1.3.x (which is probably a bug in itself that we are compiling with an older version of Kotlin) and doesn't have the same problem https://github.com/micronaut-projects/micronaut-core/blob/2.1.x/aop/build.gradle#L2

**Comment by graemerocher** [comment]
See https://github.com/JetBrains/kotlin/commit/d83d3304a5b7468c83c22b3d4871116bd11a6eb8#diff-ab42bd0581d4bfbd4e8f7b0cbdf36a2e

**Comment by graemerocher** [comment]
And https://youtrack.jetbrains.com/issue/KT-36822
