### ISSUE TITLE
Request body is being dropped when using POJO request binding

### ISSUE THREAD

**Issue by vanga** [micronaut-projects/micronaut-core#4271]
Request body is being dropped when content type header is not being sent in an HTTP request, and we use POJO request binding in controllers to convert incoming json to a POJO

### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Run the micronaut application from https://github.com/vanga/micronaut-memory-leak (ignore the repository name)
2. make a curl request `curl -XPOST -H 'Content-type:' 'http://localhost:8080/hello' --data-raw '{"firstName": "abc","lastName": "xyz"}' -v` (make sure curl doesn't send default content type header)
3. Notice the 400 response with error `    "message": "Required Body [body] not specified",`

### Expected Behaviour

Body should have been converted to POJO since application/json is the default. I think its reasonable to think that this should work
micronaut documentation also mentions that it consumes JSON as default 
https://docs.micronaut.io/latest/guide/index.html#jsonBinding

### Actual Behaviour
Body is being dropped and a misleading error that body is missing is being responded

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 1.3.1
- **JDK Version:** JDK 11

### Example Application

- https://github.com/vanga/micronaut-memory-leak/

**Comment by graemerocher** [comment]
You're sending an invalid content type header, not surprising it doesn't work

**Comment by vanga** [comment]
I am sorry, as mentioned in the description, it is a trick of curl to tell
it to not send default header. Otherwise it assumes a default of url
encoded content type.

This can be reproduced from postman or even programmatically. Curl example
is only given for ease of reproducibility

**Comment by jameskleeh** [comment]
> micronaut documentation also mentions that it consumes JSON as default

And it does. The route accepts a content type of application/json. That doesn't imply that requests without a content type will assume the data is JSON. I don't think we should make that assumption

**Comment by vanga** [comment]
@jameskleeh I am sorry, I don't quite understand what is the intention of explicitly documenting `A Micronaut’s controller action consumes application/json by default.` if one has to send a content type mandatorily? If none is sent, micronaut is probably already making an assumption that it is `text/html`? in which case, wouldn't `application/json` be more sane default? 

And the error message being returned to client is also misleading that it says body is missing where as it should have returned something else which conveys what the problem is?

**Comment by jameskleeh** [comment]
> micronaut is probably already making an assumption that it is text/html

No - in this case the raw bytes are stored in the request and the body is attempted to be converted from those bytes using the conversion service. In this case no converter is found, thus the body argument cannot be bound. I'm not sure we can even really improve the error message here. The only thing we could say at this point is that "No converter found capable of converting CompositeByteBuf to HelloRequest". I don't think that is much of an improvement over the existing error message.

**Comment by graemerocher** [comment]
It does seem to me that if a request is missing the content type header and the route requires it to bind the body then it should fail earlier with an error messaging saying the content type header is missing. Not sure why it is even attempting to bind the body if it is not able to.

**Comment by vanga** [comment]
I would like to know if there there is a way to to get around this and set the default content type?
Unfortunately,  we didn't enforce this in our API and we were internally converting the json; now we started using POJO binding since micronaut provides a nice way for us to not bother about deserialiaztion. I am just wondering if there is an alternative that doesn't require changes from client side but still be able to use POJO binding.

**Comment by jameskleeh** [comment]
> if a request is missing the content type header and the route requires it to bind the body then it should fail earlier with an error messaging saying the content type header is missing

@graemerocher The route doesn't require it. If the body type was `byte[]` for example then I believe it would work

**Comment by jameskleeh** [comment]
@vanga You may be able to achieve this with a Netty handler by adding the content type header. See https://docs.micronaut.io/latest/guide/index.html#nettyPipeline

**Comment by vanga** [comment]
Thanks @jameskleeh, I will check that out.

**Comment by vanga** [comment]
Hi @jameskleeh I have just looked at the link you shared.. however, I couldn't identify how I can set a default header. I am not sure which constant from `ChannelPipelineCustomizer` will give me that option to set. 

I probably will have to go back to not using POJO request binding (I hate to go back :) )
