### ISSUE TITLE
Native image has a very slow shutdown

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-core#4280]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot
2. Build `micronaut-simple-api` native image and run as explained at https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/simple-api/micronaut-simple-api#docker-in-native-mode
3. Stop application `docker stop micronaut-simple-api-native`

### Expected Behaviour

It should be faster, considering we will use native images for serverless use cases

### Actual Behaviour

It's taking in my machine around `10 seconds` to shutdown

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 2.0.3
- **JDK Version:** 11

### Example Application

- https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/simple-api/micronaut-simple-api

**Comment by graemerocher** [comment]
I think this is probably because the shutdown hooks are not installed

**Comment by ivangfr** [comment]
Hi guys! I've recently updated the **Micronaut** apps inside Java framework comparison project to version `2.2.0` and looks like the slow shutdown I mentioned in this issue is solved. However, there is still a problem as described in this issue https://github.com/micronaut-projects/micronaut-core/issues/4584. Thanks!

**Comment by alvarosanchez** [comment]
Closing this issue as per the last comment
