### ISSUE TITLE
Issue with Management endpoints when running native image in version 2.1.0

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-core#4282]
Hi, I've updated my `simple-api` application from version `2.0.3` to `2.1.0`. Here are the changes: https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/compare/update-micronaut-version

When running its **native image** and trying to access the "management" endpoints like `heatlh`, `env`, `beans` and `metrics`, I am getting (with version `2.1.0`) different responses compared to version `2.0.3`.

**Note: the jvm docker image is working as expected.**

### 2.0.3

- **health**
  ```
  HTTP/1.1 200 Ok
  {"name":"micronaut-simple-api","status":"UP","details":{"compositeDiscoveryClient()":{"name":"micronaut-simple-api","status":"UP"},"diskSpace":{"name":"micronaut-simple-api","status":"UP","details":{...}}}}
  ```

- **env**
  ```
  HTTP/1.1 200 OK

  {"packages":["com.mycompany.micronautsimpleapi"],"propertySources":[{"name":"application","order":-300,"convention":"JAVA_PROPERTIES","properties":{"micronaut.application.name":"micronaut-simple-api",...}
  ```

- **beans**
  ```
  HTTP/1.1 200 OK
  {"beans":{"com.mycompany.micronautsimpleapi.rest.$SimpleApiControllerDefinition":{"dependencies":["com.mycompany.micronautsimpleapi.service.GreetingService"],"type":"com.mycompany.micronautsimpleapi.rest.SimpleApiController"}...}
  ```

- **metrics**
  ```
  HTTP/1.1 200 OK
  {"names":["executor","executor.active","executor.completed","executor.pool.core","executor.pool.max","executor.pool.size","executor.queue.remaining","executor.queued","http.server.requests","jvm.classes.loaded",...]}
  ```

### 2.1.0

- **health**
  ```
  HTTP/1.1 503 Service Unavailable
  {"status":"DOWN"}
  ```

- **env**
  ```
  HTTP/1.1 401 Unauthorized
  ```

- **beans**
  ```
  HTTP/1.1 401 Unauthorized
  ```

- **metrics**
  ```
  HTTP/1.1 200 OK
  {"names":["executor","executor.active","executor.completed","executor.pool.core","executor.pool.max","executor.pool.size","executor.queue.remaining","executor.queued","http.server.requests","jvm.classes.loaded",...]}
  ```

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot
2. Switch to branch `update-micronaut-version`
3. Follow the steps how to build & run the native image of `micronaut-simple-api` as here https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/simple-api/micronaut-simple-api#docker-in-native-mode

### Expected Behaviour

The management endpoints should return `200` and some payload (as it was doing in version `2.0.3`)

### Actual Behaviour

The management endpoints are returning status different than`200` (just `metrics` endpoint is ok)

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 2.1.0
- **JDK Version:** 11

### Example Application

- https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/simple-api/micronaut-simple-api (branch `update-micronaut-version`)

**Comment by graemerocher** [comment]
PR submitted for this, your other problem is because you need `micronaut-graal` to generate the static resource configuration:

```
annotationProcessor("io.micronaut:micronaut-graal")
```

If you build with GraalVM SDK this is added automatically, if you don't you need to add it manually
