### ISSUE TITLE
HttpClient Cookie issue

### ISSUE THREAD

**Issue by myspec** [micronaut-projects/micronaut-core#4289]
### Steps to Reproduce
Java code.
            MutableHttpRequest<Map<String, String>> mainRequest = HttpRequest.POST("https://xxx.xxx.com/Login", dataMap);
            Flowable<HttpResponse<String>> req = httpClient.exchange(mainRequest, String.class);
            HttpResponse<String> body = req.blockingFirst();
            List<String> setcookie = body.getHeaders().getAll("Set-Cookie");
            Cookies cookie = body.getCookies();

case1)  setcookie 
0 = "enctp=1;Domain=.xxx.xxx.com;Expires=Sat, 09-Jan-2021 17:32:47 GMT;Max-Age=7776000"
1 = "inf=123456; path=/; domain=.xxx.com;"
2 = "AUT=aaaabbbbcccc; path=/; domain=.xxx.com; HttpOnly"
3 = SES=abcdabcd; path=/; domain=.xxx.com;"
4 = "JKL=abcdaaaa=; path=/; domain=.xxx.com; Secure;"

cookie (body.getCookies())
"Domain" -> {NettyCookie@11397} 
"Max-Age" -> {NettyCookie@11399} 
"enctp" -> {NettyCookie@11401} 

case2) setcookie
0 = "ASP.NET_SessionId=xxxxx; path=/; secure; HttpOnly; SameSite=None; SameSite=None; Secure"
1 = .ASPXAUTH=5CDC85179DFD16FB8DE57D43398"
2 = "192.168.1.1=oid=gvj7zB8zy5b5I3skoGnw8Fsg==&str"

cookie (body.getCookies())
"ASP.NET_SessionId" -> {NettyCookie@15099} 
"SameSite" -> {NettyCookie@15101} 
"path" -> {NettyCookie@15103} 

### Actual Behaviour
Cannot access all cookie.
And in case of 302 redirect, it always failed.

### Environment Information

- **Operating System**: WINDOWS10
- **Micronaut Version:** 2.1.0
- **JDK Version:** OpenJDK 14

### Example Application
Currenty, not..

**Comment by jameskleeh** [comment]
Thanks for the detailed report
