### ISSUE TITLE
Any love for micronaut-azure?

### ISSUE THREAD

**Issue by ronhitchens** [micronaut-projects/micronaut-core#4299]
Apologies for spamming the core issues list, but I opened a Micronaut Azure Bug Report ([micronaut-azure Issue 83](https://github.com/micronaut-projects/micronaut-azure/issues/83))  nearly two weeks ago and it doesn't look like it's been noticed by anyone yet.  If someone could take a look at this we would appreciate it very much.  This is becoming a very urgent problem for us and holding up our Azure migration project.

Thank you.

**Comment by jameskleeh** [comment]
@ronhitchens A Github issue isn't the appropriate place to ask this question, as I'm sure you're aware. You can ask this on [Gitter](https://gitter.im/micronautfw). You can message me there if you're interested in Micronaut support from OCI.
