### ISSUE TITLE
@MapFormat(keyFormat = RAW) not working when used with @ConfigurationProperties

### ISSUE THREAD

**Issue by john-pan9** [micronaut-projects/micronaut-core#4308]
### Steps to Reproduce

1. Simple configuration class (uses lombok)
```
@Data
@ConfigurationProperties("conf")
public class MyConfig {
    @MapFormat(keyFormat = RAW)
    private Map<String, String> animals;
}
```
2. Corresponding config in `application.yml`
```
conf:
  animals:
    VERY_FAST: rabbit
    VERY_SLOW: turtle
```

### Expected Behaviour
When accessing `MyConfig#getAnimals()`, the map should contain keys: `VERY_FAST` and `VERY_SLOW`

### Actual Behaviour
`MyConfig#getAnimals()` actually contains keys: `very-fast` and `very-slow`

### Environment Information

- **Operating System**: macOS 10.15.7
- **Micronaut Version**: 2.1.0 
- **JDK Version**: openjdk version "11.0.6" 2020-01-14 LTS

### Example Application

- https://github.com/john-pan9/micronaut-key-format-issue

**Comment by jameskleeh** [comment]
This is due to Lombok. The annotation will be placed on the field and in the case of a getter/setter, annotations are read on the setter argument. I modified your code to use `@Setter(onParam_={@MapFormat(keyFormat = RAW)})`, however it appears that the bytecode for that change isn't visible in the Micronaut annotation processor.

The following works as you expect:

```
@ConfigurationProperties("conf")
public class MyConfig {
    
    private Map<String, String> animals;

    public Map<String, String> getAnimals() {
        return animals;
    }

    public void setAnimals(@MapFormat(keyFormat = RAW) Map<String, String> animals) {
        this.animals = animals;
    }
}
```

**Comment by graemerocher** [comment]
Seems like we should be merging the annotation metadata from the field

**Comment by ivyazmitinov** [comment]
I was able to reproduce it without lombok. Indeed, looks like `io.micronaut.context.env.PropertySourcePropertyResolver#resolveSubMap(java.lang.String, java.util.Map<java.lang.String,java.lang.Object>, io.micronaut.core.convert.ArgumentConversionContext<?>)` uses only annotations from parameter.
It is confusing as it contradicts the [documentation](https://docs.micronaut.io/latest/guide/#configurationProperties) now. It also behaved as expected in 1.3.6.
