### ISSUE TITLE
Introduce a @Order annotation as alternative for the Ordered interface

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#431]
As discussed on Gitter this issue is to introduce a `@Order` annotation, similar as Spring's `@Order` annotation. 

Use case:

A user is creating multiple beans of the same class.
The class itself cannot be changes as it's coming from a third party lib, so it cannot implement the current `Ordered` interface.
A list of this class is injected somewhere but the order cannot be set currently. 
An `@Order`annotation on the method creating the bean could solve this.

**Comment by rogelio-o** [comment]
I think it can be done this way: https://github.com/rogelio-o/micronaut-core/commit/9f21530a127f1956722e0ac3b7896634002b4a10.

If you think it's a good approach I could refactor a little bit the DefaultBeanContext and add some tests for the sorting feature.

**Comment by jameskleeh** [comment]
@rogelio-o It doesn't look like some of the changes there are necessary, in regards to the `registrations` variable.

In addition this needs to replace the usage of reflection with annotation metadata api usage: https://github.com/rogelio-o/micronaut-core/commit/9f21530a127f1956722e0ac3b7896634002b4a10#diff-029ffe94e2d266e62ee634112cc0d1edR1931

A better way to get this reviewed would be to submit a PR

**Comment by vexxuh** [comment]
I am going to begin working on this ticket tomorrow and will make a progress update Sunday!

**Comment by graemerocher** [comment]
Sounds great! Let us know if you need help

**Comment by stottpaul** [comment]
Any progress with this, it would be very helpful to be able to use annotations to provide bean ordering ?

**Comment by seancarroll** [comment]
I took an initial swipe at this and have a test working. Happy to submit a PR and get feedback. I leverage BeanRegistration, perhaps inappropriately, as a way to hold both the bean and its corresponding BeanDefinition so that I can apply a comparator that checks both the new `Order` annotation from the BeanDefinition as well as the check for the `Ordered` interface on the bean.

**Comment by graemerocher** [comment]
Happy to review the PR

**Comment by seancarroll** [comment]
Created PR #3478
