### ISSUE TITLE
Apparent resource leak in applicationContext.getBeansOfType

### ISSUE THREAD

**Issue by ronhitchens** [micronaut-projects/micronaut-core#4320]
### Description

It appears that fetching a list of beans by type, by invoking `applicationContext.getBeansOfType` on the injected `ApplicationContext` object is leaking sockets or (more likely) file descriptors.  This not a particular problem in normal operation, but adding a `Singleton` bean to my app that calls the function `getBeansOfType` in its constructor starts failing when run 100s of times in a JUnit test suite.

We have roughly 400 JUnit tests.  With this code in place about half of them run ok, after which they all start failing with a `Socket closed` error.  When I comment out the `getBeansOfType` call, they run fine.  Our JUnit 5 tests are setup to run each class as one instantiation (PER_CLASS), but I don't think that's relevant.  All subsequent test classes fail.

Below is the class I've added, in its entirety.  It listens for application events sent by our controllers and sends them on to notifiers for async processing.  Note that none of that is actually happening here, just gathering the list of notifier beans in the constructor is where the leak occurs.  There is an enable flag defined, which is checked when events are raised.  I also injected it into the constructor and used it to conditionalize the bean lookup, since we don't need the notifier for 99% of our tests.  So I have a work around, but this leak should be tracked down.

Cheers.

``` java
package sa.nistolink.queryservice.events

import groovy.util.logging.Slf4j
import io.micronaut.context.ApplicationContext
import io.micronaut.context.annotation.Property
import io.micronaut.context.event.ApplicationEventListener
import io.reactivex.Flowable
import sa.nistolink.queryservice.controllers.records.RecordHelper
import sa.nistolink.queryservice.events.notify.ChangeNotifier

import javax.annotation.Nullable
import javax.inject.Singleton

@Slf4j
@Singleton
class NistoRecordChangeEventHandler<E> implements ApplicationEventListener<E>
{
	private final RecordHelper recordHelper
	private final ApplicationContext applicationContext
	private final List<ChangeNotifier> notifiers = []
	private final Boolean enabled

	NistoRecordChangeEventHandler (RecordHelper recordHelper, ApplicationContext applicationContext,
		@Nullable @Property(name = 'nisto.events.change.enabled', defaultValue = 'false') Boolean enabled)
	{
		this.recordHelper = recordHelper
		this.applicationContext = applicationContext
		this.enabled = enabled

		// Without this guard, tests will begin failing partway through
		if (enabled) {
			// This seems to leak sockets if initialized for every test. So don't do it if not enabled.
			applicationContext.getBeansOfType (ChangeNotifier).each { ChangeNotifier notifier ->
				notifiers << notifier
			}
		}
	}

	@Override
	void onApplicationEvent (E e)
	{
		sendEvent (e).subscribe()
	}

	@Override
	boolean supports (E event) {
		(event instanceof NistoRecordChangeEvent) && (notifiers.size() > 0)
	}

	// ----------------------------------------------------------------

	private Flowable<Boolean> sendEvent (NistoRecordChangeEvent event)
	{
		Map<String,Object> payload = event.payload

		recordHelper.recordForIdNotNull (event.identifier, null)
			.flatMap { Map<String,Object> record ->
				payload.newState = record

				Flowable.fromIterable (notifiers)
			}
			.flatMap { ChangeNotifier notifier ->
				notifier.handleEvent (event)
			}
			.onErrorReturn { Throwable t ->
				log.error ("Error from invoked notifier: ${t.toString()}")
				Boolean.FALSE
			}

	}
}
```

### Environment Information

- **Operating System**: OSX (Catalina)
- **Micronaut Version**: 1.3.4
- **JDK Version**: Java 8

**Comment by jameskleeh** [comment]
@ronhitchens We would need a sample application with steps to reproduce. Can you verify if you see this issue in Micronaut 2.1.1?
