### ISSUE TITLE
Annotation processor definitions in micronaut-parent and children

### ISSUE THREAD

**Issue by aalmiray** [micronaut-projects/micronaut-core#4323]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Define a parent pom with an `<annotationProcessor>` in the `maven-compiler-plugin`'s configuration.
2. Define a child pom with a different `<annotationProcessor>` in the `maven-compiler-plugin`'s configuration.
3. Resolve the effective pom with `mvn help:effective-pom`.

### Expected Behaviour

Annotation processors from the parent and child are available at the child POM, with parent's first then child's.

### Actual Behaviour

Annotation processors defined in a parent POM (such as `micronaut-parent`) when applied to the `maven-compiler-plugin` using its `<annotationProcessor>` element in the configuration block will be lost if a child POM also defines a `<annotationProcessor>` in its configuration. 

### Environment Information

- **Operating System**: N/A
- **Micronaut Version:** 2.1.1
- **JDK Version:** N/A

### Example Application

https://github.com/aalmiray/maven-annotation-processor-merge

**Comment by aalmiray** [comment]
The fix is to add an attribute `combine.children="append"` in the child's `<annotationProcessor>` block. The linked example contains the fix commented out. Once applied the effective pom contains the following configuration for the compiler plugin

      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <executions>
          <execution>
            <id>default-compile</id>
            <phase>compile</phase>
            <goals>
              <goal>compile</goal>
            </goals>
            <configuration>
              <annotationProcessorPaths combine.children="append">
                <path>
                  <groupId>org.projectlombok</groupId>
                  <artifactId>lombok</artifactId>
                  <version>1.18.14</version>
                </path>
                <path>
                  <groupId>com.google.auto.value</groupId>
                  <artifactId>auto-value</artifactId>
                  <version>1.7.4</version>
                </path>
              </annotationProcessorPaths>
            </configuration>
          </execution>
          <execution>
            <id>default-testCompile</id>
            <phase>test-compile</phase>
            <goals>
              <goal>testCompile</goal>
            </goals>
            <configuration>
              <annotationProcessorPaths combine.children="append">
                <path>
                  <groupId>org.projectlombok</groupId>
                  <artifactId>lombok</artifactId>
                  <version>1.18.14</version>
                </path>
                <path>
                  <groupId>com.google.auto.value</groupId>
                  <artifactId>auto-value</artifactId>
                  <version>1.7.4</version>
                </path>
              </annotationProcessorPaths>
            </configuration>
          </execution>
        </executions>
        <inherited>true</inherited>
        <configuration>
          <annotationProcessorPaths combine.children="append">
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>1.18.14</version>
            </path>
            <path>
              <groupId>com.google.auto.value</groupId>
              <artifactId>auto-value</artifactId>
              <version>1.7.4</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>

More information on the `combine.children` attribute (and others) can be found at https://blog.sonatype.com/2011/01/maven-how-to-merging-plugin-configuration-in-complex-projects/

**Comment by alvarosanchez** [comment]
Nice trick! We might make use of `combine.children` in few other places.

**Comment by alvarosanchez** [comment]
Fixed via https://github.com/micronaut-projects/micronaut-starter/pull/546
