### ISSUE TITLE
Support HTTP 1.1 Pipelining

### ISSUE THREAD

**Issue by myspec** [micronaut-projects/micronaut-core#4336]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce
Make a POST request to make 404 (or 403)  twice, (second request has issue)

1) excute micronaut server application
$ mn create-app hello-world
$ cd hello-world
$ gradlew.bat run

2) 
$ wget --method POST --body-data '{test}' 'http://localhost:8080/notexist1' 'http://localhost:8080/notexist2'
--2020-10-18 03:30:25--  http://localhost:8080/notexist1
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 403 Forbidden
2020-10-18 03:30:25 ERROR 403: Forbidden.

--2020-10-18 03:30:25--  http://localhost:8080/notexist2
Reusing existing connection to [localhost]:8080.
HTTP request sent, awaiting response...

micronaut 2.0.0 works fine.

### Actual Behaviour
for second request, no response. and no logs on server application.
### Environment Information

- **Operating System**: windows 10
- **Micronaut Version:** 2.1.1
- **JDK Version:** openjdk14

### Example Application
I tested with micronaut sample application.

**Comment by jameskleeh** [comment]
@myspec Are both requests sent immediately? Ie using HTTP 1.1 pipelining?

**Comment by myspec** [comment]
@jameskleeh I found some evidence..
$  wget --no-http-keep-alive --method POST --body-data '{test}' 'http://localhost:8080/notexist1' 'http://localhost:8080/notexist2'
works fine with --no-http-keep-alive option.

thank you

1. cases, not reproduced
  1) wget with seperated command
    $ wget --method POST --body-data '{test}' 'http://localhost:8080/notexist1' 
    $ wget --method POST --body-data '{test}' 'http://localhost:8080/notexist2'
  2) wget without body data
    $ wget --method POST 'http://localhost:8080/notexist1' 'http://localhost:8080/notexist2'
  3) test code with java rxhttpclient test code.
  
2. cases, reproduced
  1) wget with one command
    $ wget --method POST 'http://localhost:8080/notexist1' 'http://localhost:8080/notexist2'
  2) postman app

**Comment by jameskleeh** [comment]
@myspec I can only assume its using pipelining, which we don't currently support
