### ISSUE TITLE
Problem with @Filter and ThreadLocal variables in version 2.1.1

### ISSUE THREAD

**Issue by alejandropg** [micronaut-projects/micronaut-core#4338]
Hi,

I noticed that with versión 2.1.1 when, inside a request filter, you set something to a ThreadLocal variable, after in your application code you can not find it.

Prior, in versión 2.1.0, I can see that the `@Filter` is ran twice, the first in the NIO (Netty) event loop, and de second in the IO (application) thread. (I use configuration `micronaut.server.thread-selection: AUTO`).

But with versión 2.1.1 the request filter is run the two times over the NIO thread, so when you try to get the value in the IO thread, you can't.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
  - The problem doesn't generate any exception
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a request filter (for example with `@Filter`)
2. Inside de filter set any value in a ThreadLocal variable.
3. After try to locate the value in the IO thread (your application code).

### Expected Behaviour

In your application code you should find the value that you set in the request filter.

### Actual Behaviour

The value is not found.

I suspect (but I don't have the evidence) that the problem could be related with this change in the `RoutingInBoundHandler.java`

https://github.com/micronaut-projects/micronaut-core/pull/4301/commits/52de614390c525b7e27b923f1a022a00d5db6457

### Environment Information

- **Operating System**: macOS 10.15
- **Micronaut Version:** 2.1.1
- **JDK Version:** 11

**Comment by graemerocher** [comment]
In general thread local shouldn't be used within a filter or anywhere in Micronaut for that matter as thread locals and reactive need to be managed explicitly via instrumentation for reactive.

If you need to store something do so in the request and use `ServerRequestContext` to obtain the current context which is propagated via instrumentation and provides more guarantees

**Comment by alejandropg** [comment]
Ok, I understand.

But one more question, if there is no intent to execute the filter over the IO thread, why the filter is executed twice over different threads (in version 2.1.0 NIO and IO, and in version 2.1.1 two different threads of NIO)?

Thanks!

**Comment by graemerocher** [comment]
If it is not a once per request filter it may be executed twice for error handlers and other cases

**Comment by alejandropg** [comment]
Yes, is an once per request filter, at least it's declared like:

```
@Filter("/**")
class MyHttpServerFilter(
...
) : OncePerRequestHttpServerFilter() {
```

**Comment by jameskleeh** [comment]
@alejandropg If you can provide an example application with steps to reproduce a once pre request filter being executed multiple times for the same request please do so

**Comment by alejandropg** [comment]
ok @jameskleeh I checked again and the "double execution" issue was MY FAULT!  It was an issue with the client I was using that really was doing two different request.

I'm sorry for the noise of the "double execution", but anyway my doubt about the thread change isn't explained.

However I think that this issue is clearly resolved with the previos explanation of @graemerocher 
> In general thread local shouldn't be used within a filter or anywhere in Micronaut for that matter as thread locals and reactive need to be managed explicitly via instrumentation for reactive.

where is clear that is a bad practice to use the `ThreadLocal` in this way.

So, I procede to close this issue, because I think this is not the best way to clarify to me about the thread change.

And of course, really thanks a lot for your support as always 👏👏👏
