### ISSUE TITLE
Intermittent `DependencyInjectionException`s in unit tests

### ISSUE THREAD

**Issue by dave08** [micronaut-projects/micronaut-core#4342]
When running unit tests I get intermittent `io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [...` errors, when I use `./gradlew clean` and run the tests again, it works. I'm currently using Gradle 6.7 release.

### Environment Information

- **Operating System**: Linux Mint
- **Micronaut Version:** 2.1.1
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
Please provide an example that reproduces the problem

**Comment by dave08** [comment]
I'm not really sure what the cause is, I'm using `@MicronautTest` with MicronautData with a few entites and a repository (using test containers postgres as db). I add some data to the db, and then fetch it in the test. But the `@Inject lateinit var repo: SomeRepo` dependency in the test class seems to not be found intermittently. I first thought it happens when I make changes to the entity, but it seems to happen even without that...

In another project, I got the same error with a completely different setup (much more complex), but it seems to happen with the same dependency... one that I need to replace for my tests. It sometimes just ignores the one in the test module and tries to load the one in the main module. But this is also intermittent, I just clean the gradle build, and it works again.

**Comment by graemerocher** [comment]
Could be related to https://github.com/micronaut-projects/micronaut-core/issues/3742

KAPT is buggy

**Comment by dave08** [comment]
Doesn't sound like the problem... I tried setting incremental to false:
```kotlin
micronaut {
    micronautVersion = "2.1.1"
    runtime "netty"
    testRuntime "junit5"
    processing {
        incremental false
        annotations "com....deviceaccount.*"
    }
}
```
It still has troubles injecting a repository located in the test module, but only until I clean the gradle build. Maybe incremental needs to be disabled somewhere else too? I'm using the Micronaut gradle pluging 1.0.3

**Comment by graemerocher** [comment]
We'll need an example that reproduces the issue

**Comment by dave08** [comment]
It's a very hard one to pinpoint, I'll see if I can eventually get to some kind of pattern. If you have a general direction of where to look it might be easier though... I tried looking at the stubs generated by kapt last time it happened, and the class that seems to be missing to ApplicationContext is there... maybe it's the way `@MicronautTest` tries to load dependencies? The last time it happened for a dependency that injects a Jdbi instance, and the same datasource just happens to be used in the tests by another db wrapper (https://github.com/JetBrains/Exposed)... and it doesn't say the datasource is missing... even though I use this for putting up postgres in the test's init block:

```kotlin
@MicronautTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class OtaRequestsTest {
	init {
		Postgresql.start()
	}
        ...
``` 

```kotlin
import org.testcontainers.containers.PostgreSQLContainer

class Postgresql: PostgreSQLContainer<Postgresql>()  {
	companion object {
		private lateinit var instance: Postgresql
		fun start() {
			if (!Companion::instance.isInitialized) {
				// Reuse container between tests instead of starting a new one per execution
				instance = Postgresql()
				instance.dockerImageName = "postgres:9.6"
				instance
					.withReuse(true)
					.withUsername("some-user")
					.withDatabaseName("some-db")
					.withInitScript("db-structure.sql")
					.start()

				System.setProperty("datasources.default.url", instance.jdbcUrl)
				System.setProperty("datasources.default.username", instance.username)
				System.setProperty("datasources.default.password", instance.password)
			}
		}

		fun stop() {
			if (Companion::instance.isInitialized) {
				instance.stop()
			}
		}
	}
}
```

I wonder if those system properties are set on time before `@MicronautTest` builds the `ApplicationContext`...

**Comment by adamkobor** [comment]
We have the same issue, but - as @dave08 also pointed out - it's very hard to reproduce. Running the tests with Gradle's `--rerun-tasks` flag always solves the issue, however.
