### ISSUE TITLE
Information from MDC is not propagated to logs

### ISSUE THREAD

**Issue by jankolarik** [micronaut-projects/micronaut-core#4352]
### Issue
As the title hints, the information from the MDC is not properly propagated to the logs as is shown by the test in my reproducer which can be found at the end of this report.

### Steps to Reproduce
Please see the example application that is provided at the end of this bug report and which server as a reproducer. Specifically, run the `testPrincipalInLogs()` test. 

### Expected Behaviour

The test `testPrincipalInLogs()` in the `MdcPopulatingFilterTest.java` class should pass as the principal should be propagated from the MDC to the logs.

### Actual Behaviour

The beforementioned test failed because the principal is not propagated from the MDC into the log. Therefore the `testPrincipalInLogs()` will fail with this output since it does not find the principal in the log:

```
expected: <true> but was: <false>
Expected :true
Actual   :false
<Click to see difference>

org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:162)
	at my.app.MdcPopulatingFilterTest.testPrincipalInLogs(MdcPopulatingFilterTest.java:81)
        ...
```

### Environment Information

- **Operating System**: macOS Catalina Version 10.15.7
- **Micronaut Version:** 2.1.1
- **JDK Version:** 11.0.7.hs-adpt

### Example Application
Please see the link the the repository where I have created a reproducer for this bug: 
https://github.com/jankolarik/Information-From-MDC-Not-Propagated-To-Logs

**Comment by dstepanov** [comment]
Netty's access log is invoked before Micronaut filters if you add `LoggerFactory.getLogger("mylog").info("Hello World");` you can see your principal.

**Comment by jankolarik** [comment]
I am not sure that is the case, we specify the order of the filter with: 
`    @Override
    public int getOrder() {
        return ServerFilterPhase.SECURITY.order() + 1;
    }`
so that the `MdcPopulatingFilter.java` runs after `AuthenticationProviderUserPassword.java`, where we get the principal.

Even with adding you suggestion in, the test will still fail with the same stack trace.

The issue is that I want to be able to see the principal in the access log as well, not only in the normal logs (for which it is working).

**Comment by dstepanov** [comment]
@jankolarik Netty's access log is executed before the filter chain when your filter is triggered access is already logged.

**Comment by jankolarik** [comment]
So is there a feature/way of executing the filter chain before Netty's Access Log?

**Comment by graemerocher** [comment]
Not currently no

**Comment by jankolarik** [comment]
Is this something that might be considered in a later version?

**Comment by graemerocher** [comment]
You could maybe write your own handler that adds this to the netty channel and then propagates

**Comment by jankolarik** [comment]
Ok, thank you!
