### ISSUE TITLE
Using suspend fun in HttpClient sends the continuation info in the json payload

### ISSUE THREAD

**Issue by dave08** [micronaut-projects/micronaut-core#4360]
Given a client:
```kotlin
@Client(id = "some-service", path = "/")
interface SomeService {
    @Put("/something/{requestId}")
    suspend fun setState(@PathVariable requestId: Int, newState: SomeEnum): HttpStatus
}
```
wiremock logs report something like:
```
Accept: [application/json]
Connection: [close]
Host: [localhost:9613]
Content-Length: [156]
Content-Type: [application/json]
{"newState":"sent","continuation":{"completableFuture":{"completedExceptionally":false,"numberOfDependents":1,"done":false,"cancelled":false},"context":{}}}
```
I was expecting only:
`{"newState":"sent"}` to be in the body.

### Environment Information

- **Operating System**: linux mint
- **Micronaut Version:** 2.1.1
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
Try adding `@Body` to `newState`

**Comment by dave08** [comment]
Without @Body it sends it in json like above, with @Body it just sends the value of the status `"sent"`, I need the key "newState" (there could be multiple settings to set on the same endpoint)
