### ISSUE TITLE
ConfigurationProperties does not resolve from environment variable(s) in some cases

### ISSUE THREAD

**Issue by MikiLoz92** [micronaut-projects/micronaut-core#4362]
I have encountered a really particular case in which I'm unable to resolve a ConfigurationProperty out of an environment variable.

I have the following interface created:
```kotlin
@ConfigurationProperties("elastic")
interface ElasticConfiguration {
    val cloudId: String
    val username: String
    val password: String
    val indexPrefix: String
}
```

Then I inject this configuration in another class:
```kotlin
@Singleton
class ElasticsearchDocumentStorer(
        private val elasticConfiguration: ElasticConfiguration
) : CoroutineScope {

    private val indexPrefix = elasticConfiguration.indexPrefix

    suspend fun storeDocument(index: String, document: JsonObject) {
        val indexName = "${indexPrefix}-$index"
        ...
    }
}
```
This works OK, however if I change the `storeDocument` method's contents to this:
```kotlin
val indexName = "${elasticConfiguration.indexPrefix}-$index"
```
micronaut throws the following error at runtime, when accessing that method:
```
[astra-gateway] io.micronaut.core.value.PropertyNotFoundException: No property found for name [elastic.index-prefix] and type [java.lang.String]
[astra-gateway]         at io.micronaut.runtime.context.env.ConfigurationIntroductionAdvice.lambda$intercept$1(ConfigurationIntroductionAdvice.java:109)
[astra-gateway]         at java.util.Optional.orElseThrow(Optional.java:290)
[astra-gateway]         at io.micronaut.runtime.context.env.ConfigurationIntroductionAdvice.intercept(ConfigurationIntroductionAdvice.java:109)
[astra-gateway]         at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:82)
[astra-gateway]         at eos.connectivity.backend.astra.application.configuration.ElasticConfiguration$Intercepted.getIndexPrefix(Unknown Source)
[astra-gateway]         at eos.connectivity.backend.astra.application.infrastructure.persistence.ElasticsearchDocumentStorer.storeDocuments(ElasticsearchDocumentStorer.kt:62)
[astra-gateway]         at eos.connectivity.backend.astra.session.store.infrastructure.persistence.ElasticsearchFleetSessionStatusRepository.store(ElasticsearchFleetSessionStatusRepository.kt:26)
[astra-gateway]         at eos.connectivity.backend.astra.session.store.FleetSessionStatusUpdater.invoke(FleetSessionStatusUpdater.kt:10)
[astra-gateway]         at eos.connectivity.backend.astra.session.store.infrastructure.subscribers.StoreFleetSessionStatusOnFleetSessionStatusUpdatedEventSubscriber$invoke$1.invokeSuspend(StoreFleetSessionStatusOnFleetSessionStatusUpdatedEventSubscriber.kt:22)
[astra-gateway]         at eos.connectivity.backend.astra.session.store.infrastructure.subscribers.StoreFleetSessionStatusOnFleetSessionStatusUpdatedEventSubscriber$invoke$1.invoke(StoreFleetSessionStatusOnFleetSessionStatusUpdatedEventSubscriber.kt)
[astra-gateway]         at eos.connectivity.backend.astra.application.ExtensionsKt$fireSafeCoroutine$1.invokeSuspend(Extensions.kt:14)
[astra-gateway]         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[astra-gateway]         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
[astra-gateway]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[astra-gateway]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[astra-gateway]         at java.lang.Thread.run(Thread.java:748)

```

The property should be resolving from an environment variable called ELASTIC_INDEX_PREFIX, which at the moment of executing the method is there (I'm printing all env variables and I can see it right before). If I put the property in the application.yml file (as `elastic.index-prefix`), it resolves just fine and there are no errors.

This is happening in Micronaut 2.1.1, and was happening in Micronaut 1.3.5 as well, so I tried to update to see I could fix it, with not luck.

Unfortunately, I have been unable to provide a reproducer for this issue; it is only happening under my current project & setup, which uses Kubernetes.

If I can be of any help, I am available for a live screen sharing of this issue or private sharing of the code.

**Comment by alvarosanchez** [comment]
Can you [enable the `/env` endpoint](https://docs.micronaut.io/latest/guide/index.html#environmentEndpoint) and check it to see what configuration properties are resolved?

**Comment by MikiLoz92** [comment]
Sure, I'll try to do that today. Thanks for the tip.

**Comment by MikiLoz92** [comment]
I'm not able to start up the Micronaut HTTP server. It says everytime:
```
[INFO ] 2020-10-22 12:39:51.168 [main] Micronaut: 150 - No embedded container found. Running as CLI application
```
I'm running the fatjar created by shadowJar and I've tried every possible fix related to that error that I've found online.

It may be because I'm using Vert.x to provide an HTTP server...? I've disabled to Vert.x HTTP server itself, but I cannot make Micronaut start its own server whatsoever...

**Comment by MikiLoz92** [comment]
Saying this because AFAIK Vert.x also uses Netty for its HTTP server implementation...

**Comment by graemerocher** [comment]
Sounds like you have a pretty complex setup with lots of issues not related to Micronaut itself but more to your project. I suggest to progress this forward you provide an example that reproduces the issue.

**Comment by alvarosanchez** [comment]
@MikiLoz92 you are likely missing Micronaut HTTP server dependencies. Compare your build with a fresh one generated from https://launch.micronaut.io and try to see what are you missing

**Comment by MikiLoz92** [comment]
I have managed to procure a reproducer for this issue. It only seems to happen when I put Vert.x as a dependency and use its timer.

https://github.com/MikiLoz92/micronaut-configurationpropertiesbug-reproducer

To reproduce, run the main function and wait 5 seconds for the timer to trigger. You should see an error. If you uncomment the same property on the application.yml file, the error is gone.

I am printing the ENV variables just before the error, and I see the variable that this property is referring to just there, so that's weird.

**Comment by MikiLoz92** [comment]
@alvarosanchez I did have the Micronaut HTTP server dependencies on my project, but I guess that's a separate issue...

**Comment by graemerocher** [comment]
You are using `ApplicationContext.run()` instead of `Micronaut.run()`, the former only starts the context no the server
