### ISSUE TITLE
ConfigurationProperties do not resolve from ENV variables even when Micronaut server is active

### ISSUE THREAD

**Issue by MikiLoz92** [micronaut-projects/micronaut-core#4369]
Link to my previous issue:

https://github.com/micronaut-projects/micronaut-core/issues/4362

If I'm allowed to reply here, **the same is happening with `Micronaut.run()`**, could you take another look at it @graemerocher ??

Also, could you direct me to the place in the documentation that states that ConfigurationProperties are only usable from environment variables **if and only when** the Micronaut server is started?

**Comment by graemerocher** [comment]
Until there is actual bug established please keep to the discussion
