### ISSUE TITLE
Micronaut thymeleaf fragment file not found.

### ISSUE THREAD

**Issue by kevintanhongann** [micronaut-projects/micronaut-core#4403]
Tried loading some fragment and header using th:block and th:replace but didn't work on 2.1.2. 

`Caused by: java.io.FileNotFoundException: ClassLoader resource "views/fragments/home.html" could not be resolved`

Steps to reproduce: 
just run the project and load localhost:8080
you will notice that the th:block and th:replace was supposed to load the tags, but didnt.

**Comment by jameskleeh** [comment]
The directory had a space in the name
