### ISSUE TITLE
Improve quick start guide

### ISSUE THREAD

**Issue by ghost** [micronaut-projects/micronaut-core#4404]
1.  the default URL http://localhost:8080/ return none real good page, how about default put a success page? even a success let me feel right.
2. The default example hello world code mising the package name. the real working code minimal like this
```
package hello.world;

import io.micronaut.http.MediaType;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;

@Controller("/hello") 
public class HelloController {

    @Get(produces = MediaType.TEXT_PLAIN) 
    public String index() {
        return "Hello World"; 
    }
}
```

The default quick start not right , it led some compile error, make us feel not right. 

It broken my heart.

**Comment by jameskleeh** [comment]
> The default example hello world code

Where did the default code come from? What is the "default quick start"?

**Comment by ghost** [comment]
https://docs.micronaut.io/latest/guide/index.html#creatingServer
