### ISSUE TITLE
Cookie secure configuration is ignored when !request.isSecure

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-core#4409]
This is an issue for cases where the SSL is offloaded in a load balancer. The user should be able to set secure to true and have that be respected. Currently the secure configuration is only respected if `request.isSecure` returns true. We should be removing the default values from all configuration classes and change the logic to something like:

```
//pseudo code
if (configuration.isPresent()) {
cookie.secure(configuration.get())
} else {
cookie.secure(request.isSecure())
}
```

The problem with changing the behavior now is that there are default values that would be applied whereas today they are not.

See the discussion in https://github.com/micronaut-projects/micronaut-core/issues/2094

**Comment by Holophrasis-uk** [comment]
Is there an update or a work around for this issue? (environment is AWS ELB)
