### ISSUE TITLE
Injection within test application context not working as expected

### ISSUE THREAD

**Issue by ashish-sharma09** [micronaut-projects/micronaut-core#4420]
### Description
The demo project tries to reproduce the problem of testing the Micronaut application using the test application context where the overriding of application bean with mocked bean does not work anymore. 

This is the way we are writing most of the integration tests in our project. In some test files, we have multiple tests creating a new application context every time, overriding the behavior of some of the beans in the test path. This was working fine in version 2.0.3 we were using earlier but seems to be broken with 2.1.2

We also tried MicronautTest annotation which seems to be working fine for the demo project, but could not find a way to reset applicationContext for each test using this annotation.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Through command line or IDE run the test StatusControllerTest 

### Expected Behaviour

The test should pass with the size of components in the response being 2 as expected instead of 3.

### Actual Behaviour

The test fails as the size of components in the response comes back as 3 instead of 2.

Weirdly two components out of 3 seem to represent the same underlying instance (ie the mocked one being set in the setup). We expect to receive two components in the response (Component1 and mocked component2)

### Environment Information

- **Operating System**: MacOS Catalina 10.15.6
- **Micronaut Version:** 2.1.2
- **JDK Version:** 1.8

### Example Application

- https://github.com/ashish-sharma09/micronaut-injection

**Comment by wetted** [comment]
@ashish-sharma09 
I verified the behavior is different between Micronaut 2.0.3 and 2.1.x. However, if you just change your test to call `registerSingleton(…)` after the application context starts then your test passes. I will look into it, but there is a more idiomatic way to implement your test case, using the `@Replaces` and `@Requires` annotations. This is the kind of thing they are meant to support and we use that technique for tests in the framework itself.

I refactored your test case to demonstrate the recommended way to implement it. Note that you will need to add `testAnnotationProcessor "io.micronaut:micronaut-inject-java"` to your `build.gradle` dependencies for this to work.

```
package example.micronaut2;

import io.micronaut.context.ApplicationContext;
import io.micronaut.context.annotation.Replaces;
import io.micronaut.context.annotation.Requires;
import io.micronaut.runtime.server.EmbeddedServer;
import io.restassured.RestAssured;
import junit.framework.TestCase;
import org.junit.jupiter.api.Test;

import javax.inject.Singleton;
import java.util.Collections;

import static io.restassured.RestAssured.when;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.is;

public class StatusControllerTest extends TestCase {

    @Singleton
    @Replaces(Component2.class)
    @Requires(property="test.name", value="StatusControllerTest")
    static class MockComponent implements Component {
        @Override
        public String getName() {
            return "Test Component2";
        }
        @Override
        public Status getStatus() {
            return Status.FAIL;
        }
    }

    private EmbeddedServer server;

    @Override
    public void setUp() {
        server = ApplicationContext.run(
            EmbeddedServer.class,
            Collections.singletonMap("test.name", "StatusControllerTest"));
        RestAssured.port = server.getPort();
    }

    @Override
    protected void tearDown() {
        server.close();
    }

    @Test
    public void testWholeStatusIsFailWhenOneOutOf2ComponentsStatusIsFail() {
        when()
            .get("/_status")
            .then()
            .statusCode(200)
            .body("components.size()", is(2))
            .body("components[0].name", equalTo("Component1"))
            .body("components[0].status", equalTo("OK"))
            .body("components[1].name", equalTo("Test Component2"))
            .body("components[1].status", equalTo("FAIL"))
            .body("status", equalTo("FAIL"));
    }
}
```
