### ISSUE TITLE
Move from RxJava 2 to Reactor for Micronaut 3

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#4422]
This is up for discussion, but I strongly believe we should consider moving from RxJava 2 to Reactor for Micronaut 3 for the following reasons:

* Context propagation is built into a Reactor in a way that does not require thread locals and complex, error prone instrumentation
* R2DBC drivers are implemented in Reactor
* It will be easier for Spring Developers to use Micronaut
* RxJava 3 is out now and we have to make a breaking change anyway if we were to upgrade so I think we should just consider using Reactor instead
* Reactor is more stable now and a better fit for the server side

In terms of how this transition would play out, we would rewrite the internals of Micronaut to use Reactor instead of RxJava but continue to expose the existing `Rx*` interfaces in a backwards compatible way but instead in a new `micronaut-rxjava2` subproject thus there would be likely minimal breaking changes from a user perspective.

Same would happen for the existing `micronaut-rxjava3` project

We would then rewrite much of instrumentation logic to use reactor context propagation and provide instructions on what to do if you engage RxJava code.

**Comment by goeh** [comment]
Yes please!!! I've actually abandoned reactive code in most of my Micronaut services because I've been hit by so many weird problems with context propagation. I came from Spring Boot / Reactor and my feeling is that everything reactive there just worked (IMO).

**Comment by kmucha555** [comment]
I'm curious if the decision has been made? Any news about that?

**Comment by graemerocher** [comment]
Will be discussed soon

**Comment by graemerocher** [comment]
A decision has been made and Micronaut will move to Reactor in 3.0

**Comment by kmucha555** [comment]
Great! I believe it's a good decision.

**Comment by denis111** [comment]
I tried io.micronaut.reactor:micronaut-reactor with Micronaut v2.5.5 just to migrate out project to Reactor now while it's not so big to have it already use Reactor when Micronaut v3 released and there seems to be the issue with ServerRequestContext propagation in map, flatMap, etc. https://github.com/micronaut-projects/micronaut-core/issues/1228

**Comment by denis111** [comment]
Here's the bug I talked before https://github.com/micronaut-projects/micronaut-core/issues/5549
