### ISSUE TITLE
MethodInterceptor not executed when bean created by @Factory beans

### ISSUE THREAD

**Issue by rafaelrasso** [micronaut-projects/micronaut-core#4428]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
Steps to reproduce are in README.md of [MIA Demo](https://github.com/rafaelrasso/demo-micronaut-mia)

### Expected Behaviour
The Method Interceptor to be called on beans created by a bean factory, like when bean was created by `@Singleton`.

### Actual Behaviour
MethodInterceptor is not called when the bean was created in an `@Factory`

### Environment Information

- **Operating System**: macOS Catalina 10.15.6
- **Micronaut Version:** 2.0.3
- **JDK Version:** GraalVM 20.2.0.r11 (20.2.0.r11-grl) [SDK Man]

### Example Application
- [MIA Demo](https://github.com/rafaelrasso/demo-micronaut-mia)

**Comment by jameskleeh** [comment]
This is the expected behavior. The annotation must be placed on the factory method

**Comment by jameskleeh** [comment]
Note that factories are largely for creating beans for classes that you aren't in control of. Thus it wouldn't be possible to add AOP annotations to the methods of those classes.

**Comment by graemerocher** [comment]
This relates to the bean import feature on the Roadmap. It should be possible to do `@Import(MyInterceptor.class)` but it is not implemented yet
