### ISSUE TITLE
Rename io.micronaut.messaging.annotation.Header to io.micronaut.messaging.annotation.MessageHeader;

### ISSUE THREAD

**Issue by parisapo** [micronaut-projects/micronaut-core#4448]
This is a proposal and I guess minor but kind of reflects an accidental mistake - that might cost a bit of time if you dont notice , especially after long hours of work.

Is it possible the following annotation

```java
import io.micronaut.messaging.annotation.Header;
```

to be renamed 

```java
import  io.micronaut.messaging.annotation.KafkaHeader;
```

Since you can accidentally import this

```java
import io.micronaut.http.annotation.Header;
```

The underlying  code obviously is not affected - if you use the wrong annotation 

```java
    @Topic("some-topic")
    Single<String> sendMsg(@KafkaKey String key, String val,
                                                              @Header("messageType") String myHeader);

```

Thanks for considering - I do understand that this might not seem very important - or it might cause potentially a lot of refactorings - renames on the code base.

**Comment by adrianotr** [comment]
It seems this caused an issue in Micronaut JMS since 2.5.0.
The `@MessageHeader` annotation is not working. The `JMSArgumentBinderRegistry` only registers binders for the deprecated annotation `@Header`.

I've created https://github.com/micronaut-projects/micronaut-jms/issues/89

**Comment by graemerocher** [comment]
Fixed for Kafka with https://github.com/micronaut-projects/micronaut-kafka/commit/ad49d90d69a90a1c8e2b8f3416cb8573df2ed91b needs apply to the other message impls
