### ISSUE TITLE
DefaultHttpClient throws NoHostException on redirects with relative location header

### ISSUE THREAD

**Issue by quandor** [micronaut-projects/micronaut-core#4451]
### Steps to Reproduce

1. Clone https://github.com/quandor/micronaut-defaulthttpclient-relative-redirect-fails
2. Execute tests
3. Examine the failing test `redirectToRelativeUrl`

### Expected Behaviour

If DefaultHttpClient receives a redirect to a relative URL, it should apply that relative URL to the original request URL in order to get an absolute URL.

### Actual Behaviour

It fails with a `NoHostException`

### Environment Information

- **Operating System**: GNU/Linux 5.9.6-arch1-1
- **Micronaut Version:** 2.1.3
- **JDK Version:** openJDK 11

### Example Application
See Steps to Reproduce

**Comment by tyler-boyd** [comment]
We're also running into this. I saw discussion here: https://github.com/micronaut-projects/micronaut-core/pull/2762

I will try to patch this but no promises...
