### ISSUE TITLE
Returning a failed Rx3 Completable yields Status Code 200

### ISSUE THREAD

**Issue by Roshick** [micronaut-projects/micronaut-core#4452]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Controller that returns an rx3 failing Completable

### Expected Behaviour

Anything but a status code 200, maybe a 500 for internal server error?

### Actual Behaviour

A status code 200 is returned.

### Environment Information

- **Operating System**: Windows
- **Micronaut Version:** 2.1.3
- **JDK Version:** 15

### Example Application

https://github.com/Sixstix/micronaut-rx3-completable-bug

**Comment by Roshick** [comment]
I just realized the status code is appearently only a side effect, it seems like the Completable is never subscribed to:

    @Get
    public Completable testCompletable() {
        return Completable.error(new RuntimeException("Test"))
                .doOnError(error -> LOG.error(error.getMessage(), error));
    }

never prints the error message when the endpoint is called.

**Comment by Roshick** [comment]
Actually none of the Completables in my application are being executed. :/

**Comment by jameskleeh** [comment]
Rxjava3 needs a release but waiting for the build plugins issue to be resolved
