### ISSUE TITLE
Add support for annotation metadata on type arguments

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-core#4457]
As part of an effort to add support for the [Bean Validation Specification 2.0](https://beanvalidation.org/2.0/spec/), Micronaut Validation needs support for validation constraint annotations on type parameters.

For example, the current version of Micronaut supports something like
```
    @Size(min = 1, max = 10)
    @Valid
    List<Author> authors = []
```
where the List is constrained by the `@Size` validation annotation, and each `Author` element of the list is cascade validated (due to the presence of the `@Valid` annotation). 

However, Micronaut Validation also validates something like:
```
    @Valid
    @Max(20l)
    @NotNull
    int[] integers
``` 
Where the presence of `@Valid` implies each int in the array will be validated against the `@Max` constraint. This seems a non-conforming feature since the specification states `@Valid` can apply to arrays of objects, but it doesn't for primitives. I think this use of `@Valid` should be deprecated. I can find nothing in any version of the spec or TCK that implies this should work.

But by extension, Micronaut Validtor accepts this for validation.
```
    @Valid
    @Size(min=1, max=2)
    @NotNull
    List<String> strings
```
This implies `@Valid` specifies `@Size` should be applied to each `String` element, but this contradicts the first example for cascading validation of `List<Author>`. It's ambiguous here whether `@Size` should constrain the string elements or the list. In fact, Micronaut tries to apply the `@Size` constraint to both, which is clearly unintended and a defect in validation processing. But there's seemingly no clear way to resolve it because when validating at runtime, type erasure means both `authors` and `strings` are of type `List<Object>`. Cascade validation cannot be applied to `String` so there seems to be no clear way to reconcile this.

A solution is to add partial support for Bean Validation 2.0 with constraint annotations on type parameters. That reconciles the contradicting examples above using revised syntax like:
```
    // recommended
    @Size(min = 1, max = 10)
    List<@Valid Author> authors = []

    // or, as before, since that's a valid use
    @Size(min = 1, max = 10)
    @Valid
    List<Author> authors = []
```
and for the string container example
```
    List<@Size(min=1, max=2) String> strings
    // or 
    @NotNull
    List<@Size(min=1, max=2) String> strings
    // or 
    // says each string element is not null and 1 or 2 chars in length
    List<@NotNull @Size(min=1, max=2) String> strings
    // or even
    @NotNull // says list is not null
    @Size(min = 10, max = 20) // says list has 10 to 20 elements
    List<@NotNull @Size(min=1, max=2) String> strings
```

This will almost certainly require changes to inject-<lang> annotation processing, bean introspection processing and micronaut-validation.

**Comment by graemerocher** [comment]
Note that this is actually general support for annotations on type parameters, not specific to validation

**Comment by graemerocher** [comment]
Duplicates #4307

**Comment by graemerocher** [comment]
Actually this is the more general issue, sorry for the noise
