### ISSUE TITLE
Content type while streaming SSE

### ISSUE THREAD

**Issue by akozel** [micronaut-projects/micronaut-core#448]
I have a piece of code that streams data from controller:

    @Get(uri = "/", produces = MediaType.APPLICATION_JSON_STREAM, processes = MediaType.APPLICATION_JSON_STREAM)
    public Flux<Log> getAll() {
        return logEmitterProcessor
                .checkpoint();
    }

But in Google Chrome as responce Im getting wrong HEADERS:
```
content-encoding: gzip
content-type: application/json
```

And Body with wrong format:
`[{"logDateTime":[2018,7,28,14,8,3,508000000],"deviceId":"33","event":"playing"},{"logDateTime":[2018,7,28,14,8,3,508000000],"deviceId":"33","event":"playing"}`

the problem is '[' sing at the start of each line.

**Comment by jameskleeh** [comment]
@akozel Please upload an example application
