### ISSUE TITLE
Cannot obtain bean data from an associated @Prototype

### ISSUE THREAD

**Issue by JaroslavTulach** [micronaut-projects/micronaut-core#4484]
### Task List

- [ x ] Steps to reproduce provided
- [ NA ] Stacktrace (if present) provided
- [ x ] Example that reproduces the problem uploaded to Github
- [ x ] Full description of the issue provided (see below)

### Steps to Reproduce

I am writing a [UI extension](https://github.com/jtulach/micronautui/blob/5a336657c4a0be74b3451ea2381b803422a58470/README.md) based on Micronaut `@Introspected` annotation. Things are working fine and my [reactive UI framework](https://github.com/jtulach/micronautui/) is capable to implement classical TODO example with [Micronaut concepts](https://github.com/jtulach/micronautui/blob/b0bbbbbe522ec9c47f48ee388aab109e293fed5f/micronautui-demo/src/main/java/io/micronaut/ui/demo/Demo.java). However essential aspect of my solution is to keep additional data in my [prototype object](https://github.com/jtulach/micronautui/blob/b0bbbbbe522ec9c47f48ee388aab109e293fed5f/micronautui-api/src/main/java/io/micronaut/ui/impl/ObservableInterceptor.java) and I need to find the data when I have pointer to the bean only. I haven't found a simple way to do it.

### Expected Behaviour

The PR #4485 shows one possible solution.

### Actual Behaviour

Every [UI reactive](https://github.com/jtulach/micronautui/) class in my system has to provide a dummy override of `equals`:
```
    @Override
    public boolean equals(Object obj) {
        return super.equals(obj);
    }
```

It would be more natural if [code like this one](https://github.com/jtulach/micronautui/blob/b0bbbbbe522ec9c47f48ee388aab109e293fed5f/micronautui-demo/src/main/java/io/micronaut/ui/demo/Demo.java#L101) could be avoided.

### Environment Information

- **Micronaut Version: 2.1.2

### Example Application

https://github.com/jtulach/micronautui/

**Comment by jameskleeh** [comment]
Are you creating classes in the `io.micronaut` package (`import io.micronaut.ui.ObservableUI;`)? If so, you shouldn't do that. I don't understand the problem. Can you describe the problem you're facing more clearly?

**Comment by JaroslavTulach** [comment]
Thank you for taking a look at my inquiry. Let's give the package issue aside for now, my code is just an experiment. Imagine you have a [prototype that holds some important data](https://github.com/jtulach/micronautui/blob/master/micronautui-api/src/main/java/io/micronaut/ui/impl/ObservableInterceptor.java#L40):
```java
@Prototype
class CountingInterceptor implements MethodInterceptor<T, Object> {
   int counter = GLOBAL_COUNTER.incrementAndGet();
   private static final AtomicInteger GLOBAL_COUNTER = new AtomicInteger(0);

   @Override
    public Object intercept(MethodInvocationContext<T, Object> context) {
       return context.proceed();
    }
}
```
then there is [an annotation to apply such prototype](https://github.com/jtulach/micronautui/blob/master/micronautui-api/src/main/java/io/micronaut/ui/ObservableUI.java#L43) to some bean. Let's name it `@Countable`:
```java
@Countable
class MyBean {
}
```
Next, let's [launch the app, create few beans](https://github.com/jtulach/micronautui/blob/master/micronautui-api/src/test/java/io/micronaut/ui/impl/QueryProtoTest.java#L34):
```java
var ctx = ApplicationContext.run();
MyBean b1 = ctx.getBean(MyBean.class);
MyBean b2 = ctx.getBean(MyBean.class);
```
Annotating the `MyBean` class with `@Countable` effectively associates each instance of `MyBean` with one instance of `CountingInterceptor`. Each instance of `CountingInterceptor` carries unique value of `counter`. The question/inquiry is: How do I [get the value when I have a reference](https://github.com/jtulach/micronautui/blob/master/micronautui-api/src/main/java/io/micronaut/ui/impl/QueryProto.java#L41) to the bean instance? E.g. how shall I **implement following method**?

```java
static int findCounter(MyBean b) {
  // !!!???
}
```
so that the above code snippet can be finished with:
```java
assert 1 == findCounter(b1);
assert 2 == findCounter(b2);
```

What is the correct solution? I have found one [equals based trick](https://github.com/jtulach/micronautui/blob/master/micronautui-api/src/main/java/io/micronaut/ui/impl/QueryProto.java#L41). However it currently has some drawbacks described in #4485. Maybe there is a better way to resolve my problem than #4485. Suggestions appreciated!

**Comment by dstepanov** [comment]
@JaroslavTulach You can introduce a new method to get the counter: `@Introduction(interfaces = HasCounter.class)` and then:
```
static int findCounter(MyBean b) {
  return b instanceOf HasCounter ? ((HasCounter) b).getCounter() : -1;
}
```

You might check how I implemented compile time proxies for Hibernate:

https://github.com/micronaut-projects/micronaut-sql/blob/master/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/proxy/IntroducedHibernateProxyFactory.java#L90

BTW: You should avoid using `getTargetMethod()` which is triggering reflection, all the info is also present in `MethodInvocationContext`

**Comment by JaroslavTulach** [comment]
Yes, `@Introduction` solves my problem. This is how I [applied it](https://github.com/jtulach/micronautui/commit/d7e2fbeed1ce35946659aea540e6b06c1a43b548). No need to override `equals` anymore. Thank you Denis for your advice.

While experimenting with possible solutions I got a NPE from the annotation processor. I report it as a separate issue.

**Comment by dstepanov** [comment]
@JaroslavTulach You probably don’t need to have `proxyTarget = true`
