### ISSUE TITLE
Http Client request error in some examples.

### ISSUE THREAD

**Issue by tkec** [micronaut-projects/micronaut-core#449]
### Steps to Reproduce

1. Micronaut use `@Client` to request Spring Cloud Controller  

### Expected Behaviour

All http client requests return success.

### Actual Behaviour

I am confused that some examples return error, but similar examples return success.

E.g: 
`/client/declarativeClient/stringFlowable` return error: 
`Error occurred writing stream response: Unexpected character ('s' (code 115)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')`

`/client/declarativeClient/string` return OK.

`/client/directClient/map  ` return error: 
`{"message":"Internal Server Error: Error occurred reading HTTP response: Cannot decode byte buffer with value [{\"key\" : \"value\"}] to type: Map map"}`

`/client/directClient/mapJsonUtf8` return OK.

### Environment Information

- **Operating System**: Windows7
- **Micronaut Version:** 1.0.0.BUILD-SNAPSHOT
- **JDK Version:** JDK8

### Example Application

https://github.com/tkec/micronaut-test
Test code in `StringController`

**Comment by graemerocher** [comment]
1. The first error is because `stringFlowable` returns `"string"` which is not valid JSON. You need to set that the client consumes `text/plain` not json
2. The second error you are trying to parse a `Map` but the endpoint returns an array

**Comment by tkec** [comment]
@graemerocher I paste most codes into issue content, you can check it again. The behavior is confused in some cases.

**Comment by graemerocher** [comment]
when using `Flowable<Map>` the `Flowable` type is an unbound reactive type that may represent 1 or many results, so the expected response is an array of maps. If only a single map is returned you should use `Single<Map>`

**Comment by tkec** [comment]
Got it.
But the confused behavior is, request to `/string` return OK when use low-level httpclient, and declarative httpclient return error, both return result is `Flowable<String>`.
And request to `/map` is opposite to `/string`, low-level return error and declarative return OK, both return result is `Flowable<Map>`. @graemerocher
