### ISSUE TITLE
Introduction + Around not working with Groovy

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-core#4518]
https://github.com/micronaut-projects/micronaut-core/tree/introduction_around_groovy has a test IntroductionWithAroundOnConcreteClassSpec which is failing

**Comment by mattmoss** [comment]
I pushed some fixes to this branch.

**Comment by mattmoss** [comment]
@jameskleeh You already merged this work on another issue/PR, correct? If so, we should close this one.
