### ISSUE TITLE
Jackson serialization cannot be set correctly via `PropertySource.of`

### ISSUE THREAD

**Issue by tandel-pratik** [micronaut-projects/micronaut-core#4523]
Jackson's serialization features can be set easily using application.yaml but they can't be set properly using PropertySource.

Example of how it'll be set in YAML:

```
jackson:
  serialization:
    writeDatesAsTimestamps: false
```
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

Define a PropertySource like (sample code in Kotlin):
```
PropertySource.of(
                "my.jackson",
                mapOf("jackson.serialization.writeDatesAsTimestamps" to false)
            )
```

Note: renaming `writeDatesAsTimestamps` to alternate formats like `write-dates-as-timestamps` or `WRITE_DATES_AS_TIMESTAMPS` does not work either.
### Expected Behaviour

Tell us what should happen

### Actual Behaviour
* Serialization features are defined properly

### Environment Information

- **Operating System**: TODO
- **Micronaut Version:** TODO
- **JDK Version:** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by jameskleeh** [comment]
@pratik-brex I can't reproduce this. If you still can please upload an example app and I'll re-open the issue
