### ISSUE TITLE
Use class annotated with @Client for HTTP Client logging

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#455]
Currently, all the HTTP client logging is done with a logger associated to `io.micronaut.http.client. DefaultHttpClient`. This brings 2 problems:

1) When having Consul discovery in place, Consul's client traffic makes really hard to see anything else in the logs.
2) It's impossible to configure logging on a per-client basis.

If it's not feasible to use a logger from the class annotated with `@Client`, then at least the log level should be set-able from an `HttpClientConfiguration`, eg:

```groovy
@Named("hello")
@Singleton
class HelloConfiguration extends HttpClientConfiguration {
   public HelloConfiguration(ApplicationConfiguration applicationConfiguration) {
        super(applicationConfiguration);
        this.logLevel = Leve.TRACE;
    }
}
```

**Comment by graemerocher** [comment]
Are you working on this @puneetbehl ?

**Comment by puneetbehl** [comment]
yes
