### ISSUE TITLE
Allow to override consul client full path

### ISSUE THREAD

**Issue by nahue** [micronaut-projects/micronaut-core#456]
Here's my case:

We have a running consul populated with git2consul so the keys are something like `<repo>/<env>/<project>.yaml`.

For what i've read in ConsulConfigurationClient, the path is fixed to the `consul.client.config.path` configuration value, concatenated with the service id.

Is it possible to add a configuration key so we are able to override the entire path? because maybe the current consul project is not the same as the micronaut's service id (and also maybe in consul we have dots or hyphens in the path)

**Comment by nahue** [comment]
I'm kind of new to java (i come from a few years of exp with Python and Ruby) but if you like i think i can make a PR for this.

**Comment by graemerocher** [comment]
PRs are of course welcome

**Comment by nahue** [comment]
As i'm new to Java, i feel i'm missing a step. Do you know any doc that shows how to debug a local maven dependency?
I have a working Micronaut project with the local SNAPSHOT as a dependency, but i would love to be able to debug the discovery-client.

Thanks for such a great framework!

**Comment by graemerocher** [comment]
@nahue you can publish a local version with `./gradlew publishToMavenLocal` or `./gradlew pTML` for short

**Comment by nahue** [comment]
Created PR #472
