### ISSUE TITLE
Configuration of management endpoints not present respected in native-image.

### ISSUE THREAD

**Issue by michael-simons** [micronaut-projects/micronaut-core#4576]
Given a simple 2.2 demo downloaded from the generator with the "management" option added, Maven as build tool and a config like this:

```yml
endpoints:
  all.path: /management
  health:
    enabled: true
    sensitive: false
    details-visible: anonymous
```

and running via

```
./mvnw mn:run
```

I can query the health endpoint like this

```bash
 curl localhost:8080/management/health | jq 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   257  100   257    0     0  23363      0 --:--:-- --:--:-- --:--:-- 23363
{
  "name": "demo",
  "status": "UP",
  "details": {
    "compositeDiscoveryClient()": {
      "name": "demo",
      "status": "UP"
    },
    "service": {
      "name": "demo",
      "status": "UP"
    },
    "diskSpace": {
      "name": "demo",
      "status": "UP",
      "details": {
        "total": 1000240963584,
        "free": 785639215104,
        "threshold": 10485760
      }
    }
  }
}
```

After building the application with `./mvnw clean package -Dpackaging=native-image` 

the config is ignored and the endpoint is under 

```bash
curl localhost:8080/health | jq  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0   1071      0 --:--:-- --:--:-- --:--:--  1071
{
  "status": "UP"
}
```

Reproducer is attached.
[mm22.zip](https://github.com/micronaut-projects/micronaut-core/files/5573762/mm22.zip)

**Comment by michael-simons** [comment]
GraalVM 11 20.3 macOS, but happens with the docker build, too.

**Comment by alvarosanchez** [comment]
Tested with a Gradle build, and the result is 404:

```json
{
  "message": "Page Not Found",
  "_links": {
    "self": {
      "href": "/management/health",
      "templated": false
    }
  }
}
```

**Comment by michael-simons** [comment]
Yep. You’ll find it on its default `health` location.

**Comment by alvarosanchez** [comment]
Right, I see that now as part of your original comment

**Comment by alvarosanchez** [comment]
Tested with 2.1.4 and the behaviour is the same

**Comment by graemerocher** [comment]
It actually has nothing to do with the management endpoints. The reason is a problem with the Maven plugin in that it does not include:

```xml
          <annotationProcessorPaths combine.children="append">
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-graal</artifactId>
              <version>${micronaut.version}</version>
            </path>
          </annotationProcessorPaths>
```

Which means there is no static resource configuration. You can add the above definition which creates the correct static resource configuration.

The Maven plugin should probably be adding this dependency automatically (like the Gradle one does) or alternatively generating the correct `-H:IncludeResources` statement to include the files that exist in `src/main/resources`

**Comment by graemerocher** [comment]
Which the correct static resources config this condition fails:

https://github.com/micronaut-projects/micronaut-neo4j/blob/master/neo4j-bolt/src/main/java/io/micronaut/neo4j/bolt/condition/RequiresNeo4j.java#L35

**Comment by alvarosanchez** [comment]
@graemerocher So it is not possible to do that in Maven.

@michael-simons If you select the `graalvm` feature, it gives you a POM with the appropriate annotation processor

**Comment by michael-simons** [comment]
Thanks a lot @alvarosanchez ! 

When both build tools can be used now to create native images ootb, it is maybe a good idea to include the annotation processor by default? And have it skip processing if not native.

**Comment by alvarosanchez** [comment]
So I'm going to close this issue since, as of right now, the `graalvm` feature has to be selected.

However, I do think the situation can be improved. I have created #4578 as a follow-up
