### ISSUE TITLE
Research about adding a GraalVM profile to the parent POM

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#4578]
While validating https://github.com/micronaut-projects/micronaut-core/issues/4576, we realised about the situation that users can still generate a GraalVM native image even if they don't select the `graalvm` feature. This leads to generating native images that are incomplete, because the `micronaut-graal` annotation processor is not in the classpath.

One possibility we could explore is to add a profile to the parent POM like this:

```xml
<profile>
  <id>graalvm</id>
  <activation>
    <file>
      <exists>${env.JAVA_HOME}/bin/native-image</exists>
    </file>
  </activation>
  <dependencies>
    <dependency>
      <groupId>org.graalvm.sdk</groupId>
      <artifactId>graal-sdk</artifactId>
      <version>${graal.version}</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven-compiler-plugin.version}</version>
        <configuration>
          <annotationProcessorPaths combine.children="append">
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-graal</artifactId>
              <version>${micronaut.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>
</profile>
```

**Comment by alvarosanchez** [comment]
@michael-simons suggested including the annotation processor unconditionally, and then changing it to do nothing if the JVM being used is not GraalVM. 

This could work, but maybe we are adding unnecessary overhead to all users, even if very little.

@graemerocher thoughts?

**Comment by graemerocher** [comment]
Well they might build with another version of Java and then use native image in a container no?

**Comment by alvarosanchez** [comment]
In which case they will also have problems in Gradle.

Also, if they do what you say, our build plugins won't participate any more since the JAR is already created.

I don't think we can cover every single case, but maybe this one (someone generating an app and generating native images locally) we can.
