### ISSUE TITLE
Improve HTTP Client DEBUG log

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [micronaut-projects/micronaut-core#4581]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

Hello!

I would like to suggest an improvement regarding HTTP Client and DEBUG log level.

When setting the HTTP Client log to TRACE it shows too much information. The alternative is to use DEBUG log level, which misses an important information, the response along with its status code.

For example, when using DEBUG the following log is printed:

```
Sending HTTP Request: GET /users
Chosen Server: localhost(9001)
```

With TRACE enabled, among the massive and sensitive output we can see the following information:

```
Sending HTTP Request: GET /users
Chosen Server: localhost(9001)
HTTP Client Response Received for Request: GET http://localhost:9001/users
Status Code: 200 OK
```

My suggestion is for the DEBUG level to have a response information as well, but not like how TRACE shows them, something like:

```
Sending HTTP request to localhost(9001): GET /users
Received HTTP response 200 for GET http://localhost:9001/users
```

In 2 lines we can identify request and response details, which improves log gathering performance and storage.

I'll try achieve this behavior using HttpClientFilter, but I think these changes would improve the general quality regarding micronaut's http client.

### Steps to Reproduce

Set the HTTP Client log level to debug:
```
logger.levels.io.micronaut.http.client=DEBUG
```

Then send a request using any `@Client`.

### Expected Behaviour

To see response details in the log.

### Actual Behaviour

Only request details are shown.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.2.0
- **JDK Version:** 11

**Comment by graemerocher** [comment]
good ideas here, feel free to submit a PR. Contributions welcome!

**Comment by rafaelrenanpacheco** [comment]
I tried to build micronaut-core as [explained](https://github.com/micronaut-projects/micronaut-core#building-from-source) in the docs, but it didn't work. So I tried to build the v2.2.0 to make sure it wasn't a problem on master branch, and got the same error as well. These are the steps I did to build micronaut-core:

```
git clone https://github.com/micronaut-projects/micronaut-core.git --depth=1
cd micronaut-core
git fetch --tags
git checkout v2.2.0
gradle publishToMavenLocal
```

Then I got the following error:

```
* What went wrong:
Could not determine the dependencies of task ':bom-check:compileJava'.
> Could not resolve all task dependencies for configuration ':bom-check:compileClasspath'.
   > Could not resolve io.micronaut:micronaut-bom:2.1.3.
     Required by:
         project :bom-check > io.micronaut.xml:micronaut-jackson-xml:2.1.0
      > No matching variant of project :bom was found. The consumer was configured to find an API of a library compatible with Java 11, preferably in the form of class files, and its dependencies declared externally but:
          - Variant 'apiElements' capability io.micronaut:bom:2.2.0 declares an API of a component:
              - Incompatible because this component declares a platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
          - Variant 'enforcedApiElements' capability io.micronaut:bom-derived-enforced-platform:2.2.0 declares an API of a component:
              - Incompatible because this component declares an enforced platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
          - Variant 'enforcedRuntimeElements' capability io.micronaut:bom-derived-enforced-platform:2.2.0 declares a runtime of a component:
              - Incompatible because this component declares an enforced platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
          - Variant 'runtimeElements' capability io.micronaut:bom:2.2.0 declares a runtime of a component:
              - Incompatible because this component declares a platform and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them preferably in the form of class files)
```

I'm using the following gradle version:

```
------------------------------------------------------------
Gradle 6.7.1
------------------------------------------------------------

Build time:   2020-11-16 17:09:24 UTC
Revision:     2972ff02f3210d2ceed2f1ea880f026acfbab5c0

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          11.0.9.1 (Ubuntu 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OS:           Linux 5.4.0-54-generic amd64
```

I also tried to link the micronaut-core project on my current micronaut project in IntelliJ, but got compilations error as well. Is there some guide on how to contribute to this project?

Best regards,
Rafael Pacheco.

**Comment by ilopmar** [comment]
Hi Rafael,

Those docs are not 100% up-to-date. 

You don't need to checkout a tag but a branch. Please try with branch `2.2.x`. Also you need to use Java 8 because Micronaut still supports it.
I've tried with a fresh clone and the following works:

```
$ git clone https://github.com/micronaut-projects/micronaut-core.git --depth=1
$ cd micronaut-core
# you are on branch 2.2.x directly because that's the default branch now

$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)

$ ./gradlew publishToMavenLoca
```

Please let me know if you need more help :)

**Comment by rafaelrenanpacheco** [comment]
When using the wrapped gradle with Java 11 I was able to run `./gradlew publishToMavenLoca`. After that I changed the `DefaultHttpClient` with some new log message, run `publishToMavenLoca` again, and the changes were not picked in my project in IntelliJ. So I thought the reason was the version mismatch, since the main branch is using 2.2.1.BUILD-SNAPSHOT, something like that.  I set this version in `gradle.properties` and IntelliJ didn't find this release that I previously published using `publishToMavenLoca`.

How do you develop and test micronaut-core changes along with an existent project? My goal is this:

- I already have a project using micronaut, working just fine.
- I want to link the micronaut-core as a dependency of my project.
- I want to make changes to micronaut-core like the one proposed in this GitHub issue.
- I want to press "Debug" in my project, and it should pick the linked micronaut-core project along with the changes I made.
- If necessary, I will need to add some breakpoints in micronaut-core while running my application. 

Is there a better way to make changes to micronaut-core and test along with a project?

**Comment by ilopmar** [comment]
You need to add `mavenLocal()` repo to your application to be able to use the locally publishes snapshot version.

I recorded a screencast about how to contribute to Micronaut some time ago: https://micronaut.io/blog/2020-08-18-contributing-to-micronaut-publishing-and-reviewing-local-changes.html

**Comment by rafaelrenanpacheco** [comment]
Thanks Iván for that tutorial, it really helped me a lot. Shouldn't this video be linked in the readme? :smile: 

There was another issue in IntelliJ, but since this change was simple it didn't hinder the development. When importing micronaut-core in IntelliJ, a lot of dependency is missing or isn't found by IntelliJ:

![image](https://user-images.githubusercontent.com/12160864/100247700-60397c00-2f19-11eb-9951-48f7bc60ecd0.png)

I tried to `Reload All Gradle Projects`, `Rebuild Project`, but nothing seems to fix it. For a more complex contribution this could be a problem.

Anyway, the PR is ready :tada:
