### ISSUE TITLE
Micronaut's UriMatchTemplate.match method doesn't work the same as how Spring's UriTemplate

### ISSUE THREAD

**Issue by donbeave** [micronaut-projects/micronaut-core#4582]
I'm migrating my application from Spring Boot to Micronaut and found out that UriMatchTemplate is not exactly the same. Probably it's a bug, I am not sure yet, to figure it out I created this issue.

The main difference is that `match` method will return empty Optional instead of the result, here is an example of my code.

I have this URL format:

```java
private static final String URL_FORMAT = "https://www.mydomain.com/post/{postSlug}";
```

Spring Boot original code:

```java
UriTemplate template = new UriTemplate(MOVIE_URL_FORMAT);

Map<String, String> match = template.match("https://www.mydomain.com/post/abc");

// will return `abc`
match.get("postSlug");
```

I have converted this code to Micronaut:

```java
UriMatchTemplate template = UriMatchTemplate.of(URL_FORMAT);

// will return `Optional.empty`
Optional<UriMatchInfo> match = template.match("https://www.mydomain.com/post/abc")
```

I expect it will return `UriMatchInfo` object, where I can use `getVariableValues` method to retrieve the value for `postSlug` variable.

### Example Application

Please clone this repo: https://github.com/donbeave/micronaut-uritemplate, here is two tests which compare Micronaut and Spring behavior:
1) https://github.com/donbeave/micronaut-uritemplate/blob/master/app/src/test/java/micronaut/uritemplate/SpringTest.java
2) https://github.com/donbeave/micronaut-uritemplate/blob/master/app/src/test/java/micronaut/uritemplate/MicronautTest.java

**Comment by graemerocher** [comment]
It is not a design goal for `UriMatchTemplate` to be the same as the Spring impl. I believe you can use:

```
private static final String URL_FORMAT = "https://www.mydomain.com/post/{postSlug+}";
```

To achieve the same behaviour in Micronaut
