### ISSUE TITLE
Add ability to set HTTP response headers for reactive media

### ISSUE THREAD

**Issue by vnesek** [micronaut-projects/micronaut-core#4589]
Let say we got some media blob that provides it's content reactively and async function that returns said blob or singnals that blob is missing. For example, some CMS serving media, non blocking Google Cloud Storage or S3 API, HTTP proxy of some sort or async database driver.

We need to know if we've got a blob to set HTTP 404 or 200 response and set correct content type and content length on HTTP response. Response type for controller function would be in RxJava:

```kotlin
fun foo(): Maybe<HttpResponse<Flowable<ByteArray>>>
```

or Project Reactor:

```kotlin
fun bar(): Mono<HttpResponse<Flux<ByteArray>>>
```

or if using kotlin coroutines and reactive streams:

```kotlin
suspend fun baz(): HttpResponse<Publisher<ByteArray>>>
```

or kotlin flow and corutines:

```kotlin
suspend fun gas(): HttpResponse<Flow<ByteArray>>>
```

### Steps to Reproduce

After attempting several methods, as far as I can tell, you can't asynchronously fetch metadata and content. You can fetch complete blob data in advance in temporary file or memory or lose ability to set metadata on HttpResponse. 

```kotlin
// Some data blob suitable for async streaming ... we don't know length and type in advance
class Blob {
    val type = MediaType.APPLICATION_OCTET_STREAM
    val length = 9L

    // Provides an async flow of byte arrays
    val source = flow {
        emit("foo")
        emit("bar")
        emit("baz")
    }
        .map { it.toByteArray() }
}

// Some suspend source for blobs
suspend fun mediaSource() = Blob()

// We want to fetch Blob from suspending function and serve content from flow (or reactive stream)
// while having ability to control response HTTP headers
@Controller("/flow")
class FlowBytes {

    // Ok, but misses async fetching of Blob
    @Get("a")
    fun a(): Publisher<ByteArray> = Blob().source.asPublisher(Dispatchers.IO)

    // Ditto
    @Get("b")
    fun b(): Flow<ByteArray> = runBlocking {
        mediaSource().source
    }

    // Fails, returns content-length: 3 instead of 9 and just 'foo'
    @Get("c")
    suspend fun c(): HttpResponse<Publisher<ByteArray>> {
        val blob = mediaSource()
        return HttpResponse.ok(blob.source.asPublisher(Dispatchers.IO))
            .contentLength(blob.length)
            .contentType(blob.type)
    }

    // Fails with some weird class cast exception
    @Get("d")
    fun d(): Maybe<HttpResponse<Publisher<ByteArray>>> {
        return Maybe.just(Blob()).map { blob ->
            HttpResponse.ok(blob.source.asPublisher(Dispatchers.IO))
                .contentLength(blob.length)
                .contentType(blob.type)
        }
    }

    // Works but misses async fetching of Blob
    @Get("e")
    fun e(): HttpResponse<Flow<ByteArray>> {
        val blob = Blob()
        return HttpResponse.ok(blob.source)
            .contentLength(blob.length)
            .contentType(blob.type)
    }

    // Hangs, emits just 'foo'
    @Get("f")
    suspend fun f(): HttpResponse<Flow<ByteArray>> {
        val blob = mediaSource()
        return HttpResponse.ok(blob.source)
            .contentLength(blob.length)
            .contentType(blob.type)
    }}
```

### Expected Behaviour

Ability to reactively stream arbitrary media content type and set correct HTTP response headers.

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** 2.2.0
- **JDK Version:** 11+

**Comment by jameskleeh** [comment]
`a`, `b`, `e` -> what does "Ok, but misses async fetching of Blob" mean?
`c`, `f` -> Fails because its a suspend method when it shouldn't be
`d` -> `Maybe<HttpResponse<Publisher<ByteArray>>>` we don't support this type of signature. Only one publisher either that emits the response or the body.

**Comment by vnesek** [comment]
> a, b, e -> what does "Ok, but misses async fetching of Blob" mean?

In cases a, b, e we directly instantiate Blob() ... it's not fetched either from suspend (async) function mediaSource() nor it's fetched from some Publisher<Blob>, Mono<Blob> or Maybe<Blob>. Effectively it's blocking call in reactive framework.

That's the core issue that currently isn't supported by micronaut.

You can stream data, but can't set content type, add custom headers to responses with signature like:

```Flux<ByteArray>```

You can set content type, add custom headers to responses but can't stream data with signature like:

```Mono<HttpResponse<ByteArray>>```

What is not supported is asynchronously fetch Blob, transform it to HttpResponse and then stream data:

```Mono<HttpResponse<Flux<ByteArray>>>```

### Real world use case

Fetch Google Cloud Storage Blob larger than 200M and stream it while running micronaut service in Google Cloud Run. Set correct HTTP headers from Blob's metadata. API to fetch Blob returns Mono<Blob>, Blob data is available as Flux<ByteArray>

You can save blob to local disk or fetch all data at once in a 200M large memory byte[]. Both will blow out Cloud Run's memory limits. Either that or use blocking calls in controller methods (case a, b, e).

Perhaps there is some other way to do it but I just can't see it.

**Comment by jameskleeh** [comment]
@vnesek I don't know much about the Flow API, however constructing a `flow {}` object should be a cold observable which does not emit the items until it is subscribed. Returning a cold observable is not a blocking operation

**Comment by jameskleeh** [comment]
See https://kotlinlang.org/docs/reference/coroutines/flow.html#flows-are-cold

**Comment by vnesek** [comment]
@jameskleeh you are correct about kotlin flows but that's not what's bugging me.

Ignore kotlin flow, let's say we use Project Reactor:

```kotlin
interface Blob {
    fun data(): Flux<ByteArray>
    fun contentType(): String
}

fun someApi(): Mono<Blob> = ....
```

How would you write controller method setting content type and returning streaming Blob::data without blocking?

```kotlin
    @Get
    fun badBlockingGet(): HttpResponse<Flux<ByteArray>> {
        val blob = someApi().block() // <= we are blocking here
        return HttpResponse.ok(blob.data())
            .contentType(blob.contentType())
    }

    @Get
    fun cantSetContentType(): HttpResponse<Flux<ByteArray>> {
        val mono: Mono<Blob> = someApi()
        return HttpResponse.ok(mono.flatMapMany {
            // ...or we can't set content type (nor anything else on HTTP response)
            it.data()
        })
    }
```

**Comment by jameskleeh** [comment]
@vnesek That design doesn't make sense to me. Why would you return a `Mono` that emits an object that has a `Flux`? Having a stream that emits objects that have a stream seems like a bad idea without more context

**Comment by vnesek** [comment]
@jameskleeh check two comments up regarding use case I've got problem with.

Perhaps I wasn't clear enough:

1. You are given id/path to object stored in GCS, S3 bucket or some such API.

2. You call some reactive API to make network call that gets a Blob representing said storage object. What should such API return other than ```Mono<Blob>``` ?

3. Now we are stuck with ```Mono<Blob>```. From blob we get a stream of byte arrays representing object's data as ```Flux<ByteArray>``` .  Reading ByteArray involves network communication. If not Flux, what should be returned from Blob if we want to keep it reactive/async?

Given 1, 2 and 3. I would argue that design is quite natural if using reactive streams.

And then we have a problem as we can either get ```Flux<ByteArray>``` into ```HttpResponse``` or we can set metadata from Blob but we cannot do both at a same time. 

If you could provide any guidelines or good reactive design example for this use case, that fits well with return signatures supported by micronaut, please do so.

**Comment by jameskleeh** [comment]
@vnesek What is determining the content type? Is that data returned along with the byte stream from S3 for example?

**Comment by vnesek** [comment]
@jameskleeh Content type is stored in S3 (or some other remote service accessed over network) along with some additional metadata i.e. content length, etag, last modification time, etc... that should be placed in response HTTP headers.

For what is worth, Spring WebFlux has more-or-less same problem, but it's possible to work around it as they allow binding ServerHttpResponse (equivalent of MutableHttpResponse) as a handler method parameter. That gives you a chance to modify headers in a lambda before returning Flux for data. 

Same trick doesn't work in micronaut:

```kotlin
    @Get("h")
    fun h(): HttpResponse<Flux<ByteArray>> {
        val response = HttpResponse.ok<Flux<ByteArray>>()
        val source = Mono.create<Flow<ByteArray>> { sink ->
            val blob = runBlocking(Dispatchers.IO) { mediaSource() }
            response.contentType(blob.type) // (1)
            response.contentLength(blob.length) 
            sink.success(blob.source)
        }
        response.body(source.flatMapMany { it.asPublisher(Dispatchers.IO) }) // (2)
        return response
    }
```
as (2) will be executed before (1) and it will 'commit' response HTTP headers. IMHO (1) should throw IllegalStateException

**Comment by christophemaillot** [comment]
Another real word example : 

I'm building an image cache that fetches the data from 2 remote sources, with custom business logic and authorization management. 

So I'm first calling some remote APIs to check if the binary is available in one of the remote repositories. 
If so, I would like to emit a OK HttpResponse, who body is itself byte emitter. If not, emit a 401 ou 404 HttpResponse.

The byte emitter would call an other set of remote API to actually get and emit the binary content.

I've tried using some kind of method like this (but this is not supported, as mentioned earlier in this thread) :

```
@Get("/test")
public Single<HttpResponse<Flowable<String>>> test() {
    return Single.just(HttpResponse.ok(Flowable.just("hello")));
}
```

Hope this help,
Christophe.

**Comment by jameskleeh** [comment]
`Single<HttpResponse<Flowable<String>>>` is now supported in Micronaut 3
