### ISSUE TITLE
Micronaut Validator List<Enum> containing null values

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-core#4593]
from `ValidatorSpec.groovy`, I've added this test :

```java

    void "test cascade to bean - enum"() {
        given:
        EnumList b = new EnumList(
                enums: [null]
        )

        def violations = validator.validate(b).sort { it.propertyPath.iterator().next().name }
find { it.propertyPath.toString() == 'primaryAuthor.name'}

        expect:
        violations.size() == 1
    }


@Introspected
class EnumList {
    @Valid
    List<AuthorState> enums;
}

@Introspected
enum AuthorState {
    PUBLISHED,
    DRAFT
}

```

With : 
-  micronaut branch v2.2, I've this error  `java.lang.NullPointerException
	at io.micronaut.validation.validator.DefaultValidator.cascadeToOne(DefaultValidator.java:1327)`
-  micronaut version 1.3.7 seems to work as I understand

**Comment by jameskleeh** [comment]
I don't understand what is being validated here. There is no constraint being applied to the enum or the list, so what are you expecting?

**Comment by tchiotludo** [comment]
I'm in a special case here ! 
I'll try to make the example short as possible just to point to the NullPointer that must not be fired IMO.

In my case [here](https://github.com/kestra-io/kestra/blob/master/core/src/main/java/org/kestra/core/models/listeners/Listener.java#L20), we have a `List<Condition>`, Condition is abstract and I don't know the subclass.
I want subclass to expose the Constraint If they need (plugins systems).

* In [micronaut 1.3.7](https://github.com/kestra-io/kestra/blob/8382a27500137517fdcef4cac73650ebbeb25fe5/core/src/test/java/org/kestra/core/serializers/YamlFlowParserTest.java#L94), there is ContraintValidatation raise by this validation but also there is no NullPointer.
* In [micronaut 2.2](https://github.com/kestra-io/kestra/blob/feat/micronaut-2.2/core/src/test/java/org/kestra/core/serializers/YamlFlowParserTest.java#L103), there is NullPointer that prevent the others contraints to be raise normally. 

Just to point that the `NullPointerException` must not exists IMO.

**Comment by jameskleeh** [comment]
@tchiotludo I added this test https://github.com/micronaut-projects/micronaut-core/pull/4594/files#diff-b3e793497a14c9544a273d029aceb58e2822a5bc861c421b82e8d6bebb6eefbfR395 which I think better encapsulates the issue. Do you agree that would reproduce the bug?

**Comment by tchiotludo** [comment]
Seems to be good IMO, It will not raise a NPE id a `null` is present on the List. It will definitively fix my issues! Thanks

Just not really about this and javax specs : 
```
    @Valid
    @NotNull
    List<AuthorState> enums
```

Does the `@NotNull` apply only to `enums != null` or it must propagate to null in the List (`[null]`), I don't know the specs to be sure about that ?

**Comment by jameskleeh** [comment]
@tchiotludo It would apply to each enum in the list

**Comment by tchiotludo** [comment]
I see that, just more a question.

Just my first though are : 
```java
    @Valid
    @NotNull
    List<AuthorState> enums
```
only match with `enums == null` 

And if you want to have `@NotNull` on list, you must use this `List<@NotNull AuthorState>` see [this](https://beanvalidation.org/2.0/spec/#constraintdeclarationvalidationprocess-containerelementconstraints)

**Comment by jameskleeh** [comment]
@tchiotludo That is part of the bean validation 2.0 spec, which we do not support yet

**Comment by tchiotludo** [comment]
Ok I don't know that !
We have certainly better knowledge than me about that !
But the actual PR is fine for me, thanks 👍

**Comment by KateMost** [comment]
What about the @Pattern annotation for a List<String>? Will it be supported any time soon?
