### ISSUE TITLE
Native image is not bundling application.yml as a resource

### ISSUE THREAD

**Issue by viniciusccarvalho** [micronaut-projects/micronaut-core#4597]
Hi folks, Noticed that when we generate a native image with gradle, the generated app does not contain the application.yml file.

### Steps to Reproduce

Create a new 2.2.0 application and modify anything, for example change the server port. Generate the image and note that the server is running on 8080. In my case I had several other defaults I'd like to have loaded, I could confirm that using `MICRONAUT_CONFIG_FILES` and pointing to the yml file the app would behave as expected.  

### Expected Behaviour

Generated image should bundle application.yml

### Actual Behaviour

None of the properties on the bundled application.yml were loaded

### Environment Information

- **Operating System**: MacOS 10.15.7
- **Micronaut Version:** 2.2.0
- **JDK Version:** GraalVM 20.3-r11

**Comment by alvarosanchez** [comment]
Could this be related to #4576 ?

**Comment by viniciusccarvalho** [comment]
Probably, in my case it was gradle, it seems that the plugin is not including the application.yml on the resources section of the native image.

**Comment by alvarosanchez** [comment]
Did it have some code? (Controller, singleton bean, etc)?

**Comment by viniciusccarvalho** [comment]
No, it was really just a small web server to serve static content from a pre defined folder such as /var/www. I see do you think it's because there's no annotation processors running? I can try to add a minimal controller to confirm

**Comment by alvarosanchez** [comment]
99% sure it's because of that

**Comment by viniciusccarvalho** [comment]
Yep that was the case, so I agree its not a bug. Maybe add a one liner note bellow the section "Understanding Micronaut and GraalVM" that explains that if there's nothing for the annotation processor to process, no `resource-config.json` is generated. 
Thanks @alvarosanchez
