### ISSUE TITLE
Micronauts declarative client adds content-type header even when overidden

### ISSUE THREAD

**Issue by erikbo** [micronaut-projects/micronaut-core#460]
When I make a POST request using a created declarative Micronaut client it forces the header `content-type: application/json` onto the request, even when I specifically override it. I think this is a bug, but please let me know if this is expected behaviour.

### Steps to Reproduce

1. Create a declarative client making a post request with the content type header overidden:

```
@Header(name = HttpHeaders.CONTENT_TYPE, value = MediaType.APPLICATION_FORM_URLENCODED)
@Client("http://micronaut.io/")
interface micronautClient {

    @Post("/")
    fun test(@Body requestBody: String): Single<String>

}
```

2. Use this client to make a request:

`micronautClient.test("test").blockingGet()`

### Expected Behaviour

I'd expect a POST request to be made to micronaut.io with the header `content-type: application/x-www-form-urlencoded`.

### Actual Behaviour

Micronaut sends two `Content-Type` headers, `content-type: application/x-www-form-urlencoded` and `content-type: application/json`.

### Stack Trace

```
10:19:56.258 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1393ms. Server Running: http://localhost:63196
10:20:44.519 [nioEventLoopGroup-1-4] DEBUG i.m.http.client.DefaultHttpClient - Sending HTTP Request: POST /
10:20:44.519 [nioEventLoopGroup-1-4] DEBUG i.m.http.client.DefaultHttpClient - Chosen Server: micronaut.io(-1)
10:20:44.521 [nioEventLoopGroup-1-4] TRACE i.m.http.client.DefaultHttpClient - Accept: application/json
10:20:44.521 [nioEventLoopGroup-1-4] TRACE i.m.http.client.DefaultHttpClient - content-type: application/json
10:20:44.521 [nioEventLoopGroup-1-4] TRACE i.m.http.client.DefaultHttpClient - content-type: application/x-www-form-urlencoded
```

### Environment Information

- **Operating System**: Mac OS 10.13
- **Micronaut Version:** 1.0.0.M3
- **JDK Version:** Java 8

**Comment by graemerocher** [comment]
Instead of using `@Header` you should use `@Post(uri="/", produces =  MediaType.APPLICATION_FORM_URLENCODED)`

**Comment by erikbo** [comment]
Thanks @graemerocher. I tried this, made these changes to the client:
```
@Post("/", produces = arrayOf(MediaType.APPLICATION_FORM_URLENCODED))
    fun test(@Body requestBody: String): Single<String>
```

However this seems to be updating the Accept header instead of the content-type, stack trace:

```
10:48:37.759 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1689ms. Server Running: http://localhost:59595
10:48:46.918 [nioEventLoopGroup-1-4] DEBUG i.m.http.client.DefaultHttpClient - Sending HTTP Request: POST /
10:48:46.918 [nioEventLoopGroup-1-4] DEBUG i.m.http.client.DefaultHttpClient - Chosen Server: micronaut.io(-1)
10:48:46.922 [nioEventLoopGroup-1-4] TRACE i.m.http.client.DefaultHttpClient - Content-Type: application/json
10:48:46.922 [nioEventLoopGroup-1-4] TRACE i.m.http.client.DefaultHttpClient - Accept: application/x-www-form-urlencoded
10:48:46.922 [nioEventLoopGroup-1-4] TRACE i.m.http.client.DefaultHttpClient - host: micronaut.io
10:48:46.922 [nioEventLoopGroup-1-4] TRACE i.m.http.client.DefaultHttpClient - connection: close
10:48:46.922 [nioEventLoopGroup-1-4] TRACE i.m.http.client.DefaultHttpClient - content-length: 4
10:48:46.922 [nioEventLoopGroup-1-4] TRACE i.m.http.client.DefaultHttpClient - Request Body
```

I feel like I might be missing something here, any ideas?

**Comment by erikbo** [comment]
Update: Changed the annotation to use the `consumes` parameter instead of `produces` and that does what I want:

```
@Post("/", consumes = arrayOf(MediaType.APPLICATION_FORM_URLENCODED))
    fun test(@Body requestBody: String): Single<String>
```

Thanks for the guidance @graemerocher!
