### ISSUE TITLE
Feature Request - Allow properties to be resolved dynamically

### ISSUE THREAD

**Issue by viniciusccarvalho** [micronaut-projects/micronaut-core#4607]
This request comes after a good chat with @alvarosanchez. It seems that the PropertySource resolution works as follow (and I apologize if I misunderstood or its too simplistic view)

Properties are resolved ahead of time from the environment, be it a YAML, JSON, ENV or a backend config client such as configmaps or vault. But the framework loads all the keys ahead of time.

The approach to load all keys works well if the backend has some sort of hierarchical structure so one could load all keys from /config/${appname}.

But Google Cloud Secrets Manager is an example where a keys have no hierarchy and inside a project people can have several applications, listing all keys not only has performance issues, but would also expose other apps values.

It would be interesting if we could have some way to tap into a failed key from the property source and try to resolve it, say:

`@Value("${secret}")` fails because not key has been previously loaded, one could use this to try to fetch (and perhaps add it to the `finalMap`). 

This seems to be the least invasive way to work with the current implementation, allowing PropertySourceLoaders to react to key missing for example.

It's just an idea, I thought would allow other usages as well of the Property system.

@jameskleeh Something related to my questions on the channel too.

Thanks folks

**Comment by graemerocher** [comment]
This can be done by subclassing `DefaultEnvironment` and overriding the methods that resolve properties, although the way the code structured right now you would also have to subclass `DefaultApplicationContext` but once done you could define a `GoogleCloudApplicationContext` for example that allowed resolution to remote resources. You would probably want to cache somehow otherwise performance would not be great.

**Comment by viniciusccarvalho** [comment]
I'll take a look on this, thank you @graemerocher

**Comment by jameskleeh** [comment]
> "listing all keys not only has performance issues, but would also expose other apps values"

@viniciusccarvalho Aren't the other apps keys already exposed if the user can simply reference them and that would lead to a request for the value? Regarding the performance issues, perhaps you could have an allowed list or pattern in `bootstrap.yml` that the user could specify to limit the number of keys that are queried?

**Comment by viniciusccarvalho** [comment]
Yes, security is not really my biggest concern, apps with the same credentials would have access. More on the performance side on needing to list all keys inside a Secrets Manager instance. 

We could use a pattern, not sure if users will look into it as a replicated work if they need to both list the keys on a config file and use `@Value` to refer to them. But it is a good alternative too

Ideally I would like to let this be opaque for users. Although on spring we did use a prefix: `${sm://<key>}` which I'm not really keen of.

**Comment by viniciusccarvalho** [comment]
@graemerocher I was looking on how to override the `DefaultApplicationContext` but looking at the `Micronaut` code I noticed that Micronaut will load a DefaultApplication Context via: https://github.com/micronaut-projects/micronaut-core/blob/e938d4e9927d58cd802c56653f33282bc8381742/runtime/src/main/java/io/micronaut/runtime/Micronaut.java#L61 

and 

https://github.com/micronaut-projects/micronaut-core/blob/e938d4e9927d58cd802c56653f33282bc8381742/inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java#L242

https://github.com/micronaut-projects/micronaut-core/blob/e938d4e9927d58cd802c56653f33282bc8381742/inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java#L284

How can I tell Micronaut to use a different ApplicationContext implementation, I could not tell from this code path.

**Comment by graemerocher** [comment]
you would need a subclass of `Micronaut` as well it seems

**Comment by viniciusccarvalho** [comment]
I think I'll park this for the moment then,  IMHO I still think there's a point in case to enable developers (specially those doing integration with other middlewares) to have a chance to enhance the property resolution, such as in this case. For instance if DefaultEnvironment could have an Optional ExternalPropertyResolver and if the property is not found anywhere on the chain of property resolvers via ` public <T> Optional<T> getProperty(@NonNull String name, @NonNull ArgumentConversionContext<T> conversionContext)` it would then invoke `getProperty` on that registered service that could look it up on demand. Just a thought.

For now, I think it would be best to keep SM simple and just like other config clients load the config file on startup with all keys and do not support injection of arbitrary key/pairs.

Thank you all for the support

**Comment by graemerocher** [comment]
Closing this for the moment, if you have any other ideas let us know

**Comment by paulhilliar** [comment]
Subclassing Micronaut doesn't have to be traumatic - you can do it with just curly braces.

`public static void main(String[] args) {

        val propertySource = new TestPropertySource();

        val mn = new Micronaut() {}

                .classes(MyApplication.class)

                .propertySources(propertySource)

                .args(args);

        val appCtx = mn.start();
`
