### ISSUE TITLE
ConstraintExceptionHandler confuse behavior for 1 and N violations

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [micronaut-projects/micronaut-core#4616]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

Hello!

Long time ago there were some changes on the [ConstraintExceptionHandler](https://github.com/micronaut-projects/micronaut-core/blob/2.2.x/validation/src/main/java/io/micronaut/validation/exceptions/ConstraintExceptionHandler.java) class through the issue #980.

The confusing part is how the handler creates a response when only 1 rule is violated and how different it is when N rules are violated. These 2 ways to handle the same issue (request rules violation) causes an overhead on the frontend, because the frontend now have to understand these 2 types of violation output. I understand that the frontend must do the same validation on the client side and not rely just on the backend validation, but a backend is not only consumed by the frontend. Another backend, third party services and so on will have to be prepared for these 2 types of bad request output.

To explain what is going on with some examples, let's use a create user request with some validation:

```java
@Introspected
public class UserCreateRequest {

    @NotBlank
    private String name;

    @NotBlank
    private String email;
}
```

If I send a request without the `name` field I get this response:

```json
{
  "message": "userCreateRequest.name: must not be blank",
  "_links": {
    "self": {
      "href": "/users",
      "templated": false
    }
  }
}
```

If I send a request without the `name` and the `email` fields, I get this response:

```json
{
  "message": "Bad Request",
  "_links": {
    "self": {
      "href": "/users",
      "templated": false
    }
  },
  "_embedded": {
    "errors": [
      {
        "message": "userCreateRequest.email: must not be blank"
      },
      {
        "message": "userCreateRequest.name: must not be blank"
      }
    ]
  }
}
```

So, in the first response the `message` output has the rule violation message, but in the second response the `message` is a default bad request message, and the rules violations are instead on the `_embedded.errors` field.

Is there a reason for the first output example don't be like this?

```json
{
  "message": "Bad Request",
  "_links": {
    "self": {
      "href": "/users",
      "templated": false
    }
  },
  "_embedded": {
    "errors": [
      {
        "message": "userCreateRequest.name: must not be blank"
      }
    ]
  }
}
```

No matter if 1 rule is violated or N rules are violated, the response schema would be the same.

I understand that we can create our own ExceptionHandler to override the default ConstraintViolationException, but shouldn't this be the default behavior for micronaut?

The ConstraintExceptionHandler.handle could be changed to something like this:

```java
@Override
public HttpResponse<JsonError> handle(HttpRequest request, ConstraintViolationException exception) {
    Set<ConstraintViolation<?>> constraintViolations = exception.getConstraintViolations();

    JsonError error;

    if (exception.getMessage() == null) {
        error = new JsonError(HttpStatus.BAD_REQUEST.getReason());
    } else {
        error = new JsonError(exception.getMessage());
    }

    if (constraintViolations != null && !constraintViolations.isEmpty()) {
        List<Resource> errors = new ArrayList<>();

        for (ConstraintViolation<?> violation : constraintViolations) {
            errors.add(new JsonError(buildMessage(violation)));
        }

        error.embedded("errors", errors);
    }

    error.link(Link.SELF, Link.of(request.getUri()));

    return HttpResponse.badRequest(error);
}
```

### Steps to Reproduce

1. Send a request with 1 violated rule
1. Send a request with 2+ violated rules

### Expected Behaviour

To receive the same JSON schema showing the violated rule or rules.

### Actual Behaviour

One dedicated JSON for 1 violated rule and another dedicated JSON for 2+ violated rules.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 2.2.0
- **JDK Version:** 11

**Comment by graemerocher** [comment]
I agree `_embedded` should always be included

**Comment by rafaelrenanpacheco** [comment]
This fix is being harder than I expected. Somewhere in the deepest of micronaut's core something is doing the following algorithm right before the output response:

1 - check if `_embedded.errors` (or any path?) is an array with 1 element.
2 - if it is, then marshal to json as object, not as an array with 1 element.
3 - else, marshal to json as an array, with 2+ elements.

This is the fix for the `ConstraintExceptionHandler` class:

```java
@Override
public HttpResponse<JsonError> handle(HttpRequest request, ConstraintViolationException exception) {
    Set<ConstraintViolation<?>> constraintViolations = exception.getConstraintViolations();

    JsonError error;

    if (constraintViolations == null || constraintViolations.isEmpty()) {
        if (exception.getMessage() == null) {
            error = new JsonError(HttpStatus.BAD_REQUEST.getReason());
        } else {
            error = new JsonError(exception.getMessage());
        }
    } else {
        error = new JsonError(HttpStatus.BAD_REQUEST.getReason());

        List<Resource> errors = new ArrayList<>();

        for (ConstraintViolation<?> violation : constraintViolations) {
            errors.add(new JsonError(buildMessage(violation)));
        }

        error.embedded("errors", errors);
    }

    error.link(Link.SELF, Link.of(request.getUri()));

    return HttpResponse.badRequest(error);
}
```

As you can see both 1 or 2+ rule violation are being stored as array. But something is converting the JsonError to this for 1 violation:

```
{
  "message": "Bad Request",
  "_links": {
    "self": {
      "href": "/validated/pojo",
      "templated": false
    }
  },
  "_embedded": {
    "errors": {
      "message": "pojo.email: Email should be valid"
    }
  }
}
```

and keeping as an array for 2+ violations:

```
{
  "message": "Bad Request",
  "_links": {
    "self": {
      "href": "/validated/pojo",
      "templated": false
    }
  },
  "_embedded": {
    "errors": [
      {
        "message": "pojo.email: Email should be valid"
      },
      {
        "message": "pojo.name: must not be blank"
      }
    ]
  }
}
```

There's still a schema diff between these 2 cases.

@graemerocher do you have any clue on what could be marsheling to json with this dedicated 1-element-array algorithm?

I tried to debug but didn't find any marshal along the way.

**Comment by graemerocher** [comment]
Perhaps `ResourceSerializerModifier`
