### ISSUE TITLE
Can Micronaut integrated with Envoy?

### ISSUE THREAD

**Issue by ggservice007** [micronaut-projects/micronaut-core#463]
Envoy is an L7 proxy and communication bus designed for large modern service oriented architectures.

https://www.envoyproxy.io/

Can Micronaut integrated with Envoy?  

Or May I use Micronaut with Consul and Envory at the same time?  Any Idea?

**Comment by graemerocher** [comment]
I don't see any reason why not, I am not sure what Micronaut would need to do specifically. This maybe seems of interest https://github.com/jippi/consul-envoy
