### ISSUE TITLE
Feature request: add support absolute URIs in UriMatchTemplate

### ISSUE THREAD

**Issue by donbeave** [micronaut-projects/micronaut-core#4635]
The current implementation of `UriMatchTemplate` only supports relative URIs:

```java
String urlFormat = "/post/{+postSlug}";

UriMatchTemplate template = UriMatchTemplate.of(urlFormat);

// will return: Optional[/post/abc]
Optional<UriMatchInfo> match = template.match("/post/abc");
```

But if change `urlFormat` to the absolute URI template, it will not work as expected:

```java
String urlFormat = "https://www.mydomain.com/post/{+postSlug}";

UriMatchTemplate template = UriMatchTemplate.of(urlFormat);

// will return: Optional.empty
Optional<UriMatchInfo> match = template.match("https://www.mydomain.com/post/abc");
```

**Comment by preyest1300** [comment]
Hi! If there is no one working on this I would like to tackle it.

**Comment by graemerocher** [comment]
Sounds great!

**Comment by donbeave** [comment]
@preyest1300 Wow!!! Thank you so much!!!

**Comment by loveshah751** [comment]
Hi Guys.

I think I have solved this issue. Below is the output after I made changes.

**> Task :http:uriMatchTemplateTest.main()
Optional[/post/abc]
Optional[https://www.mydomain.com/post/abc]** 

Is this what you are expecting for this issue.

Thanks
Lovepreet Singh

**Comment by donbeave** [comment]
Yes, looks correct.

**Comment by loveshah751** [comment]
Sounds good then. I will create a PR for this issue. But do I need to write groovy test case, as I don't saw any junit test cases for this project.

**Comment by loveshah751** [comment]
#4682, Add the PR for the above issue

**Comment by donbeave** [comment]
@loveshah751 thank you!
