### ISSUE TITLE
incemental compiling can't be used beacuse gadle doesn't know anything about META-INF/spring-configuration-metadata.json

### ISSUE THREAD

**Issue by volkerrichert** [micronaut-projects/micronaut-core#4642]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Setup gradle with incremantal compiling enabled
2. start gradle with --info
3. change some code to start recompiling

### Expected Behaviour

I expect gradle to compile only changed files

### Actual Behaviour

Gradele starts recompiling the full souces beacuse of:

`Full recompilation is required because the generated resource 'META-INF/spring-configuration-metadata.json in CLASS_OUTPUT' must have exactly one originating element, but had 0. Analysis took 1.138 secs.`

### Environment Information

- **Operating System**: Win10
- **Micronaut Version:** 2.1.4 & 2.2.0
- **JDK Version:** 15

### Example Application
I have the following code as part of my buildfile

```

tasks.withType(JavaCompile) {
    options.encoding = "UTF-8"
    options.compilerArgs.addAll([
        '-parameters',
        // enables incremental compilation
        '-Amicronaut.processing.incremental=true',
        '-Amicronaut.processing.annotations=com.vodafone.service.*',
        "-Amicronaut.processing.group=$project.group",
        "-Amicronaut.processing.module=$project.name",
    ])
}

```

**Comment by graemerocher** [comment]
Note this only impacts projects that define `@ConfigurationProperties`

**Comment by volkerrichert** [comment]
yes, i use ConfigurationProperties to have app configs. Any way to solve it?

**Comment by graemerocher** [comment]
Not right now, will need a bug fix

**Comment by volkerrichert** [comment]
Ok, i'll stay turned
