### ISSUE TITLE
Disable access logger for management endpoints

### ISSUE THREAD

**Issue by tandel-pratik** [micronaut-projects/micronaut-core#4653]
Access Logging described here: https://docs.micronaut.io/latest/guide/index.html#accessLogger is turned on for both management and regular HTTP endpoints. For services that have scrapers that hit the health / info endpoints this introduces a lot of logging and it'd be ideal to disable those logs.

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

* Turn on access logging with instructions in the docs: https://docs.micronaut.io/latest/guide/index.html#accessLogger
* Send request to any management endpoint

### Expected Behaviour

* There should be a flag for disabling logging for management endpoints

### Actual Behaviour

* Expected behavior doesn't exist

### Environment Information

- **Operating System**: TODO
- **Micronaut Version:** TODO
- **JDK Version:** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by tandel-pratik** [comment]
@graemerocher I'm thinking of just taking a stab at it. From an API perspective, should I go with a boolean value to disable / enable it for management endpoints or should I try something else? I don't know if it's common to have more than 2 HTTP servers (default one, management one) and in those use cases something that's not represented as a boolean would be better.

**Comment by tandel-pratik** [comment]
One way to achieve this would be to use the zalando logbook hook which lets you customize which paths you want to log: https://docs.micronaut.io/snapshot/guide/index.html#nettyPipeline

This solves our purpose of excluding logs from periodic scrapers that call /health /info /prometheus

**Comment by timyates** [comment]
Done by https://github.com/micronaut-projects/micronaut-core/pull/6753 in Micronaut 3.3.0
