### ISSUE TITLE
RxHttpClient is not identifying proxy servers IP address changes

### ISSUE THREAD

**Issue by kavithaThirumoorthy** [micronaut-projects/micronaut-core#4656]
**Steps to Reproduce:**
 1. We are using Micronaut application as docker container in AWS ECS and using a proxy for public access from within VPC. The proxy is having dynamic ip allocation and the ip can change over time.

2. In this application  custom HttpClientConfiguration is used for RxHttpClient. The proxy is set in the following way

**Configuration class:**
public class CustomHttpClientConfiguration extends HttpClientConfiguration {

    private final DefaultHttpClientConfiguration.DefaultConnectionPoolConfiguration connectionPoolConfiguration;

    @Inject
    public CustomHttpClientConfiguration(ApplicationConfiguration applicationConfiguration,
                               DefaultHttpClientConfiguration.DefaultConnectionPoolConfiguration connectionPoolConfiguration) {
        super(applicationConfiguration);
        this.connectionPoolConfiguration = connectionPoolConfiguration;
        setProxyType(Proxy.Type.HTTP);
        InetSocketAddress inetSocketAddress = new InetSocketAddress("proxyHostName", 3128);
        setProxyAddress(inetSocketAddress);
        setConnectTtl(Duration.ofSeconds(60));  
          }
}

3. **Snippets of Client class is as below:**
@Singleton
public class CustomDetailsHTTPClientImpl  {

   private RxHttpClient httpClient;
   public CustomDetailsHTTPClientImpl(@Client(value = "${host}", configuration = CustomHttpClientConfiguration.class) RxHttpClient httpClient) {
       this.httpClient = httpClient;
   }
   public getPropertyValue(){
   
       Flowable<HttpResponse<String>> flowableHttpResponse = httpClient.exchange(HttpRequest.GET("URI"), String.class);
       HttpResponse<String> httpResponse;
       httpResponse = flowableHttpResponse.blockingSingle();
   }

}

**Expected Behaviour:**
Since  proxy is dynamic. Httpclient should identify the IP address changes and forward the request.
  

**Actual Behaviour:**
HttpClientConfiguration class gets the Ip at the time of startup (which is set with InetSocketAddress).  
This Ip address is cached then. When proxy Ip address changes,  it throws exception. 
When we restart the application, the new IP address is obtained and works fine. 

**Stacktrace:**
Caused by: io.micronaut.http.client.exceptions.HttpClientException: Connect Error: Connection refused: proxyhost/xx.xx.xx.xx:3128at 
io.micronaut.http.client.DefaultHttpClient.lambda$null$26(DefaultHttpClient.java:1038)at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500)at
 io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493)at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472)at 
 io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413)at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538)at
 io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:531)at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:111)at 
 io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:323)at
 io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:339)at 
 io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:685)at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)at
 io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)at
  io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)at
   io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)at
 io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)at
  io.micronaut.http.context.ServerRequestContext.lambda$instrument$0(ServerRequestContext.java:68)at
   io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)...
 1 moreCaused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: 
 Connection refused: proxyhost/xx.xx.xx.xx:3128 Caused by: java.net.ConnectException: 
 Connection refusedat sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)at
 io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)at 
 io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:336)at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:685)at
 io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)at 
 io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)at 
 io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)at 
 io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)at
 io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)at
  io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:52)at
   io.micronaut.http.context.ServerRequestContext.lambda$instrument$0(ServerRequestContext.java:68)at
 io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)at java.lang.Thread.run(Thread.java:748)

**Environment Information**
Operating System: AWS ECS
Micronaut Version: 1.3.4
JDK Version: 1.8

**Same proxy host name we use for connecting with SSM  in aws sdk clients which are working fine with the dynamic proxy changes.**  
**This issue basically with Micronaut and  InetSocketAddress implementation.**
**Please let me know how to avoid this  proxy Ip address caching by RxHttpClient without restarting the application**

**Comment by kavithaThirumoorthy** [comment]
Hi Team, any update on this. It is very critical issue for us.

**Comment by kavithaThirumoorthy** [comment]
Hi Team, any update on this. It is very critical issue for us.

**Comment by kavithaThirumoorthy** [comment]
Please team,  any update on this issue

**Comment by graemerocher** [comment]
Do you have a reproducer?

**Comment by graemerocher** [comment]
It would greatly aid in trying to get to the bottom of the problem

**Comment by kavithaThirumoorthy** [comment]
Thanks for the reply.

The scenario is as below,

In our application, while accessing external APIs, we are hitting it through a forward proxy with a load balancer.
This proxy server, links with more than one IP address and the IP address is dynamic due to auto scaling.

 As per above mentioned code snippet, the application gets the proxyHost name and port at the time of application start-up
and then this values cached throughout which is confirmed from our logs also.

 This dynamic IP address for the proxy server is a recent change. Before this change, only static IP addresses was linked with proxy host. So our application always connects to one of those IPs. We didn't have any problem.

 After infra team rolled over their change for dynamic IP address of this proxy server, we are facing this problem I.e
our application is trying to connect to the old IP address which could have got terminated due to autoscaling action. I have attached the error log in the previous post.

 Please let me know if any other information is needed.

**Comment by kavithaThirumoorthy** [comment]
any update on this please.

**Comment by jameskleeh** [comment]
@kavithaThirumoorthy This issue is among all other issues in our list. If you would like this issue prioritized, OCI offers support . Email me at kleehj@objectcomputing.com if you are interested.

**Comment by yawkat** [comment]
Your call to `new InetSocketAddress(String, int)` performs name resolution. The framework will then always use the IP you resolved at the start. If you want to defer the resolution, you need to use `InetSocketAddress.createUnresolved`. I don't think there's any forever-caching, so that should eventually see new IPs of the proxy, as well.
