### ISSUE TITLE
Declarative client with @RequestBean and @PathVariable not working

### ISSUE THREAD

**Issue by TorosyanV** [micronaut-projects/micronaut-core#4666]
When I'm using declarative client with **@RequestBean** and **@PathVariable** generated path is wrong,
provided @PathVariable is missing.

### Expected Behaviour

When I have client like this 

 ```JAVA
@Client("https://myapi.com")
public interface ClientApi {

  @Get(value = "/users/{userName}")
  Flowable<User> getUser(@RequestBean GetUserRequest bean);

}
```
and have POJO is 
```JAVA

@Introspected
public class GetUserRequest {

  @PathVariable
  private String userName;

  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

}
```
Should be  Send HTTP Request: GET /users/someUserName

### Actual Behaviour
Where is no any PathVariable after /users
example from logs
`[default-nioEventLoopGroup-1-4] DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP Request: GET /users/`

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** 2.1.3
- **JDK Version:** 11

But this example is working 

 ```JAVA
 @Get(value = "/users/{userName}")
 Flowable<User> getUser(@PathVariable String userName);
```
output from logs
`[default-nioEventLoopGroup-1-4] DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP Request: GET /users/someUserName
`
I don't know it's a bug or this feature is not supported. But it will be better to support such simple things, otherwise Declarative client is useless .

**Comment by asodja** [comment]
~Most likely this is because in 2.1.3 `@RequestBean` is not supported for `@Client`. I see that support was added few days ago in https://github.com/micronaut-projects/micronaut-core/pull/4610.~

Update: nvm, I tried 2.2.x branch and `@PathVariable` for Client does not work there either.
