### ISSUE TITLE
Feature request - Trim request strings

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [micronaut-projects/micronaut-core#4675]
Hello!

First of all, is there a way to trim string fields from requests globally? Usually there is no reason to accept a string field with blank spaces before and after the string, which leads to a codebase full of this:

```java
String email = userCreateRequest.getEmail().trim();
String name = userCreateRequest.getName().trim();
```

The above case is null safe because the request payload has the `@NotBlank` rule. Otherwise it would require a null check or the use of some helper like `trimToNull`.

Some frameworks like fastify or laravel allow to trim all strings through middleware, which leads to a cleaner codebase.

If there is no such thing in Micronaut, did you consider some kind of strategy to handle this "issue"? For example:

**1 - Global property**
- Add to `application.properties` something like: `micronaut.mvc.request.strings=trim` or `micronaut.mvc.request.strings=trim-to-null`.

**2 - Request type annotation**
```java
@Introspected
@Trimmed(toNull = false)
public class UserCreateRequest {

    @NotBlank
    private String name;

    @NotBlank
    @Email
    private String email;
}
```

**3 - Request field annotation**
```java
@Introspected
public class UserCreateRequest {

    @NotBlank
    @Trimmed
    private String name;

    @NotBlank
    @Email
    @Trimmed
    private String email;
}
```

If this kind of feature isn't suitable for micronaut-core, what's the best way to achieve this from an user point of view? If it is a good feature to have in micronaut, I can help with a PR, just need some lead where to code this feature.

**Comment by jameskleeh** [comment]
This is some code I found that should do want you want:

```
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.deser.std.StdScalarDeserializer;
import com.fasterxml.jackson.databind.module.SimpleModule;
import javax.inject.Singleton;

import java.io.IOException;

@Singleton
public class StringTrimModule extends SimpleModule {

    public StringTrimModule() {
        addDeserializer(String.class, new com.fasterxml.jackson.databind.deser.std.StringDeserializer() {
            @Override
            public String deserialize(JsonParser jsonParser, DeserializationContext ctx) throws IOException,
                    JsonProcessingException {
                String value = super.deserialize(p, ctxt);
                return value != null ? value.trim() : null;
            }
        });
    }
}
```

This could be in our code base only enabled by toggling on a configuration option by adding `@Requires(property = "jackson.trim-strings", value = StringUtils.TRUE)` to the class

**Comment by gabbagnale** [comment]
hello, u mean add a trim to the Introspected bean used as a RequestBean?
