### ISSUE TITLE
Documentation: several broken links in chapter 5.5 Cache advice

### ISSUE THREAD

**Issue by deining** [micronaut-projects/micronaut-core#4695]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Visit chapter 5.5 [Cache advice](https://docs.micronaut.io/latest/guide/index.html#caching) of Micronaut documentation
2. Click one of the several links given there (e.g. `@Cacheable`)

### Expected Behaviour

Link should redirect to `https://micronaut-projects.github.io/micronaut-cache/latest/api/io/micronaut/cache/annotation`/Cacheable.html

### Actual Behaviour

Link redirects to a non existing URL: `https://docs.micronaut.io/latest/api/io/micronaut/cache/annotation/Cacheable.html`

**Comment by deining** [comment]
Please note that this issue is completely independent from my latest PR (#4694, #4704).
The issue raised above has **not** been addressed yet, so this issue should be reopened.

What I'm observing here:

Links in chapter 5.5. `Cache Advice` do work when invoking the snapshot of the user guide: 
https://docs.micronaut.io/snapshot/guide/index.html

An example for an valid link is:
https://docs.micronaut.io/snapshot/api/io/micronaut/cache/CacheManager.html

However, links do **not** work with other versions of the guide, e.g. version 2.2.1:
https://docs.micronaut.io/2.2.1/guide/index.html

In this case, the links are broken, for example: 
https://docs.micronaut.io/2.2.1/api/io/micronaut/cache/CacheManager.html

I'm not sure what will be the proper way to resolve this, actually, I'm in doubt whether this should be resolved by modifying the .adoc source. If so, please advise and I'm willing  to author a PR.

**Comment by jameskleeh** [comment]
@deining The source files that are being linked no longer exist in this repo so that is the cause of the 404s. The links should instead go to https://micronaut-projects.github.io/micronaut-cache/latest/api/io/micronaut/cache/CacheManager.html for example

The reason it works in snapshot is because the files used to exist in the snapshot docs and we don't clear out old files when publishing new versions of snapshot documentation
