### ISSUE TITLE
Tuning Annotation processor

### ISSUE THREAD

**Issue by thhart** [micronaut-projects/micronaut-core#4702]
I have a big project with a lot of modules and dependencies, annotation processing is enabled where I want to achieve however the controllers are not getting registered. I know this might have a lot of reasons but instead of fixing the world I would like to understand how the processor gets started and if I can control it manually in a better way. Preferable by scoping it to specific packages. Unfortunately I can not find anything about this topic?

**Comment by jameskleeh** [comment]
I'm not aware of a way to limit what classes are scanned/processed by package. If you have a valid use case for something like that you can file an issue. In the future questions should be asked in our [gitter](https://gitter.im/micronautfw) or start a [discussion](https://github.com/micronaut-projects/micronaut-core/discussions)
