### ISSUE TITLE
HttpServer should listen only on localhost and not in all network interfaces

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#471]
With the default configuration Micronaut HttpServer will listen in all network interfaces instead of `localhost`, even if the startup message says so: `Server Running: http://localhost:8080`

We can check that the application listens on all interfaces with:
```
$ netstat -an | grep 8080
tcp6       0      0 :::8080                :::*                    LISTEN
```

As a workaround we can define `micronaut.server.host = localhost` and it will listen only on localhost:

```
$ netstat -an | grep 8080
tcp6       0      0 127.0.0.1:8080         :::*                    LISTEN
```

The safest configuration is listen only on localhost because it's safer when we deploy the application in any internet-accessible machine. If the user want to configure Micronaut to be directly accessible from the Internet they should do it manually.

**Comment by ilopmar** [comment]
I can probably add more context to this.
I think that can be misleading for a user see the message `http://localhost:8080` and then discover that the service is accessible from the internet. For me is like running your database on `localhost` and then discover that anyone can connect to it because it is not really localhost.
In other frameworks (specially frontend stuff) I've seen the message like `http://0.0.0.0:8080` so the user won't be surprise that the application is listening in all network interfaces.

**Comment by graemerocher** [comment]
This issue can be resolved with configuration:

```yaml
micronaut:
     server:
          host: localhost
```

If we make the default to be the above then there would be no way to bind to all network interfaces which may not be desirable.

**Comment by alvarosanchez** [comment]
Can it not be the other way around? i.e. it listens by default only on 127.0.0.1, and then by configuration you can make it listen in all interfaces.

**Comment by ilopmar** [comment]
I think at least we should change the message because it is misleading for a user to see `http://localhost:8080` and then discover than the application is listening in all interfaces.

**Comment by graemerocher** [comment]
@alvarosanchez What do you suggest said configuration should look like?

**Comment by alvarosanchez** [comment]
I don't have a strong opinion, but could be something like:

```yaml
micronaut:
     server:
          host: *
```

And also:

```yaml
micronaut:
     server:
          hosts:
            - 127.0.0.1
            - 10.0.5.30
```

**Comment by graemerocher** [comment]
The logic where this happens is here https://github.com/micronaut-projects/micronaut-core/blob/master/http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java#L260

I'm not sure binding to a list of hosts is possible
