### ISSUE TITLE
@Retryable doesn't work for bean factories like mentioned in documentation

### ISSUE THREAD

**Issue by zinoviy23** [micronaut-projects/micronaut-core#4733]
In `@Retryable` [documentation](https://docs.micronaut.io/2.2.1/guide/index.html#retry) it mentioned, that it is possible to retry bean creation in `@Factory`. But it doesn't works.

Example in doc:
```java
@Factory 
public class Neo4jDriverFactory {
    ...
    @Retryable(ServiceUnavailableException.class) 
    @Bean(preDestroy = "close")
    public Driver buildDriver() {
        ...
    }
}
```

There is an example with bug in the [repository](https://github.com/zinoviy23/potential-mn-retryable-bug-example).
Like in the doc there is a factory, which creates a bean.
```java
package com.example;

import io.micronaut.context.annotation.Bean;
import io.micronaut.context.annotation.EachBean;
import io.micronaut.context.annotation.Factory;
import io.micronaut.retry.annotation.Retryable;

import javax.inject.Singleton;

@Factory
public class MyBeanFactory {
    @Singleton
    @Bean(preDestroy = "close")
    @Retryable
    MyBean createBean(MyClass1 a) {
        System.out.println(a);
        System.out.println("attempt");
        throw new RuntimeException("(((");
    }
}
```

And expected behaviour after running the app and calling `http://localhost:8080/` is 3 `attempt` in output and then the exception about bean creation.

But actual behavior is failing as far as route is called without retrying.

**Comment by jameskleeh** [comment]
@zinoviy23 The documentation is misleading. I don't know if it was created a time when it in fact did work the way you're expecting or if it was just poorly worded. `@Retryable` on a factory method will allow the methods in the returned bean to be retried. The bean creation itself is not retryable. You can achieve that by delegating the bean creation to a singleton bean with `@Retryable` on it. If you look at the `Neo4jDriverFactory` today, you will see that has been done.

**Comment by zinoviy23** [comment]
I see, thank you.
