### ISSUE TITLE
Micronaut @Client("/") UnknownHostException

### ISSUE THREAD

**Issue by defect-slayer** [micronaut-projects/micronaut-core#4736]
I have some test anotated with `@MicronautTest`, and client is injected as 

```java
@Inject
@Client("/")
protected HttpClient client;
    
```

I local it works fine, but in jenkins when these tests are run inside docker I get error

```log
io.micronaut.http.client.exceptions.HttpClientException
        Caused by: java.net.UnknownHostException
```

It doesn't says anything what it is trying to access as host (localhost, 127.0.0.1 or containerid)

containers are running without network, and most probably enabling network is not an option.

how to fix this?
### Task List

- [x] Steps to reproduce provided
1. Write unit test and use @Client("/")
2. use httpclient and make request to one of the endpoints.
3. run the test in docker without network.
- [x] Stacktrace (if present) provided
```
io.micronaut.http.client.exceptions.HttpClientException
        Caused by: java.net.UnknownHostException
```
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Environment Information

- **Operating System**: centOS
- **Micronaut Version:** 2.1.2
- **JDK Version:** 11

### Example Application

Ref:https://stackoverflow.com/questions/65395163/micronaut-test-unknownhostexception?noredirect=1#comment115616754_65395163

**Comment by jeffscottbrown** [comment]
```
import io.micronaut.http.annotation.*;

@Controller("/demo")
public class DemoController {

    @Get(uri="/", produces="text/plain")
    public String index() {
        return "Example Response";
    }
}
```

```
import io.micronaut.http.HttpStatus;
import io.micronaut.http.client.HttpClient;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import org.junit.jupiter.api.Test;

import javax.inject.Inject;

import static org.junit.jupiter.api.Assertions.assertEquals;

@MicronautTest
public class DemoControllerTest {

    @Inject
    @Client("/")
    HttpClient client;

    @Test
    public void testIndex() throws Exception {
        assertEquals(HttpStatus.OK, client.toBlocking().exchange("/demo").status());
    }
}
```

Are you seeing that a test like that will fail if run inside of a Docker container?

**Comment by defect-slayer** [comment]
Yes exactly.
But I think problem is the way docker is run. I am running it in a CICD process and there its run inside docker where networking is not enabled.
May I know somehow when I use ` @Client("/")` and make a request, where does the request goes.
* localhost?
* 127.0.0.1
* or some where else?

**Comment by jameskleeh** [comment]
@devloper-404 That is resolved here https://github.com/micronaut-projects/micronaut-core/blob/2.2.x/http-client-core/src/main/java/io/micronaut/http/client/DefaultLoadBalancerResolver.java#L95

I would need a sample app and steps to reproduce to debug this further

**Comment by bakatz** [comment]
@jameskleeh I am seeing this issue even outside of a docker container. AdoptOpenJDK11, latest stable Micronaut version

`DefaultLoadBalancerResolver` doesn't even get invoked so your fix won't be applied. The issue is in this method: `io.micronaut.http.client.netty.RxNettyHttpClientRegistry#getClientKey` where the client key returns a null ID, therefore the clientID check fails and DefaultLoadBalancerResolver doesn't get invoked.

I have no idea why this client ID is null, but based off the logic this is why it won't call DefaultLoadBalancerResolver. I'm currently checking to see if I can figure out some kind of workaround like defining my own load balancer resolver that doesn't have this behavior.

**Comment by jameskleeh** [comment]
Will reopen if an example is uploaded with steps to reproduce
