### ISSUE TITLE
Content type header not being added to static assets

### ISSUE THREAD

**Issue by rferreira** [micronaut-projects/micronaut-core#4739]
Hello folks, in a fairly basic setup with micronaut/netty (v2.2.0) serving static assets but they are not getting any content type. 

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Setup a new micronaut project
2. Add a static-resource setup pointing to a class path location
3. Add a static file in that location

Example config:
```yaml
micronaut:
  router:
    static-resources:
      assets:
        enabled: true
        mapping: "/public/**"
        paths: "classpath:public"
```

### Expected Behavior

I would expect the response to include the content type like this: 

```
 curl -I http://localhost:8080/public/images/logo.svg               
HTTP/1.1 200 OK
Date: Tue, 22 Dec 2020 05:15:31 GMT
connection: keep-alive
transfer-encoding: chunked
content-type: image/svg+xml
```

### Actual Behavior

but instead we get this (notice the missing content-type response header)
```
 % curl -I http://localhost:8080/public/images/logo.svg    
HTTP/1.1 200 OK
Date: Tue, 22 Dec 2020 05:21:47 GMT
connection: keep-alive
transfer-encoding: chunked
```

### Environment Information

- **Operating System**:  MacOs Big Sur
- **Micronaut Version:**  2.2.0
- **JDK Version:**  JDK15

I do feel like I'm missing a setting somewhere that says "micronaut.router.static-resources.*.add-content-type" but that doesn't seem to exist.

**Comment by jameskleeh** [comment]
I can't reproduce this. Please upload an example application with steps to reproduce

**Comment by rferreira** [comment]
Here it is, https://github.com/rferreira/micronaut-issue4739 you can validate it by simply running a curl, I'll see if I can potentially get a PR out as well.

**Comment by jameskleeh** [comment]
@rferreira I can't reproduce with your sample app:

```
micronaut-issue4739 main $ curl -i localhost:8080/public/foo.svg
HTTP/1.1 200 OK
Date: Tue, 22 Dec 2020 16:35:06 GMT
connection: keep-alive
Content-Type: image/svg+xml
Date: Tue, 22 Dec 2020 16:35:06 GMT
Expires: Tue, 22 Dec 2020 16:36:06 GMT
Cache-Control: private, max-age=60
Last-Modified: Tue, 22 Dec 2020 16:34:46 GMT
Content-Length: 11

<svg></svg>micronaut-issue4739 main $ 
```

**Comment by rferreira** [comment]
wow, that's odd, I'll keep digging. Sorry for wasting your time.
