### ISSUE TITLE
Filter Annotations cannot be stacked on @Client (at least for HttpClientFilter)

### ISSUE THREAD

**Issue by ggerbaud** [micronaut-projects/micronaut-core#4767]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create two Filter Annotations
```java
@FilterMatcher
public @interface FilterA {}
@FilterMatcher
public @interface FilterB {}
```
2. Create two Filters implementations
```java
@FilterA
@Singleton
public class MyFilterA implements HttpClientFilter {
	@Override
	public Publisher<? extends HttpResponse<?>> doFilter(MutableHttpRequest<?> request, ClientFilterChain chain) {
		// do something
                return chain.proceed(request);
	}
}
@FilterB
@Singleton
public class MyFilterB implements HttpClientFilter {
	@Override
	public Publisher<? extends HttpResponse<?>> doFilter(MutableHttpRequest<?> request, ClientFilterChain chain) {
		// do something else
                return chain.proceed(request);
	}
}
```
3. Create an annotation to group the two previous one
```java
@FilterA
@FilterB
public @interface AllFilters {}
```

4. Create a Client
```java
@AllFilters
@Client("/path")
public interface FiltersNotWorkingDemoClient {}
```
### Expected Behaviour

Filters should be associated with the client and applied

### Actual Behaviour

Filters are only applied if both individually declared
```java
@FilterA
@FilterB
@Client("/path")
public interface FiltersWorkingDemoClient {}
```
### Environment Information
Not relevant

### Example Application

- demo here : https://github.com/ggerbaud/mn-filter-demo

### Solution
It can be solved (if it should) at this line : https://github.com/micronaut-projects/micronaut-core/blob/2.2.x/http-client-core/src/main/java/io/micronaut/http/client/filter/DefaultHttpClientFilterResolver.java#L88
replacing
```java
matches = context.getAnnotationMetadata().hasAnnotation(filterAnnotation);
```
by
```java
 matches = context.getAnnotationMetadata().getAnnotationNamesByStereotype(FilterMatcher.class).contains(filterAnnotation);
```

What do you think ?

**Comment by jameskleeh** [comment]
@ggerbaud Seems reasonable to me. Mind sending a PR?

**Comment by ggerbaud** [comment]
@jameskleeh sure, PR sent
