### ISSUE TITLE
Support Jackson Configuration for JsonFactory

### ISSUE THREAD

**Issue by re-thc** [micronaut-projects/micronaut-core#4768]
Currently there's no way to enable / disable features for Jackson JsonFactory like there is for parser and generator. Would be great if these can also be made configurable.

https://github.com/FasterXML/jackson-core/wiki/JsonFactory-Features

**Comment by jameskleeh** [comment]
@hc-codersatlas You can create a JsonFactory bean and it will be used.

**Comment by re-thc** [comment]
Sure, thanks. Possible to add it to the yaml configuration like the other features?

**Comment by Ivan01925** [comment]
@graemerocher Hello, is this issue still open? I would like to contribute

**Comment by jameskleeh** [comment]
@Ivan12273 Yes its still open, PR welcome

**Comment by Ivan01925** [comment]
Hi again, sorry I wont be able to continue with this issue, I unassign me if anyone else want to try it.

**Comment by Praytic** [comment]
Hi @jameskleeh, could you assign this issue to me and approve the workflows?

**Comment by graemerocher** [comment]
Thanks for the contribution!
