### ISSUE TITLE
Consider updating micronaut-validation to Jakarta Bean Validation 3.0

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#4770]
This will enable modules such as `micronaut-hibernate-validation` to use Hibernate Validator 7.

[Jakarta Bean Validation 3.0](https://jakarta.ee/specifications/bean-validation/3.0/)

**Comment by sergey-morenets** [comment]
Any updates on this? The next month Jakarta EE 10 will be released

**Comment by graemerocher** [comment]
Scheduled for Micronaut 4
