### ISSUE TITLE
HEAD requests are broken for controllers returning Flowables 

### ISSUE THREAD

**Issue by ronhitchens** [micronaut-projects/micronaut-core#4774]
I'm porting some code from another platform and it needs to have a few HEAD endpoints that return metadata in headers.  Obtaining that info entails making some calls to other services, which can be slow/expensive so it should be asynchronous.

I could not get HEAD to work correctly, either using the `@Head` annotation or implicitly via a `@Get` annotated controller.  It appears that when the request is a HEAD, that the `Flowable` returned by the controller is not subscribed to.  The method is invoked and the code runs, but none of the Flowable code is executed.  A generic 200 is returned, unrelated to what the controller produces.

A GET request to the same controller works as expected.

If a controller returns a simple `HttpResponse`, then HEAD works as expected.  But you lose asynchrony.

Annotating the controller with `@Head` fails in a similar way.

Attached is a zip file of a trivial little Gradle app with some JUnit tests that demonstrate the issue.

### Steps to Reproduce

1. Unpack the attached zip file
2. `./gradlew clean test`

### Expected Behaviour

I should be able to set result status and headers on an `HttpResponse` to a HEAD request.

### Actual Behaviour

Cannot set an `HttpResponse` for a HEAD request if the controller returns a `Flowable`.  My Flowable result is ignored.

### Environment Information

- Operating System: MacOS, Linux
- Micronaut Version: 2.2.2
- JDK Version: 8

### Example Application

See attached zip file of trivial app and tests

[headbroken.zip](https://github.com/micronaut-projects/micronaut-core/files/5772514/headbroken.zip)

**Comment by jameskleeh** [comment]
If you want to return a `Flowable`, you have to indicate that only a single result is expected. That can be done with `@Get(uri = '/foo/{id}', single = true)`. Without that knowledge we assume the intent is to emit multiple items as part of the body. Alternatively you can return a `Single` and that would allow Micronaut to infer only a single item is expected.
