### ISSUE TITLE
@Introspected doesn't work for fields inherited from parent class

### ISSUE THREAD

**Issue by mcanalesmayo** [micronaut-projects/micronaut-core#4776]
When having a class extending another class, and the child class annotated with `@Introspected`, it only works for fields of the child class. Something like:
```
@Data // Lombok getters and setters
public class BaseBean {
  @Header(X_CLIENT_ID)
  @Nullable
  private String clientId;

  @PathVariable
  private String parentField;
}

@Introspected
@Data // Lombok getters and setters
public class PostBean extends BaseBean {
  @Header(CONTENT_TYPE)
  @Nullable
  private String contentType;
}

@Controller("/{parentField}")
public class MyController {

  @Post
  public Mono<MutableHttpResponse<Void>> myPostMethod(@RequestBean PostBean bean) {
    // bean.clientId and bean.parentField are always null
    // bean.contentType is set as expected
  }
}
```

Adding `@Introspected` to the parent class doesn't help, and manually including all the fields in the annotation with `@Introspected(includes = { "contentType", "parentField", "clientId" })` doesn't work either.

Our use case is that all controller methods always require the same specific set of request headers and path variables in the request. So we don't wanna duplicate it in the request bean of every method. Instead, we would like to have a parent class holding this common requirements.

On top of the controller module we also have another module, where we are getting Kafka events and converting them to requests that will be passed to the controller. So having the common fields in a parent class will also help reduce a lot of duplicated code in this particular module.

### Environment Information

- **Micronaut Version:** 2.2.0
- **JDK Version:** 11

**Comment by jameskleeh** [comment]
I can't reproduce this. Please upload an app with steps to reproduce

**Comment by jameskleeh** [comment]
See https://github.com/jameskleeh/test4776 for my sample app

**Comment by mcanalesmayo** [comment]
@jameskleeh sorry for not providing a sample app
I've just forked your repo and added `@AllArgsConstructor` to the child class. Then the issue happens and all the super class fields become null. You can reproduce here: https://github.com/mcanalesmayo/test4776
Lombok doesn't add the super class fields to the all args constructor in the child, so I guess this could be related to that.

**Comment by jameskleeh** [comment]
@mcanalesmayo If a constructor exists it is used to construct the object and no further binding occurs. Either add all arguments to the constructor or use the default constructor.

**Comment by jameskleeh** [comment]
@mcanalesmayo If you'd like you can create a new issue (preferably straight Java) that demonstrates this and we can likely improve the behavior.
