### ISSUE TITLE
Mapping optional URI variable not works properly

### ISSUE THREAD

**Issue by marciomunhoz** [micronaut-projects/micronaut-core#4777]
I'm trying use an optional URI variable according to docs but not works. 

### Steps to Reproduce

1. clone repository https://github.com/marciomunhoz/demo.git
2. `gradle run`
3. GET http://localhost:8080/test/mytest/value (HTTP/1.1 200 OK)
4. GET http://localhost:8080/test/mytest (HTTP/1.1 404 Not Found)

### Expected Behaviour

Return "HTTP / 1.1 200 OK" in both test cases

### Actual Behaviour

Return "HTTP/1.1 404 Not Found" on request to "http://localhost:8080/test/mytest"

### Environment Information

- **Operating System**: Ubuntu 20.10
- **Micronaut Version:** 2.2.2
- **JDK Version:** OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)

### Example Application

https://github.com/marciomunhoz/demo.git

**Comment by jeffscottbrown** [comment]
I think your URI mapping is working as designed and you are getting a 404 because the method returns null when `val` is not provided, and that causes a 404.

https://github.com/marciomunhoz/demo/blob/fb69431c777e131729c08ff6c1cb096f5b4c07bf/src/main/java/com/example/TestController.java#L13

**Comment by jameskleeh** [comment]
@jeffbrown Thanks for looking into it
