### ISSUE TITLE
Class which implements ApplicationEventListener<ServerStartupEvent> on Messenging-driven application are not working

### ISSUE THREAD

**Issue by ghost** [micronaut-projects/micronaut-core#4790]
Trying to perform application logic on start up, but seems not to work with messengin-driven application. I am using Micronaut 2.2.3.

**Approach 1**

```
@Singleton
public class startup implements ApplicationEventListener<ServerStartupEvent> {
    @Override
    public void onApplicationEvent(ServerStartupEvent event) {
        System.out.println("Started");
    }
}
```

**Approach 2**

```
@Singleton
public class ExampleListener {
    @EventListener
    public void onApplicationEvent(ServerStartupEvent event) {
        System.out.println("Test");
    }
}
```

Sample Repo - https://github.com/anandjaisy/startupMicronaut

**Comment by graemerocher** [comment]
`ServerStartupEvent` requires a server that exposes a port which in the case of a message driven app doesn't apply. Use `StartupEvent` instead.
