### ISSUE TITLE
add support ordinal for enums in UriMatchTemplate

### ISSUE THREAD

**Issue by TorosyanV** [micronaut-projects/micronaut-core#4799]
The current implementation of UriMatchTemplate expands values using toString() method, but for enums maybe better to add some marker to use ORDINAL or STRING.

### Task List

- [x] Steps to reproduce provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Expected Behaviour
when I have enum
```
public enum Gender {
  MALE, FEMALE
}
```
and  doing request with query param
```
 @Get(value = "/endpoint{?gender}")
  void get(@PathVariable Gender gender);
```
requested url is **/endpoint?gender=FEMALE** 
where is no way to force  use ordinal for enum (_/endpoint?gender=1 ) 

### Actual Behaviour

where is no way to force  use ordinal for enum (_/endpoint?gender=FEMALE_ ) 

### Environment Information

- **Operating System**: MacOS 11.1
- **Micronaut Version:** 2.2
- **JDK Version:** 11.0.9

**Comment by jameskleeh** [comment]
Are you saying that `/endpoint?gender=FEMALE` is not the URL and you want it to be? If so, what is the URL?

**Comment by TorosyanV** [comment]
sorry, I need url like this (/endpoint?gender=1 )

**Comment by jameskleeh** [comment]
You can register a `TypeConverter`  that converts a `Gender` to a `String` and it will be used to do the conversion

**Comment by TorosyanV** [comment]
But how can  TypeConverter work if in UriTemplate class method  
`public String expand(Map<String, Object> parameters, boolean previousHasContent, boolean anyPreviousHasOperator)`
uses only **toString**

   ```
map.forEach((key, some) -> {
                            String ks = key.toString();
                            Iterable<?> values = (some instanceof Iterable) ? (Iterable) some : Collections.singletonList(some);
                            for (Object value: values) {
                                if (value == null) {
                                    continue;
                                }
                                String vs = value.toString(); //*** TypeConverter will not work here 
                                String ek = encode ? encode(ks, isQuery) : escape(ks);
                                String ev = encode ? encode(vs, isQuery) : escape(vs);
                                if (modifierChar == EXPAND_MODIFIER) {
                                    String finalValue = ek + '=' + ev;
                                    joiner.add(finalValue);
                                } else {
                                    joiner.add(ek);
                                    joiner.add(ev);
                                }
                            }
                        });
                        result = joiner.toString();
```

**Comment by graemerocher** [comment]
I think this would need a client argument binder no @jameskleeh ?

**Comment by jameskleeh** [comment]
The path variable one is being used
