### ISSUE TITLE
Lombok constructor annotations missing

### ISSUE THREAD

**Issue by chaoyangnz** [micronaut-projects/micronaut-core#4811]
I'd like to inject a property from application.properties into a bean with constructor, like 

```
@Singleton
class A {
    public A(@Value("${a.b}" configProp, OtherBean bean) {
        // ...
    }
}
```

Normally, this is supposed by Spring. and we can generate constructor using Lombok and get lean code.

Hopefully, that can be supported or I miss something

**Comment by sdhimmar006** [comment]
@chaoyangnz This is possible. Write this:


@Singleton
Class A {

private String temp;

public A(@Value("${a.b}")String temp, OtherBean bean)
{
this.temp=temp;
// ..
}

void printThis() {
System.out.println(this.name);
}

}

**Comment by chaoyangnz** [comment]
> @chaoyangnz This is possible. Write this:
> 
> @singleton
> Class A {
> 
> private String temp;
> 
> public A(@value("${a.b}")String temp, OtherBean bean)
> {
> this.temp=temp;
> // ..
> }
> 
> void printThis() {
> System.out.println(this.name);
> }
> 
> }

oh, really? I tried lots of times, it didn't work. Let me isolate it with a repo.

**Comment by chaoyangnz** [comment]
OK. found the cause. that is caused by Lombok and Micronaut annotation processing order. Even finally Lombok generates exactly the same constructor as you show, but it is not captured by Micronaut.

**Comment by sdhimmar006** [comment]
@chaoyangnz Make sure that enable annotation processing in your IDE. And add lombok to annotation processor path after the micronaut by default paths

**Comment by chaoyangnz** [comment]
@sdhimmar006 see my repo: https://github.com/chaoyangnz/demo

**Comment by dstepanov** [comment]
@chaoyangnz Lombok doesn't propagate all field annotations to constructor parameters.
You need to create `lombok.config` and add `lombok.copyableAnnotations += io.micronaut.context.annotation.Value`.

**Comment by chaoyangnz** [comment]
> @chaoyangnz Lombok doesn't propagate all field annotations to constructor parameters.
> You need to create `lombok.config` and add `lombok.copyableAnnotations += io.micronaut.context.annotation.Value`.

I did. See my repo: https://github.com/chaoyangnz/demo

I decompile the generated class, the annotation is over there. The issue is annotation processor order.

**Comment by dstepanov** [comment]
@chaoyangnz I see, you need to use the latest version of Lombok.

**Comment by jameskleeh** [comment]
@chaoyangnz You would have to file an issue with Lombok. The Lombok processor is getting executed before Micronaut's

**Comment by dstepanov** [comment]
@jameskleeh This should work the only problem is the old version of Lombok, the issue is similar to https://github.com/micronaut-projects/micronaut-core/issues/1566

**Comment by jameskleeh** [comment]
@dstepanov Are you saying you've tested the example with the newer Lombok and it works?

**Comment by dstepanov** [comment]
Yes, I'm pretty sure it works, I did fix the problem in Lombok and I'm using it in some projects.

**Comment by chaoyangnz** [comment]
Thanks all. I upgraded Lombok to the latest version (1.18.12). It works.

Now close this.
