### ISSUE TITLE
@PostConstruct not called from beans created with @EachBean

### ISSUE THREAD

**Issue by 22dasi1bwi** [micronaut-projects/micronaut-core#4817]
### Task List

- [x] Steps to reproduce provided
- [] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Checkout https://github.com/22dasi1bwi/issue-report-micronaut-eachbean .
2. Let the tests run or have a look at the output when the application is starting up.

### Expected Behaviour

When creating beans with `@EachBean` I would expect that all hooks attached to the bean's definition are registered and executed, e.g. `@PostConstruct`. Although the example application is just about `@PostConstruct` I'm pretty sure it's the same for `@PreDestroy` (and others) as well.

### Actual Behaviour

When a bean is created with `@EachBean` for example the `@PostConstruct` of the created bean is never executed.

### Environment Information

- **Operating System**: Arch Linux
- **Micronaut Version:** 2.2.3
- **JDK Version:** 11.0.5

### Example Application

- https://github.com/22dasi1bwi/issue-report-micronaut-eachbean

**Comment by jameskleeh** [comment]
@22dasi1bwi In order for this to work the `@EachBean` annotation needs to be on the `MyConstructedBean` class. We don't analyze classes returned from factories without additional annotations on the factory method, like `@Bean(preDestroy = ...)`

**Comment by 22dasi1bwi** [comment]
@jameskleeh Thanks for the clarification! I think that's nothing mentioned on the documentation. Do you think it's a good idea to improve it?

**Comment by jeffscottbrown** [comment]
@22dasi1bwi 

> I think that's nothing mentioned on the documentation. Do you think it's a good idea to improve it?

The User Guide does mention the following:

> For factory beans, the preDestroy value in the Bean annotation can be used to tell Micronaut which method to invoke.

That is accompanied with a code snippet:

```
import io.micronaut.context.annotation.Bean;
import io.micronaut.context.annotation.Factory;

import javax.inject.Singleton;

@Factory
public class ConnectionFactory {

    @Bean(preDestroy = "stop") 
    @Singleton
    public Connection connection() {
        return new Connection();
    }
}
```
Those docs are currently at https://github.com/micronaut-projects/micronaut-core/blob/fc074aacfaceef42774ac3d6a56865103c8fd930/src/main/docs/guide/ioc/lifecycle.adoc.  

Please feel free to expand on that and submit a pull request to the docs.  Thanks for all of your feedback!

**Comment by 22dasi1bwi** [comment]
Thanks @jeffbrown, I'll have a look.
