### ISSUE TITLE
ChannelPipelineCustomizer not invoked for DefaultClient when using declarative clients

### ISSUE THREAD

**Issue by jaecktec** [micronaut-projects/micronaut-core#4829]
### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. create client ChannelPipelineCustomizer
2. create declarative client with `@Client('client-name')` annotation 
3. adjust ClientChannel

### Expected Behaviour

`BeanCreatedEventListener<ChannelPipelineCustomizer>` gets invoked for DefaultHttpClient

### Actual Behaviour

does not get invoked

### Environment Information

- **Operating System**: macosx 11.1
- **Micronaut Version:** 2.2.3
- **JDK Version:** openjdk 11.0.9.1 2020-11-04

### Example Application

https://github.com/jaecktec/micronaut-channel-customizer-bug

**Comment by jaecktec** [comment]
I think the issue here is that these clients store their DefaultHttpClient instance inside a client-registry and are not exposing them as beans. 

One option to work around this is to expose default http-clients as a bean (the registry tries to get the client from the bean context.

**Comment by jaecktec** [comment]
In case someone drops by, I want to get Logbook running with declarative clients, this is the workaround I'm using for now:

```
import io.micronaut.context.annotation.EachBean
import io.micronaut.context.annotation.Factory
import io.micronaut.http.client.HttpClientConfiguration
import io.micronaut.http.client.LoadBalancer
import io.micronaut.http.client.ServiceHttpClientConfiguration
import io.micronaut.http.client.netty.DefaultHttpClient

@Factory
class ClientFactory {

    @EachBean(ServiceHttpClientConfiguration::class)
    fun buildDefaultHttpClient(config: ServiceHttpClientConfiguration): DefaultHttpClient {
        return DefaultHttpClient(null as LoadBalancer?, config as HttpClientConfiguration)
    }
}

```

**Comment by BrianEstrada** [comment]
Having this issue as well

**Comment by jaecktec** [comment]
I think this bug was introduced here: https://github.com/micronaut-projects/micronaut-core/commit/2827a91271d6d3702aaad3c6994483d30b683a07

**Comment by BrianEstrada** [comment]
Any update on this issue?
