### ISSUE TITLE
Nested ConfigurationProperties class is not initialized in 2.3.0

### ISSUE THREAD

**Issue by jpragma** [micronaut-projects/micronaut-core#4853]
### Steps to Reproduce

1. Create static class inside some other class
2. Annotated it with @ ConfigurationProperties
3. Inject this configuration bean into some other bean

### Expected Behaviour
ConfigurationProperties bean should be initialized

### Actual Behaviour
All properties inside this bean are null

### Previous version Behaviour
Same example works fine in Micronaut 2.2.3

### Environment Information
- **Micronaut Version:** 2.3.0
- **JDK Version:**  11

### Example Application
https://github.com/jpragma/mntests/tree/master/nested-config-problem
- Run ConfigPropTest -> nestedConfigIsInitialized fails
-  Open gradle.properties and update micronautVersion=2.2.3
-  Re-run the test -> now it passes

**Comment by flobaader** [comment]
I have encountered problems with configuration properties in 2.3.0 even without nesting.
In my case, the properties were not overwritten by the environment variables but simply kept their default values. Should I open a separate issue for that?

**Comment by jameskleeh** [comment]
I don't think this is one of the intended use cases. Currently `@ConfigurationProperties` is only designed to be an inner class of other classes with `@ConfigurationProperties`. Can you explain the use case?

**Comment by jameskleeh** [comment]
@flobaader I would first ask the question in Gitter. Could be behaving as expected
