### ISSUE TITLE
Trivial Micronaut Gradle project and VS Code debug attempt

### ISSUE THREAD

**Issue by raducrisan1** [micronaut-projects/micronaut-core#4855]
I have created a simple gradle micronaut project and I've added a trivial controller:
``` java
@Controller("/health")
public class HealthCheck {
    
    @Get()
    public HttpResponse<String> index() {        
        return HttpResponse.ok("success");
    }  
}
```
From VS Code I start debugging the project (F5 shortcut, using default launch.json file). VS Code started the debug mode but if I try to hit this controller from curl I get

{"message":"Page Not Found","_links":{"self":{"href":"/health","templated":false}}}
This does not happen if i start the project with gradle run. The curl command returns success

I suspect there is an issue with handling the annotation processor. If I run the same thing from IntelliJ Idea, it works just fine.

- [ X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ X] Example that reproduces the problem uploaded to Github
- [ X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a micronaut project: `mn create-app test`
2. From VSCode, add a simple class, name it for instance `HealthCheck.java` with the following content:

```  java
  package test;
  
  import io.micronaut.http.HttpResponse;
  import io.micronaut.http.annotation.Controller;
  import io.micronaut.http.annotation.Get;
  
  @Controller("/health")
  public class HealthCheck {
      
      @Get()
      public HttpResponse<String> index() {        
          return HttpResponse.ok("success");
      }  
  } 
```

3. run `gradle run` and use `curl http://localhost:8080/health` to validate it returns `success`
4.  stop the `gradle run` process and start debug from VSCode, in my case I only pressed pressed `F5`
5. run again `curl http://localhost:8080/health`

The latest curl command returns:

##### Current Result
`{"message":"Page Not Found","_links":{"self":{"href":"/health","templated":false}}}`

##### Expected Result
`success`

### Environment Information
- Operating System: Ubuntu 20.04
- JDK version: openjdk version "15.0.2" 2021-01-19
      OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
      OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
- Visual Studio Code version: 1.52.1
- Java extension version: Java Extension Pack v0.12.1
- Java Debugger extension version: v0.30.0
- Micronaut Version: 2.3.0

### Example Application

- provided above

**Comment by graemerocher** [comment]
For the Java Extension pack you have to run `gradle eclipse` before opening the project to create the correct annotation processor config.

It also uses the Eclipse compiler behind the scenes which is not as good when it comes to annotation processors. I personally recommend the new GraalVM extension pack with the NetBeans backend which provides a better experience for Micronaut https://marketplace.visualstudio.com/items?itemName=oracle-labs-graalvm.graalvm-pack

**Comment by raducrisan1** [comment]
Hello @graemerocher,

Thank you for the instructions you provided regarding NetBeans and Oracle GraalVM extensions. I confirm that the debugging works by installing the extensions and by following the the Oracle GraalVM extension documentation.
