### ISSUE TITLE
Unable to read environment variables injected by k8s in Micronaut

### ISSUE THREAD

**Issue by tandel-pratik** [micronaut-projects/micronaut-core#4861]
After upgrading to 2.3.0 from 2.2.1 we observed the issue described in the steps to repro section

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Define an environment variable `AUTH_JSON` in k8s
2. Write the following Kotlin code to try to read it

```
 @field:Value("\${auth.json}") protected var keystoreJson: String? = ""
```

Note: when trying to reproduce this locally it doesn't work so it seems to be an issue with the way micronaut reads k8s config.

### Expected Behaviour

* Variables should be read and populated into the `keystoreJson` field.

### Actual Behaviour

* Variables aren't read (in 2.3.0 and are read in previous versions).

### Environment Information

- **Operating System**: TODO
- **Micronaut Version:** TODO
- **JDK Version:** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by jameskleeh** [comment]
@pratik-brex Can you confirm the value starts with `tcp://` ?

**Comment by tandel-pratik** [comment]
The value doesn't start with `tcp://`. It's a valid JSON input

**Comment by flobaader** [comment]
I can also confirm that this regression bug affects all types of env variables. We had a problem with strings, URLs, etc. 
In a Docker Compose file, the problem does not occur.

**Comment by bjor-joh** [comment]
I have also experienced this behaviour. 
I believe it can be reproduced locally by setting `MICRONAUT_ENVIRONMENTS=k8s` and then try setting `MICRONAUT_SERVER_PORT=80`. Micronaut will still start on port 8080, ignoring the latter env variable.

**Comment by alvarosanchez** [comment]
This is likely caused by https://github.com/micronaut-projects/micronaut-core/pull/4822

Can someone please enable the [`/env` endpoint](https://docs.micronaut.io/latest/guide/index.html#environmentEndpoint) and tell its contents?

**Comment by alvarosanchez** [comment]
Ok, I think I found the issue. PR coming
