### ISSUE TITLE
Non-deterministic generation of `META-INF/services/io.micronaut.inject.BeanDefinitionReference`

### ISSUE THREAD

**Issue by cazlo** [micronaut-projects/micronaut-core#4870]
### Steps to Reproduce

Please see the README in the linked example application for more details.

1. Create simple example Micronaut project using multiple controllers, services, a factory, and some AOP.
2. Generate jar (`./gradlew clean build`)
3. Record generated jar
4. Generate jar again
5. Compare the contents of `META-INF/services/io.micronaut.inject.BeanDefinitionReference` between the 2 test runs
6. If they are the same goto step 2. (This issue is non-deterministic in nature and may require a few test runs to reproduce)
7. Observe difference in order of content.

Note: I tried removing the factory from the linked example and then could not reproduce the issue.

### Expected Behaviour

The JAR generation should be deterministic.  If there are no changes to the project, the exact same jar should be generated.  Let's ignore timestamps since gradle jar generation can easily be configured to have deterministic file timestamps.

### Actual Behaviour

Sometimes the JAR has differences in the order of contents within the `META-INF/services/io.micronaut.inject.BeanDefinitionReference` file.
This means sometimes the exact same input code state will produce 2 different JARs.

### Environment Information

- **Operating System**:  Same behavior observed in OSX and Ubuntu Linux
- **Micronaut Version:** 2.3.0
- **JDK Version:** Same behavior observed in 8 and 11

### Example Application

https://github.com/cazlo/micronaut-annotation-metadata-issue-reproduction

### Impact of issue
The determinism of the JAR generation is important for taking advantage of docker layer caching to avoid re-building the native image when the code hasn't changed.

Imagine a pipeline like this:
1. Build docker image with jdk8 installed
2. Use docker image from step 1 to generate a jar
3. Build docker image with graalvm native-image compilation specific stuff. This takes advantage of layer caching like so:
```
COPY build/libs/some-fat-jar.jar  build/libs/some-fat-jar.jar
RUN /usr/lib/graalvm/bin/native-image --no-server -cp build/libs/some-fat-jar.jar
```
Here if the JAR copy layer does not change, we don't need to re-execute the native-image command, we can just use the cached layer.  Native image generation is really slow in our real world examples, sometimes taking upwards of 6 minutes to complete.  Anything we can do to cache that helps out a bunch.

**Comment by graemerocher** [comment]
Thanks for the report, this does indeed seem like a problem in the data structures that are storing service names
