### ISSUE TITLE
Declarative client duplicates  @QueryValue when using @RequestBean

### ISSUE THREAD

**Issue by TorosyanV** [micronaut-projects/micronaut-core#4874]
Micronuat Http declarative client duplicates QueryValue 

After updating the Micronaut version  from 2.1.3 to 2.3.0
HTTP Client generates requests with duplicate query values. 

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create declarative client using @Client 
2. create @RequestBean with some field annotated with @QueryValue
3. create an endpoint for the client to do GET request using provided RequestBean.

### Expected Behaviour

When have RequestBean

``` java
@Introspected
public class GetFieldsRequest {

  @QueryValue
  private String farmName;

  public String getFarmName() {
    return farmName;
  }

  public void setFarmName(String farmName) {
    this.farmName = farmName;
  }
```

and have Client 

``` java
@Client
public interface SomeClient
{
 
@Get(value = "/fields{?getFieldsRequest*}")
  Flowable<ResourceCollection<Field>> getFields(@RequestBean GetFieldsRequest getFieldsRequest);
}
```
request URL should be  something like  **/fields?farmName=myFarm**

### Actual Behaviour

request URL is  **/fields?farmName=myFarm&farmName=myFarm**

### Environment Information

- **Operating System**: macOS
- **Micronaut Version:** 2.3.0
- **JDK Version:** 11

**Comment by jameskleeh** [comment]
@TorosyanV I don't think `@RequestBean` is supposed to be tied to anything in the URL.

Can you try it with just `@Get(value = "/fields")` ?

**Comment by TorosyanV** [comment]
@jameskleeh  When I'm using @Get(value = "/fields")  request URL is /fields?farmName=myFarm.
It's expected
