### ISSUE TITLE
Using "default" as a property or method name does not work

### ISSUE THREAD

**Issue by dave08** [micronaut-projects/micronaut-core#4887]
Given a Kotlin data class:

```kotlin
@EachProperty(value = "somekey", list = true)
data class ModuleInfo @ConfigurationInject constructor (
    @param:Parameter private val index: Int,

    val name: String,

    @JsonIgnore
    val default: Boolean? = null,

) : Ordered {
    override fun getOrder(): Int = index
}
```
`default` will always be null, even when provided in `application.yaml`. The issue @jameskleeh explained this is, is that in java default is not a valid name, and Kapt generates a funny name for the property like: p2-772401952. He said that it could be improved when moving to a native kotlin compiler plugin.

### Environment Information

- **Operating System**: Linux Mint 18.3
- **Micronaut Version:** 2.3.1
- **JDK Version:** 1.8

**Comment by jameskleeh** [comment]
When Kapt generates the stub, it assigns a random name to the property because default is not valid in Java. This should be able to be addressed with a native Kotlin compiler plugin

**Comment by jameskleeh** [comment]
Note the following also does not work due to the method name being `default`:

```
@Factory
class SchedulerProvider {

    @Singleton
    fun default(): Scheduler {
        return Schedulers.computation()
    }
}
```
