### ISSUE TITLE
Singleton bean created twice when taken from ApplicationContext.getBeansOfType() by interface

### ISSUE THREAD

**Issue by l0co** [micronaut-projects/micronaut-core#4891]
In `2.2.3`.

I have the following classes:

```java
public abstract class BaseService<T> implements IBeanValidator<T>  {

	// validates entities marked with @BeanValidation
	public boolean isValid(@Nonnull T entity,
						   @Nonnull AnnotationValue<BeanValidation> annotationMetadata,
						   @Nonnull ConstraintValidatorContext context) {
		return true;
	}

}
```

```kotlin
@TransactionalAdvice @Singleton
class BankService(...): BaseService<Bank> {} // not direct inheritance, but for simplicity ....
```

The `BankSevice` bean is created properly by the container and as I can see in `DefaultBeanContext.getBeanInternal()` its key is `io.luna.service.main.finance.bank.service.BankService`.

However, this code created another instance of this bean (and all beans derived from the `BaseService`):

```java
@Singleton
public class BeanValidatorDelegate implements ConstraintValidator<BeanValidation, Object> {

	@Inject
	protected ApplicationContext applicationContext;

	@SuppressWarnings("unchecked")
	@Override
	public boolean isValid(@Nullable Object value, @Nonnull AnnotationValue<BeanValidation> annotationMetadata,
						   @Nonnull ConstraintValidatorContext context) {
		if (value==null)
			return true;

		return applicationContext
			.getBeansOfType(IBeanValidator.class, Qualifiers.byTypeArgumentsClosest(value.getClass()))
			.stream()
			.map(bean -> bean.isValid(value, annotationMetadata, context))
			.reduce((b1, b2) -> b1 && b2)
			.orElse(true);
	}

}
```

In `DefaultBeanContext.getBeansOfTypeInternal()` I can see the `existing` bean is evaluated to `null` because of different key used here which is `<Bank> io.luna.feature.core.validation.IBeanValidator`.

I understand the underlying logic, however this breaks the rule of `@Singleton` bean in the app.

**Comment by jameskleeh** [comment]
@l0co Are you saying that `getBeansOfType` returned 2 beans?

**Comment by l0co** [comment]
No, just the instance of `BankService` which is returned from `getBeansOfType()` is a different instance of this service, than this injected into all beans.
