### ISSUE TITLE
Validation has dependency on http

### ISSUE THREAD

**Issue by tomas-langer** [micronaut-projects/micronaut-core#4893]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Add dependency on  `micronaut-validation`
2. Do not have dependency on `micronaut-http`
3. Display dependency tree (in maven using `mvn dependency:tree`

### Expected Behaviour

You should only see dependencies on core and validation

### Actual Behaviour

You see a dependency on http

### Environment Information

- **Micronaut Version:** 2.3.1
- **JDK Version:** 11.0.9

**Comment by graemerocher** [comment]
http is only needed for the compile time features so I consider this a bug

**Comment by jameskleeh** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/f81eceaba3ac8c550e56288779c686d6f50ea286
