### ISSUE TITLE
Jaeger tracing does not work with blocking controller methods

### ISSUE THREAD

**Issue by lgathy** [micronaut-projects/micronaut-core#4913]
### Steps to Reproduce

1. Enable Jaeger tracing
2. Create a blocking controller method annotated with `@ExecuteOn(TaskExecutors.IO)`
3. Try to access or manipulate the active span inside the controller method

### Expected Behaviour

I should be able to access the active span inside the controller method via `tracer.activeSpan()`.

### Actual Behaviour

Calling `tracer.activeSpan()` returns `null`.

### Environment Information

- **Operating System**: masOc 11.2
- **Micronaut Version:** 2.3.1 (I believe this bug is present since 2.0.0)
- **JDK Version:** OpenJDK 11.0.10

### Example Application

I have modified the `HttpTracingSpec` by adding `@ExecuteOn(TaskExecutors.IO)` to all non-reactive controller method and the test now fails, see my modifications [here](https://github.com/Tesco/micronaut-core/commit/11aa55d41e613b295c1b9cb2e5c5858ec9a3f197)

I have a way to fix this behaviour, but I am not sure if it is the right way to fix it. I will publish my solution in a PR.

**Comment by ilopmar** [comment]
This is possibly a duplicate of #4383

**Comment by lgathy** [comment]
Sorry, I missed to check the existing open issues. Feel free to close this issue, I can submit my PR for the original issue.
@ilopmar Are there any additional test cases for that? I am testing my fix only with the modified `HttpTracingSpec` atm.

**Comment by lgathy** [comment]
Submitted my fix in the following PR #4915

**Comment by lgathy** [comment]
Closing this now as the PR has been merged.

**Comment by avinash338** [comment]
Hi @graemerocher , 

Currently, we are on the 2.5.9 version and facing the same issue. Is there any way we can handle the above scenario? 

Thank you.
