### ISSUE TITLE
Enhancement for command line apps

### ISSUE THREAD

**Issue by jexp** [micronaut-projects/micronaut-core#496]
* Generate GraalVM native binaries
* Generate fully executable jars that run from the shell like in spring-boot
* Build a single jar instead putting all jars into the `lib` folder, should also make the shell-scripts easier.

**Comment by jameskleeh** [comment]
@jexp Can you expand on this? Perhaps given examples of what you think should work

**Comment by jameskleeh** [comment]
Closing this due to lack of feedback
