### ISSUE TITLE
Reduce Number of Generated Classes

### ISSUE THREAD

**Issue by RyanHoldren** [micronaut-projects/micronaut-core#4963]
I'm trying to reduce the memory consumption of our software to get it to fit on smaller instances in AWS. Our project has about 8,000. About half of them are generated by Micronaut, mostly similar to `$ExampleDefinition.class`, `$ExampleDefinitionClass.class` and `$ExampleDefinition$$execX`. All these classes end up consuming a lot of metaspace. Is there anything in the pipeline to reduce the number of classes generated?

### Environment Information

- **Operating System**: Amazon Linux 2
- **Micronaut Version:** 2.2.1
- **JDK Version:** OpenJDK 15.0.2

**Comment by jameskleeh** [comment]
There are no plans to reduce the number of generated classes at this time

**Comment by RyanHoldren** [comment]
Thanks for the quick reply, @jameskleeh. I'll explore other avenues :)
