### ISSUE TITLE
Field Data type is changed when serialzing and object which contains similar field names

### ISSUE THREAD

**Issue by nsnikhil** [micronaut-projects/micronaut-core#4971]
### Steps to Reproduce

1. Create a new controller as given below
```
import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.reactivex.Maybe

data class Response(
    val isBorrowing: Boolean,
    val borrowing: Borrowing
)

data class Borrowing(
    val lines: List<Line>? = null
)

data class Line(
    val lineID: String
)

@Controller("/dummy")
class DummyController {

    @Get
    fun dummy(): Maybe<Response> {
        return Maybe.just(
            Response(
                isBorrowing = true,
                borrowing = Borrowing(
                    lines = listOf(
                        Line(lineID = "some-id")
                    )
                )
            )
        )
    }

}
```

2. Write the test for the controller as below
```
import io.micronaut.http.HttpRequest
import io.micronaut.http.client.HttpClient
import io.micronaut.http.client.annotation.Client
import io.micronaut.test.extensions.junit5.annotation.MicronautTest
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.Test
import javax.inject.Inject

@Tag("unit")
@MicronautTest
internal class DummyControllerTest {

    @Inject
    @field:Client("/")
    lateinit var httpClient: HttpClient

    @Test
    fun `Test dummy`() {
        val request = HttpRequest.GET<Any>("/dummy")
        val body = httpClient.toBlocking().retrieve(request)
        assertNotNull(body)
        println(body)
        assertEquals(1, 2)
    }

}
```

3. Upon running the test you get the following output:
{"isBorrowing":{"lines":[{"lineID":"some-id"}]}}

### Expected Behaviour
The output should be something like this:
`{"isBorrowing":true,"borrowing":{"lines":[{"lineID":"some-id"}]}}`

### Actual Behaviour
The type of `isBorrowing` has changed to the type of `Borrowing`, and `Borrowing` is missing from the response.

If you change the name of the `borrowing` field in `Response` class to `resp`, then the output is:
`{"isBorrowing":true,"resp":{"lines":[{"lineID":"some-id"}]}}`
which is correct, indicating that some issue with serializer, due to smililar name.

### Environment Information One
- **Operating System**: MacOs 11.2.1
- **Micronaut Version:** 2.3.2
- **JDK Version:** java 15 2020-09-15

### Environment Information Two
- **Operating System**: RHEL 7.6
- **Micronaut Version:** 2.2.3
- **JDK Version:** open jdk 11.0.7 2020-04-14

**Comment by jameskleeh** [comment]
This is a question for Jackson. I assume having `isBorrowing` and `borrowing` confuses Jackson into believing there is a single property instead of two, given its common to have an `isBorrowing()` method for a boolean property called `borrowing`. Micronaut uses Jackson for JSON serialization so any options forward will be some annotations or configuration of that.
