### ISSUE TITLE
Bad maven central metadata after 2.3.3 release

### ISSUE THREAD

**Issue by stickycode** [micronaut-projects/micronaut-core#4978]
### Task List

- [y] Steps to reproduce provided
- [n/a] Stacktrace (if present) provided
- [n/a] Example that reproduces the problem uploaded to Github
- [y] Full description of the issue provided (see below)

### Steps to Reproduce

1. From a clean maven cache (CICD)
2. build a project that depends on micronaut-inject or micronaut-validation (probably more, only tested those at this time)
3. the build will fail not finding the library

### Expected Behaviour

Maven should resolve the 2.3.2 version and download it

### Actual Behaviour

Maven cannot resolve the 2.3.2 versions

```
[ERROR] Failed to execute goal on project xxx: Could not resolve dependencies for project xxx:jar:3.999-SNAPSHOT: Failed to collect dependencies at xxx:jar:4.1 -> xxx:jar:7.2 -> io.micronaut:micronaut-validation:jar:[2.3.2]: No versions available for io.micronaut:micronaut-validation:jar:[2.3.2] within specified range -> [Help 1]
[ERROR] 
```
we lock down all external libraries with fixed versions (e.g. [2.3.2]) to ensure we have an auditable and deterministic stack for regulatory purposes

see https://repo1.maven.org/maven2/io/micronaut/micronaut-inject/maven-metadata.xml obviously missing 2.3.2, 

this means the entity that did the 2.3.3 did not have up to date metadata and the process did not ensure it was updated

### Environment Information

- **Operating System**: All
- **Micronaut Version:** 2.3.2
- **JDK Version:** All

### Example Application

- Only if you really need it but I don't think its necessary

This issue has been raised with Sonatype for Maven Central

https://issues.sonatype.org/browse/MVNCENTRAL-6578

**Comment by stickycode** [comment]
micronaut-management also has bad metadata

**Comment by stickycode** [comment]
actually it looks like every 2.3.3 library

**Comment by jameskleeh** [comment]
Sonatype is rebuilding the metadata https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-64942

**Comment by jameskleeh** [comment]
This has been resolved

**Comment by stickycode** [comment]
Well the symptom is closed but have you put in place controls to stop it
happening again?

**Comment by jameskleeh** [comment]
@stickycode There is nothing we can do. We don't control the metadata and nothing we did caused the issue

**Comment by stickycode** [comment]
Huh. How do you get stuff into central? I control the metadata for the
stuff i put into Central.

**Comment by jameskleeh** [comment]
We use the nexus publish gradle plugin
