### ISSUE TITLE
Support fully executable applications for Unix systems

### ISSUE THREAD

**Issue by x80486** [micronaut-projects/micronaut-core#4981]
Spring Boot have a nice feature that allow to [make fully executable applications](https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html#deployment-install) for Unix systems.

I understand this is a little bit backwards, but not everyone is using containers these days 🙄 ...so I wonder if it's possible to have a built-in feature like this in Micronaut.

**Comment by jameskleeh** [comment]
Given you can create a native executable with GraalVM, I don't think a feature like this adds much value

**Comment by x80486** [comment]
GraalVM executables are different from, for instance, what Spring Boot creates. They create a wrapper script and bundle it into the JAR/WAR, so you can execute that file without the need for `java -jar`. Notice it's not only that, because there is this entire support for `systemd` services, environment variables, etc.

Also, I'm haven't done anything with GraalVM yet, but I've read time and time again that there are corner cases and stuff like that with some libraries, among the successful ones. It looks to me that one would be successful on the GraalVM business depending on the scope of the application.
