### ISSUE TITLE
AliasFor from custom TypeElementVisitor is not visible to other visitors

### ISSUE THREAD

**Issue by asodja** [micronaut-projects/micronaut-core#4983]
When mapping annotations with custom TypeElementVisitor `AliasFor` annotations are not seen to other Visitors. 

For example [JaxRsTypeElementVisitor](https://github.com/micronaut-projects/micronaut-jaxrs/blob/master/jaxrs-processor/src/main/java/io/micronaut/jaxrs/processor/JaxRsTypeElementVisitor.java) maps `@javax.ws.rs.Path` to `@Controller`. `@Controller` has  AliasFor(annotation = UriMapping.class, member = "value"). But this UriMapping is then not visible to OpenAPI Visitor. Example project is provided in https://github.com/asodja/micronaut-type-visitor-issue.

In example we have TestController.java:
- with `@Path("/user")` on class
- with `@Path("/{userId}")` on method

After running `./gradlew compileJava` Swagger yaml has path as `/{userId}` instead of `/user/{userId}`.

This can be fixed in OpenAPI with:
https://github.com/asodja/micronaut-openapi/commit/3d69c5669e91d5fbab9f419c08f0949c963c2bb9.
From this fix it seems that `@Controller` is correctly applied by JaxRsTypeElementVisitor but UriMapping is not accesible. So this looks to me like it is micronaut-core issue.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. git clone git@github.com:asodja/micronaut-type-visitor-issue.git
2. ./gradlew compileJava
3. cat ./build/classes/java/main/META-INF/swagger/demo-0.0.yml  

### Expected Behaviour

Swagger yaml contains path `/user/{userId}`

### Actual Behaviour

Swagger yaml contains path `/{userId}`

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.3.3
- **JDK Version:** 1.8

### Example Application
https://github.com/asodja/micronaut-type-visitor-issue

**Comment by altro3** [comment]
@graemerocher Fixed here: https://github.com/micronaut-projects/micronaut-openapi/pull/1445
