### ISSUE TITLE
Documentation: It would be nice to point out the "feature", not just the "modules"

### ISSUE THREAD

**Issue by jexp** [micronaut-projects/micronaut-core#499]
In most places in the docs, only the "module" to add to gradle/maven is mentioned, but not the `feature` that you would enable via `mn`. 

As they don't always correspond 1:1 in naming, it would be nice to also mention the appropriate feature flag.

e.g.

> To enable tracing you should add the tracing module to your build.gradle or pom.xml file:
> 
> build.gradle
> ```
> compile "io.micronaut:tracing"
> ```

**Comment by jameskleeh** [comment]
@jexp A PR would be welcome for this

**Comment by ZacharyKlein** [comment]
@jexp this commit has documented most of these - feel free to let me know if I've missed any. https://github.com/micronaut-projects/micronaut-core/commit/c0ca41d92f45d27c09f79fe21bbcc3a6bc8e462e
