### ISSUE TITLE
Native image fails with Oracle driver

### ISSUE THREAD

**Issue by tomasrobertsson** [micronaut-projects/micronaut-core#4994]
Building a simple REST-API as test project to verify key components in a bigger project that is to be deployed in AWS-lambda.  When I add dependency to Oracle driver the native image build fails. 

**To reproduce**
Have two branches, **hibernateJPA** and **jdbc**. In the latter I use Micronaut JDBC, in the first HibernateJPA
In both branches, if I add the oracle driver the native image build crash at the same time in the process.

- Check out the code from GIT-below, branch hibernate-jpa. Re-add the dependency to Oracle in build.  
- Build native image via docker or locally
OR
- Check out code from branch jdbc
- Build native image via docker or locally

### Error
Thrown in setup-step in native image
`Error: Incompatible change of initialization policy for java.sql.DriverManager: trying to change BUILD_TIME from feature io.micronaut.core.graal.AutomaticFeatureUtils.lambda$initializeAtBuildTime$0 to RUN_TIME from feature io.micronaut.core.graal.AutomaticFeatureUtils.lambda$initializeAtRunTime$1
com.oracle.svm.core.util.UserError$UserException: Incompatible change of initialization policy for java.sql.DriverManager: trying to change BUILD_TIME from feature io.micronaut.core.graal.AutomaticFeatureUtils.lambda$initializeAtBuildTime$0 to RUN_TIME from feature io.micronaut.core.graal.AutomaticFeatureUtils.lambda$initializeAtRunTime$1`

### Environment Information
Windows 10
OpenJDK Runtime Environment Corretto-11.0.5.10.1 (build 11.0.5+10-LTS)
GraalVM 21.0.0.2

Docker 
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
GraalVM 21.0.0.2

Micronaut 2.3.3
Micronaut data 2.2.4
ojdbc10, 19.10.0.0

### Example Application
Code in this repo have working and none working commits. 
https://github.com/tomasrobertsson/micronaut-native-hibernate-oracle/tree/main

**Comment by graemerocher** [comment]
Can you try 2.3.1 of Micronaut whilst I investigate?

**Comment by tomasrobertsson** [comment]
Oops, an error above (fixed now). Micronaut 2.3.3 is the version I use. Have also tried 2.3.1 and 2.3.0

**Comment by graemerocher** [comment]
Ok we will take a look. Seems specific for usage with lambdas as works in a normal app

**Comment by tomasrobertsson** [comment]
Thanks and yes. 
I have a successful push to lambda with H2 database on the native-image branch.  
I have successful build of native image with oracle support and netty.
Oracle and lambda support together fails at native image.

**Comment by graemerocher** [comment]
It works if you comment out the `h2` driver. Unfortunately the 2 drivers need different native image configurations that are incompatible with each other so I don't see us supporting both simultaneously

**Comment by tomasrobertsson** [comment]
Thanks, feel stupid, That I should seen by myself. Not a bug.

**Comment by graemerocher** [comment]
Well the error message is not hugely helpful
