### ISSUE TITLE
Usage of URI double encode % characters

### ISSUE THREAD

**Issue by jlafourc** [micronaut-projects/micronaut-core#503]
Hi,

I'm running into an issue here :

https://github.com/micronaut-projects/micronaut-core/blob/65c717886174ed29b556791751a2281891b88014/http-client/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java#L604

When we have encoded query params that have %, then the URI constructor converts % into %25. The immediate consequence is a query failure.

Exemple : 

Param value : {"service":["test"]}
Encoded with URLEncoder : %7B%22service%22%3A%5B%22test%22%5D%7D
After URI constructor : %257B%2522service%2522%253A%255B%2522test%2522%255D%257D 

I found some solutions here :

https://blog.stackhunter.com/2014/03/31/encode-special-characters-java-net-uri/

But I think we'd like to avoid Reflection.

We have also this kind of stuff : 

https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/utils/URIBuilder.html

But it adds a lot of dependencies.

Any suggestions that I could implement and submit as PR ? 

Thanks

Julien

**Comment by jameskleeh** [comment]
@jlafourc Can you include a more concrete example? Are you saying the values are pre-encoded when they are passed to the client?

**Comment by jlafourc** [comment]
Whoo great ! Very fast !

Thanks a lot !

Julien

**Comment by jlafourc** [comment]
Hello,

Tested it against my project this morning. Works like a charm !

Th

Julien
