### ISSUE TITLE
Duplicate Controller method invocation when using HttpServerFilter

### ISSUE THREAD

**Issue by mmindenhall** [micronaut-projects/micronaut-core#504]
This issue happens with java and kotlin (albeit with slightly different output).  I didn't try to reproduce with groovy, but assume the behavior would be similar.  When using an HttpServerFilter, we are seeing an endpoint in our controller invoked a second time.

### Steps to Reproduce

1. Clone [my fork of micronaut-examples](https://github.com/mmindenhall/micronaut-examples)
1. Check out duplicate-invocation branch
1. Run the hello-world-kotlin or hello-world-java project
1. Hit the /hello/{name} endpoint
1. Observe the output

### Detailed Description

This is the output of the **first endpoint invocation** (kotlin):

```
nioEventLoopGroup-1-2 [HelloFilter] doFilter (1) before proceed
nioEventLoopGroup-1-2 [HelloFilter] doFilter (2) after proceed
nioEventLoopGroup-1-2 [HelloResponseFilterSubscriber] onSubscribe requested 1
nioEventLoopGroup-1-2 [HelloController] hello endpoint invoked
nioEventLoopGroup-1-2 [HelloResponseFilterSubscriber] onNext invoked with response: 200 Ok
nioEventLoopGroup-1-2 [HelloResponseFilterSubscriber] onComplete
nioEventLoopGroup-1-2 [HelloFilter] doFilter (3) after subscribe

pool-1-thread-1 [HelloController] hello endpoint invoked

nioEventLoopGroup-1-2 [HelloFilter] doFilter (1) before proceed
nioEventLoopGroup-1-2 [HelloFilter] doFilter (2) after proceed
nioEventLoopGroup-1-2 [HelloResponseFilterSubscriber] onSubscribe requested 1
nioEventLoopGroup-1-2 [HelloResponseFilterSubscriber] onNext invoked with response: 404 Not Found
nioEventLoopGroup-1-2 [HelloResponseFilterSubscriber] onComplete
nioEventLoopGroup-1-2 [HelloFilter] doFilter (3) after subscribe
```

I've added some newlines to make it easier to follow.  The first 7 lines of output are expected.  Then on the next line, the endpoint is invoked for a second time (but on a pool thread rather than nioEventLoopGroup thread).  Then, over the last 6 lines, the filter is also invoked a second time (with the publisher emitting a 404 response).

This is the output on **each subsequent endpoint invocation** (kotlin):

```
nioEventLoopGroup-1-3 [HelloFilter] doFilter (1) before proceed
nioEventLoopGroup-1-3 [HelloFilter] doFilter (2) after proceed
nioEventLoopGroup-1-3 [HelloResponseFilterSubscriber] onSubscribe requested 1
nioEventLoopGroup-1-3 [HelloController] hello endpoint invoked
nioEventLoopGroup-1-3 [HelloResponseFilterSubscriber] onNext invoked with response: 200 Ok
nioEventLoopGroup-1-3 [HelloResponseFilterSubscriber] onComplete
nioEventLoopGroup-1-3 [HelloFilter] doFilter (3) after subscribe
pool-1-thread-2 [HelloController] hello endpoint invoked
```

Now the filter/subscriber are invoked just once, but the endpoint method is invoked twice (once in event loop, once in pool thread).

The behavior is slightly different with Java.  All invocations (first and all subsequent) produce the following:

```
nioEventLoopGroup-1-2 [HelloFilter] doFilter(1) before proceed
nioEventLoopGroup-1-2 [HelloFilter] doFilter(2) after proceed
nioEventLoopGroup-1-2 [HelloResponseFilterSubscriber] onSubscribe requested 1
nioEventLoopGroup-1-2 [HelloController] hello endpoint invoked
nioEventLoopGroup-1-2 [HelloResponseFilterSubscriber] onNext invoked with response: 200 Ok
nioEventLoopGroup-1-2 [HelloResponseFilterSubscriber] onComplete
nioEventLoopGroup-1-2 [HelloFilter] doFilter(3) after subscribe
nioEventLoopGroup-1-2 [HelloController] hello endpoint invoked
```

So with Java, the endpoint is invoked twice, but always on the event loop thread (presumably due to the `Single<String>` return type). 

- **Operating System**: MacOS
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:** 1.8.0_152

**Comment by jameskleeh** [comment]
@mmindenhall What is the use case for subscribing to `chain.proceed` ? The subscriber you created doesn't do anything beyond logging.

**Comment by mmindenhall** [comment]
@jameskleeh, the subscriber I created is just to demonstrate the issue.

The actual use case is to inject some data into the SLF4J MDC for each request, then clear the MDC after the request has been processed.  This is done as follows within the `doFilter` method:

1. Read data from request headers, set fields on MDC.
1. Call `chain.proceed`.  
1. Subscribe to the returned response publisher.
1. Request one response via the subscription.
1. Within the `onNext`, `onComplete`, and `onError` subscriber callbacks, clear the MDC.

I think this is the correct way to implement a pre-request _and_ post-request filter.

**Comment by mmindenhall** [comment]
@jameskleeh, yes, the pre vs. post distinction is just a matter of how you use the filter.  Anything done on the request before calling `chain.proceed` can be considered "pre-request", and anything done with the MutableHttpResponse emitted from the publisher can be considered "post-request".

I like your suggestion to wrap the publisher via `Flowable`.  However, this could not possibly work without the `Flowable` implementation issuing a `subscription.request` call.  From the [reactive streams spec](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.2/README.md#2-subscriber-code):

> A Subscriber MUST signal demand via Subscription.request(long n) to receive onNext signals.

**Comment by graemerocher** [comment]
This is not a bug, you should not subscribe to the published returned from `proceed`. See https://github.com/micronaut-projects/micronaut-core/blob/master/tracing/src/main/java/io/micronaut/tracing/instrument/http/OpenTracingServerFilter.java for an example of decorating the returned publisher
