### ISSUE TITLE
AnnotationMetadataHierarchy.getAnnotationValuesByType calls get*Declared*AnnotationValuesByType on hierarchy

### ISSUE THREAD

**Issue by ggerbaud** [micronaut-projects/micronaut-core#5050]
### Task List

- [x] Steps to reproduce provided
- [x] Full description of the issue provided (see below)

#### Direct to the point
A simple JUnit Test
```java
@Test
void should_return_same_annotations() {
    AnnotationValue<ApiResponse> av = AnnotationValue.builder(ApiResponse.class).member("description", "aa").build();
    AnnotationMetadata child = new DefaultAnnotationMetadata(null, null, null, Map.of(ApiResponse.class.getName(), av.getValues()), null);
    AnnotationMetadata parent = new AnnotationMetadataHierarchy(child);

    List<AnnotationValue<ApiResponse>> fromParent = parent.getAnnotationValuesByType(ApiResponse.class);
    List<AnnotationValue<ApiResponse>> fromChild = child.getAnnotationValuesByType(ApiResponse.class);
    assertEquals(1, fromChild.size()); // OK
    assertEquals(1, fromParent.size()); // KO -> 0
}
```

#### More realistic use-case
```java
public interface ExampleController {
  @Post("path")
  @Status(HttpStatus.CREATED)
  @ApiResponse(responseCode = "201", description = "Created, all good")
  @ApiResponse(responseCode = "400", description = "You did something wrong")
  void addSomething(@Body final MyBody myBody);
}
@Controller("/example")
public class ExampleControllerImpl implements ExampleController {

    /**
     * open api doc...
     */
    @Override
    public void addSomething(final MyBody myBody) {
        // do something
    }
```
Then when openapi processor will run on this example, it will not find the ApiResponse on the interface due to this issue. If I put those annotations on the implementing Controller then it works. But I want to separate the documented contract and the implementation.

### Expected Behaviour

getAnnotationValuesByType in AnnotationMetadataHierarchy should call getAnnotationValuesByType on each element in the hierarchy.

### Actual Behaviour

getAnnotationValuesByType in AnnotationMetadataHierarchy actually calls get**Declared**AnnotationValuesByType on each element in the hierarchy.

https://github.com/micronaut-projects/micronaut-core/blob/2.3.x/inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataHierarchy.java#L342

**Comment by graemerocher** [comment]
This is fixed in the 2.4.x branch I believe

**Comment by ggerbaud** [comment]
You're right : https://github.com/micronaut-projects/micronaut-core/blob/2.4.x/inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataHierarchy.java#L350
I didn't know this branch. 

Is a 2.4 release coming soon or is it fixeable in a 2.3.x ?

**Comment by graemerocher** [comment]
Micronaut 2.4 will hopefully be released on Monday
