### ISSUE TITLE
serviceId attribute is not set on the request when using the Low-Level HTTP client

### ISSUE THREAD

**Issue by pfyod** [micronaut-projects/micronaut-core#5059]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Inject a low level client client with a service id
2. Try to read this service id in a client filter

This functionality is required to be able to use an `OutgoingHttpRequestProcessor` within a filter. As an example, this pattern is used in [micronaut-security](https://github.com/micronaut-projects/micronaut-security/blob/master/security-oauth2/src/main/java/io/micronaut/security/oauth2/client/clientcredentials/propagation/ClientCredentialsHttpClientFilter.java). 

Here's simple way to reproduce this (also uploaded to github [here](https://github.com/pfyod/micronaut-serviceid-problem)):

`application.yaml`:
```yaml
micronaut:
  application:
    name: demo
  http:
    services:
      declarative:
        url: http://example.com
      low-level:
        url: http://example.com
```

Test:
```java
@MicronautTest
class ServiceIdTest {

    @Filter(Filter.MATCH_ALL_PATTERN)
    public static class ServiceIdCheckingFilter implements HttpClientFilter {
        @Override
        public Publisher<? extends HttpResponse<?>> doFilter(MutableHttpRequest<?> request, ClientFilterChain chain) {
            Assertions.assertTrue(request.getAttribute(HttpAttributes.SERVICE_ID.toString()).isPresent());
            return chain.proceed(request);
        }
    }

    @Client(id = "declarative")
    public interface DeclarativeClient {
        @Get("/")
        String get();
    }

    @Inject
    private DeclarativeClient declarativeClient;

    @Inject
    @Client(id = "low-level")
    private RxHttpClient rxHttpClient;

    @Test
    public void testDeclarativeClient() {
        declarativeClient.get();
    }

    @Test
    public void testRxHttpClient() {
        rxHttpClient.retrieve("/").firstElement().blockingGet();
    }
}
```

### Expected Behaviour

Service id should be present when both, declarative and low level clients are used.

### Actual Behaviour

Only declarative client sets client id attribute on the request → `testRxHttpClient` fails.

### Environment Information

- **Operating System**: N/A
- **Micronaut Version:** 2.3.4
- **JDK Version:** 11

### Example Application

https://github.com/pfyod/micronaut-serviceid-problem

Run `ServiceIdTest`

**Comment by thaDude** [comment]
Unfortunate, since ClientCredentialsHttpFilter relies on service ID to automatically add Bearer token to outgoing requests of clients matching a service ID regex, [documentation](https://micronaut-projects.github.io/micronaut-security/2.5.0/guide/index.html#clientecredentialshttpclient).

I'd appreciate hints to work around this issue.

Thanks

/David

**Comment by thaDude** [comment]
Really ugly workaround, set the attribute on requests manually.

```
HttpRequest#setAttribute(HttpAttributes.SERVICE_ID.toString(), <your-service-id>)
```

**Comment by yawkat** [comment]
not easy to fix, HttpClients aren't aware which client id was used to construct them

**Comment by mplanchant** [comment]
@yawkat any progress on this?

**Comment by thomasmillercf** [comment]
Well this is sad this is still open :(

**Comment by yawkat** [comment]
easy change now, with the recent http client changes :)
