### ISSUE TITLE
Compilation error when including hibernate-validator for Kotlin projects

### ISSUE THREAD

**Issue by johanhaleby** [micronaut-projects/micronaut-core#506]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a new micronaut project: 
  
	```bash
	$ mn create-app test-app --features=kotlin --build maven
	```
2. Follow the [getting started guide](http://guides.micronaut.io/creating-your-first-micronaut-app-kotlin/guide/index.html) and implement a simple controller.
3. Add the following dependency in order to use validation:

	```xml
	<dependency>
        <groupId>io.micronaut.configuration</groupId>
        <artifactId>hibernate-validator</artifactId>
    </dependency>
    ```
4. Annotate the controller class with @Validated in accordance with the [docs](https://docs.micronaut.io/snapshot/guide/index.html#datavalidation).
5. Do a `$ ./mvnw clean install`

### Expected Behaviour

Should work

### Actual Behaviour

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.623 s
[INFO] Finished at: 2018-08-18T08:59:19+02:00
[INFO] Final Memory: 43M/450M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.2.60:kapt (kapt) on project test-app: Compilation failure
[ERROR] /Users/johan/test-app/target/kaptStubs/compile/test/app/HelloController.java:8: error: Cannot apply AOP advice to final class. Class must be made non-final to support proxying: test.app.HelloController
[ERROR] public final class HelloController {
[ERROR] ^
[ERROR] -> [Help 1]
```

### Environment Information

- **Operating System**: MacOSX
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:** 1.8

### Other notes

It works if I manually set the `HomeController` and the `fun` to be `open`. But I can't get it working even when trying to apply the [kotlin-maven-allopen](https://kotlinlang.org/docs/reference/compiler-plugins.html) plugin which I know that Spring is using by default. Maybe I'm doing something wrong when configuring it although it says that it's applied:

```
[INFO] --- kotlin-maven-plugin:1.2.60:kapt (kapt) @ test-app ---
[INFO] Applied plugin: 'all-open'
``` 

If we can get it working maybe this plugin should be applied by default for both Maven and Gradle?

**Comment by jameskleeh** [comment]
@johanhaleby Did you specify the list of annotations you would like for the plugin to apply to?

```
    <configuration>
        <compilerPlugins>
            <plugin>all-open</plugin>
        </compilerPlugins>

        <pluginOptions>
            <!-- Each annotation is placed on its own line -->
            <option>all-open:annotation=com.my.Annotation</option>
            <option>all-open:annotation=com.their.AnotherAnnotation</option>
        </pluginOptions>
    </configuration>
```

**Comment by johanhaleby** [comment]
@jameskleeh I'm embarrassed to say that it works when I point to the `io.micronaut.validation.Validated` annotation. But maybe it should be configured by default?
