### ISSUE TITLE
Broken Link In User Guide

### ISSUE THREAD

**Issue by jeffscottbrown** [micronaut-projects/micronaut-core#5065]
The `rs:Publisher[]` reference at https://github.com/micronaut-projects/micronaut-core/blob/a6ef31ecb1f3687bd4f5ef56c1148d12943016cc/src/main/docs/guide/httpServer/sse.adoc is generating a link to https://docs.oracle.com/javase/8/docs/api/org/reactivestreams/Publisher.html which does not exist.

**Comment by jameskleeh** [comment]
I think this is a bug or issue with our docs plugin. It seems the `rs:` extension is used everywhere, but it has different behavior in some places.

**Comment by jeffscottbrown** [comment]
@jameskleeh Do you know if https://github.com/micronaut-projects/micronaut-docs/pull/27 resolves this issue?

**Comment by jameskleeh** [comment]
@jeffbrown I don't know for certain but it makes sense that it would

**Comment by graemerocher** [comment]
This should be fixed by https://github.com/micronaut-projects/micronaut-core/commit/e76576779c852616696cbd4029786b2ffabf4727

Maybe you want to verify the snapshot docs

**Comment by jeffscottbrown** [comment]
The link in the docs appears to be valid now.
