### ISSUE TITLE
Jackson fails to deserialize data classes with generic types

### ISSUE THREAD

**Issue by dayman** [micronaut-projects/micronaut-core#5081]
After updating from 2.3.3 to 2.3.4 I'm getting jackson deserialization error when using generic types in constructor.
Use Kotlin 1.4.31

### Steps to Reproduce

```
@Introspected
data class V2ResultList<T>(
        @JsonProperty("result") val result: List<T>
)
```

T is of different simple types (also data classes)

This is example of what T may be
```
@Introspected
data class Auth(
        @JsonProperty("access_token") val accessToken: String,
        @JsonProperty("refresh_token") val refreshToken: String
)
```

### Expected Behaviour

Should deserialize to object

### Actual Behaviour

Exception during deserialization
```
java.lang.IllegalStateException: No delegate constructor for [simple type, class x.x.x.ResultList]
arbitrage_1  |   at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator._createUsingDelegate(StdValueInstantiator.java:626)
arbitrage_1  |   at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDelegate(StdValueInstantiator.java:306)
```

### Environment Information

- **Operating System**: mac os or linux
- **Micronaut Version:** 2.3.4
- **JDK Version:** 14.0.2 or 15.0.2

**Comment by graemerocher** [comment]
Your example has no generic types?

**Comment by dayman** [comment]
> Your example has no generic types?

sorry, formatting ate it maybe :) fixed

**Comment by jameskleeh** [comment]
@dayman Can you provide a complete example?

**Comment by jameskleeh** [comment]
I added a test and cannot reproduce. Please let me know if you can provide an example or tell me what to change in the test to make it fail
