### ISSUE TITLE
Make default @Order value to be 0 an in Ordered interface

### ISSUE THREAD

**Issue by Zhambul** [micronaut-projects/micronaut-core#5084]
In order to make consistent behaviour of the ordering of beans, make OrderUtil.getOrder(AnnotationMetadata, Object) return 0 if no annotation or interface defined and not `Ordered.LOWEST_PRECEDENCE` as in default method of Ordered interface.

It is also somewhat inconvenient to add a bean to be the last in the collection of types(`Ordered.LOWEST_PRECEDENCE`), because you would need to explicitly set @Order(0) to other beans of the same type. If you don't add the @Order(0), it's also undeterministic which bean would be last, the one which explicitly set @Order(Ordered.LOWEST_PRECEDENCE) or the one without it

**Comment by sdelamo** [comment]
Ordered interface getOrder() method returns 0 in its default implementation. Thus, I think this change makes sense.
