### ISSUE TITLE
Micronaut HttpClient throws random Read Timeouts when doing a Http request

### ISSUE THREAD

**Issue by rikkert09** [micronaut-projects/micronaut-core#5093]
Hello,

I use the Micronaut HttpClient to do some Http requests to a REST API. Most of the times I get the expected response but sometimes the HttpClient throws a `ReadTimeoutException`. I know its a problem in the HttpClient because when I do a request to something else the problem still exists and the problem is gone when I use another http client (okHttp3 for example) 

When I look at the logs of the server of the REST API, it looks like that it receives the request when the micronaut httpClient throws the ReadTimeoutException. Also increasing the read timeout property doesn't solve this.

In the code below i've written some code to reproduce the problem:

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create new micronaut application
2. Create a controller with the code below

```java
@Controller
public class Reproduce {

    private final HttpClient httpClient;

    public Reproduce(HttpClient httpClient) {
        this.httpClient = httpClient;
    }

    public void test() {
        for (int i = 0; i < 25; i++) {
            var httpRequest =
                    HttpRequest.GET(
                            "https://baconipsum.com/api/?type=meat-and-filler");
            var result = httpClient.toBlocking().exchange(httpRequest, String.class);
            System.out.println(result.body());
        }
    }

    @Post("testCall")
    public void lorem() {
        test();
    }
}
```
3. Do a HTTP Post request to: "/testCall"

### Expected Behaviour

It should call `https://baconipsum.com/api/?type=meat-and-filler` 25 times and print the response in the console

### Actual Behaviour
At some point it throws a `ReadTimeoutException`. When this happens differs every time.

```
14:34:37.521 [default-nioEventLoopGroup-1-7] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: Read Timeout
io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
	at io.micronaut.http.client.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:26)
	at io.micronaut.http.client.netty.DefaultHttpClient.lambda$null$36(DefaultHttpClient.java:1159)
	at io.reactivex.internal.operators.flowable.FlowableOnErrorNext$OnErrorNextSubscriber.onError(FlowableOnErrorNext.java:103)
	at io.micronaut.reactive.rxjava2.RxInstrumentedSubscriber.onError(RxInstrumentedSubscriber.java:66)
	at io.reactivex.internal.operators.flowable.FlowableTimeoutTimed$TimeoutSubscriber.onTimeout(FlowableTimeoutTimed.java:139)
	at io.reactivex.internal.operators.flowable.FlowableTimeoutTimed$TimeoutTask.run(FlowableTimeoutTimed.java:170)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
```

### Environment Information

- **Operating System**: Ubuntu 20 and also on Windows 10
- **Micronaut Version:** 2.3.2
- **JDK Version:** 11

My build.gradle for the `Reproduce` controller project looks like this:

```plugins {
    id("com.github.johnrengelman.shadow") version "6.1.0"
    id("io.micronaut.application") version "1.4.2"
}

version = "0.1"
group = "demo"

repositories {
    mavenCentral()
    jcenter()
}

micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("demo.*")
    }
}

dependencies {
    implementation 'com.sun.xml.ws:jaxws-rt:2.3.3'
    implementation 'com.sun.org.apache.xml.internal:resolver:20050927'
    implementation("io.micronaut:micronaut-validation")
    implementation("io.micronaut:micronaut-runtime")
    implementation("io.micronaut:micronaut-http-client")
    runtimeOnly("ch.qos.logback:logback-classic")
}


application {
    mainClass.set("demo.Application")
}

java {
    sourceCompatibility = JavaVersion.toVersion("11")
    targetCompatibility = JavaVersion.toVersion("11")
}
```

**Comment by graemerocher** [comment]
The reason for this is you are blocking the Netty event loop, if you wish to run blocking operations on the event loop then either:

a) Add `@ExecuteOn(TaskExecutors.IO)` to the controller

or 

b) Set the thread selection strategy to I/O which will make it global. See https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.http.server.HttpServerConfiguration

**Comment by rikkert09** [comment]
> The reason for this is you are blocking the Netty event loop, if you wish to run blocking operations on the event loop then either:
> 
> a) Add `@ExecuteOn(TaskExecutors.IO)` to the controller
> 
> or
> 
> b) Set the thread selection strategy to I/O which will make it global. See https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.http.server.HttpServerConfiguration

Oh ofcourse, you saved my day :smile: thanks
