### ISSUE TITLE
URI mappings are inconsistent for relative, absolute and client discovery paths

### ISSUE THREAD

**Issue by AntonPanikov** [micronaut-projects/micronaut-core#5097]
Documentation for the URI paths used in `@Client` annotations, like `@Get`, does not clearly explain how relative and absolute paths are concatenated with the client base URL. For example for `@Client` from the official doc:
> `@Client`("/hello")
>  The `@Client` annotation is used with a value that is a relative path to the current server

While it does not explain how URI will be constructed and concatenated in case of both `@Client` and `@Get` annotation has paths, the things are going wild once `@Client` is URI with context path and even going worse once it starts using client discovery. I used 2 simple URLs with and without context path, both with and without ending slash. And used two clients with URL as constant and through discovery client, with two simple `@Get` paths: "/absolute" and "relative". You can see the full example below in groovy. Here is the summary of my observation:

URL constant used | `@Client(<URL>)` and `@Get('/absolute')` and `@Get('relative')` |   `@Client(<id with same URL from client discovery>)` and `@Get('/absolute')` and `@Get('relative')`
--- | --- | ---
http://localhost:8080                         |  http://localhost:8080/absolute                      |  http://localhost:8080/absolute
 same url `@Get('relative')`                |  http://localhost:8080relative                         | http://localhost:8080relative
http://localhost:8080/                        |  http://localhost:8080/absolute                     | http://localhost:8080/absolute
 same url `@Get('relative')`                |  http://localhost:8080/relative                        | http://localhost:8080/relative
http://localhost:8080/context/path   | http://localhost:8080/context/path/absolute | http://localhost:8080/absolute
 same url `@Get('relative')`                | http://localhost:8080/context/path/relative    | http://localhost:8080/context/relative
http://localhost:8080/context/path/  | http://localhost:8080/context/path/absolute | http://localhost:8080/absolute
 same url `@Get('relative')`                | http://localhost:8080/context/path/relative  | http://localhost:8080/context/path/relative

There are multiply issues here:
* Application context path is ignored by `/absolute` if `@Client` is using a client discovery while working for a string constant variant
e.g. _localhost:8080/absolute_ while should be _localhost:8080 **/context/path/** absolute_
* `relative` is silently rewriting the last part of the context path for a client discovery variant while working for a string constant
e.g. _localhost:8080/context/relative_ while should be _localhost:8080/context **/path/** relative_
* `relative` is not appending '/' in case of no context path and no ending '/' while working for a string constant even without '/' at the end with context path
e.g _localhost:8080relative_ while should be _localhost:8080 **/** relative_

### Steps to Reproduce

1. Define a client base interface with relative and absolute path mappings, like this:
```groovy
interface TestClient {
    @Get('relative')
    void relative()
    
    @Get('/absolute')
    void absolute()
}
```
2. Define a simple discovery client, like this:
```groovy
abstract class TestDiscoveryClient implements DiscoveryClient {

    abstract String getUrl()
    abstract String getId()

    @Override
    public void close() throws IOException {
        // Nothing to do
    }

    @Override
    String getDescription() {
        id
    }

    @Override
    Publisher<List<ServiceInstance>> getInstances(String serviceId) {
        if (serviceId != id) {
            return Flowable.just([])
        }
        Flowable.just([
            ServiceInstance.of(id, new URL(url))
        ])
    }

    @Override
    Publisher<List<String>> getServiceIds() {
        Flowable.just([id])
    }
}
```
3. Define concrete discovery clients and clients using it, like this:
```groovy
@Singleton
class DiscoveryClient1 extends TestDiscoveryClient {

    @Override
    String getId() {
        'host-port-no-slash'
    }

    @Override
    String getUrl() {
        'http://localhost:8080'
    }
}

@Singleton
class DiscoveryClient2 extends TestDiscoveryClient {
    
    @Override
    String getId() {
        'host-port-with-slash'
    }
    
    @Override
    String getUrl() {
        'http://localhost:8080/'
    }
}

@Singleton
class DiscoveryClient3 extends TestDiscoveryClient {
    
    @Override
    String getId() {
        'context-path-no-slash'
    }
    
    @Override
    String getUrl() {
        'http://localhost:8080/context/path'
    }
}

@Singleton
class DiscoveryClient4 extends TestDiscoveryClient {
    
    @Override
    String getId() {
        'context-path-with-slash'
    }
    
    @Override
    String getUrl() {
        'http://localhost:8080/context/path/'
    }
}
```
```groovy
@Client('host-port-no-slash')
interface TestClient1 extends TestClient {
}
@Client('host-port-with-slash')
interface TestClient2 extends TestClient {
}
@Client('context-path-no-slash')
interface TestClient3 extends TestClient {
}
@Client('context-path-with-slash')
interface TestClient4 extends TestClient {
}
...
```
4. Define the next set of discovery clients and clients for it, summarized in the table, (ending slashes and absence is important):

 id | URL
--- | ---
host-port-no-slash | http://localhost:8080
host-port-with-slash | http://localhost:8080/
context-path-no-slash | http://localhost:8080/context/path
context-path-with-slash | http://localhost:8080/context/path/

5. Define 4 more clients, that directly using the same URL from the table:
```groovy
...
@Client('http://localhost:8080')
interface TestClient5 extends TestClient {
}
@Client('http://localhost:8080/')
interface TestClient6 extends TestClient {
}
@Client('http://localhost:8080/context/path')
interface TestClient7 extends TestClient {
}
@Client('http://localhost:8080/context/path/')
interface TestClient8 extends TestClient {
}
...
```

6. Enable tracing of requests and run both methods on every of 8 clients:
``` groovy
...
    @Inject
    TestClient1 client1
    @Inject
    TestClient2 client2
...
client1.absolute()
client1.relative()
client2.absolute()
client2.relative()
...
```
```yaml
logger:
  levels:
    io.micronaut.http: TRACE
```

### Expected Behaviour

* Ending URL should be consistent for `@Client` using discovery and String URL
* Absolute paths in `@Get` should respect the context path of an application
* Relative paths should not silently rewrite the context path and respect the absence of ending '/'

### Actual Behaviour

Summary table from the begging:
URL constant used | `@Client(<URL>)` and `@Get('/absolute')` and `@Get('relative')` |   `@Client(<id with same URL from client discovery>)` and `@Get('/absolute')` and `@Get('relative')`
--- | --- | ---
http://localhost:8080                         |  http://localhost:8080/absolute                      |  http://localhost:8080/absolute
 same url `@Get('relative')`                |  http://localhost:8080relative                         | http://localhost:8080relative
http://localhost:8080/                        |  http://localhost:8080/absolute                     | http://localhost:8080/absolute
 same url `@Get('relative')`                |  http://localhost:8080/relative                        | http://localhost:8080/relative
http://localhost:8080/context/path   | http://localhost:8080/context/path/absolute | http://localhost:8080/absolute
 same url `@Get('relative')`                | http://localhost:8080/context/path/relative    | http://localhost:8080/context/relative
http://localhost:8080/context/path/  | http://localhost:8080/context/path/absolute | http://localhost:8080/absolute
 same url `@Get('relative')`                | http://localhost:8080/context/path/relative  | http://localhost:8080/context/path/relative

### Environment Information

- **Operating System**: CentOS 7
- **Micronaut Version:** 2.4.0/2.3.2/1.3.6
- **JDK Version:** 11

**Comment by jameskleeh** [comment]
Do you have an example project that encapsulates this code?

**Comment by jameskleeh** [comment]
This usage should not be supported. There is a path member of `@Client` that you can use to store the context path. The same applies to the service configuration. Paths should not be part of the URLs at all. 

```
@Client('http://localhost:8080/context/path')
interface TestClient7 extends TestClient {
}
@Client('http://localhost:8080/context/path/')
interface TestClient8 extends TestClient {
}
```

**Comment by AntonPanikov** [comment]
Pushed the simple example here:
https://github.com/AntonPanikov/URI_test_example

Use run task, I did not create proper test as it is failing and the purpose is to look logs for resulting URLs.

> 
> 
> This usage should not be supported. There is a path member of `@Client` that you can use to store the context path. The same applies to the service configuration. Paths should not be part of the URLs at all.
> 
> ```
> @Client('http://localhost:8080/context/path')
> interface TestClient7 extends TestClient {
> }
> @Client('http://localhost:8080/context/path/')
> interface TestClient8 extends TestClient {
> }
> ```

This is just an example, just to demonstrate that:
`@Client('http://localhost:8080/context/path')` + `@Get('relative')` = `http://localhost:8080/context/path/relative` and is working.

While the same combination coming from discovery client end up in a wrong URL:
`@Client('host-with-context-path-no-slash-id')` + `@Get('/absolute')` = `http://localhost:8080/absolute`

In real code, `@Client()` is taking URL from config variable:
application.yaml:
```yaml
service:
  url: http://localhost:8080/context/path
```
and the client defined like:
```groovy
@Client('${service.url}')
```
> The same applies to the service configuration. Paths should not be part of the URLs at all.

`io.micronaut.discovery.ServiceInstance` does not have separate host and context path fields:
```groovy
ServiceInstance.of(id, new URL('http://localhost:8080/context/path'))
```
So for `ServiceInstance` the context path is a part of the service URL.

**Comment by jameskleeh** [comment]
> In real code, @Client() is taking URL from config variable:
application.yaml:

>service:
>  url: http://localhost:8080/context/path

Right I'm saying that is not the correct way to configure it. It should be

```
service:
    url: http://localhost:8080
    path: /context/path
```

**Comment by jameskleeh** [comment]
Closing due to a lack of feedback
