### ISSUE TITLE
Circuit breaker

### ISSUE THREAD

**Issue by shashanka981** [micronaut-projects/micronaut-core#5107]
Circuit breaker annotation of Micronaut currents attempts retries on the same request. This may be undesirable if the remote service call is non-idompotent.  Because 1st call to remote service is timed out because of server being slow but was eventually succeeded, now the 2nd attempt also tries to perform the same non-idompotent operation leading to unexpected outcome. 

Is there a way to avoid retrying on the same request ?

**Comment by shashanka981** [comment]
Any opinion on this ? Is this a valid requirement to not retry on the same request  ? At least Netflix's Hystrix library doesnt seem to retry on same request ?

I am looking at other alternatives to implement circuit breaker logic using Micronaut inbuilt features. I have see the following project, https://github.com/micronaut-projects/micronaut-netflix 

but annotating with @HystrixCommand in place of circuit-breaker annotation doesn't seem to work . Any other configuration needed to work inaddition to annotating the method with HystrixCommand ?

**Comment by graemerocher** [comment]
Hystrix has been deprecated by Netflix. If you want more flexibility you could try Resilience4j https://resilience4j.readme.io/docs/getting-started-7

**Comment by shashanka981** [comment]
So Micronaut-netflix doesnt work ?? 
Also, can micronaut provide a way to avoid retries on same requests ?
