### ISSUE TITLE
NullPointerException - io.micronaut.http.netty.websocket.AbstractNettyWebSocketHandler

### ISSUE THREAD

**Issue by falcon-europe** [micronaut-projects/micronaut-core#5108]
Hi Micronaut Community,

I am getting **NullPointerException** after setup for GraphQL WebSocket

```
java.lang.NullPointerException
at io.micronaut.http.netty.websocket.AbstractNettyWebSocketHandler.handleUnexpected(AbstractNettyWebSocketHandler.java:528)
...
Exception in thread "default-nioEventLoopGroup-1-3" java.lang.NullPointerException

```
`if (LOG.isErrorEnabled()) {
            LOG.error("Unexpected Exception in WebSocket [" + webSocketBean.getTarget() + "]: " + cause.getMessage(), cause);
        }`
cause is **null**

client side receives: **java.io.IOException: An established connection was aborted by the software in your host machine**

it's appears automatically when access embedded graphiql for the first time after server run, have you ever experienced similar issue?

**Comment by graemerocher** [comment]
Not seen that, but since like a simple fix. PRs welcome of course!
