### ISSUE TITLE
Server sent event are blocking netty event loop even if using TaskExecutors.IO

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-core#5123]
from https://github.com/micronaut-projects/micronaut-core/discussions/5080, on micronaut 2.3.4, 

* create a simple controller sending SSE : 

```java 
    @ExecuteOn(TaskExecutors.IO)
    @Get(uri = "sse", produces = MediaType.TEXT_EVENT_STREAM)
    public Flowable<Event<Execution>> follow() {
        return Flowable
            .<Event<Execution>>create(emitter -> {
                Thread.sleep(1000000000000L);
                
            }, BackpressureStrategy.BUFFER);
    }
```
* Send as many request on this endpoint as your cpu * 2 
* Try to reach any other endpoint from the application, the request will be timeout. 
* change the controller to : 
```java 
    @ExecuteOn(TaskExecutors.IO)
    @Get(uri = "sse", produces = MediaType.TEXT_EVENT_STREAM)
    public Flowable<Event<Execution>> follow() {
        return Flowable
            .<Event<Execution>>create(emitter -> {
                Thread.sleep(1000000000000L);
                
            }, BackpressureStrategy.BUFFER)
            .observeOn(Schedulers.io());
    }
```
* do the same test, and see that the request on other endpoint will not timeout anymore. 

It seems that the `@ExecuteOn(TaskExecutors.IO)` is not properly handle on that case and the Flowable is executed on the netty event loop.

**Comment by graemerocher** [comment]
Relates to https://github.com/micronaut-projects/micronaut-core/issues/5192
