### ISSUE TITLE
2.4 `withValue` is incorrectly generated for Groovy

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#5129]
```
 public Object withValueInternal(Object var1, Object var2) {
        return this.getDeclaringBean().instantiate(new Object[0]);
    }
```

**Comment by graemerocher** [comment]
Are you going to provide a PR or could you provide more info on what the class looks like?

**Comment by dstepanov** [comment]
I haven’t looked into it, the class is a simple entity without constructor defined, there might be a problem because it’s defined inside a spec class.

**Comment by dstepanov** [comment]
https://github.com/micronaut-projects/micronaut-data/pull/952/files#diff-83fe97a847193852ed656cacfb4fbe8e33e4d57419ecad047c6671f791d0f4bf The example, `withValue` is generated incorrectly for entities in spec.
