### ISSUE TITLE
ClientArgumentRequestBinder: Allow changing the URL of a request 

### ISSUE THREAD

**Issue by theHacker** [micronaut-projects/micronaut-core#5131]
This is a feature request.

The manual contains a hint about the limitation of `ClientArgumentRequestBinder`:
```
This is an experimental feature in 2.1 and subject to change!
One limitation of binding is that binders may not manipulate or set the request URI because it can be a combination of many arguments.
```

This issue is about lifting the limitation.

Concrete use-case:
```kt
enum class Flag {
    A, B, C
}

@Client
interface ExternalApi {
    @Get("/some/endpoint")
    fun getFoos(desiredFlag: Flag?): List<Foo>
}

@Singleton
class FlagClientArgumentBinder : TypedClientArgumentRequestBinder<Flag> {

    override fun argumentType(): Argument<Flag> {
        return Argument.of(Flag::class.java)
    }

    override fun bind(
        context: ArgumentConversionContext<Flag>,
        uriContext: ClientRequestUriContext,
        value: Flag,
        request: MutableHttpRequest<*> // INFO: Mutable suggests, I can manipulate the request
    ) {
        val filter = complexLogicUsingFlagToCreateARequestParam(value)

        request.uri {
            // EXPECTED: it.path == "/some/endpoint"
            // ACTUAL: it.path == ""
            it.replaceQueryParam("filter", filter)
        }

        // EXPECTED: Micronaut will issue a request to "/some/endpoint?filter=xxxxxx"
        // ACTUAL: Micronaut will issue a request to "/some/endpoint"
    }
}
```

I quickly looked over the implementation of `HttpClientIntroductionAdvice`.
Problem seems to be, that for the actual request the URI is built from the `uriTemplate`, not the `request` (MN 2.4.0: lines 289-292).
The `uriTemplate` is available to the custom binder, but there the variables are also readonly (`Collections.unmodifiableList()`).

Not sure, how this is achievable. The `ClientArgumentRequestBinder` are applied in a loop for multiple arguments.
Ideas:
- Either provide them with the current/changing URL, giving custom binders the ability to even override previous queryParams.
- Maybe you could provide an interception point just before the request is sent. This could be done after line 325, where even attributes and headers are set on the `request`.

**Comment by jameskleeh** [comment]
`uriContext.getQueryParameters().put("filter", filter)` should do what you want
