### ISSUE TITLE
Cannot mix Scheduled tasks and CLI command in one single project

### ISSUE THREAD

**Issue by klamouri** [micronaut-projects/micronaut-core#514]
Hi,

I'm playing with Micronaut and I wanted to create a service that has
* One REST controller
* One Scheduled task
* One CLI command

I want to have the three in one repo so that they can all leverage the same beans.

However, when I'm executing the CLI command the scheduled task also gets executed. I don't think that should be a default behavior. Ideally, the REST controller and the scheduled task should be able to run at the same time but the CLI command should be running as a standalone, so no Http Server or scheduled tasks should run when executing a CLI.

Let me know what you think about this behavior.

P.-S. Here is a [repository](https://github.com/klamouri/micronaut-cli-schedule-rest) that shows what I'm trying to achieve. After running `./gradlew build` I run 

~~~~
java -cp build/libs/test-cli-and-schedule-0.1-all.jar test.cli.and.schedule.MyCliAppCommand -v
~~~~
The output is

~~~~
Hi!
18:28:44.010 [pool-1-thread-2] INFO  test.cli.and.schedule.ScheduledTask - Scheduled task
~~~~

When I expect it to be:

~~~~
Hi!
~~~~

P.-S. 2: I also I think that this behavior might be an issue because if two scheduled tasks overlap the CLI won't return

**Comment by jameskleeh** [comment]
Do you intend for this command to be a process that will continue to run until stopped?

**Comment by klamouri** [comment]
No I intend it to run whatever is specified in the run method and then exit. I do not want the scheduled tasks to run either.

Here is the use case:

I want to embed my micronaut application as an agent on my instances. The webapp part is providing an endpoint for the healthcheck of the instance, at the same time (meaning in the same process) I’m using the scheduled task to clean up parts of my instance. Finally I want this application to run a standalone cli to help the instance to be configured at the boot of the instance (so I don’t want to do any scheduled task at this time, just bootstrap my instance).

Let me know if you need me to clarify anything.

**Comment by graemerocher** [comment]
There is an easy way to resolve this problem. You can simply add:

```
@Requires(notEnv = Environment.CLI)
```

To the scheduled tasks in question. Maybe this should be done by default, but right now there is no environment specific disabling of beans in the core context

**Comment by klamouri** [comment]
Hi,
I confirm that adding `@Requires(notEnv = Environment.CLI)` to the class defining the scheduled class fix the issue.
Thank you!
