### ISSUE TITLE
Name of PathVariable not matched

### ISSUE THREAD

**Issue by mdeso** [micronaut-projects/micronaut-core#5151]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

After I changed a POST endpoint with a request object in a service interface to simpler GET endpoints with `PathVariable` annotations I got a compile error although the declaration was correct according to the documentation:

```java
@Get(uri = "/task/get/{id}")
Maybe<Task> getTask(@PathVariable String id);
```
This caused the following error:
>error: The route declares a uri variable named [id], but no corresponding method argument is present

I had to change the code to explicitly name the variable to make it compile.

```java
@Get(uri = "/task/get/{id}")
Maybe<Task> getTask(@PathVariable(name = "id") String id);
```

I have been using `PathVariable` parameters in other APIs and so far didn't encounter this problem. So I'm not sure what exactly causes this error. The respective service interface defines 6 methods of which three are GET requests with `PathVariable` annotations with the name id (but renaming them to distinct names didn't help). The methods themselves are inherited from another interface (and re-defined with the request annotations) but I use that for other APIs too. 

### Steps to Reproduce

1. Define GET endpoint with PathVariable annotation on parameter that has the name of a path variable
2. compile

### Expected Behaviour

Code should compile

### Actual Behaviour

Code fails with
>error: The route declares a uri variable named [name], but no corresponding method argument is present

### Environment Information

- **Operating System**: Windows, Linux
- **Micronaut Version:** 2.3.4, 2.4.1
- **JDK Version:** 8

**Comment by jameskleeh** [comment]
I cant reproduce. Please upload a sample application that reproduces the issue

**Comment by mdeso** [comment]
It's difficult as this is part of a larger project with several (Micronaut-based) libraries. And as usual I'm on a tight schedule. If I find the time I'll see if I can extract the problem into an example. But I thought it would at least be helpful to mention the workaround here. Or is there a better place for that?

**Comment by graemerocher** [comment]
Most likely reason is a missing `-parameters` flag to javac

**Comment by mdeso** [comment]
The library project where the problem occurred has the block
```groovy
tasks.withType(JavaCompile){
    options.compilerArgs.add('-parameters')
}
```
But I have recently converted the Gradle build to use the Micronaut Library plugin. Could that have an effect?

**Comment by mdeso** [comment]
I have tried with the previous build files, but the problem still occurs. So it's not caused by the plugin.

**Comment by goeh** [comment]
I saw this warning too in one or two projects after I upgraded to Micronaut 2.4.1. It's in declarative client code that I haven't touched in months. And the client seems to work fine. I noticed the warning after first compile, but on second compile it did not. I will investigate further to see if I could find any clues. I  will check the -parameters settings, both in build.gradle and in IntelliJ IDEA compiler settings.

**Comment by mdeso** [comment]
In my case it was not only a warning but an error that caused the Gradle build to fail, so I had to fix it with the mentioned workaround.

**Comment by goeh** [comment]
Is `-parameters` needed when I use the Micronaut Gradle plugin? The default generated build.gradle does **not** include that compiler config. My project with this issue does not have `-parameters`, but do use the `io.micronaut.application` plugin.

**Comment by graemerocher** [comment]
It does in versions earlier than 1.4.0 see https://github.com/micronaut-projects/micronaut-gradle-plugin/commit/b3817bb0a491e4e3ed31ec64a76e5ffb4ce2748c

**Comment by goeh** [comment]
Thanks! Great to know that we don't have to add the -parameters when using the Micronaut Gradle plugin.

I can't reproduce this anymore in my 2.4.1 project. But I'm confused. I just checked the commit history and if I revert the workaround (adding name to @PathVariable), it still compiles ok. Very strange. But I will not investigate more. My project compiles without warnings or errors.

**Comment by goeh** [comment]
Sorry, this will be my last comment. I found the problem! My `io.micronaut.application` plugin was at version 1.2.0 at the time of issues. It's now at version 1.4.2 and that's why it works ok now.
