### ISSUE TITLE
Default value not being evaluated when it is a property key

### ISSUE THREAD

**Issue by thiagolocatelli** [micronaut-projects/micronaut-core#516]
Current behavior: the expression provided to my Http Client contains an environment variable and a default property key. When the environment variable is available, it works as expected, but when the env var is not there, the DefaultPropertyPlaceholderResolver does not resolve my property, it handles it as a constat.

```
12:51:48.692 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: No available services for ID: spring-cloud.client.uri
io.micronaut.discovery.exceptions.NoAvailableServiceException: No available services for ID: spring-cloud.client.uri
```

```java
@SuppressWarnings("unused")
@Client(value = "${SPRING_CLOUD_CONFIG_URI:spring-cloud.client.uri}", configuration = SpringCloudConfiguration.class)
@Requires(beans = SpringCloudConfiguration.class)
public abstract class AbstractSpringCloudConfigClient implements SpringCloudConfigClient {
}
```

The expected behavior for my http client is:
1) Use the SPRING_CLOUD_CONFIG_URI
2) Use the property spring-cloud.client.uri from bootstrap.yml
3) Use http://localhost:8888 when none of the above are available (to be fixed with PR 469)

DefaultPropertyPlaceholderResolver.resolveExpression() should be called for the default, since, instead of being a constant, it could also be a property key.

**Comment by jameskleeh** [comment]
@thiagolocatelli We can't support this because we don't have enough information

If the `spring-cloud.client.uri` is not found in the context, should it throw an exception, or just return the static string? Which option is right depends on whether or not you expect the last value to be a configuration key.
