### ISSUE TITLE
Error in documentation generation for 6.29.1 Configuring Server Thread Pools 

### ISSUE THREAD

**Issue by gregorydickson** [micronaut-projects/micronaut-core#5166]
There is an error in the latests docs under 6.29.1 Configuring Server Thread Pools. https://docs.micronaut.io/latest/guide/index.html#threadPools

Unresolved directive in <stdin> - include::/home/runner/work/micronaut-core/micronaut-core/build/generated/configurationProperties/io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration$Worker.adoc[]

**Comment by graemerocher** [comment]
Duplicates https://github.com/micronaut-projects/micronaut-core/issues/5161

**Comment by gregorydickson** [comment]
ahh, ok. I looked through issues but didn't search. thanks.
