### ISSUE TITLE
HttpClient calls with reactive return types running on eventloop thread

### ISSUE THREAD

**Issue by sanderkoenders** [micronaut-projects/micronaut-core#5192]
### Task List

- [x] Steps to reproduce provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Checkout the [example repository](https://github.com/Archcry/micronaut-httpclient-on-io-thread).
2. Run the application.
3. Navigate to `http://localhost/hello`.
4. Read logs and observe the observable run on the eventloop thread.
5. Navigate to `http://localhost/hello/onIo`.
6. Read logs and observe the observable run on the io thread.

### Expected Behaviour

I expect the `getHello()` call in `HelloClient` which returns `Single<String>` to subscribe on the IO thread because that is what I instruct it to do in `HelloService` on line 29. Like `getHello2()` in `HelloClient` with return value `String` using `Single.fromCallable(helloClient::getHello2)` in `HelloService` on line 36.

### Actual Behaviour

The `getHello()` call in `HelloClient` with return value `Single<String>` is subscribed on the eventloop thread even though I instruct it to subscribe on the IO thread in `HelloService` on line 29.

### Environment Information

- **Operating System**: Archlinux
- **Micronaut Version:** 2.4.1
- **JDK Version:** Openjdk 11.0.10 2021-01-19

### Example Application

https://github.com/Archcry/micronaut-httpclient-on-io-thread

**Comment by graemerocher** [comment]
I believe you would have to use `observeOn` to achieve this behaviour

**Comment by sanderkoenders** [comment]
I used [this medium post](https://medium.com/swift-india/rxswift-subscribeon-vs-observeon-2b121ba95161) to look up the meaning of `subscribeOn` and `observeOn`. The way I think it works is you can initially subscribe on a thread and that's the thread the call is executed on. You can only use `subscribeOn` once so the first call is the one that affects the thread the code is executed on.

>It allows you to change the scheduler on which the subscription code will be executed. subscribeOn changes the thread for the calls prior to it and also the methods that follow it. Order doesn’t matter, subscribeOn can be placed anywhere.

With `ObserveOn` you can change the thread the code below is run on, it affects only code below the call to `observeOn`

>It allows you to change the scheduler on which the observer code will be executed.

I think the issue is that the code is subscribed on the eventloop thread and therefore I am not able to change it anymore because it was already subscribed once. For further reference I recommend the medium post I linked.

**Edit:**

The [micronaut docs](https://docs.micronaut.io/latest/guide/index.html#reactiveServer) also mention the `subscribeOn` method in the following code snippet; only the `personService.findByname(name)` returns a `Person` instead of a reactive type such as `Single<Person>` so `Single.fromCallable` is used. In this case the code is executed on the io thread.

```java
@Controller("/subscribeOn/people")
public class PersonController {

    private final Scheduler scheduler;
    private final PersonService personService;

    PersonController(
            @Named(TaskExecutors.IO) ExecutorService executorService, 
            PersonService personService) {
        this.scheduler = Schedulers.from(executorService);
        this.personService = personService;
    }

    @Get("/{name}")
    Single<Person> byName(String name) {
        return Single
                .fromCallable(() -> personService.findByName(name)) 
                .subscribeOn(scheduler); 
    }
}
```

**Edit 2:**

When you change the loglevel for `io.micronaut.http.client` to `DEBUG` this is what gets logged for both calls:
```
10:27:59.712 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 789ms. Server Running: http://localhost:8080
10:28:12.552 [default-nioEventLoopGroup-1-3] DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP GET to http://localhost:8080/hello/2 <-- First call to /hello
10:28:12.579 [default-nioEventLoopGroup-1-3] DEBUG i.m.h.client.netty.DefaultHttpClient - Received response 200 from http://localhost:8080/hello/2
10:28:12.581 [default-nioEventLoopGroup-1-3] INFO  rxjava.service.HelloService - default-nioEventLoopGroup-1-3 
10:28:26.165 [default-nioEventLoopGroup-1-5] DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP GET to http://localhost:8080/hello/2 <-- Second call to /hello/onIo
10:28:26.183 [default-nioEventLoopGroup-1-5] DEBUG i.m.h.client.netty.DefaultHttpClient - Received response 200 from http://localhost:8080/hello/2
10:28:26.185 [io-executor-thread-1] INFO  rxjava.service.HelloService - io-executor-thread-1 
10:29:04.348 [Thread-0] INFO  io.micronaut.runtime.Micronaut - Embedded Application shutting down
```
As you can see both calls (!) are executed on `default-nioEventLoopGroup-1-*` instead of the io threadpool; and as I understand you should never block the eventloop.

**Comment by ivyazmitinov** [comment]
@Archcry, it is not related to micronaut, it is just how reactive frameworks work. @graemerocher is right, `observeOn` will fix your issue, try for yourself:
```java
    public Single<String> getHello()
    {
        return helloClient.getHello()
                   .observeOn(scheduler)
                   .toObservable()
                   .doOnNext(a -> LOGGER.info(Thread.currentThread().getName()))
                   .firstOrError();
    }
```

It is the same behavior which is applied to operators after a `flatMap`. Consider the following example:
```java
        Observable.just(1, 2, 3)
            .flatMap(i -> Observable.just(i)
                              .doOnNext(__ -> LOGGER.info("in flatmap I am on {}", Thread.currentThread().getName()))
                              .subscribeOn(Schedulers.computation())
                    )
            .doOnNext(__ -> LOGGER.info("after flatmap I'm on {}", Thread.currentThread().getName()))
            .subscribeOn(Schedulers.io())
            .subscribe();
```
Intuitively you would expect the code in the `doOnNext` after the `flatMap` to be executed on `Schedulers.io()` thread, as you instructed. In reality, due to the nuances of implementation of back pressure functionality in reactive libs, it will be executed on the thread from the last applied "therad switching" operators (zips, contacts, everything assuming a `Publisher` as a parameter, basically)

**Comment by ivyazmitinov** [comment]
Still, it is a point of concern. @graemerocher, is it ok that threads from an event loop can "leak" into business logic? I mean, they should not be blocked, but I've always assumed it just means that calls to a database or something like that should always be  offloaded to a dedicated thread pool (what implied by reactive approach itself). 
In other words: is it ok for business logic to be executed on threads from event loop?

**Comment by graemerocher** [comment]
It is absolutely valid to execute logic on the event loop if it doesn’t block. In fact it scales better since you avoid the context switch to spin up another thread
