### ISSUE TITLE
Lots of kapt warnings in the logs

### ISSUE THREAD

**Issue by asarkar** [micronaut-projects/micronaut-core#5218]
Using v2.4.1.
```
> Task :model:kaptKotlin
warning: The following options were not recognized by any processor: '[micronaut.processing.incremental, micronaut.processing.module, micronaut.processing.group,, kapt.kotlin.generated, micronaut.processing.annotations]'
> Task :model:kaptTestKotlin
warning: The following options were not recognized by any processor: '[micronaut.processing.incremental, micronaut.processing.module, micronaut.processing.group,, kapt.kotlin.generated, micronaut.processing.annotations]'
> Task :persistence:kaptKotlin
[WARN] Issue detected with io.micronaut.annotation.processing.BeanDefinitionInjectProcessor. Expected 1 originating source file when generating /Volumes/Workspace/seshat/persistence/build/tmp/kapt3/classes/main/com/asarkar/seshat/persistence/$ProjectRepository$InterceptedDefinition.class, but detected 2: [io.micronaut.data.repository.CrudRepository, com.asarkar.seshat.persistence.ProjectRepository].
Note: Creating bean classes for 5 type elementswarning: The following options were not recognized by any processor: '[micronaut.processing.group,, kapt.kotlin.generated]'[WARN] Incremental annotation processing requested, but support is disabled because the following processors are not incremental: io.micronaut.annotation.processing.BeanDefinitionInjectProcessor (DYNAMIC).
```

Sample app: https://github.com/asarkar/seshat

**Comment by PatrickKaalund** [comment]
Experience these warnings again in `Micronaut version: 2.5.8`.

Please see: https://stackoverflow.com/questions/68352814/kaptkotlin-not-recognizing-micronaut-options, for details :)

**Comment by bwollmer** [comment]
Hi, I have a similar problem with a gradle multi-module micronaut project (`Micronaut Application 1.5.4, Kotlin 1.4.32`). If I create a simple micronaut project, everything works as expected. But as soon as I wrap this project into a multi-module gradle build, I run into this message while running gradle build:
`Note: Creating bean classes for 1 type elementswarning: The following options were not recognized by any processor: '[micronaut.processing.group,, kapt.kotlin.generated]'`
Where 1 is the number of `Singleton` I use.  

Here is an[ example project](https://github.com/bwollmer/micronaut-multi-project-build) where I just created one sub-module with one Singleton, which is just enough to provoke the message. This project was created with `micronaut 2.5.11`. After executing the `gradle clean` task, followed by a `gradle build` the mentioned message appears. I'm not sure, if I missed some configuration for a multi-module project with micronaut or if this is a bug.

**Comment by SolomanDavis** [comment]
Is there any update on this? I still see this in a micronaut + kotlin + gradle multi-module project. There is only 1 module however it is formatted as a multi-module project.

**Comment by igr** [comment]
Same here, with micronaut 3.2.0 and multi project gradle. Any help?

**Comment by DARB-CCM-S-20** [comment]
Any update? Same problem as @bwollmer

**Comment by chrisime** [comment]
I'm experiencing the same problem with my multi-module project.  I'm really wondering why this issue has been closed.

**Comment by mhays118** [comment]
Also experiencing this issue.
