### ISSUE TITLE
DefaultEnvironment should honor the order of environment names

### ISSUE THREAD

**Issue by thiagolocatelli** [micronaut-projects/micronaut-core#523]
[DefaultEnvironment](https://github.com/micronaut-projects/micronaut-core/blob/6bcb38b85b7054ce6793632a42568afa93fea761/inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java#L127), line 127 is using ```Set<String> specifiedNames``` to store the environment names.

By using ```Set<String>``` the order of the environment names provided by the developer is not being honored. ```List<String>``` should be used instead.

(I am implementing a discovery client for Spring Cloud config server and the order provided matters to the server, issue #501 - [link).](https://github.com/micronaut-projects/micronaut-core/issues/501#issuecomment-415553211)

**Comment by jameskleeh** [comment]
@thiagolocatelli To prevent a breaking change, I simply changed the implementation to use a `LinkedHashSet`. That way order and uniqueness is preserved.
