### ISSUE TITLE
[Improvement] Please add ability to customize http-client object mapper

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#5233]
Hello! Finally I decided to try to move from spring-boot to micronaut. In general, it turned out very well. BUT! As described above, the current implementation of http-client does not provide the ability to set up a custom serialization / deserialization policy. And, since Since the services use integrations with external systems that work absolutely differently and have completely different json formats, then we need the ability to set each http client its own custom serializer setting.

Spring webflux has such an option. Each webClient can be customized as needed.

```
    public static ExchangeStrategies createCustomExchangeStrategies(ObjectMapper objectMapper) {
        return ExchangeStrategies.builder()
                .codecs(configurer -> {
                    configurer.defaultCodecs().jackson2JsonEncoder(new Jackson2JsonEncoder(objectMapper, MediaType.APPLICATION_JSON));
                    configurer.defaultCodecs().jackson2JsonDecoder(new Jackson2JsonDecoder(objectMapper, MediaType.APPLICATION_JSON));
                })
                .build();
    }
```

Likewise with other formats such as protobuf, jackson-smile. 

This feature is sorely lacking in micronaut. Please add this feature

**Comment by jameskleeh** [comment]
Are you talking about the low level or declarative client? The declarative client can use `@JacksonFeatures`. I think with recent changes to how clients are injected it is possible to open up that annotation to fields, method params, etc where `@Client` is also used.

**Comment by altro3** [comment]
@jameskleeh Hi! I can not accurately answer this question, low-level replacement or not, but I can more accurately formulate the problem:

Now there are only 2 ways to set the object mapper format:

1. @JacksonFeatures annotation. Unfortunately, this solution does NOT allow setting namingstrategy, dateformat, locale, serialization-inclusion. And it allows you to specify only SerializationFeatures and DeserializationFeatures. In other words, this solution does not solve the problem.

2. To set annotations in each DTO (!!!) all of the above - naming strategy, date format, etc.

So, it would be cool if there was an opportunity to customize the format at the level of each client, because all systems are different, all have their own rules. For example, in my practice there was an api, when it was necessary to transfer all properties, even with a null value.

PS Of course, we always have a "crutch-solution" - to do serialization and deserialization ourselves (before sending and after receiving), and tell the client that we are passing an array of bytes and receiving an array of bytes.

**Comment by yawkat** [comment]
Starting with 3.2, you will be able to pass an additional module in `@JacksonFeatures`. In that module, you can use `(ObjectMapper) context.getOwner()` to configure the module how you want
