### ISSUE TITLE
Publish io.micronaut:micronaut-function-client:1:3.7 to Maven Central

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-core#5244]
Maven Central is missing io.micronaut:micronaut-function-client:1:3.7

see https://mvnrepository.com/artifact/io.micronaut/micronaut-function-client

It should be a single click action in Bintray UI.

Keeping 1.3.7 version alive is important because it's used by the latest Grails version.

### Steps to Reproduce

1. Create Micronaut 1.3.7 function project
2. Remove JCenter repository
3. Try to compile the project

### Expected Behaviour

The project is compiled without any issues

### Actual Behaviour

Dependency  io.micronaut:micronaut-function-client:1:3.7 is not found

### Environment Information

- **Operating System**: macOS 10.15.7
- **Micronaut Version:** 1.3.7
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
Done https://repo1.maven.org/maven2/io/micronaut/micronaut-function-client/1.3.7/

Thanks for pointing this out

**Comment by musketyr** [comment]
Thanks for a quick response!
