### ISSUE TITLE
 Debugging problem in IntelliJ when a bean has interceptors

### ISSUE THREAD

**Issue by henriquelsmti** [micronaut-projects/micronaut-core#5247]
There is a problem when inspecting private field values ​​on any beam that has interceptors linked, such as @Transactional.
Here is a project to do the simulation: https://github.com/henriquelsmti/intellij-micronaut-inspect-problem

Below the prints of a simulation:

Bean with no inteceptions:
![image](https://user-images.githubusercontent.com/9632578/114705210-dc343500-9cfd-11eb-8d08-7459bb1a0eb0.png)
![image](https://user-images.githubusercontent.com/9632578/114705275-f0783200-9cfd-11eb-81ff-75eaf1c5ff7e.png)
![image](https://user-images.githubusercontent.com/9632578/114705320-fb32c700-9cfd-11eb-9b29-6bff5e58f2e2.png)

Bean with inteceptions (@Transactional or any):

public fields works!
![image](https://user-images.githubusercontent.com/9632578/114705517-333a0a00-9cfe-11eb-8931-fec23b0cfbf6.png)
private fields throws groovy.lang.MissingPropertyException.
![image](https://user-images.githubusercontent.com/9632578/114705799-84e29480-9cfe-11eb-9d74-9e053e487f4a.png)
![image](https://user-images.githubusercontent.com/9632578/114705819-8ca23900-9cfe-11eb-8919-b2689fcba6b9.png)

But java evaluate works.
![image](https://user-images.githubusercontent.com/9632578/114705879-9f1c7280-9cfe-11eb-85ae-09d4239b820d.png)

The exemple using Micronaut Groovy and micronaut-data-jpa
Version: 2.4.2 or any after 2.0.0
IntelliJ Issue: https://youtrack.jetbrains.com/issue/IDEA-266938

**Comment by graemerocher** [comment]
The bug here is in IntelliJ/Groovy nothing we can do on the Micronaut side

Micronaut at compilation time produces a subclass that is the AOP proxy which is the actual instance. The subclass doesn't have visilbity on the super class private fields which seems to be a problem for Groovy debugging in IntelliJ
