### ISSUE TITLE
Remote @FunctionClient fails with POJO Parameter

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#525]
Invoking a remote Micronaut Function deployed to AWS Lambda which expects: 

```
{
  "memberStateCode": "es",
  "vatNumber": "B86412491"
}
```

Works when the `@FunctionClient` looks like: 

```
package example.micronaut;

import io.micronaut.function.client.FunctionClient;
import io.reactivex.Single;

import javax.inject.Named;

@FunctionClient 
public interface VatClient {

    @Override
    @Named("vies-vat-validator") 
    Single<VatValidation> validateVat(String memberStateCode, String vatNumber);
}
```

Fails when the `@FunctionClient` looks like:

```
package example.micronaut;

import io.micronaut.function.client.FunctionClient;
import io.reactivex.Single;

import javax.inject.Named;

@FunctionClient 
public interface VatClient {

    @Override
    @Named("vies-vat-validator")
    Single<VatValidation> validateVat(VatValidationRequest req);
}
```

Being `ValidationRequest` a POJO: 

```
package example.micronaut;

import java.io.Serializable;
import java.util.Objects;

public class VatValidationRequest implements Serializable {
    private String memberStateCode;
    private String vatNumber;

    public VatValidationRequest() {
    }

    public VatValidationRequest(String memberStateCode, String vatNumber) {
        this.memberStateCode = memberStateCode;
        this.vatNumber = vatNumber;
    }

    public String getMemberStateCode() {
        return memberStateCode;
    }

    public void setMemberStateCode(String memberStateCode) {
        this.memberStateCode = memberStateCode;
    }

    public String getVatNumber() {
        return vatNumber;
    }

    public void setVatNumber(String vatNumber) {
        this.vatNumber = vatNumber;
    }
}
```

Steps to reproduce:

1. Deploy to AWS Lambda Paris Region the function described in

http://guides.micronaut.io/micronaut-function-aws-lambda/guide/index.html#writingTheLambda

You can obtain the code cloning the repository:

https://github.com/micronaut-guides/micronaut-function-aws-lambda

Under 

`complete/vies-vat-validator`

NOTE: if you deploy it to a different region you will need to modify `complete/invoice/src/main/resources/application.yml` accordingly. 

2. Make sure you have a valid `~/.aws/credentials` file with access to previously deployed Lambda. 

3. Run the standalone microservice which consumes the lambda. 

`complete/invoice$ ./gradlew run`

4. Execute:

`curl -X "POST" "http://localhost:8080/invoice/vat" -H 'Content-Type: application/json' -d $'{"countryCode": "es","vatNumber": "B86412491","lines": [{"count": 2,"price": 19.99,"productId": "1491950358"},{"count": 1,"price": 15,"productId": "1680502395"}]}'`

You should get a response of: 

`{"vat":11.55}`

Now, change to branch `fails-with-pojo`. 

Start the app again:

`complete/invoice$ ./gradlew run`

Execute: 

`curl -X "POST" "http://localhost:8080/invoice/vat" -H 'Content-Type: application/json' -d $'{"countryCode": "es","vatNumber": "B86412491","lines": [{"count": 2,"price": 19.99,"productId": "1491950358"},{"count": 1,"price": 15,"productId": "1680502395"}]}'`

You will get: 

`{"vat":0.00}`

If you place an invoice in the response of the Lambda function you will see response does not contain `memberStateCode` and `vatNumber` which I believe indicates they were not correctly send to AWS Lambda. 

https://github.com/micronaut-guides/micronaut-function-aws-lambda/blob/master/complete/invoice/src/main/java/example/micronaut/InvoiceController.java#L35

Note the Function tests locally in the Function Micronaut project passes. 

https://github.com/micronaut-guides/micronaut-function-aws-lambda/blob/master/complete/vies-vat-validator/src/test/java/example/micronaut/ViesVatValidatorFunctionTest.java

The issue is experienced when invoking a remote function from another Micronaut microservice.

Tutorial: 

http://guides.micronaut.io/micronaut-function-aws-lambda/guide/index.html

Sample Repository:

https://github.com/micronaut-guides/micronaut-function-aws-lambda

Java Version: 1.8.0_181
OS Version: Mac OS High Sierra
Micronaut Version: 1.0.0.M4

**Comment by graemerocher** [comment]
Works once `@Body` is added to the POJO parameter
