### ISSUE TITLE
Returning an empty Optional in a controller makes the response to be invalid

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#526]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a controller and return `Optional.empty()`

### Expected Behaviour

Micronaut should return 404 as it does when returning `null` from a controller

### Actual Behaviour

The response is the string `null` (which is not a valid json) and the status code is 200

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:** OpenJDK 1.8.0_181

**Comment by sdelamo** [comment]
if this is changed, we should ugprade the docs to:

https://docs.micronaut.io/snapshot/guide/index.html#_404_responses

**Comment by paulolieuthier** [comment]
Isn't 4xx for client errors (like wrong path)? Maybe 204 is a better response (even though the specs suggest there should be no return then)?
