### ISSUE TITLE
Proposal: full support for JakartaEE Annotation API.

### ISSUE THREAD

**Issue by CoderYellow** [micronaut-projects/micronaut-core#5268]
I've noticed that micronaut has support Jakarta Inject feature. It would be perfect to fully support [JakartaEE Annotation API](https://github.com/eclipse-ee4j/jakartaee-api) (JPA, JAX-RS) due to the [potential license risk ](https://dzone.com/articles/jakarta-ee-without-javax-the-world-wont-end-this-time-either). I've glanced over the difference between the javax and jakarta specification, it's just a namespace problem.It sholud be easy to migrate it.

**Comment by graemerocher** [comment]
This is in progress already. Micronaut 2.4.x supports `jakarta.inject`

**Comment by jameskleeh** [comment]
We already have support for jakarta.inject and we have another issue for https://github.com/micronaut-projects/micronaut-core/issues/4770. If you have anything else in mind please create a new issue for some specific. This issue in of itself is too broad
