### ISSUE TITLE
Intercepted target is injected into ApplicationEventListener beans

### ISSUE THREAD

**Issue by destan** [micronaut-projects/micronaut-core#5271]
```java
public interface AnotherInterface {
	String anotherDemo();
}

public class AnotherService implements AnotherInterface {
	@Override
	public String anotherDemo() {
		return "...";
	}
}

@Factory
public class SomeFactory {

	@Singleton
	@SomeAnnotation
	public AnotherInterface anotherService() {
		return new AnotherService();
	}

}

@Singleton
@InterceptorBean(SomeAnnotation.class)
public class SomeInterceptor implements MethodInterceptor<Object, Object> {

	@Override
	public Object intercept(MethodInvocationContext<Object, Object> context) {

		System.out.println("########## INTERCEPTED %s#%s ##########".formatted(context.getTarget(), context.getTargetMethod().getName()));

		return context.proceed();
	}
}

@Controller
class DemoController {

	private final AnotherInterface anotherInterface;

	DemoController(AnotherInterface anotherInterface) {
		this.anotherInterface = anotherInterface;
	}

	@Get
	@Produces(MediaType.TEXT_PLAIN)
	String another() {
		return anotherInterface.anotherDemo();
	}

}
```

With above classes, in the controller `AnotherInterface` is injected as an intercepted instance:
![image](https://user-images.githubusercontent.com/442813/115226179-98836600-a117-11eb-9bc1-e7de88fac897.png)

However, when I introduce the following class:

```java
@Singleton
public class SomeEventListener implements ApplicationEventListener<StartupEvent> {

	private final AnotherInterface anotherInterface;

	private final AnotherService anotherService;

	public SomeEventListener(AnotherInterface anotherInterface, AnotherService anotherService) {
		this.anotherInterface = anotherInterface;
		this.anotherService = anotherService;
	}

	@Override
	public void onApplicationEvent(StartupEvent event) {

		anotherInterface.anotherDemo();

		anotherService.anotherDemo();

	}
}
```

There is an un-intercepted instance of `AnotherService` along with the intercepted one:
![image](https://user-images.githubusercontent.com/442813/115226476-f4e68580-a117-11eb-94c4-9431dd025f58.png)

Moreover, now the injected instance in the controller is un-intercepted version as well:
![image](https://user-images.githubusercontent.com/442813/115226587-15aedb00-a118-11eb-89b9-9a78828908f1.png)

### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone the repo and run in debug mode, you can observe the expected behavior
2. Uncomment `@Singleton` annotation on `SomeEventListener` and restart in debug mode
3. You can observe the actual behavior

### Expected Behaviour

* I would expect to find always the intercepted version of `AnotherService` independent from the reference type (`AnotherService` or `AnotherInterface`).
* I would NOT expect to find an un-intercepted (plain) instance of `AnotherService`.
* I would expect the method calls from `AnotherService` to be intercepted by `SomeInterceptor`

### Actual Behaviour

When there is an ApplicationEventListener instance which depends on both `AnotherInterface` and `AnotherService` at the same time, there appears to be a un-intercepted (plain) instance of `AnotherService`.

Moreover, we no longer able to inject the intercepted instance of `AnotherService` wheter we refence it via `AnotherService` or `AnotherInterface`.

When an un-intercepted instance is injected and used its method calls are not intercepted by `SomeInterceptor`.

### Environment Information

- **Operating System**: Ubuntu 20.04.2 LTS
- **Micronaut Version:** 2.4.2
- **JDK Version:** OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)

### Example Application

https://github.com/destan/micronaut-core-issue-5271

**Comment by graemerocher** [comment]
So this could be a breaking change. The issue is in the logic `findExistingCompatibleSingleton` which doesn't exclude proxy targets. Changing this could break existing applications although it is probably the right thing to do. @jameskleeh which version do you think we should target the fix?

**Comment by jameskleeh** [comment]
@graemerocher Probably 3.0

**Comment by jameskleeh** [comment]
This was due to the fact that AOP was on the factory. The AOP implementation is based on the interface and thus cannot be injected when requesting the subclass. If you want the subclass to be injectable it should be the return type of the method. In Micronaut 3 the implementation type cannot be injected at all due to issues like this as well as others.
