### ISSUE TITLE
[Feature] support "configurable" random in PropertyResolver / or allow custom implementations

### ISSUE THREAD

**Issue by bj-eberhardt** [micronaut-projects/micronaut-core#5291]
Feature request:
The property "${random.int}" does not help, because it returns any integer (that can be also negative,-2147483648 to 2147483647). I would like to extend the expression, allowing upper and lower bounds to the random, like used in spring. There might be situations, where you need some random values in a given range.

Background:
As an example, where this new "${random.int}" can be used, is for example a cron expression, like `0 ${random.int[0,20]} 2 * * *`, that allows to run the cron at a random hour between 0h and 22h. If you want to have multiple instances of your micronaut microservice, it makes sense, that the cron for example does not run on every instance at the same moment. With the random, you could better achieve, that the processing does not run at same time.

The changes must be done here: https://github.com/micronaut-projects/micronaut-core/blob/2.4.x/inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java

### Ideas

1. allow giving/configuring the range of randoms in properties, like `${random.int[0,20]}`
2. I would also like the approach, if you can add own "property resolver" here, that would allow custom implementations as well. But for now, all related methods are private and not reuseable for a more common approach.

### Expected Behaviour

the property `${random.int[1,7]}` would return a value between 1 and 7 (would also work with long, etc.)

Happy to hear, what you might think about the request.

**Comment by utsav0209** [comment]
@graemerocher I would like to work on this

**Comment by bj-eberhardt** [comment]
Nice. Thanks for working on this :+1:
