### ISSUE TITLE
Compilation warning: "unknown enum constant When.MAYBE" with Micronaut @Nullable and 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#5323]
There is a compilation warning when using Micronaut `@Nullable` annotation and `3.0.0-SNAPSHOT`. This doesn't happen with Micronaut 2.5.x

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal`
- `cd micronaut-data-jdbc-graal`
- `git checkout 3.0.x_h2`
- `./gradlew compileJava`

### Expected Behaviour

There should be no warnings when compiling

### Actual Behaviour

The are warnings:

```
> Task :compileJava
warning: unknown enum constant When.MAYBE
  reason: class file for javax.annotation.meta.When not found
Note: Writing reflect-config.json file to destination: META-INF/native-image/example.jdbc/micronaut-data-jdbc-graal/reflect-config.json
Note: Writing resource-config.json file to destination: META-INF/native-image/example.jdbc/micronaut-data-jdbc-graal/resource-config.json
Note: Creating bean classes for 7 type elements
warning: unknown enum constant When.MAYBE
  reason: class file for javax.annotation.meta.When not found
warning: unknown enum constant When.MAYBE
  reason: class file for javax.annotation.meta.When not found
warning: unknown enum constant When.MAYBE
  reason: class file for javax.annotation.meta.When not found
4 warnings
```

### Environment Information

- **Operating System**: Linux Mint 20.1
- **Micronaut Version:** 3.0.0-SNAPSHOT
- **JDK Version:** 8

**Comment by LajosPolya** [comment]
Does the PR give the correct solution? It indicates using `gradleScope="annotationProcessor"` but I had to use `implementation` to remove the warning.

**Comment by mariogarcia** [comment]
Same here,  **annotationProcessor** doesn't work. Both **implementation** or **compileOnly** seem to work:

```
// annotationProcessor("com.google.code.findbugs:jsr305") // doesn't work
// implementation("com.google.code.findbugs:jsr305") // does work
compileOnly("com.google.code.findbugs:jsr305")
```

My environment:

- micronautVersion=3.3.4
- jdk=17

**Comment by LajosPolya** [comment]
> Does the PR give the correct solution? It indicates using `gradleScope="annotationProcessor"` but I had to use `implementation` to remove the warning.

My Env:
Micronaut=3.2.3
JDK=16

**Comment by graemerocher** [comment]
probably it makes sense for this to be `compileOnly` in the Gradle/Maven plugins

**Comment by alvarosanchez** [comment]
Why in the plugins and not in starter?
