### ISSUE TITLE
Generic Event Listeners Gets called on all Type of implementations

### ISSUE THREAD

**Issue by utsav0209** [micronaut-projects/micronaut-core#5331]
`@EventListener` annotation when applied to a generic class regardless of what is the implementation type of object in the event it gets invoked.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone the Repository provided below
2. Run `./gradlew test` to check for failing tests
3. Go through the failing tests and then code to gather more information about issue

### Expected Behaviour
Only the methods with `@EventListener` annotation which matches the type of implementation should be called when the event is published.

### Actual Behaviour
All the methods with `@EventListener` annotation defining generic class get called when the event is published.

### Environment Information

- **Operating System**: Pop!_OS 20.10
- **Micronaut Version:** 2.4.4
- **JDK Version:** 11

### Example Application

- https://github.com/utsav0209/mn-generic-event-bug

**Comment by goeh** [comment]
The book event listener have `User` as generic type. Shouldn't it be `Book`?
https://github.com/utsav0209/mn-generic-event-bug/blob/master/src/main/java/mn/generic/event/bug/events/listeners/BookEventListener.java#L19

**Comment by utsav0209** [comment]
@goeh thanks for pointing it out, fixed it. although the issue still persists

**Comment by jameskleeh** [comment]
This feature does not exist today and there is already an issue to track it

Duplicates https://github.com/micronaut-projects/micronaut-core/issues/5281
