### ISSUE TITLE
Path variable regex fails if regex starts with ^ 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#535]
`^` which is often used in regex to matches the starting position within the string causes issue.

Given:

```
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;

@Controller("/api")
public class BookController {
    private static final String ISBN_REGEX = "^1491950358|1680502395$";

    @Get("/books/{isbn:"+ISBN_REGEX+"}")
    public Book getOperation(String isbn) {
        return new Book(isbn, "Building Microservices");
    }
}
```

curl "http://localhost:8081/api/books/1491950358"

returns 404 Not Found

Removing ^ form regex

`    private static final String ISBN_REGEX = "1491950358|1680502395$";`

curl "http://localhost:8081/api/books/1491950358"

returns 200 OK

### Environment Information

- **Operating System**: Mac OS High Sierra
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:** 1.8.0_181

**Comment by puneetbehl** [comment]
It is happening because the RouteBuilder create the pattern as: 

`\Q^\/books\/\E(^1491950358|1680502395$)`

Which does not matche the URI `/books/1491950358-test`.

**Comment by puneetbehl** [comment]
It looks like the only option here is to remove the caret from the URI which will then match to the following:
```
 /books/1491950358
 /books/1680502395
```

However, I am not sure if that's the good idea.

**Comment by puneetbehl** [comment]
@graemerocher, @jameskleeh  please share your thoughts on this once you get a chance.

**Comment by graemerocher** [comment]
I don't understand, why would the `/books/1491950358-test` URI match?

**Comment by puneetbehl** [comment]
@graemerocher I am sorry for the confusion. I meant `/api/books/1491950358` URI.

**Comment by sdelamo** [comment]
I am creating a PR
