### ISSUE TITLE
ExecutableMethod behavior change from 1.3.7 to 2.5.0

### ISSUE THREAD

**Issue by lightbody** [micronaut-projects/micronaut-core#5356]
We are in the middle of trying to upgrade to 2.5.0 and finding that the behavior around how we used `ExecutableMethodProcessor` has changed in a breaking way. You can see a simple of demo of it here:

https://github.com/lightbody/micronaut-executable-method-bug

Specifically, if you look at the [JobService](https://github.com/lightbody/micronaut-executable-method-bug/blob/main/src/main/java/executable/method/bug/JobService.java) code you can see that we are expecting the callback/processing for `@JobListener` adaptation should give us an `ExecutableMethod` that reflects the true type. That is how the 1.3.7 code worked, but with 2.5.0 we're getting the common subclass (`Job`).

**Comment by jameskleeh** [comment]
The processor is getting called with the correct types, and it is also getting called for the `JobProcessor` since they are 2 different methods.
