### ISSUE TITLE
Any request fails with WebSocket error when running in EC2 environment

### ISSUE THREAD

**Issue by derylseale** [micronaut-projects/micronaut-core#5408]
I have a simple containerized microservice that runs fine locally, but fails when deployed to an EC2 environment. This only started happening with v2.5.0, and I've confirmed that there is no problem using up to v2.4.4. Every HTTP request to the service, including to the health endpoint, fails with the following message:

````
{
   "message":"WebSocket Not Found",
   "_links":{
      "self":{
         "href":"/health",
         "templated":false
      }
   }
}
````

I am not using web sockets (so far as I know), so this message is especially confusing. I can't see anything related that changed between 2.4 and 2.5, so I've been unable to deduce any settings I might try to remedy the issue. All requests are over HTTP (not HTTPS).

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a simple service. Even just one that only supports the /health endpoint should work.
2. Create a docker container for the packaged application.
3. Deploy the container to an EC2 instance.

### Expected Behaviour

Any request should succeed, even just a GET to /health.

### Actual Behaviour

Receive a 404 error with the following message:

````
{
   "message":"WebSocket Not Found",
   "_links":{
      "self":{
         "href":"/health",
         "templated":false
      }
   }
}
````

### Environment Information

- **Operating System**: Linux ed999e65f16f 4.14.218-aptible.0 #10 SMP Tue Feb 2 16:44:40 UTC 2021 x86_64 Linux (ami-05da701d18f64756f)
- **Micronaut Version:** v.2.5.0 and higher
- **JDK Version:** openjdk version "13.0.2" 2020-01-14

**Comment by Holophrasis-uk** [comment]
I'm seeing this as well. Even just following the guide: https://guides.micronaut.io/latest/micronaut-elasticbeanstalk-gradle-java.html ends up with the health endpoint giving `{"message":"WebSocket Not Found","_links":{"self":{"href":"/health","templated":false}}}`

Built in Intellij using AWS "Corretto 11 running on 64bit Amazon Linux 2/3.1.8" platform. 

Perhaps something to do with the nginx proxying the request? Hitting the server via http://localhost:5000/health works.
