### ISSUE TITLE
Raising HTTP status 500 with UnsatisfiedRouteException

### ISSUE THREAD

**Issue by marcosflobo** [micronaut-projects/micronaut-core#5422]
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

I'm no able to reproduce the error, however, here a description of the issue.

I have micronaut application exposing an endpoint and, from time to time, on the metric `http_server_requests_seconds_count` I get HTTP status 500 with the exception `UnsatisfiedRouteException`, which means that the client-side is getting an HTTP status 500.

This happens from time to time, not always. The percentage of requests responded like this might be ~0.5%

I don't have stack trace on the server-side and, due I cannot reproduce the issue, either from the client-side.

#### Source code
```
@Controller("/v1/myendpoint")
@Slf4j
public class MyController {

    @Post
    @Consumes(ProtobufferCodec.PROTOBUFFER_ENCODED)
    @Produces(ProtobufferCodec.PROTOBUFFER_ENCODED)
    public HttpResponse<MyResponse> analyze(HttpRequest<byte[]> request,
        @Body byte[] enhanceRequest) {

        ....

        MyResponse r = ...

        return HttpResponse.ok().body(r);
    }
}
```

### Expected Behaviour

The HTTP status 500 should not happen if a request is not satisfied by the server-side

### Actual Behaviour

HTTP status 500 with the exception `UnsatisfiedRouteException` is raised to the client-side

### Environment Information

- **Operating System**: Linux (docker)
- **Micronaut Version:** 2.0.1
- **JDK Version:** 11

**Comment by jameskleeh** [comment]
> The HTTP status 500 should not happen if a request is not satisfied by the server-side

You can change the response as a result of an `UnsatisfiedRouteException` by replacing the `UnsatisfiedRouteHandler` bean

**Comment by jameskleeh** [comment]
I just read your issue again and it seems incorrect that the response code is 500. Please upload an example application with steps to reproduce that shows the response code is 500 as a result of an UnsatisifedRouteException

**Comment by marcosflobo** [comment]
@jameskleeh Unfortunately, I cannot upload the code here.

Insight for you. we replaced the siganture of the controller from 
```public HttpResponse<MyResponse> analyze(HttpRequest<byte[]> request, @Body byte[] enhanceRequest) {```
to this
```public HttpResponse<MyResponse> analyze(@Body byte[] enhanceRequest) {```
And the problem dissapears

**Comment by marcosflobo** [comment]
Actually, with that new method signature, we do not have `UnsatisfiedRouteException` anymore and now we have `UnsatisfiedBodyRouteException`

**Comment by jameskleeh** [comment]
@marcosflobo In order to proceed forward we will need an example application that shows the issue

**Comment by marcosflobo** [comment]
@jameskleeh the source code provided in the initial post is the "main entrance" of the application. I can tell you that when the issue happens, no single line of that controller is executed because the exception raises in some unknown step in advance.

After several experiments, we have some clues: Performance issue

This microservice receives 12 req/sec with body requests that can be around 30MB-60MB. Within the microservice, we perform a chop of those body requests in smaller pieces (1MB) for producing them into a NATS queue. 

We believe that the mix of req/sec and the logic we have generates performance issues that raise the `UnsatisfiedRouteException`/`UnsatisfiedRouteHandler`

**Comment by jameskleeh** [comment]
@marcosflobo Without something to debug I wouldn't know where to start. I'll close this for now, but if you're able to get an example app that reproduces the problem I'll reopen this issue

**Comment by marcosflobo** [comment]
@jameskleeh Just for you to know, we upgraded to micronaut version 2.0.1 -> 2.5.4 and the problem just disappeared
