### ISSUE TITLE
Regression 2.4.x 2.5.x Unable to deploy to Elastic Beanstalk

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#5426]
# Steps to reproduce

`mn create-app example.micronaut.micronautguide --inplace`

## Health Endpoint

Add `micronaut-management` dependency:

```groovy
dependencies {
...
..
.
    implementation("io.micronaut:micronaut-management")
}
```

## Port 5000 EC2 Env

Create a file to run the application in port 5000 when deployed to  [Elastic Beanstalk](https://aws.amazon.com/elasticbeanstalk/)

`src/main/resources/application-ec2.yml`
 
```yaml
micronaut:
  server:
    port: 5000
```    

## Deployment

Generate a FAT JAR: 

```
./gradlew build
```

## Elastic Beanstalk application

Create a Java 11 application in [Elastic Beanstalk](https://aws.amazon.com/elasticbeanstalk/). 

<img width="689" alt="Screenshot 2021-05-15 at 07 47 50" src="https://user-images.githubusercontent.com/864788/118349659-33723300-b552-11eb-90f1-6433af9a6684.png">

As application code upload FAT JAR `build/libs/micronautguide-0.1-all.jar`.

# Current behaviour

GET request to the health endpoint:

```
curl http://micronautguide.us-east-1.elasticbeanstalk.com/health 
{"message":"WebSocket Not Found","_links":{"self":{"href":"/health","templated":false}}}%   
```

# Expected output

If I change the Micronaut version in `gradle.properties` to 2.4.4, generate and deploy the FAT JAR to [Elastic Beanstalk](https://aws.amazon.com/elasticbeanstalk/)

GET request to the health endpoint:

```
curl http://micronautguide.us-east-1.elasticbeanstalk.com/health 
{"status":"UP"}   
```

**Comment by graemerocher** [comment]
@dstepanov could you take a look?
