### ISSUE TITLE
HttpClient should handle Set-Cookie header when automatically redirecting.

### ISSUE THREAD

**Issue by CoderYellow** [micronaut-projects/micronaut-core#5484]
HttpClient should use the new cookies from redirect response if the cookie matching. Just like the browser do. I can't see any cookies handling in the [HttpClient](https://github.com/micronaut-projects/micronaut-core/blob/32013f3f2c5aba3cca0431b04ae2737c4978b509/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L2330). It still use the origin headers.

**Comment by CoderYellow** [comment]
It is necessary because the new authenticated session id will be stored in the Set-Cookie header in some scenario, like gitlab login.

**Comment by CoderYellow** [comment]
I think micronaut should implement something like CookieManager in OkHttpClient.

**Comment by jameskleeh** [comment]
I don't think we will do this. See https://github.com/micronaut-projects/micronaut-core/issues/2650
