### ISSUE TITLE
Controller returning Flowable with error as a 1st item should/could return a non-200 response http code.

### ISSUE THREAD

**Issue by stepanv** [micronaut-projects/micronaut-core#5488]
Hi Micronaut team, I wonder if there is a workaround for this.
This is possibly a feature request.

I have a Controller rest endpoint returning `Flowable` and I want to get non-200 in case the first item in the `Flowable` is actually an error (the same for Reactor `Flux`).
It looks like Micronaut "blindly" sends 200 without waiting for the first item which could be an error.

In case of `Single` or `Mono` Micronaut waits for the item and correctly returns 200 or executes the error mappers in case of an error.

### Steps to Reproduce

See the `ServerErrorSpec` modification at https://github.com/stepanv/micronaut-core/commit/81f3c0b6e2cab54da4da291caf00ef7d6aee890d

### Expected Behaviour

I need to be able to control the http error code if something gets wrong (in a reactive fashion) before I start to emit the reactive items.
I cannot use the approach with returning `HttpResponse<Flowable<?>>` described at https://github.com/micronaut-projects/micronaut-core/issues/5344 as I detect the error state during the execution of the `Flowable`, so the controller's method is already executed and returned.

### Actual Behaviour

It looks like Micronaut "blindly" sends 200 without waiting for the first item which could be an error.

### Environment Information

- **Micronaut Version:** 2.5.x

**Comment by stepanv** [comment]
Hi @jameskleeh , by any chance could you please help me identify if this feature is either

- something the Micronaut team will implement soon (in next weeks let's say)
- OR 
- if it's just a nice-to-have feature and it's very unlikely it will get implemented unless someone external contributed?

Thanks!

**Comment by jameskleeh** [comment]
@stepanv This has come up in the past and its something we should fix. I can't give you a timeline for when that will happen, however.
