### ISSUE TITLE
HttpClient should not append forward slash to the base uri with query paremters

### ISSUE THREAD

**Issue by CoderYellow** [micronaut-projects/micronaut-core#5492]
HttpClien should not append forward slash to the bas uri with query paremters when the uri in `@Get` annotation is empty;
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce
1. code
```kotlin
@Client("https://api.github.com/repos/micronaut-projects/micronaut-core/issues")
interface GitHubApi {
    @Get
    @Header(name = USER_AGENT, value = "micronaut")
    @Consumes(MediaType.APPLICATION_JSON)
    fun getIssues(): String

    @Get
    @Header(name = USER_AGENT, value = "micronaut")
    @Consumes(MediaType.APPLICATION_JSON)
    fun getIssuesWithQuery(@QueryValue state: String): String

}
```

2. test
```groovy
@MicronautTest
class GitHubApiSpec extends Specification {
    @Inject
    GitHubApi gitHubApi

    def "should get issues"() {
        when:
        def issues = gitHubApi.getIssues()
        then:
        null != issues
        notThrown(Exception)

    }

    def "GetIssuesWithQuery not working"() {
        when:
        def issues = gitHubApi.getIssuesWithQuery("all")
        then:
        null == issues
    }
}
```

### Expected Behaviour
The request url in the test `GetIssuesWithQuery not working` should be 
`https://api.github.com/repos/micronaut-projects/micronaut-core/issues?state=all`. Just like the first test
Tell us what should happen

### Actual Behaviour
log in the first test:
```bash
12:58:52.156 [default-nioEventLoopGroup-1-1] DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP GET to https://api.github.com/repos/micronaut-projects/micronaut-core/issues
12:58:52.158 [default-nioEventLoopGroup-1-1] TRACE i.m.h.client.netty.DefaultHttpClient - User-Agent: micronaut
12:58:52.159 [default-nioEventLoopGroup-1-1] TRACE i.m.h.client.netty.DefaultHttpClient - Accept: application/json
12:58:52.159 [default-nioEventLoopGroup-1-1] TRACE i.m.h.client.netty.DefaultHttpClient - host: api.github.com
12:58:52.159 [default-nioEventLoopGroup-1-1] TRACE i.m.h.client.netty.DefaultHttpClient - connection: close
12:58:59.971 [default-nioEventLoopGroup-1-1] DEBUG i.m.h.client.netty.DefaultHttpClient - Received response 200 from https://api.github.com/repos/micronaut-projects/micronaut-core/issues
```

log in the second test:
```
12:54:20.254 [default-nioEventLoopGroup-1-1] DEBUG i.m.h.client.netty.DefaultHttpClient - Sending HTTP GET to https://api.github.com/repos/micronaut-projects/micronaut-core/issues/?state=all
12:54:20.257 [default-nioEventLoopGroup-1-1] TRACE i.m.h.client.netty.DefaultHttpClient - User-Agent: micronaut
12:54:20.257 [default-nioEventLoopGroup-1-1] TRACE i.m.h.client.netty.DefaultHttpClient - Accept: application/json
12:54:20.258 [default-nioEventLoopGroup-1-1] TRACE i.m.h.client.netty.DefaultHttpClient - host: api.github.com
12:54:20.258 [default-nioEventLoopGroup-1-1] TRACE i.m.h.client.netty.DefaultHttpClient - connection: close
12:54:22.311 [default-nioEventLoopGroup-1-1] DEBUG i.m.h.client.netty.DefaultHttpClient - Received response 404 from https://api.github.com/repos/micronaut-projects/micronaut-core/issues/?state=all
```
`https://api.github.com/repos/micronaut-projects/micronaut-core/issues/?state=all` is not what expecting.

### Environment Information

- **Operating System**: TODO
- **Micronaut Version:** TODO
- **JDK Version:** TODO

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by CoderYellow** [comment]
[Here](https://github.com/micronaut-projects/micronaut-core/blob/5f7a0970bc48de6d22383421131d5a1212bb0976/core/src/main/java/io/micronaut/core/util/StringUtils.java#L369):
```java
      public static String prependUri(String baseUri, String uri) {
        if (!uri.startsWith("/")) {
            uri = "/" + uri;
        }
        if (uri.length() == 1 && uri.charAt(0) == '/') {
            uri = "";
        }
        uri = baseUri + uri;
        if (uri.startsWith("/")) {
            return uri.replaceAll("[//]{2,}", "/");
        } else {
            return uri.replaceAll("(?<=[^:])[//]{2,}", "/");
        }
    }
```
I thik this method should consider this situation: the paramter list in the `@Get` annotation is empty which means the `uri` is just 
a query string  starting with `?`, then the `uri` should append to the `baseUri` directly.

**Comment by CoderYellow** [comment]
@jameskleeh

**Comment by jameskleeh** [comment]
Can you explain what problem this is causing?

**Comment by CoderYellow** [comment]
there is a forward slash between issues and ? which is not expeced 
https://api.github.com/repos/micronaut-projects/micronaut-core/issues/?state=all

**Comment by CoderYellow** [comment]
> Can you explain what problem this is causing?

Sorry for my poor English,but i think the problem is clear
![bug](https://user-images.githubusercontent.com/43698473/119829939-59261180-bf2e-11eb-9cb4-e8c912c22c29.png)
![image](https://user-images.githubusercontent.com/43698473/119829982-63e0a680-bf2e-11eb-99c1-b20619e3db9d.png)

Is it going to be fixed?

**Comment by jameskleeh** [comment]
@CoderYellow Yep seems reasonable. PR welcome

**Comment by CoderYellow** [comment]
> @CoderYellow Yep seems reasonable. PR welcome

[PR](https://github.com/micronaut-projects/micronaut-core/pull/5493) has bean made.I it be a hornor to contribute to micronaut
