### ISSUE TITLE
Micronaut still unjustly refuses WebSocket connections from Firefox

### ISSUE THREAD

**Issue by BenTels** [micronaut-projects/micronaut-core#5513]
L.S.,

I am opening this issue to draw attention to the fact that issue #5425 is not fixed. I have added a comment to that issue and a PR with a suggested fix.

I'm not sure if this is the way I am supposed to do this, but as a non-contributor I cannot reopen the issue and I was worried you wouldn't notice changes to a closed issue.

**Comment by graemerocher** [comment]
@dstepanov please take a look

**Comment by jameskleeh** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/8bbdfe2b9b7bc78b1679983f98e091730e7f7e3b
