### ISSUE TITLE
Possible HTTP Filter bug since micronaut 2.5.x

### ISSUE THREAD

**Issue by jorgsant** [micronaut-projects/micronaut-core#5526]
### Steps to Reproduce

Run micronaut application in https://github.com/jorgsant/micronaut-bug-http-filter

```
curl --location --request POST 'http://localhost:8080/micronaut-filter-test' \
--header 'Content-Type: application/json' \
--data-raw '{
    "test": "micronaut-filter"
}'
```

Check logs:
`[default-nioEventLoopGroup-1-3] INFO  e.micronaut.filter.DummyHttpFilter - HTPP Request body: null`

Change micronaut version to 2.4.4 in gradle.properties and repeat above steps:

`[default-nioEventLoopGroup-1-3] INFO  e.micronaut.filter.DummyHttpFilter - HTPP Request body: {"test":"micronaut-filter"}`

### Expected Behaviour

Body should not be null/empty

### Actual Behaviour

When accessing the request body from a HttpServerFilter it is always empty/null.
This did not happen in version 2.4.4

### Environment Information

- **Operating System**: Mac OS X and Alpine Linux
- **Micronaut Version:** 2.5.x
- **JDK Version:** OpenJDK 16

### Example Application

https://github.com/jorgsant/micronaut-bug-http-filter

**Comment by jameskleeh** [comment]
This is not a bug. See https://docs.micronaut.io/2.5.x/guide/#breaks
