### ISSUE TITLE
Tracing library restricts setting JAEGER_SERVICE_NAME via environment variable

### ISSUE THREAD

**Issue by SubhadeepSen** [micronaut-projects/micronaut-core#5527]
I have been using the micronaut tracing library with jaeger for getting the traces. The application name property has not been set in application.yml file. Now I'm trying to set the JAEGER_SERVICE_NAME via environment variable but it is never set. The value is always **application**.

Now when I update my application.yml file with application name property the JAEGER_SERVICE_NAME is also getting set to application name.

After going through the code, I've understood that setting JAEGER_SERVICE_NAME via environment variable will never be possible.

**_Reason:_**
1. It has been checked if JAEGER_SERVICE_NAME is set via System property. If it is not set, then System property is set for JAEGER_SERVICE_NAME with either application name or the default value which is **application**.

Reference: https://github.com/micronaut-projects/micronaut-core/blob/2.5.x/tracing/src/main/java/io/micronaut/tracing/jaeger/JaegerConfiguration.java#L67

2. Now a method has been called to configure from environment variables. This method is present in jaeger-core library.

Reference: https://github.com/micronaut-projects/micronaut-core/blob/2.5.x/tracing/src/main/java/io/micronaut/tracing/jaeger/JaegerConfiguration.java#L69

3.  fromEnv() method internally calls getProperty() method. Here it returns the JAEGER_SERVICE_NAME set in System property or environment variable value as default if System property is not set.

Reference: https://github.com/jaegertracing/jaeger-client-java/blob/318dad2808454f483785db270e066fed4e60160a/jaeger-core/src/main/java/io/jaegertracing/Configuration.java#L730

**_Conclusion:_** 
It will never consider the environment variable value as the System property was set by micronaut tracing library.

Can we also consider setting JAEGER_SERVICE_NAME via environment variable ?

if (StringUtils.isEmpty(System.getProperty(JAEGER_SERVICE_NAME)) && StringUtils.isEmpty(System.getenv(JAEGER_SERVICE_NAME))) {
 // existing code 
}

**Comment by graemerocher** [comment]
Sure seems reasonable. PRs welcome.

**Comment by SubhadeepSen** [comment]
Thanks, I'll work on this and raise the PR.

**Comment by SubhadeepSen** [comment]
@graemerocher could you please help by approving the workflow(s)
