### ISSUE TITLE
Type element visitors never visit inner classes

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#5534]
Related issue https://github.com/micronaut-projects/micronaut-data/issues/892

**Comment by nbrugger-tgm** [comment]
I wanted to open a bug issue but i think this might be the cause.
If i create a class that has an inner class and that inner class has an AOP advice the compiler does **not** fail but there is nothing generated for the inner class (like $Reference).

Will this be covered by this ticket or should i create a new one?

Example
```java
@Singleton
class Outer {
    pulic Inner inner(){
        new Inner();
    }
    class Inner { //not static
        @ExceptionOnCall //around AOP advice
        public void noop(){}
    }
}

//Test
@Inject Outer outer;
outer.inner().noop(); // doesn't throw exception but executes noop()
```

I think the correct way to handle this would be to error the compilation with something like:
```
AOP advices cannot be applied to inner classes since you would need to instantiate its generated proxy
```

**Comment by fwgreen** [comment]
Just encountered this while moving a hobby project from Quarkus.  Glad to know it's a known issue.

**Comment by dstepanov** [comment]
This might be fixed in Micronaut 4

**Comment by dstepanov** [comment]
It should be fixed in v4
