### ISSUE TITLE
Add more customization for query parameters & Document modifying uri with client argument binders

### ISSUE THREAD

**Issue by andriy-dmytruk** [micronaut-projects/micronaut-core#5536]
# Description

Unable to bind parameters to query with `AnnotatedClientArgumentRequestBinder ` (Using bind to add headers is described in [docs](https://docs.micronaut.io/latest/guide/#clientParameters))

# Reproduce

**The code is available in a [github repo](https://github.com/andriy-dmytruk/query-param-binder/tree/master/src/main/java/com/example).**

To add a query parameter, I create a custom annotation:
```java
@Documented
@Retention(RUNTIME)
@Target(PARAMETER)
@Bindable
public @interface NameQueryParam {
}
```

Then add the annotation to a `Client`:
```java
@io.micronaut.http.client.annotation.Client("/")
public interface Api {
    @Get("/person")
    void customQuery(@NameQueryParam String name);
}
```
(Making `@Get("/person{?name}")` does not fix it either.

The binder looks the following:
```java
@Singleton
public class NameQueryParamBinder implements AnnotatedClientArgumentRequestBinder<NameQueryParam> {
    @NotNull
    @Override
    public Class<NameQueryParam> getAnnotationType() {
        return NameQueryParam.class;
    }

    @Override
    public void bind(@NotNull ArgumentConversionContext<Object> context,
                     @NonNull ClientRequestUriContext uriContext,
                     @NotNull Object value,
                     @NotNull MutableHttpRequest<?> request
    ) {
        request.getParameters().add("name", value.toString());
    }
}
```

# Result

The request is then lacking the described query parameter and is simply `/person`.

This is likely caused because inside `HttpClientIntroductionAdvice` the uri is set on line [292](https://github.com/micronaut-projects/micronaut-core/blob/3f33453ec8b10a3bbcdd1af71ca4189cb923d87b/http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java#L292). 

It overwrites any changes to query parameters or uri which are made on line [241](https://github.com/micronaut-projects/micronaut-core/blob/3f33453ec8b10a3bbcdd1af71ca4189cb923d87b/http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java#L241).

The expected behaviour is to be able to add queryParameters (likely for both `{?name}` being specified as query and not). This is important if user wants to customize format for collections in query (like `?names=A,B` or `?name=A|B`, etc.).

**Comment by jameskleeh** [comment]
You can do so via the `ClientRequestUriContext`. I'll leave this open to improve the documentation

**Comment by andriy-dmytruk** [comment]
Thank you @jameskleeh ! 

There is one more problem I am facing. Basically I want to implement collection format `multi` given by [openapiv2](https://swagger.io/specification/v2/) specification and would transform `List foo = ["bar", "baz"]` into query parameter `foo=bar&foo=baz`. However this is not achievable, as queryParameters are stored in a Map and the values that I pass to `uriContext.getQueryParameters().put(key, value)` later get encoded (thus `&`, `=` are removed).

Can you help me with a way to solve it?

PS: there are also other formats, like pipe (`|`) separated values, which will also get encoded and not work correctly.

**Comment by jameskleeh** [comment]
@andriy-dmytruk Appreciate the feedback. I'll modify it for Micronaut 3 to support that

**Comment by andriy-dmytruk** [comment]
@jameskleeh I will work on it, as I probably know better what is required. 
Can you please reassign it to me, as I don't seem to be allowed to do it?

**Comment by jameskleeh** [comment]
@andriy-dmytruk A PR is welcome. The only thing that should be changed though is the underlying map and `getQueryParameters()` should return a `Map<String, List<String>>`. Please target the 3.0.x branch
