### ISSUE TITLE
SimpleCookie#toString doesn't generate a valid value for Set-Cookie

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [micronaut-projects/micronaut-core#5542]
Method toString of SimpleCookie currently returns a value similar to what would be possible to use on the Set-Cookie header but with some differences. It would be better to return a String value that is compliant with the HTTP specification.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

```java
import io.micronaut.http.cookie.SameSite;
import io.micronaut.http.simple.cookies.SimpleCookie;

public class Application {
    public static void main(String[] args) {
        System.out.println(
            SimpleCookie("NAME", "VALUE")
                .sameSite(SameSite.Lax)
                .maxAge(1)
                .domain(".micronaut.io")
                .path("/")
                .secure(true)
                .httpOnly(true)
                .toString()
        );
    }
}
```

### Expected Behaviour

```
NAME=VALUE; Domain=.micronaut.io; Path=/; Max-Age=1; Secure; HttpOnly; SameSite=Lax
```

### Actual Behaviour

```
NAME=VALUE, domain=.micronaut.io, path=/, maxAge=1s, secure, HTTPOnly, SameSite=Lax
```

### Environment Information

- **Operating System**: macOS Big Sur 11.3.1 (20E241)
- **Micronaut Version:** 2.5.4
- **JDK Version:** openjdk 11.0.11 2021-04-20 LTS

**Comment by t0rr3sp3dr0** [comment]
Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

**Comment by yawkat** [comment]
I don't think we should support this.

- `NettyCookie` doesn't support this either (it has no toString at all)
- netty's `DefaultCookie` impl matches our behavior for toString, they're not `Set-Cookie`-compliant either
- Cookie encoding is different for client and server, so picking one representation doesn't make sense (though the client impl is trivial, so maybe less of a point)
- Cookie encoding, like all encoding, is a potential security risk. We can't use netty `ServerCookieEncoder` for the `DefaultCookie.toString` impl. Though cookie encoding is pretty trivial, so I don't think this is a big issue.

imo if a user wants a valid cookie value they can use ServerCookieEncoder directly.

**Comment by nanodeath** [comment]
I think the fact that the `toString` is vaguely _close_ to the spec is a little confusing, and also not documented. Generally I believe/agree that `toString` should not be used for production codepaths. Except StringBuilder#toString, apparently...

Anyway, if anyone else stumbles on this in the future, the quick proper way to do this based on the above comment, is:

```java
io.micronaut.http.cookie.ServerCookieEncoder.INSTANCE.encode(cookie)
```
