### ISSUE TITLE
Custom reason phrase is inaccessible in filters when using Netty runtime

### ISSUE THREAD

**Issue by lgathy** [micronaut-projects/micronaut-core#5544]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Micronaut project using Netty runtime.
2. Create an HTTP endpoint and set a custom reason phrase in the response.
3. Create an `HttpServerFilter`, wrap the publisher to access the set reason phrase in the `onNext` method - i.e. copy its value into a custom HTTP header.

### Expected Behaviour

The custom reason phrase is expected to be set in the response header.

### Actual Behaviour

The value of the HTTP response header set in the filter contains the standard reason string defined in the `io.micronaut.http.HttpStatus` enum.

The root cause of the problem is that `io.micronaut.http.netty.NettyMutableHttpResponse` does not override the default implementation of the `reason()` method defined in the `HttpResponse` interface, so it uses `getStatus().getReason()` which always returns the default reason phrase predefined in the `HttpStatus` enum.

To fix this, override this method in `NettyMutableHttpRespnonse` as:

```java
  @Override
  public String reason() {
    return httpResponseStatus.reasonPhrase();
  }
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.5.5
- **JDK Version:** OpenJDK 11.0.11

### Example Application

https://github.com/lgathy/micronaut-netty-reason-phrase-example

**Comment by jameskleeh** [comment]
@lgathy PR welcome :)

**Comment by lgathy** [comment]
@jameskleeh PR is now raised, sorry for the delay.
