### ISSUE TITLE
Micronaut is sending connection: close for all request with status > 499

### ISSUE THREAD

**Issue by leenanimbekar** [micronaut-projects/micronaut-core#5552]
The connection isn't bad and can be reused regardless if the response was a 200, 404 or 502.
Can we have some potential feature flag or some alternative to not invoke this behaviour? Is there any issue if we bypass this logic?
```
if (!expectKeepAlive || httpStatus.getCode() &gt; 499) {                    
nettyHeaders.set(HttpHeaderNames.CONNECTION, HttpHeaderValues.CLOSE);               
 } else {                   
 nettyHeaders.set(HttpHeaderNames.CONNECTION, HttpHeaderValues.KEEP_ALIVE);                
}
```

### Steps to Reproduce

Any request where request fails with > 499 status has this header. 

### Expected Behaviour

We should have connection close only if something goes wrong with connection.   

### Actual Behaviour

Tell us what happens instead

### Environment Information

- **Operating System**: TODO
- **Micronaut Version: 1.3.7 and above
- **JDK Version:** TODO

### Example Application

link to github repository with example that reproduces the issue
link to code in question :

https://github.com/micronaut-projects/micronaut-core/blob/ee842bd1e1b62b8a49a971fead4e076a7d9a0b7b/http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java#L1712

**Comment by graemerocher** [comment]
```
Expected Behaviour

We should have connection close only if something goes wrong with connection.
```

A code 500 indicates something went wrong with the application. Having said that PRs welcome and if you wish to add a config option to address your use case go ahead.
