### ISSUE TITLE
Extracting RxJava2 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#5554]
I have created the repository to start the move RxJava2: 

https://github.com/micronaut-projects/micronaut-rxjava2

I have moved `instrument`, `converters` and the main `RxClient` files.  However, I am not sure what we want to do with 
[DefaultHttpClient](https://github.com/micronaut-projects/micronaut-core/blob/3.0.x/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java). 

The [Reactor Implementation](https://github.com/micronaut-projects/micronaut-reactor/blob/master/reactor-http-client/src/main/java/io/micronaut/reactor/http/client/BridgedReactorHttpClient.java) and the [RxJava 3 implementation](https://github.com/micronaut-projects/micronaut-rxjava3/blob/master/rxjava3-http-client/src/main/java/io/micronaut/rxjava3/http/client/BridgedRx3HttpClient.java) adapt around the `DefaultHttpClient` RxJava 2 implementation. Do we want to rewrite `DefaultHttpCllient` to use Reactor instead? And then create a `BridgeRx2HttpClient` to wrap the new Project Reactor `DefaultHttpClient` into RxJava2?

Is this the plan @graemerocher @dstepanov @jameskleeh ?

**Comment by graemerocher** [comment]
yes the client needs to be rewritten in reactor then an adaptor provide that implements `RxHttpClient`

**Comment by graemerocher** [comment]
We need upgrade docs explaining to rxjava users what to do
