### ISSUE TITLE
Feature Request: Support for auto instrumentation with OpenTelemetry standard

### ISSUE THREAD

**Issue by SubhadeepSen** [micronaut-projects/micronaut-core#5592]
The greatest promise of OpenTelemetry is a single standard for observability instead of two competing standards (OpenTracing and OpenCensus). 

Currently micronaut tracing supports auto-instrumentation feature with only Open Tracing standard where jaeger or zipkin tracing library can be used for instrumentation. But there is no auto-instrumentation feature available with Open Telemetry standard. Hence clients will have to manually instrument their application if they want to use Open Telemetry standard.

By providing an auto-instrumentation feature with Open Telemetry standard will reduce the pain of manual instrumentations.

**Comment by graemerocher** [comment]
Duplicates https://github.com/micronaut-projects/micronaut-core/issues/5138
