### ISSUE TITLE
Verify that modules work properly with Micronaut 3.0

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#5607]
We need to upgrade all modules to Micronaut 3.0 and release new major versions of them.

To do the upgrade:
  - Upgrade Micronaut version in the module to Micronaut 3.0.0-M2 (or any release after it)
  - Use Micronaut nullability annotations
  - Switch to Jakarta annotations.
  - Change `javax.inject.Provider` to `io.micronaut.context.BeanProvider`
  - If the module has an RxJava dependency add a dependency on `implementation 'io.projectreactor:reactor-core'` and switch to it (look for RxJava2 - Reactor equivalences in https://github.com/micronaut-projects/micronaut-core/pull/5583). Public interfaces should not expose reactor types but `Publisher`. 
  - Upgrade to Gradle 7
  - Upgrade to the latest version on the build plugins (currently 4.0.0) and docs (2.0.0.RC1)
  - Review the annotations in this PR https://github.com/micronaut-projects/micronaut-core/pull/5643 and modify the module accordingly
  - Review `@Introspected` classes. If the annotation is there for GraalVM, then replace it with `@ReflectiveAccess`. If not, just add `@ReflectiveAccess`/`@TypeHint`.
  - Release a new major Milestone version of the module that targets Micronaut 3.0.x branch in core.
  - When Micronaut 3.0 is released we need to upgrade the module with 3.0.0 (instead of the M or RC version) and release a new patch version targeting next Micronaut 3 patch release (theoretically 3.0.1)

Legend:

| Symbol | Status |
| :---: | --- |
| ✅| Upgraded to Micronaut 3 |
| ✳️| Upgrade to Micronaut 3 in progress, waiting on some dependency | 
| ❌| Doesn't work with Micronaut 3 |
| ❓| Hasn't been tested with Micronaut 3 |
| ☑️ | Not Applicable |

The upgrade PRs are mostly to see the changes required for the upgrade, so that when they want to move ahead, don't need to start from scratch. PRs that are failing are marked as draft to prevent merges.

Micronaut version in the following tables is the current Micronaut version used in `master` branch

### Data Access

| Module | Micronaut version | Status | Upgrade PR | Issues | Additional comments |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [Data](https://github.com/micronaut-projects/micronaut-data) | 3.0.0-M5 |✅|  |  | `3.0.0-RC1`|
| [MongoDB](https://github.com/micronaut-projects/micronaut-mongodb) | 3.0.0-M4 |✅|  |  | `4.0.0-M2`  |
| [Neo4j Configuration](https://github.com/micronaut-projects/micronaut-neo4j) | 3.0.0-M4 |✅|  |  |  `5.0.0-RC1`|
| [Redis](https://github.com/micronaut-projects/micronaut-redis) | 3.0.0-M4 |✅|  |  | `5.0.0-M1` |
| [SQL / JDBC ](https://github.com/micronaut-projects/micronaut-sql) | 2.5.8 | ✅| https://github.com/micronaut-projects/micronaut-sql/pull/469 |  | `4.0.0-RC4` |
| [Cassandra](https://github.com/micronaut-projects/micronaut-cassandra) | 3.0.0-M4 | ✅|  |  |  |
| [R2DBC](https://github.com/micronaut-projects/micronaut-r2dbc) | 2.5.9 |✅| https://github.com/micronaut-projects/micronaut-r2dbc/pull/139 |  | `2.0.0-RC2` |

### Database Migration

| Module | Micronaut version | Status | Upgrade PR | Issues | Additional comments |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [Flyway](https://github.com/micronaut-projects/micronaut-flyway) | 2.5.9 | ✅ |  |  |  Released `4.0.0`|
| [Liquibase](https://github.com/micronaut-projects/micronaut-liquibase) | 2.5.9 | ✅ |  |  | Released `4.0.0` |

### Analytics

| Module | Micronaut version | Status | Upgrade PR | Issues | Additional comments |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [ElasticSearch](https://github.com/micronaut-projects/micronaut-elasticsearch) | 3.0.0-M4 |✅|  |  | `3.0.0-M1` |
| [JMX](https://github.com/micronaut-projects/micronaut-jmx) | 3.0.0-M2 |✅|  |  | `3.0.0-RC2` |
| [Micrometer](https://github.com/micronaut-projects/micronaut-micrometer) | 3.0.0-M4 | ✅ |  |  | `4.0.0-RC2` |

### Views

| Module | Micronaut version | Status | Upgrade PR | Issues | Additional comments |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [RSS Configuration](https://github.com/micronaut-projects/micronaut-rss) | 3.0.0-M4 |✅|  |  | `3.0.0-M1` |
| [Views](https://github.com/micronaut-projects/micronaut-views) | 3.0.0-M4 |✳️|  |  | ❗️[#251](https://github.com/micronaut-projects/micronaut-views/pull/251)  |

### Languages

| Module | Micronaut version | Status | Upgrade PR | Issues | Additional comments |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [Groovy](https://github.com/micronaut-projects/micronaut-groovy) | 3.0.0-RC1 |✅|  |  | `3.0.0` |
| [Kotlin](https://github.com/micronaut-projects/micronaut-kotlin) | 3.0.0-M4 |✅|  | https://youtrack.jetbrains.com/issue/KT-47444 | `3.0.0-RC1` |

### Reactive

| Module | Micronaut version | Status | Upgrade PR | Issues | Additional comments |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [Reactor](https://github.com/micronaut-projects/micronaut-reactor) | 3.0.0-M4 |✅|  |  | `2.0.0-M1` |
| [RxJava 2](https://github.com/micronaut-projects/micronaut-rxjava2) | 3.0.0-M4 |✅|  |  | New module targeting Micronaut 3.0 for users that want to keep using RxJava2 with Micronaut 3.x. `1.0.0-M1` |
| [RxJava 3](https://github.com/micronaut-projects/micronaut-rxjava3) | 3.0.0-M4 |✅|  |  | `2.0.0-M1` |

### Misc

| Module | Micronaut version | Status | Upgrade PR | Issues | Additional comments |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [Cache](https://github.com/micronaut-projects/micronaut-cache) | 3.0.0-M3 |✅|  |  | `3.0.0-RC2` |
| [Hibernate Validator](https://github.com/micronaut-projects/micronaut-hibernate-validator) | 2.4.4 |❓|  |  |  |
| [Picocli](https://github.com/micronaut-projects/micronaut-picocli) | 3.0.0-M4 |✅|  |  | `4.0.0-RC1`  |
| [Security](https://github.com/micronaut-projects/micronaut-security) | 3.0.0-M4 |✅|  |  | `3.0.0-M2` |
| [Test](https://github.com/micronaut-projects/micronaut-test) | 3.0.0-M4 |✅|  |  | `3.0.0-RC2` |
| [ACME](https://github.com/micronaut-projects/micronaut-acme) | 2.5.8 |✅|  |  | `3.0.0-RC1` |

### Messaging

| Module | Micronaut version | Status | Upgrade PR | Issues | Additional comments |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [Kafka](https://github.com/micronaut-projects/micronaut-kafka) | 3.0.0-M4 | ✅ |  |  | `4.0.0-RC2` |
| [RabbitMQ](https://github.com/micronaut-projects/micronaut-rabbitmq) | 3.0.0-M4 |✅|  |  | `3.0.0-RC2` |
| [NATS](https://github.com/micronaut-projects/micronaut-nats) | 3.0.0-M4 |✅|  |  | `3.0.0-M2` |
| [MQTT](https://github.com/micronaut-projects/micronaut-mqtt) | 3.0.0-M4 |✅|  |  | `2.0.0-RC1` |
| [JMS](https://github.com/micronaut-projects/micronaut-jms) | 3.0.0-M4 |✅|  |  | `2.0.0-M1` |

### Cloud

| Module | Micronaut version | Status | Upgrade PR | Issues | Additional comments |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [AWS](https://github.com/micronaut-projects/micronaut-aws) | 3.0.0-M4 |✳️  |  |  |❗️Failing Test [#1138)](https://github.com/micronaut-projects/micronaut-aws/pull/1138)|
| [GCP](https://github.com/micronaut-projects/micronaut-gcp) | 3.0.0-M4 |✅|  |  | `4.0.0-RC1` |
| [Azure](https://github.com/micronaut-projects/micronaut-azure) |  3.0.0-M4 |✅|  |  | `3.0.0-M1` |
| [Oracle Cloud](https://github.com/micronaut-projects/micronaut-oracle-cloud) | 3.0.0-M4 |✅|  |  | `2.0.0-RC1` |
| [Discovery Client](https://github.com/micronaut-projects/micronaut-discovery-client) | 3.0.0-M4 |✅|  |  | `3.0.0-M2` |
| [Kubernetes](https://github.com/micronaut-projects/micronaut-kubernetes) | 3.0.0-M5 |✅|  |  |   |

### API

| Module | Micronaut version | Status | Upgrade PR | Issues | Additional comments |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [Servlet](https://github.com/micronaut-projects/micronaut-servlet) | 3.0.0-M4 |✅|  |  | `3.0.0-RC1`  |
| [GRPC](https://github.com/micronaut-projects/micronaut-grpc) | 2.5.7 |  ✅|   |  |  `3.0.0-RC2` |
| [GraphQL](https://github.com/micronaut-projects/micronaut-graphql) | 3.0.0-M4 |✅|  |  | `3.0.0-M1` |
| [JAX-RS](https://github.com/micronaut-projects/micronaut-jaxrs) | 3.0.0-M4 |✅|  |  | `3.0.0-M1` |
| [Jackson XML](https://github.com/micronaut-projects/micronaut-jackson-xml) | 3.0.0-M4 |✅|  |  | `3.0.0-M1` |
| [Open API](https://github.com/micronaut-projects/micronaut-openapi) | 2.5.9 |✅|  |  | `3.0.0` |
| [Spring](https://github.com/micronaut-projects/micronaut-spring) | 3.0.0-M4 |✅|  |  | `4.0.0-RC2` |
| [Multitenancy](https://github.com/micronaut-projects/micronaut-multitenancy) | 2.5.8 |✅|  |  | `4.0.0-M1` |
| [Problem JSON](https://github.com/micronaut-projects/micronaut-problem-json) | 3.0.0-M4 |✅|  |  | `2.0.0-M2` |

### Community & WIP

| Module | Micronaut version | Status | Upgrade PR | Issues | Additional comments |
| :---: | :---: | :---: | :---: | :---: | :---: |
| [Ignite](https://github.com/micronaut-projects/micronaut-ignite) | 2.0.1 |❓|  |  |  |
| [Pulsar](https://github.com/micronaut-projects/micronaut-pulsar) | 2.4.4 |❓|  |  |  |
| [Camel](https://github.com/micronaut-projects/micronaut-camel) | 2.0.2 |❓|  |  |  |
| [Coherence](https://github.com/micronaut-projects/micronaut-coherence) | 2.5.0 |❓|  |  |  |
| [Couchbase](https://github.com/micronaut-projects/micronaut-couchbase) | 2.0.2 |❓|  |  |  |

**Comment by ilopmar** [comment]
@micronaut-projects/core-developers after upgrading all the modules to Micronaut 3.0.0-RC1, the following still fail:

- Servlet: https://github.com/micronaut-projects/micronaut-servlet/pull/230
- Views: https://github.com/micronaut-projects/micronaut-views/pull/278
- RxJava2: https://github.com/micronaut-projects/micronaut-rxjava2/pull/10
- GCP: https://github.com/micronaut-projects/micronaut-gcp/pull/478
- Oracle Cloud: https://github.com/micronaut-projects/micronaut-oracle-cloud/pull/241
- Jax RS: https://github.com/micronaut-projects/micronaut-jaxrs/pull/140
- Jackson XML: https://github.com/micronaut-projects/micronaut-jackson-xml/pull/133
- Spring: https://github.com/micronaut-projects/micronaut-spring/pull/213

I've also upgraded Micrometer but not 100% if that was the proper fix: https://github.com/micronaut-projects/micronaut-micrometer/pull/284

**Comment by sapanparikh18** [comment]
@ilopmar micronaut-coherence seems to be using micronautVersion = '3.0.1' already along with 
Gradle 7.1, and build plugin 4.1.1
