### ISSUE TITLE
Don't use javax.annotation.Nullable warning

### ISSUE THREAD

**Issue by erdinc-gopuff** [micronaut-projects/micronaut-core#5609]
In our project, we are using immutables.org annotation processor.  When a field on a type is declared as Optional, immutables build agent generates some code which has references to the javax.annotation.Nullable annotation. The use of this annotation then results in a compile time warning by the micronaut build agent.

`Usages of deprecated annotation javax.annotation.Nullable found. You should use io.micronaut.core.annotation.Nullable instead.`

Since immutables.org doesn't let us change the annotation it places on the generated code, we end up with so many compile time warnings, which appear to be harmless but is super annoying.

What are our options here? Why is micronaut logging this warning? What's wrong with using javax.annotation.Nullable ?

**Comment by graemerocher** [comment]
See https://github.com/spotbugs/spotbugs/issues/130

**Comment by jameskleeh** [comment]
This is more appropriate for a discussion thread
