### ISSUE TITLE
When injecting a collection of strings, spaces are not trimmed.

### ISSUE THREAD

**Issue by eutkin** [micronaut-projects/micronaut-core#5615]
When we inject a collection of strings from the configuration into a bean, there are spaces in the elements of the collection.

Example:

application.yml
```yml
untrimmed: one, two
```

Bean:

```kotlin
@Singleton
class Test(@Value("\${untrimmed}") val untrimmed : Set<String>)
```

In field of Test contains `one`, ` two`.

### Steps to Reproduce

1. Create application based by Micronaut
2. Put in the `application.yml` property with value `one, two`
3. Inject this value into bean as `Collection<String>`
4. assert second collection element with `two`

### Expected Behaviour

Collection must be contains `one`, `two`

### Actual Behaviour

Collection contains `one`, ` two`

### Environment Information

- **Operating System**: Mac OS
- **Micronaut Version:** 2.5.6
- **JDK Version:** 11

### Example Application

- [Example](https://github.com/eutkin/untrimmed-collection-item)

**Comment by jameskleeh** [comment]
I don't necessarily think we should do this. If you don't want a space don't put one in the config

**Comment by jameskleeh** [comment]
Closing this because we feel the current behavior is a more sensible default

**Comment by sdelamo** [comment]
@eutkin could you use?

```yaml
untrimmed: 
    - one
    - two
```
