### ISSUE TITLE
Websocket regression in 2.5.0, unable to inject WebSocketSession in Tests

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#5618]
It seems there is a regression in Micronaut 2.5.0. Injecting a `WebSocketSession` fails when running the app via `EmbeddedServer`. 

For such as class: 

```java
@ServerWebSocket("/echo")
public class EchoServerWebSocket {
    protected static final Logger LOG = LoggerFactory.getLogger(EchoServerWebSocket.class);
    public static final String JOINED = "joined!";
    public static final String DISCONNECTED = "Disconnected!";

    private final WebSocketBroadcaster broadcaster;

    public EchoServerWebSocket(WebSocketBroadcaster broadcaster) {
        this.broadcaster = broadcaster;
    }

    @OnOpen
    public void onOpen(WebSocketSession session) {
        broadcaster.broadcastSync(JOINED, isValid(session));
```

Starting from 2.5.0 in the test I get: 

```
 - GET /echo (Bad Request): Required argument [WebSocketSession session] not specified
18:58:04.769 [default-nioEventLoopGroup-1-4] TRACE i.m.h.s.netty.RoutingInBoundHandler - Encoding emitted response object [ /session - Required argument [WebSocketSession session] not specified] using codec: io.micronaut.jackson.codec.JsonMediaTypeCodec@792ee3a4
18:58:04.823 [default-nioEventLoopGroup-1-3] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Respo
```

### Steps to Reproduce

- Clone the [sample application repository](https://github.com/grails-core-issues-forks/websockets-issues)
- ./gradlew test

### Expected Behaviour

Tests pass

### Actual Behaviour

Tests fail

If you edit `gradle.properties` to micronaut 2.4.4 the test passes. 

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.5.0
- **JDK Version:** JDK 11

### Example Application

https://github.com/grails-core-issues-forks/websockets-issues

- TODO: link to github repository with example that reproduces the issue

**Comment by jameskleeh** [comment]
I think this is due to https://github.com/micronaut-projects/micronaut-core/issues/5425
