### ISSUE TITLE
NullPointerException NettyServerWebSocketHandler.createWebSocketSession

### ISSUE THREAD

**Issue by bendi** [micronaut-projects/micronaut-core#5620]
Calling `WebsocketSession.getSubprotocol` results in NPE as `handshaker` is set after super constructor is called so `handshaker` is always null in `NettyRxWebSocketSession` inner class.

https://github.com/micronaut-projects/micronaut-core/blob/f183e79e2506d41b035de877c3d95548aadc74d7/http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketHandler.java#L156

**Comment by jameskleeh** [comment]
Do you have an example that can reproduce this? In order for the NPE to occur the `getSubprotocol` method would have to be invoked by the super class and I don't see a reference to it

**Comment by bendi** [comment]
> Do you have an example that can reproduce this? In order for the NPE to occur the `getSubprotocol` method would have to be invoked by the super class and I don't see a reference to it

Is unit test contained in the following gist enough?
https://gist.github.com/bendi/40f4936fb00c0e7117bfeeca78044ee3

Test will pass but you should see error reported to the console, I copy-pasted mine to another gist:
https://gist.github.com/bendi/5221e0f6cafab6d4cb5c0d88e34d8191

**Comment by jameskleeh** [comment]
@bendi Yeah seems reasonable
