### ISSUE TITLE
I want to print all request paths, post request parameters, etc. in micronuat, but when I use a filter to implement it, getBody always outputs empty. Is there any other way to achieve this function?

### ISSUE THREAD

**Issue by chengna106** [micronaut-projects/micronaut-core#5662]
I want to print all request paths, post request parameters, etc. in micronuat, but when I use a filter to implement it, getBody always outputs empty. Is there any other way to achieve this function?

**Comment by vonZeppelin** [comment]
Did you try setting log level of the `org.slf4j.simpleLogger.log.io.micronaut.http` logger to `trace`?

**Comment by chengna106** [comment]
That way can only print out the URL path information, but cannot print out the information of the post request
