### ISSUE TITLE
Why PongWebSocketFrame is never processed as a Message?

### ISSUE THREAD

**Issue by tkgreg** [micronaut-projects/micronaut-core#5680]
I was trying to implement WS ping-pong functionality in case when the server measures the latency between clients(Server send ping and expects pong frame from the client). I need this for detection of stalled connections. Unfortunately, the current implementation does not allow this. It simply ignores the PongWebSocketFrame

https://github.com/micronaut-projects/micronaut-core/blob/a0d5619f6c23d909159503f5ed80d44625e49fe3/http-netty/src/main/java/io/micronaut/http/netty/websocket/AbstractNettyWebSocketHandler.java#L425

What was the reason to implement it like this? Do I try to do something unusual and stupid? 😸

**Comment by graemerocher** [comment]
Seems like an oversight 

PRs welcome

**Comment by tkgreg** [comment]
We already implemented our own ping-pong solution which is not that hard but its nice to have it out of the box.

**Comment by noam-alchemy** [comment]
What's the correct behavior for propagating the pong frame back to the serverside listener?

**Comment by graemerocher** [comment]
@yawkat another one to your list :)

**Comment by yawkat** [comment]
@graemerocher This needs new API for receiving websocket pongs. `javax.websocket` does this by allowing an `@OnMessage` method that accepts a [`PongMessage`](https://docs.oracle.com/javaee/7/api/javax/websocket/PongMessage.html). However this is difficult to implement given our existing `OnMessage` handling that currently only allows one such method. I thought about implementing it as a `WebSocketEvent`, but those are only for the server. What approach is the best, here? I could add a new annotation, but this would diverge further from `javax.websocket`.

**Comment by graemerocher** [comment]
seems like you should be able to define an overridden `@OnMessage` handler that takes `Ping/PongMessage` the `WebSocketBean` API then needs extending to with additional methods like:

```
    /**
     * Returns the method annotated with {@link io.micronaut.websocket.annotation.OnMessage}.
     *
     * @return the method
     */
    Optional<MethodExecutionHandle<T, ?>> pingMethod();

    /**
     * Returns the method annotated with {@link io.micronaut.websocket.annotation.OnMessage}.
     *
     * @return the method
     */
    Optional<MethodExecutionHandle<T, ?>> pongMethod();
```

Which can be disambiguated by the presence of the appropriate argument
