### ISSUE TITLE
UriBuilder changes order of parameters

### ISSUE THREAD

**Issue by chriskosys** [micronaut-projects/micronaut-core#5697]
Version: micronaut-http-client-core-2.4.1

When using UriBuilder to create an URI for RxHttpClient the order of the provided parameters is changed.

To ensure the correct order of the params-Map i used an LinkedHashMap.
`		UriBuilder uriBuilder = UriBuilder.of("/api/v1").path("secretendpoint");
		for (String paramKey : params.keySet()) {
			uriBuilder = uriBuilder.queryParam(paramKey, params.get(paramKey));
		`}``

Even when using an template like "api/v1/secretendpoint?key={key}&timestamp={timestamp}&signature={signature}"
the order is changed in the resulting URI. This makes the request invalid e.g. when using the binance API.
It looks like the parameters are ordered alphabetically.

As a workaround i am forced to build and encode Uri-String by myself. Which feels a bit like an error-prone approach...

**Comment by jameskleeh** [comment]
Are you sure `params` is a `LinkedHashMap`?

**Comment by jameskleeh** [comment]
I added a test to assert the behavior works as expected. If you can produce an example application that reproduces the issue I'll reopen this.

**Comment by chriskosys** [comment]
I just tested it again with following code.

```
Map<String, String> params = new LinkedHashMap<>();
params.put("t_param", "t_value");
params.put("s_param", "s_value");
params.put("a_param", "a_value");

UriBuilder uriBuilder = UriBuilder.of("/api").path("v1").path("secretendpoint");
for (String paramKey : params.keySet()) {
	uriBuilder = uriBuilder.queryParam(paramKey, params.get(paramKey));
}
System.out.println(uriBuilder.build().toString());
```
UriBuilder created following url:

> /api/v1/secretendpoint?s_param=s_value&t_param=t_value&a_param=a_value

i hope that example is sufficient to reproduce the issue. or do i miss something?

**Comment by jameskleeh** [comment]
@chriskosys Thanks - I see the issue
