### ISSUE TITLE
Feature: Environment Name aware PropertySources

### ISSUE THREAD

**Issue by cemo** [micronaut-projects/micronaut-core#5701]
> Properties are resolved ahead of time from the environment, be it a YAML, JSON, ENV or a backend config client such as configmaps or vault. But the framework loads all the keys ahead of time. 

We would like to add some extra `propertysources` which are aware of `Environment`. This is important because we can load different properties from different sources in different environments.

For example: in our case we would like to load my-system-prod or my-system-test properties but this is not easy not by their configuration. I need to set some environment variables etc. 

Is it possible to support environment names aware propertysources?

**Comment by jameskleeh** [comment]
Is the config in files or dynamic?

**Comment by cemo** [comment]
Config is partially dynamic. We would like to use Azure Key Vault as a PropertySource but its name must be dynamic and configured somehow.

**Comment by jameskleeh** [comment]
Sounds like you want a custom `ConfigurationClient`

**Comment by cemo** [comment]
Would you please help me to find my way? I can contribute to documentation as well after it.

**Comment by jameskleeh** [comment]
You can look at any of the existing implementations to get inspiration to write an integration with Azure Key Vault. See https://github.com/micronaut-projects/micronaut-discovery-client/tree/master/discovery-client/src/main/java/io/micronaut/discovery. 

If you want to write it generically to work for all users and follow the standards we already have set, PRs are welcome

**Comment by jameskleeh** [comment]
Please use the github discussions or gitter to get further support
