### ISSUE TITLE
Not able to inject byte array created by factory

### ISSUE THREAD

**Issue by auke-** [micronaut-projects/micronaut-core#5708]
I'm currently unable to inject a byte array created by a factory. It seems like the BeanDefinition and BeanDefinitionReference classes aren't generated for factory methods which return an array.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem ~~uploaded to Github~~
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a `@Factory` annotated class with a method which returns an array, e.g. a byte array
2. Inject the array into a bean
3. Compile the application
4. Note that the BeanDefinition and BeanDefinitionReference classes are missing and the injection will fail

### Expected Behaviour

We should be able to create arrays such as byte arrays in factory methods and use them for injection

### Actual Behaviour

The factory methods which return an array are ignored and thus injection of the arrays fails

### Environment Information

- **Operating System**: MacOS 10.15.7
- **Micronaut Version:** 2.5.7
- **JDK Version:** OpenJDK 11.0.11

### Example Application

```
import io.micronaut.context.annotation.Bean;
import io.micronaut.context.annotation.Factory;

import javax.inject.Named;
import java.nio.ByteBuffer;
import java.util.Collections;
import java.util.List;

@Factory
public class ByteFactory {

  // Generates $ByteFactory$CreateByteBuffer0Definition and $ByteFactory$CreateByteBuffer0DefinitionClass
  @Bean @Named("my-byte-buffer")
  public ByteBuffer createByteBuffer() {
    return ByteBuffer.allocate(0);
  }

  // Is ignored, no BeanDefinition or BeanDefinitionReference generated
  @Bean @Named("my-byte-array")
  public byte[] createByteArray() {
    return new byte[0];
  }
}
```

**Comment by jameskleeh** [comment]
I don't think this is feasible to support. Even in Micronaut 3 where you can return a collection it would result in multiple beans being created. I think even if we supported arrays it should result in multiple `byte` beans being created and not a single byte array. 

@graemerocher Do you agree?

**Comment by auke-** [comment]
Okay, but the `BeanContext` itself seems to support arrays:
```
    BeanContext context = new DefaultBeanContext();

    context.registerSingleton(
        byte[].class,
        "some-value".getBytes(StandardCharsets.UTF_8),
        Qualifiers.byName("my-byte-array"));

    ...

   byte[] myByteArray = context.getBean(byte[].class, Qualifiers.byName("my-byte-array"));
```

So it looks like a restriction of the factories.

**Comment by graemerocher** [comment]
Seems an unusual use case. I guess we could special case primitive arrays and make them beans. I don't see how having each byte be a bean would ever be useful.

**Comment by auke-** [comment]
Just to be clear, my use case is to be able to inject a bytearray with a specific qualifier. I agree that injecting individual bytes from an array seems pretty unusual and that would be unexpected behavior for me.

**Comment by jameskleeh** [comment]
I agree I was just trying to outlay what would happen if we applied the same logic as we do for collections

**Comment by graemerocher** [comment]
Supported in 3.1
