### ISSUE TITLE
Controller return type of Single<HttpResponse<Flowable<byte[]>>> is transformed to JSON

### ISSUE THREAD

**Issue by martijndwars** [micronaut-projects/micronaut-core#5741]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a Micronaut project (2.5.8) with the following controller:

```
package micronaut.bug.controller;

import io.micronaut.http.HttpResponse;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.reactivex.Flowable;
import io.reactivex.Single;

@Controller("/hello")
public class HelloController {

  @Get("/a")
  public HttpResponse<Flowable<byte[]>> a() {
    return HttpResponse.ok().body(Flowable.just("a".getBytes(), "b".getBytes()));
  }

  @Get("/b")
  public Single<HttpResponse<Flowable<byte[]>>> b() {
    return Single.just(HttpResponse.ok().body(Flowable.just("a".getBytes(), "b".getBytes())));
  }
}
```
2. Invoke the endpoint: `curl http://localhost:8080/hello/a`
3. Observe the response: `ab`
4. Invoke the endpoint: `curl http://localhost:8080/hello/b`
5. Observe the response: `[a,b]`

### Expected Behaviour

The second endpoint should reply with `ab`, just like the first endpoint.

### Actual Behaviour

The response of the second endpoint is `[a,b]`. Micronaut incorrectly considers the method's return type  as "JSON formattable", and as a consequence Micronaut adds JSON separators (opening bracket, comma, closing bracket).

Note that this problem does not occur if the return type is `HttpResponse<Flowable<byte[]>>`. The [`isJsonFormattable`](https://github.com/micronaut-projects/micronaut-core/blob/d081dce9c21a95b7fd336ecb148ba0751c51d819/http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java#L786-L794) method is the culprit here, as it does not take this deep(er) nesting in the type into consideration.

A simple fix would be to change the method as follows:

```diff
     private boolean isJsonFormattable(Argument<?> argument) {
-        Class<?> javaType = argument.getType();
-        if (Publishers.isConvertibleToPublisher(javaType)) {
-            javaType = argument.getFirstTypeVariable().orElse(Argument.OBJECT_ARGUMENT).getType();
+        // If the type is a HttpResponse<T>, unwrap the HttpResponse
+        if (HttpResponse.class.isAssignableFrom(argument.getType())) {
+            argument = argument.getFirstTypeVariable().orElse(Argument.OBJECT_ARGUMENT);
+        }
+        // If the type is a reactive type, unwrap the reactive type
+        if (Publishers.isConvertibleToPublisher(argument.getType())) {
+            argument = argument.getFirstTypeVariable().orElse(Argument.OBJECT_ARGUMENT);
         }
+        Class<?> javaType = argument.getType();
+        // If what's left is a byte[], ByteBuffer, or ByteBuf, then the type is NOT JSON formattable.
         return !(javaType == byte[].class
                 || ByteBuffer.class.isAssignableFrom(javaType)
                 || ByteBuf.class.isAssignableFrom(javaType));
    }
```

### Environment Information

- **Operating System**: macOS Catalina (version 10.15.7)
- **Micronaut Version:** 2.5.8
- **JDK Version:** Java HotSpot, 1.8.0_281

### Similar Issues

Somewhat related issues:

* https://github.com/micronaut-projects/micronaut-core/issues/3095: A regression with a similar type.
* https://github.com/micronaut-projects/micronaut-core/issues/734: Basically the same bug. This was fixed and tests were added for type `HttpResponse<Flowable<String>> `, but the bug still exists for `Single<HttpResponse<Flowable<String>>>`.

**Comment by martijndwars** [comment]
Happy to work on a PR if I can get a confirmation that it's indeed a bug.

**Comment by graemerocher** [comment]
@martijndwars PRs welcome! :)

**Comment by jameskleeh** [comment]
This is related to other issues. This isn't a bug but simply not a supported use case as of today. Currently we support either a publisher as the body or a publisher of the response, but not both.

**Comment by martijndwars** [comment]
I see. My use case is similar to the use case in #734: I'm using Micronaut to proxy a request from an end-user to an origin server. I use `Single<HttpResponse>` because I don't want to block while proxying the request, and I use `HttpResponse<Flowable<byte[]>>` because I want to stream chunks of the body to the client as they come in from the origin server instead of buffering the whole response on the server.

Is there another way to satisfy my use case without using the `Single<HttpResponse<Flowable<byte[]>>>` type? If not, would it be an idea to add this as a potential future feature? I'd be happy to take this into a larger context if you can expand on the other issues that this relates to.

**Comment by graemerocher** [comment]
Have you tried https://docs.micronaut.io/latest/guide/#proxyClient

**Comment by jameskleeh** [comment]
This is fixed in the latest snapshot as part of the filter refactor

**Comment by awesomekosm** [comment]
> Have you tried https://docs.micronaut.io/latest/guide/#proxyClient

What about taking advantage about controller security, principal, query/path params? All of this goes away at filter doesn't it?

**Comment by jameskleeh** [comment]
@Z-EMB No. You can have your filter execute after the security filter and thus have access to the principal and all filters have access to the path and query params

**Comment by awesomekosm** [comment]
Okay, I guess I would have to do all the validation in the filter instead of conveniences of a controller.
```java
    @Secured(SecurityRule.IS_AUTHENTICATED)
    @Get(value = "/download/{name}", consumes = MediaType.TEXT_PLAIN, produces = MediaType.APPLICATION_OCTET_STREAM)
    Single<HttpResponse> download(@Nullable Principal principal, @Size(max = 64) @NotBlank String name) {
```

**Comment by jameskleeh** [comment]
The proxy client should work in a controller in the next release (3.1.1)
