### ISSUE TITLE
Cookie secure affecting localhost

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#5744]
There is a breaking change in Micronaut 3.0 regarding cookie secure:

> Cookie Secure Configuration
> Previously the secure configuration for cookies was only respected if the request was determined to be sent over https. Due > to a number of factors including proxies, HTTPS requests can be presented to the server as if they are HTTP. In those cases > the setting was not having any effect. The setting is now respected regardless of the status of the request. If the setting is > not set, cookies will be secure if the request is determined to be HTTPS.

However, secure should not affect localhost. 

[Restrict access to cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies)

> A cookie with the Secure attribute is sent to the server only with an encrypted request over the HTTPS protocol, never with unsecured HTTP (**except on localhost**)

Because currently it affects localhost, users need to change their local development and tests to adjust. See sample PR in Micronaut guides 

https://github.com/micronaut-projects/micronaut-guides/pull/362

**Comment by jameskleeh** [comment]
The thing to do here is change the configuration source to not provide a default value for cookie isSecure

**Comment by sdelamo** [comment]
we have [changed the setting's default value in Micronaut Security](https://github.com/micronaut-projects/micronaut-security/pull/739)
