### ISSUE TITLE
Regression with 2.5.9 and static resources in GraalVM

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#5765]
This commit (https://github.com/micronaut-projects/micronaut-core/commit/a0cfeb13bf1ef5d692d16d4a3b91b34b7456bb11) has broken static resource support for GraalVM in Micronaut 2.5.9. It works properly using the JVM.

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-views-graal`
- `cd micronaut-views-graal`
- `git checkout issue-static-resources-259`
- `sdk use java 21.1.0.r11-grl`
- `./gradlew nativeImage`
- `build/native-image/views-velocity`

Send the following curl requests:
- `curl localhost:8080`
- `curl localhost:8080/folder1/link1.html`

### Expected Behaviour

Both `curl` requests should return HTML.

### Actual Behaviour

They both return 404.

### Environment Information

- **Operating System**: Linux Mint 20.1
- **Micronaut Version:** 2.5.9
- **JDK Version:** Jdk 11

**Comment by graemerocher** [comment]
Seems on GraalVM directories are not returned even if files within the directory are included in the resource config 😕

This call returns `null` https://github.com/micronaut-projects/micronaut-core/blob/89c6a67478576e747339f2e9cb0737405e1557e9/core/src/main/java/io/micronaut/core/io/scan/DefaultClassPathResourceLoader.java#L70

**Comment by ilopmar** [comment]
As discussed during the engineering meeting I've tried adding the root directory to the resources file like (also tried with an additional `/`:

```json
{
  "resources": [
    {
      "pattern": "\\Qpublic\\E"
    }
  ]
}
```

But it doesn't work.

For context, this is the `resource-config.json` file generated that worked before the change:

```json
{
  "resources" : [ {
    "pattern" : "\\Qlogback.xml\\E"
  }, {
    "pattern" : "\\Qpublic/folder1/link1.html\\E"
  }, {
    "pattern" : "\\Qpublic/index.html\\E"
  }, {
    "pattern" : "\\Qviews/dir/home.html\\E"
  }, {
    "pattern" : "\\Qviews/velocity/home.vm\\E"
  }, {
    "pattern" : "\\Qpublic/images/micronaut_mini_copy_tm.svg\\E"
  }, {
    "pattern" : "\\Qapplication.yml\\E"
  } ]
}
```

**Comment by graemerocher** [comment]
have you tried

```json
{
  {
    "pattern" : "\\Qpublic/\\E"
  }
}
```

**Comment by ilopmar** [comment]
Yes, also tried that

**Comment by ilopmar** [comment]
I've just tried with 21.2.0-dev just in case but it doesn't work either

**Comment by graemerocher** [comment]
I am investigating a solution with the GraalVM folks

**Comment by ilopmar** [comment]
I haven't realized until today that another app failed on CI. This also breaks OpenAPI because everything (html, yaml,...) are exposed as static resources.

**Comment by graemerocher** [comment]
@ilopmar FYI the inability to register directories was identified as an issue https://github.com/oracle/graal/pull/3597

Once merged we would need to add the directories within resources as well to the resource config to the graal visitor and for newer version to the gradle / maven plugins. /cc @melix 

As a shorter term workaround for Micronaut we could alter the fix to just bar using "../" in path definitions all together. However this is not as safe. thoughts @jameskleeh ?

**Comment by ilopmar** [comment]
I've tried compiling GraalVM from the branch in that PR and I confirm that fixes the issue (after manually register the directory in resource config).

**Comment by jameskleeh** [comment]
I’m fine with blocking usage of ../

**Comment by graemerocher** [comment]
@jameskleeh I afraid that is not good enough, since paths like `classpath:/other/../../other/shouldNotAccess.txt` could still be crafted
