### ISSUE TITLE
Upgrade/Fix GraalVM test apps to Micronaut 3

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#5771]
Epic issue (that will be updated) to keep track of the pending fixes/upgrades needed by the GraalVM test applications so everything works with Micronaut 3.

CI: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/pipelines?page=1&scope=all&ref=3.0.x-stable.

Apps not listed here work without problems

### Views

Handlebars fails: https://github.com/micronaut-projects/micronaut-views/issues/252.

### Service Discovery Eureka

Fails also in JIT mode: https://github.com/micronaut-projects/micronaut-core/issues/5882

**Comment by graemerocher** [comment]
I don’t think we need a version of cache compiled with 3.0 we just need to switch it to reactor

**Comment by ilopmar** [comment]
> I don’t think we need a version of cache compiled with 3.0 we just need to switch it to reactor

I've updated the issue with your comment.

I'll keep updating this issue with new apps as I "process" them.

**Comment by ilopmar** [comment]
Please be aware that there are still two applications failing: view-handlebars and service discovery with Eureka

**Comment by ilopmar** [comment]
Service discovery Eureka #5882 and Views-Handlebars https://github.com/micronaut-projects/micronaut-views/issues/252 still doesn't work, but I agree we can close this.
