### ISSUE TITLE
Map keys converted to camelCase in nested @ConfigurationProperties

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-core#5778]
I have a class annotated with @ConfigurationProperties and some nested configuration classes.
One property has a Map of bucket names and is annotated with @MapFormat. The problem is that the keys in the map are converted to camelCase. I want them to be exactly as specified in the configuration file. Specifying `keyFormat = StringConvention.RAW` does not help here.
```
storage:
  providers:
    test:
      name: S3
      buckets:
        default: "The default bucket"
        testBucket1: "Bucket without hyphens"
        test-bucket-2: "Some hyphenated bucket"
        test-bucket-3: "Another hyphenated bucket"
```
I have some similar configuration classes with Map and @MapFormat in the top-level configuration class, and they work ok. The difference here is that the Map is in a nested configuration class (static inner class).

### Steps to Reproduce

1. Create a class and annotate it with @ConfigurationsProperties
2. Create a static inner class annotated with @ConfigurationsProperties
3. Add a Map<String, SomePOJO> to the inner class
4. Add properties to application.yml with keys containing hyphens (-)
5. Debug the application and inspect the instantiated configuration. The map keys are camelCase, not hyphenated as they were in the configuration file.

### Expected Behaviour

Map keys should be preserved as they are written i the configuration file.

### Actual Behaviour

Keys are camelCase -> **test-bucket-1** becomes **testBucket1**

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.5.9
- **JDK Version:** 11.0.11

### Example Application

- https://github.com/goeh/mapformat-raw-issue

Set a breakpoint in AppConfig.ProviderConfig#setBuckets(Map<String, String> buckets).

**Comment by goeh** [comment]
I added a workaround using `NameUtils.camelCase()` in my configuration class. This covers my use-case, so this issue is not a blocker for me anymore.
```
@ConfigurationProperties(BucketConfigurationProperties.PREFIX)
public static class BucketConfigurationProperties {

    public static final String PREFIX = "bucket";

    private String name;

    @MapFormat(transformation = MapFormat.MapTransformation.FLAT, keyFormat = StringConvention.RAW)
    protected Map<String, String> alias = new HashMap<>();

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Map<String, String> getAlias() {
        return alias;
    }

    // See https://github.com/micronaut-projects/micronaut-core/issues/5778
    public void setAlias(@MapFormat(transformation = MapFormat.MapTransformation.FLAT, keyFormat = StringConvention.RAW) Map<String, String> alias) {
        this.alias = alias;
    }

    public Optional<String> getAlias(String name) {
        return Optional.ofNullable(alias.get(name))
                // Workaround for https://github.com/micronaut-projects/micronaut-core/issues/5778
                .or(() -> Optional.ofNullable(alias.get(NameUtils.camelCase(name))));
    }
}
```

**Comment by goeh** [comment]
Related issue: https://github.com/micronaut-projects/micronaut-core/issues/4308

**Comment by jameskleeh** [comment]
As the issue you linked suggests, the annotation has to be on the setter argument. Your config class should look like this:

```
@ConfigurationProperties("storage")
public class AppConfig {

    Map<String, ProviderConfig> providers;

    AppConfig(List<ProviderConfig> providers) {
        this.providers = new LinkedHashMap<>(providers.size());
        for (ProviderConfig config: providers) {
            this.providers.put(config.getName(), config);
        }
    }

    public Optional<ProviderConfig> getProvider(String name) {
        return Optional.ofNullable(this.providers.get(name));
    }

    @EachProperty("providers")
    public static class ProviderConfig {

        private String name;
        private Map<String, String> buckets = new HashMap<>();

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        public Map<String, String> getBuckets() {
            return buckets;
        }

        public void setBuckets(@MapFormat(transformation = MapFormat.MapTransformation.FLAT, keyFormat = StringConvention.RAW) Map<String, String> buckets) {
            this.buckets = buckets;
        }

        public Optional<String> getBucket(String name) {
            return Optional.ofNullable(this.buckets.get(name));
        }
    }
}
```

**Comment by jameskleeh** [comment]
Also you can remove one level from your config

```
storage:
  providers:
    test:
      name: S3
```

The `test` there doesn't seem to be serving any purpose. You can replace that with `S3` and retrieve it in the constructor of ProviderConfig:

```
class ProviderConfig {
    ProviderConfig(@Parameter String name) {}
```
