### ISSUE TITLE
Broken documentation in configuration reference to  DefaultTrustStoreConfiguration

### ISSUE THREAD

**Issue by pgressa** [micronaut-projects/micronaut-core#5793]
in the reference doc https://docs.micronaut.io/latest/guide/configurationreference.html

**Comment by jameskleeh** [comment]
@sdelamo Were you able to track this down?

**Comment by ilopmar** [comment]
I think the problem is fixed in the build plugins 4.0.1 version.

**Comment by sdelamo** [comment]
I added this fix to 4.0.1 https://github.com/micronaut-projects/micronaut-build/pull/182
