### ISSUE TITLE
Support for regexes in @Filter for HttpServerFilter

### ISSUE THREAD

**Issue by racevedoo** [micronaut-projects/micronaut-core#5842]
Hi all!

When using `@Filter` annotations with `HttpServerFilter`, currently the `pattern` attribute only supports Ant-style patterns. Because of it, we can't use more complicated patterns (using regex, for example). A simple case that regex can support but Ant can't is accepting all paths except one.

This question was raised on gitter (discussed briefly with @jameskleeh), and I suggested that we support something like `@Filter(pattern="/mypath", patternStyle=ANT)` or `@Filter(pattern="/mypath", patternStyle=REGEX)`, with the default being Ant, to avoid breaking changes.

One thing to note is that using regexes is less performant than using Ant-style patterns. This should be communicated properly to users.

If this is fine, I can come up with a PR.

### Expected Behaviour

Micronaut should support more complex patterns for `@Filter`

### Actual Behaviour

Micronaut only supports simple Ant-style patterns for `@Filter`

**Comment by jameskleeh** [comment]
@racevedoo Proposal looks good! PR welcome

**Comment by racevedoo** [comment]
Merged into 3.1.x
