### ISSUE TITLE
Improvements to ViewsRenderer

### ISSUE THREAD

**Issue by RyanHoldren** [micronaut-projects/micronaut-core#585]
I am trying to make use of `ViewsRenderer` in my project and have a few suggestions for improvement:

1. If `render()` returned a `Streamable` instead of a `Writable`, it would be usable for binary formats (in my case PDF).
2. If the class were generic - `ViewsRenderer<T>` instead of `ViewsRenderer` - it would safer to write implementations that could only render certain kinds of data (i.e. `T data` instead of `Object data`).

I believe both of these changes could be made without breaking backwards compatibility.

**Comment by sdelamo** [comment]
Thanks for the feedback @RyanHoldren 

Do you have a code snippet of a method which generates a PDF in a `Streamable`?. The simpler the better. I would like to create a test and incorporate that option.

**Comment by RyanHoldren** [comment]
The way I am doing it is not simple at all, unfortunately. I am using XSLT and Apache FOP. There are quite a few services and moving parts, I don't think it would make a very good test.

**Comment by jameskleeh** [comment]
@RyanHoldren @sdelamo Why should the `ViewsRenderer` support binary formats? You can send PDFs back with the `StreamedFile`/`AttachedFile` classes

**Comment by jameskleeh** [comment]
Closing this due to lack of feedback
