### ISSUE TITLE
Compilation error with Micronaut OpenAPI and Micronaut 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#5856]
The GraalVM basic-app fails to compile when using Micronaut Openapi module. The module has been upgraded to be Micronaut 3 compatible although it uses Micronaut 2.5.9 for compilation.
I've tried to upgrade the module to use Micronaut 3.0.0-M4 and the error is the same.

Using Micronaut 3.0.0-SNAPSHOT in the module leads to a compilation error because of this new `isTypeVariable` added here https://github.com/micronaut-projects/micronaut-core/blob/dd97ba711de48d005ef7751a08e041e82218c3b9/inject/java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java#L101 and introduced in this PR https://github.com/micronaut-projects/micronaut-core/commit/dd97ba711de48d005ef7751a08e041e82218c3b9

### Steps to Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-basic-app`
- `cd micronaut-basic-app`
- `git checkout openapi-compilation-error`
- `./gradlew run`

### Expected Behaviour

The application should start

### Actual Behaviour

The application fails during compilation with:

```
Execution failed for task ':compileJava'.
> java.lang.NoSuchMethodError: io.micronaut.annotation.processing.visitor.JavaClassElement.<init>(Ljavax/lang/model/element/TypeElement;Lio/micronaut/core/annotation/AnnotationMetadata;Lio/micronaut/annotation/processing/visitor/JavaVisitorContext;Ljava/util/Map;I)V
```

### Environment Information

- **Operating System**: Linux Mint 20.1
- **Micronaut Version:** 3.0.0-SNAPSHOT
- **JDK Version:** 8

**Comment by ilopmar** [comment]
Using Micronaut `3.0.0-SNAPSHOT` in openapi and adding here https://github.com/micronaut-projects/micronaut-openapi/blob/049dadca805669a4ba8af28f6aa05791b0d83bfc/openapi/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElementExt.java#L69 a new parameter `false` makes everything work.

**Comment by graemerocher** [comment]
the impl really shouldn't be using these internal classes

**Comment by ilopmar** [comment]
I didn't wrote the original class in openapi https://github.com/micronaut-projects/micronaut-openapi/blob/fa48463090a09205979e44769df032a6c959e340/openapi/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElementExt.java

So what would be your suggested approach?

**Comment by graemerocher** [comment]
probably too late now, we will have to fix it but at some point we need to implement whatever features are needed that required subclassing that internal class since it is java specific and doesn't work for Groovy
