### ISSUE TITLE
3.0.0 M5 - request context lost when using Reactor types with @Cacheable and Redis

### ISSUE THREAD

**Issue by zdegner** [micronaut-projects/micronaut-core#5905]
### Expected Behavior

Server request context should still be available to consumers after using `@Cacheable` annotation with Project Reactor types. 

This appears to be a regression from 2.x where the context was still available. I noticed this change while updating a large-ish 2.x project to 3.0.0 M5. We have a MethodInterceptor which uses some cached values and it now causes the thread to be changed.

### Actual Behaviour

Server context is no longer available when handling results from @Cacheable. The thread appears to have changed to the lettuce thread pool.

### Steps To Reproduce

Start redis: `docker run --rm --name my-redis -p 6379:6379 -d redis`
Run unit tests and examine results.
Stop redis `docker stop my-redis`

Results:
"request is NOT present:lettuce-nioEventLoop-5-1"

### Environment Information

Windows 10
Java 11

### Example Application

https://github.com/zdegner/300m4-redis-threading

### Version

3.0.0 M5

**Comment by sdelamo** [comment]
@zdegner 

adding the micronaut-reactor dependency: 

``` implementation("io.micronaut.reactor:micronaut-reactor")
```

and commenting out the redis part: 

```
#
  #redis:
    ##uri: redis://localhost
    #caches:
      #sample-cache:
#expire-after-write: 5m
```
will make your test pass.

**Comment by sdelamo** [comment]
The sample app fails also for 2.5.11. I have pushed a 2.5.11 sample app here: 

https://github.com/grails-core-issues-forks/issue-5905-micronaut-2

**Comment by graemerocher** [comment]
As I mentioned we should make the request available within the Reactor context and document how to retrieve it for Reactor users

**Comment by jameskleeh** [comment]
The request is now available in the reactor context via `HttpRequest.KEY`
