### ISSUE TITLE
Micronaut 2.5.10, 11 Conflict with Azure App Config Lib

### ISSUE THREAD

**Issue by LPalmerMSI** [micronaut-projects/micronaut-core#5920]
### Expected Behavior

When including the Azure App Configuration Library in Gradle, the HttpClient should not throw exceptions.

Azure App Configuration Lib:
```
implementation ("com.azure:azure-data-appconfiguration:1.2.0")
```

Note: I've tried multiple versions of the azure lib. 

### Actual Behaviour

When including the library I get the following exception when trying to inject an HttpClient:

```
Error instantiating bean of type  [com.msi.nitro.nbi.controller.TestClientApiController]

Message: io/netty/internal/tcnative/AsyncSSLPrivateKeyMethod
Path Taken: TestClientApiController.setHttpClient([HttpClient httpClient])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [com.msi.nitro.nbi.controller.TestClientApiController]
```

### Steps To Reproduce

* Create a launch Micronaut application with 2.5.10 or greater (tested up to 11)
* Add the azure app config library
* Create a test controller 
* Create a test which uses HttpClient injected into the test class (I used Spock)
* Try to run the test.  The test client will crash with the above exception. 

### Environment Information

Windows 10
JDK 11

### Version

2.5.11

**Comment by rawilder** [comment]
It was happening with my tests as well. I tracked it down to azure-messaging-servicebus:7.3.0 -> com.azure:azure-core:1.18.0 -> netty-tcnative-boringssl-static:2.0.39.Final. AsyncSSLPrivateKeyMethod seems to be in 2.0.40.Final.

**Comment by mattmoss** [comment]
Workaround. B/C `AsyncSSLPrivateKeyMethod` is missing in `2.0.39.Final`, require the `2.0.40.Final` version in your `build.gradle` file:

```
    implementation("io.netty:netty-tcnative-boringssl-static") {
        version {
            require "2.0.40.Final"
        }
    }
```

**Comment by mattmoss** [comment]
Another option: set system property `io.netty.handler.ssl.noOpenSsl` to `true` . Micronaut will then use the JDK's SSL client context rather than Netty's OpenSSL client context.

**Comment by jameskleeh** [comment]
The responsibility of what tc-native works with netty-handler should be on Netty. I've created an issue to request them to add the tc-native to the bom (which we import). 

https://github.com/netty/netty/issues/11567

**Comment by jameskleeh** [comment]
Going to close this as its out of our hands
