### ISSUE TITLE
EventListener problem

### ISSUE THREAD

**Issue by cupkooo** [micronaut-projects/micronaut-core#5972]
### Issue description

I have the following issue with Eventlistener:

when a method is annotated with  `@EventListener` and the class where the method is defined is in the root dir of the project everything works just fine (eg. package com.example;). 
When I move the class to some other subfolder (eg. package com.example.Utils) following errors start appearing: Error starting Micronaut server: Failed to load a service: Unexpected error loading bean definition  ... .

Is it possible that all classes with `@EventListener` annotation must be in the root dir of the project together with the main  Application class, or I am doing something wrong?

Example class:

```
package com.example;

import com.example.AppContext.Events.SmartCardStatusResponsePojo;
import com.example.RestHandlers.Vpin.VerifyPinPojo;
import io.micronaut.runtime.event.annotation.EventListener;
import io.micronaut.scheduling.annotation.Async;
import org.jetbrains.annotations.NotNull;

import javax.inject.Singleton;

@Singleton
public class AppContextTest {

    @EventListener
    @Async
    public void onPinEvent(VerifyPinEvent event) {

        System.out.println("Event pin");

    }

    @EventListener
    @Async
    public void onEvent(@NotNull SmartCardStatusResponseEvent event) {
        System.out.println("Event: " + event.isScPresent());
    }

}
```

**Comment by burtbeckwith** [comment]
It's probably caused by capitalized parts of the package name. Package names should be lowercase.

**Comment by cupkooo** [comment]
Yes, that was a problem. Working like a charm now.

Thanks!
