### ISSUE TITLE
@Factory annotation broken in Modular app in Micronaut 3.0.0-M3 and later 

### ISSUE THREAD

**Issue by msgilligan** [micronaut-projects/micronaut-core#5985]
### Expected Behavior

The following simple **modular** application should run without error:

```
import io.micronaut.context.BeanContext;
import io.micronaut.context.annotation.Factory;

@Factory
public class MinimalApp {

    public static void main(String[] args) {
        BeanContext context = BeanContext.run();
        context.getBean(MinimalApp.class);
    }
}

```

### Actual Behaviour

```
 io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [app.supernaut.fx.sample.minimal.MinimalApp] exists.
```

### Steps To Reproduce

`./gradlew run`

I can send the Gradle build (currently part of a multi project, but I could break it out into a separate build and/or Github repo is you need)

Note that any one of the following changes will eliminate the problem:

1. Switch to Micronaut 3.0.0-M2 or earlier
2. Replace `@Factory` annotation with `@Singleton`
3. Remove the `module-info.java` file and Gradle Modularity Plugin configuration

### Environment Information

* macOS Big Sur
* OpenJDK Runtime Environment Temurin-16.0.2+7 (build 16.0.2+7)
* Modular Java Application
* Micronaut 3.0.0-M3 through 3.0.0-RC1

### Version

3.0.0-M3 or later

**Comment by jeffscottbrown** [comment]
See the project at https://github.com/jeffbrown/issue5985.

[src/main/java/issue5985/MinimalApp.java](https://github.com/jeffbrown/issue5985/blob/89a115c3a2a89976fe8784b3ff5e92793634106a/src/main/java/issue5985/MinimalApp.java)

```
package issue5985;

import io.micronaut.context.BeanContext;
import io.micronaut.context.annotation.Factory;

@Factory
public class MinimalApp {

    public static void main(String[] args) {
        BeanContext context = BeanContext.run();
        context.getBean(MinimalApp.class);
    }
}

```

```
~ $ git clone git@github.com:jeffbrown/issue5985.git
Cloning into 'issue5985'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 26 (delta 0), reused 26 (delta 0), pack-reused 0
Receiving objects: 100% (26/26), 58.81 KiB | 1.09 MiB/s, done.
~ $ 
~ $ cd issue5985 
issue5985 (main)$ 
issue5985 (main)$ cat src/main/java/issue5985/MinimalApp.java 
package issue5985;

import io.micronaut.context.BeanContext;
import io.micronaut.context.annotation.Factory;

@Factory
public class MinimalApp {

    public static void main(String[] args) {
        BeanContext context = BeanContext.run();
        context.getBean(MinimalApp.class);
    }
}
issue5985 (main)$ 
issue5985 (main)$ ./gradlew run

> Task :compileJava
Note: Creating bean classes for 1 type elements

BUILD SUCCESSFUL in 7s
3 actionable tasks: 3 executed
```

@msgilligan Does that sample project yield the error when run in your environment?

**Comment by jeffscottbrown** [comment]
FYI... https://github.com/jeffbrown/issue5985/commit/31d9f1305e0b0833f8dd092d7b64f092128ff9cf moves the relevant code into a submodule.

**Comment by msgilligan** [comment]
@jeffbrown Thanks for looking at it. I'll give it a try and if it doesn't yield the error, I'll try to make a PR with changes to produce it.

**Comment by msgilligan** [comment]
@jeffbrown Those weren't the (JPMS) modules we were looking for. Here's a PR that adds them:
https://github.com/jeffbrown/issue5985/pull/1

With the PR the problem can be reproduced with `./gradlew run` and changing from `@Factory` to `@Singleton` makes it work again.

**Comment by msgilligan** [comment]
I pushed two more commits to my PR (https://github.com/jeffbrown/issue5985/pull/1):

* https://github.com/jeffbrown/issue5985/pull/1/commits/b894c321d5beb427d9cce9b805e53bdc3b784806 -- Fixes  `./gradlew test` -- in part by **running on the class path**
* https://github.com/jeffbrown/issue5985/pull/1/commits/a8b42487e1a5b1a42ab1b21eb74fa7293b0ccdf6 -- Bump to Micronaut 3.0.0 (GA version)

Note that we might want to consider re-opening https://github.com/micronaut-projects/micronaut-test/issues/33 now that JDK 11 and modules are much more common (and JDK 17 is coming very soon.)

**Comment by msgilligan** [comment]
@jeffbrown Have you had a chance to take a look at my additional commits in your test repo?

**Comment by msgilligan** [comment]
Confirmed this is still failing in Micronaut 3.0.3.

**Comment by msgilligan** [comment]
@graemerocher I see this was added to the [3.0.4](https://github.com/micronaut-projects/micronaut-core/milestone/99) milestone -- thank you!

As soon as there's a snapshot or RC that I can test, let me know. Although I submitted a test case in a simple modular app, my main use case is in [Supernaut.FX](https://github.com/SupernautApp/SupernautFX#readme) apps where I'm using the [Badass JLink Plugin](https://badass-jlink-plugin.beryx.org/releases/latest/) to relocate Micronaut into the [merged module](https://badass-jlink-plugin.beryx.org/releases/latest/#_how_it_works) and then create a `jlink` and `packaged` JavaFX app.  I'm hoping the fix for the simple case will fix this, too. All previous versions of Micronaut, (from 1.1.0 to 3.0.0-M2) have worked well in this environment.

When Micronaut 3.0.4 ships, I'll release Supernaut.FX 0.3.0 with Micronaut 3.x support shortly thereafter.

**Comment by graemerocher** [comment]
@dstepanov can you look into this as well?

**Comment by msgilligan** [comment]
> @dstepanov can you look into this as well?

@dstepanov something changed from M2 to M3.

**Comment by msgilligan** [comment]
I confirmed this is still failing with Micronaut 3.1.0. I pushed commit https://github.com/jeffbrown/issue5985/pull/1/commits/e51c44042a8cd4eefe3c97801698b9c36d2be23b to https://github.com/jeffbrown/issue5985/pull/1 in @jeffbrown 's test project for this issue to upgrade to Micronaut 3.1.0.

**Comment by dstepanov** [comment]
This makes it work for me:
```
module app {
    requires jakarta.inject;
    requires jakarta.annotation;
    requires io.micronaut.inject;
    exports app;
}
```

**Comment by msgilligan** [comment]
Yeah, adding `requires jakarta.annotation;` seems to fix the issue. I'll do a little more testing before closing the issue.

**Comment by msgilligan** [comment]
Everything is looking good! Thanks! Closing...
