### ISSUE TITLE
Enable to use special characters in fallback configuration

### ISSUE THREAD

**Issue by morki** [micronaut-projects/micronaut-core#5988]
### Feature description

When using Micronaut configuration, I would like to use colon or other special characters like those contained in URL in fallback configuration value like:

```yaml
google-discovery-url: ${GOOGLE_DISCOVERY_URL:https://accounts.google.com/.well-known/openid-configuration}
```

I tried using double quotes like in Spring but without luck:

```yaml
google-discovery-url: ${GOOGLE_DISCOVERY_URL:"https://accounts.google.com/.well-known/openid-configuration"}
```

Is there any other way to use it? Thank you very much.

**Comment by ilopmar** [comment]
You need to use `backticks` to escape the value. See https://docs.micronaut.io/latest/guide/index.html#_property_value_placeholders

So in your case it would be:

```yaml
google-discovery-url: ${GOOGLE_DISCOVERY_URL:`https://accounts.google.com/.well-known/openid-configuration`}
```

**Comment by morki** [comment]
Thank you and very sorry for not reading documentation carefully.
