### ISSUE TITLE
Additional information in 500 error missing in 3.0.0-RC1

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#5995]
### Expected Behavior

When there is a 500 error there was some additional information about the error in 3.0.0-M5

### Actual Behaviour

With Micronaut 3.0.0-RC1 that extra information is gone.

When upgrading Micronaut Views to Micronaut 3.0.0-RC1 this test fails:

https://github.com/micronaut-projects/micronaut-views/blob/53c261dd959c8e12a34cebea9fda0b54bfcce977/views-freemarker/src/test/groovy/io/micronaut/docs/FreemarkerViewRendererSpec.groovy#L177

```
io.micronaut.docs.FreemarkerViewRendererSpec invoking /freemarker/bogus returns 500 if you attempt to render a template which does not exist FAILED

  Condition not satisfied:
  
  e.message == "Internal Server Error: View [bogus] does not exist"
  | |       |
  | |       false
  | |       29 differences (42% similarity)
  | |       Internal Server Error(-----------------------------)
  | |       Internal Server Error(: View [bogus] does not exist)
  | Internal Server Error
```

### Steps To Reproduce

Run the test in Micronaut Views module in branch `upgrade-micronaut3.0.0-RC1`

### Version

3.0.0-RC1

**Comment by jameskleeh** [comment]
The data is in `_embedded.errors[0].message`
