### ISSUE TITLE
GraalVM native-image build failure using SLF4J and Log4j 2

### ISSUE THREAD

**Issue by brunolellis** [micronaut-projects/micronaut-core#6041]
### Expected Behavior

The native-image command should build the image successfully.

### Actual Behaviour

The native-image command fails trying to initialize `org.apache.logging.slf4j.Log4jLogger` at build time.

Is there a way to use log4j2 with native-image?
I also tried using `--initialize-at-build-time=org.apache.logging.slf4j.Log4jLogger` but then another list of classes appears.

Output:
```
➜  micronaut-slf4j-log4j2 git:(master) native-image -jar build/libs/micronaut-slf4j-log4j2-0.1-all.jar --trace-class-initialization=org.apache.logging.slf4j.Log4jLogger
[micronaut-slf4j-log4j2-native-image:65072]    classlist:   2,661.67 ms,  1.19 GB
[micronaut-slf4j-log4j2-native-image:65072]        (cap):     411.13 ms,  1.19 GB
WARNING: Method com.sun.management.OperatingSystemMXBean.getCpuLoad() not found.
WARNING: Method com.sun.management.OperatingSystemMXBean.getCpuLoad() not found.
[micronaut-slf4j-log4j2-native-image:65072]        setup:   2,010.65 ms,  1.19 GB
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[micronaut-slf4j-log4j2-native-image:65072]     analysis:   7,738.15 ms,  1.73 GB
Error: Classes that should be initialized at run time got initialized during image building:
 org.apache.logging.slf4j.Log4jLogger was unintentionally initialized at build time. io.micronaut.runtime.Micronaut caused initialization of this class with the following trace: 
	at org.apache.logging.slf4j.Log4jLogger.<clinit>(Log4jLogger.java:41)
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:39)
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:30)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:53)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at io.micronaut.runtime.Micronaut.<clinit>(Micronaut.java:49)


Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[micronaut-slf4j-log4j2-native-image:65072]      [total]:  12,597.98 ms,  1.73 GB
# Printing build artifacts to: /home/brunolellis/workspaces/micronaut-slf4j-log4j2/micronaut-slf4j-log4j2-native-image.build_artifacts.txt
Error: Image build request failed with exit status 1
```

### Steps To Reproduce

1. `sdk use java 21.2.0.r11-grl`
2. `./gradlew clean build`
3. `native-image -jar build/libs/micronaut-slf4j-log4j2-0.1-all.jar`

### Environment Information

- Ubuntu 20.04: Linux brunolellis-T490 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- ghcr.io/graalvm/graalvm-ce:java11-21
- graalvm: 21.2.0.r11-grl

### Example Application

https://github.com/brunolellis/micronaut-slf4j-log4j2

### Version

2.5.12

**Comment by narramadan** [comment]
I was facing the same issue with the Slf4j and Log4j2. Tried different options, but couldn't get anything working.

Replaced slf4j & logj2 with `logback-classic` in `build.gradle` and native-image build is working as expected.

```
  /*
    implementation("org.slf4j:slf4j-api:1.7.32")
    runtimeOnly("org.apache.logging.log4j:log4j-core:2.14.1")
    runtimeOnly("org.apache.logging.log4j:log4j-api:2.14.1")
    runtimeOnly("org.apache.logging.log4j:log4j-slf4j-impl:2.14.1")
    */
    runtimeOnly("ch.qos.logback:logback-classic")
```

**Comment by brunolellis** [comment]
Hi,
I tried with log4j in this demo because I use an internal (proprietary) lib
that wraps logged messages, plus some key value information and format in a
json message to stdout, and it is based on log4j.

Maybe an option would be to create another internal lib based on logback.

Thanks for your time anyway!

**Comment by graemerocher** [comment]
@dstepanov is there something we can do to auto-configure log4j users for native?

**Comment by ilopmar** [comment]
Elasticsearch uses log4j and in our test application I added this to get it working with GraalVM:

https://github.com/micronaut-graal-tests/micronaut-elasticsearch-graal/blob/3.1.x/build.gradle#L29-L35

**Comment by dstepanov** [comment]
We probably need some graalvm feature that would apply class initialization only if the class is present.

The solution is also to use `log4j-over-slf4j`.

@ilopmar I think it should be enough just to include `log4j-over-slf4j` without log4j core and api.

**Comment by ilopmar** [comment]
@dstepanov I think I tried that and it didn't work, that's why I added the logj4 core and api dependencies. This was sometime ago so maybe something has changed and it's not necessary anymore. I'll give it a try.

**Comment by dstepanov** [comment]
Unfortunately, it's log4j incompatibility with a native image, the issue should be reported to the log4j team.
The workaround is to use `log4j-over-slf4j`. Nothing much we can do here.

**Comment by sschuberth** [comment]
> The workaround is to use `log4j-over-slf4j`.

I guess alternatively to getting rid of the Log4j(2) implementation *this* way (in favor of whatever implementation you use with the SLF4J API, [it's logback in the above example](logback)), you could also stick with `log4j-api` (e.g. because you're using it implicitly via `log4j-api-kotlin`) and take [log4j-to-slf4j](https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-to-slf4j) into use which "forwards" Log4j(2) API calls to the SLF4J API.

**Comment by sidlors** [comment]
I removed (commented) this lines:

 //implementation("org.springframework.boot:spring-boot-starter")
 //implementation("org.springframework.boot:spring-boot-starter-web")
//runtimeOnly("io.micronaut.spring:micronaut-spring-boot")
    //testAnnotationProcessor("io.micronaut.spring:micronaut-spring-annotation")
    //testAnnotationProcessor("io.micronaut.spring:micronaut-spring-boot-annotation")

**Comment by imgoby** [comment]
Is it resolved?How to config?

**Comment by bntv-config** [comment]
IS this resolved? Can you please suggest the steps ?
