### ISSUE TITLE
Nested annotations handling

### ISSUE THREAD

**Issue by vasac** [micronaut-projects/micronaut-core#6045]
### Expected Behavior

It's expected that ApplicationContext finds a bean annotated with nested annotation:

```
class ExtractorFactoriesTest {

    @Inherited
    @Documented
    @Retention(RetentionPolicy.RUNTIME)
    public @interface TestExtractor {
    }

    @TestExtractor
    @Singleton
    public static class TestExtractorFactory implements ExtractorFactory {
    }
}
```

This code should return `TestExtractorFactory` bean.
```
ctx.findBean(ExtractorFactory.class, new FactoryQualifier<>(TestExtractor))
```

### Actual Behaviour

ApplicationContext is unable to find a bean as deep down `annotationMetadata.declaredAnnotations` map has a key `..ExtractorFactoriesTest.TestExtractor` instead of `..ExtractorFactoriesTest$TestExtractor`.

This happens with Micronaut 3.0.0 while 3.0.0-RC1 works as expected.

### Environment Information

macOS 10.15.7
JDK 1.8.0_301

### Version

3.0.0

**Comment by jameskleeh** [comment]
What is `FactoryQualifier`? Can you upload an example?

**Comment by vasac** [comment]
Sorry, totally missed that.

`FactoryQualifier` looks like this:
```
import io.micronaut.context.Qualifier;

class FactoryQualifier<T> implements Qualifier<T> {
    private final Class<? extends Annotation> type;
    private final Class<? extends Annotation> holder;

    FactoryQualifier(Class<? extends Annotation> cls) {
        type = cls;
        Repeatable repeatable = cls.getAnnotation(Repeatable.class);
        holder = repeatable == null ? null : repeatable.value();
    }

    @Override
    public <BT extends BeanType<T>> Stream<BT> reduce(Class<T> beanType, Stream<BT> candidates) {
        return candidates.filter(this::filter);
    }

    <BT extends BeanType<T>> boolean filter(BT bt) {
        if (holder == null) {
            // there is no holder, if we find the type it must have a annotations value of zero size
            return bt.isAnnotationPresent(type) && bt.getAnnotation(type).getAnnotations("value").size() == 0;
        }
        // there is a holder (i.e. type is @Repeatable), if we find the holder it must have a annotations value of size 1
        return bt.isAnnotationPresent(holder) && bt.getAnnotation(holder).getAnnotations("value").size() == 1;
    }
}
```

`bt.isAnnotationPresent(type)` call will end at `DefaultAnnotationMetadata.hasDeclaredAnnotation(String annotation)` with value of `annotation`argument like this `...ExtractorFactoriesTest$TestExtractor` and `declaredAnnotations` map will have key `...ExtractorFactoriesTest.TestExtractor`.

Here's the actual test that fails - https://github.com/micronaut-projects/micronaut-coherence/blob/4ab19085aa069db74c53403ad2ee49d182c1971a/coherence/src/test/java/io/micronaut/coherence/ExtractorFactoriesTest.java#L153

I can try to extract it into some smaller example project if it's necessary?

**Comment by vasac** [comment]
Here is a small example project https://github.com/vasac/nested-annotation

**Comment by graemerocher** [comment]
Weird I see nothing in the diff between the RC and GA that could cause this https://github.com/micronaut-projects/micronaut-core/compare/v3.0.0-RC1..v3.0.0

Going to investigate further

**Comment by graemerocher** [comment]
I submitted a PR for this but your example application fails with 3.0 RC1 as well. This seems to be a long standing bug
