### ISSUE TITLE
Inconsistent behavior with @Introspected on abstract class in Groovy

### ISSUE THREAD

**Issue by mstein** [micronaut-projects/micronaut-core#6054]
### Expected Behavior

When trying to get an `BeanIntrospection` for an abstract class (part of our code, not a class in a jar), whether we annotate the class directly with `@Introspected` or we annotate another class with `@Introspected(classes = [TargetClass])`, the end results should be the same. In my case, I expect a `BeanIntrospection` to be generated for my abstract class. Note that I'm using Groovy in my tests.
**Case 1:**
```groovy
@Introspected
abstract class Media {
    String name
    String author
}
```
**Case 2:**
```groovy
abstract class Media {
    String name
    String author
}

@Introspected(classes = [Media])
class MyConfig {

}
```
**Testing:**
```groovy
@CompileStatic
class Application {
    static void main(String[] args) {
        BeanIntrospection<Media> biMedia = BeanIntrospection.getIntrospection(Media)
        assert biMedia.propertyNames == ['name', 'author']
    }
}
```

### Actual Behaviour

The introspection fails on **case 1** (`@Introspected` directly on the abstract class). The test results in an `IntrospectionException` being thrown:
```
Exception in thread "main" io.micronaut.core.beans.exceptions.IntrospectionException: No bean introspection available for type [class com.example.model.Media]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected
	at io.micronaut.core.beans.BeanIntrospector.lambda$getIntrospection$3(BeanIntrospector.java:105)
	at java.base/java.util.Optional.orElseThrow(Optional.java:401)
	at io.micronaut.core.beans.BeanIntrospector.getIntrospection(BeanIntrospector.java:105)
	at io.micronaut.core.beans.BeanIntrospection.getIntrospection(BeanIntrospection.java:227)
	at com.example.Application.main(Application.groovy:20)
```

**Case 2** works and a `BeanIntrospection` is returned and the test app exits without error.

I would assume that adding the annotation on the classes themselves should produce the same result, but somehow it doesn't.
This was tested on Micronaut **3.0.0** and Micronaut **2.5.12**.

Note that even in **case 2**, since we didn't define a "primary constructor" in the class, any attempt to instantiate the class with `BeanIntrospection#instantiate` will results in a error, which is expected since the class is abstract.
```
Exception in thread "main" java.lang.InstantiationError: com.example.model.Media
	at com.example.model.$com_example_model_Media$Introspection.instantiate(Unknown Source)
	at com.example.Application.main(Application.groovy:24)
```
That being said, we can get the fields data and their annotation metadata, which in my case is all I need (I'm not looking to instantiate anything from it), but the behavior is still inconsistent, so I'm wondering if you plan to let this work in the future.

### More informations

Looking into this further, I found that it seems like the reason for this behavior is located in the [IntrospectedTypeElementVisitor#processElement](https://github.com/micronaut-projects/micronaut-core/blob/6db05822666b487608dd610dc69de339b0fd543b/inject/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java#L297) method of the annotation preprocessor.

This line in particular (L297):
```java
if (ce.isAbstract() && !constructorElement.isPresent() && ce.hasStereotype(Introspected.class)) {
```

The reason **Case 2** ended up working is because the class itself wasn't annotated with `@Introspected` and thus that condition failed, so an `AbstractIntrospection` was not produced.
And looking at this it is then easy to use another way to make it work even by annotating directly the abstract class itself: we can just declare a "primary constructor" to make the `!constructorElement.isPresent()` resolve false.

Thus the following case (**case 3**) will also work: 
```groovy
@Introspected
abstract class Media {
    String name
    String author

    @Creator
    Media() {}
}
```
Of course, just like **case 2**, we can't instantiate the class from the `BeanIntrospection`. This can be resolved by declaring a static method and marking as a `@Creator`, providing for example a default concrete class instance.
By the way, a call to `getPropertyNames()` will properly return `['name', 'author']`.

Example (**Case 4**):
```groovy
@Introspected
abstract class Media {
    String name
    String author

    @Creator
    static Media from(String name, String author) {
        new Movie(name: name, author: author)
    }
}

class Movie extends Media {
    Integer duration
}
```
In that case, we can use the `instantiate` method with the proper arguments.

### Another inconsistency with explicit getter/setter

Another way I found to force a `BeanIntrospection` creation with `@Introspected` directly on the abstract class even without using a `@Creator` declaration, is to declare an explicit "getter-like" method on the class. But in that case, while the `BeanIntrospection` is created, the properties that don't have explicit getter/setter defined are no longer recognized.

Consider this example (**Case 5**):
```groovy
@Introspected
abstract class Media {
    String name
    String author
   
   String getFullTitle() {
       "${name} by ${author}"
   }
}

@Introspected
class Movie extends Media {
    Integer duration
}
```
The `BeanIntrospection` for `Media` will only return `fullTitle` when calling `getPropertyNames()`. The generated getters/setter (by Groovy) for `name` and `author` are now somehow ignored by default.

The `BeanIntrospection` for the concrete class `Movie` properly returns all the fields, including the `fullTitle` one.

So when the abstract class isn't "tricked" with a `@Creator` declaration, it seems like going into the path which produce an `AbstractIntrospection` will not produce the same end result for the `BeanIntrospection`.

### Environment Information

- **Operating system**: Windows 10 Pro 21H1
- **JDK**: 14.0.1 64 bit (compilation targets java 11)
- **Groovy**: 3.0.8 (the one included with `micronaut-runtime-groovy` 3.0.0)

### Version

3.0.0

**Comment by jameskleeh** [comment]
Thank you for the detailed issue report! This should be resolved for 3.0.1
