### ISSUE TITLE
Support for converting a specific part to POJO in Multipart form data request

### ISSUE THREAD

**Issue by rohit-s8** [micronaut-projects/micronaut-core#6060]
### Feature description

My use case is as follows:

I have a rest endpoint that needs to accept both a json body as well as an attached file. The json contains metadata about the file and will also be serialized into a pojo. 

I tried the following: According to the [documentation](https://docs.micronaut.io/2.5.12/guide/index.html#uploads), all I had to do was:
* annotate my controller method with @Consumes(MediaType.MULTIPART_FORM_DATA)
* add one method parameter for each part (optionally annotated with the part name)
* For the json i used my pojo class as the parameter type
* For the file i used CompletedFileUpload as the parameter type
The controller code is essentially as follows:
```java
  @Post(PUBLIC_BASE_PATH)
  @Status(HttpStatus.CREATED)
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.MULTIPART_FORM_DATA)
  public MyPojo saveAlgorithm(Context context,
                                 @Part("metadata") MyPojo metadata,
                                 @Part("pkl") CompletedFileUpload pkl) throws IOException {
    ...
  }
```
Now all the client has to do is create a multipart form data request with the required parts and this should work out of the box. However, when i tried this with postman I got the following error:
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/29656930/130806956-ba306a15-e8d7-4c87-8ed7-57a3993678cc.png">

It was later confirmed that the same error was being returned for a javascript/jquery/ajax request.

As can be seen, the metadata part is being sent as plain text and the pkl part as a file upload. I wasn't expected to see an error like this so I went back into the documentation to see if I missed something. Under the section `Whole Data Types`:
> A media type codec is included by default that allows conversion of JSON files to POJOs

according to the above, micronaut will perform the conversion if the `metadata` part was a json file. So i tried that and sure enough it worked.

However it doesn't make any sense why micronaut would not support the conversion of plain text part to a pojo as this is a perfectly valid usecase. And what made this more confusing is that micronaut doesn't even seem to see the part unless it's a file.

the following issue  https://github.com/micronaut-projects/micronaut-core/issues/1957 seems to voice a similar concern for which the type MultipartBody was created. But MultipartBody wouldn't work well here.

If this is by design, then I think enabling support for conversion of plain text parts to pojos would be a valid enhancement to the micronaut framework.

**Comment by jameskleeh** [comment]
The content type for the `metadata` part has to be JSON. What is the content type of the part in your case?

**Comment by jameskleeh** [comment]
> However it doesn't make any sense why micronaut would not support the conversion of plain text part to a pojo as this is a perfectly valid usecase

Because there is no sensible conversion from a string to a pojo. We don't know if the data is XML, JSON, yaml, etc etc...

**Comment by rohit-s8** [comment]
@jameskleeh yes we tried adding the content-type as application/json, but the error was the same regardless. Here's the example js code that was used to send the request:
```javascript
var formdata = new FormData()
var blobMetadata = new Blob([Json.stringify(metadata)], { type: 'application/json' })
var pkl = $('#pkl-file').prop('files')[0]
formdata.append("metadata", blobMetadata)
formdata.append("pkl", pkl);
// send the above using jquery/ajax
```
According to
> The content type for the metadata part has to be JSON.

The above should have worked as the content type of the part `metadata` is explicitly set to 'application/json'. Naturally, i do not expect automatic conversion when the content type can not be inferred before hand.

**Comment by jameskleeh** [comment]
@rohit-s8 Please upload an example application that reproduces the issue
