### ISSUE TITLE
Non-Proxy Custom Scopes

### ISSUE THREAD

**Issue by RyanHoldren** [micronaut-projects/micronaut-core#6064]
### Issue description

I suspect this is not a bug, but rather that I am just misunderstanding how Micronaut works.

Consider this example:

```
@Documented
@Retention(RUNTIME)
@Scope
@Target({TYPE, METHOD})
public @interface SpecialBean {}

@Singleton
public class SpeciaBeanScope implements CustomScope<SpecialBean> {

	private final Map<BeanIdentifier, CreatedBean<?>> beans = new ConcurrentHashMap<>();

	@Override
	public Class<SpecialBean> annotationType() {
		return SpecialBean.class;
	}

	@Override
	public <T> T getOrCreate(BeanCreationContext<T> context) {
		final var id = context.id();
		return (T) beans.computeIfAbsent(id, key -> context.create()).bean();
	}

	// ...

}

@SpecialBean
public class SpecialService {

}
```

I expected that `SpeciaBeanScope.getOrCreate()` would be called for `SpecialService` but it isn't. It looks like the scope is never looked up by `DefaultBeanContext.getScopedBeanForDefinition()` because SpecialBean is not annotated with `@ScopedProxy`.

Here is the relevant code from [`DefaultBeanContext.getScopedBeanForDefinition()`](https://github.com/micronaut-projects/micronaut-core/blob/dfae2e06547aac2cfc052f9a53fbb887c9b6c4e3/inject/src/main/java/io/micronaut/context/DefaultBeanContext.java#L2785):
```
if (registeredScope == null && !isProxy && isScopedProxyDefinition) {
	registeredScope = customScopeRegistry.findDeclaredScope(definition).orElse(null);
}
```

This seems _very_ intentional, but I am not sure why. Why do custom scopes have to be proxies? In my case, I cannot simply add `@ScopeProxy` because some of my beans are `final`.

**Comment by Paullo612** [comment]
Looks like correct condition would be

`if (registeredScope == null && ((isScopedProxyDefinition && !isProxy) || !isScopedProxyDefinition))`

which can be simplified to

`if (registeredScope == null && (!isScopedProxyDefinition || !isProxy))`.

Also, proxy target bean definition should be searched [here](https://github.com/micronaut-projects/micronaut-core/blob/dfae2e06547aac2cfc052f9a53fbb887c9b6c4e3/inject/src/main/java/io/micronaut/context/DefaultBeanContext.java#L2790) only if it is scoped proxy (to make AOP work correctly for non scoped proxies).

Patched locally for now, but looking forward to see this fixed upstream!

It also would be cool to have some API in `BeanCreationContext`, which could allow to decide whether I should throw `NoSuchBeanException` from `CustomScope#getOrCreate`, or just return null (later is relevant when bean is searched through `BeanLocator#findBean`).
