### ISSUE TITLE
Bad release notes link

### ISSUE THREAD

**Issue by benmccann** [micronaut-projects/micronaut-core#6068]
### Issue description

When I click "Release Notes" on https://micronaut.io/download/ I'm taken to a page with no details about 3.0. It would be nice to update the tagged release on Github with a link to https://micronaut.io/2021/08/18/micronaut-framework-3-released/ or to otherwise make the release notes discoverable from the release notes link

**Comment by jameskleeh** [comment]
Fixed! thanks
