### ISSUE TITLE
Accessing @RequestScope beans from filter throws exception

### ISSUE THREAD

**Issue by kahz9918** [micronaut-projects/micronaut-core#6099]
### Expected Behavior

In 2.5.0 accessing a @RequestScope bean from a filter worked without a problem but since 2.5.1 and event with the latest 2.5.x it cant find the bean and throws an exception.

### Actual Behaviour

When trying to access the bean from a filter it throws
`io.micronaut.context.exceptions.NoSuchBeanException: No bean of type...`

### Steps To Reproduce

In the example application run the test `TestControllerSpec` it passes in 2.5.0 but fails on 2.5.1 and the latest 2.5.x

### Environment Information

- Operating System: Arch LInux
- JDK version: AdoptOpenJDK 11.0.7

### Example Application

https://github.com/kahz9918/mn-requestscope-filter

### Version

2.5.1

**Comment by jameskleeh** [comment]
Cannot reproduce with Micronaut 3
