### ISSUE TITLE
EventBus support in Micronaut

### ISSUE THREAD

**Issue by luistrigueiros** [micronaut-projects/micronaut-core#611]
I would love to see support in Micronaut for a type of **EventBus** mechanics similar to the one that exists in Guava or Spring.

The would be that a bean method annotated with a given annotation i.e (**@Subscribe**) would be **_automatically registered as a listener for events_** that could be fired via an implementation of this EventBus given by Micronaut container.

Additionally optionally it would be cool if this would be handled async maybe using the equivalent of one elastic I/O executor service.

**Comment by RyanHoldren** [comment]
This sounds to me a lot like [the method adapter advice example in the documentation](https://docs.micronaut.io/snapshot/guide/index.html#adapterAdvice)

**Comment by brandonlamb** [comment]
My team started using MBassador, but +1 to this. I didnt want to pull in the entire guava library to use its event bus

**Comment by luistrigueiros** [comment]
Thank you both very useful inputs I will have a look at MBassador and the Adapter. 
I my case what I am doing is just when persisting objects to Redis using Lettuce reactive API for some reason the the doOnNext does not gets called, but I need to create additional aux keys and data structures for example to support multi-facet search.
So I am using an event listener to create the additional support indexes for a given domain object been persisted.

**Comment by luistrigueiros** [comment]
Thank you @graemerocher  this was I was looking for.

**Comment by luistrigueiros** [comment]
Hi @graemerocher:

How can one obtain an instance of ApplicationEventListener ?
I my case I don't have of these service discovery services yet.

https://docs.micronaut.io/snapshot/api/io/micronaut/context/event/ApplicationEventListener.html
All Known Implementing Classes:
AutoRegistration, ConsulAutoRegistration, DiscoveryServiceAutoRegistration, EnvironmentConfiguration, EnvironmentDeploymentContext, EurekaAutoRegistration, HeartbeatTask, RefreshScope, Route53AutoNamingRegistrationClient, SessionWebSocketEventListener, SimpleMeterRegistryEventListener

**Comment by rodolfodpk** [comment]
90% of the features? Well, Quarkus certainly got some inspiration from Micronaut and I wish Micronaut could do it too: https://quarkus.io/guides/reactive-event-bus An event bus with request/reply (not only pub/sub), blocking code annotation, and even Mutiny as an alternative reactive glue (compatible with RxJava but not Reactor, AFAIK). I have some use cases I usually implemented in Vertx/Quarkus with its event bus but now I have to use Micronaut and stucked. At least I can use Vertx reactive drivers with Micronaut, I probably will make use of its event bus too but will miss some nice building blocks.
