### ISSUE TITLE
Open up the 2nd port for mTLS or mutual TLS ( two way authentication )

### ISSUE THREAD

**Issue by nandakishorkn** [micronaut-projects/micronaut-core#6111]
### Feature description

How to open up 2nd port for mTLS or mutual TLS ( two way authentication ) ?

In DropWizard, We were using applicationConnectors to define dual ports
(a) one port for HTTPS connections ( to do BasicAuth and TokenAuth )
(b) another port for mTLS connections
https://www.dropwizard.io/en/latest/manual/configuration.html#connectors

How do we achieve the same in Micronaut ?

A snip from our DCS Agent application configuration file based on DropWizard where it allows us to configure two ports :

    "applicationConnectors": [
      {
        "port": "7070",
       ...<snip>
        "type": "https"
      },
      {
       ...<snip>
        "needClientAuth": "true",
        "port": "7071",
       ...<snip>
        "type": "https"
      }
    ]

Here, port 7070 is used for HTTPS communication ( Basic Auth & Token Auth ) and port 7071 is used for mTLS communication over HTTPS.

Do we have an equivalent for this option in Micronaut ? Otherwise, Is there
any alternate ways of achieving the same ?

**Comment by graemerocher** [comment]
Supported by https://github.com/micronaut-projects/micronaut-core/pull/6152
