### ISSUE TITLE
SSL Reload option is not available in Micronaut

### ISSUE THREAD

**Issue by nandakishorkn** [micronaut-projects/micronaut-core#6112]
### Feature description

Does Micronaut allows certificate reload (SSL reload) ? If we change / import a new certificate into public key - Will it auto reload without restarting the application ?

In existing DropWizard Jetty based DCS Application, We are referring to the following for SSL Reload.
https://javadoc.io/static/io.dropwizard/dropwizard-jetty/1.3.9/io/dropwizard/jetty/SslReload.html

Graeme confirmed "SSL reload is not currently supported".

**Comment by graemerocher** [comment]
We would need to allow the SSL configuration in the server to be refreshed

**Comment by graemerocher** [comment]
Draft PR https://github.com/micronaut-projects/micronaut-core/pull/6137

**Comment by anuragdeshpande** [comment]
Outside of official docs, I am unable to find any references online for this config. So responding to the merge where the feature was added. 

@graemerocher Thank you so much for adding this. It would really help us out in our application. I am on micronaut v3.6.0 However, I don't seem to be able to get this config to work. I have tried several versions and even tried passing in the full file path. It still seems to be using the file that was included in the original build. I am attaching screenshots of my config, attempts and logs. Am I missing anything? Could you please help? 


Original SSL config in application
![image](https://user-images.githubusercontent.com/3684197/184462424-5e19179b-1c6b-4c40-91c0-e4fea1ed04de.png)

Logging on refresh event
![image](https://user-images.githubusercontent.com/3684197/184462212-6b0c9cde-695b-4973-a081-df485a1930ed.png)

Trying full ssl.* reload
![image](https://user-images.githubusercontent.com/3684197/184462504-273aa722-a04b-4055-a90e-2252e12d4c82.png)

Confirming refresh event in logs
![image](https://user-images.githubusercontent.com/3684197/184462093-154d7567-c97a-439d-a1f8-db81d893c703.png)

Application returning old value in property as response. Also tried new requests in a new browser window, different browser as well
![image](https://user-images.githubusercontent.com/3684197/184461914-4dea3d85-f5d6-4aa0-abfe-30385ab1d9cf.png)

Trying just path refresh for SSL. Event was successfully recorded in logs, but still not using new p12 file.
![image](https://user-images.githubusercontent.com/3684197/184463061-5afaa4c7-47d4-4d08-8d97-cd86c209f571.png)
