### ISSUE TITLE
MDC propagation from server filters does not work correctly

### ISSUE THREAD

**Issue by drmaas** [micronaut-projects/micronaut-core#6124]
### Expected Behavior

1. Add `micronaut-tracing`
2. Set an MDC value in a server filter.
3. The value applies throughout the request/response lifecycle.

### Actual Behaviour

1. Add `micronaut-tracing`
2. Set an MDC value in a server filter.
3. It does not apply - the MDC seen in the controller does not match that in the server filter.

### Steps To Reproduce

Run `MdcPropagationIssueTest` in the sample app test folder to see inconsistent MDC `x-api-id` values.

### Environment Information

OSX
JDK11

### Example Application

https://github.com/drmaas/mdc-propagation-issue

### Version

2.5.13

**Comment by drmaas** [comment]
I verifed that MDC propagation works correctly in `2.5.0`, but not `2.5.1+`. So something in `2.5.1` is the root cause.

**Comment by drmaas** [comment]
Looking at it further, it seems that the removal of `ServerRequestContextFilter` in https://github.com/micronaut-projects/micronaut-core/pull/5329 causes MDC propagation to break. Adding in back into my sample project fixes the discrepancies.

**Comment by 22dasi1bwi** [comment]
Same issue we experienced: See https://github.com/micronaut-projects/micronaut-core/issues/5656

**Comment by dstepanov** [comment]
I have tried to run `MdcPropagationIssueTest` and it's passing for me

**Comment by drmaas** [comment]
@dstepanov I miscommunicated - the test iteratively loops and passes. Within the test, log messages are generated that indicate an incorrect mdc attribute (x-api-id). I will look at how to make the test actually fail.

**Comment by drmaas** [comment]
@dstepanov I updated the sample app, which shows that `MdcPropagationIssueTest` fails when comparing the MDC value seen in the controller with that seen in the server filter.

**Comment by dstepanov** [comment]
It looks like `Flowable.fromPublisher` doesn't capture context because the publisher is actually `Flowable` as well.
The working code is this:
```java
        MDC.put("x-api-id", requestId);
        Flowable<MutableHttpResponse<?>> filterResponse = Single.fromPublisher(chain.proceed(request))
                .doOnSuccess(
                        (response) -> {
                            if (response != null) {
                                response.getHeaders()
                                        .add("X-Api-Id", requestId)
                                        .add("X-Api-Id-From-Filter", requestId);
                            }
                            log.info("filter response");
                        }).toFlowable();
        MDC.remove("x-api-id");
        return filterResponse;
 ```
 Notice how `MDC.remove`, that's the correct way how to cleanup the current thread.

I will close this one, in v3 we already switched to Reactor and further fixes and improvements should be there.

**Comment by drmaas** [comment]
Confirmed this works, thanks @dstepanov
