### ISSUE TITLE
Missing dependencies in Catalog Version

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#6130]
### Expected Behavior

Zipkin-related dependencies should be included in the BOM

### Actual Behaviour

After introducing Gradle Catalog version and running a Micronaut Zipkin app, some dependencies are missing from the bom:

```
$ gw run  

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'zipkin-graal'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find io.opentracing.brave:brave-opentracing:.
     Required by:
         project :
   > Could not find io.zipkin.brave:brave-instrumentation-http:.
     Required by:
         project :
   > Could not find io.zipkin.reporter2:zipkin-reporter:.
     Required by:
         project :

* Try:
```

### Steps To Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-zipkin-graal`
- `cd micronaut-zipkin-graal`
- `git checkout 3.0.x`
- `./gradlew run`

### Version

3.0.2-SNAPSHOT

**Comment by ilopmar** [comment]
Update:

The following depedencies are missing:

```
Missing org.grails:grails-datastore-core
Missing org.grails:grails-datastore-gorm
Missing org.grails:grails-datastore-async
Missing org.grails:grails-datastore-gorm-async
Missing org.grails:grails-datastore-gorm-support
Missing org.grails:grails-datastore-gorm-test
Missing org.grails:grails-datastore-gorm-validation
Missing org.grails:grails-datastore-web
Missing org.grails:grails-datastore-gorm-hibernate5
Missing io.jaegertracing:jaeger-thrift
Missing io.zipkin.reporter2:zipkin-reporter
Missing io.zipkin.brave:brave-instrumentation-http
Missing io.opentracing.brave:brave-opentracing
Missing javax.annotation:javax.annotation-api
Missing io.methvin:directory-watcher
```

**Comment by melix** [comment]
Tip: you can check the contents of the generated BOM by calling:

`./gradlew :bom:publishAllPublicationsToBuildRepository`

and either open `bom/build/publications/publication/pom-default.xml` or look at the generated repository at `build/repo/io/micronaut/micronaut-bom/3.0.2-SNAPSHOT`.
