### ISSUE TITLE
JdbcIndicator adds url to HealthIndicator on SqlException causing it to print the url to the log

### ISSUE THREAD

**Issue by lucaslilja** [micronaut-projects/micronaut-core#6136]
### Expected Behavior

When you get an SQLException you should NOT see the connection string in the log since it can contain the user and password in clear text.

### Actual Behaviour

HealthResult prints out the connection url in the log since JdbcIndicator adds url as name in the HealthResult builder.
`try {
                    key = dataSource.getClass().getMethod("getUrl").invoke(dataSource).toString();
                } catch (Exception n) {
                    key = dataSource.getClass().getName() + "@" + Integer.toHexString(dataSource.hashCode());
                }
HealthResult.Builder builder = HealthResult.builder(key);`

### Version

2.4.2

**Comment by graemerocher** [comment]
Where is it output in the log? I don't see in recent versions of Micronaut this data being output to any log

**Comment by lucaslilja** [comment]
Our error message looks like this:
ERROR HealthResult Health indicator [jdbc:sqlserver://some.sql.server:1433;database=a-database;user=vcssql;password=passwordInPlainText;encrypt=true;trustServerCertificate=true;loginTimeout=30] reported exception: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
We have disabled it with micronaut.endpoints.health.jdbc.enabled=false

**Comment by lucaslilja** [comment]
The source for this is here: https://github.com/micronaut-projects/micronaut-core/blob/3.0.x/management/src/main/java/io/micronaut/management/health/indicator/jdbc/JdbcIndicator.java on line 104

**Comment by jameskleeh** [comment]
@lucaslilja Just to clarify - The issue is the `getUrl` method right? Would changing that to just

```
key = dataSource.getClass().getName() + "@" + Integer.toHexString(dataSource.hashCode());
```

resolve the issue for you?

**Comment by lucaslilja** [comment]
Yes, that would be much safer in a security perspective since usernames and passwords never should appear in logs. If the url is important for debugging purposes, then it should be truncated to only display the part that shows the url.
