### ISSUE TITLE
Proposal: Add grpc support

### ISSUE THREAD

**Issue by drmaas** [micronaut-projects/micronaut-core#615]
It would be really useful to be able to run a micronaut application that provides a way to easily build grpc servers and clients. This would be a vast enhancement over the current options for building grpc microservices on the jvm: 
* using https://github.com/grpc/grpc-java directly and piecing together your own microservice framework
* using something like https://github.com/LogNet/grpc-spring-boot-starter and having a hard dependency on spring boot

This could be done in a few different ways:
* Provide the ability to build grpc servers and clients
* Provide the ability to parse/render protocol buffers while using the existing netty http server and client

**Comment by graemerocher** [comment]
Yeah GRPC support would definitely be nice

**Comment by graemerocher** [comment]
@drmaas With regards to the latter option, do you have any references on how that could be achieved?

**Comment by drmaas** [comment]
@graemerocher Here's a parser and renderer we use with https://ratpack.io. It is handled via content negotiation when parsing request data and sending response data. The parse does use reflection, and there may be better ways of doing this as well.

```
import com.google.common.reflect.TypeToken;
import com.google.protobuf.Message;
import com.tgt.oss.ratpack.protobuf.Protobuf;
import ratpack.handling.Context;
import ratpack.http.TypedData;
import ratpack.parse.NoOptParserSupport;

import java.io.InputStream;

/**
 * This class parses protobuf request bodies into objects.
 */
@SuppressWarnings("unchecked")
public class ProtobufParser extends NoOptParserSupport {

  @Override
  protected <T> T parse(Context context, TypedData body, TypeToken<T> type) throws Exception {
    T result = null;

    if (Protobuf.X_PROTOBUF_MEDIA_TYPE.equalsIgnoreCase(body.getContentType().getType()) && Message.class.isAssignableFrom(type.getRawType())) {
      InputStream inputStream = body.getInputStream();
      result = (T) (type.getRawType().getDeclaredMethod("parseFrom", InputStream.class).invoke(null, inputStream));
    }

    return result;
  }
}
```

```
import com.tgt.oss.ratpack.protobuf.Protobuf;
import com.tgt.oss.ratpack.protobuf.ProtobufRender;
import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufAllocator;
import io.netty.buffer.ByteBufOutputStream;
import ratpack.handling.Context;
import ratpack.http.Response;
import ratpack.render.RendererSupport;

import java.io.OutputStream;

/**
 * This class protobuf objects into a binary byte array and sets the necessary headers.
 */
public class ProtobufRenderer extends RendererSupport<ProtobufRender> {

  @Override
  public void render(Context context, ProtobufRender protobuf) throws Exception {
    ByteBuf buffer = context.get(ByteBufAllocator.class).buffer();
    OutputStream outputStream = new ByteBufOutputStream(buffer);

    try {
      outputStream.write(protobuf.getMessage().toByteArray());
    } catch (Exception e) {
      buffer.release();
      context.error(e);
      return;
    }

    Response response = context.getResponse().contentTypeIfNotSet(Protobuf.X_PROTOBUF_MEDIA_TYPE);
    response.getHeaders()
      .add(Protobuf.X_PROTOBUF_SCHEMA_HEADER, protobuf.getMessage().getDescriptorForType().getFile().getName())
      .add(Protobuf.X_PROTOBUF_MESSAGE_HEADER, protobuf.getMessage().getDescriptorForType().getFullName());
    response.send(buffer);
  }
}
```

And the Message wrapper:
```
import com.google.protobuf.Message;

/**
 * A {@link ratpack.handling.Context#render renderable object wrapper} for rendering as Protobuf messages.
 *
 * @see Protobuf#protobuf(Message)
 */
public interface ProtobufRender {

  /**
   * The underlying object to be rendered.
   *
   * @return The underlying object to be rendered.
   */
  Message getMessage();
}
```

**Comment by o-nix** [comment]
@tomekzar they both are highly customized Netty pipelines. I believe there is no easy way to make them work on top of together.

**Comment by drmaas** [comment]
Something analogous to https://github.com/LogNet/grpc-spring-boot-starter could work too.

**Comment by schneidersteve** [comment]
I started to implement gRPC server support for Micronaut.

- https://github.com/Enegate/micronaut-grpc-server
- https://github.com/Enegate/micronaut-grpc-example

**Comment by drmaas** [comment]
@schneidersteve what about piggy-backing on https://github.com/rouzwawi/grpc-kotlin?

**Comment by schneidersteve** [comment]
@drmaas Thanks for the grpc-kotlin hint.
I read on there github page something like "Note that this only works on unix like system at the moment".
Is Java supported by the project?

**Comment by SanderSmee** [comment]
@schneidersteve hopefully I'm not too late to bring an other source of inspiration to the table https://line.github.io/armeria/ This project seems to support http and grpc simultaneously.

**Comment by schneidersteve** [comment]
@SanderSmee Thanks for the inspiration.
I managed to get gRPC and HTTP running with the _grpc-spring-boot-starter_ project.
Is there a documentation on how to integrate third party modules into the Micronaut bootstrap?
I used the NettyHttpServer and MessagingApplication from the Micronaut-Core as inspiring example.

**Comment by schneidersteve** [comment]
@drmaas The "grpc-kotlin" project is supported out of the box by my solution.
Please have a look at the kotlin only example: https://github.com/Enegate/micronaut-grpc-example-kotlin.

**Comment by SanderSmee** [comment]
@schneidersteve I can't answer your question, as I have no knowledge about Micronaut internals. 
I merely "connected the dots" between this issue and the mentioned project. I discovered it during my research regarding supported protocols beyond http/rest (e.g. grpc, RSocket) in frameworks like Micronaut, spring-boot.

**Comment by schneidersteve** [comment]
It is now possible to run the micronaut-http-server-netty and the grpc-netty-shaded server in parallel with different ports. This is a similar behaviour like the grpc-spring-boot-starter solution, my main inspiration.
I now use a MethodAdapterAdvice with StartupEvent and ShutdownEvent instead of an EmbeddedApplication to manage the life cycle of the grpc server.

**Comment by graemerocher** [comment]
Will be included in the next 1.1 milestone. Documentation can be found here https://micronaut-projects.github.io/micronaut-grpc/latest/guide/

**Comment by kamilgregorczyk** [comment]
Thanks to features like this Micronaut becomes a much better option for building services than bulky and overcomplicated spring!

**Comment by graemerocher** [comment]
@kamilgregorczyk GRPC has its own notion of retry that is configurable. See https://micronaut-projects.github.io/micronaut-grpc/latest/guide/configurationreference.html#io.micronaut.grpc.channels.GrpcDefaultManagedChannelConfiguration

And the `grpc.client.max-retry-attempts` setting

**Comment by kamilgregorczyk** [comment]
Thanks, I can see that it has retries and hedging which is great, any chance of getting some circuit breaker patter with it ?
