### ISSUE TITLE
Customer HTTP Header fields: Entry deleted if it contains more than one minus

### ISSUE THREAD

**Issue by ChristianBohn** [micronaut-projects/micronaut-core#616]
An HTTP header field is lost if the name of it contains more than one minus (-). 

Works not:
- X-Correlation-Id

Works properly:
- X-CorrelationId
- X-CorrelationIdVeryLongNameButOk

### Steps to Reproduce

1. Create a new Controller for HTTP GET
2. Send a request with HTTP Header field 'X-Correlation-Id' with some value
3. Notice that the HttpRequest object does not contain the field at all

### Expected Behaviour

Field and value should be present.

### Actual Behaviour

Header field is missing entirely.

### Environment Information

- **Operating System**: Linux Mint
- **Micronaut Version:** 1.0.0 M4
- **JDK Version:** 1.8

### Example Application

none

**Comment by jameskleeh** [comment]
I can't reproduce. Please upload an example project that demonstrates the behavior

**Comment by jameskleeh** [comment]
Closing due to lack of feedback
