### ISSUE TITLE
ServerWebSocket new instance not created from same computer

### ISSUE THREAD

**Issue by shmish111** [micronaut-projects/micronaut-core#6161]
### Expected Behavior

two tabs in the same browser should instantiate two `@ServerWebSocket` instances

### Actual Behaviour

a different `WebSocketSession` is created for each request however the same `@ServerWebSocket` instance is used (contrary to the documentation), even if different browsers are used. This is not the case across multiple computers which works as expected, multiple instances are created. This means that I would need to build a separate session cache per user to allow users to use multiple tabs, which is far from ideal.

### Steps To Reproduce

* create a `@ServerWebSocket` class
* log or debug the instance of this class in the `onOpen` or `onMessage` methods
* log or debug the `WebSocketSession` instance on these methods
* open a websocket connection to this server in two tabs

You should see that while different session instances exist, the same server instance is used

### Environment Information

confirmed on both Linux and OSX

### Version

2.5.9

**Comment by jameskleeh** [comment]
> This is not the case across multiple computers which works as expected, multiple instances are created

Are you certain about that?

**Comment by jameskleeh** [comment]
Classes annotated with `@ServerWebSocket` are by default singletons per: https://github.com/micronaut-projects/micronaut-core/blob/3.0.x/websocket/src/main/java/io/micronaut/websocket/annotation/ServerWebSocket.java#L42

I do see in the documentation "By default, a unique `@ServerWebSocket` instance is created for each WebSocket connection. ", however it seems that documentation is incorrect.

Try adding `@Prototype` to your bean

**Comment by jameskleeh** [comment]
@shmish111 If you can reproduce the issue of instances being shared after annotating the class with `@Prototype` please update this issue with an example application and I'll reopen

**Comment by shmish111** [comment]
OK, sorry I haven't had chance to try `@Prototype` yet but will try asap so happy to have this closed for now. Yes I'm not sure about it being across multiple computers I think I tried it out but can't remember, however it certainly occurred across multiple different browsers, I had chrome and safari opened at the same time and what happened on one changed the other, it was quite magical to watch!
