### ISSUE TITLE
The body is not read for streaming http client responses that produce an error

### ISSUE THREAD

**Issue by nyilmaz** [micronaut-projects/micronaut-core#6162]
### Expected Behavior

Having seen this issue: https://github.com/micronaut-projects/micronaut-core/issues/2324

Response body should be properly decoded, more specifically We want to map response body to a `Problem`.

https://github.com/nyilmaz/mcnt-demo/blob/master/src/main/java/com/migros/exception/HttpClientExceptionHandler.java#L28-L33

### Actual Behaviour

`exception.response.getBody(class)` ends up Optional.empty

### Steps To Reproduce

1. clone https://github.com/nyilmaz/mcnt-demo
2. run project
3. curl -v http://localhost:8080/test-api-v2/test
4. check logs

### Environment Information

macOS 10.15.7
```
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment Homebrew (build 16.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 16.0.1+0, mixed mode, sharing)
```

### Example Application

https://github.com/nyilmaz/mcnt-demo

### Version

2.5.13

**Comment by graemerocher** [comment]
You need to specify the `errorType` in your `@Client` declaration. See https://docs.micronaut.io/2.5.11/api/io/micronaut/http/client/annotation/Client.html#errorType--

**Comment by nyilmaz** [comment]
@graemerocher in fact errorType is already added: https://github.com/nyilmaz/mcnt-demo/blob/61cafdbf46450f999e87622e5466ca2da95f620b/src/main/java/com/migros/generatedapi/api/v2/DefaultApi.java#L11

**Comment by nyilmaz** [comment]
@graemerocher tested with 3.x with `errorType` response body still `Optional.empty`. Also updated test repository.

**Comment by graemerocher** [comment]
perhaps the response could not be decoded into the specified type

**Comment by cemo** [comment]
@graemerocher this is a serious issue on our side. We are also using [micronaut-problem](https://github.com/micronaut-projects/micronaut-problem-json/). Not only external services but also internal services as well.  Return **problem** and not resolving it is a serious problem. I could not understand why it is empty by the way in the first place but if a response has a body it must be handled.

**Comment by jameskleeh** [comment]
If you want to be able to deserialize DefaultProblem you need the problem jackson module. To get that, add

```
    <dependency>
      <groupId>org.zalando</groupId>
      <artifactId>jackson-datatype-problem</artifactId>
      <version>0.26.0</version>
      <scope>runtime</scope>
    </dependency>
```

to your dependencies

**Comment by cemo** [comment]
@jameskleeh 

We had updated the sample to demonstrate the error. Check test cases. There are 2 cases now. One of them are blocking other one is non-blocking. 

https://github.com/nyilmaz/mcnt-demo/blob/master/app/src/test/java/com/migros/McntDemoTest.java

Nonblocking errors are returning empty body.

**Comment by jameskleeh** [comment]
You need to read the body in the `onError` handler

Edit: false positive
