### ISSUE TITLE
Unexpected behaviour with @ConfigurationProperties and Lombok @AllArgsConstructor

### ISSUE THREAD

**Issue by thlaegler** [micronaut-projects/micronaut-core#6165]
### Expected Behavior

I'm using Lombok on my ConfigurationProperties classes like below and expect it to work:
```
import io.micronaut.context.annotation.ConfigurationProperties;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@ConfigurationProperties("my.example")
public class MyExampleConfigProperties
{

  @Builder.Default
  private Integer pollingMs = 120000;

  private Integer exampleStringProp;
}
```

### Actual Behaviour

But instead I get the following exception when `MyExampleConfigProperties` gets injected the first time into another bean.

```
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [java.lang.Integer] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
```

Now, when I swap the positions of `@NoArgsConstructor` and `@AllArgsConstructor` so that `@NoArgsConstructor` comes first then i's working. E.g.
```
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ConfigurationProperties("my.example")
public class MyExampleConfigProperties { ... }
```

Also, if I only keep `@AllArgsConstructor` it is throwing above exception.
```
@Data
@Builder
@AllArgsConstructor
@ConfigurationProperties("my.example")
public class MyExampleConfigProperties { ... }
```

Note: The `@Builder` annotations seem to be unrelated to this issue. I can remove `@Builder` and `@Builder.Default` and the issue is still occurring.

### Steps To Reproduce

Swap position of `@NoArgsConstructor` with `@AllArgsConstructor` (latter one on first position)
and/or
remove `@NoArgsConstructor` and only keep `@AllArgsConstructor`

Test example:
```
@MicronautTest(environments = { "local" })
public class MyExampleAppTest
{
  @Inject EmbeddedApplication<?> application;

  @Test
  void testConfigProperties() {
    Map<String, Object> items = new HashMap<>();
    items.put("my.example.pollingMs", 120000);
    items.put("my.example.exampleStringProp", "my example string");

    ApplicationContext ctx = ApplicationContext.run(items);
    MyExampleConfigProperties props = ctx.getBean(MyExampleConfigProperties.class);

    assertEquals(120000, props.getPollingMs());
    assertEquals("my example string", props.getExampleStringProp());
    ctx.close();
  }
}
```

### Environment Information

MacOS, Java11, Gradle

### Version

3.0.1

**Comment by graemerocher** [comment]
Weird Lombok nonsense 🤷‍♂️

**Comment by dstepanov** [comment]
That's because MN will choose the first constructor to build the bean and Lombok is respecting the order of the annotations when generating them. Add `@Creator` to `@NoArgsConstructor`'s `onConstructor`
