### ISSUE TITLE
Inconsistent @Body handling in browser

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#618]
Body is occasionally lost when uploaded from browser

### Steps to Reproduce

See sample

### Expected Behaviour

Body handling should work

### Actual Behaviour

Occasional:

```
i.m.h.s.netty.RoutingInBoundHandler - Encoding emitted response object [ /command - Required argument [LoginCommand command] not specified] using codec: io.micronaut.jackson.codec.JsonMediaTypeCodec@3ee39da0
```

### Example Application

https://github.com/liwujun0513/micronaut_demo

**Comment by liwujun0513** [comment]
not only @Body annotation 。 I change the method to this. the problem happens too.

    @Consumes({MediaType.APPLICATION_FORM_URLENCODED, MediaType.APPLICATION_JSON})
    @Post(value = "/demo1")
    ModelAndView postDemo1(@Nullable String username,@Nullable String password,@Nullable  String jcaptcha) {
    // ModelAndView postDemo1(@Nullable @Body LoginCommand command) {

        System.out.println(username);
        System.out.println(password);
        System.out.println(jcaptcha);

        return new ModelAndView("login", CollectionUtils.mapOf("date", new Date()));
    }

**Comment by liwujun0513** [comment]
I found that ,when I use nginx to proxy the demo app, everything is ok.

**Comment by sdelamo** [comment]
I forked the repository and used `BUILD-SNAPSHOT`

https://github.com/grails-core-issues-forks/micronaut-core-issues-618

I believe it may have to do with static resources. If I disable them it works as expected: 

<img width="1939" alt="login_and_micronaut_demo____developer_github-issues_micronaut_demo__-_____src_main_resources_application_yml__micronaut_demo_main_" src="https://user-images.githubusercontent.com/864788/46013318-359ad100-c0cc-11e8-8071-1f252a1915c8.png">

If I enable them I get some request with empty body: 

<img width="2250" alt="item-0_and_displaysextra_and_item-0" src="https://user-images.githubusercontent.com/864788/46013876-c8883b00-c0cd-11e8-8f97-4c2dce613a05.png">
