### ISSUE TITLE
Double Content-Type header on missing header

### ISSUE THREAD

**Issue by konrad-kaminski** [micronaut-projects/micronaut-core#6192]
### Expected Behavior

Only one `Content-Type` header should be returned.

### Actual Behaviour

Two `Content-Type` headers are returned.

### Steps To Reproduce

Create a simple endpoint, e.g.
```kotlin
@Controller
class TestEndpoint {
    @Get("/test")
    fun test(@Header("test") testHeader: String) = testHeader
}
```

and run `curl -v http://localhost:8080/test`.

What you get is:
```
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /test HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< Content-Type: application/json
< date: Tue, 21 Sep 2021 13:55:00 GMT
< content-length: 175
< connection: keep-alive
< 
```

### Environment Information

JDK 11, MacOS

### Version

3.0.1

**Comment by konrad-kaminski** [comment]
The problem seems to come from the fact that `contentType` is assigned twice in [HateoasErrorResponseProcessor](https://github.com/micronaut-projects/micronaut-core/blob/v3.0.1/http-server/src/main/java/io/micronaut/http/server/exceptions/response/HateoasErrorResponseProcessor.java#L67): 
* once during a call to `body`,
* a second time during an explicit call to `contentType`.

**Comment by ashishkujoy** [comment]
I think the main issue is here, similar to this method other methods in this class like `headers`,  `contentLength` etc which says that they set the given header, in reality they add the given header resulting in duplicate headers. To fix this issue these `add` call should be replaced with `set`. 

Let me know if the proposed solution looks okay, I will submit a PR with fix.

https://github.com/micronaut-projects/micronaut-core/blob/eb313ad24d4087d1dadcfa7ec18c092d68c88c4c/http/src/main/java/io/micronaut/http/MutableHttpMessage.java#L130-L137

**Comment by konrad-kaminski** [comment]
The change that introduced this behaviour seems to be the one in [this commit](https://github.com/micronaut-projects/micronaut-core/commit/e1fc5113a8312f48ca991bbb6ccf7d0666be8d73#diff-64a34311eae49ad7bda0055ddbf671bfac7ec7bfbcfebe6a6b0fec7cc63b7ea9R349).

**Comment by jameskleeh** [comment]
@ashishkujoy Looks good to me. PR welcome. Also need a test
