### ISSUE TITLE
Filter annotation is missing patternStyle

### ISSUE THREAD

**Issue by JasonTypesCodes** [micronaut-projects/micronaut-core#6193]
### Expected Behavior

The [3.0.1 User Guide](https://docs.micronaut.io/3.0.1/guide/index.html) states:
> The Filter annotation can use different styles of pattern for path matching by setting the patternStyle member. The supported options include Ant and Regex based matching.

From that, I expect `patternStyle` to be available on Filter

### Actual Behaviour

`patternStyle` is not available on [Filter](https://docs.micronaut.io/3.0.1/api/io/micronaut/http/annotation/Filter.html)

### Environment Information

OS: Debian Linux 10
JDK: openjdk version "11.0.12" 2021-07-20

### Version

3.0.1

**Comment by ilopmar** [comment]
I think this is the related PR: https://github.com/micronaut-projects/micronaut-core/pull/5954. It is included in 3.1.x but not in 3.0.x
