### ISSUE TITLE
Kotlin's default interface methods aren't recognized as default

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-core#6196]
### Expected Behavior

`TypeElementVisitor` is visiting default methods with `isDefault` true

### Actual Behaviour

`TypeElementVisitor` is visiting default methods with `isDefault` false

### Version

3.0.1

**Comment by jameskleeh** [comment]
@dstepanov What is the issue here? KAPT is not marking them as default?

**Comment by dstepanov** [comment]
I haven’t investigated yet

**Comment by jameskleeh** [comment]
@dstepanov This should probably be left open to ensure it gets handled with KSP

**Comment by altro3** [comment]
@dstepanov is it already fixed?

**Comment by dstepanov** [comment]
Yeah
