### ISSUE TITLE
Multiple @QueryValue in client doesn't build the correct url

### ISSUE THREAD

**Issue by adrien-bonnin-cbp** [micronaut-projects/micronaut-core#620]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a controller with a method with multiple @QueryValue

```
package example.micronaut

import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get
import io.micronaut.http.annotation.QueryValue

@Controller("/hello")
class HelloController {

    @Get
    String index(@QueryValue String name, @QueryValue String surname) {
        return "Hello $name $surname"
    }
}
```

2. Create a client to this controller and method

```
package example.micronaut

import io.micronaut.http.annotation.Get
import io.micronaut.http.annotation.QueryValue
import io.micronaut.http.client.Client
import io.reactivex.Single

@Client("/hello")
interface HelloClient {

    @Get
    Single<String> hello(@QueryValue name, @QueryValue surname);
}
```

3. Create a specification to test the method

```
package example.micronaut

import io.micronaut.context.ApplicationContext
import io.micronaut.runtime.server.EmbeddedServer
import spock.lang.AutoCleanup
import spock.lang.Shared
import spock.lang.Specification

class HelloClientSpec extends Specification {

    @Shared
    @AutoCleanup
    EmbeddedServer embeddedServer =
            ApplicationContext.run(EmbeddedServer)

    @Shared
    HelloClient client = embeddedServer
            .applicationContext
            .getBean(HelloClient)


    void "test hello world response"() {
        expect:
        client.hello('John', 'Doe').blockingGet() == "Hello John Doe"
    }
}
```

4. Launch the specification and check in the output that build url has no '&' character between parameters
```
GET /hello/?name=Johnsurname=Doe (Bad Request): Required argument [String surname] not specified
```

### Expected Behaviour

When a client has a method with multiple @QueryValue parameters the build url should have those parameter separated by '&' character.
```
/hello/?name=John&surname=Doe
```

### Actual Behaviour

Parameters are not separated by '&' character.
```
/hello/?name=Johnsurname=Doe 
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.0.0.M4
- **JDK Version:** 1.8

### Example Application

- https://github.com/adrien-bonnin-cbp/micronaut-issue-queryvalue

**Comment by graemerocher** [comment]
Although this is a bug, a better way to do this is use a URI template:

```java
@Get("{?name,surname}")
Single<String> hello(String name, @String surname);
```

Which will likely give you the behaviour you are after. We will look into the issue with `@QueryValue`
