### ISSUE TITLE
S3 multipart upload: StramingFileUpload and PartData chunks minimum size

### ISSUE THREAD

**Issue by bacca87** [micronaut-projects/micronaut-core#6225]
### Issue description

I need to upload large files on AWS S3 using multipart upload and i encountered an issue regarding the minimum data chunk size required by S3.
When i try to upload a file using StreamingFileUpload i get the following error:

`S3Exception: Your proposed upload is smaller than the minimum allowed size (Service: S3, Status Code: 200, Request ID: ...`

After some searches i found that S3 service requires that the PartData must be at least 5 MB in size:

[AWS S3 upload part documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html):
> Part numbers can be any number from 1 to 10,000, inclusive. A part number uniquely identifies a part and also defines its position within the object being created. If you upload a new part using the same part number that was used with a previous part, the previously uploaded part is overwritten. **Each part must be at least 5 MB in size**, except the last part. There is no size limit on the last part of your multipart upload. 

Micronaut multipart configuration doesn't have the possibility to set a minimum data chunk size, so i'm here to ask if someone can help me to achieve this.

Would be very useful to have the possibility to set the minimum data chunk size from yaml:
```
server:
  multipart:
     max-file-size: 500MB
     min-part-size: 5MB  <---- something like that
```

**Comment by jameskleeh** [comment]
I don't see this as a feature we should implement. You can buffer the data yourself

**Comment by bacca87** [comment]
I understand your point of view, but does it make sense to produce more than 600 PartData for a file of 6MB? 
I'm not an expert in the field, but if AWS puts a limit on this data chunks, maybe they have good reasons to do that...

**Comment by graemerocher** [comment]
Not tried but you may be able to configure the Netty channel option to alter the receive buffer size https://netty.io/4.1/api/io/netty/channel/ChannelOption.html#SO_RCVBUF using `micronaut.server.netty.child-options`

see https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration

Note that globally configuring a buffer size that large may impact other aspects of performance.

The alternative is to use `ChannelPipelineCustomizer` that adds a `ChannelHandler` that aggregates byte buffers until they are a certain size. See https://netty.io/4.1/api/io/netty/handler/codec/MessageAggregator.html

**Comment by bacca87** [comment]
Thanks for the tips, but at the moment i used an easier way to achieve that: Flux.bufferUntil() It does the job to buffer the parts and then send it to the S3 bucket. I can share my code if it can help.

**Comment by graemerocher** [comment]
Would be great so others know how to find a solution
