### ISSUE TITLE
Error in `IntrospectedTypeElementVisitor` with Micronaut 3.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#6228]
### Expected Behavior

It should work without any error using Micronaut 3.1.0 as it works with 3.0.x

### Actual Behaviour

The Micronaut jOOQ GraalVM application fails during compilation with the error:

```
> Task :compileJava
error: Error finalizing type visitor [io.micronaut.inject.beans.visitor.IntrospectedTypeElementVisitor@3242e5de]: Index: 0, Size: 0
Note: Writing reflect-config.json file to destination: META-INF/native-image/example.jooq/micronaut-jooq-graal/reflect-config.json
1 error

> Task :compileJava FAILED

FAILURE: Build failed with an exception.
```

### Steps To Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-jooq-graal`
- `cd micronaut-jooq-graal`
- `git checkout 3.1.x_h2`
- `./gradlew classes`

### Environment Information

JDK 8 & 11

### Version

3.1.0-SNAPSHOT

**Comment by dstepanov** [comment]
This should be fixed by https://github.com/micronaut-projects/micronaut-core/pull/6227

**Comment by ilopmar** [comment]
Thanks. I've tried locally and it works now :)
