### ISSUE TITLE
shareNext() doesn't work for controller input body as Flux<byte[]> 

### ISSUE THREAD

**Issue by denis111** [micronaut-projects/micronaut-core#6239]
### Expected Behavior

I'd like to take first bytes of input body to process it but then read whole input body of Flux<byte[]>:

```java
  @Put(consumes = MediaType.ALL)
  @Produces(MediaType.APPLICATION_JSON)
  public Mono<String> upload(@Body final Flux<byte[]> content) {
    return content.shareNext()
        .map(bytes -> {
          System.out.println("First bytes: " + new String(bytes, StandardCharsets.UTF_8));
          return "ok";
        }).flatMap(o -> content.reduce(System.out, (printStream, bytes) -> {
          printStream.println("bytes: " + new String(bytes, StandardCharsets.UTF_8));
          return printStream;
        }).then(Mono.just("ok")));
  }
```

Calling `curl -X PUT -T build.gradle http://localhost:8080/test` should return "ok".

I'm nor sure if it's really a bug or intended behaviour, in the latter case how could I then do multicasting the input flux to multiple consumers without putting all the input request to memory or file?

### Actual Behaviour

It returns 500 with `{"message":"Internal Server Error","_links":{"self":{"href":"/test","templated":false}},"_embedded":{"errors":[{"message":"Internal Server Error: Only one subscriber allowed"}]}}`
Stacktrace:
```
java.lang.IllegalStateException: This publisher only supports one subscriber
	at io.micronaut.http.netty.reactive.HandlerPublisher.subscribe(HandlerPublisher.java:127)
	at io.micronaut.http.netty.stream.DelegateStreamedHttpRequest.subscribe(DelegateStreamedHttpRequest.java:55)
	at io.micronaut.http.server.netty.DefaultHttpContentProcessor.subscribe(DefaultHttpContentProcessor.java:70)
	at io.micronaut.http.server.netty.binders.PublisherBodyBinder.lambda$null$0(PublisherBodyBinder.java:82)
	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:67)
```

### Steps To Reproduce

1. Download an example application
2. Run it
3. Execute `curl -X PUT -T build.gradle http://localhost:8080/test`

### Environment Information

OS: Linux
JDK: 11

### Example Application

https://github.com/denis111/micronaut-flux-share-issue

### Version

3.0.2

**Comment by jameskleeh** [comment]
It is only possible to support a single subscriber when reading the request body. I don't know the specifics of your requirements but you can buffer the data locally

**Comment by denis111** [comment]
@jameskleeh the specifics is validate incoming byte stream at the same time of saving the stream to file. We already do the same successfully with InputStream using PipedOutputStream. Is there anything similar for flux, like multicasting? Should I read flux in one subscriber to form another flux which supports share/publish?

**Comment by jameskleeh** [comment]
Why can't you do the validation and save in the same handler?

```
content.subscribe(data -> {
//validate
//save
})
```

**Comment by denis111** [comment]
@jamescookie there's multiple validators, I guess I must form another fluxes. Basically I guess, I need something like JavaScript's promises/pipe functionality. And if something is wrong, break the pipe.

**Comment by denis111** [comment]
Ok, I've achieved desired behaviour this way, if somebody is interested:
```java
  @Put(consumes = MediaType.ALL)
  @Produces(MediaType.APPLICATION_JSON)
  public Mono<String> upload(@Body final Flux<byte[]> content) {
    final var newFlux = Flux.<byte[]>create(fluxSink ->
            content.subscribe(fluxSink::next, fluxSink::error, fluxSink::complete))
        .publish(1)
        .autoConnect();

    return newFlux.shareNext()
        .map(bytes -> {
          System.out.println("First bytes: " + new String(bytes, StandardCharsets.UTF_8));
          return Mono.just(bytes);
        }).flatMap(o -> Flux.merge(o, newFlux).reduce(System.out, (printStream, bytes) -> {
          printStream.println("bytes: " + bytes.length);
          return printStream;
        })).then(Mono.just("ok"));
  }
```
I've updated the example repo. The only strange thing here is I thought that shareNext() will "share" the next element without removing it from the source Flux but it doesn't, so I did Flux.merge to have this first element "shared" later.
