### ISSUE TITLE
UriBuilder/UriTemplate.PATTERN_FULL_URI: Query Parameters Parsed as Part of Path

### ISSUE THREAD

**Issue by DMouse10462** [micronaut-projects/micronaut-core#6246]
### Expected Behavior

When using `UriBuilder` to add query parameters to a URI that already has query parameters, the RegEx within `UriTemplate.PATTERN_FULL_URI` should recognize the query parameters as query parameters.

For example, `UriBuilder.of("https://google.com/search?q=TESTING")` should interpret a `path` of `"/search"` and a `queryParams`  with the key/value pair of `[q: "TESTING"]`.

### Actual Behaviour

`DefaultUriBuilder(CharSequence uri)`, calling the PATTERN_FULL_URI matcher, returns the query portion of the URI as part of the path. 

For example, `UriBuilder.of("https://google.com/search?q=TESTING")` interprets a `path` of "/search?q=TESTING" and an empty map for `queryParams`. 

### Steps To Reproduce

1. Build the following:

```java
package example;

import io.micronaut.http.uri.UriBuilder;

public class Application {

    public static void main(String[] args) {
        String testUri = "https://google.com/search?q=Thisisatest";

        UriBuilder builder = UriBuilder.of(testUri);

        builder.queryParam("bad_param", "ThisIsInvalid");

        System.out.println(builder.toString());
    }
}
```
2. (Optional) Break at line 12 (`builder.queryParam(<snip>`) and observe empty map at `builder.queryParams`

3. Observe two question marks in results:
```
https://google.com/search?q=Thisisatest?bad_param=ThisIsInvalid
```

### Environment Information

Operating System: Windows 10 Version 20H2, Build 19042 (x86_64)
Java Version: 1.8

### Version

3.0.2

**Comment by ashishkujoy** [comment]
I would like to raise PR for this.

**Comment by ashwini-desai** [comment]
Since the above PR is still in draft, I would like to attempt this.

**Comment by Crow-EH** [comment]
Hi,

Is there any news on this issue ?

I just got it today, and something like changing `STRING_PATTERN_PATH = "([^#]*)"` to `STRING_PATTERN_PATH = "([^?#]*)"` seems to do the trick in this particular case, but it might break something else as @ashwini-desai said in https://github.com/micronaut-projects/micronaut-core/pull/6320.

**Comment by sdelamo** [comment]
I think this should be fixed via https://github.com/micronaut-projects/micronaut-core/pull/9635
