### ISSUE TITLE
NoSuchMethodError in io.micronaut.annotation.processing.visitor.JavaClassElement using 3.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#6267]
### Expected Behavior

A simple Micronaut application should compile.

### Actual Behaviour

When using latest 3.1.0-SNAPSHOT the application fails to compile with:

```
Execution failed for task ':compileJava'.
> java.lang.NoSuchMethodError: io.micronaut.annotation.processing.visitor.JavaClassElement.<init>(Ljavax/lang/model/element/TypeElement;Lio/micronaut/core/annotation/AnnotationMetadata;Lio/micronaut/annotation/processing/visitor/JavaVisitorContext;Ljava/util/Map;I)V
```

I think this error is related with the changes done in https://github.com/micronaut-projects/micronaut-core/pull/6230

### Steps To Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-basic-app`
- `cd micronaut-basic-app`
- `git checkout 3.1.x`
- `./gradlew run`

### Environment Information

Linux Mint 20.2 & JDK 8

### Version

3.1.0-SNAPSHOT

**Comment by graemerocher** [comment]
it is probably because `openapi` is using internal APIs again, we really need to move it away from that

**Comment by ilopmar** [comment]
Tracked in https://github.com/micronaut-projects/micronaut-openapi/issues/593
