### ISSUE TITLE
Error occurred running Micronaut CLI: unable to find valid certification path to requested target (Use --stacktrace to see the full trace)

### ISSUE THREAD

**Issue by FrankEndriss** [micronaut-projects/micronaut-core#627]
Error occurred running Micronaut CLI: unable to find valid certification path to requested target (Use --stacktrace to see the full trace)

### Steps to Reproduce

1. installed micronaut-1.0.0.M4 using sdk
2. mn

or

1. installed micronaut-1.0.0.M4 by downloading binary from micronaut.io
2. mn

### Expected Behaviour

mn should work like on linux

### Actual Behaviour
$ mn
Error |
Error occurred running Micronaut CLI: unable to find valid certification path to requested target (Use --stacktrace to see the full trace)

$mn --stacktrace
Error |
Error occurred running Micronaut CLI: unable to find valid certification path to requested target (Use --stacktrace to see the full trace)

### Environment Information

- **Operating System**: Windows 10 / Cygwin
- **Micronaut Version:** micronaut-1.0.0.M4
- **JDK Version:** 1.8.0_131

### Example Application

I wish I could create one.

**Comment by jameskleeh** [comment]
@FrankEndriss I can't reproduce this. Are you behind a proxy?

**Comment by jameskleeh** [comment]
@FrankEndriss If you have a local copy of the profiles then it would make sense that a snapshot version of the CLI would work since it falls back to local versions if remote ones cannot be found. 

The "unable to find valid certification path to requested target" comes from trying to make requests to resolve binaries for the profile. You can debug https://github.com/micronaut-projects/micronaut-core/blob/master/cli/src/main/groovy/io/micronaut/cli/profile/repository/MavenProfileRepository.groovy

**Comment by DuskoV** [comment]
This is still issue in the latest 1.0.3 version. We are having custom SSL cert which is used by firewall security. Custom SSL cert is properly installed in JDK (other applications don't have this issue).

I manually downloaded micronaut-1.0.3.zip and installed it on Windows machine. %MICRONAUT_HOME% and %PATH% Environments are correctly set.

**Comment by mboulatian** [comment]
Any resolution to this? it is micronaut-1.0.5 and still failing with the same issue

**Comment by mboulatian** [comment]
I am giving up on micronaut. No matter what I did, I cannot make mn working in windows behind corporate network. Asked for help, searched, posted on stackoverflow but no use. Back to other micro frameworks to recommend

**Comment by sf666** [comment]
Hi,

see #1115 

For MacOS:

```
export JAVA_OPTS="-Djavax.net.ssl.trustStoreType=KeychainStore -Djavax.net.ssl.trustStoreProvider=Apple"
```

**Comment by lucasaquiles** [comment]
I had the same problem using openjdk-ri@1.8.40 from the jabba. I solved that problem updating my jdk installation
