### ISSUE TITLE
Version 3.x Regression: Http client fails to deserialize `Mono` 

### ISSUE THREAD

**Issue by achaphiv** [micronaut-projects/micronaut-core#6272]
### Expected Behavior

As of v3.0.3.

I attempted to upgrade my app from 2.x to 3.x.

It broke on usages of `Mono`.

I expected it to work how it did in Micronaut v2.x with `micronaut-reactor-http-client`.

```java
@Client("https://google.com")
interface WhateverClient {
  @Get
  Mono<String> index();
}
```

### Actual Behaviour

Instead it causes this exception:

```text
class reactor.core.publisher.FluxOnErrorResume cannot be cast to class reactor.core.publisher.Mono (reactor.core.publisher.FluxOnErrorResume and reactor.core.publisher.Mono are in unnamed module of loader 'app')
java.lang.ClassCastException: class reactor.core.publisher.FluxOnErrorResume cannot be cast to class reactor.core.publisher.Mono (reactor.core.publisher.FluxOnErrorResume and reactor.core.publisher.Mono are in unnamed module of loader 'app')
  at com.example.IssueTest$WhateverClient$Intercepted.index(Unknown Source)
  at com.example.IssueTest.testItWorks(IssueTest.java:23)
```

### Steps To Reproduce

1. `git clone https://github.com/achaphiv/issue-micronaut-http-client-mono`
2. `./gradlew test`

### Environment Information

OS: Linux 5.14.7-2-MANJARO
Java: openjdk 11.0.12

### Example Application

https://github.com/achaphiv/issue-micronaut-http-client-mono

### Version

3.0.3

**Comment by jameskleeh** [comment]
`micronaut-reactor-http-client` is for injecting instances of `ReactorHttpClient`.  The `micronaut-reactor-http-client` dependency brings in `micronaut-reactor`, however you have neither of those dependencies on your classpath in that example application and that is why it doesn't work.

**Comment by achaphiv** [comment]
https://github.com/micronaut-projects/micronaut-reactor says:

> Micronaut Reactor adds support for Project Reactor to a Micronaut 2.x application

So is this actually still needed for 3.x? I thought the support was supposed to be built-in.

**Comment by jameskleeh** [comment]
Yes it is still needed. That documentation is out of date
