### ISSUE TITLE
h2c not supported by streaming client

### ISSUE THREAD

**Issue by yawkat** [micronaut-projects/micronaut-core#6282]
### Issue description

The h2c client does not currently support streaming responses. This is covered by the test cases marked 'pending' in #6270.

The cause of this issue is that the final `HttpStreamsHandler` is added to the end of the pipeline only after the h2c upgrade has completed. This means it is placed downstream from the handlers that are actually supposed to accept the `HttpResponse`. Those handlers never get the response they expect, and the streaming client is stuck forever.

**Comment by vitdolphin** [comment]
any plans to get this fixed?

**Comment by yawkat** [comment]
It was fixed by the client changes in 4.0, ive made a PR to enable the test cases.
