### ISSUE TITLE
HTTP validation message changed after migration to Micronaut 3

### ISSUE THREAD

**Issue by sergey-morenets** [micronaut-projects/micronaut-core#6297]
### Expected Behavior

The validation message was "provider.name: must not be blank" in Micronaut 2.5.0

### Actual Behaviour

Validation message is "Bad request" in Micronaut 3.0.3

### Steps To Reproduce

We have a pretty simple Micronaut application that contains the following DTO class:

```
@Getter
@Setter
public class PaymentProviderDTO {
	private String id;
	
	@NotBlank
	private String name;
}
```

and REST API, including POST handler:

```
	@Post
	public HttpResponse<?> create(@Valid @Body PaymentProviderDTO provider) {
```

We noticed that after migration to Micronaut 3 some of our tests are broken, for example:

```
		HttpClientResponseException ex = assertThrows(HttpClientResponseException.class,
				() -> client.toBlocking().exchange(HttpRequest.POST("", dto)));
		assertEquals(HttpStatus.BAD_REQUEST, ex.getStatus());
		assertEquals("provider.name: must not be blank", ex.getMessage());
```

Because the exception message now doesn't contain validation message. It seems that response body is empty so exception message is just "Bad request". Was it changed intentionally? We couldn't find any information in the documentation.

### Version

3.0.3

**Comment by sergey-morenets** [comment]
I created 2 demo projects using https://micronaut.io/launch and added simple controller with REST service:

```
@Controller("/")
@Validated
public class Controller {

    @Get
    public void get(@NotBlank String test) {
    }
}

```
And server response indeed has changed if validation failed. In Micronaut 2.5.0 server returned :

```
{
    "message": "Required argument [String test] not specified",
    "path": "/test",
    "_links": {
        "self": {
            "href": "/",
            "templated": false
        }
    }
}
```

In Micronaut 3.0.3 response is quite different:

```
{
    "message": "Bad Request",
    "_embedded": {
        "errors": [
            {
                "message": "Required argument [String test] not specified",
                "path": "/test"
            }
        ]
    },
    "_links": {
        "self": {
            "href": "/",
            "templated": false
        }
    }
}
```

I guess it should be reflected in the documentation.

**Comment by graemerocher** [comment]
It is, see https://docs.micronaut.io/latest/guide/#breaks and "Error Response Format"
