### ISSUE TITLE
Support H2C prior knowledge

### ISSUE THREAD

**Issue by yawkat** [micronaut-projects/micronaut-core#6301]
### Issue description

Micronaut does not appear to support h2c with prior knowledge. Also see https://curl.se/docs/http2.html and https://github.com/micronaut-projects/micronaut-core/issues/5005#issuecomment-935889902 . Netty does seem to have support, so it should be possible to implement.

**Comment by sgammon** [comment]
@yawkat i just wanted to note that Cloud Run's HTTP/2 support in GCP is predicated on `h2c` support, preventing micronaut users from flipping the HTTP/2 switch:

https://cloud.google.com/run/docs/configuring/http2#before_you_configure

**Comment by yawkat** [comment]
That's unfortunate. Weird that they have no TLS option.

**Comment by vitdolphin** [comment]
any plans to get this fixed?

**Comment by yawkat** [comment]
probably fairly easy with the changes in 4.0.0, but it won't be fixed before then

**Comment by vitdolphin** [comment]
when is the 4.0.0 coming out?

**Comment by yawkat** [comment]
probably early next year

**Comment by sgammon** [comment]
hey @yawkat... how's it going :)

we now need this for a new use case

**Comment by yawkat** [comment]
it's in the backlog

**Comment by sgammon** [comment]
@yawkat is there any way users could help with this?

**Comment by yawkat** [comment]
not really, though it doesn't seem super difficult to implement. all the pipeline setup is already there for alpn-based http2. it just needs the config options (a new plaintext mode for the client, and a new flag for the server listener configuration), some plumbing, and tests.
