### ISSUE TITLE
Implement general object storage abstraction for file upload / download

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#6307]
### Feature description

We should provide a general cloud abstraction over object storage implementations probably in a subproject under `micronaut-projects` to allow uploading and streaming files from object storage.

Possibly consider adding an optimized handler that bypasses Micronaut's regular router to handle streaming of files at the Netty layer

More detail to follow....

**Comment by goeh** [comment]
With https://github.com/micronaut-projects/micronaut-object-storage done this issue can be closed now?
