### ISSUE TITLE
@JsonSeralize annotation is ignored by GraalVM native image

### ISSUE THREAD

**Issue by r-darwish** [micronaut-projects/micronaut-core#6309]
### Expected Behavior

Putting a

```java
@JsonSerialize(using = ToStringSerializer.class)
```

on a field or should work as expected both in JVM and a GraalVM native image

### Actual Behaviour

When put on a field the annotation is ignored by GraalVM

### Steps To Reproduce

Annotate a field with `@JsonSerialize(using = ToStringSerializer.class)` and try to serailize it

### Environment Information

- Operating System: Windows (Native image was generated in WSL)
- JDK version: 11

### Example Application

https://github.com/r-darwish/jsonserialize-graal

### Version

3.0.3

**Comment by wimdeblauwe** [comment]
I have a very similar problem using `@JsonCreator`, something like this:

```
@Introspected
@JsonIgnoreProperties(ignoreUnknown = true)
public class AccessToken {
    @JsonProperty("access_token")
    private String accessToken;

    @JsonCreator
    public AccessToken(@JsonProperty("access_token") String accessToken) {
        this.accessToken = accessToken;
    }

    public String getAccessToken() {
        return accessToken;
    }
}
```

When creating the GraalVM version (on macOS) and running the command line tool (I'm using picocli), I get this:

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.company.app.auth.AccessToken` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
```

**Comment by graemerocher** [comment]
Try annotate the class with @ReflectiveAccess

**Comment by wimdeblauwe** [comment]
Does not help in my case (I'm using Micronaut 3.1.0 command line application with Maven project generated from the launch website)

**Comment by r-darwish** [comment]
@graemerocher  It did make a difference in my case, but instead of just not working now I get an exception:
```
Internal Server Error: Error encoding object [com.example.Result@47eb1a6e] to JSON: Class com.fasterxml.jackson.databind.ser.std.ToStringSerializer has no default (no arg) constructor
```

**Comment by graemerocher** [comment]
@yawkat we may need to modify the `GraalTypeElementVisitor` to generate reflection entries for serializers / deserializers to make this work for Jackson

**Comment by yawkat** [comment]
This looks like two separate issues that I will address separately:

- [x] `BeanIntrospectionModule` without reflection ignores `@JsonSerialize`
- [ ] A class passed to `@JsonSerialize` should automatically get the constructor included in graal reflective access

**Comment by wimdeblauwe** [comment]
Should this be fixed in version 3.1.4 ?

**Comment by graemerocher** [comment]
@wimdeblauwe should be, you seeing anything different? If so provide an example

**Comment by wimdeblauwe** [comment]
Yes, does not seem to be fixed. I created an example here: https://github.com/wimdeblauwe/jackson-native-image-issue See README for details.

**Comment by yawkat** [comment]
@wimdeblauwe are you sure this is the same issue? Your reproducer does not have `@JsonSeralize`

**Comment by wimdeblauwe** [comment]
Maybe I misunderstood the issue. Do you want me to create a new issue for the problem in my example?

**Comment by yawkat** [comment]
yes please, I will look at it in detail tomorrow and see if it's related

**Comment by wimdeblauwe** [comment]
Ok, https://github.com/micronaut-projects/micronaut-core/issues/6528 created
