### ISSUE TITLE
Micronaut bom 3.1.0 kafka version hard coded

### ISSUE THREAD

**Issue by nkwiatkowski** [micronaut-projects/micronaut-core#6330]
### Feature description

Hello.
I am using micronaut framework on microservices who use kafka, but we use our custom kafka classes, not micronaut kafka.
Until micronaut 3, we where able to change kafka version thanks to the variable kafka.version.
But in the 3.1.0 bom, the kafka version parameter is still present, but not used.
```xml
<dependency>
  <groupId>org.apache.kafka</groupId>
  <artifactId>kafka-clients</artifactId>
  <version>2.8.0</version>
</dependency>
<dependency>
  <groupId>org.apache.kafka</groupId>
  <artifactId>kafka-streams</artifactId>
  <version>2.8.0</version>
 </dependency>
<dependency>
  <groupId>org.apache.kafka</groupId>
  <artifactId>kafka_2.12</artifactId>
  <version>2.8.0</version>
</dependency>
```
Is there a reason to hard code the kafka version ? and if not, is it possible to use the kafka.version parameter ?

**Comment by fabmars** [comment]
I concur, this might be annoying to me too.

**Comment by graemerocher** [comment]
@melix it looks like the BOM is not generated correctly and is not using the versions defined in the properties to reference the actual versions. Could you take a look?

See the difference between 

https://search.maven.org/artifact/io.micronaut/micronaut-bom/3.1.0/pom

and 

https://search.maven.org/artifact/io.micronaut/micronaut-bom/2.5.12/pom

Impacts all dependencies not just Kafka it seems.
