### ISSUE TITLE
`@Cacheable` beans creating in `@Factory` doesn't get cached

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#6352]
### Expected Behavior

I'm not 100% sure if this should work or not but a user could expect that a bean created from a `@Factory` could be used with `@Cacheable` the same way if no factory is involved.

### Actual Behaviour

Given the following POJO:

```java
public class FooApi {

    AtomicInteger counter = new AtomicInteger(0);

    @Cacheable("counter")
    public Integer counter() {
        return counter.incrementAndGet();
    }
}
```

And a factory to create a bean out of it:

```java
@Factory
public class FooFactory {

    @Singleton
    FooApi foo() {
        return new FooApi();
    }
}
```

And the following controller:

```java
@Controller
public class FooController {

    private final FooApi fooApi;

    public FooController(FooApi fooApi) {
        this.fooApi = fooApi;
    }

    @Get("/counter")
    public Integer counter() {
        return fooApi.counter();
    }
}
```

When sending multiple curl requests to `localhost:8080/counter` the expected out would be always `1` but I get `1`, `2`, `3`,...

If I comment out the code in the factory and annotate `FooApi` with `@Singleton` it works as expected.

### Environment Information

Linux Mint / Java 11

### Version

3.1.0

**Comment by graemerocher** [comment]
Don't think this is a bug, since you are directly creating the instance it cannot be managed by Micronaut

**Comment by ilopmar** [comment]
Right, that makes sense. But on the other hand, once the factory returns the object, it becomes a Micronaut managed bean, so I though that could work somehow...

**Comment by jameskleeh** [comment]
If you have the ability to use Micronaut annotations on the type then there in the vast majority of cases should be no need for a factory. You can use AOP on the factory method and it will apply to the methods on the returned bean but it would apply to all methods.
