### ISSUE TITLE
Missing JavaDoc for newer versions

### ISSUE THREAD

**Issue by FilipJirsak** [micronaut-projects/micronaut-core#6355]
JavaDoc for version **3.0.2**, **3.0.3** and **3.1.0** is missing. There are links to versions **3.0.2** and **3.0.3** on the page https://micronaut.io/docs/ in section „DOCUMENTATION OF OLDER VERSIONS“, but the server responds 404 Not Found. Version **3.1.0** is the latest version, but https://docs.micronaut.io/latest/api/ shows API of version **3.0.1**.

**Comment by graemerocher** [comment]
@melix could you look at why / how our javadoc publishing infra broke?

**Comment by melix** [comment]
The generated aggregating javadoc was broken between releases [4.1, 4.2[ of the internal Micronaut build plugin. We should upgrade to the latest and it should fix this problem.

Broken: https://ge.micronaut.io/s/3bavjpaanylwi/timeline?task-path=javadoc#ijmqzulpchnyk
Fixed: https://ge.micronaut.io/s/g24dh3ud5qpgi/timeline?task-path=:javadoc#ijmqzulpchnyk
