### ISSUE TITLE
Using segment separator --- inside application.yml

### ISSUE THREAD

**Issue by wapgui** [micronaut-projects/micronaut-core#636]
Using the segment separator --- inside an application.yml causes problems wich ends in exceptions.

E.g:
@Scheduled(fixedDelay = "${worker.rate:1s}", initialDelay = "${worker.delay:1s}")
works so far
@Scheduled(fixedDelay = "${worker.rate}", initialDelay = "${worker.delay}")
doesn't works
If --- are removed second version without defaults are working too.
application.yml entries:

#--- remove this separator
worker:
    clean:
        rate: ${CLEAN_FIXED_RATE:10s}
        delay: ${CLEAN_INITIAL_DELAY:1s}

Variables are set via docker environment.

**Comment by jameskleeh** [comment]
@wapgui There isn't enough information here for me to determine any issue. Please upload an example project that demonstrates the issue with steps to reproduce

**Comment by jameskleeh** [comment]
Closing due to lack of feedback
