### ISSUE TITLE
Repository classes generated from annotation processor crashing with invalid bytecode 

### ISSUE THREAD

**Issue by safarmer** [micronaut-projects/micronaut-core#6371]
### Expected Behavior

I have a simple Micronaut DATA JDBC repository with an override for the `deleteById` method. In this example, it is for marking an entity as deleted by setting a flag or field rather than deleting the row. I have tried with records and POJOs for the entity class. I have also seen the error on an overridden `save` repository method.

The code works as expected if I remove the override of `deleteById` or when I switch to Micronaut 3.0.3. It started breaking in 3.1.0.

### Actual Behaviour

The test crashes with `java.lang.VerifyError`
```
        java.lang.VerifyError: Operand stack underflow
        Exception Details:
          Location:
            com/example/SavedContentRepository$Intercepted.deleteById(Ljava/lang/Object;)V @8: checkcast
          Reason:
            Attempt to pop empty stack.
          Current Frame:
            bci: @8
            flags: { }
            locals: { 'com/example/SavedContentRepository$Intercepted', 'java/lang/Object' }
            stack: { }
          Bytecode:
            0000000: 2a2b c000 3eb7 0040 c000 42b1           
            at com.example.$SavedContentRepository$Intercepted$Definition.build(Unknown Source)
            at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2341)
            ... 90 more
```

When I open the compiled class `SavedContentRepository$Intercepted.class` the `deleteById` method seems to have issues decompiling.

```java
  public void deleteById(Object param1) {
    // $FF: Couldn't be decompiled
  }
```

The output for this method from `javap -c -p -s`:
```java
  public void deleteById(java.lang.Object);
    descriptor: (Ljava/lang/Object;)V
    Code:
       0: aload_0
       1: aload_1
       2: checkcast     micronaut-projects/micronaut-data#62                 // class java/lang/Integer
       5: invokespecial micronaut-projects/micronaut-data#64                 // Method deleteById:(Ljava/lang/Integer;)V
       8: checkcast     micronaut-projects/micronaut-data#66                 // class java/lang/Void
      11: return
```

### Steps To Reproduce

Tested on a Linux machine:
1. checkout example application https://github.com/safarmer/bytecode-errors
2. ./gradlew check --info
3. Observe crash in log

### Environment Information

- Micronaut 3.1.x (works fine on 3.0.3)
- Fedora Linux 35
- Java from Gradle toolchain 11, 15, 16, and 17
- When using Java records or classes for the mapped entity (there is a branch with the POJO version)

### Example Application

https://github.com/safarmer/bytecode-errors

### Version

3.1.1

**Comment by graemerocher** [comment]
@dstepanov seems `void` returns types are not being handled correctly after the change to fix method dispatch

**Comment by dstepanov** [comment]
Looks like there is an extra cast check for the void
