### ISSUE TITLE
Error building Micronaut app with Turbine

### ISSUE THREAD

**Issue by sgammon** [micronaut-projects/micronaut-core#6381]
### Expected Behavior

[Turbine](https://github.com/google/turbine) is a header compiler for Java, written by Google. It is supported by [Bazel](https://bazel.build) via the CLI flag [`--[no]java_header_compilation`](https://docs.bazel.build/versions/main/command-line-reference.html#flag--java_header_compilation).

When building a Micronaut app via Bazel with Turbine enabled, the build should succeed, but instead it fails

Cross-filed with Bazel at bazelbuild/bazel#14142

### Actual Behaviour

**Code path:**
- In `TypeElementVisitorProcessor.java` ([L355](https://github.com/micronaut-projects/micronaut-core/blob/2.5.x/inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java#L355) in `2.5.x` and [L432](https://github.com/micronaut-projects/micronaut-core/blob/3.1.x/inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java#L432) in `3.1.x`), a call is made to `elementUtils.hides(...)`
- Over in Turbine, at [`TurbineElements.java#L293`](https://github.com/google/turbine/blob/main/java/com/google/turbine/processing/TurbineElements.java#L293), `UnsupportedOperationException` is thrown.
- The build fails.

**Full error:**
```
(11:24:19) ERROR: /Volumes/VANTAGE/Elide/java/gust/backend/runtime/BUILD.bazel:35:18: Compiling Java headers java/gust/backend/runtime/libAssetManager-hjar.jar (1 source file) and running annotation processors (BeanDefinitionInjectProcessor, TypeElementVisitorProcessor, PackageConfigurationInjectProcessor, ServiceDescriptionProcessor) failed: (Exit 1): java failed: error executing command 
  (cd /private/var/tmp/_bazel_sam.g/775b6236ff3326c82265b1ae5a23b488/sandbox/darwin-sandbox/1636/execroot/gust && \
  exec env - \
    LC_CTYPE=en_US.UTF-8 \
    PATH=/bin:/usr/bin:/usr/local/bin \
  external/remotejdk11_macos/bin/java -Xverify:none '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED' '--patch-module=java.compiler=external/remote_java_tools_darwin/java_tools/java_compiler.jar' '--patch-module=jdk.compiler=external/remote_java_tools_darwin/java_tools/jdk_compiler.jar' '--add-opens=java.base/java.nio=ALL-UNNAMED' '--add-opens=java.base/java.lang=ALL-UNNAMED' -jar external/remote_java_tools/java_tools/turbine_direct_binary_deploy.jar @bazel-out/darwin-fastbuild/bin/java/gust/backend/runtime/libAssetManager-hjar.jar-0.params @bazel-out/darwin-fastbuild/bin/java/gust/backend/runtime/libAssetManager-hjar.jar-1.params)
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
<>: error: Creating bean classes for 1 type elements

<>: error: An exception occurred in io.micronaut.annotation.processing.TypeElementVisitorProcessor:
java.lang.UnsupportedOperationException
	at com.google.turbine.processing.TurbineElements.hides(TurbineElements.java:293)
	at io.micronaut.annotation.processing.TypeElementVisitorProcessor$ElementVisitor.checkFieldHide(TypeElementVisitorProcessor.java:355)
	at io.micronaut.annotation.processing.TypeElementVisitorProcessor$ElementVisitor.enclosedElements(TypeElementVisitorProcessor.java:341)
	at io.micronaut.annotation.processing.TypeElementVisitorProcessor$ElementVisitor.visitType(TypeElementVisitorProcessor.java:319)
	at com.google.turbine.processing.TurbineElement$TurbineTypeElement.accept(TurbineElement.java:468)
	at io.micronaut.annotation.processing.TypeElementVisitorProcessor.process(TypeElementVisitorProcessor.java:195)
	at com.google.turbine.binder.Processing.process(Processing.java:180)
	at com.google.turbine.binder.Binder.bind(Binder.java:107)
	at com.google.turbine.main.Main.bind(Main.java:260)
	at com.google.turbine.main.Main.fallback(Main.java:235)
	at com.google.turbine.main.Main.compile(Main.java:172)
	at com.google.turbine.main.Main.compile(Main.java:133)
	at com.google.turbine.main.Main.main(Main.java:89)
```

### Steps To Reproduce

1. `git clone git@github.com:sgammon/elide.git -b turbine-repro && cd ./elide`
2. build via `bazel build //java/...`
3. after a short time, the error above is thrown

### Environment Information

- Micronaut Version: `2.5.12`
- Bazel Version: `4.2.1` (latest)
- Bazel Java Tools Version: `11.5` (latest)
- Operating System: macOS Big Sur 11.6
- JDK Version: Zulu JDK 11 latest at time of writing:
```
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)
```

### Example Application

https://github.com/sgammon/elide

### Version

2.5.12

**Comment by jameskleeh** [comment]
I don't see this as an issue with Micronaut

**Comment by sgammon** [comment]
@jameskleeh i've filed in both places because i'm not entirely sure how Micronaut is using this call. is it possible to simply suppress / wrap this exception? or is this a call which is required for proper operation of Micronaut's DI?

**Comment by sgammon** [comment]
(and thank you for your quick response)

**Comment by graemerocher** [comment]
It is requires for proper functioning of DI and handling of method inheritance. Not sure why Turbine is breaking the annotation processing API by overriding its capability to detect method overrides and throwing `UnsupportedOperationException`. It shouldn't be doing that.

**Comment by sgammon** [comment]
@graemerocher looks like google will be fixing in an upcoming update of `remote_java_tools`. thank you for explaining 👍🏻
