### ISSUE TITLE
Json annotation partially broken

### ISSUE THREAD

**Issue by hbxu** [micronaut-projects/micronaut-core#6387]
### Expected Behavior

(Native-image)
curl http://localhost:8080/hello
{"name":"james","age":0,"_links":{"self":{"href":"http://test.com","templated":false,"title":"title"}}}

### Actual Behaviour

(Native-image)
curl http://localhost:8080/hello
{"name":"james","age":0,"_links":{"self":{"href":"http://test.com","templated":false,"type":null,"deprecation":null,"profile":null,"name":null,"title":"title","hreflang":null}},"_embedded":{}}

### Steps To Reproduce

1. Run locally non-native
2. Behavior is expected, null fields are left out (expected)
3. Run docker with native image
4. Behavior is unexpected null fields are shown in Link object, TestModel is working as expected

### Environment Information

- Windows 10
- Docker for Desktop 4.1.1

### Example Application

https://github.com/hbxu/testcase_micronaut_json_graalvm

### Version

3.1.1

**Comment by graemerocher** [comment]
@yawkat please take a look

**Comment by yawkat** [comment]
This looks exactly like #6205 which should have been fixed by #6214, weird

**Comment by yawkat** [comment]
Actually more related to #6219. Will fix.
