### ISSUE TITLE
Micronaut bom calling non existent Netty package

### ISSUE THREAD

**Issue by acusworth** [micronaut-projects/micronaut-core#6404]
### Expected Behavior

Micronaut bom should list:
```
<dependency>
<groupId>io.netty</groupId>
<artifactId>netty-all</artifactId>
<version>${netty.version}</version>
</dependency>
```
Netty was moved to Netty-all after version 3.10.6.Final
Alternative is to return to the use of netty bom.

### Actual Behaviour

Micronaut bom lists:
```
<dependency>
<groupId>io.netty</groupId>
<artifactId>netty</artifactId>
<version>${netty.version}</version>
</dependency>
```

This results in:
```
   > Could not find io.netty:netty:4.1.69.Final.
     Searched in the following locations:
       - file:/Users/user1/.m2/repository/io/netty/netty/4.1.69.Final/netty-4.1.69.Final.pom
       - https://nexus3.corp.internal.com/repository/maven-central/io/netty/netty/4.1.69.Final/netty-4.1.69.Final.pom
       - https://nexus3.corp.internal.com/repository/maven-releases/io/netty/netty/4.1.69.Final/netty-4.1.69.Final.pom
       - https://nexus3.corp.internal.com/repository/confluent/io/netty/netty/4.1.69.Final/netty-4.1.69.Final.pom
     Required by:
         project :service > io.micronaut:micronaut-bom:3.1.1
```

### Steps To Reproduce

1. Set up micronaut project in Gradle using micronaut bom.
2. Set version micronaut version 3.1.1
3. Build

### Environment Information

- JDK 11
- Gradle 6.8.3

### Version

3.1.1

**Comment by devmage** [comment]
I think the following line is the issue: https://github.com/micronaut-projects/micronaut-core/blob/3.1.x/gradle/libs.versions.toml#L278

I'd imagine that removing it would resolve the import issue in a later Micronaut BOM release.

**Comment by devmage** [comment]
A related issue found on review, some dependencies that are provided by BOMs appear to have a library dependency at a specific version. I believe the BOM for those dependencies should provide the version, and the Micronaut BOM should not include a version. Netty is an example of this behavior. Jackson is another example:

```xml
<dependency>
<groupId>com.fasterxml.jackson</groupId>
<artifactId>jackson-bom</artifactId>
<version>2.12.4</version>
<type>pom</type>
<scope>import</scope>
</dependency>
```
but then later:
```xml
<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-annotations</artifactId>
<version>${jackson.version}</version>
</dependency>
```
Additionally, in the above example, it's strange that the Jackson BOM has a version directly rendered, instead of using the `jackson.version` variable as the later dependency does.

Reference: https://repo1.maven.org/maven2/io/micronaut/micronaut-bom/3.1.1/micronaut-bom-3.1.1.pom

**Comment by graemerocher** [comment]
@melix can you take a look?

**Comment by graemerocher** [comment]
@melix we used to have a BOM validation task that checked all dependencies resolve, was this perhaps removed by mistake?

**Comment by melix** [comment]
The task is here (`checkBoms`) but I have found a bug in the implementation which caused this to go unnoticed. Working on a fix.
