### ISSUE TITLE
Allow AnnotationMapper to work without loading annotation classes

### ISSUE THREAD

**Issue by lightoze** [micronaut-projects/micronaut-core#641]
Currently annotation classes manipulated by `AnnotationMapper` have to be in annotation processor classpath. When such annotations are located in a dedicated JAR files with little extra dependencies (e.g. `javax.persistence:javax.persistence-api:2.2`) this is not a big problem. However sometimes annotations are part of a bigger artifact which makes annotation processor classpath unreasonably big.

The suggestion is to change AnnotationMapper to operate annotation class names instead. This will eliminate the need to have those extra dependencies on the classpath. Also it will simplify build management for the end user.

Current AnnotationMapper API can be still provided with an adapter class.

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/commit/4b1ce776a76397f8d97d3479db867b44c7935c85
