### ISSUE TITLE
ReadTimeoutException testing authentication: cookie using junit5

### ISSUE THREAD

**Issue by asautins** [micronaut-projects/micronaut-core#6417]
### Expected Behavior

Using the following application.yml:

```
micronaut:
  security:
    authentication: cookie
```
and the following AuthenticationProvider

```
@Singleton
public class AuthenticationProviderUserPassword implements AuthenticationProvider {
    @Override
    public Publisher<AuthenticationResponse> authenticate(@Nullable HttpRequest<?> httpRequest,
                                                          AuthenticationRequest<?, ?> authenticationRequest) {
        return Flux.create(emitter -> {
                emitter.next(AuthenticationResponse.success((String) authenticationRequest.getIdentity()));
                emitter.complete();
        }, FluxSink.OverflowStrategy.ERROR);
    }
}
```

Running the following unit test:

```
    @Test
    void testAuth() {
        HttpRequest request = HttpRequest.POST("/login", new UsernamePasswordCredentials("user", "pass"));
        HttpResponse<BearerAccessRefreshToken> rsp = client.toBlocking().exchange(request, BearerAccessRefreshToken.class);
        assertEquals(HttpStatus.OK, rsp.getStatus());
    }
```
The expected behavior is the test passes successfully.

### Actual Behaviour

The above code results in the following error:

`io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
`

Note it runs successfully with authentication: bearer.

This appears to be due to the netty event loop.  The bearer authentication method only requests /login where the cookie authentication method requests /login and then re-directs to the success page.  The timeout appears to be waiting for the success page.

I attempted to create a secondary netty server for the HttpClient as described in the following without success

https://docs.micronaut.io/latest/guide/#secondaryServers

### Version

3.0.1

**Comment by asautins** [comment]
Note one workaround is to create a HttpClient disabling redirects:

```
    @BeforeEach
    void setup() {
        var config = new DefaultHttpClientConfiguration();
        config.setFollowRedirects(false);
        client = new DefaultHttpClient(server.getURL(), config);
    }
```

This allows the following test to pass:

```
    @Test
    void testAuth() {
        HttpRequest request = HttpRequest.POST("/login", new UsernamePasswordCredentials("user", "pass"));
        HttpResponse<BearerAccessRefreshToken> rsp = client.toBlocking().exchange(request, BearerAccessRefreshToken.class);
        assertEquals(HttpStatus.SEE_OTHER, rsp.getStatus());
    }
```

**Comment by graemerocher** [comment]
Seems something is broken in the client and it is not following the redirect

**Comment by graemerocher** [comment]
@yawkat could you take a look?

**Comment by yawkat** [comment]
Thanks for the report. Your description that the client was waiting for the new page was correct. It didn't get a response because it incorrectly copied the `Content-Length` header from the POST request, but did not copy the actual content, so the server was stuck waiting for the data and never responded.
