### ISSUE TITLE
Choose between `Customizer` and `Configurer`

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-core#6447]
### Issue description

For the new application context configuration mechanism, we have `@ContextConfigurer` (the annotation) and `ApplicationContextCustomizer` (the interface that types annotated with `@ContextConfigurer` need to implement).

We should probably choose between `Configurer` and `Customizer`. My preference would be to go with: `@ContextConfigurer` + `ApplicationContextConfigurer`. It's a bit sad we have to choose 2 names which look the same, for the same concept, but that's how it is...

**Comment by graemerocher** [comment]
Fine by me

**Comment by jameskleeh** [comment]
I don't have a preference either way as long as they are consistent
