### ISSUE TITLE
docker packaging not working with Java 17 and maven

### ISSUE THREAD

**Issue by mnebus** [micronaut-projects/micronaut-core#6456]
### Expected Behavior

GIven a brand new project generated from CLI or Launch with JDK_17 as the javaVersion
When you execute a `./mvnw clean package -Dpackaging=docker` build
It should complete successfully

### Actual Behaviour

```
[ERROR] Failed to execute goal io.micronaut.build:micronaut-maven-plugin:3.0.3-SNAPSHOT:docker-native (default-docker-native) on project inventory: To build native images you must set the Java target byte code level to Java 11 or below
```

This issue can be resolved by upgrading to a newer version of Jib (eg, `<jib-maven-plugin.version>3.1.4</jib-maven-plugin.version>`) and setting a JDK 17 compatible from image

### Steps To Reproduce

```
curl --location --request GET 'https://snapshot.micronaut.io/create/default/com.test?lang=JAVA&build=MAVEN&test=SPOCK&javaVersion=JDK_17' --output test.zip

unzip test.zip

cd test

./mvnw clean package -Dpackaging=docker
```

### Environment Information

Mac OS
JDK 17

### Version

3.1.1 and 3.1.2-SNAPSHOT

**Comment by ilopmar** [comment]
This will be fixed in #6465
