### ISSUE TITLE
Properties in @Named are not resolved

### ISSUE THREAD

**Issue by agsilvio** [micronaut-projects/micronaut-core#6467]
### Steps to Reproduce

1. Set up any example MN 3 project
2. Add these two classes

```
@Named("OINKY")
@Singleton()
public class A {
    public String thing = "aaaaaaaaaa";
}
```

```
@Singleton
public class B {

  @Inject
  @Named("${oink:iiiii}")
  Object oink;

  @EventListener
  public void onStartupEvent(StartupEvent event) {
    System.out.println(((A)oink).thing);
  }
}
```

3. Ensure this property is in `application.yml`

```
oink: OINKY
```

4. Configure the annotation processors in accordance with documentation

```
          <annotationProcessorPaths combine.self="override">
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
              <version>${lombok.version}</version>
            </path>
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-inject-java</artifactId>
              <version>${micronaut.version}</version>
            </path>
            <path>
              <groupId>io.micronaut</groupId>
              <artifactId>micronaut-validation</artifactId>
              <version>${micronaut.version}</version>
            </path>
          </annotationProcessorPaths>
```

### Expected Behaviour

The property expressed in `@Named` should resolve (just as in MN 2). The Bean should be found. If there is some problem resolving the property, the given default should be used.

### Actual Behaviour

The `@Named` annotation treats the given string as a literal (it does not treat it as a property). The error produced is:

```
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: 
No bean of type [java.lang.Object] exists for the given qualifier: @Named('${oink:iiiii}').
```

### Environment Information

- **Operating System**: MacOS BigSur
- **Micronaut Version:** 3.1.3
- **JDK Version:** 11

### Example Application

- everything needed is above. I haven't made a sample project.

**Comment by jameskleeh** [comment]
@agsilvio Unfortunately due to the optimizations we have done this functionality was lost. Fortunately there is a way for you to achieve the same thing, just slightly differently.

```
@Singleton
public class B {

  @Value("${oink:iiiii}")
  String name;

  @Inject
  BeanProvider<YourType> provider

  @EventListener
  public void onStartupEvent(StartupEvent event) {
    provider.get(Qualifiers.byName(name); // -> returns A
  }
}

**Comment by agsilvio** [comment]
Much appreciated. I will try this out. Thank you.
