### ISSUE TITLE
Jackson deserialization ignoring JsonProperty annotations

### ISSUE THREAD

**Issue by rsenden** [micronaut-projects/micronaut-core#6472]
### Expected Behavior

Given the class listed below, Jackson should properly deserialize the `access_token` and `expires_in` properties provided in the JSON input being deserialized, using the `BeanIntrospection` class generated through the `@Introspected` annotation.

```java
@Data @Introspected @JsonIgnoreProperties(ignoreUnknown = true)
public final class TokenResponse {
	private String accessToken;
	private long expiresAt;
	public String getAccessToken() {
		return accessToken;
	}
	@JsonProperty("access_token")
	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}
	@JsonProperty("expires_in")
	public void setExpiresIn(long expiresIn) {
		this.expiresAt = new Date().getTime()+((expiresIn-5)*1000);
	}
	public long getExpiresAt() {
		return expiresAt;
	}
	@JsonIgnore public boolean isExpired() {
		return new Date().getTime() > expiresAt;
	}
}
```

### Actual Behaviour

Jackson correctly deserializes the JSON data when running in a normal JVM, but not in a GraalVM native image. When running as a native image, it seems like Jackson doesn't see the `@JsonProperty` annotations and therefore the setters are not being invoked.

Not sure whether it's relevant, but the generated `$TokenResponse$IntrospectionRef` class only lists class-level annotations and not method-level annotations.

### Steps To Reproduce

1. Write a small sample program that deserializes a JSON object containing `access_token` and `expires_in` properties to an instance of the Java class listed under 'Expected Behavior', using the Micronaut-provided `ObjectMapper`
2. Run this program in a normal JVM, and see Jackson properly deserializing the JSON string
3. Run this program as a native GraalVM image, and see Jackson fail to properly deserialize the JSON string, failing to invoke the setters and leaving the instance fields at their default value

### Version

3.1.0

**Comment by yawkat** [comment]
Thanks for the report!

Unfortunately, fixing this would require changing the annotation behavior for bean properties. Right now, bean property scanning considers the annotations of the field, and if that isn't present, the annotations on the getter only. Expanding this to include annotations on the setter would require implementing some form of annotation merging, which is a can of worms we do not want to open. (Expanding the current behavior to setters does not work, because a bean property always has a getter or a field, or both.)

So while the difference to normal jackson behavior is a bug, the fix has some impact that is not worth it, because the workaround (placing the annotation on the getter) is so simple. If there is a good reason why you can't use this workaround, we might reconsider, but until then I will mark this wontfix.

**Comment by graemerocher** [comment]
It can go on the field or the getter. We do currently merge the metadata from the field and the getter, but like you said it is probably not worth considering the setter because then we would also need to consider the annotation on the setter parameter which complicates matters a great deal.

**Comment by yawkat** [comment]
@graemerocher Yea you're right, I misread the code. The merging happens in `getAnnotationMetadata(fieldElement, value.getter)`. So there is precedent for merging, and we could expand that to the setters.

I don't think we necessarily need to scan the param annotations though. At least for jackson annotations, they're usually on the method (except stuff like `@JsonCreator`).

**Comment by rsenden** [comment]
@yawkat @graemerocher In this particular example there is no field or getter for `expires_in` to which I could apply the `@JsonProperty` annotation. Based on the value of `expires_in` in the input JSON document, I calculate the value for the `expiresAt` property.

**Comment by graemerocher** [comment]
@yawkat the correct fix in that case is to fuse the metadata, I am actually hitting a similar issue with records and introspections at the moment

**Comment by yawkat** [comment]
@rsenden I see, that is even more problematic. Setter-only properties are not considered properties under bean introspection.

**Comment by yawkat** [comment]
ok i think copying annotations from the setter is doable, if a bit ugly. I will do that tomorrow.

**Comment by yawkat** [comment]
@graemerocher Even for fields the semantics here are weird. It seems like since it uses `buildForParent` with the field marked as the parent element of the getter, it only copies `@Inherited` annotations from the field. Do you know why this is?

**Comment by graemerocher** [comment]
@yawkat Are you sure? `@NotNull` is not inherited and seems to be copied/merged here https://github.com/micronaut-projects/micronaut-core/blob/d236f2c8a756b773143fb37a0b87c694ef750dec/inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy#L1059-L1101

**Comment by yawkat** [comment]
Hm yea, the code is super weird. Looking at the debugger, it seems like in this code, the `isDeclared` check is responsible for adding annotations from the getter, and the `element == parent` check is responsible for the field:

https://github.com/micronaut-projects/micronaut-core/blob/d236f2c8a756b773143fb37a0b87c694ef750dec/inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java#L1112-L1177

**Comment by graemerocher** [comment]
yeah this code looks like it has become a bit of mess over time as it is tries to handle both the case of inherting meta annotations but also annotations between elements :/
