### ISSUE TITLE
Add `io.projectreactor.kotlin:reactor-kotlin-extensions` to Micronaut BOM

### ISSUE THREAD

**Issue by simondean** [micronaut-projects/micronaut-core#6515]
### Feature description

The Micronaut BOM currently includes `io.projectreactor:reactor-core`: 

https://github.com/micronaut-projects/micronaut-core/blob/f06d41c120328f641813dad2cf1e9f8926732048/gradle/libs.versions.toml#L401

Since `reactor-core` 3.3.x, Reactor's Kotlin extensions have been moved into a separate library: 

https://projectreactor.io/docs/core/release/reference/#kotlin-extensions
> As of Dysprosium-M1 (ie. reactor-core 3.3.0.M1), Kotlin extensions are moved to a dedicated reactor-kotlin-extensions module with new package names that start with reactor.kotlin instead of simply reactor.
>
> As a consequence, Kotlin extensions in reactor-core module are deprecated. The new dependency’s groupId and artifactId are:
>
>io.projectreactor.kotlin:reactor-kotlin-extensions

This feature request is to add that new `io.projectreactor.kotlin:reactor-kotlin-extensions` dependency to the Micronaut BOM.

**Comment by graemerocher** [comment]
We should probably just import the BOM rather than include a single dependency https://search.maven.org/artifact/io.projectreactor/reactor-bom/2020.0.13/pom

**Comment by simondean** [comment]
> We should probably just import the BOM rather than include a single dependency

That would be great.  It would cover things like `io.projectreactor:reactor-test` too

**Comment by altro3** [comment]
@graemerocher you can close it, it's already fixed
