### ISSUE TITLE
@JsonCreator not working with native-image

### ISSUE THREAD

**Issue by wimdeblauwe** [micronaut-projects/micronaut-core#6528]
### Expected Behavior

The example application at https://github.com/wimdeblauwe/jackson-native-image-issue should work when compiled as native image. 

### Actual Behaviour

Exception when running as native image

### Steps To Reproduce

See README at https://github.com/wimdeblauwe/jackson-native-image-issue

### Environment Information

MacOS

### Example Application

https://github.com/wimdeblauwe/jackson-native-image-issue

### Version

3.1.4

**Comment by yawkat** [comment]
You're creating your own `ObjectMapper` here, which is unsupported: https://github.com/wimdeblauwe/jackson-native-image-issue/blob/main/src/main/java/com/wimdeblauwe/examples/GitHubClient.java#L24

I can't reproduce this issue with an injected `ObjectMapper`. However reproducing this seems to be a bit finicky in general, so I wouldn't bet on that. Please try reproducing this with the micronaut-provided `ObjectMapper`.

**Comment by wimdeblauwe** [comment]
Thanks! Injecting the `ObjectMapper` into the `GitHubClient` class indeed makes it work.
