### ISSUE TITLE
Controller fails to maintain order of items in map during deserialization

### ISSUE THREAD

**Issue by rbhambhra** [micronaut-projects/micronaut-core#6537]
### Expected Behavior

A map deserialized by Controller maintains order of items in map (as sent in body of post)

### Actual Behaviour

Since version 3.1.0, map order is not retained

### Steps To Reproduce

Start sample application at https://github.com/rbhambhra/mapissue

Application contains a simple controller that echos back posted map as per https://github.com/rbhambhra/mapissue/blob/main/src/main/java/com/example/TestController.java

**Request**
curl -X POST http://localhost:8080/test -H 'cache-control: no-cache' -H 'content-type: application/json' -d '{"1/1" : "one of one","1/2" : "one of two", "1/3" : "one of three","2/1" : "two of one","2/2" : "two of two", "2/3" : "two of three"}'

 **Response from 3.1.0** (Note that third item in map is out of order)
 {"1/1":"one of one","1/2":"one of two","2/1":"two of one","1/3":"one of three","2/2":"two of two","2/3":"two of three"}
 
 **Response from 3.0.3** - correct order
 {"1/1":"one of one","1/2":"one of two","1/3":"one of three","2/1":"two of one","2/2":"two of two","2/3":"two of three"}
 
 Note: explicitly changing the type to LinkedHashMap does not affect outcome
 **Request**
 curl -X POST http://localhost:8080/testlinkedhashmap -H 'cache-control: no-cache' -H 'content-type: application/json' -d '{"1/1" : "one of one","1/2" : "one of two", "1/3" : "one of three","2/1" : "two of one","2/2" : "two of two", "2/3" : "two of three"}'

### Environment Information

Operating System Windows 10
OpenJDK version "16.0.1" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

### Example Application

https://github.com/rbhambhra/mapissue

### Version

3.1.0

**Comment by yawkat** [comment]
Thanks for the bug report!

**Comment by rbhambhra** [comment]
@yawkat 
Thanks for the quick turnaround
Tested and works as expected
