### ISSUE TITLE
get duplicate bean if use ApplicationContext.getBeansOfType method with CustomScope

### ISSUE THREAD

**Issue by Linindoo** [micronaut-projects/micronaut-core#6538]
### Expected Behavior

it should get different implementation  bean of the target beanType 

### Actual Behaviour

it return the duplicate implementation  bean of the target beanType 

### Environment Information

win10
jdk8

### Example Application

https://github.com/Linindoo/micronaut-bug

### Version

3.1.4

**Comment by Linindoo** [comment]
![image](https://user-images.githubusercontent.com/26195410/142577626-2e1ed6a8-d26c-4e85-b048-da8adad44ca6.png)
i think the beanType should be replaced by candidate.asArgument()

**Comment by jameskleeh** [comment]
Really great report. Thanks for looking into it and recommending a fix!
