### ISSUE TITLE
Simple subscribe method for Publisher inside Publishers utility class

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-core#6564]
### Feature description

If one wants to write a reactive-platform independent code then there is. a `Publishers` utility class which helps to do some basic operations on the `Publisher` interface. It would be nice if it also contains a simple method to subscribe to a publisher to actually trigger the execution.

```java

public static <T> void subscribe(Publisher<T> publisher, Consumer<T> onNext)
public static <T> void subscribe(Publisher<T> publisher, Consumer<T> onNext, Consumer<Throwable> onError)
public static <T> void subscribe(Publisher<T> publisher, Consumer<T> onNext, Consumer<Throwable> onError, Runnable onComplete)
```

there might be either two variants of the method - `subscribeOne` and `susbcribeAll` which will differ in a number of requested items or there should be `subscribeN` variant which would request the expected number of items.

**Comment by jameskleeh** [comment]
In general this sort of approach (reactive platform independent) is not feasible. There will come a need for some advanced functionality and we do not want to write a new reactive implementation. In core and in our modules we use reactor as a in implementation dependency and when writing Micronaut libraries you should too. The main reason it matters for libraries is context propagation. For example the metrics library was returning a custom publisher in a filter that wrapped `context.proceed` and as a result the reactor context was lost.

As a result of this I don't think we should be expanding or promoting the use of the `Publishers` class in general for reactive independence.

**Comment by musketyr** [comment]
The problem is in the supporting multiple major versions of Micronaut. As a library developer that needs to support all major versions of Micronaut it does not make sense to use any specific reactive implementation as it changes between the versions. For example, I don't want to use Reactor for libraries which primarily aims to 1.x and I don't want to depend to RxJava which is deprecated in later versions. The use cases are very limited - the one mentioned in the title and probably some easy way how to return blocking results.

**Comment by jameskleeh** [comment]
@musketyr Surely you must have separate branches in those libraries for the major versions?

**Comment by musketyr** [comment]
No, so far so good with compiling them with Micronaut 1.3.7. Only some libraries requires Gradle tweaks to thanks to changed coordinates 😞

**Comment by musketyr** [comment]
And some libs actually required some backports TBH.

**Comment by jameskleeh** [comment]
You're missing out on a lot of improvements on the compiler side. Thoughts @graemerocher ?

**Comment by musketyr** [comment]
well, I guess I will need to spin off yet another minimal library as I guess that even this would get accepted I guess there won't be any backport to 1.x and a release 😄

**Comment by graemerocher** [comment]
yeah there are many benefits to compiling with newer versions, might be better to maintain different branches if you need multi version

**Comment by musketyr** [comment]
well, with 90% of the codebase still on 1.x, my primary target is Micronaut 1.x 😄 We're in a dependency loop right now. we're trying to get rid of all Grails apps to free our hands with Micronaut upgrades as soon as possible but "as soon as" is already taking too long. Meanwhile Grails 5 has been released but the already migrated Micronaut code is not 3.x ready (e.g. changes in the event loop made us some headaches).
