### ISSUE TITLE
SLF4J binding warnings raised during compilation

### ISSUE THREAD

**Issue by danielgonzalez3** [micronaut-projects/micronaut-core#6570]
### Expected Behavior

Importing [SLF4J](http://www.slf4j.org/) should raise no warnings at compile time. Seen from the Micronaut Launch project using Micronaut 3.1.4:

```
gw clean build

> Task :compileTestJava
Note: Creating bean classes for 1 type elements

BUILD SUCCESSFUL in 14s
15 actionable tasks: 15 executed
```

### Actual Behaviour

Importing SLF4J raises warnings during `:compileJava` and `:compileTestJava` regarding a failed class load. Seen from the Micronaut Launch project using Micronaut 3.2.0:

```
gw clean build

> Task :compileJava
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

> Task :compileTestJava
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Note: Creating bean classes for 1 type elements

BUILD SUCCESSFUL in 15s
15 actionable tasks: 15 executed
```

This warning occurs when [no SLF4J binding can be found on the classpath](http://www.slf4j.org/codes.html#StaticLoggerBinder). However, the Launch project ships `runtimeOnly("ch.qos.logback:logback-classic")`, which [should be sufficient as an SLF4J backend](http://www.slf4j.org/manual.html#swapping).

It also isn't clear why a runtime dependency would be initialized during compilation.

I saw an older [outstanding bug with the Groovy compiler](https://github.com/micronaut-projects/micronaut-core/issues/676) that showed a similar behavior. I also saw[ a bug around Graal native images ](https://github.com/micronaut-projects/micronaut-core/issues/3683#issuecomment-881713816)that may be related. However, I have also seen this warning message behavior in a private project that uses neither Groovy nor Graal.

### Steps To Reproduce

- Download demonstration project from [Micronaut Launch ](https://micronaut.io/launch/)with default settings: Micronaut 3.2.0, Java 11, Gradle build tool, etc.
- Add `implementation("org.slf4j:slf4j-api:1.7.32")` to dependencies in build.gradle
- `./gradlew clean build`

### Environment Information

- Java 11
- Gradle 7.2
- Micronaut 3.2.0

### Example Application

https://micronaut.io/launch/

### Version

3.2.0

**Comment by devmage** [comment]
@danielgonzalez3 and I are peers, thanks Daniel for raising this issue.

I went through [the diff from Micronaut 3.1.4 to 3.2.0](https://github.com/micronaut-projects/micronaut-core/compare/v3.1.4...v3.2.0) and didn't see anything immediate that would impact compilation of projects using Micronaut. My current belief then is that an updated dependency in 3.2.0 is causing these warnings to be raised.

**Comment by devmage** [comment]
Speaking to impact of this bug, Daniel and I believe that this does not impact operation of compiled services using Micronaut 3.2.0. A private service we maintain, when updated to Micronaut 3.2.0, appears to generate application logs as expected at runtime. The warnings reported in this issue appear to be limited to compilation noise. Unfortunate, but not show-stopping, as far as we can tell.

We were also unable to come up with a simple mitigation for these warnings. :shrug:

**Comment by devmage** [comment]
Perhaps also worth mentioning, this behavior is seen with both the Micronaut recommended SLF4J 1.7.29, and the latest SLF4J 1.7.32 point-release.

**Comment by graemerocher** [comment]
There is a PR for this already https://github.com/micronaut-projects/micronaut-core/pull/6566 but we are discussion the best solution

**Comment by graemerocher** [comment]
A workaround is to add:

```
annotationProcessor("org.slf4j:slf4j-simple")
```

To the `build.gradle`

**Comment by devmage** [comment]
Thanks @graemerocher . We can take any further conversation to the PR for now.
