### ISSUE TITLE
Bean introspection does not have annotation metadata for inherited props (when extending a class from another module)

### ISSUE THREAD

**Issue by mitushy** [micronaut-projects/micronaut-core#6574]
### Expected Behavior

Creating an `@Introspected` class by extending another module's `@Introspected` class should have annotation metadata for all properties (own + inherited).

### Actual Behaviour

Only local properties get returned when calling `introspection.getIndexedProperty(AnnotationType)`

This seems like a **regression in 3.2.0**. It was working fine in 3.1.3.

We found this when trying to update and tests started failing - we have controllers with `@Valid  @Body` parameters which stopped validating properties inherited from micronaut-security's classes.

Interestingly, if the _supertype is in the same module_ - it works fine.

Short gist below, but I've created a sample with a few tests trying to show our findings.

```groovy
@Introspected
class ExtendingUsernamePasswordCredentials extends UsernamePasswordCredentials {
    @NotBlank
    @NotNull
    private String tenant
    // also inherits NotNull&NotBlank "password" and "username" fields from UsernamePasswordCredentials

    ExtendingUsernamePasswordCredentials(String tenant, String username, String password) {
        super(username, password)
        this.tenant = tenant
    }
    // .. getters, setters etc
}

@Validated
@Controller("/my"
class MyController {

    @Post("/login")
    MutableHttpResponse<?> login(@Valid @Body ExtendingUsernamePasswordCredentials tenantCreds) { /*..*/ }
}
```
Now, a request like:
```http
POST http://localhost:8080/my/login
Content-Type: application/json

{
  "tenant": "tenant",
  "password": "pass"
}
```
will reach the controller, when it should have been rejected, because `username` is null.

### Steps To Reproduce

1. Use micronaut 3.2.0
2. Create a subclass by extending from micronaut-security's UsernamePasswordCredentials
3. Create a controller with `@Valid @Body ExtendedCredentials`
4. Send a request with null username
5. The controller will be executed with null binded, when this is **not** considered `@Valid`

### Environment Information

- OS: macOS 11.6.1
- jdk: 20.3.0.r11-grl

### Example Application

https://github.com/mitushy/micronaut-issue-6574

### Version

3.2.0

**Comment by graemerocher** [comment]
can you clarify which language you are using? Examples look like Groovy

**Comment by mitushy** [comment]
Yes, sorry. The language is groovy. It may be groovy-specific, I haven't tried java.

**Comment by jameskleeh** [comment]
This is partially our issue but after fixing our end it is broken because of a Groovy bug

https://issues.apache.org/jira/browse/GROOVY-10398
