### ISSUE TITLE
ServerRequestContext.currentRequest() returns empty in a Filter which intercepts a @Client using Flowable.

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#659]
The [TokenPropagationHttpClientFilter](
https://github.com/micronaut-projects/micronaut-core/blob/master/security/src/main/java/io/micronaut/security/token/propagation/TokenPropagationHttpClientFilter.java#L75) uses `ServerRequestContext.currentRequest()` to retrieve the original request and extract the token.

`ServerRequestContext.currentRequest()` is `Optional.empty()` if a client uses `Flowable` as a return type. Example:

```
@Client("http://localhost:8082")
@Requires(notEnv = Environment.TEST)
public interface BooksClient extends BooksFetcher {

    @Override
    @Get("/api/books")
    Flowable<Book> fetchBooks();
}
```

if it is `List<Book>`,  `serverRequestContext.currentRequest()` returns a request.

```
@Client("http://localhost:8082")
@Requires(notEnv = Environment.TEST)
public interface BooksClient extends BooksFetcher {

    @Override
    @Get("/api/books")
    List<Book> fetchBooks();
}
```

With this issue token propagation and multitenancy propagation do not work for `@Client` methods returning `Flowable`.

### Environment Information

- **Operating System**: Mac OS HighSierra
- **Micronaut Version:** 1.0.0.RC1
- **JDK Version:** 1.8.0_181

### Example Application

[code.zip](https://github.com/micronaut-projects/micronaut-core/files/2434999/code.zip)

### How to reproduce the error in the sample app. 

Execute every microservice: 

`./gradlew books:run`
`./gradlew inventory:run`
`./gradlew gateway:run`

Login : 

```
## Request Duplicate
curl -X "POST" "http://localhost:8080/login" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "username": "sherlock",
  "password": "elementary"
}'

```

Call `api/books` supplying the JWT access token you got in `/login` in the HTTP Header Authorization. 

```
## Request
curl "http://localhost:8080/api/books" \
     -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzaGVybG9jayIsIm5iZiI6MTUzODQxNTQ5NSwicm9sZXMiOltdLCJpc3MiOiJnYXRld2F5IiwiZXhwIjoxNTM4NDE5MDk1LCJpYXQiOjE1Mzg0MTU0OTV9.bu4nStTDm93Q5ML42CyIfxAf8UgpwpgMsroe8Jxrols' 
```

Place breakpoint in [TokenPropagationHttpClientFilter](
https://github.com/micronaut-projects/micronaut-core/blob/master/security/src/main/java/io/micronaut/security/token/propagation/TokenPropagationHttpClientFilter.java#L75) you will see `ServerRequestContext.currentRequest()` returns an empty optional.

**Comment by beedubu** [comment]
In CookieTenantResolver.resolveTenantIdentifier,         
Optional<HttpRequest<Object>> current = ServerRequestContext.currentRequest();
resolves to 
Optional.empty
I am just trying to get the micronaut-multitenancy-propagation project to work ( which it does when i remove the HomeFilter ).

Mac Mojave
Micronaut 1.0.4 RC1
