### ISSUE TITLE
Create an inherited @Nullable annotation

### ISSUE THREAD

**Issue by pbthorste** [micronaut-projects/micronaut-core#6590]
### Issue description

This is related to Micronaut 3.2.0
Hi, I have been trying to follow the guidelines in the documentation here: https://docs.micronaut.io/latest/guide/#annotationMetadata
My aim is to create a version of `io.micronaut.core.annotation.Nullable` that is inherited. I need to recreate the behaviour in Micronaut 2 where these annotations were inherited from the interface.

As an example I created this interface:
```java
import io.micronaut.core.annotation.Nullable;
import io.micronaut.http.HttpResponse;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.annotation.Header;
import reactor.core.publisher.Mono;

import java.util.List;

@Controller
public interface ControllerInterface {

    @Get(value = "/test1", produces = { "application/json" })
    default Mono<HttpResponse<List<String>>> test1(@Header(value = "header1") String header1 ) {
        return Mono.just(HttpResponse.ok());
    }

    @Get(value = "/test2", produces = { "application/json" })
    default Mono<HttpResponse<List<String>>> test2(@Nullable @Header(value = "header1") String header1 ) {
        return Mono.just(HttpResponse.ok());
    }

    @Get(value = "/test3", produces = { "application/json" })
    default Mono<HttpResponse<List<String>>> test3(@InheritedNullable @Header(value = "header1") String header1 ) {
        return Mono.just(HttpResponse.ok());
    }

    @Get(value = "/test4", produces = { "application/json" })
    default Mono<HttpResponse<List<String>>> test4(@Nullable @Header(value = "header1") String header1 ) {
        return Mono.just(HttpResponse.ok());
    }
}
```
This implementation:
```java
import io.micronaut.core.annotation.Nullable;
import io.micronaut.http.HttpResponse;
import io.micronaut.http.annotation.Controller;
import reactor.core.publisher.Mono;

import java.util.List;
import java.util.Optional;

@Controller
public class ControllerImpl implements ControllerInterface {

    @Override
    public Mono<HttpResponse<List<String>>> test1(String header1) {
        // works if the header is set
        return Mono.just(HttpResponse.ok(List.of(header1)));
    }

    @Override
    public Mono<HttpResponse<List<String>>> test2(String header1) {
        // @Nullable from interface is not inherited here
        return Mono.just(HttpResponse.ok(List.of(header1)));
    }

    @Override
    public Mono<HttpResponse<List<String>>> test3(String header1) {
        // @InheritedNullable from interface is not inherited here
        return Mono.just(HttpResponse.ok(List.of(header1)));
    }

    @Override
    public Mono<HttpResponse<List<String>>> test4(@Nullable String header1) {
        // works because @Nullable  is specified in the implementation
        return Mono.just(HttpResponse.ok(List.of(Optional.ofNullable(header1).orElse("null"))));
    }
}
```

And this annotation:
```java

import io.micronaut.core.annotation.Nullable;

import java.lang.annotation.ElementType;
import java.lang.annotation.Inherited;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Inherited
@Target({ElementType.METHOD, ElementType.PARAMETER, ElementType.FIELD, ElementType.ANNOTATION_TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Nullable
public @interface InheritedNullable {
}
```
But the `@InheritedNullable` is not inherited from the interface to the Controller.
Am I doing this wrong ? Or is there a better way to turn on inheritance for these kinds of annotations ?

**Comment by pbthorste** [comment]
and maybe one question also - why doesn't ´io.micronaut.core.annotation.Nullable´ have the ´@Inherited´ annotation ? It seems only natural that this behavior would be inherited, but with the possibility of overriding it with `@NonNull`

**Comment by graemerocher** [comment]
Semantically the original `javax.annotation.Nullable` annotations are not inherited either and overridding is tricky since if you add `@NonNull` it means you would have both `@Nullable` and `@NonNull` declared, although I guess tools would have to look at the enum value of `@When` to deduce the correct behaviour

**Comment by pbthorste** [comment]
I guess the inherent issue here is that while the  `@Header` annotation is inherited, the `@Nullable` is not, and the two are linked together - creating a sort of strange situation.
In terms of SOLID design principles it could be argued that this breaks the 'Liskov substitution principle' - since the parent and subclass will behave differently when the interface has the `@Nullable` annotation.
Spring solves this by having the `required` field i.e. `@Header(required = false)`

**Comment by jameskleeh** [comment]
@pbthorste There are dozens of annotations that interact with `@Nullable`. Adding a `required` member to each of them doesn't seem like a great solution to me. Not to mention `@Nullable` is respected in cases where there are no other annotations

**Comment by pbthorste** [comment]
@jameskleeh Interesting that `@Nullable` is respected in that case, wish that was also the case where there are other annotations.

With regards to the `required` member - it might not be ideal, but today's situation is far from perfect.
Don't you agree that being able to inherit for example  `@Header` (which means the implementing class gets a required header field) and not `@Nullable` - which is basically the only way to make the `@Header` not required - is odd ? The only other option I know of is to use Optional, which is not recommended for good reasons.

**Comment by timyates** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-core/pull/6716 for Micronaut 3.3.0
