### ISSUE TITLE
Regression when upgrading to 3.1.4 : can't build picocli native image on windows

### ISSUE THREAD

**Issue by jchanaud** [micronaut-projects/micronaut-core#6595]
### Expected Behavior

I'm using native image to compile a Micronaut Picocli CLI for windows and linux

Following Upgrade : 
- micronaut 2.5.x to 3.1.4 
- stayed in micronaut plugin 2.x : https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/303
- Graalvm 21.1.0 to 21.3.0

Linux build is **successful**
Windows build is **failed**

### Actual Behaviour

This github actions shows the failure with micronaut 3.1.4 and graalvm 21.3.0
https://github.com/michelin/ns4kafka/actions/runs/1509108289

Successful linux and windows build from a previous build before migrating to Micronaut 3.1.4
https://github.com/michelin/ns4kafka/actions/runs/1491868428

The error:
````
> Task :cli:nativeImage
[kafkactl-1.2.3-SNAPSHOT:2720]    classlist:   8,324.73 ms,  0.96 GB
[kafkactl-1.2.3-SNAPSHOT:2720]        (cap):  15,932.31 ms,  0.96 GB
[kafkactl-1.2.3-SNAPSHOT:2720]        setup:  19,482.44 ms,  0.96 GB
[kafkactl-1.2.3-SNAPSHOT:2720]     (clinit):   1,344.00 ms,  3.34 GB
[kafkactl-1.2.3-SNAPSHOT:2720]   (typeflow):  26,308.86 ms,  3.34 GB
[kafkactl-1.2.3-SNAPSHOT:2720]    (objects):  90,729.54 ms,  3.34 GB
[kafkactl-1.2.3-SNAPSHOT:2720]   (features):  15,271.58 ms,  3.34 GB
[kafkactl-1.2.3-SNAPSHOT:2720]     analysis: 138,586.75 ms,  3.34 GB
[kafkactl-1.2.3-SNAPSHOT:2720]     universe:   8,968.61 ms,  3.30 GB
[kafkactl-1.2.3-SNAPSHOT:2720]      (parse):   8,313.56 ms,  3.31 GB
[kafkactl-1.2.3-SNAPSHOT:2720]     (inline):  20,248.14 ms,  3.23 GB
[kafkactl-1.2.3-SNAPSHOT:2720]    (compile):  73,092.83 ms,  3.10 GB
[kafkactl-1.2.3-SNAPSHOT:2720]      compile: 105,749.87 ms,  3.10 GB
[kafkactl-1.2.3-SNAPSHOT:2720]        image:   6,051.36 ms,  3.14 GB
[kafkactl-1.2.3-SNAPSHOT:2720]        write:   2,305.31 ms,  3.14 GB
[kafkactl-1.2.3-SNAPSHOT:2720]      [total]: 289,948.54 ms,  3.14 GB
# Printing build artifacts to: D:\a\ns4kafka\ns4kafka\cli\build\native-image\kafkactl-1.2.3-SNAPSHOT.build_artifacts.txt
Fatal error:com.oracle.svm.core.util.VMError$HostedError: should not reach here
	at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:64)
	at com.oracle.svm.hosted.jdk.JNIRegistrationSupport.makeShimDLL(JNIRegistrationSupport.java:256)
	at com.oracle.svm.hosted.jdk.JNIRegistrationSupport.makeShimDLLs(JNIRegistrationSupport.java:230)
	at com.oracle.svm.hosted.jdk.JNIRegistrationSupport.afterImageWrite(JNIRegistrationSupport.java:175)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$doRun$8(NativeImageGenerator.java:663)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:663)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
Error: Image build request failed with exit status 1
````

### Environment Information

github actions are configured with latest windows and ubuntu images
I'm using graalvm jdk 11 everywhere

### Example Application

https://github.com/michelin/ns4kafka (original project)
https://github.com/twobeeb/demo (simplified version)

### Version

3.1.4

**Comment by graemerocher** [comment]
@twobeeb going to investigate

**Comment by melix** [comment]
Can you compare the contents of the `build/native/generated/generateResourcesConfigFile/resource-config.json` file on Linux and Windows?

**Comment by graemerocher** [comment]
@twobeeb can you confirm whether the NPE only happens on Windows?

**Comment by jchanaud** [comment]
@graemerocher 
Confirmed. The issue is only on windows build (this error is network error, This VM doesn't have internet access, bit it clearly "worked")
````console
[foundation@carsfkc01 ~]$ ./demo-http-cli 
11:04:05.773 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [cli]
11:04:16.806 [main] ERROR i.m.r.intercept.RecoveryInterceptor - Type [com.example.GithubClient$Intercepted] executed with error: Read Timeout
io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
````
@melix 
my demo project contains the github action with the artifacts containing what you need : 
https://github.com/twobeeb/demo-http-cli/actions/runs/1528085284

Windows and Linux both have the following resource-config.json
````
{
  "resources" : {
    "includes" : [ ],
    "excludes" : [ ]
  },
  "bundles" : [ ]
}
````

**Comment by jchanaud** [comment]
Hi @graemerocher @melix
Just FYI, I reverted my project to micronaut 2.5.x. I discovered then that I can't build on windows with graalvm later than 20.3.x
https://github.com/michelin/ns4kafka/blob/master/.github/workflows/on_push_master.yml
linux build is fine on graalvm 21.1.0
I don't know if this information could be any help...

**Comment by Nokorbis** [comment]
Hello,
I'm having the same issue (NullPointerException on a injected singleton) with a project generated this week using the launcher

- Micronaut 3.2.1
- Command Line Application
- Gradle
- GraalVM Feature
- Windows 10
- Visual Studio Build Tools 2022

**Comment by loicgreffier** [comment]
Hello, 
I faced the same issue: NullPointerException on an injected bean when running a Command Line App as Windows native executable.

Just instantiated a brand new project with:
- Micronaut 3.3.0, Command Line Application
- GraalVM 22.0.0.2
- Gradle (using the provided wrapper)

However, it seems working when the project is built with Maven instead of Gradle.

- Micronaut 3.3.0, Command Line Application
- GraalVM 22.0.0.2
- Maven (using the provided wrapper) and also tried with Maven 3.8.2 (manual installation and build on local workstation)

Working: https://github.com/loicgreffier/micronaut-picocli-maven
Not working: https://github.com/twobeeb/micronaut-issue-6595

The only difference is the build tool so the issue seems coming from the build with Gradle. Can anybody confirm ?

**Comment by graemerocher** [comment]
@alvarosanchez @melix could you investigate this for Windows for both Maven and Gradle

**Comment by altro3** [comment]
Hi! I confirm. Same problem.

Micronaut 3.3.3, Command Line Application
GraalVM 22.0.0.2
Windows 10
Visual Studio Build Tools 2022
Gradle 7.4

**Comment by loicgreffier** [comment]
I tested this issue again with:
- Micronaut 3.8.1, Command Line Application
- Java 11
- Gradle 7.5.1
- GraalVM 22.3.0

There is no more injection issue for me, I can run both of my native Linux/Windows images as expected
