### ISSUE TITLE
Add a way to configure Netty Boostrap resolver in DefaultHttpClient

### ISSUE THREAD

**Issue by ggerbaud** [micronaut-projects/micronaut-core#6617]
### Feature description

I have trouble to use DefaultHttpClient (through declarative HTTP Clients) with an enterprise proxy. Netty doesn't seem to use the proxy to resolve external address, so it doesn't work for me.
It seems [there is an open issue in Netty](https://github.com/netty/netty/issues/7487) and a known workaround :
```java
Bootstrap bootstrap = new Bootstrap();
bootstrap.resolver(NoopAddressResolverGroup.INSTANCE);
```
In deed when I define my own HttpClient with this workaround like this:
```java
public class ProxyClient extends DefaultHttpClient {

        public ProxyClient(URI uri, HttpClientConfiguration configuration) {
            super(uri, configuration);
            this.bootstrap.resolver(NoopAddressResolverGroup.INSTANCE);
        }
 }
```
this is working fine when using a proxy in my HttpClientConfiguration.

So the feature request is to add a way (a property like `micronaut.http.[client|service.*].proxy-XXX` maybe) to use this Noop resolver in the Boostrap initialized in DefaultHttpClient constructor

**Comment by jaecktec** [comment]
Thanks for the workaround. I used my previous [workaround](https://github.com/micronaut-projects/micronaut-core/issues/4829) to make it work together with declarative clients.

**Comment by jaecktec** [comment]
IMHO: 
I think this is a bug in the DefaultHttpClient, since the docs of the `NoopAddressResolver` say:
```
A AddressResolver that does not perform any resolution but always reports successful resolution. This resolver is useful when name resolution is performed by a handler in a pipeline, such as a proxy handler.
```

in the configureProxy method it should be added to the bootstrap.

**Comment by yawkat** [comment]
agreed. the proxy should always take over resolution
