### ISSUE TITLE
Generalize `HttpNettyFeature` for other uses of netty

### ISSUE THREAD

**Issue by yawkat** [micronaut-projects/micronaut-core#6650]
### Issue description

Other micronaut projects that use netty but do not depend on micronaut-http-netty need the same graal configuration that `HttpNettyFeature` provides. The issue where this came up is https://github.com/micronaut-projects/micronaut-grpc/pull/435 . I can think of a few ways to solve this:

- Create a new micronaut-netty module that contains a new `NettyFeature` with the relevant functionality. Make downstream projects that use netty depend on this module.
- Add the `NettyFeature` to the core module, with a `compileOnly` dependency on netty.
- Add the runtime initializations to `native-image.properties` in the core module.

My favorite is number 2, because:

- Only runtime initializations aren't sufficient to get best netty performance, we also need the other code in `HttpNettyFeature`.
- A full module seems unnecessary. It also means that if we ever decide to create a general-purpose netty framework for micronaut (not http-specific), we would need to use a different name. Though using a name like `micronaut-netty-graal` would avoid this.

@graemerocher Thoughts? If it seems reasonable to you, I will implement 2 today, so it can be reviewed by james. Otherwise one of you will have to implement it, or it will have to wait over the holidays.

**Comment by ilopmar** [comment]
Option `2` sounds good to me :)

**Comment by graemerocher** [comment]
Can we not put this config into https://github.com/micronaut-projects/micronaut-core/tree/3.2.x/buffer-netty which seems like a general netty module already

**Comment by yawkat** [comment]
Sure, but grpc doesn't depend on that. So we'd have to change the modules that use netty too.
