### ISSUE TITLE
The Environment Endpoint security issue

### ISSUE THREAD

**Issue by ivyazmitinov** [micronaut-projects/micronaut-core#6663]
### Issue description

Current design of the [environment endpoint](https://docs.micronaut.io/latest/guide/#environmentEndpoint) poses a threat for a critical security issue, since it provides all the configuration values.
The problem consist of two parts:

1. The endpoint claims to mask sensitive config values, but it doesn't provide a clear definition what it considers "sensitive". The only way to figure this out is to look at the source of `EnvironmentEndpoint` and find hard-coded list of key words. It is far from ideal, since
    - A user can define any property (`db-pass` instead of `password`)
    - A user is prone to typos (`pssword` instead of `password`)
1. By default, the endpoint can be accessed by **any** authorized user, without any checks

Given that, consider the following, quite common, use-case:

1. A developer creates an web app with regular authentication for users (via login form, for example)
1. For internal use of the app the developer sets defines property `external-service-creds : <token>` containing sensitive token 
1. After a while the developer decides to enable metrics and plugs in `management` for the `/metrics` endpoint with `senstive: false`, since they consider metrics non-sensitive information

Since the environment endpoint is enabled by default and management endpoints are exposed over the same port as the application, any authorized user now have access to the token.

I think, it is much better from the security standpoint  to: 
1. Disable all management endpoints by default
1. Make the list of key words configurable 
2. Force developers to implement custom `SensitiveEndpointRule` if they use the environment endpoint

Example is located here: https://github.com/ivyazmitinov/env-endpoint-issue

**Comment by graemerocher** [comment]
I assume you mean you are setting `endpoints.all.sensitive` to `false`?

**Comment by ivyazmitinov** [comment]
@graemerocher No, all endpoints except `/metrics` remain `sensitive:true`. That's way it is necessary for a user to log in. But after the login any user can execute `curl -X GET --location "http://<service_url>/env" -H "Authorization: Bearer <auth_from_login>"` and get the application's configuration from all sources

**Comment by ivyazmitinov** [comment]
@graemerocher updated the issue with the reproducible example

**Comment by timyates** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-core/pull/6711 for 3.3.0
