### ISSUE TITLE
Native image builds do not respect Jackson directive in application.yml

### ISSUE THREAD

**Issue by alanwhite** [micronaut-projects/micronaut-core#6665]
### Expected Behavior

In a java app, with a src/main/resources/application,yml of
`micronaut:
  application:
    name: mntest2
jackson:
   property-naming-strategy: SNAKE_CASE`
the expectation is that the properties of any POJO are transposed to snake case.
`➜  mntest1 curl http://localhost:8080/v1/things/fred
{"thing_id":"fred","property_one":"hatstand"}%  `

### Actual Behaviour

When the app is built with ./mvnw package -Dpackaging=native-image, we see this behaviour
`➜  mntest1 curl http://localhost:8080/v1/things/fred
{"thingId":"fred","propertyOne":"hatstand"}%  `

### Steps To Reproduce

Clone the app at https://github.com/alanwhite/mntest1
Build & run with ./mvnw mn:run
Once ready run curl http://localhost:8080/v1/things/fred
and witness correct response of 
`{"thing_id":"fred","property_one":"hatstand"}%  `
Cancel the running app and rebuild using ./mvnw package -Dpackaging=native-image
Once built launch with ./target/mntest1 & and then run again curl http://localhost:8080/v1/things/fred
and witness incorrect response of 
`{"thingId":"fred","propertyOne":"hatstand"}%   `

### Environment Information

Linux ubuntu 5.11.0-41-generic #45~20.04.1-Ubuntu SMP Wed Nov 10 10:20:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
java: 21.3.0.r17-grl
micronaut: 3.2.3

### Example Application

https://github.com/alanwhite/mntest1

### Version

3.2.3

**Comment by yawkat** [comment]
we're missing support for property naming strategies in the `BeanIntrospectionModule`. A workaround is to mark the bean as `@ReflectiveAccess` for now

**Comment by yawkat** [comment]
i dont see an easy way to add this, so I'm not prioritizing it. Support should be added at some point, but it's not like we can support every jackson feature, anyway.

Failing test case:

```groovy
    def 'property naming strategy'() {
        given:
        ApplicationContext ctx = ApplicationContext.run([
                'jackson.property-naming-strategy': 'SNAKE_CASE'
        ])
        ctx.getBean(BeanIntrospectionModule).ignoreReflectiveProperties = ignoreReflectiveProperties
        ObjectMapper objectMapper = ctx.getBean(ObjectMapper)

        when:
        def s = objectMapper.writeValueAsString(new SnakeCaseBean(fooBar: 'baz'))
        then:
        s == '{"foo_bar":"baz"}'

        where:
        ignoreReflectiveProperties << [false, true]
    }

    @Introspected
    static class SnakeCaseBean {
        private String fooBar

        public String getFooBar() {
            return fooBar
        }
    }
```
