### ISSUE TITLE
@JsonSubTypes discriminator property not correctly serialized in native image

### ISSUE THREAD

**Issue by ianroberts** [micronaut-projects/micronaut-core#6672]
### Expected Behavior

Given a polymorphic class hierarchy that uses `@JsonSubTypes` to declare a property discriminator

```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
        @JsonSubTypes.Type(name = "car", value = Car.class),
        @JsonSubTypes.Type(name = "van", value = Van.class),
})
@Introspected
@Data
public class Vehicle {
  private int wheels = 4;
}
```

the `Car` subclass should serialize as `{"type":"car", ...}` and the `Van` subclass as `{"type":"van", ...}` in all cases.

### Actual Behaviour

Behaviour is correct when running in a normal JVM (including GraalVM's `java`), but in a _native image_ the discriminator `"type"` property is only present when the `Vehicle` object is the _top level_ object returned from a controller action.

```json
{"type":"car","passengers":4,"wheels":4}
```

When the `Vehicle` is nested as a property of another object the true properties of the `Vehicle` are serialized as normal but the `"type"` property is missing.

```json
{"vehicle":{"passengers":4,"wheels":4}}
```

### Steps To Reproduce

1. clone the example app https://github.com/ianroberts/micronaut-jsonsubtypes-test
2. `./gradlew test` (on a Java 11 JVM - including GraalVM-as-a-JDK)
  - all tests pass
3. `./gradlew testNativeImage` (which of course requires GraalVM)
  - "unwrapped" tests pass, "wrapped" tests fail

### Environment Information

- Java 11, both adoptopenjdk and GraalVM CE 21.3.0
- Mac OS 11 (Big Sur), but the same issue occurs when building native image as a Docker container (which runs Linux)

### Example Application

https://github.com/ianroberts/micronaut-jsonsubtypes-test

### Version

3.2.3

**Comment by graemerocher** [comment]
Try add `@ReflectiveAccess` to your type

**Comment by ianroberts** [comment]
I just tried that, it makes no difference if I add `@ReflectiveAccess` to `Vehicle`, `Van` and `Car`, either _alongside_ the existing `@Introspected` or _instead of_ it.

**Comment by ianroberts** [comment]
But adding it to `Wrapper` does indeed fix the tests.

**Comment by ianroberts** [comment]
In my real use case neither the wrapper-equivalent nor the vehicle-equivalent classes are in my own codebase, but `@TypeHint` appears to have done the same trick there.

Should I just close this now I have a workaround or is it still considered a bug?  It seems very odd to me that it works in the top-level case without reflection but not in the wrapped case.

**Comment by yawkat** [comment]
it's a bug, `BeanIntrospectionModule` doesn't support `JsonSubTypes`. But subtype support is too complicated to properly implement in the module, it's not worth it. Marking as wontfix.

**Comment by Casvad** [comment]
Hi is there any news on this problem? Im having the same problem.
Thanks

**Comment by yawkat** [comment]
@Casvad this feature will not be implemented. as a workaround, use ReflectiveAccess. you could also try micronaut-serialization, which has support for this.

**Comment by subash89** [comment]
@Casvad  @yawkat  can you give an example how this can be achieved using micronaut serialization way ? I am trying to achieve same jackson sub types scenario. I don't mind using micronaut serialization if it provides an alternate?

**Comment by ianroberts** [comment]
@subash89 in my original example app in the issue report (https://github.com/ianroberts/micronaut-jsonsubtypes-test) the way I was able to make it work was to add `@ReflectiveAccess` not to the `@JsonSubTypes` base class itself, but rather to any classes that include a _property_ of the polymorphic type.

**Comment by yawkat** [comment]
@subash89 check out https://micronaut-projects.github.io/micronaut-serialization/latest/guide , it has more information on micronaut-serialization and how to use it. It is compatible with jackson annotations to some extent.

**Comment by subash89** [comment]
@ianroberts  with json sub types, I see your API returns with correct serialization(with {type:"car",..}) , even without @ReflectiveAccess. But what I am trying to do is load the Vehicle bean from application.yml.  Where I expect Config.vehicle object to be type of Car. But vehicle comes as null all the time. 


```
app:
  vehicle:
    type: car
    passengers: 55
```

From a config class as follows

```
@ConfigurationProperties("app")
public class Config {

    @JsonProperty
    private Vehicle vehicle;

    public Vehicle getVehicle() {
        return vehicle;
    }

    public void setVehicle(Vehicle vehicle) {
        this.vehicle = vehicle;
    }
}
```


@yawkat  I went though that, but micronaut-serialization not seems to have a 1:1 alternative for json sub types use case, but rather the support jackson json subtypes   correct?

**Comment by yawkat** [comment]
`ConfigurationProperties` are not loaded using jackson or micronaut-serialization at all. JsonSubTypes will not work in the config.

**Comment by subash89** [comment]
@yawkat **Is there any way** I can achieve above scenario where I need a particular sub class configuration like Car to be set to Vehicle variable. (using some kind of a qualifier or some parameter/AOP of a class or anything)

When dealing with Beans, we can  use bean qualifiers to distinguish different sub classes, like Named("prefix-of-class"). Any way to achieve this for config objects.

**Comment by yawkat** [comment]
No I don't think so. You can use a different prefix for each subtype, but there's no real polymorphism support

**Comment by subash89** [comment]
@yawkat  Can you explain what you mean by using different prefix for each sub types ?

**Comment by yawkat** [comment]
you can have a prefix app.car, app.bike, etc. one for each subtype

**Comment by subash89** [comment]
@yawkat Thanks. 
Ok. That means define then separately. (which I wanted to avoid originally) . got it. 
For my information, why is it not possible from configs, but fine in responses. I though either case it uses same serialization implementation. Both loading yaml to objects and serialize/deserialize objects from/to the wire.

**Comment by yawkat** [comment]
it does not use the same serialization implementation, no.

**Comment by ianroberts** [comment]
With configuration properties there's a lot more to it than just loading a single YAML/JSON file - various property sources get merged into one (the `application.yml` inside the JAR, values from environment variables, files named in `MICRONAUT_CONFIG_FILES` env var or `micronaut.config.files` system property, etc. etc.) and then the configuration properties bean is data-bound from the final merged config data.

**Comment by subash89** [comment]
Will  @TypeHint useful for configurations ?

**Comment by yawkat** [comment]
no

**Comment by baylorpaul** [comment]
Should you encounter this issue with third party libraries where you can't add `@ReflectiveAccess` directly to the classes, you can use `@ReflectionConfig`. E.g. I'm working on a [WebAuthn/Passkeys library for Micronaut](https://github.com/baylorpaul/webauthn4j-micronaut) using [WebAuthn4J](https://github.com/webauthn4j/webauthn4j), and I need to add a number of `@ReflectionConfig` entries. In that library, [`COSEKey.java`](https://github.com/webauthn4j/webauthn4j/blob/master/webauthn4j-core/src/main/java/com/webauthn4j/data/attestation/authenticator/COSEKey.java) uses `@JsonSubTypes`. E.g.
```java
@ReflectionConfig(type = COSEKey.class, accessType = {TypeHint.AccessType.ALL_PUBLIC, TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS, TypeHint.AccessType.ALL_DECLARED_METHODS, TypeHint.AccessType.ALL_DECLARED_FIELDS})
@ReflectionConfig(type = EdDSACOSEKey.class, accessType = {TypeHint.AccessType.ALL_PUBLIC, TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS, TypeHint.AccessType.ALL_DECLARED_METHODS, TypeHint.AccessType.ALL_DECLARED_FIELDS})
@ReflectionConfig(type = EC2COSEKey.class, accessType = {TypeHint.AccessType.ALL_PUBLIC, TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS, TypeHint.AccessType.ALL_DECLARED_METHODS, TypeHint.AccessType.ALL_DECLARED_FIELDS})
@ReflectionConfig(type = RSACOSEKey.class, accessType = {TypeHint.AccessType.ALL_PUBLIC, TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS, TypeHint.AccessType.ALL_DECLARED_METHODS, TypeHint.AccessType.ALL_DECLARED_FIELDS})
@ReflectionConfig(type = Curve.class, accessType = {TypeHint.AccessType.ALL_PUBLIC, TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS, TypeHint.AccessType.ALL_DECLARED_METHODS, TypeHint.AccessType.ALL_DECLARED_FIELDS})
@ReflectionConfig(type = COSEKeyType.class, accessType = {TypeHint.AccessType.ALL_PUBLIC, TypeHint.AccessType.ALL_DECLARED_CONSTRUCTORS, TypeHint.AccessType.ALL_DECLARED_METHODS, TypeHint.AccessType.ALL_DECLARED_FIELDS})
// TODO add @ReflectionConfig for many more classes
public class WebAuthn4jReflectionConfig {
}
```
