### ISSUE TITLE
Can't validate Kotlin data class as a controller parameter with mandatory fields

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#6681]
### Expected Behavior

It should be possible to validate a Kotlin data class uses as a parameter in a controller.

### Actual Behaviour

As discussed during the engineering meeting I file this issue. This is coming from https://github.com/micronaut-projects/micronaut-openapi/issues/611

Given the following Controller:

```kotlin
@Validated
@Controller("/v1/customers")
class CustomersController {

    @Post
    @Status(HttpStatus.CREATED)
    fun createCustomer(@Valid @Body request: CreateCustomerRequest) {
    }

}
```

And data class:

```kotlin
@Introspected
data class CreateCustomerRequest(
    @field:JsonIgnore
    @field:NotNull
    val customerName: String,

    @field:NotNull
    @field:PastOrPresent
    val birthDate: LocalDate
)
```

When sending the following curl request:

```
curl -X POST -H 'Content-Type:application/json' -d '{}' localhost:8080/v1/customers
```

The response is:

```json
{
  "message": "Bad Request",
  "_links": {
    "self": {
      "href": "/v1/customers",
      "templated": false
    }
  },
  "_embedded": {
    "errors": [
      {
        "message": "Failed to convert argument [request] for value [null] due to: Missing required creator property 'customerName' (index 0)\n at [Source: UNKNOWN; line: -1, column: -1]",
        "path": "/request"
      }
    ]
  }
}
```

Making the fields optional in the data class changing the type to `String?` and `LocalDate?` as mentioned in the linked issue makes this works, but then the generated OpenAPI is not consistent (see more details in that issue)

Using the-kind-of-equivalent Java POJO:

```java
@Introspected
public class CreateCustomerRequest {

    @NotNull
    private final String customerName;

    @NotNull
    @PastOrPresent
    private final LocalDate birthDate;

    public CreateCustomerRequest(String customerName, LocalDate birthDate) {
        this.customerName = customerName;
        this.birthDate = birthDate;
    }

    public String getCustomerName() {
        return customerName;
    }

    public LocalDate getBirthDate() {
        return birthDate;
    }
}
```
Works because Java allows to instantiate a POJO with nulls but Kotlin doesn't.

@sdelamo suggested having two data classes, one for the validation (that allows null) and then other for using internally in the rest of the code. Something like:

```kotlin
@Introspected
data class CreateCustomerRequest2(

    @field:NotNull
    val customerName: String,

    @field:NotNull
    @field:PastOrPresent
    val birthDate: LocalDate
)

    @Post
    @Status(HttpStatus.CREATED)
    fun createCustomer(@Valid @Body request: CreateCustomerRequest) {
        val req2 = CreateCustomerRequest2(request.customerName!!, request.birthDate!!)
        // ...
    }
```

### Steps To Reproduce

- `git clone https://github.com/micronaut-core-issues-test-app/validation-kotlin-dataclass`
- `cd validation-kotlin-dataclass`
- `./gradlew run`
- `curl -X POST -H 'Content-Type:application/json' -d '{}' localhost:8080/v1/customers`

### Environment Information

- Linux Mint 20.2
- JDK8

### Version

3.2.3

**Comment by graemerocher** [comment]
Have you tried adding https://search.maven.org/artifact/io.micronaut.kotlin/micronaut-kotlin-runtime/3.0.0/

**Comment by ilopmar** [comment]
Do you mean adding `micronaut-kotlin-runtime:3.0.0`?

**Comment by ilopmar** [comment]
If that's the case, then yes, it's already on the classpath

**Comment by schrek1** [comment]
is any progress with it?

**Comment by altro3** [comment]
@graemerocher @dstepanov I think, you can close it. I fixed kotlin optional types with `@NotNull` annotations here: https://github.com/micronaut-projects/micronaut-openapi/pull/1444.

Now if you write this:
```kotlin
@Introspected
data class CreateCustomerRequest(
    @field:JsonIgnore
    @field:NotNull
    val customerName: String?,

    @field:NotNull
    @field:PastOrPresent
    val birthDate: LocalDate?
)
```
both properties will be required in openapi specification
