### ISSUE TITLE
Response from streaming api has connection closed

### ISSUE THREAD

**Issue by msequino** [micronaut-projects/micronaut-core#6684]
### Issue description

I have a Micronaut application as middleware to another rest application. I need to define an API that streams the streaming response of the other application. 
When I call the streaming api that is forwarded to the other service, the connection is closed before stream all data. The result is a file with corrent number of pages, but empty.

The api definition is the following (this produces wrong headers). If I change return type as StreamedFile (in this way I need to persist the stream of the external service as tempfile), it works like a charm.

```
    @Get(value = "/ecr/last", processes = MediaType.APPLICATION_OCTET_STREAM)
    @Produces(MediaType.APPLICATION_PDF)
    @ApiResponse(content = @Content(mediaType = APPLICATION_PDF_TYPE,
            schema = @Schema(type = "string", format = "binary")), description = "Download estratto conto")
    public **HttpResponse<Flowable<byte[]>>** downloadLastTransactions(@Context HttpRequest<?> httpRequest, @QueryValue String number,
                                                                   @QueryValue String typ, @QueryValue String abi) {
        return downloadServiceClient.downloadLastEcr(getAuthorization(httpRequest), number, typ, abi);
    }
```

Is the way I defined the api right?
Thanks

_RIGHT HEADERS:_ 
HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://localhost:4200
Vary: Origin
Access-Control-Expose-Headers: Content-Type
Access-Control-Expose-Headers: Content-Disposition
Access-Control-Expose-Headers: Authorization
Access-Control-Allow-Credentials: true
Date: Wed, 22 Dec 2021 15:58:28 GMT
**connection: keep-alive**
Content-Type: [application/pdf]
Date: Wed, 22 Dec 2021 15:58:28 GMT
Expires: Wed, 22 Dec 2021 15:59:28 GMT
Cache-Control: private, max-age=60
Last-Modified: Wed, 22 Dec 2021 15:58:28 GMT
Content-Length: 115892
Content-Disposition: attachment; filename="filename.pdf"

_WRONG HEADERS:_
HTTP/1.1 200 Ok
Access-Control-Allow-Origin: http://localhost:4200
Vary: Origin
Access-Control-Expose-Headers: Content-Type
Access-Control-Expose-Headers: Content-Disposition
Access-Control-Expose-Headers: Authorization
Access-Control-Allow-Credentials: true
Date: Wed, 22 Dec 2021 16:07:54 GMT
**connection: close**
content-type: application/pdf
Date: Wed, 22 Dec 2021 16:07:54 GMT
content-length: 115892
Content-Disposition: attachment; filename="filename.pdf"
transfer-encoding: chunked

**Comment by yawkat** [comment]
Can you give a bit more detail? In particular the structure of the `Flow`. Best would be a test case project that reproduces this issue

**Comment by jameskleeh** [comment]
Closing this due to a lack of feedback
