### ISSUE TITLE
body of response in HttpClientResponseException can't be parsed

### ISSUE THREAD

**Issue by adrien-bonnin-cbp** [micronaut-projects/micronaut-core#669]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a @Controller with a method that return a bad request with a ***custom body***
(ex: `def response = HttpResponse.badRequest(error)`)
2. Create a @Client that call this method
3. Create a Spock Specification that use the @Client to call the @Controller
4. In the then: block try to parse the ***custom response body***
(ex: `def error = ex.response.getBody(CustomError).get()`)

### Expected Behaviour

The response body is parsed in order to assert values in it

### Actual Behaviour

An exception is raised :
```
java.util.NoSuchElementException: No value present

	at java.util.Optional.get(Optional.java:135)
	at example.micronaut.HelloClientSpec.test hello world(HelloClientSpec.groovy:27)
```

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** RC1
- **JDK Version:** 1.8

### Example Application

- https://github.com/adrien-bonnin-cbp/micronaut-issue-spock-client-exception
- It's a regression from RC1 : the first commit is the M4 version and the second the RC1 one.

Stacktrace :
```
13:40:27.325 [main] INFO  i.m.context.env.DefaultEnvironment - Established active environments: [test]

java.util.NoSuchElementException: No value present

	at java.util.Optional.get(Optional.java:135)
	at example.micronaut.HelloClientSpec.test hello world(HelloClientSpec.groovy:27)
```

**Comment by graemerocher** [comment]
This is not actually a bug, there was previously a bug where it was possible to access the body for a random period until it was GC'ed by Netty which was fixed. When you do:

```
def error = ex.response.getBody(CustomError).get()
```

It is not possible to retrieve the body because it has been cleaned up already as the request has terminated and Micronaut cannot convert a body that is not there.

To help with this issue in RC1 you can declare an error type on `@Client`:

```groovy
@Client(uri='/hello', errorType=CustomError.class)
```

**Comment by adrien-bonnin-cbp** [comment]
Thank you 😄

The correct `@Client` syntax is :
```groovy
@Client(value = '/hello', errorType = CustomError)
```

An example can be found in tests :
https://github.com/micronaut-projects/micronaut-core/blob/master/http-client/src/test/groovy/io/micronaut/http/client/CustomErrorTypeSpec.groovy

**Comment by abedurftig** [comment]
@graemerocher I am getting familiar with Micronaut using Kotlin. I cannot make it work... when I look at the tests below, then I would assume that it should not work with blocking clients as well. Could you give me a hint?

https://github.com/micronaut-projects/micronaut-core/blob/master/validation/src/test/groovy/io/micronaut/validation/ValidatedSpec.groovy

**Comment by graemerocher** [comment]
@abedurftig please report an issue with what is not working for you with an example of what doesn't work and we can take a look.
