### ISSUE TITLE
@RequestAttribute in HTTP Client is being treated as a Query Parameter in 3.2.x

### ISSUE THREAD

**Issue by NickHackman** [micronaut-projects/micronaut-core#6717]
### Expected Behavior

> Request attributes are intended for internal data sharing only, and are not attached to the outbound request.

https://docs.micronaut.io/latest/api/io/micronaut/http/annotation/RequestAttribute.html

### Actual Behaviour

They're being bound as Query Parameters, for example

```kotlin
@Client(id = "example")
interface ExampleClient {
  @Post("example/uri")
  suspend fun postExample(@Body body: requestExample, @RequestAttribute("example") metadata: Int): ExampleResponse
}
```

Expected URI:

```
https://example.com/example/uri
```

Actual URI:

```
https://example.com/example/uri?example=5
```

## Real Example:

GitHub Action Error:

https://github.com/NickHackman/micronaut-request-attributes-bug/runs/4730047911?check_suite_focus=true#step:4:41

Code:

https://github.com/NickHackman/micronaut-request-attributes-bug/blob/main/src/test/kotlin/example/request/attribute/bug/ExampleRequestAttributeBugTest.kt#L50-L82

### Steps To Reproduce

Above code provided in "Actual Behavior" or use example Application provided.

### Environment Information

- Operating System: MacOS
- Java: 11
- Kotlin: 1.6.0

### Example Application

https://github.com/NickHackman/micronaut-request-attributes-bug

### Version

3.2.x

**Comment by yawkat** [comment]
Ok the reason for this is as follows:

- a3c46be7bf2cb6fc91a90985e767fb4f19782b8d added the capability to have a `@RequestAttribute` that is also a path param. We have a test case for this: https://github.com/micronaut-projects/micronaut-core/blob/fb109714d62c099d05b67a9c1ad081fe51472732/http-client/src/test/groovy/io/micronaut/http/client/docs/annotation/requestattributes/StoryClient.java#L34-L36 In that test case, the `storyId` parameter is used as a path param, but is also used by the client filter as a request attribute.
- Path params that aren't bound in the request uri are automatically added as query params.

Not sure how to best fix this. I could simply revert the first behavior – it isn't really necessary imo, but it would be a breaking change. 

Another alternative would be to create an "optional" form of path params that aren't bound to query params, but will still be used when referenced explicitly in the path spec. This is a bit weird api-wise though in `ClientRequestUriContext`, it adds complexity.

@graemerocher thoughts?

**Comment by graemerocher** [comment]
This should be reverted

**Comment by NickHackman** [comment]
Thanks for the awesome work fixing this, don't mean to rush, but is there an estimated time for a new release for this?
