### ISSUE TITLE
Micronaut 3 HttpServerFilter doesn't add content-type header to response

### ISSUE THREAD

**Issue by LajosPolya** [micronaut-projects/micronaut-core#6724]
### Expected Behavior

I'm expecting that the HttpServerFilter will add the content-type header to the response when the response is generated from the filter.
Note that this bug specifically applies only to the case when the execution never reaches a controller. Instead the filter interrupts the execution and returns a response of its own.   

I'm expecting this behavior because Micronaut 2.4.2 behaved this way.

### Actual Behaviour

The response generated in the HttpServerFilter is doesn't contain a content-type header therefore the response looks malformed by the Http Client.

### Steps To Reproduce

https://github.com/LajosPolya/micronaut_2_4_0_http_filter
https://github.com/LajosPolya/micronaut_3_2_4_http_filter
The above two repos contain the example code. They're both generated by `mn create-app`.
1. Run the Micronaut 2.4.0 application. When calling `GET /home` you'll see that a JSON response is returned from the filter, the controller is never reached
2. Run the Micronaut 3.2.4 application. Calling `GET /home` will return a malformed response with no content-type
3. Calling `GET /home-with-header` returns the correct JSON response since the header is programmatically added

### Environment Information

Reproduced on both Windows 10 and macOS Monterey.
Reproduced on both JDK 11 and JDK 16, using Kotlin 1.6
Micronaut 3.2.4

### Example Application

https://github.com/LajosPolya/micronaut_3_2_4_http_filter

### Version

3.2.4

**Comment by LajosPolya** [comment]
I wanted to mention that I don't know the spec well enough to say for sure that this is a bug. This may be a known change in Micronaut 3.x.x so I'd like to confirm that as well.

**Comment by yawkat** [comment]
Thanks for the reproducer repo!
