### ISSUE TITLE
Error compiling Data JDBC interface

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#6744]
### Expected Behavior

Micronaut Data JDBC applications should compile.

### Actual Behaviour

All the Data JDBC test applications in GraalVM CI have failed during compilation today with the error:

```
> Task :compileJava FAILED
warning: unknown enum constant When.MAYBE
  reason: class file for javax.annotation.meta.When not found
error: Unable to implement Repository method: PetRepository.update(Object entity). No value available for annotation member @io.micronaut.data.annotation.AutoPopulated[updateable] of type: class java.lang.Boolean
Note: Creating bean classes for 7 type elements
warning: unknown enum constant When.MAYBE
  reason: class file for javax.annotation.meta.When not found
1 error
2 warnings
```

They worked yesterday and nothing has changed in Micronaut Data so the error should be here in core.

### Steps To Reproduce

- `git clone https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal`
- `cd micronaut-data-jdbc-graal`
- `git checkout 3.2.x_h2`
- `./gradlew compileJava`

### Environment Information

Linux Mint 20.3
JDK 8

### Version

3.2.5-SNAPSHOT

**Comment by dstepanov** [comment]
Caused by https://github.com/micronaut-projects/micronaut-core/pull/6734
