### ISSUE TITLE
Error getting values from Enum when using Groovy

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#6760]
### Expected Behavior

When using Groovy and getting the values from an `enum` having an `EnumElement`, Micronaut should return the right values.

### Actual Behaviour

Given the following Groovy Enum: 

```groovy
enum Type {
    DOG, CAT
}
```

When processing it in micronaut-openapi to get the values, Micronaut returns `DOG`, `CAT`, `MIN_VALUE` and `MAX_VALUE` and it should only return `DOG` and `CAT`.

The issues is here https://github.com/micronaut-projects/micronaut-core/blob/3.2.x/inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyEnumElement.java#L56-L60 but while debugging I can't find a way to differentiate those extra values from the "right" ones. 

This only happens with Groovy, it works properly with Java.

Related Micronaut OpenAPI issue that should be closed when this is fixed https://github.com/micronaut-projects/micronaut-openapi/issues/358

### Environment Information

Linux Mint 20.3
JDK 8

### Version

3.2.6

**Comment by yawkat** [comment]
Could just hard-code the exclusion for MIN_VALUE and MAX_VALUE

**Comment by ilopmar** [comment]
I though about it but it feels dirty... If there is no other way, I can do it.
