### ISSUE TITLE
Create a native Kotlin compiler extension with KSP

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-core#6781]
### Feature description

Should resolve the following issues:

https://github.com/micronaut-projects/micronaut-core/issues?q=is%3Aopen+is%3Aissue+label%3A%22relates-to%3A+native-kotlin%22

**Comment by Xaseron** [comment]
Awesome. This is a requirement to enable parallel compilation in Kotlin 1.6.20. https://blog.jetbrains.com/kotlin/2022/02/kotlin-1-6-20-m1-released/#support-for-parallel-compilation-of-a-single-module-in-the-jvm-backend

**Comment by jameskleeh** [comment]
TODO: Fail compilation if method passed to `@ConfigurationBuilder(factoryMethod=` is not annotated with `@JvmStatic`

Example: This will fail at runtime because `Test.build()` doesn't exist.
```
@ConfigurationProperties("test")
class MyProperties {
    
    @ConfigurationBuilder(factoryMethod="build")
    var test: Test? = null
}

class Test private constructor() {

    var foo: String? = null
    
    companion object {
        fun build(): Test {
            return Test()
        }
    }
}
```

**Comment by LifeIsStrange** [comment]
@Xaseron
> This is a requirement to enable parallel compilation in Kotlin 1.6.20. https://blog.jetbrains.com/kotlin/2022/02/kotlin-1-6-20-m1-released/#support-for-parallel-compilation-of-a-single-module-in-the-jvm-backend

Note that this is expected to be fixed in Kotlin 1.7.20 https://youtrack.jetbrains.com/issue/KT-49682
but yeah unfortunately KAPT is maintained but deprecated at the moment :/

**Comment by sgammon** [comment]
@jameskleeh we are writing a downstream framework which uses micronaut from Kotlin Multiplatform -- we can't use K2 or MPP easily without KSP. is there a way we could test against this before it is out? i've seen the relevant branch but don't want to build against it (on `3.7.x`) without a go-ahead from you first.

**Comment by graemerocher** [comment]
Implemented in https://github.com/micronaut-projects/micronaut-core/pull/8462

**Comment by sgammon** [comment]
huge news!!! @graemerocher thank you!!
