### ISSUE TITLE
`:core:test` spends most of the time initializing test classes

### ISSUE THREAD

**Issue by alextu** [micronaut-projects/micronaut-core#6791]
### Issue description

`:core:test` task takes [about 1min](https://ge.micronaut.io/s/hhzofcpjbcmci/timeline?details=m6g5y4lib3e3u) but the executed tests themselves take [about 10s](https://ge.micronaut.io/s/hhzofcpjbcmci/tests/overview?task-path=:core:test&toggled=WyI6Y29yZTp0ZXN0LTE2LWlvLm1pY3JvbmF1dC5jb3JlLmFubm90YXRpb24uaW1tdXRhYmxlc29ydGVkc3RyaW5nc2FycmF5bWFwdGVzdC0yMCIsIjpjb3JlOnRlc3QtMTYiXQ#:core:test-16)

The bottleneck seems to be `ImmutableSortedStringsArrayMapTest` spending most of the time in class initialization, `Set<String> ABSENT = KEYS - PRESENT` seems to be the culprit spending most of the time in metaclass calls. Replacing it with 
```        
        KEYS.removeAll(PRESENT)
        ABSENT = KEYS
``` 
does the trick and init time is unoticeable. I can submit a PR.

**Comment by yawkat** [comment]
Good catch, please make a PR

**Comment by timyates** [comment]
Awesome, fixed by https://github.com/micronaut-projects/micronaut-core/pull/6799 👍
