### ISSUE TITLE
@Retryable on interface 

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-core#6814]
### Expected Behavior

Since micronaut 3.0, `@Retryable` is not inherited following [this table](https://docs.micronaut.io/latest/guide/index.html#breaks) 

But on the docs [here](https://docs.micronaut.io/latest/guide/index.html#retry): 
> Note also that the @Retryable annotation can be applied on interfaces, and the behaviour is inherited through annotation metadata. The implication of this is that @Retryable can be used in combination with Introduction Advice such as the HTTP Client annotation.
This suggest that `@Retryable` is inherited.

What is the expected behaviour here ? Does the error is on the doc or the behaviour ? 

### Version

3.2.6

**Comment by graemerocher** [comment]
this is a documentation error. This was changed to allow users to override through inheritance. You can re-instate the previous behaviour with your own `@Inherited` meta annotation:

```java

@Inherited
@Documented
@Retention(RUNTIME)
@Target({ElementType.METHOD, ElementType.TYPE, ElementType.ANNOTATION_TYPE})
@Retryable
public @interface MyRetryable {
}
````

This is handy anyway since you can provide default configuration values specific to your app in the meta annotation

**Comment by tchiotludo** [comment]
Thanks @graemerocher for your incredible fast response. 
Struggling since this morning on this : 

https://github.com/micronaut-projects/micronaut-core/blob/4626884e74334e247f0e5fc510d6a03e616aeb75/runtime/src/main/java/io/micronaut/retry/intercept/DefaultRetryInterceptor.java#L216

Why only capture the `RuntimeException` and not `Throwable` ? 
In my case, it's a `IoException` that don't extends `RuntimeException`. 

Is this an intended behaviour ?

**Comment by graemerocher** [comment]
good question, we should probably make the base type extensible

**Comment by tchiotludo** [comment]
something like that https://github.com/micronaut-projects/micronaut-core/pull/6821 ?
