### ISSUE TITLE
CORS PenTest Finding

### ISSUE THREAD

**Issue by osh-zuri** [micronaut-projects/micronaut-core#6815]
### Expected Behavior

When CORS is enabled, along with which origins should be allowed, then an invalid Origin should be Forbidden.

Here is the actual PenTest finding:
<img width="1258" alt="PenTest-CORS" src="https://user-images.githubusercontent.com/66199635/151150976-48d8243f-5d7a-43e0-86c8-caf8022870c8.png">

In another project using SpringBoot we can achieve this requirement with the allowedOrigins configuration: https://spring.io/guides/gs/rest-service-cors/#global-cors-configuration

### Actual Behaviour

An invalid Origin passes through and returns data when the origin doesn't match the configured allowedOrigins.

### Steps To Reproduce

./gradlew check

### Environment Information

Java 17
OSX

### Example Application

https://github.com/osh-onstructive/micronaut-issue-cors-pentest-finding

### Version

3.2.7

**Comment by jameskleeh** [comment]
The origin header is not present in the response:

```
$ curl -i http://localhost:8080/test/cors -H "Origin: http://cors-attack"
HTTP/1.1 200 OK
date: Wed, 26 Jan 2022 14:29:16 GMT
Content-Type: application/json
content-length: 10
connection: keep-alive
```

This is the same behavior as if no origin header was sent at all. The browser would block the response in this case.

**Comment by jameskleeh** [comment]
If you can point me to where in the specification it says that the response should be 400 in this case, we will change the behavior. I looked but couldn't find anything definitive.

**Comment by osh-zuri** [comment]
Hi @jameskleeh 

Thanks for your response, but maybe I will start again and rephrase the question.

The PenTest finding indicated that whatever origin is sent to our Micronaut application during the GET request, we simply reflect this value in the response header **Access-Control-Allow-Origin**, for example (running against a Micronaut 3.2.7 application):

```
# REQUEST
GET https://service.osian.ch/consumer/test
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"
Accept: application/json
Accept-Language: DE
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
sec-ch-ua-platform: "macOS"
Origin: https://malicious-provider.osian.ch
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty

# RESPONSE
HTTP/1.1 200 OK
Date: Thu, 27 Jan 2022 08:41:35 GMT
Server: Apache
Set-Cookie: ....
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://malicious-provider.osian.ch
Adc-Request-Id: ...
Vary: Origin
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
Feature-Policy: autoplay 'self'; camera 'self'; display-capture 'self'; document-domain 'self'; encrypted-media 'self'; fullscreen 'self'; geolocation 'self'; microphone 'self'; midi 'self'; payment 'self'; vr 'self'; xr 'self'
Strict-Transport-Security: max-age=63072000; includeSubDomains
Keep-Alive: timeout=10, max=500
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: application/json
```



To solve this with our legacy Spring applications, we can supply a list of allowedOrigins which act as a whitelist, and if the origin doesn't match the value in the list, the client receives a FORBIDDEN Http response, see:

* <https://spring.io/guides/gs/rest-service-cors/#global-cors-configuration>
* <https://github.com/spring-projects/spring-framework/blob/29768cdd11883b77ba463cccc525b96247a30fd0/spring-web/src/main/java/org/springframework/web/cors/DefaultCorsProcessor.java#L119>

With Micronaut we configured a whitelist too and defined the allowed origins.

```yaml
micronaut:
  application:
    name: corsPentestFinding
  server:
    cors:
      enabled: true
      configurations:
        all:
          allowedOrigins: '${ALLOWED_ORIGINS:http://localhost}'
```

But with the Micronaut implementation it doesn't seem to treat the configuration as a whitelist; if the Origin isn't found in the configuration it simply passes the request through without interfering.

```java
protected Optional<MutableHttpResponse<?>> handleRequest(HttpRequest request) {
        HttpHeaders headers = request.getHeaders();
        Optional<String> originHeader = headers.getOrigin();
        if (originHeader.isPresent()) {

            String requestOrigin = originHeader.get();
            boolean preflight = CorsUtil.isPreflightRequest(request);

            Optional<CorsOriginConfiguration> optionalConfig = getConfiguration(requestOrigin);
            
            /*
            When there are configured 'configurations', then these should be treated as a whitelist and restrict 
            the access accordingly
            */

            if (optionalConfig.isPresent()) {
                CorsOriginConfiguration config = optionalConfig.get();

                HttpMethod requestMethod = request.getMethod();

                List<HttpMethod> allowedMethods = config.getAllowedMethods();

                if (!isAnyMethod(allowedMethods)) {
                    HttpMethod methodToMatch = preflight ? headers.getFirst(ACCESS_CONTROL_REQUEST_METHOD, CONVERSION_CONTEXT_HTTP_METHOD).orElse(requestMethod) : requestMethod;
                    if (allowedMethods.stream().noneMatch(method -> method.equals(methodToMatch))) {
                        return Optional.of(HttpResponse.status(HttpStatus.FORBIDDEN));
                    }
                }

                if (preflight) {
                    Optional<List<String>> accessControlHeaders = headers.get(ACCESS_CONTROL_REQUEST_HEADERS, ConversionContext.LIST_OF_STRING);

                    List<String> allowedHeaders = config.getAllowedHeaders();

                    if (!isAny(allowedHeaders) && accessControlHeaders.isPresent()) {
                        if (!accessControlHeaders.get().stream()
                            .allMatch(header -> allowedHeaders.stream()
                                .anyMatch(allowedHeader -> allowedHeader.equalsIgnoreCase(header.trim())))) {
                            return Optional.of(HttpResponse.status(HttpStatus.FORBIDDEN));
                        }
                    }

                    MutableHttpResponse<Object> ok = HttpResponse.ok();
                    handleResponse(request, ok);
                    return Optional.of(ok);
                }
            }
        }

        return Optional.empty();
    }
```

The thing here is that we would like to declare what origins can talk to the API and all others should be rejected.

Any idea how can we solve the same PenTest finding with our Micronaut applications?

**Comment by yawkat** [comment]
If your request has `Origin: https://malicious-provider.osian.ch`, and that origin is not matched in the micronaut config, it will be treated the same way as if no origin is present. It should not give a `Access-Control-Allow-Origin: https://malicious-provider.osian.ch` like in your example response, it should simply send no `Access-Control-` headers at all.

Are you sure your example request/response is produced by the config you give?

**Comment by osh-zuri** [comment]
Hi, many thanks for your response; and you are correct ... what was misleading is that the Spring implementation returns a Forbidden status, and here the `Access-Control-Allow-Origin` is missing, both seem to be a valid understanding of the specification.
Closing the issue, & thanks for all your help.

**Comment by timyates** [comment]
Does `ALLOWED_ORIGINS` contain a wildcard?

**Comment by osh-zuri** [comment]
Hi @timyates 
Tha allowed origins doesn't contain a wildcard, but after all of the explanations, it is now deployed and working as expected.
Many thanks
