### ISSUE TITLE
Micronaut 3.3: Flyway Upgrade breaks MariaDB/MySQL projects

### ISSUE THREAD

**Issue by saw303** [micronaut-projects/micronaut-core#6829]
### Expected Behavior

Running `mn create-app --build=gradle --jdk=11 --lang=java --test=spock --features=flyway,mariadb com.example.demo` should generate a `build.gradle` with an additional runtime dependency 

```groovy
runtimeOnly "org.flywaydb:flyway-mysql"
```

Note the the version should be provided by the BOM.

### Actual Behaviour

Micronaut 3.3.0 upgraded Micronaut Flyway 5.1.1 to use Flyway to 8.4.2. MariaDB and MySQL are no longer part of the Flyway Core. The Flyway website states:

> MariaDB support is a separate dependency for Flyway and will need to be added to your Java project to access these features. MariaDB is found within the flyway-mysql plugin module.

To make it work again I manually have to add the following runtime dependency to my `build.gradle`.

```groovy
runtimeOnly "org.flywaydb:flyway-mysql:8.4.2"
```

Since the `flyway-mysql` module is not covered by the Micronaut BOM I have to declare a specific Flyway version number.

### Steps To Reproduce

1. run `mn create-app --build=gradle --jdk=11 --lang=java --test=spock --features=flyway,mariadb com.example.demo`
2. open the `build.gradle`
3. find the flyway-mysql plugin missing

Or use Micronaut Launch with the features `flyway` & `MariaDB` and press preview.

### Version

3.3.0

**Comment by jameskleeh** [comment]
https://github.com/micronaut-projects/micronaut-flyway/pull/271

**Comment by saw303** [comment]
@jameskleeh will the template of Micronaut Launch also be extended when someone chooses MySQL, MariaDB or SQL Service together with the feature Flyway?

**Comment by jameskleeh** [comment]
https://github.com/micronaut-projects/micronaut-starter/pull/1055
