### ISSUE TITLE
Old tracing artifact missing from bom

### ISSUE THREAD

**Issue by jameskleeh** [micronaut-projects/micronaut-core#6831]
### Issue description

The old tracing group id and artifact id need to be in the bom for 3.3

**Comment by timyates** [comment]
@jameskleeh I assume we want the same (old) version as well?

**Comment by jameskleeh** [comment]
@timyates I made the change already https://github.com/micronaut-projects/micronaut-core/pull/6871

**Comment by timyates** [comment]
Cool 👍
