### ISSUE TITLE
trying to upgrade my application from Micronaut 3.1, but with both M3.2 and M3.3 Kapt throws TaskExecutionException: Execution failed for task ':kaptKotlin' and Caused by: java.util.NoSuchElementException: No value present

### ISSUE THREAD

**Issue by dniel** [micronaut-projects/micronaut-core#6840]
### Expected Behavior

When running `./gradlew build` in my application with Micronaut 3.3.0 kapt should execute successfully.

### Actual Behaviour

Both m3.2 and m3.3 Kapt throws `TaskExecutionException: Execution failed for task ':kaptKotlin' and Caused by: java.util.NoSuchElementException: No value present at io.micronaut.inject.writer.BeanDefinitionWriter.pushPropertyContainsCheck(BeanDefinitionWriter.java:2025)`

### Steps To Reproduce

1. https://github.com/dniel/traefik-forward-auth0/tree/3.0-alpha-micronaut
2. run `./gradlew build`
3. Task :kaptKotlin run successfully
4. in https://github.com/dniel/traefik-forward-auth0/blob/3.0-alpha-micronaut/gradle.properties#L2 change to 3.3.0
5. run `./gradlew build` again
6. kaptKotlin fails with `':kaptKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)`

### Environment Information

- latest ubuntu
- adoptopenjdk17
- kotlin 1.6.10
- gradle 7.3.3

### Example Application

https://github.com/dniel/traefik-forward-auth0/tree/3.0-alpha-micronaut

### Version

3.3.0

**Comment by jonnii** [comment]
We're also running into the same problem, is there anything else we can provide to help diagnose the issue?

**Comment by jonnii** [comment]
We just tried updating to 3.3.4 and still see the same issue.

**Comment by jameskleeh** [comment]
The cause is ApplicationSettings

It does not make sense to combine `@EachProperty` while using `@Value` on each of the properties. Simply removing `@Value` from the properties allows the code to compile.

**Comment by dniel** [comment]
@jameskleeh Thanx for the feedback! :+1:  It did work when I removed `@value` as you described.

My trouble here was really how to find the issue without any obvious log messages pointing to the class with the problem, or did I miss something in the error messages?  How did you diagnose the problem? Would be nice to know for the next time something like this happens.
