### ISSUE TITLE
Upgrade jackson-databind to get rid of medium vulnerability CVE FasterXML/jackson-databind#3328

### ISSUE THREAD

**Issue by mariusbalanuca** [micronaut-projects/micronaut-core#6844]
### Issue description

Upgrade jackson-databind to get rid of medium vulnerability CVE FasterXML/jackson-databind#3328

**Comment by yawkat** [comment]
Fixed in #6846 

FYI this is probably not an issue for most micronaut users, since it only affects *jdk deserialization* (eg ObjectInputStream) of arbitrary types.
