### ISSUE TITLE
Update Library Catalogue to use servlet bom included in 3.2.0

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#6854]
[Micronaut Servlet 3.2.0](https://github.com/micronaut-projects/micronaut-servlet/releases/tag/v3.2.0) introduced a bom module. 

I think this PR should be similar to: 

https://github.com/micronaut-projects/micronaut-core/pull/6806

Important property:
https://github.com/micronaut-projects/micronaut-servlet/blob/master/gradle.properties#L28

Because the property is named `micronautServletVersion`, the one in the version catalogue should be `managed-micronaut-servlet`

See:

https://github.com/micronaut-projects/github-actions/commit/7698c8eee841b5ae61a1f0225fd2ca14a48f500e

That way automatic PRs are issued to update the version catalogue number when new releases of Micronaut Servlet happen. 

The PR should target 3.4.x as base

**Comment by timyates** [comment]
Closed by https://github.com/micronaut-projects/micronaut-core/pull/6856
