### ISSUE TITLE
Netflix archaius is not picking up properties from config.properties

### ISSUE THREAD

**Issue by RaviH** [micronaut-projects/micronaut-core#687]
I have attached a sample project. Micronaut doesn't seem to work with netflix-archaius as expected.

### Steps to Reproduce

a. You can either unzip the project or execute this command:

`mn create-app --features annotation-api,netflix-archaius,http-server --lang java --build maven archaius-example`

b. Create a controller like:
```
@Controller("/foo")
public class FooController {

    @Value("${foo:NOT SET}")
    private String p;

    @Get("/")
    public String index() {

        return "property value is: " + p;
    }
}
```
c. Add config.properties:
```
foo=bar
```

d. Execute `curl "http://localhost:8080/foo"`

It should print **property value is: NOT SET**

### Task List

- [Y ] Steps to reproduce provided
- [ N/A] Stacktrace (if present) provided
- [ Y] Example that reproduces the problem uploaded to Github
- [Y ] Full description of the issue provided (see below)

### Expected Behaviour

Micronaut service should read from config.properties

### Actual Behaviour

Micronaut service is **not** reading from config.properties

### Environment Information

- **Operating System**: Mac OS High Seirra 10.13.4 
- **Micronaut Version:** 1.0.0.RC1
- **JDK Version:** 

```
$ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

### Example Application
[arrchaius-example.zip](https://github.com/micronaut-projects/micronaut-core/files/2448567/arrchaius-example.zip)

**Comment by jameskleeh** [comment]
@RaviH This doesn't have anything to do with archaius as far as I can tell. The config file must be named `application.properties`.

**Comment by RaviH** [comment]
Hey James ,

That's not my understanding. One can work with Netflix archaius in 2 ways:

A. Add a file called config.properties
B. Provide additional config url property as a system property.


https://github.com/Netflix/archaius/wiki/Getting-Started

As a matter of fact when I trace the logs, it is registering those 2 locations.

It's just that the property is not set when I read it in micronaut. 

Plus, if I have to place property in application.properties than how's that working with Netflix archaius?

Does that make sense? What am I missing?


P.S: I would highly recommend not closing the issue before getting a confirmation from the originator.

**Comment by jameskleeh** [comment]
@RaviH There is one other option, which is to load the property source yourself as part of starting the app. Something like this:

```        Micronaut.build(new String[0])
                .classes(Application.class)
                .propertySources(new PropertiesPropertySourceLoader().load("config", ClassPathResourceLoader.defaultLoader(Application.class.getClassLoader()), null).orElse(null))
                .start();```

**Comment by RaviH** [comment]
@jameskleeh Thank you for looking into this. My problem is we use netflix-archaius which in summary reloads the config every configurable seconds from a url which we provide via `-Darchaius.configurationSource.additionalUrls=http://configservice/servicename` 

This would be a deal breaker for my team. We need Netflix Archaius to work seamlessly. Would there be a way to load from a URL? Conversely, I can write the code behind refreshing from the url myself. 

What do you think?

**Comment by jameskleeh** [comment]
@RaviH I don't know how that relates to a `config.properties`, however yes you can read config from a remote source. Register a bean that implements https://github.com/micronaut-projects/micronaut-core/blob/master/inject/src/main/java/io/micronaut/context/env/BootstrapPropertySourceLocator.java

**Comment by RaviH** [comment]
@jameskleeh I think something's getting lost in translation.

Let me provide more details.

I have been using netflix-archaius for a bit so here’s what I know and based on netflix-archaius docs too:

> By default, Archaius will look for a file named “config.properties” on the application’s classpath and read its content as configuration properties. The file can be also in a jar file’s root directory.
In addition, you can define a system property “archaius.configurationSource.additionalUrls” that contains the URL path to a local configuration file. For example, add this to your application start up script

So to test whether it's working, first I provided it a `-Darchaius.configurationSource.additionalUrls=file:///home/rhasija/application.properties` and it didn't take it (in that the property defined in the file were not available). Then, I tried with `config.properties` which too didn't work. The latter is the simplest and hence that's what I opened the issue with.

A line from the logs:

`20:23:22.662 [main] INFO  c.n.c.sources.URLConfigurationSource - URLs to be used as dynamic configuration source: [file:/Users/rhasija/dev/projects/experimental/micronaut/arrchaius-example/target/classes/config.properties]`

I have also attached full log file.  [archaius-micronaut.log](https://github.com/micronaut-projects/micronaut-core/files/2448847/archaius-micronaut.log) Please review it when you get a chance, please.

Based on the above logs, I am not 100% positive that it's **not** using config.properties as source.  What I fear, is that the file is being read but I haven't configured something right for all of it to work.

Please let me know if I could clarify something better.

**Comment by RaviH** [comment]
Furthermore, I did some debugging and I can promise `config.properties` is being read:

![image](https://user-images.githubusercontent.com/141136/46514961-da788500-c815-11e8-8209-63ebeac22e99.png)

I checked right after the properties are loaded from config.properties

And than, right at this point, the properties disappear. And, hence the issue is a _possible_ bug because after loading this class: `io.micronaut.configuration.archaius1.EnvironmentDeploymentContext` the properties are lost.

![image](https://user-images.githubusercontent.com/141136/46514994-098ef680-c816-11e8-90ab-9b48571fddd6.png)

![image](https://user-images.githubusercontent.com/141136/46515022-393dfe80-c816-11e8-9721-ca941e1c95ba.png)

Either:
a. It's supposed to read from the config.properties and work seamlessly (then this is a bug ticket and should be reopened.)
b. There's some connecting config I am missing. 
c. It's not supposed to read from config.properties as you say because it's not designed to do so. Then why is it printing: `20:23:22.662 [main] INFO c.n.c.sources.URLConfigurationSource - URLs to be used as dynamic configuration source: [file:/Users/rhasija/dev/projects/experimental/micronaut/arrchaius-example/target/classes/config.properties]` and the property being actually available via `DynamicPropertyFactory` instance?

I think it's either (a) or (b) not (c) at least based on the way I am reading the logs. Please correct me and provide more info on (c) if I am wrong.

**Comment by RaviH** [comment]
Something funky is happening with `EnvironmentConfiguration`. This is the class that’s supposed to link with archaius `AbstractConfiguration`. It almost feels like there's some config I need to set.

@graemerocher I don't want to be impolite by including you directly, but I seriously think I am missing something. The way it's setup (by debugging through the code), it's supposed to work seamlessly.

@graemerocher Your input is highly appreciated.

**Comment by jameskleeh** [comment]
@RaviH You are confusing micronaut config with archaius config. Archaius is apparently loading `config.properties` as designed and shown in your debugging. That has nothing to do with Micronaut at all.

In your original example you were trying to use data from `config.properties` in a **Micronaut** bean, which as I've said will not be read by **Micronaut** by default:
```
@Controller("/foo")
public class FooController {

    @Value("${foo:NOT SET}")
    private String p;
```

**Comment by graemerocher** [comment]
@RaviH  the idea behind `EnvironmentDeploymentContext` is that it delegates to Micronaut's environment and configuration concept so that you can configure Netflix components with Micronaut's `application.yml` and have them refreshed when `RefreshEvent` is triggered. 

What this means is that you let Micronaut be in charge of loading and refreshing configuration. You can do what you want by simplify specifying `-Dmicronaut.config.files=config.properties` and it will load them. Then when you want to refresh the config hit the `/refresh` endpoint.

However, if what you want is the opposite and that is for Micronaut to delegate to Archaius then that is not currently what the `archaius` module does, however it is fairly simple to add support for this. 

You can implement a `PropertySourceLoader` that loads a `PropertySource` implementation that delegates to  Archaius.

The `PropertySourceLoader` should be registered in `META-INF/services` and the `PropertySource` methods implemented to delegate to Archaius' `Configuration` interface.

You would probably also want to implement a bean that registers a listener using `addConfigurationListener(ConfigurationListener l)` which triggers a `RefreshEvent` when the configuration changes.

If you consider implementing this, let us know, might make a good contribution!

**Comment by RaviH** [comment]
@graemerocher That information is super useful. I have created a small library that does just that. And, it works perfectly with archaius now; meaning I can use `DynamicPropertyFactory` to get the new values! 

The issue that I am currently having (in the library) is: it's not updating micronaut property values, even though I publish the `RefreshEvent`. This is probably because of `No beans found for key: <RefreshEvent> io.micronaut.context.event.ApplicationEventListener` (as shown in the logs below). This is probably because I had to remove the `io.micronaut.configuration:netflix-archaius` lib from the classpath for it to not muck my with my implementation.

```
12:51:21.210 [pollingConfigurationSource] DEBUG i.m.c.e.ApplicationEventPublisher - Publishing event: io.micronaut.runtime.context.scope.refresh.RefreshEvent[source={foo=out_bar_1}]
12:51:21.220 [pollingConfigurationSource] DEBUG i.m.context.DefaultBeanContext - Resolving beans for type: <RefreshEvent> io.micronaut.context.event.ApplicationEventListener 
12:51:21.220 [pollingConfigurationSource] TRACE i.m.context.DefaultBeanContext - Looking up existing beans for key: <RefreshEvent> io.micronaut.context.event.ApplicationEventListener
12:51:21.220 [pollingConfigurationSource] TRACE i.m.context.DefaultBeanContext - No beans found for key: <RefreshEvent> io.micronaut.context.event.ApplicationEventListener
```

I have attached the code for your reference: https://github.com/RaviH/archaius-micronaut-example

This is just sample code for demonstration purposes. Don't judge. ;-)

Thoughts?
