### ISSUE TITLE
Native image ignores properties from yaml.

### ISSUE THREAD

**Issue by spearheadOne** [micronaut-projects/micronaut-core#6874]
### Issue description

I have custom propeties in application.yaml which are not read when I run the app as native image though env endpoint shows them.

Please check here for more details https://stackoverflow.com/questions/71008037/micronaut-native-image-ignores-properties

**Comment by jameskleeh** [comment]
You are injecting into private fields, which requires reflection. Either change the fields to not be private, inject the setter method, or register the fields for reflective access with GraalVM

**Comment by graemerocher** [comment]
We do add reflection information automatically but only if you have `micronaut-graal` on your annotation processor classpath:

https://github.com/micronaut-projects/micronaut-core/blob/0f4bba77e6869a126946ebec1f74f1fc0b37640f/graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java#L208-L210

So you might want to check that.
