### ISSUE TITLE
logback.groovy no longer used after upgrading from 3.1.0 to 3.3.0

### ISSUE THREAD

**Issue by jamesdh** [micronaut-projects/micronaut-core#6885]
### Expected Behavior

Configuration via a `logback.groovy` file as opposed to a `logback.xml` file is possible and [officially supported by logback](https://logback.qos.ch/manual/groovy.html)

### Actual Behaviour

logback.groovy is ignored. 

### Steps To Reproduce

1. Take any project and apply the groovy equivalent of the default logback.xml configuration file: 

```groovy
import ch.qos.logback.classic.encoder.PatternLayoutEncoder

import static ch.qos.logback.classic.Level.*

appender("STDOUT", ConsoleAppender) {
    withJansi = true
    encoder(PatternLayoutEncoder) {
        pattern = "%cyan(%d{HH:mm:ss.SSS}) %gray([%thread]) %highlight(%-5level) %magenta(%logger{36}) - %msg%n"
    }
}

root(INFO, ['STDOUT'])
```

I tested various versions and it appears using a `logback.groovy` last worked in 3.2.7, but breaks in 3.3.0

### Environment Information

- macOS 12.2
- OpenJDK 17.0.2 aarch64

### Version

3.3.0

**Comment by graemerocher** [comment]
Unfortunately the latest version of logback removed Groovy support for security reasons. You can downgrade to an earlier version but you would do so at your own risk

**Comment by jamesdh** [comment]
Oh interesting. Their docs aren't very up to date it appears. I did find [this issue](https://jira.qos.ch/browse/LOGBACK-1601) though, which explains it.
