### ISSUE TITLE
`EmailValidator` not working properly

### ISSUE THREAD

**Issue by roma0297** [micronaut-projects/micronaut-core#6890]
### Expected Behavior

I expect that email `email@gmail` won't pass the validation

### Actual Behaviour

Email `email@gmail` Is passing the validation

### Steps To Reproduce

1. Create a simple application with `@Post` controller
2. Add `@Email` annotation to one of the string fields in the request body
3. Pass an email `email@gmail` to the request

### Version

3.3.0

**Comment by bseitkazin** [comment]
I think you are using `@Email` from `javax.validation.constraints.Email`? So, it is not an issue of the Micronaut framework, according to the answer on StackOverflow, the `email@gmail` is a valid email. 

Link - https://stackoverflow.com/questions/50535214/javax-validation-constraints-email-matching-invalid-email-address
