### ISSUE TITLE
Direct Buffers Memory leak in 3.3.1

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-core#6942]
### Expected Behavior

The application upgrade from 3.3.0 to 3.3.1 should be deployable to production and not cause memory issues in containers

### Actual Behaviour

The application very quickly causes memory issues and starts dropping requests before eventually failing.

Below are some of our grafana graphs, from production going up from v 3.1.4 through to 3.3.1.
We first noticed the issue last week when upgrading a few libs, including micronaut to the latest 3.3.3 release, and today have found the exact version causing the issue.

Here is the request saturation graph we monitor in the pods which tracks ratio between container_memory_usage_bytes and kube_pod_container_resource_requests:
![request-saturation](https://user-images.githubusercontent.com/1616940/154989047-d6b9058d-efce-4d4c-8590-3214384b23e0.png)
The app line usually settles at about 62%, but since 3.3.1 it does not settle, and eventually starts causing availability issues, increased latency and increased CPU.

Looking at the JVMs themselves, the only difference between a stable instance, and 3.3.1 was jvm_buffer_memory_used_bytes, all other data we hold (eden space, thread counts, heap, non-heap, gc times etc) all seemed to be normal except for this one value.

Here is standard instance, showing no change:
![direct-buffer-good](https://user-images.githubusercontent.com/1616940/154990615-3daa5be0-1927-4e6f-b1d2-87c69b515010.png)

Here is an example of a 3.3.1 instance:
![direct-buffer-bad](https://user-images.githubusercontent.com/1616940/154990661-8ed539ab-e958-4cf5-9bba-878680317fe2.png)

The codebase is not changed between the releases, the only change is from 3.3.0, which is working as expected, and 3.3.1 where the performance degrades very quickly (20 mins of instances being accessed in production).

### Steps To Reproduce

Upgrade working application to 3.3.1
Deploy to production

### Environment Information

Distroless image deployment in kubernetes GCP environment.
JVM 11
Kotlin application.

### Version

3.3.1

**Comment by jameskleeh** [comment]
Can you please try 3.3.3?

**Comment by markjfisher** [comment]
I updated the comments above to be more explicit, we did try 3.3.3, and then downgraded to known state and increased versions until it broke, which was 3.3.1, but 3.3.3 was broken too.

**Comment by yawkat** [comment]
Can you turn up netty leak detection? https://netty.io/wiki/reference-counted-objects.html#leak-detection-levels

Can't do much with the info in this issue

**Comment by markjfisher** [comment]
I'll have a look into that. the issue with providing more data is knowing what to provide, this is only happening obviously in production, so not the easiest to play with, but I'll try a lower environment (which we hadn't noticed this issue in) and see if we can see any problems there with more intense testing. the best we have at the moment is it's the change between 3.3.0 and 3.3.1.

**Comment by yawkat** [comment]
fwiw you could also just wait for 3.4 if it's not a huge issue to you, there are a lot of fixes in this direction in #6896

**Comment by markjfisher** [comment]
That is probably a good option, saves me spending too much time chasing my tail when there could be a fix in the pipeline. The original update to 3.3.3 was because we were getting vulnerability warnings for 3.1.2 and decided to update "all the things"™, so this isn't a blocker yet for us.

**Comment by graemerocher** [comment]
@markjfisher it still concerns me the issue is present in 3.3.x and is a regression from the previous release. If you do have time to enable leak detection and provide the logs that would be great

**Comment by markjfisher** [comment]
Does this help? I've enabled it on my local dev instance and hit it with apache bench, then noticed leak messages

[leak.txt](https://github.com/micronaut-projects/micronaut-core/files/8117776/leak.txt)

**Comment by jameskleeh** [comment]
@markjfisher That's really helpful. Thank you!

**Comment by markjfisher** [comment]
~~same ab run on 3.3.0 doesn't give those errors. i'm just upping the io.netty.leakDetection.targetRecords value and will post full logs on 3.3.3 as i'm not sure if the above is everything (that leak.txt was from 3.3.1).~~

actually, i'm having trouble reproducing this again, so here's the complete log (that contains the above) from that run in case there's anything additional in there for you.

[product-summary-leaks.log.gz](https://github.com/micronaut-projects/micronaut-core/files/8118100/product-summary-leaks.log.gz)

**Comment by jameskleeh** [comment]
@markjfisher Should be fixed in 3.3.4
