### ISSUE TITLE
wildcard for fallback endpoint is not working in @get()

### ISSUE THREAD

**Issue by chennavamshikrishna** [micronaut-projects/micronaut-core#6946]
### Expected Behavior

I created a get endpoint with * as value in a controller.I want to this endpoint to called as a fallback if none of endpoint in a controller matches

### Actual Behaviour

when I tried to endpoint  with value not present in controller fallback endpoint is not getting triggered instead i am getting 404 

### Steps To Reproduce

@Get(value=“*”)
public string getValue(){
return “apple”;
}

### Environment Information

ubuntu java version 11

### Version

3.3

**Comment by graemerocher** [comment]
`*` is not a valid uri template https://datatracker.ietf.org/doc/html/rfc6570
