### ISSUE TITLE
 ClientArgumentRequestBinder does not take precedence

### ISSUE THREAD

**Issue by sascha-frinken** [micronaut-projects/micronaut-core#6960]
### Expected Behavior

If I create a bean implementing `ClientArgumentRequestBinder` with a type that has an existing binder, mine should take precedence.

### Actual Behaviour

The original  `ClientArgumentRequestBinder`  takes precedence.

### Steps To Reproduce

1. Create a bean implementing `ClientArgumentRequestBinder<Locale>` 
```groovy
@Singleton
class MyLocaleClientArgumentRequestBinder implements ClientArgumentRequestBinder<Locale> {
    @Override
    void bind(@NonNull ArgumentConversionContext<Locale> context, @NonNull ClientRequestUriContext uriContext, @NonNull Locale value, @NonNull MutableHttpRequest<?> request) {
        // not called
        uriContext.setPathParameter('locale', value.toString())
    }
}
```
3. Set a breakpoint in the bind method
4. Create a declarative HTTP Client 
```groovy
@Client(id = "test", path = "/")
interface TestClient {
    @Get("/{locale}")
    HttpResponse<Locale> localeTest(@NotNull Locale locale)
}
```
5. Use the client and trace log the request -> there is no locale in the path as `MyLocaleClientArgumentRequestBinder` won't be used

### Environment Information

- OS: Linux
- JDK: 17

### Example Application

https://github.com/safri-net/mn-issue-6960

### Version

3.3.3

**Comment by jameskleeh** [comment]
Basically the binder must be one of `AnnotatedClientRequestBinder`, `AnnotatedClientArgumentRequestBinder`, or `TypedClientArgumentRequestBinder`. The registry should be changed to log an error if its not one of those

**Comment by sascha-frinken** [comment]
Confirm everything working as expected when implementing `TypedClientArgumentRequestBinder`.
