### ISSUE TITLE
Add MQTT Bom to 3.4.x build

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#6978]
### Issue description

See: https://github.com/micronaut-projects/micronaut-mqtt/pull/128

**Comment by sdelamo** [comment]
I have just released [MQTT 2.1.0](https://github.com/micronaut-projects/micronaut-mqtt/releases/tag/v2.1.0)

**Comment by timyates** [comment]
Fixed in https://github.com/micronaut-projects/micronaut-core/pull/7021
