### ISSUE TITLE
Hibernate/JPA Native Query

### ISSUE THREAD

**Issue by djeverson** [micronaut-projects/micronaut-core#698]
I am moving some "legacy" JPA code into Micronaut, so far pretty impressed.

Using RC1, MySQL, JDK 8, MacOS

I am having an issue making native query calls, however.

Here's the method:
```
@Override 
@Transactional(readOnly = true) 
public List<EventView> getAccountEvents(String accountId) { 
Query q = em.createNativeQuery(SQL_BY_ACCOUNT, EventView.class); 
q.setParameter("accountId", accountId); 
return q.getResultList(); 
}
```

The following error occurs on the em.createNativeQuery() line:
```
{ "message": "Internal Server Error: Method io/micronaut/configuration/hibernate/jpa/$EntityManagerFactoryBean$CurrentSessionDefinition$Intercepted.createNativeQuery(Ljava/lang/String;Ljava/lang/Class;)Ljavax/persistence/Query; is abstract" }
```

Anybody have any insight on what the issue might be?

Thanks!
Dave

**Comment by graemerocher** [comment]
I added a test for this, so it is working on core, the most likely reason you have this error is you are using an older version of Hibernate. If you upgrade to Hibernate 5.3+ (which Micronaut is compiled against) you will not encounter this issue.

**Comment by djeverson** [comment]
I am using 5.3.6.Final and am encountering this issue:
```
05:33:29.677 [main] INFO  org.hibernate.Version - HHH000412: Hibernate Core {5.3.6.Final}
```

**Comment by graemerocher** [comment]
@djeverson What issue specifically? That is just printing the Hibernate version?

**Comment by djeverson** [comment]
@graemerocher See #698, it is the issue that I submitted regarding nativequery support.  You mentioned that it is not a bug if I use Hibernate 5.3+.  I am using 5.3.6.Final and getting the error.

**Comment by graemerocher** [comment]
@djeverson please upload an example that reproduces the error

**Comment by djeverson** [comment]
[698-hello-world.zip](https://github.com/micronaut-projects/micronaut-core/files/2456747/698-hello-world.zip)

**Comment by djeverson** [comment]
I created a project that reproduces this issue (#698 - NativeQuery Support)

**Comment by graemerocher** [comment]
@djeverson Thanks for the report, I got to the bottom of it.
