### ISSUE TITLE
ProxyHttpClient.proxy() cannot proxy Server-Sent Event stream from backend.

### ISSUE THREAD

**Issue by rajakumar-sg** [micronaut-projects/micronaut-core#6985]
### Expected Behavior

SSEClient connecting to an endpoint that calls  a backend endpoint using ProxyHttpClient.proxy() should raise events same as calling the endpoint directly.

### Actual Behaviour

SSEClient connecting to an endpoint that calls  a backend endpoint using ProxyHttpClient.proxy() does not raise any event except close.

### Steps To Reproduce

Full code to reproduce the problem https://github.com/rajakumar-sg/sse-reverse-proxy
Run tests to understand the issue.

### Environment Information

MacOS

### Example Application

https://github.com/rajakumar-sg/sse-reverse-proxy

### Version

3.3.4

**Comment by timyates** [comment]
In my tests, hitting the proxy endpoint with the browser did work, but calling it from the javascript console didn't 🤔

It did start the Flux in /real/events though

**Comment by timyates** [comment]
Curl works too...

```
❯ curl http://localhost:8080/proxy/events
event: TYPE1
data: EventNo: 1

event: TYPE1
data: EventNo: 2

event: TYPE1
data: EventNo: 3

event: TYPE1
data: EventNo: 4

event: TYPE1
data: EventNo: 5

event: TYPE1
data: EventNo: 6

event: TYPE1
data: EventNo: 7

event: TYPE1
data: EventNo: 8

event: TYPE1
data: EventNo: 9

event: TYPE1
data: EventNo: 10
```

**Comment by timyates** [comment]
So it appears to be newlines getting stripped on the responses...  Investiagtions continue
