### ISSUE TITLE
openAPI and HttpResponse

### ISSUE THREAD

**Issue by hampsterx** [micronaut-projects/micronaut-core#699]
openAPI support is great but stuck on a couple of issues, note: I am new to kotlin and Java is not my strongpoint either so forgive me if there is an easy workaround for this issue.

### Steps to Reproduce
```
mn create-app hello-world --lang kotlin --features swagger-kotlin
mn create-controller hello
```
```
@Controller("/hello")
class HelloController {

    @Get("/")
    fun index(): Hello {
        return Hello(name="world")

    }
}
```

This works as expected. 

```
  /hello:
    get:
      operationId: index
      parameters: []
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
```

However when HttpResponse is returned:

```
@Controller("/hello")
class HelloController {

    @Get("/")
    fun index(): HttpResponse<Hello> {
        return HttpResponse.ok(Hello(name="world"))

    }
}
```

We now get the HttpResponse Object instead of our actual object

```
  /hello:
    get:
      operationId: index
      parameters: []
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpResponse'
```

### Expected Behaviour

Should not be any change in swagger definition?

### Actual Behaviour

We get the HttpResponse schema instead.
Note also I have tried using @ApiResponse() annotation to try and set the schema but has no effect :(

### Environment Information

- **Micronaut Version: 1.0.0.RC1

**Comment by acham** [comment]
Expanding on this, and using the latest version (1.2.5) of Micronaut:
The controller below:
```
@Get
HttpResponse<List<Pet>> ok() {
    def retlist = [new Pet(), new Pet()]
    HttpResponse.ok(retlist)
}
```
Yields this swagger yaml:
```
openapi: 3.0.1
info:
  title: my-micro-swagger2
  version: "0.0"
paths:
  /pet:
    get:
      operationId: ok
      parameters: []
      responses:
        default:
          description: ok default response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
```
That is, the type of the object in the array is not inferred.
