### ISSUE TITLE
Update Micronaut Modules to latest build infrastructure

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#6996]
### Issue description

- [ ] [Micronaut Core](https://github.com/micronaut-projects/micronaut-core)
- [x] [Micronaut Elastic Search](https://github.com/micronaut-projects/micronaut-elasticsearch)
- [x] [Micronaut JMX](https://github.com/micronaut-projects/micronaut-jmx)
- [x] [Micronaut Micrometer](https://github.com/micronaut-projects/micronaut-micrometer)
- [x] [Micronaut GraphQL](https://github.com/micronaut-projects/micronaut-graphql)
- [x] [Micronaut GRPC](https://github.com/micronaut-projects/micronaut-grpc)
- [x] [Micronaut Jackson XML](https://github.com/micronaut-projects/micronaut-jackson-xml)
- [x] [Micronaut JAX-RS](https://github.com/micronaut-projects/micronaut-jaxrs)
- [x] [Micronaut OpenAPI](https://github.com/micronaut-projects/micronaut-openapi)
- [x] [Micronaut Problem-JSON](https://github.com/micronaut-projects/micronaut-problem-json)
- [x] [Micronaut Serialization](https://github.com/micronaut-projects/micronaut-serialization)
- [x] [Micronaut Servlet](https://github.com/micronaut-projects/micronaut-servlet)
- [x] [Micronaut Spring](https://github.com/micronaut-projects/micronaut-spring)
- [x] [Micronaut AOT](https://github.com/micronaut-projects/micronaut-aot)
- [x] [Micronaut Gradle Plugin](https://github.com/micronaut-projects/micronaut-gradle-plugin)
- [x] [Micronaut Maven Plugin](https://github.com/micronaut-projects/micronaut-maven-plugin)
- [x] [Micronaut AWS](https://github.com/micronaut-projects/micronaut-aws)
- [x] [Micronaut Azure](https://github.com/micronaut-projects/micronaut-azure)
- [x] [Micronaut Discovery Client](https://github.com/micronaut-projects/micronaut-discovery-client)
- [x] [Micronaut GCP](https://github.com/micronaut-projects/micronaut-gcp)
- [x] [Micronaut Kubernets](https://github.com/micronaut-projects/micronaut-kubernetes)
- [x] [Micronaut Oracle Cloud](https://github.com/micronaut-projects/micronaut-oracle-cloud)
- [x] [Micronaut Tracing](https://github.com/micronaut-projects/micronaut-tracing)
- [x] [Micronaut Data](https://github.com/micronaut-projects/micronaut-data)
- [x] [Micronaut Cassandra](https://github.com/micronaut-projects/micronaut-cassandra)
- [x] [Micronaut MongoDB](https://github.com/micronaut-projects/micronaut-mongodb)
- [x] [Micronaut Neo4j](https://github.com/micronaut-projects/micronaut-neo4j)
- [x] [Micronaut R2DBC](https://github.com/micronaut-projects/micronaut-r2dbc)
- [x] [Micronaut Redis](https://github.com/micronaut-projects/micronaut-redis)
- [x] [Micronaut SQL](https://github.com/micronaut-projects/micronaut-sql)
- [x] [Micronaut Flyway](https://github.com/micronaut-projects/micronaut-flyway)
- [x] [Micronaut Liquibase](https://github.com/micronaut-projects/micronaut-liquibase)
- [x] [Micronaut Groovy](https://github.com/micronaut-projects/micronaut-groovy)
- [x] [Micronaut Kotlin](https://github.com/micronaut-projects/micronaut-kotlin)
- [x] [Micronuat JMS](https://github.com/micronaut-projects/micronaut-jms)
- [x] [Micronaut Kafka](https://github.com/micronaut-projects/micronaut-kafka)
- [x] [Micronaut MQTT](https://github.com/micronaut-projects/micronaut-mqtt)
- [x] [Micronaut NATS](https://github.com/micronaut-projects/micronaut-nats)
- [x] [Micronaut RabbitMQ](https://github.com/micronaut-projects/micronaut-rabbitmq)
- [x] [Micronaut ACME](https://github.com/micronaut-projects/micronaut-acme)
- [x] [Micronaut Cache](https://github.com/micronaut-projects/micronaut-cache)
- [x] [Micronaut Email](https://github.com/micronaut-projects/micronaut-email)
- [x] [Micronaut Hibernate Validator](https://github.com/micronaut-projects/micronaut-hibernate-validator)  
- [ ] [Micronaut ignite](https://github.com/micronaut-projects/micronaut-ignite)
- [x] [Micronaut Picocli](https://github.com/micronaut-projects/micronaut-picocli)
- [x] [Micronaut Security](https://github.com/micronaut-projects/micronaut-security)
- [x] [Micronaut Test](https://github.com/micronaut-projects/micronaut-test)
- [x] [Micronaut Reactor](https://github.com/micronaut-projects/micronaut-reactor)
- [x] [Micronaut RxJava2](https://github.com/micronaut-projects/micronaut-rxjava2)
- [x] [Micronaut RxJava3](https://github.com/micronaut-projects/micronaut-rxjava3)
- [x] [Micronaut Multi-tenancy](https://github.com/micronaut-projects/micronaut-multitenancy)
- [x] [Micronaut RSS](https://github.com/micronaut-projects/micronaut-rss)
- [x] [Micronaut TOML](https://github.com/micronaut-projects/micronaut-toml)
- [x] [Micronaut Views](https://github.com/micronaut-projects/micronaut-views)

**Comment by timyates** [comment]
Just ignite left AFAICT

And after looking at it, there's a question as to whether we just archive it.

I'll bring it up in the engineering meeting tomorrow, if no consensus is reached in gitter

**Comment by melix** [comment]
Micronaut Core will be much more complicated to migrate, I will do it.

**Comment by timyates** [comment]
@sdelamo can this now be closed?  Was a decision on Ignite made?

**Comment by sdelamo** [comment]
> @sdelamo can this now be closed? Was a decision on Ignite made?

Not yet. but I think we can close this issue.
