### ISSUE TITLE
Router does not refresh when changing controller path via configuration property

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#70]
How to reproduce: 

Clone branch: 

https://github.com/micronaut-projects/micronaut-core/tree/security-endpoints-configurable-path

Test fails: 

https://github.com/micronaut-projects/micronaut-core/blob/security-endpoints-configurable-path/security-jwt/src/test/groovy/io/micronaut/security/token/jwt/endpoints/OauthControllerPathConfigurableSpec.groovy

It fails because when you invoke the `/newtoken` endpoint and you place a breakpoint in 

https://github.com/micronaut-projects/micronaut-core/blob/security-endpoints-configurable-path/http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java#L221

The router does not entry for `/token` and thus the `ROUTE_MATCH` is not set.

**Comment by graemerocher** [comment]
I believe this is no longer issue, closing until verification
