### ISSUE TITLE
openAPI and Generics

### ISSUE THREAD

**Issue by hampsterx** [micronaut-projects/micronaut-core#700]
openAPI support is great but stuck on a couple of issues, note: I am new to kotlin and Java is not my strongpoint either so forgive me if there is an easy workaround for this issue.

Note: May be same issue / and or is related to #699 

This is probably more a heads up to openAPI 3 capability than an issue with micronaut. Just I spent some time researching it so might be of use to others and I know it will come up at some point. 
Feel free to close as "wont fix".

### Steps to Reproduce

```
mn create-app hello-world --lang kotlin --features swagger-kotlin
mn create-controller hello
```

```
data class Name(val name: String)

data class Hello<T>(val name: T)

@Controller("/hello")
class HelloController {

    @ApiResponse
    @Get("/")
    fun index(): Hello<*> {
        return Hello(name=Name("world"))

    }
}
```

### Expected Behaviour

Actually I am not sure. Ideal would be an list of possible T Types?

### Actual Behaviour

```
    Hello:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Object'
```

Name is generic Object schema instead of concrete Name schema.

### OpenApi Background Info

https://stackoverflow.com/questions/51499445/openapi-3-0-generic-data-types

> ... there is no way to define a generic type in OpenAPI3. The simplest way is using allOf and $ref at the same time

How can I represent java Generic type in swagger.yml
https://github.com/OAI/OpenAPI-Specification/issues/957 (open)

> How can I represent them in swagger so that I can generateEntityResponse<T>, when I refer to them, I just replace T with Cat or Dog.

..
> There's no support for templating of responses (or message wrappers).
..
> How it translates to code in a specific language is out of scope. You can use composition and inheritance, but not templating.

### Conclusion?

I guess this means we should have a concrete Class for each response?
Currently I have a standard response object that can contain error data and http status info etc as well as the result data so it's a bit unfortunate really to have to do this for every endpoint.

Any ideas/suggestions would be greatly appreciated~

**Comment by alexsavin** [comment]
I have the same issue in java. 

public class ResponseWrapper<T> {
  ...
}

@Get(value = "/somepath")
public ResponseWrapper<List<MyData>> somePath() {
   ...
}

I expect to see ResponseWrapper<List<MyData>>  in model section on swagger ui but it is absent.
In swagger yaml I have:

responses:
        default:
          description:some description.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWrapper'

but should be something like this:

responses:
        default:
          description: some description
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWrapper**<List<MyData>>**'

In springfox it works.
Micronaut guys, could you please review it and fix the issue with generics.
