### ISSUE TITLE
Handle empty file supplied for CompletedFileUpload 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#701]
If you have a form: 

```
<form method="post" action="/save" enctype="multipart/form-data">
    <label for="file">File:</label>
     <input type="file" name="file" id="file">
     <input type="submit" value="Upload"/>
</form>
```
and an action:

```
@Consumes(MediaType.MULTIPART_FORM_DATA)
@Post("/save")
public HttpResponse save(CompletedFileUpload file) {
   return HttpResponse.ok();
}
```

If the user submits the form without supplying a file, I believe the best way to detect that no file was supplied is to check wether `file.getFilename().equals("")`. 

I believe we should trigger an exception. Maybe a `ConstraintViolationException`. 

### Workaround

You can annotate the controller with `@Validated` and the method with `@Valid` and `@EmptyFileConstraints`.  

```
@Consumes(MediaType.MULTIPART_FORM_DATA)
@Post("/save")
public HttpResponse save(@Valid @EmptyFileConstraints CompletedFileUpload file) {
   return HttpResponse.ok();
}
```

and then a custom constraint:

```
package io.micronaut.validation.constraints;

import javax.validation.Constraint;
import javax.validation.Payload;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Constraint(validatedBy = { EmptyFileConstraintsValidator.class })
@Target( { ElementType.PARAMETER })
@Retention(RetentionPolicy.RUNTIME)
public @interface EmptyFileConstraints {

    String message() default "is empty";
    Class<?>[] groups() default { };
    Class<? extends Payload>[] payload() default { };
}
```

```
package io.micronaut.validation.constraints;

import io.micronaut.http.multipart.CompletedFileUpload;

import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;

public class EmptyFileConstraintsValidator implements ConstraintValidator<EmptyFileConstraints, CompletedFileUpload> {

    @Override
    public boolean isValid(CompletedFileUpload file, ConstraintValidatorContext context) {
        return file !=null && file.getFilename() != null && !file.getFilename().equals("");
    }
}
``` 

### Environment Information

- **Operating System**: Mac OS HighSierra
- **Micronaut Version:** 1.0.0.RC1
- **JDK Version:** 1.8

**Comment by jameskleeh** [comment]
@sdelamo It should throw an unsatisifed exception

**Comment by sdelamo** [comment]
@jameskleeh I've uploaded a geb test which reproduces that no failure is triggered. 

You can run it with: 

`./gradlew -Dgeb.env=chrome test-suite:test --tests io.micronaut.upload.browser.UploadBrowserSpec`

**Comment by jameskleeh** [comment]
The behavior is different between the unit test and geb test because Netty creates the request differently than the browser. Netty skips adding the filename attribute to the part if its empty and the browser adds it anyway.

On the server side Netty considers a part without a filename to be an attribute, and thus the conversion to CompletedFileUpload fails because the base type is wrong.

Overall I think the current behavior is correct and there aren't any changes necessary. The only thing I would change is how the request is encoded, however the class from Netty isn't easily extensible to allow this behavior.
