### ISSUE TITLE
Incorrect hyphenation when service request app status from Eureka

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-core#702]
When a service gets the list of all services from Eureka with GET /eureka/apps the response is ok, but then the service tries to get the status of each service the service name is incorrectly hyphenated and the response is 404.

The service issues a GET /eureka/apps to get a list of all registered apps.
The response includes correct service names (gr8crm-tag-service):
```json
{
    "name": "GR8CRM-TAG-SERVICE",
    "instance": [{
        "instanceId": "gr8crm-tag-service:8085",
        "hostName": "GR8CRM-TAG-SERVICE",
        "app": "GR8CRM-TAG-SERVICE",
        "ipAddr": "192.168.16.16",
        "status": "UP",
        "overriddenStatus": "UNKNOWN",
        "port": {
            "$": 8085,
            "@enabled": "true"
        },
        "securePort": {
            "$": 0,
            "@enabled": "false"
        },
        "countryId": 1,
        "dataCenterInfo": {
            "@class": "com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo",
            "name": "MyOwn"
        },
        "leaseInfo": {
            "renewalIntervalInSecs": 30,
            "durationInSecs": 90,
            "registrationTimestamp": 1538993723175,
            "lastRenewalTimestamp": 1538994892288,
            "evictionTimestamp": 0,
            "serviceUpTimestamp": 1538993722666
        },
        "metadata": {
            "@class": "java.util.Collections$EmptyMap"
        },
        "homePageUrl": "http://gr8crm-tag-service:8085",
        "statusPageUrl": "http://gr8crm-tag-service:8085/health",
        "healthCheckUrl": "http://gr8crm-tag-service:8085/health",
        "secureHealthCheckUrl": "https://gr8crm-tag-service/health",
        "vipAddress": "GR8CRM-TAG-SERVICE",
        "secureVipAddress": "GR8CRM-TAG-SERVICE",
        "isCoordinatingDiscoveryServer": "false",
        "lastUpdatedTimestamp": "1538993723175",
        "lastDirtyTimestamp": "1538993722665",
        "actionType": "ADDED"
    }]
}
```

Bu then the service issues a GET /eureka/apps/gr8-crm-tag-service and the response is 404

```
gr8crm-notification-service_1  | 10:33:48.262 [nioEventLoopGroup-1-9] DEBUG i.m.http.client.DefaultHttpClient - Sending HTTP Request: GET /eureka/apps/gr8-crm-tag-service
gr8crm-notification-service_1  | 10:33:48.262 [nioEventLoopGroup-1-9] DEBUG i.m.http.client.DefaultHttpClient - Chosen Server: gr8crm-registry-service(8761)
gr8crm-notification-service_1  | 10:33:48.262 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - Accept: application/json
gr8crm-notification-service_1  | 10:33:48.262 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - host: gr8crm-registry-service
gr8crm-notification-service_1  | 10:33:48.262 [nioEventLoopGroup-1-9] TRACE i.m.http.client.DefaultHttpClient - connection: close
```

### Steps to Reproduce

1. Start Eureka and two services with digits in their names (gr8crm-tag-service & gr8crm-notification-service)
2. Make sure you DEBUG log io.micronaut.http.client
3. See how incorrect url is used to contact eureka

### Expected Behaviour

Sending HTTP Request: GET /eureka/apps/gr8crm-tag-service

### Actual Behaviour

 Sending HTTP Request: GET /eureka/apps/gr8-crm-tag-service
Response is 404

### Environment Information

- **Operating System**: MacOS 10.14
- **Micronaut Version:** BUILD-SNAPSHOT 2018-10-08 12:30 MET
- **JDK Version:** 1.8.0_162-b12

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by goeh** [comment]
One thing that I find strange is that because the calling service gets a 404 response from Eureka the calling service reports DOWN to Eureka.
Example: gr8crm-notification-service issues an invalid URL to Eureka `GET /eureka/apps/gr8-crm-tag-service`. After that the notification service reports itself DOWN. The notification service is not even dependent/using the tag service so it's kind of sad that it goes DOWN.

**Comment by graemerocher** [comment]
I have added a test for this (see commit above) and I cannot reproduce. Please provide an example.

**Comment by goeh** [comment]
The problem is visible in https://github.com/goeh/micronaut-health-issue
```
./gradlew docker
docker-compose up --build
```
After 1-2 minutes you can see:
```
hello_1           | 14:33:36.373 [pool-1-thread-3] DEBUG i.m.m.h.monitor.HealthMonitorTask - Starting health monitor check
hello_1           | 14:33:36.393 [nioEventLoopGroup-1-7] DEBUG i.m.http.client.DefaultHttpClient - Sending HTTP Request: GET /eureka/apps/gr8-crm-service
hello_1           | 14:33:36.393 [nioEventLoopGroup-1-7] DEBUG i.m.http.client.DefaultHttpClient - Chosen Server: eureka(8761)
```
The **hello** service requests status for service **gr8-crm-service** from Eureka. But the correct service name is **gr8crm-service**.

**Comment by goeh** [comment]
I think I found the problem!

In my `application.yml` I have:
```yaml
micronaut:
  application:
    name: gr8crm-notification-service
```
The setter in ApplicationConfiguration hyphenates the value so the name gets converted to **gr8-crm-notification-service**.

https://github.com/micronaut-projects/micronaut-core/blob/b2493d1175df73c3427522886a8d6255f46dee5c/runtime/src/main/java/io/micronaut/runtime/ApplicationConfiguration.java#L89

**Comment by goeh** [comment]
Maybe I should remove the '8' in all my service names!  :)

**Comment by goeh** [comment]
My wrong! That was not the problem. The recent fix handles that application name correct.

**Comment by goeh** [comment]
Maybe the problem is that Eureka returns the application name  / service id in uppercase. And the hyphenate method in NameUtils matches lowercase only.

**Comment by graemerocher** [comment]
That could be it

**Comment by goeh** [comment]
@graemerocher When you look at this issue you should know that there is another problem that I have not yet reported (because I need more time to investigate). And that is I have to have an **alias** with the hostname in uppercase in my docker-compose.yml. Otherwise I get "no such host: GR8CRM-NOTIFICATION-SERVICE" when Spring Cloud Gateway try to route requests to the service. I guess this uppercase thing is a known issue with Eureka because in all my Spring Cloud Projects I have preferIpAddress = true which forces hostname field in Eureka to be the IP-address instead of the hostname.
This is what I currently have in my docker-compose.yml
```yml
services:
  gr8crm-notification-service:
    image: gr8crm-notification-service:1.0.0-SNAPSHOT
    environment:
      - EUREKA_HOST=gr8crm-registry-service
      - MICRONAUT_SERVER_HOST=gr8crm-notification-service
    depends_on:
      - mongo
      - kafka
      - gr8crm-registry-service
    networks:
      gr8crm:
        aliases:
          - GR8CRM-NOTIFICATION-SERVICE
```

**Comment by goeh** [comment]
I temporary removed the '8' from all of my (10) service names and now my cluster finally looks functional (no exceptions, all services UP, etc). I have one more service to migrate before I can verify the whole system in action.

**Comment by graemerocher** [comment]
@goeh Please try master when you can. Thx

**Comment by goeh** [comment]
Thanks! Now it works.

Getting status for gr8crm-xxxxxx-service now uses correct service name.

But there is still one other problem to solve before I can be completely happy. I'll report that in a new issue.
