### ISSUE TITLE
could not resolve SQL bom

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7068]
### Issue description

[GraalVM pipeline started failing](https://storage.googleapis.com/gitlab-gprd-artifacts/48/05/4805636ff3aae40ba81ce4a81a2b4b5e6ea10a2b300adc4cf9b04040c3685447/2022_03_15/2203206354/2399788997/job.log?response-content-type=text%2Fplain%3B%20charset%3Dutf-8&response-content-disposition=inline&GoogleAccessId=gitlab-object-storage-prd@gitlab-production.iam.gserviceaccount.com&Signature=tlx5prrmnApmX99owbNW6JQL4xXKiZZpF99zu45jB49sUBG8lDvIPyRcFdrt%0Av8F7%2BWUPD6FkkNHoMG%2F%2FanWy6j429loml3UrVP7Y8bDLEHU6SqDIgy8cHam0%0AbccymzhyxHnNmjGVntuurcYdvUiky%2Fky%2BL4TOccc3vQyUcdY2kGyQC%2Fqy6JC%0Azqb4KT54bNIRJML34hcxB7WeUSXL3Cbjch2BI4gdWxUjPD7DTDMeHIWR2F3%2F%0A%2FSd0bxUXemOjrZzmbfkwKXL4ncQcmWhvViPj16M9SLKMUDXnmCDkv1JttyCz%0AVtM33B8rL6TIRMQYlIPipFtc4JIQm2CtXgzw%2FebT6A%3D%3D&Expires=1647333659): 

```

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find io.micronaut:micronaut-validation:.
     Required by:
         project :
   > Could not find io.micronaut:micronaut-runtime:.
     Required by:
         project :
   > Could not find io.micronaut:micronaut-http-client:.
     Required by:
         project :
   > Could not find io.micronaut.mqtt:micronaut-mqttv5:.
     Required by:
         project :
   > Could not find io.micronaut:micronaut-inject:.
     Required by:
         project :
   > Could not find io.micronaut:micronaut-http-server-netty:.
     Required by:
         project :
   > Could not resolve io.micronaut:micronaut-bom:3.4.0-SNAPSHOT.
     Required by:
         project :
      > Could not resolve io.micronaut:micronaut-bom:3.4.0-SNAPSHOT.
         > Could not parse POM https://s01.oss.sonatype.org/content/repositories/snapshots/io/micronaut/micronaut-bom/3.4.0-SNAPSHOT/micronaut-bom-3.4.0-20220314.142521-51.pom
            > Could not resolve io.micronaut.sql:micronaut-sql-bom:4.2.0.
               > Could not resolve io.micronaut.sql:micronaut-sql-bom:4.2.0.
                  > Failed to add into filestore '/root/.gradle/caches/modules-2/metadata-2.97/descriptors' at 'io.micronaut.sql/micronaut-sql-bom/4.2.0/a8be1fe3b3911d3d3425fe720cf42835/descriptor.bin' 
                     > Cannot invoke "org.gradle.api.artifacts.VersionConstraint.getRequiredVersion()" because "cst" is null
```

**Comment by sdelamo** [comment]
this PR looks like the first culprit candidate https://github.com/micronaut-projects/micronaut-sql/pull/535

**Comment by melix** [comment]
mmm, this is a fairly unusual error, since it makes Gradle itself fail :/

**Comment by melix** [comment]
Early investigations seem to indicate a Gradle bug in importing BOMs...

**Comment by melix** [comment]
I would suggest we revert the PR above while I investigate the issue, since I suspect it will require a bugfix in Gradle.

**Comment by timyates** [comment]
@melix have you got this one?  Shout if I can help

**Comment by melix** [comment]
@timyates I'm trying to figure out what is causing this, it's not easy to reproduce outside of this particular BOM. Feel free to revert the commit in the meantime.

**Comment by timyates** [comment]
@melix @sdelamo Reverted in https://github.com/micronaut-projects/micronaut-sql/pull/573

**Comment by melix** [comment]
Thanks @timyates . I just managed to confirm it's a Gradle bug.

**Comment by sdelamo** [comment]
> Thanks @timyates . I just managed to confirm it's a Gradle bug.

Thanks for looking into this @melix
