### ISSUE TITLE
Create-app CLI command fails on providing default package name

### ISSUE THREAD

**Issue by andyislegend** [micronaut-projects/micronaut-core#707]
### Steps to Reproduce

> mn create-app example.my-app

### Expected Behaviour

According to [docs](https://docs.micronaut.io/latest/guide/index.html#createProject)

> You can supply your own default package when creating the application by prefixing the application name with the package:
> $ mn create-app example.my-demo-app
> 
> Will result in the following micronaut-cli-yml.
> `profile: service
> defaultPackage: example
> testFramework: junit
> sourceLanguage: java`

### Actual Behaviour

`| Error Application name should be all lower case and separated by underscores. For example: hello-world`

<img width="1273" alt="mn_fails" src="https://user-images.githubusercontent.com/8747026/46624518-aebd0e00-cb39-11e8-8b1d-017f3e06151d.png">

### Environment Information

- **Operating System**: mac os x version 10.14
- **Micronaut Version:** 1.0.0.RC2
- **JDK Version:** 11.0.0-open

**Comment by weiqigao** [comment]
I'm seeing the same problem in RC2.  I'm glad it will be fixed in RC3.  However I think the error message itself needs some tweaking.  The statement says "underscore", the example shows "dash".
