### ISSUE TITLE
Version Catalogues in every module

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7070]
### Issue description

Some modules are using [Gradle Version Catalogues](https://docs.gradle.org/current/userguide/platforms.html#sec:version-catalog-plugin).

- [x] [Micronaut ACME](https://github.com/micronaut-projects/micronaut-acme)
- [x] [Micronaut AOT](https://github.com/micronaut-projects/micronaut-aot)
- [x] [Micronaut AWS](https://github.com/micronaut-projects/micronaut-aws)
- [ ] [Micronaut Azure](https://github.com/micronaut-projects/micronaut-azure)
- [x] [Micronaut Cache](https://github.com/micronaut-projects/micronaut-cache)
- [ ] [Micronaut Cassandra](https://github.com/micronaut-projects/micronaut-cassandra)
- [x] [Micronaut Data](https://github.com/micronaut-projects/micronaut-data)
- [x] [Micronaut Discovery Client](https://github.com/micronaut-projects/micronaut-discovery-client)
- [ ] [Micronaut Elastic Search](https://github.com/micronaut-projects/micronaut-elasticsearch)
- [x] [Micronaut Email](https://github.com/micronaut-projects/micronaut-email)
- [x] [Micronaut Flyway](https://github.com/micronaut-projects/micronaut-flyway)
- [ ] [Micronaut GCP](https://github.com/micronaut-projects/micronaut-gcp)
- [x] [Micronaut Gradle Plugin](https://github.com/micronaut-projects/micronaut-gradle-plugin)
- [ ] [Micronaut GraphQL](https://github.com/micronaut-projects/micronaut-graphql)
- [x] [Micronaut Groovy](https://github.com/micronaut-projects/micronaut-groovy)
- [x] [Micronaut GRPC](https://github.com/micronaut-projects/micronaut-grpc)
- [x] [Micronaut Hibernate Validator](https://github.com/micronaut-projects/micronaut-hibernate-validator)  
- [ ] [Micronaut Ignite](https://github.com/micronaut-projects/micronaut-ignite)
- [x] [Micronaut Jackson XML](https://github.com/micronaut-projects/micronaut-jackson-xml)
- [x] [Micronaut JAX-RS](https://github.com/micronaut-projects/micronaut-jaxrs)
- [x] [Micronaut JMS](https://github.com/micronaut-projects/micronaut-jms)
- [x] [Micronaut JMX](https://github.com/micronaut-projects/micronaut-jmx)
- [x] [Micronaut Kafka](https://github.com/micronaut-projects/micronaut-kafka)
- [ ] [Micronaut Kotlin](https://github.com/micronaut-projects/micronaut-kotlin)
- [ ] [Micronaut Kubernetes](https://github.com/micronaut-projects/micronaut-kubernetes)
- [x] [Micronaut Liquibase](https://github.com/micronaut-projects/micronaut-liquibase)
- [ ] [Micronaut Maven Plugin](https://github.com/micronaut-projects/micronaut-maven-plugin)
- [x] [Micronaut Micrometer](https://github.com/micronaut-projects/micronaut-micrometer)
- [x] [Micronaut MongoDB](https://github.com/micronaut-projects/micronaut-mongodb)
- [x] [Micronaut MQTT](https://github.com/micronaut-projects/micronaut-mqtt)
- [ ] [Micronaut Multi-tenancy](https://github.com/micronaut-projects/micronaut-multitenancy)
- [x] [Micronaut NATS](https://github.com/micronaut-projects/micronaut-nats)
- [ ] [Micronaut Neo4j](https://github.com/micronaut-projects/micronaut-neo4j)
- [ ] [Micronaut OpenAPI](https://github.com/micronaut-projects/micronaut-openapi)
- [x] [Micronaut Oracle Cloud](https://github.com/micronaut-projects/micronaut-oracle-cloud)
- [x] [Micronaut Picocli](https://github.com/micronaut-projects/micronaut-picocli)
- [x] [Micronaut Problem-JSON](https://github.com/micronaut-projects/micronaut-problem-json)
- [x] [Micronaut R2DBC](https://github.com/micronaut-projects/micronaut-r2dbc)
- [x] [Micronaut RabbitMQ](https://github.com/micronaut-projects/micronaut-rabbitmq)
- [ ] [Micronaut Reactor](https://github.com/micronaut-projects/micronaut-reactor)
- [x] [Micronaut Redis](https://github.com/micronaut-projects/micronaut-redis)
- [ ] [Micronaut RSS](https://github.com/micronaut-projects/micronaut-rss)
- [ ] [Micronaut RxJava2](https://github.com/micronaut-projects/micronaut-rxjava2)
- [x] [Micronaut RxJava3](https://github.com/micronaut-projects/micronaut-rxjava3)
- [ ] [Micronaut Security](https://github.com/micronaut-projects/micronaut-security)
- [x] [Micronaut Serialization](https://github.com/micronaut-projects/micronaut-serialization)
- [x] [Micronaut Servlet](https://github.com/micronaut-projects/micronaut-servlet)
- [x] [Micronaut Spring](https://github.com/micronaut-projects/micronaut-spring)
- [x] [Micronaut SQL](https://github.com/micronaut-projects/micronaut-sql)
- [x] [Micronaut Test](https://github.com/micronaut-projects/micronaut-test)
- [x] [Micronaut TOML](https://github.com/micronaut-projects/micronaut-toml)
- [x] [Micronaut Tracing](https://github.com/micronaut-projects/micronaut-tracing)
- [ ] [Micronaut Views](https://github.com/micronaut-projects/micronaut-views)

**Comment by sdelamo** [comment]
I am worried that using version catalogues leaves us without automatic dependency updates. I think Dependabot does not work with them.

**Comment by sdelamo** [comment]
@micronaut-projects/core-developers thoughts?

**Comment by dstepanov** [comment]
We might want to consider to switch to the alternative to dependabot @melix had suggested

**Comment by alvarosanchez** [comment]
I made the same suggestion way before, but it didn't seem to get much attention: https://github.com/micronaut-projects/micronaut-build/issues/97

**Comment by donbeave** [comment]
Do you need any help here? I can say renovatebot works much better than dependabot and supports more formats, including Gradle Kotlin DSL and Gradle Version Catalogs. I'm using it in some of my projects and until now didn't encounter any problems.

If you are open to this change I can help with PRs.

P.S. It looks like these projects already migrated to Version Catalog:

1) https://github.com/micronaut-projects/micronaut-flyway/blob/master/gradle/libs.versions.toml
2) https://github.com/micronaut-projects/micronaut-groovy/blob/master/gradle/libs.versions.toml
3) https://github.com/micronaut-projects/micronaut-mongodb/blob/master/gradle/libs.versions.toml
4) https://github.com/micronaut-projects/micronaut-nats/blob/master/gradle/libs.versions.toml
5) https://github.com/micronaut-projects/micronaut-oracle-cloud/blob/master/gradle/libs.versions.toml
6) https://github.com/micronaut-projects/micronaut-spring/blob/master/gradle/libs.versions.toml

**Comment by graemerocher** [comment]
@donbeave contributions welcome!

**Comment by donbeave** [comment]
I will create a migration PR for each project and will also post the link to these PRs here in the comments section.

- [x] [Micronaut ACME](https://github.com/micronaut-projects/micronaut-acme) - https://github.com/micronaut-projects/micronaut-acme/pull/228
- [x] [Micronaut GraphQL](https://github.com/micronaut-projects/micronaut-graphql) - https://github.com/micronaut-projects/micronaut-graphql/pull/247

**Comment by donbeave** [comment]
- [x] [Micronaut Azure](https://github.com/micronaut-projects/micronaut-azure) - https://github.com/micronaut-projects/micronaut-azure/pull/327
- [x] [Micronaut Cache](https://github.com/micronaut-projects/micronaut-cache) - https://github.com/micronaut-projects/micronaut-cache/pull/457
- [x] [Micronaut Cassandra](https://github.com/micronaut-projects/micronaut-cassandra) - https://github.com/micronaut-projects/micronaut-cassandra/pull/231

**Comment by dstepanov** [comment]
@donbeave Thanks! BTW you aren’t supposed to modify anything in .github, that should be updated by the micronaut build PRs

**Comment by donbeave** [comment]
@dstepanov ok, I’ll restore these changes, but looks like many repositories aren’t synced with project template in terms of common files. I saw there are some PRs with updating common files stayed unmerged. After migrate to Gradle Version Catalogs PRs I think it’s important to merge these PRs with updating common files, otherwise the dependency updates flow will not work.

**Comment by alvarosanchez** [comment]
@donbeave agreed that there are some unmerged sync PRs, but the only reason is because we don't have enough bandwidth to quickly handle all the incoming PRs.

The majority of the projects should be sync'ed from the template. There are some exceptions, like micronaut-starter (which has a quite unique build) or the Maven Plugin (which uses Maven). If you find a notable miss, please let us know.

In some other cases, like micronaut-kubernetes, the sync PRs can't be automatically merged because they have customisations (e.g. a Kubernetes version matrix) that would otherwise be lost. Merging those PRs requires manually editing them.

One thing that was added by GitHub and that we are not leveraging yet is [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows). If you are willing to help in this area, kindly let me know.

In any case, thank you very much for your contributions so far! They are highly appreciated! ❤️

**Comment by donbeave** [comment]
> If you are willing to help in this area, kindly let me know.

I'm happy to help. Let me finish migration to Gradle Version Catalog. Probably I can finish migration for the rest of the projects today.

**Comment by donbeave** [comment]
- [x] Micronaut chatbots - https://github.com/micronaut-projects/micronaut-chatbots/pull/15
- [x] Micronaut Coherence - https://github.com/micronaut-projects/micronaut-coherence/pull/179
- [x] [Micronaut Discovery Client](https://github.com/micronaut-projects/micronaut-discovery-client) - https://github.com/micronaut-projects/micronaut-discovery-client/pull/355
- [x] [Micronaut Elastic Search](https://github.com/micronaut-projects/micronaut-elasticsearch) - https://github.com/micronaut-projects/micronaut-elasticsearch/pull/314
- [x] [Micronaut Email](https://github.com/micronaut-projects/micronaut-email) - https://github.com/micronaut-projects/micronaut-email/pull/73

**Comment by donbeave** [comment]
- [x] [Micronaut GCP](https://github.com/micronaut-projects/micronaut-gcp) - https://github.com/micronaut-projects/micronaut-gcp/pull/630
- [x] [Micronaut Jackson XML](https://github.com/micronaut-projects/micronaut-jackson-xml) - https://github.com/micronaut-projects/micronaut-jackson-xml/pull/195
- [x] [Micronaut JAX-RS](https://github.com/micronaut-projects/micronaut-jaxrs) - https://github.com/micronaut-projects/micronaut-jaxrs/pull/233
- [x] [Micronaut Kotlin](https://github.com/micronaut-projects/micronaut-kotlin) - https://github.com/micronaut-projects/micronaut-kotlin/pull/408
- [x] [Micronaut Kubernetes](https://github.com/micronaut-projects/micronaut-kubernetes) - https://github.com/micronaut-projects/micronaut-kubernetes/pull/478
- [x] [Micronaut Micrometer](https://github.com/micronaut-projects/micronaut-micrometer) - https://github.com/micronaut-projects/micronaut-micrometer/pull/389
- [x] [Micronaut MQTT](https://github.com/micronaut-projects/micronaut-mqtt) - https://github.com/micronaut-projects/micronaut-mqtt/pull/168
- [x] [Micronaut Multi-tenancy](https://github.com/micronaut-projects/micronaut-multitenancy) - https://github.com/micronaut-projects/micronaut-multitenancy/pull/124

**Comment by donbeave** [comment]
- [x] [Micronaut Neo4j](https://github.com/micronaut-projects/micronaut-neo4j) - https://github.com/micronaut-projects/micronaut-neo4j/pull/237
- [x] [Micronaut Picocli](https://github.com/micronaut-projects/micronaut-picocli) - https://github.com/micronaut-projects/micronaut-picocli/pull/241
- [x] [Micronaut R2DBC](https://github.com/micronaut-projects/micronaut-r2dbc) - https://github.com/micronaut-projects/micronaut-r2dbc/pull/233
- [x] [Micronaut Reactor](https://github.com/micronaut-projects/micronaut-reactor) - https://github.com/micronaut-projects/micronaut-reactor/pull/195
- [x] [Micronaut RxJava2](https://github.com/micronaut-projects/micronaut-rxjava2) - https://github.com/micronaut-projects/micronaut-rxjava2/pull/82
- [x] [Micronaut RxJava3](https://github.com/micronaut-projects/micronaut-rxjava3) - https://github.com/micronaut-projects/micronaut-rxjava3/pull/201

**Comment by donbeave** [comment]
- [x] [Micronaut OpenAPI](https://github.com/micronaut-projects/micronaut-openapi) - https://github.com/micronaut-projects/micronaut-openapi/pull/705
- [x] [Micronaut RSS](https://github.com/micronaut-projects/micronaut-rss) - https://github.com/micronaut-projects/micronaut-rss/pull/203
- [x] [Micronaut Security](https://github.com/micronaut-projects/micronaut-security) - https://github.com/micronaut-projects/micronaut-security/pull/995
- [x] [Micronaut Serialization](https://github.com/micronaut-projects/micronaut-serialization) - https://github.com/micronaut-projects/micronaut-serialization/pull/200
- [x] [Micronaut SQL](https://github.com/micronaut-projects/micronaut-sql) - https://github.com/micronaut-projects/micronaut-sql/pull/621
- [x] [Micronaut Test](https://github.com/micronaut-projects/micronaut-test) - https://github.com/micronaut-projects/micronaut-test/pull/553
- [x] [Micronaut Views](https://github.com/micronaut-projects/micronaut-views) - https://github.com/micronaut-projects/micronaut-views/pull/410

**Comment by altro3** [comment]
@sdelamo I think, it's already done
