### ISSUE TITLE
GraalVM Jooq Postgres failed org.jooq.SQLDialect unintentionally initialized at build time

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7084]
### Issue description

Steps to reproduce:

- Clone [`micronaut-jooq-graal`](https://github.com/micronaut-graal-tests/micronaut-jooq-graal)
- checkout branch `3.4.x_postgres`
- `./build-jooq-postgres.sh`

https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2208553736
```
Error: Classes that should be initialized at run time got initialized during image building:
 org.jooq.SQLDialect was unintentionally initialized at build time. To see why org.jooq.SQLDialect got initialized use --trace-class-initialization=org.jooq.SQLDialect
```

**Comment by graemerocher** [comment]
I can't reproduce this with the current stable 22.0.0 release of GraalVM

**Comment by sdelamo** [comment]
This happens with SNAPSHOT of GraalVM.
