### ISSUE TITLE
Declarative HttpClient blocking on http registry getClientKey

### ISSUE THREAD

**Issue by tom-rauk** [micronaut-projects/micronaut-core#7087]
### Expected Behavior

Expect no blocking on `beanContext.getBean(JsonMapper.class)` in `io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry#getClientKey` while using declarative http client.

### Actual Behaviour

Lot of blocking on `beanContext.getBean(JsonMapper.class)` in `io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry#getClientKey` while using declarative http client for lots of concurrent calls to various clients.

### Steps To Reproduce

Hard to reproduce without lots of concurrent calls to many declarative http clients.

### Environment Information

Alpine Linux v3.14
openjdk 11.0.11 2021-04-20

### Version

3.3.4

**Comment by graemerocher** [comment]
probably happens only the first intiialization of the `JsonMapper` as it reads the config for Jackson. Doubt this is a problem of generally blocking

**Comment by yawkat** [comment]
@graemerocher i think this refers to lock blocking, from the getBean call

should be straight-forward to fix, just cache the JsonMapper in a field in the registry

**Comment by graemerocher** [comment]
Gotcha, makes sense
