### ISSUE TITLE
Docs are published to micronaut-core/gh-pages they should be published to micronaut-docs/gh-pages

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7126]
### Issue description

We publish Micronaut Core docs to [`gh-pages` branch of `micronaut-docs`](https://github.com/micronaut-projects/micronaut-docs/tree/gh-pages). 

[3.4.0 Release](https://github.com/micronaut-projects/micronaut-core/actions/runs/2020360635) published them to [`gh-pages` branch of `micronaut-core`](https://github.com/micronaut-projects/micronaut-core/commit/5b3464c0a2e73b0cab6a1e37ce29540e9e2e1a2f). 

To fix 3.4.0 docs, I did [commit](https://github.com/micronaut-projects/micronaut-docs/commit/7220656c21df2f9ea0383e4afb937318f126413e) to `micronaut-docs` `gh-pages` to publish the docs manually. 

However, We need to fix the release process.

**Comment by melix** [comment]
Is this something new (a newly added regression)?

**Comment by alvarosanchez** [comment]
An overlook while merging a sync PR: https://github.com/micronaut-projects/micronaut-core/commit/5f79a991fc3c7ecfd2ac1ea813e58363b6e8da44#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L63

Having that line different in core is a pain, so instead, I will put the condition in the template
