### ISSUE TITLE
BUG 3.4.0:  No bean of type io.micronaut.context.event.ApplicationEventPublisher exists

### ISSUE THREAD

**Issue by codeconsole** [micronaut-projects/micronaut-core#7144]
### This is a bug new to v3.4.0 - Perhaps test building a basic empty app before future releases?
v3.3.4 works fine

### Expected Behavior

Freshly created basic app can be run via `java -jar./build/libs/test-0.1-all.jar`

`./gradlew run` works:
20:06:55.564 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 285ms. Server Running: http://localhost:8080

`java -jar ./build/libs/test-0.1-all.jar` does *not* work

### Actual Behaviour

```
% ./gradlew assemble
% java -jar ./build/libs/test-0.1-all.jar
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.4.0)

20:02:41.144 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2795)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1654)
	at io.micronaut.context.BeanLocator.getBean(BeanLocator.java:94)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1733)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:344)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:183)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:72)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:320)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:306)
	at test.Application.main(Application.java:8)

```

### Steps To Reproduce

```
% sdk use java 11.0.14-zulu  
% sdk use micronaut 3.4.0
% mn create-app test
% cd test
% ./gradlew assemble
% java -jar ./build/libs/test-0.1-all.jar
```

### Environment Information

macOS Monterey 12.3
MacBook Pro (14-Inch, 2021)
Chip Apple M1 Pro
Memory 16 GB

### Version

3.4.0

**Comment by graemerocher** [comment]
This is https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/406

**Comment by sdelamo** [comment]
Workaround: 

```

shadowJar {
    mergeServiceFiles()
}
```

**Comment by codeconsole** [comment]
Thanks for the fast response and providing a workaround that I can confirm works.

**Comment by NirajKuma4r** [comment]
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [com.azure.cosmos.CosmosAsyncContainer] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).

**Comment by NirajKuma4r** [comment]
please help

**Comment by sivaprasadreddy** [comment]
I am using Micronaut 4.7.0 with Maven and I am getting the same Exception only on GitHub Actions, but running fine locally.

```
[test-resources-service] 11:45:41.353 [pool-1-thread-1] INFO  tc.testcontainers/ryuk:0.9.0 - Container testcontainers/ryuk:0.9.0 started in PT0.55039206S
[test-resources-service] 11:45:41.358 [pool-1-thread-1] INFO  o.t.utility.RyukResourceReaper - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
[test-resources-service] 11:45:41.358 [pool-1-thread-1] INFO  o.testcontainers.DockerClientFactory - Checking the system...
[test-resources-service] 11:45:41.358 [pool-1-thread-1] INFO  o.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
Error: Exception in thread "main" io.micronaut.runtime.exceptions.ApplicationStartupException: Error starting Micronaut server: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. 
	at io.micronaut.runtime.Micronaut.handleStartupException(Micronaut.java:353)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:1[74](https://github.com/sivaprasadreddy/joyful-devex-using-testcontainers/actions/runs/11878556800/job/33099369073#step:4:75))
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:334)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:320)
	at io.micronaut.testresources.server.TestResourcesService.main(TestResourcesService.java:43)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. 
	at io.micronaut.context.DefaultBeanContext.newNoSuchBeanException(DefaultBeanContext.java:2798)
	at io.micronaut.context.DefaultApplicationContext.newNoSuchBeanException(DefaultApplicationContext.java:329)
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2761)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1745)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:842)
	at io.micronaut.context.BeanLocator.getBean(BeanLocator.java:97)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1831)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:360)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:216)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:[75](https://github.com/sivaprasadreddy/joyful-devex-using-testcontainers/actions/runs/11878556800/job/33099369073#step:4:76))
	... 3 more
```

**Comment by dirkhas** [comment]
I'm seeing this error in github actions too, after upgrading to 4.7.1. Simply using 4.6.3 instead makes the error go away.

**Comment by graemerocher** [comment]
@dirkhas @sivaprasadreddy do you have reproducers?

**Comment by melix** [comment]
seems to be related to https://github.com/micronaut-projects/micronaut-test-resources/issues/785

**Comment by dirkhas** [comment]
> @dirkhas @sivaprasadreddy do you have reproducers?

@graemerocher  I'm afraid not. I'm seeing the problem in a work project I can't share.

> seems to be related to [micronaut-projects/micronaut-test-resources#785](https://github.com/micronaut-projects/micronaut-test-resources/issues/785)

@melix Super interesting, my project uses test resources too 👀

**Comment by sivaprasadreddy** [comment]
@graemerocher 
Repository: https://github.com/sivaprasadreddy/joyful-devex-using-testcontainers
Here is the pipeline execution the failed: https://github.com/sivaprasadreddy/joyful-devex-using-testcontainers/actions/runs/11992348693/job/33432062373

**Comment by sivaprasadreddy** [comment]
@graemerocher 
Now it got more interesting. The PR to update to 4.7.1 failed: https://github.com/sivaprasadreddy/joyful-devex-using-testcontainers/actions/runs/11992348693/job/33432062373

Somehow after upgrading to version 4.7.1, the build succeed in GitHub Actions pipeline https://github.com/sivaprasadreddy/joyful-devex-using-testcontainers/actions/runs/12213382342/job/34072929948

**Comment by MaximDzhezhelo** [comment]
I am getting the **No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists.** Exception only on GitHub Actions with this configuration
```
plugins {
    id "io.micronaut.minimal.library" version "4.4.4"
    id "io.micronaut.test-resources" version "4.4.4"
    id "com.github.johnrengelman.shadow" version "8.1.1"
    id "nu.studer.jooq" version "9.0"
}
with micronautVersion=4.7.3
```

Works properly locally and on GitHub with micronautVersion=4.6.3

**Comment by marcosflobo** [comment]
Same issue than @sivaprasadreddy but in my case I have micronaut version `4.7.8` and io.micronaut.application version `4.0.4`

The full log

```log
{
  "sequenceNumber": 0,
  "timestamp": 1736414952815,
  "nanoseconds": 815422367,
  "level": "ERROR",
  "threadName": "main",
  "loggerName": "io.micronaut.runtime.Micronaut",
  "context": {
    "name": "default",
    "birthdate": 1736414951620,
    "properties": {}
  },
  "mdc": {},
  "formattedMessage": "Error starting Micronaut server: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. ",
  "throwable": {
    "className": "io.micronaut.context.exceptions.NoSuchBeanException",
    "message": "No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. ",
    "stepArray": [
      {
        "className": "io.micronaut.context.DefaultBeanContext",
        "methodName": "newNoSuchBeanException",
        "fileName": "DefaultBeanContext.java",
        "lineNumber": 2798
      },
      {
        "className": "io.micronaut.context.DefaultApplicationContext",
        "methodName": "newNoSuchBeanException",
        "fileName": "DefaultApplicationContext.java",
        "lineNumber": 329
      },
      {
        "className": "io.micronaut.context.DefaultBeanContext",
        "methodName": "resolveBeanRegistration",
        "fileName": "DefaultBeanContext.java",
        "lineNumber": 2761
      },
      {
        "className": "io.micronaut.context.DefaultBeanContext",
        "methodName": "getBean",
        "fileName": "DefaultBeanContext.java",
        "lineNumber": 1745
      },
      {
        "className": "io.micronaut.context.DefaultBeanContext",
        "methodName": "getBean",
        "fileName": "DefaultBeanContext.java",
        "lineNumber": 842
      },
      {
        "className": "io.micronaut.context.BeanLocator",
        "methodName": "getBean",
        "fileName": "BeanLocator.java",
        "lineNumber": 97
      },
      {
        "className": "io.micronaut.context.DefaultBeanContext",
        "methodName": "publishEvent",
        "fileName": "DefaultBeanContext.java",
        "lineNumber": 1831
      },
      {
        "className": "io.micronaut.context.DefaultBeanContext",
        "methodName": "start",
        "fileName": "DefaultBeanContext.java",
        "lineNumber": 360
      },
      {
        "className": "io.micronaut.context.DefaultApplicationContext",
        "methodName": "start",
        "fileName": "DefaultApplicationContext.java",
        "lineNumber": 216
      },
      {
        "className": "io.micronaut.runtime.Micronaut",
        "methodName": "start",
        "fileName": "Micronaut.java",
        "lineNumber": 75
      },
      {
        "className": "io.micronaut.runtime.Micronaut",
        "methodName": "run",
        "fileName": "Micronaut.java",
        "lineNumber": 334
      },
      {
        "className": "io.micronaut.runtime.Micronaut",
        "methodName": "run",
        "fileName": "Micronaut.java",
        "lineNumber": 320
      },
      {
        "className": "com.mypackage.myapp.Application",
        "methodName": "main",
        "fileName": "Application.java",
        "lineNumber": 9
      }
    ]
  }
}
```

**Comment by rkrishnas81** [comment]
grails 6 jboss 7.4
getting failed: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 
my build.gradle. please help me
buildscript {
    repositories {
        maven { url "https://repo.grails.org/grails/core" }
        mavenCentral()
    }
    dependencies { // Not Published to Gradle Plugin Portal
        classpath "org.grails:grails-gradle-plugin:6.2.4"
        classpath "org.grails.plugins:hibernate5:8.1.0"
    }
}

plugins {
    id "groovy"
    id "com.github.erdi.webdriver-binaries" version "3.2"
    id "war"
    id "idea"
    id "com.bertramlabs.asset-pipeline" version "4.5.1"
    id "application"
    id "eclipse"
}

// Not Published to Gradle Plugin Portal
apply plugin: 'war'
apply plugin: 'org.grails.grails-web'

bootWar {
    enabled = true
}
jar {
    enabled = false
}
group = "com.example"

repositories {
    mavenCentral()
    maven { url "https://repo.grails.org/grails/core/" }
}

configurations {
    all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details->
            if (details.requested.group == 'org.seleniumhq.selenium') {
                details.useVersion('4.19.1')
            }
        }
    }
}

dependencies {

    profile "org.grails.profiles:web"

        implementation('org.springframework.boot:spring-boot-starter-web') {
            exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
        }
    implementation "org.grails:grails-core"
    implementation "org.grails:grails-logging"
    implementation "org.grails:grails-plugin-databinding"
    implementation "org.grails:grails-plugin-i18n"
    implementation "org.grails:grails-plugin-interceptors"
    implementation "org.grails:grails-plugin-rest"
    implementation "org.grails:grails-plugin-services"
    implementation "org.grails:grails-plugin-url-mappings"
    implementation "org.grails:grails-web-boot"
    implementation "org.grails.plugins:gsp"
    implementation "org.grails.plugins:hibernate5"
    implementation "org.grails.plugins:scaffolding"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-logging"
    //implementation "org.springframework.boot:spring-boot-starter-tomcat"
    providedCompile 'org.springframework.boot:spring-boot-starter-tomcat'
    implementation "org.springframework.boot:spring-boot-starter-validation"
    compileOnly "io.micronaut:micronaut-inject-groovy"
    console "org.grails:grails-console"
    runtimeOnly "com.bertramlabs.plugins:asset-pipeline-grails:4.5.1"
    runtimeOnly "com.h2database:h2"
    runtimeOnly "org.apache.tomcat:tomcat-jdbc"
    runtimeOnly "org.fusesource.jansi:jansi:1.18"
    testImplementation "io.micronaut:micronaut-inject-groovy"
    testImplementation "org.grails:grails-gorm-testing-support"
    testImplementation "org.grails:grails-web-testing-support"
    testImplementation "org.grails.plugins:geb"
    testImplementation "org.seleniumhq.selenium:selenium-api:4.19.1"
    testImplementation "org.seleniumhq.selenium:selenium-remote-driver:4.19.1"
    testImplementation "org.seleniumhq.selenium:selenium-support:4.19.1"
    testImplementation "org.spockframework:spock-core"
    testRuntimeOnly "org.seleniumhq.selenium:selenium-chrome-driver:4.19.1"
    testRuntimeOnly "org.seleniumhq.selenium:selenium-firefox-driver:4.19.1"
    testRuntimeOnly "org.seleniumhq.selenium:selenium-safari-driver:4.19.1"
}

application {
    mainClass = "com.example.Application"
}

java {
    sourceCompatibility = JavaVersion.toVersion("11")
}

tasks.withType(Test) {
    useJUnitPlatform()
    systemProperty "geb.env", System.getProperty('geb.env')
    systemProperty "geb.build.reportsDir", reporting.file("geb/integrationTest")
    systemProperty 'webdriver.chrome.driver', "${System.getenv('CHROMEWEBDRIVER')}/chromedriver"
    systemProperty 'webdriver.gecko.driver', "${System.getenv('GECKOWEBDRIVER')}/geckodriver"
}
webdriverBinaries {
    chromedriver '122.0.6260.0'
    geckodriver '0.33.0'
    edgedriver '110.0.1587.57'
}
assets {
    minifyJs = true
    minifyCss = true
    skipNonDigests = true
}

**Comment by rkrishnas81** [comment]
using jdk17
