### ISSUE TITLE
Is eager init required to get the config evaluated at startup?

### ISSUE THREAD

**Issue by codepitbull** [micronaut-projects/micronaut-core#7154]
### Issue description

I wasn't sure if this is by design or I am overlooking something so I filed this as other.

We are using Micronaut 3 for several applications and I just realised that config isn't evaluated on startup.
This is rather important to us because we are running continuous deployment and a broken config (e.g. missing environment variable) could be the cause for the application failing at an arbitrary time.

I figured out that config is evaluated eagerly together with other singletons so I switched on eager init.

it feels kinda weird because a failure to resolve a property in the configuration should fail the startup early on and not when the property is accessed the first time.

I'd really like to avoid making all singletons initialise eagerly just to get the config evaluated because I like to stick with framework defaults as far as possible.

So, am I overlooking something or is this really the only way to get the config checked?

Thanks,
Jochen

**Comment by graemerocher** [comment]
See https://docs.micronaut.io/latest/guide/#eagerInit

You can add:

```
public class Application {

    public static void main(String[] args) {
        Micronaut.build(args)
            .eagerInitConfiguration(true) 
            .mainClass(Application.class)
            .start();
    }
}
```

Which eagerly initializes only the configuration

**Comment by codepitbull** [comment]
Aaaaaaahhhhhhhh, I am so sorry.
Yes, I just stumbled over that method.

Sorry for bothering and thanks even more for your quick reply :)
