### ISSUE TITLE
Newly created projects with the base profile lack mainClassName, causing build failures

### ISSUE THREAD

**Issue by weiqigao** [micronaut-projects/micronaut-core#717]
### Steps to Reproduce

1. $ mn create-app -p base demo
2. $ cd demo
3. $ ./gradlew build

### Expected Behaviour

BUILD SUCCESSFUL

### Actual Behaviour

> Task :compileJava
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.NonIncrementalProcessor' less than -source '11'
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.NonIncrementalProcessor' less than -source '11'
warning: Supported source version 'RELEASE_8' from annotation processor 'org.gradle.api.internal.tasks.compile.processing.NonIncrementalProcessor' less than -source '11'
3 warnings

> Task :processResources
> Task :classes
> Task :jar
> Task :startScripts FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':startScripts'.
> No value has been specified for property 'mainClassName'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
4 actionable tasks: 4 execute

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** |Micronaut Version: 1.0.0.RC2
|JVM Version: 11
- **JDK Version:** openjdk 11 2018-09-25
OpenJDK Runtime Environment AdoptOpenJDK (build 11+28)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11+28, mixed mode)

**Comment by jameskleeh** [comment]
@weiqigao The base profile is not designed to be used directly. One of the other profiles must be used (service, function-aws, kafka, etc). I'll mark this issue as an improvement to the CLI to throw an error if this case is encountered in the future.
