### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder

### ISSUE THREAD

**Issue by TimothyL96** [micronaut-projects/micronaut-core#7173]
> Gradle Daemon started in 2 s 594 ms
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

In build.gradle:
`implementation("ch.qos.logback:logback-classic")`

- Micronaut 3.4.1
- Logback Classic 1.2.10

I'm getting this error same any idea how to fix it though I'm not sure if the problem is from Micronaut or Gradle.

Looks like it's fixed here: https://github.com/micronaut-projects/micronaut-core/issues/6912 but is still happening for debug.
The logback classic library already has the `org.slf4j.impl.StaticLoggerBinder`

### Steps To Reproduce

With Intellij IDEA, set up run configuration at top right with Gradle run and run it in debug mode.

### Environment Information

JDK 17
Windows 10

### Version

3.4.1

**Comment by graemerocher** [comment]
can you provide an example that reproduces the issue?

**Comment by TimothyL96** [comment]
Looks like the error comes from `id("com.gorylenko.gradle-git-properties") version "2.4.0"` instead

https://github.com/n0mer/gradle-git-properties/issues/203
