### ISSUE TITLE
Object to string json is empty on native image

### ISSUE THREAD

**Issue by glats** [micronaut-projects/micronaut-core#7179]
### Expected Behavior

The method `objectMapper.writeValueAsString()` should transform the object to the string in the utility class.

### Actual Behaviour

The objectMapper doesn't transform enything.

``` 
$ ./target/empty-object-error-jackson
 __  __ _                                  _   
|  \/  (_) ___ _ __ ___  _ __   __ _ _   _| |_ 
| |\/| | |/ __| '__/ _ \| '_ \ / _` | | | | __|
| |  | | | (__| | | (_) | | | | (_| | |_| | |_ 
|_|  |_|_|\___|_|  \___/|_| |_|\__,_|\__,_|\__|
  Micronaut (v3.4.1)

15:03:26.836 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 122ms. Server Running: http://localhost:8080
15:03:55.685 [default-nioEventLoopGroup-1-2] INFO  me.jics.MainController - User={} <-- wrong!
15:04:10.008 [default-nioEventLoopGroup-1-4] INFO  me.jics.MainController - User={"name":"test"}


$ curl http://localhost:8080/main/user-wrong
{"name":"test"}
$ curl http://localhost:8080/main/user-fine
{"name":"test"}
``` 

### Steps To Reproduce

1. create a project with the following params `mn create-app me.jics.empty-object-error-jackson --jdk=17 -t spock  --features graalvm,reactor,lombok,gcp-pubsub --build maven`
2. create an utility class an add the objectMapper.
3. create a native image: `mvn -T 1C package -Dpackaging=native-image -Pgraalvm`
4. make request to see the output

### Environment Information

- Mac OSX Big Sur
- GraalVM 22.0.0.2.r17-grl

### Example Application

https://github.com/j1cs/empty-object-error-jackson

### Version

3.4.1

**Comment by yawkat** [comment]
native-image does not include reflection information for classes by default. You need to either use the micronaut-provided ObjectMapper, which has special handling for `@Introspected` beans, or mark your beans as `@ReflectiveAccess`.

**Comment by glats** [comment]
@yawkat thanks for responding. Look I tried using `@ReflectiveAccess` in the utility class, `@TypeHint` in the controller, in the utility class as well, and neither working. 
Could you please show me an example to carry out my task? would be very much appreciated.

**Comment by yawkat** [comment]
See https://docs.micronaut.io/latest/guide/index.html#_understanding_micronaut_and_graalvm

The annotation must be on the bean youre serializing.

**Comment by glats** [comment]
@yawkat I don't want to waste your time but unfortunately it seems that I don't think I'm understanding the concepts well. let me see if I understand, my bean in this case would be my utility class, if this is so then putting the annotation should work, right?
I checked the `reflect-config.json` that micronaut generate for the graalvm and it show this:
``` 
[ {
  "name" : "me.jics.JsonUtil",
  "allDeclaredFields" : true,
  "allPublicMethods" : true,
  "methods" : [ {
    "name" : "<init>",
    "parameterTypes" : [ ]
  } ],
  "allDeclaredConstructors" : true
}, {
  "name" : "me.jics.JsonUtil[]"
}, {
  "name" : "me.jics.User$UserBuilder",
  "allDeclaredMethods" : true,
  "allDeclaredFields" : true,
  "allDeclaredConstructors" : true
} ]
``` 
I added a pair of log to see what's going on inside:
```
    public String getStringFromObject(Object obj) {
        try {
            log.info(obj.toString());
            log.info(objectMapper.writeValueAsString(obj)); // empty
            return objectMapper.writeValueAsString(obj);
        } catch (JsonProcessingException e) {
            log.error(e.getLocalizedMessage());
            return "{}";
        }
    }
 ```
and it's entering fine into the class
```
10:28:22.953 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 266ms. Server Running: http://localhost:8080
10:28:24.893 [default-nioEventLoopGroup-1-2] INFO  me.jics.JsonUtil - User(super=me.jics.User@3644cd, name=test)
10:28:24.894 [default-nioEventLoopGroup-1-2] INFO  me.jics.JsonUtil - {}
10:28:24.894 [default-nioEventLoopGroup-1-2] INFO  me.jics.MainController - User={}

```

**Comment by yawkat** [comment]
No, the bean is me.jics.User

**Comment by glats** [comment]
Perfect. Now I understand. I need to set `@ReflectiveAccess` to my POJO (in this case also a bean) and now the objectMapper can catch all the attributes of the class. Thank you, very clarified.
