### ISSUE TITLE
Does micronaut supports request body for a HTTP GET method ?

### ISSUE THREAD

**Issue by SushmaReddyLoka** [micronaut-projects/micronaut-core#7182]
### Issue description

Does micronaut supports request body for a HTTP GET method ? 

Here is a sample controller, which defines a Http 'Get' method with body. It fails with error , "Required Body [body] not specified"

@Controller()
public class TestController {

 @Get(value = "/getdata", consumes = MediaType.TEXT_PLAIN)
    public Object test1(@Body byte[] body){
        System.out.println(body);
        return body;
    }
}

As Http RFC doesn't say that body is strictly prohibited for GET requests. Wanted to check if there any suggestions on how to make this work ?

**Comment by yawkat** [comment]
No it is not supported
