### ISSUE TITLE
document @Blocking

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7183]
### Issue description

@Blocking is almost undocumented. We have this mention: 

 > Micronaut’s version of Transactional is meta-annotated with @Blocking, ensuring that all methods annotated with it use the I/O thread pool when executing within the HTTP server

https://docs.micronaut.io/snapshot/api/io/micronaut/core/annotation/Blocking.html

It seems the logic is here: 

[DefaultExecutorSelector](https://github.com/micronaut-projects/micronaut-core/blob/3.4.x/context/src/main/java/io/micronaut/scheduling/executor/DefaultExecutorSelector.java)

**Comment by sdelamo** [comment]
@wetted can you please check core and understand what `@Blocking` does and document it. I think it is pretty much the same as `@ExecuteOn`-

**Comment by wetted** [comment]
The documentation snippet referenced above is no longer relevant for Micronaut 3.x and beyond. The Micronaut meta-annotated `io.micronaut.spring.tx.annotation.Transactional` annotation was removed altogether for Micronaut 3. The section at https://docs.micronaut.io/latest/guide/#springAop needs additional revision to reflect that change. The Spring/Micronaut mapping for `Transactional` was replaced by `TransactionInterceptor` re-annotated with `@InterceptorBean(org.springframework.transaction.annotation.Transactional.class)`. See: https://github.com/micronaut-projects/micronaut-spring/pull/207.

With that said, `@Blocking` seems similar but not the same as `@ExecuteOn`. I still need to understand it all better for the sake of proper documentation, so it's a WIP.
