### ISSUE TITLE
Using @Client in a library can cause NonUniqueBeanException: Multiple possible bean candidates found

### ISSUE THREAD

**Issue by drew-corporate-creations** [micronaut-projects/micronaut-core#7186]
### Expected Behavior

I'm currently in the process of upgrading a multi-project application from micronaut 2.5 to micronaut 3.4.1. I have a project with multiple libraries, and another project with multiple services.

One library has an @Client. There are other libraries that depend on client lib. The services are a completely separate project, and depend on the shadow jars of the libraries.

Example: 

client-lib -> contains the @Client

libA -> depends on client-lib

libB -> depends on client-lib

service -> a separate project that depends on libA and libB. Uses the @Client.

Expected behavior is that no error should occur when using @Client in the service.
Error did not occur in micronaut 2.5.

### Actual Behaviour

This error occurs when using @Client in the service in micronaut 3.4.1 but not micronaut 2.5: 
```
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [com.example.service.SomeController]

Message: Multiple possible bean candidates found: [io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry, io.micronaut.aop.InterceptorRegistry]
```

### Steps To Reproduce

I created a minimal example application and included it in the attached GitHub repo: https://github.com/drew-corporate-creations/mn-multi-project

I used projects created by 'micronaut launch'.

Since it involves two separate projects, Instructions on how to run it are included in the README. (build libs, publishToMavenLocal, then run the unit test in the service.)

### Environment Information

Java 11
macOS Monterey 12.2.1

### Example Application

https://github.com/drew-corporate-creations/mn-multi-project

### Version

3.4.1

**Comment by goeh** [comment]
Thank you for reporting. Looks very much like the problem I had two weeks ago. But I was on a tight schedule so I downgraded to Micronaut 2.5.13 to be able to deliver on time.

**Comment by graemerocher** [comment]
This issue is typically an issue with your dependency graph in that you have multiple versions of `micronaut-aop` on the classpath hence multiple `InterceptorRegistry` beans hence the exception.

**Comment by graemerocher** [comment]
The issue in your example is you are shadow packaging the client libraries into FAT jars which include all of the Micronaut JARs twice into the target application hence the exception

**Comment by goeh** [comment]
Thanks @graemerocher , that explains my problems. I'm sure I had a mix of dependencies built/assembled with Micronaut 2.5.x i my 3.4.1 application. I need to go through all my api/client projects and make sure I have a minimum of Micronaut dependencies in the jars. Suggestion: A section in the documentation on best practices building client libraries with Micronaut and how to avoid gotchas lite this.

**Comment by graemerocher** [comment]
we have it in mind to create library projects with launch /cc @sdelamo
