### ISSUE TITLE
/routes not working.

### ISSUE THREAD

**Issue by yassirez-znafry** [micronaut-projects/micronaut-core#7238]
### Issue description

I have this sample [hello world project](https://github.com/yassirez-znafry/sample-micronaut-app) in micronaut. After I added the _micronaut-management_ dependency, I tried to enter to _http://localhost:8080/routes_ to see all my endpoints. but It shows me _This page isn’t working_.
Steps to reproduce:
1- Create a micronaut project using https://micronaut.io/launch , (Java 8 and maven).
2- Add the _micronaut-management_ dependency to the pom.xml .
3- run the application and enter to _http://localhost:8080/routes_ .

**Comment by jeffscottbrown** [comment]
@yassirez-znafry 

https://stackoverflow.com/a/71944127/3533584

Did the pull request at https://github.com/yassirez-znafry/sample-micronaut-app/pull/1 address the issue?
