### ISSUE TITLE
Heartbeat is ignoring enabled and interval 

### ISSUE THREAD

**Issue by neo-lestat** [micronaut-projects/micronaut-core#7251]
### Expected Behavior

1. I set micronaut.heartbeat.enabled to false so HeartbeatTask should not be executed
2. I set micronaut.heartbeat.interval to 1s to change the HeartbeatTask frecuency (1s just to test the frecuency is changed)

I tested with versions 2.5.12, 3.4.0

### Actual Behaviour

1. HeartbeatTask was executed ignoring the enabled equals false
2. HeartbeatTask was executed with the default frequency (15s)

I debug my application and i could see that HeartbeatConfiguration contains the right values, as workaround i tried to use the HeartbeatEnabled annotation in the custom health indicators and this disable the health indicators both in the health endpoint and HeartbeatTask.

### Steps To Reproduce

1. Create micronaut application
2. create a healthindicator with log to see the execution or change the micronaut log level to debug to see the HeartbeatEvent executions
4. set the heartbeat configurations
5. start the application and see the logs 

### Version

2.5.12, 3.4.0

**Comment by neo-lestat** [comment]
I found the problem, i tried to use the properties in the configuration guide

micronaut.heartbeat.interval
micronaut.heartbeat.enabled


but in the source the properties are:

micronaut.health.monitor.interval
micronaut.health.monitor.enabled

Maybe there is some confusion in the docs between HealthMonitorTask and HeartbeatConfiguration.

**Comment by alvarosanchez** [comment]
`HealthMonitorTask` and `HeartbeatTask` are different things.
