### ISSUE TITLE
Multiple Gradle workers and tests using @MicronautTest sometimes fail with "Unable to start Micronaut server on port: xxx"

### ISSUE THREAD

**Issue by KarlHakanNordgren** [micronaut-projects/micronaut-core#7264]
### Expected Behavior

The @MicronautTest should generate an embedded server with an available port even if the tests are run using multiple gradle workers in parallel.

### Actual Behaviour

Tests annotated with `@MicronautTest` sometimes fail with "Unable to start Micronaut server on port: xxx". We configure the server with port: ${random.port} so it appears that the randomly selected port is available when it is found using `SocketUtils.findAvailableTcpPort()` and then it is not available when `bindServerToHost()` attempts to use it. 

### Steps To Reproduce

1. Run multiple tests using `@MicronautTest` and in Gradle workers with `maxParallelForks > 1`.
2. This will eventually lead to `ERROR i.m.h.server.netty.NettyHttpServer - Unable to start server. Port xxx already in use.` and `ServerStartupException: Unable to start Micronaut server on port: xxx`.

### Environment Information

- Repros on OSX and Ubuntu
- Java 17
- Kotlin 1.6.20
- Micronaut 3.4.1

### Version

3.4.1

**Comment by graemerocher** [comment]
Try using -1 as the port number instead

**Comment by KarlHakanNordgren** [comment]
@graemerocher : Ok thanks will do.
