### ISSUE TITLE
Docs should describe the syntax and semantics of placeholder properties in config files

### ISSUE THREAD

**Issue by bobtiernay-okta** [micronaut-projects/micronaut-core#731]
Currently there doesn't appear to be any documentation describing `${...}` syntax and semantics in configuration files, including information on accessing environmental variables and system properties, as well as default values. This should be added similar to what Spring Boot does:

- https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-placeholders-in-properties

**Comment by graemerocher** [comment]
This has been improved with https://docs.micronaut.io/snapshot/guide/index.html#propertySource and new sections under https://docs.micronaut.io/snapshot/guide/index.html#configurationProperties

Is that what you are looking for?
