### ISSUE TITLE
Correct type for mjs files (Javascript modules)

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7313]
[I think we should return `text/javascript`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)

### Discussed in https://github.com/micronaut-projects/micronaut-core/discussions/7301

<div type='discussions-op-text'>

<sup>Originally posted by **siddharth223437** May  2, 2022</sup>
Micronaut think that all ".mjs" file are "text/plain" so how can i tell micronaut to map all ".mjs" to "application/javascript". Below is  springboot code:

```
 @Override
    public void customize(ConfigurableServletWebServerFactory factory) {
        MimeMappings mappings = new MimeMappings(MimeMappings.DEFAULT);
        mappings.add("mjs", "application/javascript");
        factory.setMimeMappings(mappings);
    }
```</div>

**Comment by alvarosanchez** [comment]
Apart from changing this default, we should also allow users to define arbitrary mappings. 

Probably worth a separate issue.

**Comment by sdelamo** [comment]
closed via https://github.com/micronaut-projects/micronaut-core/pull/7307
