### ISSUE TITLE
Websocket connection fails (timeout) after two successfull connections

### ISSUE THREAD

**Issue by gbennardo** [micronaut-projects/micronaut-core#7314]
### Expected Behavior

Client should connect successfully to the websocketclient

### Actual Behaviour

After two successful connections, the third connection request to a websocketclient fails due to a timeout. This only happens if the micronaut application runs as a kubernetes pod. Running as a stand alone application locally it doesn't happen. 

This is the ingress error:
`[error] 1990#1990: *827489 upstream timed out (110: Operation timed out) while reading response header from upstream,`

The problem is similar to #3651 but `micronaut.server.thread-selection: IO` did not solve.

### Steps To Reproduce

1. Run a kubernetes pod that runs a micronaut application with a `ServerWebSocket` implementation
2. Connect to the websocket and disconnect multiple times
3. The third attempt to connect fails

### Environment Information

- JDK 17
- microk8s

### Version

3.4.2

**Comment by yawkat** [comment]
Can you give a test case?
