### ISSUE TITLE
Flowable<String> should not be wrapped as 

### ISSUE THREAD

**Issue by jespersm** [micronaut-projects/micronaut-core#734]
### Steps to Reproduce

1. Make a controller which returns something streamable (but opaque) content, like byte[] or String), using af JSON'ish content-type:

```
        @Get(value = "/someJson", produces = MediaType.APPLICATION_JSON)
        Flowable<byte[]> someJson() {
            return Flowable.just('{"key":"value"}'.getBytes(StandardCharsets.UTF_8))
        }
```
or
```
        @Get(value = "/someJson", produces = MediaType.APPLICATION_JSON)
        Flowable<String> someJson() {
            return Flowable.just('{"key":"value"}')
        }
```
or even
```
        @Get(value = "/someJson", produces = MediaType.APPLICATION_JSON)
        HttpResponse<Flowable<String>> someJson() {
            return HttpResponse.ok(Flowable.just('{"key":"value"}'))
        }
```
2. Call this endpoint.

### Expected Behaviour

I expect a payload of

```
{"key":"value"}
```

### Actual Behaviour

I get this:
```
[{"key":"value"}]
```
(if I had returned more strings, they would have been comma separated)

This happens because RoutingInBoundHandler judges this to be a stream of JSON content, since it the controller has a non-single reactive return type variable.

The downside of this is that if you are writing a controller which just transports the raw buffer (and blindly copies the HTTP contentType (like in a proxy), you'd interfere with the content bytes.

### Environment Information

- **Operating System**: macOS, probably everywhere
- **Micronaut Version:** current master
- **JDK Version:** 1.8.0_181

### Example Application

Patch containing testcase and a (crude?) fix is coming as a PR.

**Comment by graemerocher** [comment]
This is not a bug, but by design. A `Flowable` is an unbound type and if your example emitted two items you would get:

```
{"key":"value"}{"key":"value"}
```

Which is not valid JSON and violates the specified return type. If you want the above you have to specify that the return type is `MediaType.APPLICATION_JSON_STREAM`

**Comment by graemerocher** [comment]
Ok I see what you are saying, however I don't know how you would disambiguate the case where you return 2 fully formed JSON strings with this change.

**Comment by jespersm** [comment]
The catch is that the [<chunk>,<chunk>,...] framing happens for all content wrapped in a 'streamable' when using any JSON type, not just `APPLICATION_JSON_STREAM`.

I stumbled across this while developing a proxy for generic content, connecting the (reactive) response flow of the Micronaut HTTP client to a Flowable<byte[]> in a controller. Right now this works for anything but JSON.

I guess one could envisage a 'raw' attribute in the @Produces annotation? Or just let byte[] through?

**Comment by graemerocher** [comment]
I think if you update the PR to only allow `byte[]` or `ByteBuf` or `ByteBuffer` then we can consider longer term adding `raw` or something equivalent to customise the behaviour.

**Comment by jespersm** [comment]
I've updated #735 with the short term solution
