### ISSUE TITLE
Service introduction requires adding package to the incremental build settings in Gradle

### ISSUE THREAD

**Issue by musketyr** [micronaut-projects/micronaut-core#7340]
### Expected Behavior

When I add a library which has an `@Introduction` annotation and I use the annotation on the interface then the bean is created for the interface.

### Actual Behaviour

The bean is not created and `NoSuchBeanException` is thrown at the injection point. I need to add the package of the annotation from the library to the `build.gradle` file to make the introduction work.

```
micronaut {
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("hello.paris.jug.at.agorapulse.*")
        annotations("com.agorapulse.*") // this line is required even it should not be
    }
}
```

### Steps To Reproduce

1. Clone the example application https://github.com/musketyr/service-introduction-micronaut-issue
2. Run the `MessageRepositoryTest` test - the test will fail
3. Remove the comment in `48` in `build.gradle` - the test will pass.

### Environment Information

Tested on JDK 8 or JDK 11

### Example Application

https://github.com/musketyr/service-introduction-micronaut-issue

### Version

3.4.3

**Comment by graemerocher** [comment]
This is correct since Micronaut needs to know about the annotations that are to be processed. If this is not what you want you can disable incremental compile

**Comment by melix** [comment]
It's a bit confusing: the service annotation here is in a library, so adding `annotations("com.agorapulse.*")` suggests that it would process the annotations _in the library_. Is it really required?

**Comment by graemerocher** [comment]
I agree it is confusing, I am just not sure what we can do about it since the annotation processors in incremental mode are limited to a set of annotation name patterns. A "workaround" would be to make the Micronaut compiler aware of the new annotations. But for that you would need to do two things which are also a bit ugly:

* Add a module for the library that contains a no-op `AnnotationRemapper` with the new package name since these are added automatically https://github.com/micronaut-projects/micronaut-core/blob/4fb1c7f61e2701f8babd561942c414332d37ab52/inject-java/src/main/java/io/micronaut/annotation/processing/AbstractInjectAnnotationProcessor.java#L168-L171
* Add the module for the library to the annotation processor classpath

I am not sure if this "better" than just documenting how the library can be used in the documentation.

In general this is not an issue for Micronaut modules because they use the `io.micronaut` and we process all annotations in that package.

**Comment by musketyr** [comment]
thanks @graemerocher. I will try the re-mapper. I would like to add more of these libraries soon as a new starter features and I would them to work out of the box.

**Comment by musketyr** [comment]
just to be sure @graemerocher, by no-op remapper you mean something like this?

```
public class ServiceAnnotationRemapper implements AnnotationRemapper {

    @Nonnull
    @Override
    public String getPackageName() {
        return Service.class.getPackage().getName();
    }

    @Nonnull
    @Override
    public List<AnnotationValue<?>> remap(AnnotationValue<?> annotation, VisitorContext visitorContext) {
        return Collections.singletonList(annotation);
    }

}
```

Or can I simply return `Collections.emptyList()` from the `remap` method?

**Comment by graemerocher** [comment]
yes like that

**Comment by musketyr** [comment]
I've created a remapper for every annotation using `@Introduction` in the Micronaut AWS SDK but it still looks to me that there is still some missing piece. I have created files in `resources/META-INF/services/io.micronaut.inject.annotation.AnnotationRemapper` to point to the new remappers.

See the commit here: https://github.com/agorapulse/micronaut-aws-sdk/commit/22d2e6cae1894697c48aa9d1c0ac39c877fda7b4

When I migrate the imports and publish the library locally and then use it with the demo project with `implementation` and `annotationProcessor` **without** defining the annotation packages then it still does not generate the required sidecar classes.

<img width="1279" alt="Snímek obrazovky 2022-05-10 v 12 43 06" src="https://user-images.githubusercontent.com/660405/167611111-c37d8fb5-f7cf-4ce9-8eb6-e7ae282000a0.png">

**Comment by graemerocher** [comment]
yes as I said it needs to be a separate module that is present in the `annotationProcessor` classpath

**Comment by musketyr** [comment]
I'm sorry for the noise, it was actually working. I have looked at the wrong class.

**Comment by graemerocher** [comment]
note that I recommend you create a separate module rather than placing the whole dynamodb module in the annotation processor classpath

**Comment by musketyr** [comment]
got it. so the module will only contain the single class - the remapper, right?

**Comment by graemerocher** [comment]
right

**Comment by musketyr** [comment]
thank you, you all saved my day (and demo in the evening) :-)

I have created a PR for the Micronaut AWS and I later I will check the other libraries

https://github.com/agorapulse/micronaut-aws-sdk/pull/105

**Comment by musketyr** [comment]
I'm closing the issue as this is by design and verified workaround is available
