### ISSUE TITLE
build: Add JaxRS module bom

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-core#7341]
Once this is out

https://github.com/micronaut-projects/micronaut-jaxrs/pull/236

We should integrate the bom into the build

**Comment by sdelamo** [comment]
[Micronaut JAX-RS 3.3.0 is out](https://github.com/micronaut-projects/micronaut-jaxrs/releases/tag/v3.3.0)

**Comment by timyates** [comment]
Closed by https://github.com/micronaut-projects/micronaut-core/pull/7400
