### ISSUE TITLE
Fails to route when controller method with multiple uris and client using accept header

### ISSUE THREAD

**Issue by sumitaneja** [micronaut-projects/micronaut-core#7344]
### Expected Behavior

Create a controller with methods for Get, put, post. Configure multiple uris(same set) for these Http methods.

From client make request with accept header(see reproducer)

 Expected Request should be received by controller. 

### Actual Behaviour

But micronaut RoutingInboundHandler rejects with from one of the URIs.
Method [..] not allowed for URI [...]

### Version

2.5.13

**Comment by sumitaneja** [comment]
Steps to reproduce
Git https://github.com/sumitaneja/MicronautIssues/tree/main/Issue7344

Download this module and run URLContorllerSpec.  Failing test is the use case. 

Passing tests are other combinations that work

**Comment by graemerocher** [comment]
@yawkat would you mind taking a look

**Comment by yawkat** [comment]
The issue is your `@Produces(MediaType.ALL)`, if you remove it, the test works fine.

@graemerocher what is `@Produces(MediaType.ALL)` supposed to do?

**Comment by graemerocher** [comment]
I think this was only designed to be used for consumes and not produces, probably we should fail compilation if it is used in combination with produces

**Comment by sumitaneja** [comment]
HI @graemerocher @yawkat we tried above workaround, it has issues with other content type.
We removed @Produces annotation.
Client sending application/xml as content type in accept header

Client received error:
io.micronaut.http.client.exceptions.HttpClientResponseException: Specified Accept Types [application/xml] not supported. Supported types: [application/json]
