### ISSUE TITLE
Find mainClassName automatically

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-core#736]
More than one time I have had mismatch between the actual main class and the `mainClassName` config in `build.gradle`. Sometimes I copied and renamed an existing project and sometimes I renamed the java class and forgot to change build.gradle.

Would it be possible to find the main class automatically without the need to specify it in build.gradle? I guess this logic is not in Micronaut itself but in one of the Gradle/Maven plugins.

This issue has low priority because the error message is clear and the fix is easy, but it would improve the developer experience if this setting was not needed.

### Steps to Reproduce

1. Create a Micronaut application
2. Remove or comment out the `mainClassName` setting
3. Try to start the application

### Expected Behaviour

The application should start if it only finds one main class.

### Actual Behaviour

```
./gradlew run
* What went wrong:
Execution failed for task ':run'.
> No main class specified
```

```
./gradlew build
* What went wrong:
A problem was found with the configuration of task ':startScripts'.
> No value has been specified for property 'mainClassName'.
```

If `mainClassName` is set to an invalid class name.

```
`Error: Could not find or load main class .......`
```

### Environment Information

- **Operating System**: MacOs
- **Micronaut Version:** 1.0.0.RC3
- **JDK Version:** 1.8.0_162-b12

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by graemerocher** [comment]
This would likely require class path scanning unless we could do something at compilation time. We will not do class path scanning due to the impact on startup time, so the latter is the only option. Not for 1.0 however.

**Comment by jameskleeh** [comment]
@graemerocher I personally don't think the cost/benefit works out for something like this. I vote to close
