### ISSUE TITLE
Investigate if we can get rid of managed-kafka

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7383]
### Issue description

see: https://github.com/micronaut-projects/micronaut-core/pull/7370

**Comment by timyates** [comment]
For 3.4.x, we need to keep this.  In 3.5.0 we introduce the Kafka BOM

https://github.com/micronaut-projects/micronaut-core/issues/7116

This removes many of the requirements for managed-kafka, however we still have a library `managed-kafka212`

This was [discussed here](https://github.com/micronaut-projects/micronaut-core/pull/7123/files#r831939072) where we decided we needed to keep it, and maybe revisit for 4.0
