### ISSUE TITLE
StreamedFile and SystemFile not fully support attachment with not standard alphanumeric characters

### ISSUE THREAD

**Issue by Ksnz** [micronaut-projects/micronaut-core#7401]
### Expected Behavior

`StreamedFile` created as:
```
var filename = "example(汉字).filename"
new StreamedFile(fileStream, MediaType.forFilename(filename))
            .attach(filename);
```
Downloaded via browsers with name `example(汉字).filename`

### Actual Behaviour

`StreamedFile` created as:
```
var filename = "example(汉字).filename"
new StreamedFile(fileStream, MediaType.forFilename(filename))
            .attach(filename);
```
downloaded via browsers with name `example(__).filename`

If you force filename url encoding : `.attach(URLEncoder.encode(filename,UTF-8))`
Chrome will download it with name `example(汉字).filename`, 
But Safari download it like `example%28汉字%29.filename` where `()` keeps in encoded form 

It may sound like a Safari's bug, but if we read standard https://datatracker.ietf.org/doc/html/rfc6266#section-4.3 we can implement building `CONTENT_DISPOSITION` header it more fully
### Workarround
We can extend `StreamedFile` and add `filename*` section to `ATTACHMENT_HEADER` according to standard
```
    private final static String FIXED_ATTACHMENT_HEADER = "attachment; filename=\"%s\"; filename*=UTF-8''%s";
    @Override
    public void process(MutableHttpResponse<?> response)    {
        if (attachmentName != null)  {
            response.header(HttpHeaders.CONTENT_DISPOSITION,
                String.format(FIXED_ATTACHMENT_HEADER,
                    attachmentName,
                    URLEncoder.encode(attachmentName, StandardCharsets.UTF_8)));
        }
    }
```
And now all browsers download file with correct name :+1: 

### Environment Information

Chrome  101.0.4951.41
Safari 15.4

### Example Application

https://github.com/Ksnz/micronaut-attachment-header-issue

### Version

3.4.3

**Comment by yawkat** [comment]
the behavior of different browsers is described here: https://httpwg.org/specs/rfc6266.html#alternatives

**Comment by yawkat** [comment]
Thanks for the report
