### ISSUE TITLE
Kotlin value classes support

### ISSUE THREAD

**Issue by o-shevchenko** [micronaut-projects/micronaut-core#7409]
### Feature description

[Kotlin value classes](https://kotlinlang.org/docs/inline-classes.html) currently can't be used in Micronaut.
Value classes are very useful to create wrappers around standard types. 
Unfortunately, `value classes` is not supported, and we are forced to use [type aliases](https://kotlinlang.org/docs/type-aliases.html) as a workaround.

Example:
```kotlin
@Get(uri = "/{myId}")
    fun get(@PathVariable myId: Myid): HttpResponse<MyDto> {
        return HttpResponse.ok(service.get(myId))
    }
    
typealias MyId = String
```
I would like to replace it by:
```kotlin
value class MyId(private val id: String)
```

**Comment by samu-developments** [comment]
This is still not supported but would be greatly appreciated, I added an example project here https://github.com/samu-developments/mn-value-class

**Comment by samu-developments** [comment]
@sdelamo Is this something being considered?

**Comment by dstepanov** [comment]
It might work with KSP

**Comment by samu-developments** [comment]
@dstepanov I'm using KSP and unfortunately it does not work.

**Comment by sdelamo** [comment]
Probably the root issue, is that we don't support the `@Introspected` annotation for Kotlin inline classes. For example: 

```koltlin
@JvmInline
@Introspected
value class UserInlineValueClass(val name: String) {
}
val introspection: BeanIntrospection<UserInlineValueClass> = assertDoesNotThrow { 
    BeanIntrospection.getIntrospection(UserInlineValueClass::class.java) 
}
```

Fails with `Unexpected exception thrown: io.micronaut.core.beans.exceptions.IntrospectionException: No bean introspection available for type [class com.example.UserInlineValueClass]. Ensure the class is annotated with io.micronaut.core.annotation.Introspected`

**Comment by samu-developments** [comment]
Should this stay open until support is added?
