### ISSUE TITLE
Question: How to use extended types as return values from services

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-core#747]
Hello, I am trying to setup a demo for work on using Micronaut as our micro-services framework, and have a couple of questions. Wasn't sure if this is the right place to ask, so please let me know if there's a better forum for this.

I have setup a simple application with 3 projects: 'api', 'gateway' and 'service'. I based my code on reading combinations of the tutorial in the notes, the workshop and the petstore.

I setup a "Product" as an interface in kotlin (with id/name fields) as the main type that all APIs would use for methods, e.g.

    // data
    interface Product {
         val id: String
         val name: String
    }

    class RealProduct(pid: String, pname: String) : Product {
        override val id = pid
        override val name = pname
    }

    // api interface
    interface ProductOperations<T: Product> {
        @Get("/")
        fun listProducts(): Single<List<T>>
    }

    // gateway client
    @Client(id = "productcatalogue", path = "/products")
    interface ProductClient : ProductOperations<Product> {
        override fun listProducts(): Single<List<Product>>
    }

    // gateway controller
    @Get("/products")
    fun products() : Single<List<Product>> {
        return productClient.listProducts()
    }

    // service:
    override fun listProducts(): Single<List<Product>> {
        return Single.just(listOf(RealProduct("1", "name1"), RealProduct("2", "name2")))
    }

In my first attempt above, it failed. The gateway controller was causing Fallback behaviour on receiving the values from the service. If i hit the service endpoint directly, i was getting the json results I expected, but not the gateway. The only type that worked was Flowable<List < Product > >, the following caused Fallbacks on other methods I tried: Single< Product >, Maybe< Product >, Flowable< Product >.

To fix this, I had to change the interface to an open class for Product instead, and at which point all the above cases were correct, not falling back, and returning the data I required. I don't understand why though, particularly when the service calls work directly, but maybe it's the interaction from gateway to service and it being an interface, not a concrete class?

However, I then wanted to allow the services to return extended Product versions that may have additional fields. Is this possible? My attempts to do this returned only the Product fields in the eventual json response and not the extended fields of the subclass.

e.g.

    // type definition
    class ProductWithDesc(pid: String, pname: String, val desc: String) : Product(pid, pname)

    // gateway controller and client both as before...
    @Get("/products")
    fun products() : Single<List<Product>> {
        return productClient.listProducts()
    }

    // service (returning extended type)
    override fun listProducts(): Single<List<Product>> {
        return Single.just(listOf(ProductWithDesc("1", "name1", "desc1"), ProductWithDesc("2", "name2", "desc2")))
    }

    // This returns the json:
    [{"id":"1","name":"name1"},{"id":"2","name":"name2"}]

I can't change the service to return Single< List< ProductWithDesc > > because that causes a compilation error, as it doesn't override Single< List< Product>>, also I don't want to as I want to be able to return all kinds of sub-types that may have richer sets of data.

I'm not sure if this is a generic problem I haven't found a solution to, or a micronaut/reactive one (I'm guessing there's a better pattern to this).

Any advice on the above 2 issues? a) not being able to use interface, b) not seeing sub-class fields?

Many thanks.

**Comment by sdelamo** [comment]
Do you have a sample app?

**Comment by markjfisher** [comment]
I've created a repo at https://github.com/markjfisher/mn-demo

**Comment by jameskleeh** [comment]
You can't simply give Jackson an interface and some JSON and expect it to figure it out. When you tell Jackson to decode to an interface, you have to supply either your own deserialization strategy or given it a default type to deserialize to. This is entirely a Jackson question so I would suggest looking up Jackson resources for solutions. 

With regards to the multiple `[]`. When returning a Flowable that is intended to emit only a single item, you must supply that intent via the annotation. For example: `@Get(value = "/flowableListOfTypeProductInterface", single = true)`.

**Comment by markjfisher** [comment]
I forgot this was still open!
