### ISSUE TITLE
Remove `--allow-incomplete-classpath` 

### ISSUE THREAD

**Issue by alvarosanchez** [micronaut-projects/micronaut-core#7482]
The use of `--allow-incomplete-classpath` produce the following warning with GraalVM 22.1.0:

```
Warning: Using a deprecated option --allow-incomplete-classpath from 'META-INF/native-image/io.micronaut/micronaut-inject/native-image.properties' in 'file:///home/app/libs/micronaut-inject-3.5.0-SNAPSHOT.jar'. Allowing an incomplete classpath is now the default. Use --link-at-build-time to report linking errors at image build time for a class or package.
```

It is only used in micronaut-inject as far as I can tell.

**Comment by graemerocher** [comment]
we can't remove this as it will break compatibility with older versions of GraalVM which may break existing builds. Should probably only be fixed in the new major version.
