### ISSUE TITLE
build: remove swagger version from catalog

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-core#7490]
https://github.com/micronaut-projects/micronaut-core/pull/7457

**Comment by timyates** [comment]
This requires the release of a BOM version of Openapi https://github.com/micronaut-projects/micronaut-openapi/pull/733

**Comment by sdelamo** [comment]
what is the status of this?

**Comment by timyates** [comment]
This can be closed, swagger removal is for 4.0.0 and is tracked here https://github.com/micronaut-projects/micronaut-core/issues/7727
