### ISSUE TITLE
IntelliJ incremental build not working when modifying a class that is directly injected.

### ISSUE THREAD

**Issue by stepanv** [micronaut-projects/micronaut-core#7502]
### Expected Behavior

Ideally, IntelliJ with enabled "Build and run using" -> "IntelliJ IDEA" should be able to leverage its incremental build when Micronaut managed beans are modified. 

![image](https://user-images.githubusercontent.com/883323/170285737-9e02e6cd-8bc4-4271-bea5-ed10dba8b11c.png)

Incremental build takes usually few milliseconds comparing to a full module rebuild which may take 30 second or 2 minutes or even longer. In such case, when a Micronaut based application has many beans, development becomes extremely painful especially if people write their code + tests in a TDD cycle with small increments.

Note that the full rebuild is triggered when a particular class that is being injected is changed.
Such as
- If an impl class is injected, then when that class is changed, a full rebuild is triggered.
- if an interface is injected, then when that interface is changed, a full rebuild is triggered.

whereas
- If an interface is injected, then modifying its impl doesn't make IntelliJ to do a full rebuild.

Based on what I investigated, Micronaut 2 (2.2.1, 2.4.3, 2.5.13) and 3 (3.4.4) suffer from that behavior. However Micronaut 1 (I tried 1.3.7) was able to do incremental compilation.

In our project with 150 beans we suddenly hit the threshold. The full rebuild is taking more than 1 minute and because we like to inject beans without declaring interfaces for them (some folks are old enough to remember the J2EE days and are refusing to accept a workaround to "always" create an interface) we're now completely desperate because of the slow turn around.

This is how incremental compilation in IntelliJ looks like:
![image](https://user-images.githubusercontent.com/883323/170277988-5ea38e06-a608-4a79-ab30-cba1d31e1b29.png)

### Actual Behaviour

When modifying a class file of a bean that is injected somewhere else, IntelliJ full rebuild is triggered.

This is what IntelliJ logs when `MyService` is injected into `DemoController` directly and is changed:
```
2022-05-25 15:52:55,193 [  32193]   FINE - #o.j.j.b.j.d.Mappings - Begin of Differentiate:
2022-05-25 15:52:55,193 [  32193]   FINE - #o.j.j.b.j.d.Mappings - Easy mode: false
2022-05-25 15:52:55,198 [  32198]   FINE - #c.i.u.i.FileChannelWithSizeTracking - Inst:/Users/stepan.vavra/Library/Caches/JetBrains/IntelliJIdea2022.1/compile-server/demo_7ab3cf90/mappings/sourceToClass.tab.values@33bd46cc,Thread[JPS thread pool,5,main],java.net.URLClassLoader@2626b418
2022-05-25 15:52:55,198 [  32198]   FINE - #c.i.u.i.FileChannelWithSizeTracking - read:/Users/stepan.vavra/Library/Caches/JetBrains/IntelliJIdea2022.1/compile-server/demo_7ab3cf90/mappings/sourceToClass.tab.values@33bd46cc,Thread[JPS thread pool,5,main],7412,168355
2022-05-25 15:52:55,208 [  32208]   FINE - #o.j.j.b.j.d.Mappings - Processing changed classes:
2022-05-25 15:52:55,209 [  32209]   FINE - #o.j.j.b.j.d.Mappings - Changed: com/example/MyService
2022-05-25 15:52:55,213 [  32213]   FINE - #o.j.j.b.j.d.Mappings - End of changed classes processing
2022-05-25 15:52:55,213 [  32213]   FINE - #o.j.j.b.j.d.Mappings - Checking dependent classes:
2022-05-25 15:52:55,216 [  32216]   FINE - #o.j.j.b.j.d.Mappings - Dependent class: com/example/$MyService$Definition$Reference
2022-05-25 15:52:55,228 [  32228]   FINE - #o.j.j.b.j.d.Mappings - Dependent class: com/example/$DemoController$Definition
2022-05-25 15:52:55,230 [  32230]   FINE - #o.j.j.b.j.d.Mappings - Turning non-incremental for the BuildTarget because dependent class is annotation-processor generated
2022-05-25 15:52:55,231 [  32231]   FINE - #o.j.j.b.j.d.Mappings - Dependent class: com/example/DemoController
2022-05-25 15:52:55,231 [  32231]   FINE - #o.j.j.b.j.d.Mappings - Dependent class: com/example/$MyService$Definition
2022-05-25 15:52:55,232 [  32232]   FINE - #o.j.j.i.Builder - Differentiate Results:
2022-05-25 15:52:55,232 [  32232]   FINE - #o.j.j.i.Builder -    Compiled Files:
2022-05-25 15:52:55,232 [  32232]   FINE - #o.j.j.i.Builder -       /Users/stepan.vavra/Repos/other/micronaut-test-slow-compilation/src/main/java/com/example/MyService.java
2022-05-25 15:52:55,233 [  32233]   FINE - #o.j.j.i.Builder -    Affected Files:
2022-05-25 15:52:55,233 [  32233]   FINE - #o.j.j.i.Builder - End Of Differentiate Results.
2022-05-25 15:52:55,233 [  32233]   INFO - #o.j.j.i.Builder - Non-incremental mode: Marking demo.main and direct dependants for recompilation
```
and a full rebuild is triggered.

This is how a full rebuild looks like in IntelliJ:
![image](https://user-images.githubusercontent.com/883323/170278440-399d2a5c-730f-42a0-96e3-c00e91844257.png)

### Steps To Reproduce

Consider a simple demo app
```
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import jakarta.inject.Inject;

@Controller
public class DemoController {

    private final MyService myService;

    @Inject
    public DemoController(MyService myService) {
        this.myService = myService;
    }

    @Get("/message")
    String message() {
        return myService.hello("hello");
    }
}

```
with a service 
```
import jakarta.inject.Singleton;

@Singleton
class MyService {

    public String hello(String input) {
        // comment and uncomment next 2 lines to get a full rebuild
        return "foo".equals(input) ? "hello3" : "HELLO";
//        return "foo".equals(input.toLowerCase()) ? "hello3" : "HELLO";
    }
}

```
When the `MyService` is changed in a way that its bytecode significantly changes (i.e., it's not enough to change the string constants), that is to do for instance
```
return "foo".equals(input.toLowerCase()) ? "hello" : "HELLO";
```

Then when "Build" -> "Build module" is executed, IntelliJ marks the module for a full recompilation
```
Checking dependencies… [demo.main]
Marking demo.main and direct dependants for recompilation
```

### Environment Information

As mentioned above, this problem happens with Micronaut 2.5.13 and 3.4.4 
I tried IntelliJ 2022.1, 2021.3.3, 2021.3.2.
JDK 17 and 11 on Mac.

### Example Application

https://github.com/stepanv/micronaut-full-rebuild-sample-app

### Version

3.4.4

**Comment by graemerocher** [comment]
can you post a change that will trigger the issue

**Comment by stepanv** [comment]
Hi @graemerocher , thx for the quick response, not sure if I understand your question though.
I tried to describe the change that would trigger the issue above ^^ but to make it absolutely clear:

- this PR demonstrates changes in micronaut beans that cause a full recompilation: https://github.com/stepanv/micronaut-full-rebuild-sample-app/pull/1
- this PR demonstrates changes in micronaut beans that is IntelliJ able to compile incrementally: https://github.com/stepanv/micronaut-full-rebuild-sample-app/pull/2

**Comment by graemerocher** [comment]
ok, PS Micronaut 3.5 might help here

**Comment by stepanv** [comment]
I just tried `3.5.0` and it's still the same. :(
I need an advice though, shall we aim to enable incremental compilation OR to find out what is slowing down the full rebuild? In both cases, I believe it's Micronaut annotation processing that needs some tunning.
For the latter case, do you have a suggestion how to enable logging during the compilation to see where Micronaut is burning its time?

**Comment by graemerocher** [comment]
I tried enabling incremental compilation with your sample app but even that triggered a full rebuild of all beans for some reason, which will require further investigation.

**Comment by stepanv** [comment]
Great, I believe Micronaut should be able to support incremental compilation, especially for such simple app.

In the meantime, we were profiling the full rebuild of our (not publicly available) app and we discovered Micronaut annotation processing is extremely ineffective when processing beans with many overloaded methods (same name, different params). For this we will be creating a different ticket soon.

**Comment by graemerocher** [comment]
well it does support incremental compilation for most changes, and once I enabled most changes compiled incrementally. It looks like there is some cases that don't work which I would like to understand for sure

**Comment by stepanv** [comment]
For the record, renaming `visit` methods in our visitors to unique names improves the full rebuild speed significantly: https://github.com/micronaut-projects/micronaut-core/issues/7525

It would be great though, if Micronaut annotation processing was able to support the incremental compilation more. 

Is there anything I can help with (considering my limited micronaut knowledge) to support the case when a directly injected micronaut bean is changed (e.g., just a method body is changed) and the build works in an incremental way?

**Comment by graemerocher** [comment]
that already works

**Comment by graemerocher** [comment]
if I alter your project as follows:

```diff
diff --git a/build.gradle b/build.gradle
index 222ad92..05111cf 100644
--- a/build.gradle
+++ b/build.gradle
@@ -1,7 +1,6 @@
 plugins {
-    id 'java-library'
+    id "io.micronaut.library" version "3.4.0"
 }
-
 version = "0.1"
 group = "com.example"
 
@@ -9,11 +8,14 @@ repositories {
     mavenCentral()
 }
 
-dependencies {
-    annotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
-    annotationProcessor 'io.micronaut:micronaut-inject-java'
+micronaut {
+    processing {
+        incremental true
+        annotations "com.example.*"
+    }
+}
 
-    implementation platform("io.micronaut:micronaut-bom:$micronautVersion")
+dependencies {
     implementation platform("org.apache.logging.log4j:log4j-bom:$log4jVersion")
     implementation("io.micronaut:micronaut-http-client")
     implementation("io.micronaut:micronaut-runtime")
@@ -23,11 +25,7 @@ dependencies {
     implementation("org.apache.logging.log4j:log4j-api")
     implementation("org.apache.logging.log4j:log4j-slf4j-impl")
 
-    testAnnotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
-    testAnnotationProcessor "io.micronaut:micronaut-inject-java"
 
-    testImplementation platform("io.micronaut:micronaut-bom:$micronautVersion")
-    testImplementation platform("org.junit:junit-bom:$junitVersion")
     testImplementation 'io.micronaut.test:micronaut-test-core'
     testImplementation 'io.micronaut.test:micronaut-test-junit5'
     testImplementation 'org.junit.jupiter:junit-jupiter-api'
@@ -39,9 +37,6 @@ java {
     targetCompatibility = JavaVersion.toVersion("17")
 }
 
-compileJava.options.compilerArgs += '-parameters'
-compileTestJava.options.compilerArgs += '-parameters'
-
 test {
     useJUnitPlatform()
 }
diff --git a/gradle.properties b/gradle.properties
index 5eddeeb..acc3f2c 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -1,3 +1,3 @@
-micronautVersion=3.4.4
+micronautVersion=3.5.0
 junitVersion=5.8.2
 log4jVersion=2.17.2
```

And I change IntelliJ to delegate to Gradle for building (which is just as fast) then when I change just method bodies of any type in the project it incrementally compiles only that type

**Comment by stepanv** [comment]
You're right, Gradle is able to do incremental compilation. I do see
```
Compiling with JDK Java compiler API.
Note: Creating bean classes for 2 type elements
Incremental compilation of 7 classes completed in 0.29 secs.
Class dependency analysis for incremental compilation took 0.001 secs.
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 0.351 secs.
```

Unfortunately, IntelliJ has to do full recompilation
```
Checking dependencies… [demo.main]
Marking demo.main and direct dependants for recompilation
```

I always assumed delegating to Gradle is never just as fast as compiling with IntelliJ directly. Actually I always thought delegating to Gradle adds at least 5 and sometimes even 20 or more seconds for large multi-module codebases. With IntelliJ, to recompile few changed classes incrementally, it was always just a few milliseconds thing.
I can give it a try.

To close this issue, do I read it correctly, Micronaut doesn't aim to support IntelliJ incremental compilation?

**Comment by stepanv** [comment]
Sadly, :( I think I'm hitting this bug https://github.com/gradle/gradle/issues/13767 with Gradle 7.3.3
```
Note: Creating bean classes for 20 type elements
error: Unexpected error: Attempt to recreate a file for type com.appdynamics.$ContextFilter$Definition
error: Unexpected error: Attempt to recreate a file for type com.appdynamics.$ResultDiagnosticsProcessor$Definition
```
I enabled 
```
compileJava.options.fork = true
```
but that didn't help either. :(

I'm assuming you're not aware of anything else one could try to make it work? (Maybe to downgrade Gradle?)

**Comment by stepanv** [comment]
Nevermind, I upgraded Micronaut to 3.5.0 and now I'm getting
```
Created classpath snapshot for incremental compilation in 0.013 secs.
Full recompilation is required because the generated resource 'META-INF/spring-configuration-metadata.json in CLASS_OUTPUT' must have exactly one originating element, but had 6. Analysis took 0.036 secs.
```
I found https://github.com/micronaut-projects/micronaut-core/issues/4642 but that is probably unrelated.

I'm sorry for the comments storm. I'll try to dig deeper on my own further on.

**Comment by graemerocher** [comment]
ok, it seems that configuration properties have an incremental compilation issue. That is worth an issue report, in the meantime one option is to move the `@ConfigurationProperties` classes in your code base (6 of them) to a separate sub project so they don't trigger a recompile

**Comment by stepanv** [comment]
Thanks @graemerocher , that works perfectly!

Is the
```
Full recompilation is required because the generated resource 'META-INF/spring-configuration-metadata.json in CLASS_OUTPUT' must have exactly one originating element, but had 2. Analysis took 0.013 secs.
```
flaw of Micronaut or is it a Gradle thing? I have the reproducer ready so I'm ready to report it right away.

**Comment by graemerocher** [comment]
it is Micronaut, we will need to figure out how to produce Spring Configuration metadata (used to allow code completion of application.yml in IDEs) incrementally

**Comment by stepanv** [comment]
Gotcha, I created https://github.com/micronaut-projects/micronaut-core/issues/7534 to track that.

Thanks again for the prompt support!
