### ISSUE TITLE
A simple API native is not working with version 3.5.0

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-core#7505]
### Expected Behavior

Able to run the Docker native image of very simple Greeting API that includes the following dependencies: graalvm, jib, http-client and micrometer-prometheus.

### Actual Behaviour

I am able to build both JVM and Native Docker images. The JVM one works pretty well. On the other hand, the Native one builds and starts up fine. However, when I submit a POST request to the endpoint `/api/greeting`, it's returning
```
HTTP/1.1 404 Not Found
Content-Type: application/json

{"message":"Not Found","_links":{"self":{"href":"/api/greeting?name=Ivan","templated":false}},"_embedded":{"errors":[{"message":"Page Not Found"}]}}
```

### Steps To Reproduce

1. `git clone https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot.git`
2. `cd graalvm-quarkus-micronaut-springboot`
3. `git checkout upgrade-to-micronaut-3.5.x`
4. `./collect-native-jar-docker-size-times.sh micronaut-simple-api`
5. `docker run --rm --name micronaut-simple-api-native -p 9083:8080 ivanfranchin/micronaut-simple-api-native:1.0.0`
6. `curl -i "localhost:9083/api/greeting?name=Ivan"`

### Environment Information

- OS: Mac
- JDK: 11

### Example Application

https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/simple-api/micronaut-simple-api

### Version

3.5.0

**Comment by graemerocher** [comment]
Works when packaging locally with `./mvnw package -Pgraalvm -Dpackaging=native-image` so seems specific to the Maven  plugin and docker packaging

**Comment by graemerocher** [comment]
Thanks for the report!
