### ISSUE TITLE
Support of Gradle incremental compilation when having more that 1 @ConfigurationProperties annotated classes

### ISSUE THREAD

**Issue by stepanv** [micronaut-projects/micronaut-core#7534]
### Feature description

When having multiple `@ConfigurationProperties` annotated classes, as per an example app: https://github.com/stepanv/micronaut-full-rebuild-sample-app/tree/main/src/main/java/com/example 

with `micronaut.processing.incremental=true` enabled, the incremental compilation gets broken
```
Task ':compileJava' is not up-to-date because:
  Input property 'stableSources' file /Users/stepan.vavra/Repos/other/micronaut-test-slow-compilation/src/main/java/com/example/MyService.java has changed.
Created classpath snapshot for incremental compilation in 0.008 secs.

Full recompilation is required because the generated resource 'META-INF/spring-configuration-metadata.json in CLASS_OUTPUT' must have exactly one originating element, but had 2. Analysis took 0.013 secs.

```

It would be great if Micronaut was able to support incremental compilation even in such case.

As a workaround one can extract those annotated classes to a different gradle module where incremental compilation is not that needed (thx @graemerocher for that hint).

**Comment by graemerocher** [comment]
I sent a PR, to support this case if a `@ConfigurationProperties` bean is changed then it will re-run for all beans of that type, but will still be incremental

**Comment by aleksei-lissitsin-kodality** [comment]
I think the same problem is still present when having multiple classes annotated with `@Factory`, instead. Tested with Micronaut 3.7.4 / Gradle 7.5.1.
