### ISSUE TITLE
Overriding "core" package factory beans in app code does not work

### ISSUE THREAD

**Issue by vesavlad** [micronaut-projects/micronaut-core#7544]
### Expected Behavior

For example I want to override ```DatasourceFactory``` to add some custom behavior. With 3.4.3 the factory bean was overriding the default bean inside ```io.micronaut.sql:micronaut-jdbc-hikari``` with 3.5.0 this does not work anymore

### Actual Behaviour

Bean does not get overwritten regardless of what I do. In the system I see that I have to beans for ```DatasourceFactory``` class for different packages.

### Steps To Reproduce

see expected behavior for details

### Environment Information

- Operating system: Linux, Ubuntu 20.04
- Java version: 17

### Version

3.5.0, 3.5.1

**Comment by vesavlad** [comment]
Might be related to https://github.com/micronaut-projects/micronaut-core/pull/7537, will check fix on 3.5.1

**Comment by vesavlad** [comment]
Problem still present for 3.5.1

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue

**Comment by vesavlad** [comment]
@graemerocher sorry for delay, here you have it
[micronaut-project.zip](https://github.com/micronaut-projects/micronaut-core/files/8876150/micronaut-project.zip)


In this project I'm expecting that the behavior of 3.4.2 is kept: ```ro.vladvesa.exporter.core.jdbc.DatasourceFactory``` is replacing the default  ```DatasourceFactory```

**Comment by Lucas3oo** [comment]
Have you checked that the annotation processor is kicking in? For instance there shall be a "$DatasourceFactory$Definition.class" class in the build folder.

**Comment by Lucas3oo** [comment]
And have you tested annotate your own factory with 
@Replaces(factory = io.micronaut.configuration.jdbc.hikari.DatasourceFactory.class)

**Comment by ameet123** [comment]
I am still having this issue. the last version that works is 3.4.4 after that every single version fails to instantiate custom `HikariUrlDataSource` bean. I have tried the `@Replaces` annotation, but that does not work.
