### ISSUE TITLE
java.lang.ClassCastException thrown when sending a message to a RabbitMQ broker.

### ISSUE THREAD

**Issue by yakom** [micronaut-projects/micronaut-core#7545]
### Expected Behavior

a message should be sent to a RabbitMQ broker.

### Actual Behaviour

`java.lang.ClassCastException: class reactor.core.publisher.FluxOnErrorResume cannot be cast to class reactor.core.publisher.Mono (reactor.core.publisher.FluxOnErrorResume and reactor.core.publisher.Mono are in unnamed module of loader 'app')` gets thrown.

### Steps To Reproduce

i've created an example application to reproduce the exception.

### Environment Information

- OS: Fedora 34
- JDK: 17.0.3

### Example Application

https://github.com/yakom/bug-report-2

### Version

3.5.1

**Comment by graemerocher** [comment]
add `micronaut-reactor` to your classpath

**Comment by yakom** [comment]
that was it, thank you.
