### ISSUE TITLE
Bean injection fails on barebones app

### ISSUE THREAD

**Issue by adityasrini** [micronaut-projects/micronaut-core#755]
### Task List

- [X] Steps to reproduce provided
- [X] Stacktrace (if present) provided
- [X] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

I am unable to get a bean to get injected on the most barebones app created using the Micronaut cli.

### Steps to Reproduce

1. Run `sdk install Micronaut` to get the RC3 version of micronaut
2. Run `mn create-app my-app --features jdbc-hikari`
3. Create empty service class
4. Create controller class with service class as field. Use `@Controller("/")` path.
5. Create constructor for controller with service class instantiation (Repo has code example)
6. Create method with "hello" String return for a `@Get("/")` path 
6. Run app and hit `/` endpoint

### Expected Behaviour

The endpoint should show "hello"

### Actual Behaviour

An error is produced with the following text 
`{"message":"Internal Server Error: Failed to inject value for parameter [someService] of class: my.app.SomeController\n\nMessage: No bean of type [my.app.SomeService] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.\nPath Taken: new SomeController([SomeService someService])"}`

Full stack trace: https://gist.github.com/adityasrini/d0a76a716b8f793659951bdeb634ac2f

### Environment Information

- **Operating System**: macOS 10.14
- **Micronaut Version:** RC3
- **JDK Version:** 11
- **Gradle Version:** 4.10 (the problem persists with 5.0-milestone-1 as well)

### Example Application

https://github.com/adityasrini/my-app

**Comment by jeffbrown** [comment]
https://github.com/adityasrini/my-app/pull/1 fixes the problem.

**Comment by adityasrini** [comment]
Now doing the same for `DataSource dataSource` throws the error:
`{"message":"Internal Server Error: Failed to inject value for parameter [dataSource] of class: my.app.SomeService\n\nMessage: No bean of type [javax.sql.DataSource] exists. Ensure the class is declared a bean and if you are using Java or Kotlin make sure you have enabled annotation processing.\nPath Taken: new SomeController([SomeService someService]) --> new SomeService([DataSource dataSource])"}`

All I added was the field with a constructor in the SimpleService class. The lines are [here](https://github.com/adityasrini/my-app/blob/f0951b981c48e1e448a55b56d0147a4eb842b536/src/main/java/my/app/SomeService.java#L8-L12)
