### ISSUE TITLE
Property endpoints.all.path is concat with micronaut.server.context-path

### ISSUE THREAD

**Issue by weesftw** [micronaut-projects/micronaut-core#7552]
### Expected Behavior

It would be attractive to keep them on separate paths, as they are different contexts. Or have some variable that allows you to make this distinction because they are totally different routes.

Inside the processors package in the `management` module, in class [AbstractEndpointRouteBuilder](https://github.com/micronaut-projects/micronaut-core/blob/c23b826872bd4afa72d3267d1229b399e0d5e204/management/src/main/java/io/micronaut/management/endpoint/processors/AbstractEndpointRouteBuilder.java#L166) there is the `resolveUriByRouteId()` method returning `uriNamingStrategy.resolveUri()` which does the proper concatenation. If it makes sense for the Micronaut context, would allowing a configuration that changes this behavior for greater flexibility be interesting? I'm glad in conttribute.

### Actual Behaviour

Management endpoints such as `/health` would be available at the URI `localhost:9090/foo/fff/health` instead of `localhost:9090/fff/health`.

There is an [issue](https://github.com/micronaut-projects/micronaut-core/issues/2090) that has been closed similar to this issue, but with no apparent conclusion.

### Steps To Reproduce

Set this properties in application.yml:

```
micronaut.server.context-path=/foo
endpoints.all.path=/fff
```

### Environment Information

Ubuntu 22.04
Java 11

### Version

3.5.x

**Comment by agugan** [comment]
I am willing to pick this up. @graemerocher

**Comment by vexxuh** [comment]
I don't see a resolution to this issue. I have not worked on this project in a while so I don't mind grabbing this if @agugan has not worked on a resolution!

**Comment by graemerocher** [comment]
feel free

**Comment by ginaesps** [comment]
Hello! Is this issue already solved, or could I take it?

**Comment by graemerocher** [comment]
Sure go for it

**Comment by ginaesps** [comment]
I'm new in here and have read documentation. Where would you recommend me to start so I can get a better grasp of the issue?
And, is there a Slack/Discord or some other kind or community where I can ask for help?

**Comment by graemerocher** [comment]
there is a gitter/matrix community https://micronaut.io/2022/04/13/how-to-access-the-micronaut-gitter-community-from-the-element-matrix-client/

**Comment by bpstelios10** [comment]
👀

**Comment by bpstelios10** [comment]
hi @graemerocher. Regarding this issue, do we really want it? we had a discussion with @yawkat and we feel it is debatable.
One point is that since this is for management, it makes sense to be separate from the main application server. Also, it is more flexible this way. If a client wants to have the same `endpoints.all.path` and `micronaut.server.context-path` they can still do it.

**Comment by yawkat** [comment]
I'll close this for now since management is a separate server so the context path makes less sense for it. If someone can give a good use case for this change, I can be convinced otherwise.

**Comment by viniciusxyz** [comment]
@yawkat I'm out of the discussion, but I implemented this feature that was merged into [PR 10870](https://github.com/micronaut-projects/micronaut-core/pull/10870)

In my case, for example, this helps me maintain the same behavior I have in spring and facilitates the migration of applications. Currently, in the applications we work with here at the company, we separate the application and management port and allow our customers to configure the root path for each one of these ports separately

If you need any extra details please let me know
