### ISSUE TITLE
HttpClient regressions: response payload is no logger logged when TRACE enabled

### ISSUE THREAD

**Issue by stepanv** [micronaut-projects/micronaut-core#7572]
### Expected Behavior

The `DefaultHttpClient` is no longer logging the response payload.

Prior the @yawkat 's change https://github.com/micronaut-projects/micronaut-core/commit/18ef607c4c6ec276b2e0163f27cf4e28fce96b01 

when enabled trace logging in `http-client/src/test/resources/logback.xml` 
```
  <logger name="io.micronaut.http.client" level="TRACE" />
```
the Micronaut test `http-client/src/test/groovy/io/micronaut/http/client/HttpGetSpec.groovy` (and all the other tests or production code) used to log (for example when running `test get with @Client` test method)
```
14:52:16.273 [default-nioEventLoopGroup-1-2] DEBUG i.m.h.client.netty.DefaultHttpClient - Received response 200 from http://localhost:62676/get/queryParam?foo=a!b
...
14:52:16.273 [default-nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - Response Body
14:52:16.273 [default-nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - ----
14:52:16.273 [default-nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - a!b
14:52:16.273 [default-nioEventLoopGroup-1-2] TRACE i.m.h.client.netty.DefaultHttpClient - ----
... 
```

### Actual Behaviour

After that change, Micronaut skips logging the response payload completely:
```
15:00:18.681 [default-nioEventLoopGroup-1-10] DEBUG i.m.h.client.netty.DefaultHttpClient - Received response 200 from http://localhost:63089/get/queryParam?foo=a!b
15:00:18.681 [default-nioEventLoopGroup-1-10] TRACE i.m.h.client.netty.DefaultHttpClient - HTTP Client Streaming Response Received (200 OK) for Request: GET http://localhost:63089/get/queryParam?foo=a!b
15:00:18.681 [default-nioEventLoopGroup-1-10] TRACE i.m.h.client.netty.DefaultHttpClient - date: Mon, 13 Jun 2022 13:00:18 GMT
15:00:18.681 [default-nioEventLoopGroup-1-10] TRACE i.m.h.client.netty.DefaultHttpClient - Content-Type: application/json
15:00:18.681 [default-nioEventLoopGroup-1-10] TRACE i.m.h.client.netty.DefaultHttpClient - connection: close
15:00:18.681 [default-nioEventLoopGroup-1-10] TRACE i.m.h.client.netty.DefaultHttpClient - content-length: 3
15:00:18.681 [default-nioEventLoopGroup-1-10] TRACE i.m.h.client.netty.DefaultHttpClient - [id: 0x1563a4f3, L:/127.0.0.1:63094 - R:localhost/127.0.0.1:63089] CLOSE
```

I also noticed there is a new log statement `HTTP Client Streaming Response Received (200 OK)` which is there even when nothing is being streamed as far as a user can tell (using blocking client with `Controller` returning a non-reactive type).

### Steps To Reproduce

Execute `io.micronaut.http.client.HttpGetSpec#test get with @Client` test
with `TRACE` logging enabled.

### Version

3.5.1

**Comment by stepanv** [comment]
Do you guys have any "framework" that helps to set up test with some logging configuration on demand and assert what is being logged? 
If not I can contribute something.

**Comment by yawkat** [comment]
we do but it's not used extensively
