### ISSUE TITLE
SoftServiceLoader.load don't return all class in unit test in last 3.5.1

### ISSUE THREAD

**Issue by tchiotludo** [micronaut-projects/micronaut-core#7594]
### Actual Behaviour

I use `SoftServiceLoader.load` to get all `BeanIntrospectionReference.class` for the current classLoader 

https://github.com/kestra-io/kestra/blob/b55ac08ba9661b7803cfd7ac4116f4c93c9f29ec/core/src/main/java/io/kestra/core/plugins/PluginScanner.java#L90-L93

It works well in `3.4.1` but on `3.5.1` it return a subset of all classes only for unit test and I can't figured the reason why. The application is working well, only unit test failed. 

https://github.com/kestra-io/kestra/blob/develop/core/src/test/java/io/kestra/core/docs/DocumentationGeneratorTest.java

On this unit test class, there is unit test load with a special ClassLoader isolating class for a Jar files and it's working well, but I didn't work for main classLoader

### Steps To Reproduce

1. clone https://github.com/kestra-io/kestra
2. Change version in `gradle.properties` to 3.5.1 
3. Run unit test [here](https://github.com/kestra-io/kestra/blob/develop/core/src/test/java/io/kestra/core/docs/DocumentationGeneratorTest.java)
4. `returnDoc` failed on 3.5.1 and not on 3.4.1 

### Environment Information

- JDK: 11 
- OS: Linux / Github actions 

### Example Application

https://github.com/kestra-io/kestra/blob/develop/core/src/test/java/io/kestra/core/docs/DocumentationGeneratorTest.java

### Version

3.5.1

**Comment by yawkat** [comment]
This probably broke due to https://github.com/micronaut-projects/micronaut-core/commit/b404311ff45925eef3e5cc573401f6fe8de3ab6f

BeanIntrospectionReference isn't accessible through service loader anymore, but i think this might be wontfix because BeanIntrospectionReference is `@Internal`. What do you think @graemerocher ?

The machinery to access the new format is there for ServiceCollector, but not for the SoftServiceLoader.iterator method, which seems a bit odd to me.

**Comment by yawkat** [comment]
@tchiotludo please move to ServiceCollector for now if possible. i will fix SoftServiceLoader, but we may deprecate it eventually.

**Comment by tchiotludo** [comment]
Sorry, @yawkat, not really sure to catch where to start.

The service ServiceCollector you are talking is this one? 
```java 
        SoftServiceLoader.ServiceCollector<String> collectors = SoftServiceLoader.newCollector(
            BeanIntrospectionReference.class.getName(),
            s -> true,
            classLoader,
            s -> s
        );
```
I was looking at micronaut source, it's always `SoftServiceLoader.load(BeanIntrospectionReference.class, classLoader)` that is used everywhere.

**Comment by yawkat** [comment]
Actually you can still use SoftServiceLoader.load, just use collectAll instead of the iterator. The iterator is the problem, and we don't use that anymore for BeanIntrospectionReference.
