### ISSUE TITLE
StreamedFile with type of text/plain always downloaded as Transfer-Encoding: chunked

### ISSUE THREAD

**Issue by Ksnz** [micronaut-projects/micronaut-core#7623]
### Expected Behavior

The following code allow browser get lenght of attached content (content-lenght header is present)
```       return new StreamedFile(new FileInputStream(tempFile),
            MediaType.forFilename(filename),
            tempFile.lastModified(),
            tempFile.length())
                   .attach(filename);
```

### Actual Behaviour

If filename MediaType resolved as `text/plain` it will be downloaded with `Transfer-Encoding: chunked` header and no `content-lenght` header
Even 
```
micronaut:
  server:
    netty:
      chunked-supported: false
```
has no effect

### Steps To Reproduce

Run the example app
Open in google chrome
```
http://localhost:8080/download/foo.mp4
```
and
```
http://localhost:8080/download/foo.txt
```
First one will show download estimate, second one won't.
First one will have a `content-lenght` header, second one won't

I can't reproduce it via curl, it may depends on request headers send by browser.

### Possible workaround
Use `MediaType.ALL` as  `StreamedFile` constructor param

### Environment Information

Google Chrome Version 103.0.5060.53 (Official Build) (64-bit)

### Example Application

https://github.com/Ksnz/demo

### Version

3.5.2

**Comment by yawkat** [comment]
I can reproduce this, but this is actually a feature we want to keep around. For text content types, we enable compression by default, which requires chunked transport. If you don't want this, you can disable compression, or even register your own `HttpCompressionStrategy`.

**Comment by yevmel** [comment]
Hi @yawkat ,

a custom `HttpCompressionStrategy` doesn't seem to help 🤷
Here is the implementation:

    @Primary
    @Singleton
    public class AlwaysNoHttpCompressionStrategy implements HttpCompressionStrategy {
        
        @Override
        public boolean shouldCompress(final HttpResponse response) {
            return false;
        }
    }

i have a `chunked-supported: false` in my application.yml too.

my use case is slightly different from @Ksnz. I return a InputStream in my controller with Content-Disposition set to attachment:

    return HttpResponse
       .ok(inputStream)
       .header(HttpHeaders.CONTENT_LENGTH, Long.toString(contentLength))
       .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=test..png"); 

there is still a `Transfer-Encoding: chunked` when i run curl.

**Comment by yawkat** [comment]
a stream is always chunked no matter what you do
