### ISSUE TITLE
Performance loss due to HTTP/1.1 connections not being persistent by default

### ISSUE THREAD

**Issue by jespersm** [micronaut-projects/micronaut-core#763]
### Steps to Reproduce

1. Create a controller which just returns a String
2. Call it using an HTTP 1.1. client
3. Check that it keeps the connection open by default (i.e. without specifying "Connection: keep-alive")

### Expected Behaviour

From the HTTP 1.1 spec:

>    A significant difference between HTTP/1.1 and earlier versions of
>    HTTP is that persistent connections are the default behavior of any
>    HTTP connection. [...]

Micronaut is expected to keep the connection open after sending the response body, if the client doesn't specifically requests the opposite.

### Actual Behaviour

While Micronaut HTTP Server honors the explicit "Connection: keep-alive"-header and will maintain a persistent connection, it defaults to closing the socket connection (and dutifully sets "Connection: close" in the response headers). This is without regard of the protocol version in use.

While this is is spec. compliant, performance will suffer for those clients who do not specify "Connection: keep-alive".

One such client is the bombardier testing tool (https://github.com/codesenberg/bombardier), and likely other clients written in Go, using the standard Go HTTP client library.

### Environment Information

- **Operating System**: macOS, but platform neutral
- **Micronaut Version:** 1.0.0.RC3
- **JDK Version:** 1.8.0_181

### Example Application

Test and patch is underway.

**Comment by jeffbrown** [comment]
https://github.com/micronaut-projects/micronaut-core/pull/764
