### ISSUE TITLE
Remove manage-reactor as it is in the BOM

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-core#7638]
### Issue description

Once https://github.com/micronaut-projects/micronaut-reactor/pull/201 is merged and 2.3.0 is out, we should add the BOM to the dependency catalog, and remove `managed-reactor`

Check the TOML keeps the same names with `./gradlew pAPTBR`

**Comment by sdelamo** [comment]
I released Micronaut Reactor 2.3.0

**Comment by timyates** [comment]
Removal of managed-reactor has to be done in 4.0 (see PR)
