### ISSUE TITLE
Remove Neo4j managed dependencies

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-core#7639]
### Issue description

managed-neo4j and managed-neo4j-bolt are exported by the BOM, and can be removed from the build for 4.0.0

Check the TOML keeps the same names with ./gradlew pAPTBR

**Comment by sdelamo** [comment]
I released Micronaut Neo4J 5.1.0

**Comment by timyates** [comment]
This is already done when we pulled out the platform BOM
