### ISSUE TITLE
Enabling HTTP/2 push causes unconditional stream error

### ISSUE THREAD

**Issue by sgammon** [micronaut-projects/micronaut-core#7677]
### Expected Behavior

Without any actual invocation of push code (i.e. just enabling the setting), I would expect that the server would start and behave as normal

### Actual Behaviour

After enabling HTTP/2 push with `micronaut.server.netty.http2.push-enabled`, HTTP/2 streams are no longer closed cleanly (`curl`'s term):
```
*   Trying 127.0.0.1:8443...
* Connected to localhost (127.0.0.1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=localhost
*  start date: Jul 12 23:25:16 2021 GMT
*  expire date: Dec 31 23:59:59 9999 GMT
*  issuer: CN=localhost
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x12180ca00)
> GET / HTTP/2
> Host: localhost:8443
> user-agent: curl/7.79.1
> accept: */*
> 
* TLSv1.2 (IN), TLS alert, close notify (256):
* HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
* stopped the pause stream!
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, close notify (256):
curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
```

### Steps To Reproduce

1. Create a totally fresh Micronaut project at [launch.micronaut.io](https://launch.micronaut.io)
2. Build and run with `./gradlew run`
3. Observe working call: `curl -vvv http://localhost:8080/` (yields Not Found but that's fine)
4. Amend configuration by adding the snippet below:
```yaml
micronaut:
  server:
    ssl:
      port: 8443
      enabled: true
      build-self-signed: true
    http-version: 2.0
```
5. Observe working call: `curl -vvv https://localhost:8443/`
6. Amend configuration by adding the snippet below:
```patch
micronaut:
  server:
    ssl:
      port: 8443
      enabled: true
      build-self-signed: true
    http-version: 2.0
+   netty:
+     http2:
+       push-enabled: true
```
7. Observe broken call: `curl -vvv https://localhost:8443/`, which now yields the above error

Note: In some environments, at Step 4, you may need to add Bouncycastle to avoid a `NoClassDefFoundError`, which you can do with:
```patch
dependencies {
+    runtimeOnly("org.bouncycastle:bcprov-jdk18on:1.71")
+    runtimeOnly("org.bouncycastle:bcpkix-jdk18on:1.71")
}
```

### Environment Information

Observed on:
- macOS Monterey 12.4
- JDK Version: 17
- JDK Variant: Zulu

Output of `java -version`:
```
openjdk version "17.0.3" 2022-04-19 LTS
OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode, sharing)
```

### Example Application

https://github.com/sgammon/http2repro

### Version

3.5.3 (latest)

**Comment by sgammon** [comment]
this behavior seems to happen even if you set the property to `false`, fwiw

**Comment by sgammon** [comment]
i haven't yet been able to trace down where the reset is happening, or really even where `push-enabled` could be triggering different functionality at server startup. in case they could help someone else, here are some packet captures and other observations.

[`captures.zip`](https://github.com/micronaut-projects/micronaut-core/files/9099249/captures.zip):
- `http2-nopush.pcapng`: Push disabled, regular HTTP/2 request/response cycle (HTTP200)
- `http2-push-err.pcapng`: Push enabled, stream reset error
- `http2-combined.pcapng`: Combined with both (`nopush`, then `push-err`)

Logging samples:
- [tracelogs.txt](https://github.com/micronaut-projects/micronaut-core/files/9099279/tracelogs.txt): `TRACE` logging (full run) when `pushEnabled` is active -- doesn't show much

**Comment by yawkat** [comment]
`push-enabled: true` makes no sense for server http2 SETTINGS. we should remove that setting

**Comment by sgammon** [comment]
@yawkat sounds good. reading the code, it seems like `PushEnabledHttpRequest` is all that is needed to opt-in for support -- is that the case?

**Comment by yawkat** [comment]
sure. though it's more accurate to say that support does not need to be "enabled" at all – as long as the client does not disable it in its SETTINGS frame, you can just use it from the server. It does not require any setup.

**Comment by sgammon** [comment]
@yawkat gotcha, makes sense. thank you 👍🏻
