### ISSUE TITLE
Tests fail after upgrade to 3.5.2 @Inject is not working

### ISSUE THREAD

**Issue by jesperancinha** [micronaut-projects/micronaut-core#7684]
### Expected Behavior

I expect this test to work as it did before:

```kotlin
@Testcontainers
@MicronautTest
@ExperimentalCoroutinesApi
class ReceiptTest @Inject constructor(
    private val receiptRepository: ReceiptRepository,
    private val ticketReservationRepository: TicketReservationRepository
) : AbstractBuyOddYuccaConcertContainerTest() {
```

### Actual Behaviour

When running this and all other examples in my project, it says now that it cannot inject the repositories:

```java
org.junit.jupiter.api.extension.ParameterResolutionException: 
No ParameterResolver registered for parameter 
[org.jesperancinha.concert.buy.oyc.commons.domain.ReceiptRepository arg0] 
in constructor [public org.jesperancinha.concert.buy.oyc.commons.domain.ReceiptTest(
org.jesperancinha.concert.buy.oyc.commons.domain.ReceiptRepository,
org.jesperancinha.concert.buy.oyc.commons.domain.TicketReservationRepository)].
```

### Steps To Reproduce

Just running the tests on the root will generate the error

### Environment Information

- JDK 17
- MAC-OS or Linux

### Example Application

https://github.com/jesperancinha/buy-odd-yucca-concert

### Version

3.5.2

**Comment by jesperancinha** [comment]
You can find a build run example here: https://github.com/jesperancinha/buy-odd-yucca-concert/runs/7145768256?check_suite_focus=true

**Comment by graemerocher** [comment]
@dstepanov could you take a look at this?

**Comment by dstepanov** [comment]
I need some maven experts 🧚 @alvarosanchez 

After checking out https://github.com/jesperancinha/buy-odd-yucca-concert/pull/425
I see `buy-oyc-commons` is not generating any service entities for the main (for the test it does) I suspect it might be because of `micronaut-data-processor` which depends on core `3.4.3`

Any idea what to do?

**Comment by dstepanov** [comment]
This helps:
```
        <micronaut.version>3.5.3</micronaut.version>
        <micronaut.data.processor>3.5.0</micronaut.data.processor>
 ```
 
There is one test that fails on some cryptic error:
```
Suppressed: java.lang.NoClassDefFoundError: Could not initialize class org.jesperancinha.concert.buy.oyc.api.client.ReceiptTest
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by jesperancinha** [comment]
@dstepanov , thanks! It works now 👍 . This latest version of the data processor fixes it for me.

**Comment by dstepanov** [comment]
BTW Why aren't you using Redis clients?

**Comment by jesperancinha** [comment]
I will have a look. I only used the first thing I knew about Redis for this project.  This could potentially be a great improvement. Thanks for the tip!
