### ISSUE TITLE
Reactive bean validation doesn't work

### ISSUE THREAD

**Issue by luckyswede** [micronaut-projects/micronaut-core#769]
Bean validation in routes works well in the sync case, eg
```
@Post("/sync/{id}")
HttpResponse createSync(String id, @Body @Valid SomePojo pojo) {
    ...
}
```

but it doesn't work in the async case:
```
@Post("/async/{id}")
Single<HttpResponse> createAsync(String id, @Body @Valid Single<SomePojo> pojoProducer) {
    ...
}
```
Thanks / Jonas

**Comment by graemerocher** [comment]
Whilst the bug is valid, note that simply writing `@Body @Valid SomePojo pojoProducer` will resolve it, Micronaut will not block when using this syntax. Instead it will read the request body in a non-blocking manner and only execute the method once a `SomePojo` object can be materialised.

**Comment by luckyswede** [comment]
Ok, makes sense, and the `Single<>` response type makes the method invocation run on the event loop I guess.

**Comment by graemerocher** [comment]
Yes that is correct

**Comment by kamilgregorczyk** [comment]
If I'm correct, it is totally fine to consume pojo in a "blocking" way as micronaut will not block requests, right?

+ Is it possible to manually run validation with `ExecutableValidator.class` or something similar?

**Comment by jameskleeh** [comment]
This has been implemented in the Micronaut validation library that will be part of the 1.2 release
