### ISSUE TITLE
Create test module to verify simple native image generation and execution

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7691]
The goal is to catch errors such as https://github.com/micronaut-projects/micronaut-core/issues/7671 earlier. 

I think we could add a submodule which use the [Gradle graalvm plugin](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#testing-support) to run a [Junit native test via  `./gradlew nativeTest`](https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#testing-support)

I think we could do `check` depends on `nativeTest` for that module. 

A test such as: 

```java
package com.example;

import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import java.util.Collections;
import java.util.Map;

@Controller
public class HomeController {

    @Get
    Map<String, Object> index() {
           return Collections.singletonMap("message", "Hello World");
    }
}

```

```java
package com.example;

import io.micronaut.http.client.HttpClient;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

@MicronautTest
class HomeControllerTest {

    @Inject
    @Client("/")
    HttpClient httpClient;

    @Test
    void helloWorld() {
        assertEquals("Hello World",
                httpClient.toBlocking().retrieve("/", Map.class).get("message"));
    }
}
```

should help us catch most issues. 

It would be good to create such a module, branching of [the commit which fixed native image](https://github.com/micronaut-projects/micronaut-core/commit/204e4d1de554e5821a462b46f5dc88565e5ce35b) and see if the module test fails.

**Comment by timyates** [comment]
Thinking about how we would run this on CI where we only have GraalVM for specific builds.

We would somehow need to detect that we're running on Graal, and only then add the module into the check chain of tasks 🤔

**Comment by yawkat** [comment]
with the nativeTest approach, couldnt we just adjust the actions that have graal to also execute nativeTest, not just test?

**Comment by timyates** [comment]
This is going to have to go into 4.0.0, as the shaded Caffeine in 3.8.x is causing me issues with native compilation

**Comment by timyates** [comment]
Closed by https://github.com/micronaut-projects/micronaut-core/pull/8280
