### ISSUE TITLE
DefaultHttpClient no way to turn off compression

### ISSUE THREAD

**Issue by rjaros87** [micronaut-projects/micronaut-core#7711]
### Issue description

Hi,

I'm trying to handle 100s of simultaneously websocket connections sending binary content.
During CPU profiling I'm observing a lot of  CPU usage on `deflate` calls that harm performance of my service in dockerized environment.
Since data are being sent on the same Kubernetes cluster, network bandwidth is bigger than available CPUs and in such case burning CPU cycles on compression and decompression is a huge bottleneck.

What I've found during debugging is that the following line sets the compression level with a default value `6`: https://github.com/micronaut-projects/micronaut-core/blob/3.5.x/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L952 - it uses a default instance of `WebSocketClientCompressionHandler` which in turn sets default value for compression (and for other parameters, too).

This has been incorporated in this PR: #6487

I don't see any way to turn off this behaviour or set compression level to 0 (no compression) for http client. Is there any way to enforce no compression? or whether an enhancement request required to let it be configurable (in a similar way as it is for server: `micronaut.server.netty.compression-level`)?

**Comment by graemerocher** [comment]
Seems a reasonable thing to want to configure

**Comment by bawarren44** [comment]
I am new to Micronaut but I would like to take a shot at this
