### ISSUE TITLE
Unable to pass arguments to Lambda Function in Graal

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-core#772]
When running lambda functions using Graal native image we could do something like this:
```
$ echo '{"memberStateCode":"es", "vatNumber":"B99286353"}' | ./vies-vat-validator
```

But not, while upgrading this guide http://guides.micronaut.io/micronaut-function-aws-lambda/guide/index.html#graal to use Micronaut 1.0.0 I don't know if it's possible to pass those arguments and how to do it.

If I try to start the docker container exposing the ports, for example, to be able to execute a curl, the application doesn't start:
```
$ docker run -p 8080:8080 vies-vat-validator
Error executing function (Use -x for more information): Error decoding JSON stream for type [request]: No content to map due to end-of-input
 at [Source: (BufferedInputStream); line: 1, column: 0]
```

I've pushed the docker image to docker hub. To pull it and do some tests:
```
$ docker pull ilopmar/vies-vat-validator
```

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.0.0
- **JDK Version:** 1.8

**Comment by graemerocher** [comment]
With the following diff works as expected https://gist.github.com/graemerocher/2637fe74e6191ad8005db99e43ef16c4
