### ISSUE TITLE
Cloud Platform detection fails for Fargate when provisioner decides to run on bare-metal

### ISSUE THREAD

**Issue by jaecktec** [micronaut-projects/micronaut-core#7740]
### Expected Behavior

When running Micronaut in AWS Fargate
and Fargate choses an EC2 bare metal instance (e.g. [M5D](https://aws.amazon.com/ec2/instance-types/))

Micronaut still detects, that it's running in the cloud. 

### Actual Behaviour

since `/sys/devices/virtual/dmi/id/bios_vendor` is empty, micronaut won't detect that it's running in the cloud

### Steps To Reproduce

That's a tricky one, since you are a victim to the fargate-provisioner. 

Create a MN Application, host it in fargate, restart a few times and if you get lucky it prints: 

```
Established active environments: []
```

You can simulate this by providing an empty file in `/sys/devices/virtual/dmi/id/bios_vendor`

### Version

3.5.3

**Comment by graemerocher** [comment]
The solution is to explicitly set the environment for your deployment

**Comment by jaecktec** [comment]
I know. But would you consider this a bug? bare-metal instances are also EC2, therefore the detection as implemented as in 
[DefaultEnvironment](https://github.com/micronaut-projects/micronaut-core/blob/20e29a27638e2c67e5a070b9ebd618c94fe5ed5b/inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java#L956) is not working for these cases

**Comment by jaecktec** [comment]
using the environment variable as mentioned in [this stackoverflow](https://stackoverflow.com/a/54241697) would also reduce the complexity of the code (detecting on which OS we're running)

**Comment by alvarosanchez** [comment]
We never supported officially Fargate, so if anything, this looks like an improvement to me.

Is the `AWS_EXECUTION_ENV` variable officially documented somewhere? I couldn't find it.

**Comment by jaecktec** [comment]
Me neither, just for the [lambda use case](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html)

**Comment by alvarosanchez** [comment]
Then I don't think we should use that. Pinging @msailes just in case.

Anyway, the workaround described by @graemerocher would be the most efficient option.

**Comment by jaecktec** [comment]
yes, we've used that for now. I will research a bit to see if `AWS_EXECUTION_ENV` is documented in relation to fargate somewhere. Should we keep this issue open and treat it as a feature or should I open a new one?

**Comment by msailes** [comment]
I think the way to do this would be with the ECS meta data service
 https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-v4-fargate.html

It has a launch type.

But I appreciate you might not want to make network calls for this action.

**Comment by alvarosanchez** [comment]
Yeah, we used to query the Metadata Service at the beginning of times, but have switched to other ways where possible.

@jaecktec we can keep this issue

**Comment by jaecktec** [comment]
I've found this one in the java sdk javadoc:

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/SdkSystemSetting.html#AWS_EXECUTION_ENV

**Comment by alvarosanchez** [comment]
"... automatically set **in certain environments**..." still brings doubts.

Also, bear in mind that the [future direction is to disable environment detection by default](https://github.com/micronaut-projects/micronaut-core/issues/7758).

**Comment by jaecktec** [comment]
hmm ok. I guess adding the profile would be enough. If it was disabled I'd be also happy :)
