### ISSUE TITLE
Management Test App fails for GraalVM 22.2

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#7774]
### Issue description

see: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2789452427
see: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2789642886

**Comment by timyates** [comment]
So `"system.load.average.1m"` is the missing metric name...

Looking for it's removal

**Comment by timyates** [comment]
So this was fixed in 22.2 here: https://github.com/oracle/graal/issues/3289

Which is why we now see the metric (as micrometer can now get the value)

**Comment by timyates** [comment]
https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/merge_requests/7
