### ISSUE TITLE
failing CI

### ISSUE THREAD

**Issue by DanielRuf** [micronaut-projects/micronaut-core#778]
The CI build is currently failing: https://travis-ci.org/micronaut-projects/micronaut-core/builds/445918707

**Comment by graemerocher** [comment]
Thanks yes, we have some Kafka tests that fail intermittently due to the limited amount of memory available on Travis.. most likely we will move these tests to a separate `micronaut-kafka` project to reduce the memory requirements for the build

**Comment by DanielRuf** [comment]
Or could these tests be splitted into several? Maybe CircleCI works better (not sure regarding the resources).

Or maybe switch to sudo builds using `sudo: required`: https://docs.travis-ci.com/user/reference/overview/

**Comment by DanielRuf** [comment]
How much memory is needed? Would like to provide a PR to test if the sudo builds would work.

**Comment by graemerocher** [comment]
hard to measure. The issue occurs with the embedded Kafka server which occupies a lot of memory

CircleCI has more memory constraints than Travis

**Comment by DanielRuf** [comment]
So we already have this:

```
dist: trusty
sudo: required
```

**Comment by jameskleeh** [comment]
This will be resolved when https://github.com/micronaut-projects/micronaut-core/issues/956 is completed
