### ISSUE TITLE
PR build failed

### ISSUE THREAD

**Issue by JoeBeeContrast** [micronaut-projects/micronaut-core#7802]
### Issue description

hello
Can someone take a look at the build for PR https://github.com/micronaut-projects/micronaut-core/pull/7577 the build failed due to a sonarqube token issue. But I'm not able to rerun the build. And so cannot progress the PR

**Comment by graemerocher** [comment]
you can ignore the sonarqube build for the moment. But the PR is still failing due to binary incompatible changes
