### ISSUE TITLE
Tests in github.com/micronaut-graal-tests repositories fail

### ISSUE THREAD

**Issue by debuglevel** [micronaut-projects/micronaut-core#7806]
### Expected Behavior

The test in <https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/tree/3.5.x_h2/src/test/java/example> should work with `./gradlew nativeTest` (or, for a start, with `./gradlew test`).

This is might be the case for most repositories.

### Actual Behaviour

The tests fail due to `javax` dependencies et cetera. They seem untouched for quite some time.

I understand that the actual tests are done via <https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/blob/3.5.x-stable/test-data-jpa-h2.sh>. But this is still odd, as it complicates local testing and reproducing issues. It would be nice if https://github.com/micronaut-graal-tests could be some sort of knowledge base to look up if one has got some `native-image` issue.

### Steps To Reproduce

Assuming GraalVM stuff is installed:

```
git clone https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal.git
git switch 3.5.x_h2 
./gradlew nativeTest
```

### Version

3.5.5-SNAPSHOT

**Comment by sdelamo** [comment]
please note that the way we test those repositories is by [building a native image of the app](https://github.com/micronaut-graal-tests/micronaut-data-jpa-graal/blob/3.6.x_h2/build-native-image.sh), [starting the app and doing a curl request](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/blob/3.6.x-stable/test-data-jdbc-h2.sh). 

but we should fix the test. However we don't really use them
