### ISSUE TITLE
 No embedded container found when micronaut-runtime added transitively 

### ISSUE THREAD

**Issue by subash89** [micronaut-projects/micronaut-core#7819]
### Expected Behavior

I have a java maven library which has micronaut Application(main method) and pretty much everything. And I use that library as a maven dependency in a separate application project. When I try to run mvn mn:run 

10:52:26.046 [main] INFO  io.micronaut.runtime.Micronaut - No embedded container found. Running as CLI application

This only works if I directly add micronaut-runtime module in the current project pom. Even though micronaut-runtime comes transitively from other java library. 

Why this is happening ? 

### Environment Information

JDK 11
Micronaut 3.5.1

### Version

3.5.1

**Comment by yawkat** [comment]
it just means there's no http server or similar present in the micronaut application. it's not an error.

**Comment by subash89** [comment]
@yawkat It works all well when I add micronaut-runtime dependency to my pom.xml.  But issue is when I don't have any micronaut-* dependencies in my pom.xml but only one dependency  

**project-y pom.xml** 
Here I have Micronaut Main method, all micronaut dependencies etc.

**project-x pom.xml** 
This project use project-y and provide the jaxrs resource class. 

```
    <dependency>
      <groupId>com.myapp.core</groupId>
      <artifactId>project-y</artifactId>
    </dependency>
```

And inside this project I do mvn mn:run. And it complains no container.

**Comment by yawkat** [comment]
@alvarosanchez think this might be related to maven? i would think the classpath for both setups would be basically the same.

**Comment by subash89** [comment]
@yawkat  found something else also related. Even after adding direct dependency I can start micronaut. 
There's a @Singleton class in project-y. And if I try to inject that in my project-x's jaxrs resource class, it will complain  

```
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [org.example.ExampleService] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2778)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1594)
	at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:66)
	at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2055)
	... 29 common frames omitted
```

I think for same reason, things in a different project/dependency, it does not like it. Even singletons.

Is there any set of dependencies that micronaut does not like other projects to hold  ? If so then I can try excluding all those from external dependency to see i f it work.

**Comment by alvarosanchez** [comment]
@subash89 the setup you are trying is not really supported. The Micronaut Maven Plugin has only been tested when added to Micronaut applications.

That said, if you share a reproducible example, I can take a look

**Comment by subash89** [comment]
@alvarosanchez Thanks for the response. I am preparing a project to recreate this easily. Meanwhile can you tell me whether we must use micronaut maven plugin ? Is there any other way like a creating a shaded jar and run it like java -jar? 
(I tried that too, it complains about some invalid signature of the manifest of the jar).

**Comment by alvarosanchez** [comment]
Running a shaded jar works, but again, this is only supported when using the Micronaut Maven Plugin

**Comment by subash89** [comment]
Can you clarify a bit ? My understanding was, micronaut maven plugin does not need a shade plugin.  Is there any example project I can refer to

**Comment by subash89** [comment]
[projecty.zip](https://github.com/micronaut-projects/micronaut-core/files/9262714/projecty.zip)
[projectx.zip](https://github.com/micronaut-projects/micronaut-core/files/9262715/projectx.zip)

Added two projects as in the above scenario. 
1. Build project x.(mvn clean install)
2. Go inside projectx and  do mvn mn:run 
3. Then curl -i  --header "AppId: 123"   http://localhost:8080/hello 

This will throw that error. Basically project x trying to use a Singleton defined in project y. 
This is necessary if you want to maintain a set of common functionalities as a library and distribute it to teams who want to use them with in an org.
