### ISSUE TITLE
Secured annotation isn't applied to HttpServerFilter

### ISSUE THREAD

**Issue by ThraaxSession** [micronaut-projects/micronaut-core#7872]
### Expected Behavior

A HttpServerFilter class can be annotated with "@Secured".

### Actual Behaviour

The annotation will be ignored

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/3085830/184451460-59ea8915-f923-4544-99ac-9097b2c25690.png)

### Environment Information

GraalVM 22.2.0.r11

### Version

3.6.0

**Comment by jameskleeh** [comment]
What gave you the impression this should work?

**Comment by ThraaxSession** [comment]
Hi @jameskleeh 
I see HttpServerFilter like a superset on HTTP requests over HTTP Controller. Why it shouldn't be possible to secure this superset? A controller might be more specific endpoints. But the the filters can handle the same as far I figure out. Especially when I need more control over the request. That's why I think it should be possible to secure HttpServerFilter. If `Secured` annotation is Controller specific, it would be at least useful to have possibility to extend the `Filter` annotation.

**Comment by ThraaxSession** [comment]
@jameskleeh what is the alternative for now? I need this annotation. How can I manually check it?

**Comment by jameskleeh** [comment]
Ensure it runs after the secured one and get the authentication from the
request

**Comment by ThraaxSession** [comment]
@jameskleeh any example?

**Comment by ThraaxSession** [comment]
Hi @jameskleeh the latest release of micronaut (I guess) security provides for the request new parameters. A first help to solve the authentication issue. Might be to add "request.isAuthenticated". The annotation is still anyway a smoother solution.

**Comment by ThraaxSession** [comment]
@jameskleeh any update on this?

**Comment by yawkat** [comment]
james doesn't work on micronaut full-time anymore.

if you want to check for authentication, you can add your filter after the `SecurityFilter`, and check the `SecurityFilter.AUTHENTICATION` attribute. I don't think we should implement the annotation for filters, it'd be like filters for filters, which is just weird.

**Comment by jameskleeh** [comment]
@yawkat Agreed this should be closed imo
