### ISSUE TITLE
@Value not expanded correctly in Spock test

### ISSUE THREAD

**Issue by marcpa00** [micronaut-projects/micronaut-core#788]
### Task List

- [x ] Steps to reproduce provided
- [x ] Stacktrace (if present) provided
- [x ] Example that reproduces the problem uploaded to Github
- [x ] Full description of the issue provided (see below)

### Steps to Reproduce

1. clone my fork of micronaut-examples : `git clone https://github.com/marcpa00/micronaut-examples`
2. cd into project : `cd micronaut-examples`
3. switch to `marcpa00-value-annotation-groovy` branch : `git checkout marcpa00-value-annotation-groovy`
3. run the test for java hello world and see that they pass : `(cd hello-world-java; ./gradlew test)`
4. run the test for groovy hello world and see that they fail : `(cd hello-world-groovy; ./gradlew test)`
5. look at the Spock test `hello-world-groovy/src/test/groovy/example/HelloControllerSpec.groovy` : the field `greeting` is annotated with a `@Value` but the property value from the yml file is not picked up.

### Expected Behaviour

Both project should have their test successful : the property value from the application-test.yml file for `greeting` should be picked up by the code under test *and* by the spock test.

### Actual Behaviour

In the spock test (groovy project), the `@Value` annotation does not have any effect, the annotated variable has the value it was initialized with instead of being overwritten by the value of the `greeting` property from `application-test.yml` file. 

Similar code in the JUnit test under the java project behaves as expected.

### Environment Information

- **Operating System**: macOS High Sierra Version 10.13.6 (17G65)
- **Micronaut Version:** 1.0.0
- **JDK Version:** 1.8.0_161-b12

### Example Application

See my fork of micronaut-examples (https://github.com/marcpa00/micronaut-examples), branch `marcpa00-value-annotation-groovy`.

**Comment by graemerocher** [comment]
Currently if you use raw spock then there is nothing that will inject the `@Value` setup for you. If you want this feature consider using `@MicronautTest`. See https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html#spock
