### ISSUE TITLE
JWT Cookie path not set, and not possible to configure

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-core#798]
When configuring `micronaut.security.token.jwt.cookie.enabled=true` to enable `JwtCookieLoginHandler` the Set-Cookie header does not include a path so the browser uses the path of the login controller "/login". The result is that cookies are sent from the browser for paths starting with /login but not for others paths. I could not find a way to configure cookie path for the JWT cookie.

 https://github.com/micronaut-projects/micronaut-core/blob/48bb8fc7ca76b2c5945f51b62ddc90eb38614656/security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieLoginHandler.java#L63

### Steps to Reproduce

1. Configure `micronaut.security.token.jwt.cookie.enabled: true`
2. Login with browser or curl (/login)
3. Check the Set-Cookie response header, it does not contain Path=
4. Do another request, for example to / or /foo
5. Cookie header is not included in the request
6. Do a new request to /login
7. The Cookie header is now included in the request

### Expected Behaviour

I expected the default cookie path to be / or at least possible to configure the wanted path.

### Actual Behaviour

Cookie path is not sent to the browser so it uses the request path which is /login.
No way to configure cookie path.

### Environment Information

- **Operating System**: MacOS 10.14
- **Micronaut Version:** 1.0.0
- **JDK Version:** 1.8.0_162-b12

### Example Application

- TODO: link to github repository with example that reproduces the issue

**Comment by graemerocher** [comment]
Thanks for the PR
