### ISSUE TITLE
BeanLocator's `findBean(Class<T>, Qualifier<T>)` intermittently not finding `HttpContentSubscriberFactory` with qualifier

### ISSUE THREAD

**Issue by racevedoo** [micronaut-projects/micronaut-core#8011]
### Expected Behavior

Should find the bean with the qualifier.

### Actual Behaviour

Returns empty optional.

More details:
I observed this happening in `DefaultHttpContentProcessorResolver`, specifically [here](https://github.com/micronaut-projects/micronaut-core/blob/50d40203e886ab9c3ab01413b91d2f57fd20c1d9/http-server-netty/src/main/java/io/micronaut/http/server/netty/DefaultHttpContentProcessorResolver.java). This happens under some strange circumstances I cannot replicate locally. 

Good news is that I managed to run a remote debugger in a production instance that this issue happened and found that `beanLocator.getBeansOfType` returns the correct beans. I'm not sure if there is significant difference between the implementations, but the `Qualifier.reduce` method is called in the `getBeansOfType` call, but not in the `findBean`. Is this on purpose?

My guess is that there is some caching/race condition going on here. It's also worth noting that the end result when this error happens is that the applications returns 400 bad request, as the request body is not parsed properly into a `io.micronaut.json.tree.JsonNode`

### Environment Information

OS: Ubuntu 22.04
Java version: Eclipse Temurin 11

### Version

3.5.1

**Comment by racevedoo** [comment]
cc @yawkat this is the issue I mentioned on [gitter](https://gitter.im/micronautfw/questions?at=6321b3bc6837563d1cd2bd1f)

**Comment by graemerocher** [comment]
can you provde a reproducer?
