### ISSUE TITLE
Move to jakarta.validation annotations

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#8057]
### Feature description

It seems to me that it is time to completely switch to jakarta packages, because javax is now history

**Comment by altro3** [comment]
I think similar tickets should be created for all Jakarta packages (mail, persistence etc.)

**Comment by Goldmensch** [comment]
That would be a big breaking change. What are the benefits of this?

**Comment by altro3** [comment]
javax is no longer supported, I think it's worth switching to this package precisely because of development and support. I cannot name a specific profit, because. did not study this issue in detail. A similar question to the changes in version 3.0 - what was the profit from switching to jakarta.inject ? However, this upgrade took place

**Comment by graemerocher** [comment]
This is already being worked on here https://github.com/micronaut-projects/micronaut-validation

**Comment by altro3** [comment]
@graemerocher ok, and what about other? Mail, el, annotation, persistence?

**Comment by sdelamo** [comment]
> @graemerocher ok, and what about other? Mail, el, annotation, persistence?

The plan is to move completely to jakarta by Micronaut 4.0.

**Comment by graemerocher** [comment]
* `annotation` and `inject` are already migrated. 
* `persistence` requires a new module for Hibernate 6. 
*  We don't support `el` at this stage. 
* `email` will require a issue in the Micronaut Email module to track it if it is not done already

**Comment by altro3** [comment]
@graemerocher @sdelamo Perfect! The main thing is that it is in the nearest plans. So the ticket can be closed, as work is already underway.
