### ISSUE TITLE
Modules master branch should target next githubCoreBranch 4.0.x 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#8059]
Per module tasks: 

- [ ] gradle wrapper to 7.5.1 (or build plugins 6.x might break in strange ways) `./gradlew wrapper --gradle-version=7.5.1`
- [ ] `micronaut-build` plugins to 6.0.1
- [ ] `micronaut-test` to 4.0.0-SNAPSHOT
- [ ] `groovy` to 4.0.6
- [ ] `spock` to 2.3-groovy-4.0 
- [ ] add dependency on `mn.snakeyaml` where necessary (for imports, or use of `.yml` config files)
- [ ] remove `io.micronaut.build.internal.dependency-updates` from `build.gradle` (not needed)
- [ ] update all `.github/workflows` scripts to Java 17
- [ ] double check docs (update refs from jdk8 api docs to jdk 17 if necessary)
- [ ] dependency substitution to prevent leaking `codehaus` groovy if necessary, use
```
configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute(module("org.codehaus.groovy:groovy"))
                .using(module("org.apache.groovy:groovy:4.0.6"))
    }
}
```

---

### Issue description 

> all those with a ✅ have had a [PR raised against 4.0.x core](https://github.com/micronaut-projects/micronaut-core/pull/8286) to include the snapshot version in the BOM
> All those with ❌ require fixing for the latest 4.0.0-SNAPSHOT

- [x] [Micronaut Elastic Search](https://github.com/micronaut-projects/micronaut-elasticsearch) ✅ https://github.com/micronaut-projects/micronaut-core/pull/8313
- [x] [Micronaut JMX](https://github.com/micronaut-projects/micronaut-jmx)
- [x] [Micronaut Micrometer](https://github.com/micronaut-projects/micronaut-micrometer) ✅
- [x] [Micronaut GraphQL](https://github.com/micronaut-projects/micronaut-graphql) ❌
- [x] [Micronaut GRPC](https://github.com/micronaut-projects/micronaut-grpc)
- [x] [Micronaut Jackson XML](https://github.com/micronaut-projects/micronaut-jackson-xml) ✅
- [x] [Micronaut JAX-RS](https://github.com/micronaut-projects/micronaut-jaxrs) ❌
- [x] [Micronaut OpenAPI](https://github.com/micronaut-projects/micronaut-openapi)
- [x] [Micronaut Problem-JSON](https://github.com/micronaut-projects/micronaut-problem-json)
- [x] [Micronaut Serialization](https://github.com/micronaut-projects/micronaut-serialization) ✅
- [x] [Micronaut Microstream](https://github.com/micronaut-projects/micronaut-microstream) ✅
- [x] [Micronaut Servlet](https://github.com/micronaut-projects/micronaut-servlet) ✅
- [x] [Micronaut Spring](https://github.com/micronaut-projects/micronaut-spring)
- [x] [Micronaut AOT](https://github.com/micronaut-projects/micronaut-aot) ✅
- [ ] [Micronaut Gradle Plugin](https://github.com/micronaut-projects/micronaut-gradle-plugin)
- [ ] [Micronaut Maven Plugin](https://github.com/micronaut-projects/micronaut-maven-plugin)
- [ ] [Micronaut AWS](https://github.com/micronaut-projects/micronaut-aws)
- [ ] [Micronaut Azure](https://github.com/micronaut-projects/micronaut-azure)
- [ ] [Micronaut Discovery Client](https://github.com/micronaut-projects/micronaut-discovery-client)
- [ ] [Micronaut GCP](https://github.com/micronaut-projects/micronaut-gcp)
- [ ] [Micronaut Kubernets](https://github.com/micronaut-projects/micronaut-kubernetes)
- [ ] [Micronaut Oracle Cloud](https://github.com/micronaut-projects/micronaut-oracle-cloud)
- [x] [Micronaut Tracing](https://github.com/micronaut-projects/micronaut-tracing) ❌ (attempt to fix https://github.com/micronaut-projects/micronaut-tracing/pull/204)
- [ ] [Micronaut Data](https://github.com/micronaut-projects/micronaut-data)
- [ ] [Micronaut Cassandra](https://github.com/micronaut-projects/micronaut-cassandra)
- [ ] [Micronaut MongoDB](https://github.com/micronaut-projects/micronaut-mongodb)
- [x] [Micronaut Neo4j](https://github.com/micronaut-projects/micronaut-neo4j) ✅ https://github.com/micronaut-projects/micronaut-core/pull/8313
- [ ] [Micronaut R2DBC](https://github.com/micronaut-projects/micronaut-r2dbc)
- [ ] [Micronaut Redis](https://github.com/micronaut-projects/micronaut-redis)
- [x] [Micronaut SQL](https://github.com/micronaut-projects/micronaut-sql) ❌ There's a PR, but it's not in master yet
- [ ] [Micronaut Flyway](https://github.com/micronaut-projects/micronaut-flyway)
- [x] [Micronaut Liquibase](https://github.com/micronaut-projects/micronaut-liquibase) ❌
- [x] [Micronaut Groovy](https://github.com/micronaut-projects/micronaut-groovy) ✅
- [ ] [Micronaut Kotlin](https://github.com/micronaut-projects/micronaut-kotlin)
- [ ] [Micronuat JMS](https://github.com/micronaut-projects/micronaut-jms)
- [ ] [Micronaut Kafka](https://github.com/micronaut-projects/micronaut-kafka)
- [x] [Micronaut MQTT](https://github.com/micronaut-projects/micronaut-mqtt) ❌
- [ ] [Micronaut NATS](https://github.com/micronaut-projects/micronaut-nats)
- [ ] [Micronaut RabbitMQ](https://github.com/micronaut-projects/micronaut-rabbitmq)
- [x] [Micronaut ACME](https://github.com/micronaut-projects/micronaut-acme) ❌ (fix: https://github.com/micronaut-projects/micronaut-acme/pull/259)
- [x] [Micronaut Cache](https://github.com/micronaut-projects/micronaut-cache) ✅
- [x] [Micronaut Email](https://github.com/micronaut-projects/micronaut-email) ✅
- [x] [Micronaut Hibernate Validator](https://github.com/micronaut-projects/micronaut-hibernate-validator) ✅
- [ ] [Micronaut ignite](https://github.com/micronaut-projects/micronaut-ignite)
- [x] [Micronaut Picocli](https://github.com/micronaut-projects/micronaut-picocli) ✅
- [x] [Micronaut Security](https://github.com/micronaut-projects/micronaut-security) ✅
- [x] [Micronaut Test](https://github.com/micronaut-projects/micronaut-test) ❌ (requires micronaut-data)
- [x] [Micronaut Reactor](https://github.com/micronaut-projects/micronaut-reactor) ✅
- [x] [Micronaut RxJava2](https://github.com/micronaut-projects/micronaut-rxjava2) ✅
- [x] [Micronaut RxJava3](https://github.com/micronaut-projects/micronaut-rxjava3) ✅
- [x] [Micronaut Multi-tenancy](https://github.com/micronaut-projects/micronaut-multitenancy) ❌ (fix: https://github.com/micronaut-projects/micronaut-multitenancy/pull/144)
- [x] [Micronaut RSS](https://github.com/micronaut-projects/micronaut-rss) ❌ (fix: https://github.com/micronaut-projects/micronaut-rss/pull/245)
- [x] [Micronaut TOML](https://github.com/micronaut-projects/micronaut-toml) ✅
- [x] [Micronaut Views](https://github.com/micronaut-projects/micronaut-views) ❌ (fix: https://github.com/micronaut-projects/micronaut-views/pull/460)
- [ ] [Micronaut Validation](https://github.com/micronaut-projects/micronaut-validation)

**Comment by wetted** [comment]
@sdelamo We need to start pointing to `micronaut-test` 4.0.0-SNAPSHOT to avoid groovy 4.0 / spock groovy-3.0 collisions leaking into builds. @timyates agrees and we both went over the draft PR I have for `micronaut-mqtt` that has build issues because of it. Tim is also fixing `micronaut-test` 4.0.0-SNAPSHOT to correct the BOM to expose spock 2.3-groovy-4.0 instead of 21-groovy-3.0.

**Comment by timyates** [comment]
@wetted Micronaut-test 4.0.0-SNAPSHOT does have the correct dependencies, but it's failing to publish snapshots to Sonatype as we believe there's a currently a bug in the BeanDefinition code for Groovy classes in core 4.0.0-SNAPSHOT.  Investigations continue, and we'll get a SNAPSHOT published ASAP

**Comment by altro3** [comment]
micronaut-grpc: https://github.com/micronaut-projects/micronaut-grpc/pull/596

**Comment by altro3** [comment]
micronaut-openapi: https://github.com/micronaut-projects/micronaut-openapi/pull/831

**Comment by grimmjo** [comment]
micronaut-nats: micronaut-projects/micronaut-nats#265
