### ISSUE TITLE
StaticResourceResolver.resolve edits parameter path in iteration

### ISSUE THREAD

**Issue by mstego** [micronaut-projects/micronaut-core#807]
When you configurate multiple static resources in your application.yaml and the mapping field has a leading "/" (and the first (default) mapping is "/**"),  the resolve method will just work for the first static resource. 
So the AntPathMatcher will return true for the default mapping and the parameter path will be cut by the leading /.  But the requested resource will not be found in the default resource and the next iteration will be executed.
In the next iterations the pathMatcher.matches will return false because the parameter path was reduced by the leading "/".

Of course there are workarounds for this issue, but i think this should be solve, either by 

1.  making a local copy of the parameter path which, will be reduced by the leading /
or by
2.  changing the logic in AntPathMatcher.matches for default mappings.

 - **Operating System:** Windows10
- **Micronaut Version:** 1.0.0
- **JDK Version:** 1.8

example application.yaml 
`router:
   static-resources:
      default:
        mapping: /**
       paths: classpath:static
      swagger:
        enabled: true
        paths: classpath:swagger
        mapping: /swaggerUI/**`

**Comment by jameskleeh** [comment]
@mstego Can you upload an example project that demonstrates the issue? I'm having trouble determining what the issue is by your description

**Comment by jameskleeh** [comment]
@mstego I ran the application and executed those 3 URLs and it returned the correct result

```
TestServer $ curl localhost:8080
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  TEST MAIN
</body>
</html>TestServer $ curl localhost:8080/swaggerUI/
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Swagger</title>
</head>
<body>
 TEST SWAGGER
</body>
</html>TestServer $ curl localhost:8080/other/
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Other Stuff</title>
</head>
<body>
Test Other API
</body>
</html>TestServer $ 
```

**Comment by mstego** [comment]
how? did you debug the StaticResourceResolver.resolve? which mapping was the first in the iteration?

**Comment by mstego** [comment]
did you try it just once?

**Comment by jameskleeh** [comment]
@mstego I did as you said, "Try to call all 3 paths". If there are further steps required to reproduce the issue, please let me know

**Comment by mstego** [comment]
Maybe the error don't occur each time. In my original Project it worked some times.

**Comment by Hades32** [comment]
Hat the same problem. It did not occur every time and I think it only occurred when debugging...

**Comment by jameskleeh** [comment]
I was able to reproduce a 404, however it only is happening when I'm *not* debugging :(

**Comment by mstego** [comment]
It probably depends on the order of the resource mappings.

**Comment by graemerocher** [comment]
LinkedHashMap vs HashMap used somewhere probably
