### ISSUE TITLE
Remove all uses of AutomaticFeature annotation for GraalVM and replace with explicit configuration

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#8073]
### Issue description

The `@AutomaticFeature` annotation is going to be deprecated in the next version of GraalVM. We need to look for all uses of this annotation and switch to explicit configuration to specify the feature.

**Comment by alvarosanchez** [comment]
Should we not take the opportunity to migrate that configuration to the metadata repository? (#7805)

**Comment by graemerocher** [comment]
Where possible yes

**Comment by graemerocher** [comment]
@msupic related ticket
