### ISSUE TITLE
Remove Kotest 4

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-core#8075]
### Issue description

Issue description
The upgrade to Kotlin 1.7.x for Micronaut 4 introduces some breaking changes to Kotest 4. We should remove Kotest 4 for Micronaut 4.

see https://github.com/micronaut-projects/micronaut-test/issues/643
see https://github.com/kotest/kotest/issues/2960
see #8074

**Comment by wetted** [comment]
I have already added support for testing with Kotest5 in the core build plugin, needed for upgrade to kotlin 1.7.10 in `:test-suite-kotlin:test`

see #8074

**Comment by sdelamo** [comment]
@wetted what is the status?
