### ISSUE TITLE
@ExecuteOn not actually doing much?

### ISSUE THREAD

**Issue by phlppnhllngr** [micronaut-projects/micronaut-core#8077]
### Expected Behavior

If I use `@ExecuteOn` with a fixed pool ("requests") that has core size X and max size Y, I expect the framework to create up to Y threads if required. 
I only found [this](https://stackoverflow.com/questions/70395525/micronaut-microservice-can-only-handle-16-concurrent-http-connections) Stackoverflow post that seems to describe the same issue. It has no solution.

### Actual Behaviour

The framework only creates request-pool-threads equal to the number of event loop threads (16 in my case) even when you set a higher max pool size (75 in my case). I suspect the event loop threads are blockingly waiting for the request-pool-threads. If this is the case, can't I just execute everything on the event loop threads instead? I know this is bad practice but I don't see the difference.

### Steps To Reproduce

1. Create a thread pool bean with core size AVAILABLE_PROCESSORS * 2 (16 in my case) and max size 75. Unfortunately yaml config doesn't let you set them independently, a pool of type "fixed" always has core size = max size. Also you can't set a keep-alive time so if you do what the documentation suggests (type fixed, nThreads = 75) you will always have 75 threads no matter how many of them are idle. But that's another problem.

2. Put `@ExecuteOn` (with name of custom thread pool) on a `@Controller` with blocking (non-reactive) return type, e. g. String or StreamedFile.

3. Spam/invoke a controller method with Thread.sleep(5000) e. g. using gatling

4. Launch visualVM or another tool to inspect the app's threads

### Environment Information

- OS: Windows 10

### Example Application

[https://github.com/phlppnhllngr/mn-issue-8077](https://github.com/phlppnhllngr/mn-issue-8077)

### Version

3.7.0

**Comment by graemerocher** [comment]
@yawkat could you investigate this

**Comment by phlppnhllngr** [comment]
I created a demo project: https://github.com/phlppnhllngr/mn-issue-8077

**Comment by yawkat** [comment]
@phlppnhllngr ive tried your demo project, but can't reproduce the issue. i turned down the event loop size using the following config:

```yaml
micronaut:
  application:
    name: demo
  server:
    netty:
      parent:
        threads: 1
      worker:
        threads: 4
        event-loop-group: worker
```

With this, I get 4 worker event loop threads, but the pool still takes the full size when I run gatling (I see 50 threads).

**Comment by phlppnhllngr** [comment]
I had wrongly assumed how the pool adds more threads. It won't create more than coreSize threads unless the queue is full, and Executors.newFixedThreadPool() creates a queue with limit MAX_INTEGER. @yawkat thank you though.
