### ISSUE TITLE
Kotlin support for repeatable annotations

### ISSUE THREAD

**Issue by forresthopkinsa** [micronaut-projects/micronaut-core#8102]
### Issue description

The docs say that you need to use a workaround for repeated annotations when using Kotlin here:

https://github.com/micronaut-projects/micronaut-core/blob/3.7.x/src/main/docs/guide/ioc/conditionalBeans.adoc

However, the feature for repeatable annotations in Kotlin [landed](https://youtrack.jetbrains.com/issue/KT-12794/Allow-runtime-retention-repeatable-annotations-when-compiling-under-Java-8#focus=Comments-27-5090393.0-0) more than a year ago.

I don't know if this is a code change to be made in Micronaut to support this (feature request) or if the documentation just needs to be updated.

**Comment by Blueclaus13** [comment]
I'm a first-time contributor, Could I collaborate on this issue? Do you need to change the documentation to change that Kotlin doesn't have the repeatable annotation?

**Comment by altro3** [comment]
@graemerocher You can close it. It's already fixed
