### ISSUE TITLE
HttpStatus 425 is UNORDERED_COLLECTION instead of TOO_EARLY

### ISSUE THREAD

**Issue by tbehner** [micronaut-projects/micronaut-core#8120]
### Issue description

Hi everyone, HttpStatus.value(425) is translated to HttpStatus.UNORDERED_COLLECTION, but shouldn't this be TOO_EARLY as described here: https://www.rfc-editor.org/rfc/rfc8470

**Comment by yawkat** [comment]
i think with #5621 we should drop these weird status codes and only have those in rfc 9110 by default
