### ISSUE TITLE
After installation, micronaut cli commands not working on Mac

### ISSUE THREAD

**Issue by satb** [micronaut-projects/micronaut-core#813]
Followed the sdkman installation instructions and installed on the Mac.

```
❯ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

```
❯ mn --version
[Fatal Error] :1:107: The reference to entity "r" must end with the ';' delimiter.
| Error Error occurred running Micronaut CLI: The reference to entity "r" must end with the ';' delimiter. (Use --stacktrace to see the full trace)
```

```
❯ mn --version --stacktrace
[Fatal Error] :1:107: The reference to entity "r" must end with the ';' delimiter.
| Error Error occurred running Micronaut CLI: The reference to entity "r" must end with the ';' delimiter. (Use --stacktrace to see the full trace)
```

What could I do to troubleshoot more?

**Comment by jeffbrown** [comment]
@satb Are you using bash?

**Comment by satb** [comment]
@graemerocher  - You mean clean the entire maven cache? Or just a part of the repo? I can't clean the entire repo on my current machine. Its several gigabytes which will take a long time to load again. Will try to do it on another machine that hasn't been used.

**Comment by satb** [comment]
If I build from source and run, it works fine. However, the one from sdkman is a problem

```
❯ which mn
/Users/satb/dev/micronaut-core//cli/build/bin/mn

❯ mn --version
| Micronaut Version: 1.0.1.BUILD-SNAPSHOT
| JVM Version: 1.8.0_101
```

On another terminal window

```
❯ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

❯ which mn
/Users/satb/.sdkman/candidates/micronaut/current/bin/mn

❯ mn --version
[Fatal Error] :1:107: The reference to entity "r" must end with the ';' delimiter.
| Error Error occurred running Micronaut CLI: The reference to entity "r" must end with the ';' delimiter. (Use --stacktrace to see the full trace)
```

**Comment by jameskleeh** [comment]
@satb You can clear the cache of micronaut `rm -rf ~/.m2/repository/io/micronaut`

**Comment by jameskleeh** [comment]
@satb You can also debug the CLI by exporting `MN_OPTS="-Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"` then attaching a remote debugger from the 1.0.0 tag

**Comment by satb** [comment]
@jameskleeh - Thank you for the hint. I was able to track down the problem. 

During launch of the cli, the pom file:/Users/satb/.m2/repository/io/micronaut/micronaut-bom/1.0.0/micronaut-bom-1.0.0.pom is read in. However, the file had this corrupted data somehow:

```
<html><body><script>window.location="http://dnserrorassist.att.net/search/?q="+escape(window.location)+"&r="+escape(document.referrer)+"&t=0";</script></body></html>
```

I have no idea how the pom ended up having that data. Like @graemerocher pointed out, removing the repo cache for micronaut and then fetching it again fixed the problem and now it works even with sdkman. 

Thank you all for your input in pointing me the right direction. Will close the defect.
