### ISSUE TITLE
BeanDefinitionInjectProcessor requiresValidation method incorrect

### ISSUE THREAD

**Issue by kevind-wgu** [micronaut-projects/micronaut-core#8131]
### Expected Behavior

@dstepanov I have been fighting a bug I encountered when upgrading from 3.6.4 to 3.7.1.  I have tracked the problem down to the method BeanDefiintionInjectProcessor.requresValidation which was recently added by you. 

The method "requiresValidation" seems to return true for any method on a class that has a "Constraint" annotation defined. 
I have written a class level validation constraint and applied it to my POJO. As a result the new code is flagging my POJO as a bean and adding it to the application context. ([Class Level Constraint example](https://howtodoinjava.com/hibernate/hibernate-validator-java-bean-validation/)

This is particularly problematic for me because it causes issues in my unit tests because my Junit5 ParameterResolver conflicts with the micronaut Parameter Resolver because my POJO is now a bean.

You can see an example of what I am describing here - https://github.com/kevind-wgu/micronaut-junit5-bug

### Steps To Reproduce

See example app.

### Environment Information

Mac 12.5.1
Java 17.0.3

### Example Application

https://github.com/kevind-wgu/micronaut-junit5-bug

### Version

3.7.1

**Comment by dstepanov** [comment]
It’s already fixed.

**Comment by kevind-wgu** [comment]
Awesome! Thank you!

**Comment by dstepanov** [comment]
Should be in 3.7.2
