### ISSUE TITLE
Unnecessary context recreation at every AWS Lambda function call

### ISSUE THREAD

**Issue by khelman** [micronaut-projects/micronaut-core#814]
I've noticed that MicronautRequestStreamHandler recreates context at every call.
Adding simple cache for context shortens execution noticeably.
For example:
```
public class CachingRequestHandler extends MicronautRequestStreamHandler {

    private static ApplicationContext cachedContext;

    @Override
    protected ApplicationContext buildApplicationContext(Context context) {
        if (cachedContext == null) {
            cachedContext = super.buildApplicationContext(context);
        }
        return cachedContext;
    }
}
```

### Steps to Reproduce

1. mn create-function --build=maven test
2. change root log level in logback.xml to debug 
3. mvn clean install
4. deploy on aws
5. run function twice (with any test data)

### Expected Behaviour

Function should build bean context once on cold start and reuse it for following requests

### Actual Behaviour

logs for both runs looks the same. It rebuilds context for every request. It takes about 0.8 - 1 second for very basic function.

**Comment by graemerocher** [comment]
Good idea
