### ISSUE TITLE
Arrays in query params 

### ISSUE THREAD

**Issue by Bejenar** [micronaut-projects/micronaut-core#8145]
### Issue description

I need to build a request that will have the following query params:

`/endpoint?filter[has]=resources&filter[site]=foobar&filter[external_id]=47917&include=bar`

```Java
@Client(id = "myclient", httpVersion = HttpVersion.HTTP_2_0)
public interface MyClient{

    @Get("/endpoint")
    String getSomething(@QueryValue Map<String, String> filter, @QueryValue String include);
}
```

expected result: http client makes the desired call

actual:
```
java.lang.ClassCastException: class io.micronaut.core.convert.value.ConvertibleValuesMap cannot be cast to class
 io.micronaut.core.convert.value.ConvertibleMultiValues (io.micronaut.core.convert.value.ConvertibleValuesMap and
 io.micronaut.core.convert.value.ConvertibleMultiValues are in unnamed module of loader 'app')
```

Am I doing something wrong perhaps?

**Comment by Patrolfr** [comment]
Hi, it should be possible with `@QueryValue @Format("DEEP_OBJECT") Object filter` parameter.
@Bejenar I have prepared [an example for your case](https://github.com/Patrolfr/micronaut-core/commit/d61cdb52dcf9a6bb29e6b8bdf0b715736ad42037). Does it solve your problem?

**Comment by Bejenar** [comment]
@Patrolfr yes it works, thank you! By the way, is `ClientFormatSpec` the only place to see how `@Format` can be used? Don't seem to find a lot here: https://docs.micronaut.io/2.3.3/api/io/micronaut/core/convert/format/Format.html

**Comment by Patrolfr** [comment]
I have found example usage when I was trying to tackle down this issue during Hacktoberfest.
See `Query values formatting` in the [docs](https://docs.micronaut.io/latest/guide/#clientParameters).
I guess annotation is too general to have such a detailed usage described in the javadoc
