### ISSUE TITLE
Extract session to its own repository

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#8152]
### Issue description

see: https://github.com/micronaut-projects/micronaut-core/tree/4.0.x/session

**Comment by sdelamo** [comment]
what would be the best way to do this? Fork the repo and remove the rest of the modules to preseve the history?

**Comment by timyates** [comment]
I'm not sure 🤔 

Q; Will it be under the group `io.micronaut.session`?

If so, we will will need to fix up starter (so that it uses a different dependency for 4.0.0)

**Comment by alvarosanchez** [comment]
> what would be the best way to do this? Fork the repo and remove the rest of the modules to preseve the history?

We have done this in the past multiple times (cache, discovery client, etc). It required running a complex `git filter-branch` command, but now it is much easier: https://stackoverflow.com/questions/359424/detach-move-subdirectory-into-separate-git-repository

> Q; Will it be under the group `io.micronaut.session`?

Yes. `io.micronaut` is reserved for core modules.

**Comment by timyates** [comment]
We now have https://github.com/micronaut-projects/micronaut-session

I'll leave this open and it can be closed once https://github.com/micronaut-projects/micronaut-core/pull/8281 is merged
