### ISSUE TITLE
When running @MicronautTest server is not started via Application.java

### ISSUE THREAD

**Issue by sapanparikh18** [micronaut-projects/micronaut-core#8176]
### Expected Behavior

Add `System.out.println("Starting app")` at the first line of Application.java of your Micronaut project. When you run the integration test, this string should be printed.

### Actual Behaviour

The string does not get printed. 
This is important because this is where we initialize BlockHound. This means our integration tests pass but the production system fails, complaining of blocking-related issues. 

### Environment Information

- JDK 11
- id("io.micronaut.application") version "3.6.2"
- OS Windows and MacOS

### Version

3.6.2

**Comment by alvarosanchez** [comment]
You should not use the Application class for that. A better option would be [a server event listener](https://docs.micronaut.io/latest/guide/#serverEvents).

Alternatively, initialise BlockHound in a `static {}` block, [as they recommend](https://github.com/reactor/BlockHound/blob/master/docs/quick_start.md#installation)
