### ISSUE TITLE
StreamingUpload truncates data

### ISSUE THREAD

**Issue by vnesek** [micronaut-projects/micronaut-core#818]
StreamingFileUpload truncates input stream if uploading multiple files.

### Steps to Reproduce

1. We're uploading multiple XML documents (POST multipart/form-data) processing them reactively and returning combined list as a result.

```kotlin
@Controller("/api/bankstatement")
class BankStatementController(
        val camt: Camt053
) : HasLog() {

    @PermitAll
    @Post(consumes = [MediaType.MULTIPART_FORM_DATA])
    fun upload(file: Publisher<StreamingFileUpload>): Mono<List<Transaction>> {
        return file.toFlux()
                .flatMap { f ->
                    f.toMono().map { part ->
                        part.inputStream.use {
                            try {
                                camt.transactionsFrom(f.filename, it).apply {
                                    log.debug("Extracted {} transactions from bank statement file {}", size, f.filename)
                                }
                            } catch (t: Throwable) {
                                log.error("Invalid bank statement file {}: {}", f.filename, t.toString())
                                emptyList<Transaction>()
                            }
                        }
                    }
                }
                .reduce { a, b -> a + b }
    }
}
```
2. POST some files to controller. Sometimes it works, and sometimes it fail to process one or more files with following exceptions logged. Errors occurs even when posting a single file.

We're processing files with JAXB and files are valid XML. 

```
12:31:08.795 [nioEventLoopGroup-2-3] ERROR e.e.b.BankStatementController - Invalid bank statement file ISTM1100281241_20180912.xml: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.]

12:31:08.795 [nioEventLoopGroup-2-3] ERROR e.e.b.BankStatementController - Invalid bank statement file BCS.35488677401.20181017.0087.xml: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.]

12:31:10.026 [nioEventLoopGroup-2-3] ERROR e.e.b.BankStatementController - Invalid bank statement file BCS.35488677401.20181017.0087.xml: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 139; columnNumber: 10; XML document structures must start and end within the same entity.]
```
Errors sugest that sometimes we get an empty stream, and sometimes we get first few lines.

If StreamingFileUpload is replaced with CompletedFileUpload everything works as expected. 

Replacing StreamingFileUpload with Publisher<StreamingFileUpload> doesn't help.

### Expected Behaviour

Uploaded files should be processed correctly.

### Actual Behaviour

Uploaded file isn't received completely. Stream is either empty or truncated.

### Environment Information

- **Operating System**: macOS 10.14
- **Micronaut Version:** 1.0.0
- **JDK Version:** 1.8 and 11

**Comment by graemerocher** [comment]
Could you provide an example that reproduces the issue?

**Comment by vnesek** [comment]
No need... it was my fault. You can't pass InputStream from PartData to some random service as there is no guarrantee that it will contain whole file. Most likely it will be just a chunk that fits into an TCP/IP packer. First you need to assemble all parts into a buffer and then pass it to classic InputStream IO style service.
