### ISSUE TITLE
Automatically configure a separate event loop for the client if only 1 CPU is detected

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#8198]
### Feature description

A common deployment scenario is to deploy Micronaut to k8s with pods that have only a single CPU.

In this scenario if you have any blocking HTTP client calls in your application it deadlocks the event loop because the event loop size is calculated from the number of available CPUs.

To resolve this the user has to re-configure a separate event loop for the client to run operations blocking client operations on a separate event loop. This is non-obvious and users keep hitting this problem and wondering why they are getting read time out exceptions.

We should consider altering this for Micronaut 4.x to instead detect the CPU configuration and automatically configure a separate event loop for the HTTP client so users don't keep hitting this problem on K8s

**Comment by graemerocher** [comment]
thoughts @yawkat @dstepanov @sdelamo ?

**Comment by dstepanov** [comment]
It doesn't matter how many threads you have, the blocking client can block them all. IMHO I would switch back to `auto` thread selection. The use-case where we have imperative controller methods that need to be run on the event loop is, in my opinion, far less than the opposite.

**Comment by graemerocher** [comment]
Perhaps defaulting to IO makes more sense

**Comment by yawkat** [comment]
we could implement a simple detection for this and log a warning (or even error, if we can be sure the event loop we're waiting on is the same that we're blocking).

**Comment by graemerocher** [comment]
Fail fast would definitely be better than the current behavior

**Comment by sdelamo** [comment]
@graemerocher can we close this issue since #8354 is merged?
