### ISSUE TITLE
Move tracing relating components from external modules to micronaut-tracing module

### ISSUE THREAD

**Issue by donbeave** [micronaut-projects/micronaut-core#8212]
### Issue description

Hello!

It looks like opentracing support was added to [kafka](https://github.com/micronaut-projects/micronaut-kafka), [grpc](https://github.com/micronaut-projects/micronaut-grpc), etc modules before `micronaut-tracing` module was moved from core to a separate module and added additional tracing API, like OpenTelemetry. For me, it looks like completely makes sense to move all tracing-related configurations from such modules to `micronaut-tracing` repository, it can be done for Micronaut 4.0.0 release.

If you have some interest in such work, please let me know, I think I can take care of it.

**Comment by graemerocher** [comment]
Makes sense. PRs welcome 🙏

**Comment by donbeave** [comment]
Seems it's already done. I see kafka module has deleted legacy tracing classes and grpc moved them to a separate package `grpc-opentracing`, which probably should be marked as deprecated and for deletion in the future, as opentelemetry is becoming a standard for doing tracing.
