### ISSUE TITLE
fromValue() for an enum receives null when passed in a JSON array

### ISSUE THREAD

**Issue by AndrejMitrovic** [micronaut-projects/micronaut-core#8215]
### Expected Behavior

When an enum with a `fromValue(String)` is defined it should be called with the string value so the routine can convert it to the appropriate enum type.

### Actual Behaviour

When passing a JSON array the passed in string is `null`. This makes it impossible to return an error code if the user wrongly specified an array when another type was expected.

### Steps To Reproduce

1. Clone https://github.com/AndrejMitrovic/micronaut-issues/tree/array
2. `grade run`
3. In another terminal run first query: `curl -H "Content-Type: application/json" --request POST --data "{ \"id\": \"asdf\" }" http://localhost:8080/test`
4. Run second query with array: `curl -H "Content-Type: application/json" --request POST --data "{ \"id\": [\"asdf\"] }" http://localhost:8080/test`

In stdout for the server the first query emits:

> -- CONVERTING FROM: asdf

The second query emits:

> -- CONVERTING FROM: null

That means we cannot throw an exception if the user passed an array when one was not expected. `null` could be a valid state if the parameter is optional. But an array should not be implicitly converted to `null` in this case.

### Environment Information

Operating System: Windows 10
Micronaut Version: 2.5.13
JDK Version: temurin-11.0.16.1

### Example Application

https://github.com/AndrejMitrovic/micronaut-issues/tree/array

### Version

2.5.13

**Comment by yawkat** [comment]
This is handled by jackson-databind, micronaut json support isn't involved. I'm not sure if it's intentional or a bug. You can report it at https://github.com/FasterXML/jackson-databind . This is a test case that does not use micronaut:

```java
package arrayissue;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.annotation.JsonCreator;

enum MyEnum {
    FOO("FOO"),
    BAR("BAR");

    private String value;

    MyEnum(String value) {
        this.value = value;
    }

    public static void main(String[] args) throws JsonProcessingException {
        ObjectMapper om = new ObjectMapper();
        om.enable(DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS);
        System.out.println(om.readValue("\"FOO\"", MyEnum.class));
        System.out.println(om.readValue("[\"FOO\"]", MyEnum.class));
    }

    @JsonCreator
    public static MyEnum fromValue(String text) {
        System.out.println("-- CONVERTING FROM: " + text);
        return MyEnum.FOO;
    }
}
```

it prints

```
-- CONVERTING FROM: FOO
FOO
-- CONVERTING FROM: null
FOO
```

If you create an issue on jackson-databind, tatu can decide what to do about it. Feel free to ping me on the issue.

**Comment by AndrejMitrovic** [comment]
Thanks a lot for your help @yawkat!
