### ISSUE TITLE
Upgrade SnakeYaml and Netty and do a release

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#8229]
Micronaut 3.7.2 ships with versions of Netty and SnakeYAML that have reported vulnerabilities. We need to upgrade and do another release. We should also check Jackson for newer patch releases.

**Comment by graemerocher** [comment]
@sdelamo can you look at this?

**Comment by sdelamo** [comment]
yes

**Comment by graemerocher** [comment]
Note Micronaut and Netty are also broken under GraalVM which is fixed in the latest version. So this is quite urgent. See https://github.com/netty/netty/issues/12725

**Comment by sdelamo** [comment]
closed via https://github.com/micronaut-projects/micronaut-core/pull/8233 and https://github.com/micronaut-projects/micronaut-core/pull/8232
