### ISSUE TITLE
Use Nullable annotation from Jakarta EE to check the nullability of an element

### ISSUE THREAD

**Issue by perococco** [micronaut-projects/micronaut-core#8264]
### Context
As far as I could find, the nullability of an element is determined with the method [AnnotatedElement#isDeclareNullable](https://github.com/micronaut-projects/micronaut-core/blob/85ffc39fa7950dbce5ab5fb9eb0d430ac9ef8c5e/core/src/main/java/io/micronaut/core/annotation/AnnotatedElement.java#L38) (I reached this method after an exception while deserializing an object with a nullable property).

The check is based on the presence of the stereotype `javax.annotation.Nullable` from JSR305 (defined in [AnnotationUtil#NULLABLE](https://github.com/micronaut-projects/micronaut-core/blob/85ffc39fa7950dbce5ab5fb9eb0d430ac9ef8c5e/core/src/main/java/io/micronaut/core/annotation/AnnotationUtil.java#L104)).

### Request
Since Jakarate EE is already used in a Micronaut project (through `@Singleton` for instance), it seems to me that would be natural to include also a test on the presence of the stereotype "jakarta.annotation.Nullable" from Jakarta EE when checking the nullability of an element.

**Comment by graemerocher** [comment]
this would be a matter of adding another nullable transformer like 

https://github.com/micronaut-projects/micronaut-core/blob/85ffc39fa7950dbce5ab5fb9eb0d430ac9ef8c5e/core-processor/src/main/java/io/micronaut/inject/annotation/internal/CoreNullableTransformer.java or 

https://github.com/micronaut-projects/micronaut-core/blob/85ffc39fa7950dbce5ab5fb9eb0d430ac9ef8c5e/core-processor/src/main/java/io/micronaut/inject/annotation/internal/KotlinNullableMapper.java

**Comment by perococco** [comment]
Is there a test for the `CoreNullableTransformer` that I can draw inspiration from for the new nullable transformer ?

**Comment by yawkat** [comment]
`NullabilityAnnotationsSpec`
