### ISSUE TITLE
Different annotation processing with 3.7.x and v4.0.0 for method getDeclaredAnnotation (micronaut-openapi)

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#8287]
### Expected Behavior

Classes structure:
```java
@Controller
class OpenApiController {

    @Post("/path")
    public void processSync(@Body MyDto dto) {
    }
}

class MyDto {

    @Schema(
            name = "test",
            description = "this is description"
    )
    private Parameters parameters;

    public Parameters getParameters() {
        return parameters;
    }

    public void setParameters(Parameters parameters) {
        this.parameters = parameters;
    }
}

class Parameters {

    private Integer stampWidth;
    private Integer stampHeight;
    private int pageNumber;

    public Integer getStampWidth() {
        return stampWidth;
    }

    public void setStampWidth(Integer stampWidth) {
        this.stampWidth = stampWidth;
    }

    public Integer getStampHeight() {
        return stampHeight;
    }

    public void setStampHeight(Integer stampHeight) {
        this.stampHeight = stampHeight;
    }

    public int getPageNumber() {
        return pageNumber;
    }

    public void setPageNumber(int pageNumber) {
        this.pageNumber = pageNumber;
    }
}
```
I process class `MyDto`, next I get properties in this class  - field `parameters` - and next I try to process annotation `@Schema` on `parameters` field. 

1. First we get JavaParameterElement `dto` for method `processSync`.
2. Get JavaClassElement for dto - this is `MyDto` class
3. Get beanProperties for class MyDto:
```java
List<PropertyElement> beanProperties = classElement.getBeanProperties();
```
Difference between versions 3.7.3 and 4.0.0:
In 3.7.3 this method returns collection of `JavaClassElement`, but in version 4.0.0 return collection of `JavaPropertyElement`.

Hmm... Logically, we should get a list of properties, not classes. So the question is: was this a bug in version 3.7 and is it fixed in version 4.0? Or vice versa?

### Version

4.0.0-SNAPSHOT

**Comment by altro3** [comment]
@dstepanov @graemerocher Look to this, pls

**Comment by dstepanov** [comment]
I don’t think that would return class elements before. In V4 properties should be more complete and better to work with.

**Comment by altro3** [comment]
It is a fact that it was. This is the last reason why the remaining 7 tests on micronaut-openapi failed. To understand the difference, I had to run the test in parallel with version 3.7.3 and version 4.0.0 in debug. Here's what I saw:

Debug 4.0.0:
![изображение](https://user-images.githubusercontent.com/48474279/200015496-5f41fb75-c927-4690-9c68-e633e274f2d8.png)
As you see `definingElement` is JavaPropertyElement `parameters`. And found `@Schema` annotation.

Debug 3.7.3:
![изображение](https://user-images.githubusercontent.com/48474279/200015885-769df707-63c4-499d-bc45-b5cc6ce99a12.png)
`definingElement` is a JavaClassElement `parameters` and annotation `@Schema` not found.

**Comment by altro3** [comment]
@dstepanov Apparently, this bug was before version 4.0.0. The problem is that all the logic is already built around that bug :-D . Therefore, now I need to understand and rebuild the logic in accordance with the new behavior of the micronaut. Oh, the very case when it would be better if the bug remained :-))))

**Comment by dstepanov** [comment]
In v4 properties are more complete so for the use case you have you shouldn’t need to combine various things like field+get set method etc

**Comment by altro3** [comment]
@dstepanov Hallelujah! Finally, all openapi works correctly with micronaut 4.0.

This difference is the only one. I once again analyzed the differences between versions 3.7 and 4.0, the conclusion is this:

in version 3.7, the getDeclaredAnnotation() method on a PropertyElement does NOT read the annotations on the field itself, but only the annotations on the getter and setter. In version 4.0, both annotations are read. To fix it, I had to add such a block and not read the annotations for properties in this place:
```java
        // Here we need to skip Schema nnotation on field level, because with micronaut 3.x method getDeclaredAnnotation
        // returned always null and found Schema annotation only on getters and setters
        AnnotationValue<io.swagger.v3.oas.annotations.media.Schema> schemaValue = null;
        if (definingElement != null) {
            if (definingElement instanceof PropertyElement) {
                var getterOpt = ((PropertyElement) definingElement).getReadMethod();
                if (getterOpt.isPresent()) {
                    schemaValue = getterOpt.get().getDeclaredAnnotation(io.swagger.v3.oas.annotations.media.Schema.class);
                }
                if (schemaValue == null) {
                    var setterOpt = ((PropertyElement) definingElement).getWriteMethod();
                    if (setterOpt.isPresent()) {
                        schemaValue = setterOpt.get().getDeclaredAnnotation(io.swagger.v3.oas.annotations.media.Schema.class);
                    }
                }
            } else {
                schemaValue = definingElement.getDeclaredAnnotation(io.swagger.v3.oas.annotations.media.Schema.class);
            }
        
```

**Comment by dstepanov** [comment]
Why is it a problem? There is a lot of places where a property is supposed to inherit the field annotations.

**Comment by dstepanov** [comment]
If it’s such a problem maybe we can add a method to the property element that can skip the field annotations.

**Comment by altro3** [comment]
No, no, that's not a big problem. Just a nuance. I'm just saying that this looks very much like a bug in version 3.7.x . But I remind you that the openapi logic is already built with this bug in mind (as I found out), so fixing the bug led to a change in the logic in the openapi and some of the tests failed.
