### ISSUE TITLE
Openapi schema not generated for fields that are public

### ISSUE THREAD

**Issue by frehov** [micronaut-projects/micronaut-core#829]
Seeing an issue where the openapi annotation processor is not handling classes with public fields and no getters/setters.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create project with 'mn create-app --build=maven --features=swagger-java dummyapp'
2. Create controller with 'mn create-controller dummycontroller'
3. Create a PublicUser class with public username
4. Create a PrivateUser class with private username, and public getter/setter
5. Create a new endpoints under dummycontroller for each class, specifying the class as the return type
5. Compile with 'mvn clean install'
6. Check generated swagger yml file

### Expected Behaviour

The same fields rendered in the yml for both PublicUser and PrivateUser

### Actual Behaviour

Only PrivateUser' schema get's rendered

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 1.0.0
- **JDK Version:** 1.8.0_161

### Example Application

DummyController
```java
package dummyapp.controller;

import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import no.knowit.drift.personfinder.model.PrivateUser;
import no.knowit.drift.personfinder.model.PublicUser;

@Controller("/dummy")
public class dummycontroller {

    @Get("/private")
    public PrivateUser privateUser() {
        return new PrivateUser();
    }

    @Get("/public")
    public PublicUser publicUser() {
        return new PublicUser();
    }
}
```    
  

```java
package dummyapp.model;

public class PublicUser {
    public String username;
}
```  

```java
package dummyapp.model;

public class PrivateUser {

    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}
```    

Rendered openapi spec
```
openapi: 3.0.1
info:
  title: Dummy API
  description: API for looking up things
  license:
    name: Apache 2.0
  version: "0.1"
paths:
  /dummy/private:
    get:
      operationId: privateUser
      parameters: []
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrivateUser'
  /dummy/public:
    get:
      operationId: publicUser
      parameters: []
      responses:
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicUser'
components:
  schemas:
    PrivateUser:
      type: object
      properties:
        username:
          type: string
          nullable: false
    PublicUser:
      type: object
```

**Comment by graemerocher** [comment]
Currently we do not process public fields it seems only properties, so you would need a getter and a setter.

**Comment by frehov** [comment]
I can confirm that adding getters and setters to public variables works, but it introduces a lot of extra boilerplate.
To avoid boilerplate, it's possible to use Lombok.

Jackson will however deserialize to public fields.
