### ISSUE TITLE
Java records cannot be used for request beans with @PathVariable

### ISSUE THREAD

**Issue by lbkulinski** [micronaut-projects/micronaut-core#8295]
### Expected Behavior

I expect to be able to use Java records with `@RequestBean` and `@PathVariable` for API endpoints in the same way that I can declare a POJO.

### Actual Behaviour

Instead, I get the following compilation error:
```
java: The route declares a uri variable named [id], but no corresponding method argument is present
```

### Steps To Reproduce

1. Clone the provided repository
2. Run the Micronaut application
3. See the following compilation error: `java: The route declares a uri variable named [id], but no corresponding method argument is present`

### Environment Information

- Operating System: macOS Ventura 13.0
- JDK (I presume this would still occur on non-ea builds):  openjdk 20-ea 2023-03-21
OpenJDK Runtime Environment (build 20-ea+21-1545)
OpenJDK 64-Bit Server VM (build 20-ea+21-1545, mixed mode, sharing)

### Example Application

https://github.com/lbkulinski/record_bug_example

### Version

3.7.3

**Comment by lbkulinski** [comment]
@sdelamo @dstepanov Any help with this issue? Thanks!

**Comment by yawkat** [comment]
thanks for the report! will be fixed in 3.8

**Comment by lbkulinski** [comment]
@yawkat

> thanks for the report! will be fixed in 3.8

Thanks for the quick turnaround! This will be super nice to use!

**Comment by lbkulinski** [comment]
@yawkat Is this fix available in 3.8.0-SNAPSHOT? I recently picked a project back up that was trying to use it, and appear to be having issues with using `@PathVariable` and records still. The original example now compiles, but I am now getting the following when making a request:
```
{
    "message": "Bad Request",
    "_links": {
        "self": {
            "href": "/api/example/1",
            "templated": false
        }
    },
    "_embedded": {
        "errors": [
            {
                "message": "Required argument [Integer id] not specified",
                "path": "/id"
            }
        ]
    }
}
```
This occurs when I `POST` to `/api/example/1`, where `1` would be the value for the required `id` path variable. I have update the following repository, where you should be able to see the issue: https://github.com/lbkulinski/record_bug_example

Thanks!

**Comment by lbkulinski** [comment]
@dstepanov @sdelamo Are you able to take a look at [the comment above](https://github.com/micronaut-projects/micronaut-core/issues/8295#issuecomment-1365620692)? Thanks and sorry for the trouble!

**Comment by lbkulinski** [comment]
I opened https://github.com/micronaut-projects/micronaut-core/issues/8551. Thanks!
