### ISSUE TITLE
ApplicationContext.getBeansOfType() returning different number of results in test

### ISSUE THREAD

**Issue by cancech** [micronaut-projects/micronaut-core#8315]
### Expected Behavior

`ApplicationContext.getBeansOfType(MyClass.class)` should always retrieve the same number of bean instances regardless of running as an application proper or whether running a `@MicronautTest` case.

### Actual Behaviour

Running the application proper looks to properly retrieve all beans, regardless of their source, however within an `@MicronautTest` only a subset of them are actually returned by `ApplicationContext.getBeansOfType(MyClass.class)`. In the reproducing example (see Steps To Reproduce) the application proper returns 30 beans, while the test only 20. In our actual code where this issue was encountered, the test will retrieve a seemingly arbitrary number (25 - 35, unsure of the actual total) with the total varying from each execution of the test to the next.

### Steps To Reproduce

[micronaut-bug.zip](https://github.com/micronaut-projects/micronaut-core/files/9971321/micronaut-bug.zip)

In this example 30 `MyPrinter` beans are generated through various means and all 30 are triggered when running the application proper. However, when running the test case only 20 beans are retrieved by `ApplicationContext.getBeansOfType(MyPrinter.class)` .

### Environment Information

1. Windows 10 Enterprise (21H2 OS build 19044.2130)
2. OpenJDK11.0.2 (64-bit)
3. Gradle 7.2.0
4. PicoCLI 4.7.0
5. Micronaut 3.7.3
6. Micronaut Test 3.7.0

### Version

3.7.3

**Comment by jameskleeh** [comment]
The configuration you are supplying in your `Main` class does not apply when running test and that accounts for the difference in counts. If you want to supply property sources for both running normally and testing you can create a class like: 

```
    @ContextConfigurer
    public static class PropertySourcesConfigurer implements ApplicationContextConfigurer {
        @Override
        public void configure(@NonNull ApplicationContextBuilder builder) {
            builder.proprtySources(...)
        }
    }
```
