### ISSUE TITLE
Ability to customize SSLParameters for http clients

### ISSUE THREAD

**Issue by drmaas** [micronaut-projects/micronaut-core#8325]
### Feature description

I'd like to be able to customize various SSL properties via the `SSLHandler --> SSLEngine --> SSLParameters` api in the `ConnectionManager` class. Something like:

```
SslHandler sslHandler = sslContext.newHandler(ch.alloc(), requestKey.getHost(), requestKey.getPort());
...
SSLEngine engine = sslHandler.engine();
SSLParameters params = new SSLParameters();
params.setEndpointIdentificationAlgorithm("");
engine.setSSLParameters(params);
...
```

Is there a way to do this currently? If not, would the best way to do this to add properties to the `AbstractClientSslConfiguration` class (where we can already trust all certs), or to add some sort of `SSLHandlerCustomizer` that gets injected? Either way, it would be useful to be able to set these properties on http clients to account for various scenarios.

**Comment by yawkat** [comment]
you could create a NettyClientCustomizer, and on onInitialPipelineBuilt, get the SSLHandler from the pipeline to set the parameters. LMK if that works for you, I don't want to add a new customization API if the current one is sufficient.

**Comment by drmaas** [comment]
For future reference, I verified that for example, we can disable hostname verification by adding something like this:

```kotlin
@Singleton
class SSLNettyClientCustomizer : BeanCreatedEventListener<NettyClientCustomizer.Registry> {

	override fun onCreated(event: BeanCreatedEvent<NettyClientCustomizer.Registry>): NettyClientCustomizer.Registry {
		val registry = event.bean
		registry.register(Customizer(null))
		return registry
	}

	private inner class Customizer(private val channel: Channel?) : NettyClientCustomizer {

		override fun specializeForChannel(channel: Channel, role: NettyClientCustomizer.ChannelRole) = Customizer(channel)

		override fun onRequestPipelineBuilt() {
			val pipeline = channel!!.pipeline()
			val sslHandler = pipeline.get(ChannelPipelineCustomizer.HANDLER_SSL) as SslHandler
			val engine = sslHandler.engine()
			val params = engine.sslParameters
			params.endpointIdentificationAlgorithm = ""
		}
	}
}
```

**Comment by yawkat** [comment]
good to hear, but should probably use `onInitialPipelineBuilt`
