### ISSUE TITLE
trimLeading() method is not working as expected, when all the characters satisfy the predicate.

### ISSUE THREAD

**Issue by harikrishna553** [micronaut-projects/micronaut-core#8328]
### Expected Behavior

```
String out = StringUtils.trimLeadingCharacter("aaaaaa", 'a');
System.out.println(out); // Prints aaaaaa
```
Above snippet is retuning the actual string, instead of returning an empty string.

### Actual Behaviour

As per the Javadoc, I am expecting a new string without any leading characters that match the supplied character. In the above case, it should be an empty string.

As I dig into the code, the problem is with the following implementation.

```
    public static String trimLeading(String str, Predicate<Character> predicate) {
        if (isEmpty(str)) {
            return str;
        }
        for (int i = 0; i < str.length(); i++) {
            if (!predicate.test(str.charAt(i))) {
                return str.substring(i);
            }
        }
        return str;
    }
```

Following snippet can resolve this issue.

```
public static String trimLeading(final String str, final Predicate<Character> predicate) {
		if (isEmpty(str)) {
			return str;
		}

		int counter = 0;
		while (counter < str.length()) {
			if (predicate.test(str.charAt(counter))) {
				counter++;
				continue;
			}
			return str.substring(counter);
		}

		return str.substring(counter);
	}

```

### Environment Information

- Operating system : Mac OS
- Jdk version: 15
- Micronaut version: 3.7.3

### Example Application

Code provided in 'Expected Behavior' section

### Version

3.7.3

**Comment by yawkat** [comment]
Good catch!

**Comment by timyates** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-core/pull/8335
