### ISSUE TITLE
@JsonFormat ignored for deserialization when @Introspected present 

### ISSUE THREAD

**Issue by oujesky** [micronaut-projects/micronaut-core#8330]
### Expected Behavior

`@Introspected` java record should respect `@JsonFormat` when deserializing from JSON. 

### Actual Behaviour

When deserializing from JSON to a Java record containing `@JsonFormat` annotation on a field, this format is ignored when `@Introspected` annotation is present on that record, causing exception `Cannot deserialize value of type `java.time.LocalDateTime` from String "13.11.2022 22:44:55": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '13.11.2022 22:44:55' could not be parsed at index 0`.

When the `@Introspected` annotation is removed, formatter is picked up properly. Please see the test code in the "Steps To Reproduce" part - the `testNonIntrospectedThing` will pass but `testIntrospectedThing` will fail despited using the same  data type for the property and the same input. 

This seems to be already reported as #4418 and supposedly fixed later under #6546, so maybe this issue was reintroduced recently or is related to Java records specifically?  

### Steps To Reproduce

```java
package com.example;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import jakarta.inject.Inject;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.assertEquals;

@MicronautTest
public class JsonFormatIntrospectionTest {

    private static final String JSON = "{\"date\":\"13.11.2022 22:44:55\"}";
    private static final LocalDateTime EXPECTED_DATE_TIME = LocalDateTime.of(2022, 11, 13, 22, 44, 55);

    public record Thing(@JsonFormat(pattern = "dd.MM.yyyy HH:mm:ss") LocalDateTime date) {}
    
    @Introspected
    public record IntrospectedThing(@JsonFormat(pattern = "dd.MM.yyyy HH:mm:ss") LocalDateTime date) {}
    
    @Inject
    private ObjectMapper objectMapper;

    @Test
    void testNonIntrospectedThing() throws JsonProcessingException {
        var thing = objectMapper.readValue(JSON, Thing.class);
        assertEquals(EXPECTED_DATE_TIME, thing.date());
    }

    @Test
    void testIntrospectedThing() throws JsonProcessingException {
        var thing = objectMapper.readValue(JSON, IntrospectedThing.class);
        assertEquals(EXPECTED_DATE_TIME, thing.date());
    }
}
```

### Environment Information

- macOS 12.6
- JDK 17

### Version

3.7.3

**Comment by yawkat** [comment]
Nice catch! #6546 only fixed it for setters, not for creator properties (and thus not for records)
