### ISSUE TITLE
EachBean annotation does not initialize beans outside of targeting EachProperty beans

### ISSUE THREAD

**Issue by kr10n1** [micronaut-projects/micronaut-core#8332]
### Expected Behavior

EachBean annotation should initialize bean based on every class instance that was passed as an argument. It is specified in documentation that it is used mainly with EachProperty but there is no mention that it would no work in other cases.

### Actual Behaviour

From what I can tell EachBean works only in conjunction with EachProperty annotation

### Steps To Reproduce

1. Create bean instantiated by configuration properties
2. Prepare property values for said bean
3. Create a bean instantiated by EachBean annotation targeted at previous bean
4. Verify that second bean is created in application context

### Environment Information

Windows 10
OpenJDK 11

### Example Application

https://github.com/kr10n1/mockbeantest/blob/master/src/test/java/com/example/EachBeanTest.java

### Version

3.7.2

**Comment by graemerocher** [comment]
the bean requires at least a `@Named` qualifier for `@EachBean` to work

**Comment by kr10n1** [comment]
@graemerocher thanks for quick reply.

I've added that annotation to ConfigurationPropsInst class which implempents EachProp interface on which I've configured EachBean annotation in EachBeanInst class, but still there is no instance created that would be linked with ConfigurationPropsInst

**Comment by graemerocher** [comment]
fixed in 4.0.x
