### ISSUE TITLE
No Operation Subscriber

### ISSUE THREAD

**Issue by alxxyz** [micronaut-projects/micronaut-core#8334]
### Feature description

In our application we have a lot of `HttpClient` requests, which we only need to send, and not to wait for the response.

So, it will be useful to have some `NoOperationsSubscriber` which will be used on `subscribe`

```
httpClient.exchange(request).subscribe(new NoOperationsSubscriber())
```

**Comment by yawkat** [comment]
You can do `Flux.from(...).subscribe()` but you should probably have *some* error handling

**Comment by alxxyz** [comment]
How I can use `Flux` in `Micronaut` application?

**Comment by yawkat** [comment]
it's part of reactor, you can add it with https://docs.micronaut.io/latest/guide/index.html#reactor
