### ISSUE TITLE
Http client metrics are reporting 500s when declarative http client throws an exception based on unsuccessful response status codes

### ISSUE THREAD

**Issue by tomrauk** [micronaut-projects/micronaut-core#835]
The Http client metrics are reporting status of 500 when the declarative http client throws an exception. 

This is the result WebMetricsPublisher treating all exceptions as 500s and the declarative http client throwing exceptions based on unsuccessful response status codes.

This has been verified with micrometer prometheus provider.

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Turn on metrics
2. Provide a declarative http client
3. Provide a controller to call the http client
4. Call the controller endpoint with a bad request that returns a 400 status code from the http client
5. Look at the http client request metrics to verify that the status code is 500 and not the expected 400

### Expected Behaviour

I expect that http client request metrics report the actual http status code. 

### Actual Behaviour

If an exception is thrown from the declarative http client because of the http status code then the report status code in the metrics is always 500.

### Environment Information

- **Operating System**: MacOS 10.13.6 (17G65)
- **Micronaut Version: 1.0.0
- **JDK Version: 1.8.0_152

### Example Application
Example application with failing test to expose the issue with metrics.

https://github.com/tomrauk/micronaut-metrics-issue

**Comment by jameskleeh** [comment]
@tomrauk The tests failed even after fixing the issue because the test always looks at the first item and the registry appends new items.

```
        String metric = metrics.findAll() {it.startsWith('http_client_requests_seconds_sum{') && it.contains('/micronaut-projects/micronaut-core/releases/tag/v1.0.0')}.last()
```

Causes the test to pass with my changes
