### ISSUE TITLE
Missing generics annotations

### ISSUE THREAD

**Issue by andriy-dmytruk** [micronaut-projects/micronaut-core#8392]
### Expected Behavior

All annotations of type parameters of properties should be visible in Introspection.

### Problem example

Given a class:
```java
@Introspected
public class Book {
    @Size(min=2)
    private String name;

    private List<@Valid Author> authors;

    public Book(String name) {
        this.name = name;
        this.authors = null;
    }

    public Book(String name, List<Author> authors) {
        this.name = name;
        this.authors = authors;
    }

    public List<Author> getAuthors() {
        return authors;
    }

    public String getName() {
        return name;
    }
}
```
I expect to see the generics annotations in the introspection.

So the following test should run successfully:
```groovy
    void "test generic annotations present"() {
        given:
        def introspection = BeanIntrospection.getIntrospection(Book.class)
        def property = introspection.getBeanProperties().first()
        def typeParameter = property.asArgument().getTypeParameters()[0]

        expect:
        typeParameter.annotationMetadata.hasStereotype("javax.validation.Valid")
    }
```

The test fails as can be seen: https://ge.micronaut.io/s/wk26iclb54dsq

The annotations are missing from the type parameter except for the type annotations of the `Author class` (`@Introspected`).

The spec class can be found here: https://github.com/andriy-dmytruk/micronaut-validation/blob/missing-introspection/validation/src/test/groovy/io/micronaut/validation/validator/IntrospectionTest.groovy together with the relevant `Book` class.

### Version

4.0.0

**Comment by dstepanov** [comment]
Cannot reproduce this one https://github.com/micronaut-projects/micronaut-core/pull/8409 Maybe it's fixed already.
