### ISSUE TITLE
IndexOutOfBounds if (len = pos)

### ISSUE THREAD

**Issue by umaymaht** [micronaut-projects/micronaut-core#8393]
https://github.com/micronaut-projects/micronaut-core/blob/b9d08c838377810b4fca8bf40f4b6310cbda6c44/http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java#L1709

Hello,
It appears that this code is not handling the scenario where len = pos and that results in an IndexOutOfBounds Exception for us.

Thanks,
Umaymah

**Comment by yawkat** [comment]
nice catch. just to make sure, this is only an issue in error reporting, correct? there would be an error either way, but the message is misleading due to this  bug?

**Comment by umaymaht** [comment]
Thank you for your response, please see my comments in the code snippet below:

private ClientFilterChain buildChain(AtomicReference<MutableHttpRequest<?>> requestWrapper, List<HttpClientFilter> filters) {
        AtomicInteger integer = new AtomicInteger();
        int len = filters.size();  **// if filters.size is 1 for example, then len = 1**
        return new ClientFilterChain() {
            @Override
            public Publisher<? extends io.micronaut.http.HttpResponse<?>> proceed(MutableHttpRequest<?> request) {

                int pos = integer.incrementAndGet(); **// pos is assigned to 1 here, when called for the first time. Does the integer have to be incremented, before comparing it to len? **
                if (pos > len) {
                    throw new IllegalStateException("The FilterChain.proceed(..) method should be invoked exactly once per filter execution. The method has instead been invoked multiple times by an erroneous filter definition.");
                }
                HttpClientFilter httpFilter = filters.get(pos); **// Index 1 out of bounds for length 1, even though the proceed method was called the correct number of times**
                try {
                    return httpFilter.doFilter(requestWrapper.getAndSet(request), this);
                } catch (Throwable t) {
                    return Flux.error(t);
                }
            }
        };
    }

**Comment by umaymaht** [comment]
Thank you for your response, please see my comments in the code snippet below.
I apologize for the poor formatting, but github is auto formatting it, leaving with me no control.
Please view it in your IDE for a better reviewing experience.

``` java
 private ClientFilterChain buildChain(AtomicReference<MutableHttpRequest<?>> requestWrapper, List<HttpClientFilter> filters) {
        AtomicInteger integer = new AtomicInteger();
        int len = filters.size();  **// if filters.size is 1 for example, then len = 1**
        return new ClientFilterChain() {
            @Override
            public Publisher<? extends io.micronaut.http.HttpResponse<?>> proceed(MutableHttpRequest<?> request) {

                int pos = integer.incrementAndGet(); **// pos is assigned to 1 here, when called for the first time. Does the integer have to be incremented, before comparing it to len? **
                if (pos > len) {
                    throw new IllegalStateException("The FilterChain.proceed(..) method should be invoked exactly once per filter execution. The method has instead been invoked multiple times by an erroneous filter definition.");
                }
                HttpClientFilter httpFilter = filters.get(pos); **// Index 1 out of bounds for length 1, even though the proceed method was called the correct number of times**
                try {
                    return httpFilter.doFilter(requestWrapper.getAndSet(request), this);
                } catch (Throwable t) {
                    return Flux.error(t);
                }
            }
        };
    }
```

**Comment by umaymaht** [comment]
private ClientFilterChain buildChain(AtomicReference<MutableHttpRequest<?>> requestWrapper, List<HttpClientFilter> filters) {
        AtomicInteger integer = new AtomicInteger();
        int len = filters.size();  **// if filters.size is 1 for example, then len = 1**
        return new ClientFilterChain() {
            @Override
            public Publisher<? extends io.micronaut.http.HttpResponse<?>> proceed(MutableHttpRequest<?> request) {

                int pos = integer.incrementAndGet(); **// pos is assigned to 1 here, when called for the first time. Does the integer have to be incremented, before comparing it to len? **
                if (pos > len) {
                    throw new IllegalStateException("The FilterChain.proceed(..) method should be invoked exactly once per filter execution. The method has instead been invoked multiple times by an erroneous filter definition.");
                }
                HttpClientFilter httpFilter = filters.get(pos); **// Index 1 out of bounds for length 1, even though the proceed method was called the correct number of times**
                try {
                    return httpFilter.doFilter(requestWrapper.getAndSet(request), this);
                } catch (Throwable t) {
                    return Flux.error(t);
                }
            }
        };
    }

**Comment by umaymaht** [comment]
There are 2 issues here, 
1 is that the 'pos' should not be incremented preemptively because it reaches the illegal state before it is supposed to.
The 2nd issue is that the following check: 
if (pos > len) 
should ideally be:
 if (pos > = len)

**Comment by yawkat** [comment]
i think the increment coming first is actually fine. the filter with position 0 is called separately, though it's not obvious from that snippet.

agree on the comparison being wrong though

**Comment by umaymaht** [comment]
Thank you.
Can you please push the update to micronaut-http-client-2.2.0 or at least, micronaut-http-client-2.2.2?

**Comment by yawkat** [comment]
No, it will not be backported
