### ISSUE TITLE
Unwanted initialization at build time

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-core#8511]
### Issue description

It seems that Micronaut Data (using the snapshot from `prepare-mn4` branch) in combination with Micronaut 4 causes unwanted initialization at runtime of a couple classes:

- [ReflectionUtils](https://ge.micronaut.io/s/4nwocet5fiyy6/tests/:functional-tests:test/io.micronaut.gradle.testresources.TestResourcesWithAotAndGraalVMSpec/runs%20optimized%20binary?focused-execution=1&page=eyJvdXRwdXQiOnsiMCI6Mn19&top-execution=1#L208-L227)
- [io.micronaut.data.runtime.criteria.$RuntimeCriteriaBuilder$Definition$Reference](https://ge.micronaut.io/s/4nwocet5fiyy6/tests/:functional-tests:test/io.micronaut.gradle.testresources.TestResourcesWithAotAndGraalVMSpec/runs%20optimized%20binary?focused-execution=1&page=eyJvdXRwdXQiOnsiMCI6Mn19&top-execution=1#L229-L245)

The links above include the initialization stack traces.

**Comment by graemerocher** [comment]
think this might need to be fixed in core. Either the usage of these classes should be removed (probably the best):

https://github.com/micronaut-projects/micronaut-core/blob/139621446b8360d5b2e00e23b18ce61fb7ab06be/core/src/main/java/io/micronaut/core/graal/GraalReflectionConfigurer.java#L26-L27

Or they need to be declared to be initialized at build time.

**Comment by dstepanov** [comment]
What is pulling `RuntimeCriteriaBuilder`?

**Comment by melix** [comment]
It comes from our `ServiceLoaderFeature`. I am not particularly well aware of what it's supposed to do, but the build time initialization happens because of this line:

https://github.com/micronaut-projects/micronaut-core/blob/79c56c65b40ca361904f2a723041379b15c7f26f/core/src/main/java/io/micronaut/core/graal/ServiceLoaderInitialization.java#L84
