### ISSUE TITLE
Upgrade to Jakarta EE 10 and Java 17

### ISSUE THREAD

**Issue by hantsy** [micronaut-projects/micronaut-core#8556]
### Feature description

Currently most of the Microant modules are based on JavaEE 8/Jakarta EE 8, Jakarta EE 10 was released for a long time, and the latest Spring 6/Spring Boot 3.0 has already upgraded to Jakarta EE9/10 and Java 17. 

I think in the next generation 4.0 Micronaut should consider the alignment of Jakarta EE 10 and Java 17.

Upgrade all modules to use new `jakarta.`. 

* Jakarta Common Annotations 
* Jakarta Bean Validation 3.0
* Jakarta Persistence 3.1.0
* Implements CDI Lite 4.0
* Jakarta Transaction 2.0
* JSON-B/JSON-P as Jackson alternatives

Use Java 17 as base line to build Micronaut projects, consider more integration with new features in Java 17, such as Record, HttpClient(since Java 11) etc.

**Comment by sdelamo** [comment]
@hantsy Thanks for the feedback. Current plan is to have Micronaut Framework 4 with Java 17 as a baseline. 

We have been upgrading as much as possible to use `jakarta.` as well. 

moving this to discussions.
