### ISSUE TITLE
Support annotation based CORs Configuration

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#8558]
### Feature description

Support CORs configuration via annotation. For example, it will enable Micronaut developers only to allow CORS for a few routes in their applications. Thus, having more secure applications. 

It will also ease people migrating from Spring Framework to the Micronaut framework. Thus, find a similar replacement to [Spring's CrossOrigin](https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/web/bind/annotation/CrossOrigin.java)

I think we will need the following steps: 

Create an annotation. E.g. `@CrossOrigin` whose members map [`CorsOriginConfiguration's`](https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/http-server/src/main/java/io/micronaut/http/server/cors/CorsOriginConfiguration.java) fields. 

Enable `Corsfilter` by default by removing this line: 

https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/http-server/src/main/java/io/micronaut/http/server/cors/package-info.java#L23

Create a method that returns an  [`@NonNull  Optional<CorsOriginConfiguration> getCorsOriginConfigurationForRequest(@NonNull HttpRequest<?> request)`](https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/http-server/src/main/java/io/micronaut/http/server/cors/CorsOriginConfiguration.java).  We can [obtain the `RouteMatch` of a request](https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/filters/SecurityFilter.java) and [get the annotation contents if the method has the `@CrossOrigin` annotation](https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/rules/SecuredAnnotationRule.java#L65-L68).

The [`CorsFilter::getConfiguration`](https://github.com/micronaut-projects/micronaut-core/blob/4.0.x/http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java#L212-L218) should first look for configuration coming from an annotation in the route match.

**Comment by sdelamo** [comment]
@micronaut-projects/core-developers anyone thinks this is a bad idea?

**Comment by melix** [comment]
The only thing I'm seeing as a potential breaking change is enabling CORS by default. Maybe target 4.0?

**Comment by sdelamo** [comment]
> The only thing I'm seeing as a potential breaking change is enabling CORS by default. Maybe target 4.0?

I think we should target MN 3. we could use the `enabled` property to behave the same way if enabled is false. In that scenario, annotation based will work. But if you don't have any annotation or it is not enabled the filter will just do chain.proced(request)`
