### ISSUE TITLE
Multiple InterceptorRegistries when testing AOT module in micronaut-security

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-core#8581]
When we re-enable the AOT module for Micronaut Security (for Micronaut 4.0.0) and add the test back in, we get an error

https://github.com/micronaut-projects/micronaut-security/pull/1193

```
Distributed Test Run :security-aot:test > Partition 1 in session 1 on localhost-executor-1 > OpenIdProviderMetadataFetcherCodeGeneratorSpec verify OpenIdProviderMetadataFetcherCodeGenerator generates OpenIdProviderMetadataFetcher per openid client FAILED

  io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.serde.support.DefaultSerdeIntrospections]

  Message: Multiple possible bean candidates found: [InterceptorRegistry, InterceptorRegistry]
```

https://ge.micronaut.io/s/osvthaiic6lti/console-log?task=:security-aot:test

I seem to recall this is caused by having two different versions of micronaut-aop on the test runtime classpath, however I cannot see that

https://ge.micronaut.io/s/osvthaiic6lti/dependencies?dependencies=aop&expandAll&toggled=W1syLDNdLFsyLDJdLFsyLDFdLFsyLDBdLFsxXSxbMF0sWzNdLFs0XSxbNV0sWzZdLFs3XSxbOF0sWzldLFsxMF0sWzExXSxbMTJdLFsxM10sWzE0XSxbMTVdLFsxNl0sWzE3XV0

Do you have any idea what's wrong?

As an aside, a way of showing where beans were created in the case there are multiple in error would be awesome 😉

**Comment by sdelamo** [comment]
@timyates I think this is done. Closing it. Please reopen it if not.
