### ISSUE TITLE
@Inject annotation in K8s module doesn't work properly

### ISSUE THREAD

**Issue by n0tl3ss** [micronaut-projects/micronaut-core#8593]
### Expected Behavior

In this line: https://github.com/micronaut-projects/micronaut-kubernetes/blob/prepare-for-mn4/test-utils/src/main/groovy/io/micronaut/kubernetes/test/KubernetesSpecification.groovy#L46

```
  @Shared
    @AutoCleanup
    @Inject
    KubernetesOperations operations
```
when running test `KubernetesOperations operations` should be injected.

### Actual Behaviour

It gives next error:
```
Cannot get property 'client' on null object
java.lang.NullPointerException: Cannot get property 'client' on null object
	at io.micronaut.kubernetes.test.KubernetesSpecification.setupSpec(KubernetesSpecification.groovy:70)
```

because operations is null.

### Steps To Reproduce

1. Clone https://github.com/micronaut-projects/micronaut-kubernetes/
2. switch to `prepare-for-mn4` branch for micronaut v4
3. Try to run `HelloControllerSpec` test

### Version

4.0.0-SNAPSHOT

**Comment by n0tl3ss** [comment]
If something helps. For some reason IntelliJ in debugger uses `3.7.0` version instead of `4.0.0-SNAPSHOT` but there is no mention of `3.7.0` inside Kubernetes module and there is not mention even with `./gradlew dependencies`
<img width="686" alt="Screenshot 2023-01-27 at 16 05 07" src="https://user-images.githubusercontent.com/44323106/215124097-a6a7c2fc-1e65-425b-8bf8-878281d0225d.png">

**Comment by alvarosanchez** [comment]
The spec is not a `@MicronautTest`. I have never seen `@Inject` without `@MicronautTest`

**Comment by alvarosanchez** [comment]
Oh wait, it's an abstract parent class, in that case, forget about my last comment
