### ISSUE TITLE
logback configuration defined via JAVA_TOOL_OPTIONS is ignored

### ISSUE THREAD

**Issue by vekonypeter** [micronaut-projects/micronaut-core#8596]
### Expected Behavior

When the path to the `logback.xml` file is defined in the `JAVA_TOOL_OPTIONS` environment variable (like e.g.: `JAVA_TOOL_OPTIONS=-Dlogback.configurationFile=/path/to/logback-external.xml`) this configuration should be used

### Actual Behaviour

The external logback XML file is used as expected until the end of the bean registration phase. From that point, the framework switches back to the default `logback.xml` file placed under the resources folder.

This behaviour was introduced in PR https://github.com/micronaut-projects/micronaut-core/pull/8238, it's caused by this method: https://github.com/micronaut-projects/micronaut-core/blob/3.8.x/management/src/main/java/io/micronaut/management/endpoint/loggers/impl/LogbackLoggingSystem.java#L135-L149

### Steps To Reproduce

1. define e.g. `logback-external.xml` file either in the resources folder or anywhere else. Make sure that it logs somehow differently than the default `logback.xml`.
2. run the application with `JAVA_TOOL_OPTIONS=-Dlogback.configurationFile=/path/to/logback-external.xml` environment variable
3. configuration defined in `logback-external.xml` is ignored once the application started up

### Environment Information

- Micronaut version: 3.8.0 - everything works fine below that
- Operating system: MacOS
- JVM: Temurin-17.0.5+8

### Version

3.8.0

**Comment by adamkobor** [comment]
seems to be that https://github.com/micronaut-projects/micronaut-core/pull/8238 was the change that breaks this

**Comment by driverpt** [comment]
Try to set `-Dlogger.config=/path/to/logback-external.xml`.

**Comment by adamkobor** [comment]
@driverpt Unfortunately this doesn't work if the config file is not on your classpath (e.g. attached through a volume in the container)

**Comment by ckosmowski** [comment]
This is also a real issue for us because we use this feature to inject logback configuration in a kubernetes environment and with an update to 3.8.x the services won't start up anymore complaining about logback.xml is mssing.

**Comment by albrechtflo-hg** [comment]
I checked out the `LogbackUtils` code which loads the config into Logback, and I really cannot understand why this is limited to the Classpath. The resource is mapped to a URL anyway in that class, so why not use just a little cleverer approach to look up the resource?
@driverpt @graemerocher  This should really be looked into, as it really is a huge regression when upgrading Micronaut.
