### ISSUE TITLE
Methods annotated with aop annotation in Handler class are not triggering method interceptor

### ISSUE THREAD

**Issue by marcin-majewski-sonarsource** [micronaut-projects/micronaut-core#8599]
### Expected Behavior

We use Micronaut and we started recently to use AOP for our AWS Lambdas. One of the use cases is to annotate handler methods with annotation (used for e.g for logging and monitoring purposes). Unfortunately, when one of the methods of the top handler class is annotated, the method interceptor is not triggered.

I would expect this piece of code to invoke an interceptor that is registered with `@ExampleAopAnnotation` but it does not happen:
```java
public class FunctionRequestHandler extends MicronautRequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {
  @Inject
  ObjectMapper objectMapper;

  @Inject
  Service service;

  @Override
  public APIGatewayProxyResponseEvent execute(APIGatewayProxyRequestEvent input) {
    APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent();
    try {
      //this will return not-intercepted
      //String json = objectMapper.writeValueAsString(Collections.singletonMap("message", methodToBeIntercepted()));

      //this will return intercepted
      String json = objectMapper.writeValueAsString(Collections.singletonMap("message", service.methodToBeIntercepted()));

      response.setStatusCode(200);
      response.setBody(json);
    } catch (JsonProcessingException e) {
      response.setStatusCode(500);
    }
    return response;
  }

  @ExampleAopAnnotation
  public String methodToBeIntercepted() {
    return "not-intercepted";
  }
```  
  
 I am not sure if this is expected behaviour, it is a bug in micronaut-aop or in micronaut-function-aws.

### Actual Behaviour

Method interceptor is not called

### Steps To Reproduce

1. Annotate the method with AOP annotation in lambda handler (in other words: in class that extends `MicronautRequestHandler`)
2. The method interceptor is not called

### Environment Information

JDK 11

### Example Application

https://github.com/marcin-majewski-sonarsource/aop-issue-reproducer

### Version

3.8.0

**Comment by graemerocher** [comment]
unfortunately I don't think the handler itself can be AOP intercepted since Lambda infrastructure instantiates this directly
