### ISSUE TITLE
Add no-args build() to Micronaut class.

### ISSUE THREAD

**Issue by RaviH** [micronaut-projects/micronaut-core#860]
`Micronaut` class extends `DefaultApplicationContextBuilder`. `Micronaut` has a method `build` that takes varags of `String` but doesn't provide a `build` method with no args. 

For the code below: `DefaultApplicationContextBuilder` takes over and returns `ApplicationContext`
```
 Micronaut.build()
                .environments(System.getProperty("archaius.deployment.environment"))
                .start();
```

So to get `Micronaut` I have to: provide empty string so that I call `Micronaut`'s `build` vs `DefaultApplicationContextBuilder`'s `build`.

```
 Micronaut.build("")
                .environments(System.getProperty("archaius.deployment.environment"))
                .start();
```

Please add a no-args `build` to Micronaut so that it overrides parent `DefaultApplicationContextBuilder`'s build.

**Comment by jameskleeh** [comment]
The `Micronaut#build` method is static, so it cannot be confused with the one in the parent

`Micronaut.build() instanceof Micronaut` returns true

**Comment by RaviH** [comment]
@jameskleeh @graemerocher I am sorry, I should have provided a an example project reproducing the issue. Please find attached: 
[micronaut-build-example.zip](https://github.com/micronaut-projects/micronaut-core/files/2559630/micronaut-build-example.zip)

![image](https://user-images.githubusercontent.com/141136/48167382-66138480-e2a0-11e8-8e87-3b7e43f6b3b6.png)

As shown in the screenshot above: I cannot compile via `maven`.

I am hoping I am not missing something obvious.

**Comment by jameskleeh** [comment]
@RaviH Looks like a bug with the maven compiler plugin. You can pass `null` to the build method
