### ISSUE TITLE
Reactor code different behaviour in 3.7.3 and 3.8.0

### ISSUE THREAD

**Issue by n0tl3ss** [micronaut-projects/micronaut-core#8600]
### Expected Behavior

Test in demo application should pass. if you change Micronaut version in `gradle.properties` to 3.7.3 test passes.
Both 3.7.3 and 3.8.0 version uses same `micronaut-tracing` (4.4.0). 

### Actual Behaviour

Test fails.

### Steps To Reproduce

1. Clone demo app
2. Run test

### Example Application

https://github.com/n0tl3ss/tracing-demo

### Version

3.8.0

**Comment by graemerocher** [comment]
@yawkat @dstepanov were there changes in 3.8 reactive code paths?

**Comment by dstepanov** [comment]
The code paths changes are in v4

**Comment by yawkat** [comment]
yea this is likely one of my changes, i will take a look

**Comment by driverpt** [comment]
I've tried forcing `reactor-core:3.5.2` but no success. Reactor 3.5.2 adds some extra Reflection Hints

**Comment by yawkat** [comment]
actually this was caused by https://github.com/reactor/reactor-core/commit/88587fc64b486ed04b15cac2081c01623a5b1c57#diff-27b3a7edb375bd47e0dfc6da6b5aac669f19fccdf3f73fcba0a999171b56906d

Since that change, MonoCallable (the one used in TestController) only calls the callable on the first subscription.request, not on publisher.subscribe. Unfortunately we relied on the old behavior, ScopePropagationPublisher wraps lots of things, but not subscription.request. I think changing this will fix the regression. @n0tl3ss do you want to try a patch or should I?

imo this whole thread local approach is super brittle and will lead to further breakage in the future. but not sure we can do much about it.

**Comment by yawkat** [comment]
fyi @driverpt i dont know your actual bug, but you can work around the issue by using defer instead of fromCallable:

```patch
Index: src/main/java/com/example/TestController.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/com/example/TestController.java b/src/main/java/com/example/TestController.java
--- a/src/main/java/com/example/TestController.java	(revision e1d16086414c7904bb257a96c1fd1d8f5914f097)
+++ b/src/main/java/com/example/TestController.java	(date 1673874094664)
@@ -18,11 +18,11 @@
     @Get("/{name}")
     HttpResponse<Publisher<String>> responseRx(String name) {
         return HttpResponse.ok(Publishers.map(
-                Mono.fromCallable(() -> {
+                Mono.defer(() -> {
                     if (tracer.activeSpan() != null) {
                         tracer.activeSpan().setTag("foo", "bar");
                     }
-                    return name;
+                    return Mono.just(name);
                 }
             ), (n->n)));
     }
```

**Comment by driverpt** [comment]
I don't use `Mono.defer()`, I have an issue with Micronaut AWS API Proxy. By adding debug code, i notice that my Controller is properly invoked and response returned, and for some reason it stops logging stuff in `MicronautLambdaContainerHandler` 

https://github.com/micronaut-projects/micronaut-aws/blob/master/function-aws-api-proxy/src/main/java/io/micronaut/function/aws/proxy/MicronautLambdaContainerHandler.java#L374-L400

Issue: https://github.com/micronaut-projects/micronaut-aws/issues/1568

**Comment by n0tl3ss** [comment]
@yawkat I can do it but not sure how to wrap `subscription.request` :) I am not so good with java reactive (reactor). If you can provide me with an example that would be nice.

**Comment by yawkat** [comment]
@n0tl3ss something like this should be enough:

```java
       new Subscription() {
           @Override
           public void request(long n) {
               try (Scope ignored = tracer.scopeManager().activate(span)) {
                   s.request(n);
               }
           }

           @Override
           public void cancel() {
               try (Scope ignored = tracer.scopeManager().activate(span)) {
                   s.cancel();
               }
           }
       };
```

and pass that to `actual.onSubscribe(s);` instead.

**Comment by yawkat** [comment]
@driverpt sorry i thought that you had this issue since you commented, but i dont think https://github.com/micronaut-projects/micronaut-aws/issues/1568 is related.

**Comment by driverpt** [comment]
Since it depends on Core, it might be indirectly related

**Comment by n0tl3ss** [comment]
Thanks @yawkat :)
