### ISSUE TITLE
Apply instrumentation to ExecutionFlow.async

### ISSUE THREAD

**Issue by yawkat** [micronaut-projects/micronaut-core#8617]
### Issue description

For reactor, `ReactorInstrumentation` (in micronaut-runtime in 3.x, moved to micronaut-reactor for 4.x) takes care of propagating the instrumentation to worker threads when we use `subscribeOn`. However `ExecutionFlow.asyncOn` does not do similar instrumentation propagation, so switching threads loses the instrumentation information.

This leads to a test failure in https://github.com/micronaut-projects/micronaut-tracing/pull/213 : MDCReactorSpec sets the MDC in a filter, and the MDC used to be propagated by `MdcInstrumenter` to the worker thread (the controller that checks the MDC has `@ExecuteOn`). Now that we use `ExecutionFlow.async` instead, the MDC is not propagated and the test fails.

We need something like ReactorInstrumentation for ExecutionFlow. ReactorInstrumentation is a bit ugly though, it sets reactor global state (`Schedulers.onScheduleHook`). We should avoid this, but this would also require context information for `ExecutionFlow.async`. So I think we should move `ExecutionFlow.async` into a singleton bean that does the instrumation, and delete the current static `ExecutionFlow.async`. WDYT @dstepanov?

**Comment by dstepanov** [comment]
Do it if you think it's needed for now. I'm planning to start working on a new propagation API soon, which should replace the instrumentations directly.

**Comment by yawkat** [comment]
do you think it will be ready for 4.0.0? in that case i would skip this, thread local propagation is a PITA anyway...

**Comment by dstepanov** [comment]
I'm planning it for v4

**Comment by sdelamo** [comment]
@dstepanov @yawkat what is the status of this issue?

**Comment by sdelamo** [comment]
ping @dstepanov @yawkat what is the status of this issue?

**Comment by dstepanov** [comment]
I think this can be closed
