### ISSUE TITLE
Deprecate `ConversionService.SHARED` in Micronaut 3.9, for removal in Micronaut 4

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#8620]
### Issue description

Deprecate in Micronaut 3.9, for removal in Micronaut 4

**Comment by alvarosanchez** [comment]
Didn't we agree to deprecate in 3.9 and remove in 4?

**Comment by wetted** [comment]
> Didn't we agree to deprecate in 3.9 and remove in 4?

I was wondering about that too. I thought we did. @sdelamo ?

**Comment by sdelamo** [comment]
Yes, 3.9.x

**Comment by sdelamo** [comment]
Closed via https://github.com/micronaut-projects/micronaut-core/pull/8695
