### ISSUE TITLE
Micronaut war fails to start under WebLogic 12c

### ISSUE THREAD

**Issue by mattmoss** [micronaut-projects/micronaut-core#8636]
### Expected Behavior

A Micronaut war file should deploy successfully to Oracle WebLogic 12c.

### Actual Behaviour

The application fails to start because it cannot find a `ApplicationEventPublisher` bean. This bean cannot cannot be created, because the startup process (via `SoftServiceLoader`) fails to find and instantiate the `ApplicationEventPublisherFactory`.

Please see the README file in the sample repository for full details on the application behavior.

Note that this may or may not be the only issue in getting a Micronaut war working in WebLogic 12c; it's certainly the first issue and affects many beans/Micronaut services.

### Steps To Reproduce

I created a default Micronaut 3.5.4 application with `mn create-app demo.weblogic-war` and only a few minor changes to `build.gradle`. I then built a war file and attempted to deploy to Oracle WebLogic 12c.

Please see the README file in the sample repository for full details to reproduce.

### Environment Information

- WebLogic 12c (running in docker)
- Java 8
- Micronaut 3.5.4

### Example Application

https://github.com/mattmoss/weblogic-war

### Version

3.5.4

**Comment by cfaoliv** [comment]
The same issue happens in newer weblogic versions. We tested in Weblogic 14.1 and had the same problem

**Comment by mattmoss** [comment]
Assuming the patch is accepted, there is a conflict between Micronaut-provided jackson libs and those provided by WebLogic (at least in 12c). To deal with this, `weblogic.xml` should include:
```
<prefer-application-packages>
    <package-name>com.fasterxml.*</package-name>
</prefer-application-packages>
```

**Comment by sdelamo** [comment]
> <prefer-application-packages>
>     <package-name>com.fasterxml.*</package-name>
> </prefer-application-packages>

should `weblogic.xml` be placed should be place in `src/main/resources`. Can you included in the sample application?

**Comment by mattmoss** [comment]
> should `weblogic.xml` be placed should be place in `src/main/resources`. Can you included in the sample application?

I updated the sample application with a `weblogic.xml` file and a simple controller for testing which, once things are running, should be accessible at `http://localhost:7001/weblogic-war-0.1` (given the instructions in the README).

**Comment by mattmoss** [comment]
I re-tested my sample project using the 3.5.6 release; looks good!

**Comment by mattmoss** [comment]
This worked for WebLogic on Linux in a docker container, but failed WebLogic on Windows. Will be pushing a minor tweak for fix that.

**Comment by mattmoss** [comment]
Verified working under WebLogic/Windows with 3.5.7 release.
