### ISSUE TITLE
Logback can configure only from XML since 3.8.0

### ISSUE THREAD

**Issue by te5in** [micronaut-projects/micronaut-core#8650]
### Expected Behavior

According to the [documentation of Logback ](https://logback.qos.ch/manual/configuration.html#auto_configuration), Logback can be configured either **programmatically** or with a configuration script expressed in XML or Groovy format.

> 1. Logback will search for any custom [Configurator](https://logback.qos.ch/xref/ch/qos/logback/classic/spi/Configurator.html) providers using [service-provider loading facility](http://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html) (introduced in JDK 1.6). If any such custom provider is found, it takes precedence over logback's own DefaultJoranConfigurator.
> 2. If no custom Configurator was found in the previous step, then [DefaultJoranConfigurator](https://github.com/qos-ch/logback/blob/master/logback-classic/src/main/java/ch/qos/logback/classic/util/DefaultJoranConfigurator.java) will be instantiated and invoked.

### Actual Behaviour

With providing default LoggingSystem "logback.xml" in [LogbackLoggingSystem](https://github.com/micronaut-projects/micronaut-core/blob/3fe132aa1cb8d937a73936d1940dd77181530355/management/src/main/java/io/micronaut/management/endpoint/loggers/impl/LogbackLoggingSystem.java#L57) constructor there is no way to configure logback programmatically.

**Comment by graemerocher** [comment]
broken by https://github.com/micronaut-projects/micronaut-core/commit/214051e4b5f12ff3f2626a8e535614f40b61ff02 looks like it

**Comment by sdelamo** [comment]
We have two issues ( #8678 #8679 ) with Logback and with custom configuration in Micronaut Framework 3.8. 

However, having both a `logback.xml` and a custom configuration and the custom configuration take precedence does not work with Micronaut 3 (logback 1.2.11) but it works with Micronaut Framework 4.0 (logback 1.4.5)

see: 

https://github.com/grails-core-issues-forks/micronaut-core-8650

**Comment by timyates** [comment]
@te5in Can you check if this is fixed in Micronaut 3.8.4

**Comment by te5in** [comment]
@timyates yep, its working now, thx

**Comment by timyates** [comment]
Awesome news 👍 

Fixed by https://github.com/micronaut-projects/micronaut-core/pull/8674
