### ISSUE TITLE
MN4: Update docs in core and modules to point to jdk17 api docs

### ISSUE THREAD

**Issue by wetted** [micronaut-projects/micronaut-core#8705]
### Issue description

In some places we link to the jdk api docs

For Micronaut 4.0.x core and all the modules (where applicable), instead of gradle.properties with:
`jdkapi=https://docs.oracle.com/javase/8/docs/api`
and asciidocs links to jdk api docs (e.g.)
`link:{jdkapi}/java.base/java/util/...` 

We should use:
`jdkapi=https://docs.oracle.com/en/java/javase/17/docs/api`
and 
`link:{jdkapi}/java.base/java/util/...`

**Comment by sdelamo** [comment]
@wetted what is the status of this?

**Comment by wetted** [comment]
I should check all the modules. I have corrected it it some places, but I haven't checked everywhere.

**Comment by wetted** [comment]
The following PRs cover everything that remained of jdk8 links in docs. 

cache: https://github.com/micronaut-projects/micronaut-cache/pull/599
core: https://github.com/micronaut-projects/micronaut-core/pull/9358
gcp: https://github.com/micronaut-projects/micronaut-gcp/pull/847
sql: https://github.com/micronaut-projects/micronaut-sql/pull/909
