### ISSUE TITLE
Remove flakiness of BinaryWebSocketSpec

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#8718]
This test `io.micronaut.http.server.netty.websocket.BinaryWebSocketSpec` `test binary websocket exchange` is flaky when executed in a suite :

https://ge.micronaut.io/scans/tests?search.timeZoneId=Europe/Madrid&tests.container=io.micronaut.http.server.netty.websocket.BinaryWebSocketSpec&tests.test=test%20binary%20websocket%20exchange

**Comment by timyates** [comment]
Done in https://github.com/micronaut-projects/micronaut-core/pull/8725
