### ISSUE TITLE
Missing docs for KSP (Kotlin Symbol Processing API﻿) support

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#8730]
[PR introducing KSP did not introduced any docs about it](https://github.com/micronaut-projects/micronaut-core/pull/8462/files). 

Reference: 
[Kotlin Symbol Processing API﻿](https://kotlinlang.org/docs/ksp-overview.html)

**Comment by graemerocher** [comment]
Still working on the Gradle plugin so will take some time
