### ISSUE TITLE
Localhost Bound Server Blocks CORS Requests for other origins

### ISSUE THREAD

**Issue by tmapes** [micronaut-projects/micronaut-core#8749]
### Expected Behavior

1. Server running bound to `127.0.0.1:8080`
    1. CORS disabled (`micronaut.server.cors.enabled` unset or false)
3. Reverse Proxy Application running on same VM but accepting traffic on 0.0.0.0:80
4. CORS related request is sent with a load balancer URL that is eventually forwarded to the Proxy container
5. Proxy container performs successful CORS validation and forwards API call to 127.0.0.1:8080 with the `Origin` header set to the previously mentioned load balancer hostname
6. Micronaut processes requests as normal

### Actual Behaviour

1. Server running bound to `127.0.0.1:8080`
    1. CORS disabled (`micronaut.server.cors.enabled` unset or false)
3. Reverse Proxy Application running on same VM but accepting traffic on 0.0.0.0:80
4. CORS related request is sent with a load balancer URL that is eventually forwarded to the Proxy container
5. Proxy container performs successful CORS validation and forwards API call to 127.0.0.1:8080 with the `Origin` header set to the previously mentioned load balancer hostname
6. Micronaut responds with a 403 with no visible logging (unless TRACE is enabled)
    1. I believe this is related to #8582

### Steps To Reproduce

1. Run a Micronaut web service bound to 127.0.0.1
2. Make an OPTIONS request against the service with origin set to something other than localhost

### Environment Information

- Linux (x86_64) / macOS (ARM)
- JDK 11

### Version

3.8.3

**Comment by tmapes** [comment]
Ideally the Micronaut server wouldn't care about the CORS validation in this scenario as my 'sidecar' reverse proxy application would've already validated the request before forwarding it onward.

**Comment by graemerocher** [comment]
@timyates could you take a look?

**Comment by timyates** [comment]
Fixed in 3.8.5 https://github.com/micronaut-projects/micronaut-core/pull/8751

There will be a new configuration, so setting `micronaut.server.cors.localhost-pass-through: true` will allow the described usage

Thanks for reporting @tmapes 👍

**Comment by tmapes** [comment]
Thanks for the quick turnaround @timyates!
