### ISSUE TITLE
Micronaut 3.8.4 application can't start when used in combination with Logback > 1.2.11

### ISSUE THREAD

**Issue by ljpengelen** [micronaut-projects/micronaut-core#8758]
### Expected Behavior

A Micronaut application that is used in combination with a recent version of Logback should start.

### Actual Behaviour

Starting from version 3.8.4, such applications will no longer start.

Changes introduced in https://github.com/micronaut-projects/micronaut-core/pull/8674 are not compatible with recent versions of Logback.

### Steps To Reproduce

1. Start a new Micronaut 3.8.4 project using the generator.
2. Observe that the generated Micronaut test passes.
3. Add a recent version of logback as a dependency, for example `runtimeOnly "ch.qos.logback:logback-classic:1.4.5"`
4. Observe that the generated Micronaut test no longer passes.

### Environment Information

I'm using a Mac with Java 17, but I don't think that's relevant.

### Example Application

https://github.com/ljpengelen/micronaut-3.8.4-logback-1.4.5

### Version

3.8.4

**Comment by sdelamo** [comment]
Micronaut Framework 3 is built with Logback 1.2.11. Lets see what e can do. There are breaking changes between Logback 1.2.11 and 1.4.5
