### ISSUE TITLE
Document breaking changes to annotation API

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#8775]
### Issue description

The annotation metadata APIs have been changed to return default values when previously they did not. We need to document this change and any other breaking changes to the way the annotation API works.

**Comment by Blueclaus13** [comment]
Could I contribute to this issue?  I'm new to open source and would like to work on an issue, thanks!

**Comment by sdelamo** [comment]
@dstepanov @graemerocher is this something you can do?

**Comment by sdelamo** [comment]
@dstepanov @graemerocher is this done? are we planning to do this?

**Comment by sdelamo** [comment]
I assume we are not going to document anything.
