### ISSUE TITLE
Content-Type not set via produces attribute of @Read

### ISSUE THREAD

**Issue by semeiser** [micronaut-projects/micronaut-core#883]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

Define an endpoint with a `@Read` method, set the `produces` attribute to desired content type, e.g.:
```groovy
@Endpoint(id = 'produces', defaultSensitive = false, defaultEnabled = true)
class ProducesEndpoint {

    String myValue = 'init'

    @Read
    @Produces(MediaType.TEXT_PLAIN)
    String value() {
        "test $myValue"
    }

    @Read(produces = MediaType.TEXT_PLAIN)
    String named(@Selector String name) {
        "test $name"
    }
}
```

### Expected Behaviour

Both Methods should set content-type to `text/plain`.

### Actual Behaviour

The second method with `@Read(produces = MediaType.TEXT_PLAIN)` has the default content-type of `application/json`, see `com.example.ProducesEndpointSpec` in the linked example repository.

### Environment Information

- **Operating System**: macOS 10.14
- **Micronaut Version:** 1.0.0
- **JDK Version:** 1.8.0_191

### Example Application

https://github.com/semeiser/mn-endpoints-media-type-error

**Comment by jameskleeh** [comment]
Thanks for the excellent issue report!
