### ISSUE TITLE
Make the DefaultHttpClient exception customizable 

### ISSUE THREAD

**Issue by jntakpe** [micronaut-projects/micronaut-core#8896]
### Feature description

As of now the `DefaultHttpClient` will wrap errors in a `HttpClientResponseException` which is perfectly fine by default. 
Nevertheless, in some companies, HTTP errors always have the same format and should be mapped to a `CustomException` that includes the custom payload fields. As far I know, to do so we need to wrap all the `HttpClient` calls in `try - catch` blocks or call `onErrorMap` to map the `HttpClientResponseException` in `CustomException` which is is cumbersome and error prone.
I would like to be able to customize the`DefaultHttpClient` to be able to map once for all the `HttpClientResponseException` into my `CustomException`.

If I had to do it, my proposal would be to have the method`DefaultHttpClient#customizeException(HttpClientException exc)` calling an instance variable of type `Function<E extends HttpClientException, O extends RuntimeException>` to perform exception mapping, if needed. By default, the function would simply call `Function.identity()`.

**Comment by graemerocher** [comment]
you can do this with an `HttpClientFilter`

**Comment by jntakpe** [comment]
Ok thanks for the advice

**Comment by mplanchant** [comment]
@graemerocher do you have an example of this?
