### ISSUE TITLE
Header name being modified before http call

### ISSUE THREAD

**Issue by jvictorcf** [micronaut-projects/micronaut-core#8908]
### Expected Behavior

We have an openapi spec that we've passed through the java-micronaut-client generator.
It generates the following header in the interface method:
`@Header(name="WCToken") @NotNull String wcToken`

When we use this interface, we expect the http header to have the name "WCToken" as per the annotation.

### Actual Behaviour

However, what happens is that the header name is modified by micronaut and becomes a hyphenised version of the parameter name. It becomes "wc-token".

I've done some debugging of the micronaut classes, so I'll provide some information that may be useful:
When we call the generated interface, it is intercepted by HttpClientIntroductionAdvice.
Because a custom binder is not found, this Header annotation is processed by the DefaultHttpClientBinderRegistry.
The "byAnnotation" field with the key of "Header.class" is used for getting the header name. It looks for the annotation's value (which is null, as the generator has set the name, not the value). Because it's null, the binderRegistry uses the parameter name as the basis for the http header.

### Steps To Reproduce

1. Create an interface that uses the @Client annotation
2. Create a method representing an endpoint
3. Create a parameter in this method with the annotation @Header(name = "ABC")
4. Make this parameter have a completely different name (like xyz)
5. Enable the trace logs for the "io.micronaut.http.client" package.
6. You'll see the header is sent as "xyz", not as "ABC"

### Environment Information

- Operation system: MacOS 11.7.2
- JDK Version: 18

### Version

3.8.5

**Comment by jfsanchez91** [comment]
I guess the Header class documentation is clear about this:
```
/**
 * If used as a bound parameter, this is the header name. If used on a class level this is value and not the header name.
 * @return The name of the header, otherwise it is inferred from the parameter name
 */
@AliasFor(annotation = Bindable.class, member = "value")
String value() default "";
```
as you are using the Header as a bound parameter, the `value` (and not the `name`) is the one chosen.

**Comment by jfsanchez91** [comment]
I guess the issue is actually in that generator, because the Header javadoc is clear about that:
```java
/**
 * If used as a bound parameter, this is the header name. If used on a class level this is value and not the header name.
 * @return The name of the header, otherwise it is inferred from the parameter name
 */
@AliasFor(annotation = Bindable.class, member = "value")
String value() default "";
```
when you use the Header as a bound parameter, the `value` (and not the `name`) will be used as the header name.

**Comment by jvictorcf** [comment]
Makes sense, @jfsanchez91.
I'll create an issue at the generator's repository.

Thank you.

**Comment by jvictorcf** [comment]
For those with the same issues, I've opened an issue with the openapi code generator: https://github.com/OpenAPITools/openapi-generator/issues/15015
