### ISSUE TITLE
Ensure Logging System is always refreshed

### ISSUE THREAD

**Issue by driverpt** [micronaut-projects/micronaut-core#8918]
### Expected Behavior

Logging System to be refreshed everytime application starts and Context is Refreshed

### Actual Behaviour

Only happens if `logger.levels` property is defined

### Version

3.8.7

**Comment by driverpt** [comment]
This is causing a Serverless Function (Non-Native, AWS java11 runtime) not to log anything

**Comment by sdelamo** [comment]
> This is causing a Serverless Function (Non-Native, AWS java11 runtime) not to log anything

do you have sample app which reproduce this?

**Comment by driverpt** [comment]
Give me a couple of hours to create Sample App. In the meanwhile I've already created a PR with a Test Reproducing this issue

**Comment by sdelamo** [comment]
> This is causing a Serverless Function (Non-Native, AWS java11 runtime) not to log anything

Are you saying such an app will not log anything?

https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_11&lang=JAVA&build=GRADLE&test=JUNIT&features=aws-lambda&features=aws-cdk&features=amazon-api-gateway&version=3.8.7

**Comment by driverpt** [comment]
Hello @sdelamo , please find the demo app [here](https://github.com/driverpt/micronaut-logback-refresh-issue).

To reproduce try to set the Environment variable: `LOGGER_LEVELS_COM_EXAMPLE=DEBUG` in Lambda Configuration.

This also causes issue with Native Build when we're using Environment Variables unrelated to `LOGGER_LEVELS` and used in Logback.

I've created a [Test and Proposed a Fix ](https://github.com/micronaut-projects/micronaut-core/pull/8919) for this issue

Thanks

**Comment by sdelamo** [comment]
Does the issue only happen when you use [Lombok](https://github.com/driverpt/micronaut-logback-refresh-issue/commit/a328120465072137d102b65216dac2baa1a85d62) `@Slf4j`?

**Comment by driverpt** [comment]
Hello @sdelamo , did not test that.

**Comment by yuri1969** [comment]
This issue causes more undesirable side-effects.

I can confirm that the logging-related config property [`logger.config`](https://docs.micronaut.io/latest/guide/index.html#logging) (and maybe others) takes effect only when the `logger.levels` property is set. A peek into the code revealed it was caused by the lack of a refresh.
