### ISSUE TITLE
Fix tracing module after request processing refactoring

### ISSUE THREAD

**Issue by graemerocher** [micronaut-projects/micronaut-core#8929]
### Expected Behavior

Distributed tracing module should work however it seems the request processing refactoring has changed or broken how spans are propagated. Perhaps the filters need re-writing for the new filter API.

### Actual Behaviour

Test failures https://ge.micronaut.io/s/a265pehxryjui/tests/overview

### Steps To Reproduce

Run tests of master branch of https://github.com/micronaut-projects/micronaut-tracing

### Version

4.0.x

**Comment by yawkat** [comment]
fixed by https://github.com/micronaut-projects/micronaut-tracing/pull/281
