### ISSUE TITLE
Add support for Azure Java serverless functions

### ISSUE THREAD

**Issue by rvanderwerf** [micronaut-projects/micronaut-core#897]
More info here.. https://azure.microsoft.com/en-us/blog/announcing-the-preview-of-java-support-for-azure-functions/

Need to add ability at compile time to create a JSON deployment file automatically for deployment on Azure functions via a new annotation.

**Comment by marceloverdijk** [comment]
@rvanderwerf I guess this is more than only creating the JSON host and function files? Would it be possible to create these files manually and make it work? I wonder how to use Azure's `@FunctionName` interface in a Micronaut app.

**Comment by graemerocher** [comment]
See https://github.com/micronaut-projects/micronaut-azure
