### ISSUE TITLE
Create Micronaut-logging repository

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#8986]
It should be Micronaut Framework 4 only. 

It relates and closes: https://github.com/micronaut-projects/micronaut-core/pull/8968

Use the [project-template](https://github.com/micronaut-projects/micronaut-project-template) and send PR for the [management repository](https://github.com/micronaut-projects/management/blob/master/repos.auto.tfvars) once it is created. 

@graemerocher 
 > makes sense to move everything logback related there in that case

**Comment by timyates** [comment]
Done https://github.com/micronaut-projects/micronaut-logging/
