### ISSUE TITLE
Injecting single instance of @EachProperty bean does not throw NonUniqueBeanException

### ISSUE THREAD

**Issue by dguggi** [micronaut-projects/micronaut-core#910]
Hi

1. Create two beans of the same type without making one of them primary:
```java
@EachProperty("test.some")
public class SomeType { }
```

2. Using the following properties:
```
test.some.bean1 = one
test.some.bean2 = two
```
This will result in two beans named "one" and "two" and none of the beans is marked primary.

3. Inject into another bean:
```java
@Context
public class AnotherType {
    public AnotherType(SomeType someType) {}
}
```
This will inject one of the two beans. I would have expected to get a NonUniqueBeanException as I'd get for "non-iterable" bean-definitions? Is this known/expected behavior?

Thanks!

**Comment by jameskleeh** [comment]
If my memory serves, this was known and expected behavior. It was decided a while back to not change this because which bean is injected is deterministic. The bean for the configuration that comes first will be chosen.
