### ISSUE TITLE
Custom SSL protocol defects

### ISSUE THREAD

**Issue by ai-houzi** [micronaut-projects/micronaut-core#9110]
### Expected Behavior

I need to customize the SSL protocol, but there is a logical flaw in setting the SSL protocol for the SslConfiguration class. I am unable to customize the protocol, and its code logic is as follows

![image](https://user-images.githubusercontent.com/39689003/232080103-be1b1c86-cdc4-42cb-b0db-d02a5b0a46ff.png)

By the way, can I customize the transmission for the SSLContext class

### Version

3.8.9

**Comment by sdelamo** [comment]
closed via https://github.com/micronaut-projects/micronaut-core/pull/9118
