### ISSUE TITLE
Unexpected duplicate beans in custom singleton-like scope based on AbstractConcurrentCustomScope

### ISSUE THREAD

**Issue by mancze** [micronaut-projects/micronaut-core#9208]
### Expected Behavior

We were implementing custom scope with the use of `AbstractConcurrentCustomScope`. Our custom scope lives exist itself as a singleton bean, and it doesn't have any special logic. The expectation was that the scope should effectively work as the singleton scope, only under our custom scope annotation. Every bean under that scope should exist purely as singleton - single instance.

### Actual Behaviour

We discovered that possibly different beans (different instances of objects) might get injected or resolved from bean context, depending on the injection points. 

Multiple instances of the same type might be created and exist in our custom scope where only single instance of given bean type is expected. No qualifiers are incorporated.

### Steps To Reproduce

1. Repro-repo: https://github.com/mancze/micronaut-sandbox/tree/custom-scope-bean-double-init
2. Run tests: `./gradlew :test --tests "com.example.scope.CustomScopeDoubleInitTest"`

### Example Application

https://github.com/mancze/micronaut-sandbox/tree/custom-scope-bean-double-init

### Version

3.9.1

**Comment by graemerocher** [comment]
As a workaround you can add `@Bean(typed = Bar.class)` to `BarImpl` which will restrict `Bar` as the only injectable byte
