### ISSUE TITLE
Provide OpenRewrite recipe for Micronaut 3.x to 4.x upgrade

### ISSUE THREAD

**Issue by jeremyg484** [micronaut-projects/micronaut-core#9214]
### Feature description

For the release of Micronaut 4, provide an OpenRewrite recipe to ease the task of upgrading an existing application.

There is an existing OpenRewrite recipe for upgrading from Micronaut 2.x to 3.x here: 
https://github.com/openrewrite/rewrite-micronaut

The new recipe can be based upon this existing work and contributed via PR to that existing repository. An initial attempt at the recipe will be based upon the upgrade guidelines here:
https://micronaut.io/2023/05/09/upgrade-to-micronaut-framework-4-0-0/

Once the recipe is complete enough, the core docs can be updated to detail the basic steps involved in using OpenRewrite for the upgrade.

**Comment by sdelamo** [comment]
Work is being done here https://github.com/openrewrite/rewrite-micronaut
