### ISSUE TITLE
JDK HTTP client probably doesn't handle raw strings properly

### ISSUE THREAD

**Issue by melix** [micronaut-projects/micronaut-core#9223]
### Issue description

This is a follow up to https://github.com/micronaut-projects/micronaut-test-resources/pull/255#issuecomment-1545396551

Using a server which returns a response like this:

```
HTTP/1.1 200 OK
Content-Type: application/json
connection: keep-alive
content-length: 5
date: Fri, 12 May 2023 07:26:03 GMT

world
```

and a declarative client using the `micronaut-http-client-jdk`:

```java
@Client
interface SomeClient {
   ...
   Optional<String> getString()
}
```

Client fails with:

> io.micronaut.json.JsonSyntaxException: Unrecognized token 'world': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')

This error goes away when switching from the JDK client to the Netty client. Quoting @yawkat : 

> Yes, types like String (and byte[] and ByteBuffer) are treated specially and don't go through the json encoding/decoding process. It's possible that the jdk client is missing this special handling.

**Comment by timyates** [comment]
Maybe related https://github.com/micronaut-projects/micronaut-core/issues/9300
