### ISSUE TITLE
ResourceLeakDetector ByteBuf.release was not called before it's garbage-collected

### ISSUE THREAD

**Issue by brandonlamb** [micronaut-projects/micronaut-core#923]
### Steps to Reproduce

pom.xml, Dockerfile, run.sh included in gist below:

https://gist.github.com/brandonlamb/55fb3a11690158bc870ac0a75a0c4059

Not sure I can easily share code without rewriting a bunch of it. This is an API that receives XML and writes a message using Kafka client.

I have 8 docker instances running a 1g memory limit (no cpu limit). I've tried openjdk 8 and 11, tried setting some options for buffer limit, and tried with and without specifying `-Xmx`.

Originally the controller method was returning a Mono<HttpResponse<Any>> but then i made it blocking and then used coroutines to see if that would help, doesnt seem to

### Expected Behaviour

Does not dump errors about OutOfMemory or leaking memory from netty.

### Actual Behaviour

```
2018-11-17T15:44:59.135Z [nioEventLoopGroup-1-7] ERROR i.m.h.s.netty.RoutingInBoundHandler - Micronaut Server Error - No request state present. Cause: Direct buffer memory
java.lang.OutOfMemoryError: Direct buffer memory
2018-11-17T16:00:45.843Z [nioEventLoopGroup-1-7] ERROR io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
```

### Environment Information

- **Operating System**: alpine docker image
- **Micronaut Version:** 1.0.1
- **JDK Version:** adoptopenjdk/openjdk8-openj9:x86_64-alpine-jdk8u192-b12_openj9-0.11.0r0-slim

**Comment by graemerocher** [comment]
Could you provide what the XML parsing code looks like. If that is not possible please add the following to your `main` method of your `Application` class:

```
ResourceLeakDetector.setLevel(Level.PARANOID);
```

Then run the application, hit the endpoint that does the XML parsing a few times and provide the output logs where the leak is occuring. Thanks

**Comment by brandonlamb** [comment]
Updated gist with:

- RestController.kt (I've tried ByteArray and String)
- payload.xml with a sample
- console.log containing the paranoid level dump

**Comment by brandonlamb** [comment]
Just to try something, I updated my controller to below, and it says there is not body.

```kotlin
  @Post("/")
  @Consumes(APPLICATION_XML)
  fun createTransactions(request: HttpRequest<Any>): HttpStatus {
//    val body = request.getBody(String::class.java).get()
    val body = request.body.get() as String
    val m = ctx.createUnmarshaller()
    val transactions = m.unmarshal(body.byteInputStream(UTF_8)) as SalesTransactions
//snipped
    return HttpStatus.ACCEPTED
  }
```

```
2018-11-18T16:27:46.167Z [nioEventLoopGroup-1-2] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: No value present
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source)
```

Not to conflate my issues, but shouldn't the above work?

**Comment by graemerocher** [comment]
Seems that by specifying `Any` as the body Micronaut interprets that as you not being interested in the Body. The Body is only parsed if you specify a specific type to the generic type argument of `HttpRequest`

**Comment by graemerocher** [comment]
Can you provide the `SalesTransactions` class, so far I have not been able to reproduce in 1.0.1

**Comment by brandonlamb** [comment]
Yea I can update the gist today with the data classes.

One interesting tidbit, we have probably 10 APIs now using Micronaut, this is the only one using XML (not by our choice) and I think the only one having this issue. I can consistently build, use postman to post the payload, and after a couple hits I will get this over and over.

I can try remove all the logic and see if it still happens.

One thing to note, this uses Kafka client as well, but not sure that has anything to do with this as the stack traces look like all http stuff.

**Comment by graemerocher** [comment]
Ok, I am sure we can track down the issue, just need to be able to reproduce it

**Comment by brandonlamb** [comment]
Updated the gist with the data models

**Comment by graemerocher** [comment]
So far I have not been able to reproduce this issue. Attached is the sample I am using do to so. Maybe I am doing something wrong. If you are able to attach an example that reproduces the issue with clear instructions on how to do so we can take a look. Thanks.

[leak-issue923.zip](https://github.com/micronaut-projects/micronaut-core/files/2663642/leak-issue923.zip)

**Comment by brandonlamb** [comment]
Hm shoot. I'm not sure I can provide much more without the potential for our security team to start balking about sharing code publicly (not that its anything special).

Should we just close this issue? This is really one of our only APIs out of some 70+ that requires XML. I did end up migrating it back to Java EE to make it work. Maybe we just have some weird fluke lol

**Comment by marcosflobo** [comment]
We could reproduce this issue here https://github.com/micronaut-projects/micronaut-core/issues/2158
