### ISSUE TITLE
Groovy module tests fail when updated to core M3

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-core#9234]
We updated micronaut-groovy to core-M3, but a couple of the tests are failing

https://github.com/micronaut-projects/micronaut-groovy/pull/464

https://ge.micronaut.io/s/rhtlqdaouk2ky/tests/overview?outcome=failed

https://github.com/micronaut-projects/micronaut-groovy/blob/889b897ab9229ca02b400cd9fc1a910f52c6d750/function-groovy/src/test/groovy/io/micronaut/function/groovy/FunctionTransformSpec.groovy#L275

**Comment by sdelamo** [comment]
I assume this can be closed now
