### ISSUE TITLE
OpenAPIDefinition annotation not used for Kotlin class

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-core#930]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an application with swagger-kotlin feature enabled
2. Add an OpenAPIDefinition annotation
2. Change object to class and wrap main in companion object
3. Build Project

### Expected Behaviour

The swagger file should include the open api annotation information.

### Actual Behaviour

The information is missing.

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.0.1
- **JDK Version:** 1.8

### Comments

When using the generated "object" class, the swagger is generated, ie. this works:

    @OpenAPIDefinition(
        info = Info(
            title = "Swagger Test"
        )
    )

    object Application {
        @JvmStatic
        fun main(args: Array<String>) {
            Micronaut.build()
                    .packages("test.swagger")
                    .mainClass(Application.javaClass)
                    .start()
        }
    }

And generates the following swagger file:

    openapi: 3.0.1
    info:
      title: Swagger Test
    paths:
      /swagger:
        get:
          operationId: index
    ...

But the following does not:

    @OpenAPIDefinition(
        info = Info(
            title = "Swagger Test"
        )
    )

    class Application {
        companion object {
            @JvmStatic
            fun main(args: Array<String>) {
                Micronaut.build()
                        .packages("test.swagger")
                        .mainClass(Application::class.java)
                        .start()
            }
        }
    }

The info section is no longer in the swagger file:

    openapi: 3.0.1
    paths:
      /swagger:
        get:
          operationId: index
    ...

**Comment by markjfisher** [comment]
I am able to work around this by putting

    object Fake

immediately after the OpenAPIDefinition

**Comment by glazzari** [comment]
Hi, I'm facing a similar issue. I'm not able to use the OpenApiDefinition annotation in the Application.kt gerenated by micronaut CLI. I can workaround this by adding object Fake, as suggested above.

```
@OpenApiDefinition --> In IntelliJ, this returns "This annotation is not applicable to target 'top level function'"
fun main(args: Array<String>) {
	build()
	    .args(*args)
		.packages("com.example")
		.start()
}
```
