### ISSUE TITLE
Generated swagger file using application properties in controller path still has property names in definition

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-core#932]
### Task List

- [X] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Steps to Reproduce

1. Generate a controller in an application with swagger-kotlin feature enabled
2. Configure the Controller path with an application property value
3. Generate swagger with a build

### Expected Behaviour

The 'path' section of the swagger should use the application property

### Actual Behaviour

The placeholder variable is present instead of the value

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.0.1
- **JDK Version:** 1.8

### Full Description

My Controller is defined like:

    @Controller("/\${app.base-path}/product")
    class SomeController {
        @Get("/{id}")
        fun getProduct(id: String): Maybe<Product> {
        ...

The generated swagger definition looks like:

    openapi: 3.0.1
    paths:
      /${app.base-path}/product/{id}:
        get:
        ...

This means any generated swagger UI client sees the path incorrectly.

![image](https://user-images.githubusercontent.com/1616940/48718976-51c27680-ec14-11e8-9a6a-8b10d69b71ff.png)

It would be good if the generated swagger file honors any property values in the application definition.

**Comment by jameskleeh** [comment]
This is not possible since the file is created at compilation time and the configuration property is not known until runtime

**Comment by markjfisher** [comment]
ok, thanks for the update.
