### ISSUE TITLE
new Propagation API is undocumented

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9332]
### Issue description

We need to document the new Propagation API. 

Moreover, we need to review the current documentation and what we recommend people do. For example, currently we recommend using the Reactor Context API 

> Using the context to retrieve the request is the best approach for reactive flows because Project Reactor propagates the context and it does not rely on a thread local like [ServerRequestContext](http://localhost/micronaut-core/api/io/micronaut/http/context/ServerRequestContext.html).

I assume we want people to use the new api. However, our docs are not up-to-date.

**Comment by sdelamo** [comment]
@dstepanov I assume this is something you will do. The docs should indicate the motivation behind the API, why people should use and how to use it.

**Comment by dstepanov** [comment]
I will do it after it's more stable.

**Comment by sdelamo** [comment]
@dstepanov can we do this now?

**Comment by dstepanov** [comment]
Yes, I will do it

**Comment by sdelamo** [comment]
Closed via https://github.com/micronaut-projects/micronaut-core/pull/9554
