### ISSUE TITLE
Certain swagger properties are being ignored

### ISSUE THREAD

**Issue by RaviH** [micronaut-projects/micronaut-core#935]
Started with Micronaut's own hello-world java example:

[hello-world-java.zip](https://github.com/micronaut-projects/micronaut-core/files/2598353/hello-world-java.zip)

Steps to reproduce:

a) Start the application.
b) Look for `the-title-0.0.yml` . Should be at: `./target/classes/META-INF/swagger/the-title-0.0.yml` from the main directory

Example resource:
```
    @Operation(
            summary = "Gets mappings from TTT using vod provider mappings",
            description = "Migration of /networks endpoint from TTT. Gets mappings from XYZ using provider mappings",
            responses = {
                    @ApiResponse(
                            responseCode = "200", description = "Successfully got abc data from TTT",
                            content = {
                                    @Content(
                                            mediaType = "application/json", schema = @Schema(implementation = Greeting.class)
                                    )
                            }
                    )
            })
    @Get
    public HttpResponse<Greeting> getNetworks(
            @Parameter(
                    name = "fooBar",
                    description = "NA/true/false (case insensitive)",
                    required = false,
                    schema = @Schema(
                            nullable = true,
                            type = "string", allowableValues = "NA/true/false (case insensitive)",
                            defaultValue = "NA"
                    )
            )
            @QueryValue(value = "fooBar", defaultValue = "NA") String fooBar
    ) throws IOException {
        return HttpResponse.ok(new Greeting());
    }
```

Partial swagger yml file:
```
  /:
    get:
      summary: Gets mappings from TTT using vod provider mappings
      description: Migration of /networks endpoint from TTT. Gets mappings from XYZ
        using provider mappings
      operationId: getNetworks
      parameters:
      - name: fooBar
        in: query
        description: NA/true/false (case insensitive)
        required: true
        schema:
          type: string
          nullable: false
      responses:
        200:
          description: Successfully got abc data from TTT
          content:
            application/json:
              schema:
                type: object
```

Noticed a few issues:

a. Schema type is `object` even though I have mentioned: `@Schema(implementation = Greeting.class)`

b. `required: true` in the yml file even though I am specifically stating `required = false`

c. `defaultValue` is being ignored.

d. `allowableValues` is being ignored.

e. Java docs seems to take precedence over Swagger annotations. IMO swagger annotations should be source of truth over java docs. If not, I have to comment out my java docs for Swagger annotations to take precedence and we can't detail as much in Java docs as much as we can with Swagger annotations.

f. Is there an example of swagger ui / html to provide a UI for the generated yml file?

Thank you,
Ravi

**Comment by graemerocher** [comment]
Will look into these issues as for Swagger UI, it can be run as a standalone app and you just point the app to where you have published your YAML

**Comment by markjfisher** [comment]
For the swaggerUI, i've used the plugin https://github.com/int128/gradle-swagger-generator-plugin.

Here's a sample configuration from my gradle build for configuring both SwaggerUI and ReDoc.

    plugins {
        id 'org.hidetake.swagger.generator' version '2.15.0'
    }
    dependencies {
        swaggerUI 'org.webjars:swagger-ui:3.10.0'
    }
    swaggerSources {
        app {
            inputFile = file("$buildDir/tmp/kapt3/classes/main/META-INF/swagger/your-swagger-1.0.yml")
            ui {
                outputDir = file("$buildDir/tmp/kapt3/classes/main/META-INF/swagger-ui")
            }
            reDoc {
                outputDir = file("$buildDir/tmp/kapt3/classes/main/META-INF/redoc")
                scriptSrc = "https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"
            }
        }
    }

The "app" section is any name you want. I've picked "swagger-ui" and "redoc" myself as directory output names for simplicity.

Then in application.yml file add a router section to serve the generated files:

    micronaut:
        router:
            static-resources:
                swagger:
                    paths: classpath:META-INF/swagger
                    mapping: /swagger/**
                swagger-ui:
                  paths: classpath:META-INF/swagger-ui
                  mapping: /swagger-ui/**
                redoc:
                  paths: classpath:META-INF/redoc
                  mapping: /redoc/**

Build the swagger-ui with:

    ./gradlew clean build generateSwaggerUI

optionally, run `generateReDoc` for the ReDoc output

Now you can browse the swagger file at http://localhost:8080/swagger/your-swagger-1.0.yml
and use the swagger-UI at http://localhost:8080/swagger-ui
and view the redoc at http://localhost:8080/redoc

**Comment by graemerocher** [comment]
Nice tip

**Comment by RaviH** [comment]
@markjfisher Thank you! Any idea how I could do it via Maven?

**Comment by markjfisher** [comment]
sorry, I haven't tried via maven, I use gradle pretty much exclusively as it has such wonderful and easy to use plugins :)

**Comment by RaviH** [comment]
@markjfisher Thank you! Work uses maven, so I gotta follow. 

@graemerocher I found this in my research for the UI and it works:

https://stackoverflow.com/questions/52551178/swagger-for-micronaut-with-maven

The solution in the top answer as part of core mcironaut would be an awesome addition!

What do you think?

**Comment by graemerocher** [comment]
@RaviH it would be a great addition, PRs are welcome to improve this area

**Comment by graemerocher** [comment]
Resolved issues b) to e) 

I am not sure what you mean with issue a) .. what would you expect it to be if not an `object`? How would you expect that to be mapped.
