### ISSUE TITLE
Multiple controllers derived from same base class throw exception from default router 

### ISSUE THREAD

**Issue by jamiebernardin** [micronaut-projects/micronaut-core#936]
Hi - I'm building a simple CRUD framework on top of micronaut.  I've simplified my problem down to the a few simple classes.... and all the necessary code is provided.  When I create a single controller from a base class, it works.  If I try to create a second, I get an error.   Meaning run as is, and the route foo will work.  If you uncomment out the bar controller, it won't compile.  See the file, it's very straightforward.  

### Recreate easily

`mn create-app hello-world --lang kotlin`

Copy attached file into kotlin file in source folder under hello/world. 

### Expected Behaviour
It will work and provide a route at "foo".  Uncomment out //@Controller("/bar") and I'd expect a route "bar" to be available.  

### Actual Behaviour

> Task :run FAILED
10:38:11.928 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Failed to inject value for parameter [router] of class: io.micronaut.web.router.DefaultRouter

Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,[Router router],RequestArgumentSatisfier requestArgumentSatisfier,MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,List outboundHandlers) --> new DefaultRouter([Collection builders])
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for parameter [router] of class: io.micronaut.web.router.DefaultRouter

### Environment Information

- **Operating System**: MAC Mohave
- **Micronaut Version:** 1.0
- **JDK Version:** 1.8

### Example Application

-Included in entirety with attached file.

[classes.txt](https://github.com/micronaut-projects/micronaut-core/files/2600552/classes.txt)

**Comment by jameskleeh** [comment]
The real exception is `Caused by: io.micronaut.web.router.exceptions.RoutingException: No such route: hello.world.RestController.read
`
