### ISSUE TITLE
Compilation error when trying to name abstract methods in service like GORM Finders

### ISSUE THREAD

**Issue by mostwantedv2** [micronaut-projects/micronaut-core#938]
-Steps to reproduce provided
1. Create following classes
class Base<T> implements GormEntity<T> {
    Boolean active = true
    Date dateCreated
    Date lastUpdated
}

@Entity
class Port extends Base<Port> {
    String name
    Address address
    static constraints = {
        address nullable: true
    }
}

2. Create following service
@Service(Port)
abstract class PortService {
    abstract Port findByNameAndActive(@NotEmpty String name, Boolean active = true)
}

Compilation Error =>
[ Cannot implement finder for non-existent property [active] of class [org.domain.Port]

### Expected Behaviour
Framework should identify properties of Base classes in GORM finders

### Environment Information
- **Operating System**: Windows 10
-**Database**: Postgres 10
- **Micronaut Version:** 1.0.0
- **JDK Version:** 1.8.0_191

**Comment by graemerocher** [comment]
Please report to https://github.com/grails/grails-data-mapping/issues this is not related to Micronaut but GORM

**Comment by mostwantedv2** [comment]
> Please report to https://github.com/grails/grails-data-mapping/issues this is not related to Micronaut but GORM

Thanks for replying, I found same issue reported on grails-data-mapping repo, although there seem to be no development into the issue there, its been some months since that issue was reported. :(
