### ISSUE TITLE
Document @ServerFilter and Ordered

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9382]
### Issue description

`HttpFilter` extends `Ordered`. Thus it is clear to the users that they can tweak the order of the filters which use the new API.

The new annotation-based filters, e.g., `@ServerFilter`, support the usage of `Ordered`. 

```java
@ServerFilter(Filter.MATCH_ALL_PATTERN)
public class FooFilter implements Ordered {
    @RequestFilter
    @Nullable
    public HttpResponse<?> doFilter(HttpRequest<?> request) {
    ....
    }
    @Override
    public int getOrder() {
        return ServerFilterPhase.SECURITY.order();
    }
}
```

But it is unclear to the users that they should implement `Ordered` with the new annotation-based API. 

Is it optional or required to implement `Ordered`? 

 If optional, we should document what happens if you don't implement `Ordered` in the class annotated with `@ServerFilter`. If you don't implement Ordered, what is the order? 0 or Integer.MIN_VALUE?

**Comment by graemerocher** [comment]
think we should document how to use the `@Order` annotation instead

**Comment by dstepanov** [comment]
BTW I have noticed that the response filters are executed in the opposite order direction than the request once. I think that's something that needs correction.

**Comment by sdelamo** [comment]
> BTW I have noticed that the response filters are executed in the opposite order direction than the request once. I think that's something that needs correction.


@dstepanov can you create an issue, mark it as a bug and add it to 4.0.0-M3 and 4.0.0 projects. Thanks

**Comment by yawkat** [comment]
@dstepanov the order should be highest precedence request filter, lowest precedence request filter, lowest precedence response filter, highest precedence response filter. is that not the current behavior?

**Comment by dstepanov** [comment]
I have created an issue https://github.com/micronaut-projects/micronaut-core/issues/9390

**Comment by dstepanov** [comment]
You can see the current behavior in the tests:
- FiltersPropagatedContextSpec9
- FiltersPropagatedContextSpec10
