### ISSUE TITLE
Documentation needs to be updated now that @Body is required

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9388]
The Variable resolution documentation says: 

> If the request can have a body and no @Body is defined then try to parse the body (either JSON or form data) and bind the method arguments from the body.

However, now `@Body` is required.

**Comment by sdelamo** [comment]
@yawkat can you update the docs?

**Comment by yawkat** [comment]
no that's still correct

**Comment by sdelamo** [comment]
> If the request can have a body and no @Body is defined then try to parse the body (either JSON or form data) and bind the method arguments from the body.

Does this sentence means if you have a controller such as: 


```
@Status(HttpStatus.OK)
void foo(String firstName, String lastName)  {
}
```

then a request with a body such as `{"firstName": "Sergio", "lastName": "del Amo"}`  will work.

**Comment by yawkat** [comment]
correct

**Comment by wetted** [comment]
@sdelamo @yawkat Is there anything that needs to be done here? I can add Sergios example as a note in the docs for clarification.

**Comment by sdelamo** [comment]
@wetted we should add a test to the TCK and an example with `test-suite`, `test-suite-kotlin`, `test-suite-groovy` to the docs.

**Comment by sdelamo** [comment]
> @wetted we should add a test to the TCK and an example with test-suite, test-suite-kotlin, test-suite-groovy to the docs.

Can you do this @wetted ?

**Comment by wetted** [comment]
> > @wetted we should add a test to the TCK and an example with test-suite, test-suite-kotlin, test-suite-groovy to the docs.
> 
> Can you do this @wetted ?

Yes, I'll work on this today.
