### ISSUE TITLE
Cannot apply AOP advice to final class

### ISSUE THREAD

**Issue by hantsy** [micronaut-projects/micronaut-core#9426]
### Expected Behavior

I tried to upgrade my example project to 4.0, the example used R2dbc/Postgres, Kotlin Coroutines.

When compiling it, it throws exception, even I add the following configuration in Gradle build script explicitly.

```kotlin 
allOpen{
  annotation("~.Controller")
}
```

### Actual Behaviour

```bash
e: [ksp] D:/hantsylabs/micronaut-sandbox/data-r2dbc-kotlin-co/src/main/kotlin/com/example/PostController.kt:18: Cannot apply AOP advice to final class. Class must be made non-final to support proxying: com.example.PostController
e: Error occurred in KSP, check log for detail
```

### Environment Information

Windows 10 Pro, Java 17

### Example Application

https://github.com/hantsy/micronaut-sandbox/tree/master/data-r2dbc-kotlin-co

### Version

4.0.0-M3

**Comment by graemerocher** [comment]
sounds more like a Kotlin bug to me, not sure why the `allOpen` thing doesn't work for KSP

**Comment by yawkat** [comment]
this is a huge pain to debug (intellij won't let me set breakpoints in some kotlin code), but i think this may be pretty hard to fix. ksp runs as an analysis step, while allopen is implemented as a transformation of the IR, which seems to run much later in the process.

**Comment by hantsy** [comment]
still does not work in 4.0.0-M4

**Comment by sdelamo** [comment]
@hantsy a workaround would be to use kapt with all-open plugin. Micronaut Framework 4 still supports kapt. 

or annotate manually your classes as open.

**Comment by sdelamo** [comment]
@yawkat have we submit a bug to all-open?

**Comment by hantsy** [comment]
@sdelamo But launch generated codes use KSP instead of kapt.

**Comment by yawkat** [comment]
@sdelamo ive not reported it, AIUI it is already on their roadmap.

**Comment by sdelamo** [comment]
@hantsy you can still [generate Micronaut Kotlin applications with kapt in Launch](https://micronaut.io/launch?type=DEFAULT&name=demo&package=com.example&javaVersion=JDK_17&lang=KOTLIN&build=GRADLE_KOTLIN&test=JUNIT&features=kapt&version=4.0.0-M4). We just default to ksp for gradle projects.
