### ISSUE TITLE
Uncaught exceptions in scheduled jobs don't get logged

### ISSUE THREAD

**Issue by giovanniberti** [micronaut-projects/micronaut-core#9432]
### Expected Behavior

Uncaught exceptions in scheduled tasks should be logged to stderr with their stacktrace

### Actual Behaviour

Exceptions aren't logged

### Steps To Reproduce

1. Download the [scheduled tasks gradle-kotlin example](https://guides.micronaut.io/latest/micronaut-scheduled-gradle-kotlin.html)
2. Apply this patch:

```patch
diff --git a/src/main/kotlin/example/micronaut/RegisterUseCase.kt b/src/main/kotlin/example/micronaut/RegisterUseCase.kt
index 0fe57ff..e3985a2 100644
--- a/src/main/kotlin/example/micronaut/RegisterUseCase.kt
+++ b/src/main/kotlin/example/micronaut/RegisterUseCase.kt
@@ -20,7 +20,11 @@ class RegisterUseCase(private val emailUseCase: EmailUseCase, // <1>
 
     private fun scheduleFollowupEmail(email: String, message: String) {
         val task = EmailTask(emailUseCase, email, message) // <3>
-        taskScheduler.schedule(Duration.ofMinutes(1), task)  // <4>
+        taskScheduler.schedule(Duration.ofSeconds(10)) {
+			LOG.info("throwing")
+			throw RuntimeException("uncaught")
+  			task.run()
+	   }  // <4>
     }
 
     companion object {
```

3. Run with `./gradlew run`
4. After 10s "throwing" will be logged with INFO severity, but the exception won't be logged

### Environment Information

- OS: Linux
- JDK Version: OpenJDK build 19.0.2+7

### Version

3.9.2

**Comment by yawkat** [comment]
TaskScheduler returns a ScheduledFuture that will fail if the task encounters an exception. This behavior matches that of [ScheduledExecutorService](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ScheduledExecutorService.html).

**Comment by giovanniberti** [comment]
Thanks! Maybe it should be added to the docs, as the default behaviour is not that straightforward :slightly_smiling_face:
