### ISSUE TITLE
Environment Cloud Provider detection is slow

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#947]
Currently [DefaultEnvironment::determineCloudProvider](https://github.com/micronaut-projects/micronaut-core/blob/master/inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java#L585) spends half a second when I run tests. 

If using gradle one workaround is is to set:

```
tasks.withType(Test) {
    systemProperty "micronaut.cloud.platform", 'BARE_METAL'
}
```

**Comment by sdelamo** [comment]
I think we should:

A) remove cloud provider detection which require a network call

or 

B) the user should opt-in to cloud detection which require a network call via a system property. something like: `-Dmicronaut.cloud.platform.network-detection=true`

**Comment by alvarosanchez** [comment]
https://github.com/micronaut-projects/micronaut-core/pull/942 partially addresses the problem.

**Comment by jameskleeh** [comment]
https://github.com/micronaut-projects/micronaut-core/pull/942

**Comment by jmtrue** [comment]
This may not be fully resolved. I'm seeing the Google Compute environment detection adding 10 seconds to my application startup time in Micronaut 1.1.0.
