### ISSUE TITLE
Dedicated management port

### ISSUE THREAD

**Issue by missourian55** [micronaut-projects/micronaut-core#948]
Like `spring boot 2`, it would be nice to have a dedicated management port.  K8 and service mesh providers dictate this as a good practice.

```
management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.server.port=7999

``` 
This feature request is follow up of this https://github.com/micronaut-projects/micronaut-core/issues/538

### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.0.1
- **JDK Version:** JDK8

**Comment by hberrayana** [comment]
+1 for this issue
I need it for a product that I'm working on.

**Comment by markjfisher** [comment]
This would be a really handy feature. We're being requested if possible to move management endpoints onto a different port in our GCS environments.

**Comment by gosiapolitowska** [comment]
Hi, any update on this one? It's an important feature for my project as well. Will it make its way to next milestone? Or maybe there's a workaround for it?

**Comment by dave08** [comment]
This could even possibly be a way to initiate the server to listen on multiple ports, and have a `@Port` annotation for HttpServer controllers... that would help in providing inter-microservice communication while providing an external facade for only what's really necessary... then internally, the management services could also use this.

**Comment by graemerocher** [comment]
PR submitted https://github.com/micronaut-projects/micronaut-core/pull/2529
