### ISSUE TITLE
Unable to disable cors server

### ISSUE THREAD

**Issue by ssj1basil** [micronaut-projects/micronaut-core#9484]
### Expected Behavior

`micronaut.server.cors.enabled: false`
Using this config, I assume the cors filter should be disabled and any request with non-localhost origin should passthrough.

### Actual Behaviour

The actual behavior, any request with origin from a non-localhost gets a response of 403. If there is anyway to disable cors filter that i am missing, I would appreciate that info as well.

### Steps To Reproduce

1. Clone this repo https://github.com/ssj1basil/cors-issue-demo-project
2. ./gradlew run
3. run `curl -H "Origin: www.google.com" -v "http://localhost:8080/test"`
4. We get a response of 403

### Environment Information

- JVM version 11 is used

### Example Application

https://github.com/ssj1basil/cors-issue-demo-project

### Version

3.9.3

**Comment by yawkat** [comment]
you also need to enable micronaut.server.cors.localhost-pass-through

**Comment by sdelamo** [comment]
Configuration options available: https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.http.server.HttpServerConfiguration.CorsConfiguration

**Comment by sdelamo** [comment]
To disallow drive-by localhost attacks on a server under development, we added an Origin check for all requests even if Cors itself was disabled.

You could set `micronaut.server.cors.localhost-pass-through` to `true` to enable it.

**Comment by yawkat** [comment]
@sdelamo it's a bit confusing that `enabled: false` doesnt turn off the localhost protection, maybe we should change it in 4.0 to be enabled by default

**Comment by sdelamo** [comment]
cors is disabled by default. Thus, if we turned off localhost protection when cors is off, you will be vulnerable by default.

**Comment by yawkat** [comment]
yes i am saying we should enable it by default

**Comment by sdelamo** [comment]
enable cors by default?

**Comment by yawkat** [comment]
yes, but with safe defaults, eg no allowed origins

**Comment by sdelamo** [comment]
I think cors off by default seems like a sensible default. cors on with no allowed origins by default is practically the same as what we currently have. 

I don't have a strong feeling about this however we will need to change some code to change all the defaults. 

Thus, I am afraid we are a bit late for that change. If you are ok, I am going to create a separate issue to reconsider this in MN 5.

**Comment by sdelamo** [comment]
https://github.com/micronaut-projects/micronaut-core/issues/9518
