### ISSUE TITLE
Enable binary compatibility check for 4.0.x branch of Micronaut Core

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9500]
I have not checked but you may need to set a baseline. 

```groovy
micronautBuild {
    binaryCompatibility {
        baselineVerison = “4.0.0-RC3”
        enabled = true 
    }
}
```

**Comment by wetted** [comment]
@sdelamo @melix 

Looking at `core-bom/build.gradle` I find this, with logic to determine `enabled` dynamically.  I'm not so sure I should replace or do anything with that.

Cedric, can you please advise?

```groovy
micronautBuild {
    binaryCompatibility {
        def dash = version.indexOf('-')
        def v = dash > 0 ? version.substring(0, dash) : version
        def (major, minor, patch) = v.split('[.]').collect { it.toInteger() }
        enabled = major > 4 || (major == 4 && minor > 0) || (major == 4 && minor == 0 && patch > 0)
    }
}
```

**Comment by melix** [comment]
This code is a safety net to make sure that as soon as 4.0 is released we have compatibility enabled. You can remove it if you set the baseline version. However, you'll have to remember to _remove_ the baseline once a new version is out.

**Comment by wetted** [comment]
OK. Thanks. I'll make that change on a PR, and create an issue to remove the baseline on the 4.1 project.

**Comment by wetted** [comment]
@melix when I change it to what's in the issue description it fails with "Could not find a previous version for 4.0.0"
