### ISSUE TITLE
Multipart form upload hangs with empty parameter values

### ISSUE THREAD

**Issue by lukfor** [micronaut-projects/micronaut-core#9502]
### Expected Behavior

We are using a multipart form to submit different types of jobs. The name of the parameters are depending on the type of the job and could be attributes or files. Some parameters are optional and could be contain empty values.

Therefore, we used the code from [Whole Body Binding](https://docs.micronaut.io/latest/guide/#_whole_body_binding) from the guide to parse each `CompletedPart`. However, we need to extend the example by adding `s.request(1)` in the `onNext(..)` handler to get it working. (Is this a typo in the guide?)

```java
@Controller
public class JobController {


    @Post(value = "/submit", consumes = MULTIPART_FORM_DATA, produces = TEXT_PLAIN)
    @SingleResult
    public Publisher<String> submit(@Body MultipartBody body) {

        return Mono.create(emitter -> {
            body.subscribe(new Subscriber<CompletedPart>() {
                private Subscription s;

                @Override
                public void onSubscribe(Subscription s) {
                    this.s = s;
                    System.out.println("Subscribed.");
                    s.request(1); 
                }

                @Override
                public void onNext(CompletedPart completedPart) {
                    // Business logic that parses completedPart based on class
                    System.out.println("OnNext: " + completedPart.getName() + " (Class: " + completedPart.getClass() + ")");
                    s.request(1);  //request next CompletedPart
                }

                @Override
                public void onError(Throwable t) {
                    emitter.error(t);
                }

                @Override
                public void onComplete() {
                    emitter.success("Uploaded");
                }
            });
        });
    }

}
```

### Actual Behaviour

If we submit a multipart form with one single parameter and its value is an empty string (see Test `testUploadWithEmptyJobName`), then the subscriber hangs in the `s.request(1)` call.

However, if we add an additional file to the multipart form (see `testUploadWithEmptyJobNameAndFile`), then it works also for empty values.

### Steps To Reproduce

1. Checkout https://github.com/lukfor/micronaut-multipart-issue/
2. Run the tests
3. Test `testUploadWithEmptyJobName` hangs and after some time it gets a `NoHttpResponseException`
4. Test `testUploadWithEmptyJobNameAndFile` adds an additional file to the request and it works 

### Environment Information

- MacOS, Ubuntu  and Github Actions (Ubuntu)
- Java 11

### Example Application

https://github.com/lukfor/micronaut-multipart-issue/

### Version

3.9.4

**Comment by yawkat** [comment]
fixed by the server changes in 4.x. thanks for the test case, sorry it took so long to look at.
