### ISSUE TITLE
Cloud environment detection cannot be turn on again via env. variable in Micronaut Framework 4

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9506]
### Expected Behavior

Cloud environment detection is off by default in Micronaut framework 4. However, we should give users the ability to turn it on by defining the environment variable `MICRONAUT_ENV_DEDUCTION` to true. 

### Actual Behaviour

I deployed a Micronaut 4 application to Elastic beanstalk.

✅ With Micronaut framework 3 both cloud and ec2 where detected. 
✅ With Micronaut framework 4 none were detected .
❌ With Micronaut framework 4 and `MICRONAUT_ENV_DEDUCTION ` set to true `cloud` and `ec2` where detected. 

### Version

4.0.0-M4

**Comment by timyates** [comment]
As far as I can tell, `MICRONAUT_ENV_DEDUCTION` is `true` by default

As it says in the docs:

> Automatic detection of environments can be disabled by setting the micronaut.env.deduction system property or the `MICRONAUT_ENV_DEDUCTION` environment variable to false.

In https://github.com/micronaut-projects/micronaut-core/pull/8068 we introduced `isDeduceCloudEnvironment` which defaults to `false`

This is used to switch off deducing the environment by means other than looking for Environment variables...

For instance, Heroku is detected via the `DYNO` env var, so adding the following test passes:

```diff
diff --git a/inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy b/inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
index 2cd570cc55..80c840f935 100644
--- a/inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
+++ b/inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
@@ -20,6 +20,7 @@ import io.micronaut.context.ApplicationContext
 import io.micronaut.context.ApplicationContextConfiguration
 import io.micronaut.context.exceptions.ConfigurationException
 import io.micronaut.core.naming.NameUtils
+import io.micronaut.core.util.StringUtils
 import io.micronaut.core.version.SemanticVersion
 import spock.lang.Issue
 import spock.lang.Requires
@@ -741,6 +742,23 @@ class DefaultEnvironmentSpec extends Specification {
         env.getProperty("micronaut.server.port", Integer).get() == 8081
     }

+    void "cloud environment detection is on by default when we pretend to be Heroku"() {
+        given:
+        DefaultEnvironment env = SystemLambda
+                .withEnvironmentVariable("DYNO", "web.1")
+                .execute {
+                    new DefaultEnvironment(new ApplicationContextConfiguration() {
+                        @Override
+                        List<String> getEnvironments() {
+                            []
+                        }
+                    }, true).start()
+                }
+
+        expect:
+        env.activeNames.contains(Environment.HEROKU)
+    }
+
```

I don't think we can tie this `isDeduceCloudEnvironment` to the `MICRONAUT_ENV_DEDUCTION` variable, as we would be back to exactly the same location prior to https://github.com/micronaut-projects/micronaut-core/pull/8068 (as they will both be defaulting to true)

**Comment by timyates** [comment]
At present, the only way of switching on cloud file/host detection is via something like:

```
    @ContextConfigurer
    public class MyEnvironmentConfigurer implements ApplicationContextConfigurer {

        @Override
        public void configure(@NonNull ApplicationContextBuilder builder) {
            builder.deduceCloudEnvironment(true);
        }
    }
```

**Comment by sdelamo** [comment]
Please, add a MICRONAUT_ENV_DEDUCTION_CLOUD env check and default it to false. which does the same as `builder.deduceCloudEnvironment`. That way you can easily not use cloud environment deduction while development or testing but enable it  in your cloud deployments
