### ISSUE TITLE
@Factory class with multiple (dependent) beans not working as expected

### ISSUE THREAD

**Issue by marceloverdijk** [micronaut-projects/micronaut-core#951]
### Task List

- [*] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [*] Example that reproduces the problem uploaded to Github
- [*] Full description of the issue provided (see below)

### Steps to Reproduce

Create a `@Factory` class with multiple (dependent) beans.
E.g. https://github.com/marceloverdijk/micronaut-graphql/blob/master/src/main/java/com/github/marceloverdijk/micronaut/configuration/graphql/GraphQLToolsFactory.java

### Expected Behaviour

All beans to be created.

### Actual Behaviour

`@Factory` is not be loaded due to failing conditions

```
18:00:54.673 [pool-1-thread-4] DEBUG i.m.context.condition.Condition - Bean [Definition: com.github.marceloverdijk.micronaut.configurations.graphql.GraphQLToolsFactory] will not be loaded due to failing conditions:
18:00:54.673 [pool-1-thread-4] DEBUG i.m.context.condition.Condition - * Existing bean [graphql.schema.GraphQLSchema] of type [class graphql.schema.GraphQLSchema] registered in context
```

But actually no `graphql.schema.GraphQLSchema` was registered - at least not manually -.

Probably because the `@Factory` class creates a `GraphQLSchema` and I've added to the missingBeans on class level.
Do I e.g. have to move `@Requires` conditions to methods?

### Environment Information

- **Operating System**: OSX
- **Micronaut Version:** 1.0.1
- **JDK Version:** 8

### Example Application

- https://github.com/marceloverdijk/micronaut-graphql/blob/master/src/test/groovy/com/github/marceloverdijk/micronaut/configuration/graphql/GraphQLToolsFactorySpec.groovy#L59

**Comment by jameskleeh** [comment]
I don't think this is a bug. You have `@Requires(missingBeans = GraphQLSchema.class)` at the factory level, but a method in the factory creates the bean, so the factory is not loaded.

The solution is to move `@Requires(missingBeans = GraphQLSchema.class)` to the method that returns a `GraphQLSchema`

**Comment by marceloverdijk** [comment]
Actually it is not working yet. I've updated the `@Factory` class and moved the `@Requires(missingBeans = GraphQLSchema.class)` to all 3 factory methods like:

```
@Factory
@RequiresGraphQLEnabled
@Requires(classes = SchemaParser.class)
@Requires(beans = GraphQLResolver.class)
public class GraphQLToolsFactory {

    @Bean
    @Singleton
    @Requires(missingBeans = {GraphQLSchema.class, SchemaParserOptions.class})
    public SchemaParserOptions schemaParserOptions(..) { .. }

    @Bean
    @Singleton
    @Requires(missingBeans = {GraphQLSchema.class, SchemaParser.class})
    public SchemaParser schemaParser(..) { .. }

    @Bean
    @Singleton
    @Requires(missingBeans = GraphQLSchema.class)
    public GraphQLSchema graphQLSchema(SchemaParser schemaParser) { .. }
}
```

But still `SchemaParserOptions` and `SchemaParser` are not created as the bottom one is providing the `GraphQLSChema`.

When moving `missingBeans = {GraphQLSchema.class,` from both `schemaParserOptions` and `schemaParser` it works. But then those beans get created when the user registered a `GraphQLSchema` bean manually.

All three beans should not be created when there is `GraphQLSchema` bean registered manually.
