### ISSUE TITLE
Memory leak when using Fallback of a service

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-core#952]
### Environment Information

- **Operating System**: Linux
- **Micronaut Version:** 1.0.1
- **JDK Version:** JDK8

### Description of issue

I'm testing concurrency of my service with ApacheBench in normal and fallback scenarios.

I'm forcing fallback in my service as follows:

    override fun getProduct(id: String): Maybe<Product> {
        return Maybe.error(NotImplementedError("default not implemented yet"))
    }

which micronaut then automatically falls-back to an implementation that reads from a map to supply the product data so it's all in memory.

When I run it in fallback configuration using the above to force it, I'm seeing a memory leak and increased response time per apache bench run until the JVM is completely thrashing GC to try and work.

If I switch the 2 services around so there's no fallback in action, then there's no issues, no increasing latency, no memory leak. i.e. the method/service that's doing all the work doesn't appear to be causing the leak. The only difference between the two scenarios is the above Maybe.error() call.

Firstly, is the above method bad in some way that might cause this issue?
And if it is, what would be a better way to do it in a 'live' scenario? e.g. if the main service is down, should I be throwing an error to cause the fallback to happen?

Here's a few graphs showing the increased heap object count. These are taken after every 20,000 requests that I'm hitting the service with:

(The lighter colour in the bars is the "mark" point that was set after running the load test for the first time to see the difference on subsequent runs.)

After 2 runs:

![image](https://user-images.githubusercontent.com/1616940/48899699-32ac2a80-ee48-11e8-8ddc-704bc132f025.png)

After 3 runs:

![image](https://user-images.githubusercontent.com/1616940/48899742-540d1680-ee48-11e8-84df-ccb015fee347.png)

After 4 runs:

![image](https://user-images.githubusercontent.com/1616940/48899792-7010b800-ee48-11e8-9c63-a8b98348f75b.png)

In the diagrams (all taken after a forced GC), the class StaticProductCatalogueService is the service that is being "fallback"ed to.

The class count increases consistently with the number of requests I'm making. The counts are pretty linear in increase per run, which is what makes me believe it's leaking.

**Comment by markjfisher** [comment]
ok, it'll take a while to cut down a project to show this, but i'll upload one to github

**Comment by markjfisher** [comment]
I've create a repo at https://github.com/markjfisher/mn-leak
The README.md has all the instructions.

**Comment by graemerocher** [comment]
Seems the qualifier used didn't implement equals/hashCode - could you try the latest 1.0.x branch once the build completes and let me know if it resolved the problem for you?

**Comment by markjfisher** [comment]
I've not done that before. Do I just checkout the 1.0.x branch and run publish maven local, or are the assets deployed somewhere I can directly use from a build?

**Comment by graemerocher** [comment]
You need to add the https://oss.sonatype.org/content/repositories/snapshots/ repo to your maven repos then set your Micronaut version to `1.0.2.BUILD-SNAPSHOT` on this line:

```
dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:1.0.2.BUILD-SNAPSHOT'
    }
}
```

**Comment by markjfisher** [comment]
Thanks for the information.

Yes, that's solved the issue. I'm seeing the fallback work correctly without the same profile as previously.

Excellent. Thanks for the fix.
