### ISSUE TITLE
GraalVM native tests fail with Kotlin `1.9.0`

### ISSUE THREAD

**Issue by sgammon** [micronaut-projects/micronaut-core#9547]
### Expected Behavior

1. Upgrade Micronaut codebase to Kotlin `1.9.0`
2. Run `nativeTest`

### Actual Behaviour

It should run the tests, but instead it fails with:

```
kotlin.annotation.AnnotationTarget was unintentionally initialized at build time
```
and
```
kotlin.annotation.AnnotationRetention was unintentionally initialized at build time
```

### Steps To Reproduce

1. Generate a Micronaut app with GraalVM, at v4.0.0
2. Run the tests, observe that it works
3. Upgrade to Kotlin `1.9.0`
4. Run the tests, observe failure

### Environment Information

- Operating System: macOS Ventura
- JDK Version: `GraalVM EE 22.3.1 (build 19.0.2+7-jvmci-22.3-b11)` and `GraalVM 20.0.1+9.1 (build 20.0.1+9-jvmci-23.0-b12)`

### Example Application

https://github.com/sgammon/kotlin-1.9.0-gvm-reproducer

### Version

4.0.0-RC1

**Comment by sgammon** [comment]
filed with Kotlin team at [`KT-60211`](https://youtrack.jetbrains.com/issue/KT-60211/Kotlin-1.9.0-kotlin.annotation.AnnotationTarget-was-unintentionally-initialized-at-build-time-GraalVM-nativeTest) and GraalVM team at oracle/graal#6957.

i've mostly determined this to be related only to Kotlin and GraalVM, but seeing as it breaks Micronaut downstream, i filed here so others can find it / it can be tracked ahead of v4 release.

**Comment by sdelamo** [comment]
@sgammon is this still present?

**Comment by sgammon** [comment]
@sdelamo The issues upstream haven't been fixed (for that version of Kotlin), but we no longer hit this issue, and the GraalVM and Kotlin teams are tracking it. I think it's safe to close with respect to Micronaut.
