### ISSUE TITLE
KSP failure with Kotlin Client in micronaut-k8s guide

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-core#9550]
In the [4.0.0 PR for Micronaut Guides](https://github.com/micronaut-projects/micronaut-guides/pull/1269), the micronaut-k8s guide `api` project is currently set to use Kapt for annotation processing, and it builds successfully with:

```
./gradlew clean micronautK8sBuild --no-build-cache
```

Removing [kapt from the `kotlinFeatures`](https://github.com/micronaut-projects/micronaut-guides/blob/81ec66455c80fbbbb9e34f566b9e75de20221315/guides/micronaut-k8s/metadata.json#L22) so it builds with KSP and re-running the command results in test failures for the kotlin api project:

https://scans.gradle.com/s/rmif3ykomr7po/tests/overview?outcome=failed

I believe the underlying cause is [shown here](https://scans.gradle.com/s/rmif3ykomr7po/tests/task/:test/details/example.micronaut.GatewayControllerTest/orders()?top-execution=1):

```
java.lang.AbstractMethodError: Receiver class example.micronaut.$GatewayControllerTest$OrdersClient0$Definition$Intercepted does not define or inherit an implementation of the resolved method 'abstract java.util.List getOrders()' of interface example.micronaut.clients.OrdersClient.
```

I'm hoping this is the cause of the [mockito errors](https://scans.gradle.com/s/rmif3ykomr7po/tests/task/:test/details/example.micronaut.GatewayControllerTest/createOrderUserDoesntExists()?top-execution=1) (which I don't currently understand)

### To Reproduce

- Check out the `sdelamo-patch-3` branch of micronaut-guides
- Remove the [kapt feature](https://github.com/micronaut-projects/micronaut-guides/blob/81ec66455c80fbbbb9e34f566b9e75de20221315/guides/micronaut-k8s/metadata.json#L22)
- Run `./gradlew clean micronautK8sBuild --no-build-cache`
- See it failing
- open `build/code/micronaut-k8s/micronaut-k8s-gradle-kotlin/api` in intellij to just look at the failing project

**Comment by timyates** [comment]
I tried to create a simple reproducer here in core, but I couldn't find where it should go 😞

**Comment by timyates** [comment]
This could be because the guide is using a property getter in [the client](https://github.com/micronaut-projects/micronaut-guides/blob/1658a6ca45c5be06dbae8ac42ab17173afc4585e/guides/micronaut-k8s/api/kotlin/src/main/kotlin/example/micronaut/clients/OrdersClient.kt)

```
@Client("orders") // <1>
interface OrdersClient {
    @Get("/orders/{id}")
    fun getOrderById(id: Int): Order

    @Post("/orders")
    fun createOrder(@Body order: Order?): Order

    @get:Get("/orders")
    val orders: List<Order>

    @get:Get("/items")
    val items: List<Item>

    @Get("/items/{id}")
    fun getItemsById(id: Int): Item
}
```

(see orders and items)

**Comment by timyates** [comment]
There may be an issue in `@MockBean` in the `GatewayControllerTest` as well, but I'm not sure 🤔

**Comment by timyates** [comment]
Another datapoint:

We see a similar mockito error in the kotlin test for the micronaut-rabbitmq guide

Again, remove the `"kotlinFeatures": ["kapt"]` and run `./gradlew clean mRabbitmqBuild --no-build-cache`

```
Argument passed to verify() is of type $BookControllerTest$AnalyticsClient0$Definition$Intercepted and is not a mock!
```

**Comment by sdelamo** [comment]
is this still pending?

**Comment by timyates** [comment]
I don't believe Kotlin, KSP and Mockito (I suspect with `@MockBean`) work together...

I will try and create a simpler reproducer

**Comment by timyates** [comment]
Tried to create a reproducer, and it works for both Kapt and KSP, this can be closed AFAICT
