### ISSUE TITLE
Possible incorrect links in User Guide

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9566]
### Issue description

@jef
> There are some links at [docs.micronaut.io/3.9.3/guide/](https://docs.micronaut.io/3.9.3/guide/) which point to snapshot docs in places where I think it probably should point to 3.9.3 docs.
> 
> Example:
> 
> 
> <a href="https://docs.micronaut.io/snapshot/guide/#nettyClientPipeline">configure the Netty Client Pipeline</a>
> 
> I do not know which other versions of the doc have similar content

**Comment by jeffscottbrown** [comment]
This is not the same thing, but related...

When view the 3.9.4 docs at https://micronaut-projects.github.io/micronaut-docs-mn3/3.9.4/guide/index.html, there are a lot of links that point to "latest".  

Example:

`<a href="https://docs.micronaut.io/latest/guide/#bootstrap">Bootstrap</a>`

This is going to cause confusion as folks navigating through the user guide are going to be hopping from the docs for 3.9.4 to whatever version of the docs is the latest at a particular moment.

**Comment by sdelamo** [comment]
@guillermocalvo just use `<<nettyClientPipeline, configure the Netty Client Pipeline>>` for that link.

**Comment by guillermocalvo** [comment]
Merged: #9567

**Comment by jeffscottbrown** [comment]
I think there are still snapshot references in the 3.9.3 docs.  Ex:
```

<a href="https://docs.micronaut.io/snapshot/guide/#propertySource"><code>PropertySourceLoader</code></a>

 <a href="https://docs.micronaut.io/snapshot/guide/#nettyClientPipeline">configure the Netty Client Pipeline</a> and to <a href="https://docs.micronaut.io/snapshot/guide/#nettyServerPipeline">

<a href="https://docs.micronaut.io/snapshot/guide/#nettyServerPipeline">configure the Netty Server Pipeline</a>
```

**Comment by jeffscottbrown** [comment]
I think there is the same issue with links to latest like:

`<a href="https://docs.micronaut.io/latest/guide/#bootstrap">Bootstrap</a>`

**Comment by guillermocalvo** [comment]
> I think there are still snapshot references in the 3.9.3 docs.

I just checked [the 3.9.4 docs](https://micronaut-projects.github.io/micronaut-docs-mn3/3.9.4/guide/index.html#_3_7_0) and `PropertySourceLoader` still points to `/snapshot/`, even though #9567 was merged 🤔

@sdelamo Do you know if there's anything else we need to do to actually publish the updated HTML files?

**Comment by sdelamo** [comment]
Documentation gets published upon release. Your changes are visible in 3.9.5

**Comment by sdelamo** [comment]
@richardson-e can you please evaluate the current docs. 

It seems the problem with latest still persist. 

@jeffbrown 
> There are a lot of places in the 3.9 docs that link to /latest.  Ex:
> 
> <a href="https://docs.micronaut.io/latest/guide/#distributedConfigurationVault">HashiCorp Vault</a>
> 
> <a href="https://docs.micronaut.io/latest/api/io/micronaut/context/env/BootstrapPropertySourceLocator.html">BootstrapPropertySourceLocator</a>
> 
> <a href="https://docs.micronaut.io/latest/api/io/micronaut/inject/ast/package-summary.html">Element API</a>
> 
> Etc...
> 
> I think that is going to cause confusion as folks will inadvertently navigate from the 3.9 user guide to whatever is the latest version on whatever day they click those links.

Additionally, please, go through every link in the documentation, identify them and fix any broken link. 

To generate docs in the 4.0.x branch run `./gradlew docs`. 

@richardson-e please use 4.0.x as the PR base not 3.9.x.

**Comment by wetted** [comment]
I'm also seeing broken links to javase docs, where our links are missing the module prefix. I'll fix these too.
