### ISSUE TITLE
Micronaut 4 can't identificate enum in generics with kotlin

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#9571]
Simple example to reproduce:
```kotlin
@Controller("/hello")
class HelloController {

    @Get
    @Produces(MediaType.TEXT_PLAIN)
    fun index(@Nullable @QueryValue("channels") channels: Collection<Channel>?) = "Hello World"

    @Introspected
    enum class Channel {
        SYSTEM1,
        SYSTEM2
    }
}
```
I found problem in `AbstractOpenApiVisitor` when I check generic type to enum (when class Channel processing):
```java
        ClassElement componentType = type != null ? type.getFirstTypeArgument().orElse(null) : null;
        Map<String, ClassElement> typeArgs = type != null ? type.getTypeArguments() : null;

context.warn("type = " + type + ", type.isEnum " + type.isEnum() + ", componentType = " + componentType + ", typeArgs = " + (typeArgs != null ? typeArgs.entrySet().stream().map(entry -> entry.getKey() + " -> " + entry.getValue()).collect(Collectors.joining("\n", "", "")) : "null"), null);
```

In logs I see:
```
type = example.micronaut.HelloController$Channel, type.isEnum false, componentType = null, typeArgs = 
```

and this:
```
type.getClass().getName() = io.micronaut.annotation.processing.visitor.JavaWildcardElement
```

With micronaut-openapi 4.9.2 and micronaut 3.9.4 all works fine

### Version

4.0.0

**Comment by altro3** [comment]
@dstepanov please, look to this. Related issue: https://github.com/micronaut-projects/micronaut-openapi/issues/1131

**Comment by altro3** [comment]
@dstepanov Also interesting, that problem only with kotlin collections. When use `Array<Channel>?` all woks fine

**Comment by altro3** [comment]
@dstepanov I figured out what the problem is. The behavior of the core has changed: earlier in my case, when calling type.getFirstTypeArgument() , it was TypeElement that was returned, and now WildcardElement is returned. Is this a bug or a feature?

**Comment by dstepanov** [comment]
It’s a feature. Is it KSP or KAPT?

**Comment by altro3** [comment]
I tested it only with kapt

**Comment by altro3** [comment]
@dstepanov Ok, this logic correct, but it means that bug in micronaut 3.x ;-)
