### ISSUE TITLE
Incorrect definition of generic in the set of enums

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#9578]
See related issue: https://github.com/micronaut-projects/micronaut-openapi/issues/1135

Classes structure:
```groovy
@CompileStatic
@Controller
class DogController {

    @Get('/dog')
    HttpResponse<Dog> get() {
        Dog dog = new Dog(
                name: 'Rex', breed: Breed.GERMAN_SHEPHERD,
                traits: EnumSet.of(Trait.QUICKNESS, Trait.COURAGE, Trait.LOYALTY)
        )

        return HttpResponse.ok(dog)
    }
}

@CompileStatic
class Dog {

    String name
    Breed breed
    Set<Trait> traits
}

@CompileStatic
enum Breed {

    GERMAN_SHEPHERD,
    BULLDOG,
    GOLDEN_RETRIEVER
}

@CompileStatic
enum Trait {

    QUICKNESS,
    COURAGE,
    LOYALTY
}
```
Bug when processing field `Set<Trait> traits`. Class of this field is `Set`.

Problem with method `type.getFirstTypeArgument().orElse(null)` - return `GroovyClassElement` with name `Trait`, but must be `GrovyEnumElement`

II've added a hack to work around this bug, but I'd like to fix it in the kernel. My crutch: I reload the class from the context by name and then the correct `GroovyEnumElement` is returned to me

### Version

3.9.4

**Comment by altro3** [comment]
@dstepanov Could you look?

**Comment by altro3** [comment]
@dstepanov With microanut 4.0 all works fine, bug only in micronaut 3

**Comment by dstepanov** [comment]
It would be to complicated to fix in v3

**Comment by altro3** [comment]
It's clear. Okay, this is not a critical bg. since my crutch works and allows you to bypass it
