### ISSUE TITLE
@RequestScope no longer works in micronaut 4.0

### ISSUE THREAD

**Issue by StefanSrf** [micronaut-projects/micronaut-core#9579]
### Expected Behavior

@RequestScope continues to work like in micronaut 3.9. The following two features no longer work:
- Default value assignments in Kotlin class constructors of @RequestScope classes
- @RequestScope objects should be freshly initialized for each http request.

### Actual Behaviour

- Default value assignments in Kotlin class constructors are ignored. The value is assigned null. If the type is defined as non-nullable the request fails.
- @RequestScope object behaves like a Singleton and retains state of previous requests.

### Steps To Reproduce

- Assign a default value to a @RequestScope object, e.g:
```
@RequestScope
class RequestScopeClass(
    // this no longer works in micronaut 4.0, default value is ignored and as a result type can't be non-null
    var text: String = "defaultText",
)
```

- Assign a request scoped value and check in a subsequent request if the assigned value was reset.

The example application contains tests for both cases.

### Environment Information

- Linux
- JDK 17

### Example Application

https://github.com/StefanSrf/micronaut-4-0-request-scope-bug

### Version

4.0.0

**Comment by sdelamo** [comment]
@dstepanov could the Request Scope issue be related to the new Context propagation api?

**Comment by dstepanov** [comment]
No, it might be because of KSP. I'm sure default parameters aren't supported yet. Not sure how it would work with KAPT anyway

**Comment by sdelamo** [comment]
@dstepanov will this work in 4.1. with the work with default parameters?

**Comment by dstepanov** [comment]
No, beans don’t support it yet

**Comment by StefanSrf** [comment]
@dstepanov: Note that RequestScope does not work correctly, even if no default parameters are used. RequestScope now basically behaves like a Singleton. Values from previous requests are not reset. Problems related to this may be very hard to track.

**Comment by chrisparton1991** [comment]
I'm currently migrating a Kotlin app to Micronaut 4.0.2. I haven't been able to reproduce these `@RequestScope` issues. Each request populates a new copy of the request-scoped object, and I can set+read variables with default values inside the objects.

KSP was mentioned above. I'm not using KSP anywhere yet, so that may be why it's working for me.

**Comment by chrisparton1991** [comment]
Update: I tested this in a fresh repository and can confirm that `@RequestScope` breaks with KSP.

Using `kapt` instead of `ksp` for the Serde processor was enough to get it working for me:

```gradle
// Added kapt plugin
id("org.jetbrains.kotlin.kapt") version "1.8.22"
...
// @RequestScope still works with KSP added as a plugin
id("com.google.devtools.ksp") version "1.8.22-1.0.11"
...

// Changed from ksp to kapt
kapt("io.micronaut.serde:micronaut-serde-processor")
```
