### ISSUE TITLE
MN:4.0.0 ProxyHttpClient: Parse Error: "Content-Length" and "Transfer-Encoding" can't be present in the response headers together

### ISSUE THREAD

**Issue by roar-skinderviken** [micronaut-projects/micronaut-core#9584]
### Expected Behavior

We have an API Gateway that proxies requests further into our architecture using ProxyHttpClient. The app has been running with MN since MN:3.2. When migrating to MN:4.0.0 from 3.9.4, the user of the API experienced difficulties accessing the API, and we started to get errors in the logs.

### Actual Behaviour

I was able to reproduce the problem in a MRE app (please see below).

The example app runs on port 8080. The management endpoints runs on port 8081. The GatewayController will proxy requests from port 8080 to port 8081.

With Postman, when accessing 
http://localhost:8081/health/liveness
with the example application, everything works fine as expected.

When accessing the proxied endpoint
http://localhost:8080/gateway/health/liveness
Postman says "Could not get response"
Parse Error: "Content-Length" and "Transfer-Encoding" can't be present in the response headers together

### Steps To Reproduce

- Clone and build https://github.com/roar-skinderviken/mn-content-length-issue
- Start the app: `mvn mn:run`
- Verify that you can access http://localhost:8081/health/liveness (with Postman)
- Then try to access the proxied liveness on port 8080: http://localhost:8080/gateway/health/liveness (with Postman)

Observe the following error in Postman
![image](https://github.com/micronaut-projects/micronaut-core/assets/7499642/c81d6319-7a44-4a30-9372-0ae540073f81)

### From the logs
Stack trace  from Google Cloud. The app is running in GKE.

"A task raised an exception. Task: io.micronaut.http.server.netty.handler.PipeliningServerHandler$StreamingOutboundHandler$$Lambda$1015/0x0000000100c03590@693eff42"
stack_trace: "java.lang.IllegalStateException: onComplete before request?
at io.micronaut.http.server.netty.handler.PipeliningServerHandler$StreamingOutboundHandler.onComplete(PipeliningServerHandler.java:859)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:833)

### Environment Information

Ubuntu 22.04
OpenJDK Temurin 17.0.7

### Example Application

https://github.com/roar-skinderviken/mn-content-length-issue

### Version

4.0.0

**Comment by yawkat** [comment]
thanks for the report!

**Comment by roar-skinderviken** [comment]
Thank you for a very fast fix :clap:

Did a quick test with MN:4.0.2-SNAPSHOT, and the fix works great.

**Comment by roar-skinderviken** [comment]
@yawkat First day in production with MN:4.0.2. Had to increase memory for the gateway pods (gateway is using ProxyHttpClient), else no issues :thumbsup:
