### ISSUE TITLE
(Rx1) Custom action set by RxJavaHooks.setOnScheduleAction is not applied

### ISSUE THREAD

**Issue by luckyswede** [micronaut-projects/micronaut-core#964]
Hi, thanks for a great product.
I'm scheduling rx hooks for MDC propagation for both Rx1 and Rx2. For Rx1 it doesnt work.

Micronaut 1.0.1
Rx1 1.3.8
Rx2 2.2.2

It shows the same behaviour whether tracing is enabled or not.

Code: 
```
        RxJavaHooks.setOnScheduleAction(new Rx1MdcPropagatingOnScheduleAction());
        RxJavaPlugins.setScheduleHandler(new Rx2MdcPropagatingOnScheduleFunction());
        ...
        Micronaut.run();
```
The `Action0.call` in the returned `Action0` from `Rx1MdcPropagatingOnScheduleAction.call` is not executed on scheduling of tasks in Rx1.
I have verified that hooks for Rx1 are executed in Rx1 code that run _before_ `Micronaut.run()`.

**Comment by graemerocher** [comment]
Could you provide an example that reproduces the issue you are seeing?

**Comment by luckyswede** [comment]
Ok, while cleaning up an example for this issue it seems like Rx1 scheduling is not working (or just not working as I was expected, I don't have that much Rx experience). After Micronaut has been started the subscriber within an Rx1 BlockingObservable never gets the onNext callback. Eg when running this:
```
    public static void main(String[] args) throws Exception {
        List<String> list = new LinkedList<>();
        rx1(list);
        rx2(list);
        Micronaut.run();
        rx2(list);
        rx1(list);
    }

    private static void rx1(List<String> list) {
        Observable<String> s1 = Observable.just("1", "1").subscribeOn(Schedulers.newThread());
        s1.collect(() -> list, (l, p) -> l.add(p)).toBlocking().first();
        System.out.println(i.incrementAndGet() + " " + list);
    }

    private static void rx2(List<String> list) throws ExecutionException, InterruptedException {
        Flowable<String> s2 = Flowable.just("2", "2").subscribeOn(io.reactivex.schedulers.Schedulers.newThread());
        s2.collect(() -> list, (l, p) -> l.add(p)).toFuture().get();
        System.out.println(i.incrementAndGet() + " " + list);
    }
```
the last `rx1` invocation never completes.
However when I comment out `Micronaut.run()` it runs.

This blocks me from testing the onScheduleHook :), because whenever I force a thread switch the pipeline won't complete. I'll try to dig more into it during the weekend.

**Comment by graemerocher** [comment]
Thanks we will take a look
