### ISSUE TITLE
Inject in ConfigurationProperties does not work in Micronaut 4

### ISSUE THREAD

**Issue by francesco-monorchio** [micronaut-projects/micronaut-core#9640]
### Expected Behavior

Inside a ConfigurationProperties bean I want to be able to inject another bean correctly (usually another configurationproperties).

### Actual Behaviour

With Micronaut 4 the injected field is always null.

### Environment Information

OpenSUSE Tumbleweed
JDK17

### Example Application

https://github.com/francesco-monorchio/micronaut-bugreport/tree/failed-to-inject-beans-in-configproperties

### Version

4.0.1

**Comment by roar-skinderviken** [comment]
@francesco-monorchio This is not a new issue in Micronaut 4; it is not working with Micronaut 3.9.x. (needs to be investigated further)

Normally, you will do something like this:

```
import io.micronaut.serde.annotation.Serdeable

@Serdeable
class SubConfig {
    String name
}

@ConfigurationProperties('super')
class SuperConfig {
    String name
    SubConfig sub
}
```
with this in application.yml
```
super:
  name: super
  sub:
    - name: sub
```

**Comment by roar-skinderviken** [comment]
@francesco-monorchio Created a PR in your repo with the above changes:
https://github.com/francesco-monorchio/micronaut-bugreport/pull/1

**Comment by francesco-monorchio** [comment]
Are you sure? because before moving to v4 I didn't have problems. I usually prefer injection to have more organized configurations.

**Comment by sdelamo** [comment]
Closing this for now.
