### ISSUE TITLE
Support resilience4j (Hystrix no longer being developed)

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-core#965]
As Hystrix is no longer under active development (https://github.com/Netflix/Hystrix#hystrix-status) can Micronaut have direct support for https://github.com/resilience4j/resilience4j (as per hystrix docs recommendation)?

**Comment by graemerocher** [comment]
A PR to https://github.com/resilience4j/resilience4j with an implementation for Micronaut would make sense

**Comment by RobWin** [comment]
Go go :)

**Comment by pollend** [comment]
I've made some early progress on trying to add this to resilience4j.
here is the branch I'm working on: https://github.com/pollend/resilience4j/tree/feature/micronaut

**Comment by graemerocher** [comment]
Awesome!

**Comment by RobWin** [comment]
@pollend Just ping me if you have some questions regarding Resilience4j

**Comment by pollend** [comment]
@RobWin so I'm looking at the spring plugin for some guidance with the setup. so spring uses AOP to attach to a method where the micronaut-ratelimiter will use OncePerRequestHttpServerFilter. the configuration from spring to micronaut in resilience4j is essentially the same. If you have the time would you be able to look at my branch?

https://objectcomputing.com/news/2019/10/07/micronaut-aop-awesome-flexibility-without-complexity

**Comment by pollend** [comment]
@RobWin I created a WIP PR that should be available now. I'm making some pretty good progress with the implementation.
