### ISSUE TITLE
Add request data to the SLF4J MDC Micronaut version 4

### ISSUE THREAD

**Issue by THARA40** [micronaut-projects/micronaut-core#9659]
[Document how to add request data to the SLF4J MDC](https://github.com/micronaut-projects/micronaut-core/issues/7914)

I used HttpServerFilter, but those are run on the event loop thread.

```
micronaut:
  server:
    thread-selection: io
```

Upto version 3.9.4 Thread-local MDC is supported across to the request-handling child threads by using this dependency.

```
<dependency>
	<groupId>io.micronaut</groupId>
	<artifactId>micronaut-tracing</artifactId>
	<scope>runtime</scope>
</dependency>
```

After version 4 the above dependency not supported anymore. Then I tried with opentracing dependency on version 4, but it not works,

```
<dependency>
      <groupId>io.micronaut.tracing</groupId>
      <artifactId>micronaut-tracing-opentracing</artifactId>
      <scope>runtime</scope>
</dependency>
```

I am looking for a working solution. Thanks

**Comment by graemerocher** [comment]
you have an example here https://docs.micronaut.io/latest/guide/#httpFilterContextPropagation

**Comment by THARA40** [comment]
> you have an example here https://docs.micronaut.io/latest/guide/#httpFilterContextPropagation

Thanks, I solved my issue.
