### ISSUE TITLE
@EachProperty is not working as expected in 4.0.1

### ISSUE THREAD

**Issue by marlonmoncoresfriday** [micronaut-projects/micronaut-core#9668]
I'm migrating an app from Micronaut 3 to 4 and @EachProperty does not work during tests.
I created an empty project using the lauch app as the following image
![image](https://github.com/micronaut-projects/micronaut-starter/assets/138526263/64e96761-150d-4927-9d7b-9f72a4d59414)

I created the @EachProperty bean and the tests. But both tests fail on creating the beans.
[EachPropertyTest.zip](https://github.com/micronaut-projects/micronaut-starter/files/12194560/EachPropertyTest.zip)

**Comment by graemerocher** [comment]
currently property references have to be specified in kebab case. Using `@EachProperty("my-bean")` works

**Comment by sdelamo** [comment]
@wetted can you clarify in docs that `@EachProperty` requires kebab case.

**Comment by sdelamo** [comment]
@marlonmoncoresfriday we recommend you to set it in `application.yml`as: 

```
my-bean:
  instance1:
    prop: value1
  instance2:
    prop: value2
```

Micronaut configuration uses kebab case not lower camel case.

**Comment by eddie-thp** [comment]
@sdelamo 
I see the documents were updated, but this looks like a **regression** when compared with `Micronaut 3` behavior.
is this something that should be fixed, instead of just a document update ?
I mean, should this issue be reopened ?

**Comment by sdelamo** [comment]
@eddie-thp the use of kebap-case is intentional
