### ISSUE TITLE
KSP: context.getProjectDir() return null

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#9672]
From micronaut-openapi: can't get current project directory from context, always retrun null

### Version

4.0.2

**Comment by dstepanov** [comment]
I don't think that would be possible. I have corrected the file generation, but it looks like the files are copied to the temporary directory for compilation, which prevents locating the project dir. We might want to pass the project dir location in using the build plugins.

**Comment by altro3** [comment]
@dstepanov it's not a critical bug, because users can set projectDir by annotation processor property

**Comment by nbrugger-tgm** [comment]
I am affected by this bug through micronaut openapi in micronaut v3.8.10 (yes I know v4 is out..) is there a fix for this bug in the 3.x Version line? openapi searches the openapi.properties in ~/.gradle/worker which breaks View rendering. Is there any reference/guide how to set this project dir in gradle?

Thanks for looking at this

**Comment by dstepanov** [comment]
This is a KSP issue, only introduced in v4.

**Comment by altro3** [comment]
@nbrugger-tgm Yes, sure. look to micronaut-openapi documentation:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/b500a4be-2558-45d2-b2ff-b7d24a77f52a)
And here:

![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/53088fe6-1045-4606-80c9-5ac1dacbd70e)

This property available in micronaut-openapi `4.10.0` (for micronaut v3) and  in micronaut-openapi `5.1.0` (for micronaut v4).

But as mentioned above, ksp support was added only in micronaut 4
