### ISSUE TITLE
Jackson serialization unable to serialize kotlin sealed interface correctly in version 4.0.2

### ISSUE THREAD

**Issue by byronwong-dev** [micronaut-projects/micronaut-core#9681]
## Context
- Micronaut 4.0.2
- Using jackson xml as serialization lib (not micronaut serde lib)

## Expectation

In Controller when defining the return type as interface, will be able to serialize the payload correctly
Example:
```kotlin
@Get("/")
fun foo(): Parent {
  return Parent.Foo("Zeus") // this will return json {"name":"Zeus"} in version 3
}

@Introspected
sealed interface Parent {
    @Introspected
    data class Foo (
        val name: String
    ): Parent
}
```

### Actual Behaviour

It serializes as empty object

```kotlin
@Get("/")
fun foo(): Parent {
  return Parent.Foo("Zeus") // instead it returns {} in version 4
}
```

### Steps To Reproduce

This is not working in 4.0.2, but prior to this, in version 3 it is working. Here's the working example
- [Ver 3](https://github.com/byronwong-dev/micronaut_3_http_serialization) This works fine
- [Ver 4](https://github.com/byronwong-dev/micronaut_4_http_serialization/tree/master) This isn't

Please let me know if this could be a missing setup that I've left out.

### Example Application

https://github.com/byronwong-dev/micronaut_4_http_serialization

### Version

4.0.2

**Comment by yawkat** [comment]
See #9695

> This was an intentional change as a part of https://github.com/micronaut-projects/micronaut-core/pull/9151. As an optimization, we now "bake" the body writer with the route return type when it is statically known. For jackson, this means using ObjectMapper.createWriter to prepare a writer for the specific type, which will not include subtype fields.

**Comment by byronwong-dev** [comment]
got it, as this is an expected behaviour I'll be closing the issue.
