### ISSUE TITLE
Different supertype JSON response behaviour in Micronaut 4

### ISSUE THREAD

**Issue by chrisparton1991** [micronaut-projects/micronaut-core#9695]
### Expected Behavior

A controller endpoint that returns `HttpResponse<Supertype>` should include JSON fields from the subtype object that is actually returned. I'm using Jackson databind here, not Micronaut Serde.

### Actual Behaviour

In Micronaut 4, only the supertype fields are returned.

In the example code below, we return a `Dog()` in the controller method, but we don't get specific fields like `legs` in the JSON output.

This looks to be occurring in `io.micronaut.json.body.JsonMessageHandler#writeTo()`. The workaround is to return `HttpResponse<Any>` (or presumably `HttpResponse<Object>` for Java).

In my case, I have a system that involves returning configuration data for various tasks, and each task has its own data structure. Upgrading to Micronaut 4 broke this endpoint.

```kotlin
@Controller("/")
class TestController {
    @Get("/dog")
    fun test1(): HttpResponse<Animal> = HttpResponse.ok(Dog()) // "legs" isn't returned in the JSON response.
}

interface Animal {
    val type: String
}

data class Dog(
    override val type: String = "Dog",
    val legs: Int = 4,
) : Animal
```

### Steps To Reproduce

1. Clone https://github.com/chrisparton1991/micronaut-4-json-test
2. Run `src/test/kotlin/DemoTest.kt`
3. One test will fail
4. Run the same test in the Micronaut 3 repo (https://github.com/chrisparton1991/micronaut-3-json-test), tests will pass

### Environment Information

- Operating System: MacOS Ventura
- JDK Version: OpenJDK 17.0.6
- Using Jackson databind, not Micronaut Serde

### Example Application

https://github.com/chrisparton1991/micronaut-4-json-test

### Version

4.0.3

**Comment by dstepanov** [comment]
Please try to annotate the class with `@io.micronaut.serde.annotation.Serdeable`

**Comment by yawkat** [comment]
This was an intentional change as a part of #9151. As an optimization, we now "bake" the body writer with the route return type when it is statically known. For jackson, this means using ObjectMapper.createWriter to prepare a writer for the specific type, which will not include subtype fields.

**Comment by chrisparton1991** [comment]
Fair enough, given I have an easy workaround I’m happy for this to be
closed.

I’ll also try annotating with Serdeable and see if that changes things.
Will also try migrating to Micronaut Serde when time allows.

Thanks!

**Comment by yawkat** [comment]
pretty sure serde has the same issue

**Comment by chrisparton1991** [comment]
Yep, I just meant I’ll try migrating to Serde for the performance
improvements :)

Though I’ll report back if I get a chance to test this use case in Serde
regardless.

**Comment by chrisparton1991** [comment]
I switched the v4 test repo over to Serdeable. By applying `@Serdeable` to the `Dog` class, the code works as intended (i.e. the `legs` property is returned regardless of the controller return type).

Sounds like reason enough for me to make the jump to Serdeable. I'll close this issue, appreciate the help!

**Comment by rorueda** [comment]
It's also possible to make it work with jackson databind by configuring the type for polymorphic serialization/deserialization. 

I made it by annotating the supertype with `JsonTypeInfo` and registering the subtypes with the `ObjectMapper` (one can also annotate the supertype with `JsonSubTypes`).
