### ISSUE TITLE
Propagated context cleared when using Micronaut Security

### ISSUE THREAD

**Issue by olamelin** [micronaut-projects/micronaut-core#9718]
### Issue description

Hello, 
I created an issue in the Micronaut Security project but realised that it might be related to the context propagation and therefore should be reported here. Is it the correct project to have it reported in Micronaut Security and does anyone know what might be happening?

https://github.com/micronaut-projects/micronaut-core/issues/9719

Thank you in advance.

**Comment by dstepanov** [comment]
I will check

**Comment by olamelin** [comment]
Awesome thanks

**Comment by olamelin** [comment]
https://github.com/micronaut-projects/micronaut-core/pull/9720

**Comment by olamelin** [comment]
@dstepanov we tried upgrading to 4.0.4 but the test project in https://github.com/micronaut-projects/micronaut-core/issues/9719 still fails. Is there something wrong with the setup in that project or is the root cause still around?

**Comment by dstepanov** [comment]
It's not released as part of the platform yet.

**Comment by olamelin** [comment]
Ahh OK thanks, which release is target in the platform?

**Comment by dstepanov** [comment]
Probably 4.0.5

**Comment by olamelin** [comment]
Great, thanks.
