### ISSUE TITLE
Add to Cors configuration a mapping like into grails

### ISSUE THREAD

**Issue by pierre-yves-legendre-cbp** [micronaut-projects/micronaut-core#9726]
### Feature description

In grails, it's possible to configure some mapping authorized without cors and then all other are not 

**Example :**
    _cors:
        enabled: true
        mappings:
            '[/private/open/supervision]': inherit_

I thinks, it'll be a good thinks to micronaut to accept the same configuration.
Like this for example:
   _cors:
        enabled: true
        configurations:
              web:
                 mappings:
                        - '/private/open/supervision'_

The autorizations order  can be in first **mappings* and after the other like *allowedOrigins**, etc.

**Comment by sdelamo** [comment]
You could achieve this with [annotation-based CORS Configuration](https://docs.micronaut.io/latest/guide/#annotationBasedCors)
