### ISSUE TITLE
BeanDefinitionSpec inline class return type is flaky 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9730]
`io.micronaut.kotlin.processing.beans.BeanDefinitionSpec.test inline class return type` test fails more often than it passes. I don't think we can trust it in its current sate. 

Steps to reproduce: 

./gradlew :inject-kotlin:test --tests "io.micronaut.kotlin.processing.beans.BeanDefinitionSpec.test inline class return type" 

https://ge.micronaut.io/scans/tests?search.timeZoneId=Europe/Madrid&tests.container=io.micronaut.kotlin.processing.beans.BeanDefinitionSpec&tests.test=test%20inline%20class%20return%20type

**Comment by sdelamo** [comment]
@dstepanov is this something you could look into?

**Comment by dstepanov** [comment]
yeah the method should be selected in some other way
