### ISSUE TITLE
Configuration reference documentation default values are broken

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9735]
We broken configuration reference default values in 6.x 

see: 

https://micronaut-projects.github.io/micronaut-security/3.11.1/guide/configurationreference.html

![CleanShot 2023-08-17 at 13 14 25@2x](https://github.com/micronaut-projects/micronaut-build/assets/864788/ba0da83a-53fa-4532-988c-d5b61a4056c0)

https://micronaut-projects.github.io/micronaut-security/4.0.0/guide/configurationreference.html

![CleanShot 2023-08-17 at 13 15 01@2x](https://github.com/micronaut-projects/micronaut-build/assets/864788/d1d1f781-c2da-4db7-8512-40a19e28c8bf)

**Comment by sdelamo** [comment]
@timyates give priority to this

**Comment by timyates** [comment]
Think this may be in micronaut-docs...  Checking

**Comment by timyates** [comment]
Actually, it may be in PropertyMetadata in core 🤔
