### ISSUE TITLE
Groovy return empty string instead null when call `element.getValue(...)`

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#9736]
From micronaut-openapi: sample class
```java
@Controller
class TestController {

    @Post(uri = "/breaks")
    MutableHttpResponse<?> breaks(@Body Map body) {
        return HttpResponse.accepted()
    }
}
```

When `body` paramater is processing, I call `element.getValue(Bindable.class, "defaultValue", String.class).orElse(null);` to get default value from annotation. As you see in calss I don't set default value, but this method return empty line `""`

The same tes works fine with java, bug only in groovy.

### Version

4.0.2

**Comment by altro3** [comment]
@dstepanov Look to this, please

**Comment by altro3** [comment]
Related issue: https://github.com/micronaut-projects/micronaut-openapi/issues/1169

**Comment by dstepanov** [comment]
Why not call `stringValue`?

**Comment by dstepanov** [comment]
I believe this is v4 change. The element now contains the default values and is returning them. To avoid getting the default you should use `stringValue`.

**Comment by altro3** [comment]
@dstepanov hmm.. understand. Yes, with stringValue all works fine. So, could you review my PR's and merge them?

**Comment by altro3** [comment]
@dstepanov Hmm... I was thinking, it turns out that the bug is on the other side. The problem now is that micronaut returns different results in groovy and java. In my opinion, the behavior should be the same both there and there.

In general, if you call `element.getValue(Bindable.class, "defaultValue", String.class).orElse(null);` in Java, then you get `null`. If you call the same line in a groovy, then you will get an `empty line`

**Comment by dstepanov** [comment]
Hmm, strange. But `stringValue` work correctly for both?

**Comment by altro3** [comment]
Yeah, stringValue return null in Groovy and in Java
