### ISSUE TITLE
Executor IO settings not honoured

### ISSUE THREAD

**Issue by markjfisher** [micronaut-projects/micronaut-core#974]
### Task List

- [X] Example that reproduces the problem uploaded to Github
- [X] Full description of the issue provided (see below)

### Description

The documented values to fix the number of threads in the IO pool don't appear to be working.

https://docs.micronaut.io/latest/guide/index.html#reactiveServer describes setting:

    micronaut:
      executors:
        io:
          type: fixed
          nThreads: 5

but the example application below when hit with >5 concurrent requests is creating threads to match instead of being limited.

Test code is effectively:

    @Get("/{id}")
    fun getId(id: String): Maybe<String> {
        logger.info { "getId: on thread ${Thread.currentThread().name}"}
        return Maybe
                .just(id)
                .subscribeOn(Schedulers.io())
                .doOnEvent { success, throwable ->
                    try { Thread.sleep(500) } catch (_: Exception) {}
                    logger.info { "doOnEvent called success: $success, throwable: $throwable, thread: ${Thread.currentThread().name}" }
                }
                .map { it }
    }

If I remove the `subscribeOn(Schedulers.io())` line, the NIO event loop thread is reported, illustrating it is moving it to the IO thread.

### Environment Information

- **Operating System**: linux
- **Micronaut Version:** 1.0.2.BUILD_SNAPSHOT
- **JDK Version:** oracle 8

### Example Application

https://github.com/markjfisher/mn-schedulers

**Comment by jameskleeh** [comment]
`io.reactivex.schedulers.Schedulers.io()` doesn't have anything to do with Micronaut, so it won't read anything in configuration. If you want to use the configured IO thread pool, you can inject the named executor service.

`class Controller(@Named(TaskExecutors.IO) private val executionService: ExecutorService) {`

then

`.subscribeOn(Schedulers.from(executionService))`

**Comment by markjfisher** [comment]
Thanks Steve, sorry for the noise, but this wasn't clear from the docs, and in fact searching/googling for TaskExecutors.io and micronaut only leads to hits on the source code (which I wouldn't have done before knowing the solution), so this might be worth making a bit more clear in the section where it describes configuring the executor. I can raise a PR if you like once I have it working locally? Maybe it's just me though!

**Comment by markjfisher** [comment]
Thanks James, sorry for the noise, but this wasn't clear from the docs, and in fact searching/googling for TaskExecutors.io and micronaut only leads to hits on the source code (which I wouldn't have done before knowing the solution), so this might be worth making a bit more clear in the section where it describes configuring the executor. I can raise a PR if you like once I have it working locally? Maybe it's just me though!

**Comment by jameskleeh** [comment]
@markjfisher Absolutely if you think the docs could be improved, a PR is welcome

**Comment by AceHack** [comment]
@Named(TaskExecutors.IO) for sure needs lots better documentation.  It's impossible to find something as simple as a plain non-blocking http call with retires that does this correctly.
