### ISSUE TITLE
Micronaut-management submodule lacks of logging

### ISSUE THREAD

**Issue by rlconst** [micronaut-projects/micronaut-core#9740]
### Feature description

In case of troubleshoouting it'll be good to be able to log specific health checks results as it could affect mesh of services i.e. service liveness depends on several indicators and you want to troubleshoot what indicator exactly prevent service to be UP

For context github [search](https://github.com/search?q=repo%3Amicronaut-projects%2Fmicronaut-core%20path%3A%2F%5Emanagement%5C%2F%2F%20log&type=code) I used

Currently I have to enable full http debug: `<logger name="io.micronaut.http" level="debug"/>`

**Comment by sdelamo** [comment]
We have a configuration setting `endpoints.health.details-visible`. However, I assume you may want to have details off in the endpoint but see the details in the logs. is that correct?

**Comment by rlconst** [comment]
Correct, because I dont have access to health endpoint in production contour, but have access to logs18 авг. 2023 г., в 14:31, Sergio del Amo ***@***.***> написал(а):﻿
We have a configuration setting endpoints.health.details-visible. However, I assume you may want to have details off in the endpoint but see the details in the logs. is that correct?

**Comment by sdelamo** [comment]
> Correct, because I dont have access to health endpoint in production contour, but have access to logs18 авг. 2023 г., в 14:31, Sergio del Amo ***@***.***> написал(а):﻿ We have a configuration setting endpoints.health.details-visible. However, I assume you may want to have details off in the endpoint but see the details in the logs. is that correct? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

make sense to me to improve the logging.
