### ISSUE TITLE
KSP: ClassElement.isEnum() return false for kotlin enums

### ISSUE THREAD

**Issue by altro3** [micronaut-projects/micronaut-core#9754]
### Expected Behavior

From micronaut-openapi: Don't know what about java with ksp, but kotlin enums not defined correctly. It was not possible to configure the debugger, but you can see everything in the logs.

1. Sample controller:
```kotlin
@Controller("/hello")
class HelloController {

    @Get
    @Produces(MediaType.TEXT_PLAIN)
    fun index(@Nullable @QueryValue("channels") channels: Collection<Channel>?) = ""

    @Introspected
    enum class Channel {
        SYSTEM1,
        SYSTEM2
    }
}
```

2. logging in AbstractOpenApiVisitor in micronaut-openapi:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/b4db6e71-0901-4ed2-8711-62e8239a40eb)

3. Logs in gardle asssemble:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/62337f9b-99c6-4b60-9e27-187602e3debf)

As you see, method `isEnum()` return false

### Version

4.1.1

**Comment by altro3** [comment]
@dstepanov please, look to this

**Comment by altro3** [comment]
@dstepanov I see, that I have wrong element. Must be `KotlinEnumElement` but I see `KotlinTypeArgumentElement`

**Comment by dstepanov** [comment]
You might need to call resolved

**Comment by altro3** [comment]
Already do it:

![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/955e421e-d443-4294-a624-410580a62731)

This code works fine with kapt, but doesn't work with ksp

**Comment by altro3** [comment]
@dstepanov i think, it's better, if merge all changes from branch 4.1.x to 4.2.x. and after it you will see only my changes.

I don't know another way to sync new branch in fork. I need to create branch with the same name - 4.2.x, but I need to start this branch from 4.1.x. And in original repo ypu still didn't merge branch 4.1.x. Jsut merge 4.1.x to 4.2.x

**Comment by altro3** [comment]
@dstepanov I checked your last changes: still have a problem. That's what I see now:
![изображение](https://github.com/micronaut-projects/micronaut-core/assets/48474279/9d089b86-4e93-4133-8519-699152eabe47)

I see. that I need to call the resolved method to get my `EnumElement` . But here's the problem `KotlinTypeArgumentElement ` implements a `GenericElement `, although in this context it should be a `GenericPlaceholderElement` . And the `GenericElement` interface does not have a resolved method.

That is, it turns out that `KotlinGenericPlaceholderElement` should be returned to me, and I get `KotlinTypeArgumentElement`....

I see 2 solutions:

1. Add the resolved method to the GenericElement interface.
2. Return KotlinGenericPlaceholderElement instead of KotlinTypeArgumentElement

**Comment by dstepanov** [comment]
Already did 1. Check 4.2.X branch

**Comment by altro3** [comment]
Yeah, sorry, You already did it.... mb
