### ISSUE TITLE
kapt problem with Kotlin serialization plugin enabled

### ISSUE THREAD

**Issue by luistrigueiros** [micronaut-projects/micronaut-core#976]
I am trying to build  a kotlin 1.3 project with the Kotlin serialization compiler plugin enabled.
It looks like there is a problem with the with the micronaut kapt compiler with the kotlin serialization enable both are using kapt annotations processing.
I would like to use kotlin serialization features to make reflection-less codec.  

> λ gradle test
> Starting a Gradle Daemon (subsequent builds will be faster)
> e: [kapt] An exception occurred: java.lang.NullPointerException
>         at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
>         at io.micronaut.caffeine.cache.BoundedLocalCache.getIfPresent(BoundedLocalCache.java:1524)
>         at io.micronaut.caffeine.cache.LocalManualCache.getIfPresent(LocalManualCache.java:49)
>         at io.micronaut.annotation.processing.AnnotationUtils.getAnnotationMetadata(AnnotationUtils.java:123)
>         at io.micronaut.annotation.processing.JavaConfigurationMetadataBuilder.<init>(JavaConfigurationMetadataBuilder.java:57)
>         at io.micronaut.annotation.processing.BeanDefinitionInjectProcessor.init(BeanDefinitionInjectProcessor.java:118)
>         at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.init(annotationProcessing.kt)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment$ProcessorState.<init>(JavacProcessingEnvironment.java:500)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.next(JavacProcessingEnvironment.java:597)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:690)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
>         at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
>         at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
>         at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)
>         at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:55)
>         at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:27)
>         at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.runAnnotationProcessing(Kapt3Extension.kt:218)
>         at org.jetbrains.kotlin.kapt3.AbstractKapt3Extension.analysisCompleted(Kapt3Extension.kt:183)

**Comment by jameskleeh** [comment]
Can you provide an example application?

**Comment by luistrigueiros** [comment]
Hi @jameskleeh :

I have created a simple hellow world app to reproduce the issue at https://github.com/luistrigueiros/micronaut-kapt-issue.

Unfortunately it does not happens in this simple repo yet, I can't disclose the original one.
Will iterate on this to reproduce it in the simple example.
Oscar

**Comment by luistrigueiros** [comment]
Hi @jameskleeh 
I have upgraded my build to 1.0.1 and this not happens any more. 
Maybe it is better to close this issue.

Thank you, kindly
 Luis Oscar Trigueiros
