### ISSUE TITLE
Micronaut 4 - ServerRequestContext empty after reactive DB call

### ISSUE THREAD

**Issue by j1m-renwick** [micronaut-projects/micronaut-core#9773]
### Expected Behavior

Calling Mongo via its reactive API should not affect the ServerRequestContext request data

### Actual Behaviour

ServerRequestContext.currentRequest() becomes an empty Optional after the call is made

### Steps To Reproduce

1. run [request-context-bug.zip](https://github.com/micronaut-projects/micronaut-core/files/12423679/request-context-bug.zip) (local MongoDB instance must be running on port 27017 and have a database named `test`)
2. call GET http://localhost:8080/test
3. see the logging in the output:
```
Before mongo call ServerRequestContext.currentRequest() present: true
.....
After mongo call ServerRequestContext.currentRequest() present: false
```
4. Switch out the commented plugins in `build.gradle` and version in `gradle.properties` to downgrade to Micronaut 3.9.0
5. Repeat the API call and see the logging: 
```
Before mongo call ServerRequestContext.currentRequest() present: true
.....
After mongo call ServerRequestContext.currentRequest() present: true
```

### Environment Information

Operating System: MacOS Ventura, Version 13.4
JDK Version: Coretto 17

### Example Application

See above

### Version

4.0.3

**Comment by yawkat** [comment]
The context is not propagated automatically anymore in 4.x: https://docs.micronaut.io/latest/guide/index.html#contextPropagation
