### ISSUE TITLE
Default pagination implementation

### ISSUE THREAD

**Issue by BogdanOros** [micronaut-projects/micronaut-core#981]
A suggestion is to add support of default pagination abstraction similar to Springs one for `@HttpMethodMapping` via TypedRequestArgumentBinder (same approach as with PrincipalTypeArgumentBinder). 
- Pageable abstraction for HttpRequest parameters
- PaginationConfiguration for limit/offset naming and default/min/max value for limit query parameter.
- Page<> response type for paginated `Iterable<>`

Maybe I can help with it and create the implementation via PR?

**Comment by graemerocher** [comment]
Sounds good. Contributions welcome

**Comment by BogdanOros** [comment]
Created a PR for this feature. Currently, it contains a configuration and Pageable binding.

**Comment by BogdanOros** [comment]
Resolved the CLA issue on pull #986

**Comment by graemerocher** [comment]
Great, I plan to work on improved APIs for data access for 1.1 so will incoporate the PR in some form in this work. Thanks for the contribution

**Comment by jameskleeh** [comment]
Closing because this issue is resolved with Micronaut Data
