### ISSUE TITLE
PoolTimeoutSpec is flaky 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9844]
### Issue description

https://ge.micronaut.io/scans/tests?search.timeZoneId=Europe/Madrid&tests.container=io.micronaut.http.client.PoolTimeoutSpec&tests.test=cancelled%20pool%20acquire%20should%20not%20leak%20connection

**Comment by timyates** [comment]
Ok, ran this in isolation 40+ times on 4.1.x with no failure

Then ran :http-client:test on a loop and it failed...  So I suspect something is persisting between tests and interfering

**Comment by timyates** [comment]
Hopefully fixed by https://github.com/micronaut-projects/micronaut-core/pull/10084
