### ISSUE TITLE
Provide an error message when application.yml is present, but snake yaml is not on the classpath

### ISSUE THREAD

**Issue by matejdro** [micronaut-projects/micronaut-core#9864]
### Feature description

It seems like Micronaut only loads yaml config when Snakeyaml is present on the classpath:

https://github.com/micronaut-projects/micronaut-core/blob/637b8a6494bde7fb134a406c843c43fda9882c4b/inject/src/main/java/io/micronaut/context/env/yaml/YamlPropertySourceLoader.java#L44

However, this fail is very silent. I spent an entire afternoon banging my head against the wall on why my config will not load.

Maybe this could be solved in a better way? Perhaps, YamlPropertySourceLoader should throw an exception if `application.yml` is found, but there is no SnakeYaml?

**Comment by yawkat** [comment]
If you have an application.yml but snakeyaml is missing, the gradle and maven plugins should print a warning/error. Did that not work in your case? Make sure your build plugins are up-to-date as well.

**Comment by matejdro** [comment]
Huh, it appears I'm not using the Gradle plugin, I'm just manually declaring micronaut dependencies.
