### ISSUE TITLE
log4j appender is ignored for http access logger

### ISSUE THREAD

**Issue by hunsricker** [micronaut-projects/micronaut-core#9865]
### Expected Behavior

Each received request should produce one log statement written to the file http-access.log. The log format specified in the log4j2.xml must be used.

### Actual Behaviour

Each request causes two lines written to the console. The format specified with the property _micronaut.server.netty.access-logger.log-format_ is used or if no format is specified, the common one is used.

### Steps To Reproduce

1. Start the application
2. call the URL http://localhost:9080/writehttpaccesslogstofile
3. take a look into the http-access.log file

### Environment Information

- OS: macOS Ventura 13.5.2
- Java 17

### Example Application

https://github.com/hunsricker/writeHttpAccessLogsToFile

### Version

4.1.4

**Comment by yawkat** [comment]
It's because you're using slf4j-simple instead of log4j2.
