### ISSUE TITLE
Micronaut client send a request to wrong URL in certain conditions 

### ISSUE THREAD

**Issue by dmeshkov-brex** [micronaut-projects/micronaut-core#9868]
### Expected Behavior

Clients always use the URL setting from application.yaml properties `micronaut.http.services.*.url` and never redirect to other URL.

### Actual Behaviour

when we supply URL path with double trailing slashes Micronaut redirects to that host for some reason.

There is a risk of SSRF attack if client works this way - it modifies client behavior substantially.

### Steps To Reproduce

1. Setup micronaut client
2. Setup properties for the client URL `micronaut.http.services.*.url` to https://youtube.com
3. Implement the client instantiation logic and perform the request like this:
```

        val request = HttpRequest
            .create<String>(originalRequest.method, urlPath)
   
```
Example input to urlPath: `//google.com`
5.  Observe that client performs request to google.com

### Version

3.3.4

**Comment by yawkat** [comment]
The client follows the logic of [URI.resolve](https://docs.oracle.com/javase/8/docs/api/java/net/URI.html#resolve-java.lang.String-). If the URI passed to HttpRequest.create is absolute like yours, then that URI will be used. There is no guarantee that it will stay within the service URI. You should not let users pass an arbitrary URI, it could lead to issues even if we were to disallow passing a host, e.g. if they pass `../secret`.
