### ISSUE TITLE
Logger configured at application.yml does not show messages at application log

### ISSUE THREAD

**Issue by lsborg** [micronaut-projects/micronaut-core#9884]
### Expected Behavior

Logger configuration on application.yml should work as [user guide](https://docs.micronaut.io/4.1.1/guide/index.html#loggingConfiguration). 

### Actual Behaviour

Application log does not show messages from loggers configured at application.yml. 

### Steps To Reproduce

1. Create an application with cli - `mn create-app --build=maven --jdk=17 --lang=java --test=spock com.example.log-yaml`
2. Add an application.yml file
3. Insert logging message `logger.debug('log yaml spec')` inside method `'test it works'` at `LogYamlSpec.java`.
4. Configure logger at application.yml run test and look for message
```
logger:
  levels:
    com.example.LogYamlSpec: DEBUG
```

### Environment Information

- OS: Ubuntu 22.04 (WSL)
- JDK 17.0.7 Correto

### Example Application

https://github.com/lsborg/micronaut-log-yaml

### Version

4.1.1

**Comment by msupic** [comment]
There is no
```
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <scope>runtime</scope>
    </dependency>
```
in `pom.xml`. Without that dependency `application.yml` is not read at all.

https://micronaut.io/2023/02/19/micronaut-framework-4-0-and-snakeyaml-transitive-dependency/

**Comment by yawkat** [comment]
why isnt micronaut-maven-plugin failing?

**Comment by graemerocher** [comment]
@alvarosanchez I thought we put in place compile time checks for this?

**Comment by alvarosanchez** [comment]
Clone the above repo and run `mvn compile` (or any other command) and you will see the failure

**Comment by yawkat** [comment]
well then we're good :)
