### ISSUE TITLE
Maven Central versions are out of sync

### ISSUE THREAD

**Issue by kirill-linnik** [micronaut-projects/micronaut-core#9886]
### Expected Behavior

Well, it doesn't have some latest versions and we want them :)

### Actual Behaviour

But it doesn't! :)))

### Steps To Reproduce

1. Go to https://repo.maven.apache.org/maven2/io/micronaut/platform/micronaut-platform/
2. As of now, the latest version is 4.1.1 and 4.0.7
3. If you check here: https://github.com/micronaut-projects/micronaut-core/releases <- it mentions 4.1.5 and 4.0.6 as latest

### Version

4.1.1

**Comment by graemerocher** [comment]
you're looking at the wrong project https://github.com/micronaut-projects/micronaut-platform/releases

**Comment by kirill-linnik** [comment]
> you're looking at the wrong project https://github.com/micronaut-projects/micronaut-platform/releases

OK, I will try to explain it in different words. On GitHub you have releases *not present* on Maven Central. And, for my project, I get jar's not from github, but through Gradle from Maven Central. and if I put, for example, 4.1.5, it won't compile, becuase Gradle will say: cannot find this version.

I hope it explains

**Comment by sgammon** [comment]
@kirill-linnik 

> On GitHub you have releases not present on Maven Central

[Micronaut Core version `4.1.5` is available on Maven Central.](https://search.maven.org/artifact/io.micronaut/micronaut-core/4.1.5/jar)

> Gradle will say: cannot find this version.

It will only say this if you try to use the Micronaut Core version as a version catalog, but these are different artifacts.

Micronaut Core is not the same as Micronaut Platform, and typically you add the Micronaut Platform to your app. Micronaut Core isn't something you usually version or add directly; Micronaut Platform includes it _for_ you at the right version.

All you need to do is:

**`settings.gradle.kts`**:
```kotlin
dependencyResolutionManagement {
  versionCatalogs {
    create("mn") {
      from("io.micronaut.platform:micronaut-platform:$micronautVersion")
    }
  }
}
```

Now, you can do the following in your project:

**`build.gradle.kts`**:
```kotlin
dependencies {
  implementation(mn.micronaut.core)
}
```

This will include the correct `micronaut-core` version for the top-level `micronautVersion` in your project.

If you _really need_ to override the Micronaut Core version, which isn't usually a good idea, there are still some ways to do it. Of course you can include your own dependency:

```kotlin
dependencies {
  implementation("io.micronaut:micronaut-core:4.1.5")
}
```

This isn't a good idea because `micronaut-core` may not align with the rest of your version catalog / the rest of the Micronaut dependencies. It's important that it aligns.

A cleaner way to do it is to use the [catalog plugin](https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#sec:micronaut-platform-catalog-plugin):

**`settings.gradle.kts`**:
```kotlin
plugins {
  id("io.micronaut.platform.catalog") version "4.1.0"
}
```

Which can [override versions](https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#sec:overriding-version):

**`gradle/mn-override.versions.toml`**:
```toml
[versions]
micronaut-core = "4.5.0" # override version of Micronaut Core
```

Or [use the DSL](https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#_using_the_dsl):

```kotlin
micronaut {
    coreVersion.set("4.5.0") // override the version of Micronaut Core
}
```

**Comment by kirill-linnik** [comment]
> @kirill-linnik
> 
> > On GitHub you have releases not present on Maven Central
> 
> [Micronaut Core version `4.1.5` is available on Maven Central.](https://search.maven.org/artifact/io.micronaut/micronaut-core/4.1.5/jar)
> 
> > Gradle will say: cannot find this version.
> 
> It will only say this if you try to use the Micronaut Core version as a version catalog, but these are different artifacts.
> 
> Micronaut Core is not the same as Micronaut Platform, and typically you add the Micronaut Platform to your app. Micronaut Core isn't something you usually version or add directly; Micronaut Platform includes it _for_ you at the right version.
> 
> All you need to do is:
> 
> **`settings.gradle.kts`**:
> 
> ```kotlin
> dependencyResolutionManagement {
>   versionCatalogs {
>     create("mn") {
>       from("io.micronaut.platform:micronaut-platform:$micronautVersion")
>     }
>   }
> }
> ```
> 
> Now, you can do the following in your project:
> 
> **`build.gradle.kts`**:
> 
> ```kotlin
> dependencies {
>   implementation(mn.micronaut.core)
> }
> ```
> 
> This will include the correct `micronaut-core` version for the top-level `micronautVersion` in your project.
> 
> If you _really need_ to override the Micronaut Core version, which isn't usually a good idea, there are still some ways to do it. Of course you can include your own dependency:
> 
> ```kotlin
> dependencies {
>   implementation("io.micronaut:micronaut-core:4.1.5")
> }
> ```
> 
> This isn't a good idea because `micronaut-core` may not align with the rest of your version catalog / the rest of the Micronaut dependencies. It's important that it aligns.
> 
> A cleaner way to do it is to use the [catalog plugin](https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#sec:micronaut-platform-catalog-plugin):
> 
> **`settings.gradle.kts`**:
> 
> ```kotlin
> plugins {
>   id("io.micronaut.platform.catalog") version "4.1.0"
> }
> ```
> 
> Which can [override versions](https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#sec:overriding-version):
> 
> **`gradle/mn-override.versions.toml`**:
> 
> ```toml
> [versions]
> micronaut-core = "4.5.0" # override version of Micronaut Core
> ```
> 
> Or [use the DSL](https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#_using_the_dsl):
> 
> ```kotlin
> micronaut {
>     coreVersion.set("4.5.0") // override the version of Micronaut Core
> }
> ```

this feature seems to be too experimental (as it is mentioned here: https://github.com/micronaut-projects/micronaut-core/wiki/Gradle-Build-Tips), when I do:

`gradle.properties`:
```
micronautVersion=4.1.6
```

`settings/gradle`:
```
dependencyResolutionManagement {
  versionCatalogs {
    create("mn") {
      from("io.micronaut.platform:micronaut-platform:$micronautVersion")
    }
  }
}
```
and then `build.gradle`:
```
dependencies {
  annotationProcessor(platform(mn))
  //here are lot of other dependencies in old stile
} 
```
I get:
```
Could not resolve all artifacts for configuration 'incomingCatalogForMn0'.
> Cannot resolve external dependency io.micronaut.platform:micronaut-platform:4.1.6 because no repositories are defined.
  Required by:
      unspecified:unspecified:unspecified

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```
...but it works in old-fashioned way

**Comment by sgammon** [comment]
@kirill-linnik it says no repositories are defined:

> because no repositories are defined.

You can fix this with:

```kotlin
dependencyResolutionManagement {
  repositories {
    mavenCentral()
  }

  versionCatalogs {
    create("mn") {
      from("io.micronaut.platform:micronaut-platform:$micronautVersion")
    }
  }
}
```

The `repositories` block defines `mavenCentral` as the place to pull repositories.

With regard to the annotation processor, you will want to do:
```
dependencies {
  annotationProcessor(mn.micronaut.inject.java)
}
```

**Comment by kirill-linnik** [comment]
> @kirill-linnik it says no repositories are defined:
> 
> > because no repositories are defined.
> 
> You can fix this with:
> 
> ```kotlin
> dependencyResolutionManagement {
>   repositories {
>     mavenCentral()
>   }
> 
>   versionCatalogs {
>     create("mn") {
>       from("io.micronaut.platform:micronaut-platform:$micronautVersion")
>     }
>   }
> }
> ```
> 
> The `repositories` block defines `mavenCentral` as the place to pull repositories.
> 
> With regard to the annotation processor, you will want to do:
> 
> ```
> dependencies {
>   annotationProcessor(mn.micronaut.inject.java)
> }
> ```

I wish to go there (btw, do I understand correctly, that I will need to refresh dashes and colons to dots? for example, `"io.micronaut.spring:micronaut-spring-annotation"` will be transformed into `mn.spring.micronaut.spring.annotation`? maybe you have some page for that?), but I still get an error for `4.1.6`, but a new one:

```
Could not resolve all artifacts for configuration 'incomingCatalogForMn0'.
> Could not find io.micronaut.platform:micronaut-platform:4.1.6.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/io/micronaut/platform/micronaut-platform/4.1.6/micronaut-platform-4.1.6.pom
  If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
  Required by:
      unspecified:unspecified:unspecified

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

BTW, if I put it to `4.1.2`, which is the latest found in the Maven Central, then I get different error (with `annotationProcessor(platform("mn"))`):

```
> Supplied String module notation 'mn' is invalid. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core:1.9.5:javadoc'.
```
Or (with `annotationProcessor(platform(mn))`):
```
A problem occurred evaluating project '...'.
> Cannot convert the provided notation to an object of type Dependency: extension 'mn'.
  The following types/formats are supported:
    - String or CharSequence values, for example 'org.gradle:gradle-core:1.0'.
    - Maps, for example [group: 'org.gradle', name: 'gradle-core', version: '1.0'].
    - FileCollections, for example files('some.jar', 'someOther.jar').
    - Projects, for example project(':some:project:path').
    - ClassPathNotation, for example gradleApi().
```
I have the latest gradle 8.3

**Comment by sdelamo** [comment]
> 3\. If you check here: https://github.com/micronaut-projects/micronaut-core/releases <- it mentions 4.1.5 and 4.0.6 as latest

In your issue you mention: 

> If you check here: https://github.com/micronaut-projects/micronaut-core/releases <- it mentions 4.1.5 and 4.0.6 as latest

as Graeme mentioned it should be: 

https://github.com/micronaut-projects/micronaut-platfrom/releases

instead of: 

https://github.com/micronaut-projects/micronaut-core/releases

Micronaut Platform: 

> This Micronaut Platform module specifies the Bill of Materials (BOM) for the Micronaut Project, also known as the Micronaut Platform.

> The Micronaut Platform is a collection of modules that can be used to build Micronaut applications and have been verified to work well together.

> It aggregates many of the individual Micronaut module BOMs and provides a single BOM to manage the versions of all the modules.


Micronaut Framework release is not a Micronaut Core release. 

Since Micronaut Framework 4. A Micronaut Framework Releases = [Micronaut Platform](https://github.com/micronaut-projects/micronaut-platform)  + [Micronaut Starter](https://github.com/micronaut-projects/micronaut-starter) (CLI and [Launch](https://launch.micronaut.io))

You can find how to use [the Version Catalogue in the Micronaut Platform documentation](https://micronaut-projects.github.io/micronaut-platform/latest/guide/index.html#repository).

**Comment by kirill-linnik** [comment]
> > 3. If you check here: https://github.com/micronaut-projects/micronaut-core/releases <- it mentions 4.1.5 and 4.0.6 as latest
> 
> In your issue you mention:
> 
> > If you check here: https://github.com/micronaut-projects/micronaut-core/releases <- it mentions 4.1.5 and 4.0.6 as latest
> 
> as Graeme mentioned it should be:
> 
> https://github.com/micronaut-projects/micronaut-platfrom/releases
> 
> instead of:
> 
> https://github.com/micronaut-projects/micronaut-core/releases
> 
> Micronaut Platform:
> 
> > This Micronaut Platform module specifies the Bill of Materials (BOM) for the Micronaut Project, also known as the Micronaut Platform.
> 
> > The Micronaut Platform is a collection of modules that can be used to build Micronaut applications and have been verified to work well together.
> 
> > It aggregates many of the individual Micronaut module BOMs and provides a single BOM to manage the versions of all the modules.
> 
> Micronaut Framework release is not a Micronaut Core release.
> 
> Since Micronaut Framework 4. A Micronaut Framework Releases = [Micronaut Platform](https://github.com/micronaut-projects/micronaut-platform) + [Micronaut Starter](https://github.com/micronaut-projects/micronaut-starter) (CLI and [Launch](https://launch.micronaut.io))
> 
> You can find how to use [the Version Catalogue in the Micronaut Platform documentation](https://micronaut-projects.github.io/micronaut-platform/latest/guide/index.html#repository).

yeah, the correct link would be https://github.com/micronaut-projects/micronaut-platform/releases but the way @sgammon suggests to do gradle configuration simply doesn't work for me :(

**Comment by kirill-linnik** [comment]
ah, I found an error and maybe it makes sense documenting in the manual, because, well, it is not so straight forward. I had to be doing `annotationProcessor(platform(mn.micronaut.platform))` instead of `annotationProcessor(platform(mn))` :))
