### ISSUE TITLE
netty server response without body throw ClassCastException

### ISSUE THREAD

**Issue by asantare** [micronaut-projects/micronaut-core#9894]
### Expected Behavior

no exception is thrown and an empty Http response 304 is returned

### Actual Behaviour

`java.lang.ClassCastException` is thrown:
`class io.netty.handler.codec.http.DefaultHttpResponse cannot be cast to class io.netty.handler.codec.http.FullHttpResponse`

it seems that `RoutingInBoundHandler` always expects a `FullHttpResponse` (cast) while in this case a `DefaultHttpResponse` is created in `NettyHttpResponseBuilder.toHttpResponse`

### Steps To Reproduce

1. server `Controller`s endpoint that returns a `HttpResponse` that is not a Netty response with no body provided (for example the `SimpleHttpResponse`)
2. invoke the endpoint

(see test case in the provided project)

### Environment Information

- mac OS
- JDK 17

was working in 3.x

### Example Application

https://github.com/asantare/micronaut-core-httpserver-bug

### Version

4.1.1

**Comment by graemerocher** [comment]
not sure if this is a bug, use `HttpResponse.ok()` etc. static methods not the factories directly

**Comment by asantare** [comment]
indeed, I had some HttpFilter code for the 3.x to create a new response and this code was using the `HttpResponse.ok`, I had changed it to use the `SimpleHttpResponseFactory` because in AWS environment the default factory was the `MicronautAwsProxyResponseFactory` which returned the AWS proxy response and not a new response.

But now I see that `MicronautAwsProxyResponseFactory` is gone from the 4.1.x, so I guess the HttpFilter should get a new response when using the `HttpResponse.ok`.

Thanks I'll use that approach then.

Not sure about the `SimpleHttpResponseFactory` then, I mean, when is it used? or when can it be used?

**Comment by asantare** [comment]
it works fine with the default response factory.
I'll close this specific issue, regarding the usefulness of `SimpleHttpResponseFactory` to be seen in another place.
