### ISSUE TITLE
Typo in documentation Annotation Interface Factory

### ISSUE THREAD

**Issue by FeliciaMarlove** [micronaut-projects/micronaut-core#9897]
### Issue description

For example for a singleton instance you can **annotation** the method with Singleton. -> Should be "annotate"

**Comment by alvarosanchez** [comment]
Thanks for reporting the issue. Would you be willing to contribute a PR fixing it? There is an "Improve this doc" button next to each chapter that will take you directly to the GitHub edit view.

**Comment by FeliciaMarlove** [comment]
Would gladly do, but sorry I can't see that button 🙈

**Comment by FeliciaMarlove** [comment]
I would gladly do but I can't find that button 🙈

**Comment by alvarosanchez** [comment]
I couldn't find the typo you mentioned. Can you point us the exact link where the typo appears?
