### ISSUE TITLE
Retryable on a reactive HttpClient logs warnings but continues

### ISSUE THREAD

**Issue by turneand** [micronaut-projects/micronaut-core#9899]
### Expected Behavior

We unfortunately have a relatively flaky network, so rely heavily on the Retryable annotation to retry any failed connections, similar to the following:
```
    @Retryable(attempts = "5", delay = "5s")
    @Client("/")
    public interface MyClient {
        @Get(uri = "/sayHelloError")
        Mono<String> sayHelloError();
    }
```

The actual semantics of retry all still work correctly, we don't expect ReadTimeoutException's to be logged after the first retry attempt.

### Actual Behaviour

In micronaut 4.x, we are now receiving the following warning in the logs.  Although this doesn't appear to impact the application, unsure if this is an underlying issue that will bite us later.
```
09:06:39.154 [custom-event-loop-nioEventLoopGroup-3-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.timeout.ReadTimeoutException: null
```

### Steps To Reproduce

Please see sample application at https://github.com/turneand/micronaut-retryable-warning
This includes a test case that when run will demonstrate the issue (although test is not able to assert anything other than the retryable flows do still work/retry as expected).

1. Define an endpoint that we can control the http response for:
```
public class SimpleController {
    private int counter;

    @Get(uri = "/sayHelloError")
    public HttpResponse sayHelloError() {
        if (++counter < 3) {
            return HttpResponse.serverError();
        }
        return HttpResponse.ok("hello-no-error");
    }
}
```

1. Create an HttpClient with Retryable annotation:
```
    @Retryable(attempts = "5", delay = "5s")
    @Client("/")
    public interface MyClient {
        @Get(uri = "/sayHelloError")
        Mono<String> sayHelloError();
    }
```

1. Invoke client, this should try up to 5 times to get the remote call, which will succeed on the fourth call.  Note the times here are artificially higher than the "real" application, but is able to recreate the issue consistently.

### Environment Information

Windows10/11 + RHEL8
Java17

### Example Application

https://github.com/turneand/micronaut-retryable-warning

### Version

4.1.1

**Comment by enricojonas** [comment]
We are having the same warnings since Micronaut 4 upgrade. Would be nice to know what this is about and if it can be fixed.

**Comment by yawkat** [comment]
Thanks for the reproducer!
