### ISSUE TITLE
Api versioning not working, instead returns Bad Request

### ISSUE THREAD

**Issue by thiagohora** [micronaut-projects/micronaut-core#9928]
### Expected Behavior

Given the following controller, Micronaut should route the request based on the correct API version.

```
@Controller("/dog")
public class DogCountControllerV1 {

    @Get(value = "/count")
    @Version("1")
    public Flowable<String> countV1(@QueryValue("max") @Nullable Integer max) {
        return Flowable.fromStream(
            Stream.iterate(0, i -> i + 1)
                .map(index -> "Dog " + index)
                .limit(max == null ? 10 : max)
        );
    }


    @Get(uri = "/count")
    @Version("2")
    public Flowable<String> countV2(@Nonnull Integer max) {
        return Flowable.fromStream(
                Stream.iterate(0, i -> i + 1)
                        .map(index -> "Dog " + index)
                        .limit(max)
        );
    }

}

```

Test:

```
    @Test
    void countV2() {

        final var actual = Flowable.fromPublisher(
            client.retrieve(HttpRequest.GET("/dog/count?max=10").header("X-API-VERSION", "2"))
        ).count().blockingGet();

        Assertions.assertEquals(6, actual);
    }
 
```

application.yml

```
micronaut:
  router:
    versioning:
      enabled: true
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
```

### Actual Behaviour

Rather than properly route the request, the application returns 400, saying it cannot solve the route.

``` 
05:23:17.371 [default-nioEventLoopGroup-3-2] TRACE i.m.h.client.netty.DefaultHttpClient - {"_links":{"self":[{"href":"/dog/count?max=10","templated":false}]},"_embedded":{"errors":[{"message":"More than 1 route matched the incoming request. The following routes matched /dog/count: GET - /dog/count, GET - /dog/count"}]},"message":"Bad Request"}
``` 

### Environment Information

JDK 17
Maven 3.8.6
Micronaut 4.1.2 runtime netty 
Micronaut rxjava3 3.0.1

### Version

4.1.2

**Comment by timyates** [comment]
Could it be you're missing `@QueryValue` from the v2 handler?

**Comment by thiagohora** [comment]
Hi @timyates 

No, because I'm configuring the header-based routing. You can see the @Version annotation in both.

**Comment by caioguedes** [comment]
Hey @thiagohora, I've been testing some configuration and found a strange workaround... using  `.properties` file for your application configuration seems to be able to enable this feature and make the bean loaded in the context of the application.

Could you test if it works for you? Use the following `application.properties`.
```
micronaut.router.versioning.enabled=true
micronaut.router.versioning.header.enabled=true
```
Obs.: The default name of the header is already `X-API-VERSION` so I just omitted here.

I am doing more validation to find the root of the problem...

**Comment by caioguedes** [comment]
@thiagohora, I just find out that I was missing a dependency to add support to `yaml`, so you should add the `org.yaml:snakeyaml` package in your project, and then your application starts using the `application.yml`. As I could see, Java Properties and JSON are the default options. 

You can check more details [here](https://docs.micronaut.io/4.1.6/guide/#config).

**Comment by thiagohora** [comment]
Make sense, let me try.

**Comment by thiagohora** [comment]
Sorry for the delay, @caioguedes. Thank you very much. This fixed the problem.

**Comment by yawkat** [comment]
we recommend using the micronaut maven/gradle plugins, they detect when youre using yaml without the right dependency.
