### ISSUE TITLE
Remove logback native image metadata

### ISSUE THREAD

**Issue by msupic** [micronaut-projects/micronaut-core#9929]
Remove reflection [metadata file](https://github.com/micronaut-projects/micronaut-core/blob/4.1.x/context/src/main/resources/META-INF/native-image/io.micronaut/micronaut-context/reflect-config.json) once a new version (0.3.5) of [graalvm-reachability-metadata](https://github.com/oracle/graalvm-reachability-metadata) gets released and also when `micronaut-gradle-plugin` and `micronaut-maven-plugin` start using the released metadata version.

**Comment by sdelamo** [comment]
0.3.5 was released two weeks ago. https://github.com/oracle/graalvm-reachability-metadata/releases/tag/0.3.5

@msupic can we work towards closing this issue?

**Comment by msupic** [comment]
@sdelamo - The Native Build Tools is still using `0.3.4` version of metadata. Once they release a new version of NBT which uses `0.3.5` version of metadata, we can upgrade micronaut maven and gradle plugins and then remove the temporary metadata files from the micronaut-core project

**Comment by graemerocher** [comment]
@melix do you know when this will happen?

**Comment by melix** [comment]
I am not aware of a new release of NBT, however we can still include newer releases of the metadata repository if needed.

**Comment by msupic** [comment]
@sdelamo - I removed the native image metadata that exist in the shared metadata repo: https://github.com/micronaut-projects/micronaut-core/pull/10453
