### ISSUE TITLE
Generate reflect-config.json instead of using a Graal Feature 

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9931]
I was talking to the GraalVM team and they are recommending that frameworks should output `reflect-config.json` files instead of using a [`org.graalvm.nativeimage.hosted.Feature`](https://github.com/micronaut-projects/micronaut-core/blob/4.1.x/core/src/main/java/io/micronaut/core/io/service/ServiceLoaderInitialization.java). 

Reflection registered via a feature is invisible to the agent and thus running the agent will output more information than necessary. I guess the same apply to resources registration which we do in our build plugins. I assume we should be generating `resource-config.json` instead. 

cc @graemerocher @melix  @vjovanov @fniephaus @alvarosanchez

**Comment by graemerocher** [comment]
this is what we had before and we removed it because it is not possible to build `reflect-config.json` incrementally

**Comment by sdelamo** [comment]
Maybe, we could add a setting so that the `micronaut-graal` annotation processor could generate `refect-config.json` files for scenarios where we don't need incremental builds.  E.g. publishing modules ( `micronaut-aws`) with `reflect-config.json` files. Although, maybe `micronaut-aws` should not have any `@TypeHint` code at all and that should live in the GraalVM Metadata repository.

**Comment by graemerocher** [comment]
in general we should avoid reflection configuration in individual modules except as a temporary workaround until upstream metadata exists. I am closing this since I don't think it is worth fixing.
