### ISSUE TITLE
StreamingFileUpload fails when multipart.disk=true

### ISSUE THREAD

**Issue by mmindenhall** [micronaut-projects/micronaut-core#994]
In #975, I confirmed that netty does not allow for "streaming" file uploads.  The entire request body is either buffered in memory, or to a file on disk.  The in-memory approach is limited to 2GB, after which the buffer capacity overflows `Integer.MAX_VALUE`.

I therefore changed my focus to testing with `micronaut.server.multipart.disk=true`.

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Clone my [micronaut-examples fork](https://github.com/mmindenhall/micronaut-examples)
1. `cd micronaut-examples/hello-world-kotlin`
1. `git checkout large-file-upload-disk`
1. `./gradlew :cleanTest :test --info --tests example.UploadControllerTest`
1. In the provided test, a temp file of any size fails.

### Expected Behaviour

The file upload should succeed when using `micronaut.server.multipart.disk=true`.

### Actual Behaviour

The file upload fails.  Here's the stacktrace:

```
java.lang.IndexOutOfBoundsException: null
	at io.netty.buffer.EmptyByteBuf.checkIndex(EmptyByteBuf.java:1055)
	at io.netty.buffer.EmptyByteBuf.retainedSlice(EmptyByteBuf.java:893)
	at io.micronaut.http.server.netty.multipart.NettyPartData.getByteBuf(NettyPartData.java:109)
	at io.micronaut.http.server.netty.multipart.NettyPartData.getInputStream(NettyPartData.java:63)
	at example.UploadController$postSet$upload$1.apply(UploadController.kt:42)
	at example.UploadController$postSet$upload$1.apply(UploadController.kt:23)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onNext(FlowableOnBackpressureBuffer.java:112)
	at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:54)
	at io.reactivex.subjects.ReplaySubject$UnboundedReplayBuffer.replay(ReplaySubject.java:770)
	at io.reactivex.subjects.ReplaySubject.subscribeActual(ReplaySubject.java:330)
	at io.reactivex.Observable.subscribe(Observable.java:12090)
	at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer.subscribeActual(FlowableOnBackpressureBuffer.java:46)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.Flowable.subscribe(Flowable.java:14426)
	at io.micronaut.http.server.netty.multipart.NettyStreamingFileUpload.subscribe(NettyStreamingFileUpload.java:169)
	at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.Flowable.subscribe(Flowable.java:14426)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:53)
	at io.micronaut.http.context.ServerRequestContext.lambda$instrument$0(ServerRequestContext.java:69)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

After some debugging, I discovered the subscriber is invoked as expected with a `NettyPartData`, but with `multipart.disk=true`, `NettyPartData.getByteBuf` always returns `io.netty.buffer.EmptyByteBuf`.

Regardless, the current Micronaut implementation would encounter the same problem as reported in #975 (see `io.netty.handler.codec.http.multipart.AbstractDiskHttpData:283`).  When `multipart.disk=true`, `NettyPartData.getByteBuf` will call that method, which attempts to read the entire file into a byte array, then return a buffer wrapping the array.  That buffer would also overflow capacity at 2GB.

So it appears that Micronaut will need to behave differently depending on whether the `FileUpload` created by Netty is using memory or disk.

### Environment Information

- **Operating System**: macOS 10.14 (Mojave)
- **Micronaut Version:** 1.1.0.BUILD-SNAPSHOT
- **JDK Version:** 1.8.0_191

### Example Application

- See above

**Comment by mmindenhall** [comment]
@jameskleeh, @graemerocher, would it be possible to do a short investigation on this and give a timeline on when it might be resolved?  My project includes an endpoint that needs to accept files as large as 10GB.  If there's a way to fix this without netty trying to read the entire file into memory, that would be fantastic (I'm pretty busy the next two weeks, but I can try to help if you can point me in the right direction).  If this won't be possible, we will unfortunately need to abandon using Micronaut for this service.

Long term, the netty issue (see [#3359](https://github.com/netty/netty/issues/3559#issuecomment-158469168) and [#859](https://github.com/netty/netty/issues/859)) is unlikely to go away.  Would you consider adding support for another framework (e.g., undertow) in Micronaut?

**Comment by mmindenhall** [comment]
Thanks @jameskleeh.  I looked at `getChunk`, but it appears to only support reading a chunk from the start of the file.

**Comment by jameskleeh** [comment]
It should also advance the reading index so the next call to it should start from the end of the last chunk read

**Comment by jameskleeh** [comment]
@mmindenhall Upon further inspection it appears not to be the case. I think I have a solution ready. I'll push it after i add a test

**Comment by jameskleeh** [comment]
@mmindenhall I have a working solution that also includes the transfer of control of backpressure after the route is executed.

For disk uploads I'm opening a FileChannel and keeping it open allowing for concurrent reads. When the final chunk is read the channel is closed.

**Comment by mmindenhall** [comment]
@jameskleeh, Awesome...very much appreciated!  I'd like to start testing with it as soon as possible.  Is it something you can push to a branch?

**Comment by jameskleeh** [comment]
@mmindenhall I've pushed the `file_handling_changes` branch. Check it out

**Comment by mmindenhall** [comment]
Thanks @jameskleeh!

 I ran my test with a 3GB file.  This required the `start` being declared as `long` instead of `int`:

`NettyPartData:46`: (also change in constructor (line 55) and cast back to `int` (line 119) when using `MemoryFileUpload`)
```
    private final long start;
```
`RoutingInboundHandler:726`: 
```
long start = partPositions.get(dataKey);
```

The good news is that it does work.  However, it works as follows:

1. The entire multipart request (one small JSON part, one 3GB file part) is uploaded by the HttpClient.  I can watch the temp file created by netty grow in my temp folder.
1. _After_ the entire file has been uploaded, the `StreamingFileUpload` subscriber starts to receive `PartData` chunks.  All of the chunks are successfully processed, and the request completes successfully.

Is there any way to trigger the subscriber as the chunks are being received from Netty so the chunks can be read from the file and processed nearly as quickly as they're being received?

**Comment by jameskleeh** [comment]
@mmindenhall I've pushed an update to support mixed file uploads as well

**Comment by mmindenhall** [comment]
Yes, it's certainly possible that I'm doing something wrong.  I'm just starting to grock RxJava/Kotlin.  It looks like I had forgotten to push my test, so I made a couple of updates just now and pushed it.  See the "Steps to Reproduce" in the original report above.  I figured out how do upload the same files using curl the other night, so I'll try that as well.

**Comment by mmindenhall** [comment]
Hmm...running the test works, but attempting the same request with curl fails almost right away:

```
22:53:22.339 [nioEventLoopGroup-1-2] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matching route POST - /upload
22:53:22.349 [nioEventLoopGroup-1-2] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matched route POST - /upload to controller class example.UploadController
22:53:23.033 [pool-1-thread-2] INFO  example.UploadController - ===== posted DataSet: DataSet(dataSourceId=dsId1, stateId=null, mode=FULL, metadata={datatype=com.vendavo.cloud.datatypes.Transaction}, path=null, tenantId=null)
22:53:23.034 [pool-1-thread-2] INFO  example.UploadController - ===== attempting to write uploaded file to /var/folders/sq/5png5p093k5f88d1kqr_wkdx6wptnw/T/very_large_file.avro2909463285962836561.temp
22:53:23.036 [pool-1-thread-2] INFO  example.UploadController - ===== Executing upload.blockingGet()
22:53:23.049 [RxCachedThreadScheduler-1] INFO  example.UploadController - ===== copied chunk #0, size 0 bytes
22:53:23.054 [pool-1-thread-2] ERROR example.UploadController - Upload failed:
java.nio.channels.ClosedChannelException: null
        at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
        at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:721)
        at io.micronaut.http.server.netty.multipart.NettyPartData.getByteBuf(NettyPartData.java:122)
        at io.micronaut.http.server.netty.multipart.NettyPartData.getInputStream(NettyPartData.java:72)
        at example.UploadController$postSet$upload$1.apply(UploadController.kt:42)
        at example.UploadController$postSet$upload$1.apply(UploadController.kt:23)
        at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:63)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
...
```

Here are instructions to reproduce this:

1. Clone (or pull) my [micronaut-examples fork](https://github.com/mmindenhall/micronaut-examples)
1. `git checkout large-file-upload-disk`
1. Run the test once (to create a 2.1GiB file in $TMPDIR):
    ```
    ./gradlew :cleanTest :test --info --tests example.UploadControllerTest
    ```
1. Run the server:  `./gradlew run`
1. In a different terminal window/tab: `cd $TMPDIR`
1. `ls -lactr` (verify very_large_file.avro exists)
1. Create dataSet.json file with these contents:
    ```json
    {
        "dataSourceId": "dsId1",
        "mode": "FULL",
        "metadata": {
            "datatype": "com.vendavo.cloud.datatypes.Transaction"
        }
    }
    ```
1. Run this curl command:
    ```
    curl -v "http://localhost:8080/upload" \
        -H "Transfer-Encoding:chunked" \
        -H "Content-Type:multipart/form-data" \
        -H "Tenant-Id:1234" \
        -F "dataSet=@dataSet.json;type=application/json" \
        -F "dataFile=@very_large_file.avro;type=avro/binary"
    ```

**Comment by jameskleeh** [comment]
@mmindenhall I can't reproduce the exception you see above. Did you test with the latest pull from the branch? As far as the route execution time, I was able to see that using our client caused the file to be uploaded first even though it was added after the json file. That causes the route to not get executed until after the file is completely uploaded.

I also discovered a bug in the flow control logic and pushed an update.

**Comment by jameskleeh** [comment]
@mmindenhall I've discovered why in the test the file is being uploaded first. Fix being pushed now

**Comment by mmindenhall** [comment]
Hi @jameskleeh, the exception I reported 3 comments above happens every time, even with your latest commits.

It looks like this is a bug in the version of curl that ships with macOS Mojave.

```bash
# Using this version fails
$ curl --version
curl 7.54.0 (x86_64-apple-darwin18.0) libcurl/7.54.0 LibreSSL/2.6.4 zlib/1.2.11 nghttp2/1.24.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets HTTPS-proxy

# Using curl installed from homebrew succeeds
$ /usr/local/opt/curl/bin/curl --version
curl 7.62.0 (x86_64-apple-darwin18.0.0) libcurl/7.62.0 SecureTransport zlib/1.2.11
Release-Date: 2018-10-31
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets
```

Here's what happens with curl 7.54.0:

1. The first `PartData` always arrives with `start=0`, `length=0`, and `fileUpload.definedLength()=0`.
1. The channel is closed (`NettyPartData:124-125`).  
1. The next `PartData` arrives (this time with correct values)
1. The channel read on line 122 throws a `ChannelClosedException`.

I was able to work around this by checking the file length on line 124:

```java
                if (fileUpload.definedLength() != 0 && start + length == fileUpload.definedLength()) {
```
That check _seems_ innocuous, but perhaps in some other edge case would result in the channel not being closed.

**Comment by mmindenhall** [comment]
@jameskleeh, I think we can call this fixed with or without the check in the my previous comment.  If the check is excluded, I can note the curl failure in our documentation.  We'd like to move ahead with testing in our CI/CD environment, which means we need an accessible snapshot build.  Would it be possible to merge the branch and trigger a new build?

Thanks again for getting this resolved so quickly!

**Comment by mmindenhall** [comment]
Hi @jameskleeh, I've been traveling this week for meetings, so just got back to this.  I tested with your latest changes, and it appears that the flow control makes the request processing become **increasingly** slow as chunks are processed (despite running on a MacBook Pro with plenty of RAM and a fast SSD).  For example, look at these results (updated test pushed to hello-world-kotlin in [my fork](https://github.com/mmindenhall/micronaut-examples)):

```
11:55:52.306 [Test worker] INFO  example.UploadControllerTest - 

===== Starting test with file size 0.2 GB =====


11:55:52.328 [Test worker] INFO  example.UploadControllerTest - ===== created temporary file
11:55:52.473 [multithreadEventLoopGroup-3-2] DEBUG i.m.http.client.DefaultHttpClient - Sending HTTP Request: POST /upload
11:55:52.473 [multithreadEventLoopGroup-3-2] DEBUG i.m.http.client.DefaultHttpClient - Chosen Server: localhost(62211)
11:55:52.501 [nioEventLoopGroup-1-2] DEBUG i.m.h.server.netty.NettyHttpServer - Server localhost:62211 Received Request: POST /upload
11:55:52.505 [nioEventLoopGroup-1-2] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matching route POST - /upload
11:55:52.513 [nioEventLoopGroup-1-2] DEBUG i.m.h.s.netty.RoutingInBoundHandler - Matched route POST - /upload to controller class example.UploadController
11:55:53.134 [pool-1-thread-8] INFO  example.UploadController - ===== posted DataSet: DataSet(dataSourceId=dsId1, stateId=null, mode=FULL, metadata={datatype=com.vendavo.cloud.datatypes.Transaction}, path=null, tenantId=null)
11:55:53.135 [pool-1-thread-8] INFO  example.UploadController - ===== attempting to write uploaded file to /var/folders/sq/5png5p093k5f88d1kqr_wkdx6wptnw/T/transactions-001.avro584872802771444169.temp
11:55:53.139 [pool-1-thread-8] INFO  example.UploadController - ===== Executing upload.blockingGet()
11:55:53.154 [RxCachedThreadScheduler-1] INFO  example.UploadController - ===== copied chunk #0, size 289 bytes
11:55:53.156 [RxCachedThreadScheduler-1] INFO  example.UploadController - ===== copied chunk #1, size 7310 bytes
11:55:53.156 [RxCachedThreadScheduler-1] INFO  example.UploadController - ===== copied chunk #2, size 8096 bytes
11:55:53.157 [RxCachedThreadScheduler-1] INFO  example.UploadController - ===== copied chunk #4, size 7134 bytes
11:55:53.157 [RxCachedThreadScheduler-1] INFO  example.UploadController - ===== copied chunk #8, size 8096 bytes
11:55:53.163 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #16, size 8096 bytes
11:55:53.178 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #32, size 8096 bytes
11:55:53.202 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #64, size 8096 bytes
11:55:53.270 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #128, size 8096 bytes
11:55:53.570 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #256, size 8096 bytes
11:55:54.805 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #512, size 126 bytes
11:55:58.376 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #1000, size 8096 bytes
11:56:10.667 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #2000, size 8096 bytes
11:56:31.015 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #3000, size 8096 bytes
11:57:00.552 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #4000, size 8096 bytes
11:57:38.894 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #5000, size 7274 bytes
11:58:27.404 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #6000, size 3674 bytes
11:59:26.541 [nioEventLoopGroup-1-2] INFO  example.UploadController - ===== copied chunk #7000, size 74 bytes

```

This continues until the request times out after 10 minutes.

| Chunks  | Time to process  |
|--:|--:|
| 0-1000  | 5s  |
|  1000-2000 | 12s  |
|  2000-3000 |  20s |
|  3000-4000 | 29s  |
|  4000-5000 |  38s |
|  5000-6000 |  49s |
|  7000-7000 |  59s |

Also note in the output above that request processing starts on an `RxCachedThreadScheduler` thread, but somewhere between chunks 8 and 16 switches to `nioEventLoopGroup-1`.

**Comment by jameskleeh** [comment]
@mmindenhall Which branch are these changes on? I pulled `large-file-upload-disk`, but no changes are there

**Comment by jameskleeh** [comment]
@mmindenhall I got it figured out - thanks for testing this out!
