### ISSUE TITLE
AttributeConverter : Could Not determine recommended JdbcType for Quantity

### ISSUE THREAD

**Issue by haaah** [micronaut-projects/micronaut-core#9944]
### Expected Behavior

Was trying out AttributeConverter example from Micronaut Data Document
[https://micronaut-projects.github.io/micronaut-data/latest/guide/#dbcAttributeConverter](url)

Created a new Testing Project with Micronaut 4.1.3.

Copy and Paste Code from the website to both Quantity.groovy and QuantityAttributeConverter.groovy

Created a new Class with reference to the new data type

>class Car {
>  @Id
>  @GeneratedValue(strategy = GenerationType.IDENTITY)
>  Long id
>
>  String name
>
>  Quantity quantity
>}

Expecting application to runup and run some test.

### Actual Behaviour

The application fail to run up with error

> Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [org.hibernate.boot.SessionFactoryBuilder]

> Caused by: org.hibernate.type.descriptor.java.spi.JdbcTypeRecommendationException: Could not determine recommended JdbcType for `TestMicronautJPA413.test1.bean.Quantity`

### Environment Information

- Mac BigSur
- Azul 17

### Version

4.1.3

**Comment by graemerocher** [comment]
the stack trace indicates you are using Hibernate which has its own API for attribute converters. All the documentation under https://micronaut-projects.github.io/micronaut-data/latest/guide/#dbc does not apply to Hibernate
