### ISSUE TITLE
`@Retryable` doesn't support exponential backoff as suggested by documentation

### ISSUE THREAD

**Issue by stupidfive** [micronaut-projects/micronaut-core#9947]
### Expected Behavior

With
```kotlin
@Retryable(
    delay = "100ms",
    multiplier = "2",
    attempts = "10",
)
```
The retry delays should be exponential:
100ms, 200ms, 400ms, 800ms, 1600ms, 3200ms, 6400ms, 12800ms, 25600ms, 51200ms

### Actual Behaviour

The retry delays are linear:
400ms, 600ms, 800ms, 1000ms, 1200ms, 1400ms, 1600ms, 1800ms, 2000ms, 2200ms

logs
```
23:10:30.853 [default-nioEventLoopGroup-1-2] DEBUG i.m.r.i.DefaultRetryInterceptor - Retrying execution for method [void retryMe()] after delay of 400ms for exception: Try again
23:10:31.259 [default-nioEventLoopGroup-1-2] DEBUG i.m.r.i.DefaultRetryInterceptor - Retrying execution for method [void retryMe()] after delay of 600ms for exception: Try again
23:10:31.865 [default-nioEventLoopGroup-1-2] DEBUG i.m.r.i.DefaultRetryInterceptor - Retrying execution for method [void retryMe()] after delay of 800ms for exception: Try again
23:10:32.669 [default-nioEventLoopGroup-1-2] DEBUG i.m.r.i.DefaultRetryInterceptor - Retrying execution for method [void retryMe()] after delay of 1000ms for exception: Try again
23:10:33.676 [default-nioEventLoopGroup-1-2] DEBUG i.m.r.i.DefaultRetryInterceptor - Retrying execution for method [void retryMe()] after delay of 1200ms for exception: Try again
23:10:34.881 [default-nioEventLoopGroup-1-2] DEBUG i.m.r.i.DefaultRetryInterceptor - Retrying execution for method [void retryMe()] after delay of 1400ms for exception: Try again
23:10:36.283 [default-nioEventLoopGroup-1-2] DEBUG i.m.r.i.DefaultRetryInterceptor - Retrying execution for method [void retryMe()] after delay of 1600ms for exception: Try again
23:10:37.893 [default-nioEventLoopGroup-1-2] DEBUG i.m.r.i.DefaultRetryInterceptor - Retrying execution for method [void retryMe()] after delay of 1800ms for exception: Try again
23:10:39.698 [default-nioEventLoopGroup-1-2] DEBUG i.m.r.i.DefaultRetryInterceptor - Retrying execution for method [void retryMe()] after delay of 2000ms for exception: Try again
23:10:41.701 [default-nioEventLoopGroup-1-2] DEBUG i.m.r.i.DefaultRetryInterceptor - Retrying execution for method [void retryMe()] after delay of 2200ms for exception: Try again
23:10:43.908 [default-nioEventLoopGroup-1-2] DEBUG i.m.r.i.DefaultRetryInterceptor - Cannot retry anymore. Rethrowing original exception for method: void retryMe()
23:10:43.918 [default-nioEventLoopGroup-1-2] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Try again

```

### Steps To Reproduce

1. Create a Micronaut application with retry feature included
2. Enable log for `io.micronaut.retry.intercept` to debug level or lower
3. Add `@Retryable` to a must-fail method, with `multiplier` set to a value other than `1`, such as
```
@Retryable(
    value = [RuntimeException::class],
    delay = "100ms",
    multiplier = "2",
    attempts = "10",
)
open fun retryMe() {
    throw RuntimeException("Try again")
}
```
4. Call the annotated method

### Environment Information

- OS: macOS Ventura 13.4
- JDK: OpenJDK 17.0.2

### Example Application

https://github.com/stupidfive/micronaut-retry-issue-demo

### Version

4.1.3

**Comment by stupidfive** [comment]
The [documentation](https://github.com/micronaut-projects/micronaut-core/blob/aebaec5c5d136ec28bcd67d54f13a1e85676f0d9/src/main/docs/guide/aop/retry.adoc?plain=1#L21) quotes:
> The `multiplier` value of the `@Retryable` annotation can be used to configure a multiplier used to calculate the delay between retries, allowing exponential retry support.

But from the implementation of `SimpleRetry`

https://github.com/micronaut-projects/micronaut-core/blob/aebaec5c5d136ec28bcd67d54f13a1e85676f0d9/retry/src/main/java/io/micronaut/retry/intercept/SimpleRetry.java#L166-L178

it's not hard to infer that the delay values can only be {2*c, 3*c, 4*c, 5*c, ... }, with c being a constant. Which can't be exponential.

The formula should likely be: `delay * multiplier ^ (attemptNumber - 1)`.

**Comment by graemerocher** [comment]
Seems PR worthy, fancy sending one?

**Comment by stupidfive** [comment]
> Seems PR worthy, fancy sending one?

Can do
