### ISSUE TITLE
Missing binaries in 1.0.1 release repo

### ISSUE THREAD

**Issue by luistrigueiros** [micronaut-projects/micronaut-core#996]
:\tools\micronaut.io\study\kapp (master)
λ gradle testClasses
> Task :core:kaptGenerateStubsKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:kaptGenerateStubsKotlin'.
> Could not resolve all files for configuration ':core:compileClasspath'.
   > Could not find io.micronaut:runtime:1.0.1.
     Searched in the following locations:
       - https://jcenter.bintray.com/io/micronaut/runtime/1.0.1/runtime-1.0.1.pom
       - https://jcenter.bintray.com/io/micronaut/runtime/1.0.1/runtime-1.0.1.jar
       - https://dl.google.com/dl/android/maven2/io/micronaut/runtime/1.0.1/runtime-1.0.1.pom
       - https://dl.google.com/dl/android/maven2/io/micronaut/runtime/1.0.1/runtime-1.0.1.jar
       - https://repo.maven.apache.org/maven2/io/micronaut/runtime/1.0.1/runtime-1.0.1.pom
       - https://repo.maven.apache.org/maven2/io/micronaut/runtime/1.0.1/runtime-1.0.1.jar
       - https://dl.bintray.com/micronaut/core-releases-local/io/micronaut/runtime/1.0.1/runtime-1.0.1.pom
       - https://dl.bintray.com/micronaut/core-releases-local/io/micronaut/runtime/1.0.1/runtime-1.0.1.jar
       - https://kotlin.bintray.com/kotlinx/io/micronaut/runtime/1.0.1/runtime-1.0.1.pom
       - https://kotlin.bintray.com/kotlinx/io/micronaut/runtime/1.0.1/runtime-1.0.1.jar
     Required by:
         project :core
   > Could not find io.micronaut:http-client:1.0.1.
     Searched in the following locations:
       - https://jcenter.bintray.com/io/micronaut/http-client/1.0.1/http-client-1.0.1.pom
       - https://jcenter.bintray.com/io/micronaut/http-client/1.0.1/http-client-1.0.1.jar
       - https://dl.google.com/dl/android/maven2/io/micronaut/http-client/1.0.1/http-client-1.0.1.pom
       - https://dl.google.com/dl/android/maven2/io/micronaut/http-client/1.0.1/http-client-1.0.1.jar
       - https://repo.maven.apache.org/maven2/io/micronaut/http-client/1.0.1/http-client-1.0.1.pom
       - https://repo.maven.apache.org/maven2/io/micronaut/http-client/1.0.1/http-client-1.0.1.jar
       - https://dl.bintray.com/micronaut/core-releases-local/io/micronaut/http-client/1.0.1/http-client-1.0.1.pom
       - https://dl.bintray.com/micronaut/core-releases-local/io/micronaut/http-client/1.0.1/http-client-1.0.1.jar
       - https://kotlin.bintray.com/kotlinx/io/micronaut/http-client/1.0.1/http-client-1.0.1.pom
       - https://kotlin.bintray.com/kotlinx/io/micronaut/http-client/1.0.1/http-client-1.0.1.jar
     Required by:
         project :core
   > Could not find com.fasterxml.jackson.datatype:jackson-datatype-jsr310:.
     Required by:
         project :core

**Comment by jameskleeh** [comment]
You are not using the correct artifact names. This was changed in RC3. See https://docs.micronaut.io/latest/guide/index.html#breaks

**Comment by luistrigueiros** [comment]
Thank you.
