### ISSUE TITLE
Allow converting YAML application configuration to property format at build time

### ISSUE THREAD

**Issue by auke-** [micronaut-projects/micronaut-core#9964]
### Feature description

Since Micronaut 4 the default way to define application configuration is the property file format, which allowed removing the YAML dependencies from Micronaut projects. It is however easier to define the configuration in the YAML format.

It would be nice if Micronaut allowed defining application configuration in YAML and automatically convert it to the property file when building/packaging the application (e.g. using the Micronaut AOT plugin). This wouldn't support loading YAML at runtime but makes defining the application configuration easier (the generated YAML could include a comment describing this limitation).

One aspect to consider is whether or not this should be enabled by default. In my opinion this would improve the developer experience when creating new projects.

**Comment by kevind-wgu** [comment]
If you import snakeyaml into your pom then it will load application.yml automatically.

**Comment by auke-** [comment]
> If you import snakeyaml into your pom then it will load application.yml automatically.

I know. As of Micronaut 4 snakeyaml isn't added by default, I suppose in order to make the resulting application a bit leaner. For developer experience it would be nice to support yaml at build time without having the runtime dependency on snakeyaml

**Comment by graemerocher** [comment]
this is actually possible already with Micronaut AOT. See https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/#_micronaut_aot_plugin and `convertYamlToJava = true`

**Comment by auke-** [comment]
You guys keep surprising me and keep over delivering :)

I've create https://github.com/micronaut-projects/micronaut-starter/issues/2131 as a proposal to make the instructions a bit more clear.
