### ISSUE TITLE
Support for different methods of Versioning APIs

### ISSUE THREAD

**Issue by in28minutes** [micronaut-projects/micronaut-core#997]
There are a number of situations where we would need to version APIs. I was unable to find support for 3 versioning options in Micronaut.

**Request Parameter versioning**
- http://localhost:8080/person/param?version=1
- http://localhost:8080/person/param?version=2

Implementations in Spring Boot is Shown below
```
  @GetMapping(value = "/student/param", params = "version=1")
  public StudentV1 paramV1() {
    return new StudentV1("Bob Charlie");
  }

  @GetMapping(value = "/student/param", params = "version=2")
  public StudentV2 paramV2() {
    return new StudentV2(new Name("Bob", "Charlie"));
  }

```

**(Custom) Headers versioning**

Use a Request Header to differentiate the versions.

**Examples**

Sent GET to http://localhost:8080/person/header using a header
headers=[X-API-VERSION=1]

Sent GET to http://localhost:8080/person/header using a header
headers=[X-API-VERSION=2]

Spring Boot Implementations are shown below:

```
  @GetMapping(value = "/student/header", headers = "X-API-VERSION=1")
  public StudentV1 headerV1() {
    return new StudentV1("Bob Charlie");
  }

  @GetMapping(value = "/student/header", headers = "X-API-VERSION=2")
  public StudentV2 headerV2() {
    return new StudentV2(new Name("Bob", "Charlie"));
  }

```

**Media type versioning (a.k.a “content negotiation” or “accept header”)**

The last versioning approach is to use the Accept Header in the request.

Sending GET to http://localhost:8080/person/produces using this header
Accept=application/vnd.company.app-v1+json
Sending GET to http://localhost:8080/person/produces using this header
Accept=application/vnd.company.app-v2+json

Corresponding code in Spring Boot is below

```
  @GetMapping(value = "/student/produces", produces = "application/vnd.company.app-v1+json")
  public StudentV1 producesV1() {
    return new StudentV1("Bob Charlie");
  }

  @GetMapping(value = "/student/produces", produces = "application/vnd.company.app-v2+json")
  public StudentV2 producesV2() {
    return new StudentV2(new Name("Bob", "Charlie"));
  }

```

**Comment by BogdanOros** [comment]
Currently, the `executableMethod` for Route is chosen only via the uri match.
For version we will face the route duplication problem:
` if (uriRoutes.size() > 1) {
            throw new DuplicateRouteException(requestPath, uriRoutes);
`
But should Micronaut be generic in route choosing behaviour?
1) Micronaut should include for route matching also request params / headers / producing value?
2) `@Version` annotation for this specific case?
    - `@Version(header="X-API-VERSION, value = "1")`
    - `@Version(param="version", value="1")`
    - `@Version(produces="application/vdn.company.app-v1+json")`

I'll be glad to help with implementation via PR

**Comment by graemerocher** [comment]
PRs welcome. Thanks

**Comment by BogdanOros** [comment]
Okay, will start on it as soon as possible.
So which of my proposals (Spring behavior VS dedicated `@Version` annotation) is more intuitive?
The `@Version` maybe is more apparent for developers?

**Comment by markjfisher** [comment]
+1 for @Version

**Comment by in28minutes** [comment]
+1 for @Version. Describes Intent more clearly.

**Comment by jameskleeh** [comment]
@BogdanOros The micronaut side really shouldn't support any specific solution imo. You can define the contract for retrieving a version from the request and inject a collection of those beans. Then loop through those beans until one produces a version for you to compare with. 

That way Micronaut will continue to perform as well as is does today for those who aren't using versioning and for those that do, they simply need to register a bean that returns the version using whatever strategy they wish. They can register multiple beans if they want to support multiple strategies.

**Comment by BogdanOros** [comment]
@jameskleeh, it seems reasonable, I will refactor my existing solution to remove extra configurations in the `@Version` annotation and move the resolving to a configurable set of beans. 
It will not break the existing behavior .

**Comment by graemerocher** [comment]
@BogdanOros yes those seem like good ideas

**Comment by in28minutes** [comment]
Was this fixed or closed?

**Comment by in28minutes** [comment]
Cool. Thanks.

**Comment by dekstroza** [comment]
I have tried this, but keep getting error in the test:
```
io.micronaut.http.client.exceptions.HttpClientResponseException: More than 1 route matched the incoming request. The following routes matched /greeter/hello: GET - /greeter/hello, GET - /greeter/hello
```
Same happens when tested with curl.
1.1.0.M2 version
java 11

**Comment by BogdanOros** [comment]
The configuration in the documentation is a bit inconsistent.
```
micronaut:
    router:
        versioning:
            enabled: true
            header:
                enabled: true
                names:
                    - 'X-API-VERSION'
                    - 'Accept-Version'
    application:
        name: demo-app
```
Versioning should be enabled in `application.yml`
```
micronaut:
    router:
        versioning:
            enabled: true
```
or `application.properties`
```
micronaut.router.versioning.enabled=true
```

**Comment by dekstroza** [comment]
@BogdanOros That was it. Thanks for the help. Sent pull request with the update.

**Comment by raderio** [comment]
Does it also supports version in URL?

Example `api.corp.com/v1/products`

**Comment by jameskleeh** [comment]
@raderio You can write your own resolver to pull the version from the URL

**Comment by hotzen** [comment]
> @raderio You can write your own resolver to pull the version from the URL

@jameskleeh you *have* to bind the actual version-specific controller to the actual api-specific uri/route `/v1/products`, isn't it? so any additional version-resolver is just pointless in this case, or am i missing something?

**Comment by jameskleeh** [comment]
@hotzen The route could be `/{version}/products` and then the method could do what it wants to do based on the version, but you could do that without this specific version support. The `@Version` annotation for that use case wouldn't make much sense you're right.

**Comment by hittlle** [comment]
How can I integrate this feature with swagger/openapi if I use the header-based approach for versioning? I assume that I can see only one endpoint there in swagger UI? how to group different version of API endpoints like we do with SprintBoot GroupedOpenApi? thanks.

**Comment by ernamonta** [comment]
> How can I integrate this feature with swagger/openapi if I use the header-based approach for versioning? I assume that I can see only one endpoint there in swagger UI? how to group different version of API endpoints like we do with SprintBoot GroupedOpenApi? thanks.

Did you happen to find a solution to this? I also need to figure it this out...

**Comment by sdelamo** [comment]
I don't think versioning via headers is the best approach to using OpenAPI. Micronaut OpenAPI supports [`@OpenApiGroup`](https://micronaut-projects.github.io/micronaut-openapi/6.5.1/guide/#openapigroup)
