### ISSUE TITLE
Document how to load a file from resources in memory

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-core#9979]
### Issue description

> For example, last week, it took me a while to figure out how to read a file from the resources, that I needed to load somehow in memory.
> And I felt the documentation was lacking a bit in this area.

**Comment by sdelamo** [comment]
@glaforge did you use the [ResourceLoader](https://github.com/micronaut-projects/micronaut-core/blob/4.2.x/core/src/main/java/io/micronaut/core/io/ResourceLoader.java) API?

**Comment by glaforge** [comment]
I ended up doing something like the following:

```java
        Optional<URL> resource = new ResourceResolver().getResource("classpath:saved-embedding-store.json");
        Readable savedEmbeddingStore = Readable.of(resource.get());

        String storeJson = "{}";
        try {
            storeJson = IOUtils.readText(new BufferedReader(savedEmbeddingStore.asReader()));
        } catch (IOException ioe) { // ...
        }
```
