### ISSUE TITLE
regression: support merge-patch+json

### ISSUE THREAD

**Issue by stefanos-kalantzis** [micronaut-projects/micronaut-core#9991]
### Expected Behavior

- After migration to Micronaut v4, `merge-patch+json` is no longer recognized as JSON.
- Ideally, all "sub" json content types should be recognized as JSON.
- This issue is similar to https://github.com/micronaut-projects/micronaut-core/pull/9951
- Workaround exists:
   ```
   micronaut:
     codec:
       json:
         additional-types:
           - application/merge-patch+json
   ```

### Actual Behaviour

Controller patch method definition:
```
    @Patch(value = "/", consumes = "application/merge-patch+json")
    public SomeResponseDto update(@Body SomeRequestDto dto) {
        return service.patch(dto);
    }
```

Throws error: `Required Body [dto] not specified`

### Steps To Reproduce

call HTTP endpoint with header `Content-Type: application/merge-patch+json`

### Environment Information

```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Java version: 17.0.4.1, vendor: IBM Corporation, runtime: /home/stefanos/.sdkman/candidates/java/17.0.4.1-sem
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.5.6-200.fc38.x86_64", arch: "amd64", family: "unix"
```

### Version

4.x

**Comment by altro3** [comment]
@sdelamo Could you close it, please. it's already fixed
