### ISSUE TITLE
OPTIONS method not allowed after enable cors

### ISSUE THREAD

**Issue by stanleyw2014** [micronaut-projects/micronaut-core#9992]
### Expected Behavior

should return 200 ok

### Actual Behaviour

curl --location 'http://localhost:8080/foo/123' --request OPTIONS,
it returned:
{"_links":{"self":[{"href":"/foo/123","templated":false}]},"_embedded":{"errors":[{"message":"Method [OPTIONS] not allowed for URI [/foo/123]. Allowed methods: [HEAD, GET]"}]},"message":"Method Not Allowed"}%

### Steps To Reproduce

I have my project configured with cors enabled:
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.web.allowed-methods[0]=POST
micronaut.server.cors.configurations.web.allowed-methods[1]=PUT
micronaut.server.cors.configurations.web.allowed-methods[2]=GET
micronaut.server.cors.configurations.web.allowed-methods[3]=OPTIONS
and has a REST api defined:
  @Get(value = "/foo/{id}", produces =  MediaType.APPLICATION_JSON)
  public String getSomething(@PathVariable String id)  {
    return "ok"
  }

and I send request like :
curl --location 'http://localhost:8080/foo/123' --request OPTIONS,
it returned:
{"_links":{"self":[{"href":"/foo/123","templated":false}]},"_embedded":{"errors":[{"message":"Method [OPTIONS] not allowed for URI [/foo/123]. Allowed methods: [HEAD, GET]"}]},"message":"Method Not Allowed"}%

### Version

4.1.1

**Comment by graemerocher** [comment]
@dstepanov can you take a look

**Comment by sdelamo** [comment]
I talked to @dstepanov I am going to check this.

**Comment by sdelamo** [comment]
@stanleyw2014 if you are trying to emulate a CORS preflight request your Options request should include an `Origin` HTTP Header.

**Comment by stanleyw2014** [comment]
tried with curl --location 'http://localhost:8080/foo/123' --header 'Origin: http://localhost:8000' --request OPTIONS, still the same error.

{"_links":{"self":[{"href":"/foo/123","templated":false}]},"_embedded":{"errors":[{"message":"Method [OPTIONS] not allowed for URI [/foo/123]. Allowed methods: [HEAD, GET]"}]},"message":"Method Not Allowed"}%

**Comment by sdelamo** [comment]
I created a PR to dispatch OPTION  requests unrelated to CORS preflight requests: https://github.com/micronaut-projects/micronaut-core/pull/10011

@stanleyw2014  can we close this issue?

**Comment by jub0bs** [comment]
@stanleyw2014 

Be aware that preflight requests systematically contain an `Access-Control-Request-Method` header. If an `OPTIONS` request lacks that header, the CORS middleware (correctly) [will not](https://github.com/micronaut-projects/micronaut-core/blob/9a26d7413ac0d9f7045bd8657396be695b2673c6/http-server/src/main/java/io/micronaut/http/server/cors/CorsUtil.java#L38) categorise that request as a preflight request. Try again with

```shell
curl --location 'http://localhost:8080/foo/123' \
  --request OPTIONS \
  --header 'Origin: http://localhost:8000' \
  --header 'Access-Control-Request-Method: GET'
```

Note also that listing `OPTIONS` as an allowed method in your CORS configuration may not have the effect you expect. It simply allows client to explicitly use that method in their _actual_ requests, e.g.

```javascript
fetch('http://localhost:8080/foo/123', {method: 'OPTIONS'})
```

but it's not necessary (in general) for preflight to succeed.

**Comment by sdelamo** [comment]
See `CorsUtil` which encapsulates our check for CORS preflight: 

https://github.com/micronaut-projects/micronaut-core/blob/4.2.x/http-server/src/main/java/io/micronaut/http/server/cors/CorsUtil.java#L41

**Comment by sdelamo** [comment]
I am going to go ahead and close the issue @stanleyw2014 Let me know if you think there is still an issue.

**Comment by karthik-thotamgari** [comment]
Hey @sdelamo,
I've added the header `Access-Control-Request-Method: GET` to my request, but the server still returns a 405 error. The solution works locally, but in my dev environment it fails. Here are the details:
- **Micronaut version:** 4.9.0
- **Current CORS configuration (application.yml):**
``` 
 micronaut:
    server:
      cors:
        enabled: true
        configurations:
          ui:
            allowed-origins: 
                - 'https://app.company.com'
```
Are there any additional configuration changes required to support the OPTIONS preflight request?

**Comment by karthik-thotamgari** [comment]
tried this [solution](https://github.com/micronaut-projects/micronaut-aws/issues/271#issuecomment-627378486) as well. but the result remained same works locally but not in dev.
