### ISSUE TITLE
Missing equals/hashCode in HttpVersionSelection class generates a memory leak

### ISSUE THREAD

**Issue by jpbempel** [micronaut-projects/micronaut-core#9994]
### Expected Behavior

no memory leak

### Actual Behaviour

`io.micronaut.http.client.netty.DefaultHttpClient` instances are leaking and are retained in `unbalancedClients` map in `io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry`

<img width="1280" alt="Screenshot 2023-10-17 at 15 13 36" src="https://github.com/micronaut-projects/micronaut-core/assets/4610701/018b78c9-118e-4a27-b4f8-d5f8d5bc78f5">

### Steps To Reproduce

In our application we have defined a http client like this:

```
@Client(
    id = "rc-api",
    path = "/api/unstable/remote_config/products/product1",
    alpnModes = [HttpVersionSelection.ALPN_HTTP_1],
)
interface RcApiClient {
}
```
We have noticed after a certain time, that the Java Heap was filling up to the maximum.
By analysis of the heap dump we noticed a large amount of `DefaultHttpClient` instances stored into the unbalancedClients map in `DefaultNettyHttpClientRegistry`.

Insertion into the map is done by [this](https://github.com/micronaut-projects/micronaut-core/blob/426e891f3258ddadaa513c78ec10df2c9bfa1a2c/http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java#L328):
```
private DefaultHttpClient getClient(ClientKey key, BeanContext beanContext, AnnotationMetadata annotationMetadata) {
        return unbalancedClients.computeIfAbsent(key, clientKey -> {
```
and the key of this `unbalancedClients` map is `io.micronaut.http.client.netty.DefaultNettyHttpClientRegistry.ClientKey`

[ClientKey](https://github.com/micronaut-projects/micronaut-core/blob/426e891f3258ddadaa513c78ec10df2c9bfa1a2c/http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java#L561) class is made from the following fields:
```
        final HttpVersionSelection httpVersion;
        final String clientId;
        final List<String> filterAnnotations;
        final String path;
        final Class<?> configurationClass;
        final JsonFeatures jsonFeatures;
```

and [`equals` and `hashCode`](https://github.com/micronaut-projects/micronaut-core/blob/426e891f3258ddadaa513c78ec10df2c9bfa1a2c/http-client/src/main/java/io/micronaut/http/client/netty/DefaultNettyHttpClientRegistry.java#L585):
```
       @Override
        public boolean equals(Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            ClientKey clientKey = (ClientKey) o;
            return httpVersion == clientKey.httpVersion &&
                    Objects.equals(clientId, clientKey.clientId) &&
                    Objects.equals(filterAnnotations, clientKey.filterAnnotations) &&
                    Objects.equals(path, clientKey.path) &&
                    Objects.equals(configurationClass, clientKey.configurationClass) &&
                    Objects.equals(jsonFeatures, clientKey.jsonFeatures);
        }

        @Override
        public int hashCode() {
            return Objects.hash(httpVersion, clientId, filterAnnotations, path, configurationClass, jsonFeatures);
        }
```

The problem is that `httpVersion` field when not null is using the type [`io.micronaut.http.client.HttpVersionSelection`](https://github.com/micronaut-projects/micronaut-core/blob/426e891f3258ddadaa513c78ec10df2c9bfa1a2c/http-client-core/src/main/java/io/micronaut/http/client/HttpVersionSelection.java#L34) that does not provide any `equals` and `hashCode` methods.
So in the case of the ClientKey::hashCode it means that we are using an identityHashCode and using @Client annotation with `alpn` will create a new instance of `HttpVersionSelection` (through `DefaultNettyHttpClientRegistry#getClientKey` -> `HttpVersionSelection#forClientAnnotation`.
Then every http client have a different hashCode that will spread across the `unbalancedClients` map.
Moreover the `ClientKey::equals` use reference equality (`==`) for the `httpVersion` field which will be always false.

It ends up creating a new http client for every request and stored into the map.

### Version

4.1.5

**Comment by yawkat** [comment]
thanks for the report and figuring out the cause.
